### ISSUE TITLE
NTR: ADP-ribosyltransferase terms

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#22874]
Hi GO,

I would need a bunch of terms for protein ADP-ribosylation. These terms are required for consistence in GO and with Rhea. And I would also need a term for a protein that defines specificity of ADP-ribosylation.

Thanks

Sylvain

- [x]  1) I would first need a slight update for the GO:1990404 term. It would be more consistent to name it ADP-ribosyltransferase

FROM:
GO:1990404 protein ADP-ribosylase activity IDA
TO:
GO:1990404 protein ADP-ribosyltransferase activity IDA

1b) Please note that GO:0106274 NAD+-protein-arginine ADP-ribosyltransferase activity IDA should be a child of GO:1990404

- [x] 2) The first term is for a protein that defines specificity of ADP-ribosylation
Proposed term:
Name: protein ADP-ribosyltransferase-substrate adaptor activity
Definition: The binding activity of a molecule that brings together a ADP-ribosyltransferase and its substrate and confers specificity to the ADP-ribosylase.
child of GO:0030674 protein-macromolecule adaptor activity
child of GO:0006471 protein ADP-ribosylation
PMID:32028527

Other terms are for the different reaction for ADP-ribosylatransferase activities (this would be consistent with GO:0106274 that is specific for arginine)

- [ ] 3) Name:  protein-C-terminal glycine ADP-ribosyltransferase activity 
Definition: Catalysis of the reaction: [protein]-C-terminal glycine + NAD(+) = [protein]-C-terminal O-(ADP-D-ribosyl)-glycine + nicotinamide
Child of GO:1990404 protein ADP-ribosyltransferase activity
PMID:28525742
RHEA:58268

- [ ] 4) Name:  protein-cysteine ADP-ribosyltransferase activity 
Definition: Catalysis of the reaction: L-cysteinyl-[protein] + NAD(+) = H(+) + nicotinamide + S-(ADP-D-ribosyl)-L-cysteinyl-[protein] 
Child of GO:1990404 protein ADP-ribosyltransferase activity
Child of GO:0018123 peptidyl-cysteine ADP-ribosylation
PMID:25043379
RHEA:56612

- [ ] 5) Name:  protein-lysine ADP-ribosyltransferase activity 
Definition: Catalysis of the reaction: L-lysyl-[protein] + NAD(+) = H(+) + N(6)-(ADP-D-ribosyl)-L-lysyl-[protein] + nicotinamide 
Child of GO:1990404 protein ADP-ribosyltransferase activity
PMID:25043379
RHEA:58220

- [ ] 6) Name:  protein-serine ADP-ribosyltransferase activity 
Definition: Catalysis of the reaction: L-seryl-[protein] + NAD(+) = H(+) + nicotinamide + O-(ADP-D-ribosyl)-L-seryl-[protein] 
Child of GO:1990404 protein ADP-ribosyltransferase activity
Child of GO:0018312 peptidyl-serine ADP-ribosylation
PMID:32028527, PMID:33186521
RHEA:58232

- [ ] 7) Name:  protein-aspartate ADP-ribosyltransferase activity 
Definition: Catalysis of the reaction: L-aspartyl-[protein] + NAD(+) = 4-O-(ADP-D-ribosyl)-L-aspartyl-[protein] + nicotinamide
Child of GO:1990404 protein ADP-ribosyltransferase activity
PMID:19764761, PMID:25043379
RHEA:54424

- [ ] 8) Name:  protein-glutamate ADP-ribosyltransferase activity 
Definition: Catalysis of the reaction: L-glutamyl-[protein] + NAD(+) = 5-O-(ADP-D-ribosyl)-L-glutamyl-[protein] + nicotinamide
Child of GO:1990404 protein ADP-ribosyltransferase activity
PMID:19764761, PMID:25043379
RHEA:58224

- [ ] 9) Name:  protein-tyrosine ADP-ribosyltransferase activity 
Definition: Catalysis of the reaction: L-tyrosyl-[protein] + NAD(+) = H(+) + nicotinamide + O-(ADP-D-ribosyl)-L-tyrosyl-[protein]
Child of GO:1990404 protein ADP-ribosyltransferase activity
PMID:29954836, PMID:30257210
RHEA:58236

**Comment by ValWood** [comment]
Hi Sylvain, 
I realised that I have not used GO:1990404 to annotate ribosylation factors, they are instead annotated to GTPase. Since they are often described as GTPases, what is the relationship between  ADP-ribosyltransferase and GTPases if any?

**Comment by pgaudet** [comment]
Hi @sylvainpoux 

Is there a RHEA for GO:1990404 protein ADP-ribosyltransferase activity and for GO:0106274 NAD+-protein-arginine ADP-ribosyltransferase activity? 

Thanks, Pascale

**Comment by pgaudet** [comment]
What about NAD/NAPD: we have the 3 terms in GO
* GO:0003956 NAD(P)+-protein-arginine ADP-ribosyltransferase activity
* GO:0106274 NAD+-protein-arginine ADP-ribosyltransferase activity = RHEA:19149
* GO:0106275 NADP+-protein-arginine ADP-ribosyltransferase activity = RHEA:54884

However: 
1. All annotations are to RHEA:19149
2. The papers cited in RHEA:54884 all talk about the NAD (RHEA:19149) activity. 

Should these be merged? This may be a question for @kaxelsen 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi Pascale,

I suppose @kaxelsen will have more information about this, but I suspect NADP-dependant activity was created because it was defined in the initial definition of the EC number. 

However both MetaCyc and KEGG only report the reaction with NAD
Does the NADP reaction exist? This is a good question
Sylvain

**Comment by kaxelsen** [comment]
The abstract for pmid:225315 reads: The enzyme used both NAD and NADP as ADP-ribose donors; Km values for the two were similar (30 uM), although the Vmax for NAD was considerably higher than that for NADP.

So the reaction does exist, or else we would not have created it. We do not use comments of EC entries as the only evidence, but they are a good lead for interesting things to check.

**Comment by sylvainpoux** [comment]
Many thanks Kristian!
So the reaction exists, just that no enzyme has been defined yet.
Can you confirm that we should not merge them?
Sylvain

**Comment by kaxelsen** [comment]
As the reaction with NADP exists we cannot merge it with the reaction using NAD.

**Comment by pgaudet** [comment]
Thanks both!

**Comment by pgaudet** [comment]
- [ ] GO:1990404 protein ADP-ribosyltransferase activity: changed label to NAD+-protein ADP-ribosyltransferase activity (consistent with definition, The transfer, from NAD, of ADP-ribose to a protein amino acid residue.)

**Comment by pgaudet** [comment]
- [ ] Merge     GO:0003956 NAD(P)+-protein-arginine ADP-ribosyltransferase activity and   GO:0106275 NADP+-protein-arginine ADP-ribosyltransferase activity 
into     GO:0106274 NAD+-protein-arginine ADP-ribosyltransferase activity = RHEA:19149 (consistent with EC and with annotations; there is not enough physiological evidence that the NADP version of the enzyme exists to keep the term.

**Comment by pgaudet** [comment]
@sylvainpoux Here you go: 

Last login: Wed Apr 27 11:46:21 on console
➜  ~ git:(master) ✗ cd repos/go-ontology 
➜  go-ontology git:(master) ✗ cd src/ontology 
➜  ontology git:(master) ✗ git pul 
git: 'pul' is not a git command. See 'git --help'.

The most similar commands are
	pull
	spull
➜  ontology git:(master) ✗ git pull 
Already up to date.
➜  ontology git:(master) ✗ git checkout -b issue-22482-11
Switched to a new branch 'issue-22482-11'
➜  ontology git:(issue-22482-11) ✗ git diff 
➜  ontology git:(issue-22482-11) ✗ git commit -m 'fixed generic mf subset fixes #22482' go-edit.obo
[issue-22482-11 bfebc598] fixed generic mf subset fixes #22482
 1 file changed, 4 insertions(+)
➜  ontology git:(issue-22482-11) ✗ git push origin issue-22482-11
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.34 KiB | 685.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: 
remote: Create a pull request for 'issue-22482-11' on GitHub by visiting:
remote:      https://github.com/geneontology/go-ontology/pull/new/issue-22482-1
remote: 
To https://github.com/geneontology/go-ontology.git
 * [new branch]        issue-22482-11 -> issue-22482-11
➜  ontology git:(issue-22482-11) ✗ git checkout master 
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git pull 
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/geneontology/go-ontology
   96a5d195..ff9eb001  master     -> origin/master
Updating 96a5d195..ff9eb001
Fast-forward
 src/ontology/go-edit.obo | 4 ++++
 1 file changed, 4 insertions(+)
➜  ontology git:(master) ✗ git branch -d issue-22482-11
Deleted branch issue-22482-11 (was bfebc598).
➜  ontology git:(master) ✗ git pull                    
Already up to date.
➜  ontology git:(master) ✗ git checkout -b issue-23023
Switched to a new branch 'issue-23023'
➜  ontology git:(issue-23023) ✗ git diff 
➜  ontology git:(issue-23023) ✗ git diff 
➜  ontology git:(issue-23023) ✗ git diff 
➜  ontology git:(issue-23023) ✗ git diff 
➜  ontology git:(issue-23023) ✗ git commit -m 'added prok subset as one GO subset for #23023' go-edit.obo
[issue-23023 26bf21d9] added prok subset as one GO subset for #23023
 1 file changed, 1 insertion(+)
➜  ontology git:(issue-23023) ✗ git push origin issue-23023
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.30 KiB | 444.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: 
remote: Create a pull request for 'issue-23023' on GitHub by visiting:
remote:      https://github.com/geneontology/go-ontology/pull/new/issue-23023
remote: 
To https://github.com/geneontology/go-ontology.git
 * [new branch]        issue-23023 -> issue-23023
➜  ontology git:(issue-23023) ✗ git diff 
➜  ontology git:(issue-23023) ✗ git diff 
➜  ontology git:(issue-23023) ✗ git commit -m 'added prok subset terms fixes  #23023' go-edit.obo
[issue-23023 2feebb6b] added prok subset terms fixes  #23023
 1 file changed, 67 insertions(+), 1 deletion(-)
➜  ontology git:(issue-23023) ✗ git diff 
➜  ontology git:(issue-23023) ✗ git commit -m 'added prok subset terms fixes  #23023' go-edit.obo
[issue-23023 ba21af85] added prok subset terms fixes  #23023
 1 file changed, 35 insertions(+), 1 deletion(-)
➜  ontology git:(issue-23023) ✗ git push origin issue-23023
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 8 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (10/10), 5.50 KiB | 1.83 MiB/s, done.
Total 10 (delta 8), reused 0 (delta 0)
remote: Resolving deltas: 100% (8/8), completed with 4 local objects.
To https://github.com/geneontology/go-ontology.git
   26bf21d9..ba21af85  issue-23023 -> issue-23023
➜  ontology git:(issue-23023) ✗ git diff 
➜  ontology git:(issue-23023) ✗ git commit -m 'added prok subset terms fixes  #23023' go-edit.obo
[issue-23023 07a62210] added prok subset terms fixes  #23023
 1 file changed, 100 insertions(+), 100 deletions(-)
➜  ontology git:(issue-23023) ✗ git push origin issue-23023
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 3.02 KiB | 1.01 MiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/geneontology/go-ontology.git
   ba21af85..07a62210  issue-23023 -> issue-23023
➜  ontology git:(issue-23023) ✗ git checkout master 
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git pull 
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/geneontology/go-ontology
   ff9eb001..6f04f1f5  master     -> origin/master
Updating ff9eb001..6f04f1f5
Fast-forward
 src/ontology/go-edit.obo | 1 +
 1 file changed, 1 insertion(+)
➜  ontology git:(master) ✗ git pull 
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/geneontology/go-ontology
   6f04f1f5..9bc9606e  master     -> origin/master
Updating 6f04f1f5..9bc9606e
Fast-forward
 src/ontology/go-edit.obo | 102 ++++++++++++++++++++++++++++++++++++++++++++++-
 1 file changed, 101 insertions(+), 1 deletion(-)
➜  ontology git:(master) ✗ git branch -d issue-23023
Deleted branch issue-23023 (was 07a62210).
➜  ontology git:(master) ✗ git pull
Already up to date.
➜  ontology git:(master) ✗ git pull
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 30 (delta 20), reused 21 (delta 13), pack-reused 2
Unpacking objects: 100% (30/30), done.
From https://github.com/geneontology/go-ontology
   9bc9606e..e0809d3b  master       -> origin/master
 * [new branch]        issue-19463  -> origin/issue-19463
 * [new branch]        issue-19463b -> origin/issue-19463b
 * [new branch]        issue-23234  -> origin/issue-23234
 * [new branch]        issue-23239  -> origin/issue-23239
 * [new branch]        issue-23239b -> origin/issue-23239b
Updating 9bc9606e..e0809d3b
Fast-forward
 src/ontology/go-edit.obo | 29 ++++++++++++++++++++---------
 1 file changed, 20 insertions(+), 9 deletions(-)
➜  ontology git:(master) ✗ git checkout -b issue-23242
Switched to a new branch 'issue-23242'
➜  ontology git:(issue-23242) ✗ git diff 
➜  ontology git:(issue-23242) ✗ git diff 
➜  ontology git:(issue-23242) ✗ git diff 
➜  ontology git:(issue-23242) ✗ git commit -m 'fixed subclass, definition fixes #23242' go-edit.obo
[issue-23242 499082e3] fixed subclass, definition fixes #23242
 1 file changed, 2 insertions(+), 2 deletions(-)
➜  ontology git:(issue-23242) ✗ git push origin issue-23242
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.38 KiB | 470.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: 
remote: Create a pull request for 'issue-23242' on GitHub by visiting:
remote:      https://github.com/geneontology/go-ontology/pull/new/issue-23242
remote: 
To https://github.com/geneontology/go-ontology.git
 * [new branch]        issue-23242 -> issue-23242
➜  ontology git:(issue-23242) ✗ git diff 
➜  ontology git:(issue-23242) ✗ git commit -m 'fixed subclass, definition fixes #23242' go-edit.obo
[issue-23242 c1442757] fixed subclass, definition fixes #23242
 1 file changed, 1 insertion(+), 1 deletion(-)
➜  ontology git:(issue-23242) ✗ git push origin issue-23242
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.28 KiB | 435.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/geneontology/go-ontology.git
   499082e3..c1442757  issue-23242 -> issue-23242
➜  ontology git:(issue-23242) ✗ git checkout master 
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git pull 
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/geneontology/go-ontology
   e0809d3b..ffceba30  master     -> origin/master
Updating e0809d3b..ffceba30
Fast-forward
 src/ontology/go-edit.obo | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
➜  ontology git:(master) ✗ git branch -d issue-23242
Deleted branch issue-23242 (was c1442757).
➜  ontology git:(master) ✗ git checkout -b issue-22874-2
Switched to a new branch 'issue-22874-2'
➜  ontology git:(issue-22874-2) ✗ git diff 

RI
+created_by: pg
+creation_date: 2022-05-02T06:46:35Z
+
+[Term]
+id: GO:0140806
+name: NAD+- protein-aspartate ADP-ribosyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-aspartyl-[protein] + NAD(+) = 4-O-(ADP-D-ribosyl)-L-aspartyl-[protein] + nicotinamide." [PMID:19764761, PMID:25043379, RHEA:54424]
+is_a: GO:1990404 ! NAD+-protein ADP-ribosyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22874 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-02T06:46:47Z
+
+[Term]
+id: GO:0140807
+name: NAD+-protein-glutamate ADP-ribosyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-glutamyl-[protein] + NAD(+) = 5-O-(ADP-D-ribosyl)-L-glutamyl-[protein] + nicotinamide." [PMID:19764761, PMID:25043379, RHEA:58224]
+is_a: GO:1990404 ! NAD+-protein ADP-ribosyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22874 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-02T06:47:00Z
+
+[Term]
+id: GO:0140808
+name: NAD+-protein-tyrosine ADP-ribosyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-tyrosyl-[protein] + NAD(+) = H(+) + nicotinamide + O-(ADP-D-ribosyl)-L-tyrosyl-[protein]." [PMID:29954836, PMID:30257210, RHEA:58236]
+xref: RHEA:58236
+is_a: GO:1990404 ! NAD+-protein ADP-ribosyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22874 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-02T06:47:12Z

**Comment by sylvainpoux** [comment]
Thank you Pascale! I will curate the different activities of PARP enzymes in GO (and make a bunch of GO-CAM models).
Sylvain

**Comment by pgaudet** [comment]
Thanks! Note that I did not create links to the BPs as some of them will be obsoleted. 

I think we should obsolete: 

* GO:0018120 peptidyl-arginine ADP-ribosylation
* GO:0018122 peptidyl-asparagine ADP-ribosylation
* GO:0018123 peptidyl-cysteine ADP-ribosylation
* GO:0018424 peptidyl-glutamic acid poly-ADP-ribosylation
* GO:0018312 peptidyl-serine ADP-ribosylation

and ask people to reannotate to the MFs we just created. 

I am not sure what to do about 
* GO:0006471 protein ADP-ribosylation
* GO:0070213 protein auto-ADP-ribosylation
* GO:0140289 protein mono-ADP-ribosylation
* GO:0070212 protein poly-ADP-ribosylation
Should these also be obsoleted? is there a better BP these can be moved to? 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi Pascale,
it makes sense to obsolete the terms related to amino acid specificity as you propose.

Regarding the second list, at least 2 terms are still important: 
GO:0140289 protein mono-ADP-ribosylation
GO:0070212 protein poly-ADP-ribosylation

As some PARP enzymes mediate mono-ADP ribosylation and some Poly-ADP-ribosylation and that this specificity is not related to the catalytic activity, I would propose to keep them for the moment

Thanks

Sylvain

**Comment by ValWood** [comment]
Hi @sylvainpoux @pgaudet  

>As some PARP enzymes mediate mono-ADP ribosylation and some Poly-ADP-ribosylation and that this specificity is not related to the catalytic activity

should this still not be  modelled as a more specific MF than as a BP? 
In GO terms these aren't the biological processes, which are usually related to membrane organization or vesicle-mediated transport.

**Comment by sylvainpoux** [comment]
Hi @ValWood

Good point. I looked more in detail and in fact we already have a GO term for Poly-ADP-ribosylation (GO:0003950), which descibes the elongation step from mono-ADP-ribosylation. It corresponds to EC 2.4.2.30 

Then I'm not sure we should create a specific term for mono-ADP-ribosylation

Sylvain

**Comment by sjm41** [comment]
Hi @sylvainpoux @pgaudet 

I was just using some of the terms above, and got confused about the difference/relationship between these two:
- NAD+-protein ADP-ribosyltransferase activity (GO:1990404)
- NAD+ ADP-ribosyltransferase activity (GO:0003950) (=EC:2.4.2.30)

From the descriptions in this ticket, I think it would be much clearer to specify the 'mono-ADP-ribosylation' vs 'poly-ADP-ribosylation' in the term names and definitions. Also, I think GO:0003950 acts on proteins (and that's what the EC:2.4.2.30 comment also says). So the two names would become:
- NAD+-protein mono-ADP-ribosyltransferase activity (GO:1990404)
- NAD+-protein poly-ADP-ribosyltransferase activity (GO:0003950) (=EC:2.4.2.30)
(Would also need to add 'is_a: GO:0140096 ! catalytic activity, acting on a protein' parent to GO:0003950)

Lastly, there's some inconsistency in the presence/absence of a space character after the 'NAD+-" bit in the term names of the child terms that it would be good to fix:

```
pentosyltransferase activity (GO:0016763)
    |_NAD+ ADP-ribosyltransferase activity (GO:0003950) (EC:2.4.2.30)
    |_NAD+-protein ADP-ribosyltransferase activity (GO:1990404)
        |_NAD+- protein-aspartate ADP-ribosyltransferase activity (GO:0140806)
        |_NAD+-protein-serine ADP-ribosyltransferase activity (GO:0140805)
        |_NAD+- protein-lysine ADP-ribosyltransferase activity (GO:0140804)
        |_NAD+-protein-histidine ADP-ribosyltransferase activity (GO:0140815)
        |_NAD+- protein-cysteine ADP-ribosyltransferase activity (GO:0140803)
        |_NAD+-protein-arginine ADP-ribosyltransferase activity (GO:0106274)
        |_NAD+-protein-C-terminal glycine ADP-ribosyltransferase activity (GO:0140802)
        |_NAD+-protein-tyrosine ADP-ribosyltransferase activity (GO:0140808)
        |_NAD+-protein-glutamate ADP-ribosyltransferase activity (GO:0140807)
```

And here are the current GO and EC reaction/comment, FYI:

id: GO:1990404
name: NAD+-protein ADP-ribosyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: amino acyl-[protein] + NAD+ = H+ + (ADP-D-ribosyl)-amino acyl-[protein] + nicotinamide." [PMID:1899243]
synonym: "protein ADP-ribosylase activity" EXACT []
synonym: "protein ADP-ribosyltransferase activity" BROAD []
synonym: "ribosylase activity" BROAD []
xref: Wikipedia:ADP-ribosylation
is_a: GO:0016763 ! pentosyltransferase activity
is_a: GO:0140096 ! catalytic activity, acting on a protein
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/22874" xsd:anyURI
created_by: pg
creation_date: 2014-06-24T07:04:44Z



id: GO:0003950
name: NAD+ ADP-ribosyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: NAD+ + (ADP-D-ribosyl)(n)-acceptor = nicotinamide + (ADP-D-ribosyl)(n+1)-acceptor." [EC:2.4.2.30]
synonym: "ADP-ribosyltransferase (polymerizing) activity" RELATED [EC:2.4.2.30]
synonym: "NAD ADP-ribosyltransferase activity" EXACT []
synonym: "NAD+:poly(adenine-diphosphate-D-ribosyl)-acceptor ADP-D-ribosyl-transferase activity" RELATED [EC:2.4.2.30]
synonym: "poly(adenosine diphosphate ribose) polymerase activity" RELATED [EC:2.4.2.30]
synonym: "poly(ADP-ribose) synthase activity" RELATED [EC:2.4.2.30]
synonym: "poly(ADP-ribose) synthetase activity" RELATED [EC:2.4.2.30]
synonym: "poly(ADP-ribose)polymerase activity" RELATED [EC:2.4.2.30]
xref: EC:2.4.2.30
xref: MetaCyc:NAD+-ADP-RIBOSYLTRANSFERASE-RXN
is_a: GO:0016763 ! pentosyltransferase activity

ENZYME entry: EC 2.4.2.30
Reaction: NAD(+) + (ADP-D-ribosyl)n-acceptor <=> nicotinamide + (ADP-D-ribosyl)n+1-acceptor + H(+)
Comment(s): The ADP-D-ribosyl group of NAD(+) is transferred to an acceptor carboxy group **on a histone or the enzyme itself,** and further ADP- ribosyl groups are transferred to the 2'-position of the terminal adenosine moiety, building up a polymer with an average chain length of 20-30 units.

**Comment by sjm41** [comment]
Hi @sylvainpoux @pgaudet

Looking again at this, I would like to at least proceed with the proposal to tweak this name:

NAD+ ADP-ribosyltransferase activity (GO:0003950) (=EC:2.4.2.30)
>
NAD+-protein poly-ADP-ribosyltransferase activity (GO:0003950) (=EC:2.4.2.30)
(And also add 'is_a: GO:0140096 ! catalytic activity, acting on a protein' parent)

Is that OK with you?

**Comment by pgaudet** [comment]
Hi @sjm41 
If we change the term label then I think we need to merge NAD+ ADP-ribosyltransferase activity (GO:0003950)  with [NAD+-protein ADP-ribosyltransferase activity](http://purl.obolibrary.org/obo/GO_1990404) - right?? 

see also https://github.com/geneontology/go-ontology/issues/28382

**Comment by pgaudet** [comment]
Chatting with @sylvainpoux  - yes we agree, this is clearer

**Comment by pgaudet** [comment]
@sjm41 I will do it since I was working on that branch for #28382
