### ISSUE TITLE
definition "carbohydrate metabolic process'

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22880]
Definition is:

The chemical reactions and pathways involving carbohydrates, any of a group of organic compounds based of the general formula Cx(H2O)y. Includes the formation of carbohydrate derivatives by the addition of a carbohydrate residue to another molecule.

Should " Includes the formation of carbohydrate derivatives by the addition of a carbohydrate residue to another molecule." be removed? It isn't true?

https://www.ebi.ac.uk/QuickGO/term/GO:1901135

**Comment by pgaudet** [comment]
Right, I think this is how it was used in the past but we dont do that anymore.
