### ISSUE TITLE
Incorrect is-a relation: rhizobactin 1021 biosynthetic process is-a catechol-containing compound biosynthetic process

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22894]
<img width="523" alt="GO_0019289 GO_0009713 Erroneous" src="https://user-images.githubusercontent.com/17500953/155012860-bd1bad86-3743-4e53-8897-1b181af793a5.png">

_GO:0019289 rhizobactin 1021 biosynthetic process_
is-a
_GO:0009713 catechol-containing compound biosynthetic process_

Above is-a relation might be incorrect as no catechol found in rhizobactin 1021.

**Comment by pgaudet** [comment]
Thanks for the feedback, I removed the incorrect assertion. 

Pascale
