### ISSUE TITLE
Incorrect is-a relation: positive regulation of prosthetic group metabolic process is-a positive regulation of cellular protein metabolic process

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22893]
<img width="312" alt="GO_0051200 GO_0032270 Erroneous" src="https://user-images.githubusercontent.com/17500953/155011159-f96e248d-0dcb-4221-93f8-afa01bebd789.png">

_GO:0051200 positive regulation of prosthetic group metabolic process_
is-a
_GO:0032270 positive regulation of cellular protein metabolic process_

The above relation is likely incorrect as prosthetic groups are non-protein components.

**Comment by pgaudet** [comment]
There are no annotations and no references for these terms: 
* GO:0051199 regulation of prosthetic group metabolic process
* GO:0051201 negative regulation of prosthetic group metabolic process
* GO:0051200 positive regulation of prosthetic group metabolic process

These terms conflate a chemical and its role (prosthetic group), we want to avoid this for metabolic process (see also #22899). I will propose obsoletion. 

Thanks, Pascale
