### ISSUE TITLE
Missing parent: GO:0075041 positive regulation of establishment of turgor in appressorium

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22898]
* **GO term ID and label for which you request a new superclass**
_GO:0075041 positive regulation of establishment of turgor in appressorium_

* **New superclass (parent) suggested**
_GO:0075037 positive regulation of appressorium maturation_

<img width="439" alt="GO_0075041 GO_0075037 Missing" src="https://user-images.githubusercontent.com/17500953/155021803-77bedbea-3f47-4e97-96ef-4b0056580f90.png">

* **Reference(s), if appropriate**
The following is-a relation already exists in GO.
_GO:0075042 negative regulation of establishment of turgor in appressorium_ 
is_a 
_GO:0075038 negative regulation of appressorium maturation_

**Comment by pgaudet** [comment]
These 3 terms should be obsoleted: 
* GO:0075040 regulation of establishment of turgor in appressorium
* GO:0075042 negative regulation of establishment of turgor in appressorium
* GO:0075041 positive regulation of establishment of turgor in appressorium

There are no annotations, but this would anyway be a phenotype of [GO:0075017 regulation of appressorium formation](http://amigo.geneontology.org/amigo/term/GO:0075017#display-lineage-tab)

@ValWood OK with you? 

Thanks, Pascale

**Comment by ValWood** [comment]
yes I don't think these are required.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 

* GO:0075040 regulation of establishment of turgor in appressorium
* GO:0075042 negative regulation of establishment of turgor in appressorium
*GO:0075041 positive regulation of establishment of turgor in appressorium

* GO:0075026 regulation of appressorium initiation 
* GO:0075028 negative regulation of appressorium initiation
* GO:0075027 positive regulation of appressorium initiation
* GO:0075036 regulation of appressorium maturation
* GO:0075038 negative regulation of appressorium maturation
* GO:0075037 positive regulation of appressorium maturation


The reason for obsoletion is that this is a phenotype than should be annotated to the parent GO:0075017 regulation of appressorium formation (and GO:0075019 negative and GO:0075018 positive children). 

There are no annotations or mappings to these terms. These terms are not present in any subsets. You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/22898


Thanks, Pascale
