### ISSUE TITLE
Incorrect is-a relation: purine nucleobase biosynthetic process is-a pigment biosynthetic process

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22895]
<img width="425" alt="GO_0009113 GO_0046148 Erroneous" src="https://user-images.githubusercontent.com/17500953/155013910-018bad6a-114a-4823-8de1-6110d9bf723b.png">

_GO:0009113 purine nucleobase biosynthetic process_
is-a
_GO:0046148 pigment biosynthetic process_

The above is-a relation might be incorrect as purine compounds cannot be classed as true pigments.

**Comment by pgaudet** [comment]
Thanks for pointing this out.
