### ISSUE TITLE
Incorrect is-a relation: glycosinolate metabolic process is-a organic acid metabolic process

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22892]
<img width="292" alt="GO_0019757 GO_0006082 Erroneous" src="https://user-images.githubusercontent.com/17500953/155006811-34f0b555-ec87-4c10-bee4-1d521817d918.png">

_GO:0019757 glycosinolate metabolic process_
is-a
_GO:0006082 organic acid metabolic process_

Above is-a relation seems wrong as glycosinolate is not an acid.

**Comment by ValWood** [comment]
glycosinolate is now obsoleted as an unnecessary grouping term for glucosinolate

**Comment by ValWood** [comment]
glucosinolate still has the parent  oxoacid metaboic process,

https://www.ebi.ac.uk/QuickGO/term/GO:0019760

but I don't know where this originates because it isn't in CHEBI?

https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:24279

Action, check if asserted and remove

**Comment by pgaudet** [comment]
Term was obsoleted here 
https://github.com/geneontology/go-ontology/issues/28109
