### ISSUE TITLE
Missing parent: GO:0045493 xylan catabolic process

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22900]
* **GO term ID and label for which you request a new superclass**
_GO:0045493 xylan catabolic process_

* **New superclass (parent) suggested**
_GO:2000895 hemicellulose catabolic process_

<img width="1192" alt="GO_0045493 GO_2000895 Missing" src="https://user-images.githubusercontent.com/17500953/155026819-f2fd2faf-7981-4a0c-a66c-8536917e6b56.png">

* **Reference(s), if appropriate**
The following is-a relation exists in GO
_GO:0045491 xylan metabolic process_ 
is_a
_GO:0010410 hemicellulose metabolic process_

**Comment by pgaudet** [comment]
Hi @rashmie 

Thanks for reporting this. GO relies on ChEBI to classify the chemicals; would you please contact ChEBI to add the missing relation? 

https://github.com/ebi-chebi/ChEBI/issues

Thanks, Pascale

**Comment by rashmie** [comment]
Hi @pgaudet 

I contacted ChEBI regarding this. It seems they have addressed this.

https://github.com/ebi-chebi/ChEBI/issues/4228#issuecomment-1056923792

Best,
Rashmie

**Comment by pgaudet** [comment]
Now fixed, thanks ! 

<img width="363" alt="image" src="https://user-images.githubusercontent.com/4782928/185138366-148a9643-6590-4c31-884b-f3742737dcd9.png">
