### ISSUE TITLE
Fix 'conjugation' branch 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22916]
- [x]   GO:0000746 conjugation: obsolete: unnecessary and confusing grouping term
- [x] rehouse and redefine:
*  GO:0000747 'conjugation with cellular fusion'
*  GO:0000748 'conjugation with mutual genetic exchange'
*  GO:0009291 'unidirectional conjugation'
*  GO:0000762 pheromone-induced unidirectional conjugation

- [x] Also need to obsolete 
* GO:0046999 regulation of conjugation: 2 EXP  dicty (fusion of cells of opposite mating types) 
* * GO:0031135 negative regulation of conjugation 0 annotations
* * GO:0031136 positive regulation of conjugation 0 annotations

**Comment by pgaudet** [comment]
This addresses a remaining issue in https://github.com/geneontology/go-ontology/issues/21459

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
* GO:0046999 regulation of conjugation: 
* GO:0031135 negative regulation of conjugation 0 annotations
*  GO:0031136 positive regulation of conjugation 0 annotations


The reason for obsoletion is that 'conjugation' is a confusing grouping term, has been used inconsistently and so will be obsoleted. There are 2 EXP annotations to GO:0046999 by dictyBase. There are no mappings, these terms are not present in any subsets. 

You can comment on the ticket: 

https://github.com/geneontology/go-ontology/issues/22916

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete  'GO:0000762  pheromone-induced unidirectional conjugation'. The reason for obsoletion is that this term is a child of a term that describes bacterial conjugation but is defined as a eukaryote conjugation (ie it refers to different mating types). There are no references, no annotations, no mappings, this term is not in any subset. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/22916

Thanks, Pascale

**Comment by pgaudet** [comment]
- [x] conjugation with mutual genetic exchange: add def xref: PMID:2244414
 - [x] unidirectional conjugation: remove is_a conjugation

**Comment by pgaudet** [comment]
In fact I found some references for 'GO:0000762 pheromone-induced unidirectional conjugation', so I'll add these and edit the definition to "The process of unidirectional (polarized) transfer of genetic information involving direct cellular contact between a donor and recipient cell; the contact is followed by the formation of a cellular bridge that physically connects the cells; some or all of the chromosome(s) of the donor cell is  transferred into the recipient cell; unidirectional conjugation occurs between cells of different mating types." (ie remove 'male/female' in favor of donor/recipient)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 

- [ ] GO:0000746 conjugation  - 0 annotations
- [ ] GO:0000767 cell morphogenesis involved in conjugation 1 EXP by SGD (consider the child term: GO:0000753
    cell morphogenesis involved in conjugation with cellular fusion) 
- [ ] GO:0000771  agglutination involved in conjugation - 0 annotations

The reason for obsoletion is that this term represents an unnecessary and confusing grouping class, as it is defined as "The union or introduction of genetic information from compatible mating types that results in a genetically different individual", but this is not the case for all existing children. Children have been rehoused and redefined (see comments in the ticket). 

There are no mappings, these terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/22916

Thanks, Pascale

**Comment by pgaudet** [comment]
- [ ] [GO:0071835 mating pheromone secretion involved in regulation of conjugation](http://amigo.geneontology.org/amigo/term/GO:0071835#display-lineage-tab) > change label to 'mating pheromone secretion involved in regulation of conjugation with cellular fusion'

**Comment by pgaudet** [comment]
- [ ]  GO:0071832  peptide pheromone export involved in regulation of conjugation -> 0 annotations; merge into GO:0071835 mating pheromone secretion involved in regulation of conjugation with cellular fusion

**Comment by pgaudet** [comment]
In fact there were mappings to conjugation: 

* goslim_aspergillus  -> change mapping to [GO:0000747 conjugation with cellular fusion](http://amigo.geneontology.org/amigo/term/GO:0000747#display-lineage-tab)
* goslim_yeast -> change mapping to [GO:0000747 conjugation with cellular fusion](http://amigo.geneontology.org/amigo/term/GO:0000747#display-lineage-tab)
* goslim_candida -> change mapping to [GO:0000747 conjugation with cellular fusion](http://amigo.geneontology.org/amigo/term/GO:0000747#display-lineage-tab)
* goslim_pir -> change mapping to [GO:0000747 conjugation with cellular fusion](http://amigo.geneontology.org/amigo/term/GO:0000747#display-lineage-tab) (fungal)
AND GO:0009291 unidirectional conjugation (bacterial)

@marekskrzypek @srengel @nataled let me know if you want to do something different

**Comment by pgaudet** [comment]
@Antonialock There is a KW mapping to conjugation, KW-0184

I dont think this can be remapped, as the KW describes both yeast and bacterial conjugation.

**Comment by Antonialock** [comment]
@pgaudet I removed the mapping and suggested the KW is used in a rule instead.

**Comment by pgaudet** [comment]
Further changes during discussion in multiorg group
@dsiegele @mgiglio99 @genegodbold @nsuvarnaiari

**Comment by pgaudet** [comment]
add synonym: "bacterial conjugation" RELATED

**Comment by pgaudet** [comment]
GO:0000762  pheromone-induced unidirectional conjugation
Change def: 
-def: "Unidirectional transfer of genetic information in response to a pheromone." [GOC:elh, PMID:17360276, PMID:27021562, PMID:31191478]
+def: "Unidirectional transfer of genetic information triggered by to a pheromone signal.
