### ISSUE TITLE
Changes to children of 'reproduction' and 'reproduction process'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22929]

**Comment by pgaudet** [comment]
- [ ] sexual reproduction: fix def from 
"A reproduction process that creates a new organism by combining the genetic material of two gametes, which may come from two organisms or from a single organism, in the case of self-fertilizing hermaphrodites, e.g. C. elegans, or self-fertilization in plants. It occurs both in eukaryotes and prokaryotes: in multicellular eukaryotic organisms, an individual is created anew; in prokaryotes, the initial cell has additional or transformed genetic material. In a process called genetic recombination, genetic material (DNA) originating from two gametes join up so that homologous sequences are aligned with each other, and this is followed by exchange of genetic information. After the new recombinant chromosome is formed, it is passed on to progeny." [GOC:jl, GOC:kmv, GOC:krc, GOC:tb, ISBN:0387520546, Wikipedia:Sexual_reproduction]" 
to "A type of reproduction that combines the genetic material of two gametes (such as a sperm or egg cell or fungal spores). The gametes have an haploid genome (with a single set of chromosomes, the product of a meiotic division) and combines with one another to produce a zygote (diploid)." [Wikipedia:Sexual_reproduction]"
+ moved part of the old def to the comment: "Note that gametes may come from two organisms or from a single organism in the case of self-fertilizing hermaphrodites, e.g. C. elegans, or self-fertilization in plants."
- [x] GO:0097736 aerial mycelium formation: change subclass from is_a GO:0019954 ! asexual reproduction to part_of GO:0019954 ! asexual reproduction
- [x]  GO:1990277 parasexual conjugation with cellular fusion: change def from ""A conjugation process that results in the union of cellular and genetic information from compatible mating types, without meiosis or the development of sexual structures." [GOC:di, PMID:26210747] to "A type of reproduction in which new individuals are produced from two individuals, without the fusion of gametes." [GOC:di, PMID:26210747]"

**Comment by pgaudet** [comment]
@ValWood I think 'parasexual reproduction with cellular fusion' should be is_a 'asexual reproduction', right?

**Comment by ValWood** [comment]
I think so...

**Comment by pgaudet** [comment]
I'll leave the 3 terms separate (sexual, asexual and parasexual reproduction)
