### ISSUE TITLE
Missing parent: GO:0036336 dendritic cell migration

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22939]
* **GO term ID and label for which you request a new superclass**
_GO:0036336 dendritic cell migration_

* **New superclass (parent) suggested**
_GO:0072676 lymphocyte migration_

The above two are siblings of the parent: _GO:0071674 mononuclear cell migration_

* **Reference(s), if appropriate**
The following relation currently exists in GO.
_GO:0044565 dendritic cell proliferation_ 
is_a 
_GO:0046651 lymphocyte proliferation_

**Comment by raymond91125** [comment]
It seems to me that dendritic cell is NOT a sub-type of lymphocyte (B, T, and NK cell), and thus the IS_A relationship between dendritic cell proliferation and lymphocyte proliferation should be REMOVED. 
Ref: https://www.onlinebiologynotes.com/cells-immune-system-lymphocytes-phagocytic-cell-granulocytes-dendritic-cells/
@rashmie What do you think? Thanks.

**Comment by addiehl** [comment]
Hi Raymond,

You are correct.  Dendritic cells are not a type of lymphocyte, and the is_a relationship between 'dendritic cell proliferation' and 'lymphocyte proliferation' should be removed.  The appropriate parent for 'dendritic cell proliferation' is 'mononuclear cell proliferation'.

The current parent of 'dendritic cell migration', 'mononuclear cell migration', is the correct parent and should not be changed.

-- Alex

**Comment by raymond91125** [comment]
Yes, the relationship to mononuclear cell migration is automatically inferred and will be kept. Thanks. @addiehl

**Comment by raymond91125** [comment]
@rashmie If it's OK with you, we can close this ticket. Thanks.

**Comment by rashmie** [comment]
@raymond91125 and @addiehl Thanks for looking into this. I will close this now.
