### ISSUE TITLE
Missing parent: GO:0034488 basic amino acid transmembrane export from vacuole

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22932]
* **GO term ID and label for which you request a new superclass**
_GO:0034488 basic amino acid transmembrane export from vacuole_

* **New superclass (parent) suggested**
_GO:0032974 amino acid transmembrane export from vacuole_

The above two classes are siblings under _GO:0034486 vacuolar transmembrane transport_.

* **Reference(s), if appropriate**
The following is-a relation already exists in GO.
_GO:0034490 basic amino acid transmembrane import into vacuole_ 
is_a
_GO:0032975 amino acid transmembrane import into vacuole_

**Comment by pgaudet** [comment]
This may have been fixed via a different ticket - this relation is now there: 

<img width="385" alt="image" src="https://user-images.githubusercontent.com/4782928/185137542-f15cc5df-8b11-4a2f-ac5c-e5e3616a7eef.png">
