### ISSUE TITLE
Missing parent: GO:0014028 notochord formation

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22936]
* **GO term ID and label for which you request a new superclass**
_GO:0014028 notochord formation_

* **New superclass (parent) suggested**
_GO:0048645 animal organ formation_

The above two are siblings under the parent: _GO:0048646 anatomical structure formation involved in morphogenesis_

* **Reference(s), if appropriate**
The following is-a relations already exists in GO.
_GO:0030903 notochord development_ 
is_a 
_GO:0048513 animal organ development_

**Comment by raymond91125** [comment]
Notochord is an organ. see PMID:15890825 Structure and function of the notochord: an essential organ for chordate development. If we add this IS_A relationship in Uberon, we may get the desired classification automatically.
