### ISSUE TITLE
Missing parent: GO:1901293 nucleoside phosphate biosynthetic process

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22935]
* **GO term ID and label for which you request a new superclass**
  _GO:1901293 nucleoside phosphate biosynthetic process_

* **New superclass (parent) suggested**
_GO:0034404 nucleobase-containing small molecule biosynthetic process_

Above two are siblings under the parent: _GO:0034654 nucleobase-containing compound biosynthetic process_

* **Reference(s), if appropriate**
The following relation already exists in GO.
_GO:0006753 nucleoside phosphate metabolic process_ 
is_a 
_GO:0055086 nucleobase-containing small molecule metabolic process_

**Comment by ValWood** [comment]
This was fixed already:
<img width="657" alt="Screenshot 2023-05-16 at 14 11 42" src="https://github.com/geneontology/go-ontology/assets/7359272/7596c3b0-fe29-4db6-800e-bf4748c1f2cf">

**Comment by ValWood** [comment]
This was fixed already:
<img width="488" alt="Screenshot 2023-06-16 at 11 07 46" src="https://github.com/geneontology/go-ontology/assets/7359272/6d055dfc-7c1f-4285-b395-f64c2cf603fd">

**Comment by pgaudet** [comment]
I dont see this relation in Protégé
