### ISSUE TITLE
Changes to auxin influx/efflux

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22948]
Hi, 

I am making these changes to have unique logical definitions for transport BP terms, see #22721

- [x]  GO:0010315 auxin efflux
- Change label to  'auxin export across the plasma membrane'
- Change logical def to 
 intersection_of: GO:0006810 ! transport
 intersection_of: has_input GOCHE:22676 ! substance with auxin role
+intersection_of: has_target_end_location GO:0005576 ! extracellular region
+intersection_of: has_target_start_location GO:0005622 ! intracellular anatomical structure
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane

- [x]  GO:0060919 auxin influx
- Change label to  'auxin import into cell'
- Change logical def to 
 intersection_of: GO:0006810 ! transport
 intersection_of: has_input GOCHE:22676 ! substance with auxin role
+intersection_of: has_target_end_location GO:0005622 ! intracellular anatomical structure
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane

- [x]  GO:0080162  intracellular auxin transport (single annotation)
- Change label to : 'endoplasmic reticulum to cytosol auxin transport'
- REMOVE is_a: GO:0060919 ! auxin influx
- REMOVE intersection_of: GO:0060918 ! auxin transport
- REMOVE intersection_of: occurs_in GO:0005622 ! intracellular anatomical structure
- Change logical def to 
+intersection_of: GO:0006810 ! transport
+intersection_of: has_input GOCHE:22676 ! substance with auxin role
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005788 ! endoplasmic reticulum lumen
+intersection_of: results_in_transport_across GO:0005789 ! endoplasmic reticulum membrane

@tberardini I checked that this was consistent with existing annotations; let me know if you'd like me to make other modifications. 

Thanks, Pascale

**Comment by vanaukenk** [comment]
@pgaudet - Is the plan to eventually use 'has primary input' in place of 'has input' for these kinds of transport logical defs?
I'm also looking at https://github.com/geneontology/go-ontology/issues/22721

**Comment by tberardini** [comment]
@pgaudet  I did not see this ticket before. :(  Please confirm that you retained the original primary term names as synonyms.  Thanks.

**Comment by pgaudet** [comment]
@tberardini this is weird, usually we get an error for not having the former term label as a synonym, but I thought all checked had passed! I now added the synonym back. 

Is there anything else you'd like changed?

**Comment by tberardini** [comment]
I can't remember how to view the final term block. If you would like me to have one more look, please copy/paste them and I'll do so.

**Comment by pgaudet** [comment]
Yeah the diff only shows partial information. Here are the changes for the 3 terms: 

**id: GO:0010315
name: auxin export across the plasma membrane**
namespace: biological_process
def: "The directed movement of auxins from inside of a cell, across the plasma membrane and into the extracellular region." [GOC:tair_curators, PMID:16990790]
synonym: "auxin efflux" BROAD []
synonym: "auxin export" BROAD []
intersection_of: GO:0006810 ! transport
intersection_of: has_primary_input GOCHE:22676 ! substance with auxin role
intersection_of: has_target_end_location GO:0005576 ! extracellular region
intersection_of: has_target_start_location GO:0005737 ! cytoplasm
intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
relationship: regulates GO:0009734 ! auxin-activated signaling pathway


**id: GO:0060919
name: auxin import into cell**
namespace: biological_process
def: "The directed movement of auxins from outside of a cell into a cell." [PMID:22773749]
synonym: "auxin influx" BROAD []
is_a: GO:0060918 ! auxin transport
intersection_of: GO:0006810 ! transport
intersection_of: has_primary_input GOCHE:22676 ! substance with auxin role
intersection_of: has_target_end_location GO:0005829 ! cytosol
intersection_of: has_target_start_location GO:0005576 ! extracellular region
intersection_of: results_in_transport_across GO:0005886 ! plasma membrane

**id: GO:0080162
name: endoplasmic reticulum to cytosol auxin transport**
namespace: biological_process
def: "The directed movement of auxins from endoplasmic reticulum to cytosol." [PMID:19506555]
synonym: "intracellular auxin transport" BROAD []
intersection_of: GO:0006810 ! transport
intersection_of: has_primary_input GOCHE:22676 ! substance with auxin role
intersection_of: has_target_end_location GO:0005829 ! cytosol
intersection_of: has_target_start_location GO:0005788 ! endoplasmic reticulum lumen
intersection_of: results_in_transport_across GO:0005789 ! endoplasmic reticulum membrane

**Comment by tberardini** [comment]
Do you want to be consistent with cytosol/cytoplasm?  2/3 are cytosol. Otherwise, this looks good. Thanks for the additional details.
