### ISSUE TITLE
Missing 'regulates' relation for: GO:0005981 regulation of glycogen catabolic process

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22942]
The GO currently does not contain the following relation:
_GO:0005981 regulation of glycogen catabolic process_	
regulates	
_GO:0006007 glucose catabolic process_

However, GO has the following regulates relation which is similar to the above.
_GO:0070873 regulation of glycogen metabolic process_ 
regulates 
_GO:0006006 glucose metabolic process_

Note that the latter existing GO relation is not a direct relation relation. GO:0070873 is-a GO:0010906 part-of GO:0006006.

**Comment by raymond91125** [comment]
I think the asserted relationship 'regulation of glycogen metabolic process' SubClassOf 'regulation of glucose metabolic process' is conflated and should be removed.
There is NOT a relationship 'glycogen metabolic process' SubClassOf 'glucose metabolic process'
@hdrabkin second opinion? Thanks.

**Comment by ukemi** [comment]
For GO-CAM pathways, both Reactome and mouse have made glycogen catabolism/biosynthesis start with glucose-6-phosphate. So although the objective is to store and mobilize 'glucose', our pathways would not count as glucose metabolic processes. @deustp01

**Comment by ukemi** [comment]
If we decided that we wanted them to be glucose metabolic processes, we would have to include a gluco/hexokinase step and a glucose-6-phosphatase step. To me it makes most sense to have the currency be G-6-P as it can feed directly into glycolysis as well as glycogen synthesis, but I'd like to hear what @deustp01 thinks.

**Comment by ukemi** [comment]
Pathway boundaries, sigh.

**Comment by ukemi** [comment]
Sorry for the multiple comments, but may also be worthwhile to consider that I'm pretty sure glucose is the circulating molecule that gets transported in and out of cells. Maybe we do want to go all the way to glucose?

**Comment by ukemi** [comment]
By the way, I don't think glycogen catabolism and biosynthesis would be considered to be types of glucose biosynthesis and catabolism, just metabolism if we went the extra step. They really relate more to glucose homeostasis I would think.

**Comment by deustp01** [comment]
This is the discussion from four or five years ago that went into the manual reannotation of glycolysis and related processes. If we say that a process / pathway should start at the point where it becomes unique, not overlapping other processes that use the same outputs, then it would make sense, sat least for mammals, to have a process something like glucose transport and uptake that encompasses all the molecular functions that enable glucose liberated in the gut by digestion, to be taken up into the circulation, to be taken up by various target cells, and to be converted to glucose-6-phosphate in those target cells. The phosphorylation mostly renders the glucose incapable of being transported back out of the cell, and readies it for three intracellular processes, glycolysis, glycogen synthesis, and the pentose phosphate pathway. There are probably other uses of glucose-6-phosphate in humans that I am forgetting, as well as ones in non-human animals that I don't know.

In the other direction, two major processes, glycogen catabolism and gluconeogenesis generate glucose-6-phosphate as an end product, ready for entry into other processes including dephosphorylation and export from the cell. That dephosphorylation reaction would be part of the glucose uptake and transport process.

This network of processes can be assembled into all sorts of futile cyclical processes in which glucose is phosphorylated and dephosphorylated, or catabolized to pyruvate and then metabolized back to glucose. Coordinate regulatory processes respond to hormones like insulin and glucogon to selectively up- and down-regulate various combinations of specific processes to keep that futile cycling form happening.

That all makes glucose-6-phosphate a key intracellular metabolic junction - many processes make it; many others consume it; regulation of the flux among these pathways enables an animal to maintain circulating blood glucose levels needed for red blood cell and brain function in the face of wildly variable environmental and nutritional stresses.

The patriarchs of biochemistry, in their wisdome, howevr, even as they and their followers were working out the details of all of these processes, decreed that glycolysis begins with the phosphorylation of cytosolic glucose to form glucose-6-phosphate, so unless we want to form a breakaway sect, we're stuck with that starting point.

**Comment by deustp01** [comment]
> However, GO has the following regulates relation which is similar to the above.
> _GO:0070873 regulation of glycogen metabolic process_
> regulates
> _GO:0006006 glucose metabolic process_

In light of the sermon in the previous comment, this is sometimes true in the sense that glucose-6-phosphate generated by glycogen catabolism can be consumed by the process of glycolysis. It is also formally possible that glucose-6-phosphate generated by gluconeogenesis could be consumed by glycogen synthesis but the hormone-dependent regulation processes mentioned in the sermon normally act on each of the processes separately to prevent this - it's not the case that regulation of only one process regulates the other as aqn add-on effect.

**Comment by ukemi** [comment]
We also have, due to convention I think, made gluconeogenesis end with glucose via G6PC. So we are in alignment with the classics at that point and GO and Reactome are in alignment. If you search the GO-CAM repository, you will see the GO-CAMs I made for all of these in mice. They were based on imported Reactome models. I have used some conventions for splitting them into separate models when Reactome branched and sometimes when Reactome invoked a set.

**Comment by ukemi** [comment]
@deustp01 I think the immediate action point of this ticket is to remove the regulates relation in the ontology since it is not universally true.

**Comment by ValWood** [comment]
please also bear in mind this ticket when you implement a solution.
https://github.com/geneontology/go-annotation/issues/4017

**Comment by raymond91125** [comment]
@ValWood thanks for the reminder. But perhaps that discussion may not directly affect the decision on this regulation ticket.

**Comment by ValWood** [comment]
Yes you are right. It isn't related.
v
