### ISSUE TITLE
Missing part-of relation for: GO:0060658 nipple morphogenesis	

### ISSUE THREAD

**Issue by rashmie** [geneontology/go-ontology#22941]
The GO currently does not have the following part-of relation.

_GO:0060658 nipple morphogenesis_	
part_of	
_GO:0060443 mammary gland morphogenesis_

However, GO has the following similar part-of relation.
_GO:0060618 nipple development_ 
part_of
_GO:0030879 mammary gland development_

**Comment by pgaudet** [comment]
Should this not come from Uberon?

**Comment by raymond91125** [comment]
Apparently not. The requested relationship is not in AmiGO or QuickGO.
nipple morphogenesis LogicalDef 'anatomical structure morphogenesis' and ('results in morphogenesis of' some nipple)
mammary gland morphogenesis LogicalDef 'anatomical structure morphogenesis' and ('results in morphogenesis of' some 'mammary gland')
In Uberon, nipple part_of mammary gland.

**Comment by pgaudet** [comment]
I see, but for mammary gland development the relation 'part of' some 'mammary gland development' is asserted. 

The question is, do we want to assert that each part of a larger structure is part of its development? or do we want the relations to do that for us? 

@cmungall @balhoff @ukemi 
Is it on purpose that there are no inference chains here? 

Thanks, Pascale

**Comment by balhoff** [comment]
In Uberon, nipple is only part of mammary gland in mice. It is stated to be part of breast in human, and otherwise doesn't seem to have globally asserted 'part of' relations.

**Comment by pgaudet** [comment]
So, it is true to assert this in GO then? If this is not universally true?

**Comment by balhoff** [comment]
I'm not sure it's universally true; it isn't implied by our existing property chains. But I would rather ask a developmental biologist than myself. :-)

**Comment by pgaudet** [comment]
@ukemi Any thoughts on this?

**Comment by raymond91125** [comment]
In FMA, there is no relationship between mammary gland and nipple, or mammary gland and breast for that matter. 
But it seems nipple part_of (mammary gland part_of breast) <https://www.ncbi.nlm.nih.gov/books/NBK547666/>.

**Comment by pgaudet** [comment]
@raymond91125 maybe we could just assert this ?

**Comment by raymond91125** [comment]
The part_of relationship has been asserted. I'll close this ticket unless someone objects.

**Comment by cmungall** [comment]
This is still under discussion on the uberon tracker. It’s important we
propagate relationships via standard rules and don’t make ac hoc assertions

**Comment by pgaudet** [comment]
Maybe it's OK that we assert, we can later look for redundant assertions/infererences and remove them ?

**Comment by raymond91125** [comment]
That is the idea. Not perfect, of course.

> Maybe it's OK that we assert, we can later look for redundant assertions/infererences and remove them ?
