### ISSUE TITLE
missing taxon constraints

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#22946]
@alexsign reports 531 taxon constraints disappearing from last Friday's snapshot, using http://purl.obolibrary.org/obo/go/snapshot/extensions/go-plus.json.

**Comment by balhoff** [comment]
@alexsign I compared the current snapshot to the last release, and I don't see much of a difference in taxon constraints. I used a very rough method to look at the json, after I did an OWL diff on the OWL files that didn't show many changes:

```
$ grep RO_0002161 go-plus-release.json | wc -l
     530
$ grep RO_0002160 go-plus-release.json | wc -l
    1068
$ grep RO_0002161 go-plus-current.json | wc -l
     531
$ grep RO_0002160 go-plus-current.json | wc -l
    1061
```

Can you describe how you are counting? Thanks!

**Comment by pgaudet** [comment]
Cannot reproduce. We will open a new ticket if this happens again.

**Comment by kltm** [comment]
@balhoff 's patch for non-deterministic issues https://github.com/geneontology/go-ontology/pull/23496

**Comment by pgaudet** [comment]
Is this still valid @alexsign @balhoff ?

**Comment by balhoff** [comment]
I think this is fixed now, so we can close. But @alexsign please let us know if it happens again.
