### ISSUE TITLE
Add a check for 'replaced by' and 'consider' fields

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#22961]
Hi @balhoff 

We need a check to make sure that the values in the 'replaced by' and 'consider' fields are of the format GO:nnnnnnn

Thanks, Pascale

**Comment by pgaudet** [comment]
Ah ! 
Certainly for 'replaced:by it needs to be a GO term. 

I dont have a string feeling about 'consider', although most curation interfaces will not be able to use that directly, perhaps a comment is better? We can change that later if we encounter other examples? What do you think?

**Comment by balhoff** [comment]
I'll keep it restricted to GO, at least until we run into an issue. 'cell' was the only example I thought of, and we must have avoided replaced_by on purpose due to GO annotation use cases.

**Comment by pgaudet** [comment]
> ERROR: Non-GO replacement for obsolete term: http://purl.obolibrary.org/obo/GO_0097458 refers to non-GO term: CL:0000540

neuron part / neuron

 > ERROR: Non-GO replacement for obsolete term: http://purl.obolibrary.org/obo/GO_0044464 refers to non-GO term: CL:0000000

cell part/ cell

>    ERROR: Non-GO replacement for obsolete term: http://purl.obolibrary.org/obo/GO_0097223 refers to non-GO term: CL:0000019

sperm part/ sperm

@cmungall Do we want these kinds of replacements? If we do, we must be missing a lot.
