### ISSUE TITLE
NTR: [ACP-dependent peptidyl-lysine N6-myristoyltransferase activity] and other terms related

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#22968]
Hi GO,

I recently requested an update to add Rhea cross references for GO:0018030 (peptidyl-lysine N6-myristoyltransferase activity) and GO:0018031 (peptidyl-lysine N6-palmitoyltransferase activity)
 
Unfortunately, it looks like that there are 2 different manners to catalyze peptidyl-lysine N6-palmitoylation and N6-myristoylation.

Some proteins catalyze a CoA-dependent reaction, while a family in bacteria catalyzes reactions dependent on ACP. 

I would therefore need to create children GO terms

Thanks

Sylvain

1)
ACP-dependent peptidyl-lysine N6-myristoyltransferase activity
Catalysis of the reaction: L-lysyl-[protein] + tetradecanoyl-[ACP] = H(+) + holo-[ACP] + N(6)-tetradecanoyl-L-lysyl-[protein] 
child of GO:0018030 peptidyl-lysine N6-myristoyltransferase activity
PMID:32461253
Xref: Rhea:70611

2)
ACP-dependent peptidyl-lysine N6-palmitoyltransferase activity
Catalysis of the reaction: hexadecanoyl-[ACP] + L-lysyl-[protein] = H(+) + holo-[ACP] + N(6)-hexadecanoyl-L-lysyl-[protein] 
child of GO:0018031 peptidyl-lysine N6-palmitoyltransferase activity
PMID:32461253
Xref Rhea:70615

3)
CoA-dependent peptidyl-lysine N6-myristoyltransferase activity
Catalysis of the reaction: L-lysyl-[protein] + tetradecanoyl-CoA = CoA + H(+) + N(6)-tetradecanoyl-L-lysyl-[protein] ~[Rhea:59752]~
PMID: 1402651
child of GO:0018030 peptidyl-lysine N6-myristoyltransferase activity
~RHEA:59752~

4)
CoA-dependent peptidyl-lysine N6-palmitoyltransferase activity
Catalysis of the reaction: L-lysyl-[protein] + hexadecanoyl-CoA = CoA + H(+) + N(6)-hexadecanoyl-L-lysyl-[protein] [Rhea:59752]
PMID: 30061757 
child of GO:0018031 peptidyl-lysine N6-palmitoyltransferase activity
~RHEA:55420~ has been removed  from RHEA.

5) Update GO:0018031 peptidyl-lysine N6-palmitoyltransferase activity

Remove Xref RHEA:55420

5) Update GO:0018030 peptidyl-lysine N6-myristoyltransferase activity

Remove RHEA:59752

**Comment by pgaudet** [comment]
+def: "Catalysis of the reaction: L-lysyl-[protein] + tetradecanoyl-[ACP] = H(+) + holo-[ACP] + N(6)-tetradecanoyl-L-lysyl-[protein]." [PMID:32461253, RHEA:70611]
+xref: RHEA:70611
+is_a: GO:0018030 ! peptidyl-lysine N6-myristoyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22968 xsd:anyURI
+created_by: pg
+creation_date: 2022-03-02T12:44:18Z
+
+[Term]
+id: GO:0140770
+name: CoA-dependent peptidyl-lysine N6-myristoyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-lysyl-[protein] + tetradecanoyl-CoA = CoA + H(+) + N(6)-tetradecanoyl-L-lysyl-[protein]." [PMID:1402651, RHEA:59752]
+xref: RHEA:59752
+is_a: GO:0018030 ! peptidyl-lysine N6-myristoyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22968 xsd:anyURI
+created_by: pg
+creation_date: 2022-03-02T12:45:16Z
+
+[Term]
+id: GO:0140771
+name: ACP-dependent peptidyl-lysine N6-palmitoyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: hexadecanoyl-[ACP] + L-lysyl-[protein] = H(+) + holo-[ACP] + N(6)-hexadecanoyl-L-lysyl-[protein]." [PMID:32461253, RHEA:70615]
+xref: RHEA:70615
+is_a: GO:0018031 ! peptidyl-lysine N6-palmitoyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22968 xsd:anyURI
+created_by: pg
+creation_date: 2022-03-02T12:51:53Z
+
+[Term]
+id: GO:0140772
+name: CoA-dependent peptidyl-lysine N6-palmitoyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-lysyl-[protein] + hexadecanoyl-CoA = CoA + H(+) + N(6)-hexadecanoyl-L-lysyl-[protein]." [PMID:30061757, RHEA:59752]
+xref: RHEA:59752
+is_a: GO:0018031 ! peptidyl-lysine N6-palmitoyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22968 xsd:anyURI
+created_by: pg
+creation_date: 2022-03-02T12:52:22Z

**Comment by pgaudet** [comment]
After exchange with @sylvainpoux 

GO:0140772  CoA-dependent peptidyl-lysine N6-palmitoyltransferase activity is in fact a broader term for 
RHEA:59768
hexadecanoyl-CoA + L-lysyl-/S-(2E,6E,10E)-geranylgeranyl-L-cysteinyl-[protein] = CoA + H(+) + N(6)-hexadecanoyl-L-lysyl-/S-(2E,6E,10E)-geranylgeranyl-L-cysteinyl-[protein]
