### ISSUE TITLE
NTR: [radial glial cell process extension]

### ISSUE THREAD

**Issue by magrane** [geneontology/go-ontology#22966]
Please provide as much information as you can: 

* **Suggested term label:** radial glial cell process extension

* **Definition (free text)** The elongation of radial glial cell processes during embryonic brain development which are required to guide immature neurons to the appropriate cortical layer.

* **Reference, in format PMID:#######** PMID:31147466

* **Gene product name and ID to be annotated to this term** mouse Ano1 (Q8BHY3)

* **Parent term(s)** Not sure where this fits. Maybe as a child of "radial glial cell differentiation"?

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
I think the process growth/extension of RGC is not part of its differentiation but development.
Perhaps --

- radial glial cell process extension IS_A glial cell projection elongation

- radial glial cell process extension PART_OF radial glial cell development (new term)

**Comment by pgaudet** [comment]
Thanks for finding these terms! Can we also define the difference between 'process' and 'extension'?

**Comment by raymond91125** [comment]
How about DEF: Radial glial cell projection elongation that occurs during embryonic brain development and is required to guide immature neurons to the appropriate cortical layer.
"radial glial cell process extension" is how the authors call it.

**Comment by pgaudet** [comment]
Hi @raymond91125 

Do we really need 'GO:0160026 radial glial cell **process** extension' ? If we do, we should create the corresponding CC. Right now GO:0097386 'glial cell projection' is defined as "A prolongation or process extending from a glial cell.", ie it sounds like a process is the same as a projection. Unless we can define  'process' and 'projection' differently, I dont think we should create a new term (also, the paper cited in the GO:0097386 term [PMID:27131624](http://www.ncbi.nlm.nih.gov/pubmed/27131624), talks about 'processes'). 

Thanks, Pascale

**Comment by raymond91125** [comment]
@magrane Do you think annotating to the term GO:0106091 glial cell projection elongation is sufficient? Thanks.

**Comment by magrane** [comment]
I guess it depends on how fine-grained the term should be. Radial glial cells are a subtype of glial cells so "glial cell projection elongation" would be ok but PMID:31147466 talks specifically about radial glial cells.

**Comment by pgaudet** [comment]
Maybe this is OK? We probably cannot distinguish every cell type. Do you think you can use an extension to specific the exact cell type?

**Comment by magrane** [comment]
Sure - I can use "glial cell projection elongation". Thanks both for your help with this.
