### ISSUE TITLE
lots of myosin phosphatases (EC mapping)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22987]
we have lots of mappings from Ec to "myosin phosphatase". I don't know if all of these  ~kinases~ phosphatases have myosin as a substrate but it seems unlikely, so I will remove this mapping. The mapping is likely  derived from the fact that the gene product mapped from is called a "myosin phosphatase" because myosin is frequently used in kinase assays

I don't think we should have Ec mappings to myosin substrates (or, any other specific substrates)

<img width="949" alt="Screenshot 2022-03-07 at 07 40 14" src="https://user-images.githubusercontent.com/7359272/156988449-4f9111b0-27a1-43a5-b0b1-a0a889062fd9.png">

**Comment by pgaudet** [comment]
I suggest we merge the children of GO:0004722 protein serine/threonine phosphatase activity describing specific targets into GO:0004722 protein serine/threonine phosphatase activity:

* GO:0004723 calcium-dependent protein serine/threonine phosphatase activity: 10 EXP
* GO:1990439 MAP kinase serine/threonine phosphatase activity: 6 EXP
* GO:0033192 calmodulin-dependent protein phosphatase activity: 21 EXP

+ several other terms should be merged in this area. 

Or does anyone want to keep these terms?

Thanks,

**Comment by ValWood** [comment]
I'm not sure. it has been discussed in the past and I think people wanted to keep them.  I would prefer that we didn't. For example the "MAP kinase serine/threonine phosphatase activity" is not specific for MAP kinases, they have many other substrates so these aren't  like the MAP kinase terms.

@vanaukenk  what do you think? Can you remember the discussions, or have we never discussed these particular terms?

**Comment by ValWood** [comment]
closing because the EC mappings have gone
