### ISSUE TITLE
NTR: [ iron carrier activity]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#22989]
* **Suggested term label:**

GO:0140104   
molecular carrier activity

* **Definition (free text)**

Directly binding to an iron ion  and delivering it either to an acceptor molecule.

* **Reference, in format PMID:#######**

PMID:34154323
https://pubmed.ncbi.nlm.nih.gov/34154323/

* **Gene product name and ID to be annotated to this term**

Dph3 a diphthamide biosynthesis protein  conserved across eukaryotes 
e.g. https://www.pombase.org/gene/SPAC8F11.02c

* **Parent term(s)**

GO:0140104   molecular carrier activity

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

exact: iron ion donor

**Comment by pgaudet** [comment]
@ValWood Can you use 
'GO:0034986 iron chaperone activity'

I can change the def to the one you propose (current def= "Directly binding to and delivering iron ions to a target protein."). 

Thanks, Pascale

**Comment by ValWood** [comment]
I can use iron chaperone.

but I am now confused why some things are described as carriers, and some as chaperones.

iron-sulfur cluster carrier activity
Binding to an iron-sulfur cluster and delivering it to an acceptor molecule.
is a chaperone.

The same applies to most, but not all of the other activities describes as carriers. What do we mean by 'delivering'? in terms of molecular activity/mechanism?

**Comment by pgaudet** [comment]
I'd be OK renaming the hole branch 'carrier activity'. The history is that in the literature people mention 'iron chaperones', copper chaperones', but these can be synonyms. 

It's hard to find the right balance between consistency and usability.

**Comment by ValWood** [comment]
Right, I forgot that chaperones were in the carrier branch. I thought there were 2 separate branches. So there isn't really a problem.  You can close this and I will use the existing term.
