### ISSUE TITLE
NTR - metabolism: [ilicicolin H biosynthetic process]

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#22982]
I would only create the biosynthesis term since in general there are no degradation pathways of these metabolites (only few exceptions). No regulation terms, it was not characterized yet.

"ilicicolin H biosynthetic process"

ChEBI Name: ilicicolin H
ChEBI ID: CHEBI:77772

Definition:
The chemical reactions and pathways resulting in the formation of ilicicolin H, a 4-hydroxy-2-pyridone alkaloid that has potent and broad antifungal activities by inhibiting the mitochondrial respiration chain.

PMID:30905148, PMID:31216742 and PMID:34947016

Gene product names and IDs to be annotated to this term:
iccA, A0A482N9V7 (RHEA:64544)
iliA, P0DO30 (RHEA:64544)
iliA, G0REX6 (RHEA:64544)
iccB, A0A482N9T9 (RHEA:64548)
iliB, P0DO31 (RHEA:64548)
iliB, G0REX7 (RHEA:64548)
iccC, A0A482NAF7 (RHEA:64552)
iliC, P0DO32 (RHEA:64552)
iliC, G0REX9 (RHEA:64552)
iccD, A0A482NB13 (RHEA:64556)
iliD, P0DO33 (RHEA:64568)
iliD, P9WEU0 (RHEA:64568)
IccE, A0A482N8M8 (RHEA:64565)

Parent terms:
GO:0009821 alkaloid biosynthetic process
GO:0043386 mycotoxin biosynthetic process

Synonyms:
ilicicolin H synthesis, ilicicolin H biosynthesis, ilicicolin H formation, ilicicolin H anabolism (EXACT)

Child terms: None

Cross-references
MetaCyc: None 
KEGG: None 

Taxon constraint: Only in taxon 4751 Fungi

Thanks a lot.
Best regards,
Marc

**Comment by pgaudet** [comment]
- [ ] add ilicicolin H ChEBI ID: CHEBI:77772  in CHeBI imports
- [ ] add LD with ChEBI Name: ilicicolin H ChEBI ID: CHEBI:77772  
- [ ] add taxon constraint Only in taxon 4751 Fungi

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140781
+name: ilicicolin H biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of ilicicolin H, a 4-hydroxy-2-pyridone alkaloid that has potent and broad antifungal activities by inhibiting the mitochondrial respiration chain." [PMID:30905148, PMID:31216742, PMID:34947016]
+synonym: "ilicicolin H anabolism" EXACT []
+synonym: "ilicicolin H biosynthesis" EXACT []
+synonym: "ilicicolin H formation" EXACT []
+synonym: "ilicicolin H synthesis" EXACT []
+is_a: GO:0043386 ! mycotoxin biosynthetic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22982 xsd:anyURI
+created_by: pg
+creation_date: 2022-03-31T11:15:26Z
