### ISSUE TITLE
NTR: corneal epithelial differentiation

### ISSUE THREAD

**Issue by Mingsenli** [geneontology/go-ontology#22991]
Please provide as much information as you can: 

* **Suggested term label:**
corneal epithelial differentiation

* **Definition (free text)**
Limbal stem/progenitor cells residing in the basal layer of the limbus differentiate into corneal epithelial cells during homeostasis.

* **Reference, in format PMID:#######**
PMID: 33414365
* **Gene product name and ID to be annotated to this term**
EntrezID | gene name
2812 | SEPT5
63874 | ABHD4
57406 | ABHD6
25890 | ABI3BP
84448 | ABLIM2
59272 | ACE2
131 | ADH7
122622 | ADSSL1
216 | ALDH1A1
218 | ALDH3A1
221 | ALDH3B1
222 | ALDH3B2
10218 | ANGPTL7
55616 | ASAP3
285973 | ATG9B
8705 | B3GALT4
10317 | B3GALT5
573 | BAG1
576 | BAI2
27113 | BBC3
8424 | BBOX1
604 | BCL6
29760 | BLNK
90427 | BMF
149428 | BNIPL
770 | CA11
199731 | CADM4
810 | CALML3
57118 | CAMK1D
23492 | CBX7
57126 | CD177
948 | CD36
1004 | CDH6
1028 | CDKN1C
79603 | CERS4
10752 | CHL1
64581 | CLEC7A
1191 | CLU
152330 | CNTN4
27151 | CPAMD8
119587 | CPXM2
153222 | CREBRF
9244 | CRLF1
1410 | CRYAB
1471 | CST3
8722 | CTSF
51523 | CXXC5
79901 | CYBRD1
92196 | DAPL1
1628 | DBP
1634 | DCN
1672 | DEFB1
414918 | DENND6B
3338 | DNAJC4
1823 | DSC1
1828 | DSG1
1950 | EGF
2043 | EPHA4
2049 | EPHB3
79852 | EPHX3
79152 | FA2H
2167 | FABP4
220965 | FAM13C
284069 | FAM171A2
131177 | FAM3D
131583 | FAM43A
55603 | FAM46A
2192 | FBLN1
2217 | FCGRT
387758 | FIBIN
1112 | FOXN3
2548 | GAA
2593 | GAMT
9615 | GDA
54857 | GDPD2
124975 | GGT6
2697 | GJA1
2752 | GLUL
10457 | GPNMB
7107 | GPR137B
2861 | GPR37
283120 | H19
10014 | HDAC5
84525 | HOPX
3248 | HPGD
374875 | HSD11B1L
3315 | HSPB1
5654 | HTRA1
402778 | IFITM10
3481 | IGF2
3488 | IGFBP5
146433 | IL34
8850 | KAT2B
23254 | KAZN
3868 | KRT16
342574 | KRT27
3850 | KRT3
10536 | LEPREL2
29094 | LGALSL
10161 | LPAR6
22859 | LPHN1
10234 | LRRC17
66004 | LYNX1
137797 | LYPD2
130576 | LYPD6B
4094 | MAF
4118 | MAL
84557 | MAP1LC3A
4147 | MATN2
4211 | MEIS1
84709 | MGARP
26002 | MOXD1
196264 | MPZL3
4477 | MSMB
4488 | MSX2
143662 | MUC15
394263 | MUC21
79784 | MYH14
29116 | MYLIP
25791 | NGEF
2831 | NPBWR1
80896 | NPL
4883 | NPR3
1728 | NQO1
9315 | NREP
440836 | ODF3B
93145 | OLFM2
93129 | ORAI3
29943 | PADI1
5064 | PALM
89932 | PAPLN
54852 | PAQR5
5087 | PBX1
57326 | PBXIP1
5152 | PDE9A
5164 | PDK2
64065 | PERP
93210 | PGAP3
57115 | PGLYRP4
55022 | PID1
113791 | PIK3IP1
5570 | PKIB
10957 | PNRC1
5439 | POLR2J3
151742 | PPM1L
89801 | PPP1R3F
83886 | PRSS27
8000 | PSCA
442213 | PTCHD4
5764 | PTN
10966 | RAB40B
10267 | RAMP1
51195 | RAPGEFL1
56963 | RGMA
58480 | RHOU
727800 | RNF208
80352 | RNF39
6092 | ROBO2
6095 | RORA
6338 | SCNN1B
9037 | SEMA5A
80031 | SEMA6D
89778 | SERPINB11
26470 | SEZ6L2
90525 | SHF
6565 | SLC15A2
51310 | SLC22A17
63027 | SLC22A23
79085 | SLC25A23
146802 | SLC47A2
23428 | SLC7A8
285195 | SLC9A9
57152 | SLURP1
10924 | SMPDL3A
8470 | SORBS2
55553 | SOX6
6678 | SPARC
11005 | SPINK5
84651 | SPINK7
10417 | SPON2
6707 | SPRR3
55304 | SPTLC3
222183 | SRRM3
55959 | SULF2
9145 | SYNGR1
6920 | TCEA3
6948 | TCN2
7045 | TGFBI
7077 | TIMP2
257000 | TINCR
7089 | TLE2
7100 | TLR5
7108 | TM7SF2
55273 | TMEM100
51754 | TMEM8B
84000 | TMPRSS13
94241 | TP53INP1
58476 | TP53INP2
79090 | TRAPPC6A
55521 | TRIM36
1831 | TSC22D3
25809 | TTLL1
10628 | TXNIP
10791 | VAMP5
57216 | VANGL2
10451 | VAV3
5212 | VIT
155382 | VPS37D
64856 | VWA1
65268 | WNK2
54361 | WNT4
83719 | YPEL3
201501 | ZBTB7C
140467 | ZNF358
168544 | ZNF467
4582 | MUC1
4585 | MUC4
94025 | MUC16
192666 | KRT24
3859 | KRT12
9518 | GDF15
655 | BMP7
2296 | FOXC1
9314 | KLF4
3490 | IGFBP7
3486 | IGFBP3

* **Parent term(s)**
biological_process

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
 differentiation of corneal epithelial cells

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Hi @Mingsenli 

Welcome to the GO project! Before we go ahead and create this term, would you please fill the form here: 
https://github.com/geneontology/helpdesk/issues/new?assignees=&labels=&template=new-member-onboarding.md&title=New+User+Onboarding

Also, have you had a chance to look at the GO annotation guidelines? This page could be useful: http://wiki.geneontology.org/index.php/Guide_to_GO_Evidence_Codes

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @Mingsenli 

Did you have a chance to look at the document above? 

Thanks, Pascale

**Comment by Mingsenli** [comment]
I have Filled out the above form

**Comment by pgaudet** [comment]
Hi @raymond91125 Would you please look into this? 

If this process is in scope, pleas use the standard definitions; usually differentiation and homeostasis are not part of the same process. 

Thanks, Pascale

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160122
+name: corneal epithelial cell differentiation
+namespace: biological_process
+def: "The process in which a relatively unspecialized cell acquires specialized features of an corneal epithelial cell, any of the cells making up an corneal epithelium." [PMID:32697979, PMID:33414365]
+is_a: GO:0030855 ! epithelial cell differentiation
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/22991" xsd:anyURI
+created_by: rynl
+creation_date: 2023-10-30T18:58:42Z
