### ISSUE TITLE
Missing parent:  GO:0017183 peptidyl-diphthamide biosynthetic process from peptidyl-histidine

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#22999]
* **GO term ID and label for which you request a new superclass**
GO:0017183 peptidyl-diphthamide biosynthetic process from peptidyl-histidine

* **New superclass (parent) suggested**

GO:0006547 histidine metabolic process

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by pgaudet** [comment]
This would not bee right, as it doesn't happen on the free histidine.
