### ISSUE TITLE
NTR: oxidoreductase activity, with an iron-sulfur protein as acceptor 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#23001]
I wonder if I should suggest new terms based on the papers I'm annotating, but I need some chemistry help. 

In diphthamide biosynthesis. 

DPH1/2 is a catalytic enzyme that contains [4Fe-4S]2+ clusters
For catalytic activity the catalytic cluster must be reduced to [4Fe-4S]1+
Additionally, in aerobic environment the cluster(s) degenerate to 3Fe-4S

DPH3 + CBR1 + NADH serves to regenerate and reduce the cluster. 
DPH3 (aka KTI11) contains Fe that is donated to degenerated clusters pmid:34154323
The DPH3 + CBR1 + NADH  system also reduces the catalytic cluster pmid:24422557
CBR1 reduces DPH3 using NADH PMID:27694803

I wonder if I can go more specific for DPH3 then "oxidoreductase activity" based on pmid:24422557 and pmid:34154323
how about cbr1?

cbr1- annotated to GO:0003954 NADH dehydrogenase activity 
how about GO:0016723 oxidoreductase activity, acting on metal ions, NAD or NADP as acceptor?

DPH3 - do I need a new term? oxidoreductase activity, with an iron-sulfur protein as acceptor 
acting on what?
EC 1.6.7.-??

Thank you

**Comment by hdrabkin** [comment]
Perhaps @kaxelsen can help here? Does RHEA have anything? This might be a  little out of my depth

**Comment by deustp01** [comment]
Rhea does indeed have something, [RHEA:36783](https://www.rhea-db.org/rhea/36783). It looks to me like, in describing the overall reaction they have managed to evade the molecular details of the dancing iron atoms. Would it be appropriate to follow their lead here and say that, since proteins can be identified and associated with overall functions that they enable, that is already sufficient for GO annotation purposes. Also, I'm pretty sure that the mechanism with the dancing iron atoms is the only mechanism that is known for this reaction, so there is no need for mechanism-aware GO terms to distinguish alternative versions of the function (contrast with, e.g., hydrolysis of peptide bonds where serine proteases and metalloproteases work in very different ways and annotating the differences is useful).

**Comment by Antonialock** [comment]
@deustp01 so I would annotate CBR1+DPH3 to:
RHEA:36783 &
2-(3-amino-3-carboxypropyl)histidine synthase activity (qualifier: contributes_to)
? 

Thanks

yes would be great to also hear from @kaxelsen

**Comment by Antonialock** [comment]
Also, CBR1 is additionally believed to serve as the reductase for ELP3 in the first step of  wobble uridine biosynthesis. Wuuld this mean I should also annotate CBR1 to the elp3 function
GO:0106261 tRNA uridine(34) acetyltransferase activity  ?

**Comment by Antonialock** [comment]
Hello, so I had help from Kristian and Elisabeth on this. 

I have been advised to annotate  (yeast) CBR1 to
 RHEA:71231 2 Fe3+-[Dph3] + NADH = 2 Fe2+-[Dph3] + H+ + NAD+
 

DPH3:
The reactions involving Dph3 are for electron transfer:
RHEA:71235 [3Fe-4S]1+-[protein] + Fe2+-[Dph3] = [3Fe-4S]0-[protein] + Fe3+-[Dph3]

 Fe-atom transfer
 RHEA:71239 2 [3Fe-4S]0-[protein] + 2 Fe2+-[Dph3] + NADH = 2
 [4Fe-4S]1+-[protein] + 2 [Dph3] + H+ + NAD+


 > As you will note, I have also include NADH in RHEA:71239. This is because I
 > have based the reactions on the model shown in pmid:34154323 Fig. 4, and
 > according to that model Dph3 donates both the Fe-atom AND an electron, and
 > that is a little difficult to do. So instead of using two Fe2+-[Dph3] where
 > one donated the Fe-atom and the other an electron, I used NADH to arrive at
 > the [4Fe-4S]1+ cluster. I find this results in a simpler reaction. I am aware
 > that eEF2 and AdoMet should be present for RHEA:71239 to take place, but that
 > is not possible to include in the reaction, but can be described in the
 > Swiss-Prot entry.

**Comment by hdrabkin** [comment]
So is a new term needed or can I close this ticket?

**Comment by hdrabkin** [comment]
Seem to need a generic term. The RHEA:71231 appears to be actually the same reaction as RHEA:46680, differing in only which protein has the iron bound to it. In fact, 71231 does indicate the iron /amino acid residue, whereas 46680 does not. 
But in each case Fe3 + NADH = Fe2 + NAD + H

**Comment by hdrabkin** [comment]
![Screen Shot 2022-08-17 at 9 58 01 AM](https://user-images.githubusercontent.com/10440080/185153531-1f99eb60-713e-4300-a0d4-e1fff7c9cff7.png)
![Screen Shot 2022-08-17 at 9 57 52 AM](https://user-images.githubusercontent.com/10440080/185153535-da2a9b41-0590-4b13-a9b5-7b2d2dde81e6.png)

**Comment by hdrabkin** [comment]
RHEA:71231 does not reference an EC whereas 46880 references  EC 1.6.2.2 cytochrome-b5 reductase
GO has GO:0004128m with this EC and the RHEA:46880

**Comment by hdrabkin** [comment]
RHEA:71231 currently does not have a GO mapping, 
RHEA:71235 also has no GO mapping
RHEA:71239  also no GO mapping

**Comment by Antonialock** [comment]
I annotated to DPH3 and CBR1 to GO:0090560 2-(3-amino-3-carboxypropyl)histidine synthase activity. I couldn't add the contribute_to qualifier since P2GO complained there's no complex annotation but hope that is ok. I think for my purposes this ticket can close.

**Comment by hdrabkin** [comment]
Thanks, @Antonialock;
