### ISSUE TITLE
NTR: regulation of proteoglycan catabolic process

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#23005]
Please provide as much information as you can: 

* **Suggested term label:**

1. regulation of proteoglycan catabolic process
2. positive regulation of proteoglycan catabolic proces
3. negative regulation of proteoglycan catabolic process 

* **Definition (free text)**

1. Any process that modulates the rate, frequency, or extent of the chemical reactions and pathways resulting in the breakdown of proteoglycans, any glycoprotein in which the carbohydrate units are glycosaminoglycans.
2. Any process that activates or increases the frequency, rate or extent of the chemical reactions and pathways resulting in the breakdown of proteoglycans, any glycoprotein in which the carbohydrate units are glycosaminoglycans.
3. Any process that decreases the rate, frequency, or extent of the chemical reactions and pathways resulting in the breakdown of proteoglycans, any glycoprotein in which the carbohydrate units are glycosaminoglycans. 

* **Reference, in format PMID:#######**

PMID:32083858 and PMID:32484067

* **Gene product name and ID to be annotated to this term**

Btk/Bruton tyrosine kinase RGD:1359683

* **Parent term(s)**

"proteoglycan catabolic process” (GO:0030167)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Hi @slaulederkind 

I dont see evidence that the proteoglycans are degraded; just that the levels are lower (for example, they could be excreted?)
Also, it looks like proteoglycan loss is a way to assess inflammation and auto-immune induced arthritis, see also https://arthritis-research.biomedcentral.com/articles/10.1186/s13075-020-02219-7

How about annotating to GO:0006954 inflammatory response instead?

Thanks, Pascale

**Comment by slaulederkind** [comment]
Hi @pgaudet, We''ll annotate with something else.  We won't need the proteoglycan terms.  Thanks, Stan
