### ISSUE TITLE
NTR: positive regulation of lncRNA catabolic process

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#23018]
Please provide as much information as you can: 

* **Suggested term label:**positive regulation of lncRNA catabolic process

alternatively is GO:0035195 miRNA-mediated gene silencing sufficient?

* **Definition (free text)**
Any process that activates or increases the frequency, rate or extent of lncRNA catabolic process.

* **Reference, in format PMID:#######** PMID:34454184

* **Gene product name and ID to be annotated to this term** Homo-sapiens hsa-miR-665 URS0000355E82_9606
* **Parent term(s)**
* positive regulation child of GO:0110064 lncRNA catabolic process
* is a child of GO:0051254 positive regulation of RNA metabolic process (should there be the more specific term positive regulation of RNA catabolic process?)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
* EXACT: positive regulation of long noncoding RNA catabolic process
* EXACT: positive regulation of long non-coding RNA catabolic process
* EXACT: positive regulation of lncRNA breakdown
* EXACT: positive regulation of lncRNA degradation
* EXACT: positive regulation of lncRNA catabolism

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
MIAT is a lncRNA and the binding by/of the hsa-miR-665 leads to degradation of both MIAT and hsa-miR-665. However, in theory we view the lncRNA as acting as a sponge it is just that it is destroyed in the process of destroying the miR. But it would be useful to include.

Or should GO:0035195 miRNA-mediated gene silencing be used instead?

Thanks
Ruth

**Comment by pgaudet** [comment]
Why is the a regulation? It seems like some sort of adaptor. Unfortunately I dont have access to the paper, can you email it? 

Thanks, Pascale

**Comment by RLovering** [comment]
I think we need this term to enable consistent annotation of miRs that cause the catabolism of lncRNAs. The miR is not an enzyme so it must be regulating the process rather than contributing to it?

Also see PMID: 31545249: The results of the GAS5 luciferase reporter in dual-luciferase
reporter assays show that transfection of miR-135a mimics, but not a control sequence, significantly reduced the luciferase activity of GAS5-WT (Fig 5B). The  RIP assay to confirm the endogenous correlation
between GAS5 and miR-135a and showed a substantial enrichment of GAS5 in the presence of miR-135a mimics in macrophages (Fig 5C).

**Comment by pgaudet** [comment]
After discussion with @RLovering and @gantonazzo we will not implement this as it represents the consequence of the miRNA being destructed, and we already capture lncRNA being the target of the miRNA.
