### ISSUE TITLE
remove parent from  GO:0140764 small RNA binding translational repressor activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#23021]
GO:0140764 small RNA binding translational repressor activity has the definition:
A translational repressor activity that binds to a single-stranded small regulatory RNA (either a miRNA or a siRNA) to guide it to its target mRNA. 

and the Comments: This term is intended for activities such as that mediated by argonaute in the RISC complex, that bring a miRNA or an siRNA to their target mRNA.

- [ ] Agonaute does not base-pair with the small RNA therefore it should not have the is a parent term:
GO:1903231 mRNA base-pairing post-transcriptional repressor activity

Definition: A translation repressor activity that acts by base-pairing with an mRNA. The binding can result in targeting the mRNA for degradation or interfering with mRNA translation, hence resulting in posttranscriptional gene silencing. 

Comments: This term is indended for microRNAs that act by base-pairing with a target mRNA.
Probably the is_a parent should be: GO:0030371 translation repressor activity

Thanks

Ruth

**Comment by pgaudet** [comment]
Thanks for pointing this out. In fact this was caused be the logical definition of 'GO:1903231 mRNA base-pairing post-transcriptional repressor activity', that was 

 is_a: GO:0003729 ! mRNA binding
-intersection_of: GO:0030371 ! translation repressor activity
-intersection_of: part_of GO:0016441 ! post-transcriptional gene silencing

we would need a MF 'binding by base pairing' to be able to logically define these terms (would this be a useful term?) 

Thanks, Pascale

**Comment by RLovering** [comment]
interesting I have always felt that the word 'binding' is a bit weird because it is more like annealing and not the same as protein binding, or RNA-protein binding of RNA-protein binding so I would like the idea of creating a term 'binding by base pairing'
