### ISSUE TITLE
Are more terms needed to describe role of lncRNAs?

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#23028]
**Edited to add proposed annotations for each lncRNA**

In progress - Hi

Figure 2 of PMID:31048766  describes 13 functions of lncRNAs. If the MFs for these RNAs are not available then other terms will be used that are perhaps not appropriate or no MF will be assigned.
Based on figure 2 I have tried to find MF terms that could be used for each description and noted the missing terms below.
Also to work out how many of these different roles would be captured with the same GO terms and which would use different terms and perhaps need NTRs.

- b, Xist modulates inactive X chromosome (Xi) architecture during X chromosome inactivation (XCI) by recruiting Xi to associate with the lamin B receptor (LBR) at the nuclear lamina to silence transcription. 
> As human XIST URS000025784F_9606 had no annotations I have used this review to create some TAS annotations PMID: 32482714 (MF: chromatin-protein adaptor part_of BP: inactivation of X chromosome by heterochromatin assembly, CC dosage compensation complex), 
> but maybe need NTRs: nuclear matrix binding? Is the MF: chromatin-protein adaptor appropraite or is a more specific term required (Check with transcription working group). 

**Proposed annotations:** 
MF: GO:0140707 chromatin-nuclear membrane anchor activity
BF: GO:0060820 inactivation of X chromosome by heterochromatin formation

----

- b2 The review also points to nuclear elements (LINEs), may act to decompact chromatin on x-inactivated chromosome suggesting a positive role in chromatin opening[38] seePMID: 34722514 chromatin-associated RNA (caRNA) encompasses a wide variety of specific RNAs such as short nuclear/nucleolar (snRNA/snoRNA) and long non-coding RNA (lncRNA) and newly transcribed mRNA. While their specific action mechanism is mostly unknown, it is now generally believed that they act in combination with RNA-binding proteins (RBP) and histone modifying proteins such as, for example, the Suppressor of Variegation 3–9 (SUV39), Polycomb Repressor complex (PRC1 and 2) and hNRNP-family protein to regulate gene expression and nuclear dynamics - emerging evidence of the role of repetitive RNA and repeat-containing repetitive motifs (i.e., genomic, simple/tandem containing repeats) in the organization of chromatin and the regulation of gene expression.

**No proposed MF annotation:** 
Since the specific action is unknown, all we can do is annotate to the process (chromatin remodeling or a child). 

----

- c, Firre transcripts localize to their transcription site and five additional autosomal chromosomal loci in trans to affect interactions between distant genomic regions. 

**Proposed annotations:** 
MF: GO:0106260  DNA-DNA tethering activity

----

- d, CCAT1-L accumulates in cis to modulate chromatin loops between enhancers and the promoter of MYC. 

**Proposed annotations:** 
MF: GO:0140585 promoter-enhancer loop anchoring activity

----

- e, lncRNAs regulate chromatin accessibility. Left, Xist recruits HDAC1-associated repressor protein (SHARP), silencing the mediator for retinoid and thyroid hormone receptor (SMART) and HDAC3 to silence Xi. Right, Mhrt prevents SWI/SNF binding to corresponding DNA loci.

**Proposed annotations:** 
GO:0030674 protein-macromolecule adaptor activity + appropriate inputs

----

- f, Khps1 enhances Pol II transcription by forming an R-loop that anchors Khps1-interacting p300/CBP to the SPHK1 promoter. 

**Proposed annotations:** 
- GO:0030674 protein-macromolecule adaptor activity + appropriate inputs

----

- g, lncRNAs interfere with Pol II transcription machineries both at the initiation (left) and elongation (right) stages. 
**Proposed:** 
 

- [x] Create new term, RNA polymerase inhibitor activity

----

- h, SLERT promotes Pol I transcription by binding DDX21 to alter its conformation, thereby releasing its inhibitory effect on Pol I. 
 
**Proposed:** 
- [x]  DDX21: NTR RNA polymerase inhibitor activity (see above)
- [x]   SLERT: NTR repressor of RNA polymerase inhibitor activity

----

- i, NEAT1 is an architectural lncRNA that nucleates paraspeckles. Upon cellular stress, altered NEAT1 transcription and processing lead to changes of paraspeckles. PSP, paraspeckle proteins. 

**Proposed:** 
GO:0140693 molecular condensate scaffold activity

 - [x] add synonym phase separation nucleation activity
 
----

- j, MALAT1 interacts with SR proteins and alters their phosphorylation to impact pre-mRNA splicing in splicing speckles. 
Text states "On the basis of these observations, it has been proposed that MALAT1 may function as a ‘scaffold’ to enhance protein–protein, protein–RNA and protein–DNA interactions within or near nuclear speckles"

**Proposed:** 
Since the mechanism is not known, cannot annotate MF

----

- k, A regulatory network consisting of different types of ncRNAs. Cyrano, harbouring miR-7 binding sites, targets miR-7 for degradation and prevents miR-7 from repressing its target RNAs including the circRNA Cdr1as.

**Proposed:** 
* Use new MF term GO:0140869 miRNA inhibitor activity 
* BP: GO:0000512 lncRNA-mediated post-transcriptional gene silencing 

----

- l, lncRNAs modulate mRNA stability by associating with proteins involved in mRNA degradation. Left, double-stranded RNAs formed by Alu-containing lncRNAs with mRNA 3′ UTRs recruit STAU1 to induce STAU1-mediated mRNA decay (SMD). Right, NORAD stabilizes PUMILIO 1/2 (PUM1/2)-targeted mRNAs via sequestering PUM1/2 from mRNAs. 

**Proposed:** 
* MF: GO:1903231 mRNA base-pairing translational repressor activity
* BP: GO:0000512 lncRNA-mediated post-transcriptional gene silencing 

----

- m, lncRNAs regulate translation. Association of lincRNA-p21 (linc-p21) with HuR favours the recruitment of let-7/Ago2, leading to its destabilization. In the absence of HuR, lincRNA-p21 identifies mRNA targets to repress their translation by recruiting the translation repressor Rck[129](https://www.nature.com/articles/s41556-019-0311-8#ref-CR129). RISC, RNA-induced silencing complex. 

**Proposed:** 
* MF: GO:1903231 mRNA base-pairing translational repressor activity
* BP: GO:0000512 lncRNA-mediated post-transcriptional gene silencing 

----

- n, lncRNAs modulate post-translational modifications. Lnc-DC directly interacts with STAT3 to prevent its dephosphorylation by SHP1.
-  GO:0019212 phosphatase inhibitor activity and/or GO:0140311 protein sequestering activity

**Comment by pgaudet** [comment]
I've added this to the next miRNA call

**Comment by hattrill** [comment]
tagging @gantonazzo and @ValWood as well

**Comment by RLovering** [comment]
OK I have only just started trying to look at this and problably many of you have a better idea of what terms are needed, maybe I should stop trying to do the whole list and leave each of you to add a comment for each type. If I create a new conversation section for each set then everyone could edit the actual text? Or would it be better to do this in a google doc?
@colinlog

**Comment by RLovering** [comment]
**LncRNAs with a role in Chromatin organisation** 

    b, Xist modulates inactive X chromosome (Xi) architecture during X chromosome inactivation (XCI) by recruiting Xi to associate with the lamin B receptor (LBR) at the nuclear lamina to silence transcription.

    As human XIST URS000025784F_9606 had no annotations I have used this review to create some TAS annotations PMID: 32482714 (MF: chromatin-protein adaptor part_of BP: inactivation of X chromosome by heterochromatin assembly, CC dosage compensation complex),
    but maybe need NTRs: nuclear matrix binding? Is the MF: chromatin-protein adaptor appropraite or is a more specific term required (Check with transcription working group).

    b2 The review also points to nuclear elements (LINEs), may act to decompact chromatin on x-inactivated chromosome suggesting a positive role in chromatin opening[38] seePMID: 34722514 chromatin-associated RNA (caRNA) encompasses a wide variety of specific RNAs such as short nuclear/nucleolar (snRNA/snoRNA) and long non-coding RNA (lncRNA) and newly transcribed mRNA. While their specific action mechanism is mostly unknown, it is now generally believed that they act in combination with RNA-binding proteins (RBP) and histone modifying proteins such as, for example, the Suppressor of Variegation 3–9 (SUV39), Polycomb Repressor complex (PRC1 and 2) and hNRNP-family protein to regulate gene expression and nuclear dynamics - emerging evidence of the role of repetitive RNA and repeat-containing repetitive motifs (i.e., genomic, simple/tandem containing repeats) in the organization of chromatin and the regulation of gene expression.

    c, Firre transcripts localize to their transcription site and five additional autosomal chromosomal loci in trans to affect interactions between distant genomic regions.

    d, CCAT1-L accumulates in cis to modulate chromatin loops between enhancers and the promoter of MYC.

**Comment by hattrill** [comment]
That sounds like a good idea, then we can collect examples as we go.

**Comment by RLovering** [comment]
**LncRNAs with a role in transcription**

- e, lncRNAs regulate chromatin accessibility. Left, Xist recruits HDAC1-associated repressor protein (SHARP), silencing the mediator for retinoid and thyroid hormone receptor (SMART) and HDAC3 to silence Xi. Right, Mhrt prevents SWI/SNF binding to corresponding DNA loci.

- f, Khps1 enhances Pol II transcription by forming an R-loop that anchors Khps1-interacting p300/CBP to the SPHK1 promoter.

- g, lncRNAs interfere with Pol II transcription machineries both at the initiation (left) and elongation (right) stages.

- h, SLERT promotes Pol I transcription by binding DDX21 to alter its conformation, thereby releasing its inhibitory effect on Pol I. *i, NEAT1 is an architectural lncRNA that nucleates paraspeckles. Upon cellular stress, altered NEAT1 transcription and processing lead to changes of paraspeckles. PSP, paraspeckle proteins.

**Comment by RLovering** [comment]
**LncRNAs with a role in post-transcription**


- i, NEAT1 is an architectural lncRNA that nucleates paraspeckles. Upon cellular stress, altered NEAT1 transcription and processing lead to changes of paraspeckles. PSP, paraspeckle proteins. 

- j, MALAT1 interacts with SR proteins and alters their phosphorylation to impact pre-mRNA splicing in splicing speckles. k, A regulatory network consisting of different types of ncRNAs. Cyrano, harbouring miR-7 binding sites, targets miR-7 for degradation and prevents miR-7 from repressing its target RNAs including the circRNA Cdr1as.

- l, lncRNAs modulate mRNA stability by associating with proteins involved in mRNA degradation. Left, double-stranded RNAs formed by Alu-containing lncRNAs with mRNA 3′ UTRs recruit STAU1 to induce STAU1-mediated mRNA decay (SMD). Right, NORAD stabilizes PUMILIO 1/2 (PUM1/2)-targeted mRNAs via sequestering PUM1/2 from mRNAs. 

- m, lncRNAs regulate translation. Association of lincRNA-p21 (linc-p21) with HuR favours the recruitment of let-7/Ago2, leading to its destabilization. In the absence of HuR, lincRNA-p21 identifies mRNA targets to repress their translation by recruiting the translation repressor Rck[129](https://www.nature.com/articles/s41556-019-0311-8#ref-CR129). RISC, RNA-induced silencing complex. 

- n, lncRNAs modulate post-translational modifications. Lnc-DC directly interacts with STAT3 to prevent its dephosphorylation by SHP1.

**Comment by hattrill** [comment]
Just trying to list other ways in which we can distinguish activities - not mutually exclusive, but to help thinking about it all as from Ruth's list, their activities seem almost as diverse as protein's are....

- Acting in cis (ie when their transcription interferes with a neighboring gene) or in trans (at distance)
- Nuclear and cytosolic
- Interaction target
- Molecular interaction - base pairing, displacement (?), competition, protein recruitment.....etc

**Comment by colinlog** [comment]
Interesting gene regulatory topic these LncRNAs. Glad that S.pombe also has the protein, makes me believe the whole more...  

My take has been that each of these LncRNAs has its own story to tell and the whole is rather idiosyncratic. 
Xist, Hotair, SRA, etc..  are much studied RNAs, a lot of hot attention has gone to a polycomb H3K27methylation theory, but again, not easy to model or understand...   

In addition there is also a ribosomal promoter DNA-RNA basepair phenomenon -- initially by Ingrid GRummt that cannot be dismissed as an artefact. 

Still, to my knowledge no-one could biochemically reconstitute what they do, what the molecular activities really are? The sponge activities are perhaps the best documented? Furthermore there are 'regulators of the regulators'. For instance, Xist has an antogonist TSIX...   

Ultimately, there are proteins involved, so those may bear the specific biochemical-molecular function (bind RNA and then do ...), whilst the RNAs have more of an adaptor-target specifying role?

**Comment by colinlog** [comment]
> OK I have only just started trying to look at this and problably many of you have a better idea of what terms are needed, maybe I should stop trying to do the whole list and leave each of you to add a comment for each type. If I create a new conversation section for each set then everyone could edit the actual text? Or would it be better to do this in a google doc? I think there are 3 main areas covered in Fig 2 LncRNAs with a role in Chromatin organisation, LncRNAs with a role in transcription, LncRNAs with a role post-transcriptionally @colinlog

Yes @RLovering , I see much sense in your proposal for organizing the process regulation aspects by LncRNAs in terms of (i) regulation - induction of chromatin organisation / histone or DNA modification  (ii) regulation of transcription with of course iia initiation, iib elongation iic termination of transcription and (iii) the post-transcriptional pathways, that modulate iiia RNA splicing, iiib RNA stability, iiic RNA nuclear localisation export/re-import or iiid translation by ribosomes.   I think then that the STAT3 example would be a (iia) type regulation. Xist a (i) type, and teh Lnc-p21 example iiid. The trick being to have product oriented definitions and logic for the BPs and RNA molecule or RNA binding protein activity-centered definitions for the MFs, so . Most of this is already in place for proteins, isn't it?

@hattrill  The cell components, are where it happens, rather than activities? "This MF for that BP in this CC" and in GO-CAMS this RNA MF has + or - effect on the next bioentity's MF

**Comment by pgaudet** [comment]
+id: GO:0140870
+name: RNA polymerase inhibitor activity
+namespace: molecular_function
+def: "Binds to and stops, prevents or reduces the activity of RNA polymerase." [PMID:15300239, PMID:18313387, PMID:31048766]
+is_a: GO:0004857 ! enzyme inhibitor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23028 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-04T14:26:28Z
+
+[Term]
+id: GO:0140871
+name: repressor of RNA polymerase inhibitor activity
+namespace: molecular_function
+def: "Binds to and stops, prevents or reduces the activity of an RNA polymerase inhibitor." [PMID:28475895, PMID:31048766]
+is_a: GO:0004857 ! enzyme inhibitor activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23028 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-04T14:26:28Z

**Comment by sjm41** [comment]
@pgaudet For "repressor of RNA polymerase inhibitor activity", should the parent be changed to "enzyme activator activity", given the activity is repressing an inhibitor of an RNApol?

**Comment by colinlog** [comment]
I would go for a regulator of activity annotation for some Lnc (if convincingly demonstrated) but not inhibitor of enzyme activity when RNA polymerase II is concerned since there are many functions that can lead to less or more transcription of a gene (rate/frequency of intiation, processivity of elongation, etc, etc.) The exception would be if the active site of the polymerase is contacted.   So, global BP annotation to transcription regulator [***GO:0006355 
regulation of DNA-templated transcription***] if that is demonstrated.   Possibly with a DNA cis-acting element binding has_part [***GO:0000978] RNA polymerase II cis-regulatory region sequence-specific DNA binding***], if that is demonstrated. Often I would imagine that an annotation to an epigenetic process + (positive regulator eg; [***GO:0045815	biological_process	epigenetic maintenance of chromatin in transcription-competent conformation***] or - (negative regulator eg; [***GO:0045814 biological_process negative regulation of gene expression, epigenetic***] or its descendant term (eg [***GO:0031507	biological_process heterochromatin formation***], or one of it's more defined descendant terms if more is known.
