### ISSUE TITLE
use Sequence Ontology for RNA terms (was : Use RNACentral ontology for RNA terms)

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#23060]
I think we should look at the RNA central index on the side of this page https://rnacentral.org/search?q=RNA and use some of these terms and the ontology structure eg in RNAcentral [sncRNA (6,493,737)](https://rnacentral.org/) has tRNAs as child terms where as [small regulatory ncRNA (557,293)](https://rnacentral.org/) has miRNA, siRNA, piRNA and tmRNA child terms
small regulatory ncRNA seems like a good grouping term to me

**Comment by sjm41** [comment]
Hi @RLovering 
The index/ontology at the top left of the RNAcentral search page is just a representation of Sequence Ontology terms, mostly those under ncRNA ([SO:0000655](http://sequenceontology.org/browser/current_svn/term/SO:0000655)).
Note that the 'sncRNA' grouping term is slated for deletion following discussions within RNAcentral (https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/572), though the 'small regulatory ncRNA' grouping should persist.


Steven.

**Comment by blakesweeney** [comment]
Just to follow up a little more on what the SO terms in RNAcentral, I should point it it is a slighly modified version of sequence ontology. We hide a few intermediate nodes, eg there are several nodes between transcript and pre-miRNA  which we hide, as well as moving some nodes around to be easier to find. This is done to try and make things easier to use.

**Comment by RLovering** [comment]
I should have thought that SO would be a useful ontology for GO to align to. Good to know that sncRNA is going to go and that 'small regulatory ncRNA' will stay - I think for GO this will be very useful
