### ISSUE TITLE
NTR: [L-glutamate:proton antiporter activity]

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#23075]
Please provide as much information as you can: 

* **Suggested term label:**
L-glutamate:proton antiporter activity

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: L-glutamate(out) + H+(in) = L-glutamate(in) + H+(out). 

* **Reference, in format PMID:#######**
PubMed=29273736

* **Gene product name and ID to be annotated to this term**
Slc17a7

* **Parent term(s)**
GO:0015299 solute:proton antiporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106421
+name: L-glutamate:proton antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: L-glutamate(out) + H+(in) = L-glutamate(in) + H+(out)." [PMID:29273736]
+is_a: GO:0015299 ! solute:proton antiporter activity
+intersection_of: GO:0015297 ! antiporter activity
+intersection_of: has_primary_input CHEBI:24636 ! proton
+intersection_of: has_primary_input CHEBI:29985 ! L-glutamate(1-)
+property_value: creation_date 2022-04-01T20:09:58Z xsd:dateTime
