### ISSUE TITLE
protein disaggregase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23088]
ntr: protein-unfoldase activity

definition
An ATP-dependent molecular chaperone activity that mediates the solubilization of protein substrates.

see cdc48 summary
https://www.yeastgenome.org/locus/YDL126C

**Comment by ValWood** [comment]
here is a reference
 VCP/p97-Mediated Unfolding as a Principle in Protein Homeostasis and Signaling
PMID: 29153394

Similarly, p97 can harness unfolding to distort the interfaces between client proteins and their binding partners to trigger dissociation. 

ts molecular function is ATP-driven protein unfolding, which is directed by ubiquitin and assisted by a host of cofactor proteins. This activity underlies p97’s diverse ability to pull proteins out of membranes, unfold proteins for proteasomal degradation, or segregate proteins from partners for downstream activity.


"p97 Is an Unfolding Machine
The different cellular functions of p97 imply distinct conceptual demands for p97. However, all p97 activities can be explained in principle by an unfolding enzyme that uses pulling force to break up the tertiary and, to a certain extent, also the secondary structure of its client proteins ([Prakash and Matouschek, 2004](https://www.cell.com/molecular-cell/fulltext/S1097-2765(17)30805-5?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS1097276517308055%3Fshowall%3Dtrue#bib84)). This mechanism can pull proteins out of membranes during ERAD, but can also be employed for global protein unfolding in preparation for proteasomal degradation. Similarly, p97 can harness unfolding to distort the interfaces between client proteins and their binding partners to trigger dissociation. Over the past years, the underlying molecular mechanism of p97-mediated unfolding has been controversially discussed."

**Comment by ValWood** [comment]
actually, these are different.

disaggregase is soluabalization of an aggregate, this is soulablization of a protein, I will edit

**Comment by ValWood** [comment]
The paper I am approving PMID:35320724 also provides these refs

"Cdc48 has an N-termi-nal domain, two tandem ATPase domains (D1 and D2), and an unstructured C-terminal tail. In the hexameric complex, D1 and D2 form a double-ring structure with a central pore through which substrates can be threaded, which unfolds the polypep- tide (Banerjee et al., 2016; Bodnar and Rapoport, 2017; Cooney et al., 2019; Ji et al., 2021; Twomey et al., 2019)"

**Comment by pgaudet** [comment]
Hi @ValWood 

Does this new term I created last week work ? 
protein-containing complex destabilizing activity, see https://github.com/geneontology/go-ontology/issues/23065#issuecomment-1076352973

I can add synonyms.

**Comment by ValWood** [comment]
It is slightly different. Although "destabilizing activity" is another function of cdc48 (it specifically extracts ubiquitinated substrates from binding partners) before it unfolds them.

The authors of this paper call this activity "a segregase activity"
Central to the function of Cdc48 is its role as a segregase. Cdc48 separates ubiquitinated targets from their non-modified binding partners or from cellular structures (Stolz et al., 2011; Ye et al., 2017). For example, p97Ufd1/Npl4 extracts ubiquitinated Aurora B kinase from chromatin at mitotic exit to promote chro- matin decondensation and nuclear envelope reformation (Ramadan et al., 2007), and yeast Cdc48 mobilizes the transcrip- tion factors Mga2 and Spt23 from the endoplasmic reticulum membrane (Rape et al., 2001; Shcherbik and Haines, 2007).

I would therefore add 
"ubiquitnated protein segregate" as a narrow synonym of  +name: protein-containing complex destabilizing activity

The aforementioned "unfoldase" is a separate activity that occurs after "extraction" by threading the protein through a central pore.

I guess these two activities could be combined in some way, but only if all unfoldases are destabilizers and vice versa.

One is defined as destabilizing a complex (extraction), the second as destabilizing a individual  protein (unfolding), once it is extracted.

It seems to be an important distinction because the extraction may not result in degradation (especially in the context of actin etc) where the extracted protens are recycled, but not unfolded.

**Comment by pgaudet** [comment]
In fact, I had created protein disaggregase activity here: #19173

I now changed the label to 'ATP-dependent protein disaggregase activity', and added 'protein unfoldase activity' to 'ATP-dependent protein disaggregase activity' and to 'protein-containing complex destabilizing activity'. 


Does this address the issue? 

Thanks, Pascale

**Comment by ValWood** [comment]
remember that the 'protein-containing complex destabilizing activity'  was to be a parent for the severing  (If I remember correctly, this isn't in QuickGO yet), and this isn't 'unfolding' the  subunits don't unfold, the polymers are severed into smaller parrtts. So  'protein unfoldase activity' does not work as a synonym for this term.

**Comment by pgaudet** [comment]
I think this is done - see comment above
https://github.com/geneontology/go-ontology/issues/23088#issuecomment-1082712628
