### ISSUE TITLE
NTR: plastid gene expression

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#23083]
Please provide as much information as you can: 

This is something more of a question before seeing if we need the actual term. Is there some other combination of term and extension that is preferred?

* **Suggested term label:**
plastid gene expression

* **Definition (free text)**
~The process in which a plastid encoded gene's sequence is converted into a mature gene product or products (proteins or RNA). This includes the production of an RNA transcript as well as any processing to produce a mature RNA product or an mRNA or circRNA (for protein-coding genes) and the translation of that mRNA or circRNA into protein. Protein maturation is included when required to form an active form of a product from an inactive precursor form~

To match the definition of mitochondrial gene expression, the definition should be: 
"The process in which a platid gene's sequence is converted into a mature gene product or products (proteins or RNA). This includes the production of an RNA transcript as well as any processing to produce a mature RNA product or an mRNA or circRNA (for protein-coding genes) and the translation of that mRNA or circRNA into protein. Protein maturation is included when required to form an active form of a product from an inactive precursor form.

* **Reference, in format PMID:#######**

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
need new term for regulation of ....

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
Is this intentional- that is should we use a more generic regulation of gene expression WITH the location info in a NOCTUA type model>

* **Subsets**
* Add to goslim_plant
* Add to goslim_generic

**Comment by pgaudet** [comment]
We do have 'mitochondrial gene expression', we probably also should have 'plastid gene expression' 

@ValWood What do you think? I think you use 'mitochondrial gene expression' at least for slimming purposes? 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes,  'mitochondrial gene expression' is important for slimming and enrichment. It groups mitochondrial transcription, translation and RNA processing and these are a separate  "module"  from the perspective of pathways/phenotypes/interactions so it's an important biological distinction. The same would apply for plastids. The proposed 'plant slim' would likely require this term.

**Comment by pgaudet** [comment]
+id: GO:0140899
+name: plastid gene expression
+namespace: biological_process
+def: "The process in which a plastid gene's sequence is converted into a mature gene product or products (proteins or RNA). This includes the production of an RNA transcript as well as any processing to produce a mature RNA product or an mRNA or circRNA (for protein-coding genes) and the translation of that mRNA or circRNA into protein. Protein maturation is included when required to form an active form of a product from an inactive precursor form" [PMID:28377785]
+intersection_of: GO:0010467 ! gene expression
+intersection_of: occurs_in GO:0009536 ! plastid
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23083 xsd:anyURI
+created_by: pg
+creation_date: 2022-08-17T10:34:35Z
+
