### ISSUE TITLE
Obsoletion: [ GO:0030433 | ubiquitin-dependent ERAD pathway ]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23092]
* **GO term ID and label for which you request a new superclass**

I have annotated to  GO:0030433 | ubiquitin-dependent ERAD pathway | ISO with S000002284

but I am picking up a mapping to  GO:0071712 | ER-associated misfolded protein catabolic process

but GO:0030433 | ubiquitin-dependent ERAD pathway IS_A  ER-associated misfolded protein catabolic process
based on its definition:
The series of steps necessary to target endoplasmic reticulum (ER)-resident proteins for degradation by the cytoplasmic proteasome. Begins with recognition of the ER-resident protein, includes retrotranslocation (dislocation) of the protein from the ER to the cytosol, protein ubiquitination necessary for correct substrate transfer, transport of the protein to the proteasome, and ends with degradation of the protein by the cytoplasmic proteasome.

so it seems to be missing a superclass?

* **New superclass (parent) suggested**

**Comment by ValWood** [comment]
Actually, I think these terms are describing the same pathway. Although I'm not sure  that the pathway distinguishes between "misfolded" and other  Protein Quality Control issues.

**Comment by ValWood** [comment]
the refs for 
ER-associated misfolded protein catabolic process (GO:0071712)
both refer to ERAD

**Comment by ValWood** [comment]
I think so. The children of 
GO:0036503   ERAD pathway
are a bit confusing.

**Comment by ValWood** [comment]
GO:0030433 | ubiquitin-dependent ERAD pathway  
and GO:0036503  ERAD pathway
are also the same thing

<img width="459" alt="Screenshot 2023-11-15 at 11 45 31" src="https://github.com/geneontology/go-ontology/assets/7359272/e4d32a5d-a067-4bd0-921d-7d36a8c26e55">

**Comment by ValWood** [comment]
Also the child

GO:1904379    protein localization to cytosolic proteasome complex involved in ERAD pathway
[GO:1904379](https://www.ebi.ac.uk/QuickGO/term/GO:1904379)    protein localization to cytosolic proteasome complex involved in ERAD pathway

This is a phenotype (single EXP)

**Comment by ValWood** [comment]
- [ ] obsoletion notice
- [ ] GO friends e-mail
- [ ] annotation tracker tickets

**Comment by pfey03** [comment]
we had 4 ISS which I replaced with other terms

**Comment by ValWood** [comment]
The terms are  
GO:0071712 ER-associated misfolded protein catabolic process & regulation children
GO:0030433 ubiquitin-dependent ERAD pathway
GO:1904379 protein localization to cytosolic proteasome complex involved in ERAD pathway
