### ISSUE TITLE
go_plot.py usage help/issue

### ISSUE THREAD

**Issue by pan-genome** [geneontology/go-ontology#23108]
go_plot.py does not work for me. it gives unknown key error,  from the error log and and the relevant code section, it appears the one or more args are missing. I am not sure if it is expecting something more?

[ke@mxz061 data]$ ../scripts/go_plot.py GO:0003304 -o file.png
Traceback (most recent call last):
  File "../scripts/go_plot.py", line 16, in <module>
    run()
  File "../scripts/go_plot.py", line 12, in run
    PlotCli().cli()
  File "/sc/anaconda3/lib/python3.6/site-packages/goatools/cli/gosubdag_plot.py", line 169, in cli
    kws_all = self.get_docargs() if not kws_plt else kws_plt
  File "/sc/anaconda3/lib/python3.6/site-packages/goatools/cli/gosubdag_plot.py", line 277, in get_docargs
    docargs = self.objdoc.get_docargs(args, prt)
  File "/sc/anaconda3/lib/python3.6/site-packages/goatools/cli/docopt_parse.py", line 25, in get_docargs
    arg_kws = self._get_docargs(args, prt)
  File "/sc/anaconda3/lib/python3.6/site-packages/goatools/cli/docopt_parse.py", line 38, in _get_docargs
    self._chk_docopt_kws(kwargs_doc, args_user)
  File "/sc/anaconda3/lib/python3.6/site-packages/goatools/cli/docopt_parse.py", line 74, in _chk_docopt_kws
    raise RuntimeError(self._err("UNKNOWN KEY", key, val, exp))
RuntimeError: Command-line script to create GO term diagrams

Usage:
  go_plot.py [GO ...] [options]
  go_plot.py [GO ...] [--obo=<file.obo>] [--outfile=<file.png>] [--title=<title>]
             [--go_file=<file.txt>]
             [--relationship]
             [--relationships=<part_of>]
             [--sections=<sections.txt>]
             [--gpad=<file.gpad>]
             [--gaf=<file.gaf>]
             [--gene2go=<gene2go>] [--taxid=<Taxonomy_number>]
             [--id2gos=<file.txt>]
             [--shorten]
             [--parentcnt] [--childcnt] [--mark_alt_id]
             [--go_aliases=<go_aliases.txt>]
             [--draw-children]
             [--norel]
             [--go_color_file=<file.txt>]
  go_plot.py [GO ...] [--obo=<file.obo>] [-o <file.png>] [-t <title>]
             [--shorten] [-p] [-c]
  go_plot.py [GO ...] [-o <file.png>] [--draw-children]
  go_plot.py [GO ...] [-o <file.png>] [--draw-children] [--shorten]
  go_plot.py [--obo=<file.obo>]
  go_plot.py [--obo=<file.obo>] [--outfile=<file.png>]
  go_plot.py [GO ...]
  go_plot.py [GO ...] [--outfile=<file.png>] [--title=<title>]
  go_plot.py [GO ...] [--outfile=<file.png>] [--title=<title>] [--shorten]
  go_plot.py [GO ...] [-o <file.png>] [-t <title>]
  go_plot.py [GO ...] [-o <file.png>] [-t <title>] [--parentcnt]
  go_plot.py [GO ...] [-o <file.png>] [-t <title>] [--childcnt]
  go_plot.py [GO ...] [-o <file.png>] [-t <title>] [--parentcnt] [--childcnt]
  go_plot.py [GO ...] [-o <file.png>] [-t <title>] [-p]
  go_plot.py [GO ...] [-o <file.png>] [-t <title>] [-p] [-c]

Options:
  -h --help                            show this help message and exit
  -i --go_file=<file.txt>              GO IDs in an ASCII file
  -o <file.png>, --outfile=<file.png>  Plot file name [default: go_plot.png]
  -r --relationship                    Plot all relationships
  --relationships=<part_of>            Plot user-specified relationships
  -s <sections.txt> --sections=<sections.txt>  Sections file for grouping
  -S <sections module str>             Sections file for grouping

  --gpad=<file.gpad>                   Annotations from a gpad file
  --gaf=<file.gaf>                     Annotations from a gaf file
  --id2gos=<file.txt>                  Annotations from a text file, e.g., data/association
  --gene2go=<gene2go>                  Annotations from a gene2go file downloaded from NCBI
  --taxid=<taxid_num>                  TaxID for use when reading NCBI's gene2go file

  --obo=<file.obo>                     Ontologies in obo file [default: go-basic.obo].

  -t <title>, --title=<title>          Title string to place in image
  -p --parentcnt                       Include parent count in each GO term
  -c --childcnt                        Include child count in each GO term
  --shorten                            Shorten the GO name on plots
  --mark_alt_id                        Add 'a' if GO ID is an alternate ID: GO:0007582a
  --draw-children                      Draw children. By default, they are not drawn.
  --go_aliases=<go_aliases.txt>        ASCII file containing letter alias
  --go_color_file=<file.txt>           GO color file. GO and color (eg #cafffb)

  --norel                              Don't load relationship from the GO DAG

UNKNOWN KEY: KEY(t) VAL(False):

**Comment by cmungall** [comment]
Hi @pan-genome it looks like you are using the goatools python library. This is a great library but it's not something supported by the GO consortium (or EBI GOA) despite the name

You can file an issue here https://github.com/tanghaibao/goatools
