### ISSUE TITLE
Missing parent: [actin filament-based process (GO:0030029)]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23114]
* **GO term ID and label for which you request a new superclass**

actin filament-based process (GO:0030029)
and descendants, are no longer under 
GO:0030036   actin cytoskeleton organization

is that intentional (affects slims as annotations to descendants no longer slim)

**Comment by raymond91125** [comment]
In AmiGO, actin cytoskeleton organization is a child of actin filament-based process
![image](https://user-images.githubusercontent.com/619520/163488595-a3446703-5fa8-47a5-9def-6819139278be.png)

But in QuickGO, these two terms appear unrelated
![image](https://user-images.githubusercontent.com/619520/163488292-d6f5111b-58aa-4480-a4af-38fc873bc969.png)

**Comment by raymond91125** [comment]
@ValWood Where do you see the lack of relationship (it's opposite from what you said, BTW)? AmiGO seems fine.

**Comment by pgaudet** [comment]
Note that I made changes to that branch here: #19809

**Comment by raymond91125** [comment]
I see. So QuickGO is ahead of AmiGO.

But I wonder if this is correct.
https://github.com/geneontology/go-ontology/issues/19809#issuecomment-1078769890
> * [x]  GO:0030036 'actin cytoskeleton organization' > remove parent 'actin filament-based process', since the actin filement is the target, not a participant, in the process

GO:0030029 actin filament-based process DEFINITION Any cellular process that depends upon or alters the actin cytoskeleton, that part of the cytoskeleton comprising actin filaments and their associated proteins. 

Thus It appears to cover actin being the participant and the target.

**Comment by pgaudet** [comment]
@raymond91125 

>  So QuickGO is ahead of AmiGO.

Yes. AmiGO is updated monthly at each GO release. You can see the date of the the data in AmiGO at the bottom right footer: 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/4782928/164155903-d67d0009-438e-45d4-b82a-208291dfb581.png">


Pascale

**Comment by pgaudet** [comment]
@ValWood 
Do you think actin filament-based process (GO:0030029)
should be under GO:0030036 actin cytoskeleton organization? 

Isn't the organization independent of the function of the 'organelle' or structure? Although for the cytoskeleton it works by reorganizing itself, so maybe this is different from for example, mitochondrion organization? 

Thanks, Pascale

**Comment by ValWood** [comment]
1.
I agree, but at present there are a bunch of terms under here that  are organization.
see
https://www.pombase.org/term/GO:0030029
the only term that isn't clearly organization is 
"vesicle transport along actin filament"
but even then the cytoskeleton will likely be dynamic and so  I do think it is difficult for the cytoskeleton to separate the organization from the functions.

2. The term " actin filament-based process" is poorly defined, it encompasses organization:
Any cellular process that **depends upon or alters the actin cytoskeleton**, that part of the cytoskeleton comprising actin filaments and their associated proteins.
Note that the organization terms under actin filament-based process (GO:0030029)  related to 'branching' and severing' will probably be obsoleted in favour of single-step processes?

3.
The "microtubule-based process"/ GO:0000226   microtubule cytoskeleton organization
is similarly organized, and the same  logic will apply here. If the 2 branches are retained
At least some of the terms here"GO:0099098   microtubule polymerization based movement"
should have dual parentage. However I think it will be very difficult to separate.

@manulera (new Pombase curator) has expertise here, might be able to advise here. We can have a call sometime, might be easier?

**Comment by manulera** [comment]
Hello,

I had a look and tend to agree with @ValWood.

* I think it's good to have a single parent for all microtubule/actin-related processes.
* As she was saying, the cytoskeleton is not "passive" in its organisation. I see how this can be the case for an organelle moved to a certain place or transported somewhere without its components being involved. For the cytoskeleton this is not the case, changing its organisation will always involve the polymers themselves doing something.
* I think the old arrangement that can be found in Amigo makes sense, where organization is child of actin filament-based process. Same for microtubules
* You can imagine a microtubule-based process that does not involve re-organisation, such as the transport of a vesicle along the existing microtubule network without changing it, but I cannot think of an example of the opposite.

**Comment by raymond91125** [comment]
@pgaudet would you take this on since it's related to #19809?

**Comment by pgaudet** [comment]
So, I will revert this: 
https://github.com/geneontology/go-ontology/issues/19809#issuecomment-1078769890 $

* GO:0030036 'actin cytoskeleton organization' > remove parent 'actin filament-based process', since the actin filement is the target, not a participant, in the process
* same for GO:0000226 'microtubule cytoskeleton organization'

**Comment by pgaudet** [comment]
Also: 

- [x] microtubule cytoskeleton attachment to nuclear envelope: change parent from 'cytoskeleton organization' to 'microtubule cytoskeleton organization'
