### ISSUE TITLE
obsolete GO:0010108 detection of glutamine

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#23123]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0010108 detection of glutamine

* **Reason for deprecation**
This sounds like what might be a collection of different processes?

* **"Replace by" term (ID and label)**
I will request a new term for something that functions as a glutamine sensor

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
I don't think so?

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
* no

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

**Comment by pgaudet** [comment]
How about if we create 'nutrient sensor activity', and suggest to replace 
GO:0009594 detection of nutrient 
GO:0010108 detection of glutamine 
GO:0031318 detection of folic acid

with that new MF, and use has_input to specify the exact chemical? 

SGD has 2 annotations from PMID:34535752
@srengel Does that sound OK to you? 

Thanks, Pascale

**Comment by Antonialock** [comment]
@ValWood 

> SGD has 2 annotations from PMID:34535752

Oh I wasn't aware. I did not see this in P2GO...I guess it will be imported at some point

**Comment by srengel** [comment]
sounds ok to me @pgaudet

**Comment by ValWood** [comment]
@ValWood  pinging myself to update pombe pib2

**Comment by Antonialock** [comment]
Oh now I can see the annotations in SGD - I guess it was just some glitch

**Comment by pgaudet** [comment]
It's in AmiGO .. 
http://amigo.geneontology.org/amigo/term/GO:0010108 
and in Noctua, indeed : http://noctua.geneontology.org/editor/graph/gomodel:617b481400003011

I guess SGD loads a file from Noctua that QuickGO doesn't ? 
@srengel @suzialeksander 

Thanks, Pascale

**Comment by srengel** [comment]
yes SGD loads annotations from P2GO and from Noctua.

**Comment by ValWood** [comment]
So doesn't the EBI load the annotation that so into AmiGO from Noctua into QuickGO?

**Comment by pgaudet** [comment]
No. This is on the to-do list.

**Comment by raymond91125** [comment]
The parent term of GO:0010108 detection of glutamine is GO:0009593 detection of chemical stimulus. Perhaps it is sufficient to merge them? There is a MF GO:0070406 glutamine binding I believe appropriate for Sc PIB2 annotation.
IMHO, "nutrient sensor activity" sounds like a rather complex MF (with BP built in).

**Comment by pgaudet** [comment]
The BP 'detection' is a single step, that for most other terms represents some sensor activity (see small molecule sensor activity & children). 
Maybe to discuss on the next ontology call? 

Thanks, Pascale

**Comment by raymond91125** [comment]
There is a MF GO:0140786 glutamine sensor activity.

**Comment by raymond91125** [comment]
My feeling on this is that "nutrient sensor activity" seems like something that is context dependent, e.g. one organism's nutrient maybe another's waste. In other words, such MF terms have an implied purpose (BP). In the case of chemical reactions, we usually don't assign directions thus we are agnostic about what the desired product is.

**Comment by ValWood** [comment]
> My feeling on this is that "nutrient sensor activity" seems like something that is context dependent,

it is, but when the nutrient sensor term is used as an MF term  we would only use it in the correct context of specifying a known nutrient?  These sensor terms are essential for modeling, because they determine the starting point of a pathway (indicating that other indirect affects are causally upstream).

**Comment by srengel** [comment]
i have removed the two SGD annotations.  in noctua, which was not easy to do in any intuitive way.  hope i didn't mess it up.

**Comment by raymond91125** [comment]
@srengel Thanks!

**Comment by vanaukenk** [comment]
> i have removed the two SGD annotations. in noctua, which was not easy to do in any intuitive way. hope i didn't mess it up.

@srengel - it'd be helpful to know what changes you made and why it didn't seem easy to do in an intuitive way.  We can follow-up offline.  Thanks.
