### ISSUE TITLE
Merge  GO:0034587 piRNA metabolic process   & GO:1990511 piRNA biosynthetic process ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23135]
Discussing with @hattrill 

- [x]  GO:0034587 piRNA metabolic process and GO:1990511 piRNA biosynthetic process seem to have been used interchangeably to mean 'piRNA processing' - we need to review annotations to make sure the merge is OK

Annotations are here: 
https://docs.google.com/spreadsheets/d/1og1_ZyWBl133-nZnJjXC4HnG5HfmjxmJt4HXWdpX2Kk/edit#gid=0

- [x] the term should be moved under 'GO:0070918 small regulatory non-coding RNA processing
- [x]  GO:0034588  piRNA catabolic process should be obsoleted

**Comment by pgaudet** [comment]
NTR gene silencing by piRNA-directed DNA methylation

https://pubmed.ncbi.nlm.nih.gov/32674113/

**Comment by pgaudet** [comment]
NTR piRNA-mediated transposon silencing
NTR tRNA-mediated transposon silencing

https://pubmed.ncbi.nlm.nih.gov/33789107/

**Comment by pgaudet** [comment]
NTR piRNA amplification loop
 PMID:23706823

**Comment by pgaudet** [comment]
Note that piRNA is mediated by polII (are there other polymerases than transcribe piRNAs?)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0034588 piRNA catabolic process'. The reason for obsoletion is that there is not evidence that this process exists; ie that piRNAs are specifically degraded.   There are no annotations or mappings to 
this term, this term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/23135


Thanks, Pascale

**Comment by pgaudet** [comment]
GO:1990511 

- [x] Changed label 
piRNA biosynthetic process -> to piRNA processing

- [x] Changed definition
- old def: : "The chemical reactions and pathways resulting in the formation of piRNAs, Piwi-associated RNAs, a class of 24- to 30-nucleotide RNA derived from repeat or complex DNA sequence elements and processed by a Dicer-independent mechanism." [GOC:kmv, PMID:24696457]

- new def: "Any process that results in the conversion of one or more primary piRNAs transcripts into one or more mature piRNA molecules. piRNAs, also known as Piwi-associated RNAs, are a class of 24- to 30-nucleotide RNA derived from repeat or complex DNA sequence elements and processed by a Dicer-independent mechanism." [GOC:kmv, PMID:24696457]

@gantonazzo @hattrill let me know if you want to change the definition. 

Thanks, Pascale

**Comment by pgaudet** [comment]
From https://pubmed.ncbi.nlm.nih.gov/34724117/

> piRNAs can be categorized into primary piRNAs and secondary piRNAs based on their biogenesis pathways, which
are principally distinguished by their mechanisms of 5′end formation. 

**Primary piRNAs** are produced from long single-
stranded RNA precursors that are synthesized from piRNA loci, and their 5′ends are produced during the fragmenta-
tion process, likely involving the MitoPLD endonuclease (or PLD6, which has a homolog “Zucchini” in Drosophila)
located on mitochondrial outer membranes. 

**Secondary piRNAs** are produced from piRNA-targeted transcripts, and their 5′ends are generated by the endonucleolytic activity of PIWI proteins, which cleaves between positions 10 and 11 of the base-pair complementary RNA target relative to the piRNA 5′end. These secondary piRNAs can target the primary piRNA precursor transcripts to generate more secondary piRNAs, resulting in a piRNA-specific “Ping-Pong” loop. This loop is believed to represent an adaptive immune response that enables piRNAs to silence TE transcripts post-transcriptionally, as the loop continues to produce TE piRNAs until the TE transcripts are diminished (Gunawardane et al. 2007; Brennecke et al. 2007).

**Comment by pgaudet** [comment]
@gantonazzo
From my reading (see pasted text above, among other references), the ping-pong amplification is part of 'secondary piRNAs processing' ; should we create 'primary piRNA processing' and 'secondary piRNA processing' as children of piRNA processing, instead of 'ping-pong amplification', which is one of the steps of the pathway?

**Comment by ValWood** [comment]
NTR piRNA amplification loop
seems an odd term. Positive feedback loops exist in  all of the siRNA pathways (not to mention many other pathways, cell cycle regulation etc). It isn't something we have usually explicitly created a GO term for.

I agree it is a useful concept to but I am not sure that GO terms are the place. Perhaps it should be something that is  represented in some way in the modelling process (down the line, once we have nailed rules for simple regulation)

**Comment by pgaudet** [comment]
Right, it would be 'Secondary piRNA processing', see my comment just above

**Comment by ValWood** [comment]
But this is the case for every  siRNA pathway:

This is PTGS: 

<img width="408" alt="Screenshot 2022-07-21 at 08 07 55" src="https://user-images.githubusercontent.com/7359272/180151735-9488c4ca-5674-4a1b-a8aa-4adcd2d31cf9.png">

If you make this split, you are breaking down a  'linear pathway" which includes amplification , for which we know all the MF steps , into two processes.

primary RNAs and secondary RNAs seem that they would be better modelled as inputs and outputs rather than processes?  Otherwise, we would need initiation and amplification processes for
PTGS, siRNA dependent heterochromatin assembly, and every other RNAi related pathway

**Comment by pgaudet** [comment]
Do all the small RNAs go through this amplification process? I thought the siRNAs did, but not the miRNAs. 

I think we need to review that branch to make sure that the terms are no redundant (ie that the pathways being described really are different); right now you are right that these all seems to just have different outputs, we need to add more details to describe the pathways.

**Comment by ValWood** [comment]
I don't know about miRNAs, but all the pathways which use siRNA have an amplification step. We have never included this in a term before.

I think it is a good idea to begin with a list of the known pathways an how they  differ.  From my limited knowledge the main difference between piRNA and siRNA is dicer dependent and that piRNA are dicer independent (I was going to open a ticket about this also because the definitions do adequately  not describe the differences).

**Comment by pgaudet** [comment]
![image](https://user-images.githubusercontent.com/4782928/180156640-248f726f-91f2-45fd-ae57-2742c9904969.png)


from https://pubmed.ncbi.nlm.nih.gov/20687832/

**Comment by pgaudet** [comment]
Discussion with @RLovering @hattrill 

- [ ] NTR primary piRNA processing

- [ ] NTR secondary piRNA processing
synonym: ping-pong derived piRNA EXCACT
synonym: ping-pong amplification RELATED

**Comment by pgaudet** [comment]
Also, we need a MF for piRNA

**Comment by pgaudet** [comment]
Good review on piRNA biogenesis and mechanism of action in mouse, Drosophila and C. elegans: https://pubmed.ncbi.nlm.nih.gov/33419460/

**Comment by ValWood** [comment]
Right, there is not always an amplification step, but the ampification when it occurs is performed by RNA dependent RNA polymerase, and so it is a single-step (MF)? Is that correct? Or are there other amplification mechanisms?

**Comment by ValWood** [comment]
This split
NTR primary piRNA processing
 NTR secondary piRNA processing

sort of works, except that the RNA-dependent RNA polymerase amplification MF isn't processing (processing is specifically producing  a mature RNA molecule and the amplification step is copying it)

**Comment by ValWood** [comment]
The paper I am reading right now calls this process "production"  not processing


PMID:15615848

Title | RNA-dependent RNA polymerase is an essential component of a self-enforcing loop coupling heterochromatin assembly to siRNA production.

 In C. elegans, RRF-1 and EGO-1 are essential for secondary siRNA production from RNAi-targeted transcripts in somatic cells and germ-line development, respectively (11, 27),

**Comment by hattrill** [comment]
Sticking to piRNA, which is indep of RNA-dep RNA pol - ping-pong amplification couples piRNA processing to target destruction. (think I got a bit mixed up with dual strand cluster transcription and the mechanism of ping-pong amplification on the call earlier today):
<img width="850" alt="Screenshot 2022-07-21 at 14 14 46" src="https://user-images.githubusercontent.com/11865746/180222737-546b3214-8e2c-40c6-800d-52ca0db1dd02.png">

So, possibly need to think about how 2ndary processing and piRNA-mediated destruction of transposon RNA are linked

**Comment by hattrill** [comment]
Hi @ValWood are priRNAs only in yeast? 
I shall have a look at this. 

I think for the ping-pong cycle it may be impossible to separate the generation of new secondary piRNAs from the destruction of transposon RNA or other target RNAs. I think I need to understand whether the first piRNA has some sort of initiator activity. From what I can understand, it mainly depends on the target - if it is at the level of transcription/chromatin structure, then primary piRNAs are sufficient to dampen the element but if a transposon is being actively transcribed, the ping pong mechanism is an 'adaptive' response which allows the cell to generate a cascade of piRNAs from the target so that there are more and new piRNAs sequences that are complementary to the transposon. ie primary piRNA seqs are determined by the piRNA gene and secondary piRNAs sequences are independent of the piRNA gene and reflect the transposon.

Think  I am starting to get my head around it, but will probably need more discussion. Going to try and understand if there is any difference between regulating transposition and regulation of transposon transcription later today. @RLovering [this paper ](https://royalsocietypublishing.org/doi/epdf/10.1098/rsob.180181) has a summary of the types of transposition.

**Comment by ValWood** [comment]
woah that is cnfusing. I was confusing pri and pi, but I think they are the same thing.

"We have previously identified priRNAs, a class of Dicer-independent small RNAs in fission yeast."
which is exactly what a pri is isn't it?

In this paper the authors refer to these as primal small RNAs  https://pubmed.ncbi.nlm.nih.gov/30397104/
so  I think pri an pi are referring to the same thing? I will double check this....

Certainly the pombe priRNAs ae involved in the genome surveillance and transposon quelling, so I think they are largely the same. Some parts of the pathway are the same but some are different (Our amplification step probably uses RdRP which is absent in flies, but I haven't looked at this pathway in detail.

**Comment by hattrill** [comment]
This is very good ['Fly piRNA biogenesis: tap dancing with Tej'](https://pubmed.ncbi.nlm.nih.gov/25335561/) looks at the difference between where primary and secondary processing occurs - essentially shows that In short, primary and secondary processing are separate processes, but, I would say that secondary processing is not separable from post-transcritional transposon silencing.
![Screenshot 2022-07-24 at 11 12 57](https://user-images.githubusercontent.com/11865746/180642955-76675434-32ed-4257-8827-0153d86974d8.png)
![Screenshot 2022-07-24 at 11 22 30](https://user-images.githubusercontent.com/11865746/180642958-499e8db9-ecf5-4b21-a3e5-087ef508fa26.png)

**Comment by pgaudet** [comment]
Discussion ncRNA @hattrill @gantonazzo @RLovering 

- [ ] piRNA processing: add RELATED synonym: primary piRNA processing
- [ ] NTR: secondary piRNA processing
- synonym: ping-pong derived piRNA EXCACT
- synonym: ping-pong amplification RELATED
- definition:

**Comment by pgaudet** [comment]
@hattrill and @gantonazzo will provide a definition and reference

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140965
+name: secondary piRNA processing
+namespace: biological_process
+def: "A the processing of a non-coding RNA \n..." []
+synonym: "ping-pong amplification" RELATED []
+synonym: "ping-pong derived piRNA" EXACT []
+synonym: "secondary piRNA biogenesis" EXACT []
+synonym: "secondary PIWI-associated RNA processing" EXACT []
+is_a: GO:0070918 ! regulatory ncRNA processing
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23135 xsd:anyURI
+creation_date: 2022-12-12T13:25:26Z


(note that the definition is incomplete)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140966
+name: piRNA-directed heterochromatin formation
+namespace: biological_process
+namespace: The formation of facultative heterochromatin into a heterochromatin domain, enriched in histone H3 methylated on lysine 9 (H3K9me), by a process mediated by a small interfering piRNA. {comment="PMID:23329111"}
+synonym: "piwiRNA-directed heterochromatin formation" EXACT []
+is_a: GO:0031048 ! RNA-mediated heterochromatin formation
+created_by: pg
+creation_date: 2022-12-12T13:51:08Z
+

**Comment by pgaudet** [comment]
- [ ] NTR piRNA-mediated gene silencing by mRNA destabilization
- [ ] @hattrill @gantonazzo : please provide a reference

**Comment by pgaudet** [comment]
Draft definition for primary piRNA processing (from https://github.com/FlyBase/GO-curation/issues/23)

The process involved in converting precursor piRNAs (long single-stranded capped and polyadenylated RNAs) into non-overlapping, contiguous primary piRNAs (∼24-30-nt piRNAs with a preference for a 5' uridine (U) via the endonucleolytic activity of cytosolic PIWI. This may include pre-piRNA maturation of 3′ ends by trimming and 2′-O-methylation.

Refs: PMID:34469728
PMID:26166577

**Comment by hattrill** [comment]
Draft for "Secondary piRNA processing"
A self-perpetuating piRNA loop, often called the ping-pong cycle, in which piRNAs are amplified by pairing with complementary transcripts (for example the transposable element mRNA target). In Drosophila, the processing involves the piwi proteins aubergine and Argonaute 3 and in mice, the piwi proteins Piwil2 and Piwil4.
PMID:32895365
PMID:29281264

**Comment by hattrill** [comment]
We would like 
primary piRNA processing
and 
secondary piRNA processing

to be child terms of GO:0034587	piRNA processing (as this has been used for both primary and secondary)

All of these terms should be "Only in Metazoa TAXID:33208"
TAXID:33208

**Comment by hattrill** [comment]
We may also want "tertiary piRNA processimg" which can occur after primary or secondary pathways and is sometimes called phasing, but we will need to do a bit more background.

**Comment by hattrill** [comment]
> +[Term] +id: GO:0140966 +name: piRNA-directed heterochromatin formation +namespace: biological_process +namespace: The formation of facultative heterochromatin into a heterochromatin domain, enriched in histone H3 methylated on lysine 9 (H3K9me), by a process mediated by a small interfering piRNA. {comment="PMID:23329111"} +synonym: "piwiRNA-directed heterochromatin formation" EXACT [] +is_a: GO:0031048 ! RNA-mediated heterochromatin formation +created_by: pg +creation_date: 2022-12-12T13:51:08Z +

Hi @pgaudet I think that we decided not to use "facultative" here?

**Comment by pgaudet** [comment]
Hi @hattrill I removed 'facultative' from the definition. 

A question for @colinlog - is H3K9me any heterochromatin, or facultative ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
> We would like
primary piRNA processing
secondary piRNA processing
to be child terms of GO:0034587 piRNA processing (as this has been used for both primary and secondary)


Should we not rather re-annotate ? (83 EXP). Or at least I will make 'piRNA processing' 'do not annotate'

**Comment by pgaudet** [comment]
Secondary piRNA processing draft definition: https://github.com/geneontology/go-ontology/issues/23135#issuecomment-1351273759

Added as "A process leading to the generation of a functional secondary piRNA, involving a self-perpetuating piRNA loop, often called the ping-pong cycle, in which piRNAs are amplified by pairing with complementary transcripts (for example the transposable element mRNA target). In Drosophila, the processing involves the piwi proteins aubergine and Argonaute 3 and in mice, the piwi proteins Piwil2 and Piwil4."

**Comment by colinlog** [comment]
H3K9me3 is any heterochromatin, including constitutive heterochromatin, but
not every heterochromatin. H3K27me3 is facultative, mostly. There are about
as many sites that have both H3K27me3 and H3K9me3, as there are with only
any one of the two marks.

**Comment by hattrill** [comment]
Draft def for ""piRNA-mediated gene silencing by mRNA destabilization""
A cytoplasmic post-transcriptional gene silencing pathway in which piRNAs direct the cleavage of target mRNAs. The target mRNA, often transcribed from a transposable element, is destabilized by the activity of a PIWI class endonuclease within the piRNA-induced silencing complex. This may also be accompanied by mRNA deadenylation and decapping.
PMID:33419460
PMID:29281264

**Comment by hattrill** [comment]
Hi @pgaudet, just got round to reviewing this ticket:
piRNA processing still needs some work:
1. piRNA processing GO:0034587 - definition is fine


2. Secondary piRNA processing GO:0140965 - definition is fine ; should be a child of piRNA processing GO:0034587 rather than ncRNA processing GO:0034470

3. need to add new term: 
primary piRNA processing 
Def "The process involved in converting precursor piRNAs (long single-stranded capped and polyadenylated RNAs) into non-overlapping, contiguous primary piRNAs (∼24-30-nt piRNAs with a preference for a 5' uridine (U) via the endonucleolytic activity of cytosolic PIWI. This may include pre-piRNA maturation of 3′ ends by trimming and 2′-O-methylation.""

Refs:
PMID:34469728
PMID:26166577
PMID: 22907665

Make child of piRNA processing GO:0034587

**Comment by hattrill** [comment]
For the 'silencing':

1. piRNA-directed heterochromatin formation GO:0140966 - looks done

2. Term still to make:
piRNA-mediated gene silencing by mRNA destabilization

A cytoplasmic post-transcriptional gene silencing pathway in which piRNAs direct the cleavage of target mRNAs. The target mRNA, often transcribed from a transposable element, is destabilized by the activity of a PIWI class endonuclease within the piRNA-induced silencing complex. This may also be accompanied by mRNA deadenylation and decapping.
PMID:33419460
PMID:29281264

Not sure if we discussed the parentage of this?
As, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8490990/ says "piRNAs execute transposon repression in two ways: degrading their RNA transcripts and compacting the genomic loci via heterochromatinization"

think that this can be a child of both:

mRNA destabilization GO:0061157
and 
RNA-mediated post-transcriptional gene silencing GO:0035194

**Comment by pgaudet** [comment]
From https://github.com/FlyBase/GO-curation/issues/23#issuecomment-1410007885

@hattrill commented 
> I think from looking over the papers Giulia and I think that it would be safer to have a parent term (piRNA processing) for primary piRNA processing or secondary terms. The reasoning behind this is that although they can be and mainly are separate processes, there are examples where they may feed into each other or that authors are just not clear. And, if we were to make a term for tertiary processing (and I am not sure about whether we would want that), it would have to be under a generic parent as it can't take place without primary or secondary processing first.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140990
+name: primary piRNA processing
+namespace: biological_process
+def: "The process involved in converting precursor piRNAs into non-overlapping, contiguous primary piRNAs (approximately 24-30-nt piRNAs with a preference for a 5' uridine (U) via the endonucleolytic activity of cytosolic PIWI. This may include pre-piRNA maturation of 3' ends by trimming and 2'-O-methylation." [PMID:22907665, PMID:26166577, PMID:34469728]
+is_a: GO:0034587 ! piRNA processing
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23135 xsd:anyURI
+created_by: pg
+creation_date: 2023-02-01T13:36:56Z

**Comment by pgaudet** [comment]
I created a ticket to reanotate to the more precise terms when possible:
https://github.com/geneontology/go-annotation/issues/4432

I think this takes care of all tasks in the present ticket. 

Closing.

**Comment by pgaudet** [comment]
- [ ]  primary piRNA processing and secondary piRNA processing
Add TC  "Only in Metazoa TAXID:33208"

**Comment by pgaudet** [comment]
@hattrill I've added 

GO:0034587	piRNA processing	NCBITaxon:6072	Eumetazoa	

OK ?
