### ISSUE TITLE
NTR histone phosphatase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23148]
Hello, 

To rehouse some annotations due to the obsoletion of histone dephosphorlyation (see #23145), @sylvainpoux is requesting 'histone phosphatase activity' 

To be consistent with other histone modification reactions, we should perhaps create the specific modifications. I found 2 annotated modifications: 
H2-Y142  (catalyzed by O00167 and Q99504)
H2-S140 (catalyzed by P60510)

For the Tyrosine, I can put the term under 'GO:0004725 protein tyrosine phosphatase activity'; but for the Serine, we dont have a 'phosphoserine phosphatase activity'  - we have either 
* GO:0004722 protein serine/threonine phosphatase activity or 
* GO:0008138 protein tyrosine/serine/threonine phosphatase activity

@sylvainpoux do you know if these phosphatases are specific for phosphoserine? I would probably create a grouping term. 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi Pascale,
if we follow protein phosphatase specificities, we should have one for protein serine/threonine phosphatase (P60510) activity and one for protein tyrosine/serine/threonine phosphatase activity (O00167 and Q99504)
Let me know when terms are created, I will curate them
Thank you very much!
Sylvain

**Comment by pgaudet** [comment]
Last login: Mon Apr  4 17:57:51 on console
➜  ~ git:(master) ✗ cd repos/go-ontology/src/ontology
➜  ontology git:(master) ✗ git diff master 
➜  ontology git:(master) ✗ git pull                         
remote: Enumerating objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 1
Unpacking objects: 100% (1/1), done.
From https://github.com/geneontology/go-ontology
   b6559c99..d6429f7b  master     -> origin/master
Updating b6559c99..d6429f7b
Fast-forward
 src/ontology/go-edit.obo | 25 ++++++++++++-------------
 1 file changed, 12 insertions(+), 13 deletions(-)
➜  ontology git:(master) ✗ git checkout -b issue-23132
M	src/ontology/imports/go-pattern-conformance.ttl
M	src/ontology/imports/x-disjoint.owl
Switched to a new branch 'issue-23132'
➜  ontology git:(issue-23132) ✗ git diff 
➜  ontology git:(issue-23132) ✗ git commit -m 'created new term for #23132' go-edit.obo
[issue-23132 f111614d] created new term for #23132
 1 file changed, 10 insertions(+)
➜  ontology git:(issue-23132) ✗ git push origin issue-23132
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.40 KiB | 476.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: 
remote: Create a pull request for 'issue-23132' on GitHub by visiting:
remote:      https://github.com/geneontology/go-ontology/pull/new/issue-23132
remote: 
To https://github.com/geneontology/go-ontology.git
 * [new branch]        issue-23132 -> issue-23132
➜  ontology git:(issue-23132) ✗ git checkout master 
M	src/ontology/imports/go-pattern-conformance.ttl
M	src/ontology/imports/x-disjoint.owl
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git branch -l 
➜  ontology git:(master) ✗ git checkout  new_prokaryote_subset
M	src/ontology/imports/go-pattern-conformance.ttl
M	src/ontology/imports/x-disjoint.owl
Switched to branch 'new_prokaryote_subset'
➜  ontology git:(new_prokaryote_subset) ✗ git diff 
➜  ontology git:(new_prokaryote_subset) ✗ git commit -m 'fixed prok subset' go-edit.obo
[new_prokaryote_subset aa496b1e] fixed prok subset
 1 file changed, 2 insertions(+)
➜  ontology git:(new_prokaryote_subset) ✗ git checkout master 
M	src/ontology/imports/go-pattern-conformance.ttl
M	src/ontology/imports/x-disjoint.owl
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git pull 
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/geneontology/go-ontology
   d6429f7b..aae5a51a  master     -> origin/master
Updating d6429f7b..aae5a51a
Fast-forward
 src/ontology/go-edit.obo | 10 ++++++++++
 1 file changed, 10 insertions(+)
➜  ontology git:(master) ✗ git branch -d issue-23132
Deleted branch issue-23132 (was f111614d).
➜  ontology git:(master) ✗ git checkout new_prokaryote_subset
M	src/ontology/imports/go-pattern-conformance.ttl
M	src/ontology/imports/x-disjoint.owl
Switched to branch 'new_prokaryote_subset'
➜  ontology git:(new_prokaryote_subset) ✗ git pull origin master 
From https://github.com/geneontology/go-ontology
 * branch              master     -> FETCH_HEAD
Auto-merging src/ontology/go-edit.obo
CONFLICT (content): Merge conflict in src/ontology/go-edit.obo
Automatic merge failed; fix conflicts and then commit the result.
➜  ontology git:(new_prokaryote_subset) ✗ git commit -m 'fixed conflict for #23023' go-edit.obo
fatal: cannot do a partial commit during a merge.
➜  ontology git:(new_prokaryote_subset) ✗ git commit -i * -m "fixed conflict" go-edit.obo
[new_prokaryote_subset 2c40260d] fixed conflict
➜  ontology git:(new_prokaryote_subset) ✗ git push origin new_prokaryote_subset
Enumerating objects: 42, done.
Counting objects: 100% (40/40), done.
Delta compression using up to 8 threads
Compressing objects: 100% (28/28), done.
Writing objects: 100% (28/28), 75.69 KiB | 332.00 KiB/s, done.
Total 28 (delta 23), reused 0 (delta 0)
remote: Resolving deltas: 100% (23/23), completed with 10 local objects.
To https://github.com/geneontology/go-ontology.git
   2c802dc7..2c40260d  new_prokaryote_subset -> new_prokaryote_subset
➜  ontology git:(new_prokaryote_subset) ✗ git checkout master 
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git pull 
Already up to date.
➜  ontology git:(master) ✗ git pull 
Already up to date.
➜  ontology git:(master) ✗ git diff master 
➜  ontology git:(master) ✗ git checkout -b issue-23143
M	src/ontology/go-edit.obo
Switched to a new branch 'issue-23143'
➜  ontology git:(issue-23143) ✗ git diff 
➜  ontology git:(issue-23143) ✗ git commit -m 'added new term fixes #23143' go-edit.obo
[issue-23143 31057a87] added new term fixes #23143
 1 file changed, 24 insertions(+), 6 deletions(-)
➜  ontology git:(issue-23143) ✗ git push origin issue-23143
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.67 KiB | 571.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: 
remote: Create a pull request for 'issue-23143' on GitHub by visiting:
remote:      https://github.com/geneontology/go-ontology/pull/new/issue-23143
remote: 
To https://github.com/geneontology/go-ontology.git
 * [new branch]        issue-23143 -> issue-23143
➜  ontology git:(issue-23143) ✗ git diff
➜  ontology git:(issue-23143) ✗ git commit -m 'added new term fixes #23143' go-edit.obo
[issue-23143 b1f24156] added new term fixes #23143
 1 file changed, 1 insertion(+), 1 deletion(-)
➜  ontology git:(issue-23143) ✗ git push origin issue-23143
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.26 KiB | 431.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/geneontology/go-ontology.git
   31057a87..b1f24156  issue-23143 -> issue-23143
➜  ontology git:(issue-23143) ✗ git diff master 
➜  ontology git:(issue-23143) ✗ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git pull 
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/geneontology/go-ontology
   aae5a51a..f601b4a8  master     -> origin/master
Updating aae5a51a..f601b4a8
Fast-forward
 src/ontology/go-edit.obo | 30 ++++++++++++++++++++++++------
 1 file changed, 24 insertions(+), 6 deletions(-)
➜  ontology git:(master) ✗ git branch -d issue-23143
Deleted branch issue-23143 (was b1f24156).
➜  ontology git:(master) ✗ git checkout -b issue-23148
Switched to a new branch 'issue-23148'
➜  ontology git:(issue-23148) ✗ git diff 
➜  ontology git:(issue-23148) ✗ git diff 
➜  ontology git:(issue-23148) ✗ git diff 
➜  ontology git:(issue-23148) ✗ git diff master 

+
+[Term]
+id: GO:0140790
+name: histone serine/threonine phosphatase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: histone serine phosphate + H2O = histone serine + phosphate, and histone threonine phosphate + H2O = histone threonine + phosphate." [PMID:18614045]
+is_a: GO:0004722 ! protein serine/threonine phosphatase activity
+is_a: GO:0140789 ! histone phosphatase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23148 xsd:anyURI
+created_by: pg
+creation_date: 2022-04-06T08:16:16Z
+
+[Term]
+id: GO:0140791
+name: histone serine phosphatase activity (H2-S140 specific)
+namespace: molecular_function
+def: "Catalysis of the reaction: histone H2 serine-140 phosphate + H2O = histone serine + phosphate." [PMID:18614045]
+is_a: GO:0140790 ! histone serine/threonine phosphatase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23148 xsd:anyURI
+created_by: pg
+creation_date: 2022-04-06T08:16:16Z
+
+[Term]
+id: GO:0140792
+name: histone tyrosine phosphatase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: histone tyrosine phosphate + H2O = histone tyrosine + phosphate." [PMID:19234442, PMID:19351884]
+is_a: GO:0004725 ! protein tyrosine phosphatase activity
+is_a: GO:0140789 ! histone phosphatase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23148 xsd:anyURI
+created_by: pg
+creation_date: 2022-04-06T08:20:40Z
+
+[Term]
+id: GO:0140793
+name: histone tyrosine phosphatase activity (H2-Y142 specific)
+namespace: molecular_function
+def: "Catalysis of the reaction: histone tyrosine phosphate + H2O = histone tyrosine + phosphate." [PMID:19234442, PMID:19351884]
+is_a: GO:0140792 ! histone tyrosine phosphatase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23148 xsd:anyURI
+created_by: pg
+creation_date: 2022-04-06T08:20:40Z
+

**Comment by pgaudet** [comment]
This has been said elsewhere, but for the record: we will not be doing this for every protein, but we have agreed that the histone code should be captured.
