### ISSUE TITLE
Single step BPs: histone phosphorylation 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23140]
Dear all, 

For the project of removing single step BPs from the ontology (and moving them to MFs as appropriate), the proposal has been made to obsolete:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  |   |   |   | Consider: |  
-- | -- | -- | -- | -- | --
GO:0016572 | histone phosphorylation | 32 |   | GO:0035173 | histone kinase activity
GO:0035404 | histone-serine phosphorylation | 0 |   | GO:0035174 | histone serine kinase activity
GO:0035405 | histone-threonine phosphorylation | 0 |   | GO:0035184 | histone threonine kinase activity
GO:0035406 | histone-tyrosine phosphorylation | 0 |   | GO:0035400 | histone tyrosine kinase activity
  |   |   |   |   |  
GO:1990164 | histone H2A phosphorylation | 6 |   |   |  
GO:1990853 | histone H2A SQE motif phosphorylation | 0 |   |   |  
GO:0043990 | histone H2A-S1 phosphorylation | 1 |   | GO:0044024 | histone kinase activity (H2A-S1 specific)
GO:0072370 | histone H2A-S121 phosphorylation |   |   | GO:0072371 | histone kinase activity (H2A-S121 specific)
GO:0035978 | histone H2A-S139 phosphorylation | 2 |   | GO:0035979 | histone kinase activity (H2A-S139 specific)
GO:1990245 | histone H2A-T120 phosphorylation | 1 |   | GO:1990244 | histone kinase activity (H2A-T120 specific)
GO:0043991 | histone H2B-S14 phosphorylation | 1 |   | GO:0044025 | histone kinase activity (H2B-S14 specific)
GO:0043987 | histone H3-S10 phosphorylation | 13 |   | GO:0035175 | histone kinase activity (H3-S10 specific)
GO:0043988 | histone H3-S28 phosphorylation | 5 |   | GO:0044022 | histone kinase activity (H3-S28 specific)
GO:0035407 | histone H3-T11 phosphorylation | 2 |   | GO:0035402 | histone kinase activity (H3-T11 specific)
GO:0072355 | histone H3-T3 phosphorylation | 3 |   | GO:0072354 | histone kinase activity (H3-T3 specific)
GO:0035408 | histone H3-T6 phosphorylation | 2 |   | GO:0035403 | histone kinase activity (H3-T6 specific)
GO:0035409 histone H3-Y41   phosphorylation | histone H3-Y41 phosphorylation | 1 |   | GO:0035401 | histone kinase activity (H3-Y41 specific)
GO:0043989 | histone H4-S1 phosphorylation | 0 |   | GO:0044023 | histone kinase activity (H4-S1 specific)
  |   |   |   |   |  
  |   |   |   |   |  
GO:2000751 | histone H3-T3 phosphorylation   involved in chromosome passenger complex localization to kinetochore: 2
  |   |   |   |   |  
GO:0033127 | regulation of histone phosphorylation | 2 |   |   |  
GO:0033128 | negative regulation of histone phosphorylation | 11 |   |   |  
GO:0033129 | positive regulation of histone phosphorylation | 13 |   |   |  
GO:2000817 | regulation of histone H3-T3 phosphorylation involved in chromosome   passenger complex localization to kinetochore | 0 |   |   |  
GO:2000281 | regulation of histone H3-T3 phosphorylation | 0 |   |   |  
GO:0061866 | negative regulation of histone H3-S10 phosphorylation | 1 |   |   |  
GO:2000281 | regulation of histone H3-S10 phosphorylation | 0 |   |   |  

</body>

</html>

_Edited numbers_
There are 98 annotations to these terms: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/pgaudet/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Contributor   (Assigned by)
--
AgBase | 1
AspGD | 1
BHF-UCL | 4
CACAO | 3
CAFA | 5
ComplexPortal | 7
FlyBase | 8
GeneDB | 6
GOC | 2
MGI | 8
RGD | 6
TAIR | 15
UniProt | 31
ZFIN | 1

</body>

</html>

**Comment by pgaudet** [comment]
Dear all, 

For the project of removing single step BPs from the ontology (and moving them to MFs as appropriate), the proposal has been made to obsolete histone phosphorlyation and its children: 

<body>

<html>

GO:0016572 | histone phosphorylation
GO:0035404 | histone-serine phosphorylation
GO:0035405 | histone-threonine phosphorylation
GO:0035406 | histone-tyrosine phosphorylation
  |  
GO:1990164 | histone H2A phosphorylation
GO:1990853 | histone H2A SQE motif phosphorylation
GO:0043990 | histone H2A-S1 phosphorylation
GO:0072370 | histone H2A-S121 phosphorylation
GO:0035978 | histone H2A-S139 phosphorylation
GO:1990245 | histone H2A-T120 phosphorylation
GO:0043991 | histone H2B-S14 phosphorylation
GO:0043987 | histone H3-S10 phosphorylation
GO:0043988 | histone H3-S28 phosphorylation
GO:0035407 | histone H3-T11 phosphorylation
GO:0072355 | histone H3-T3 phosphorylation
GO:0035408 | histone H3-T6 phosphorylation
GO:0035409 histone H3-Y41   phosphorylation | histone H3-Y41 phosphorylation
GO:0043989 | histone H4-S1 phosphorylation
  |  
  |  
GO:2000751 | histone H3-T3 phosphorylation involved in chromosome passenger complex   localization to kinetochore: 2
  |  
GO:0033127 | regulation of histone phosphorylation
GO:0033128 | negative regulation of histone phosphorylation
GO:0033129 | positive regulation of histone phosphorylation
GO:2000817 | regulation of histone H3-T3 phosphorylation involved in chromosome   passenger complex localization to kinetochore
GO:2000281 | regulation of histone H3-T3 phosphorylation
GO:0061866 | negative regulation of histone H3-S10 phosphorylation
GO:2000281 | regulation of histone H3-S10 phosphorylation



</body>

</html>

There are 98 EXP annotations to these terms: 

<body>

<html>

AgBase | 1
AspGD | 1
BHF-UCL | 4
CACAO | 3
CAFA | 5
ComplexPortal | 7
FlyBase | 8
GeneDB | 6
MGI | 8
RGD | 6
TAIR | 15
UniProt | 31
ZFIN | 1



</body>

</html>

There are 2 InterPro mappings:  
InterPro:IPR015519 
InterPro:IPR028772

These terms are not present in any subsets. 

We will leave 2 weeks for review before obsoleting the terms. You can comment in the ticket: 
https://github.com/geneontology/go-ontology/issues/23140

Thanks, Pascale

**Comment by pgaudet** [comment]
Annotations are here: 
https://github.com/geneontology/go-annotation/issues/4099

**Comment by hdrabkin** [comment]
MGI was done a couple weeks (?) ago; see spreadsheet

**Comment by RLovering** [comment]
done

**Comment by gthayman** [comment]
RGD done.
