### ISSUE TITLE
GO:0019156 isoamylase activity is not a subclass of GO:0004133 glycogen debranching enzyme activity]

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#23144]
GO:0019156 isoamylase activity is not necessarily [GO:0004133 glycogen debranching enzyme activity](http://amigo.geneontology.org/amigo/term/GO:0004133#display-lineage-tab) 
Basically, this linkage can be cleaved in sugars that are not glycogen so child relationship to glycogen debranching function is wrong.

**Comment by ukemi** [comment]
I think this extends to the other subtypes of GO:0004133 as well.

**Comment by deustp01** [comment]
Piling on, [amylopectin](https://en.wikipedia.org/wiki/Amylopectin), found in plants, is not a kind of glycogen but has (1->6)-alpha-D-glucosidic linkages that can be cleaved by enzymes.
And it looks like [4-alpha-glucanotransferase (EC 2.4.1.25) ](https://enzyme.expasy.org/EC/2.4.1.25)is associated with multiple plant enzymes (so no glycogen to act on) as well as animal ones

**Comment by hdrabkin** [comment]
removed glycogen debranching enzyme activity as parent of isoamylase activity, 4-alpha-gucanotransferase activity, and amyl-alpha-1,6 glucosidase activity.
