### ISSUE TITLE
NTR: L-glutamate uniporter activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#23143]
Please provide as much information as you can: 

* **Suggested term label:**
Molecular Function

* **Definition (free text)**
Catalysis of the active transport of a L-glutamate across a membrane by a mechanism involving conformational change, where energy for active transport is derived from membrane potential if the solute is charged.

* **Reference, in format PMID:#######**
PubMed=29642010 and PubMed=27133463
* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
membrane potential driven uniporter activity GO:0022810

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
RHEA:66336
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
Evidence:PubMed=29642010, see  Fig. 1 and 2.
Evidence:PubMed=27133463, see  Fig. 6.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140788
+name: L-glutamate uniporter activity
+namespace: molecular_function
+def: "Catalysis of the active transport of a L-glutamate across a membrane by a mechanism involving conformational change, where energy for active transport is derived from membrane potential if the solute is charged." [PMID:27133463, PMID:29642010]
+synonym: "glutamate uniporter activity" BROAD []
+xref: RHEA:66336 {source="skos:broadMatch"}
+intersection_of: GO:0022810 ! membrane potential driven uniporter activity
+intersection_of: has_primary_input CHEBI:29985 ! L-glutamate(1-)
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23143 xsd:string
+created_by: pg
+creation_date: 2022-04-06T07:05:14Z
