### ISSUE TITLE
Obsoletion proposal: GO:0016576 histone dephosphorylation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23145]
Dear all, 

As part of the project of removing single step BPs from the ontology (and moving them to MFs as appropriate), the proposal has been made to obsolete GO:0016576 histone dephosphorylation. 

There are 10 EXP annotations to this term. This term is not present in any subsets; there are no mappings to this term. 

Annotations are by
* ComplexPortal	4 
* RGD	2
* UniProt	4  (disputed in P2GO)

Annotations to be removed are here: 
https://docs.google.com/spreadsheets/d/1t2Yh3ujayvi1MwsTXuZfOWhV5j6t6d10tDJEq_WgueU/edit#gid=0

Thanks, Pascale

**Comment by slaulederkind** [comment]
RGD annotations have been removed or fixed.
