### ISSUE TITLE
Textual definition update: retinal binding

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-ontology#23158]
* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request a definition update**
GO:0016918 retinal binding

* **New proposed definition (genus-differentia pattern, plus additional information if needed) **
Binding to retinal, one of the forms of vitamin A.

* **Reference(s)**
PMID:15774036

* **Additional information**
Binding (GO:0005488) by definition should be non-covalent interactions. But opsin-retinal interaction is covalent. Thus this term should exclude opsins in the definition and synonyms. Note opsin-retinal interaction in the literature is often referred to as binding.

**Comment by raymond91125** [comment]
This term retinal binding has been incorrectly used for annotations. The LD is binding and ('has input' some retinal) but there is mentioning of opsin, which is covalently bonded to retinal, in the text definition and in synonyms. Any advice on what is the best course forward to disentangle? @pgaudet Thanks.

**Comment by pgaudet** [comment]
This paper talks about covalent binding of Rhodopsin and its ligand
https://pubmed.ncbi.nlm.nih.gov/20042594/

**Comment by pgaudet** [comment]
obsolete with 'consider'  GO:0008020 G protein-coupled photoreceptor activity
and modify the definition of GO:0008020 to describe that the chromophore binds covalently (and maybe some mention of the rhodopsin cycle?) 


And please replace the definition by more specific one(s)

**Comment by raymond91125** [comment]
A ref for noncovalent binding: PMID:11301033 Role of noncovalent binding of 11-cis-retinal to opsin in dark adaptation of rod and cone photoreceptors

**Comment by raymond91125** [comment]
There are other retinal binding proteins such as Interphotoreceptor retinoid-binding protein (IRBP) PMID:17222825.

In sum, I think "retinal binding" is a valid MF, despite the fact that in some instances (opsins) non-covalent binding precedes covalent attachment.
