### ISSUE TITLE
NTR: renal cortex tubule dedifferentiation

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#23169]
Please provide as much information as you can: 

* **Suggested term label:**

renal cortex tubule dedifferentiation

* **Definition (free text)**

Tubule dedifferentiation is manifested by production of mesenchymal markers, such as vimentin, indicating cells of the tubule are no longer in a differentiated state.

* **Reference, in format PMID:#######**

PMID:18987110

* **Gene product name and ID to be annotated to this term**

rat Csf1r (RGD:2425)

* **Parent term(s)**

nephron tubule morphogenesis (GO:0072078)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

1. regulation of renal cortex tubule dedifferentiation
2. positive regulation of renal cortex tubule dedifferentiation
3. negative regulation of renal cortex tubule dedifferentiation

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
I suggest the term label "kidney cortex tubule cell dedifferentiation" IS_A GO:0043697 cell dedifferentiation.

Definition: The process in which a kidney cortex tubule cell (specialized epithelial cell of the kidney) loses the structural or functional features that characterize it in the mature organism, or some other relatively stable phase of the organism's life history. Under certain conditions, these cells can revert back to the features of the stem cells that were their ancestors. (PMID:18987110, PMID:31847447)

Comment: Following injury, renal cortex tubular epithelial cell appears to be undergoing epithelial-mesenchymal transition, detected by overexpression of vimentin (PMID:31847447). 

Is this good? @slaulederkind Thanks.

**Comment by slaulederkind** [comment]
Sounds good. Thank you @raymond91125.
