### ISSUE TITLE
NTR: histone kinase activity (H2A-Y142 specific)

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#23170]
Please provide as much information as you can: 

* **Suggested term label:**

 histone kinase activity (H2A-Y142 specific)
* **Definition (free text)**

 Catalysis of the transfer of a phosphate group to the tyrosine-142 residue of the C-terminal tail of histone H2A. 
* **Reference, in format PMID:#######**
PMID: 19092802
* **Gene product name and ID to be annotated to this term**
Q9UIG0 (BAZ1B_HUMAN)
* **Parent term(s)**

GO:0035400
* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140801
+name: histone kinase activity (H2A-Y142 specific)
+namespace: molecular_function
+def: "Catalysis of the transfer of a phosphate group to the tyrosine-142 residue of the C-terminal tail of histone H2A." [PMID:19092802]
+is_a: GO:0035400 ! histone tyrosine kinase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23170 xsd:anyURI
+created_by: pg
+creation_date: 2022-04-08T16:17:40Z

**Comment by pgaudet** [comment]
In fact this in on the H2AX variant - this position does not exist on the canonical H2A -need to edit term label and possibly the definiton

**Comment by pgaudet** [comment]
Created grouping term 

 
+[Term]
+id: GO:0141003
+name: histone H2AX kinase activity
+namespace: molecular_function
+def: "Catalysis of the transfer of a phosphate group to a histone variant H2AX." [GOC:bf]
+is_a: GO:0035173 ! histone kinase activity
+created_by: pg
+creation_date: 2023-02-28T13:55:39Z
+


and fixed label of GO:0140801 to histone H2AXY142 kinase activity

Thanks, Pascale
