### ISSUE TITLE
Why is GO:0050450 restricted to archaea?

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#23189]
Why has this term (citrate (Re)-synthase activity) been restricted to archaea? It has been found in a number of bacteria;
Clostridium kluyveri, PMID 17400742
Syntrophus aciditrophicus PMID  23378508
Dehalococcoides strain CBDB1 PMID 21784924
Can you check this please and thank you, Andrea

**Comment by pgaudet** [comment]
Right, bacteria is right! The paper cited was PMID:17400742


Should it even be in archae, do you know?

**Comment by AndreaAuchincloss** [comment]
I don't know, there are only 13 papers in PubMed on Re-citrate synthase, all are in bacteria. I doubt if it is known if it exists in archaea. I wouldn't restrict it to bacteria because I don't think enough is known.
