### ISSUE TITLE
Rhea mapping to GO:0004165

### ISSUE THREAD

**Issue by alanbridge** [geneontology/go-ontology#23198]
Hi 

for GO:0004165, 

"Catalysis of the reactions: a (3Z)-enoyl-CoA = a 4-saturated (2E)-enoyl-CoA or a (3E)-enoyl-CoA = a 4-saturated (2E)-enoyl-CoA"

the mapping to https://www.rhea-db.org/rhea/23716 is to a specific form of one of these reactions: 

(3Z)-dodecenoyl-CoA = (2E)-dodecenoyl-CoA 

(which is specific form of "a (3Z)-enoyl-CoA = a 4-saturated (2E)-enoyl-CoA")

should this be removed?

All the best, Alan

**Comment by hdrabkin** [comment]
Hi alan
would RHEA:45900 be better?  However, GO:0004165 is already mapped to it.
I could make RHEA:23716 a narrowMatch xref to GO:0004165 also.

**Comment by alanbridge** [comment]
Hi Harold, 

thanks for looking at this. Rhea:45900 would be better. A narrowMatch xref would also be good, but I noticed that in QuickGO you don't see the type of match (such as narrowMatch) when browsing the data - just a list of xrefs, take a look:

https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0004165

All the best, Alan

**Comment by hdrabkin** [comment]
ARGH: I just noticed that there are TWO exact rheas for GO:0004165; one is RHEA:23716 and the other is RHEA:45900.

I will remove RHEA:23716 as a def ref and make it a norrowMatch xref. Since 45900 was already used in the def, I don't have to worry about that one.

**Comment by hdrabkin** [comment]
I see   RHEA:45228  is already a narrowMatch xref but was not removed from a def ref upon a term merge ; I'm suprised that was allowed to go through 
RHEA:45228 is now removed from def ref.

I will bring up the ability of Amigo/QuickGO to display an xref type label on the Ontology call monday.

**Comment by pgaudet** [comment]
For QuickGO we need to notify @alexsign
