### ISSUE TITLE
NTR rixosome complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23192]
rixosome complex
A conserved RNA endonuclease complex required for spreading and epigenetic inheritance of heterochromatin.

parent
GO:1905348 endonuclease complex

References
A conserved RNA degradation complex required for spreading and epigenetic inheritance of heterochromatin.
Shipkovenska G, Durango A, Kalocsay M, Gygi SP, Moazed D.
Elife. 2020 Jun 3;9:e54341. doi: 10.7554/eLife.54341.
PMID: 32491985 

Rixosomal RNA degradation contributes to silencing of Polycomb target genes.
Zhou H, Stein CB, Shafiq TA, Shipkovenska G, Kalocsay M, Paulo JA, Zhang J, Luo Z, Gygi SP, Adelman K, Moazed D.
Nature. 2022 Apr;604(7904):167-174. doi: 10.1038/s41586-022-04598-0. Epub 2022 Mar 30.
PMID: 35355014

Notes, some could be added as gloss
The rixosome contains six unique subunits – three structural subunits Crb3, Rix1 and Ipi1, which form the core of the complex, and three catalytic subunits – the endonuclease Las1, the polynucleotide kinase Grc3 and the AAA-type ATPase Mdn1, which are involved in the processing of ribosomal RNA precursors. All subunits are essential for viability and are conserved from yeast to mammals, including humans (Figure 2A). 

Composition:
<img width="522" alt="rixosome" src="https://user-images.githubusercontent.com/7359272/162811596-8f2831b9-1d87-482d-b0e8-5df98cf31bdc.png">

**Comment by krchristie** [comment]
Hi @ValWood - since you specified that it is an "**RNA** endonuclease" I placed it under the term "GO:1902555 - endo**RIBO**nuclease complex" rather than under "GO:1905348 - endonuclease complex" as you requested.

**Comment by ValWood** [comment]
Of course, thanks!
