### ISSUE TITLE
siderophore transmembrane transporter activity, revise primary name

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23199]
siderophore transmembrane transporter activity (GO:0015343)
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: siderophore-iron(out) + H+(out) = siderophore-iron(in) + H+(in).

could this term be renamed to 
siderophore-iron transmembrane transporter activity
(would make more sense as the purpose is to transport iron)

Also it would match

GO:0033214 | siderophore-dependent iron import into cell

**Comment by raymond91125** [comment]
1. Siderophores (Greek: "iron carrier"), thus the purpose is fairly clear.
"iron" is not included in the names of the parent term or any of the children terms. e.g.
GO:0044718 siderophore transmembrane transport
GO:0015344 siderophore uptake transmembrane transporter activity

2. siderophore-iron transmembrane transporter activity is a "related" synonym for GO:0015343.

3. However, from the label and definition, this term is not restricted to import into cell (at least it's not clearly stated).

**Comment by raymond91125** [comment]
refs - https://en.wikipedia.org/wiki/Siderophore, PMID:20376388, PMID:31748738, PMID:17804665

**Comment by ValWood** [comment]
> Siderophores (Greek: "iron carrier"), thus the purpose is fairly clear.

This is true, but it is really the Siiderophore-Fe complex that is transported. The siderophore  (a small peptide synthesised and exported  by fungi and bacteria) alone is only a carrier. It seems more precise to say siderophore-iron in the term name, anyone who does not know what a siderophore is, it will be more plainly obvious that iron is the transported compound of interest. The main focus in the term name should really be on the iron, not on the siderophore.

> However, from the label and definition, this term is not restricted to import into cell (at least it's not clearly stated).

Perhaps import into cell should be clearly stated. Siderophores are only used for import across the plasma membrane.

In fact a function -process link could be instantiated between 
GO:0015343 siderophore transmembrane transporter activity 
and
GO:0033214 | siderophore-dependent iron import into cell

**Comment by raymond91125** [comment]
At least one gene annotated with siderophore transmembrane transporter activity, irtA in Mycobacterium tuberculosis, is demonstrated to be a siderophore exporter, by selective binding to non-ferrated siderophores [PMID:18461140].
Thus, if we are to distinguish importers from exporters, we need to: 
1. Review all annotations of siderophore transport terms, those that are not explicit about the direction.
2. Make new directional child terms and reannotate.

**Comment by pgaudet** [comment]
Right - I think I saw that before; is this worth it ?

**Comment by ValWood** [comment]
wearing my haemochromotosis hat, I'm not bothered about the function process (I can do that at annotation time) , my reason for requesting  this is that currently  siderophore transporter
is not a descendant of iron ion transporter :

<img width="470" alt="Screenshot 2022-04-22 at 09 07 53" src="https://user-images.githubusercontent.com/7359272/164645860-aefa546a-b06e-4d85-8e8c-b0283d802c4b.png">

1. so if a user retrieves all "iron ion transporters",  "siderophore transporter" is excluded and Fe3+ is an iron ion (this is what lead me to the problem, I did a query and these known iron transporters were missing)

2. "Siderophore transmembrane transport" is already under "iron ion transmembrane transport"

3. The definition of 
GO:0015343   siderophore transmembrane transporter activity
is
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: siderophore-iron(out) + H+(out) = siderophore-iron(in) + H+(in).

and the exact definition is "iron-siderophore transporter activity" so it's correct use is as a "iron-siderophore transporter activity" -- if it has been otherwise used  it has been used incorrectly. 
Replacing the name to match the narrower meaning, and adding the missing parent  would. be ontology best practice (if anyone wants to annotate the transport of an actual siderophore without iron, they can request the correct term for this,  as it will be much clearer that the existing term is not the right one)

4. There is also the additional issue that I not  noticed, that siderophore-dependent iron import is not related to  siderophore transmembrane transport at all.  I think that likely these 2 terms could be merged and inherit the properties of both (import, transmembrane, iron, plasma membrane)
Unless, there are siderophores that  import iron via endocytosis...

**Comment by ValWood** [comment]
edited to replace the figure.

**Comment by raymond91125** [comment]
> 4\. There is the additional issue that I  had not  noticed-  siderophore-dependent iron import is not related to siderophore transmembrane transport at all in the graph.  I think that likely these 2 terms could be merged and inherit the properties of both (import, transmembrane, iron, plasma membrane)
>Unless, there are siderophores that  import iron via endocytosis...

It seems to me that siderophore transmembrane transport concerns both directions thus not equivalent to siderophore-dependent iron import.

**Comment by ValWood** [comment]
Do you have an example? I thought siderophores were only involved in iron accumulation.

**Comment by raymond91125** [comment]
PMID:18461140 -- "IrtA is involved in the export of non-ferrated siderophores"
![image](https://user-images.githubusercontent.com/619520/189713701-11a428c7-8365-4319-a7f9-4504f17e9061.png)

**Comment by raymond91125** [comment]
@ValWood I guess the question is where the process "siderophore-dependent iron import" starts. I thing it does not include the exporting of iron-free siderophore from the cell.

**Comment by ValWood** [comment]
I am not sure whether the export would be part of the pathway, or causally upstream.
Go does not have good rules about this.  @pgaudet ?

**Comment by raymond91125** [comment]
siderophore transmembrane transport has the def "The directed movement of siderophores, low molecular weight Fe(III)-chelating substances, from one side of a membrane to the other, by means of some agent such as a transporter or pore." It does not exclude any direction or membrane per se.
Perhaps we can add the relationship siderophore-dependent iron import has_part siderophore transmembrane transport.

**Comment by ValWood** [comment]
Here what I wanted was an MF term to describe the activity of the ferrated siderophore.

(i.e siderophore-iron transmembrane transporter activity
or ideally
plasma membrane siderophore-iron transmembrane transporter activity

that could be part of  both

GO:0033214 | siderophore-dependent iron import into cell
and
siderophore transmembrane transport

**Comment by raymond91125** [comment]
@ValWood both of the part of relationships are in with my last commit https://github.com/geneontology/go-ontology/commit/17ecc9dd4842cf8ca135aa13ecb600549ea1ce14

**Comment by raymond91125** [comment]
closed for now. thanks.
