### ISSUE TITLE
Missing parent: estrogen secretion (GO:0035937) 

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#23211]
* **GO term ID and label for which you request a new superclass**

estradiol secretion (GO:0035938) 

* **New superclass (parent) suggested**

estrogen secretion (GO:0035937) 

* **Reference(s), if appropriate**

estradiol (CHEBI:23965) is a child term of estrogen (CHEBI:50114)

**Comment by pgaudet** [comment]
Fixed. Note that I had to add the assertion 'relationship: has_primary_input GOCHE:50114 ! substance with estrogen role' to all 3 terms to make this work - just the chemical do not classify the terms correctly (estrogen, estradiol and estrone). 

For eg CHEBI:23965 - estradiol

<img width="702" alt="image" src="https://user-images.githubusercontent.com/4782928/165235651-780c0cb9-4168-4876-bdf5-cca40b35d75c.png">


Thanks, Pascale
