### ISSUE TITLE
Incorrect parent, cohesin complex -> obsolete DNA packaging complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23212]
I just spotted that "cohesin complex" is a descendant of
i) DNA packaging complex
ii) condensed chromosome

But cohesin is active in interphase immediately after replication, so "condensed chromosome" is not always true.

For the same reason, I don't think that "DNA packaging" is always true (cohesin has multiple roles, cohesion, and looping. The looping process probably IS packaging, but cohesion isn't really packaging)
Also the definition "A protein complex that plays a role in the process of DNA packaging." is circular (and we do not have a generic term DNA packaging).
The descendants of "DNA packaging complex" are pretty random, so I wonder about it's existence as a grouping term.

**Comment by pgaudet** [comment]
I can easily remove the subclass 'condensed chromosome complex'

For the DNA packaging complex, this is the results oft he logical definitons: 

cohesin complex: 
'protein-containing complex'
 and ('capable of' some 'sister chromatid cohesion')

DNA packaging complex
'protein-containing complex'
 and ('capable of part of' some 'chromosome organization')

But we have merged DNA packaging into 'chromosome organization', which is why this term looks odd now. It only has 6 annotations, we can obsolete? and suggest replacing with [GO:0140513 nuclear protein-containing complex](http://amigo.geneontology.org/amigo/term/GO:0140513#display-lineage-tab)? 

Thanks, Pascale

**Comment by ValWood** [comment]
That works.

**Comment by pgaudet** [comment]
Annotations are here: 
https://docs.google.com/spreadsheets/d/1tDeatLIExWEng1_Cq1Ud78a6s6CZxQjcidzESiVNOr4/edit#gid=0

But maybe this is a useful grouping class? it groups for instance: 
GO:0140092 bBAF complex
GO:0035060 brahma complex
GO:0140093 esBAF complex
GO:0140091 mBAF complex
GO:0071565 nBAF complex
GO:0031617 NMS complex
GO:0071564 npBAF complex 

(and other unrelated complexes). Should we discuss this on a transcription call ? 

@colinlog any thought on this?

**Comment by ValWood** [comment]
I don't know what all of these are, but NMS complex isn't a "DNA packaging complex" (NMS is  at the interphase between the microtubule and the centromeric core).

**Comment by pgaudet** [comment]
@sandraorchard I was wondering what you thought about this - currently the children of ' DNA packaging complex' are

<img width="510" alt="image" src="https://user-images.githubusercontent.com/4782928/185088359-041ca6ab-6882-4dc4-b582-b93b279b04a3.png">


Taking into account that we have merged 'DNA packaging' into 'chromatin organization'. Your suggestions about this branch would be much appreciated.

**Comment by ValWood** [comment]
I propose to obsolete 
GO:0044815  DNA packaging complex

It is defined:
A protein complex that plays a role in the process of DNA packaging.
but we do not have a process "DNA packaging"

and the terms are a mixture of unrelated DNA associated complexes, some of which are  doing packaging
but I'm not sure that this grouping term really helps?

**Comment by pgaudet** [comment]
Sure, go ahead

Current children can move under '[GO:0032993 protein-DNA complex](http://amigo.geneontology.org/amigo/term/GO:0032993#display-lineage-tab)'

**Comment by colinlog** [comment]
The telomere CAP is a DNA loop. The t-Loop is bound by Shelterin complexes, etc... 

BP/MF is looping not packaging. but is part of super-BP Chromosome organization.

This loop is not by cohesin, rather, the single strand 3'overhang of the chromosome is a g-rich strand that base-pairs with the homologous telomere repeats inside the telomere, thus displaces its own copy as single strand D-loop and form a large telomere t-loop.

By the way, this does not involve the SMC1/3 cohesin motors, as far as I know. Not sure about condensin and DNA recombination motors SMC2/4 and SMC5/6 

Say, this ticket asks also about SWI/SNF ATP-dependent remodellers and their grouping. Yes true, there is a panther group with all the histone acetylation-reading BROMO domain-containing SNF2-type ATPases. That is the common denominator ATPase motor enzyme-type of all those BAF complexes, which decorate enhancers and  promoters with varying avidity, depending on the associated subunits.

**Comment by ValWood** [comment]
Moving comment to the correct ticket

@pgaudet apart from "nucleosome" all of the other children are inferred from the reasoner. However, sometimes there is no logical axiom so I can't see what reasoning they come from.
Sometimes I can see a logical def, but even in those cases I can't see how "DNA packaging complex" gets inferred.
Because this is a misused grouping term, I wanted to rehouse the descendant terms first.

@pgaudet  let me know when you have time to show me how to do this.

**Comment by ValWood** [comment]
This ticket is no longer required.
Obsoletion ticket is here https://github.com/geneontology/go-ontology/issues/25070
