### ISSUE TITLE
NTR: [positive regulation of nucleosome disassembly]

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#23229]
Please provide as much information as you can: 

* **Suggested term label:**

positive regulation of nucleosome disassembly

* **Definition (free text)**

Any process that activates or increases the frequency, rate or extent of the controlled breakdown of nucleosomes, the beadlike structural units of eukaryotic chromatin composed of histones and DNA. 

* **Reference, in format PMID:#######**

https://pubmed.ncbi.nlm.nih.gov/34471130/
https://pubmed.ncbi.nlm.nih.gov/35308047/

* **Gene product name and ID to be annotated to this term**

CLB5-CDC28 kinase complex (S. cerevisiae) aka CPX-1702

* **Parent term(s)**

GO:0006337 nucleosome disassembly

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

none

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

none

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by robnash** [comment]
anyone able to add this one for me?

**Comment by pgaudet** [comment]
Hi @robnash 

Thanks for the ping. We are actively working in this area, there has been many recent changes in the ontology. This complex (as well the the chaperone it regulates) can be annotated to 'GO:0006335 DNA replication-dependent chromatin assembly' (see https://github.com/geneontology/go-ontology/issues/22130 for relevant changes). 

We could create a MF histone chaperone regulator activity if you think this is needed. 

@colinlog other suggestions? 

Thanks, Pascale

**Comment by robnash** [comment]
In the paper I have been trying to annotate, Yta7p is shown to disrupt chromatin by disassembling nucleosomes, and this facilitates progression of the replisome through a chromatin template, preventing replicative stress. The S phase CDK complex (CLB5-CDC28 kinase complex (CPX-1702)) stimulates the the ATPase activity and the chromatin segregase function of Yta7p resulting in nucleosome disassembly. 

So far I have captured the remodeling activity (they never referred to it as a histone chaperone) as part of nucleosome disassembly, as part of DNA replication:

YTA7	GO:0140658 ATP-dependent chromatin remodeler activity (IDA, IMP); part of GO:0006337 nucleosome disassembly (IDA, IMP); part of: GO:0006261 DNA-templated DNA replication (IDA, IMP); is located on: GO:0000785 chromatin (IDA)

and the stimulation of ATPase activity by the CDK complex as:

CLB5-CDC28 kinase complex (CPX-1702)	GO:0004693 cyclin-dependent protein serine/threonine kinase activity (IDA), has input: YTA7; part of: GO:0032781 positive regulation of ATP-dependent activity, has input: YTA7 (IDA)

what I need to capture is the stimulation of segregase activity, and was therefore proposing to annotate it as:

CLB5-CDC28 kinase complex (CPX-1702)	GO:0004693 cyclin-dependent protein serine/threonine kinase activity (IDA), has input: YTA7; regulates NTR: GO:XXXXXXX positive regulation of nucleosome disassembly, has input: YTA7 (IDA)

So if this is not possible, I need another way to capture this stimulation of segregase activity (nucleosome disassembly). So if I bypass the inclusion of the kinase activity on regulating the process, I suppose I could annotate the complex directly using a new term to describe a regulator of "ATP-dependent chromatin remodeler activity (GO:0140658)". So am thining something like "ATP-dependent chromatin remodeler regulator activity" but the wording sounds a bit awkward

**Comment by pgaudet** [comment]
After discussion with @colinlog 
We will create 'positive regulation of nucleosome disassembly' 
and a sibling to  'GO:0006335 DNA replication-dependent chromatin assembly',  DNA replication-dependent chromatin **dis**assembly. 

Note that for the CLB5-CDC28 complex: 

> CLB5-CDC28 kinase complex (CPX-1702) GO:0004693 cyclin-dependent protein serine/threonine kinase activity (IDA), has input: YTA7; regulates NTR: GO:XXXXXXX positive regulation of nucleosome disassembly, has input: YTA7 (IDA)

it is not correct to have YTA7 as the input; the input would be the nucleosome (or the histones composing it), which is already in the term label, so you don't need an input here.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140887
+name: positive regulation of nucleosome disassembly
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of the controlled breakdown of nucleosomes, the beadlike structural units of eukaryotic chromatin composed of histones and DNA." [PMID:34471130, PMID:35308047]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0006334 ! nucleosome assembly
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23229 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-11T16:56:42Z

+[Term]
+id: GO:0140889
+name: DNA replication-dependent chromatin disassembly
+namespace: biological_process
+namespace: The disruption of nucleosomes during DNA replication to allow the replication machinery to access the DNA. {xref="PMID:35308047", xref="PMID:34471130"}
+is_a: GO:0006325 ! chromatin organization
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23229 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-11T19:41:22Z
+

**Comment by robnash** [comment]
Thanks Colin and Pascale for taking a look and creating the new terms. Much appreciated!

**Comment by pgaudet** [comment]
I still have a doubt about the regulation of the nucleosome assembly - I _think_ (but I am not sure) that CLB5-CDC28 regulates replication, and that all the steps nucleosome disassembly /reassembly, DNA polymerase activity, etc et, are _part of_ DNA replication. 

So I think the correct model is
* CLB5-CDC28  regulates YTA7 activity (and its 200 other substrates)
* YTA7 _part_of nucleosome disassemby
* CLB5-CDC28 _acts upstream of, positive effect_ nucleosome disassemby (via YTA7)

Anyhow, I'll leave it like this for now, but just to say, we may revisit this when we look at DNA replication/cell cycle progression more closely. 

Thanks, 

Pascale

**Comment by ValWood** [comment]
I'm still struggling to understand these terms.

This activity seems to be part of the  overall  pathway of removing and adding nucleosomes during replication.
But the process term to represent this process covers only the reassembly/ de novo assembly part 
GO:0006335 DNA replication-dependent chromatin assembly

I'm also still struggling also with the distinction between "nucleosome assembly" and "chromatin assembly".

I'm also struggling with where the "regulation" should be represented (but this is a more general issue  I have lots of examples of this,  not just in the chromatin area -I will raise questions on Slack  and then  on an annotation call, hopefully in the next few weeks).

**Comment by pgaudet** [comment]
Hi @robnash 

Sorry to reactivate this - can you use the term '[DNA replication-dependent chromatin disassembly](http://purl.obolibrary.org/obo/GO_0140889)' ?

**Comment by robnash** [comment]
Not sure why after such a long time this continues to be an issue? I don't want data loss and by changing "positive regulation of nucleosome disassembly" to "DNA replication-dependent chromatin disassembly" I lose the whole regulatory aspect. If I wanted to use this term and a GO-CAM relation from the RO to replace "part_of" and connect MF and BP, which term would it be? Its known to be via phosphorylation and direct stimulation of Yta7p, but I cannot find an appropriate RO term?

Looking here https://wiki.geneontology.org/Annotation_Relations#Standard_Annotation:_Annotation_Extension_Relations the positive effect RO terms that link MF to BP say either "... mechanism relating the activity to the Biological Process **is not known**" (causally upstream of or within, positive effect) or "... when the mechanism relating an activity to a Biological Process is known and the activity occurs before the Biological Process, is required for the process to occur, **but does not regulate it**." (causally upstream of, positive effect) and neither is correct in this case.

Including a screenshot if that helps to ask what to replace the part_of relation with to connect the MF protein kinase activity to the BP DNA replication-dependent chromatin disassembly and preserve the regulatory aspect.

<img width="597" height="233" alt="Image" src="https://github.com/user-attachments/assets/0b62d22d-bb33-401e-ac90-fec05d95bf73" />

**Comment by pgaudet** [comment]
Hi @robnash 

Thanks for the quick reply. The problem with these terms is that they are quite overlapping with the chromatin remodeling and the histone chaperone terms, and we are struggling to come up with definitions that are not just read-outs. 

@colinlog and I will look at this again in January. 

Happy holidays!

Pascale
