### ISSUE TITLE
endonuclease complex - not related to subtypes of endonuclease complexes

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#23220]
The term `endonuclease complex` does not have relationships with subtypes of endonuclease complexes, e.g. `endodeoxyribonuclease complex`  and `endoribonuclease complex`.

It should be like this:
-- endonuclease complex - GO:1905348
--- endodeoxyribonuclease complex - GO:1905347
--- endoribonuclease complex - GO_:902555

but currently, we have this:
![20220422-endonuclaseComplex-andShouldBeChildTerms](https://user-images.githubusercontent.com/10533218/164845036-5de63574-565c-44f5-8290-5b5935d0e9e1.png)

**Comment by pgaudet** [comment]
Looks OK now 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/4782928/185097192-48eeaa6b-28f2-4549-93e5-4f2e08687356.png">
