### ISSUE TITLE
NTR: [positive regulation of ATP hydrolysis activity]

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#23228]
Please provide as much information as you can: 

* **Suggested term label:**

positive regulation of ATP hydrolysis activity

* **Definition (free text)**

Any process that activates or increases the frequency, rate or extent of catalysis of the reaction: ATP + H2O = ADP + H+ Pi. ATP hydrolysis is used in some reactions as an energy source, for example to catalyze a reaction or drive transport against a concentration gradient. 

* **Reference, in format PMID:#######**

https://pubmed.ncbi.nlm.nih.gov/34471130/
https://pubmed.ncbi.nlm.nih.gov/35308047/

* **Gene product name and ID to be annotated to this term**

CLB5-CDC28 kinase complex (S. cerevisiae) aka CPX-1702

* **Parent term(s)**

GO:0016887  ATP hydrolysis activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

none

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

EXACT 	activation of adenosinetriphosphatase activity
EXACT 	activation of adenosine triphosphatase activity
EXACT 	activation of ATP hydrolase activity
EXACT 	activation of adenosine 5'-triphosphatase activity
EXACT 	activation of ATP monophosphatase activity
EXACT 	activation of ATP phosphohydrolase activity
EXACT 	positive regulation of adenosinetriphosphatase activity
EXACT 	positive regulation of adenosine triphosphatase activity
EXACT 	positive regulation of ATP hydrolase activity
EXACT 	positive regulation of adenosine 5'-triphosphatase activity
EXACT 	positive regulation of ATP monophosphatase activity
EXACT 	positive regulation of ATP phosphohydrolase activity

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
We dont create 'regulation of MF' in the BP aspect; we are trying to weed those out (but it takes some time).

Please use 'GO:0001671 ATPase activator activity' instead.

Thanks, Pascale

**Comment by robnash** [comment]
Thanks for the feedback. YSince the regulator is a cyclin-dependent kinase complex I am sure the 'GO:0001671 ATPase activator activity' works here. It is through phosphorylation that the activity of the ATPase is increased. Since the definition "Binds to and increases the activity of an ATP hydrolysis activity." suggests a stable binding and activation such as you would get with a chaperone/co-chaperone I may not be able to make the annotation.
