### ISSUE TITLE
NTR: carotenoid isomerooxygenase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23234]
* **Suggested term label:**
carotenoid isomerooxygenase activity

* **Definition (free text)**
Zeaxanthin + O(2) <=> (3R)-11-cis-3-hydroxyretinal + (3R)-all-trans-3-hydroxyretinal
The enzyme accepts different all-trans carotenoids, including beta- carotene, alpha-carotene and lutein, and catalyzes the symmetrical cleavage of the carotenoid and the simultaneous isomerization of only one of the products to a cis configuration. 

* **Reference, in format PMID:#######**
PMID:19889630, PMID:19020100

* **Gene product name and ID to be annotated to this term**
fly ninaB (FBgn0002937, Q9VFS2)

* **Parent term(s)**
GO:0010436 carotenoid dioxygenase activity

* **Cross-references**
EC 1.13.11.65
RHEA:33931

* **Any other information**
Needed for https://github.com/geneontology/go-annotation/issues/4136

**Comment by sjm41** [comment]
Should also review if any other existing terms should be moved to be children of GO:0010436 carotenoid dioxygenase activity.  Current tree looks like this (only showing relevant terms):
```
oxidoreductase activity, acting on single donors with incorporation of molecular oxygen, incorporation of two atoms of oxygen
|__9-cis-10'-apo-beta-carotenal cleavage oxygenase activity
|__9-cis-beta-carotene 9',10'-cleavage oxygenase activity
|__all-trans-8'-apo-beta-carotenal 15,15'-oxygenase
|__all-trans-beta-apo-10'-carotenal cleavage oxygenase activity
|__beta,beta-carotene-9',10'-cleaving oxygenase activity
|__beta-carotene 15,15'-dioxygenase activity
|__beta-carotene oxygenase activity
|__carotenoid dioxygenase activity
    |__9,10 (9', 10')-carotenoid-cleaving dioxygenase activity
    |__9-cis-epoxycarotenoid dioxygenase activity
```

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106422
+name: carotenoid isomerooxygenase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: Zeaxanthin + O(2) <=> (3R)-11-cis-3-hydroxyretinal + (3R)-all-trans-3-hydroxyretinal." [PMID:19020100, PMID:19889630, RHEA:33931]
+comment: The enzyme can use  various all-trans carotenoids, including beta- carotene, alpha-carotene and lutein, and catalyzes the symmetrical cleavage of the carotenoid and simultaneous isomerization of only one of the products to a cis configuration.
+xref: EC:1.13.11.65
+xref: RHEA:33931
+is_a: GO:0010436 ! carotenoid dioxygenase activity
+property_value: creation_date 2022-04-29T17:37:22Z xsd:dateTime
+created_by: hjd

**Comment by sjm41** [comment]
Thanks Harold.
Do you think any existing terms should be moved to be children of GO:0010436 carotenoid dioxygenase activity too (see my second comment above)?

**Comment by pgaudet** [comment]
>  wherease an oxygenase will have ONE atom incorporated

Isn't that a 'monooxygenase'? I thought an 'oxygenase' was less specific about the number of oxygen atoms incorporated.

**Comment by hdrabkin** [comment]
From here
https://www.tocris.com/pharmacology/oxygenases-and-oxidases
I pulled this:Dioxygenases incorporate both oxygen atoms into the substrate, whilst monooxygenases incorporate a single oxygen atom as a hydroxyl group into the substrate and the second oxygen atom is reduced to water.
But I think if the original term was using the EC id as def ref, it is clear that at least in the case above, it is a dioxygenease as water is not a product.

**Comment by hdrabkin** [comment]
I may need to remove the comment from the new term
The definition is specific to  Zeaxanthin , whereas the comment says not "can use various all-trans carotenoids, including beta- carotene, alpha-carotene and lutein".  
Do you by chance know what the exact CHEBI term the new RHEA is using? 
Is it  CHEBI:27547?   That CHEBI has a parent term caratenoid. 
I don't think we want to make terms for each
beta- carotene, alpha-carotene and lutein?   (sibs). Yet. 
@ukemi  thought the comment makes this confusing, especially

**Comment by sjm41** [comment]
Hi @hdrabkin The comment is ad verbatim from the corresponding EC entry here: https://enzyme.expasy.org/EC/1.13.11.65.
RHEA maps 1.13.11.65 to [RHEA:33931](https://www.rhea-db.org/rhea/33931)

Yes, the RHEA pages says the ChEBI for "all-trans-zeaxanthin" is [CHEBI:27547](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:27547)

So I see the problem, but this ought to be fixed at the EC end.

The earlier fly papers (PMID:10766819, PMID:11158606) said that the ninaB enzyme used beta-carotene, but the later paper (PMID:19889630) said that zeaxanthin is used:
_Previously, it has been shown that β-carotene is converted via cryptoxanthin into zeaxanthin when fed to larvae, indicating that hydroxylated carotenoids are the direct precursor for chromophore (35). However, tests for enzymatic activity with zeaxanthin and recombinant NinaB failed in a previous study (17). We therefore applied the modified test conditions that were recently established for Galleria NinaB (25). We confirmed that recombinant Galleria NinaB efficiently converts zeaxanthin to 3-hydroxy-retinal (Fig. 4, A and B). Recombinant Drosophila NinaB proved to be less active, but mass spectrometry revealed that 3-hydroxy-retinal was produced (Fig. 4C). Thus, β-carotene is first converted to zeaxanthin and then cleaved by NinaB to directly yield 3-hydroxy-retinal._

So, I think it would be OK if you decided to keep the single new GO term with zeaxanthin as the substrate and remove the comment, and I could still use that to annotate all the fly papers.

**Comment by hdrabkin** [comment]
Will do now. EC is not just describing a reaction like RHEA (and GO). EC is describing the enzyme. So the comment is really about the property of an enzyme, which may be loosey-goosey with substrate selection
