### ISSUE TITLE
TPV:  peptide pheromone export

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23245]
This has a parent to "regulation of hormone levels"

but in single-celled yeast, mating peptide export isn't  part_of "regulation of hormone level"

<img width="583" alt="GO-ticket" src="https://user-images.githubusercontent.com/7359272/166268340-d6f48ba5-48a4-4133-80cf-3fc21986e92c.png">

**Comment by pgaudet** [comment]
Should it be? which one if the two is wrong? Are single celled organisms are not considered to have hormones?

**Comment by ValWood** [comment]
nope, since hormone is "A hormone is a class of signaling molecules in multicellular organisms that are sent to distant organs by complex biological processes to regulate physiology and behavior"
It's one of those 'role' problems like vitamin and cofactor...

**Comment by ValWood** [comment]
Actually it seems that a pheromone is not a hormone?

"Both hormones and pheromones are produced inside the body. The main difference between hormones and pheromones is that hormones act inside the body, changing the functions and behavior of the animal whereas pheromones act on another animal of the same species by changing the behavior."
https://pediaa.com/difference-between-hormones-and-pheromones/#:~:text=Both%20hormones%20and%20pheromones%20are,species%20by%20changing%20the%20behavior.

**Comment by raymond91125** [comment]
removed is_a: GO:0009914 ! hormone transport.
