### ISSUE TITLE
Ontology not currently able to successfully complete full build

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#23248]
The ontology build in the pipelines are currently failing:
```
01:09:38   :: ERROR: definition-lacks-dbxref: GO:0015369
```
Is this maybe related to a recent change?
On:
```
01:09:46  make: *** [Makefile:260: go.obo] Error 1
```

Possibly related to:

https://github.com/geneontology/go-ontology/commit/9c7c6d5181cad1c84fa16d30518568e7fdbc1662
https://github.com/geneontology/go-ontology/commit/eaaf0681756a9004f8696a9d3df94618cf66824e

Is there something we need to import/update?

Tagging @balhoff

**Comment by kltm** [comment]
Also tagging @hdrabkin and @pgaudet

**Comment by pgaudet** [comment]
Hi @kltm 
Not sure why these PRs would be a problem ? https://github.com/geneontology/go-ontology/commit/9c7c6d5181cad1c84fa16d30518568e7fdbc1662
https://github.com/geneontology/go-ontology/commit/eaaf0681756a9004f8696a9d3df94618cf66824e

I change xrefs regularly, I never saw that.

**Comment by kltm** [comment]
This has been cleared--thank you!
