### ISSUE TITLE
 iron-sulfur cluster transfer

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23246]
GO:0097428 | protein maturation by iron-sulfur cluster transfer

Is this a single-step process? if so it should  be removed from the BP ontology
term requested here: https://github.com/geneontology/go-ontology/issues/13839
The MF term is GO:0140132   iron-sulfur cluster carrier activity

I am trying to fix IEA mapping here:
https://www.pombase.org/gene/SPAC8C9.11
as described here:
https://github.com/geneontology/go-annotation/issues/4134
(Annotation looks wrong for fra2?)

@Antonialock  do you agree?

**Comment by ValWood** [comment]
@pgaudet @Antonialock  is this just describing a 
GO:0140132 iron-sulfur cluster carrier activity
if so, I will obsolete.
(62 EXP annotations)

**Comment by Antonialock** [comment]
Well, from my memory there are several parts to this

- in the mitochondrion, 2Fe-2S clusters are assembled and end up attached to grx5
- grx5 can then EITHER transfer the 2Fe-2S cluster to a protein that requires the cofactor (single protein process) OR let it go into the production of 4Fe-4S clusters (requires isa1, isa2 and iba57). These 4Fe-4S clusters are then inserted into target proteins by e.g. Nfu1, the complex I-specific Ind1, and the Bol proteins
- alternatively the cluster is transported out of the mitochondrion. In the cytosol, it is EITHER transferred to a protein that requires the cofactor (multi-protein process, at least two pathways and involves cia2, cia1, mms19, nar1, ito1, yac1) OR  it goes into the production of 4Fe-4S clusters (requires nbp35, dre2, tah18, cfd1, grx3 and grx4....)

 here's a recent'ish review
https://www.frontiersin.org/articles/10.3389/fmicb.2019.02478/full

mitochondria
_"The resulting bridging [2Fe-2S] cluster on a Grx5 dimer is inserted directly into [2Fe-2S] recipient apoproteins or trafficked to the late ISC machinery for [4Fe-4S] cluster biogenesis. The early ISC machinery, including the chaperones and Grx5, is also responsible for generating the component X-S for transport of sulfur out of the mitochondria to the CIA machinery for cytosolic-nuclear Fe/S protein biogenesis. The late ISC machinery consists of the yet structurally and functionally uncharacterized Isa1-Isa2-Iba57 complex and is needed for the generation of [4Fe-4S] clusters. Trafficking and insertion of the [4Fe-4S] clusters into target Fe/S proteins are facilitated by specific ISC targeting factors, such as Nfu1, the complex I-specific Ind1, and the Bol proteins. Dashed arrows indicate steps that remain poorly elucidated on the biochemical level."_

https://www.frontiersin.org/files/Articles/482978/fmicb-10-02478-HTML/image_m/fmicb-10-02478-g001.jpg


cytosolic
_"In a second step, the transiently bound [4Fe-4S] cluster of Cfd1-Nbp35 is transferred to and inserted into apoproteins by the Fe-S protein Nar1, and the CIA targeting complex consisting of Cia1, Cia2, and Mms19. Maturation of the essential Fe-S protein Rli1 additionally depends on the function of the two specific adaptor proteins Yae1 and Lto1. "_

![image](https://github.com/geneontology/go-ontology/assets/12727506/f8f18f59-f2fe-4d5f-8933-94ea8654eb00)

**Comment by ValWood** [comment]
Thanks for that1

**Comment by pgaudet** [comment]
Close?

**Comment by ValWood** [comment]
Sorry I thought I had
