### ISSUE TITLE
NTR - metabolism: [non-proteinogenic amino acid biosynthesis]

### ISSUE THREAD

**Issue by danielhhaft** [geneontology/go-ontology#23269]
_Please provide as much information as you can:_ 

* **non-proteinogenic amino acid biosynthesis**

* **Definition (free text)**
Biosynthesis of any substance characterized chemically as an amino acid, but that is not one of the 20 common proteinogenic amino acids (ACDEFGHIKLMNPQRSTVWY), for N-formyl-Met, selenocysteine, or pyrrolysine.

Examples of non-proteinogenic amino acids include L-ornithine, D-alanine, D-serine, capreomycidine, etc.

This term can describe amino acids biosynthesized to be used by non-ribosomal peptide synthetases to make various natural products.

This term does not processes of post-translational modification.

_Please add 'description of substance' as appropriate:_
* *  **substance metabolic process:** The chemical reactions and pathways involving substance, [description of substance].
* * **substance biosynthetic process:** The chemical reactions and pathways resulting in the formation of substance, [description of substance].
* * **substance catabolic process:** The chemical reactions and pathways resulting in the breakdown of substance, [description of substance]. 

* **Reference, in format PMID:#######**

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0008652 cellular amino acid biosynthetic process

* **Synonym(s) (please specify, EXACT, BROAD, NARROW or RELATED)**
_Other than the standard synonyms below_

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
ornithine biosynthetic process
D-alanine biosynthetic process
capreomycidine biosynthetic process

* **Cross-references**
* MetaCyc or KEGG pathways, can also provide Wikipedia or other links.

* **Any other information**

----

* **FOR ONTOLOGY EDITOR**

* **Logical definition**
* *  **substance metabolic process:**
'metabolic process'
 and ('has primary input or output' some [substance]
* * **substance biosynthetic process:**
'biosynthetic process'
 and ('has primary output' some [substance].
* * **substance catabolic process:**
'catabolic process'
 and ('has primary output' some [substance] 

* **Standard synonyms**
* *  **substance metabolic process:**
* * * EXACT: substance metabolism
* * **substance biosynthetic process:** 
* * * EXACT: substance anabolism
* * * EXACT: substance biosynthesis
* * * EXACT: substance formation
* * * EXACT: substance synthesis

* * **substance catabolic process:**    
* * * EXACT: substance breakdown
* * * EXACT: substance catabolism
* * * EXACT: substance degradation

__edit from @cmungall__ parallel request:
- #23268

**Comment by tberardini** [comment]
Are these aa **never ever** found in a protein?

**Comment by tberardini** [comment]
@deustp01 found this paper PMID: 3622507 which he says suggests that one of these aa may be incorporated into a protein.

**Comment by danielhhaft** [comment]
Non-proteinogenic amino acids are NEVER EVER coded for in mRNA and then incorporated into a protein during protein biosynthesis on a ribosome.   That is the definition of a non-proteinogenic amino acid, and "non-proteinogenic amino acid" is a basic vocabulary term for those studying the biosynthetic gene clusters (BGC) that rely on non-ribosomal peptide synthetases (NRPS) to make natural products.

If some other process modifies an amino acid side chain, post-translationally, that's irrelevant.  In that case, it was not one of the 22 amino acids that get put in on ribosomes.

**Comment by deustp01** [comment]
> Non-proteinogenic amino acids are NEVER EVER specifically coded for in mRNA and then incorporated into a protein during protein biosynthesis on a ribosome.

OK, but what do we gain in reasoning power for data analysis by incorporating this role in a process ontology, beyond what is already provided by a list  (the 23 amino acids at the top of this thread) that can be used as a filter to include / exclude items in these analyses? The role distinction is real, just as the distinction between toxic and benign substances is real, but why is it the basis for useful ontology terms?

**Comment by tberardini** [comment]
> 
> 
>     @deustp01 found this paper PMID: 3622507 which he says suggests that one of these aa may be incorporated into a protein.
> 
> No, the paper doesn't say that. It says that norleucine is a substrate for a transamination reaction, a prominent feature of amino acid metabolism, whose inputs and outputs can include both "proteinogenic" amino acids (L-glutamate) and "nonproteinogenic" ones, as in the paper. Apologies if I misrepresented it.

My bad. I didn't understand correctly.
