### ISSUE TITLE
obsolete GO:0097393 telomeric repeat-containing RNA transcription

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23260]
Please provide as much information as you can:

* **GO term ID and Label**
obsolete GO:0097393 telomeric repeat-containing RNA transcription

* **Reason for deprecation**

There is no evidence that any of this is functionally relevant, could be cryptic transcription. I just kept the phenotypes

[https://www.pombase.org/reference/PMID:22139915](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.pombase.org%2Freference%2FPMID%3A22139915&data=04%7C01%7Cvw253%40cam.ac.uk%7C01bc206511844d88db1608da13e8df40%7C49a50445bdfa4b79ade3547b4f3986e9%7C0%7C0%7C637844188134161035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uz4jG81xaMhlOghD5dDWOeMnyJOch%2BPWBabOo%2B0a%2BlE%3D&reserved=0)

since these are the only EXP I think this term should be obsoleted

* **Are there annotations to this term?**
- How many EXP: 
pombe only, removed

**Comment by pgaudet** [comment]
Dear all, 
The proposal has been made to obsolete GO:0097393 telomeric repeat-containing RNA transcription. The reason for obsoletion is that there is no evidence that any of this is functionally relevant, could be cryptic transcription. There are no manual annotations to this term (EXP has been removed); no mappings; these terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/23260

Thanks, Pascale

**Comment by pgaudet** [comment]
Note there there are children terms - 
* GO:0097394 telomeric repeat-containing RNA transcription by RNA polymerase II
* *  [regulates relation] [GO:1901580 regulation of telomeric RNA transcription from RNA pol II promoter](http://amigo.geneontology.org/amigo/term/GO:1901580#display-lineage-tab)
* * *  [GO:1901581 negative regulation of telomeric RNA transcription from RNA pol II promoter](http://amigo.geneontology.org/amigo/term/GO:1901581#display-lineage-tab)
* * * [GO:1901582 positive regulation of telomeric RNA transcription from RNA pol II promoter](http://amigo.geneontology.org/amigo/term/GO:1901582#display-lineage-tab)

And one annotation to the positive regulation term by BHF @RLovering 
PMID:26055325

**Comment by RLovering** [comment]
ps did you check wikipedia? https://en.wikipedia.org/wiki/TERRA_(biology)

**Comment by paolaroncaglia** [comment]
Hi @ValWood @pgaudet @RLovering 
In case it helps with the decision, please find the original request [here](https://github.com/geneontology/go-ontology/issues/9997) (by Antonia while at PomBase; at the time - 2012 - she did indeed mention that there was no evidence for the process or pathway). @ukemi edited the term following a discussion [here](https://github.com/geneontology/go-ontology/issues/12157).
I don't feel strongly one way or another, but I was curious to track this term down as it was one of mine. 
Thanks and take care!
Paola

**Comment by ValWood** [comment]
If this is the same mechansim as pombe the unproductive  ncRNA transcript is the regulation. it works like this:
https://www.pombase.org/reference/PMID:34389684
(click on the summary image to make it bigger)

The ncRNA is  a non functional transcript that is targeted for degradation by the surveillance machinery, but it is preventing the expression of the coding transcript.

(I don't know how GO should represent this, it's quite complex, related to the alternative polyadenylation coupled termination- I think we have too may ways to say the same thing already, I'm seeing a lot of overlap, but I have not read enough papers to comment fully).

**Comment by pgaudet** [comment]
@RLovering 

We went over this with @colinlog and @ValWood 

For [GO:1901582 positive regulation of telomeric RNA transcription from RNA pol II promoter](http://amigo.geneontology.org/amigo/term/GO:1901582#display-lineage-tab) : Looking at PMID:24500201, ATRX seems to be involved in (among other processes), the Alternative Lengthening of Telomeres pathway. We have a GO term that mentions 'Alternative Lengthening of Telomeres pathway',  defined as 'A telomere maintenance process that results in the formation of a telomeric circle, or t-circle. A t-circle is an extrachromosomal duplex or single-stranded circular DNA molecule composed of t-arrays. T-circles are involved in the control of telomere length **via alternative-lengthening of telomeres (ALT) pathway** and telomere rapid deletion (TRD).' 

but this term is part_of 'telomere maintenance via telomere trimming', which does not not mention the t-circle. 

It seems like the paper you've annotated to GO:1901582 positive regulation of telomeric RNA transcription from RNA pol II promoter](http://amigo.geneontology.org/amigo/term/GO:1901582#display-lineage-tab), [PMID:26055325](http://amigo.geneontology.org/amigo/reference/PMID:26055325), is probably just an effect of the role ATRX plany in the ALT pathways?

**Comment by ValWood** [comment]
I'm having second thoughts about this. The regulation terms are probably OK, if we are allowing RNA species-specific terms ( but in these cases it is confusing to have non- regulation terms like "GO:0097393 telomeric repeat-containing RNA transcription" available.

**Comment by pgaudet** [comment]
@RLovering changed the annotation of  P46100 | ATRX from positive regulation of telomeric RNA transcription from RNA pol II promoter to  to subtelomeric heterochromatin formation

Ready for obsoletion.
