### ISSUE TITLE
term merge GO:0034990	nuclear mitotic cohesin complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23265]
GO:0034990	nuclear mitotic cohesin complex
Merge into mitotic cohesin complex (GO:0030892)

(Same complex)

**Comment by raymond91125** [comment]
There is a note for the parent term nuclear cohesin complex "Note that this term and its children should be used to annotate gene products found in cohesin complexes in organisms that undergo closed mitosis (i.e. where the nuclear envelope does not break down, as in fungi). For organisms in which the nuclear envelope breaks down during mitosis, the parent should be used."

**Comment by raymond91125** [comment]
We could replicate that note here for mitotic cohesin complex to make the intended usage clear.

**Comment by ValWood** [comment]
I believe the current protocol is not to create location specific complete terms  (and to merge existing).

**Comment by ValWood** [comment]
I realise that isn't  what your statement is about.
I don't think it is necessary to replicate the comment. The comment was only required when a nuclear and non-nuclear version existed.

**Comment by raymond91125** [comment]
There are 25 EXP annotations under nuclear cohesin complex, including some for mouse and human genes. I guess that indicates the intended usage was not followed.

**Comment by ValWood** [comment]
Cohesin is nuclear some of the time. It is just that the term does not make sense with current practice. The complex is the same complex if it is in the nucleus or not....
