### ISSUE TITLE
peptidyl-cysteine S-nitrosylase activity (GO:0035605) xrefs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23262]
id: GO:0035605
name: peptidyl-cysteine S-nitrosylase activity
namespace: molecular_function
def: "Catalysis of the transfer of a nitric oxide (NO) group to a sulphur atom within a cysteine residue of a protein." [EC:2.6.99.-, GOC:sp, PMID:20972425, PMID:20972426]
comment: This term should not be used to annotate the nitrosylating action of nitric oxide synthase (NOS) if the nitroso group is synthesized directly on the substrate.
synonym: "protein nitrosylase activity" RELATED [GOC:sp]
synonym: "S-nitrosylase activity" EXACT [PMID:20972426]
is_a: GO:0016769 ! transferase activity, transferring nitrogenous groups
is_a: GO:0140096 ! catalytic activity, acting on a protein

- [x] I _think_ we can add RHEA:66684 to this term? (e.g. see https://www.uniprot.org/uniprot/P04797)
- [x] I don't think it's appropriate/necessary to have the partial EC EC:2.6.99.- as a reference in the def (doesn't look like this specific reaction/enzyme is in EC) - remove this EC ref? (though see #8160)

**Comment by sjm41** [comment]
Hi Harold, I just assigned you to this ticket - hope that's OK!

**Comment by hdrabkin** [comment]
I used to have a report for partial ecs used as defs, but I can't easily generate it anymore myself (OboEDIT's search function much better, but program will no longer run on mac (16bit)).
since there are PMDs it certainly doesn't need the EC at all. 
Thanks will fix.

**Comment by hdrabkin** [comment]
RHEA:67152 might also fit too; will see.

**Comment by hdrabkin** [comment]
[RHEA:66684]   L-cysteinyl-[protein] + S-nitroso-L-cysteinyl-[GAPDH] = L-cysteinyl-[GAPDH] + S-nitroso-L-cysteinyl-[protein]

RHEA:67152   L-cysteinyl-[protein] + S-nitroso-L-cysteinyl-[NO transferase protein] = L-cysteinyl-[NO transferase protein] + S-nitroso-L-cysteinyl-[protein]

**Comment by hdrabkin** [comment]
Based on the GO def
Catalysis of the transfer of a nitric oxide (NO) group to a sulphur atom within a cysteine residue of a protein." 
I'm inclined to use both RHEAs as narrowMatch

**Comment by sjm41** [comment]
ok

**Comment by hdrabkin** [comment]
Done
