### ISSUE TITLE
GO:0004085 butyryl-CoA dehydrogenase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23274]
* **GO term ID and label for which you request a new superclass**
GO:0004085 butyryl-CoA dehydrogenase activity

* **New superclass (parent) suggested**
GO:0003995 acyl-CoA dehydrogenase activity

butyryl-CoA dehydrogenase activity has EC:1.3.8.1 (Short-chain acyl-CoA dehydrogenase), and other acyl-CoA dehydrogenase GO terms all have 'GO:0003995 acyl-CoA dehydrogenase activity' as parent.

**Comment by pgaudet** [comment]
Done in #23497
