### ISSUE TITLE
Wrong parent: GO:0047057 & GO:0047058

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23270]
* **GO term ID and label for which you request a new superclass**
GO:0047057 vitamin-K-epoxide reductase (warfarin-sensitive) activity (EC:1.17.4.4)
GO:0047058 vitamin-K-epoxide reductase (warfarin-insensitive) activity (EC:1.17.4.5)

* **New superclass (parent) suggested**
Current parent is:
GO:0016900 oxidoreductase activity, acting on the CH-OH group of donors, disulfide as acceptor (xref: EC:1.1.4.-)

Based on the current EC xrefs, this should be changed on both to:
GO:0016728 oxidoreductase activity, acting on CH or CH2 groups, disulfide as acceptor (xref: EC:1.17.4.-)

(EC:1.17.4.4/EC:1.17.4.5 was Formerly EC 1.1.4.1/EC 1.1.4.2, which would explain the parentage issue.)

**Comment by hdrabkin** [comment]
done; thanks for catching.
