### ISSUE TITLE
EC xrefs on acyl-CoA dehydrogenase activity (GO:0003995) and children

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23273]
id: GO:0003995
name: acyl-CoA dehydrogenase activity
namespace: molecular_function
alt_id: GO:0019109
def: "Catalysis of the reaction: acyl-CoA + acceptor = 2,3-dehydroacyl-CoA + reduced acceptor." [EC:1.3.99.3]
synonym: "acyl CoA dehydrogenase activity" RELATED [EC:1.3.99.3]
synonym: "acyl coenzyme A dehydrogenase activity" RELATED [EC:1.3.99.3]
synonym: "acyl dehydrogenase activity" RELATED [EC:1.3.99.3]
synonym: "acyl-CoA reductase activity" EXACT [GOC:mah]
synonym: "acyl-CoA:(acceptor) 2,3-oxidoreductase activity" RELATED [EC:1.3.99.3]
synonym: "acyl-CoA:acceptor 2,3-oxidoreductase activity" RELATED [EC:1.3.99.3]
synonym: "fatty acyl coenzyme A dehydrogenase activity" RELATED [EC:1.3.99.3]
synonym: "fatty-acyl-CoA dehydrogenase activity" RELATED [EC:1.3.99.3]
synonym: "general acyl CoA dehydrogenase activity" RELATED [EC:1.3.99.3]
synonym: "long-chain acyl coenzyme A dehydrogenase activity" RELATED [EC:1.3.99.3]
synonym: "long-chain acyl-CoA dehydrogenase activity" RELATED [EC:1.3.99.3]
synonym: "medium-chain acyl-CoA dehydrogenase activity" NARROW [EC:1.3.99.3]
synonym: "medium-chain acyl-coenzyme A dehydrogenase activity" RELATED [EC:1.3.99.3]
xref: EC:1.3.99.3

- [ ] **remove obsolete xref: EC:1.3.99.3 and all associated synonyms from GO:0003995 (EC:1.3.99.3 is transferred to 1.3.8.7, 1.3.8.8 & 1.3.8.9)**

id: GO:0070991
name: medium-chain-acyl-CoA dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: acyl-CoA + acceptor = 2,3-dehydroacyl-CoA + reduced acceptor, where the acyl group is a medium-chain fatty acid residue. A medium chain fatty acid is any fatty acid with a chain length of between C6 and C12." [GOC:BHF, GOC:mah]
synonym: "MCAD activity" EXACT [GOC:mah]
xref: EC:1.3.99.-

- [ ] **change xref to EC 1.3.8.7**

id: GO:0017099
name: very-long-chain-acyl-CoA dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: acyl-CoA + acceptor = 2,3-dehydroacyl-CoA + reduced acceptor, where the acyl group is a very long chain fatty acid residue. A very long-chain fatty acid is a fatty acid which has a chain length greater than C22." [GOC:mah]
synonym: "very long-chain-acyl-CoA dehydrogenase activity" EXACT []
xref: Reactome:R-HSA-548831 "TECR,TECRL dehydrogenate TOD-CoA to ST-CoA"

- [ ] **add xref EC 1.3.8.9**

**Comment by raymond91125** [comment]
Is acyl-CoA dehydrogenase activity equivalent to EC 1.3.8.-
EC Tree
    [ 1 Oxidoreductases]
        [ 1.3 Acting on the CH-CH group of donors]
            [ 1.3.8 With a flavin as acceptor]
@deustp01 Thanks.

**Comment by sjm41** [comment]
@pgaudet You've fixed all of the above in #23497 (including @raymond91125's comment) so I'm closing this one!

**Comment by sjm41** [comment]
Should also add these MetaCyc xrefs:
- short-chain fatty acyl-CoA dehydrogenase activity (GO:0016937) [EC:1.3.8.1, RHEA:47196] -> add MetaCycRXN-13449
- medium-chain fatty acyl-CoA dehydrogenase activity (GO:0070991) [EC:1.3.8.7, RHEA:14477] -> add MetaCyc:RXN-11734
- very-long-chain fatty acyl-CoA dehydrogenase activity (GO:0017099) [EC:1.3.8.9, RHEA:19181] -> add MetaCyc:RXN-13451
