### ISSUE TITLE
Wrong parent: 1-pyrroline-5-carboxylate dehydrogenase activity (GO:0003842)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23277]
* **GO term ID and label for which you request a new superclass**
1-pyrroline-5-carboxylate dehydrogenase activity (GO:0003842) = EC:1.2.1.88 (Formerly EC 1.5.1.12.)

* **New superclass (parent) suggested**
Current parent is: 
oxidoreductase activity, acting on the CH-NH group of donors, NAD or NADP as acceptor (GO:0016646) = EC:1.5.1.-

Should be:
oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor (GO:0016620) = EC:1.2.1.-

**Comment by ValWood** [comment]
>I wonder if there could be a bulk check for any enzymatic parent-child GO relations that have inconsistent EC xrefs? E.g. GO parent term has EC:1.5.1.- but GO child term has EC that doesn't match EC:1.5.1.*

@pgaudet @cmungall don't let this idea from @sjm41 slip by, would be really useful

**Comment by deustp01** [comment]
Tagging @hdrabkin , who is the gate-keeper here and who has already done much of the clean-up in this direction.

**Comment by sjm41** [comment]
ticket for making general check: https://github.com/geneontology/go-ontology/issues/23286

**Comment by pgaudet** [comment]
Emailed @kaxelsen (back in May): 

 Hi,

 RHEA:16417 is mapped to EC 1.2.1.88, but the substrate in this RHEA reaction is (S)-1-pyrroline-5-carboxylate, while EC has L-glutamate 5-semialdehyde.

 I dont think these are the same compounds?

 Thanks, Pascale


@kaxelsen 's answer: 

> Hi Pascale,

> The reaction described in the IUBMB entry (see
https://www.enzyme-database.org/query.php?ec=1.2.1.88) is
RHEA:30235 H2O + L-glutamate 5-semialdehyde + NAD+ = 2 H+ + L-glutamate + NADH

> In addition to this reaction we have added reactions mentioned in the
comments. In this case you can read: " This enzyme catalyses the irreversible
oxidation of glutamate-γ-semialdehyde to glutamate as part of the proline
degradation pathway. (S)-1-pyrroline-5-carboxylate, the product of the first
enzyme of the pathway (EC 1.5.5.2, proline dehydrogenase) is in spontaneous
equilibrium with its tautomer L-glutamate γ-semialdehyde."
This corresponds to:
RHEA:16417 (S)-1-pyrroline-5-carboxylate + 2 H2O + NAD+ = H+ + L-glutamate +
NADH
Which can be split into two steps:
RHEA: 28234 L-glutamate 5-semialdehyde = (S)-1-pyrroline-5-carboxylate + H+ +
H2O (spontaneous)
RHEA:30235 H2O + L-glutamate 5-semialdehyde + NAD+ = 2 H+ + L-glutamate + NADH

> More comment: " The enzyme can also oxidize other 1-pyrrolines, e.g.
3-hydroxy-1-pyrroline-5-carboxylate is converted into 4-hydroxyglutamate and
(R)-1-pyrroline-5-carboxylate is converted into D-glutamate." The first part
corresponds to:
RHEA:31155 (3R,5S)-1-pyrroline-3-hydroxy-5-carboxylate + 2 H2O + NAD+ =
(4S)-4-hydroxy-L-glutamate + H+ + NADH

>The final part of the comment: " NADP+ can also act as acceptor, but with
lower activity "
corresponds to:
RHEA:24882 (S)-1-pyrroline-5-carboxylate + 2 H2O + NADP+ = H+ + L-glutamate +
NADPH
RHEA:24943 (3R,5S)-1-pyrroline-3-hydroxy-5-carboxylate + 2 H2O + NADP+ =
(4S)-4-hydroxy-L-glutamate + H+ + NADPH

> I hope this explains why we have linked these reactions to EC 1.2.1.88.

> Cheers,

> Kristian

**Comment by pgaudet** [comment]
So: 

1. We should edit the definition to match IUBMB:  H2O + L-glutamate 5-semialdehyde + NAD+ = 2 H+ + L-glutamate + NADH
2. map to RHEA:30235 which is the closest reaction

**Comment by pgaudet** [comment]
Also added the other RHEA reactions mentioned: 
+xref: RHEA:16417 {source="skos:broadMatch"}
+xref: RHEA:24882 {source="skos:broadMatch"}
+xref: RHEA:24943 {source="skos:relatedMatch"}
+xref: RHEA:28234 {source="skos:relatedMatch"}
+xref: RHEA:30235 {source="skos:exactMatch"}
+xref: RHEA:31155 {source="skos:relatedMatch"}

We probably dont want to create new GO terms for these. 

Thanks, Pascale
