### ISSUE TITLE
GO:0043458 ethanol biosynthetic process involved in glucose fermentation to ethanol/  vs GO:0019655 glycolytic fermentation to ethanol 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23284]
I don't understand the difference between

GO:0043458 ethanol biosynthetic process involved in glucose fermentation to ethanol
The chemical reactions and pathways resulting in the formation of ethanol, CH3-CH2-OH, as part of the process of glucose catabolism to ethanol, CO2 and ATP.

and the parent
GO:0019655 glycolytic fermentation to ethanol 
The anaerobic chemical reactions and pathways resulting in the breakdown of glucose; it is converted into ethanol and carbon dioxide (CO2), producing two molecules of ATP for each molecule of glucose.

**Comment by pgaudet** [comment]
SGD has annotated to both terms - @srengel can you comment on this one?

**Comment by ukemi** [comment]
Here is what I would deduce from the structure of the ontology and the logical definitions, which unfortunately only ontology editors can see. Glycolytic fermentation has several sublasses, each having a different output at the end. One of those is ethanol (glycolytic fermentation to ethanol).  I suspected that those subclasses all have a conserved subpathway. This  is confirmed in the ontology where it states that glycoytic fermentation starts with some glycolytic process, thus the glycolytic part of the name. So the first part of any glycolytic fermentation are the steps, MFs or subprocesses, in some glycolytic process. By defintion in the ontology, glycolytic processes all end with an output of pyruvate. From pyruvate, the downstream consequences (fermentations) can diverge and one of the fates is to form ethanol (thus the subclass 'glycolytic fermentation to ethanol'). So 'ethanol biosynthetic process involved in glucose fermentation to ethanol' would be the part of 'glycolytic fermentation to ethanol' that happens downstream of the common steps of the glycolytic pathway ie, downstream of the formation of pyruvate. The key here for someone who can't see the ontlology in full that the two processes aren't the same is the  'involved in'. In the past, it always meant part_of.
For annotation, all of the gene products that enable functions in the common glycolytic process portion of the fermentation process would get annotated to the parent. Only those that occur downstream of the pyruvate would be annotated to the ethanol biosynthesis part of the process. Put them all together and you get the whole process.  So if the gene that SGD has annotated to both the parent and child catalyzes one of the steps that is downstream of pyruvate and on the way to Friday night, then your annotations are correct.

**Comment by ValWood** [comment]
I don't really get this. Bother terms seem to begin with a starting point at the beginning of glycolysis (glucose) and end with ethanol?

**Comment by pgaudet** [comment]
Thanks for the explanation @ukemi 

> For annotation, all of the gene products that enable functions in the common glycolytic process portion of the fermentation process would get annotated to the parent

Is this distinction useful @srengel ? Maybe this is more than what the curator and the user need?

**Comment by srengel** [comment]
i don't think the distinction is useful.  we would not make the distinction here while curating, and during my previous years working as a fermentation scientist (consuming GO as a user) this detail would not have been useful for anything practical.

**Comment by ValWood** [comment]
I worry about these has_parts in the ontology  since the users (and curators) never see them. I could not understand the difference between these terms based on the term names OR definitions. They still both sound to me as though they would begin with glucose.

Also a major point, fermentation isn't a descendant of anaerobic respiration? It should be shouldn't it?

<img width="423" alt="Screenshot 2022-05-10 at 16 04 25" src="https://user-images.githubusercontent.com/7359272/167660723-3ff2dd47-ab4b-41e0-8be9-a019956e89d1.png">
