### ISSUE TITLE
New EC xref for diacylglycerol diphosphate phosphatase activity GO:0000810

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23289]
* **GO term ID and label for which you request a new superclass**
diacylglycerol diphosphate phosphatase activity GO:0000810 (EC:3.1.3.81)

* **New superclass (parent) suggested**
Currently has parent of GO:0016462 pyrophosphatase activity (no EC), which is a child of GO:0016818  hydrolase activity, acting on acid anhydrides, in phosphorus-containing anhydrides (EC:3.6.1.-)

From its EC xref, it should have additional parent of GO:0016791 phosphatase activity (EC:3.1.3.-)

EC describes it as a "bifunctional enzyme catalyzes the dephosphorylation of diacylglycerol diphosphate to phosphatidate and the subsequent dephosphorylation of phosphatidate to diacylglycerol l cf. EC [3.1.3.4]...The diacylglycerol pyrophosphate phosphatase activity in Saccharomyces cerevisiae is induced by zinc depletion.".

So, I'm not entirely sure if GO:0016791 should be made an _additional_ parent, or _replace_ the current parent.  Any insights?

Also see previous discussion in #9573

**Comment by sjm41** [comment]
@kaxelsen What's your view on this one?

EC classifies [EC:3.1.3.81](https://enzyme.expasy.org/EC/3.1.3.81) under 3.1.3.- (Phosphoric monoester hydrolases), which corresponds to GO:0016791 phosphatase activity.

But the GO term for EC:3.1.3.81 (GO:0000810 diacylglycerol diphosphate phosphatase activity) is currently in a different branch of GO, being a child of GO:0016462 pyrophosphatase activity, which is itself a child of "hydrolase activity, acting on acid anhydrides, in phosphorus-containing anhydrides GO:0016818" ( EC:3.6.1.-)

Here's the picture of the corresponding [RHEA entry](https://www.rhea-db.org/rhea/27449):
![Screenshot 2022-06-07 at 12 33 08](https://user-images.githubusercontent.com/16306861/172369545-9af3947b-2b96-491f-b13e-97ead5606b9a.png)

Should we change the parent of "GO:0000810 diacylglycerol diphosphate phosphatase activity" to "GO:0016791 phosphatase activity" to be consistent with the EC xref?

**Comment by sjm41** [comment]
Hi @kaxelsen Just checking if you can help with this? Thanks.

**Comment by kaxelsen** [comment]
Hi @sjm41, the enzyme was misclassified by IUBMB. So I have just submitted a transfer to EC 3.6.1.-

**Comment by sjm41** [comment]
Actually, I'll change the title and reopen this so we remember to add the new EC when available.

**Comment by pgaudet** [comment]
Done in #24052
