### ISSUE TITLE
EC:3.6.1.30 is obsolete

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23290]
EC:3.6.1.30 associated with the following GO term is obsolete:

id: GO:0050072
name: m7G(5')pppN diphosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: 7-methylguanosine 5'-triphospho-5'-polynucleotide + H2O = 7-methylguanosine 5'-phosphate + polynucleotide." [EC:3.6.1.30, MetaCyc:M7G5PPPN-PYROPHOSPHATASE-RXN]
synonym: "7-methylguanosine-5'-triphospho-5'-polynucleotide 7-methylguanosine-5'-phosphohydrolase activity" RELATED [EC:3.6.1.30]
synonym: "decapase activity" RELATED [EC:3.6.1.30]
synonym: "M(7)G(5')pppN pyrophosphatase activity" EXACT []
synonym: "m7G(5')pppN pyrophosphatase activity" RELATED [EC:3.6.1.30]
xref: EC:3.6.1.30
xref: MetaCyc:M7G5PPPN-PYROPHOSPHATASE-RXN
is_a: GO:0016462 ! pyrophosphatase activity

(this is mentioned in #17844 but it hasn't been fixed yet)

EC (https://enzyme.expasy.org/EC/3.6.1.30) says EC:3.6.1.30 has been transferred to 2 entries:

[3.6.1.59](https://enzyme.expasy.org/EC/3.6.1.59):
NAME: 5'-(N(7)-methyl 5'-triphosphoguanosine)-[mRNA] diphosphatase.
REACTION: A 5'-(N(7)-methyl 5'-triphosphoguanosine)-[mRNA] + H(2)O <=> N(7)-methylguanosine 5'-phosphate + a 5'-diphospho-[mRNA]
=> This is RHEA [65384](https://www.rhea-db.org/rhea/65384) / [65388](https://www.rhea-db.org/rhea/65388)

[3.6.1.62](https://enzyme.expasy.org/EC/3.6.1.62):
NAME: 5'-(N(7)-methylguanosine 5'-triphospho)-[mRNA] hydrolase.
REACTION: 5'-(N(7)-methylguanosine 5'-triphospho)-[mRNA] + H(2)O <=> N(7)-methylguanosine 5'-diphosphate + 5'-phospho-[mRNA]
=> this is [RHEA:67484](https://www.rhea-db.org/rhea/67484)

Neither of the two replacement EC numbers (or their corresponding RHEAs) appear to be in the current GO.

I'm not sure of the appropriate fix here.... @hdrabkin ??

**Comment by pgaudet** [comment]
The 2 EC correspond to the specificity of the enzymes. We should create the 2 activities, obsolete GO:0050072 and add 'consider' the two activities. 

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140932
+name: 5'-(N(7)-methyl 5'-triphosphoguanosine)-[mRNA] diphosphatase activity
+def: "Catalysis of the reaction: a 5'-end (N2,N2,N7-trimethyl 5'-triphosphoguanosine)-ribonucleoside in mRNA + H2O = a 5'-end diphospho-ribonucleoside in mRNA + 2 H+ + N7-methyl-GMP. Can also use (N7-methyl 5'-triphosphoguanosine)-ribonucleoside in mRNA as a substrate." [PMID:24742626, PMID:32723815]
+synonym: "m(7)GpppN m(7)GMP phosphohydrolase activity" EXACT [EC:3.6.1.59]
+synonym: "m(7)GpppX diphosphatase activity" EXACT [EC:3.6.1.59]
+synonym: "m(7)GpppX pyrophosphatase activity" EXACT [EC:3.6.1.59]
+xref: EC:3.6.1.59 {source="skos:exactMatch"}
+xref: RHEA:65384 {source="skos:narrowMatch"}
+xref: RHEA:65388 {source="skos:narrowMatch"}
+is_a: GO:0034353 ! mRNA 5'-diphosphatase activity
+created_by: pg
+creation_date: 2022-10-24T15:37:32Z
+
+[Term]
+id: GO:0140933
+name: 5'-(N(7)-methylguanosine 5'-triphospho)-[mRNA] hydrolase activity
+def: "Catalysis of the reaction:  a 5'-end (N7-methyl 5'-triphosphoguanosine)-ribonucleoside in mRNA + H2O = a 5'-end phospho-ribonucleoside in mRNA +  N7-methyl-GDP + H+." [PMID:18820299, PMID:29483298]
+xref: EC:3.6.1.62
+xref: RHEA:67484
+is_a: GO:0140818 ! mRNA 5'-phosphatase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23290 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-24T15:48:42Z

**Comment by pgaudet** [comment]
- [ ] Announce obsoletion 
- [ ] Create annotation review ticket

**Comment by pgaudet** [comment]
@hdrabkin does that seem reasonable to you?

**Comment by hdrabkin** [comment]
@pgaudet these look fine.

H

**Comment by ValWood** [comment]
what about
GO:1990521 | m7G(5')pppN diphosphatase activator activity ?

**Comment by hdrabkin** [comment]
@ValWood ; can you expand comment?

**Comment by ValWood** [comment]
you are obsoleting
 GO:0050072 name: m7G(5')pppN diphosphatase activity

what about
GO:1990521 | m7G(5')pppN diphosphatase activator activity

(I would like to do both at the same time, as we need to also fix all FYPO ids that use in logical defes too)

**Comment by hdrabkin** [comment]
It would make sense then to obsolete the activator activity if the activity that is being activiated is obsolete.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 

GO:0050072 m7G(5')pppN diphosphatase activity
 GO:1990521  m7G(5')pppN diphosphatase activator activity
 GO:1903398 regulation of m7G(5')pppN diphosphatase activity
 GO:1903399 positive regulation of m7G(5')pppN diphosphatase activity 

The reason for obsoletion is that the corresponding EC term has been obsoleted. The term has been replaced by two activities: 
- GO:0140932 5'-(N(7)-methyl 5'-triphosphoguanosine)-[mRNA] diphosphatase activity 
- GO:0140933  5'-(N(7)-methylguanosine 5'-triphospho)-[mRNA] hydrolase activity 

There are EXP annotations by GeneBD, PomBase, WormBase, and one mapping by InterPro. This term is not present in any subsets. 

You can comment on the ticket: 

https://github.com/geneontology/go-ontology/issues/23290


Thanks, Pascale

**Comment by ValWood** [comment]
Which term replac es 
GO:1990521 m7G(5')pppN diphosphatase **activator** activity
thanks
Val

**Comment by ValWood** [comment]
I thought we would create a regulator activity if the regulator is specifically an activator for a specific activity.  At least we have until now?
For sure we would need a more specific term than 'phosphatase activator activity', otherwise it will look a bit weird, as though we could not annotate any more specifically, even though there are children.

 mRNA phosphatase activator activity could work,  because at the moment this is the only one  I have, but what happens if there are other mRNA phosphatase activators with different specificities (i.e. not for the  mRNA guanine cap), then we can't distinguish them by MF even though we know they have different activities.
