### ISSUE TITLE
NTR: glycine betaine:sodium:chloride symporter activity

### ISSUE THREAD

**Issue by ccasalsc** [geneontology/go-ontology#23298]
Please provide as much information as you can: 

* **Suggested term label:** glycine betaine:sodium:chloride symporter activity

* **Definition (free text)** Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: glycine betaine(out) + Na+(out) + Cl-(out)= glycine betaine(in) + Na+(in) + Cl-(in). 

* **Reference, in format PMID:10358010**

* **Gene product name and ID to be annotated to this term  SLC6A12  P27799**

* **Parent term(s)** ~GO:0031460 glycine betaine transport~ 
* (from @pgaudet:)  This is a process; I'll use symporter activity or a child 

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
sodium/chloride-dependent glycine betaine transporter activity | broad
betaine/GABA:sodium symporter activity | exact

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
Rhea:71175

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140814
+name: glycine betaine:sodium:chloride symporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: glycine betaine(out) + Na+(out) + Cl-(out)= glycine betaine(in) + Na+(in) + Cl-(in)." [PMID:10358010]
+synonym: "betaine/GABA:sodium symporter activity" EXACT []
+synonym: "sodium/chloride-dependent glycine betaine transporter activity" BROAD []
+xref: RHEA:71175
+intersection_of: GO:0015293 ! symporter activity
+intersection_of: has_primary_input CHEBI:17750 ! glycine betaine
+intersection_of: has_primary_input CHEBI:17996 ! chloride
+intersection_of: has_primary_input CHEBI:29101 ! sodium(1+)
+relationship: part_of GO:0031460 ! glycine betaine transport
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23298 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-12T06:05:59Z
+
