### ISSUE TITLE
Non-specific mentions of EC:6.2.1.3

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23296]
Please remove mentions (attributions) of EC:6.2.1.3 (Long-chain-fatty-acid--CoA ligase) from the definitions of these two terms:

id: GO:0031955
name: short-chain fatty acid-CoA ligase activity
def: "Catalysis of the reaction: ATP + a short-chain fatty acid + CoA = AMP + diphosphate + an acyl-CoA; short-chain fatty acids are fatty acids with a chain length of less than C6." [EC:6.2.1.3, GOC:mah]

id: GO:0031957
name: very long-chain fatty acid-CoA ligase activity
def: "Catalysis of the reaction: ATP + a very-long-chain fatty acid + CoA = AMP + diphosphate + an acyl-CoA; a very long-chain fatty acid is a fatty acid which has a chain length greater than C22." [EC:6.2.1.3, GOC:mah]

I'm not sure if there's agreement on what the cut-offs are for short/medium/long/very long fatty acids, but the EC entry for EC:6.2.1.3 (Long-chain-fatty-acid--CoA ligase) doesn't really help/support with the GO defs above  - it just says "The liver enzyme acts on acids from C(6) to C(20); that from brain shows high activity up to C(24)."

EC:6.2.1.3 is already correctly an xref on this term:
id: GO:0004467
name: long-chain fatty acid-CoA ligase activity
def: "Catalysis of the reaction: ATP + a long-chain fatty acid + CoA = AMP + diphosphate + an acyl-CoA; a long-chain fatty acid is a fatty acid with a chain length between C13 and C22." [RHEA:15421]
xref: EC:6.2.1.3

**Comment by hdrabkin** [comment]
Well, I guess EC:6.2.1.3 shouldn't be with : GO:0031955; I'm on the fence with id: GO:0031957

**Comment by sjm41** [comment]
_I'm on the fence with id: GO:0031957_
If we want to keep EC:6.2.1.3 associated with that, then it should be promoted to an xref rather than just in the definition...

But given EC:6.2.1.3 is already an accurate (1:1) xref on GO:0004467, I'd say it shouldn't appear in the xref/def of any other term.

**Comment by hdrabkin** [comment]
Done
