### ISSUE TITLE
NTR: [Urate:anion antiporter activity]

### ISSUE THREAD

**Issue by LucillePo** [geneontology/go-ontology#23306]
* **Suggested term label:**
Urate:anion antiporter activity
* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: urate(out) + anion (in) = urate (in) + anion (out). 
* **Reference, in format PMID:#######**
PubMed=18411268 Fig8b, 9b; 
PubMed=12024214 Fig3
* **Gene product name and ID to be annotated to this term**
URAT1/SLC22A12 (Q96S37), OAT10/SLC22A13 (Q9Y226)
* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
urate: organic anion antiporter activity | narrow
* **Parent term(s)**
GO:0015301 anion:anion antiporter activity; GO:0015143 urate transmembrane transporter activity; GO:0008514 organic anion transmembrane transporter activity

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140813
+name: urate:anion antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: urate(out) + anion (in) = urate (in) + anion (out)." [PMID:12024214, PMID:18411268]
+synonym: "urate:organic anion antiporter activity" NARROW []
+is_a: GO:0015301 ! anion:anion antiporter activity
+intersection_of: GO:0015297 ! antiporter activity
+intersection_of: has_primary_input CHEBI:22563 ! anion
+intersection_of: has_primary_input CHEBI:30848 ! urate(1-)
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23306 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-12T05:57:12Z
+

**Comment by pgaudet** [comment]
@LucillePo Can you confirm that CHEBI:30848 ! urate(1-) is correct ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
From @LucillePo and Nevila Nouspikel - 
urate has no charge at pH7.3. 
CHEBI should be CHEBI:17775 ! 7,9-dihydro-1H-purine-2,6,8(3H)-trione
and NOT CHEBI:30848 ! urate(1-)


Also, this is then not an anion antiporter, but just an antiporter.

**Comment by pgaudet** [comment]
I will change all terms using CHEBI:30848 ! urate(1-) to CHEBI:17775 ! 7,9-dihydro-1H-purine-2,6,8(3H)-trione: 
- GO:0015747 urate transport
-  GO:0046415 urate metabolic process 
- GO:0034418 urate biosynthetic process
- GO:0019628 urate catabolic process
