### ISSUE TITLE
NTR: [orotate:anion antiporter activity]

### ISSUE THREAD

**Issue by LucillePo** [geneontology/go-ontology#23307]
* **Suggested term label:**
Orotate:anion antiporter activity

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: orotate(out) + anion (in) = orotate (in) + anion (out). 

* **Reference, in format PMID:#######**
PubMed=21350910 Fig1d; 
PubMed=35144162 Fig 2-6

* **Gene product name and ID to be annotated to this term**
URAT1/SLC22A12 (Q96S37), OAT10/SLC22A13 (Q9Y226)

* **Parent term(s)**
GO:0015301 anion:anion antiporter activity; GO:0008514 organic anion transmembrane transporter activity

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
orotate: organic anion antiporter activity | narrow

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140812
+name: orotate:anion antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: orotate(out) + anion (in) = orotate (in) + anion (out)." [PMID:21350910, PMID:35144162]
+synonym: "orotate:organic anion antiporter activity" NARROW []
+is_a: GO:0008514 ! organic anion transmembrane transporter activity
+is_a: GO:0015301 ! anion:anion antiporter activity
+intersection_of: GO:0015297 ! antiporter activity
+intersection_of: has_primary_input CHEBI:22563 ! anion
+intersection_of: has_primary_input CHEBI:30839 ! orotate
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23307 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-12T05:51:36Z
+
