### ISSUE TITLE
NTR: [NAD+-protein-histidine ADP-ribosyltransferase activity] [NAD+-histone-serine ADP-ribosyltransferase activity (H2B-S6 specific)] [NAD+-histone-serine ADP-ribosyltransferase activity (H3-S10 specific)]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#23309]
Hi GO,

while reannotating the PARP enzymes, I would need a bunch of GO terms.

Thanks

Sylvain

1)
NAD+-protein-histidine ADP-ribosyltransferase activity
Catalysis of the reaction: L-histidyl-[protein] + NAD+ = H+ + Nt-(ADP-D-ribosyl)-L-histidyl-[protein] + nicotinamide 
child of GO:1990404 NAD+-protein ADP-ribosyltransferase activity
Xref Rhea:72071
PMID:35393539

2)
NAD+-histone-serine ADP-ribosyltransferase activity (H2B-S6 specific)
Catalysis of the transfer of ADP-ribose groups to the serine-6 or an equivalent residue of the N-terminal tail of histone H2B. 
child of GO:0140805 NAD+-protein-serine ADP-ribosyltransferase activity
PMID:34874266

3)
NAD+-histone-serine ADP-ribosyltransferase activity (H3-S10 specific)
Catalysis of the transfer of ADP-ribose groups to the serine-10 or an equivalent residue of the N-terminal tail of histone H3. 
child of GO:0140805 NAD+-protein-serine ADP-ribosyltransferase activity
PMID:34874266

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140815
+name: NAD+-protein-histidine ADP-ribosyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-histidyl-[protein] + NAD+ = H+ + Nt-(ADP-D-ribosyl)-L-histidyl-[pro
tein] + nicotinamide." [PMID:35393539]
+xref: RHEA:72071
+is_a: GO:1990404 ! NAD+-protein ADP-ribosyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23309 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-12T07:49:41Z
+
+[Term]
+id: GO:0140816
+name: NAD+-histone-serine ADP-ribosyltransferase activity (H2B-S6 specific)
+namespace: molecular_function
+def: "Catalysis of the transfer of ADP-ribose groups to the serine-6 or an equivalent residue of the N-terminal tail of histone H2B." [PMID:34874266]
+is_a: GO:0140805 ! NAD+-protein-serine ADP-ribosyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23309 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-12T07:52:48Z
+
+[Term]
+id: GO:0140817
+name: NAD+-histone-serine ADP-ribosyltransferase activity (H3-S10 specific)
+namespace: molecular_function
+def: "Catalysis of the transfer of ADP-ribose groups to the serine-10 or an equivalent residue of the N-terminal tail of histone H3." [PMID:34874266]
+is_a: GO:0140805 ! NAD+-protein-serine ADP-ribosyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23309 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-12T07:53:59Z
+
