### ISSUE TITLE
NTR: mRNA 5'-phosphatase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23319]
Please provide as much information as you can: 

* **Suggested term label:**
mRNA 5'-phosphatase activity

* **Definition (free text)**
A 5'-triphospho-[mRNA] + H(2)O <=> a 5'-diphospho-[mRNA] + H+ + phosphate

* **Reference, in format PMID:#######**
PMID: 9473487

* **Gene product name and ID to be annotated to this term**
human RNGTT (O60942)
fly mRNA-cap (FBgn0030556/Q9VY44)

* **Parent term(s)**
polynucleotide 5'-phosphatase activity (GO:0004651)

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
5'-polynucleotidase.[BROAD]
Polynucleotide 5'-triphosphatase.[BROAD]
mRNA capping enzyme [EXACT]

* **Cross-references**
EC 3.6.1.74
[RHEA:67004](https://www.rhea-db.org/rhea/67004)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140818
+name: mRNA 5'-phosphatase activity
+namespace: molecular_function
+def: "A 5'-end triphospho-[mRNA] + H(2)O = a 5'-end diphospho-[mRNA] + H+ + phosphate." [PMID:9473487]
+synonym: "mRNA 5'-triphosphate monophosphatase activity" EXACT []
+xref: EC:3.6.1.74
+xref: RHEA:67004
+is_a: GO:0004651 ! polynucleotide 5'-phosphatase activity
+is_a: GO:0140098 ! catalytic activity, acting on RNA
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23319 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-16T06:01:07Z

**Comment by sjm41** [comment]
Thanks.

**Comment by sjm41** [comment]
Sorry @pgaudet , but it looks like I got the parent wrong for this one....

According to EC classification, the parent of the new term mRNA 5'-phosphatase activity (= EC:3.6.1.74) should be GO:0016818 "hydrolase activity, acting on acid anhydrides, in phosphorus-containing anhydrides" (= EC:3.6.1.-)

So can you change 
is_a: GO:0004651 ! polynucleotide 5'-phosphatase activity
to
is_a: GO:0016818 ! hydrolase activity, acting on acid anhydrides, in phosphorus-containing anhydrides

**Comment by pgaudet** [comment]
Good catch! 

I suggest we obsolete the grouping class 'GO:0098518 polynucleotide phosphatase activity' (no EC, no annotations), because it's confusing not to have mRNA 5'-phosphatase activity under there. 

What do you think ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0098518 polynucleotide phosphatase activity'. The reason for obsoletion is that this represents an unnecessary grouping class. There are no annotations to this term. This term is not present in any subset. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/23319

Thanks, Pascale

**Comment by pgaudet** [comment]
Phosphatase activity has xref 3.1.3.- so that would be inconsistent with GO:0140818's classification as a 3.6.-.-.

**Comment by sjm41** [comment]
Hmmm, interesting....

EC has lots of "phosphatases" under 3.6.1.- in addition to those under 3.1.3.- (as well as some under 3.1.7.-, 3.1.8.-, 3.7.1.-, 3.9.1.-)

See https://enzyme.expasy.org/EC/3.6.1.-

@kaxelsen Should EC:3.6.1.- enzymes be classified as "phosphatases" or not?

Currently we have:
id: GO:0016791
name: phosphatase activity
def: "Catalysis of the hydrolysis of phosphoric monoesters, releasing inorganic phosphate." [GOC:curators, GOC:pg]
xref: EC:3.1.3.- (= Phosphoric monoester hydrolases)

id: GO:0016818
name: hydrolase activity, acting on acid anhydrides, in phosphorus-containing anhydrides
def: "Catalysis of the hydrolysis of any acid anhydride which contains phosphorus." [GOC:jl]
xref: EC:3.6.1.- (= Hydrolases, Acting on acid anhydrides, In phosphorus-containing anhydrides)

**Comment by kaxelsen** [comment]
The sub-subclass EC 3.6.1 covers hydrolases (EC 3) acting on acid anhydrides (EC 3.6) In phosphorus-containing anhydrides (EC 3.6.1).

So this sub-subclass covers di- and triphosphatases and acylphosphatases were the hydrolysis produces a carboxylate and a phosphate (see EC 3.6.1.7, RHEA:14965), so yes, they are phosphatases.

**Comment by pgaudet** [comment]
So is the problem that GO:0016791 phosphatase activity is linked to the wrong EC? 
Or phosphatases act by 2 mechanisms?

**Comment by pgaudet** [comment]
That probably makes sense - although it's an exact synonym but in this case it would help to be more precise. 

Do we want a general 'phosphatases' grouping class?

**Comment by kaxelsen** [comment]
The difference is the chemical nature of the substrate. EC 3.1.3 enzymes produce a hydroxy group and a phosphate, EC 3.6.1 enzymes produce a carboxy or phosphate group and a phosphate.

**Comment by pgaudet** [comment]
The more general issues will be fixed in #23401
