### ISSUE TITLE
GO:0070579  methylcytosine dioxygenase activity - add EC xref?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23312]
Can't recall policy on adding 'provisional' EC xrefs, but this GO term:

id: GO:0070579
name: methylcytosine dioxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: methylcytosine + 2-oxoglutarate + O2 = 5-hydroxymethylcytosine + succinate + CO2." [PMID:19372391]

corresponds to EC 1.14.11.n2 (https://enzyme.expasy.org/EC/1.14.11.n2)
Methylcytosine dioxygenase.
DNA 5-methylcytosine + 2-oxoglutarate + O(2) <=> DNA 5-hydroxymethylcytosine + succinate + CO(2)

**Comment by hdrabkin** [comment]
When I come across them I usually email EC to see if there is an update. I can do so with this one

**Comment by pgaudet** [comment]
From yesterday's ontology call, we can add these provisional ECs.

**Comment by hdrabkin** [comment]
Add EC:1.14.11.n2 and RHEA:52636
