### ISSUE TITLE
Textual definition update: 

### ISSUE THREAD

**Issue by manulera** [geneontology/go-ontology#23317]
* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request a definition update**

GO:0110162: regulation of mitotic spindle elongation (spindle phase three)
GO:0110163: negative regulation of mitotic spindle elongation (spindle phase three)
GO:0110164: positive regulation of mitotic spindle elongation (spindle phase three)

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**

GO:0110162: Any process that modulates the frequency, rate or extent of the cell cycle process in which the distance is lengthened between poles of the mitotic spindle during mitotic ~~prophase~~ <ins>anaphase B</ins> (spindle phase three) PMID:27697865

GO:0110163: Any process that stops, prevents or reduces the frequency, rate or extent of the cell cycle process in which the distance is lengthened between poles of the mitotic spindle during mitotic ~~prophase~~ <ins>anaphase B</ins> (spindle phase three). PMID:27697865

GO:0110164: Any process that activates or increases the frequency, rate or extent of the cell cycle process in which the distance is lengthened between poles of the mitotic spindle during mitotic ~~prophase~~ <ins>anaphase B</ins> (spindle phase three). PMID:27697865

* **Reference(s)**
PMID:27697865

* **Additional information**

The definitions of these terms are wrong. Phase 3 of spindle elongation is anaphase B, not prophase. Quoted text from the article cited in the term definition PMID:27697865:

> Spindle assembly in S. pombe is similar to that in other eukaryotes and can be divided into three phases corresponding to prometaphase (I), metaphase/anaphase A (II), and anaphase B (III). Phase I spindles rapidly elongate to approximately 1.5 μm, while phase II spindles are much less dynamic, with a length of up to 3 μm. Phase III spindles rapidly elongate to 10 to 12 μm ([8](https://journals.asm.org/doi/10.1128/MCB.00330-16#core-B8), [9](https://journals.asm.org/doi/10.1128/MCB.00330-16#core-B9)). In phase II, sister chromosomes need to become bioriented, and the cell will stay in this phase until biorientation has been achieved.

Probably annotations should be revised in case they were made based on the definition and not the term name.

**Comment by manulera** [comment]
Hi @ValWood, tagging you here, not sure if I have to mention someone when making these kind of requests.

**Comment by ValWood** [comment]
The  only annotations to this term for any species are 3 from PomBase:
https://www.pombase.org/term/GO:0061805

and they are all "phase" 3 so although not best practice,  I think it would be OK to tweak the def to match the intent in the term name.

**Comment by manulera** [comment]
Agreed, went into the references, and indeed they are annotated to phase 3, so they are correct, we would just need the definitions of these tree terms to be changed as indicated above.
