### ISSUE TITLE
Two GO terms with EC:3.1.4.3

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23316]
id: GO:0004629
name: phospholipase C activity
def: "Catalysis of the reaction: a phospholipid + H2O = 1,2-diacylglycerol + a phosphatidate." [EC:3.1.4.3, GOC:mah]
xref: EC:3.1.4.3

id: GO:0034480
name: phosphatidylcholine phospholipase C activity
def: "Catalysis of the reaction: phosphatidylcholine + H2O = 1,2-diacylglycerol + a choline phosphate." [EC:3.1.4.3, GOC:mah]
xref: EC:3.1.4.3
xref: RHEA:10604
is_a: GO:0004629 ! phospholipase C activity

[EC:3.1.4.3](https://enzyme.expasy.org/EC/3.1.4.3) reaction is defined as:
A phosphatidylcholine + H(2)O <=> 1,2-diacyl-sn-glycerol + phosphocholine

So can you remove EC:3.1.4.3 as an xref and from the def of GO:0004629 please (which is a grouping term in GO anyway).

**Comment by pgaudet** [comment]
Actually there are 3 terms with EC:3.1.4.3, the third being GO:0050429 calcium-dependent phospholipase C activity. 

I will also remove EC:3.1.4.3 from GO:0050429, I dont think this is the same actvity. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Also removed MetaCyc:PHOSPHOLIPASE-C-RXN from  GO:0004629 phospholipase C activity
That reaction also describes phosphatidylcholine as a substrate: https://biocyc.org/META/NEW-IMAGE?type=NIL&object=PHOSPHOLIPASE-C-RXN

**Comment by pgaudet** [comment]
Also fixed the definition to match RHEA and the def xref from EC to RHEA. 
Old def:  "Catalysis of the reaction: a phospholipid + H2O = 1,2-diacylglycerol + a phosphatidate." 

New def: "Catalysis of the reaction: a 1,2-diacyl-sn-glycero-3-phosphocholine + H2O = a 1,2-diacyl-sn-glycerol + H+ + phosphocholine."

**Comment by sjm41** [comment]
Thanks!
