### ISSUE TITLE
GO:0097363 protein O-GlcNAc transferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23320]
id: GO:0097363
name: protein O-GlcNAc transferase activity
def: "Catalysis of the reaction: UDP-N-acetyl-D-glucosamine + [protein]-L-serine = UDP + [protein]-3-O-(N-acetyl-D-glucosaminyl)-L-serine, or UDP-N-acetyl-D-glucosamine + [protein]-L-threonine = UDP + [protein]-3-O-(N-acetyl-D-glucosaminyl)-L-threonine." [GOC:jsg, GOC:sart, PMID:22158438]
xref: EC:2.4.1.255
is_a: GO:0016757 ! glycosyltransferase activity
is_a: GO:0140096 ! catalytic activity, acting on a protein

I think the "is_a: GO:0016757 ! glycosyltransferase activity" should be changed to "is_a: GO:0008375 ! acetylglucosaminyltransferase activity".

This would then match the parentage of the related term "GO:0016262 protein N-acetylglucosaminyltransferase activity".

Should also consider making the term names of those two terms similar, either:
protein O-GlcNAc transferase activity & protein N-GlcNAc transferase activity
or
protein O-acetylglucosaminyltransferase activity & protein N-acetylglucosaminyltransferase activity

**Comment by hdrabkin** [comment]
The term could also use two RHEAs as narrowmatch depending on the target amino acid

RHEA:48904 L-seryl-[protein] + UDP-N-acetyl-α-D-glucosamine = 3-O-(N-acetyl-β-D-glucosaminyl)-L-seryl-[protein] + H+ + UDP 

 RHEA:48908 L-threonyl-[protein] + UDP-N-acetyl-α-D-glucosamine = 3-O-(N-acetyl-β-D-glucosaminyl)-L-threonyl-[protein] + H+ + UDP

**Comment by hdrabkin** [comment]
Adjusted names to 
protein O-acetylglucosaminyltransferase activity & protein N-acetylglucosaminyltransferase activity
made protein O-GlcNAc transferase activity &  protein N-GlcNAc transferase activity exact synonyms respectively.

**Comment by hdrabkin** [comment]
done

**Comment by sjm41** [comment]
Thanks Harold.
