### ISSUE TITLE
Improve label and def of GO:0098676 modulation of host virulence by virus

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23326]
Looking at the Viral Zone description of this term, https://viralzone.expasy.org/3965, this term describes a interaction between 3 organisms. We'd like to clarify the definition.

**Comment by pgaudet** [comment]
definition needs to be improved: Current def: Any process by which a virus modulates the ability of its host to infect and/or damage an organism for which it is a host. Typically this involves a phage modulating the virulence of a bacterium. Mechanisms include the expression of factors that modulate a bacterial adhesion to a host cell, spread through host tissues, production of exotoxins or provide protection against host immune defenses.

Proposed:  A process by which a virus improves the virulence of its host for that host's respective host. Common in but not limited to bacteriophages; also occurs in phage-bearing bacteria infecting plants or animals for example. Mechanisms include the expression of factors that modulate a bacterial adhesion to a host cell, spread through host tissues, production of exotoxins or provide protection against host immune defenses.


PMID:23981100 -> enhancing host defense response to a third organism
PMID:10913072 -> phenotype, remove from def xref
PMID:11553559 -> OK keep 
Add PMID:8658163

**Comment by pgaudet** [comment]
@pmasson55 can you please check that the proposed changes are OK from your perspective?

**Comment by pmasson55** [comment]
Hi Pascale 

The new definition looks good.  Do you need more example or are you good to go?
Let me know if you require more info.
Patrick.

**Comment by pgaudet** [comment]
No it's fine, I just wanted to make sure this looked OK to you.
