### ISSUE TITLE
Textual definition/xref update: GO:0070224 sulfide:quinone oxidoreductase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23325]
id: GO:0070224
name: sulfide:quinone oxidoreductase activity
def: "Catalysis of the reaction: hydrogen sulfide + a quinone = S0 + a hydroquinone." [MetaCyc:R17-RXN]
synonym: "sulfide-quinone reductase activity" EXACT [MetaCyc:MONOMER-12314]
synonym: "sulphide:quinone oxidoreductase activity" EXACT [GOC:mah]
xref: MetaCyc:R17-RXN
xref: Reactome:R-HSA-1614665 "SQR oxidizes sulfide to bound persulfide"
xref: RHEA:30239
is_a: GO:0016672 ! oxidoreductase activity, acting on a sulfur group of donors, quinone or similar compound as acceptor

Looks like this term covers these two ECs:

ID: EC:1.8.5.4
Name: Bacterial sulfide:quinone reductase.
Def: n sulfide + n quinone <=> polysulfide + n quinol
(this is RHEA:30239, which is the current xref on the GO term)

ID: EC:1.8.5.8
Name: Eukaryotic sulfide quinone oxidoreductase.
Def: Hydrogen sulfide + glutathione + a quinone <=> S-sulfanylglutathione + a quinol
(this is RHEA:55156)

Not sure what to do here....  Make two new child terms corresponding to the specific ECs/RHEAs and update GO:0070224 appropriately?

**Comment by sjm41** [comment]
Hi @hdrabkin What do you think we should do here?

**Comment by hdrabkin** [comment]
This appears to be a big mess

RHEA:30239 quinone + H(+) + HS = a quinol + **S** 
Does not seem to describe GO:0070224 "Catalysis of the reaction: hydrogen sulfide + a quinone = **S0** + a hydroquinone." [MetaCyc:R17-RXN]

ID: EC:1.8.5.8
Name: **Eukaryotic** sulfide quinone oxidoreductase.
Def: Hydrogen sulfide + glutathione + a quinone <=> S-sulfanylglutathione + a quinol
(this is RHEA:55156)
Seems very different in that it uses glutathione and the others do not.  I cringe at the term name also.

**Comment by pgaudet** [comment]
Discussing with @amorgat: EC:1.8.5.4 describes the same reaction as GO:0070224, but is prokaryote-specific. I added the xref as narrowMatch. 

+ added a comment:  Note that EC:1.8.5.4 describes the reaction as bacterial-specific, but it has been observed in eukaryotes (PMID:22852582, PMID:10224084).

**Comment by pgaudet** [comment]
EC:1.8.5.8 does appear to be a different reaction - additionally transferring the S to glutathione. 

@amorgat is looking into this. 

Thanks, Pascale

**Comment by sjm41** [comment]
FYI, I see 3 Swiss-Prot entries annotated with EC:1.8.5.8 and GO:0070224
https://www.uniprot.org/uniprot/?query=ec%3A1.8.5.8&sort=score

**Comment by hdrabkin** [comment]
Just looking again
RHEA:30239 is 'n a quinone + n H+ + n hydrogen sulfide = n a quinol + n sulfur'
GO:0070224 is 'H2S (hydrogen sulfide) + a quinone = S0 (sulfane sulfur) + a hydroquinone.'
quinol is a synonym for hydroquinone (CHEBI( but 
what is 'sulfane sulfur" : The term, “sulfane,” designates sulfur atoms that are bonded covalently in chains only to other sulfur atoms.  (https://doi.org/10.1016/0076-6879(87)43009-7)

But I don't see GO:0070224 being a parent for the other 
ID: EC:1.8.5.4   Product is a polysulfide, not free S
ID: EC:1.8.5.8  glutathione + a quinone <=> S-sulfanylglutathione + a quinol
(this is RHEA:55156)

**Comment by hdrabkin** [comment]
Need new terms?

**Comment by sjm41** [comment]
I think Pascale and Anne agreed earlier in thread that GO:0070224 = RHEA:30239 = EC:1.8.5.4.

The issue is that there are 3 Swiss-Prot annotations to GO:0070224 that are co-annotated to the other EC, EC:1.8.5.8/RHEA:55156:
https://www.uniprot.org/uniprot/?query=ec%3A1.8.5.8&sort=score

And one of those annotations is used in a PAINT annotation (PTN000066985) which affects a fly gene (at least!)

So...looks to me like we need to:

- [ ] get a new GO term equivalent to EC:1.8.5.8/RHEA:55156
- [ ] use that term to reannotate those 3 Swiss-Prot entries.
- [ ] update PTN000066985

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106436
+name: eukaryotic sulfide quinone oxidoreductase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: a quinone + glutathione + H(+) + hydrogen sulfide <=> a quinol + S-sulfanylglutathione." [RHEA:55156]
+xref: EC:1.8.5.8
+xref: RHEA:55156
+is_a: GO:0016672 ! oxidoreductase activity, acting on a sulfur group of donors, quinone or similar compound as acceptor
+property_value: creation_date 2022-10-07T00:15:41Z xsd:dateTime
+created_by: hjd

Note: exceptor for annotation to the human protein, all other annotations to GO:0070224 based on ISS/ISO evidence

**Comment by pgaudet** [comment]
Do you think we can find a better label for this new term?

**Comment by sjm41** [comment]
How about "glutathione-dependent sulfide quinone oxidoreductase activity"?

**Comment by hdrabkin** [comment]
Good suggestion @sjm41; the name changed. closing ticket
