### ISSUE TITLE
NTR: [NAD+-histone-glutamate ADP-ribosyltransferase activity (H2B-E35 specific)] [histone kinase activity (H2B-S36 specific)]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#23323]
Hi GO,
I would need a couple of terms for 2 histone modifications that are not yet described in GO

Thanks

Sylvain

1)
NAD+-histone-glutamate ADP-ribosyltransferase activity (H2B-E35 specific)
Catalysis of the transfer of ADP-ribose groups to the glutamate-35 or an equivalent residue of the N-terminal tail of histone H2B.
child of GO:0140807 NAD+-protein-glutamate ADP-ribosyltransferase activity
PMID:32822587

2)
histone kinase activity (H2B-S36 specific)
Catalysis of the transfer of a phosphate group to the serine-36 residue of the N-terminal tail of histone H2B.
child of GO:0035174 histone serine kinase activity
PMID:32822587

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140822
+name: NAD+-histone-glutamate ADP-ribosyltransferase activity (H2B-E35 specific)
+namespace: molecular_function
+def: "Catalysis of the transfer of ADP-ribose groups to the glutamate-35 or an equivalent residue of the N-terminal tail of histone H2B." [PMID:32822587]
+is_a: GO:0140807 ! NAD+-protein-glutamate ADP-ribosyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23323 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-17T13:57:05Z
+
+[Term]
+id: GO:0140823
+name: histone kinase activity (H2B-S36 specific)
+namespace: molecular_function
+def: "Catalysis of the transfer of a phosphate group to the serine-36 residue of the N-terminal tail of histone H2B." [PMID:32822587]
+is_a: GO:0035174 ! histone serine kinase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23323 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-17T13:58:11Z
