### ISSUE TITLE
NTR: pollen intine formation

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#23330]
Please provide as much information as you can: 

* **Suggested term label:**
Pollen intine formation

* **Definition (free text)**

Formation of pollen intine, the  inner layer of the pollen wall. The reticulate pollen wall pattern consists of two layers, exine and intine.
* **Reference, in format PMID:#######**
PMID:35498668

* **Gene product name and ID to be annotated to this term**
AtNMDM1|AT5G09250 

* **Parent term(s)**
part of [GO:0010208 pollen wall assembly]

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by lreiser** [comment]
yes please and thank you

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160030
+name: pollen intine formation
+namespace: biological_process
+def: "Formation of pollen intine, the inner layer of the pollen wall. The reticulate pollen wall pattern consists of two layers, exine and intine." [PMID:35498668]
+is_a: GO:0010208 ! pollen wall assembly
+intersection_of: GO:0022607 ! cellular component assembly
+intersection_of: results_in_assembly_of GO:0043678 ! intine
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23330 xsd:anyURI
+created_by: rynl
+creation_date: 2022-05-17T18:13:46Z

**Comment by lreiser** [comment]
thanks
