### ISSUE TITLE
Remove EC:2.1.1.31 from GO:0009019 tRNA (guanine-N1-)-methyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23336]
id: GO:0009019
name: tRNA (guanine-N1-)-methyltransferase activity
def: "Catalysis of the reaction: S-adenosyl-L-methionine + tRNA = S-adenosyl-L-homocysteine + tRNA containing N1-methylguanine." [EC:2.1.1.31]
synonym: "S-adenosyl-L-methionine:tRNA (guanine-1-N-)-methyltransferase activity" RELATED [EC:2.1.1.31]
synonym: "S-adenosyl-L-methionine:tRNA (guanine-N1-)-methyltransferase activity" RELATED [EC:2.1.1.31]
synonym: "transfer ribonucleate guanine 1-methyltransferase activity" RELATED [EC:2.1.1.31]
synonym: "tRNA guanine 1-methyltransferase activity" RELATED [EC:2.1.1.31]

[EC:2.1.1.31](https://enzyme.expasy.org/EC/2.1.1.31) is obsolete.  It's been removed as an xref on GO:0009019 (and the replacement ECs are correctly on the GO child terms), but EC:2.1.1.31  remains in the def and synonym lines - see above. Can these be removed too?

**Comment by pgaudet** [comment]
We should obsolete this term, since C removed it and there is no RHEA.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0009019 tRNA (guanine-N1-)-methyltransferase activity. The reason for obsoletion is that EC and RHEA removed this term. Annotations should be moved to one of the children: 
GO:0052906 tRNA (guanine(37)-N(1))-methyltransferase activity
GO:0052905 tRNA (guanine(9)-N(1))-methyltransferase activity 

There are 5 remaining annotations to this term, by SGD, EcoCyc and Reactome. 
There are mappings by InterPro, UniRule, HAMAP, and Reactome. 

Annotations and suggestions for reannotation can be found here: https://github.com/geneontology/go-annotation/issues/4735

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/23336

Thanks, Pascale
