### ISSUE TITLE
Add EC xref to GO:0043337 CDP-diacylglycerol-phosphatidylglycerol phosphatidyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23339]
id: GO:0043337
name: CDP-diacylglycerol-phosphatidylglycerol phosphatidyltransferase activity
def: "Catalysis of the reaction: CDP-diacylglycerol + phosphatidylglycerol = CMP + diphosphatidylglycerol." [GOC:jl]
synonym: "cardiolipin synthase" BROAD []
synonym: "cardiolipin synthetase" BROAD []
xref: RHEA:32931

RHEA:32931 = EC:2.7.8.41 

[2.7.8.41](https://enzyme.expasy.org/EC/2.7.8.41)
Name: Cardiolipin synthase (CMP-forming).
Reaction: A CDP-diacylglycerol + a phosphatidylglycerol <=> a cardiolipin + CMP

**Comment by pgaudet** [comment]
Maybe this term should be renamed Cardiolipin synthase (CMP-forming)? It's simpler than the current mouthful 'CDP-diacylglycerol-phosphatidylglycerol phosphatidyltransferase activity'

**Comment by sjm41** [comment]
Yes, I was thinking the same!

**Comment by sjm41** [comment]
Thanks!
