### ISSUE TITLE
Add EC xref to GO:0061708 tRNA-5-taurinomethyluridine 2-sulfurtransferase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23340]
id: GO:0061708
name: tRNA-5-taurinomethyluridine 2-sulfurtransferase
def: "Catalysis of 5-taurinomethyluridine in tRNA + a [protein]-S-sulfanylcysteine + ATP + a reduced electron acceptor = a 5-taurinomethyl-2-thiouridine in tRNA + a [protein]-L-cysteine + AMP + an oxidized electron acceptor + diphosphate + H+." [GOC:dph, PMID:15509579]
xref: RHEA:47040

RHEA:47040 = EC:2.8.1.14 

[EC:2.8.1.14](https://enzyme.expasy.org/EC/2.8.1.14) 
Name: tRNA-5-taurinomethyluridine 2-sulfurtransferase.
Reaction: A [protein]-S-sulfanyl-L-cysteine + 5-taurinomethyluridine(34) in tRNA + ATP + reduced acceptor <=> a [protein]-L-cysteine + 5-taurinomethyl-2-thiouridine(34) in tRNA + AMP + diphosphate + acceptor

**Comment by hdrabkin** [comment]
done
