### ISSUE TITLE
NTR: [zinc:proton antiporter activity]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#23359]
Please provide as much information as you can: 

* **Suggested term label:**
zinc:proton antiporter activity

* **Definition (free text)**
Enables the transfer of zinc from one side of a membrane to the other according to the reaction: H(+)(out) + Zn(2+)(in) = H(+)(in) + Zn(2+)(out) 

* **Reference, in format PMID:#######**
PubMed=19366695 fig 4 and fig 5

* **Gene product name and ID to be annotated to this term**
SLC30A5 UniProtKB/Q8TAD4
* **Parent term(s)**
solute:proton antiporter activity GO:0015299. But we are missing an intermediate like GO:0005451
monovalent cation:proton antiporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
[Rhea:28839]

* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
>  But we are missing an intermediate like GO:0005451
monovalent cation:proton antiporter activity

Do you think these intermediate classes are needed? ie do any protein only transport monovalent cations? or is this to be consistent with the other branched in the ontology? I think some intermediate levels are just adding complexity and not much useful classification.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140826
+name: zinc:proton antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of zinc from one side of a membrane to the other according to the reaction: H(+)(out) + Zn(2+)(in) = H(+)(in) + Zn(2+)(out)" [PMID:19366695, RHEA:28839]
+xref: RHEA:28839
+intersection_of: GO:0015299 ! solute:proton antiporter activity
+intersection_of: has_primary_input CHEBI:24636 ! proton
+intersection_of: has_primary_input CHEBI:63056 ! zinc cation
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23359 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-20T05:22:59Z
