### ISSUE TITLE
Obsolete GO:0016657 ! oxidoreductase activity, acting on NAD(P)H, nitrogenous group as acceptor and move subclasses

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23357]
All the subclasses of 1.6.6.- have been deleted or transferred. So GO:0016657 should also been obsoleted and children classes moved under a new parent.

**Comment by raymond91125** [comment]
- [ ] GO:0052603 1-chloro-4-nitrosobenzene nitroreductase activity
- [ ] GO:0018543 4-amino-2-nitroso-6-nitrotoluene reductase activity
- [ ] GO:0018544 4-carboxy-4'-sulfoazobenzene reductase activity
- [ ] GO:0052602 4-chloronitrobenzene nitroreductase activity
- [ ] GO:0018545 NAD(P)H nitroreductase activity
- [ ] GO:0080007 S-nitrosoglutathione reductase activity
- [ ] GO:0009033 trimethylamine-N-oxide reductase activity

**Comment by raymond91125** [comment]
GO:0009033 trimethylamine-N-oxide reductase activity is RHEA:22024 and EC:1.7.2.3, thus parent is GO:0016662 oxidoreductase activity, acting on other nitrogenous compounds as donors, cytochrome as acceptor

**Comment by raymond91125** [comment]
I am not sure how to proceed with GO:0080007 S-nitrosoglutathione reductase activity

Per the original reference, PMID:11260719, "Ammonia (NH3) and glutathione disulphide (GSSG) were main products of the E. coli enzyme".
![image](https://github.com/geneontology/go-ontology/assets/619520/ec1346bb-089e-4dc8-82d1-936e00341da7)

Per PMID:27094420 GSNOR should be EC:1.1.1.1 alcohol dehydrogenase. There are 3 corresponding RHEAs https://www.rhea-db.org/rhea?query=EC%3A1.1.1.1
'''
GSNOR activity is associated with another previously known enzyme, formerly referred to as glutathione-dependent formaldehyde dehydrogenase (FALDH; EC 1.2.1.1). S-(hydroxymethyl)glutathione (HMGSH) as a spontaneous adduct of glutathione and formaldehyde was later identified as the proper substrate; therefore the enzyme was reclassified as S-(hydroxymethyl)glutathione dehydrogenase (EC 1.1.1.284). It catalyzes the oxidation of HMGSH to S-formylglutathione as a part of formaldehyde detoxification [6]. However, the NADH-dependent reduction of GSNO, leading to the formation of oxidized glutathione (GSSG) and ammonium, has been uncovered as a more physiologically relevant reaction [7, 8]. For this reason, the denomination of this enzyme as GSNOR is currently highly extended within scientific literature, although this designation has not been accepted yet by IUBMB nomenclature commission. According to the enzyme classification, GSNOR belongs to a family of Zn-dependent class III alcohol dehydrogenases (ADH3; EC 1.1.1.1), which are distinct from members of class I ADH family by their high affinity towards long-chain alcohols like cinnamyl alcohol, farnesol, and geraniol [9]. S-nitrosoglutathione is considered as the physiologically most relevant substrate, as the K m value of GSNOR for HMGSH is about 100 times higher as compared to GSNO [10].
'''

**Comment by raymond91125** [comment]
GO:0018545 NAD(P)H nitroreductase activity has XREF UM-BBD_enzymeID:e0346, which corresponds to EC:1.7.1.-. Thus the parent should be GO:0016661 oxidoreductase activity, acting on other nitrogenous compounds as donors.

**Comment by raymond91125** [comment]
GO:0052602 4-chloronitrobenzene nitroreductase activity has XREF MetaCyc:RXN-8833, which XREF EC:1.7.1.16, which is GO:0018546 nitrobenzene nitroreductase activity. Thus GO:0052602 should be obsoleted with replaced_by GO:0018546.

**Comment by pgaudet** [comment]
Hi @raymond91125 
For GO:0018546 nitrobenzene nitroreductase activity, please also migrate the MetaCyc xref (MetaCyc:RXN-8833)
and at least one PubMeds from RHEA:52884 (since we dont have any references or annotations, this helps know rapidly if the reaction has been characterized)

**Comment by pgaudet** [comment]
WRT GO:0080007 S-nitrosoglutathione reductase activity
I suggest we obsolete this term, and add the term label as synonyms to other terms? 
Also, add consider 'GO:0051903 S-(hydroxymethyl)glutathione dehydrogenase activity' 
This term has 3 annotations, trxA	Thioredoxin (MTBBASE), HOT5 (TAIR), and Fdh (drosophila). 

HOT5 (TAIR), and Fdh (drosophila) are already annotated to GO:0051903 S-(hydroxymethyl)glutathione dehydrogenase activity

I modified the trxA annotation to 'glutathione disulfide oxidoreductase activity'  has input S-nitrosoglutathione(1−) 

What do you think ?

**Comment by raymond91125** [comment]
> WRT GO:0080007 S-nitrosoglutathione reductase activity I suggest we obsolete this term, and add the term label as synonyms to other terms? Also, add consider 'GO:0051903 S-(hydroxymethyl)glutathione dehydrogenase activity' This term has 3 annotations, trxA Thioredoxin (MTBBASE), HOT5 (TAIR), and Fdh (drosophila).

The problem is, if I understand it correctly, this class of proteins have multiple enzymatic activities (see PMID:27094420) and these activities are synonymous to each other. I am no expert in enzymology.

**Comment by raymond91125** [comment]
GO:0018544 4-carboxy-4'-sulfoazobenzene reductase activity is probably equivalent to GO:0050446 azobenzene reductase activity. 4-carboxy-4'-sulfoazobenzene is an azobenzene and the original paper (PMID:9603860, referenced by http://eawag-bbd.ethz.ch/servlets/pageservlet?ptype=r&reacID=r0543 ) did include NADH or NADPH in the reaction.
Thus it should be obsoleted with replaced_by GO:0050446.

**Comment by pgaudet** [comment]
Hi @raymond91125 
Please fix the ones for which we know how to proceed, and if any thing remains, please open other ticket(s). 


Thanks, Pascale

**Comment by raymond91125** [comment]
GO:0018543 4-amino-2-nitroso-6-nitrotoluene reductase activity is XREFed to UM-BBD_reactionID:r0464 and the ref thereof is PMID:16535610. This paper describes the metabolism of TNT by Pseudomonas. It's unclear if this is meant to be a physiologically relevant reaction and there is no annotations. I think this term may be obsoleted.

**Comment by raymond91125** [comment]
GO:0052603  1-chloro-4-nitrosobenzene nitroreductase activity is XREFed to MetaCyc:RXN-8834 and thus is a sub-reaction activity of EC:1.7.1.16, GO:0018546.

**Comment by pgaudet** [comment]
So, we can obsolete GO:0052603 as out of scope for GO (sub-reaction). It has no annotations.

**Comment by raymond91125** [comment]
Then we should also obsolete GO:0018544 4-carboxy-4'-sulfoazobenzene reductase activity because it is a sub-activity of GO:0050446 azobenzene reductase activity and it has no annotations.

**Comment by raymond91125** [comment]
> WRT GO:0080007 S-nitrosoglutathione reductase activity I suggest we obsolete this term, and add the term label as synonyms to other terms? Also, add consider 'GO:0051903 S-(hydroxymethyl)glutathione dehydrogenase activity' This term has 3 annotations, trxA Thioredoxin (MTBBASE), HOT5 (TAIR), and Fdh (drosophila).
> 
> HOT5 (TAIR), and Fdh (drosophila) are already annotated to GO:0051903 S-(hydroxymethyl)glutathione dehydrogenase activity
> 
> I modified the trxA annotation to 'glutathione disulfide oxidoreductase activity' has input S-nitrosoglutathione(1−)
> 
> What do you think ?

I think at this point, the simplest solution is to place GO:0080007 S-nitrosoglutathione reductase activity as a child of GO:0004022 alcohol dehydrogenase (NAD+) activity (EC:1.1.1.1). There are already several children terms for ADH already and GSNOR is an important specific enzyme which may acquire formal EC or RHEA of its own.
