### ISSUE TITLE
NTR: [zinc chaperone activity] (new gene characterization)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23363]
Please provide as much information as you can: 

* **Suggested term label:**

zinc chaperone activity

* **Definition (free text)**

Binding to and delivering zinc ions to a target protein.

* **Reference, in format PMID:#######**

https://pubmed.ncbi.nlm.nih.gov/35584675/
PMID:35584675

* **Gene product name and ID to be annotated to this term**

https://www.yeastgenome.org/locus/ynr029c
https://www.pombase.org/gene/SPBC15D4.05
https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:17134
etc

* **Parent term(s)**
GO:0016530  
metallochaperone activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

zinc transferase (related or exact??)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140827
+name: zinc chaperone activity
+namespace: molecular_function
+def: "Binding to and delivering zinc ions to a target protein." [PMID:35584675]
+intersection_of: GO:0140104 ! molecular carrier activity
+intersection_of: has_primary_input CHEBI:63056 ! zinc cation
+relationship: has_part GO:0008270 ! zinc ion binding
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23363 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-20T06:19:17Z
+
