### ISSUE TITLE
Review the children of GO:0015925, galactosidase activity

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#23375]
Some of the children that are currently siblings and children of beta- and alpha- could possible be nested.

**Comment by hdrabkin** [comment]
galactosidase activity (GO:0015925)
	alpha-galactosidase activity (GO:0004557)
		raffinose alpha-galactosidase activity (GO:0052692)
	beta-galactosidase activity (GO:0004565) <<<<<<<<<
	arabinogalactan endo-1,4-beta-galactosidase activity (GO:0031218)
	6-phospho-beta-galactosidase activity (GO:0033920)
	capsular-polysaccharide endo-1,3-alpha-galactosidase activity (GO:0033921)
	blood-group-substance endo-1,4-beta-galactosidase activity (GO:0033929)
	keratan-sulfate endo-1,4-beta-galactosidase activity (GO:0033930)
	galactan 1,3-beta-galactosidase activity (GO:0033943)   <<<<< make child of GO:0031218

Based on def of beta-alactosidease activity (Catalysis of the hydrolysis of **terminal,** non-reducing beta-D-galactose residues in beta-D-galactosides.) propose moving galactan 1,3-beta-galactosidase activity (GO:0033943) as a child,

**Comment by hdrabkin** [comment]
Note other terms do not specify a terminal residue OR are alpha-galactosidase specific; 6-phospho-beta-galactosidase (GO:0033920) not clear.

**Comment by hdrabkin** [comment]
@deustp01 , do  you think I can close this one. I changed parentage of one, but not comfortable with anything further due to the lack of specifying either a terminal residue or alpha-galactosidase specific.

**Comment by deustp01** [comment]
OK to close, I think.
