### ISSUE TITLE
Modifications to antiporter (and symporter) branch 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23374]
Hello, 

Protégé cannot count items in a logical definitions, such that terms like  GO:0062158 chloride:proton antiporter activity, which transports a positively charged and a negatively charged ions, ends up under both GO:0015491 cation:cation antiporter activity
and GO:0015301 anion:anion antiporter activity: 

<img width="458" alt="image" src="https://user-images.githubusercontent.com/4782928/169846429-9bb861c3-b96e-41a2-9665-919dadd6a89b.png">

I propose to get rid of the double change in the term labels (and logical definitions), and use the superclass terms
* GO:0140323 solute:anion antiporter activity and 
* GO:0015299 solute:proton antiporter activity

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete
* GO:0005451 monovalent cation:proton antiporter activity
* GO:0015491 cation:cation antiporter activity
* GO:0015301 anion:anion antiporter activity

The reason for obsoletion is that these unnecessary grouping classes and cause incorrect inferences (since the reasoner cannot 'count' the number of items in the logical definitions). 

There are 72 manual annotations and 5 InterPro annotations, see https://docs.google.com/spreadsheets/d/1ZqlyeAS5UmwUh1MgJ9FvePR8wCfwKMoixGnruoOiz3s/edit#gid=0. 

Including 5 InterPro domains 

Thanks, Pascale

**Comment by pgaudet** [comment]
Created a new term to group some cation:cation antiporters

[Term]
id: GO:0140828
name: solute:metal cation antiporter activity
namespace: molecular_function
def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: solute(out) + Na+(in) = solute(in) + Na+(out)." [GOC:pg]
intersection_of: GO:0015297 ! antiporter activity
intersection_of: has_input CHEBI:25213 ! metal cation
intersection_of: has_primary_input CHEBI:24431 ! chemical entity
created_by: pg
creation_date: 2022-05-23T14:30:46Z

**Comment by deustp01** [comment]
> The reason for obsoletion is that these are unnecessary grouping classes

But sometimes the "grouping" follows the actual biology. For example, human SLC9B2 can transport either Na+ or Li+, a function that is captured in a [single reaction](https://reactome.org/content/detail/R-HSA-2889070) enabled by "monovalent cation transporter". Splitting the reaction into two, one that mediates Li+ transport enabled by [GO:0010348](https://www.ebi.ac.uk/QuickGO/term/GO:0010348) lithium:proton antiporter activity and one that mediates Na+ transport enabled by [GO:0015385](https://www.ebi.ac.uk/QuickGO/term/GO:0015385) sodium:proton antiporter activity, is straoghtforward to do but obscures a useful bit of information.

Thoughts @pgaudet?

**Comment by pgaudet** [comment]
Thanks for noting this @deustp01 

The GO guidelines (that we discussed for example for the NAD/NADP case) is that if a protein catalyses two reactions (that exist in GO), we annotate both reactions. Annotating to the grouping class means that we dont know whether the activity is more specific. We can always create a term that indicates broad substrate specificity, but I dont think this works for monovalent inorganic cation ([CHEBI:60242](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A60242)) ? 

Other children (in addition to Na+ and Li+) are: 

* ammonium   (CHEBI:28938)
* caesium(1+) (CHEBI:49547)
* cobalt(1+) (CHEBI:85033)
* oxidonitrogen(1+) (CHEBI:29120)
* potassium(1+) (CHEBI:29103)
* rubidium(1+) (CHEBI:49847)
* silver(1+) (CHEBI:49468)

So, if you annotate SLC9B2 to 'monovalent inorganic cation ' it means it also transports ammonuim and potassium, which is not true.

What do you think ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
That being said, I agree we could keep more granularity under the 'solute' part of the antiporter - 
* [CHEBI:23906 monoatomic cation](https://www.ebi.ac.uk/chebi/chebiOntology.do?treeView=true&chebiId=CHEBI:23906#graphView)
* [CHEBI:23905 monoatomic anion](https://www.ebi.ac.uk/chebi/chebiOntology.do?treeView=true&chebiId=CHEBI:23905#graphView)

That would exclude oxidonitrogen and ammonium. 

Does that work ?

**Comment by deustp01** [comment]
> We can always create a term that indicates broad substrate specificity

That leads to a proliferation of term. For example, for human SLC9B2 we'd want a term for transport of Na+ and Li+. And there are a number of transporters that each act on overlapping combinations of amino acids. Despite the NAD(P) discussion, there is still a discussion needed, I think, about tradeoffs between specificity in GO MF terms and specificity in annotation. For example, a few months ago @ukemi and I were pushing for multiple catalytic activity terms to be used to annotate the activity on the same enzyme on each of a series of nucleotide derivatives, and the decision then was to use the existing more general MF term and capture the substrate details at the level of GO-CAM annotation. That implies that if an MG+F definition lists multiple substrates, they are related by logical ORs, so the objection that using the general transport MF term means the transporter must handle all of the possible substrates should be wrong, so similar use of a monovalent cation transport MF term, coupled at the level of annotation to a list of relevant substrates seems reasonable.

Of course that does not solve the counting problem by itself because we would need consistent annotation rules (to be developed and implemented) and scripts to parse combinations of MF terms and substrates out of latest-generation GO-CAM models to get reliable tallies - not trivial.

But that is a future discussion. Current usage requires that if we want SLC9B2 to transport either of two cations, we need two reactions, so I will make the change and note it in the spreadsheet.

**Comment by pgaudet** [comment]
@deustp01 I added this to next week's ontology call

**Comment by deustp01** [comment]
> Note that I did not yet obsolete "monovalent cation transporter"

But meanwhile I've re-annotated the reaction that used it, to use terms for transport of specific cations, so we don't need this particular term. What does remain, I think, is the hard issue of how fine-grained a GO MF term should be, and how to trade off granularity in MF terms against granularity in GO-CAM annotations: does coupling a gene product to a broad MF term and a specific substrate in a GO-CAM annotation unit reliably capture all the information? Can we come up with general standards for addressing this issue? @ukemi @vanaukenk

**Comment by vanaukenk** [comment]
@deustp01 @pgaudet @ukemi 
It looks like the specificity question wrt this ticket is on the agenda for the next ontology call.  I've also added #23378 to the agenda to discuss specificity wrt terms capturing information about specific gene products.  We do need general guidelines about this.

**Comment by pgaudet** [comment]
- [x] Obsoleted GO:0005451 monovalent cation:proton antiporter activity
- [x] AS A TEST: GO:0015299 solute:proton antiporter activity: changed LD from 'has primary input' some 'chemical entity' to the more narrow 'organic molecular entity'
- [x] and GO:0140848
-name: amino acid:monoatomic cation antiporter activity
+name: amino acid:solute antiporter activity
-intersection_of: has_primary_input CHEBI:23906 ! monoatomic cation
-intersection_of: has_primary_input CHEBI:33709 ! amino acid
+intersection_of: has_primary_input CHEBI:35238 ! amino acid zwitterion
+intersection_of: has_primary_input CHEBI:50860 ! organic molecular entity

Some edits: 
Changed amino acids to match RHEA and added RHEA xrefs when I found them: 

- [x] GO:0000515
-name: aspartate:glutamate, proton antiporter activity
+name: L-aspartate:L-glutamate, proton antiporter activity
- [x] GO:0015496
-name: putrescine:ornithine antiporter activity
+name: putrescine:L-ornithine antiporter activity
- added +xref: RHEA:28827
+xref: TC:2.A.3.2.1
- [x]  GO:0043858
-name: arginine:ornithine antiporter activity
+name: L-arginine:L-ornithine antiporter activity
- [x]  GO:0043862
-name: arginine:agmatine antiporter activity
+name: L-arginine:agmatine antiporter activity
+xref: RHEA:29651
- [x] GO:0043872
-name: lysine:cadaverine antiporter activity
+name: L-lysine:cadaverine antiporter activity
+xref: RHEA:28895
+xref: TC:2.A.3.2.2


- [x] Created grouping class 
+[Term]
+id: GO:0140849
+name: amino acid derivative:cation antiporter activity
+def: "Enables the transfer of an amino acid derivative from one side of a membrane to the other according to the reaction: amino acid derivativ(out) + cation(in) = amino acid derivativ(in) + cation(out)." [GOC:curators]
+intersection_of: GO:0015298 ! solute:cation antiporter activity
+intersection_of: has_primary_input CHEBI:83821 ! amino acid derivative
+created_by: pg
+creation_date: 2022-05-31T06:01:27Z

**Comment by pgaudet** [comment]
Done in https://github.com/geneontology/go-ontology/issues/24479
