### ISSUE TITLE
NTR: Term to describe toll ligand proteolytic cascade 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#23378]
The Toll signaling pathway GO:0008063 is described as "A series of molecular signals initiated by the binding of an extracellular ligand to the receptor Toll on the surface of a target cell, and ending with regulation of a downstream cellular process, e.g. transcription."

We would like to have a term to describe the upstream protease cascade (plus its regulation) that leads to the generation of an active ligand (spatzle) for Toll receptors.
![67852579-92a15b80-fb04-11e9-91fa-9c22b32f7fa6](https://user-images.githubusercontent.com/11865746/170012060-cd05fee9-e05e-49e9-87d3-e9d8a00405e6.png)

* **Suggested term label:**
Either:
Toll ligand activation cascade
Pro-spatzle activation cascade

* **Definition**
A zymogen activation cascade that leads to the generation of an active protease that cleaves a pro-ligand to an active ligand for the Toll receptor. Starting with the activation of the protease cascade by extracellular recognition factors and ending with the cleave of the Toll receptor pro-ligand (in Drosophila, this ligand is Spatzle). 

* **Reference**

PMID:21209287
* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0072376 	protein activation cascade ?(not sure)

* **Children terms (if applicable)**
* 
regulation (+ve/-ve) terms as well, please!

tagging @gantonazzo

**Comment by ukemi** [comment]
I would suggest a child of signaling receptor ligand precursor processing (GO:0140448). I have used its grandchild to annotate the proteases that process EGF-family ligands.

**Comment by hattrill** [comment]
> I would suggest a child of signaling receptor ligand precursor processing (GO:0140448). I have used its grandchild to annotate the proteases that process EGF-family ligands.

Oh, yes. I like that very much!

**Comment by raymond91125** [comment]
@hattrill what is the source of the figure 2 above? It is not PMID:21209287, I believe. That would be a better reference for below terms.

If I understand it correctly, "Toll signaling pathway" includes TLRs that do not use Spatzle as ligands. How about:

Subclass of GO:0016486 peptide hormone processing 
"Toll peptide ligand processing" definition "The generation of a mature active peptide ligand for the Toll receptor by the proteolytic cleavage of a pro-ligand to generate a functional ligand. In Drosophila, this ligand is Spatzle."

Subclass of GO:0060568 regulation of peptide hormone processing
"regulation of Toll peptide ligand processing" definition "Any process that modulates the frequency, rate or extent of Toll peptide ligand processing."

"positive regulation of Toll peptide ligand processing" definition "Any process that activates or increases the frequency, rate or extent of Toll peptide ligand processing."

"negative regulation of Toll peptide ligand processing" definition "Any process that stops, prevents, or reduces the frequency, rate or extent of Toll peptide ligand processing."

**Comment by hattrill** [comment]
> @hattrill what is the source of the figure 2 above? It is not PMID:21209287, I believe. That would be a better reference for below terms.

@raymond91125 the source for that figure is PMID:23632253

> If I understand it correctly, "Toll signaling pathway" includes TLRs that do not use Spatzle as ligands. 

Actually, TLRs are covered by GO:0002224 toll-like receptor signaling pathway - the TLR is activated by directly binding pathogen molecules (PAMPs) whereas the Drosophila/insect Toll receptors are activated by processed Spaetzle ligand and are  covered by GO:0008063 Toll signaling pathway.

**Comment by hattrill** [comment]
Thinking about signaling receptor ligand precursor processing/peptide hormone processing, I realise that this won't work for Spatzle as what I want to capture is the cascade of events that final leads to processing of the ligand, whereas "signaling receptor ligand precursor processing" is for the processing steps that act on the ligand itself.

I therefore think that 'protein activation cascade' is more appropriate as the steps are a series of zymogen-activations ending in Spatzle activation by cleavage.

**Comment by raymond91125** [comment]
> I therefore think that 'protein activation cascade' is more appropriate as the steps are a series of zymogen-activations ending in Spatzle activation by cleavage.

I see. How about:
"spatzle activation cascade" definition: "A zymogen activation cascade that leads to the generation of an active protease that cleaves an inactive to an active ligand, spazle, for the Toll receptor. Starting with the activation of the protease cascade by extracellular recognition factors and ending with the cleavage of spatzle." PMID:23632253.

Given that there are three parallel cascades, is one term enough for you? You probably don't want to mix the annotations.

But then I don't know if this gets too granular for GO. @pgaudet What do you think?

**Comment by pgaudet** [comment]
I agree this is very specific, but we have all these other ones: 

<img width="405" alt="image" src="https://user-images.githubusercontent.com/4782928/171235753-322d6615-0ed4-4eba-afcd-bbf4155de04e.png">


@hattrill isn't signaling receptor ligand precursor processing sufficient with the ligand as the input? 

Thanks, Pascale

**Comment by deustp01** [comment]
Yet another vignette for the hard uniform-granularity discussion>

**Comment by raymond91125** [comment]
signaling receptor ligand precursor processing DEF The cleavage of a peptide bond in a precursor form of a signaling receptor ligand, resulting in the mature (active) form of the ligand. That sounds like a single-step process. What @hattrill wants, I believe, is something more like a 'regulation of signaling receptor ligand precursor processing', specifically, the toll ligand spatzle. But the regulation is in itself complex, involving pathways that consists of cascades of proteolytic reactions and their regulations. Thus the proposal of a child of protein activation cascade seems more direct and better.

**Comment by pgaudet** [comment]
> That sounds like a single-step process.

That's right - we should make the definitions more general, as we did for small non-coding RNA processing, which is now "A process leading to the generation of a functional x" (+ including some additions steps as needed). 

Wouldn't 'maturation' be more appropriate than 'processing? 

Thanks, Pascale

**Comment by raymond91125** [comment]
Similar to the term GO:0072378 blood coagulation, fibrin clot formation. a child of protein activation cascade, how about:

"Toll receptor ligand protein activation cascade" definition "A protein activation cascade that contributes to the generation of an active peptide ligand for the Toll receptor and consists of the cascade of enzymatic reactions initiated by by extracellular recognition factors, leading to the cleavage of the inactive form of spatzle." PMID:23632253.

**Comment by hattrill** [comment]
I like that. It works for me.

**Comment by raymond91125** [comment]
@hattrill Sorry, I spoke too soon. Do you think it's workable for you to annotate genes involved in the spatzle activation cascade with (new term) signaling receptor ligand activation cascade: A series of modifications to a set of proteins where the product of one reaction catalyzes the following reaction, ultimately leading to the generation of a mature ligand.
is_a protein activation cascade (GO:0072376); and specify spatzle as the ligand in annotation extension?
We prefer to do it this way because it would avoid specifying a single gene product in the GO term.
Thanks for your consideration and patience.

**Comment by hattrill** [comment]
Hi @raymond91125 I think that this is an exceptional case - can't think of many similarities and as this is a distinguishing feature of arthropod Toll signaling pathways (not TLRs) and there are mulitple enzymes explictly dedicated to this process and many routes, it would get too hard. Spz is at the end, so the individual step would the pro-enzyme as the "has_input" rather thgan spz and then another extension would be needed to say how it was activated e.g. part_of DV axis or innate immune response to X pathogen.

So, would like a special term please!

**Comment by pgaudet** [comment]
@hattrill does this only occur for the toll ligand? maybe then we dont create the grouping term?

**Comment by raymond91125** [comment]
I think the question is about whether it's best to create a term addressing Spz specifically (with or without a grouping term) or let Spz be specified some other way (annotation extension or GO-CAM). I'm not experienced in annotation practices. @ukemi @vanaukenk Could you advise? Thanks!

**Comment by pgaudet** [comment]
WRT the complement system, it seems GO:0006956 complement activation should be given the additional superclass 'protein activation cascade'.

Thanks, Pascale

**Comment by addiehl** [comment]
It looks like GO:0006956 complement activation already 'has part' some 'protein activation cascade', per AmiGO.

**Comment by raymond91125** [comment]
good catch @addiehl

**Comment by pgaudet** [comment]
Wouldn't is_a be more accurate ? I dont see the other parts of complement activation?

**Comment by raymond91125** [comment]
@hattrill Would you be interested in coming to a GO ontology developer meeting (Monday 9AM PST) so that we can discuss this with the larger group in real time? @pgaudet When do you think we can fit Helen in, June 20th?

Again, I'm sorry this takes so much time but it touches on some fundamental issues of GO moving forward.

**Comment by hattrill** [comment]
June 20th would be fine for me.

**Comment by raymond91125** [comment]
Summary of alternative proposals
protein maturation
   is_a protein activation cascade (GO:0072376)
        is_a signaling receptor protein ligand activation cascade
OR   is_a Toll receptor ligand protein activation cascade

**Comment by raymond91125** [comment]
regulation terms added. Thanks for reminding me. @hattrill
