### ISSUE TITLE
Update EC xref on GO:0004325 ferrochelatase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23371]
id: GO:0004325
name: ferrochelatase activity
namespace: molecular_function
def: "Catalysis of the reaction: heme B (protoheme) + H+ = Fe(2+) + protoporphyrin IX." [RHEA:22584]
xref: EC:4.99.1.1
xref: KEGG_REACTION:R00310
xref: MetaCyc:PROTOHEMEFERROCHELAT-RXN
xref: Reactome:R-HSA-189465 "FECH binds Fe2+ to PRIN9 to form heme"
xref: RHEA:22584
is_a: GO:0016829 ! lyase activity

EC has been transferred to 4.98.1.1
https://www.enzyme-database.org/query.php?ec=4.99.1.1

@kaxelsen that website says the transfer happened in 2021, but I don't see the update here: https://enzyme.expasy.org/EC/4.99.1.1
Is there a synchrony problem??

Also, I think reference to EC:4.99.1.1 should be deleted from the comment on this entry:
id: GO:0016851
name: magnesium chelatase activity
namespace: molecular_function
def: "Catalysis of the reaction: ATP + H(2)O + Mg(2+) + protoporphyrin IX = ADP + 2 H(+) + magnesium protoporphyrin IX + phosphate." [EC:6.6.1.1, RHEA:13961]
comment: Note that this was EC:4.99.1.1.
xref: EC:6.6.1.1
xref: KEGG_REACTION:R03877
xref: MetaCyc:RXN1F-20
xref: RHEA:13961
is_a: GO:0051003 ! ligase activity, forming nitrogen-metal bonds, forming coordination complexes

**Comment by kaxelsen** [comment]
Concerning EC 4.99.1.1 transferred to EC 4.98.1.1
You are quite right the SIB ENZYME data is not up to date. We have had problems with the curation tool that was old and needed to be replaced. This has now been done, and I have started working down the back-log. I hope to be up-to-date by release 2022_04 scheduled for September 28.

**Comment by pgaudet** [comment]
Since we make links to https://enzyme.expasy.org, we need to wait for the September update to update the xref.

**Comment by sjm41** [comment]
OK!

What do you think about removing "Note that this was EC:4.99.1.1." from the GO:0016851 entry.  Seems a different reaction, and https://enzyme.expasy.org/EC/6.6.1.1 doesn't mention it.

**Comment by pgaudet** [comment]
Sounds good. I also updated the definition of GO:0016851  to match RHEA: 

EC 
ATP + protoporphyrin IX + Mg(2+) + H(2)O <=> ADP + phosphate + Mg-protoporphyrin IX + 2 H(+)


RHEA
ATP + H2O + Mg2+ + protoporphyrin IX = ADP + 3 H+ + Mg-protoporphyrin IX + phosphate

Not sure why there is a discrepancy.

**Comment by kaxelsen** [comment]
The reason is that IUBMB texts are not perfectly balanced for charge and mass, that is one of the improvements in Rhea. Protons are only added to IUBMB reactions when they are deemed to be an important part of the reaction.

**Comment by kaxelsen** [comment]
I don't think there is. Until now we (Rhea) have made lists of the EC numbers and GO terms concerned and informed @pgaudet .

**Comment by pgaudet** [comment]
I think this is done.

**Comment by sjm41** [comment]
Hi @pgaudet I think we still need to change 4.99.1.1 -> 4.98.1.1 on GO:0004325, don't we?

You said above that we should wait until September to do this since we make links to https://enzyme.expasy.org/, but I think we should make the change now given 4.99.1.1 is already invalid at all other places (https://www.enzyme-database.org, KEGG, MetaCyc...) and it's just EXPASY that is out of date.  It's true that the hyperlink to EXPASY won't resolve, but I think that's OK - better that than report an obsolete EC number?

**Comment by pgaudet** [comment]
That was starting from a good intention but it's too confusing to keep track of true obsolete xrefs and not yet visible ones.
