### ISSUE TITLE
NTR: [NAD+-histone-glutamate ADP-ribosyltransferase activity (H2B-E2 specific)]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#23377]
Hi GO,

I would need a new term for an enzyme that catalyzes another histone modification

Thanks

Sylvain

NAD+-histone-glutamate ADP-ribosyltransferase activity (H2B-E2 specific)
Catalysis of the transfer of ADP-ribose groups to the glutamate-2 or an equivalent residue of the N-terminal tail of histone H2B.
child of GO:0140807 NAD+-protein-glutamate ADP-ribosyltransferase activity
PMID:27530147

**Comment by pgaudet** [comment]
Hi @sylvainpoux 
Maybe we could be more explicit about what we mean by 'equivalent residue' - I think the E2 position is in human (or mammals?) How about Catalysis of the transfer of ADP-ribose groups to the glutamate-2 residue of a mammalian histone H2B (or an equivalent residue) of the N-terminal tail of histone H2B.

Same for NAD+-histone-glutamate ADP-ribosyltransferase activity (H2B-E35 specific)

What do you think? Do you know the phylogenetic range (even approximate) for H2B H2 and E35? 

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140844
+name: NAD+-histone-glutamate ADP-ribosyltransferase activity (H2B-E2 specific)
+namespace: molecular_function
+def: "Catalysis of the transfer of ADP-ribose groups to the glutamate-2 residue of the N-terminal tail of histone H2B (or an equivalent residue)." [PMID:27530147]
+is_a: GO:0140807 ! NAD+-protein-glutamate ADP-ribosyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23377 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-25T07:28:00Z

**Comment by sylvainpoux** [comment]
Hi @pgaudet,
to be honest, I copied pasted the  'equivalent residue'  from many other Chromatin modifier terms.

Glu-2 is well conserved in vertebrates (it is sometimes an Asp) and Glu-35 is almost 100% conserved.

Thanks

Sylvain
