### ISSUE TITLE
NTR - L-histidine, sodium:proton antiporter activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#23384]
_Please provide as much information as you can:_ 

* **Suggested term label:**
L-histidine, sodium:proton antiporter activity

* **ChEBI ID and label of the substance:**
 [Rhea:71135]: H(+)(in) + L-histidine(out) + Na(+)(out) = H(+)(out) + L-histidine(in) + Na(+)(in)

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction:  H(+)(in) + L-histidine(out) + Na(+)(out) = H(+)(out) + L-histidine(in) + Na(+)(in).

* **Reference, in format PMID:11742981 and PMID: 10619430

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0015299 solute:proton antiporter activity 

* **Synonym(s) (please specify, EXACT, BROAD, NARROW or RELATED)**
_Other than the standard synonyms below_

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Cross-references**
* MetaCyc or KEGG pathways, can also provide Wikipedia or other links.

* **Any other information**

----

* **FOR ONTOLOGY EDITOR**

* **Logical definition**
* *  **substance metabolic process:**
'metabolic process'
 and ('has primary input or output' some [substance]
* * **substance biosynthetic process:**
'biosynthetic process'
 and ('has primary output' some [substance].
* * **substance catabolic process:**
'catabolic process'
 and ('has primary output' some [substance] 

* **Standard synonyms**
* *  **substance metabolic process:**
* * * EXACT: substance metabolism
* * **substance biosynthetic process:** 
* * * EXACT: substance anabolism
* * * EXACT: substance biosynthesis
* * * EXACT: substance formation
* * * EXACT: substance synthesis

* * **substance catabolic process:**    
* * * EXACT: substance breakdown
* * * EXACT: substance catabolism
* * * EXACT: substance degradation

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140832
+name: L-histidine, sodium:proton antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: H(+)(in) + L-histidine(out) + Na(+)(out) = H(+)(out) + L-histidine(in) + Na(+)(in)." [PMID:10619430, PMID:11742981]
+xref: RHEA:71135
+intersection_of: GO:0015299 ! solute:proton antiporter activity
+intersection_of: has_primary_input CHEBI:24636 ! proton
+intersection_of: has_primary_input CHEBI:29101 ! sodium(1+)
+intersection_of: has_primary_input CHEBI:57595 ! L-histidine zwitterion
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23384 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-24T12:37:29Z
+
