### ISSUE TITLE
NTR regulation of promoter clearance

### ISSUE THREAD

**Issue by colinlog** [geneontology/go-ontology#23388]
We need three new terms The reference is: PMID: 28248323

Regulation of promoter clearance from RNA polymerase II promoter

Any process that regulates the transition from the initiation to the elongation phases of transcription by RNA polymerase II,

child of GO:0001111 promoter clearance from RNA polymerase II promoter

 

 

Positive regulation of promoter clearance from RNA polymerase II promoter

Any process that activates or increases the frequency, rate or extent the transition from the initiation to the elongation phases of transcription by RNA polymerase II,

child of GO:XXXXXXX Regulation of promoter clearance from RNA polymerase II promoter

 

 

Negative regulation of promoter clearance from RNA polymerase II promoter

Any process that stops, prevents, or reduces the the transition from the initiation to the elongation phases of transcription by RNA polymerase II,

child of GO:XXXXXXX Regulation of promoter clearance from RNA polymerase II promoter

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140845
+name: regulation of promoter clearance from RNA polymerase II promoter
+namespace: biological_process
+def: "A process that modulates the frequency, rate or extent of the transition from the initiation to the elongation phases of transcription by RNA polymerase II." [PMID:28248323]
+is_a: GO:0065007 ! biological regulation
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23388 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-25T07:54:33Z
+
+[Term]
+id: GO:0140846
+name: positive regulation of promoter clearance from RNA polymerase II promoter
+namespace: biological_process
+def: "A process that stops, prevents or reduces the transition from the initiation to the elongation phases of transcription by RNA polymerase II." [PMID:28248323]
+is_a: GO:0065007 ! biological regulation
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23388 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-25T07:54:33Z
+
+[Term]
+id: GO:0140847
+name: negative regulation of promoter clearance from RNA polymerase II promoter
+namespace: biological_process
+def: "A process that modulates the frequency, rate or extent of the transition from the initiation to the elongation phases of transcription by RNA polymerase II." [PMID:28248323]
+is_a: GO:0065007 ! biological regulation
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23388 xsd:anyURI
+created_by: pg
+creation_date: 2022-05-25T07:54:33Z

**Comment by pgaudet** [comment]
@sylvainpoux
