### ISSUE TITLE
Update term labels for 'Promoter clearance from RNA polymerase promoter'

### ISSUE THREAD

**Issue by colinlog** [geneontology/go-ontology#23386]
promoter clearance from RNA polymerase I promoter and the same for II and III
new name: RNA polymerase I promoter clearance and the same for II and III

**Comment by pgaudet** [comment]
* [GO:0001182 promoter clearance from RNA polymerase I promoter](http://amigo.geneontology.org/amigo/term/GO:0001182#display-lineage-tab)
*  [GO:0001111 promoter clearance from RNA polymerase II promoter](http://amigo.geneontology.org/amigo/term/GO:0001111#display-lineage-tab)
* [GO:0001110 promoter clearance from RNA polymerase III promoter](http://amigo.geneontology.org/amigo/term/GO:0001110#display-lineage-tab)

**Comment by pgaudet** [comment]
Removed commas in 
* 'DNA-templated transcription, elongation' -> 'DNA-templated transcription elongation'
* 'DNA-templated transcription, initiation' -> 'DNA-templated transcription initiation'
*'DNA-templated transcription, termination' -> 'DNA-templated transcription termination'

**Comment by pgaudet** [comment]
Changed labels 
* 'transcription initiation from mitochondrial promoter' ->  'transcription initiation **at** mitochondrial promoter'
* 'transcription initiation from RNA polymerase I promoter' -> 'transcription initiation  **at** RNA polymerase I promoter' 
* 'transcription initiation from RNA polymerase II promoter'  -> 'transcription initiation  **at** RNA polymerase II promoter' 
* 'transcription initiation from RNA polymerase III promoter'  -> 'transcription initiation  **at** RNA polymerase III promoter'

**Comment by pgaudet** [comment]
Changed labels
* maintenance of transcriptional fidelity during DNA-templated transcription elongation -> 'maintenance of transcriptional fidelity during transcription elongation'
*  maintenance of transcriptional fidelity during DNA-templated transcription elongation from RNA polymerase II promoter -> 'maintenance of transcriptional fidelity during transcription elongation by RNA polymerase II'
*  maintenance of transcriptional fidelity during DNA-templated transcription elongation from RNA polymerase II promoter -> 'maintenance of transcriptional fidelity during transcription elongation by RNA polymerase III'
