### ISSUE TITLE
RNA polymerase II CTD variant repeat modifications

### ISSUE THREAD

**Issue by colinlog** [geneontology/go-ontology#23392]
In some organisms, including human, there are variants repaets of the CTD of RNA polymerase that include arginines or lysines.
These can be modified and this is important fro specific transcriptional events. According to the 2017 review PMID: 28248323 the modifications are arginine and lysine methylation, lysine acetylation and lysine ubiquitylation. References for these variant repeat modifications are provided in Table I.  

This therefore calls for the creation a MF term branch called 'Non-consensus RNA polymerase II large subunit heptad repeat modification' parent term. A synonym being 'Variant RNA polymerase II CTD heptad repeat modification'.  

the biological processes that are associated are

Rme: snRNA and snoRNA regulation, R-loop resolution and transcription termination
Kme: transcription repression
Kac: 
Kub: RBP1 degradation

**Comment by pgaudet** [comment]
Done in #24910 and #24980
