### ISSUE TITLE
cohesin unloading/ 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23400]
Although this might seem counterintuitive, I am not sure that "cohesin unloading" should be under 
"negative regulation of cohesion" but under 
cohesion. The cohesion   cycle process would include both loading and unloading

<img width="888" alt="fix open ticket_cohesin unloading parent" src="https://user-images.githubusercontent.com/7359272/170281646-de24a1a1-2844-4bc5-81ff-51b4aa6a8509.png">

(Currently this ends up in the "regulation" bin which seems odd.

Would be good to have @colinlog  input next time we chat.

**Comment by ValWood** [comment]
I wonder if this. ticket could be processed.  It's straightforward (it is part of my review of everything annotated to. "regulation of process".This isn't regulation, but  the gene products annotated to it end up in the "regulation of ....." bin (and hence will be excluded from enrichment /slims)

**Comment by pgaudet** [comment]
Hi @ValWood 

It's not so straight forward because once we remove the regulation parents, this term has no more parents. 

I wonder 'cohesin loading' and 'cohesin unloading' should not be deleted in favor of the corresponding MF: 
'GO:0061775 cohesin loading activity'
GO:0140670 ATP-dependent cohesin unloading activity (created in #21700) 

Note that we would need to rehouse annotations to  GO:1905343 regulation of cohesin unloading (3 SGD) and     GO:0071922 regulation of cohesin loading (23 EXP)

**Comment by ValWood** [comment]
I considered that for a while, but cohesin loading and unloading are multistep processes:

<img width="970" alt="Screenshot 2022-09-20 at 08 38 06" src="https://user-images.githubusercontent.com/7359272/191196557-726ca45a-d347-4f52-bd19-67980b184747.png">


https://www.researchgate.net/publication/290392950_DNA_Entry_into_and_Exit_out_of_the_Cohesin_Ring_by_an_Interlocking_Gate_Mechanism/figures?lo=1

**Comment by ValWood** [comment]
Actually what you suggest would work.
Pds5/Wpl would be described as a cohesin loader/unloader  activity, and the other steps (like the ATPase which is intrinsic to the cohesin, and the acetylation. step would just be part of "cohesion". Otherwise what is "cohesion"?

**Comment by ValWood** [comment]
I have been trying to annotate this pathway since the Noctua workshop in Hinxton. I think it was about 10 years ago ;)

**Comment by pgaudet** [comment]
Right - because although the steps can be decomposed, it seems like the overall activity of each complex is 'loading/loader' and unloading/unloader'

**Comment by ValWood** [comment]
Yes. I was being dim.

**Comment by pgaudet** [comment]
Need to change the labels for the MFs - 

*GO:0061775 cohesin loading activity' -> cohesin loader activity'
* GO:0140670 ATP-dependent cohesin unloading activity  -> ATP-dependent cohesin unloader activity

**Comment by colinlog** [comment]
Yes I fully agree, cohesin loader (NIPB and SCC4) and unloader (WPL)  are much better as MFs than BPs. The BP is sister chromatin cohesion (and is in fact restricted to S-G2/M phases) as in G1, there are no sister chromatids yet. In G1, S and G2/M chromosome looping is performed by cohesin.

**Comment by ValWood** [comment]
Hi Colin. Doesn't APL function as both a loader and an unloader. I am sure I have annotations to both?

**Comment by ValWood** [comment]
Ignore. I did . I don't seem to now...

**Comment by Antonialock** [comment]
do we need "maintenance of mitotic sister chromatid cohesion"
I was wondering if the term was applicable to sororin, so I looked at what's currently annotated to the term. There are 11 experimental annotations, it looks like a mix of things?

https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0034088&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

**Comment by colinlog** [comment]
To me sister chromatid cohesion is the BP. The MFs are establishment (loading cohesin ring) and dissolution (unloading cohesin ring). The ;maintenance is the integrity of the cohesin ring itself, I would say. 

There are the specialised meitoic division aspects of cohesion of course.

There is the motor activity of the cohesin complex, which is a loop extrusion activity in the BP chromatin looping, as far as we know.

**Comment by ValWood** [comment]
@pgaudet  remember to merge the "regulation of cohesion loading" into the "regulation  of (mitotic?) cohesion"

**Comment by ValWood** [comment]
ping

**Comment by pgaudet** [comment]
Hi @ValWood 
What is the action exactly? you write merge  "regulation of cohesion loading" into the "regulation of (mitotic?) cohesion"

This term does not exist. We do have ' regulation of sister chromatid cohesion '; is that what you mean? We dont seem to have ' regulation of mitotis sister chromatid cohesion ', although we do have a very large number of terms in this branch:  

![image](https://user-images.githubusercontent.com/4782928/204253353-507c6d78-ed03-4425-9f7c-f042d4bcedd8.png)


Thanks, Pascale

**Comment by ValWood** [comment]
Since  we are not doing merges anymore we should obsolete.

we  (should) now have MF terms for cohesin loading and cohesin unloading so we can obsolete any terms  in BP with loading or unloading.

when terms say "regulation of cohesin loading" the appropriate annotation would be 
"regulation of cohesion".
So regulation of mitotic sister chromatid cohesion loading  for example would be 
"regulation of mitotic sister chromatid cohesion"

You are correct, there are too many terms, I think these might be best dealt with by  a comprehensive  annotation review of the pathway. There are different paths operating at the arms and the centromeres but we don't need all of the establishment and maintenance terms. 

I think things will be clearer once the loading and unloading terms have gone.

**Comment by pgaudet** [comment]
Just to make sure we're on the same page: The MFs do exist: 

[GO:0061775](https://www.ebi.ac.uk/QuickGO/term/GO:0061775)
cohesin loader activity 

[GO:0140670](https://www.ebi.ac.uk/QuickGO/term/GO:0140670)
cohesin unloader activity

**Comment by pgaudet** [comment]
**- GO:0061774  cohesin unloading  > 0 annotations**
- GO:0061781 mitotic cohesin unloading > 0 annotations
-  GO:1905411 positive regulation of mitotic cohesin unloading > 0 annotations
- GO:1905410 regulation of mitotic cohesin unloading > 0 annotations


- **GO:0071921 cohesin loading**  >> 1 EXP pombase
- GO:0061780 mitotic cohesin loading  >> 1 EXP ComplexPortal
- GO:0071922 regulation of cohesin loading > 0 annotations
- GO:0071923 negative regulation of cohesin loading >> 4 EXP pombase
- GO:1905406 positive regulation of mitotic cohesin loading  >> 1 EXP pombase
-  GO:1905309 positive regulation of cohesin loading >> 1 EXP ComplexPortal


@ValWood Do you want to keep these terms?

**Comment by ValWood** [comment]
I think we decided on a call with @colinlog  way back that these should be described using the
MF cohesin loader, and  the process sister chromatid cohesion (because  cohesion is essentially the loading of cohesin)

So if @colinlog  still agrees, I think this would be OK, I am fine with it

**Comment by pgaudet** [comment]
So, we go ahead and obsolete 

'cohesin unloading' <http://purl.obolibrary.org/obo/GO_0061774>
'regulation of cohesin unloading' <http://purl.obolibrary.org/obo/GO_1905343>
'regulation of mitotic cohesin unloading' <http://purl.obolibrary.org/obo/GO_1905410>
'negative regulation of cohesin unloading' <http://purl.obolibrary.org/obo/GO_1905338>
'positive regulation of cohesin unloading' <http://purl.obolibrary.org/obo/GO_1905339>
'positive regulation of mitotic cohesin unloading' <http://purl.obolibrary.org/obo/GO_1905411>

Right @ValWood ?

**Comment by pgaudet** [comment]
as well as the loading 
'cohesin loading' <http://purl.obolibrary.org/obo/GO_0071921>
'mitotic cohesin loading' <http://purl.obolibrary.org/obo/GO_0061780>
'mitotic cohesin dsDNA (leading strand) loading' <http://purl.obolibrary.org/obo/GO_0062021>
'mitotic cohesin ssDNA (lagging strand) loading' <http://purl.obolibrary.org/obo/GO_0062022>
'regulation of cohesin loading' <http://purl.obolibrary.org/obo/GO_0071922>
'regulation of mitotic cohesin loading' <http://purl.obolibrary.org/obo/GO_1905405>
'negative regulation of cohesin loading' <http://purl.obolibrary.org/obo/GO_0071923>
'positive regulation of cohesin loading' <http://purl.obolibrary.org/obo/GO_1905309>
'negative regulation of mitotic cohesin loading' <http://purl.obolibrary.org/obo/GO_1905412>
'positive regulation of mitotic cohesin loading' <http://purl.obolibrary.org/obo/GO_1905406>
'negative regulation of mitotic cohesin dsDNA (leading strand) loading' <http://purl.obolibrary.org/obo/GO_0106115>
'negative regulation of mitotic cohesin ssDNA (lagging strand) loading' <http://purl.obolibrary.org/obo/GO_0106112>
'positive regulation of mitotic cohesin dsDNA (leading strand) loading' <http://purl.obolibrary.org/obo/GO_0106116>
'positive regulation of mitotic cohesin ssDNA (lagging strand) loading' <http://purl.obolibrary.org/obo/GO_0106113>

**Comment by ValWood** [comment]
I believe that is what we decided in discussion with @colinlog  long ago.

We said it was enough to use the loader/GO:0061776   
topological DNA co-entrapment activity activities and the mitotic cohesion process
(anything regulating would be "regulation of mitotic cohesion", "rather than regulation of loading".

**Comment by ValWood** [comment]
BUt make the loading /unloading terms narrow synonyms of cohesion. One could group some function terms as loading or unloading, but it wouldn't be very helpful, because it only represents a sub part of a linear pathway.

**Comment by raymond91125** [comment]
- [ ] 'cohesin unloading' http://purl.obolibrary.org/obo/GO_0061774
- [ ] GO:0061781 mitotic cohesin unloading
- [ ] 'regulation of cohesin unloading' http://purl.obolibrary.org/obo/GO_1905343
- [ ] 'regulation of mitotic cohesin unloading' http://purl.obolibrary.org/obo/GO_1905410
- [ ] 'negative regulation of cohesin unloading' http://purl.obolibrary.org/obo/GO_1905338
- [ ] 'positive regulation of cohesin unloading' http://purl.obolibrary.org/obo/GO_1905339
- [ ] 'positive regulation of mitotic cohesin unloading' http://purl.obolibrary.org/obo/GO_1905411
- [ ] 'cohesin loading' http://purl.obolibrary.org/obo/GO_0071921
- [ ] 'mitotic cohesin loading' http://purl.obolibrary.org/obo/GO_0061780
- [ ] 'mitotic cohesin dsDNA (leading strand) loading' http://purl.obolibrary.org/obo/GO_0062021
- [ ] 'mitotic cohesin ssDNA (lagging strand) loading' http://purl.obolibrary.org/obo/GO_0062022
- [ ] 'regulation of cohesin loading' http://purl.obolibrary.org/obo/GO_0071922
- [ ] 'regulation of mitotic cohesin loading' http://purl.obolibrary.org/obo/GO_1905405
- [ ] 'negative regulation of cohesin loading' http://purl.obolibrary.org/obo/GO_0071923
- [ ] 'positive regulation of cohesin loading' http://purl.obolibrary.org/obo/GO_1905309
- [ ] 'negative regulation of mitotic cohesin loading' http://purl.obolibrary.org/obo/GO_1905412
- [ ] 'positive regulation of mitotic cohesin loading' http://purl.obolibrary.org/obo/GO_1905406
- [ ] 'negative regulation of mitotic cohesin dsDNA (leading strand) loading' http://purl.obolibrary.org/obo/GO_0106115
- [ ] 'negative regulation of mitotic cohesin ssDNA (lagging strand) loading' http://purl.obolibrary.org/obo/GO_0106112
- [ ] 'positive regulation of mitotic cohesin dsDNA (leading strand) loading' http://purl.obolibrary.org/obo/GO_0106116
- [ ] 'positive regulation of mitotic cohesin ssDNA (lagging strand) loading' http://purl.obolibrary.org/obo/GO_0106113
- [ ] GO:0106114 regulation of mitotic cohesin dsDNA (leading strand) loading
