### ISSUE TITLE
Changes to children of GO:0016462 pyrophosphatase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23401]
In the ticket #23319 @sjm41 uncovered several modifications that should be made to children of GO:0016462 pyrophosphatase activity. Terms and suggested changes are here: https://docs.google.com/spreadsheets/d/1_LSxmArtht1kj4cuHjTBKUgokwgqHF1keM8KLugAQoY/edit#gid=0

- [x] GO:0097382 deoxynucleoside-diphosphatase activity : grouping term for a single term, [GO:0097383 dIDP diphosphatase activity](http://amigo.geneontology.org/amigo/term/GO:0097383#display-lineage-tab). No annotations == > obsolete
- [x] move GO:0097383 dIDP diphosphatase activity under GO:0017110  nucleoside-diphosphatase activity [+]

* GO:0004551 nucleotide diphosphatase activity:
- [x]  remove EC:3.6.1.9, which corresponds to GO:0047429  nucleoside-triphosphate diphosphatase activity (EC already correctly on GO:0047429)
- [x] change label to dinucleotide phosphatase activity

-- | --

**Comment by pgaudet** [comment]
- [x] GO:0017111 nucleoside-triphosphatase activity: 
* change label to nucleoside triphosphate phosphatase activity
* Add back EC:3.6.1.15

**Comment by pgaudet** [comment]
- [ ] GO:0017110 nucleoside-diphosphatase activity
* change label to nucleoside diphosphate phosphatase activity

**Comment by pgaudet** [comment]
GO:0052842 inositol diphosphate pentakisphosphate diphosphatase activity 
GO:0052840 inositol diphosphate tetrakisphosphate diphosphatase activity 

==> remove EC:3.6.1.52; this is correctly on GO:0008486 diphosphoinositol-polyphosphate diphosphatase activity	but not relevant for tetra and penta

**Comment by pgaudet** [comment]
From @sjm41 
References for GO:0004551  

Nakajima Y, Fukunaga N, Sasaki S, Usami S (1973). "Purification and properties of NADP pyrophosphatase from Proteus vulgaris". Biochim. Biophys. Acta. 293 (1): 242–55. [doi](https://en.wikipedia.org/wiki/Doi_(identifier)):[10.1016/0005-2744(73)90397-5](https://doi.org/10.1016%2F0005-2744%2873%2990397-5). [PMID](https://en.wikipedia.org/wiki/PMID_(identifier)) [4405504](https://pubmed.ncbi.nlm.nih.gov/4405504)

Shin HJ, Mego JL (1988). "A rat liver lysosomal membrane flavin-adenine dinucleotide phosphohydrolase: purification and characterization". Arch. Biochem. Biophys. 267 (1): 95–103. [doi](https://en.wikipedia.org/wiki/Doi_(identifier)):[10.1016/0003-9861(88)90012-4](https://doi.org/10.1016%2F0003-9861%2888%2990012-4). [PMID](https://en.wikipedia.org/wiki/PMID_(identifier)) [2848456](https://pubmed.ncbi.nlm.nih.gov/2848456)

**Comment by pgaudet** [comment]
@sjm41 I think GO:0010943 NADPH pyrophosphatase activity corresponds to RHEA:60820

**Comment by pgaudet** [comment]
Standardized term labels: 

- [ ] GO:0004382 guanosine-diphosphatase activity ->  GDP diphosphatase activity
- [ ] GO:0036384 cytidine-diphosphatase activity ->  CDP diphosphatase activity
- [ ] GO:0043262 adenosine-diphosphatase activity -> ADP diphosphatase activity
- [ ] GO:0045134 uridine-diphosphatase activity -> UDP diphosphatase activity 
- [ ] GO:1990003 inosine-diphosphatase activity ->  IDP diphosphatase activity

**Comment by sjm41** [comment]
_I think GO:0010943 NADPH pyrophosphatase activity corresponds to RHEA:60820_

Ah yes, that's looks correct. And rhea says it's used on 1,396 UniProt proteins, so we should probably keep the GO term (even though no-one has used it to date!)

I see we can also add RHEA:48868 to NADH pyrophosphatase activity | GO:0035529

**Comment by sjm41** [comment]
Standardized term labels:

  GO:0004382 guanosine-diphosphatase activity -> GDP diphosphatase activity
  GO:0036384 cytidine-diphosphatase activity -> CDP diphosphatase activity
  GO:0043262 adenosine-diphosphatase activity -> ADP diphosphatase activity
  GO:0045134 uridine-diphosphatase activity -> UDP diphosphatase activity
  GO:1990003 inosine-diphosphatase activity -> IDP diphosphatase activity

@pgaudet I think the new names here should be just 'XXX phosphatase activity' rather than 'XXX diphosphatase activity'
E.g. GO:0004382 is "Catalysis of the reaction: GDP + H2O = GMP + phosphate"

**Comment by sjm41** [comment]
@paolaroncaglia @deustp01 The original term Peter requested (GO:0097383 dIDP diphosphatase activity) is being retained but under the grouping term "nucleoside diphosphate phosphatase activity (GO:0017110)".  That grouping term already has several child terms, whereas the "deoxynucleoside-diphosphatase activity" grouping term only had that single child.  The change is consistent with how GO already organises children of "nucleoside triphosphate diphosphatase activity (GO:0047429)".

**Comment by pgaudet** [comment]
thanks @sjm41 
The children of 'nucleoside diphosphate phosphatase activity' are now: 

'8-hydroxy-dADP phosphatase activity'
'8-oxo-dADP phosphatase activity'
'8-oxo-dGDP phosphatase activity'
'8-oxo-GDP phosphatase activity'
'ADP phosphatase activity'
'CDP phosphatase activity'
'dIDP phosphatase activity'
'GDP phosphatase activity'
'IDP phosphatase activity'
'thiamine diphosphatase activity'
'UDP phosphatase activity'

**Comment by sjm41** [comment]
@pgaudet We changed the name of thymidine-triphosphatase activity	(GO:0050339) to 'TTPase activity', but I think it should be 'dTTPase activity' to match the definition and xref.
('thymidine' is a synonym for 'deoxythymidine'/'dT')

**Comment by deustp01** [comment]
> So, these two terms should be moved to be direct children of 'pyrophosphatase activity':

Something is wrong here. GO:0016462 pyrophosphatase activity is "Catalysis of the hydrolysis of a pyrophosphate bond between two phosphate groups, leaving one phosphate on each of the two fragments" but RHEA:11744 shows a phosphatase reaction (removal of a single phosphate group as free phosphate, not attached to anything). Likewise for GO:0004787 - that looks like phosphatase activity, not pyrophosphatase activity.

**Comment by sjm41** [comment]
@deustp01 I think the GO def should probably omit the "leaving one phosphate on each of the two fragments" bit and just say "Catalysis of the hydrolysis of a pyrophosphate bond between two phosphate groups."

What do you think?

There's no reference for the current GO def and I can't easily find a good definition/reference from web searches. Certainly nothing saying a phosphate must remain attached to each fragment.  Do you know of a good reference saying that?

Note that GO:0050333/RHEA:11744/3.6.1.28 and GO:0004787/RHEA:27998 are both already classified under pyrophosphase activity GO:0016462 (and thereby under EC:3.6.1.- via its parent GO term) in the current public GO.  I don't think they should/can be classified under the regular 'phosphatase activity' GO:0016791 term as that term is defined as "Catalysis of the hydrolysis of phosphoric monoesters" and represents a different branch of EC (3.1.3.-).

**Comment by deustp01** [comment]
> What do you think?

I think I'm out of my depth, arguing about the EC distinctions, which have both history and real expertise in chemistry behind them.

I was relying on my recollection of textbook biochemistry. Pyrophosphate (diphosphate; CHEBI:33019 - diphosphate(3−)) is released in many biosynthetic reactions. "The splitting of inorganic pyrophosphate (PPi) to two phosphate (Pi) groups is catalyzed by pyrophosphatases that apparently occur universally. Their function appears to be simply to remove the product PPi from reactions that produce it, shifting the equilibrium toward formation of a desired compound." (Metzler, "Biochemistry: The Chemical Reactions of Living Cells" 1st ed., 1977 - page 635). One could extrapolate from there to assert that hydrolysis between the two phosphate groups in a molecule R1-Pi-Pi- R2 to yield R1-Pi + R2-Pi is an example of pyrophosphatase activity (because the pyrophosphate moiety is what actually is cleaved) while hydrolysis of R-Pi-Pi-Pi to yield R-Pi-Pi + Pi is phosphatase activity.

That may be logical but, apparently, not standard reasoning.

**Comment by pgaudet** [comment]
- [ ] need to look at the definition of GO:0017111; in GO the substrate is a nucleoside triphosphate , in RHEA (RHEA:23680) it's a ribonucleoside triphosphate - not consistent

**Comment by pgaudet** [comment]
- [x] XTP diphosphatase activity, moved from -is_a: GO:0017111 ! nucleoside triphosphate phosphatase activity to 
+is_a: GO:0047429 ! nucleoside triphosphate diphosphatase activity

**Comment by deustp01** [comment]
> * need to look at the definition of GO:0017111; in GO the substrate is a nucleoside triphosphate , in RHEA (RHEA:23680) it's a ribonucleoside triphosphate - not consistent

In ChEBI, CHEBI:61557 - nucleoside 5'-triphoshate(4−) is_a ribonucleoside 5'-triphosphate(4−), so it looks like there's a parentage issue at ChEBI (also a spelling issue - missing p in phoshate.

Meanwhile, there is a RHEA reaction for dNTP's, [RHEA:64916](https://www.rhea-db.org/rhea/64916) with 2'-deoxyribonucleoside 5'-triphosphate(4−) ([CHEBI:61560](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A61560)) as input.

**Comment by pgaudet** [comment]
As far as @sjm41  and I can tell, Thiamine is a pyrimidine but not a nucleoside - ie it doesn't have a  sugar attached. 
So we'll move it from is_a 'nucleoside triphosphate phosphatase activity' to is_a 'pyrophosphatase'

@kaxelsen if you have a minute to check this, we'd much appreciate it.

**Comment by pgaudet** [comment]
- [ ] thiamine phosphate phosphatase activity addxrefs: 

* RHEA:47948 | H2O +   thiamine phosphate =   phosphate +   thiamine | 
* EC:3.1.3.100 Thiamine phosphate phosphatase

**Comment by sjm41** [comment]
- [ ] add EC:3.6.1.67 as xref to GO:0019177 dihydroneopterin triphosphate pyrophosphohydrolase activity

**Comment by sjm41** [comment]
Thanks @kaxelsen. Our latest edits address all of your comments and I think we're on the same page :-)

**Comment by pgaudet** [comment]
Looks like everything was done here
