### ISSUE TITLE
Obsolete "GO:0097573 glutathione oxidoreductase activity"?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23411]
* **GO term ID and Label**
GO:0097573 glutathione oxidoreductase activity
Def: Catalysis of the reaction: protein-S-S-glutathione + glutathione-SH = protein-SH + glutathione-S-S-glutathione. PMID:18992757 

* **Reason for deprecation**
I'm not sure this enzymatic reaction/activity really exists. There's no corresponding EC/RHEA. The PMID in the definition talks about S. cerevisiae glutaredoxins Grx1 and Grx2, but those proteins aren't given this term by SGD/UniProt.

There is only one EXP annotation (to Q8GWS0, Arabidopsis GRXC5), and we think that is wrong (see https://github.com/geneontology/go-annotation/issues/3684#issuecomment-1140935805) @tberardini ?

Other annotations are IEA via InterPro:IPR002109 & IPR011901, and those associations are being removed (see https://github.com/geneontology/go-annotation/issues/3684#issuecomment-1138300244)

* **Are there annotations to this term?**
- How many EXP: one (see above)

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
- Two InterPro mapping (see above)

* **Is this term in a subset? (check the AmiGO page for that term)**
No

FYI @kaxelsen

**Comment by pgaudet** [comment]
PMID:18992757 seems to distinguish between GO:0097573 glutathione oxidoreductase activity (monothiol mechanism) and 
 GO:0015038 glutathione disulfide oxidoreductase activity (dithiol mechanism): Catalysis of the reaction: 2 glutathione + electron acceptor = glutathione disulfide + electron donor.

Although is that distinction relevant for GO ? 

Also, this reaction is NADPH-dependent (regardless of the mechanism, see  Fig 1 in PMID:18992757), so we could possibly merge 

* GO:0015038 | glutathione disulfide oxidoreductase activity (no EC, no RHEA)
* GO:0097573 | glutathione oxidoreductase activity (no EC, no RHEA)
* into GO:0004362 | glutathione-disulfide reductase (NADPH) activity (RHEA:11740; EC:1.8.1.7)

I checked the annotations to [GO:0015038 | glutathione disulfide oxidoreductase activity](https://docs.google.com/spreadsheets/d/1E-iKsWfinL_KP5cTXdwayIKPZ6RfJKl5KfvOkf9EoHk/edit#gid=0)


What do you think @sjm41 @kaxelsen ? 

Thanks, Pascale

**Comment by sjm41** [comment]
Hi Pascale

**GO:0015038 | glutathione disulfide oxidoreductase activity (no EC, no RHEA)**
This is a grouping term in GO, for these two children (one NADPH-dependent, one ascorbate-dependent):

GO:0015038 | glutathione disulfide oxidoreductase activity (no EC, no RHEA)
    |_GO:0004362 | glutathione-disulfide reductase (NADPH) activity (RHEA:11740; EC:1.8.1.7)
    |_GO:0045174 | glutathione dehydrogenase (ascorbate) activity [RHEA:24424; EC:1.8.5.1]

So I think we should keep these three terms as they are, and not merge GO:0015038 with GO:0004362.

Maybe "GO:0015038 | glutathione disulfide oxidoreductase activity" should be marked as 'do no annotate'?

That just leaves "GO:0097573 | glutathione oxidoreductase activity (no EC, no RHEA)".
Question is whether we need this to specifically annotate the "monothiol mechanism of action of glutaredoxins", and distinguish that from the "dithiol mechanism of action of glutaredoxins". I'm sure @kaxelsen will say no, as glutaredoxins are electron carriers rather than enzymes in his view.

From that perspective, "GO:0004362 | glutathione-disulfide reductase (NADPH) activity (EC:1.8.1.7)" is meant to be specific for glutathione reductase (GR) rather than glutaredoxins (GRX).  I see a few SGD annotations using this term to GRXs.

**Comment by sjm41** [comment]
Update: QuickGO now says there are just 4 annotations to this term - 2 IEA via EnsemblPlants, 1 TAS, and 1 IDA to Arabidopsis GRXC5 (as mentioned above).

**Comment by pgaudet** [comment]
Maybe this is a just a synchronization problem - when was the 2022 Q3 released?

**Comment by sjm41** [comment]
On the other hand, Amigo (but not QuickGO) still shows all the InterPro2GO mappings to this term, which were removed from InterPro months ago...

**Comment by pgaudet** [comment]
I dont think this is surprising - there is a delay from the Interpro change to the InterPro release, then there is the GOA release, and the data gets into the GO Central release from GOA...

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0097573 glutathione oxidoreductase activity. The reason for obsoletion is that this term is redundant with other terms. It dosen't have any EC or RHEA mappings. 

There is a single annotation to this term by BHF, see https://github.com/geneontology/go-annotation/issues/4414

Consider: 
* GO:0015038 glutathione disulfide oxidoreductase activity or children: 
**  GO:0045174 glutathione dehydrogenase (ascorbate) activity
** GO:0004362 glutathione-disulfide reductase (NADPH) activity

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/23411

Thanks, Pascale

**Comment by tberardini** [comment]
2022 Q3 TAIR association file was released on 10-01-2022.

**Comment by pgaudet** [comment]
Thanks @tberardini 

I made a not elsewhere to make sure this is in the next GOA release, so far our hypothesis is that the file loaded from GOA was older than that.
