### ISSUE TITLE
NTR: [Tubulin-tyrosine carboxypeptidase]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#23419]
Hi GO,

I would need a reaction for Tubulin-tyrosine carboxypeptidase,  which removes the C-terminal tyrosine of alpha-tubulin. Note that we already have a GO term for the enzyme that mediates the reverse and adds a tyrosine at the C-terminus (GO:0004835)

Thanks

Sylvain

Name:  Tubulin-tyrosine carboxypeptidase
Definition: Catalysis of the reaction: ATP + detyrosinated alpha-tubulin + L-tyrosine = alpha-tubulin + + H2O = detyrosinated alpha-tubulin + L-tyrosine
Child of GO:0004181; F:metallocarboxypeptidase activity
Xref EC=3.4.17.17
Xref Rhea:57444
PMID:29146869
PMID:35482892

**Comment by hdrabkin** [comment]
Your definition is a little confusing.  The reaction does not need ATP, and the substrate is tyrosinated alpha-tubulin.
C-terminal L-α-aminoacyl-L-glutamyl-L-glutamyl-L-tyrosyl-[tubulin] + H2O = C-terminal L-α-aminoacyl-L-glutamyl-L-glutamyl-[tubulin] + L-tyrosine

**Comment by hdrabkin** [comment]
And I need more coffee as I put def refs on the term and not on the def.  sigh
