### ISSUE TITLE
Terme merge: GO:0103073 & GO:0102077

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#23420]
* **GO term ID and label for which you request a new superclass**
GO:0103073 anandamide amidohydrolase activity
GO:0102077 oleamide hydrolase activity

* **New superclass (parent) suggested**
GO:0017064 fatty acid amide hydrolase activity

Both GO:0103073 and GO:0102077 have this EC xref:
3.5.1.99
Name: Fatty acid amide hydrolase
Alt Names: Anandamide amidohydrolase, Oleamide hydrolase.
Comments: the enzyme is responsible for the catabolism of neuromodulatory fatty acid amides, including anandamide and oleamide, occurs in mammalia. 

Options:
1. Add GO:0017064 as parent to both GO:0103073 and GO:0102077; add EC:3.5.1.99 to GO:0017064 too.
2. Merge GO:0103073 and GO:0102077 into GO:0017064; add EC:3.5.1.99 to GO:0017064.

GO:0103073 has one EXP annotation (P97612)
GO:0102077 has no EXP annotations.

**Comment by pgaudet** [comment]
I think the merge is right. The single EXP annotation to GO:0103073 anandamide amidohydrolase activity is to a fatty acid hydrolase protein. 

Thanks, Pascale
