### ISSUE TITLE
Taxon constraint: transforming growth factor beta receptor signaling pathway GO:0007179

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#23449]
transforming growth factor beta receptor signaling pathway GO:0007179
(as this is for the subfamily not the superfamily)

Only in taxon: Deuterostome

PMID: 35309318 "TGF-b superfamily members: 
TGF-betas, Activins, Inhibins, bone morphogenetic proteins (BMPs), growth, and differentiation factors (GDFs), Nodals, Myostatins, MIS (Müllerian-inhibiting substance), and Lefty. 

Members of the TGF-beta superfamily have emerged since the early evolution of the animal kingdom, and conserved members of the TGF-b pathway arepresent in all metazoans studied. The first members of theTGF-b superfamily to emerge were BMPs/GDFs, which subsequently differentiated into Activins/Inhibins, while the ‘true’ TGF-b subfamily emerged later and is only present in deuterostomes.

**Comment by vanaukenk** [comment]
This taxon restriction is still causing issues for C. elegans annotations.
In Padua, we discussed the possibility of having a grouping class, e.g. transforming growth factor beta-like signaling pathway, or maybe we could define the existing pathway terms more precisely by including components downstream of the receptor and that might help.
Either way, it'd be good to sort this out, perhaps on one of the signaling group calls or an ontology call.
Thx.

**Comment by hattrill** [comment]
@vanaukenk just commenting to say that I've seen this and it's on the list. Will look at it today.

**Comment by vanaukenk** [comment]
Thanks @hattrill

**Comment by hattrill** [comment]
Hi @vanaukenk 
In QuickGO I can see 19 annotations under 
GO:0007179	transforming growth factor beta receptor signaling pathway
for c.elegans

It looks like there are three TGFR class receptors in c.elegans:
sma-6 & daf-4 are part of GO:0030509 BMP signaling pathway
and 
daf-1 is part of GO:0032924 activin receptor signaling pathway

I am wondering if you could assign these annotations to either:
GO:0030509	BMP signaling pathway
or
GO:0032924	activin receptor signaling pathway

rather than fixing it with an umbrella class term for this one?

sma-10 has been shown to interact with sma-6 & daf-4, but looks like it's probably a regulator of BMP signaling than part of.

for components that act at the level of SMAD protein signal transduction, perhaps annotate to this term or regulation terms.

**Comment by vanaukenk** [comment]
Thanks @hattrill 

I think what I am wrestling with is reconciling orthology data with GO classes.

In C. elegans, we have two Type I receptors, but only a single Type II receptor that does double duty.

In one case, the Type II receptor (and other genetically/physically defined members of that pathway) could reasonably be annotated to the BMP receptor signaling pathway term, but in the other case, that same Type II receptor combines with what looks to be a Type I activin-like receptor.  The ligand in this other pathway seems to group with the vertebrate GDFs.
So for the latter example, would you recommend annotating all members of that signaling pathway to both the activin receptor and BMP receptor signaling pathways?

I'm beginning to understand better now why in the C. elegans literature they describe signaling through the different Type I and Type II receptors and the phenotypic outcomes, but don't always choose a more specific TGFb superfamily signaling pathway to reference.

Let me know if it'd be easier to chat in person.

**Comment by hattrill** [comment]
Hi @vanaukenk I think that if you have had a good go at it and can't put it the pots that we have in GO, then you do need the TGFb superclass term.

Perhaps we need to think of a term pattern that could be used for other superfamilies?
transforming growth factor beta receptor superfamily signaling pathway
rather than -like (as might be confusing with situations where "like" is used for a non-umbrella pathway e.g. insulin-like growth factor type.

**Comment by vanaukenk** [comment]
Thanks @hattrill 

I like the idea of creating a new 'transforming growth factor beta receptor superfamily signaling pathway' parent term that we could use for annotation, when the various members of the C. elegans pathways don't all fit neatly into one of the more specific child pathway terms.

Shall I create that NTR?

**Comment by hattrill** [comment]
Yes :-)

**Comment by hattrill** [comment]
@vanaukenk I am happy with that.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141091
+name: transforming growth factor beta receptor superfamily signaling pathway
+namespace: biological_process
+def: "The series of molecular signals initiated by an extracellular ligand binding to a member of the transforming growth factor receptor superfamily, and ending with the regulation of a downstream cellular process, e.g. transcription." [PMID:22651914, PMID:28096268]
+synonym: "TGF-beta receptor superfamily signaling pathway" EXACT []
+synonym: "TGF-beta receptor superfamily signalling pathway" EXACT []
+synonym: "TGFbeta receptor superfamily signaling pathway" EXACT []
+synonym: "TGFbeta receptor superfamily signalling pathway" EXACT []
+synonym: "transforming growth factor beta receptor superfamily signalling pathway" EXACT []
+is_a: GO:0007178 ! transmembrane receptor protein serine/threonine kinase signaling pathway
+created_by: pg
+creation_date: 2023-08-30T05:48:29Z

**Comment by pgaudet** [comment]
@vanaukenk Does this (not so new) "new" term (GO:0141091 transforming growth factor beta receptor superfamily signaling pathway) address the C elegans issue? 

Note that right now that GO:0141091 transforming growth factor beta receptor superfamily signaling pathway doesn't have TC yet; could we add only Metazoa?

**Comment by vanaukenk** [comment]
Thanks @pgaudet @hattrill 

Yes, I think that new term addresses the C. elegans annotation issues.
I *think* we could add an 'only in Metazoa' TC for this term.
