### ISSUE TITLE
Merge or obsolete     GO:0062103 double-stranded RNA biosynthetic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23443]
There is a single paper annotated to GO:0062103 double-stranded RNA biosynthetic process, PMID:19701182, that describes GO:0001172 RNA-templated transcription (or maybe its child, GO:0140745 siRNA transcription)

@RLovering your group has annotated to this term - should we obsolete and replace by GO:0001172 RNA-templated transcription, or merge?  

Thanks, Pascale

**Comment by RLovering** [comment]
Thanks Pascale

I have changed the GO:0062103 double-stranded RNA biosynthetic process annotations to siRNA transcription

please do what ever is appropriate with GO:0062103 double-stranded RNA biosynthetic process

Best

Ruth

**Comment by pgaudet** [comment]
Thanks, I will merge into the parent GO:0032774 RNA biosynthetic process

Pascale
