### ISSUE TITLE
Move 'utilization' terms under 'response to nutrient levels' (was: Move 'utilization' terms under 'metabolic process')

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23458]
Move: 

- [x] 'carbon utilization' -> is_a organic substance metabolic process (not has part)
& remove 
-is_a: GO:0008150 ! biological_process
-relationship: has_part GO:0071702 ! organic substance transport
-relationship: has_part GO:0071703 ! detection of organic substance
-relationship: has_part GO:0071704 ! organic substance metabolic process

- [x] 'carbohydrate utilization' -> is_a carbohydrate metabolic process
 & remove 
-relationship: has_part GO:0005975 ! carbohydrate metabolic process
-relationship: has_part GO:0008643 ! carbohydrate transport
-relationship: has_part GO:0009730 ! detection of carbohydrate stimulus

- [x] 'sulfur utilization'  -> is_a  sulfur compound metabolic process
 -is_a: GO:0008150 ! biological_process
-relationship: has_part GO:0006790 !

- [x] 'nitrogen utilization'  -> is_a nitrogen compound metabolic process
-is_a: GO:0008150 ! biological_process
-relationship: has_part GO:0071705 ! nitrogen compound transport

**Comment by ValWood** [comment]
Is that correct? I thought utilization also includes transport (unless we now say that transport is part of metabolism?)

I expect ed utilization terms to be parents of metabolism terms when present.

**Comment by pgaudet** [comment]
I will move the terms under 'response to nutrient levels' - I hope that's better. 

Thanks, Pascale

**Comment by ValWood** [comment]
yup.
