### ISSUE TITLE
Taxon constraint:  numerous

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23452]
Please provide as much information as you can: 

* **GO term ID label:**

Add taxon constraints for
GO:0005902 microvillus 
GO:0032528 microvillus organization
GO:0030175 filopodium (motile cells)
GO:0046847 filopodium assembly
stereocilium GO:0032420 (auditory and vestibular hair cells)
GO:0043005  neuron projection
GO:0005903 brush border
GO:1904970 brush border assembly
GO:0001931 uropod (def seems to define as immunological cells)
GO:0034460 uropod assembly
GO:0044393 microspike 
GO:0030035 microspike assembly

All are never in fungi, but some could probably be only in metazoa?

**Comment by krchristie** [comment]
This is a very quick ticket if I just add **never in fungi** to all of these terms.

Trying to decide if **only in metazoa** is appropriate, or not, for these terms turns this ticket into 7 different literature research questions. 

A very quick look at the paper @ukemi suggested quickly indicates that **only in metazoa** is too specific for the two **microvillus** terms as microvilli are also present in Choanoflagellates, but knowing what IS appropriate would be harder to determine.

@pgaudet - Do I remember correctly that we decided that curators should not spend a ton of time trying to track this stuff down as @thomaspd has a plan to do taxon constraints systematically? In the interest of expediency, I'd like to just add the **never in fungi** constraints that @ValWood has requested and NOT look into what *only in ______** terms might apply to each of these structures.

**Comment by ValWood** [comment]
If anything is defined so it would be restricted to metazoa, I think you could add "never in metazoa".

That would apply to 
stereocilium GO:0032420 (auditory and vestibular hair cells)
and
GO:0043005 neuron projection
for example. If these turn out to be incorrect the term is not defined broadly enough and would need to be revisited anyway to increase the species scope.

For  those where the existing definition does not restrict, I would add only "never in fungi" for now.

**Comment by krchristie** [comment]
> If anything is defined so it would be restricted to metazoa, I think you could add "never in metazoa".

You mean **only in Metazoa**
 
> That would apply to stereocilium GO:0032420 (auditory and vestibular hair cells) and GO:0043005 neuron projection for example. If these turn out to be incorrect the term is not defined broadly enough and would need to be revisited anyway to increase the species scope.
> 
> For those where the existing definition does not restrict, I would add only "never in fungi" for now.

I think that's a good approach

**Comment by krchristie** [comment]
Hi @ValWood 

I ended up NOT adding the two specific "**only in metazoa**" constraints you suggested previously as when I checked what should be inferred using the instructions in the link below, it looked to me like these are already inferred:

https://wiki.geneontology.org/Adding_Taxon_Restrictions#Checking_existing_taxon_constraints

I have added all of the "**never in Fungi**" constraints you requested.

@pgaudet @balhoff - Should we discuss this at an ontology editors call to check if I understood the instructions correctly, and then if these constraints are inferred, are he inferred constraints available to people like @ValWood to use in addition to the directly asserted ones?

**Comment by balhoff** [comment]
@krchristie I think it would be great to review that on an ontology editors call (you did it right!). Yes, the inferred constraints are used by Val when PomBase runs their species-subset command in owltools.

**Comment by pfey03** [comment]
For Dicty is should be allowed to use:

GO:0030175 filopodium (motile cells) 40 annotations most IDA some IC
GO:0046847 filopodium assembly. 22 EXP
GO:0001931 uropod (def seems to define as immunological cells) (change DEF) we have 6 EXP to this term
GO:0034460 uropod assembly - none but I will check some papers maybe just missed
GO:0044393 microspike not used but when entered Dicty + microspike in PM I found several papers and will check them 
GO:0030035 microspike assembly

**Comment by krchristie** [comment]
> @krchristie For Dicty these must absolutely be allowed to use:
> 
> GO:0030175 filopodium (motile cells) 40 annotations most IDA some IC GO:0046847 filopodium assembly. 22 EXP GO:0001931 uropod (def seems to define as immunological cells) (change DEF) we have 6 EXP to this term GO:0034460 uropod assembly - none but I will check some papers maybe just missed GO:0044393 microspike not used but when entered Dicty + microspike in PM I found several papers and will check them GO:0030035 microspike assembly
> 
> So not just metazoa!!

@pfey03 - Thanks for chiming in with your knowledge. To reassure you, I did **NOT** add any "**only in Eumetazoa**", or any other "**only in ____**", constraints to any of the terms in this ticket. I knew from the paper @ukemi had suggested that this constraint was NOT appropriate for "microvillus" and did not want to do the research to make determine what "**only in ____**" would be appropriate for these terms.

For the two terms (stereocilium & neuron projection) that @ValWood had suggested that "If anything is defined so it would be restricted to metazoa, I think you could add "never only in metazoa".", I also did add any directly asserted "**only in Eumetazoa**" constraints as these terms already inherit this as inferred constraint.
