### ISSUE TITLE
GO:0008260  3-oxoacid CoA-transferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23466]
GO:0008260  3-oxoacid CoA-transferase activity
Catalysis of the reaction: succinyl-CoA + a 3-oxo acid = succinate + a 3-oxo-acyl-CoA.

has related synonym
Succinyl-CoA:3-ketoacid-CoA transferase.

Should this be exact?
Could it be primary?

seems to be more used:
https://www.uniprot.org/uniprot/P55809#function

**Comment by ValWood** [comment]
In that case can we have a GO term for
Succinyl-CoA:3-ketoacid-CoA transferase?

**Comment by ValWood** [comment]
note that Hu SCOT =  Hu OXCT1

**Comment by ValWood** [comment]
SGD says
Protein with CoA transferase activity; particularly for CoASH transfer from succinyl-CoA to acetate;
so I feel confident to annotate the fission yeast ortholog to this specific term.

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106424
+name: succinyl-CoA 3-ketoacid-CoA transferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: a 3-keto acid + succinyl-CoA = a 3-ketoacyl-CoA + succinate." [GOC:vw, PMID:10964512, PMID:8844009]
+is_a: GO:0008260 ! 3-oxoacid CoA-transferase activity
+property_value: creation_date 2022-06-10T14:37:09Z xsd:dateTime
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23466 xsd:anyURI
+created_by: hjd

**Comment by hdrabkin** [comment]
I'm leaving this open until I hear back from RHEA to confirm

**Comment by hdrabkin** [comment]
@kaxelsen 
Do you think we then should merge the new term id: GO:0106424
+name: succinyl-CoA 3-ketoacid-CoA transferase activity into GO:0008260 3-oxoacid CoA-transferase activity?

**Comment by kaxelsen** [comment]
From what you write it looks like GO:0106424 is a GO:000826

**Comment by hdrabkin** [comment]
Ok I'll leave it then. But with no RHEA.

**Comment by suzialeksander** [comment]
OK, so is GO agreeing that "a 3-keto acid" = "a 3-oxo acid" ?  

So now aren't the definitions for  GO:0106424 and GO:0008260 identical?

a 3-keto acid + succinyl-CoA = a 3-ketoacyl-CoA + succinate
succinyl-CoA + a 3-oxo acid = succinate + a 3-oxo-acyl-CoA

**Comment by deustp01** [comment]
> OK, so is GO agreeing that "a 3-keto acid" = "a 3-oxo acid" ?

From @hdrabkin quoting @kaxelsen below, in this case 3-oxo is the definitive standard correct chemical usage so, yes, GO should follow it. (This may also reflect usage differences between US and UK/European biochemists, with US people holding on to keto despite the official preferred usage)

> @ValWood @kaxelsen just emailed me 'Hi Harold,
> 
> I think the current problem is based on a difference in the usage of the terminology. I have consulted the IUPAC Gold Book to get the precise chemical definitions for the terms used here.

**Comment by kaxelsen** [comment]
> OK, so is GO agreeing that "a 3-keto acid" = "a 3-oxo acid" ?
> 
> So now aren't the definitions for GO:0106424 and GO:0008260 identical?
> 
> a 3-keto acid + succinyl-CoA = a 3-ketoacyl-CoA + succinate succinyl-CoA + a 3-oxo acid = succinate + a 3-oxo-acyl-CoA
> 

To me, yes these are identical.

**Comment by ValWood** [comment]
So, this goes back to my original comment to make 

Succinyl-CoA:3-ketoacid-CoA transferase.

the primary name instead of a related synonym, since it seems to more used? (and seems clearer)

**Comment by kaxelsen** [comment]
I disagree. Your suggested name includes 3-ketoacid-CoA which is NOT recommended nomenclature. This is what I have tried to explain all throughout this thread.

**Comment by ValWood** [comment]
So we make
Succinyl-CoA:3-oxo acid-CoA transferase the primary name
Succinyl-CoA:3-ketoacid-CoA transferase = exact synonym
 3-oxoacid CoA-transferase activity = exact synonym
of GO:0008260
 and merge new  GO:0106424  into GO:0008260

Or is the original definition of GO:0008260 too broad?

**Comment by kaxelsen** [comment]
That sounds much better

> Or is the original definition of GO:0008260 too broad?

It would be better if succinate (or succinyl-CoA) was mentioned in the definition

**Comment by ValWood** [comment]
actually the def is 
Catalysis of the reaction: succinyl-CoA + a 3-oxo acid = succinate + a 3-oxo-acyl-CoA.

**Comment by kaxelsen** [comment]
Oh, I looked at the name. 

The definition is unambiguous. I don't know why you think it could be too broad, that should only be if you would like to have a specific 3-oxo acid, but that would just be a child of this.

**Comment by ValWood** [comment]
> I don't know why you think it could be too broad
ignore that. I did not check. I forgot how we got here.

So actions:

GO:0008260
make
Succinyl-CoA:3-oxo acid-CoA transferase the primary name
Succinyl-CoA:3-ketoacid-CoA transferase = exact synonym
3-oxoacid CoA-transferase activity = exact synonym


and merge new GO:0106424 into GO:0008260

**Comment by kaxelsen** [comment]
> Or is the original definition of GO:0008260 too broad?

You wrote it yourself this morning ;-)

**Comment by hdrabkin** [comment]
Before I begin doing this is everyone happy with this @ValWood 's suggestion
For GO:0008260
make
Succinyl-CoA:3-oxo acid-CoA transferase the primary name
Succinyl-CoA:3-ketoacid-CoA transferase = exact synonym
3-oxoacid CoA-transferase activity = exact synonym
and merge new GO:0106424 into GO:0008260
?

**Comment by hdrabkin** [comment]
Done as suggested above

**Comment by hdrabkin** [comment]
need to fix duplicate synonyms.

**Comment by hdrabkin** [comment]
fixed
