### ISSUE TITLE
 regulation of cellular protein metabolic process" pending obsoletion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23462]
@pgaudet 
I don't have any annotations to this term apart from this one, and it doesn't have any descendants so I suspect it is pending obsoletion?

GO:0032268 | regulation of cellular protein metabolic process | IEA with ARBA00028280 | GO_REF:0000117

**Comment by ValWood** [comment]
(the other 7000 annotation all appear to be from ARBA)

**Comment by pgaudet** [comment]
Merged up in #17904
