### ISSUE TITLE
Check GO:0035042 fertilization, exchange of chromosomal proteins

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23465]
This term is probably not defined correctly and not is_a fertilization - this happens *after* fertilization

@colinlog @hattrill

**Comment by hattrill** [comment]
looks like in some cases like dnd 'sperm DNA decondensation' would be more correct and others are exchange factors that act somewhen after deconsensation and the first zygotic cycle.

**Comment by pgaudet** [comment]
@hattrill I will let you review the annotations (11 flybase; no other group has used this term), and decide what to do. 

Thanks, Pascale

**Comment by hattrill** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/hla28/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/hla28/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



GENE PRODUCT ID | SYMBOL | QUALIFIER | REFERENCE
-- | -- | -- | --
O17468 | Hira | involved_in | PMID:11735001
O17468 | Hira | involved_in | PMID:15988027
Q7KU24 | Chd1 | involved_in | PMID:17717186
P25992 | yem | involved_in | PMID:23408912
Q7JXC4 | P32 | involved_in | PMID:25228646
O17468 | Hira | involved_in | PMID:27876811
P16909 | Mst77F | involved_in | PMID:27876811
P47938 | dhd | involved_in | PMID:27876811
Q9VU52 | snky | involved_in | PMID:27876811
Q9VU52 | snky | involved_in | PMID:9630751



</body>

</html>

**Comment by hattrill** [comment]
Removed all annotations to this term - please obsolete

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0035042 fertilization, exchange of chromosomal proteins'. The reason for obsoletion is that this represents a molecular function (histone chaperone activity) and a process (sperm DNA decondensation). EXP annotations have been removed. There are no mappings to this term; this term is not present in any subsets. 
You can comment on the ticket: 
https://github.com/geneontology/go-ontology/issues/23465

Thanks, Pascale
