### ISSUE TITLE
Missing parent: [GO term] CAT tailing 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23474]
* **GO term ID and label for which you request a new superclass**
CAT tailing (GO:0140708) 
* **New superclass (parent) suggested**
add parent 	GO:0072344	rescue of stalled ribosome

* **Reference(s), if appropriate**
The C-terminal elongation of 60S-anchored stalled nascent polypeptide chains with untemplated alanine and threonine tails (CAT tails). CAT tails participate in the recognition of stalled nascent chains by the ribosome quality control sytem. PMID:25554787 PMID:32934225

**Comment by pgaudet** [comment]
part_of rescue of stalled ribosome? (is_a seems an overstatement)

**Comment by pgaudet** [comment]
This is already 'part of' some 'ribosome-associated ubiquitin-dependent protein catabolic process' - these two terms seems redundant?
