### ISSUE TITLE
Renaming of GO terms GO:0031771 and GO:0031772

### ISSUE THREAD

**Issue by Yvonne-Lussi** [geneontology/go-ontology#23504]
Dear GO team
In relation to a UniProt user request to update the naming of UniProt entries O43612 (human HCRT) and P01189 (human POMC), the user suggested the renaming of the GO terms GO:0031771 "type 1 hypocretin receptor binding" and GO:0031772 "type 2 hypocretin receptor binding". The user suggested to use the names "OX1 and OX2 orexin receptors"  (the digits in subscript) and change the GO terms to "OX1 orexin receptor binding" and "OX2 orexin receptor binding", respectively.  

Would you be so kind to look into this matter and let me know of your decision, so I can forward your reply to the respective user?

Thank you very much for your time.
Best wishes,
Yvonne

**Comment by Yvonne-Lussi** [comment]
Hi Pascale
Thank you very much for your reply about this issue. I understand you are avoiding acronyms for GO terms. Your suggestion to replace 'hypocretin' by 'orexin' and using 'OX1/OX2'  in the synonyms sounds like a good solution to me.
Thank you very much and best wishes, Yvonne

**Comment by pgaudet** [comment]
Also changed 

GO:0061585
-name: hypocretin secretion, neurotransmission
+name: orexin secretion, neurotransmission

GO:0061584
-name: hypocretin secretion
+name: orexin secretion


Thanks, Pascale
