### ISSUE TITLE
NTR interleukin-19-mediated signaling 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23500]
Requested by @pmasson55 

We have 
interleukin-19 <http://purl.obolibrary.org/obo/PR_000001472>
'interleukin-19 binding' <http://purl.obolibrary.org/obo/GO_0042013>
'interleukin-19 production' <http://purl.obolibrary.org/obo/GO_0032622>
'interleukin-19 receptor activity' <http://purl.obolibrary.org/obo/GO_0042014>
'interleukin-19 receptor binding' <http://purl.obolibrary.org/obo/GO_0045516>
'regulation of interleukin-19 production' <http://purl.obolibrary.org/obo/GO_0032662>
'negative regulation of interleukin-19 production' <http://purl.obolibrary.org/obo/GO_0032702>
'positive regulation of interleukin-19 production' <http://purl.obolibrary.org/obo/GO_0032742>

so there is no reason not to have the signaling BP, right @addiehl ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140854
+name: interleukin-19-mediated signaling pathway
+namespace: biological_process
+def: "The series of molecular signals initiated by interleukin-19 binding to its receptor on the surface of a target cell, and ending with the regulation of a downstream cellular process, e.g. transcription." [PMID:34052656]
+synonym: "IL19-mediated signalling pathway" EXACT [GOC:bf]
+is_a: GO:0019221 ! cytokine-mediated signaling pathway
+relationship: part_of GO:0071345 ! cellular response to cytokine stimulus
+created_by: pg
+creation_date: 2022-06-16T08:33:15Z
+

**Comment by addiehl** [comment]
Works for me.
