### ISSUE TITLE
NTR: [serotonin-gated anion-selective channel activity]

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#23509]
NTR: [serotonin-gated anion-selective channel activity]

Please provide as much information as you can: 

* **Suggested term label:**
serotonin-gated anion-selective channel activity

* **Definition (free text)**
Enables the transmembrane transfer of an inorganic anion by a channel that opens when the biogenic amine serotonin has been bound by the channel complex or one of its constituent parts.
Serotonin (5-hydroxytryptamine) is a neurotransmitter and hormone found in vertebrates and invertebrates.

* **Reference, in format PMID:#######**
PMID:11100728

* **Gene product name and ID to be annotated to this term**
Q9GQ00	mod-1	Serotonin-gated chloride channel mod-1

* **Parent term(s)**
GO:0099589	serotonin receptor activity
GO:0099095	ligand-gated anion channel activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
Not sure but would also like to request:

**NEW CHILD TERM REQUEST (child to "serotonin-gated anion-selective channel activity", above).

serotonin-gated chloride ion channel activity

* **Definition of new child term (free text)**
Enables the transmembrane transfer of a chloride ion by a channel that opens when the biogenic amine serotonin has been bound by the channel complex or one of its constituent parts.

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.  
https://en.wikipedia.org/wiki/Ligand-gated_ion_channel
https://tcdb.org/search/result.php?tc=1.A.9

* **Any other information**
This new term(s) would avoid having to co-annotate to 'serotonin receptor activity' and 'ligand-gated anion channel activity'.

**Comment by Pauldenny** [comment]
@vanaukenk

**Comment by Pauldenny** [comment]
Sorry - forgotten how to tag people here!

**Comment by raymond91125** [comment]
@Pauldenny Is it useful to create serotonin-gated anion-selective channel activity in addition to serotonin-gated chloride ion channel activity? In other words, are there other serotonin-gated anion (but chloride) channels that we know of?
In comparison, GO:0022851 GABA-gated chloride ion channel activity does not have a grouping parent GABA-gated anion-selective channel activity.
Thanks.

**Comment by raymond91125** [comment]
Please reopen if there are more comments. Thanks.

**Comment by pgaudet** [comment]
I was also wondering if we really needed the anion grouping term?

Le mar. 12 juil. 2022 à 7:40 PM, Raymond Lee ***@***.***> a
écrit :

**Comment by Pauldenny** [comment]
Having looked in PubMed (I'm not an expert in this field), perhaps the grouping term 
serotonin-gated anion-selective channel activity
is not necessary - I couldn't find any examples, other than the already known chloride-selective worm channel

**Comment by pgaudet** [comment]
Thanks for checking on this @Pauldenny
