### ISSUE TITLE
incorrect parent GO:0008137

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23508]
@pgaudet 
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008137

GO:0008137   NADH dehydrogenase (ubiquinone) activity
has ancestry to transmembrane transport?

**Comment by pgaudet** [comment]
See discussion here: #21275 

I dont find this really intuitive...

**Comment by ValWood** [comment]
No this one always gets me.
