### ISSUE TITLE
NTR: [interleukin-20-mediated signaling pathway]

### ISSUE THREAD

**Issue by pmasson55** [geneontology/go-ontology#23534]
Please provide as much information as you can: 

* **Suggested term label:**

interleukin-20-mediated signaling pathway

* **Definition (free text)**
The series of molecular signals initiated by interleukin-20 binding to its receptor on the surface of a target cell, and ending with the regulation of a downstream cellular process

* **Reference, in format PMID:#######**

PMID: 28424238

* **Gene product name and ID to be annotated to this term**

IL20_HUMAN (Q9NYY1 )
I20RA_HUMAN (Q9UHF4 )

* **Parent term(s)**

GO:0019221 cytokine-mediated signaling pathway

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

GO:0042016 interleukin-20 receptor activity 
GO ??? negative regulation of interleukin-20-mediated signaling pathway
GO ??? positive regulation of interleukin-20-mediated signaling pathway

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140866
+name: interleukin-20-mediated signaling pathway
+namespace: biological_process
+def: "The series of molecular signals initiated by interleukin-20 binding to its receptor on the surface of a target cell, and ending with the regulation of a downstream cellular process, e.g. transcription." [PMID:34755534]
+synonym: "IL-20-mediated signaling pathway" EXACT []
+synonym: "interleukin-20-mediated signalling pathway" EXACT []
+is_a: GO:0019221 ! cytokine-mediated signaling pathway
+relationship: part_of GO:0071345 ! cellular response to cytokine stimulus
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23535 xsd:anyURI
+created_by: pg
+creation_date: 2022-06-22T11:17:42Z
