### ISSUE TITLE
Two instances of 1 RHEA mapping to two terms found in ontology; Second instance RHEA:30059

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#23541]
See ticket #23540 for context

Details for RHEA:30059 mapping to both GO_1990663 and GO_0004158
GO:1990663 dihydroorotate dehydrogenase (fumarate) activity
Catalysis of the reaction: (S)-dihydroorotate + fumarate = orotate + succinate.
EC:1.3.98.1
RHEA:30059 ( S)-dihydroorotate + fumarate = orotate + succinate
Has 1 IEA  annotation based on the EC

The 
GO:0004158 dihydroorotate oxidase activity
Catalysis of the reaction: (S)-dihydroorotate + O(2) = H(2)O(2) + orotate.
Since This GO reaction does not involve fumarate, I removed both EC and RHEA
I used GOC:curators as def ref so I could get my pull request through (see other ticket). 
This term has one manual annotation (ISS) made by JCVI based on PMID:15115801 orthology to UniProtKB:P54322 and an RCA based on PMID:18405346
The other 13 annotations are electronic (IEA, based on interpro domains) 
Because this reaction did NOT specify the use of fumarate as substrate and succinate as product, I removed the RHEA mapping, and replaced with GOC:curators as a def ref. 

GO:1990663 dihydroorotate dehydrogenase (fumarate) activity 
Def Catalysis of the reaction: (S)-dihydroorotate + fumarate = orotate + succinate.
EC:1.3.98.1  (S)-dihydroorotate + fumarate <=> orotate + succinate
RHEA:30059 S)-dihydroorotate + fumarate = orotate + succinate
This term has 1 IEA annotation based on the EC to a yeast gene URA1.
This term seems to properly be described by the RHEA (def ref and xref) and ec.

**Comment by hdrabkin** [comment]
In comment of obsolete GO:0052888
RHEA:30059 and EC:1.3.98 removed so as not to conflict with remapping
However, the mention of the RHEA triggers shows up mapping 2 GO terms to one RHEA. 
(EC has determined that this reaction in fact does not exist and have withdrawn EC:1.3.3.1. Note: If fumarate is not shown to be involved, you may want to consider GO:0004152, dihydroorotate dehydrogenase activity (parent term); if the reaction involves fumarate, then use GO:0052888 dihydroorotate oxidase (fumarate) activity. Details at http://sourceforge.net/p/geneontology/ontology-requests/10770/, RHEA:30059 and EC:1.3.98 removed so as not to conflict with remapping)

Forgot to get rid of RHEA in the obsoleted term. done.

**Comment by pgaudet** [comment]
This
