### ISSUE TITLE
Heterochromatin assembly vs. formation 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23553]
During the transcription group discussion, the issue was raised that 'heterochromatin formation' is a more common term in the literature than 'heterochromatin assembly'. Moreover the LD caused issues, because heterochromatin assembly is not a type of chromatin assembly, although heterochromatin is a type of chromatin. 

So, I removed the logical definitons, and changed  'GO:0031507 heterochromatin assembly' to 'heterochromatin formation', and 
changed definition from
-def: "An epigenetic gene silencing mechanism that involves the assembly of chromatin into heterochromatin, resulting in a chromatin conformation refractory to transcription. This process starts with heterochromatin nucleation, its spreading, and ends with heterochromatin boundary formation." [GOC:mah, PMID:25192661, PMID:33827924]
to: "An epigenetic gene silencing mechanism in which chromatin is compacted into heterochromatin, resulting in a chromatin conformation refractory to transcription. This process starts with heterochromatin nucleation, its spreading, and ends with heterochromatin boundary formation." [PMID:25192661, PMID:33827924]

@colinlog 
@ValWood @hattrill @RLovering

**Comment by pgaudet** [comment]
The question is, should the children also be changed: 
![image](https://user-images.githubusercontent.com/4782928/175529912-32030a1b-ebf3-417b-becb-39105f2c9415.png)

* 'constitutive heterochromatin assembly' -> 'constitutive heterochromatin formation'
* 'facultative heterochromatin assembly' -> 'facultative heterochromatin formation'
* 'heterochromatin assembly by small RNA'  -> 'heterochromatin formation by small RNA' 
and likewise for 
* 'subtelomeric heterochromatin assembly'
* 'pericentric heterochromatin assembly'
* 'inactivation of X chromosome by heterochromatin assembly'
* 'DNA methylation-dependent heterochromatin assembly'
* 'rDNA heterochromatin assembly'
* 'siRNA-independent facultative heterochromatin assembly'


Thanks, Pascale

**Comment by hattrill** [comment]
I think yes -  that would be consistent with yesterday's discussion.

**Comment by ValWood** [comment]
me too.

**Comment by pgaudet** [comment]
Changed definitions: 

GO:0006346 DNA methylation-dependent heterochromatin formation
-old def: "Repression of transcription by methylation of DNA, leading to the formation of heterochromatin." [GOC:mah]
+new def: "Formation of constitutive heterochromatin by a pathway that includes methylation of genomic DNA such as CpG islands." [GOC:mah]

Change parent: from  GO:0140718 ! facultative heterochromatin formation to GO:0140719 ! constitutive heterochromatin formation and remove has_part GO:0009008 ! DNA-methyltransferase activity

----

Change definition GO:0140718 facultative heterochromatin formation
-old def: "The compaction of chromatin into a conformation that is refactory to transcription but that be converted to euchromatin and allow transcription in specific contexts. These can be temporal (e.g., developmental states or specific cell-cycle stages), spatial (e.g., nuclear localization changes from the center to the periphery or vice versa due to exogenous factors/signals), or parental/heritable (e.g., monoallelic gene expression)." [PMID:17936700]
+new def: "The compaction of chromatin into a conformation that is refactory to transcription but that can be converted to euchromatin and allow transcription in specific contexts. These can be temporal (e.g., developmental states or specific cell-cycle stages), spatial (e.g., nuclear localization changes from the center to the periphery or vice versa due to exogenous factors/signals), or parental/heritable (e.g., monoallelic gene expression). In metazoa, this involves the methylation of histone H3K27." [PMID:17936700]


 ----

Change definition GO:0140719 constitutive heterochromatin formation
-old def: "The compaction of chromatin into a conformation that is refractory to transcription." [PMID:17936700]
-comment: Note that constitutive heterochromatin indicates that it usually cannot be reprogrammed to a transcriptionally-competent state, as opposed to facultative heterochromatin, which can be reprogrammed.
+new def: "The compaction of chromatin into heterochromatin, a conformation that is refractory to transcription. Constitutive heterochromatin cannot be converted back to euchromatin, the transcriptionally-active conformation. In metazoa, this involves the methylation of histone H3K9." [PMID:17936700]

**Comment by pgaudet** [comment]
For consistency: we had changed the parent of 'GO:0006346 DNA methylation-dependent heterochromatin formation' from 'GO:0140718 ! facultative heterochromatin formation' to 'GO:0140719 ! constitutive heterochromatin'; we have now renamed it DNA methylation-dependent **constitutive** heterochromatin formation, even though this was in the parent term, but it was confusing not to have it in the term label.

**Comment by pgaudet** [comment]
Also, added comment to [facultative heterochromatin formation](http://purl.obolibrary.org/obo/GO_0140718): 
> Note also that facultative heterochromatin formation does not usually involve DNA methylation, while constitutive heterochromatin formation does.

and to GO:0140719 constitutive heterochromatin formation: 
> Note also that constitutive usually involves DNA methylation, while facultative heterochromatin formation does not.

**Comment by ValWood** [comment]
"Note also that constitutive usually involves DNA methylation, while facultative heterochromatin formation does not."

this isn't true for yeast which don't have DNA methylation so I'm not sure that this comment is super helpful for al curators, maybe you could qualify (I know it says usually, not always, but in yeast  it is never)

**Comment by pgaudet** [comment]
Updated definition of parent to 

end with "In metazoa, this involves the methylation of histone H3K27, and in certain case methylation of H3K9. On the other hand, in unicellular eukaryotes, only methylation of H3K9 is involved and H3K27 is not methylated." 

, since children terms mentioned H3K9 only and that appeared inconsistent,

**Comment by ValWood** [comment]
Isn't H3K9 trimethylation (H3K9me3) always the defining histone modification for heterochromatin formation?

Added by histone methyltransferases such as SUV39 and recognised by HP1 (Heterochromatin Protein 1)?

I thought this was universal?

cc @PCarme

**Comment by pgaudet** [comment]
As far as I understand, this is different in yeast versus animals. 

@colinlog

**Comment by PCarme** [comment]
> Isn't H3K9 trimethylation (H3K9me3) always the defining histone modification for heterochromatin formation?
> 
> Added by histone methyltransferases such as SUV39 and recognised by HP1 (Heterochromatin Protein 1)?

From my understanding, H3K9 methylation is a universal marker of constitutive heterochromatin, and H3K27 trimethylation by the Polycomb complex is a marker of facultative heterochromatin in metazoa (it is absent in yeast)

**Comment by pgaudet** [comment]
Are you saying that for 
[constitutive heterochromatin formation](http://purl.obolibrary.org/obo/GO_0140719): we should change the definition _"The compaction of chromatin into heterochromatin, a conformation that is refractory to transcription. Constitutive heterochromatin cannot be converted back to euchromatin, the transcriptionally-active conformation. In metazoa, this involves the methylation of histone H3K9."_ to remove "In metazoa,"? 

[facultative heterochromatin formation](http://purl.obolibrary.org/obo/GO_0140718) seems OK: _The compaction of chromatin into a conformation that is refractory to transcription but that can be converted to euchromatin and allow transcription in specific contexts. These can be temporal (e.g., developmental states or specific cell-cycle stages), spatial (e.g., nuclear localization changes from the center to the periphery or vice versa due to exogenous factors/signals), or parental/heritable (e.g., monoallelic gene expression). In metazoa, this involves the methylation of histone H3K27, and in certain cases methylation of H3K9. On the other hand, in unicellular eukaryotes, only methylation of H3K9 is involved and H3K27 is not methylated._

Or please let me know what changes you are proposing.

**Comment by PCarme** [comment]
> [constitutive heterochromatin formation](http://purl.obolibrary.org/obo/GO_0140719): we should change the definition _"The compaction of chromatin into heterochromatin, a conformation that is refractory to transcription. Constitutive heterochromatin cannot be converted back to euchromatin, the transcriptionally-active conformation. In metazoa, this involves the methylation of histone H3K9."_ to remove "In metazoa,"?

Yes, I would remove "in metazoa"


> [facultative heterochromatin formation](http://purl.obolibrary.org/obo/GO_0140718) seems OK: _The compaction of chromatin into a conformation that is refractory to transcription but that can be converted to euchromatin and allow transcription in specific contexts. These can be temporal (e.g., developmental states or specific cell-cycle stages), spatial (e.g., nuclear localization changes from the center to the periphery or vice versa due to exogenous factors/signals), or parental/heritable (e.g., monoallelic gene expression). In metazoa, this involves the methylation of histone H3K27, and in certain cases methylation of H3K9. On the other hand, in unicellular eukaryotes, only methylation of H3K9 is involved and H3K27 is not methylated._

This one seems correct

**Comment by pgaudet** [comment]
Thanks !

**Comment by colinlog** [comment]
Hi Val, no H3K9me2/3 is not a universal mark for heterochromatin. There is
also H3K27me3 heterochromatin that is devoid of H3K9me3 (Fly, other
metazoa). To the best of my knowledge, H3K27me3 is always
'facultative heterochromatin'. It is often found in the 'bivalent' state
where promoter -1 and +1 nucleosomes that bear H4K4me3 are surrounded by
nucleosomes modified by H3K27me3 and bound to its readers .
In Pombe H3K9me2 is involved in both constitutive and facultative
heterochromatin.
Furthermore, in humans I know of many loci that have both H3K27me3 and
H3K9me3.
Altogether, this makes it untenable to state that all heterochromatin
involves H3K9 methylation or to make a (simple) one-on-one link between
constitutive heterochromatin and H3K9me3, and facultative heterochromatin
and H3K27me3.

**Comment by ValWood** [comment]
> Altogether, this makes it untenable to state that all heterochromatin
involves H3K9 methylation

OK noted!
