### ISSUE TITLE
NTR NAD+-histone-glutamate ADP-ribosyltransferase activity (H2B-E18 specific)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23551]
PMID:28252050

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140867
+name: NAD+-histone-glutamate ADP-ribosyltransferase activity (H2B-E18 specific)
+namespace: molecular_function
+def: "Catalysis of the transfer of ADP-ribose groups to the glutamate-18 residue of histone H2B (or an equivalent residue)." [PMID:27530147]
+is_a: GO:0140807 ! NAD+-protein-glutamate ADP-ribosyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23551 xsd:anyURI
+created_by: pg
+creation_date: 2022-06-24T06:06:36Z


@pfey03  for your review of ADP-ribosylation 

https://docs.google.com/spreadsheets/d/1YMPZQ1y8-xGu-JFpjxP2-LEm9uWdEbsmJB1BJBmBasQ/edit#gid=0

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi Pascale,

I already requested a GO term for this paper (GO:0140844 NAD+-histone-glutamate ADP-ribosyltransferase activity (H2B-E2 specific))

I cannot find evidences for the H2B Glu-18 ADP-ribosylation in the paper. Is there an error?

Thanks

Sylvain

**Comment by pgaudet** [comment]
I think I've added the wrong paper - I meant to use the dicty paper 
28252050

Thanks for pointing that out. 

Thanks, Pascale
