### ISSUE TITLE
NTR: positive/negative regulation of kainate selective glutamate receptor activity

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#23558]
Please provide as much information as you can: 

* **Suggested term label:**

1.  positive regulation of kainate selective glutamate receptor activity
2.  negative regulation of kainate selective glutamate receptor activity

* **Definition (free text)**

1.  Any process that activates or increases the frequency, rate or extent of kainate selective glutamate receptor activity.
2.  Any process that decreases the rate, frequency, or extent of kainate selective glutamate receptor activity.

* **Reference, in format PMID:#######**

1.  PMID:12597860
2.  PMID:12597860

* **Gene product name and ID to be annotated to this term**

1.  RGD:69437, rat Pick1
3.  RGD:621667, rat Grip1

* **Parent term(s)**

1.  regulation of kainate selective glutamate receptor activity (GO:2000312)
2.  regulation of kainate selective glutamate receptor activity (GO:2000312)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Hi @slaulederkind 
We dont create 'regulation of MF terms' anymore; instead we'd like to capture this as a MF: 
'signaling receptor regulator activity'
'signaling receptor activator activity'
'signaling receptor inhibitor activity'

You can use 'has input' with the specific target. 

And for BP, would it be OK with you if we changed '[regulation of kainate selective glutamate receptor activity](http://amigo.geneontology.org/amigo/term/GO:2000312) to 'regulation of kainate selective glutamate receptor signaling pathway' ? (GO:0098991) ? 


Thanks, Pascale

**Comment by slaulederkind** [comment]
Okay, we'll take 'regulation of kainate selective glutamate receptor signaling pathway'.  Thank you, Pascale.

**Comment by slaulederkind** [comment]
Will "positive..." and "negative regulation of kainate selective glutamate receptor signaling pathway" be added?
