### ISSUE TITLE
migrate CHEBI terms to pH 7.3 subset

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#23568]
I'm trying to update the pH 7.3 mapping list in #23567, but the update reveals some terms used in GO that aren't currently in the pH 7.3 list, and don't have mappings there:

- [x] [phytochromobilin](http://purl.obolibrary.org/obo/CHEBI_26116) -> changed in the ontology; the correct ph7.3 term was alread in the imports file -> added CHEBI_169942 ## kaempferol 3-O-β-D-glucoside(1−)
- [ ] [kaempferol 3-O-beta-D-glucoside](http://purl.obolibrary.org/obo/CHEBI_30200)
- [x] [kainic acid](http://purl.obolibrary.org/obo/CHEBI_31746) -> added CHEBI_156548 ## kainate(1−)
- [x] [noradrenaline](http://purl.obolibrary.org/obo/CHEBI_33569) -> changed to CHEBI_72587 ## (R)-noradrenaline (was already in chebi imports)
- [x] [bacitracin A](http://purl.obolibrary.org/obo/CHEBI_35862)  ->  Added CHEBI_184381 ## bacitracin A zwitterion to chebi imports
- [x] [suramin](http://purl.obolibrary.org/obo/CHEBI_45906) -> added CHEBI_180911 ## suramin(6−)

**Comment by balhoff** [comment]
I think this was the case with the previous version of the file, so I'm not sure why these weren't flagged before.

**Comment by pgaudet** [comment]
Hi @balhoff 

CHEBI:26116 phytochromobilin and CHEBI:33569 noradrenaline were *not* in the CHEBI imports; can hey be removed from the other file where this data is coming from, to avoid we use these by mistake in the future? 

Thanks, Pascale

**Comment by pgaudet** [comment]
For [kaempferol 3-O-beta-D-glucoside](http://purl.obolibrary.org/obo/CHEBI_30200) I dont know how to find the corresponding pH 7.3 - @kaxelsen can you help ? 

Thanks, Pascale

**Comment by kaxelsen** [comment]
Go to www.rhea-db.org and search for the CHEBI ID of the compound you have (here CHEBI:30200) or for the compound name (kaempferol 3-O-beta-D-glucoside) 
https://www.rhea-db.org/rhea?query=kaempferol+3-O-beta-D-glucoside.
Choose one of the reactions and scroll down to "reaction participants". Here you will see the compound we use is CHEBI:169942

**Comment by deustp01** [comment]
> Go to [www.rhea-db.org](http://www.rhea-db.org) and search for the CHEBI ID of the compound you have (here CHEBI:30200) or for the compound name (kaempferol 3-O-beta-D-glucoside)
> https://www.rhea-db.org/rhea?query=kaempferol+3-O-beta-D-glucoside.
> Choose one of the reactions and scroll down to "reaction participants". Here you will see the compound we use is CHEBI:169942

Possible scaling and mapping issue (and possibly also a digression here) - my anecdotal sense, from working to align hundreds of Reactome reactions with their pH 7.3 RHEA counterparts, is that the correctly charged ChEBI instance often (maybe 10% of the time) lacks any comment to indicate that it is the predominant microspecies at pH 7.3. I can indeed check the various ChEBI instances to identify the one that is associated with RHEA reactions but that is slow. It would make our checking and new-curation work easier and more reliable if this information were reliably present in ChEBI entries.

**Comment by balhoff** [comment]
@pgaudet we've still got a GO term [phytochromobilin metabolic process](http://purl.obolibrary.org/obo/GO_0051202) referencing phytochromobilin.
