### ISSUE TITLE
New term request: protein O-linked-N-acetylglucosaminylation

### ISSUE THREAD

**Issue by abish200** [geneontology/go-ontology#23575]
**Suggested term label:**
protein O-linked-N-acetylglucosaminylation

**Definition (free text)**
The glycosylation of a protein by the addition of N-acetylglucosamine to serine or threonine residue.

**Reference, in format PMID:#######**
PMID: 34176417

**Gene product name and ID to be annotated to this term**
HGNC:8127 (OGT - in Homo sapiens)

**Parent term(s)**
protein O-linked glycosylation (GO:0006493)

**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
protein O-GlcNAcylation via threonine (GO:0097370)

**Synonyms** (please specify, EXACT, BROAD, NARROW or RELATED)
EXACT: O-GlcNAcylation, O-linked beta-N-acetylglucosaminylation

**Cross-references**

**For enzymes, please provide RHEA and/or EC numbers.**

Can also provide MetaCyc, KEGG, Wikipedia, and other links.

**Any other information**

**Comment by pgaudet** [comment]
Hi @abish200 
This corresponds to the MF protein GO:0097363 O-acetylglucosaminyltransferase activity, since it is a single reaction. 

Thank you, 

Pascale
