### ISSUE TITLE
Change GO:0000931 term name to gamma-tubulin ring complex	

### ISSUE THREAD

**Issue by manulera** [geneontology/go-ontology#23586]
* **GO:0000931**

* **Change term name to Gamma-TuRC**

* **Additional information**

There are currently no occurrences of the current term name "gamma-tubulin large complex" in PubMed.

![Screenshot 2022-06-30 at 14 40 23](https://user-images.githubusercontent.com/22526102/176679285-d2816717-d2e5-43fe-ba26-3e68ecef2079.png)

vs. 183 results for gamma-tubulin ring complex

![Screenshot 2022-06-30 at 14 43 50](https://user-images.githubusercontent.com/22526102/176679931-3ddfa30d-d27b-40a7-aa7e-69d86b97076e.png)

Right now, "gamma-tubulin ring complex" is listed as a narrow synonym. Given that the current term name is not used as such in the literature, and that all other synonyms seem to come from yeast, where we know this is used for gamma-TuRC, we think it would be safe to change the term name.

cc: @ValWood

**Comment by ValWood** [comment]
add exact sunonym gamma-TuRC
