### ISSUE TITLE
NTR: [halogenase activity]

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#23587]
I would like to request the creation of MF terms to describe the activity of halogenases, enzymes that generate carbon–halogen bonds during the biosynthesis of many  natural product. As an exeample, the halogenase otaD from Aspergillus niger chlorinates position C-5 of ochratoxin B to produce ochretoxin A, the final compound of the ochratoxin biosynthesis pathway.

**Term:** 

- [ ] halogenase activity, MF

**Definition:**
Catalysis of the reaction that generates carbon-halogen bonds during the biosynthesis of many natural products

**References**
PMID:34368824
PMID: 28466644

**Parent terms:** 
~GO:0003824  catalytic activity~

GO:0016705 oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen

**Children terms** 

Create 

- [ ] **flavin-dependent halogenase activity**

Definition: Catalysis of the reaction that generates FAD-dependent carbon-halogen bonds during the biosynthesis of many natural products. 

* parent: GO:0016712 oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen

See:
- Flavin-dependent halogenase malA · UniProtKB: - Malbranchea aurantiaca · EC:1.14.-.-   Rhea:62296
- Flavin-dependent halogenase gsfI · UniProtKB:D7PI14  - Penicillium aethiopicum · EC:1.14.14.-  No Rhea yet
- Flavin-dependent halogenase armH4 · UniProtKB:A0A0U3AL34  - Armillaria mellea · EC:1.14.19.-  Rhea:67160
- Flavin-dependent halogenase armH5 · UniProtKB:A0A0U3C228 -  Armillaria mellea · EC:1.14.19.- Rhea:67160
- Flavin-dependent halogenase otaD · UniProtKB:A0A1R3RGJ2   - Aspergillus carbonarius - EC:1.14.14.-  No Rhea yet
- Flavin-dependent halogenase rdc2 · UniProtKB:B3FWT7 - Metacordyceps chlamydosporia · EC:1.14.14.-  No Rhea yet
- Flavin-dependent halogenase radH · UniProtKB:C5H881 -  Floropilus chiversii · EC:1.14.14.-   No Rhea yet
- Flavin-dependent halogenase aclH · UniProtKB:Q2UPC7  - Aspergillus oryzae -  EC:1.14.14.-   No Rhea yet
- Sulochrin halogenase · UniProtKB:Q0CCX4  -  Aspergillus terreus · EC:1.14.19.-  Rhea:64312
- Flavin-dependent halogenase ascD · UniProtKB:A0A455R7M0 - Acremonium egyptiacum · EC:1.14.99.-  Rhea:63084
- Flavin-dependent halogenase ptaM · UniProtKB:A0A067XMV4 - Pestalotiopsis fici  · EC:1.14.14.-  No Rhea yet

Create: 

- [x] **haloperoxidase activity**

Definition: Catalysis of the reaction that generates carbon-halogen bonds by using hydrogen peroxide during the biosynthesis of many natural products. 

* parent should be : GO:0004601 peroxidase activity

See:
- Chloroperoxidase CPO · UniProtKB:P04963 - Leptoxyphium fumago · EC:1.11.1.10 · No Rhea

Thanks a lot.
Marc

**Comment by pgaudet** [comment]
@marcfeuermann for  haloperoxidase activity EC:1.11.1.10, we already have GO:0016691 chloride peroxidase activity, defined as "Catalysis of the reaction: 2 R-H + 2 chloride + hydrogen peroxide = 2 R-Cl + 2 H2O."; would this term work for you? 
I can add a synonym for haloperoxidase activity.

**Comment by marcfeuermann** [comment]
GO:0016691 chloride peroxidase activity should be a child term of haloperoxidase activity because chlore is only one halogen, brome and fluor are also often used. So **haloperoxidase activity** should be a parent of **GO:0016691 chloride peroxidase activity** and a child of **halogenase activity**.
I think like this we have a clear hierarchy for these enzymes (Bromo or fluoroperoxidase activities could be added if necessary in the future).

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140905
+name: haloperoxidase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: RH + a halogen + H2O2 = R-halogen + H2O." [PMID:28466644, PMID:34368824]
+is_a: GO:0004601 ! peroxidase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23587 xsd:anyURI
+created_by: pg
+creation_date: 2022-08-26T15:43:50Z

**Comment by pgaudet** [comment]
For halogenase activity,how do you know that this is a GO:0016705 oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen? 

This is not clear to me in the definition you propose "Catalysis of the reaction that generates carbon-halogen bonds during the biosynthesis of many natural products." ?

**Comment by marcfeuermann** [comment]
"Oxygen is required as an essential co-substrate of oxidoreductases like halogenases and enzymatic reactions are usually conducted in aqueous solution" from PMID: 28464370

In fact when ypou look at the reactions:
haloperoxidases use one oxygene from H2O2 and release halogenated product and H2O
and 
flavin-dependant halogenases extract one oxygene from O2, the other leading to H2O from FADH2.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140906
+name: halogenase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: R-CH + a halogen + oxygen donor = R-C-halogen +H2O." [PMID:28466644, PMID:34368824]
+is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23587 xsd:anyURI
+created_by: pg
+creation_date: 2022-08-29T09:36:00Z
+
+[Term]
+id: GO:0140907
+name: flavin-dependent halogenase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: R-CH + a halogen + FADH2 + O2 = R-C-halogen + FAD + H2O." [PMID:28466644, PMID:34368824]
+is_a: GO:0140906 ! halogenase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23587 xsd:anyURI
+created_by: pg
+creation_date: 2022-08-29T09:37:39Z
