### ISSUE TITLE
NTR - metabolism: [paraherquonin biosynthetic process]

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#23591]
I would only create the biosynthesis term since in general there are no degradation pathways of these metabolites (only few exceptions). No regulation terms, it was not characterized yet.

**"paraherquonin biosynthetic process"**

ChEBI Name: paraherquonin
ChEBI ID: CHEBI:156379

**Definition:**
The chemical reactions and pathways resulting in the formation of paraherquonin, a meroterpenoid with a unique, highly congested hexacyclic molecular architecture.

PMID: 27602587

**Gene product names and IDs to be annotated to this term:**

prhL A0A1E1FFN8 Rhea:49628
prhE A0A1E1FFM8 Rhea:49632
prhM A0A1E1FFN5 No Rhea yet
prhF A0A1E1FFL6  No Rhea yet
prhH A0A1E1FFM9 No Rhea yet
prhI  A0A1E1FFP5 Rhea:65176
prhJ A0A1E1FFN7 Rhea:65180
prhK A0A1E1FFN4  Rhea:65168
prhA A0A1E1FFL0  Rhea:65184
prhC A0A1E1FFL1 No Rhea yet 
prhB A0A1E1FFM3  No Rhea yet
prhD A0A1E1FFL4 No Rhea yet 
prhN A0A1E1FFN3 No Rhea yet 
prhG A0A1E1FFK8  MFS transporter

**Parent terms:**
GO:0016114 terpenoid biosynthetic process

**Synonyms:**
paraherquonin synthesis, paraherquonin biosynthesis, paraherquonin formation, paraherquonin anabolism (EXACT)

Child terms: None

**Cross-references**
MetaCyc: None
KEGG: None

**Taxon constraint:** Only in taxon 4751 Fungi

----

* **FOR ONTOLOGY EDITOR**

* **Logical definition**
* *  **substance metabolic process:**
'metabolic process'
 and ('has primary input or output' some [substance]
* * **substance biosynthetic process:**
'biosynthetic process'
 and ('has primary output' some [substance].
* * **substance catabolic process:**
'catabolic process'
 and ('has primary output' some [substance] 

* **Standard synonyms**
* *  **substance metabolic process:**
* * * EXACT: substance metabolism
* * **substance biosynthetic process:** 
* * * EXACT: substance anabolism
* * * EXACT: substance biosynthesis
* * * EXACT: substance formation
* * * EXACT: substance synthesis

* * **substance catabolic process:**    
* * * EXACT: substance breakdown
* * * EXACT: substance catabolism
* * * EXACT: substance degradation

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140874
+name: paraherquonin biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of paraherquonin, a meroterpenoid with a unique, highly congested hexacyclic molecular architecture." [PMID:27602587]
+synonym: "paraherquonin anabolism" EXACT []
+synonym: "paraherquonin biosynthesis" EXACT []
+synonym: "paraherquonin formation" EXACT []
+synonym: "paraherquonin synthesis" EXACT []
+is_a: GO:0016114 ! terpenoid biosynthetic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23591 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-05T10:31:37Z

**Comment by pgaudet** [comment]
Need to add LD
