### ISSUE TITLE
NTR - metabolism: [griseofulvin biosynthetic process]

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#23598]
I would only create the biosynthesis term since in general there are no degradation pathways of these metabolites (only few exceptions). There are 2 transcription factors present in the cluster, but they have not been characterized yet so I would not create regulation terms at the moment.

**"griseofulvin biosynthetic process"**

ChEBI Name: griseofulvin 
ChEBI ID: CHEBI:27779 

**Definition:**
The chemical reactions and pathways resulting in the formation of griseofulvin, an important antifungal drug that has been in use for a long time for treating dermatophyte infections.

PMID:  20534346,  23978092

**Gene product names and IDs to be annotated to this term:**
gsfA D7PI15 No Rhea
gsfB D7PI16 No Rhea
gsfC D7PI17 No Rhea
gsfD D7PI18 No Rhea
gsfE D7PI19 No Rhea
gsfF D7PI20 No Rhea
gsfI D7PI14 No Rhea
gsfJ D7PI13 Efflux pump
gsfK D7PI11 No Rhea

**Parent terms:**
GO:0043386 mycotoxin biosynthetic process
GO:0030639 polyketide biosynthetic process

**Synonyms:**
griseofulvin synthesis, griseofulvin biosynthesis, griseofulvin formation, griseofulvin anabolism (EXACT)

**Child terms:**
None

**Cross-references**
MetaCyc: https://metacyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-7653
KEGG: https://www.genome.jp/dbget-bin/www_bfind_sub?mode=bfind&max_hit=1000&locale=en&serv=kegg&dbkey=kegg&keywords=griseofulvin&page=1

**Taxon constraint**: Only in taxon 4751 Fungi

----

* **FOR ONTOLOGY EDITOR**

* **Logical definition**
* *  **substance metabolic process:**
'metabolic process'
 and ('has primary input or output' some [substance]
* * **substance biosynthetic process:**
'biosynthetic process'
 and ('has primary output' some [substance].
* * **substance catabolic process:**
'catabolic process'
 and ('has primary output' some [substance] 

* **Standard synonyms**
* *  **substance metabolic process:**
* * * EXACT: substance metabolism
* * **substance biosynthetic process:** 
* * * EXACT: substance anabolism
* * * EXACT: substance biosynthesis
* * * EXACT: substance formation
* * * EXACT: substance synthesis

* * **substance catabolic process:**    
* * * EXACT: substance breakdown
* * * EXACT: substance catabolism
* * * EXACT: substance degradation

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140878
+name: griseofulvin biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of griseofulvin, an important antifungal drug that has been in use for a long time for treating dermatophyte infections." [PMID:20534346, PMID:23978092]
+synonym: "griseofulvin anabolism" EXACT []
+synonym: "griseofulvin biosynthesis" EXACT []
+synonym: "griseofulvin formation" EXACT []
+synonym: "griseofulvin synthesis" EXACT []
+xref: MetaCyc:PWY-7653
+is_a: GO:0043386 ! mycotoxin biosynthetic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23598 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-05T07:12:13Z
+

**Comment by pgaudet** [comment]
Need to add LD
