### ISSUE TITLE
Term obsoletion GO:0043000 Golgi to plasma membrane CFTR protein transport & children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23593]
* **Term to be merged: Provide GO ID and term label**

GO:0043002   negative regulation of Golgi to plasma membrane CFTR protein transport
(and it's descendant) are gene-specific terms and should merge into the parent term
(1 EXP annotation)

**Comment by pgaudet** [comment]
This whole branch should be obsoleted: 

* GO:0043000 Golgi to plasma membrane CFTR protein transport
*  [GO:0043002 negative regulation of Golgi to plasma membrane CFTR protein transport](http://amigo.geneontology.org/amigo/term/GO:0043002#display-lineage-tab)
*  [GO:0043003 positive regulation of Golgi to plasma membrane CFTR protein transport](http://amigo.geneontology.org/amigo/term/GO:0043003#display-lineage-tab)
*  [GO:0042999 regulation of Golgi to plasma membrane CFTR protein transport](http://amigo.geneontology.org/amigo/term/GO:0042999#display-lineage-tab)
* [GO:0043004 cytoplasmic sequestering of CFTR protein](http://amigo.geneontology.org/amigo/term/GO:0043004#display-lineage-tab)

* 2 EXP UniProt

**Comment by raymond91125** [comment]
Annotation review https://github.com/geneontology/go-annotation/issues/4265

**Comment by raymond91125** [comment]
There is an InterPro2GO mapping
InterPro:IPR038879 Golgi-associated PDZ and coiled-coil motif-containing protein > GO:cytoplasmic sequestering of CFTR protein ; GO:0043004

How do I deal with that? @pgaudet Thanks.

**Comment by ValWood** [comment]
Hi @raymond91125  you report it here
https://github.com/geneontology/go-annotation/issues

**Comment by raymond91125** [comment]
OK. Done, Thanks. Anyone particular should be assigned?

**Comment by ValWood** [comment]
I assigned to @blazaropinto  for InterPro and @Antonialock for UniProt.
If you  select to create tickets using templayes for specific resources the  assignee is done automatically.
However, I notice there is no template for UniProt, maybe one could be added @pgaudet ?

**Comment by raymond91125** [comment]
Thanks everyone.
