### ISSUE TITLE
NTR - metabolism: [viridicatumtoxin biosynthetic process]

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#23599]
I would only create the biosynthesis term since in general there are no degradation pathways of these metabolites (only few exceptions). There are 2 transcription factors present in the cluster, but they have not been characterized yet so I would not create regulation terms at the moment.

**"viridicatumtoxin biosynthetic process"**

ChEBI Name: viridicatumtoxin 
ChEBI ID: CHEBI:85616

**Definition:**
The chemical reactions and pathways resulting in the formation of viridicatumtoxin, a tetracycline-like fungal meroterpenoid with a unique, fused spirobicyclic ring system .

PMID:  20534346,  24161266

**Gene product names and IDs to be annotated to this term:**
vrtA D7PHZ2 No Rhea
vrtB D7PHZ3 No Rhea
vrtC D7PHZ4 No Rhea
vrtD D7PHZ5 Rhea:22408
vrtE D7PHZ6 No Rhea
vrtF D7PHZ7 No Rhea
vrtG D7PHZ8 No Rhea
vrtH D7PHZ9  No Rhea
vrtI D7PHZ1 No Rhea
vrtJ D7PHZ0 No Rhea
vrtK D7PHY9 No Rhea
vrtL D7PHY8  Efflux pump

**Parent terms:**
GO:0043386 mycotoxin biosynthetic process
GO:0016114 terpenoid biosynthetic process

**Synonyms:**
viridicatumtoxin synthesis, viridicatumtoxin biosynthesis, viridicatumtoxin formation, viridicatumtoxin anabolism (EXACT)

**Child terms:**
None

**Cross-references**
MetaCyc: https://metacyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-7659
KEGG: None

**Taxon constraint:** Only in taxon 4751 Fungi

----

* **FOR ONTOLOGY EDITOR**

* **Logical definition**
* *  **substance metabolic process:**
'metabolic process'
 and ('has primary input or output' some [substance]
* * **substance biosynthetic process:**
'biosynthetic process'
 and ('has primary output' some [substance].
* * **substance catabolic process:**
'catabolic process'
 and ('has primary output' some [substance] 

* **Standard synonyms**
* *  **substance metabolic process:**
* * * EXACT: substance metabolism
* * **substance biosynthetic process:** 
* * * EXACT: substance anabolism
* * * EXACT: substance biosynthesis
* * * EXACT: substance formation
* * * EXACT: substance synthesis

* * **substance catabolic process:**    
* * * EXACT: substance breakdown
* * * EXACT: substance catabolism
* * * EXACT: substance degradation

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140872
+name: viridicatumtoxin biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of viridicatumtoxin, a tetracycline-like fungal meroterpenoid with a unique, fused spirobicyclic ring system." [PMID:20534346, PMID:24161266]
+synonym: "viridicatumtoxin anabolism" EXACT []
+synonym: "viridicatumtoxin biosynthesis" EXACT []
+synonym: "viridicatumtoxin formation" EXACT []
+synonym: "viridicatumtoxin synthesis" EXACT []
+xref: MetaCyc:PWY-7659
+is_a: GO:0043386 ! mycotoxin biosynthetic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23599 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-05T07:12:13Z
+
