### ISSUE TITLE
NTR - metabolism: [PR-toxin biosynthetic process]

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#23592]
I would only create the biosynthesis term since in general there are no degradation pathways of these metabolites (only few exceptions). Regulation was not characterized yet.

 ****PR-toxin biosynthetic process****

ChEBI Name: PR-toxin
ChEBI ID: CHEBI:7883

**Definition**
The chemical reactions and pathways resulting in the formation of PR-toxin, a bicyclic sesquiterpene belonging to the eremophilane class and acting as a mycotoxin.

PMID:  24239699,  27921136 

**Gene product name and ID to be annotated to this term**
prx1 W6QB10 
prx2 W6Q4Q9 Rhea:19825
prx3 W6Q5R7 
prx4 W6QP06 
ORF5 W6Q3Z9 
ORF6 W6QB15 
ORF7 W6Q4S2 
ORF8 W6QP10 
ORF9 W6Q403 
ORF11 W6Q4S4 

Rhea reactions not created yet for most

**Parent term(s)**
GO:0016106: sesquiterpenoid biosynthetic process
GO:0043386: mycotoxin biosynthetic process

* **Synonym(s):**
PR-toxin synthesis, PR-toxin biosynthesis, PR-toxin formation, PR-toxin anabolism (EXACT)

**Children terms** 
None

**Cross-references**
MetaCyc: https://metacyc.org/compound?orgid=META&id=CPD-13303   - No pathway -
KEGG: www.genome.jp/dbget-bin/www_bfind_sub?mode=bfind&max_hit=1000&locale=en&serv=kegg&dbkey=kegg&keywords=PR-toxin&page=1

**Taxon constraint:** Only in taxon 4751 Fungi

----

* **FOR ONTOLOGY EDITOR**

* **Logical definition**
* *  **substance metabolic process:**
'metabolic process'
 and ('has primary input or output' some [substance]
* * **substance biosynthetic process:**
'biosynthetic process'
 and ('has primary output' some [substance].
* * **substance catabolic process:**
'catabolic process'
 and ('has primary output' some [substance] 

* **Standard synonyms**
* *  **substance metabolic process:**
* * * EXACT: substance metabolism
* * **substance biosynthetic process:** 
* * * EXACT: substance anabolism
* * * EXACT: substance biosynthesis
* * * EXACT: substance formation
* * * EXACT: substance synthesis

* * **substance catabolic process:**    
* * * EXACT: substance breakdown
* * * EXACT: substance catabolism
* * * EXACT: substance degradation

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140875
+name: PR-toxin biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of PR-toxin, a bicyclic sesquiterpene belonging to the eremophilane class and acting as a mycotoxin." [PMID:24239699, PMID:27921136]
+synonym: "PR-toxin anabolism" EXACT []
+synonym: "PR-toxin biosynthesis" EXACT []
+synonym: "PR-toxin formation" EXACT []
+synonym: "PR-toxin synthesis" EXACT []
+is_a: GO:0016106 ! sesquiterpenoid biosynthetic process
+is_a: GO:0043386 ! mycotoxin biosynthetic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23592 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-05T10:37:05Z
+

**Comment by pgaudet** [comment]
Need to add LD
