### ISSUE TITLE
NTR: [zinc ion export from cell]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#23603]
Please provide as much information as you can: 

* **Suggested term label:**
zinc ion export from cell

* **Definition (free text)**
The directed movement of zinc ions from a cell, into the extracellular region.

* **Reference, in format PMID:#######**
PMID:17355957

* **Gene product name and ID to be annotated to this term**
SLC30A5

* **Parent term(s)**
GO:0140352 export from cell

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140882
+name: zinc export across plasma membrane
+namespace: biological_process
+def: "The directed movement of zinc ions from a cell, into the extracellular region." [PMID:17355957]
+synonym: "zinc ion export from cell" EXACT []
+intersection_of: GO:0006810 ! transport
+intersection_of: has_primary_input CHEBI:29105 ! zinc(2+)
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+created_by: pg
+creation_date: 2022-07-08T04:56:15Z

**Comment by pgaudet** [comment]
@lbreuza 

We use 'import/export' across plasma membrane to indicate transmembrane transport; the general term 'import into/export from cell' is used to group transmembrane compounds and endocytosis for specific compounds. Maybe this is not necessary to distinguish? But this is to explain why the term label is different from what you requested. 

Thanks, Pascale
