### ISSUE TITLE
problem with recent merge of 	CENP-A containing chromatin organization and 	CENP-A containing chromatin assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23606]
cpp1 is a *disassembly * chaperone. It evicts  CENP-A from nucleosomes

[Q. Dong et al., Ccp1 homodimer mediates chromatin integrity by antagonizing
CENP-A loading. Mol. Cell 64, 79–91 (2016).](https://pubmed.ncbi.nlm.nih.gov/27666591/)

Which term will I use for this?
@colinlog 
@pgaudet

**Comment by pgaudet** [comment]
Discussion with @colinlog @ValWood @colinlog @hattrill - this term would not be useful to annotate the PMID:34810257: 
Ccp1 removes CENP-A from non-centromeric regions, so this is not 'CENP-A containing chromatin organization'

**Comment by pgaudet** [comment]
Correct term would be 'CENP-A eviction from euchromatin' https://pubmed.ncbi.nlm.nih.gov/27666591/

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140898
+name: CENP-A eviction from euchromatin
+namespace: biological_process
+def: "A chromatin remodeling process in which CENP-A is removed from euchromatin regions to prevent neocentromere formation." [PMID:27666591]
+is_a: GO:0006338 ! chromatin remodeling
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23606 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-28T09:33:29Z

**Comment by pgaudet** [comment]
Isn't this some kind of chaperone MF?

**Comment by ValWood** [comment]
It is a chaperone, but we have terms for chromatin assembly, but no way to describe the removal of nucleosomes at the incorrect location.  Presumably  it will be a  multi step process, there is presumably  some mechanism to identify the  ectopic assembly.
I'd be happy to use a chaperone if there was an appropriate one to capture this QC role.

**Comment by pgaudet** [comment]
Ah ok, right. Is the parent ('chromatin remodeling') OK ? 
I dont think we have the notion of nucleosome assembly QC...

**Comment by ValWood** [comment]
I think so!

**Comment by pgaudet** [comment]
Close for now
