### ISSUE TITLE
NTR: [zinc ion import into cell]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#23602]
Please provide as much information as you can: 

* **Suggested term label:**
zinc ion import into cell

* **Definition (free text)**
The directed movement of zinc ions from outside of a cell into the cytoplasmic compartment. This may occur via transport across the plasma membrane or via endocytosis.

* **Reference, in format PMID:#######**
PMID:12504855

* **Gene product name and ID to be annotated to this term**
SLC39A8, SLC30A5
* **Parent term(s)**
GO:0006829 zinc ion transport

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
I just noticed, we already have 'GO:0071578 zinc ion import across plasma membrane'; can you use that ? 

I added the synonym, zinc ion import into cell.

Thanks, Pascale
