### ISSUE TITLE
NTR - metabolism: [conidiogenone biosynthetic process]

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#23600]
I would only create the biosynthesis term since in general there are no degradation pathways of these metabolites (only few exceptions). No regulation has been characterized.

**"conidiogenone biosynthetic process"**

ChEBI Name: conidiogenone 
ChEBI ID: CHEBI:189095

**Definition:**
The chemical reactions and pathways resulting in the formation of conidiogenone , a diterpene known to induce the conidiation.

PMID:  30343633

**Gene product names and IDs to be annotated to this term:**
PchDS B6HFX8 Rhea:17653
PrDS W6QAE7 Rhea:17653
PchP450 B6HFX9 No Rhea
PrP450 W6Q9B3 No Rhea

**Parent terms:**
GO:0016102 diterpenoid biosynthetic process

**Synonyms:**
conidiogenone synthesis, conidiogenone biosynthesis, conidiogenone formation, conidiogenone anabolism (EXACT)

**Child terms:**
None

**Cross-references**
MetaCyc: None
KEGG: None

Taxon constraint: Only in taxon 4751 Fungi

----

* **FOR ONTOLOGY EDITOR**

* **Logical definition**
* *  **substance metabolic process:**
'metabolic process'
 and ('has primary input or output' some [substance]
* * **substance biosynthetic process:**
'biosynthetic process'
 and ('has primary output' some [substance].
* * **substance catabolic process:**
'catabolic process'
 and ('has primary output' some [substance] 

* **Standard synonyms**
* *  **substance metabolic process:**
* * * EXACT: substance metabolism
* * **substance biosynthetic process:** 
* * * EXACT: substance anabolism
* * * EXACT: substance biosynthesis
* * * EXACT: substance formation
* * * EXACT: substance synthesis

* * **substance catabolic process:**    
* * * EXACT: substance breakdown
* * * EXACT: substance catabolism
* * * EXACT: substance degradation

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140879
+name: conidiogenone biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of conidiogenone , a diterpene known to induce the conidiation." [PMID:30343633]
+synonym: "conidiogenone anabolism" EXACT []
+synonym: "conidiogenone biosynthesis" EXACT []
+synonym: "conidiogenone formation" EXACT []
+synonym: "conidiogenone synthesis" EXACT []
+is_a: GO:0043386 ! mycotoxin biosynthetic process
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23600 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-05T11:01:27Z
+
