### ISSUE TITLE
NTR: [induction by virus of host reticulophagy]

### ISSUE THREAD

**Issue by magrane** [geneontology/go-ontology#23616]
Please provide as much information as you can: 

* **Suggested term label:** induction by virus of host reticulophagy

* **Definition (free text)** Any process in which a virus activates or increases the frequency, rate or extent of reticulophagy in the host.

* **Reference, in format PMID:#######** PMID:35239449

* **Gene product name and ID to be annotated to this term** P0DTC3 (AP3A_SARS2)

* **Parent term(s)** GO:0039520 (induction by virus of host autophagy)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140883
+name: induction by virus of host reticulophagy
+namespace: biological_process
+def: "Any process in which a virus activates or increases the frequency, rate or extent of reticulophagy in the host." [PMID:35239449]
+synonym: "activation of host reticulophagy by virus" EXACT []
+synonym: "positive regulation by virus of host reticulophagy" BROAD []
+is_a: GO:0010508 ! positive regulation of autophagy
+is_a: GO:0039519 ! modulation by virus of host autophagy
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23616 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-08T05:08:02Z

**Comment by pgaudet** [comment]
Merge GO:0075044 positive regulation by symbiont of host autophagy (no annotations)
into child GO:0039520 induction by virus of host autophagy

The multi-organism WG has decided to use induction (and suppression) of host processes to distinguish from normal regulation.

**Comment by pgaudet** [comment]
GO:0140883 induction by virus of host reticulophagy >> change label to symbiont-mediated activation of host reticulophagy'
