### ISSUE TITLE
GO:0039547 suppression by virus of host TRAF activity : merge into GO:0039527 suppression by virus of host TRAF-mediated signal transduction

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23644]
GO:0039547 suppression by virus of host TRAF activity represents a MF. We could merge it into 'GO:0039527 suppression by virus of host TRAF-mediated signal transduction (0 annotations)' 

However the definition of GO:0039547 suppression by virus of host TRAF activity  is more precise than that of GO:0039527: 
* GO:0039547: Any process in which a virus stops, prevents, or reduces the activity of a host TRAF (tumor necrosis factor receptor-associated factor) protein. TRAFs are intracellular signal transducers that lie downstream of receptors including RIG-I, MDA-5 and Toll-like receptors (TLR) and transfer the signal to other intracellular signaling components.
 
* GO:0039527: Any process in which a virus stops, prevents, or reduces the frequency, rate or extent of TRAF-mediated signal transduction in the host.

@pmasson55 should we add the bit about "TRAFs are intracellular signal transducers that lie downstream of receptors including RIG-I, MDA-5 and Toll-like receptors (TLR) and transfer the signal to other intracellular signaling components." in the definition of GO:0039527? @genegodbold was mentioning that other pathways activate TRAF. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Note that this is a KW using that term, KW-1110 Inhibition of host TRAFs by virus > GO:suppression by virus of host TRAF activity ; GO:0039547

**Comment by genegodbold** [comment]
Hey @pgaudet and @pmasson55,
I like the idea of adding more details of TRAFs role in signal transduction.
I also note that bacterial, viral, and eukaryotic parasites all have virulence factors that mess with TRAF--directly binding to it.
Bacterial: TssM from Burkholderia pseudomallei probably deubiquitinates TRAF-3, TRAF-6, and IkappaB, keeping them active in the host cell [PMID20335533]; NleB from Citrobacter rodentium AND Escherichia coli [PMID27387501][PMID28522607]; Translocated intimin receptor from E. coli recruits host SHP-1 to inhibit host TNFR-associated factor 6 (TRAF6) ubiquitination and suppress the host innate immune response [PMID23707390]; SopB from Salmonella binds TRAF6 to prevent mitochondrial recruitment necessary for ROS generation [PMID27473656].
Viral: Membrane protein from SARS-CoV2 prevents the interaction of RIG-I with MAVS, MAVS with TBK1, and TRAF3 with TBK1 [PMID33372174]; LMP1 from Epstein-Barr virus engages TNF receptor-associated factors (TRAFs) and TNFR1-associated death domain protein (TRADD), which are adaptors used by TNFR to activate the transcription of anti-apoptotic genes through NFkappaB and c-Jun N-terminal kinase-dependent signaling pathways [PMID12407409]; MC159 from Molluscum contagiosum poxvirus binds TRAF2 and TRAF3 [PMID22301546]; E10 from equine herpesvirus activates the JNK pathway through TRAF6 [PMID11238466].
Eukaryotic parasites: GRA15 from Toxoplasma gondii activates host NFkappaB through direct interaction with TNF receptor-associated factors (TRAFs). Elimination of the TRAF binding sites in the GRA15 sequence reduces its ability to activate the NFkappaB pathway [PMID31311877]. GRA7 from Toxpolasma gondii induces innate immune responses in macrophages by interacting with TRAF6 via the MyD88-dependent pathway. GRA7 forms a complex with MyD88 which promotes the activation of TRAF6 and the generation of reactive oxygen species which enhances the release of inflammatory mediators [PMID26553469].

**Comment by genegodbold** [comment]
That Lb(pro) from FMD virus that somebody brought up in last week's meeting *also* interferes with TRAF by acting as a deubiquintase

FMDV Lb(pro), a shorter form of L(pro), has deubiquitinating activity, processing Lys48-linked and Lys63-linked polyubiquitin chains. This ability is independent of its ability to cut eIF4gamma. Lb(pro) expressed ectopically blocks the activation of type I interferon (IFN) in cells through deubiquitination of RIG-1, TBK1, **TRAF3**, and **TRAF6**. A mutant of Lb(pro) that is catalytically inactive does not exert this activity [PMID21307201].
