### ISSUE TITLE
GO:0006110 regulation of glycolytic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23643]
GO:0006110 regulation of glycolytic process is_a regulation of protein phosphorylation' (reported by @pfey03 in https://github.com/geneontology/go-annotation/issues/4042#issuecomment-1178330541). 

I think this is caused by the logical definition: 

'carbohydrate catabolic process'
 and ('has part' some 'phosphoglycerate kinase activity')
 and ('has part' some 'phosphoglycerate mutase activity')
 and ('has part' some 'phosphopyruvate hydratase activity')
 and ('has part' some 'glyceraldehyde-3-phosphate dehydrogenase (NAD(P)+) (phosphorylating) activity')
 and ('ends with' some 'pyruvate kinase activity')
 and ('has input' some 'NAD(P)(+)')
 and ('has input' some 'ADP(3-)')
 and ('has output' some 'NAD(P)H')
 and ('has output' some 'ATP(4-)')
 and ('has primary output' some pyruvate)

1. I think the 'has parts' should move to asserted subclasses, as we did for other metabolic processes
2. To be consistent with the guidelines for logical definitions, the LD should be 
'carbohydrate catabolic process'
 and ('has primary output' some pyruvate) (the primary input 'carbohydrate' is covered by the parent class 'carbohydrate catabolic process')

@ukemi does this look right to you? 

Thanks, Pascale

**Comment by deustp01** [comment]
> and ('has part' some 'phosphoglycerate kinase activity')
> and ('has part' some 'phosphoglycerate mutase activity')
> and ('has part' some 'phosphopyruvate hydratase activity')
> and ('has part' some 'glyceraldehyde-3-phosphate dehydrogenase (NAD(P)+) (phosphorylating) activity')

The target of all of these has_part kinases is a small molecule, not a protein, and "protein phosphorylation" means an activity that leads to the phosphorylation of a target protein, not phosphorylation enabled by a protein, so how can these items be causing the error? What am I missing?

**Comment by ukemi** [comment]
I only see it inferred to be a regulation of phosphorylation, which is correct. ADP gets phosphorylated.

**Comment by pfey03** [comment]
I had this one annotation that is from a 2005 paper, and I changed it after reading to take it off my plate.

However, glycolysis has many reactions (parts) and is not a single step process and this needs to be fixed.

**Comment by pgaudet** [comment]
Hi @pfey03 I dont see the relation between 


GO:0006110 | regulation of glycolytic process and
GO:0001932 | regulation of protein phosphorylation

![image](https://user-images.githubusercontent.com/4782928/185999954-936467c9-7d0f-4dc7-9d62-3bb0a9120bb8.png)


Is this still a problem?

**Comment by pfey03** [comment]
@pgaudet the I wonder why it came up when I downloaded for the annotations under the phosphorylation term in QuickGO. I was also surprised to see in that list. But good if not related and must have been a mistake

**Comment by pgaudet** [comment]
I thought I saw it too ! Anyhow, if all tickets could magically fix themselves like that, it'd be great!
