### ISSUE TITLE
Obsoletion notice: GO:0039596 modulation by virus of host protein dephosphorylation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23641]
Dear all, 

The proposal has been made to obsolete 

* GO:0039596  modulation by virus of host protein serine/threonine phosphatase activity and 
* GO:0039596 modulation by virus of host protein dephosphorylation

There are no annotations or mappings to these terms; these terms are not present in any subsets. 
You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/23641

Thanks, Pascale

**Comment by pgaudet** [comment]
We will also obsolete the child term 
GO:0039586 modulation by virus of host PP1 activity

This has one keyword mapping, KW:KW-1126 Modulation of host PP1 activity by virus
@Antonialock please remap to 
- GO:0004865 protein serine/threonine phosphatase inhibitor activity and 
- GO:0039606 suppression by virus of host translation initiation

**Comment by Antonialock** [comment]
fixed
