### ISSUE TITLE
The term GO:0016218 has a consider-attribute but is not obsoleted

### ISSUE THREAD

**Issue by cmpich** [geneontology/go-ontology#23659]
GO:0016218:
`[Term]
id: GO:0016218
name: polyketide synthase activity
namespace: molecular_function
def: "Catalysis of a multistep reaction that produce polyketides through decarboxylative condensation of carboxylic acids. The key chain-building reaction, a C-N bond-forming reaction, involves the generation of the characteristic peptide bond by nucleophilic attack of the amino group of an amino-acyl donor unit covalently bound to a downstream peptidyl carrier protein module (amino acyl-S-PCP) on the acyl group of an upstream electrophilic acyl- or peptidyl acyl-S-PCP chain, catalyzed by a condensation (C) domain. Supplementing these core chain-elongation domains are variable numbers of auxiliary domains that are responsible for modification of the growing polypeptide chain by a small set of iterated reactions including epimerization, N-methylation, and heterocyclization." [PMID:10631508]
synonym: "PKS activity" RELATED []
is_a: GO:0003824 ! catalytic activity
intersection_of: GO:0003824 ! catalytic activity
intersection_of: part_of GO:0030639 ! polyketide biosynthetic process
relationship: part_of GO:0030639 ! polyketide biosynthetic process
property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/7340 xsd:anyURI
consider: GO:0034081
`
This term probably should be marked as obsoleted or the consider attribute needs to be removed.

**Comment by pgaudet** [comment]
Fixed, thanks for reporting this.
