### ISSUE TITLE
Obsoletion notice: GO:0039649 modulation by virus of host ubiquitin-protein ligase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23651]
Dear all, 

The proposal has been made to obsolete GO:0039649 modulation by virus of host ubiquitin-protein ligase activity. The reason for obsletion is that this term represents a molecular function. There are no annotations to this term. This term is not in any subsets. 

There is one KW mapping and one UniRule: 
* UniProtKB-KW:KW-1123 Modulation of host E3 ubiquitin ligases by virus > GO:modulation by virus of host ubiquitin-protein ligase activity ; GO:0039649
* UniRule:UR000496164 
These mappings can be moved to GO:0039648 modulation by virus of host protein ubiquitination

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/23651

Thanks, Pascale

**Comment by Antonialock** [comment]
fixed,
