### ISSUE TITLE
NTR:  neutral amino acid, sodium:proton antiporter activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#23663]
Please provide as much information as you can: 

* **Suggested term label:**
neutral amino acid, sodium:proton antiporter activity

* **Definition (free text)**
Enables the transfer of neutral amino acids from one side of a membrane to the other.

* **Reference, in format PMID:11698233

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
sodium:proton antiporter activity
neutral amino acid transmembrane transporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
GO:0140832
GO:0140831
GO:0140830

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140893
+name: neutral amino acid, sodium:proton antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: H+(in) + amino acid(out) + Na+(out) = H+(out) + amino acid(in) + Na+(in)." [PMID:11698233, PMID:34704597]
+synonym: "amino acid-coupled Na+/H+ exchanger activity" EXACT []
+xref: TC:2.A.18.6.8
+intersection_of: GO:0015297 ! antiporter activity
+intersection_of: has_primary_input CHEBI:24636 ! proton
+intersection_of: has_primary_input CHEBI:29101 ! sodium(1+)
+intersection_of: has_primary_input CHEBI:35238 ! amino acid zwitterion
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23663 xsd:anyURI
+created_by: pg
+creation_date: 2022-07-20T12:11:12Z
+
