### ISSUE TITLE
Retinal Isomerase GO:00004744 

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#23669]
RHEA:24124 **GO:0004744**
RHEA:24124, now obsolete. It was created for EC 5.2.1.3, which has been deleted by the Enzyme Commission
Deleted entry: retinal isomerase. Now known to be catalysed by a pathway involving EC 1.1.1.300, NADP-retinol dehydrogenase; EC 2.3.1.135, phosphatidylcholine--retinol O-acyltransferase; EC 3.1.1.64, retinoid isomerohydrolase; and EC 1.1.1.315, 11-cis-retinol dehydrogenase.
[EC 5.2.1.3 created 1961, modified 1976, deleted 2011] 
Best to obsolete this term
Check annotations to see which EC they can be mapped to.

_Anne_: I noticed that **GO:0004744** is used in UniProt
https://www.uniprot.org/uniprot/?query=goa:(%22retinal%20isomerase%20activity%20[4744]%22)
I will send a mail to UniProt curators to updated the corresponding entries

**Comment by sjm41** [comment]
Annotation review ticket: https://github.com/geneontology/go-annotation/issues/4136

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106429
+name: 11-cis-retinol dehydrogenase
+namespace: molecular_function
+def: "Catalysis of the reaction:11-cis-retinol-[retinal-binding-protein] + NAD(+) <=> 11-cis-retinal-[retinol-binding-protein] + NADH." [RHEA:55668]
+xref: EC:1.1.1.315
+xref: RHEA:55668
+is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
+property_value: creation_date 2022-07-15T17:58:20Z xsd:dateTime
+created_by: hjd

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106434
+name: retinal isomerization
+namespace: biological_process
+def: "The reactions involved in isomerization of all trans to all cis retnal." [PMID:21447403]
+comment: This process term replaces 'retinal isomerase' because  the Enzyme Commission has determined that the reaction is known to be catalyzed by a pathway involving multiple steps, catalized by  EC:1.1.1.300, EC:2.3.1.135, EC:3.1.1.64, and EC:1.1.1.315.
+is_a: GO:0042574 ! retinal metabolic process
+property_value: creation_date 2022-09-28T16:44:26Z xsd:dateTime
+property_value: term_tracker_item "" xsd:anyURI
+created_by: hjd

**Comment by hdrabkin** [comment]
All done
