### ISSUE TITLE
Obsoletion proposal: GO:0043486 histone exchange and regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23682]
Dear all, 

The proposal has been made to obsolete GO:0043486 histone exchange and regulation children: 
* GO:1900049 regulation of histone exchange
* GO:1900050 negative regulation of histone exchange
* GO:1900051 positive regulation of histone exchange
The reason for obsoletion is that this corresponds to a molecular function, GO:0140713 histone chaperone activity, or a child.     

Suggestions have been made for reannotation: 
* 1 TAIR
* 20 SGD SGD
* 2 MGI

(other groups have already removed their annotations to these terms.)

There are 3 InterPro annotations, see https://github.com/geneontology/go-annotation/issues/4235

These terms are no in any subsets.  

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/23682

We'd like to proceed to the obsoletion by July 26, 2022.

Thanks, Pascale

**Comment by tberardini** [comment]
@ebakker2 Can you please update the one TAIR annotation?

**Comment by EricaBakker** [comment]
Obsoleted it in TAIR, no need to find replacement GO annotation since was based on mutant, gene has other histone GO annotations.

**Comment by srengel** [comment]
Hi @pgaudet is there a spreadsheet of annotations for this? i can only find ~5 SGD annotations, and have removed those just now in P2GO.

**Comment by pgaudet** [comment]
Hi @srengel 

The spreadsheet is here: 
https://docs.google.com/spreadsheets/d/13Sys5a4tYDCtXJKzwZ29K-0VCCN_IMl9SGMchl_QLGM/edit#gid=0

Thanks, Pascale

**Comment by pgaudet** [comment]
And the annotation ticket here: https://github.com/geneontology/go-annotation/issues/4236

Sorry about the confusion.
