### ISSUE TITLE
GO:0103064	inositol phosphorylceramide mannosyltransferase activity  parent query

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23684]
SPAC2F3.01
I am picking up a mapping for 
GO:0000030	 mannosyltransferase activity IBA with A0A1D8PIF7 , S000000365 , S000005978 , PTN001285482

Is  already annotated to 
GO:0103064	inositol phosphorylceramide mannosyltransferase activity ISO with S000000365

So, should  GO:0000030	 mannosyltransferase activity be a parent of  GO:0103064 (or should the GO:0000030 annotation be removed), I am not sure?

**Comment by hdrabkin** [comment]
This should be fixed from another ticket (#23995) which made GO:0103064 a child of GO:0000030. I will close this now.
