### ISSUE TITLE
obsolete regulation of ER to Golgi vesicle-mediated transport by GTP hydrolysis (GO:0090113)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23686]
Please provide as much information as you can:

* **GO term ID and Label**
regulation of ER to Golgi vesicle-mediated transport by GTP hydrolysis (GO:0090113)

* **Reason for deprecation**

Added here
https://github.com/geneontology/go-ontology/issues/6761

combines a function and process

* **"Replace by" term (ID and label)**

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

Annotate to "regulation of ER to Golgi vesicle-mediated transport"

* **Are there annotations to this term?**
- How many EXP:

10
9 SGD
1 FlyBase

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0090113 ER to Golgi vesicle-mediated transport by GTP hydrolysis'. The reason for obsoletion is that this represents a combination of a MF and a BP. There are no annotations, no mappings to this term. This term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/23686


Thanks, Pascale
