### ISSUE TITLE
Fix labels  'GO:0140673 co-transcriptional chromatin reassembly'  and GO:0045815 epigenetic maintenance of chromatin in transcription-competent conformation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23696]
The labels of  'GO:0140673 co-transcriptional chromatin reassembly'  and GO:0045815 epigenetic maintenance of chromatin in transcription-competent conformation are confusing and not close enough to express that these are similar processes. 

We propose to change to 

- [x]  'GO:0140673 co-transcriptional chromatin reassembly'  -> transciptional elongation-coupled chromatin remodeling 
- [x]  GO:0045815 epigenetic maintenance of chromatin in transcription-competent conformation ->  transciptional initiation-coupled chromatin remodeling 

@colinlog @ValWood @hattrill @RLovering 

Thanks, Pascale

**Comment by ValWood** [comment]
I had to look them up every time ;)

**Comment by pgaudet** [comment]
Also made definitions more uniform:

- [ ] transciptional elongation-coupled chromatin remodeling 

The reestablishment of chromatin structure that was disrupted upon passage of RNA polymerase II during transcription elongation. This process prevents cryptic intragenic transcription initiation.

-> change to: A chromatin remodeling process that reestablishes the chromatin structure following the passage of RNA polymerase II during transcription elongation.


- [ ] transciptional initiation-coupled chromatin remodeling

An epigenetic process that capacitates gene expression by remodelling of chromatin by either modifying the chromatin fiber, the nucleosomal histones, or the DNA.
-> change to: A chromatin remodeling process that capacitates gene expression by either modifying the chromatin fiber, the nucleosomal histones, or the DNA.

**Comment by ValWood** [comment]
On the next call can we discuss which complexes should be annotated to each of these terms?

For example SWR-C, I have annotated to chromatin remodelling, I am not sure if it is GO:0140673 or GO:0045815  . Most likely transciptional initiation-coupled chromatin remodelling as it seems to do something at the +1 nucleosome?

**Comment by pgaudet** [comment]
Thanks for the comment. 
- GO:0140673 'transcriptional elongation-coupled chromatin remodeling'-> we fixed 'part of elongation' to 'happens during elongation' 
- However since  'GO:0045815 transcriptional initiation-coupled chromatin remodeling' is not restriction to initiation, it also happens before, I dont think we can add the relation 'happens during transcription initiation'. 
OK? 

Thanks, Pascale

**Comment by ValWood** [comment]
GO:0140673 'transcriptional elongation-coupled chromatin remodeling

I'm still confused by this ;)
The annotations to  include things like
GO:0140673 'transcriptional elongation-coupled chromatin remodeling'

SPBC21C3.16c | spt4 | DSIF transcription elongation factor complex subunit Spt4
SPAC23C4.19 | spt5 | DSIF transcription elongation factor complex subunit Spt5

which are always described as "elongation factors" (MF)
Are we saying. that these should no longer be annotated directly to "elongation"?
That seems confusing.

I did not know you could use "happens during" links within the ontology, and if they are used shud they be restricted to phases, rather than to say processes happen concurrently  (but I thought the remodelling was part of the elongation process)

**Comment by pgaudet** [comment]
> I did not know you could use "happens during" links within the ontology, and if they are used shud they be restricted to phases, rather than to say processes happen concurrently (but I thought the remodelling was part of the elongation process)

Good point, we don't have checks for usages of relations, I should remove that. 

WRT elongation, the definition of GO:0006354 DNA-templated transcription elongation is 'The extension of an RNA molecule after transcription initiation and promoter clearance at a DNA-dependent RNA polymerase promoter by the addition of ribonucleotides catalyzed by an RNA polymerase.', so that seems to exclude the chromatin unfolding and remodeling that takes place during elongation.  This is the conclusion @colinlog and I came to yesterday. Does that work? 

Should I just remove any link to DNA-templated transcription elongation? It can certainly be co-annotated if relevant. 

Otherwise the definition of elongation should be widened, but that would be odd. 

Thanks, Pascale

**Comment by ValWood** [comment]
Maybe we shouldn't still  be describing spt5 and spt6 as "elongation factors". This is the problem with these  "factor "terms in the MF ontology, they aren't precisely defined for process or function. (historically meaning a factor affecting).

(with the  GO exception of the precisely defined  DNA-binding transcription factor).

But maybe DSIF complex is involved in both elongation directly and in the chromatin remodelling.
(in which case I am happy to co-annotate)

@colinlog ?
.

**Comment by pfey03** [comment]
@pgaudet I find it bad that epigenetic is gone from the term. As epigenetic in papers is a big deal for example for set1 H3k4 methylase and so on. I was recently confused that I found the epigenetic term in AmiGO but in P2GO it's already the new term that I don't like so much instead. Need to inspect again from what I annotated that.

**Comment by ValWood** [comment]
Good point...

A sibling term has
negative regulation of gene expression, epigenetic
so would
 transcription initiation-coupled chromatin remodeling, epigenetic
be appropriate?

**Comment by pfey03** [comment]
Yes, I would like this primary term much better!

**Comment by pgaudet** [comment]
@pfey03 Would that help ?

**Comment by pfey03** [comment]
I'm not so happy that epigenetic is gone from all these terms. Epigenetic is used all over the place and says a lot in one word. Can at least in the def epigenetic be mentioned? I don't know if these terms can be used for Dicty, maybe 'transcriptional initiation-coupled chromatin remodeling' but I have so much to do, so checking these annotations again is a pain and not sure I can use these.

**Comment by pgaudet** [comment]
Also, changed GO:0140673 'transcriptional elongation-coupled chromatin remodeling' 'happens during'  GO:0006368 ! transcription elongation by RNA polymerase II

to part of'  GO:0006368 ! transcription elongation by RNA polymerase II'
