### ISSUE TITLE
Does this function exist? peptidyl-arginine C-methyltransferase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23704]
Hi, 

GO:0035244 peptidyl-arginine C-methyltransferase activity is defined as 'Catalysis of the transfer of a methyl group to the carbon atom of an arginine residue in a protein.' - however all the PRMT enzymes I find transfer to the nitrogen group, see for e. g. this review: https://journals.asm.org/doi/10.1128/EC.00099-07

There is a single annotations by GeneDB to l PRMT6 arginine N-methyltransferase, type I from [PMID:20418380](http://amigo.geneontology.org/amigo/reference/PMID:20418380) (also annotated to '[histone-arginine N-methyltransferase activity](http://amigo.geneontology.org/amigo/term/GO:0008469)'  - I think this annotation is wrong? 

@kaxelsen do you know if this activity exists? 

Thanks, Pascale

**Comment by pgaudet** [comment]
If there is not C-methlytransferases for proteins, then we'll need to merge 
'histone arginine N-methyltransferase activity' & 'histone methyltransferase activity'

**Comment by kaxelsen** [comment]
Based on the available evidence (PMID:20418380), Trypanosoma brucei PRMT6 is NOT a C-methyltransferase, but an N-methyltransferase. 
I have not been able to find (by a simple literature search) any evidence of protein C-methyltransferases.

**Comment by pgaudet** [comment]
I think I have found evidence for this reaction: 

PMID:29743535, PMID:33162960

This modification occurs in anaerobic bacteria. 

I'll keep the MF and obsolete the 2 corresponding BPs  (single step processes):

* GO:0035245 peptidyl-arginine C-methylation
* GO:0018181 peptidyl-arginine C5-methylation

Thanks, Pascale

**Comment by pgaudet** [comment]
+ change label 
 GO:0035244
-name: peptidyl-arginine C-methyltransferase activity
+name: protein-arginine C-methyltransferase activity

to match other terms

**Comment by kaxelsen** [comment]
Do you have a typo in PMID:29743535? It does not link to an article in PubMed.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
* GO:0035245 peptidyl-arginine C-methylation
* GO:0018181 peptidyl-arginine C5-methylation

because these represent molecular functions.  There are no annotations to these terms, these terms are not in any subsets. 
RESID:AA0272 maps to  GO:0018181 peptidyl-arginine C5-methylation @nataled.   

You can comment on the ticket: 
https://github.com/geneontology/go-ontology/issues/23704

Thanks, Pascale

**Comment by pgaudet** [comment]
+ add taxon constraint bacteria

**Comment by pgaudet** [comment]
Added xrefs: 
EC:2.1.1.379
RHEA:66028
