### ISSUE TITLE
Obsolete GO:0016277 [myelin basic protein]-arginine N-methyltransferase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23705]
The EC associated with some synonyms of 'GO:0016277 myelin basic protein]-arginine N-methyltransferase activity', EC:2.1.1.126, has been transferred to [2.1.1.319,](https://enzyme.expasy.org/EC/2.1.1.319,) 2.1.1.320, 2.1.1.321 and 2.1.1.322

GO:0016277 should probably be obsoleted (5 EXP)

**Comment by hdrabkin** [comment]
Clearly the human annotation is one of the 'omega,omega" terms 
J Biol Chem
. 2005 Feb 4;280(5):3656-64.
doi: 10.1074/jbc.M405295200. Epub 2004 Oct 19.
PRMT7, a new protein arginine methyltransferase that synthesizes **symmetric dimethylarginine**

**Comment by hdrabkin** [comment]
AT1G04870	protein arginine methyltransferase 10		GO:0016277		TAIR	NCBITaxon:3702	IDA			protein	TAIR:gene:1005715709	TAIR:Publication:501723548|PMID:18007657	20080912

AT3G06930	AT3G06930		GO:0016277		TAIR	NCBITaxon:3702	IDA			protein	TAIR:locus:2077567	TAIR:Publication:501727245|PMID:18660432	20080907

AT5G49020	protein arginine methyltransferase 4A		GO:0016277		TAIR	NCBITaxon:3702	IDA			protein	TAIR:locus:2154339	TAIR:Publication:501727245|PMID:18660432	20080906
WB:WBGene00016408			GO:0016277		UniProt	NCBITaxon:6239	IDA		PANTHER:PTHR10738	gene		WB_REF:WBPaper00038379|PMID:21531333	20170210

UniProtKB:Q9NVM4	Protein arginine N-methyltransferase 7		GO:0016277		HGNC-UCL	NCBITaxon:9606	IDA		PANTHER:PTHR11006	protein		PMID:15494416	20060303

**Comment by hdrabkin** [comment]
3 Tair IDA annotations to this term. The MBP is being used in substrate assay, and so not relevant to this term. Move these annotations to parent.
UniProt  (HGNC) annotation could be moved up to parent with MBP in has_input extension UNLESS MBP is being used only as in vitro assay.

**Comment by pgaudet** [comment]
Annotations are here: https://github.com/geneontology/go-annotation/issues/4256

Thanks, Pascale
