### ISSUE TITLE
GO:0000510   H3-H4 histone complex chaperone activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23718]
GO:0000510   H3-H4 histone complex chaperone activity

Definition ([GO:0000510 GONUTS page](http://gowiki.tamu.edu/wiki/index.php/Category:GO:0000510))
A histone chaperone that carries a H3-H4 histone complex. PMID:28053344

From our conversation last week it seems that this term should  also be used for 
H3.1/H4 chaperone 

can this be made clearer in the definition, and perhaps with exact synonyms?

**Comment by pgaudet** [comment]
How about if we add a comment that states "Note that this term includes the exchange of histone H3 variants H3.1 and H3.3."


+ narrow synonyms 
* H3.1-H4 histone complex chaperone activity
* H3.3-H4 histone complex chaperone activity

Would that be sufficiently clear?

**Comment by pgaudet** [comment]
@colinlog

**Comment by ValWood** [comment]
For me, that would work
