### ISSUE TITLE
Taxon constraint: GO:0140858    histone ubiquitin ligase activity (H2A-K15 specific)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23719]
Please provide as much information as you can: 

* **GO term ID label:**

GO:0140858    histone ubiquitin ligase activity (H2A-K15 specific)

* **Request to add a taxon constraint:**

But  yeast H2A  does not have an equivalent  K15 position  

* * **only in taxon: **
* * **never in taxon: **

add "never in yeast"

(this will ensure that we do not get propagated annotations)

**Comment by pgaudet** [comment]
Is NCBITaxon:4890 Ascomycota right?

**Comment by ValWood** [comment]
correct!
