### ISSUE TITLE
siRNA processing defintion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23749]
It seems that this term has been made narrower in scope.

The term processing refers to the production of a mature transcript. but the definition includes
"MAy also include amplification step of the siRNA by RNA-directed RNA polymerase."
This part of the process isn't processing.

**Comment by pgaudet** [comment]
What is the problem ? 'Processing' is defined differently for RNAs than for proteins, this encompasses the entire maturation. This is how it's used in the literature, I think it's better to leave it as it is. 

What do you think?

**Comment by ValWood** [comment]
It may be OK, will close until I try to curate the pathways. I struggle with these modules within modules.
