### ISSUE TITLE
add GO:0008275 part_of GO:0000931

### ISSUE THREAD

**Issue by manulera** [geneontology/go-ontology#23740]
cc @ValWood 

The gamma-tubulin small complex is part of the gamma-tubulin ring complex

From PMID:35622906

![25789430-2021-micropub biology 000464 (1)](https://user-images.githubusercontent.com/22526102/180006164-b2df3e2b-c968-4f48-b266-80b5087a4058.jpg)

From this review: https://link.springer.com/article/10.1007/s00709-016-1070-z

![Screenshot 2022-07-20 at 15 23 37](https://user-images.githubusercontent.com/22526102/180006628-7712dd72-3dd6-4eb0-bdbb-9107b5e51378.png)

**Comment by raymond91125** [comment]
In the ref PMID:35622906, "In addition, there is also evidence for differential localization of γ-TuSC and γ-TuRC complexes (Gao et al. 2019). The combined effect could translate into molecularly distinct MTOCs with differential microtubule nucleation potential, leading to unique microtubule arrays in different regions of a cell. "
Doesn't this mean that NOT all γ-TuSC is in γ-TuRC? In other words, the relation should probably be γ-TuRC **HAS_PART** γ-TuSC (all γ-TuRC contains some γ-TuSC).

**Comment by manulera** [comment]
> Doesn't this mean that NOT all γ-TuSC is in γ-TuRC?

Hello @raymond91125. In this case, it does not mean that those gamma-turcs don't have gamma-tusc in them.

From the reference metioned there (Gao et al. 2019)
> Three components, γ-tubulin, GCP2 and GCP3, constitute the core structure of the γ-TuRC and are termed the γ-tubulin small complex (γ-TuSC).

The main conclusion from that publication is:
> Our data suggest that SPBs consist of γ-tubulin small complexes (γ-TuSCs) at the outer plaque, and larger γ-tubulin ring complexes (γ-TuRC) at the inner plaque.

Several gamma-tusc complexes can assemble into a ring-link structure that is not the cannonical gamma-turc, and also nucleate microtubules. That's what the authors mean when they are saying that they have differential localization, that there are structures that have gamma-tusc complexes but are not canonical gamma-turcs.

From the same publication, the different structures they describe:

![Screenshot 2022-07-22 at 09 42 18](https://user-images.githubusercontent.com/22526102/180400481-11d6083b-80e4-4806-b8be-0a31ac22522e.png)

Gamma-tusc is the complex of 2 γ-tubulins, 1 GCP2 and 1 GCP3 (2 pink balls, 1 blue oval, 1 purple oval), so you can see it is present in all types of structures.

**Comment by raymond91125** [comment]
@manulera Sorry that I did not say it clearly. Yes, it makes sense to me. And as @ValWood said, the has_part relation is the correct one. That is γ-TuRC has_part γ-TuSC.

From http://geneontology.org/docs/ontology-relations/:

The part of relation is used to represent part-whole relationships. part of has a specific meaning in GO, and a part of relation would only be added between A and B if B is necessarily part of A: wherever B exists, it is as part of A, and the presence of the B implies the presence of A. However, given the occurrence of A, we cannot say for certain that B exists.

The logical complement to the part of relation is has part, which represents a part-whole relationship from the perspective of the parent. As with part of, the GO relation has part is only used in cases where A always has B as a part, i.e. where A necessarily has part B. If A exists, B will always exist; however, if B exists, we cannot say for certain that A exists. i.e. all A have part B; some B part of A.

**Comment by manulera** [comment]
Oh I see now. I had misunderstood. So then yes, has_part it is!

**Comment by ValWood** [comment]
Thanks @raymond91125 A better explanation!
