### ISSUE TITLE
TPV small non-coding RNA-dependent heterochromatin formation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23748]
small non-coding RNA-dependent heterochromatin formation

There is an issue here:

1, GO:0140727  
siRNA-dependent pericentric heterochromatin formation
is a type of 
small non-coding RNA-dependent heterochromatin formation

but it cannot go under this term, because it isn't gene silencing. 

The name of the term is too broad.
I think you can only solve this by being explicit in the  name of 
small non-coding RNA-dependent heterochromatin formation
and reverting it to 
pre-transcriptional gene silencing by small non-coding RNA
or some other way to separate the two processes. The term needs to have "gene silencing" somewhere in the name.

Otherwise  the name is too broad and curators will be confused.

also some of the synonyms are broader in scope than the definition
e.g.
heterochromatin assembly by small RNA | exact

2. note trancription-> transcription and  beginnning ->beginning
3. The definition 
"that occur before the beginning of transcription"  is a bit odd 
"to prevent transcription" might be better wording since you cant happen before something that doesn't occur?

**Comment by ValWood** [comment]
I see the same issue here:


<img width="664" alt="Screenshot 2022-07-21 at 13 54 58" src="https://user-images.githubusercontent.com/7359272/180218584-816bd7ff-e81a-4bcd-841d-79a1ce76217c.png">

siRNA-dependent pericentric heterochromatin formation should be a sibling of 
siRNA-dependent facultative  heterochromatin formation 
under 
small non-coding RNA-dependent heterochromatin formation

based on standerrd nomenclature, but this would be a TVP because 
siRNA-dependent pericentric heterochromatin formation 
is a child of gene-silencing by RNA.

Not all siRNA-dependent heterochromatin formation  is gene silencing

**Comment by pgaudet** [comment]
@ValWood @colinlog 

'siRNA-dependent pericentric heterochromatin formation' should be is_a 'pericentric heterochromatin organization', which should be moved under 'constitutive heterochromatin formation', right ?

**Comment by pgaudet** [comment]
And I can rename GO:0031048 small ncRNA-mediated heterochromatin formation >> small ncRNA-mediated facultative heterochromatin formation 

OK @ValWood @colinlog ?

**Comment by ValWood** [comment]
'siRNA-dependent pericentric heterochromatin formation' should be is_a 'pericentric heterochromatin organization', which should be moved under 'constitutive heterochromatin formation', right ?

'pericentric heterochromatin organization', is broader than formation. It includes terms to organizing the heterochromatin spatially....

but 
pericentric heterochromatin formation (GO:0031508)
should be under
'pericentric heterochromatin organization',

**Comment by ValWood** [comment]
>And I can rename GO:0031048 small ncRNA-mediated heterochromatin >formation >> small ncRNA-mediated facultative heterochromatin formation

no because siRNAs are ncRNAs and these are often constitutive regions

**Comment by pgaudet** [comment]
Fixed - OK for @ValWood
