### ISSUE TITLE
GO:0031508   pericentric heterochromatin formation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23752]
single inheritance

GO:0031508   pericentric heterochromatin formation
has only one none-regulation child
GO:0140727   siRNA-dependent pericentric heterochromatin formation

are there other mechanisms of pericentromeric heterochromatin assembly, or do they all involve siRNA-dependent 

@colinlog 

(for pombe it is only siRNA-dependent)

**Comment by pgaudet** [comment]
There are non.RNA dependent mechanisms of pericentric heterochromatin formation, see for eg PMID:14612388

So we decided to 

- [ ] remove parent ''small ncRNA-mediated heterochromatin formation'' from 'pericentric heterochromatin formation' ''
- [ ] add direct asserted superclass ''small ncRNA-mediated heterochromatin formation' to GO:0140727 siRNA-dependent pericentric heterochromatin formation

**Comment by ValWood** [comment]
Are you sure about this?

>There are non.RNA dependent mechanisms of pericentric heterochromatin formation, see for eg PMID:14612388

"These results are consistent with a model in which Lsh is recruited by intact heterochromatin structure and then assists in maintaining heterochromatin organization by establishing CpG methylation patterns."

I remember when we  originall discussed  this, we concluded that establishment (aka formation) was always via siRNA mechanisms.
this paper (PMID:14612388) is describing  non-RNA dependent mechanisms for **maintaining** pericentric heterochromatin, (i.e after it is formed). Do you have any other papers supporting a non RNAi-based mechanism for pericentromeric heterochromatin formation?

**Comment by pgaudet** [comment]
We obsoleted 'heterochromatin maintenance' - the paper states "These results are consistent with a model in which Lsh is recruited by intact heterochromatin structure and then assists in maintaining heterochromatin organization by **establishing** CpG methylation patterns" - so heterochromatin formation still seems OK for this. 

Do you suggest hat we restore heterochromatin maintenance ? Then would that be RNA-independent?

**Comment by ValWood** [comment]
Actually, if

[RNAi-dependent heterochromatin assembly.]stays under
[pericentric heterochromatin formation](https://www.pombase.org/term/GO:0031508)
this is probably OK.
