### ISSUE TITLE
Question about hasSynonym property

### ISSUE THREAD

**Issue by psiotwo** [geneontology/go-ontology#23778]
I was not able to find best practices / rules for using `oboInOwl:hasSynonym` and its sub properties (e.g. `oboInOwl:hasExactSynonym`). In particular, for some cases I need to represent some metadata (not only editorial) about labels (e.g. their source, author, and other). 

To ensure OBO compliance I am using `oboInOwl:hasExactSynonym`, but not sure whether the intended use-cases involve also resources as fillers (not just literals). Basically, I need st. similar to `skosxl:Label`.

What is the intended usage of `oboInOwl:hasSynonym` and its sub properties? Thanks a lot.

**Comment by pgaudet** [comment]
Hi @psiotwo 
The guidelines for GO synonym types are here: https://wiki.geneontology.org/Synonyms#Synonym_scopes

Does that address your question? 

Thanks, Pascale

**Comment by psiotwo** [comment]
@pgaudet thanks a lot for the link to the wiki. It does not seem to contain an explicit discussion about what should be a filler here. But I found [this query](https://github.com/geneontology/go-ontology/blob/9f43bc4164b683a7ed9196272780a5c3805b8f21/src/sparql/synonyms.sparql) which seems to suggest that OWL annotation mechanism is the anticipated way of modeling the metadata here.

**Comment by pgaudet** [comment]
OK great!
