### ISSUE TITLE
suggestion: remove RHEA:58156 from GO:0046932, GO:0046962

### ISSUE THREAD

**Issue by rwst** [geneontology/go-ontology#23771]
See also #19379 but there is still a problem. RHEA:58156 is one of only 5 RHEA xrefs that are referred to twice by a GO xref. But it is the only one where there is a second xref on the GO entry that is more exact:

id: GO:0046932
name: sodium-transporting ATP synthase activity, rotational mechanism
xref: RHEA:58156
xref: RHEA:58158

Here RHEA:58158 is the exact ref.

id: GO:0046962
name: sodium-transporting ATPase activity, rotational mechanism
xref: RHEA:58156
xref: RHEA:58157

Here RHEA:58157 is the exact ref.
I therefore propose to remove RHEA:58156 from both entries.

**Comment by hdrabkin** [comment]
RHEA: 58156 is a broad synonym for both, which is fine.

**Comment by pgaudet** [comment]
Maybe just to add a bit of context: we usually xref to the non-directional reactions, so we want to keep links to the non-directional reactions, so we do want to keep RHEA:58156, in addition to the directional reactions that correspond to GO:0046932 and GO:0046962.
