### ISSUE TITLE
Obsoletion proposal: GO:0004158 dihydroorotate oxidase activity -

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/go-ontology#23789]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0004158 dihydroorotate oxidase activity  Catalysis of the reaction: (S)-dihydroorotate + O(2) = H(2)O(2) + orotate.

* **Reason for deprecation**
The EC and RHEA mapped to this term
EC:1.3.3.1 Dihydroorotate oxidase (fumarate) (S)-dihydroorotate + fumarate <=> orotate + succinate  is not consistent with the GO definition

RHEA:15441 was obsoleted by RHEA and replaced with RHEA:30059, which describes the EC reaction. Again, not consistent with the GO def. 
Thus these were removed, leaving NO xref (including PMIDS) for this reaction.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
There are 15 annotations to this term. All but 2 are IEA via Interpro domains
The remaining two annotations

1. pyrD Dihydroorotate dehydrogenase B (NAD(+)), catalytic subunit dihydroorotate oxidase activity JCVI Listeria monocytogenes serotype 4b str. F2365 **ISS** UniProtKB:P54322 protein PMID:15115801
This annotation is an ISS made to UniProtKB:P54322 PYRDB_LACLM. UniProt has THIS annotated to EC:1.3.1.14 and Rhea 13513. These map to **GO:0004589; thus the current annotation to pyrD should be changed to this GO term.** 

2. ANIA_05909 Dihydroorotate dehydrogenase (quinone), mitochondrial dihydroorotate oxidase activity AspGD Aspergillus nidulans FGSC A4 **RCA** dihydroorotate dehydrogenase (quinone), mitochondrial-related pthr48109 protein PMID:18405346
This paper is used to annotate 1146 gene products via RCA . Based on the incorrect original EC assignment, **I propose that this annotation be deleted as there is no data on substrates, etc. in this paper.** 

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
13 IEA annotations 
* **Is this term in a subset? 
 NOT a member of a subset.

* **Any other information**
See ticket #23786
We propose to obsolete this term asap.

**Comment by hdrabkin** [comment]
@pgaudet 
JCVI: 
AspGD

Are these two something UniProt handles?

**Comment by pgaudet** [comment]
I handle these (or Antonia) - see https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

**Comment by hdrabkin** [comment]
I removed the replace_by from the obsoleted term. Closing.
