### ISSUE TITLE
fixes in GO:0004152 dihydroorotate dehydrogenase activity branch

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23786]
Related to #23541

Some edits need to be made in this branch: 
* GO:0004152 dihydroorotate dehydrogenase activity
 ** has  dbxref [EC:1.3.5.2](https://enzyme.expasy.org/EC/1.3.5.2) -> WRONG, this is Dihydroorotate dehydrogenase (**quinone**).  

- [x]  Removed EC; kept RHEA; also removed quinone synonyms.

**EC:1.3.5.2 corresponds to [RHEA:30187](https://www.rhea-db.org/rhea/30187), which we dont have in GO. Create new term? Most annotations to GO:0004152 are to the quinone enzyme (although some are to the fumarate)

 ** GO:0004152 has dbxref https://www.rhea-db.org/rhea/18073 -> OK, this is the general reaction '(S)-dihydroorotate +   A =   AH2 +   orotate'; kept.

 **  GO:1990663 dihydroorotate dehydrogenase (fumarate) activity -> [EC:1.3.98.1](https://enzyme.expasy.org/EC/1.3.98.1) -> move under 'oxidoreductase activity, acting on the CH-CH group of donors' ; 
  

** GO:0004158 dihydroorotate oxidase activity -> obsolete with replace by GO:1990663  (InterPro annotations already moved)

**Comment by hdrabkin** [comment]
How I see this
GO:0004152 is the parent reaction, whereby  (S)-dihydroorotate + A = AH(2) + orotate.
So, you can have different Acceptors.
 GO:1990663 uses fumarate as the acceptor; child of 4152
 GO: new uses quinone as the acceptor; this is child for 4152
GO:0004158 uses O2 as acceptor but we have no evidence. All synonyms points to GO:new

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106430
+name: dihydroorotate dehydrogenase (quinone) activity
+namespace: molecular_function
+def: "(S)-dihydroorotate + a quinone <=> orotate + a quinol." [RHEA:30187]
+xref: EC:1.3.5.2
+xref: RHEA:30187
+is_a: GO:0004152 ! dihydroorotate dehydrogenase activity
+property_value: creation_date 2022-07-26T19:27:20Z xsd:dateTime
+property_value: term_tracker_item s://github.com/geneontology/go-ontology/issues/23786 xsd:anyURI
+created_by: hjd

**Comment by hdrabkin** [comment]
@pgaudet just realized GO:0004158 did have two non IEA annotations; one RCA using PMID:18405346 and one ISS using 
PMID:15115801 to  UniProtKB:P54322 |  
--

[UniProtKB:P54322
UniProt has annotated using
EC:1.3.1.14 ([UniProtKB](https://www.uniprot.org/uniprotkb?query=ec:1.3.1.14) | [ENZYME](https://enzyme.expasy.org/EC/1.3.1.14) | [Rhea](https://www.rhea-db.org/rhea?query=ec:1.3.1.14)
Source: [Rhea 13513](https://www.rhea-db.org/rhea/13513)


I need to undo the obsolete

**Comment by hdrabkin** [comment]
And looking, I think GO:0004589 should also be made a child of GO:0004152 (4589 using NAD as the acceptor).

**Comment by pgaudet** [comment]
1. ISS using PMID:15115801 to UniProtKB:P54322 | GO:0004589
-> Gene annotated: Q71YI3: I changed to GO:0004589 orotate reductase (NADH) activity to match the annotation in the P54322 entry ([Rhea 13513](https://www.rhea-db.org/rhea/13513))
2. RNA PMID:18405346 / G5EB61 will need to be moved to GO:0106430 when this is in P2GO (should be imminent)

**Comment by hdrabkin** [comment]
obsoleted  GO:0004158 in ticket  #23789 and added to additonal parent to new quinone term.  
+[Term]
+id: GO:0106430
+name: dihydroorotate dehydrogenase (quinone) activity
+namespace: molecular_function
+def: "(S)-dihydroorotate + a quinone <=> orotate + a quinol." [RHEA:30187]
+xref: EC:1.3.5.2
+xref: RHEA:30187
 is_a: GO:0004152 ! dihydroorotate dehydrogenase activity
**+is_a: GO:0016635 ! oxidoreductase activity, acting on the CH-CH group of donors, quinone or related compound as acceptor**
+property_value: creation_date 2022-07-26T19:27:20Z xsd:dateTime
+property_value: term_tracker_item s://github.com/https://github.com/geneontology/go-ontology/issues/23786 xsd:anyURI
+created_by: hjd
