### ISSUE TITLE
missing parent small non-coding RNA-dependent heterochromatin formation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23783]
GO:0031048 small non-coding RNA-dependent heterochromatin formation

should be a parent of
GO:0140727  siRNA-dependent pericentric heterochromatin formation

or probably even
GO:0031508  pericentric heterochromatin formation
(since I think pericentric heterochromatin formation always depended on siRNA? do we know of any examples where it isn't?)

**Comment by pgaudet** [comment]
I'm adding the relation shown in red here: 

<img width="656" alt="image" src="https://user-images.githubusercontent.com/4782928/184829832-c9a43520-3c6a-41c9-9436-4f0b10a5b8c0.png">



@colinlog @hattrill @gantonazzo @RLovering
