### ISSUE TITLE
NTR      histone acyltransferase activity and histone propionyltransferase

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23791]
- [ ] ~histone~ protein acyltransferase activity 
[RHEA:53916](https://www.rhea-db.org/rhea/53916)
    an acyl-CoA + L-lysyl-[protein] = CoA + H+ + N6-acyl-L-lysyl-[protein]

- [x] histone propionyltransferase activity (synonym: histone propanoyltransferase activity)
 [RHEA:54020](https://www.rhea-db.org/rhea/54020)
L-lysyl-[protein] + propanoyl-CoA = CoA + H+ + N6-propanoyl-L-lysyl-[protein]

- [x] histone H4K16 propionyltransferase activity
PMID:31794431
PMID:17267393
PMID: 29321206

**Comment by pgaudet** [comment]
Other reference: PMID:31794431
KAT8 + histone propionyltransferase activity (Fig 6)

**Comment by edwong57** [comment]
@pgaudet  Does this sound right?

Add new term histone acyltransferase activity as a subclass of acyl-CoA N-acyltransferase activity (GO:0019186).

It looks like histone propionyltransferase activity is GO:0061922, so I will add the RHEA as a cross ref. 

Make the new term histone H4K16 propionyltransferase activity a sublcass of histone propionyltransferase activity (GO:0061922).

**Comment by pgaudet** [comment]
I'll take this back - this is not right

**Comment by pgaudet** [comment]
> histone propionyltransferase activity (synonym: histone propanoyltransferase activity)

already exists GO:0061922

- [ ] Added xref RHEA:54020 to GO:0061920 protein propionyltransferase activity

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141002
+name: histone H4K16 propionyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: histone H4 L-lysine (position 16) + propionyl-CoA = CoA + H+ + histone H3 N6-propionyl-L-lysyl (position 16)." [PMID:17267393, PMID:29321206, PMID:31794431]
+is_a: GO:0061922 ! histone propionyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23791 xsd:anyURI
+created_by: pg
+creation_date: 2023-02-28T13:42:40Z
+

**Comment by pgaudet** [comment]
For RHEA mapping see #25036 (this was not a histone-specific term)
