### ISSUE TITLE
GO:2000708   myosin filament organization involved in cytokinetic actomyosin contractile ring assembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23809]
Please provide as much information as you can:

* **GO term ID and Label**

GO:2000708  
myosin filament organization involved in cytokinetic actomyosin contractile ring assembly

* **Reason for deprecation**

This term has no annotations and  although myosin filaments are part of assembly it seems strange to have a separate process for this (myosin filaments don't seem to be independently organised by assembly, the parent is sufficient)

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

**Comment by pgaudet** [comment]
How about if I merge into 
[GO:0000915 actomyosin contractile ring assembly](http://amigo.geneontology.org/amigo/term/GO:0000915#display-lineage-tab)? 

Thanks, Pascale

**Comment by pgaudet** [comment]
There seems to be a lot of redundancy in this branch: 


![image](https://user-images.githubusercontent.com/4782928/184611635-ccf69187-3722-4b1c-9515-6bb82863d7f0.png)

**Comment by ValWood** [comment]
Yep I agree about the redundancy. I will suggest removal/ merges when I see them, especially unused. Some are really MF placeholders.  Some are subtly different, but I don't think we need them all.
