### ISSUE TITLE
NTR: [mitocytosis]

### ISSUE THREAD

**Issue by LiNiMGI** [geneontology/go-ontology#23807]
New term: mitocytosis
Definition: a migrasome-mediated selective removal of damaged mitochondria process that maintains mitochondrion homeostasis in migrating cells.

PMID:34048705 “Mitocytosis, a migrasome-mediated mitochondrial quality-control process”.  

There is also a commentary published about this paper, which might be helpful for the editors to quickly understand the process.
PMID: 34108688
https://www.nature.com/articles/s41580-021-00388-0

Gene product name and ID to be annotated to this term: mouse Tspan9, tetraspanin 9

We do already have migrasome GO:0140494 in GO.

My discussion with Harold and Val: we don't know what all its parents should be, but “export from cell" GO:0140352 would certainly be a one and
it should probably also be a child of 
GO:0061726    mitochondrion disassembly 
which would make it a sibling of mitophagy

The paper also named these mitochondrion-containing migrasomes as mitosomes.
 In GO, we already have a term mitosome, however, it is defined in GO as: The mitosome has been detected only in anaerobic or microaerophilic organisms that do not have mitochondria.

**Comment by raymond91125** [comment]
There is a term GO:0140495 Name migracytosis Definition A cell migration-dependent mechanism for releasing cellular contents. This could be a IS_A parent. However, migracytosis has an IS_A parent "cell migration". That does not seem right as it is only part of a cell migration process (not a type of), and may not be a necessary part.

So perhaps
mitocytosis IS_A migracytosis IS_A export from cell
&&
mitocytosis IS_A mitochondrion disassembly

The usage of "mitosome" in PMID:34108688 is unfortunate; I agree with that we may not want to propagate it.

**Comment by LiNiMGI** [comment]
sounds good to me, thanks Raymond!

**Comment by raymond91125** [comment]
Instead of mitochondrion disassembly, this process probably should be a child of mitochondrion distribution DEF Any process that establishes the spatial arrangement of mitochondria between and within cells.
WRT to Myo19's role, the authors cited an article titled "ROS induced distribution of mitochondria to filopodia by Myo19 depends on a class specific tryptophan in the motor domain.".

**Comment by pgaudet** [comment]
Thanks!
