### ISSUE TITLE
insulin-like growth factor receptor activity (GO:0005010) is not always a tyrosine kinase

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#23810]
The IGF2R is not a tyrosine kinase. PMID:22710100, PMID:23257688. It appears that this receptor functions to scavenge IGF2, so I'm not sure we would even consider it a signaling receptor.

**Comment by hattrill** [comment]
@ukemi could a NOT be used to block propagation from non-manual sources here?

**Comment by ukemi** [comment]
That would be a solution for annotations, but this error exists in the ontology. It would be better to correct it there.

**Comment by hattrill** [comment]
I think for the example that you cite, it's not a it a signaling receptor and so the annotation would be wrong. Perhaps a new term for this scavenge-like function - not sure if GO:0005044 would do?

**Comment by pgaudet** [comment]
Hi @ukemi 
IGF2R is not a signaling receptor either then, is it?  Since it does not activate signaling upon ligand binding, it seems to  regulate insulin-like signaling rather than be involved in the signaling?

**Comment by ukemi** [comment]
Works for me.
