### ISSUE TITLE
NTR: [Bicarbonate:chloride antiporter activity]

### ISSUE THREAD

**Issue by SHS111** [geneontology/go-ontology#23813]
Please provide as much information as you can: 

* **Suggested term label:**
*  Bicarbonate:chloride antiporter activity

Rhea:72363]: chloride(out) + hydrogencarbonate(in) = chloride(in) + hydrogencarbonate(out) 

* **Definition (free text)**
*  Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction:  chloride(out) + hydrogencarbonate(in) = chloride(in) + hydrogencarbonate(out) 

* **Reference, in format
*  PMID:12958022, PMID:24515893, PubMed:34668226

* **Gene product name and ID to be annotated to this term** 
* gene:Slc4a2  ID: B3A2_human, mouse, rat

* **Parent term(s)**
* GO:0015299 solute:proton antiporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Redundant with #23828
