### ISSUE TITLE
NTR: L-asparagine:sodium symporter activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#23815]
Please provide as much information as you can: 

* **Suggested term label:**
 L-asparagine:sodium symporter activity

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: L-asparagine(out) + Na+(out) = L-asparagine(in) + Na+(in).

* **Reference, in format PMID:28416685

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
neutral amino acid:sodium symporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
RHEA:71383

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140901
+name: L-asparagine:sodium symporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: L-asparagine(out) + Na+(out) = L-asparagine(in) + Na+(in)." [PMID:21511949, PMID:28416685]
+synonym: "L-asparagine:sodium symporter activity" EXACT []
+synonym: "sodium:asparagine symporter activity" EXACT []
+synonym: "sodium:L-asparagine symporter activity" EXACT []
+xref: RHEA:71383
+xref: TC:2.A.18.6.13
+intersection_of: GO:0015293 ! symporter activity
+intersection_of: has_primary_input CHEBI:32650 ! L-asparaginate
+intersection_of: has_primary_input CHEBI:66916 ! alanine zwitterion
+created_by: pg
+creation_date: 2022-08-18T05:58:25Z
