### ISSUE TITLE
NTR:L-glutamine:sodium symporter activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#23814]
Please provide as much information as you can: 

* **Suggested term label:**
L-glutamine:sodium symporter activity

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: L-glutamine(out) + Na+(out) = L-glutamine(in) + Na+(in). 

* **Reference, in format PMID:#######**28416685 

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
neutral amino acid:sodium symporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140902
+name: L-glutamine:sodium symporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: L-glutamine(out) + Na+(out) = L-glutamine(in) + Na+(in)." [PMID:28416685]
+synonym: "L-glutamine:sodium symporter activity" EXACT []
+synonym: "sodium:glutamine symporter activity" EXACT []
+synonym: "sodium:L-glutamine symporter activity" EXACT []
+xref: TC:2.A.18.6.13
+is_a: GO:0005295 ! neutral amino acid:sodium symporter activity
+intersection_of: GO:0015293 ! symporter activity
+intersection_of: has_primary_input CHEBI:58359 ! L-glutamine zwitterion
+intersection_of: has_primary_input CHEBI:66916 ! alanine zwitterion
+created_by: pg
+creation_date: 2022-08-18T06:09:17Z
