### ISSUE TITLE
NTR: [chloride:bicarbonate antiporter activity]

### ISSUE THREAD

**Issue by SHS111** [geneontology/go-ontology#23828]
Please provide as much information as you can: 

* **Suggested term label:**
*  chloride:bicarbonate antiporter activity

* **Definition (free text)**
* Enables the transfer of a solute or solutes from one side of a membrane to the other    according to the reaction: 
Reaction=2 chloride(out) + hydrogencarbonate(in) = 2 chloride(in) + hydrogencarbonate(out)   [Rhea:72203]

* **Reference, in format PMID:#######**
* PMID:10428871, PMID:16606687

* **Gene product name and ID to be annotated to this term**
* Gene:SLC26A3,  ID=S26A3_human,  S26A3_mouse

* **Parent term(s)**
* bicarbonate:anion antiporter activity GO:0140829

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Rhea : [Rhea:72203]
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+id: GO:0140900
+name: chloride:bicarbonate antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: chloride(in) + HCO3-(out) = chloride(out) + HCO3-(in)." [PMID:10428871, PMID:16606687, RHEA:72203]
+synonym: "bicarbonate:chloride antiporter activity" EXACT []
+xref: RHEA:72203
+xref: TC:2.A.53.2.18
+intersection_of: GO:0015297 ! antiporter activity
+intersection_of: has_primary_input CHEBI:17544 ! hydrogencarbonate
+intersection_of: has_primary_input CHEBI:17996 ! chloride
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23828 xsd:anyURI
+created_by: pg
+creation_date: 2022-08-17T14:47:35Z

**Comment by pgaudet** [comment]
Done in https://github.com/geneontology/go-ontology/commit/6aeffd1d883496cd7781efb520483acd07e78ac0
