### ISSUE TITLE
NTR: [T240 body]

### ISSUE THREAD

**Issue by LiNiMGI** [geneontology/go-ontology#23835]
T240 body:
A multilamellar subcellular structure formed in the cytoplasm of developing neuron composed of Tmem240 and Emd.

Part_Of: cytoplasm GO:0005737
IS_A intracellular membrane-bounded organelle GO:0043231

PMID:32535204. Gene product name: Tmem240

**Comment by pgaudet** [comment]
Looks like this is a new structure - I only find this one paper that mentions this structure.

**Comment by raymond91125** [comment]
Would it be better to use "TMEM240-Body" as the term label, "T240 body" as a synonym?

**Comment by LiNiMGI** [comment]
"TMEM240-Body" as the term label, "T240 body" as a synonym- that sounds good to me, thanks!
