### ISSUE TITLE
synonyms: GO:0008479  queuine tRNA-ribosyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23845]
Please add exact synonyms:  
tRNA guanine transglycosylase 
eTGT 

also , most of the currently "related" seem to be "exact":
guanine, queuine-tRNA transglycosylase activity
tRNA-guanine transglycosylase activity
tRNA guanine transglycosidase activity
queuine transfer ribonucleate ribosyltransferase activity

or broad:
tRNA transglycosylase activity

or odd
guanine insertion enzyme activity?

**Comment by hdrabkin** [comment]
done
