### ISSUE TITLE
NTR - Queuosine nucleosidase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23846]
_Please provide as much information as you can:_ 

* **Suggested term label:**

Queuosine nucleosidase activity

* **Definition (free text)**

A queuosine nucleosidase is a purine nucleosidase that cleaves the N-glycosidic bond of queuosine to yield the nucleobase queuine and D-ribose.

(i.e. converts queuosine to queuonine)

* *  **substance metabolic process:** The chemical reactions and pathways involving substance, [description of substance].

purine ribonucleoside catabolic process

* **Reference, in format PMID:#######**

PMID:35940128

Queuosine salvage in fission yeast by Qng1-mediated hydrolysis to queuine.

Patel BI, Heiss M, Samel-Pommerencke A, Carell T, Ehrenhofer-Murray AE

* **Gene product name and ID to be annotated to this term**

https://www.pombase.org/gene/SPAC589.05c

* **Parent term(s)**

GO:0008477 | purine nucleosidase activity

* **Any other information**

requested by Ann Ehrenhofer-Murray

* **FOR ONTOLOGY EDITOR**

* **Logical definition**
* *  **substance metabolic process:**
'metabolic process'
 and ('has primary input or output' some [substance]
* * **substance biosynthetic process:**
'biosynthetic process'
 and ('has primary output' some [substance].
* * **substance catabolic process:**
'catabolic process'
 and ('has primary output' some [substance] 

* **Standard synonyms**
* *  **substance metabolic process:**
* * * EXACT: substance metabolism
* * **substance biosynthetic process:** 
* * * EXACT: substance anabolism
* * * EXACT: substance biosynthesis
* * * EXACT: substance formation
* * * EXACT: substance synthesis

* * **substance catabolic process:**    
* * * EXACT: substance breakdown
* * * EXACT: substance catabolism
* * * EXACT: substance degradation

**Comment by ValWood** [comment]
synonym , exact
Queuosine Nucleoside Glycosylase
tRNA Queuosine Nucleoside Glycosylase

**Comment by hdrabkin** [comment]
A queuosine nucleosidase is a purine nucleosidase that cleaves the N-glycosidic bond of queuosine to yield the nucleobase queuine and D-ribose.

Catalysis of the reaction: a N-D-queuosine + H2O = queuine + D-ribose.

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106432
+name: queuosine nucleosidase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: a N-D-queuosine + H2O = queuine + D-ribose." [PMID:35940128]
+synonym: "queuosine nucleoside glycosylase" EXACT []
+synonym: "tRNA queuosine nucleoside glycosylase" EXACT []
+is_a: GO:0008477 ! purine nucleosidase activity
+property_value: creation_date 2022-08-17T17:39:10Z xsd:dateTime
+created_by: hjd

**Comment by ValWood** [comment]
wow speedy, thanks Harold!

**Comment by hdrabkin** [comment]
Not yet val; having issues with the commit (new token). hope I dont' have to redo ; I'll let you know when

**Comment by hdrabkin** [comment]
Ok this term is good to GO
