### ISSUE TITLE
NTR: histone H3R26 methyltransferase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#23851]
Please provide as much information as you can: 

* **Suggested term label:**
histone H3R26 methyltransferase activity

* **Definition (free text)**
standard

* **Reference, in format PMID:#######**
 17882261

* **Gene product name and ID to be annotated to this term**
* Q9WVG6 Carm1 prmt4

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+name: histone H3R26 methyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: S-adenosyl-L-methionine + (histone H3)-arginine (position 26) = S-adenosyl-L-homocysteine + (histone H3)-N-methyl-arginine (position 26). This reaction is the addition of a methyl group to the arginine residue at position 26 of histone H3." [PMID:17882261]
+synonym: "histone H3R26 arginine methyltransferase activity" EXACT [GOC:mah]
+synonym: "histone methylase activity (H3-R26 specific)" EXACT []
+synonym: "histone methyltransferase activity (H3-R26 specific)" EXACT []
+synonym: "histone-arginine N-methyltransferase activity (H3-R26 specific)" EXACT []
+synonym: "histone-H3R26 methyltransferase activity" EXACT []
+is_a: GO:0008469 ! histone arginine N-methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23851 xsd:anyURI
+created_by: pg
+creation_date: 2022-08-18T13:56:32Z
