### ISSUE TITLE
Change label 'ovarian follicle cell ' ->  'follicle cell of egg chamber'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23870]
Related to #22603

'ovarian follicle cell development' <http://purl.obolibrary.org/obo/GO_0030707>
'ovarian follicle cell migration' <http://purl.obolibrary.org/obo/GO_0007297>
'ovarian follicle cell stalk formation' <http://purl.obolibrary.org/obo/GO_0030713>
'ovarian follicle cell-cell adhesion' <http://purl.obolibrary.org/obo/GO_0007299>

Need to be renamed  to align with CL 'follicle cell of egg chamber' x
 https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000477

**Comment by raymond91125** [comment]
Wouldn't we update CL import first? @balhoff

**Comment by pgaudet** [comment]
You can go ahead with the change in labels, the logical definitions will automatically fix when we reload CL.

**Comment by balhoff** [comment]
CL is updated now.

**Comment by raymond91125** [comment]
Thanks. @balhoff
