### ISSUE TITLE
Changes to 'GO:0015454 light-driven active transmembrane transporter activity' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23876]
From @sjm41 

> Proteins like bacteriorhodopsin & halorhodopsin (members of 3.E.1) are the best characterised and are described as “light driven ion pumps” (e.g. PMID: [26442282](https://pubmed.ncbi.nlm.nih.gov/26442282/), [23994288](https://pubmed.ncbi.nlm.nih.gov/23994288/)), pumping protons or chloride ions.

> I don’t think “ion pumping" is defined as “catalysis” in the GO, is it?

> Maybe this means the "light-driven active transmembrane transporter activity” GO term should:
- be moved from its current location in the GO and become a child of "GO:0022853 active ion transmembrane transporter activity
- have its definition changed to say ‘ion’ rather than ’solute’, and remove references of “primary active transport/catalysis"

> There are no current annotations using this term, though it looks like the bacteriorhodopsin & halorhodopsin proteins could/should have it applied.

**Comment by pgaudet** [comment]
+ obsolete [GO:0015989 light-driven proton transport](http://amigo.geneontology.org/amigo/term/GO:0015989#display-lineage-tab) -> no annotations. Represents a MF

**Comment by sjm41** [comment]
Thanks!

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0015989 light-driven proton transport'. The reason for obsoletion is that this term represents a molecular function. There are no annotations or mappings to this term; this term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/23876

Thanks, Pascale
