### ISSUE TITLE
GO:0140826 zinc:proton antiporter activity change definition or create a new term

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#23874]
Hi,
https://www.rhea-db.org/rhea/72627 describes an electroneutral antiporter activity as described see PubMed=30893306. The stoichiometry is different compared to https://www.rhea-db.org/rhea/28839 which is not electroneutral as there is only one proton exchanged. Should we change the definition and add cross-references to GO:0140826 zinc:proton antiporter activity or create a new term?
Thanks, Lionel

**Comment by pgaudet** [comment]
After discussion with @lbreuza , since GO does not capture stochiometry, I will add the other RHEA as a xref

**Comment by pgaudet** [comment]
Added comment 'Some transporters exchange 1 H+ for a Zn2+ while others are electroneutral and exchange 2 H+.' and added both RHEAs as narrowMatch.
