### ISSUE TITLE
Import latest Uberon and CL releases

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#23871]
Incompatibilities with these should have been resolved since incoherencies we had earlier this year. @kltm we'll need to coordinate this with the golr load I think.

**Comment by kltm** [comment]
@balhoff That would be:
https://github.com/geneontology/pipeline/issues/291
https://github.com/geneontology/pipeline/issues/290

**Comment by pgaudet** [comment]
@balhoff 
Is this done?

**Comment by balhoff** [comment]
Yes.
