### ISSUE TITLE
GO:0006488 | dolichol-linked oligosaccharide biosynthetic process parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23885]
* **PTHR ID & PTN node:**

dpm1 | GO:0019348 | dolichol metabolic process | IBA with PTN000092440 , O60762 , 1310120 , MGI:1330239 | Gaudet P et al. (2011)

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPAC31G5.16c

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

I annotated to 
GO:0006488 | dolichol-linked oligosaccharide biosynthetic process

which seems to be correct. 

OR should  GO:0006488 | dolichol-linked oligosaccharide biosynthetic process be a descendant of 

GO:0019348 | dolichol metabolic process

**Comment by ValWood** [comment]
@pgaudet  what do you think about this parent? I can take this if you agree.

**Comment by ValWood** [comment]
ACTION: GO:0006488 | dolichol-linked oligosaccharide biosynthetic process should be a descendant of GO:0019348 | dolichol metabolic process.

**Comment by pgaudet** [comment]
Sorry I just saw this one: 

> ACTION: GO:0006488 | dolichol-linked oligosaccharide biosynthetic process should be a descendant of GO:0019348 | dolichol metabolic process.

Normally the logical definitions (or ChEBI) should be doing this work, it's always a bit suspicious to have to add asserted statements. 

In this case, isn't 
* dolichol metabolic process >> the metabolism of dolichol
* dolichol-linked oligosaccharide biosynthetic process >> the synthesis of some oligosaccharide, that happpens to be dolichol-linked? What are you trying to capture? Isn't dolichol the substrate?

**Comment by ValWood** [comment]
right, got it, you can close this. But a lot of the annotations to this dolichol-linked  term seem to be the synthesis of the dolichol part (I  ISS'd most of them from SGD). I'll remove the dolichol ones.
