### ISSUE TITLE
new children of "cytosolic ribosome assembly"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23886]
Follow on from
https://github.com/geneontology/go-ontology/issues/11517

We should have

cytosolic ribosome small subunit assembly
and 
cytosolic ribosome large subunit assembly

underneath cytosolic ribosome  assembly

**Comment by pgaudet** [comment]
I dont find these terms - only 

<img width="389" alt="image" src="https://user-images.githubusercontent.com/4782928/187635609-a62aa4e3-1b03-478c-a091-63f9a82dd782.png">

so this seems right?

**Comment by ValWood** [comment]
Sorry those were new term requests (not clear). The problem is , because we have these 2 terms:

<img width="988" alt="Screenshot 2022-08-31 at 13 22 51" src="https://user-images.githubusercontent.com/7359272/187677532-35c8c3aa-af55-435a-819c-b8fc72520a25.png">

so unless we have cytosolic equivalents we will not be able to get the resolution between cytosolic and mitochondrial. Note that these term it should be clear that the assembly does not all occur in the cytosol.

I don't think we need equivalent small and large subunit assembly terms for mitochondrial because we don't have such resolution- there seems to be very few papers. I only have 4 genes annotated to assembly.
It might be OK to repurpose. the existing small and large subunit assembly terms as cytosolic (I know it is bad practice but it would dave a lot of work)

**Comment by ValWood** [comment]
we cant repurpose, a lot of the annotations are bacterial.

**Comment by ValWood** [comment]
Any objection if I add these terms,  with do_not_annotate flags for the parents which do not specify mitochondrial or cytosolic?
Or could we rename the term here if it os only used for cytosolic?

**Comment by ValWood** [comment]
It's a completely different (but largely unknown) process.   I can't see any overlap in the genes involved, but in GO currently they are all lumped in one bag, which is  difficult for those studying mitochondrial gene expression.

mitochondrial ribosome assembly has more in common processually with mitochondrial translation than with cytosolic ribosome assembly, so I would like to be able to link these modules

mitochondrial ribosome assembly-> (upstream of) mitochondrial translation 
which is difficult to do with extensions (the class will bring in all non mitochondrial assembly)

Note that I see annotations transferred by PAINT from cytosolic ribosomal proteins to mitochondrial ribosomal proteins  but these should be removed.

**Comment by pgaudet** [comment]
ok sound good, please go ahead

**Comment by ValWood** [comment]
1. Added
+[Term]
+id: GO:0180023
+name: cytosolic large ribosomal subunit assembly
+def: "The aggregation, arrangement and bonding together of a set of components to form a cytosolic large ribosomal subunit." [PMID:30467428]
+intersection_of: GO:0022607 ! cellular component assembly
+intersection_of: results_in_assembly_of GO:0022625 ! cytosolic large ribosomal subunit
+relationship: part_of GO:0042256 ! cytosolic ribosome assembly
+property_value: creation_dat "2023-11-03T16:06:38Z" xsd:dateTime
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/23886" xsd:anyURI
+created_by: vw

+[Term]
+id: GO:0180025
+name: cytosolic small ribosomal subunit assembly
+def: "The aggregation, arrangement and bonding together of a set of components to form a cytosolic small ribosomal subunit." [PMID:30467428]
+is_a: GO:0000028 ! ribosomal small subunit assembly
+intersection_of: GO:0022607 ! cellular component assembly
+intersection_of: results_in_assembly_of GO:0022627 ! cytosolic small ribosomal subunit
+relationship: part_of GO:0042256 ! cytosolic ribosome assembly
+property_value: creation_dat "2023-11-03T16:22:03Z" xsd:dateTime
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/23886" xsd:anyURI
+created_by: vw

+[Term]
+id: GO:0180026
+name: mitochondrial small ribosomal subunit assembly
+def: "The aggregation, arrangement and bonding together of a set of components to form a mitochondrial small ribosomal subunit." [] {def="PMID:30467428"}
+is_a: GO:0000028 ! ribosomal small subunit assembly
+intersection_of: GO:0022607 ! cellular component assembly
+intersection_of: results_in_assembly_of GO:0005763 ! mitochondrial small ribosomal subunit
+relationship: part_of GO:0061668 ! mitochondrial ribosome assembly
+property_value: creation_dat "2023-11-03T16:24:18Z" xsd:dateTime
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/23886" xsd:anyURI
+created_by: vw

2. Addfed logical defs to match existing

3. Made the parents
GO:0000028  ribosomal small subunit assembly
GO:0000027  ribosomal large subunit assembly 
(this axis of classification could eventually be removed , it is more important to separate cytosolic and mitochondrial gene expression than large and small subunits of different compartments

4. 90S pre ribosome assembly
Was part of both large and small ribosome subunit assembly
Removed and replaced with just "cytosolic..."

5. made Small-subunit processor assembly
part of "cytosolic small"

6. Found  GO:1902626   assembly of large subunit precursor of preribosome
Add missing parent
part_of "ribosome large subunit assembly"
(Probably this should be cytosolic?)



not for direct annotation

**Comment by ValWood** [comment]
before.
<img width="604" alt="Screenshot 2023-11-03 at 17 05 46" src="https://github.com/geneontology/go-ontology/assets/7359272/6c7f2089-8fc9-481c-ab0e-54ead9bfc0af">


double check after
[ribosome_basket.txt](https://github.com/geneontology/go-ontology/files/13252924/ribosome_basket.txt)
