### ISSUE TITLE
Proposal for side of x membrane

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23880]
* 'cytoplasmic side of membrane': OBSOLETE 11 EXP
* 'lumenal side of membrane': OBSOLETE : 1 EXP

**Proposal: change labels to** 
* 'cytoplasmic side of apical plasma membrane' -> cytosol adjacent to apical plasma membrane -> 30 EXP
* 'cytoplasmic side of dendritic spine plasma membrane' -> cytosol adjacent to dendritic spine plasma membrane -> single annotation (RGD), consistent with new label 
* 'cytoplasmic side of early endosome membrane' -> cytosol adjacent to early endosome membrane
* 'cytoplasmic side of endoplasmic reticulum membrane' -> cytosol adjacent to endoplasmic reticulum membrane
* 'cytoplasmic side of endosome membrane' -> cytosol adjacent to endosome membrane
* 'cytoplasmic side of Golgi membrane' -> cytosol adjacent to Golgi membrane
* 'lumenal side of Golgi membrane' -> Golgi lumen adjacent to Golgi membrane
* 'cytoplasmic side of late endosome membrane' -> cytosol adjacent to late endosome membrane
* 'cytoplasmic side of lysosomal membrane' -> cytosol adjacent to lysosomal membrane
 * 'cytoplasmic side of mitochondrial outer membrane' -> cytosol adjacent to mitochondrial outer membrane
* 'cytoplasmic side of plasma membrane' -> cytosol adjacent to plasma membrane
* 'cytoplasmic side of rough endoplasmic reticulum membrane' -> cytosol adjacent to rough endoplasmic reticulum membrane
* 'cytoplasmic side of smooth endoplasmic reticulum membrane' -> cytosol adjacent to  smooth endoplasmic reticulum membrane
* 'cytoplasmic side of trans-Golgi network transport vesicle membrane' -> cytosol adjacent to trans-Golgi network transport vesicle membrane
* 'cytoplasmic side of transport vesicle membrane' -> cytosol adjacent to transport vesicle membrane
* 'external side of cell outer membrane' -> extracellular region adjacent to cell outer membrane
* 'external side of mycolate outer membrane' -> cytosol adjacent to mycolate outer membrane
* 'external side of plasma membrane' -> extracellular region adjacent to plasma membrane (space??) 
* 'external side of apical plasma membrane' -> extracellular region adjacent to apical plasma membrane
* 'periplasmic side of plasma membrane' -> periplasmic space adjacent to plasma membrane
* 'internal side of mycolate outer membrane'   -> 
* 'lumenal side of early endosome membrane' -> endosome lumen adjacent to early endosomal membrane
* 'lumenal side of endosome membrane'  -> endosome lumen adjacent to early endosomal membrane 

* 'lumenal side of endoplasmic reticulum membrane'  -> endoplasmic reticulum lumen adjacent to endosomal membrane
* 'lumenal side of late endosome membrane'  -> 
* 'lumenal side of lysosomal membrane'  -> 
* 'lumenal side of membrane''lumenal side of plastid thylakoid membrane'  -> 
* 'lumenal side of membrane''lumenal side of rough endoplasmic reticulum membrane'  -> 
* 'lumenal side of membrane''lumenal side of smooth endoplasmic reticulum membrane'  -> 
* 'lumenal side of membrane''lumenal side of trans-Golgi network transport vesicle membrane'  -> 
* 'lumenal side of membrane''lumenal side of transport vesicle membrane'  -> 
* 'lumenal side of membrane''lumenal side of trans-Golgi network transport vesicle membrane'  -> 
* 'lumenal side of membrane''matrix side of mitochondrial inner membrane'  -> 
* 'lumenal side of membrane''periplasmic side of cell outer membrane'  -> 
* 'lumenal side of membrane''stromal side of plastid inner membrane'  -> 
* 'lumenal side of membrane''stromal side of plastid thylakoid membrane'  ->

**Comment by ValWood** [comment]
Q will these terms still be children of "membrane"?  because the existing terms were children of membrane I have used for membrane attached proteins, located on a specific side of a membrane (usually lipid anchored etc).

**Comment by pgaudet** [comment]
Thanks for pointing that out; I think these terms indeed mean that the proteins are somehow in the membrane (at least anchored); so, yes, they would remain children of membrane. Is this consistent with all annotations?

**Comment by ValWood** [comment]
so in this image
https://user-images.githubusercontent.com/4782928/33712835-27722394-db49-11e7-9752-078a6abdd7cb.png
I would annotate 
beta 2AR, alpha, and gamma subunits to membrane.
I might also annotate additional complex subunits if they were part of the. same "functional unit" like a transport 
or adaptor (I am not sure about this I would need to check). I  would not annotate the proteins they recruited to perform some other activity, or connect to other cortical structures (for example).

**Comment by hattrill** [comment]
I was specifiically thinking of those to be labelled "cytosol adjacent to x" would be classed as cytosolic not membrane? vs the annotation of proteins which are anchored - which would be classed as in the membrane.

**Comment by ValWood** [comment]
In this case  "cytosol adjacent to x"  would be equivalent to "cell cortex"

The region of a cell that lies just beneath the plasma membrane and often, but not always, contains a network of actin filaments and associated proteins.

**Comment by hattrill** [comment]
Yes....for PM that would be the case. But for the organelles...

**Comment by ValWood** [comment]
That would be useful. I somehow missed this proposal. I knew it was on the cards, but I did not seem to be tagged in. any tickets.

**Comment by pgaudet** [comment]
I think we decided to stick with the current terms. OK @ValWood ?

**Comment by ValWood** [comment]
OK for me.
