### ISSUE TITLE
fatty acid elongation terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23896]
Please provide as much information as you can:

* **GO term ID and Label**

It seems like these elongation process terms should instead be more specific  MF "fatty acid elongase activity'  terms instead?

<img width="847" alt="Screenshot 2022-08-25 at 19 53 49" src="https://user-images.githubusercontent.com/7359272/186745957-99478aba-8868-4cf4-9849-9c7ea37b576d.png">

**Comment by deustp01** [comment]
@hdrabkin @ukemi What do we men by elongation? Isn't the entire sequence of ~5 molecular functions by which a 2-carbon unit is added to a fatty acid and reduced to generate as the final product a fatty acid 2 carbons longer than the starting one? And there are variations in this sequence, enabled by alternative gene products, to yield various specific j=kinds of unsaturarion?

Or am I misunderstanding the request here?

**Comment by hdrabkin** [comment]
These are not single-step processes as you point out.  5 steps each. (5 MFs).

**Comment by ValWood** [comment]
OK! are they all steps performed by the elongase?

**Comment by deustp01** [comment]
> OK! are they all steps performed by the elongase?

That depends on the taxon. In textbook bacteria, each function is enabled by a different gene product. In textbook eukaryotes (vertebrates, but also including yeasts, I think) a single multidomain gene product uses its various domains to enable the reaction sequence, and because the reaction intermediates are physically tethered to the elongase all of this can be done very efficiently.

**Comment by ValWood** [comment]
Of couse, it's multi-domain.

It still seems a little odd to me to have  the saturation status in the process term.

rather than
"MF fatty acid synthase step " involved in lipoic/ palmitic or whatever fatty acid- the saturation status  seems slightly orthogonal.

**Comment by hdrabkin** [comment]
Each step is a separate go activity; the difference is that they are all carried out by  one gene product  vs several. 
A process is a collection of MFs with a specific goal.

**Comment by alanbridge** [comment]
Hi, 

I'm out the office at the moment, but you might try checking this with Lucila Aimo, I will drop her a line. Humans have 7 elongases, ELOVL1- ELOVL7, and each has a very well defined specificity, both in terms of the pattern and degree of saturation of their substrates, and the length to which they elongate. Each is associated with specific tissues and in some cases diseases.

These elongases add the 2 carbon units, creating an oxo-acyl-FA, e.g.:

https://www.rhea-db.org/rhea/32727 - a very-long-chain acyl-CoA + H+ + malonyl-CoA = a very-long-chain 3-oxoacyl-CoA + CO2 + CoA

 which is then reduced and saturated by other enzymes: 

https://www.rhea-db.org/rhea/48680 - a very-long-chain (3R)-3-hydroxyacyl-CoA + NADP(+) = a very-long-chain 3-oxoacyl-CoA + H(+) + NADPH (read R->L)
https://www.rhea-db.org/rhea/45812 - a very-long-chain (3R)-3-hydroxyacyl-CoA = a very-long-chain (2E)-enoyl-CoA + H2O (read L->R)
https://www.rhea-db.org/rhea/14473 - a very-long-chain 2,3-saturated fatty acyl-CoA + NADP(+) = a very-long-chain (2E)-enoyl-CoA + H(+) + NADPH (read R->L)

All the best, Alan

**Comment by alanbridge** [comment]
NB: different species have different FAs, e.g. yeast don't make PUFAs, only SFAs and MUFAs.

**Comment by aimol** [comment]
Hi, that is correct @alanbridge, elongases catalyze the first reaction of the 4 reactions that constitute the fatty acid elongation cycle, and they may have different specificities, for example human ELOVL1 prefers saturated and monounsaturated fatty acids, while human ELOVL2 prefers polyunsaturated fatty acids as substrates.

**Comment by ValWood** [comment]
thanks @alanbridge  So we should add a 'never in yeast' taxon restriction to 
GO:0034626  fatty acid elongation, polyunsaturated fatty acid?
