### ISSUE TITLE
NTR: [zinc ion import into mitochondrion]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#23890]
Please provide as much information as you can: 

* **Suggested term label:**
zinc ion import into mitochondrion

* **Definition (free text)**
The directed movement of Zn2+ ions from the cytoplasm into mitochondrion.

* **Reference, in format PMID:#######**
PubMed=21289295

* **Gene product name and ID to be annotated to this term**
Slc30a2 mouse

* **Parent term(s)**
GO:0062111 zinc ion import into organelle

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140917
+name: zinc ion import into mitochondrion
+namespace: biological_process
+def: "The directed import of zinc(2+) from the cytosol, across an organelle membrane, into a mitochondrion." [PMID:21289295]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_primary_input CHEBI:29105 ! zinc(2+)
+intersection_of: has_target_end_location GO:0005759 ! mitochondrial matrix
+intersection_of: has_target_start_location GO:0005829 ! cytosol
+intersection_of: results_in_transport_across GO:0005743 ! mitochondrial inner membrane
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23890 xsd:anyURI
+created_by: pg
+creation_date: 2022-09-23T07:01:26Z
+
