### ISSUE TITLE
NTR: [zinc ion import into lysosome]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#23907]
Please provide as much information as you can: 

* **Suggested term label:**
zinc ion import into lysosome

* **Definition (free text)**
The directed movement of zinc ions from the cytoplasm into lysosomes.

* **Reference, in format PMID:#######**
PubMed=25808614

* **Gene product name and ID to be annotated to this term**
SLC30A2 human

* **Parent term(s)**
GO:0062111 zinc ion import into organelle

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140916
+name: zinc ion import into lysosome
+namespace: biological_process
+def: "The directed import of zinc(2+) from the cytosol, across an organelle membrane, into a lysosome." [PMID:25808614]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_primary_input CHEBI:29105 ! zinc(2+)
+intersection_of: has_target_end_location GO:0043202 ! lysosomal lumen
+intersection_of: has_target_start_location GO:0005829 ! cytosol
+intersection_of: results_in_transport_across GO:0005765 ! lysosomal membrane
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23907 xsd:anyURI
+created_by: pg
+creation_date: 2022-09-23T06:58:57Z
