### ISSUE TITLE
NTR: [zinc ion import into zymogen granule]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#23908]
Please provide as much information as you can: 

* **Suggested term label:**
zinc ion import into zymogen granule

* **Definition (free text)**
The directed movement of zinc ions from the cytoplasm into zymogen granule.

* **Reference, in format PMID:#######**
PubMed=20133611

* **Gene product name and ID to be annotated to this term**
Slc30a2 rat

* **Parent term(s)**
GO:0062111 zinc ion import into organelle

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140915
+name: zinc ion import into zymogen granule
+namespace: biological_process
+def: "The directed import of zinc(2+) from the cytosol, across an organelle membrane, into a zymogen granule." [PMID:20133611]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_primary_input CHEBI:29105 ! zinc(2+)
+intersection_of: has_target_end_location GO:0042588 ! zymogen granule
+intersection_of: has_target_start_location GO:0005829 ! cytosol
+intersection_of: results_in_transport_across GO:0042589 ! zymogen granule membrane
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23908 xsd:anyURI
+created_by: pg
+creation_date: 2022-09-23T06:57:52Z
