### ISSUE TITLE
Term merge: RAD51C-XRCC3 complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23911]
* **Term to be merged: Provide GO ID and term label**

<img width="967" alt="Screenshot 2022-08-29 at 19 39 45" src="https://user-images.githubusercontent.com/7359272/187274245-cfd4c3c9-e4d9-4d00-8b86-4936b15b6091.png">

* **Reason for merge**

These 2 complexes appear to be the same.

**Comment by ValWood** [comment]
ignore

**Comment by ValWood** [comment]
pombe Rhp55= S. cerevisiae Rad55(we call it rad55 now) = human Rad51C
rhp57= human XRCC3

I suggest merge and keep the human name.

**Comment by raymond91125** [comment]
@ValWood Could you attach a ref? AGR does not show S. cerevisiae Rad55 = human Rad51C. Thanks.

**Comment by ValWood** [comment]
https://www.pombase.org/gene/SPAC3C7.03c
see ortholog section.
Confirmed by Panther
and orthofinder

**Comment by ValWood** [comment]
https://pubmed.ncbi.nlm.nih.gov/9469824/

and https://pubmed.ncbi.nlm.nih.gov/12427746/
" By analogy to the yeast Rad55 and Rad57, our results suggest that Rad51B and Rad51C function through interactions with the human Rad51 recombinase and play a crucial role in the homologous recombinational repair pathway."

rad57= XRCC3
rad55=rad51C (and B)
