### ISSUE TITLE
obsolete GO:1990920    proteasome localization to nuclear periphery

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23921]
Please provide as much information as you can:

* **GO term ID and Label**
GO:1990920    proteasome localization to nuclear periphery

* **Reason for deprecation**

I think we can get rid of this term while it has no annotations.
This is a term originally requested by PomBAse (I think?) but we now represent this with MF teethering term

* **Are there annotations to this term?**
- How many EXP:

No annotations, any. evidence code

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been  made to obsolete GO:1990920 proteasome localization to nuclear periphery. The reason for obsoletion is that this is now represented by a molecular function, 'GO:1990919 proteasome-nuclear membrane anchor activity'. There are no annotations or mappings to this term; this term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/23921

Thanks, Pascale
