### ISSUE TITLE
merge centromemre repeat terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23924]
GO:0062199   chromosome, centromeric inner repeat region (no annotations)
no annotations. 

and
GO:0034507   chromosome, centromeric outer repeat region
3 pombe annotations

can merge into GO:0005721 pericentric heterochromatin 
(these repeat regions are heterochromatin markers, but they don't need to be in GO, we have SO terms for the repeat regions).

**Comment by pgaudet** [comment]
Likewise, it seems
 GO:0000775 chromosome, centromeric region
and GO:0034506 chromosome, centromeric core domain refer to the same structure?

**Comment by pgaudet** [comment]
see also #21371

**Comment by ValWood** [comment]
I don't think so,.

GO:0000775 chromosome, centromeric region is the entire centromere (core and pericentromeric).

**Comment by pgaudet** [comment]
OK this is done
