### ISSUE TITLE
NTR: [Protein dislocase activity]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#23926]
Hi GO,

I would need a a new GO term regarding protein dislocase activity mediated by PEX1-PEX6 and p97 (VCP, CDC48) 

Name: Protein dislocase activity
Definition: The activity of removing a protein from a membrane and releasing it from the hydrophobic region of one or both lipid bilayers. The reaction is driven by ATP hydrolysis.

child of GO:0140318 protein transporter activity
child of GO:0140657 ATP-dependent activity
parent of GO:0140567 transmembrane protein dislocase activity
PMID:29884772
PMID:31249135

Thanks

Sylvain

**Comment by pgaudet** [comment]
Should we repurpose GO:0140567 transmembrane protein dislocase activity
and wider its definition? It seems to me it's the same activity, whether the substrate is transmembrane or not ?

**Comment by sylvainpoux** [comment]
Exactly. The only thing is that there is a Rhea for the GO:0140567 transmembrane protein dislocase activity
Sylvain

**Comment by hdrabkin** [comment]
We could make the RHEA a narrowMatch

**Comment by edwong57** [comment]
Should I also add 'transmembrane protein dislocase activity' as a synonym?

**Comment by pgaudet** [comment]
Yes sounds good!  - Narrow synonym?
