### ISSUE TITLE
Catalytic reaction directionality

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23923]
Hi, 

We have > 700 cases where a definition uses "<=>" rather than just = in a definition, see https://docs.google.com/spreadsheets/d/12LsYSzR1vqZwzBQvUjIXl6vU-0UiUgFf_kILtkL5EGQ/edit#gid=0

I dont think this is intentional? Or are there cases where we should really write that the reaction is bi-directional? 

@hdrabkin @deustp01 @cmungall 
@amorgat @kaxelsen 

Thanks, Pascale

**Comment by hdrabkin** [comment]
With that many, I don't think it's intentional.  I seem to remember that we decided that the default was '=' (non-directional) unless there was a strong reason to use anything else.

**Comment by deustp01** [comment]
> we decided that the default was '=' (non-directional) unless there was a strong reason to use anything else

Note the distinction between non-directional (agnostic as to direction) and bi-directional (asserting that the reaction is freely reversible). Non-directional is what I remember too, from the 2018 Geneva meeting. At that point we also imagined that when a GO MF term and its associated Rhea reaction is associated with a biological process / pathway, the pathway context would provide a direction for the reaction.

**Comment by pgaudet** [comment]
See also #19371
I think this is saying essentially the same thing, although it concludes that we need directionality for 
GO:0004618 phosphoglycerate kinase activity - but in fact that would be captured in the model - right @deustp01 ?

**Comment by deustp01** [comment]
To get all scholarly and theoretical, all chemical reactions are reversible: given enough moles of phosphoprotein, ADP, and patience, some bit of protein + ATP will form. To get realistic and practical, our scope is biology and under those conditions, the reaction enables by GO:0004618 phosphoglycerate kinase activity goes only in one direction (likewise protein phosphorylation with ATP consumtoopn and protein dephosphoylation with water consumption to form plain protein plus phosphate).

There are some exceptions, which are rare enough to get mentioned in textbooks and we should try to respect those, I think. I don't see how to do this except by manual curation both for ontology development and for annotating specific processes. Examples of physiologically reversible reactions are the steps of glycolysis / gluconeogenesis, where an enzyme (e.g. aldolase) catalyzes a reaction that is reversible under physiological conditions, and is driven in a particular direction in any specific tissue / physiological state by mass action: when a normal liver cell is carrying out glycolysis in the well-fed physiological state, there is abundant fructose 1,6-bisphosphate and trioses are rapidly removed by following reactions so aldolase catalyzes triose formation. In the starved state, the reverse is true and abundant trioses react to form rapidly removed fructose 1,6-bisohosphate.

Transamination reactions as a class almost all fall into this "freely reversible - direction determined by physiological state" class as well.

So we (rarely) need the <=> form of a reaction when we are annotating one of these reactions without regard to context. When the reaction is part of a process, the process will impose a => or <= direction on it, and meanwhile the form associated with a GO MF definition should be = , by defaulr.

Apologies for the oration. @ukemi @hdrabkin care to pile on?

**Comment by pgaudet** [comment]
Removed the reaction directionality 

FYI @sjm41 @raymond91105 @ValWood @edwong57 

Unless there is a strong case to keep reaction directionality, we use "=" in reactions, and not "<=>". 

I removed all instances of <=> since there was no specific case mentioned when someone wanted to keep the bidirectionality, because for all the reactions I looked at, this was added in error. 

Thanks, Pascale
