### ISSUE TITLE
NTR: centrosomal core

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#23933]
Please provide as much information as you can: 

* **Suggested term label:**
* centrosomal core

* **Definition (free text)**
The core region of the centrosome, a layered structure containing proteins, surrounded by the centrosomal corona. The core duplicates once per cell cycle at the G2/M transition when two outer layers form the mitotic spindle poles.

* **Reference, in format PMID:#######**
* PMID:28104305

* **Gene product name and ID to be annotated to this term**
* cepA / DDB_G0292142
* cepD / DDB_G0283111
* cepE / DDB_G0275495

* **Parent term(s)**
* GO:0005813: centrosome

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
* none

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
* 'centrosomal corona' has been added  and is not only used by Dicty. It would be logical to also add 'centrosomal core'. The def is somewhat from Dicty paper feel free to more generalize.

**Comment by pgaudet** [comment]
Hi Petra, 

We probably need to update the definition of the parent to include this structure - right now     GO:0005813 centrosome is defined as "A structure comprised of a core structure (in most organisms, a pair of centrioles) and peripheral material (...)" 

Is the centrosome core synonymous with GO:0005814 centriole ? or is GO:0005814 centriole a type of centrosomal core? 

Thanks, Pascale

**Comment by pfey03** [comment]
Hi Pascale,

Dicty has no centrioles. 
https://pubmed.ncbi.nlm.nih.gov/?term=Dictyostlium+AND+centriole

Dicty has a semi closed mitosis and  a cylindrical3 -layered core with all proteins of core and envelope known. 

Maybe 'centriole' can be a child of 'centrosomal core' and centriole taxon restricted to exclude Dicty and maybe others.

**Comment by ValWood** [comment]
you might wish to mirror the SPB terms


GO:0005824    outer plaque of spindle pole body 
GO:0005825    half bridge of spindle pole body 
GO:0005821    intermediate layer of spindle pole body 
GO:0005822    inner plaque of spindle pole body

but increasingly fungal biologists refer to the spindle pole body as the centrosome (they are analogous), so perhaps they should be merged?
https://pubmed.ncbi.nlm.nih.gov/34133218/
[Orderly assembly underpinning built-in asymmetry in the yeast centrosome duplication cycle requires cyclin-dependent kinase.](https://pubmed.ncbi.nlm.nih.gov/32851976/)
Geymonat M, Peng Q, Guo Z, Yu Z, Unruh JR, Jaspersen SL, Segal M.

[Yeast pericentrin/Spc110 contains multiple domains required for tethering the γ-tubulin complex to the centrosome.](https://pubmed.ncbi.nlm.nih.gov/32374651/)
Alonso A, Fabritius A, Ozzello C, Andreas M, Klenchin D, Rayment I, Winey M.

 
[Synthetic Physical Interactions with the Yeast Centrosome.](https://pubmed.ncbi.nlm.nih.gov/31076383/)
Howell RSM, Csikász-Nagy A, Thorpe PH.
G3 (Bethesda). 2019 Jul 9;9(7):2183-2194. doi: 10.1534/g3.119.400117.

[Structure and function of Spc42 coiled-coils in yeast centrosome assembly and duplication.](https://pubmed.ncbi.nlm.nih.gov/30969903/)
Drennan AC, Krishna S, Seeger MA, Andreas MP, Gardner JM, Sether EKR, Jaspersen SL, Rayment I.
Mol Biol Cell. 2019 Jun 1;30(12):1505-1522. doi: 10.1091/mbc.E19-03-0167. Epub 2019 Apr 10.
PMID: 30969903

It is after all a founding principle of GO to represent the same structure in different species with the same term.

**Comment by pfey03** [comment]
In Dicty nobody talks about spindle pole body, they talk about centrosomes. The core duplicates once per cell cycle at the G2/M transition when two outer layers of the core form the mitotic spindle poles.
https://pubmed.ncbi.nlm.nih.gov/28104305/

**Comment by ValWood** [comment]
I am saying that in yeast they increasingly refer to the spindle pole body as the centrosome. So the spindle pole body terms *could* become the required centromere terms.  I believe the multilayered structure and components  largely is analogous.
Would need to run this via SGD, but many recent papers seem to say "centrosome".
It would really help people trying to compare the SPB/centrosome structures between yeast and higher eukaryotes.

I will see if there is a comparative paper. I could also run this by the pombe SPB researchers.

@manulera  any thoughts?

**Comment by pfey03** [comment]
Well, although in Yeast it's inserted in the nuclear envelope the kind of plaque structure of the core seems somewhat similar to Dicty. Maybe in yeast you don't talk about centrosomal core because there's no centrosomal corona as it's mostly embedded in the NE.

Also, the many spindle pole body terms, I don't think we need a term for each of the 3 plaque layers or such. Just the two terms would be awesome for annotations.

**Comment by ValWood** [comment]
I think what you requested is fine. It. seems that the structures are quite different so we would probably need calde-specific terms anyway even if thee labels were merged.

**Comment by pfey03** [comment]
@pgaudet are you planning to add this term 'centrosomal core'? 
Thanks!

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140918
+name: centrosomal core
+def: "The core region of the centrosome, a layered structure containing proteins, surrounded by the centrosomal corona. The core duplicates once per cell cycle at the G2/M transition when two outer layers form the mitotic spindle poles." [PMID:28104305, PMID:30413081]
+synonym: "centrosome core" EXACT []
+is_a: GO:0110165 ! cellular anatomical entity
+relationship: part_of GO:0005813 ! centrosome
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/23933 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-05T10:17:08Z
+

**Comment by pgaudet** [comment]
thanks for the reminder!
