### ISSUE TITLE
GO:0047822 hypotaurine dehydrogenase activity maps to a RHEA term that will be obsoleted

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#23931]
email from @kaxelsen 

> A recent paper (pmid: 32156684) has shown that this activity is catalyzed by FMO1 (Q01740; FMO1_HUMAN) that is classified as EC 1.14.13.8. The corresponding reaction covering hypotaurine is RHEA:69819, H+ + hypotaurine + NADPH + O2 = H2O + NADP+ + taurine
and it is already public.
 
>The EC 1.8.1.3 has been deleted by IUBMB and the corresponding reaction RHEA:17385 has been set to obsolete (will be public in release 2022_05 scheduled for December 7).
 
>Best wishes,
>Kristian

**Comment by pgaudet** [comment]
hypotaurine dehydrogenase activity has no annotations, only the following mappings: 

* EC [1.8.1.3](https://enzyme.expasy.org/EC/1.8.1.3) 
* KEGG_REACTION [R01681](http://www.genome.jp/dbget-bin/www_bget?rn:R01681) 
* MetaCyc [HYPOTAURINE-DEHYDROGENASE-RXN](http://biocyc.org/META/NEW-IMAGE?type=NIL&object=HYPOTAURINE-DEHYDROGENASE-RXN) 
* Reactome  [R-HSA-1655453](https://www.reactome.org/content/detail/R-HSA-1655453) 
* RHEA  [17385](https://www.rhea-db.org/rhea/17385)

**Comment by alanbridge** [comment]
@lbreuza could you please link human FMO1 and https://www.rhea-db.org/rhea/69819 if your team isn't already working on it? thanks!

**Comment by deustp01** [comment]
@pgaudet Will GO:0047822 "hypotaurine dehydrogenase activity" remain a valid GO MF term, suitable to annotate the activity of FMO1 gene product on hypotaurine, now associated with the correct EC number and Rhea reaction, or will a new GO term be necessary?

**Comment by deustp01** [comment]
> Reactome  R-HSA-1655453

... has been revised to match the chemistry of RHEA:69819 and the enzymology described in PMID: 32156684. The revised reaction is visible on the Reactome internal website [here](https://curator.reactome.org/PathwayBrowser/#/R-HSA-1614635&SEL=R-HSA-1655453&PATH=R-HSA-1430728,R-HSA-71291), and will become visible on our public site as part of our December 2022 release. It will be linked to RHEA:69819 at that time.

Note that the reaction is still associated with GO:0047822 "hypotaurine dehydrogenase activity". If that term is replaced by a new one, I will correct the Reactome reaction when the new term is available.

**Comment by pgaudet** [comment]
We can keep the same GO term - I think the important part of the reaction, the conversion of hypotaurine to taurine, is unchanged. 

Thanks, Pascale

**Comment by kaxelsen** [comment]
@pgaudet @deustp01 It is not a good idea to keep the current GO term. It refers to an enzyme (EC 1.8.1.3) that does not exist, and also hints a reaction mechanism that is wrong. A correct GO term would be called: hypotaurine monooxygenase activity.

**Comment by deustp01** [comment]
@pgaudet @ukemi One new GO term or two if we need to distinguish reaction using NADP (RHEA:69819, H+ + hypotaurine + NADPH + O2 = H2O + NADP+ + taurine, as at top of this ticket) from one using NAD (RHEA: 74111 H+ + hypotaurine + NADH + O2 = H2O + NAD+ + taurine - newly created by @kaxelsen). The reference for the term or terms is PMID: 32156684 also from the top of this ticket.
Two terms preserve exact alignment between GO MF and current Rhea; one term captures the fact that the one enzyme so far known to enable the reaction (FMO1 - PMID: 32156684) appears to be able to use either, although the reaction proceeds more efficiently in vitro with NADPH.

**Comment by sjm41** [comment]
FYI, here's how the current GO:0047822 term looks:

id: GO:0047822
name: hypotaurine dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: H+ + hypotaurine + NADPH + O2 = H2O + NADP+ + taurine." [RHEA:69819]
xref: EC:1.14.13.8
xref: MetaCyc:HYPOTAURINE-DEHYDROGENASE-RXN
xref: RHEA:69819
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/23931" xsd:anyURI


Remaining tasks?:
- [ ] Looks like  EC:1.14.13.8 should be changed to be a broadMatch xref on this term (and on GO:0004499 N,N-dimethylaniline monooxygenase activity)
- [ ] Kristian suggested a better name for this term would be "hypotaurine monooxygenase activity"
- [ ] Decide whether a new GO term corresponding to RHEA:74111 is needed at this time - it seems not.

**Comment by balhoff** [comment]
Here's relevant output from my recent boomer run:
![75d379a758aab150a10f2c250a33d00dbd7e34ca50557eeadef3b67bdbb8bbae](https://github.com/geneontology/go-ontology/assets/210210/954c3406-3a01-44ce-913c-9bd123a4ad5a)

@sjm41 I could explain these boomer pictures on the ontology call next Monday (or sooner if you want). Any red or black line indicates there is some sort of xref between those two terms. Boomer tries to create equivalence, subclass, or superclass relations from each xref.

**Comment by pgaudet** [comment]
Fixed EX xref to broad and term label. 
Did not create  RHEA:74111
