### ISSUE TITLE
NTR: histone H3K122 acetyltransferase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#23969]
Please provide as much information as you can: 

* **Suggested term label:**
histone H3K122 acetyltransferase activity

* **Definition (free text)**
 Catalysis of the reaction: acetyl-CoA + histone H3 L-lysine (position 122) = CoA + histone H3 N6-acetyl-L-lysine (position 122). 

* **Reference, in format PMID:#######**
 23415232
* **Gene product name and ID to be annotated to this term**
Q09472 ep300
* **Parent term(s)**

stndard
* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140908
+name: histone H3K122 acetyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: acetyl-CoA + histone H3 L-lysine (position 122) = CoA + histone H3 N6-acetyl-L-lysine (position 122)." [PMID:23415232]
+synonym: "histone acetylase activity (H3-K122 specific)" EXACT []
+synonym: "histone acetyltransferase activity (H3-K122 specific)" EXACT []
+synonym: "histone H3-K122 acetyltransferase activity" EXACT []
+synonym: "histone lysine N-acetyltransferase activity (H3-K122 specific)" EXACT []
+is_a: GO:0010484 ! histone H3 acetyltransferase activity
+created_by: pg
+creation_date: 2022-09-09T07:33:35Z
+
