### ISSUE TITLE
	inositol phosphorylceramide mannosyltransferase activity parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#23995]
I am not sure if the issue here is propagation or ontology
GO:0000030 is not an ancestor of GO:0103064

<img width="1062" alt="Screenshot 2022-09-10 at 17 32 40" src="https://user-images.githubusercontent.com/7359272/189492833-c6dfa8f4-dcc5-4a44-82ca-5532ce816a8f.png">

**Comment by ValWood** [comment]
Catalysis of the transfer of a mannosyl group to an acceptor molecule, typically another carbohydrate or a lipid.

**Comment by hdrabkin** [comment]
I see no reason for GO:0000030 not being  an ancestor of GO:0103064. I'll make the change
