### ISSUE TITLE
telomere cap is not a DNA packaging complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24000]
telomere cap complex (GO:0000782)
has parent
[DNA packaging complex]
it is 'protecting DNA' but it isn't really packaging is it?

although to be fair we should probably just remove
a [DNA packaging complex]
because most of the children have nothing to do with DNA packaging? (i.e NMS,  Ndc80 single-stranded DNA-dependent ATP-dependent DNA helicase complex, telomere cap)

(and it is defined 
A protein complex that plays a role in the process of DNA packaging.
which isn't very helpful. 
I would obsolete rather than try to define, since we don't have a "DNA packaging" process term.

**Comment by pgaudet** [comment]
See also #23212

**Comment by pgaudet** [comment]
This will be fixed by obsoletion of DNA packaging complex, see 
#23212
