### ISSUE TITLE
Query  tRNA re-export from nucleus (GO:0071528) (merge?)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24002]
Is **re-export** really a separate process? Most things will be shuttled and  between the nucleus and cytoplasm, and constantly re-exported//improted to the preferred location.  The annotation I am picking up is for a normal karyopherin that exports tRNAs 

Definition | Parents
-- | --
The directed movement from the nucleus to the cytoplasm of a tRNA that was previously exported to the cytoplasm and then imported back into the nucleus. The processes of primary tRNA export and secondary export (re-export) can be distinguished because in organisms in which tRNA splicing occurs in the cytoplasm, the export of a mature tRNA must occur by re-export. [PMID:17475781, PMID:20032305]

suggest to merge.
2 EXP annotations from the same paper (genetic interactions), SGD  (both protein areinvolved  in tRNA export generally)

**Comment by pgaudet** [comment]
It seems like tRNAs as exported to the cytosol, then re-imported by 'retrograde tRNA nuclear import', and then re-exported, see Fig 1 in https://academic.oup.com/nar/article/48/20/11577/5930391

I am not sure these are different transport processes; but are we sure we dont want to capture this?

**Comment by ValWood** [comment]
OK ignore there is a purpose to the reimport (seems to be some maturation steps, not surer what)
