### ISSUE TITLE
Obsolete GO:0039633 killing by virus of host cell

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24011]
Dear all, 

The proposal has been made to obsolete 'GO:0039633 killing by virus of host cell'. The reason for obsoletion is that this term is redundant with viral exist from host terms. There are no annotations or mappings to this term; this term is not present in any subset. 

Children 
GO:0044696 killing by virus of host cell by post-segregational killing
GO:0039634 killing by virus of host cell during superinfection exclusion 

have been moved to upper level classes:  killing by symbiont of host cells

Thanks, Pascale

**Comment by genegodbold** [comment]
This is a sloppy term. I know that viruses kill cells, but this is just *so* agnostic as to the means and it is really high level. The molecular steps that have to occur are manifold. It's almost useless.
