### ISSUE TITLE
NTR: Regulation terms for cGAS/STING signaling pathway

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#24016]
Could I have regulation terms for the GO:0140896  cGAS/STING signaling pathway?

PMID:29875158 https://pubmed.ncbi.nlm.nih.gov/29875158/ shows that Bombyx mori Casp8L can negatively regulate the cGAS/STING signaling pathway

**Comment by pgaudet** [comment]
If there is only evidence for the negative regulation, we should only create that one term.

**Comment by hattrill** [comment]
Thanks
