### ISSUE TITLE
NTR: cyclic-di-GMP transmembrane transporter activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#24013]
Please provide as much information as you can: 

* **Suggested term label:**
cyclic-di-GMP transmembrane transporter activity

* **Definition (free text)**
Enables the transfer of cyclic-di-GMP from one side of a membrane to the other.

* **Reference, in format PMID:#######**
PMID:[34965418]

* **Gene product name and ID to be annotated to this term**
CNT2; FBgn0025709
* **Parent term(s)**
GO:0005346 	purine ribonucleotide transmembrane transporter activity 	
GO:0001409 	guanine nucleotide transmembrane transporter activity

* **Possible new parent umbrella term** 
for this new term & GO:0140360 cyclic-GMP-AMP transmembrane transporter activity

could be made "cyclic di-nucleotide  transmembrane transporter activity"

* **Cross-references**
CHEBI:58805

**Comment by pgaudet** [comment]
+
+[Term]
+id: GO:0140927
+name: cyclic-di-GMP transmembrane transporter activity
+namespace: molecular_function
+def: "Enables the transfer of cyclic-di-GMP from one side of a membrane to the other." [PMID:34965418]
+intersection_of: GO:0022857 ! transmembrane transporter activity
+intersection_of: has_primary_input CHEBI:58805 ! c-di-GMP(2-)
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24013 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-18T13:17:30Z
+
