### ISSUE TITLE
Missing parent: [GO term] GO:0023052  signaling

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24029]
* **GO term ID and label for which you request a new superclass**

GO:0023052  signaling

I was wondering why signalling isn't a child of "regulation of biological process", I always thought it was, but it seems that it has never been.

**Comment by ukemi** [comment]
Because originally a process could regulate a function too.

**Comment by pgaudet** [comment]
There is one children that would be inconsistent, 'multicellular organismal signaling', as it is a parent of 
* GO:0061337 cardiac conduction
* GO:0019226 transmission of nerve impulse

These have other parents anyway, so we will obsolete the problematic parent 'multicellular organismal signaling',

**Comment by pgaudet** [comment]
Dear all,
 
The proposal has been made to obsolete GO:0035637 multicellular organismal signaling. The reason for obsoletion is that this is an unnecessary grouping class. There are no direct annotations or mappings to this term; this term is not present in any subsets.
 
You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24029
 
Thanks, Pascale
