### ISSUE TITLE
NTR - metabolism: [dihydroxyacetone kinase l]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24037]
Request,
dihydroxyacetone kinase 
Currently related for glycerone kinase activity
but they seem to be  different activities?

https://pubmed.ncbi.nlm.nih.gov/16535475/ (1996)
Although both of the enzymes had some affinity for glycerol and dl-glyceraldehyde in addition to dihydroxyacetone and glyceraldehyde, V(infmax) values for dihydroxyacetone were much higher than those for glycerol and dl-glyceraldehyde. 

Until now, three different types of kinases which are active on DHA have been found. The first is DHAK, which is highly specific for DHA (8, 9). However, several enzymes capable of phosphorylating both DHA and glyceraldehyde but with much higher affinity for DHA than for glyceraldehyde are also classified as DHAKs (2, 4, 6, 14). The second is triokinase (EC 2.7.1.28), which is capable of catalyzing the phosphorylation of DHA and glyceraldehyde with similar rates for both substrates but cannot catalyze the phosphorylation of glycerol at all. The third is glycerol kinase (EC 2.7.1.30). This enzyme preferentially phosphorylates glycerol but is also active on DHA and glyceraldehyde. The Km values of glycerol kinase purified from
Escherichia coli were reported to be 0.0013, 0.5, and 0.5 mM for glycerol, DHA, and DL-glyceraldehyde, respectively (9).
Although two kinases from S. pombe IFO 0354 have activity toward glycerol, phosphorylation of glycerol is a very minor
activity of DHAK I and DHAK II, with Vmax values for glycerol that were only 3.3 and 5.5%, respectively, of the velocities for
DHA as the substrate (Table 3). We concluded that these kinases should be classified as DHAKs on the basis of higher
affinities and higher Vmax values for DHA than for the other
substrates.

What do you think? Does this need its own term?

(sorry this is a really old paper but it's all I have)

**Comment by ValWood** [comment]
cc @deustp01

**Comment by deustp01** [comment]
according to the [ChEBI entry for dihydroxyacetone](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16016), "glycerone" is a synonym for dihydroxyacetone and kinases can catalyze its reaction with ATP to yield ADP plus dihydroxyacetone phosphate ([RHEA:15773](https://www.rhea-db.org/rhea/15773)).

Here it looks like different gene products can enable this reaction with different efficiencies and with different abilities to also act on other substrates. If I understand GO criteria correctly, a difference in the efficiency with which a reaction is enabled does not warrant creating a new GO term, nor would action by the same mechanism on related substrates (hence, a single term "[alcohol dehydrogenase activity](https://www.ebi.ac.uk/QuickGO/term/GO:0004022)" appears to be appropriate for methanol, ethanol, ... .

But perhaps here the different enzymes use different mechanisms, something analogous to the distinction in GO between NAD- and NADP-dependent alcohol dehydrogenases. No clue from here as to whether that is the case but if it is (and the sanity test will be persuading our RHEA colleagues that the difference is legitimate), then a new GO term seems right.

**Comment by ValWood** [comment]
It's OK, i'm happy close this and just stick with glycerone kinase activity.....

**Comment by hdrabkin** [comment]
Ok closing.
