### ISSUE TITLE
Taxon constraint: GO:0032922

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#24034]
Hello,
GO:0032922 (circadian regulation of gene expression) should not be excluded from cyanobacteria, and maybe not from archaea either.

The circadian clock is highly studied in cyanobacteria, especially Synechococcus elongatus PCC 7942 and Thermosynechococcus elongatus BP-1 (now Thermosynechococcus vestitus), see review PMID:33419320. This paper (https://bmcecolevol.biomedcentral.com/articles/10.1186/s12862-017-0999-7) discusses a possible clock in archaea, although it is not yet clear if they really exist. There may be a clock in a few other (non-oxygenic) photosynthetic bacteria as well based simply on gene conservation.

I think you should remove this taxonomic restraint. If you want it could be limited to cyanobacteria, but I wonder if we would have to revisit this issue one day if you chose to limit it to that taxonomic level.
Thanks, Andrea

**Comment by pgaudet** [comment]
Removed 'multicellular organismal process' as a parent of GO:0032922 circadian regulation of gene expression and 'GO:0097167 circadian regulation of translation'
