### ISSUE TITLE
EC 1.14.13.147 linked to GO: 0036239 has now been transferred to EC 1.14.14.182

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24049]
From @kaxelsen 

I just wanted to inform you that EC 1.14.13.147 linked to GO: 0036239 has now been transferred to EC 1.14.14.182. The two Rhea reactions linked to the EC numbers remain the same. The transfer will be part of the freeze taking place next Wednesday and should go public in release 2022_05 December 7.

**Comment by hdrabkin** [comment]
Need check parent 1.14.13 to 1.14.14; need to supply a def ref since it was used as a def ref and will be removed.
term has RHEA:31975; is reaction still valid? (since I can't see the new EC to judge. If not I need to remove this also

GO:0036239 has 1 exp annotaton (IDA) based on PMID:15157877
I will use as reference

**Comment by hdrabkin** [comment]
Curent parent: oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen IS EC:1.14.14.-, so not need to change
Metacyc:RXN-12885 already has the new EC ; I removed RHEA but if ok, @kaxelsen let me know if I can put back.

**Comment by hdrabkin** [comment]
Done for now.

**Comment by kaxelsen** [comment]
EC 1.14.14.182 is linked to RHEA:31975 and RHEA:71403. Both reactions are part of the definition of the new EC number:
https://www.enzyme-database.org/query.php?ec=1.14.14.182

**Comment by hdrabkin** [comment]
Ah, ok, so I'll add these as narrowMatch xrefs

**Comment by hdrabkin** [comment]
Catalysis of the reaction:  taxusin + [reduced NADPH—hemoprotein reductase] + O2 = 7beta-hydroxytaxusin + [oxidized NADPH—hemoprotein reductase] + H2O and  2apha-hydroxytaxusin + [reduced NADPH—hemoprotein reductase] + O2 = 2alpha7beta-dihydroxytaxusin + [oxidized NADPH—hemoprotein reductase] + H2O.

**Comment by pgaudet** [comment]
Fixed parent from GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

 to 

GO:0016712 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen
