### ISSUE TITLE
Inconsistency coming from term 'tube lumen cavitation'

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#24041]
![image](https://user-images.githubusercontent.com/112839/191470932-1c10e152-d174-486a-b2e2-e1a3212524f7.png)

Tube lumen is immaterial, but the process, (via the relations and standard patterns used to define it) refer to development of a material entity.  This makes sense in that the process that leads to lumen formation are taking place in the tissue that comes to surround the lumen.  It could be fixed if the process can refer to the cavitated entity rather than cavity (lumen). 

I think that GO should have some more general class ‘cavitation’ that has no logical def but a good textual one.  This can sit under ‘anatomical structure formation involved in morphogenesis’.  We can then define ‘tube lumen cavitation’ (perhaps better named ‘tube lumen formation by cavitation)’ as cavitation and results_formation of some ‘anatomical tube’.  This distinguishes it from other mechanisms of tube formation, e,g, by folding.

**Comment by dosumis** [comment]
CC @balhoff @cmungall

**Comment by cmungall** [comment]
I think the proposed solution makes sense. Let's just remove the existing equivalence axiom for now
