### ISSUE TITLE
GO:0102040: EC 1.3.5.4 transferred to (included in) EC 1.3.5.1 

### ISSUE THREAD

**Issue by kaxelsen** [geneontology/go-ontology#24056]
EC 1.3.5.4 linked to GO:0102040 has now been transferred to EC 1.3.5.1 as the two EC numbers described the same reaction but from different directions. EC 1.3.5.1 describes 'succinate dehydrogenase' (succinate to fumarate) while EC 1.3.5.4 described 'fumarate reductase' (fumarate to succinate). The Rhea reactions linked to the EC numbers remains the same. The transfer will be part of the freeze taking place next Wednesday and should go public in release 2022_05 December 7.

**Comment by hdrabkin** [comment]
No parent change needeD (1.3.5.-_
Keep RHEAs
Metacyc has been updated. 
Done
