### ISSUE TITLE
EC 3.1.3.81 linked to GO:0000810 has now been transferred to EC 3.6.1.75

### ISSUE THREAD

**Issue by kaxelsen** [geneontology/go-ontology#24052]
EC 3.1.3.81 linked to GO: 0000810 has now been transferred to EC 3.6.1.75. The Rhea reaction linked to the EC numbers remains the same. The transfer will be part of the freeze taking place next Wednesday and should go public in release 2022_05 December 7.

**Comment by hdrabkin** [comment]
Parent change 3.1.3.- to 3.6.1.- hydrolase activity, acting on acid anhydrides  but current parent pyrophosphatase activity, a child of 3.6.1.- So keep.
Keep RHEA
Metacyc is already updated.
Done.
