### ISSUE TITLE
GO:0090409: EC 6.2.1.n3 transferred to EC 6.2.1.76

### ISSUE THREAD

**Issue by kaxelsen** [geneontology/go-ontology#24054]
EC 6.2.1.n3 linked to GO: 0090409 has now been transferred to EC 6.2.1.76. The Rhea reaction linked to the EC numbers remains the same. The transfer will be part of the freeze taking place next Wednesday and should go public in release 2022_05 December 7.

**Comment by hdrabkin** [comment]
6.2.1 parent not needed update. 
Keep rhea
metacyc already updated. 
done
