### ISSUE TITLE
EC 1.14.99.51 linked to GO: 0061686 has now been transferred to EC 1.21.3.10

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24051]
From @kaxelsen 

EC 1.14.99.51 linked to GO: 0061686 has now been transferred to EC 1.21.3.10. The Rhea reaction linked to the EC numbers remains the same. The transfer will be part of the freeze taking place next Wednesday and should go public in release 2022_05 December 7.

**Comment by hdrabkin** [comment]
Parentage change 1.14.99 to 1.21.3
'oxidoreductase activity, acting on X-H and Y-H to form an X-Y bond, with oxygen as acceptor', EC:1.21.3.-, GO:0046993
Keep RHEA
Done.
