### ISSUE TITLE
GO:0004013 EC 3.3.1.1 transferred to EC 3.13.2.1

### ISSUE THREAD

**Issue by kaxelsen** [geneontology/go-ontology#24053]
EC 3.3.1.1 linked to GO: 0004013 has now been transferred to EC 3.13.2.1. The Rhea reaction linked to the EC numbers remains the same. The transfer will be part of the freeze taking place next Wednesday and should go public in release 2022_05 December 7.

**Comment by hdrabkin** [comment]
Parent change 3.3.1 to 3.13.2; cannot find a 3.13.2 class in EC.;will use grandparent hydrolase activity, acting on carbon-sulfur bonds (EC:3.13.-P
metacyc already changed.
Keep RHEA
removed 3.3.1.1 to all synonyms.
Done.

**Comment by kaxelsen** [comment]
Sub-subclass EC 1.13.2 Thioether and trialkylsulfonium hydrolases
It will become public together with the changes to the EC mappings in release 2022_05

**Comment by hdrabkin** [comment]
GO:new
Term: hydrolase activity, acting on thioether and trialkylsulfonium hydrolases
Def: Catalysis of the hydrolysis of any thioesters or trialkysulfonates
is_a: hydrolase activity, acting on carbon-sulfur bonds (EC:1.13.-)
ref: GOC curators
xref: EC:1.13.2.-

**Comment by sjm41** [comment]
@kaxelsen @hdrabkin 

_The definition of the new Sub-subclass is:
EC 1.13.2 Thioether and trialkylsulfonium hydrolases_

Hmmm...does that mean we should also check the parentage and xrefs of "trialkylsulfonium hydrolase activity (GO:0016802)" and its remaining children?  Is 3.3.1.2 also being transferred?

hydrolase activity, acting on ether bonds (EC:3.3.-.-)
|__trialkylsulfonium hydrolase activity (EC:3.3.1.-)
....|__adenosylmethionine hydrolase activity (EC:3.3.1.2)
....|__adenosylselenohomocysteinase activity (n/a)

term: trialkylsulfonium hydrolase activity (GO:0016802)
Def: Catalysis of the hydrolysis of a thioether bond, -S-.

term: adenosylmethionine hydrolase activity
Def: Catalysis of the reaction: S-adenosyl-L-methionine + H(2)O = S-methyl-5'-thioadenosine + L-homoserine + H(+).

term: adenosylselenohomocysteinase activity (GO:0098604)
Def: Catalysis of the reaction: Se-Adenosyl-L-selenohomocysteine + H2O => Adenosine + Selenohomocysteine.


If so, will also need to tweak def of parent term:
term: hydrolase activity, acting on ether bonds (GO:0016801)
Def: Catalysis of the hydrolysis of any ether or thioether bond, -O- or -S- respectively.

**Comment by kaxelsen** [comment]
EC 3.3.1.2 has been transferred to EC 3.13.2.2.
EC 3.13.1.8 has been transferred to EC 3.13.2.3.
