### ISSUE TITLE
taxon constraint incorrectly applied in P2GO?

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#24057]
P2GO gives an error
 "Extra Tax Id can only be used with terms that are descendants of GO:0044419 (interspecies interaction between organisms) or GO:0043903 (regulation of symbiosis, encompassing mutualism through parasitism) or GO:0018995 (host cellular component)" 
 for an entity annotated with GO:0050829 defense response to Gram-negative bacterium - which, according to QuickGO is a descendant of GO:0044419 - is this a P2GO problem, or a GO problem?
 I've also added taxon Id for the microbe involved, which is 666  Vibrio cholerae.

**Comment by pgaudet** [comment]
I think this is in P2GO, because this is a relatively recent problem, and I dont think GO changed the TCs in this areas of the ontology.  

@alexsign would you please check ?

**Comment by pgaudet** [comment]
@Pauldenny I dont see this anymore - see for example PMID:18603306
There are annotations to GO:0050829 defense response to Gram-negative bacterium and interacting taxa but no errors - can you please check again?
