### ISSUE TITLE
NTR defense response against disruption of plasma membrane integrity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24061]
Hello, 

While reviewing GO:0051673 membrane disruption in another organism (see #24008), we found that some host/prey genes could be annotated to 'defense response against disruption of plasma membrane integrity',  

Def: The cellular processes and signaling pathways by which a cell responds to disruption of the integrity of its plasma membrane by another organism. Some toxins produced by other organisms can form pores in membranes, or affect the membrane permeability.  

PMID:17234446
PMID:21518219

**Comment by pgaudet** [comment]
placed under is_a 'innate immune response' 
@dsiegele @genegodbold is this right ?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140976
+name: defense response against disruption of plasma membrane integrity
+def: "The cellular processes and signaling pathways by which a cell responds to disruption of the integrity of its plasma membrane by another organism. Some toxins produced by other organisms can form pores in membranes, or affect the membrane permeability." [PMID:17234446, PMID:21518219]
+is_a: GO:0045087 ! innate immune response
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24061 xsd:anyURI
+created_by: pg
+creation_date: 2022-09-23T13:28:52Z

**Comment by genegodbold** [comment]
Hey @pgaudet, I lost internet at my house last night so I couldn't attend this morning's session.

I don't know if this MAPK-activation pathway is actually what's behind this immune response, but I agree that it is an innate immune response. I can't see that anybody has followed up with *that* (MAPK-activated) immune pathway, but there is more and better work describing host NOD-like receptors and subsequent inflammasome activation in response to bacterial perturbations of (1) the host membrane (2) the host cytoskeleton (3) host small GTPases in response to bacterial effectors

Earliest review (I can find) of this mechanism: https://pubmed.ncbi.nlm.nih.gov/19539499/
More recent stuff: 
- https://pubmed.ncbi.nlm.nih.gov/21995284/
- https://pubmed.ncbi.nlm.nih.gov/25914126/
- https://pubmed.ncbi.nlm.nih.gov/26562791/
"Among the canonical caspase-1-activating inflammasomes, the NAIP subfamily of NLR proteins serves as the receptors for bacterial flagellin and type III secretion apparatus; Pyrin indirectly senses Rho modification/inactivation by various bacterial agents; NLRP1 in mice/rats detects the protease activity of anthrax lethal toxin by serving as its substrate. Caspase-11 and caspase-4/5 directly recognize bacterial LPS and then become activated. Inflammasome sensing of cytosolic bacteria employs much more diversified biochemical mechanisms, compared with Toll-like receptors-mediated recognition on the membrane."
- https://pubmed.ncbi.nlm.nih.gov/33426791/

**Comment by genegodbold** [comment]
Also, @pgaudet, I just don't buy the papers that are saying that membrane integrity is strengthened or preserved. And there has been no follow-up showing mechanisms (NOT a good sign), so I don't agree with defense against membrane integrity part of this definition. The inflammasome activation is involved with the *execution* of the host cell, and with extreme prejudice (i.e. inflammation). Why? So the neutrophils and macrophages know to come in and clean up the bacteria in the area.

**Comment by genegodbold** [comment]
For metazoans, the modus operandi is to sacrifice individual cells for the greater good of the whole. It would be unusual to *preserve* the cell in the face of a viral or bacterial or fungal or protozoal infection.

**Comment by pgaudet** [comment]
- [ ] Change label: 'host defense response against symbiont-mediated perturbation of plasma membrane integrity'
- [ ] Move under defense response to symbiont
