### ISSUE TITLE
NTR: hydrogen peroxide membrane transport activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#24070]
Please provide as much information as you can: 

* **Suggested term label:**
hydrogen peroxide membrane transport activity

* **Definition (free text)**
Enables the transfer of hydrogen peroxide from one side of a membrane to the other.

* **Reference, in format PMID:#######**
PubMed=23541115 and PMID: 27256569
* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
part of hydrogen peroxide transmembrane transport (BP)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: RO:0012009
+name: hydrogen peroxide channel activity
+namespace: molecular_function
+def: "Enables the transfer of hydrogen peroxide from one side of a membrane to the other." [PMID:23541115, PMID:27256569]
+synonym: "hydrogen peroxide transmembrane transporter activity" RELATED []
+is_a: GO:0015267 ! channel activity
+intersection_of: GO:0015267 ! channel activity
+intersection_of: has_primary_input CHEBI:16240 ! hydrogen peroxide
+relationship: part_of GO:0080170 ! hydrogen peroxide transmembrane transport
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24070 xsd:anyURI
+created_by: pg
+creation_date: 2022-09-27T11:35:19Z

**Comment by pgaudet** [comment]
@Argoudpuy 

I made this a 'channel' since aquaporins are channels. Is that OK for you ? 

Thanks, Pascale

**Comment by Argoudpuy** [comment]
yes, I was I was writing to you that I was mistaken, sorry

**Comment by Argoudpuy** [comment]
thanks

**Comment by Argoudpuy** [comment]
Hi Pascale,
is it possible that this GO term has been not created because of an error in id: RO:0012009 instead of id: GO:0012009 (see above)?
Thanks
Guilaine

**Comment by pgaudet** [comment]
Yes thanks @Argoudpuy 
I changed the ID - hopefully this will fix it
