### ISSUE TITLE
apolipoprotein B mRNA editing enzyme complex as a child of  mRNA editing complex

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#24088]
Hi,
shouldn't apolipoprotein B mRNA editing enzyme complex  be a child of mRNA editing complex as it is defined for its substrate specificity.
Thanks

**Comment by raymond91125** [comment]
apolipoprotein B mRNA is a product of the APOB gene. Thus perhaps apolipoprotein B mRNA editing enzyme complex is too specific and should be merged into mRNA editing enzyme. This term has only 1 EXP annotation from UniProt.
@pgaudet does this fit our guidelines or are protein complexes different?

**Comment by lbreuza** [comment]
From what I read there is not a single complex able to process APOB mRNA and such complex is not specific of a single mRNA. PubMed=24916387 and PubMed=30844405.
APOB mRNA is a well studied case of mRNA editing often used as a reference.

**Comment by raymond91125** [comment]
I see. Does this mean that apolipoprotein B mRNA editing enzyme complex is a misnomer, using an enzymatic assay as the name for some function (and the complex)? If this all seems OK per field standard practices, I can add the parent. Thanks.

**Comment by lbreuza** [comment]
Yes, for me kind of misnomer based on the first target mRNA identified, though I cannot exclude yet there is no RNA-editing complex specific for APOB mRNA.

**Comment by pgaudet** [comment]
Evelyn requested that about 20 years ago: https://github.com/geneontology/go-ontology/issues/1192

She wrote that we dont know all the components of the complex. There is a single EXP annotation. I would not object to obsoletion (I thought maybe it represented a different complex, but it doesn't seem this is the case).


Thanks, Pascale

**Comment by raymond91125** [comment]
I think we should keep it. This is a type of editosome (GO:0045293 mRNA editing complex) that contains a deaminase APOBEC-1 and an RNA-binding protein ACF. PMID:12683974
![image](https://user-images.githubusercontent.com/619520/192855943-6314233f-7151-4cb3-b3b5-2526add99ff7.png)

**Comment by raymond91125** [comment]
ASP = APOBEC1 complementation factor 1 (by blast), aka a1cf, acf
KSRP = Khsrp (KH-type splicing regulatory protein)
