### ISSUE TITLE
Obsoletion notice: modification by host of symbiont cellular component' & some children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24085]
Dear all, 

The proposal has been made to obsolete: 
* 'modification by host of symbiont cellular component'  
* '~disruption by host of symbiont cellular component'~ will merge in parent  modification by host of symbiont structure
* 'modification by host of symbiont cell wall'
* 'modification by host of symbiont cytoskeleton'
* 'occlusion by host of symbiont vascular system'
* 'occlusion by host of symbiont xylem'

The reason for obsoletion is that these terms are either too vague ("modification") or not known to exist ('occlusion by host of symbiont vascular system' and 'occlusion by host of symbiont xylem', which were created to by the opposite of GO:0052494 occlusion by host of symbiont vascular system and GO:0052496 occlusion by host of symbiont xylem). 

There are no annotation and no mappings to these terms. These terms are not present in any subsets. You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24085

Thanks, Pascale

**Comment by pgaudet** [comment]
Change labels of related terms: 

* 'modification by host of symbiont structure' -> keep as a grouping class -> change label to 'disruption by host of symbiont structure'
* 'disruption by host of symbiont cell wall' -> keep as vaid term (1 paper annotated)
* 'modification by host of symbiont membrane' -> change label to 'disruption by host of symbiont membrane

**Comment by genegodbold** [comment]
If I am a host and I have my legions of neutrophils generate oodles of antimicrobial peptides and use them to disrupt the membranes of my Staphylococcus aureus symbiont, then am I a bad host? Also, am I not modifying the symbiont cell wall (by destroying it)?

I'm just kidding @pgaudet, please get rid of all of these. They need to go.
