### ISSUE TITLE
NTR: formamide channel activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#24089]
Please provide as much information as you can: 

* **Suggested term label:**

formamide channel activity

* **Definition (free text)**
Enables the facilitated diffusion of formamide (by an energy-independent process) involving passage through a transmembrane aqueous pore or channel without evidence for a carrier-mediated mechanism. 

* **Reference, in format PMID:PubMed=15948717

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0015267 channel activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
see comment in https://github.com/geneontology/go-ontology/issues/24091#issuecomment-1259589179

**Comment by pgaudet** [comment]
after discussion with @Argoudpuy , we agreed that formamide is an analogue of ammonium and there is no known physiological role for formamide  in the mitochondria. We wont create this term.
