### ISSUE TITLE
NTR: formamide transmembrane transport

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#24091]
Please provide as much information as you can: 

* **Suggested term label:**
formamide transmembrane transport

* **Definition (free text)**
 The process in which formamide is transported across a membrane. 

* **Reference, in format PMID:15948717

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
formamide transport (see NTR: formamide transport #24090)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
 formamide channel activity ( see NTR: formamide channel activity #24089 )

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Hi @Argoudpuy 

This is not physiological, the authors write in the methods, "Formamide (HCONH2), a small uncharged solute, has been used as an ammonium analogue " - we would not create this term, unless you think this is relevant in vivo ?

**Comment by Argoudpuy** [comment]
Hi Pascale,
PMID: 20132793 describes in fig. 3. formamide and water transport across mitochondria from rat liver and brain.
