### ISSUE TITLE
NTR: formamide transport

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#24090]
Please provide as much information as you can: 

* **Suggested term label:**
formamide transport

* **Definition (free text)**
* 
The directed movement of formamide into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore. 

* **Reference, in format PMID:15948717

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0019755: one-carbon compound transport

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
see comment in https://github.com/geneontology/go-ontology/issues/24091#issuecomment-1259589179
