### ISSUE TITLE
NTR: ammonium channel activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#24109]
Please provide as much information as you can: 

* **Suggested term label:**
ammonium channel activity

* **Definition (free text)**

Enables the facilitated diffusion of ammonium (by an energy-independent process) involving passage through a transmembrane aqueous pore or channel without evidence for a carrier-mediated mechanism. 

* **Reference, in format PMID:16624991

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
channel activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Ammonium channel activity was merged in #22368


Please annotate to GO:0008519 ammonium transmembrane transporter activity

Thanks, Pascale
