### ISSUE TITLE
Textual definition update: alpha-galactosidase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24117]
* **GO term ID and label for which you request a definition update**

GO:0004557
alpha-galactosidase activity
Molecular Function

Definition 

Catalysis of the hydrolysis of terminal, non-reducing alpha-D-galactose residues in alpha-D-galactosides, including galactose oligosaccharides, galactomannans and galactohydrolase.

* **New proposed definition (genus-differentia pattern, plus additional information if needed) **

There is a problem with this definition. I don't know what it should  be, but I'm sure that the last word in the list of substrates shouldn't be  'galactohydrolase'

One example of this activity is
"The diversification is driven due to a public good enzyme α-galactosidase, which hydrolyses melibiose into glucose and galactose." PMID: 36181481

The synonym relationships may also need reviewing. Should the related synonyms be narrow? Except melibiase which seems to be narrow (also should some of the narrow synonyms be instantiated as terms?)

* **Additional information**

**Comment by hdrabkin** [comment]
Must have been a typo. Very old term by the looks of the id.  Oxford dictionary has the same def but has galactolipids rather than galactohydrolase, so will fix now.
