### ISSUE TITLE
GO:0032268   regulation of cellular protein metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24123]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0032268   regulation of cellular protein metabolic process

* **Reason for deprecation**

This term has no children and I'm not sure why it would be used over a  more specific term in the "regulation of biological process branch"

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:
11 EXP
355 total

* **Any other information**

**Comment by pgaudet** [comment]
Thanks . I forgot this one when I did https://github.com/geneontology/go-ontology/issues/23112
