### ISSUE TITLE
GO:0090225 regulation of spindle density

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24121]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0090225 regulation of spindle density

* **Reason for deprecation**

I don't think this should be in biological process. I suspect ist was added for a logical definition of a phenotype. it has no annotations

**Comment by ValWood** [comment]
I can't see the ticket where this term was created...

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0090225 regulation of spindle density. The reason for obsoletion is that this represents a phenotype. There are no annotations or mappings to this term; this term is not in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24121


Thanks, Pascale

**Comment by pgaudet** [comment]
@ValWood 
This is where the term was created
https://github.com/geneontology/go-ontology/issues/6846

**Comment by ValWood** [comment]
OK. Spindle 'density' is not really regulated, but can probably be inferred from the spindle appearance in micrographics (the spindle 'looks denser'.  But there is not a specific process to regulate spindle density (it would be just 'spindle organization' or 'spindle assembly' - the density is just an observation. Some mutants have 'less dense spindles'
