### ISSUE TITLE
Taxon constraint: selenocysteine incorporation & selenocysteine-tRNA ligase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24134]
Please provide as much information as you can: 

* **GO term ID label:**

GO:0098619 selenocysteine-tRNA ligase activity
GO:0001514 selenocysteine incorporation

* **Request to add a taxon constraint:**

* * **never in taxon: **
Dikarya 451864 
Embryophyta 3193 

* **Supporting evidence if available (e.g PMID):**

I think we can add a taxon restriction for these to Dikaryia - they were thought to be completely absent in fungi, but [30742068](https://pubmed.ncbi.nlm.nih.gov/30742068) suggests they may be present in early diverging lineages of fungi

Also to "higher plants" 
_"higher plants, which make oxygen, completely lack proteins that contain selenocysteine"_
https://www.sciencedirect.com/science/article/pii/B9780128132883000136

this recent paper specifies "land plants"

_" The pathway of selenocysteine biosynthesis was identified by our approach as a metabolic loss during land plant evolution (Figure 1). The gene encoding the first enzyme in the pathway is found in all plant taxa analyzed, while the genes encoding the full combination of enzymes required for this pathway are found only in the algae (Figure S5)._
https://www.sciencedirect.com/science/article/pii/S0960982220302931

present in: Chlamydomonas reinhardtii (green algae)
https://www.embopress.org/doi/full/10.1093/emboj/cdf372

I was also going to suggest blocking "selenocysteine biosynthesis" but I'm not sure, they do seem to make selenocysteine, but it is toxic? 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4724052/

@ValWood

**Comment by Antonialock** [comment]
There's not actually many annotations to these in those taxon groups, but I was looking at them because fungal + plant SYSC_entries are associated with
selenocysteine-tRNA ligase activity doesn't appear to have any annotations? I just annotated P49591 to this term

**Comment by Antonialock** [comment]
(i.e. I don't know how important to add in blocks if they are not causing so many problems....but I guess it is increasingly important with more and more  automatic prediction pipelines?)

**Comment by ValWood** [comment]
Yes add them. Better to have them and remove if necessary than to fix 100's of annotations.
