### ISSUE TITLE
NTR: Retinoic acid-induced apoptosis

### ISSUE THREAD

**Issue by smoe** [geneontology/go-ontology#24142]
Please provide as much information as you can: 

* **Suggested term label:**
Retinoic acid-induced apoptosis

* **Definition (free text)**
Retinoic acid-induced apoptosis

* **Reference, in format PMID:#######**

PMID: 9187263
PMID: 16568081
PMID: 33190441
PMID: 18474417
PMID: 17869331 ; close to suggest a physiological role of ATRA in development

* **Gene product name and ID to be annotated to this term**

BCL-2 [P10415](https://www.uniprot.org/uniprotkb/P10415/entry)
RARG [P13631](https://www.uniprot.org/uniprotkb/P13631/entry)
FLT3 [P36888](https://www.uniprot.org/uniprotkb/P36888/entry)
ERK1 [P27361](https://www.uniprot.org/uniprotkb/P27361/entry) # MAKP3
ERK2 [P28482](https://www.uniprot.org/uniprotkb/P28482/entry) # MAPK1

* **Parent term(s)**
GO:0071300 (cellular response to retinoic acid)
GO:0071887 (leukocyte apoptotic process)
GO:0043065 (positive regulation of apoptotic process)

GO:0048384 (retinoic acid receptor signaling pathway)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

N/A

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

Don't know any.

* **Cross-references**

All-trans-retinoic-acid (ATRA):
 * https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:45376
 * https://reactome.org/content/detail/R-ICO-013649
 * https://en.wikipedia.org/wiki/Tretinoin

* **Any other information**

This term is of clinical (oncological) relevance. The genes listed are incomplete, not sure if one should separate the induction of apoptosis with retinoids and particular markers of apoptosis when induced by retinoids. The Wikipedia page on https://en.wikipedia.org/wiki/Tretinoin presents an overview on clinical applications.

**Comment by raymond91125** [comment]
Is this a normal physiological response or an artificial insult? We may want to distinguish between a 'normal' signalling process from cellular response to crisis.

**Comment by smoe** [comment]
Thank you for your comments. @pgaudet, @raymond91125, I do not know if this is truly an external stimulus. ATRA (https://en.wikipedia.org/wiki/Tretinoin) is a metabolite of Vitamin A and thus whatever may also be triggered externally to have a systemic or tissue-level effect, I also expect to observe as a physiological response on a cellular level. There may well be a dose-effect when applied externally, but I would rather see this as a co-annotation for whoever is assigning this GO term. My analogy would be a GO term "hammer-induced-pain" for which there would be a distinction between "hitting hard" and "hitting softly" - there is quite a difference for all practical purposes but it is still some hammer-induced pain as a concept.

**Comment by raymond91125** [comment]
How about:
Term label: "programmed cell death in response to retinoic acid"
Definition: "Cell death resulting from activation of endogenous cellular processes and occurring as a result of a retinoic acid."

**Comment by smoe** [comment]
Not wrong, and I like it,  and this may be most consistent with the GeneOntology. It is not on me to judge but if it is the preferred way to represent this term, then "Retinoic acid-induced apoptosis" should be an alias. It is the terminus technicus that the community will search for and that clinicians (main audience for me) will immediately understand.

On a side-note, I added a ref to https://pubmed.ncbi.nlm.nih.gov/17869331/ which again has a series of interesting citations. I had also thought more about the "external vs intrinsic response" you brought up. My initial position "is its derived from a vitamin and hence is intrinsic" I have now problems with - the definition of a vitamin is that it is externally provided, so it is external for humans. Just, what defines a Vitamin differs between species, and GO should be species-agnostic.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160059
+name: programmed cell death in response to retinoic acid
+namespace: biological_process
+def: "Cell death resulting from activation of endogenous cellular processes and occurring as a result of a retinoic acid." [PMID:17869331, PMID:9187263]
+synonym: "retinoic acid-induced apoptosis" EXACT []
+is_a: GO:0012501 ! programmed cell death
+relationship: part_of GO:0071300 ! cellular response to retinoic acid
+created_by: rynl
+creation_date: 2022-10-27T23:22:22Z

**Comment by raymond91125** [comment]
Thanks.
