### ISSUE TITLE
NTR: [proposed new term label] negative  regulation of metaphase/anaphase transition of meiosis II

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24145]
Please provide as much information as you can: 

* **Suggested term label:**
negative  regulation of metaphase/anaphase transition of meiosis II 

* **Definition (free text)**
standard of parents

: regulation of metaphase/anaphase transition of meiosis II (GO:1905189)
: negative regulation of metaphase/anaphase transition of meiotic cell cycle (GO:1902103)

* **Reference, in format PMID:#######**

https://www.pombase.org/gene/SPAC5D6.08c

(will replace all existing annotations with a single specific term.)
note to self, also connect MF-BP

* **Gene product name and ID to be annotated to this term**
for mes1

**Comment by ValWood** [comment]
Also


negative regulation of mitotic metaphase/anaphase transition



[positive regulation of mitotic metaphase/anaphase transition](https://www.pombase.org/term/GO:0045842)

**Comment by pgaudet** [comment]
@val can you provide references?

**Comment by ValWood** [comment]
PMID:18331722 pombe
a review here for mammalian  https://pubmed.ncbi.nlm.nih.gov/16146756/

**Comment by ValWood** [comment]
bizarre, this already exists
GO:1905190   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:1905190/complete)
negative regulation of metaphase/anaphase transition of meiosis II
