### ISSUE TITLE
New term and complex definition update CENP-A maintenance]]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24147]
Mis6-Sim4 complex (GO:0031511)
Definition | 
A protein complex that forms part of the inner kinetochore, which is involved in the loading of the centromeric histone h3 variant CENP-A onto centromeres and in centromere specific heterochromatin formation. The complex contains about 12 proteins, of which two are known as Mis6 and Sim4 in S. pombe and CENP-I and CENP-H in human. [PMID:15897182, PMID:12719471]

The definition of this complex is out of date. This is a very nice paper demonstrating that Mis6-Sim4 is required for CENP-A loading (in interphase), but for the maintenance of CENP-A chromatin during mitotic M-phase.

A protein complex that forms part of the inner kinetochore, which is involved in the centromere specific heterochromatin formation and maintenance. The complex contains about 12 proteins, of which two are known as Mis6 and Sim4 in S. pombe and CENP-I and CENP-H in human. 
Ref PMID:35970865 

So now I do not have the correct process term for Mis6 and Mis15.

Some explanation
Once recruited to centromeres, they appear neither disassembled nor replaced by new nucleosomes containing CENP-A or H3 during both mitotic cycles and meiosis in higher eukaryotes6,21 implying the existence of machinery for CENP-A maintenance.

.....These findings indicate that CENP-A needs to be maintained against the transcription of centromeric ncRNAs, even outside DNA replication.

While CENP-A maintenance at centromeres is necessary during the cell cycle, the underlying molecular mechanism remains elusive. Ubiquitylation of CENP-A was recently shown to contribute to CENP-A maintenance in human cells26. Further, human kinetochore proteins CENP-C and CENP-N directly interact with CENP-A-containing nucleosomes in vitro27,28. These interactions are required for the immobility of CENP-A- containing nucleosomes in human cells29,30.

Another study suggested that CENP-C and CENP-N do not contribute to CENP-A maintenance in human cells3

Taken together, whether these factors are required for CENP-A retention in vivo remains controversial. It was recently demonstrated that HJURP is necessary for CENP-A maintenance during DNA replication32. However, HJURP dissociates from centromeres in metaphase both in human cells8,13,14 and in fission yeast9,15,16, indicating that HJURP does not engage in CENP-A maintenance during metaphase. It was recently reported that the histone chaperone Spt6, which is known as a histone H3 recycler, also contributes to the recycling of pre-existing CENP-A during ncRNA transcrip- tion at centromeres in both Drosophila and human cells33. However, whether more factors are involved in CENP-A main- tenance remains unclear.
In this study, we demonstrate that the kinetochore protein Mis6 (CENP-I in human), which is required for centromere localisation of HJURP15,16, contributes to maintenance of CENP- A during metaphase. We also found that Mis15 (CENP-N in human)34 maintains CENP-A. We propose that the inner kine- tochore subcomplex containing Mis6–Mis15 may counteract progression of RNAPII into core centromeres to prevent the reduction of CENP-A nucleosomes during metaphase

...then they do some nice experiments to prove.

Do you think that 
maintenance of CENP-A chromatin (extended by during mitotic metaphase) would be appropriate here? Or some other term? MAybe some  MF + BP "CENP-A chromatin organization" during "mitotic metaphase"

**Comment by ValWood** [comment]
note that 

centromeric chromatin organization | related
seems to be merged into assembly.

I don't think it should because there are clearly M-phase processes that are not 'assembly'

**Comment by ValWood** [comment]
Or maybe, since
"These results demonstrated that the inner kinetochore subcomplex including Mis6 prevents unnecessary transcription of ncRNAs at the central core region, thereby maintaining Cnp1 on chromatin during metaphase."

centromeric chromatin protection? it's really just making the chromatin inaccessible?

**Comment by ValWood** [comment]
"Transcription of ncRNAs in the central core region occurs at a certain level even in the presence of the
functional inner kinetochore containing Mis6. "

it seems there is also a role for FACT maintaining the CENP-A heterochromatin during transcription at the G2/M transition.

and " Drosophila and human Spt6 have been shown to contribute to CENP-A maintenance during interphase33."

**Comment by ValWood** [comment]
I meant to tag Colin too
@colinlog @pgaudet

**Comment by colinlog** [comment]
I thought we had found enough papers that indicate that CENPA is not
assembled during S-phase?
The MF is likely to be remodelling/reassembly of CENPA nucleosomes upon
disruption by RNA polymerase II.
'Protection' is perhaps too strong a word for these histone chaperones? By
chaperoning they reassemble. The 'disassembler' is the RNA polymerase
together with its associated elongation factors, like FACT who are
chaperones of import for any of this 'chromatin remodelling at centromere'.

Sorry, I am very busy this month. In November I will join back with Pascale
and you can see if then you still want to discuss ***CENPA and epigenetic
maintenance of centromere identity***.

**Comment by ValWood** [comment]
> I thought we had found enough papers that indicate that CENPA is not
assembled during S-phase?

Did we? maybe (I forgot), but it is assembled during Interphase (not during M-phase).

We can discuss next month.

**Comment by pgaudet** [comment]
Agreed not create this new term
