### ISSUE TITLE
GO:0048478 replication fork protection

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24151]
GO:0048478 replication fork protection 

This is currently a "regulation of process" term, based on parentage.

Really it's more like a collection of things including "replication restart" and "processing of collapsed replication forks"
 Chatting with @pgaudet  we thought this term, based on its position, and meaning, should probably be obsoleted.

30 EXP annotation
10 PomBase  
10 SGD 
7 UniProt 
1 FlyBase 
1 MGI 
1 Complex Portal

For replacement consider:
GO:0031297 replication fork processing
or some other DNA metabolism term

Note that "replication fork protection complex" is unaffected

**Comment by ValWood** [comment]
- [ ] create spreadsheet
- [ ] create annotation ticket, tag curators
- [ ] fix mappings (internal)
- [ ] find external mappings , include in blah
- [ ] check subset usage
- [ ] check taxon constraints 
- [ ] check ontology usage
- [ ] create obsoletion announcement
- [ ] announce to GO friends

**Comment by sandraorchard** [comment]
COmplex Portal done
