### ISSUE TITLE
NTR: neutral amino acid:sodium:chloride symporter activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#24162]
Please provide as much information as you can: 

* **Suggested term label:**
neutral amino acid:sodium:chloride symporter activity

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: neutral amino acid(out) + Na+(out) + Cl-(out) = neutral amino acid(in) + Na+(in)+ Cl-(in).

* **Reference, in format PMID:19478081 fig.2A and 3B

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
sodium:chloride symporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140931
+name: neutral L-amino acid:sodium:chloride symporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: neutral L-amino acid(out) + Na+(out) + Cl-(out) = neutral L-amino acid(in) + Na+(in)+ Cl-(in)." [PMID:19478081]
+synonym: "neutral amino acid:sodium:chloride symporter activity" EXACT []
+is_a: GO:0015175 ! neutral L-amino acid transmembrane transporter activity
+is_a: GO:0015293 ! symporter activity
+relationship: has_primary_input CHEBI:17996 ! chloride
+relationship: has_primary_input CHEBI:29101 ! sodium(1+)
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24162 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-21T11:40:45Z
+
