### ISSUE TITLE
creation of GO term: glideosome complex

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#24178]
Would it be possible to create a cellular component GO term for the 'glideosome complex'?

Possible definition:
Protein complex composed of at least GAP45, GAP50 and myosin heavy and light chains. Anchored via GAP50 to the inner membrane complex of motile and invasive forms of apicomplexan parasites and regulates parasite gliding motility and invasion of host cells.

PMID:15123738
PMID:19577950 (review)

Thank you

Rossana

**Comment by raymond91125** [comment]
Literature usually uses glideosome rather than "glideosome complex". Let me know if that's an issue. Thanks.
