### ISSUE TITLE
NTR: L-phenylalanine import across plasma membrane

### ISSUE THREAD

**Issue by manulera** [geneontology/go-ontology#24183]
Please provide as much information as you can: 

* **Suggested term label:** L-phenylalanine import across plasma membrane

* **Definition (free text)** 

The directed movement of L-phenylalanine from outside of a cell, across the plasma membrane and into the cytosol.

(like [GO:0098712](https://www.ebi.ac.uk/QuickGO/term/GO:0098712))

* **Reference, in format PMID:#######** PMID:11069779

* **Gene product name and ID to be annotated to this term**

cc @ValWood https://journals.biologists.com/jcs/article/113/23/4351/26339/The-SHR3-homologue-from-S-pombe-demonstrates-a

* **Parent term(s)**
equivalent of [GO:0098712](https://www.ebi.ac.uk/QuickGO/term/GO:0098712)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140925
+name: L-phenylalanine import across plasma membrane
+namespace: biological_process
+def: "The directed movement of L-phenylalanine from outside of a cell, across the plasma membrane and into the cytosol." [PMID:11069779]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_primary_input CHEBI:58095 ! L-phenylalanine zwitterion
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0005576 ! extracellular region
+intersection_of: results_in_transport_across GO:0005886 ! plasma membrane
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24183 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-18T13:11:20Z
