### ISSUE TITLE
Consider renaming GO:0036335 to 'intestinal crypt stem cell homeostasis'

### ISSUE THREAD

**Issue by bvarner-ebi** [geneontology/go-ontology#24180]
From https://github.com/obophenotype/cell-ontology/issues/79:

From @addiehl's [comment](https://github.com/obophenotype/cell-ontology/issues/79#issuecomment-937021460):

"I think the CL class 'intestinal crypt stem cell' ([CL:0002250](http://purl.obolibrary.org/obo/CL_0002250)) is the appropriate choice for the required logical definition of GO:0036335, based on a [simple Google search](https://www.google.com/search?client=safari&rls=en&q=intestinal+stem+cell&ie=UTF-8&oe=UTF-8) for "intestinal stem cell" and reading what I found. Arguably GO:0036335 should be renamed "intestinal crypt stem cell homeostasis," but I will leave that to GO to ponder."

**Comment by bvarner-ebi** [comment]
Thank you for the insight, @raymond91125. 
If a reference can be identified to justify whether to close the ticket or make an edit, can that be provided?

**Comment by gouttegd** [comment]
Indeed, there are no crypts in the _Drosophila_ midgut – though people sometimes use that term even in flies, by analogy with the mammalian gut.

For reference, you may have a look at Figure 2 in [Jiang and Edgar, 2012](https://doi.org/10.1016/j.gde.2012.04.002) (PMID:22608824).

So if `intestinal stem cell homeostasis` is intended to also apply to _Drosophila_ (which seems to be the case, I can see that it has been used to annotate fly genes), I agree that it should probably not be renamed to mention “crypt” in the label – though maybe this could be added as a synonym?

**Comment by gouttegd** [comment]
By the way, I meant Figure **1** in the Jiang and Edgar paper, sorry.

**Comment by raymond91125** [comment]
I can add a 'narrow' synonym "intestinal crypt stem cell homeostasis" if that's helpful. Also PMID:22608824 is a good ref to add. Thanks.
