### ISSUE TITLE
NTR: [mannose:sodium symporter activity]& [fructose:sodium symporter activity]

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#24185]
Hello,
I would like to annotate SLC5A10_ A0PJK1 transporter activity in GO and wonder if it’s reasonable to create specific GO terms for mannose and fructose substrates: 
*
new GO: mannose:sodium symporter activity
child of 
GO:0015578    mannose transmembrane transporter activity
GO:0005402    carbohydrate:cation symporter activity
GO:0015370    solute:sodium symporter activity

Definition: Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: D-mannose(out) + Na+(out) => D-mannose(in) + Na+(in).

RHEA:72908 D-mannose(out) + Na+(out) => D-mannose(in) + Na+(in)
Evidence:
PubMed=24573086, see Fig. 2 and 4.
PubMed=22212718, see Fig. 2.
PubMed=23451068, see Fig. 1 and 2c,d (D-mannose explicitly mentioned)
https://www.rhea-db.org/rhea/72908

*
new GO: fructose:sodium symporter activity
child of 
GO:0005353    fructose transmembrane transporter activity
GO:0005402    carbohydrate:cation symporter activity
GO:0015370    solute:sodium symporter activity

RHEA:72915 D-fructose(out) + Na+(out) = D-fructose(in) + Na+(in)  
Evidence:
PubMed=22212718, see Fig. 2.
PubMed=23451068, see Fig. 1 and 2c,d (D-Fuctose explicitly mentioned)
http://internal.rhea-db.org/rhea/72915

Definition: Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: D-fructose(out) + Na+(out) = D-fructose(in) + Na+(in).

*
Looking forward to your feedback.

Many thanks
Nevila Hyka-Nouspikel

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140929
+name: mannose:sodium symporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: D-mannose(out) + Na+(out) = D-mannose(in) + Na+(in)." [PMID:22212718, PMID:23451068, PMID:24573086]
+intersection_of: GO:0015293 ! symporter activity
+intersection_of: has_primary_input CHEBI:16024 ! D-mannose
+intersection_of: has_primary_input CHEBI:29101 ! sodium(1+)
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24185 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-20T14:15:09Z
+
+[Term]
+id: GO:0140930
+name: fructose:sodium symporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: D-fructose(out) + Na+(out) = D-fructose(in) + Na+(in)." [PMID:22212718, PMID:23451068]
+intersection_of: GO:0015293 ! symporter activity
+intersection_of: has_primary_input CHEBI:15824 ! D-fructose
+intersection_of: has_primary_input CHEBI:29101 ! sodium(1+)
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24185 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-20T14:15:18Z

**Comment by nnouspikel** [comment]
Thanks a lot !
