### ISSUE TITLE
Term merge: GO:0052846 and GO:0101012

### ISSUE THREAD

**Issue by manulera** [geneontology/go-ontology#24181]
* **Term to be merged: GO:0101012:** inositol 1,5-bisdiphosphate 2,3,4,6-tetrakisphosphate 1-diphosphatase activity

* **Which term do you propose this term merge into? GO:0052846:** inositol-1,5-bisdiphosphate-2,3,4,6-tetrakisphosphate 1-diphosphatase activity

* **Reason for merge**: I think they are identical

* **Reference(s)**
PMID:26422458,  PMID:10827188

* **Any other information**
https://www.ebi.ac.uk/QuickGO/term/GO:0101012
https://www.ebi.ac.uk/QuickGO/term/GO:0052846

cc: @ValWood

**Comment by pgaudet** [comment]
Hi, 

Thanks for reporting this. I merged the terms and used the parent of GO:0052846, GO:0052841 inositol bisdiphosphate tetrakisphosphate diphosphatase activity as the superclass. 

Thanks, Pascale

**Comment by manulera** [comment]
Thanks! Closing

**Comment by pgaudet** [comment]
Thanks, but in our procedure the ticket gets closed automatically after the checks: https://github.com/geneontology/go-ontology/pull/24184

It's useful *not* to close manually, as if the checks fail we know that the ticket is not really completed. 

(in this case the tests should pass ;)

**Comment by sjm41** [comment]
@manulera @pgaudet @ValWood 
I think a similar merge may apply to these two terms?:

inositol 1-diphosphate 2,3,4,5,6-pentakisphosphate 1-diphosphatase activity (GO:0101011)
Def: myo-inositol 1-diphosphate 2,3,4,5,6-pentakisphosphate + H2O = myo-inositol hexakisphosphate + phosphate. PMID:26422458

and 

inositol-1-diphosphate-2,3,4,5,6-pentakisphosphate diphosphatase activity (GO:0052843)
Def: inositol 1-diphosphate 2,3,4,5,6-pentakisphosphate + H2O = inositol 1,2,3,4,5,6-hexakisphosphate + phosphate + 2 H+. PMID:10827188 PMID:11502751
