### ISSUE TITLE
NTR:thermomorphogenesis

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#24192]
* **Suggested term label:**
thermomorphogenesis

* **Definition (free text)**
The suite of morphological and architectural changes in an organism induced by high ambient temperatures, below the heat-stress range.

* **Reference, in format PMID:#######**
PMID: 27250752  (for definition)
PMID: 36155833 (for annotation)

* **Gene product name and ID to be annotated to this term**
WRKY14, AT1G30650

* **Parent term(s)**
response to temperature stimulus, GO:0009266
post-embryonic development, GO:0009791

* **Children terms (if applicable)** 
Wondering about regulation terms but after this week's GO meeting, leaning towards no on those.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140919
+name: thermomorphogenesis
+namespace: biological_process
+def: "The suite of morphological and architectural changes in an organism induced by high ambient temperatures, below the heat-stress range." [PMID:27250752]
+is_a: GO:0009266 ! response to temperature stimulus
+is_a: GO:0009791 ! post-embryonic development
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24192 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-17T06:30:55Z

**Comment by pgaudet** [comment]
WRT regulation: 

From PMID:27250752

> The transcription factor PHYTOCHROME INTERACTING FACTOR 4 (PIF4) has emerged as a critical player in regulating phytohormone levels and their activity. To control thermomorphogenesis, multiple regulatory circuits are in place to modulate PIF4 levels, activity and downstream mechanisms. 


So, it seem like PIF4 is part of thermomorphogenesis, but that there are also regulators, so I think in this case we could create the terms (+ and - regulation) - is that what you had in mind?

**Comment by tberardini** [comment]
I agree - please do add the +/- regulation terms when able.

**Comment by pgaudet** [comment]
Voilà 

+[Term]
+id: GO:0140920
+name: regulation of thermomorphogenesis
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of thermomorphogenesis." [PMID:27250752]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: regulates GO:0140919 ! thermomorphogenesis
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24192 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-18T07:34:53Z
+
+[Term]
+id: GO:0140921
+name: negative regulation of thermomorphogenesis
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of thermomorphogenesis." [PMID:27250752]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0140919 ! thermomorphogenesis
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24192 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-18T07:35:38Z
+
+[Term]
+id: GO:0140922
+name: positive regulation of thermomorphogenesis
+namespace: biological_process
+def: "Any process that increases the rate, frequency or extent of thermomorphogenesis." [PMID:27250752]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0140919 ! thermomorphogenesis
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24192 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-18T07:36:04Z

**Comment by tberardini** [comment]
Thank you very much!
