### ISSUE TITLE
"not for direct annotation" flags required

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24200]
- [x] GO:0051234    establishment of localization (no point if you do not know what is being localized)
- [x] GO:0110165    cellular anatomical entity (no point if you do not know the entity)
- [x] GO:0036211    protein modification process  (MF in BP)
GO:0043227    membrane-bounded organelle  (no point if you do not know the organelle)
GO:0006996    organelle organization (no point if you do not know the organelle)
GO:0022607    cellular component assembly (no point if you do not know the component, and many of these annotations are misleading anyways)

More than this,  for these examples I did not agree with the annotations that the high-level terms were derived from, otherwise descendants would be annotated, so the inferences are most likely incorrect anyways)

**Comment by ValWood** [comment]
GO:0043231 	intracellular membrane-bounded organelle 
(note this one is also used by PAINT), and I can't work out what the membrane-bounded organelle referred to is in all cases (for example one is a plasma membrane protein)

<img width="967" alt="Screenshot 2022-10-24 at 18 12 31" src="https://user-images.githubusercontent.com/7359272/197585702-18d189b4-3d0f-47fa-b6ee-183ce1788398.png">

**Comment by pgaudet** [comment]
PAINT issue reported in https://github.com/geneontology/go-annotation/issues/4400

**Comment by pfey03** [comment]
@ValWood 
Can protein modification process still be used for phenotypes? The children which are mF I will fix but this term itself?

**Comment by ValWood** [comment]
Hi @pfey03  currently there are only 38 direct annotations to "protein modification process", only 15 IMP and none for Dicty? 
I don't know if the term will survive long term, but probably it will since some modifications a (like ubiquitination, SUMOylation) are multistep
v

**Comment by pgaudet** [comment]
Hi @pfey03 

What would be the definition of "GO:0036211 protein modification process "?  Generally I think this corresponds to either protein maturation (glycosylation), or to signaling (other PTMs). Are there other cases for which 'protein modification process' would be needed? It does sound very vague, it's hard to argue it's a 'coordinated process'. 

Thanks, Pascale

**Comment by pfey03** [comment]
Phenotypes are different. I fixed all in GO but we annotate phenotypes for ages and I have so many strains to this term annotated. It's a pain with phenotypes fixing with all these GO changes.

**Comment by ValWood** [comment]
Isn't the best  solution to put the obsoleted terms into a mini ontology at UPHENO until they can be handled ( @cmungall suggested (it shouldn't be necessary to fix annotations, it's only the logical definitions in the uPHENO design patterns that need fixing).

We were discussing these modification terms at PomBase today  (we have over 100's of terms and >1000 annotations using GO modification defined phenotypes). Modification phenotypes should  be possible to define logically using PRO provided they have the necessary grouping terms for the modifications 
(note that in GO these terms did not have logical definitions, - if you follow the logical def through you just get abnormal GO:blah with no equivalence axioms- so this is really just a form of outsourcing which would need to be dealt with eventually)

**Comment by pfey03** [comment]
Well I don't think there will be some UPHENO ontology for these. Like in cell death they will add a PATO term that is good for all and then it  can be solved in different patterns. I have already changed 275 phenotypes by now with all the MF BP going. It is bottomless. But the 30 strains with protein modification will take me another week just doing that. I've been for weeks on updating phenotypes with current good GO, a few for chemorepellent Pascale added 2 new terms I could use for all these. Maybe protein modification I will have to delete quite some as there is no better term.

**Comment by ValWood** [comment]
@cmungall  is there a way to address this? I think I'm missing something, but I haven't needed to delete a single  phenotype annotation, even though we use GO in logical definitions throughout and have 1000's of annotations to these modification and cell death terms. Couldn't the terms we obsolete move into some temporary ontology until the  uPHENO group can manage the changes by finding an appropriate logical definition? The annotations shouldn't need updating at all,  just migrating? I'm stressing that people are losing good phenotype annotation even though this process is an absolutely necessary GO clean-up exercise. Also of note, I don't think a single one of these terms had a GO logical definition (otherwise uPHENO could use possibly use these logical defs directly (kim's suggestion). Many of us have been guilty of punting the problem of logically defining some phenotypes to GO....

**Comment by pfey03** [comment]
I'm even getting done today with my strains
