### ISSUE TITLE
NTR: L-kynurenine transmembrane  transport

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#24204]
Please provide as much information as you can: 

* **Suggested term label:**
L-kynurenine transmembrane transport

* **Definition (free text)**
The directed movement of L-kynurenine across a membrane

* **Reference, in format PMID:35245456

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
L-alpha-amino acid transmembrane transport

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140924
+name: L-kynurenine transmembrane transport
+namespace: biological_process
+def: "The directed movement of L-kynurenine across a membrane." [PMID:35245456]
+intersection_of: GO:0055085 ! transmembrane transport
+intersection_of: has_primary_input CHEBI:57959 ! L-kynurenine zwitterion
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24204 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-18T13:08:26Z
