### ISSUE TITLE
NTR: L-kynurenine transmembrane transporter activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#24205]
Please provide as much information as you can: 

* **Suggested term label:**
L-kynurenine transmembrane transporter activity

* **Definition (free text)**
Enables the transfer of L-kynurenine from one side of a membrane to the other.

* **Reference, in format PMID:35245456

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
L-amino acid transmembrane transporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140926
+name: L-kynurenine transmembrane transporter activity
+namespace: molecular_function
+def: "Enables the transfer of L-kynurenine from one side of a membrane to the other." [PMID:35245456]
+intersection_of: GO:0022857 ! transmembrane transporter activity
+intersection_of: has_primary_input CHEBI:57959 ! L-kynurenine zwitterion
+relationship: part_of GO:0140924 ! L-kynurenine transmembrane transport
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24205 xsd:anyURI
+created_by: pg
+creation_date: 2022-10-18T13:14:59Z
