### ISSUE TITLE
NTR:  N-acetyl-L-cysteine:glutamate antiporter activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#24235]
Please provide as much information as you can: 

* **Suggested term label:**
 N-acetyl-L-cysteine:glutamate antiporter activity

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction:  N-acetyl-L-cysteine(out) + glutamate(in) =  N-acetyl-L-cysteine(in) + glutamate(out). 

* **Reference, in format PMID:34120018

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0140323: solute:anion antiporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
[Rhea:74567]
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Hi @Argoudpuy 
I dont think this is physiological, this is a drug, according to the abstract it is using the cystine/glutamate transporter xCT  - which corresponds to GO:0015327 'cystine:glutamate antiporter activity' (see also https://tcdb.org/search/result.php?tc=2.A.3.8.5) 

You should use that term with 'has input' N-acetyl-L-cysteine. 

OK ? 

Thanks, Pascale

**Comment by Argoudpuy** [comment]
Hi Pascale,
ok I create an extension
Thanks
Guilaine
