### ISSUE TITLE
Advice: development terms related to the plant endodermis

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#24248]
Review of recent QC reports showed that there are some plant genes annotated to %endoderm% biological process terms. The two I was looking at were CACAO annotations to 'endodermal cell fate specification , GO:0001714'. It looks like most (all?) such terms are linked (transitively?) to the CL term for endoderm. Reading the def of the above term doesn't give the clue that it is animal specific. 

> The cell fate determination process that results in a cell becoming capable of differentiating autonomously into an endoderm cell in an environment that is neutral with respect to the developmental pathway; upon specification, the cell fate can be reversed. Source: GOC:go_curators)

There are several plant anatomy terms that share this root word and GO BP terms exist that look from the surface like they would apply to plants as well.

https://browser.planteome.org/amigo/search/ontology?q=endoderm
http://amigo.geneontology.org/amigo/search/ontology?q=endoderm

Example paper:
SCARECROW-LIKE23 and SCARECROW jointly specify endodermal cell fate but distinctly control SHORT-ROOT movement
http://doi.org/10.1111/tpj.13038

How would you like to handle this situation?
Should we request terms that are specific to the plant endodermis like 'plant endodermal cell fate specification?' Does it make sense to rename the existing generic sounding terms to something like 'animal endodermal cell fate specification?'

**Comment by tberardini** [comment]
@lreiser Looping you in.

**Comment by raymond91125** [comment]
It appears that endoderm (animal embryo) and endodermis (plant ground tissue) were meant to indicate the *inner* cell layer in different anatomical contexts. Thus it would not make sense to mix them together. As it was pointed out, the existing GO terms are defined by the animal specific term CL:00000223 endodermal cell.
Is the word "endomermis" restricted to plants? If so:
I think it would be best if GO have endodermis-specific terms that are logically defined with a CL or Uberon term (perhaps "cell of endodermis", "endodermis, respectively). The CL and Uberon terms would be defined as plant-specific and the GO terms will inherit the taxon constraints.
In GO, we could have terms that are, e.g. "endodermal cell fate specification, plant ground tissue" and they are 'siblings' (not child) of "endodermal cell fate specification". @pgaudet Are terms like that OK still?

**Comment by pgaudet** [comment]
Thanks for looking into this @raymond91125 

This does seem reasonable, the animal and plant processes must be very different. 

So, we'd need to split  GO:0035987 endodermal cell differentiation - I dont see plant annotations to the other terms when you query http://amigo.geneontology.org/amigo/search/ontology?q=endoderm

Thanks, Pascale

**Comment by tberardini** [comment]
Thanks @pgaudet  and @raymond91125 for your insights.

I think the logical definitions for the plant-specific terms should use PO terms as neither CL nor UBERON contain plant terms.  That may have changed but I don't think so.

https://browser.planteome.org/amigo/term/PO:0000252

The two existing terms with A. thaliana annotations that I see are the following:

endodermal cell fate specification
http://amigo.geneontology.org/amigo/term/GO:0001714

endodermal cell differentiation
http://amigo.geneontology.org/amigo/term/GO:0035987

Having separate terms for the plant processes would be great and we can transfer the annotations from the animal one to the plant one after they are created. There are multiple parents for the current terms, some of which are generic but some are animal specific so the sibling status may be only appropriate under some of those parent terms.


plant endodermal cell fate specification
plant endodermal cell differentiation

**Comment by lreiser** [comment]
Probably want to look at the taxon constraints here too. I am pretty sure  that at some point may have moved some TAIR annotations because of previous taxon constraint. But  I can't remember...

**Comment by raymond91125** [comment]
https://browser.planteome.org/amigo/term/PO:0000252 endodermis is a tissue. Is there a PO for endodermal cell?

**Comment by tberardini** [comment]
It was requested a while ago on the PO tracker. I'm trying to see if there's any progress possible.
https://github.com/Planteome/plant-ontology/issues/618

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160057
+name: plant endodermal cell fate specification
+namespace: biological_process
+def: "The process in which a cell becomes capable of differentiating autonomously into a plant endodermal cell in an environment that is neutral with respect to the developmental pathway. Upon specification, the cell fate can be reversed." [PMID:26415082]
+is_a: GO:0001708 ! cell fate specification
+created_by: rynl
+creation_date: 2022-10-25T05:56:54Z
+
+[Term]
+id: GO:0160058
+name: plant endodermal cell differentiation
+namespace: biological_process
+def: "The process in which a relatively unspecialized cell acquires specialized features of a plant endodermal cell." [PMID:21735349]
+is_a: GO:0030154 ! cell differentiation
+created_by: rynl
+creation_date: 2022-10-25T06:12:17Z

**Comment by raymond91125** [comment]
Thanks. Please reopen or start a new ticket when plant endodermal cell becomes available and we can add the logical definition.

**Comment by tberardini** [comment]
@raymond91125  Will do. Thank you.
