### ISSUE TITLE
Term merge:  fatty-acyl-CoA reductase (alcohol-forming) activity & alcohol-forming fatty acyl-CoA reductase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24250]
Do you think these two meant to refer to the same thing?

id: GO:0080019
name: fatty-acyl-CoA reductase (alcohol-forming) activity
def: "Catalysis of the reaction: a very long chain fatty acyl-CoA + NADPH + H+ = a very long chain primary alcohol + NADP+ + CoA." [PMID:16980563]
synonym: "fatty acyl CoA reductase (alcohol-forming) activity" EXACT []
synonym: "fatty acyl-CoA reductase (alcohol-forming) activity" EXACT [GOC:mah]
is_a: GO:0016620 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor

id: GO:0102965
name: alcohol-forming fatty acyl-CoA reductase activity
def: "Catalysis of the reaction: 2 NADPH + 2 H+ + a long-chain acyl-CoA = coenzyme A + 2 NADP + a long-chain alcohol." [EC:1.2.1.84, GOC:pz]
xref: EC:1.2.1.84
xref: MetaCyc:RXN-9344
xref: RHEA:52716
is_a: GO:0016620 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor

FYI, EC:1.2.1.84 is:
alcohol-forming fatty acyl-CoA reductase.
a long-chain fatty acyl-CoA + 2 H(+) + 2 NADPH <=> a long-chain primary fatty alcohol + CoA + 2 NADP(+)

Looks like they should be merged to me.
But if there is a reason to keep both, can we (i) make the term names and defs have a consistent format, and (ii) add 'long chain' and 'very long chain' to the term names to better distinguish them?

**Comment by deustp01** [comment]
Note also the difference in stoichiometry, 2 NADP (GO:0102965) vs 1 NADP (GO:0080019) per fatty acyl CoA reduced. EC and RHEA say 2 NADP. The two human enzymes are said to prefer C16 and C18 - long chain, not very long chain - Chang and Russell PMID: 15220348
@tberardini TAIR appears to have made the most annotations to GO:0080019 based on direct assay evidence - any opinion here?

**Comment by tberardini** [comment]
Neither of the papers that I looked at stated anything about the stoichiometry. Given both existing terms, if I were to annotate a fatty acyl-CoA reductase today, I would look up the length of the fatty acid that was tested in the experiment to see if it was long chain or very long chain and pick a term that way.

**Comment by pgaudet** [comment]
**Length of fatty acids** (https://en.wikipedia.org/wiki/Fatty_acid#Long_and_short)

* [Short-chain fatty acids](https://en.wikipedia.org/wiki/Short-chain_fatty_acids) (SCFA) are fatty acids with [aliphatic](https://en.wikipedia.org/wiki/Aliphatic) tails of five or fewer [carbons](https://en.wikipedia.org/wiki/Carbon) (e.g. [butyric acid](https://en.wikipedia.org/wiki/Butyric_acid)).[[7]](https://en.wikipedia.org/wiki/Fatty_acid#cite_note-7)
* [Medium-chain fatty acids](https://en.wikipedia.org/wiki/Medium-chain_fatty_acids) (MCFA) are fatty acids with aliphatic tails of 6 to 12[[8]](https://en.wikipedia.org/wiki/Fatty_acid#cite_note-e-medicine-8) carbons, which can form [medium-chain triglycerides](https://en.wikipedia.org/wiki/Medium-chain_triglyceride).
* Long-chain fatty acids (LCFA) are fatty acids with aliphatic tails of 13 to 21 carbons.[[9]](https://en.wikipedia.org/wiki/Fatty_acid#cite_note-lipidworld-9)
* [Very long chain fatty acids](https://en.wikipedia.org/wiki/Very_long_chain_fatty_acids) (VLCFA) are fatty acids with aliphatic tails of 22 or more carbons.d)

**Comment by pgaudet** [comment]
Hi, 

I downloaded all direct EXP annotations to GO:0080019 fatty-acyl-CoA reductase (alcohol-forming) activity 
https://docs.google.com/spreadsheets/d/1fk-RVpASu2xaUKo9_hlcSUStovgnKz_64TNlz0R21Sk/edit#gid=0

All except 2 Arabidopsis papers (TAIR:Publication:501719916|PMID:16980563 & TAIR:Publication:501729391|PMID:19062129) mention long chain fatty acids.  Even these 2 papers detect long chain fatty acid synthesis in E.coli or yeast, suggesting that the activity may depend on the subtrates available. 

@kaxelsen @lbreuza have annotated these plant entries (a while ago, I understand if you dont remember the details!) 
@kaxelsen do you know why 'very long chain' is not in EC (and I cannot find it in RHEA either)?  Have you guys assigned the long chain and very long chain FA substrates to the same activity? 

Thanks, Pascale

**Comment by kaxelsen** [comment]
If you refer to EC 1.2.1.84, the comments state: 
The enzyme has been characterized from the plant Simmondsia chinensis (jojoba). The alcohol is formed by a four-electron reduction of fatty acyl-CoA. Although the reaction proceeds through an aldehyde intermediate, a free aldehyde is not released. The recombinant enzyme was shown to accept saturated and mono-unsaturated fatty acyl-CoAs of 16 to 22 carbons.

So, EC 1.2.1.84 is created for long chain and not very long chain.

**Comment by pgaudet** [comment]
Thanks @kaxelsen 
Is there another EC /RHEA for very long chain?

**Comment by kaxelsen** [comment]
For the time being, no.

**Comment by deustp01** [comment]
Here are two papers that from their abstracts look like they present evidence for a reductase that can convert very long chain fatty acids to fatty alcohols, in Arabidopsis (PMID: [16980563](https://pubmed.ncbi.nlm.nih.gov/16980563)) and in humans ([PMID: 35238077](https://pubmed.ncbi.nlm.nih.gov/35238077/)). Note that the second paper attributes this activity to FAR2, while Chang & Russell, above ([PMID: 15220348](https://pubmed.ncbi.nlm.nih.gov/15220348/)) say acts on long-chain, not very long chain, fatty acids, so there may be a conflict here.

**Comment by sjm41** [comment]
Thanks Peter!  (Note the Arabidopsis paper (PMID:16980563) is the one mentioned by Pascale in her previous comment and in the spreadsheet).

So...it looks like the two terms should both be retained and we should: (i) make the term names and defs have a consistent format, and (ii) add 'long chain' and 'very long chain' to the term names to better distinguish them. ?

**Comment by deustp01** [comment]
That all sounds good to me. There's still the factual discrepancy between substrate specificities (chain length) asserted by [PMID: 15220348](https://pubmed.ncbi.nlm.nih.gov/15220348/) and by [PMID: 35238077](https://pubmed.ncbi.nlm.nih.gov/35238077/), but regardless of that, it is clear that long-chain and very-long-chain fatty alcohols exist and the processes that generate them can be distinguished (though maybe not at a reaction-mechanism level, so perhaps only one EC and one Rhea is still correct for both GO terms - @kaxelsen ?

**Comment by sjm41** [comment]
Hi @pgaudet 

I believe the main outstanding task here is to make the term names consistent and clearer.  I suggest:

- [ ] Rename 'fatty-acyl-CoA reductase (alcohol-forming) activity' (GO:0080019) to 'alcohol-forming very long-chain fatty acyl-CoA reductase activity'
- [ ] Rename 'alcohol-forming fatty acyl-CoA reductase activity' (GO:0102965) to 'alcohol-forming long-chain fatty acyl-CoA reductase activity'

**Comment by sjm41** [comment]
@pgaudet I think there's just a couple of quick term name changes to do here (see my previous comment) - then this can be closed.
