### ISSUE TITLE
obsoletion: GO:0046838 phosphorylated carbohydrate dephosphorylation and descendants

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24269]
* **GO term ID and Label**

GO:0046838 phosphorylated carbohydrate dephosphorylation
GO:0033518 myo-inositol hexakisphosphate dephosphorylation
GO:0046855 inositol phosphate dephosphorylation

* **Reason for deprecation**

Single step (inositol phosphatase)

* **"Replace by" term (ID and label)**

BP GO:0043647   inositol phosphate metabolic process

may also want to check that the appropriate MF is annotated under:
MF GO:0052745   inositol phosphate phosphatase activity
(ideally a specific child term would be used)

* **Are there annotations to this term?**
- How many EXP: 46

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

**Comment by ValWood** [comment]
Also
GO:0046838  phosphorylated carbohydrate dephosphorylation
GO:0033518   myo-inositol hexakisphosphate dephosphorylation

mappings
InterPro:IPR000760

**Comment by ValWood** [comment]
- [x] obsoletion notice sent

**Comment by pgaudet** [comment]
Aim to obsolete on Dec 5th (to give more time because of the Thanksgiving holidays)
