### ISSUE TITLE
Missing parent: GO:0035004	phosphatidylinositol 3-kinase activity (descendants)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24265]
* **GO term ID and label for which you request a new superclass**

Should 
GO:0035004	phosphatidylinositol 3-kinase activity
Be a parent of
	inositol tetrakisphosphate 3-kinase activity
And
	inositol-1,4,5-trisphosphate 3-kinase activity

**Comment by hdrabkin** [comment]
GO:0035004  is a EC:2.7.1.-, as are the i inositol tetrakisphosphate 3-kinase activity and inositol-1,4,5-trisphosphate 3-kinase activity; so are sibs really;
'Transferases Transferring phosphorus-containing groups; Phosphotransferases with an alcohol group as acceptor'

**Comment by ValWood** [comment]
ok
