### ISSUE TITLE
endopolyphosphatase activity (possible merge or obsolete)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24268]
<img width="615" alt="Screenshot 2022-10-25 at 14 30 05" src="https://user-images.githubusercontent.com/7359272/197843023-e9695030-b55b-42e7-b639-769688b1c858.png">

Is 
	endopolyphosphatase activity
A useful grouping term?

And if so, should it be a parent of

	GO:0034431	bis(5'-adenosyl)-hexaphosphatase activity
	GO:0034432	bis(5'-adenosyl)-pentaphosphatase activity
	GO:0008486	diphosphoinositol-polyphosphate diphosphatase activity
	GO:0050072	m7G(5')pppN diphosphatase activity
	GO:0047710	bis(5'-adenosyl)-triphosphatase activity

but I think it could be obsoleted and things would either be reannotated to 
pyrophosphatase of one of the descendants. It is a bit orthogonal and most thing are annotated to  two terms.
It could probably be a synonym of  pyrophosphatase ?

Note the definition is
Catalysis of the reaction: polyphosphate + n H2O = (n+1) oligophosphate. The product contains 4 or 5 phosphate residues.
(I',m not even sure that the second part is true but it isn't part of the necessary and sufficient bit of the def which matches the parent?)

**Comment by hdrabkin** [comment]
I think the chemistry disagrees

 GO:0000298 endopolyphosphatase activity
EC 3.6.1.10
[phosphate](n+1) + n H2O <=> n H(+) + (n+1) phosphate         <<<<< a polyphosphate
RHEA:22452
phosphate](n+1) + n H2O = n H+ + (n+1) phosphate

Example:
GO:0034431 
EC 3.6.1.60 diadenosine hexaphosphate hydrolase (AMP-forming)
RHEA:32047; 
Note the substrates; 3.6.1.10 works on a polyphosphate; that is not the substrate of EC:36.1.60 (CHEBI:63740)
These are all sibs with an EC class 3.6.1.-
None of the other term's substrates are classified as 'polyphosphates' in CHEBI.

@kaxelsen , what do you think?

**Comment by ValWood** [comment]
I thought 
bis(5'-adenosyl)-hexaphosphatase/ bis(5'-adenosyl)-pentaphosphatase activity
are dinucleotide polyphosphate/bis(5'-adenosyl)-triphosphatase 
are dinucleoside polyphosphates


GO:0008486	diphosphoinositol-polyphosphate diphosphatase activity
has polyphosphate in the term name

pppN diphosphatase looks 'polyphosphate -ish

**Comment by hdrabkin** [comment]
I think the use of 'polyphosphate' in the term names is a bit misleading; the CHEBI term for polyphosphate has only phosphate to phosphate esters; 

I would want to hear from CHEBI also (I put ticket in https://github.com/ebi-chebi/ChEBI/issues/4303)
GO:0008486 diphosphoinositol-polyphosphate diphosphatase activity, 
has polyphosphate in the term name
 EC:3.6.1.52:   again, a sib of EC:3.6.1.10; 
The RHEAS associated with 3.6.1.52 (three, GO:0008486 diphosphoinositol-polyphosphate diphosphatase activity
has polyphosphate in the term name) uses the exact substrate name in the reaction.

**Comment by ValWood** [comment]
Note also that the gene product for arg82 is described as a "polyphosphate kinase"
https://www.yeastgenome.org/locus/YDR173C
and UniProt, eg human
https://www.uniprot.org/uniprotkb/Q8NFU5/entry

but here the specificity doe not seem to be phosphate-phosphate esters:
<img width="492" alt="inositol" src="https://user-images.githubusercontent.com/7359272/198297320-742c6785-1f2e-4a5e-b18a-2303deb8c243.png">

If CHEBI is correct, these will also need fixing.

**Comment by kaxelsen** [comment]
@hdrabkin I agree. The definition fits EC 3.6.1.10 for which the substrate is a polymer of phosphate units.
In all the terms @ValWood suggests could be child terms, the 'poly' refers to a number of phosphate groups attached to a nucleoside or inositol. The same is true for arg82.

**Comment by ValWood** [comment]
Right so this is all OK? Close?
