### ISSUE TITLE
nociception is not the same as sensory perception of pain

### ISSUE THREAD

**Issue by wdduncan** [geneontology/go-ontology#24277]
**GO term**
GO:0019233 'sensory perception of pain' 

**Issue description**
'sensory perception of pain' `has_exact_synonym` nociception  

According this [reference](https://www.physio-pedia.com/Nociception):
> The terms nociception and [pain](https://www.physio-pedia.com/Pain_Behaviours) should not be used synonymously, because each can occur without the other.[[1]](https://www.physio-pedia.com/Nociception#cite_note-1.-1). [Pain](https://www.physio-pedia.com/Pain_Mechanisms) arising from activation of the nociceptors is called nociceptive pain.

**Comment by wdduncan** [comment]
nociception  may be a better synonym for `detection of stimulus involved in sensory perception of pain`

**Comment by raymond91125** [comment]
See also https://pain.ucsf.edu/understanding-pain-pain-basics/nociception-versus-pain. Thus, nociception may (or may not) lead to pain and pain may (or may not) be induced by nociception. I think the best synonymous relationship is "related".
Nociception is the "the neural process of encoding noxious stimuli" and we should have a stand-alone GO term for that.

**Comment by raymond91125** [comment]
It seems that this issue is more deeply entangled. Uberon nociceptor is logically defined as "'sensory receptor'
 and ('capable of' some 'detection of mechanical stimulus involved in sensory perception of pain')". Thus I think an agreement among more people is needed to either rename "sensory perception of pain" as nociception or to create a new term nociception. But then it's unclear what "sensory perception of pain" is. 
PMID:29032407 states that "Nociception is the neural process of encoding noxious stimuli, whereas pain is defined as an unpleasant sensory and emotional experience associated with actual or potential tissue damage, or described in terms of such damage".
IASP https://www.iasp-pain.org/resources/terminology/ definition of nociceptor: A high-threshold sensory receptor of the peripheral somatosensory nervous system that is capable of transducing and encoding noxious stimuli.

**Comment by wdduncan** [comment]
@raymond91125 Yes. I originally rain across this issue b/c I was working with UBERON (cc @cmungall ).

> PMID:29032407 states that "Nociception is the neural process of encoding noxious stimuli, whereas pain is defined as an unpleasant sensory and emotional experience associated with actual or potential tissue damage, or described in terms of such damage". 

Thanks for including this.

**Comment by raymond91125** [comment]
Well, even though nociception and pain are not the same per se, it seems that in the literature, nociception and the sensory perception of pain are not different. That is, there does not seem to be another type of sensory perception of pain and nociceptor is synonymous with pain receptor. @wdduncan have you come across anything contradicting?

**Comment by wdduncan** [comment]
Re: nociception vs. sensory perception of pain   

I suppose it depends what is meant by `sensory perception of pain `. The current definition reads:
> The series of events required for an organism to receive a painful stimulus, convert it to a molecular signal, and recognize and characterize the signal. Pain is medically defined as the physical sensation of discomfort or distress caused by injury or illness, so can hence be described as a harmful stimulus which signals current (or impending) tissue damage. Pain may come from extremes of temperature, mechanical damage, electricity or from noxious chemical substances. This is a neurological process.

I would agree that nociception is a part of this part this process. It seems a bit strong to specify that nociception is an exact synonym of `sensory perception of pain` (IMHO).

To be honest, I don't completely understand what it means for nociception to be the process that "encodes" the noxious stimulus (as defined in the [IASP terminology](https://www.iasp-pain.org/resources/terminology/), and how nociception (in the IASP sense) is distinct from `detection of stimulus involved in sensory perception of pain`, which is defined as:
> The series of events involved in the perception of pain in which a stimulus is received and converted into a molecular signal.

Depending what is meant by "encodes", it seems that nociception may be part of `detection of stimulus involved in sensory perception of pain` too.

**Comment by raymond91125** [comment]
I randomly checked some references that provide the evidence for EXP annotations to GO:0019233 'sensory perception of pain' directly; 8 of 8 mention nociception. Thus the usage of this term appears consistently to be about nociception.

**Comment by wdduncan** [comment]
Sure ... consistent use doesn't mean correct use, though.

**Comment by wdduncan** [comment]
@raymond91125 We've had a lot of back and forth :)   

So, to summarize, the IASP makes a distinction between nociception (neural process of encoding noxious stimuli) and pain, 'pain' being defined as "an unpleasant sensory and emotional experience associated with actual or potential tissue damage, or described in terms of such damage". That is, nociception can occur without the unpleasant sensory and emotional experience of pain.

The GO definition of `sensory perception of pain` is ambiguous about whether this entails a sensory experience. So, all I am suggesting is that the `has_exact_synonym nociception` be dropped or changed to `has_related_synonym nociception` (which you proposed).

**Comment by raymond91125** [comment]
@wdduncan Thank you for your patience. I will bring this up in our ontology editor meeting (as soon as next week). My concern about the action 'has_related_synonym nociception' is that nociception is an important biological process that should be more formally represented in GO, not just as a related synonym.
The examples I've read (e.g.  https://pain.ucsf.edu/understanding-pain-pain-basics/nociception-versus-pain) to distinguish between nociception and the perception of pain are about conditions that may be considered abnormal (patient under general anesthesia or patient with central neuropathic pain after stroke). Thus, 'normally', perhaps the sensory input that leads to pain is exclusively nociception. I don't have the answer.
Nociception is more generally applicable to animals and readily definable whereas pain may be more relevant to human perception and experiences.

**Comment by raymond91125** [comment]
@wdduncan I made the change of nociception as a related synonym, since @ukemi pointed out that in GO lingo "sensory perception" covers the CNS part of 'interpretation' (recognition). As you pointed out, "detection of stimulus involved in sensory perception of pain" is probably an exact synonym for nociception instead.

**Comment by wdduncan** [comment]
Thanks @raymond91125 !
