### ISSUE TITLE
Obsoletion notice: GO:1903171 carbon dioxide homeostasis & GO:1903172 cellular carbon dioxide  homeostasis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24274]
Dear all, 

The proposal has been made to obsolete GO:1903171 carbon dioxide homeostasis & GO:1903172 cellular carbon dioxide  homeostasis. The reason for obsoletion is that there is no evidence that these processes exist, i. e. that there are pathways that maintain the levels of CO2 in the body or in cells. The terms cite PMID:16571594, which talk about pH homeostasis. 

There are no annotations to these terms, these terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24274

Thanks, Pascale

**Comment by raymond91125** [comment]
PMID:26335642 Neural Control of Breathing and CO2 Homeostasis

**Comment by raymond91125** [comment]
At least organismal level CO2 homeostasis is well established (it may be mediated through blood pH).

**Comment by pgaudet** [comment]
Hi @raymond91125 

Thanks for this, it's great to have a second pair of eyes on these issues! 

Paul and I also noticed how 'homeostasis' was used in very inconsistent ways in the literature. For GO this means that the cell/organism has a program to regulate the level of the chemical. For CO2 what I understand is that lungs eliminate it as a waste product, the organism doesn't try to have a steady-state level of CO2. 

https://pubmed.ncbi.nlm.nih.gov/26068853/ may have a better was to formulate this, ie  'respiratory chemosensitivity'  - "A homeostatic process by which the sensing of CO2 and/or H+ by the brain leads to appropriate altering in breathing to regulate blood gas and tissue pH." 


So a proposal could be to 

- [ ] create that new term 'respiratory chemosensitivity', as a child of 'multicellular organismal homeostasis' (for now) - ideally we would have a more general parent like 'multicellular organismal pH homeostasis' 

I would have proposed to 'recycle' GO:1903171 carbon dioxide homeostasis but @cmungall suggests we move away from this practice. 

- [ ] GO:1903171 carbon dioxide homeostasis could have 'replaced by' the new term. 
- [ ] The cellular version (GO:1903172 cellular carbon dioxide homeostasis) must be obsoleted. 

What do you think ? 


Thanks, Pascale

**Comment by pfey03** [comment]
Yes I checked Dicty annotations with all ECO in QuickGO and there are no annotations not electronic or IBA either to GO:190317 or any of it's children.

**Comment by raymond91125** [comment]
Thanks.

**Comment by pgaudet** [comment]
New term: 

[Term]
id: GO:0160061
name: respiratory chemosensitivity
namespace: biological_process
def: "A homeostatic process by which the sensing of CO2 and/or H+ by the brain leads to appropriate altering in breathing to regulate blood gas and tissue pH." [PMID:26068853]
is_a: GO:0048871 ! multicellular organismal homeostasis
created_by: rynl
creation_date: 2022-10-31T00:43:20Z
