### ISSUE TITLE
is sensory perception of pain meant to be the same as the subjective feeling of pain

### ISSUE THREAD

**Issue by wdduncan** [geneontology/go-ontology#24278]
I am developing on a pain ontology for annotating pain studies. GO has the term `sensory perception of pain` and the emotion ontology has the term [feeling of pain](https://ontobee.org/ontology/MFOEM?iri=http://purl.obolibrary.org/obo/MFOEM_000203).  

Is the term `sensory perception of pain` intended to rise to the level consciously feeling pain? The first part of the definition says:
```
The series of events required for an organism to receive a painful stimulus, convert it to a molecular signal, and recognize and characterize the signal.
```
It is difficult for me to tell if "characterize the signal" means that the signal is consciously registered as pain.

**Comment by cmungall** [comment]
Very cool and interesting question!

The thing to remember is that GO is a multispecies ontology. Let's take a look at:

http://amigo.geneontology.org/amigo/term/GO:0019233

and look at the organism facet - you will see fly, worm, ...

We could get into really interesting discussions about whether these organisms are conscious, what is consciousness anyway...

But I think that is something GO should stay away from!

And indeed the current GO definition doesn't mention subjective feelings at all, it is intentionally neutral.

I'll close this as I think this answers your question but feel free to reopen if there is something actionable you would like to see done. I think the question of how to relate EMO terms to GO biological processes is an interesting one, but that would be for the EMO issue tracker I think

**Comment by wdduncan** [comment]
@cmungall After thinking about it a bit, I'll think I can just use `sensory perception of pain` for pain scores (e.g., pain score is about sensory perception of pain). I want to stay clear of philosophy of mind debates .... for now :)
