### ISSUE TITLE
NTR cellular response to disruption of membrane integrity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24286]
more details to be provided by @sylvainpoux

**Comment by sylvainpoux** [comment]
Hi Pascale,

NLRP3 inflammasome is activated by many different stimuli and none of them seems to directly bind NLRP3 , the sensor component of the inflammasome.

From recent papers (PMID:30487600, PMID:23582325), all evidences point to activation in response to defects in membrane integrity. However, I cannot find it concerns all membranes or only specific ones. And molecular mechanisms are still unclear. I therefore think that we cannot create a term yet.

I will keep an eye on this topic and let you know if we have more information

Sorry for the inconvenience

Sylvain

**Comment by pgaudet** [comment]
Thanks for looking into that! Closing.
