### ISSUE TITLE
Obsoletion notice: Children of histone modification (single step process):

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24294]
Dear all,

For the work on single-step BPs, we proposed to obsolete all children of '[GO:0016570 histone modification](http://amigo.geneontology.org/amigo/term/GO:0016570#display-lineage-tab)

The following terms have no annotations left 

- [x] GO:2001167 negative regulation of histone H2B ubiquitination
- [x] GO:2001174 negative regulation of histone H2B conserved C-terminal lysine ubiquitination 
- [x] GO:2001175 positive regulation of histone H2B conserved C-terminal lysine ubiquitination 
- [x] GO:1902028 regulation of histone H3-K18 acetylation
- [x] GO:1902030 negative regulation of histone H3-K18 acetylation
- [x] GO:1902029 positive regulation of histone H3-K18 acetylation 
- [x] GO:0150166 regulation of histone H3-K4 acetylation
- [x] GO:0150168 negative regulation of histone H3-K4 acetylation
- [x] GO:0150167 positive regulation of histone H3-K4 acetylation 
- [x] GO:1905435 regulation of histone H3-K4 trimethylation 
- [x] GO:1905436 negative regulation of histone H3-K4 trimethylation
- [x] GO:1905437 positive regulation of histone H3-K4 trimethylation  
- [x] GO:0000416 positive regulation of histone H3-K36 methylation 
- [ ] GO:1901314 regulation of histone H2A K63-linked ubiquitination
- [ ] GO:1901316 positive regulation of histone H2A K63-linked ubiquitination 
- [ ] GO:2001167 negative regulation of histone H2B ubiquitination 

Thanks, Pascale

**Comment by ValWood** [comment]
Note that this ticket only covers the terms with no annotations. Is there a ticket for all of the annotated terms yet?

**Comment by pgaudet** [comment]
This is the full list 

histone modification   (GO:0016570)
histone peptidyl-prolyl isomerization   (GO:0000412)
histone methylation (GO:0016571)
histone lysine methylation (GO:0034968)
histone H3-K36 methylation (GO:0010452)
histone H3-K36 trimethylation   (GO:0097198)
histone H3-K36 dimethylation (GO:0097676)
histone H3-K79 methylation (GO:0034729)
histone H4-K20 methylation (GO:0034770)
histone H4-K20 dimethylation (GO:0034772)
histone H4-K20 trimethylation   (GO:0034773)
histone H3-K9 methylation (GO:0051567)
histone H3-K9 dimethylation (GO:0036123)
histone H3-K9 trimethylation (GO:0036124)
histone H3-K4 methylation (GO:0051568)
histone H3-K4 dimethylation (GO:0044648)
histone H3-K4 trimethylation (GO:0080182)
histone H3-K4 monomethylation   (GO:0097692)
histone H3-K27 methylation (GO:0070734)
histone H3-K27 trimethylation   (GO:0098532)
histone arginine methylation (GO:0034969)
histone H3-R2 methylation (GO:0034970)
histone H3-R17 methylation (GO:0034971)
histone H3-R26 methylation (GO:0034972)
histone H4-R3 methylation (GO:0043985)
histone glutamine methylation   (GO:1990258)
histone acetylation (GO:0016573)
histone H3 acetylation (GO:0043966)
histone H3-K9 acetylation (GO:0043970)
histone H3-K18 acetylation (GO:0043971)
histone H3-K23 acetylation (GO:0043972)
histone H3-K4 acetylation (GO:0043973)
histone H3-K27 acetylation (GO:0043974)
histone H3-K14 acetylation (GO:0044154)
histone H3-K56 acetylation (GO:0097043)
histone H4 acetylation (GO:0043967)
histone H4-K5 acetylation (GO:0043981)
histone H4-K8 acetylation (GO:0043982)
histone H4-K12 acetylation (GO:0043983)
histone H4-K16 acetylation (GO:0043984)
histone H2A acetylation (GO:0043968)
histone H2A-K5 acetylation (GO:0043977)
histone H2B acetylation (GO:0043969)
histone H2B-K5 acetylation (GO:0043979)
histone H2B-K12 acetylation (GO:0043980)
histone ubiquitination (GO:0016574)
histone monoubiquitination (GO:0010390)
histone H2A monoubiquitination   (GO:0035518)
histone H2A-K119 monoubiquitination   (GO:0036353)
histone H2A ubiquitination (GO:0033522)
histone H2A-K13 ubiquitination   (GO:0036351)
histone H2A-K15 ubiquitination   (GO:0036352)
histone H2A K63-linked ubiquitination   (GO:0070535)
histone H2B ubiquitination (GO:0033523)
histone H2B conserved C-terminal lysine   ubiquitination (GO:0071894)
histone deacetylation (GO:0016575)
histone H3 deacetylation (GO:0070932)
histone H3-K56 deacetylation (GO:0071572)
histone H3-K9 deacetylation (GO:1990619)
histone H4 deacetylation (GO:0070933)
histone H4-K16 deacetylation (GO:1990678)
histone H4-K12 deacetylation (GO:1990679)
histone demethylation (GO:0016577)
histone lysine demethylation (GO:0070076)
histone H3-K9 demethylation (GO:0033169)
histone H3-K4 demethylation (GO:0034720)
histone H3-K4 demethylation,   trimethyl-H3-K4-specific (GO:0034721)
histone H3-K36 demethylation (GO:0070544)
histone H3-K27 demethylation (GO:0071557)
histone H3-R2 demethylation (GO:0070078)
histone H4-R3 demethylation (GO:0070079)
histone deubiquitination (GO:0016578)
monoubiquitinated histone   deubiquitination (GO:0035521)
monoubiquitinated histone H2A   deubiquitination (GO:0035522)
histone H2B conserved C-terminal lysine   deubiquitination (GO:0035616)
histone H2A K63-linked deubiquitination   (GO:0070537)
histone H3-K9 modification (GO:0061647)
 
regulation of histone modification   (GO:0031056)
negative regulation of histone   modification (GO:0031057)
negative regulation of histone   methylation (GO:0031061)
negative regulation of histone H3-K36   methylation (GO:0000415)
negative regulation of histone H3-K36   trimethylation (GO:2001254)
negative regulation of histone H3-K4   methylation (GO:0051572)
negative regulation of histone H3-K9   methylation (GO:0051573)
negative regulation of histone H3-K9   dimethylation (GO:1900110)
negative regulation of histone H3-K9   trimethylation (GO:1900113)
negative regulation of histone H3-K27   methylation (GO:0061086)
negative regulation of histone H3-K27   trimethylation (GO:1902465)
negative regulation of histone H3-K79   methylation (GO:2001161)
negative regulation of histone   deacetylation (GO:0031064)
negative regulation of histone   deacetylase activity (GO:1901726)
negative regulation of histone   ubiquitination (GO:0033183)
negative regulation of histone H2A   K63-linked ubiquitination (GO:1901315)
negative regulation of histone   acetylation (GO:0035067)
negative regulation of histone H3-K14   acetylation (GO:0071441)
negative regulation of histone H4   acetylation (GO:0090241)
negative regulation of histone H4-K16   acetylation (GO:2000619)
negative regulation of histone H3-K27   acetylation (GO:1901675)
negative regulation of histone H3-K9   acetylation (GO:2000616)
negative regulation of histone   deubiquitination (GO:1903585)
negative regulation of histone   demethylase activity (H3-K4 specific) (GO:1904174)
positive regulation of histone   modification (GO:0031058)
positive regulation of histone   methylation (GO:0031062)
positive regulation of histone H3-K4   methylation (GO:0051571)
positive regulation of histone H3-K9   methylation (GO:0051574)
positive regulation of histone H3-K9   dimethylation (GO:1900111)
positive regulation of histone H3-K9   trimethylation (GO:1900114)
positive regulation of histone H3-K27   methylation (GO:0061087)
positive regulation of histone H3-K27   trimethylation (GO:1902466)
positive regulation of histone H4-K20   methylation (GO:0070512)
positive regulation of histone H3-K79   dimethylation (GO:1905473)
positive regulation of histone H3-K79   methylation (GO:2001162)
positive regulation of histone H3-K36   trimethylation (GO:2001255)
positive regulation of histone   deacetylation (GO:0031065)
positive regulation of histone   deacetylase activity (GO:1901727)
positive regulation of histone   ubiquitination (GO:0033184)
positive regulation of histone H2A   K63-linked ubiquitination (GO:1901316)
positive regulation of histone H2B   ubiquitination (GO:2001168)
positive regulation of histone   acetylation (GO:0035066)
positive regulation of histone H3-K14   acetylation (GO:0071442)
positive regulation of histone H4   acetylation (GO:0090240)
positive regulation of histone H4-K16   acetylation (GO:2000620)
positive regulation of histone H3-K27   acetylation (GO:1901676)
positive regulation of histone H3-K9   acetylation (GO:2000617)
positive regulation of histone   deubiquitination (GO:1903586)
positive regulation of histone   demethylase activity (H3-K4 specific) (GO:1904175)
regulation of histone methylation   (GO:0031060)
regulation of histone H3-K36 methylation   (GO:0000414)
regulation of histone H3-K36   trimethylation (GO:2001253)
regulation of histone H3-K4 methylation   (GO:0051569)
regulation of histone H3-K9 methylation   (GO:0051570)
regulation of histone H3-K9 dimethylation   (GO:1900109)
regulation of histone H3-K9   trimethylation (GO:1900112)
regulation of histone H3-K27 methylation   (GO:0061085)
regulation of histone H3-K27   trimethylation (GO:1902464)
regulation of histone H3-K79 methylation   (GO:2001160)
regulation of histone deacetylation   (GO:0031063)
regulation of histone deacetylase   activity (GO:1901725)
regulation of histone ubiquitination   (GO:0033182)
regulation of histone H2A K63-linked   ubiquitination (GO:1901314)
regulation of histone H2B ubiquitination   (GO:2001166)
regulation of histone H2B conserved   C-terminal lysine ubiquitination (GO:2001173)
regulation of histone acetylation   (GO:0035065)
regulation of histone H3-K14 acetylation   (GO:0071440)
regulation of histone H4 acetylation   (GO:0090239)
regulation of histone H4-K16 acetylation   (GO:2000618)
regulation of histone H3-K27 acetylation   (GO:1901674)
regulation of histone H3-K9 acetylation   (GO:2000615)
regulation of histone deubiquitination   (GO:1903584)
regulation of histone demethylase   activity (H3-K4 specific) (GO:1904173)

**Comment by pgaudet** [comment]
What's the problem with the list ?

**Comment by pgaudet** [comment]
Note that this excludes ubiquitination for now - this is because it not clear yet that this really is a single step, especially polyubiquitination. I would prefer to look at all ubiquitination together.

**Comment by ValWood** [comment]
the length ; (

**Comment by RLovering** [comment]
Hi

do I need a new term before this can be completed see PMID:17349954 proteins involved in Polyubiquitylation of H2AX
Although I am a bit confused about when it is OK to use histone modification terms. Is it OK to have regulation of H2AX polyubiquitylation term? 

Also would I need the term histone H2AX ubiquitin ligase activity

Thanks

Ruth

Ruth
