### ISSUE TITLE
obsolete GO:0000904 'cell morphogenesis involved in differentiation'

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#24299]
@cmungall and I are adding some GCIs which help to infer extra part_of edges for morphogenesis in #24280. After adding this axiom: 

[anatomical structure morphogenesis](http://purl.obolibrary.org/obo/GO_0009653) and ([results in morphogenesis of](http://purl.obolibrary.org/obo/RO_0002298) some [cell](http://purl.obolibrary.org/obo/CL_0000000)) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some 
([anatomical structure development](http://purl.obolibrary.org/obo/GO_0048856) and ([results in development of](http://purl.obolibrary.org/obo/RO_0002296) some [cell](http://purl.obolibrary.org/obo/CL_0000000))) 

we find that 'cell morphogenesis involved in differentiation' is logically equivalent to 'cell morphogenesis':

## [cell morphogenesis](http://purl.obolibrary.org/obo/GO_0000902) EquivalentTo [cell morphogenesis involved in differentiation](http://purl.obolibrary.org/obo/GO_0000904) ##

  - [cell morphogenesis](http://purl.obolibrary.org/obo/GO_0000902) EquivalentTo [anatomical structure morphogenesis](http://purl.obolibrary.org/obo/GO_0009653) and ([results in morphogenesis of](http://purl.obolibrary.org/obo/RO_0002298) some [cell](http://purl.obolibrary.org/obo/CL_0000000))
  - [anatomical structure development](http://purl.obolibrary.org/obo/GO_0048856) EquivalentTo [developmental process](http://purl.obolibrary.org/obo/GO_0032502) and ([results in development of](http://purl.obolibrary.org/obo/RO_0002296) some [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061))
  - [anatomical structure morphogenesis](http://purl.obolibrary.org/obo/GO_0009653) and ([results in morphogenesis of](http://purl.obolibrary.org/obo/RO_0002298) some [cell](http://purl.obolibrary.org/obo/CL_0000000)) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some 
([anatomical structure development](http://purl.obolibrary.org/obo/GO_0048856) and ([results in development of](http://purl.obolibrary.org/obo/RO_0002296) some [cell](http://purl.obolibrary.org/obo/CL_0000000)))
  - [developmental process](http://purl.obolibrary.org/obo/GO_0032502) SubClassOf [biological_process](http://purl.obolibrary.org/obo/GO_0008150)
  - [cell development](http://purl.obolibrary.org/obo/GO_0048468) EquivalentTo [biological_process](http://purl.obolibrary.org/obo/GO_0008150) and ([results in development of](http://purl.obolibrary.org/obo/RO_0002296) some [cell](http://purl.obolibrary.org/obo/CL_0000000))
  - [cell morphogenesis involved in differentiation](http://purl.obolibrary.org/obo/GO_0000904) EquivalentTo [cell morphogenesis](http://purl.obolibrary.org/obo/GO_0000902) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [cell development](http://purl.obolibrary.org/obo/GO_0048468))

We will also need to obsolete [regulation of cell morphogenesis involved in differentiation](http://purl.obolibrary.org/obo/GO_0010769).

**Comment by pgaudet** [comment]
Ontology call 2022-10-31 

Agree on the obsoletion of GO:0000904 'cell morphogenesis involved in differentiation'  - children can probably be rehoused under cellular component assembly + other terms.

**Comment by pgaudet** [comment]
Also; change term label 'cell morphogenesis involved in differentiation' to 'developmental cell morphogenesis', and this will be the genus of 'x cell morphogenesis'

**Comment by raymond91125** [comment]
I am confused by the LD for the term cell morphogenesis involved in differentiation -- 
cell morphogenesis and (part of some ***cell development***)
Shouldn't it be 
cell morphogenesis and (part of some ***cell differentiation***)?

![image](https://github.com/geneontology/go-ontology/assets/619520/1162828d-9ffa-483a-9efb-e945f6beb0ca)

Perhaps we should merge cell morphogenesis involved in differentiation into cell morphogenesis and also add a relationship cell morphogenesis PART_OF cell development.

@ukemi Do you think this makes sense?

**Comment by raymond91125** [comment]
@balhoff does that PR solve the problems?

**Comment by balhoff** [comment]
@raymond91125 @pgaudet possibly—I will need to update the PR and check.

**Comment by balhoff** [comment]
@pgaudet @raymond91125 the change does not fix the issue:

## [cell morphogenesis](http://purl.obolibrary.org/obo/GO_0000902) EquivalentTo [cell morphogenesis involved in differentiation](http://purl.obolibrary.org/obo/GO_0000904) ##

  - [cell morphogenesis](http://purl.obolibrary.org/obo/GO_0000902) EquivalentTo [anatomical structure morphogenesis](http://purl.obolibrary.org/obo/GO_0009653) and ([results in morphogenesis of](http://purl.obolibrary.org/obo/RO_0002298) some [cell](http://purl.obolibrary.org/obo/CL_0000000))
  - [anatomical structure development](http://purl.obolibrary.org/obo/GO_0048856) EquivalentTo [developmental process](http://purl.obolibrary.org/obo/GO_0032502) and ([results in development of](http://purl.obolibrary.org/obo/RO_0002296) some [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061))
  - [anatomical structure morphogenesis](http://purl.obolibrary.org/obo/GO_0009653) and ([results in morphogenesis of](http://purl.obolibrary.org/obo/RO_0002298) some [cell](http://purl.obolibrary.org/obo/CL_0000000)) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some 
([anatomical structure development](http://purl.obolibrary.org/obo/GO_0048856) and ([results in development of](http://purl.obolibrary.org/obo/RO_0002296) some [cell](http://purl.obolibrary.org/obo/CL_0000000)))
  -  Transitive: [part_of](http://purl.obolibrary.org/obo/BFO_0000050)
  - [developmental process](http://purl.obolibrary.org/obo/GO_0032502) SubClassOf [biological_process](http://purl.obolibrary.org/obo/GO_0008150)
  - [cell development](http://purl.obolibrary.org/obo/GO_0048468) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [cell differentiation](http://purl.obolibrary.org/obo/GO_0030154)
  - [cell development](http://purl.obolibrary.org/obo/GO_0048468) EquivalentTo [biological_process](http://purl.obolibrary.org/obo/GO_0008150) and ([results in development of](http://purl.obolibrary.org/obo/RO_0002296) some [cell](http://purl.obolibrary.org/obo/CL_0000000))
  - [cell morphogenesis involved in differentiation](http://purl.obolibrary.org/obo/GO_0000904) EquivalentTo [cell morphogenesis](http://purl.obolibrary.org/obo/GO_0000902) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [cell differentiation](http://purl.obolibrary.org/obo/GO_0030154))

**Comment by pgaudet** [comment]
Replacement terms for the regulation terms: 
* GO:0045595 regulation of cell differentiation
* GO:0045596 negative regulation of cell differentiation
* GO:0045597 positive regulation of cell differentiation

**Comment by raymond91125** [comment]
@pgaudet I am confused. Shouldn't it be that:
GO:0000904 cell morphogenesis involved in differentiation 'merge into' GO:0000902 cell morphogenesis
GO:0010769 regulation of cell morphogenesis involved in differentiation 'merged into' GO:0022604 regulation of cell morphogenesis
There are no positive/negative regulation of cell morphogenesis terms
GO:0010771 negative regulation of cell morphogenesis involved in differentiation
GO:0010770 positive regulation of cell morphogenesis involved in differentiation

**Comment by pgaudet** [comment]
You are right, these are is_a morphogenesis, but since the term also has 'involved in' (ie, the relation we use to link gene products and GO terms), it seems both terms would be suitable. 

But maybe it's safest to leave without a replacement, just 'consider'. There are 5 EXP, I appended to the review spreadsheet: https://docs.google.com/spreadsheets/d/1hvYeqnzHsyHq-IMHEAj-qOdipYR8dJocU90LceWwK1o/edit#gid=0

Does that work ? 

Thanks, Pascale

**Comment by raymond91125** [comment]
I believe the problem in the first place is that since cell morphogenesis *must be* part of cell differentiation, it is EquivalentTo cell morphogenesis involved in differentiation. That is, "cell morphogenesis involved in differentiation" is just another way of saying "cell morphogenesis". This is a true case of two terms that should be merged.
Moving annotations to cell differentiation may cause a loss of specificity as morphogenesis is a specific aspect of differentiation.  Another aspect is function.

**Comment by raymond91125** [comment]
The proposal is to
GO:0000904 cell morphogenesis involved in differentiation 'merge into' GO:0000902 cell morphogenesis
GO:0010769 regulation of cell morphogenesis involved in differentiation 'merged into' GO:0022604 regulation of cell morphogenesis
GO:0010771 negative regulation of cell morphogenesis involved in differentiation change label to negative regulation of cell morphogenesis
GO:0010770 positive regulation of cell morphogenesis involved in differentiation change label to positive regulation of cell morphogenesis
