### ISSUE TITLE
NTR: halotropism

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#24300]
Suggested term label:
halotropism
Syn: root halotropism

Definition (free text)
A sodium-specific negative tropism that is crucial for surviving and thriving under high salinity.

Reference, in format PMID:#######
https://doi.org/10.1016/j.devcel.2022.09.012
**->> this is PMID:36243013**

Gene product name and ID to be annotated to this term
SP2L, AT1G50890

Parent term(s)
tropism,     GO:0009606

**Comment by edwong57** [comment]
+[Term]
+id: GO:0170002
+name: halotropism
+namespace: biological_process
+def: "A sodium-specific negative tropism that is crucial for surviving and thriving under high salinity." [PMID:36243013]
+synonym: "root halotropism" EXACT []
+is_a: GO:0009606 ! tropism
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24300 xsd:anyURI
+created_by: ew
+creation_date: 2022-11-01T17:36:17Z

**Comment by tberardini** [comment]
Thank you @edwong57!
