### ISSUE TITLE
NTR: renal zinc excretion

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#24307]
For review https://github.com/geneontology/go-annotation/issues/4346

* **New term**
* renal zinc excretion

*is_a GO:0097254 renal tubular secretion

* **Definition (free text)**
The elimination of zinc ions from peritubular capillaries (or surrounding hemolymph in invertebrates) into the renal tubules to be incorporated subsequently into the urine.

* **Reference**
* PMID:28196538

* **Gene product name and ID to be annotated to this term**
* ZnT63C; FBgn0035432

**Comment by ValWood** [comment]
+[Term]
+id: GO:0180002
+name: renal zinc excretion
+def: "The elimination of zinc ions from peritubular capillaries (or surrounding hemolymph in invertebrates) into the renal tubules to be incorporated subsequently into the urine." [PMID:28196538]
+synonym: "renal zinc ion excretion" EXACT []
+synonym: "renal zinc secretion" EXACT []
+is_a: GO:0097254 ! renal tubular secretion
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24307 xsd:anyURI
+created_by: vw
+creation_date: 2022-11-01T17:35:12Z
