### ISSUE TITLE
 GO:0018741 alkyl sulfatase activity def restricts to dodecyl (C12H25) chains

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#24319]
* **GO term ID and label for which you request a definition update**
GO:0018741 alkyl sulfatase activity (https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0018741/complete)

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
New definition should be something generic, not referring to dodecyl:
Catalysis of the reaction: an alkyl sulfate ester + H2O <=> a primary alcohol + H(+) + sulfate

* **Reference(s)**
https://enzyme.expasy.org/EC/3.1.6.21
PMID: 28720494 https://doi.org/10.1016/j.bbrc.2017.07.092 -> source of attached image that shows alkyl sulfate hydrolysis on something other than C12

* **Additional information**
* the cross reference UM-BBD_reactionID  r0602 is quite narrow
 
![Screenshot 2022-11-03 at 14 42 54](https://user-images.githubusercontent.com/13735608/199830136-de2d2851-38ac-40b5-80db-68be52522a91.png)

**Comment by hdrabkin** [comment]
current ec xref EC:3.1.6.-.
 maps to
Hydrolases Acting on ester bonds
Sulfuric ester hydrolases
Even 3.1.6.21 seems more specific (linear primary-alkylsulfatase.

**Comment by hdrabkin** [comment]
Added EC and RHEA xrefs and changed def.
RHEA and EC specifically say linear primary-alkylsufatase, which is more specific, so making those narrowMarch exrefs

**Comment by pgaudet** [comment]
Based on the 2 annotations, I think it would be safe to align with RHEA and EC and make this a 'linear linear primary alkylsulfatase'?

**Comment by hdrabkin** [comment]
Just checked that there are two other ECs for non-linear substrates. 
So, if we remove narrow match, then the name and def should be changed to reflect the liniear chain substrate. Leaving it 'alkyl' is ambiguous.
EC 3.1.6.19 (R)-specific secondary-alkylsulfatase (type III)
EC 3.1.6.22 branched primary-alkylsulfatase.

So would change GO:0018741 term name to 
linear primary-alkylsulfatase activity  with def like a primary linear alkyl sulfate ester + H2O= primary alcohol + H(+) + sulfate (ie, as it was), or the RHEA def (basically the same def).

I checked the SGD paper and they used SDS (linear) when testing for growth.

**Comment by hdrabkin** [comment]
Just checked that there are two other ECs for non-linear substrates. 
So, if we remove narrow match, then the name and def should be changed to reflect the liniear chain substrate. Leaving it 'alkyl' is ambiguous.
EC 3.1.6.19 (R)-specific secondary-alkylsulfatase (type III)
EC 3.1.6.22 branched primary-alkylsulfatase.

So would change GO:0018741 term name to 
linear primary-alkylsulfatase activity  with def like a primary linear alkyl sulfate ester + H2O= primary alcohol + H(+) + sulfate (ie, as it was), or the RHEA def (basically the same def).

I checked the SGD paper and they used SDS (linear) when testing for growth.
