### ISSUE TITLE
cuticle development and children- taxon constraints and plant specific terms

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#24315]
In reviewing TAIR (plant) annotations flagged as violations of taxon constraints I found that 
the following GO terms triggered a taxon constraint violation. From QuickGo it  seems to be excluding single cell organisms but not sure what else is causing the taxon violation maybe something further up the tree or a CL link?

GO:0042335 | cuticle development
GO:0006723 | cuticle hydrocarbon biosynthetic process
GO:0035017 | cuticle pattern formation

Looking at the terms and annotations I think we do need to maybe restructure and add  a plant specific term which I propose here
Term:cutin-based cuticle development
Definition:  Synthesis and deposition of cutin-based  extracellular structure composed of a covalently linked macromolecular scaffold of cutin and a variety of organic solvent-soluble lipids that are collectively termed waxes. Such structures are found on the external face of polysaccharide cell walls in land plants.
Ref:PMID:23893170
Taxon constraint: NCBI:3193

Furthermore,  propose to add as children of cutin-based cuticle development:
GO:0010143 cutin biosynthetic process
GO:0010025 wax biosynthetic process (does this occur in other taxa-does it need a constraint or cuticular wax biosynthetic process)

Does this seem reasonable wrt  structure and constraints?

**Comment by tberardini** [comment]
I've subscribed to this ticket so I will see the thread development.

**Comment by pgaudet** [comment]
Animals also produce wax https://en.wikipedia.org/wiki/Wax

There are lots of compounds in CHEBI under 'wax' - 
https://www.ebi.ac.uk/chebi/chebiOntology.do?treeView=true&chebiId=CHEBI:10036#graphView

I point to out to be sure we dont create undesired assertions in the ontology. 

Thanks, Pascale

**Comment by lreiser** [comment]
Makes sense and agreed that we don't want  undesired assertions. I'm happy just having a cutin-based cuticle term ;)

**Comment by raymond91125** [comment]
I propose to have uberon add a cutin-based cuticle and broaden cuticle taxon constraints. Then I can add the GO terms accordingly.

**Comment by lreiser** [comment]
I will defer to the expertise of the ontologists wrt how to best handle this.
thank you,

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160062
+name: cutin-based cuticle development
+namespace: biological_process
+def: "The process whose specific outcome is the progression of the cutin-based cuticle over time, from its formation to the mature structure. Cutin-based cuticle is an extracellular structure composed of a covalently linked macromolecular scaffold of cutin and a variety of organic solvent-soluble lipids that are collectively termed waxes. Such structures are found on the external face of polysaccharide cell walls in land plants." [PMID:23893170]
+is_a: GO:0048856 ! anatomical structure development
+created_by: rynl
+creation_date: 2022-11-07T21:07:03Z

**Comment by raymond91125** [comment]
Created GO term and added taxon constraints. If and when Uberon adds cutin-based cuticle, we can then add logical def accordingly. Thanks.

**Comment by raymond91125** [comment]
Uberon does not cover plants.
