### ISSUE TITLE
Remove general xref from GO:0004177 aminopeptidase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24313]
GO:0004177 aminopeptidase activity has many cross reference, including EC:3.4.11.-

This one is too general, it should be removed . 

Thanks, Pascale

**Comment by sjm41** [comment]
@pgaudet Why do you say EC:3.4.11.- is too general for GO:0004177 aminopeptidase activity?  Seems an exact match for equivalent grouping terms to me.

https://enzyme.expasy.org/EC/3.4.11.-
Hydrolases -> Acting on peptide bonds (peptidases) -> Aminopeptidases

id: GO:0004177
name: aminopeptidase activity
namespace: molecular_function
def: "Catalysis of the hydrolysis of a single N-terminal amino acid residue from a polypeptide chain."

**Comment by pgaudet** [comment]
Thanks @sjm41 
OK - we could add this back - and maybe make these narowMatch? 

* [3.4.11.9](https://enzyme.expasy.org/EC/3.4.11.9) Xaa-Pro aminopeptidase
* [3.4.11.21](https://enzyme.expasy.org/EC/3.4.11.21)  aspartyl aminopeptidase
* [3.4.11.6](https://enzyme.expasy.org/EC/3.4.11.6)  aminopeptidase B
* [3.4.11.5](https://enzyme.expasy.org/EC/3.4.11.5) prolyl aminopeptidase

A bit on a different topic- I am not convinced we were right to obsolete these; do they really represent gene functions? It seems they are different specificity of different enzymes. 


Pascale

**Comment by sjm41** [comment]
Thanks for adding back EC:3.4.11.- to GO:0004177. I'll reopen this ticket until that's done.

I'm not sure about whether those four other ECs merit their own GO term or not. I agree they are different functions/specificities.

I see there was a previous discussion about [3.4.11.21](https://enzyme.expasy.org/EC/3.4.11.21) here: https://github.com/geneontology/go-ontology/issues/6849

Doing a quick search on UniProt for human EC annotations:
- 3.4.11.9 Xaa-Pro aminopeptidase -> hits 3 paralogs (XPNPEP1, XPNPEP2, XPNPEP3)
- 3.4.11.21 aspartyl aminopeptidase -> only hit is DNPEP gene?
- 3.4.11.6 aminopeptidase B -> only hit is RNPEP gene?
- 3.4.11.5 prolyl aminopeptidase -> only hit is LAP3 gene?
This seems to support distinct functions, though only one gene is involved in each case.  Not sure this helps or not....
