### ISSUE TITLE
NTR: L-lysine:L-arginine antiporter activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#24324]
Please provide as much information as you can: 

* **Suggested term label:**
L-lysine:L-arginine antiporter activity

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: L-lysine(out) + L-arginine(in) = L-lysine(in) + L-arginine(out). 

* **Reference, in format PMID:10903140 (fig 6A)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
solute:cation antiporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by hdrabkin** [comment]
+[Term]
+id: GO:0106439
+name: L-lysine:L-arginine antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: L-lysine(out) + L-arginine(in) = L-lysine(in) + L-arginine(out)." [PMID:10903140, RHEA:70827]
+xref: RHEA:70827
+is_a: GO:0015298 ! solute:cation antiporter activity
+property_value: creation_date 2022-11-08T21:55:18Z xsd:dateTime
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24324 xsd:anyURI
+created_by: hjd
