### ISSUE TITLE
NTR:  neutral amino acid, sodium: L-arginine antiporter activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#24323]
Please provide as much information as you can: 

* **Suggested term label:**
neutral amino acid, sodium: L-arginine antiporter activityy

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: L-arginine(in) + neutral amino acid(out) + Na(+)(out) = L-arginine(out) + neutral amino acid(in) + Na(+)(in).

* **Reference, in format PMID:10903140

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
solute:cation antiporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by hdrabkin** [comment]
trying to find a CHEBI id for 'neutral amino acid' to see if I can find a RHEA or if I can request one.

**Comment by hdrabkin** [comment]
Neutral amino acids are the amino acids that possess an equal number of amino and carboxylic acid groups. The groups attached to the amino acid, apart from the carboxylic acid groups and amino acid groups, may be either polar or non-polar.
note this def has to be pH dependent; in GO we use the form that exists at pH 7.3
I thought maybe 'non-polar amino acid', but 


non-polar amino acids; CHEBI:25588
Nonpolar amino acids include alanine (Ala), leucine (Leu), isoleucine (Ile), proline (Pro), tryptophan (Trp), valine (Val), phenylalanine (Phe), and methionine (Met). The side chains of these amino acids are long carbon chains or carbon rings,

**Comment by hdrabkin** [comment]
So I'm thinking Neutral amino acids at pH 7.3, the R group would have no charge? 
@amorgat does RHEA have a 'neutral amino acid' entry? I might not be searching correctly

**Comment by deustp01** [comment]
I think "neutral" would be all of the nonpolar ones plus glutamine, asparagine, serine, threonine, and cysteine - uncharged but polar side chains.
Question: does the transporter studied in PMID: 10903140 really interact roughly equally with this full range of amino acids, and if not, do you need to find a grouping term for the full range of neutral amino acids to deal with this term request, or only one to cover the range shown in the paper?
But you'd still need a grouping term for the subset that this transporter does handle, so my evasion may not help.

**Comment by deustp01** [comment]
Or maybe here multiple annotations are needed. By analogy, Human ALDOB can convert fructose 1,6-bisphosphate to glyceraldehyde 3-phosphate + dihydroxyacetone phosphate [fructose-bisphosphate aldolase activity](https://www.ebi.ac.uk/QuickGO/term/GO:0004332) and can also convert fructose 1-phosphate to glyceraldehyde + dihydroxyacetone phosphate 
[fructose-1-phosphate aldolase activity](https://www.ebi.ac.uk/QuickGO/term/GO:0061609) - one gene product, 2 activities, 2 GO terms, and no attempt in GO to make a grouping term to merge them into a single annotation.

**Comment by hdrabkin** [comment]
I'm also thinking of multiple annotations to whatever specific amino acid might do.

**Comment by Argoudpuy** [comment]
Hi,
I hesitated to ask a new term GO for each amino acid for which a Rhea has been created from this PMID:10903140, namely L-leucine[Rhea:70831], L-glutamine[Rhea:70835], L-histidine[Rhea:70839] and L-cysteine[Rhea:70847].
Finally SLC7A6 transports very specific amino acid, it is not a SLC transporter with a large spectre, probably better to create  a specific term for each amino acid describes above.
I hope that helps

**Comment by hdrabkin** [comment]
So, I could create the term, and define 'neutral amino acid' based on the def above (Neutral amino acids are the amino acids that possess an equal number of amino and carboxylic acid groups.)
taken from https://byjus.com/question-answer/give-an-example-of-neutral-amino-acid/
Therefore, apart from the carboxylic acid and amino acid groups, the groups linked to the amino acid might be non-polar or polar.
but needs to be pH7.3-friendly. 
So at 7.3, zwitterionic forms for glycine, tyr, phe, ser, thr, leu, ile, val

**Comment by pgaudet** [comment]
I think the parent should be 'GO:0005295 neutral L-amino acid:sodium symporter activity'

**Comment by pgaudet** [comment]
Also need to remove the LD from GO:0140893 neutral amino acid, sodium:proton antiporter activity since this is not defining a neutral amino acid

**Comment by Argoudpuy** [comment]
Hi Harold,
ok but finally according to your definition of a neutral amino acid, this tem will only match L-leucine[Rhea:70831], so it will miss me  the 3 others L-glutamine[Rhea:70835], L-histidine[Rhea:70839] and L-cysteine[Rhea:70847].
It's probably better to create a term for each amino acid describes above, what do you think?
thanks

**Comment by ValWood** [comment]
Can this one be closed if we do not need this grouping term?
