### ISSUE TITLE
NTR: mitotic transcriptional state inheritance

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#24332]
Please provide as much information as you can: 

New term: * **mitotic transcriptional state inheritance**

Defintion: * **Mitotic relatedness of post-transcriptional modifications between cell generations** 

* **PMID: 20188556**

* **Set1, Ash2 extensions PRO IDs for H3K4me3**

* **Parent term(s)** not sure, I looked at transcription but also the single step BP will go. I saw the many other inheritance terms but they don't fit and a MF cannot be a parent for BP, can just be related. Maybe GO:0006325 chromatin organization?

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
* EXACT: active cellular transcriptional state inheritance 
* BROAD: transcriptional relatedness along cell lineages

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
*From paper: " By live imaging of single-gene transcriptional events in individual cells, we have directly recorded the potential for mitotic inheritance of transcriptional states down cell lineages. Our data showed strong similarity in frequency of transcriptional firing between mother and daughter cells... Analysis of transcription in chromatin mutants demonstrated that the histone H3K4 methylase Set1 and Ash2, a component of the methylase complex, are required for memory. 
To study transcription in single cells, we have utilized a live-cell RNA detection system for monitoring transcriptional firing events of single genes as they occur, to relate transcription to cell division, at the single-cell level."

**Comment by ValWood** [comment]
Hi Petra,
I think this might be the term you need?
GO:0040029  epigenetic regulation of gene expression
v

**Comment by pfey03** [comment]
Hi Val I annotated that but it's not inheritance what the paper is about that these are passed on to daughter cells and so forth. If that's not in scope of Go ok but then I cannot annotate this aspect, it's fine.

**Comment by ValWood** [comment]
Definition ([GO:0040029 GONUTS page](http://gowiki.tamu.edu/wiki/index.php/Category:GO:0040029))
A process that modulates the frequency, rate or extent of gene expression through chromatin remodelling either by modifying higher order chromatin fiber structure, nucleosomal histones, or the DNA. Once established, this regulation may be maintained over many cell divisions. It can also be heritable in the absence of the instigating signal. PMID:10521337 PMID:11498582 PMID:22243696 PMID:34414474


The def is just "inheriting over cell divisions", we use it  this way for fission yeast.

@colinlog is Petra covered by this term?

**Comment by pfey03** [comment]
Yes my my paper and annotations are covered. Thanks!
