### ISSUE TITLE
Textual definition update: GO:0016020

### ISSUE THREAD

**Issue by cmpich** [geneontology/go-ontology#24333]
* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request a definition update**
Term
id: GO:0016020

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
"A lipid bilayer along with all the proteins and protein complexes embedded in it and attached to it."

* **Reference(s)**
PMID:nnnnnnn

* **Additional information**
There is just a typo in the definition: an -> and

**Comment by pgaudet** [comment]
Hi @cmpich Thanks for reporting this.
