### ISSUE TITLE
BP NTRs: 'effector-mediated modulation of host DNA synthesis by symbiont' and child term 'effector-mediated induction of host DNA synthesis'

### ISSUE THREAD

**Issue by CuzickA** [geneontology/go-ontology#24370]
Please provide as much information as you can: 

* **Suggested term label:**
'effector-mediated modulation of host DNA synthesis by symbiont' 
and child term 
'effector-mediated induction of host DNA synthesis'

* **Definition (free text)**
NTR: effector-mediated modulation of host DNA synthesis by symbiont
A process mediated by a molecule secreted by a symbiont that results in the modulation (either activation or suppression) of DNA synthesis involved in DNA replication (GO:0090592). The host is defined as the larger of the organisms involved in a symbiotic interaction. PMID:25888589

AND child term NTR: effector-mediated induction of host DNA synthesis
A process mediated by a molecule secreted by a symbiont that results in the activation of DNA synthesis involved in DNA replication (GO:0090592). The host is defined as the larger of the organisms involved in a symbiotic interaction. PMID:25888589

* **Reference, in format PMID:#######**
PMID:25888589

* **Gene product name and ID to be annotated to this term**
* [UMAG_02239](https://canto.phi-base.org/curs/1f5e9ca2be427dab/feature/gene/view/1) See1 from Ustilago maydis

* **Parent term(s)**
GO:0140418 effector-mediated modulation of host process by symbiont

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
New GO BP terms required for publication curation into PHI-base using our new community curation tool PHI-Canto in collaboration with @ValWood.

I also noticed a typo in GO:0140418 definition should be 'suppression' not 'suppresion' and also a typo in GO:0140590 'supression' should be 'suppression'. Thanks, Alayne.

**Comment by pgaudet** [comment]
@Antonialock 

DNA synthesis seems to be the readout here - (GO:0071897 DNA biosynthetic process is 'The biosynthetic process resulting in the formation of DNA.' ) Both the paper you mention, and PMID:29314018 mention that the See1 effector "interacts with a maize homolog of SGT1 (Suppressor of G2 allele of skp1), a factor acting in cell cycle progression in yeast" (PMID:25888589) and "U. maydis See1 was identified as the first cell type-specific fungal effector, being required for induction of cell cycle reactivation in bundle sheath cells." (PMID:29314018)


So I propose to label the new term: "effector-mediated induction of cell cycle reactivation in host"
This would be part_of "GO:0051819 induction by symbiont of tumor or growth in host"

I dont think we need the general term 'effector-mediated modulation of host DNA synthesis by symbiont', until we have examples of inhibition. 

Does that work for (and Alayne) ?

Thanks, Pascale

**Comment by ValWood** [comment]
Apologies, my fault I checked, but I didn't check the paper, only the ontology positioning. That sounds correct.

**Comment by CuzickA** [comment]
Sound good thanks.

Is it possible for the new term "effector-mediated induction of cell cycle reactivation in host" to also have the parent "GO:0140418 effector-mediated modulation of host process by symbiont"?

![image](https://user-images.githubusercontent.com/11753634/202665867-da1fee62-dbca-40c6-9465-63138915677b.png)

The reason for this is that in our new PHI-base 5 website we capture high level information about whether the pathogen gene functions as an 'effector'. This information is then provided as a high level term label. The logic to do this involves looking for GO BP terms that are children of "GO:0140418 effector-mediated modulation of host process by symbiont".

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141017
+name: effector-mediated induction of cell cycle reactivation in host
+namespace: biological_process
+def: "A symbiont process in which a molecule secreted by the symbiont reactivates the host cell cycle, resulting in DNA synthesis and host cell division, and contributing to vegetative tumor formation." [PMID:25888589]
+is_a: GO:0140418 ! effector-mediated modulation of host process by symbiont
+relationship: part_of GO:0051819 ! induction by symbiont of tumor or growth in host
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24370" xsd:anyURI
+created_by: pg
+creation_date: 2023-04-04T08:41:31Z
