### ISSUE TITLE
Add do not annotate to 'RNA biosynthetic process' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24382]
7 direct annotations left: 

https://docs.google.com/spreadsheets/d/1nFV2XU4JU3gvUoWfGgT73W5OnHsN_Z5cdsz4FoanNhY/edit#gid=0

**Comment by pgaudet** [comment]
PomBase: 2 
GeneDB: 1
ComplexPortal: 3 
TAIR: 1
UniProt: 2 DONE 

@ValWood @sandraorchard @tberardini 
[Suggestions have been made](https://docs.google.com/spreadsheets/d/1nFV2XU4JU3gvUoWfGgT73W5OnHsN_Z5cdsz4FoanNhY/edit#gid=0) to rehouse these annotations


Thanks, Pascale

**Comment by tberardini** [comment]
Why is the 'do not annotate' tag being added to this term? I'm hunting around for the explanation but can't find the right ticket.

**Comment by tberardini** [comment]
TAIR done
