### ISSUE TITLE
obsoletion of histone "amino acid"  axis of classification (in favour of histone class and residue)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24397]
[ Note that this obsoletion is because there are multiple axes of classification, grouping term will be histone class (H2A, H3 etc), not amino acid-specific residue modifiers (e.g. histone H3K4 acetyltransferase activity) , will be kept. So you can move your annotations up to the parent, or down to a more specific child.]

Please provide as much information as you can:

* **GO term ID and Label**

Added to annotation review
- [x] GO:0018024    histone lysine N-methyltransferase activity 
https://github.com/geneontology/go-annotation/issues/4402

- [x] GO:0008469   histone arginine N-methyltransferase activity
https://github.com/geneontology/go-annotation/issues/4403

- [x] GO:0035184    histone threonine kinase activity 
https://github.com/geneontology/go-annotation/issues/4402

- [x] ~GO:1990259  histone glutamine N-methyltransferase activity~ 
-> 3EXP humn H2A Q104 (corresponds to yeast Q105)
https://github.com/geneontology/go-annotation/issues/4427
**WILL NOT BE OBSOLETED see https://github.com/geneontology/go-ontology/issues/24687**

No annotations EXP or IEA mappings
- [x] GO:0035174    histone serine kinase activity 
- [x] GO:0018110   histone arginine kinase activity 
- [x] GO:0035400  histone tyrosine kinase activity
- [x] GO:0140792  histone tyrosine phosphatase activity	
- [x] GO:0140790  histone serine/threonine phosphatase activity

* **Reason for deprecation**

Mulitiple axes of classification (grouping term will be histone class (H2A, H3 etc), not amino acid- specific residue modifiers (e.g. histone H3K4 acetyltransferase activity) , will be kept.

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

All annotations can move to the parent safely, but ideally would be made more specific. i.e. to specific histone and/or residue.

* **Are there annotations to this term?**
- How many EXP:
-See individual annotation tickets for numbers

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
See individual annotating tickets for numbers

* **Is this term in a subset? (check the AmiGO page for that term)**
NO

**Comment by ValWood** [comment]
migrate cross references

GO:0018024    histone lysine N-methyltransferase activity 
GO:1990259  histone glutamine N-methyltransferase activity
GO:0008469    histone arginine N-methyltransferase activity
GO:0035184    histone threonine kinase activity 
GO:0035174    histone serine kinase activity 
GO:0018110    histone arginine kinase activity 
GO:0035400    histone tyrosine kinase activity
GO:0140792    histone tyrosine phosphatase activity	
GO:0140790    histone serine/threonine phosphatase activity

**Comment by ValWood** [comment]
Mappings:
GO:0018024
InterPro:IPR016858
InterPro:IPR006560
InterPro:IPR017155
InterPro:IPR007728
InterPro:IPR013257
InterPro:IPR011381
InterPro:IPR038034
InterPro:IPR043550
InterPro:IPR021654
InterPro:IPR032926
InterPro:IPR045318
InterPro:IPR025789
InterPro:IPR011381
InterPro:IPR038035
InterPro:IPR037841
InterPro:IPR037842
InterPro:IPR018848
InterPro:IPR017111
InterPro:IPR015722
InterPro:IPR025789
InterPro:IPR013110
InterPro:IPR044422
InterPro:IPR025805
InterPro:IPR044420
InterPro:IPR044418
InterPro:IPR044439
InterPro:IPR045318
InterPro:IPR044419
InterPro:IPR016858


UniRule:UR000400130

**Comment by ValWood** [comment]
**mappings GO:0008469** 

UniRule:UR000615760
UniRule:UR000128653





[UniRule:UR000128653](https://www.uniprot.org/unirule/UR000128653)

**Comment by ValWood** [comment]
Next
- [ ] create new term for  histone glutamine N methyltransferase activity
- [ ] organize spreadsheet (need @pgaudet )
- [ ] send obsoletion notice

**Comment by ValWood** [comment]
@cmungall  this took 3 hours... just to gather the info for the obsoletion notice and the spreadsheet.
Although I think it was quite a bad one.

**Comment by ValWood** [comment]
and I am quite slow... and I did the mappings in a dim way...

**Comment by deustp01** [comment]
> So you can move your annotations up to the parent, or down to a more specific child.
Or, I hope, to a cousin, one of the many histone-specific residue agnostic children of [GO:0042054](https://www.ebi.ac.uk/QuickGO/term/GO:0042054)?

**Comment by ValWood** [comment]
Yes I didn't explain that very well. It took me a while to see why they were being removed. We keep specific histone, and specific residue. The amino acid is implicit in the residue, but we will no longer have an **"amino acid only"** grouping term.

**Comment by hdrabkin** [comment]
MGI done

**Comment by ValWood** [comment]
@deustp01  It is confusing. 
This is my understanding,  but I didn't initiate this issue even though I opened the ticket.

Here if you see [ histone H3 methyltransferase]  has no amino acid specificity until the residue. There is no amino acid grouping term. The plan is to make all branches look like this.

However, this does mean that we would lose specificity in some cases, if for example you know that a you have a histone lysine methyltransferase, but you don't have any information about the specific residue. In this case you would  to histone methyltransferase.  @pgaudet Is this OK ?

![Presentation2](https://user-images.githubusercontent.com/7359272/215134741-0df31868-d135-40ba-b4e2-866ac243a275.png)

**Comment by ValWood** [comment]
In fact, if you have a histone lysine methyltransferase, but you don't know the residue, histone lysine methyltransferase would no longer exist, so in the case you  would then need to annotate to BOTH
i) protein lysine-N methyltransferase  AND
ii) histone methyltransferase. 
So you would need to make annotations in 2 branches to describe the current knowledge completely. One of my pet peeves is needing to make 2 annotations to say one thing....

**Comment by srengel** [comment]
this ticket says that histone glutamine N-methyltransferase activity GO:1990259 will be obsoleted but i see in QuickGO and P2GO that it has instead been renamed histone H2AQ104 methyltransferase activity.  S.cerevisiae doesn't have H2AQ104, so this is going to be problematic for budding yeast.

**Comment by pgaudet** [comment]
@ValWood 
https://github.com/geneontology/go-ontology/issues/24397#issuecomment-1406726709
Usually the paper will list at least which histone is modified, so it should be possible to annotate a single term, such as 'histone H2A(or 2B or 3 or 4) methyltransferase activity'

**Comment by pgaudet** [comment]
@srengel This is the orthologous position, as stated in the paper (PMID:24352239)

> position 105 (Q105) and human H2A at Q104


The definition of the term explains this: 

>Catalysis of the reaction: S-adenosyl-L-methionine + (histone H2A)-glutamine (position 104) = S-adenosyl-L-homocysteine + (histone H2A)-N5-methyl-glutamine (position 104). Note that this corresponds to  Q105 in yeast.


Is this OK for you ? 

Thanks, Pascale

**Comment by ValWood** [comment]
OK I was thinking of SET domain, which is  a lysine methylase. I still have 3 set domain proteins where I still don't know the actual specificity (set3, 5 and 6), although 2 of them are in known chromatin remodelling complexes. I might be able to annotate these from orthologs, but I don't immediately see that these are annotated specifically. I'll have a dig around today.

**Comment by ValWood** [comment]
>Is this OK for you ?
I think these will turn out to be really confusing for a lot of people

I wonder if we can use the notation
histone H2AQ104 methyltransferase activity
->
histone H2AQ104(Q105) methyltransferase activity

for the variable residue terms?

**Comment by sjm41** [comment]
See #24715 for similar discussion of histone numbering discrepancy.

**Comment by pgaudet** [comment]
Hi @ValWood 
I think that would be extermely confusing as a label. 

How about synonyms? Would that work ? Plus comments about the positions being relative to human, and giving other organism's corresponding positions. 

Do you know which residues differ between organisms?

**Comment by pgaudet** [comment]
WRT the pombe genes: 

- set3: annotated as a methlytransferase by ISS to Q8IZD2, but that seems incorrect (a paper starting that this a a histone methylase has been retracted)
- set5 and set6: the paper cited by pombase does not mention that these may methylate histones - they just list SET domain proteins. 

These look  quite uncertain to me. 

Pascale

**Comment by ValWood** [comment]
> set3: annotated as a methlytransferase by ISS to Q8IZD2, but that seems incorrect (a paper starting that this a a histone methylase has been retracted)

I will remove this.

> set5 and set6: the paper cited by pombase does not mention that these may methylate histones - they just list SET domain proteins.


Set6 is ortholog of S. cerevisiae set6 and  mammalian (SMYD1-3)

Mouse ortholog SMYD1
**https://www.uniprot.org/uniprotkb/P97443/entry
described as Methylates histone H3 at 'Lys-4' (H3K4me). 
but GO annotation is only to 
Function | histone lysine N-methyltransferase activity

or human SMYD3
https://www.uniprot.org/uniprotkb/Q9H7B4/entry
Histone methyltransferase. Specifically methylates 'Lys-4' of histone H3, inducing di- and tri-methylation, but not monomethylation (PubMed:[15235609](https://www.uniprot.org/citations/15235609), PubMed:[22419068](https://www.uniprot.org/citations/22419068)).
Also methylates 'Lys-5' of histone H4 (PubMed:[22419068](https://www.uniprot.org/citations/22419068)).

I would like to ISS these to minimally H3 methylation and H4 methyltransferase once the annotation/terms  exist. For now I will just move up to 'histone methyltransferase'

**Comment by deustp01** [comment]
> Do you know which residues differ between organisms?

The original goal of GO is "the unification of biology". Doesn't that mean that we should transcend species-specific details like the position of the target residue of a modification reaction, to focus instead on the sequence motif well-conserved across species that defines the target site? And Don't we have an array of GO-related tools, in PAINT and PANTHER, to enable exactly this trans-species focus?

Also, practically, considering the continuing revisions of model organism genome builds and hence of model organism proteomes, doesn't this sequence-specific focus in=mpose a large maintenance burden on future curators and ontology developers?
@thomaspd @cmungall ?

**Comment by ValWood** [comment]
I would be happy to use some unified nomenclature for histone residue reporting, but there does not appear to be one. ....

**Comment by pgaudet** [comment]
Actually there were 3 EXP annotations to histone serine kinase, see https://github.com/geneontology/go-annotation/issues/4469

**Comment by pgaudet** [comment]
T
