### ISSUE TITLE
Update definitions for 'cell differentiation' and main children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24390]
Hello, 

Working on design patterns (see https://github.com/geneontology/go-ontology/issues/24389) with @ukemi we propose to improve the definitions of the 'patternable' children of cell differentiation',  as well as 'cell differentiation' itself. 

- [x] **GO:0030154 cell differentiation:**  

Current def: The process in which relatively unspecialized cells, e.g. embryonic or regenerative cells, acquire specialized structural and/or functional features that characterize the cells, tissues, or organs of the mature organism or some other relatively stable phase of the organism's life history. Differentiation includes the processes involved in commitment of a cell to a specific fate and its subsequent development to the mature state.

Proposed def:The cellular developmental process in which a relatively unspecialized cell, e.g. embryonic or regenerative cell, acquires specialized structural and/or functional features that characterize a specific cell. Differentiation includes the processes involved in commitment of a cell to a specific fate and its subsequent development to the mature state.

**GO:0045165 cell fate commitment:** (see comment below https://github.com/geneontology/go-ontology/issues/24390#issuecomment-1343330297)
Current def: The commitment of cells to specific cell fates and their capacity to differentiate into particular kinds of cells. Positional information is established through protein signals that emanate from a localized source within a cell (the initial one-cell zygote) or within a developmental field.

Proposed def:The cellular developmental process by which a cell becomes restricted to a specific cell fate and attains the capacity to differentiate into that specific cell.

**GO:0001709 cell fate determination:**  (see comment below https://github.com/geneontology/go-ontology/issues/24390#issuecomment-1343330297)
Current def: A process involved in cell fate commitment. Once determination has taken place, a cell becomes committed to differentiate down a particular pathway regardless of its environment.

Proposed def:The cellular developmental process involved in cell fate commitment in which a cell becomes capable of differentiating autonomously into a specific cell, regardless of its environment.

**GO:0001708 cell fate specification:**  (see comment below https://github.com/geneontology/go-ontology/issues/24390#issuecomment-1343330297)

Current def: The process involved in the specification of cell identity. Once specification has taken place, a cell will be committed to differentiate down a specific pathway if left in its normal environment. 

Proposed def:The cellular developmental process involved in cell fate commitment in which a cell will be committed to differentiate into a specific cell if left in its normal environment.

- [x]  **GO:0048468 cell development:** 
Current def: The process whose specific outcome is the progression of the cell over time, from its formation to the mature structure. Cell development does not include the steps involved in committing a cell to a specific fate. 

Proposed def: The cellular developmental process in which a specific cell progresses from an immature to a mature state. Cell development start once cell commitment has taken place.

- [x]  **GO:0048469 cell maturation:** 

Current def: A developmental process, independent of morphogenetic (shape) change, that is required for a cell to attain its fully functional state.          

Proposed def: The cellular developmental process, independent of morphogenetic (shape) change, that is required for a specific cell to attain its fully functional state.

**GO:0000904 cell morphogenesis involved in differentiation:**
Current def: The change in form (cell shape and size) that occurs when relatively unspecialized cells, e.g. embryonic or regenerative cells, acquire specialized structural and/or functional features that characterize the cells, tissues, or organs of the mature organism or some other relatively stable phase of the organism's life history.

Proposed def: (to do) 

Thanks, Pascale

**Comment by pgaudet** [comment]
@vanaukenk @hattrill your feedback would be much appreciated

**Comment by addiehl** [comment]
I am concerned that both the original definition and the proposed definition of 'cell differentiation' and the proposed definition fail to consider the differentiation of the highly specialized cells of the immune system, such as when a 'naive T cell' (already considered a mature cell type) differentiates into an 'effector T cell' or a 'memory T cell', when a 'memory T cell' differentiates into an effector memory T cell upon reencounter with an antigen, or when a 'class-switched B memory cell' differentiates into a 'plasma cell'.

**Comment by hattrill** [comment]
Hi @pgaudet - I have feedback from FB. 

cell fate commitment/determination/specification

There were comments on the use of 'specific cell' in the text defs, as this is too restrictive and should be replaced with mature/more mature.
A couple of examples were given to illustrate this:
:a cell may be committed to a cell _lineage_ before being committed to a _specific cell type_
e.g., the daughter cell of a neuroglioblast may be committed to become a type of glial cell, but still have room to “decide” between the different types of glial cells. The new definition of “cell fate commitment” does not allow to use the term to refer to such a case, because it explicitly says that the commitment is for a “specific cell”.
:specific cell, does not neccessarily mean mature:
e.g. 'thoracic neuroblast NB1-1' is quite specific, but it is a stem cell rather than a mature cell type.

**Comment by hattrill** [comment]
Also, comments from Nick Brown, who teaches development raised the point that often **differentiation** is used to describe the process by which a determined cell acquires the specialized features that characterize a particular cell type, i.e. differentiation starts after commitment, specification and determination. 
And, I agree with his point that the definition of **cell development** sounds more like differentiation than development. ie cell development should include the entire developmental history of a cell.

**Comment by hattrill** [comment]
For GO:0048469 **cell maturation** Nick commented that he regards"cell maturation [..] to the case where a fully differentiated cell, then shifts to another "more mature" state. The only place I have come across it is in the immune system."

**Comment by malcolmfisher103** [comment]
Hello,
We discussed this with some of our development domain experts and they had similar feedback to what @hattrill reports for differentiation and commitment.  To quote one of our experts, "can cell development only start once commitment begins if commitment itself is classified as a ‘cellular developmental process’?"

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-library/blob/main/notebooks/CellDifferentiation-Comparison.ipynb

**Comment by hattrill** [comment]
Just adding a couple of note:
1. Quite like the destinctions provided on https://www.khanacademy.org/science/biology/developmental-biology/development-and-differentiation/a/introduction-to-development
"At first, cells may be specified, earmarked for a certain **fate** but able to **switch** given the right cues. Next, they may become **determined**, meaning that they are **irreversibly committed to a certain fate.** Once a cell is **determined, even if it’s moved to a new environment, it will differentiate as the cell type to which it's become committed**[.....] Eventually, most cells in the body **differentiate**, or take on a **stable**[...] identity. Examples of differentiated cell types in the human body include neurons, the cells lining the intestine, and the macrophages"

2. cell maturation has the related synonym "functional differentiation", which doesn't seem to mean much in biology and "cell development" has the related synonym "terminal differentiation" which doesn't sit right for me. It think that iof we want to distinguish "terminal differentiation", then there should be a stand-alone term for this.

**Comment by pgaudet** [comment]
https://pubmed.ncbi.nlm.nih.gov/19921742/

**Comment by pgaudet** [comment]
@hattrill 
> The first part of cell fate commitment process in which the cell becomes determined to follow a particular fate, even if the cell were to be moved to a neutral environment, it would continue to commit to that developmental pathway..

**Comment by hattrill** [comment]
Suggested defs:

GO:0001708 cell fate specification 
The cellular developmental process involved in cell fate commitment in which the cell is designated to follow a developmental path, unless they receive extrinsic cues that direct an alternative fate.


GO:0001709 cell fate determination: A process involved in cell fate commitment, that occurs after cell fate specification,  in which a cell is irreversibly committed to a cellular developmental fate which is heritable on cell division. 


GO:0045165 cell fate commitment 
A cellular developmental process by which a cell establishes the intrinsic character of a cell or tissue region irreversibly committing it to a particular fate.

**Comment by pgaudet** [comment]
Hi everyone, 

I updated the definitions as suggested above. There is still the issue of immune cell transitions brought up by @addiehl 
(copied below from email exchange)

> immune cell transitions, the original cell is fully functional in its existing state (a ‘naive T cell’ which is considered a subtype of ‘mature T cell’), and after differentiation to its new state (‘helper T cell’, for instance), is still fully functional, though with a somewhat different set of functions.  Also some differentiation steps, such as from a ‘mature B cell’ to a ‘plasma cell’ (via a ‘plasmablast’ intermediate), involve significant changes in morphology that are required for the new set of functions. This progress of cell differentiation in the immune system can go down differing pathways based on environment cues, such that, for instance, T cell activation in certain contexts might lead to differentiation into an ‘effector T cell’ subclass, whereas in in other contexts might lead to differentiation into a ‘regulatory T cell’.
 
The paradigm of cell differentiation always having a fixed endpoint, as developed from simpler model organisms, does not seem to fit the complexity of the immune system, but certainly this is far first time a biological model breaks down when faced with the details of actual life. What is clear is that progenitor cells typically commit to, for instance, the T cell lineage or the B cell lineage, at an early stage, and subsequent differentiation steps stay within that lineage.
 
A possible solution would be to have a general class ‘T cell differentiation’, but to then use subclasses of ‘cell development’ for differentiation/development of particular T cell subtypes, so for instance ‘regulatory T cell differentiation’ would become (or be replaced by) ‘regulatory T cell development’. However this suggestion would only apply to some of the children of ‘T cell differentiation’, and would require some additional analysis before implementing.
 


However I these immune transition terms do not yet exist, so we can revisit this when these terms are added. 

Thanks, Pascale
