### ISSUE TITLE
GO:0009451    RNA modification

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24394]
Please provide as much information as you can:

* **GO term ID and Label**

GO:0009451    RNA modification and children

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/vw253/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/vw253/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Code | Name |   | Count
-- | -- | -- | --
GO:0030488 | tRNA methylation | 113
GO:0031167 | rRNA methylation | 97
GO:0080009 | mRNA methylation | 89
GO:0002098 | tRNA wobble uridine modification | 71
GO:0006400 | tRNA modification | 65
GO:0016554 | cytidine to uridine editing | 46
GO:0070475 | rRNA base methylation | 42
GO:0016556 | mRNA modification | 39
GO:0002143 | tRNA wobble position uridine   thiolation | 38
GO:0031119 | tRNA pseudouridine synthesis | 37
GO:0031118 | rRNA pseudouridine synthesis | 36
GO:0080156 | mitochondrial mRNA modification | 33
GO:0002949 | tRNA threonylcarbamoyladenosine   modification | 32
GO:0009451 | RNA modification | 30
GO:0001510 | RNA methylation | 27
GO:0006382 | adenosine to inosine editing | 27
GO:1990481 | mRNA pseudouridine synthesis | 23
GO:0000454 | snoRNA guided rRNA pseudouridine   synthesis | 19
GO:0031120 | snRNA pseudouridine synthesis | 19
GO:0034227 | tRNA thio-modification | 16
GO:1900865 | chloroplast RNA modification | 15
GO:0000455 | enzyme-directed rRNA pseudouridine   synthesis | 14
GO:0035553 | oxidative single-stranded RNA   demethylation | 14
GO:0036261 | 7-methylguanosine cap   hypermethylation | 13
GO:0002128 | tRNA nucleoside ribose methylation | 11
GO:0002926 | tRNA wobble base   5-methoxycarbonylmethyl-2-thiouridinylation | 11
GO:0031591 | wybutosine biosynthetic process | 11
GO:0101030 | tRNA-guanine transglycosylation | 10
GO:0002100 | tRNA wobble adenosine to inosine   editing | 9
GO:1900864 | mitochondrial RNA modification | 9
GO:0000451 | rRNA 2'-O-methylation | 8
GO:0070901 | mitochondrial tRNA methylation | 8
GO:0000154 | rRNA modification | 7
GO:0002943 | tRNA dihydrouridine synthesis | 7
GO:0000452 | snoRNA guided rRNA 2'-O-methylation | 6
GO:0002130 | wobble position ribose methylation | 6
GO:0002939 | tRNA N1-guanine methylation | 6
GO:0071951 | conversion of methionyl-tRNA to   N-formyl-methionyl-tRNA | 6
GO:0016553 | base conversion or substitution   editing | 5
GO:0035600 | tRNA methylthiolation | 5
GO:0040031 | snRNA modification | 5
GO:0106004 | tRNA (guanine-N7)-methylation | 5
GO:0106217 | tRNA C3-cytosine methylation | 5
GO:0120049 | snRNA (adenine-N6)-methylation | 5
GO:1900871 | chloroplast mRNA modification | 5
GO:0000453 | enzyme-directed rRNA   2'-O-methylation | 4
GO:0001522 | pseudouridine synthesis | 4
GO:0002097 | tRNA wobble base modification | 4
GO:0002101 | tRNA wobble cytosine modification | 4
GO:0002127 | tRNA wobble base cytosine   methylation | 4
GO:0002938 | tRNA guanine ribose methylation | 4
GO:0002940 | tRNA N2-guanine methylation | 4
GO:0061504 | cyclic threonylcarbamoyladenosine   biosynthetic process | 4
GO:0070476 | rRNA (guanine-N7)-methylation | 4
GO:0097309 | cap1 mRNA methylation | 4
GO:0106005 | RNA 5'-cap (guanine-N7)-methylation | 4
GO:0002927 | archaeosine-tRNA biosynthetic   process | 3
GO:0051391 | tRNA acetylation | 3
GO:0070329 | tRNA seleno-modification | 3
GO:0070899 | mitochondrial tRNA wobble uridine   modification | 3
GO:0070900 | mitochondrial tRNA modification | 3
GO:0002099 | tRNA wobble guanine modification | 2
GO:0002131 | wobble position cytosine ribose   methylation | 2
GO:0002937 | tRNA 4-thiouridine biosynthesis | 2
GO:0002946 | tRNA C5-cytosine methylation | 2
GO:0019988 | charged-tRNA amino acid modification | 2
GO:0035513 | oxidative RNA demethylation | 2
GO:0070705 | RNA nucleotide insertion | 2
GO:0070706 | RNA nucleotide deletion | 2
GO:0070903 | mitochondrial tRNA thio-modification | 2
GO:0080178 | 5-carbamoylmethyl uridine residue   modification | 2
GO:1904812 | rRNA acetylation involved in   maturation of SSU-rRNA | 2
GO:1990438 | U6 2'-O-snRNA methylation | 2
GO:1990882 | rRNA acetylation | 2
GO:1990983 | tRNA demethylation | 2
GO:0002129 | wobble position guanine ribose   methylation | 1
GO:0002132 | wobble position uridine ribose   methylation | 1
GO:0002136 | tRNA wobble base lysidine   biosynthesis | 1
GO:0070902 | mitochondrial tRNA pseudouridine   synthesis | 1
GO:0072670 | mitochondrial tRNA   threonylcarbamoyladenosine modification | 1
GO:0097310 | cap2 mRNA methylation | 1
GO:0106349 | snRNA methylation | 1
GO:1990799 | mitochondrial tRNA wobble position   uridine thiolation | 1

</body>

</html>

* **Reason for deprecation**

Describes  a molecular function

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:
1,200 annotations

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

**Comment by pfey03** [comment]
Just checked we have 25 EXP annotations I will take care of them after Thanksgiving

**Comment by ValWood** [comment]
For these cases where  the entire branch will be obsoleted it would be nicer if there could be some automation.
@cmungall @pgaudet  can we discuss.
For these  we think we will be able to do replaced_by in which case won't the   tools deal with it?

**Comment by ValWood** [comment]
No, actually some of them aren't. Definitely 
tRNA wobble position uridine thiolation
and 
GO:0001522 | pseudouridine synthesis

The  methylation/demethylation/acetylation are...so it isn't the entire branch.

**Comment by pfey03** [comment]
@ValWood, @pgaudet 
Will the non single single step then retained or also obsoleted? I did annotate the functions but have not yet deleted  BP
GO:0002098: tRNA wobble uridine modification

Thanks

**Comment by ValWood** [comment]
I don't think the multi-step processes will be obsoleted, but they will move from under the modification term I think. @pgaudet  is that correct?

**Comment by pfey03** [comment]
Dicty is done
