### ISSUE TITLE
GO:0033862 UMP kinase activity and  GO:0009041 uridylate kinase activity are the same activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24402]
See https://github.com/geneontology/go-annotation/issues/3429

These should be either merged or obsoleted with replaced_by 

See also https://www.rhea-db.org/rhea?query=2.7.4.14+

**Comment by pfey03** [comment]
@pgaudet let me know what's the decision, we have 1 EXP UMP kinase activity annotation

**Comment by pgaudet** [comment]
We need to obsolete + replace by

Thanks for the ping!

**Comment by raymond91125** [comment]
GO:0009041 uridylate kinase activity is a grouping term (has no direct annotations) for GO:0033862 UMP kinase activity and GO:0120136 dUMP kinase activity and both have EXP annotations. Thus, I don't think it makes sense to merge just one child with the parent.
https://enzyme.expasy.org/EC/2.7.4.14 uses CMP, dCMP, or UMP, which seems to be a different enzyme.
The label for GO:0009041 "Uridylate" appears to be causing the confusion. Perhaps we can change it to UMP/dUMP kinase activity.

**Comment by raymond91125** [comment]
[Term]
 id: GO:0009041
-name: uridylate kinase activity
+name: UMP/dUMP kinase activity
 namespace: molecular_function
 def: "Catalysis of the reaction: ATP + (d)UMP = ADP + (d)UDP." [GOC:go_curators]
-xref: EC:2.7.4.22
 is_a: GO:0016776 ! phosphotransferase activity, phosphate group as acceptor
 is_a: GO:0050145 ! nucleoside monophosphate kinase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24402" xsd:anyURI

**Comment by raymond91125** [comment]
@pgaudet do you agree with this solution? There would be no need of moving annotations.

**Comment by pgaudet** [comment]
yes that works!

**Comment by raymond91125** [comment]
thanks.
