### ISSUE TITLE
protein kinase A signaling - MF vesus BP 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24403]
I don't really understand this term in relation to yeast.

ptn1	↑regulates GO:0051896	 regulation of protein kinase B signaling
IBA with P60484 , ZDB-GENE-030616-47 , PTN000959472 , MGI:109583 , FBgn0026379 , ZDB-GENE-030131-3776	

pombe protein kinase B ortholog. is  Sck1
it inhibits gpa2 at the top of
adenylate cyclase-activating glucose-activated G protein-coupled receptor signaling pathway

and is itself a target of Tor. I don't think it requires it's own signalling pathway term? It seems a bit gene product specific?

@pgaudet  do you think this term should exist?

**Comment by pgaudet** [comment]
No, these are true pathways, we have tried to define these more clearly with @hattrill
