### ISSUE TITLE
vegetative cell differentiation ( primary term name swap)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24414]
GO:0022620 vegetative cell differentiation
The process in which a relatively unspecialized cell acquires specialized features of a vegetative cell. The vegetative cell is gives rise to the pollen tube.

has exact synonym
tube cell differentiation

@tberardini  would you mind if we swapped the primary names of these terms?
"vegetative cell differentiation" can have different meanings to different species.

**Comment by tberardini** [comment]
Consulting Planteome for the proper Plant Ontology term:

microgametophyte vegetative cell
https://browser.planteome.org/amigo/term/PO:0020099
related syn: tube cell

I suggest these GO updates:

1. change primary term name to 'microgametophyte vegetative cell differentiation'
2. update definition to include 'microgametophyte'
3. change 'exact' synonym of tube cell to 'related'
4. if there isn't yet a taxon restriction, we could probably stick 'Spermatophyta' on this

**Comment by ValWood** [comment]
Def now reads
The process in which a relatively unspecialized cell acquires specialized features of a microgametophyte. The microgametophyte gives rise to the pollen tube.

I also made 
vegetative cell differentiation synonym_related
Is that OK?

**Comment by tberardini** [comment]
@ValWood  Sorry, I should have been more specific.  The definition should read **microgametophyte vegetative cell** not **microgametophyte**.

The process in which a relatively unspecialized cell acquires specialized features of a **microgametophyte vegetative cell**. The **microgametophyte vegetative cell** is gives rise to the pollen tube.

The synonym is good.
