### ISSUE TITLE
Obsoletion request: [GO:1990736)   regulation of vascular associated smooth muscle cell membrane depolarization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24417]
Please provide as much information as you can:

* **GO term ID and Label**
GO:1990736 regulation of vascular associated smooth muscle cell membrane depolarization

* **Reason for deprecation**

precomposed, cell type

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

NO ANNOTATIONS

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
@pgaudet  do we want to include this one too?
GO:0060373 regulation of ventricular cardiac muscle cell membrane depolarization (15 EXP)

**Comment by RLovering** [comment]
Hi All
The heart ontology has a lot of precomposed terms. Currently there are no enrichment tools that use the cell or tissue information, it seems a shame to remove all of these before a system is in place that will enable the information about specific channels that have a specific role in controlling heart function to be deleted. As I have said many times, the problem and utility of GO is that it is mets the needs of many different user communities and uses. If you read my paper https://pubmed.ncbi.nlm.nih.gov/29440116/ or watch the the [YouTube](https://www.youtube.com/watch?reload=9&v=fhF7anN37rc&feature=youtu.be) summary you will see how GO annotations can be used to identify the causative genes associated with risk SNPs that fall in gene rich regions.

However, I guess that if you remove 'cell' from the term perhaps these will be acceptable? 

I would be interested to hear if you planning to remove microglial, T-cell, Macrophage etc from the ontology terms, and if not why are the specific cells of the heart and vascular systems not allowed to be captured in this way?

Best

Ruth

**Comment by ValWood** [comment]
Hi Ruth,
I removed this term from this ticket
GO:0060373 regulation of ventricular cardiac muscle cell membrane depolarization (15 EXP)
for now until there is time for a global review of these types of terms.
 
I am removing the term with no annotation 
(regulation of vascular associated smooth muscle cell membrane depolarization)
only and I'll close this ticket,
but  a brief look at the annotations, they look like readouts, and there does not seem to be a different mechanism of different cells for this process.

**Comment by RLovering** [comment]
FYI from discussions with experts in this field the different cell types in the heart use different proteins to ensure that cells in different parts of the heart conduct the electrical impulse at an appropriate speed. Unfortunately, my understanding of these differences is not suffient to explain this. However, while there is an overlap of the proteins in each cell there are also proteins that are only functional in specific cell types.

**Comment by ValWood** [comment]
Is it odd that these terms aren't related to GO:0061337   cardiac conduction? That seems to be what is described here?

**Comment by RLovering** [comment]
I am not an ontologist. And I got into trouble with cardiac conduction v cardiac physiology v action potential, so I just left David OS to sort this out. 
But cardiac conduction is (as defined by GO and agreed by experts) Transfer of an organized electrical impulse across the heart to coordinate the contraction of cardiac muscles. The process begins with generation of an action potential (in the sinoatrial node (SA) in humans) and ends with a change in the rate, frequency, or extent of the contraction of the heart muscles. 
The depolarisation of the ventricle cells I think might be regulated by internal systems as well as by the cardiac conduction system.

and the cells that are part of the cardiac conduction system are not ventricular cells

Best
Ruth

**Comment by ValWood** [comment]
Will close this.  Seems to be a larger issue. I can't remember what initiated this ticket
