### ISSUE TITLE
heterocyst differentiation (change parent, correct definition)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24415]
This has been gived the standard differentiation definition which is incorrect

The process in which a relatively unspecialized cell acquires specialized features of a heterocyst, a differentiated cell in certain cyanobacteria whose purpose is to fix nitrogen.

actions

- [x] change parent GO:0030154   cell differentiation
to
GO:0048869   cellular developmental process

- [x] Remove biosynthesis synonym

**Comment by pgaudet** [comment]
Update def to : The cellular developmental process by which a cell becomes a heterocyst, a cell that carries out nitrogen fixation. This process involves changes to the cell wall, expression of nitrogenase and other proteins involved in nitrogen fixation, and degradation of photosystem II, which produces oxygen. This process is known to occur in some cyanobacteria.


Thanks, Pascale
