### ISSUE TITLE
Obsoletion request:  GO:0004704 NF-kappaB-inducing kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24418]
Please provide as much information as you can:

* **GO term ID and Label**

[GO:0004704]NF-kappaB-inducing kinase activity

* **Reason for deprecation**

Gene product specific 
(note that this is instantiated as an enzyme regulator, but it is actually a protein kinase)

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**

Suggestions for reannotation
protein kinase activity (or a child)
Also consider:
[GO:1901222] regulation of NIK/NF-kappaB signaling

* **Are there annotations to this term?**
**- How many EXP:
2 + annotations to child term https://github.com/geneontology/go-annotation/issues/4692**

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

NO 
* **Is this term in a subset? (check the AmiGO page for that term)**

NO

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [x]  https://github.com/geneontology/go-annotation/issues/4737
**- [ ] https://github.com/geneontology/go-annotation/issues/4692**
- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: ***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
@pgaudet  Obsolete or Keep?
If we keep it should move to be is_a kinase (rather than is_a enzyme regulator)

**Comment by pgaudet** [comment]
I was just looking into this here: https://github.com/geneontology/go-annotation/issues/4692

Does GO:0030295 protein kinase activator activity work?

**Comment by deustp01** [comment]
> Does GO:0030295 protein kinase activator activity work?

Yes. That term is less specific but I guess the idea here is that the specificity is captured at the level of the Reactome reaction / GO-CAM activity unit, where specific inputs and outputs are annotated, so all information is preserved.

**Comment by pgaudet** [comment]
@ValWood  I agree about obsoleting this term. Many of the annotated terms are not kinases, so the term has been used inconsistently, and this is not how we would represent this now.

**Comment by ValWood** [comment]
Since this is used inconsistently I will obsolete without direct replacement.
The 2 annotated gene products will need to be reannotated.

**Comment by pgaudet** [comment]
Please @ValWood  make sure https://github.com/geneontology/go-annotation/issues/4692 
is done, this is the correct (complete) review ticket)
