### ISSUE TITLE
improve def phragmoplast

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24426]
Existing
Fibrous structure (light microscope view) that arises between the daughter nuclei at telophase and within which the initial partition (cell plate), dividing the mother cell in two (cytokinesis), is formed. Appears at first as a spindle connected to the two nuclei, but later spreads laterally in the form of a ring. Consists of microtubules.

https://en.wikipedia.org/wiki/Phragmoplast
The phragmoplast is a [plant cell](https://en.wikipedia.org/wiki/Plant_cell) specific structure that forms during late [cytokinesis](https://en.wikipedia.org/wiki/Cytokinesis). It serves as a scaffold for [cell plate](https://en.wikipedia.org/wiki/Cell_plate) assembly and subsequent formation of a new [cell wall](https://en.wikipedia.org/wiki/Cell_wall) separating the two daughter cells. The phragmoplast can only be observed in [Phragmoplastophyta](https://en.wikipedia.org/wiki/Phragmoplastophyta),

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6518215/#:~:text=The%20cell%20plate%20is%20synthetized,transition%20from%20anaphase%20to%20telophase.
The cell plate is synthetized by a specialized structure called the phragmoplast, which consists of microtubules, actin filaments, membrane compartments and associated proteins. The phragmoplast forms between daughter nuclei during the transition from anaphase to telophase.

**Comment by ValWood** [comment]
Suggest
The phragmoplast is a plant cell-specific cytoplasmic **microtubular** structure that forms during late cytokinesis. It serves as a scaffold for [cell plate](https://en.wikipedia.org/wiki/Cell_plate) assembly and subsequent formation of a new [cell wall](https://en.wikipedia.org/wiki/Cell_wall) separating the two daughter cells.

Also add only in  [Phragmoplastophyta](https://en.wikipedia.org/wiki/Phragmoplastophyta)

**Comment by ValWood** [comment]
@tberardini does this sound OK?

**Comment by ValWood** [comment]
Also, should phragmoplast](https://github.com/geneontology/go-ontology/issues/24426#top)  have "cytoskeleton" as a  part_of parent?

**Comment by tberardini** [comment]
Slight tweak:

The phragmoplast is a plant cell specific cytoplasmic actin and microtubule-based structure that serves as a scaffold for cell plate assembly and the formation of a new cell wall between two daughter cells during late cytokinesis.

If 'spindle' is part_of 'microtubule cytoskeleton', then I suppose that 'phragmoplast' should be part_of cytoskeleton.

More background:
https://www.sciencedirect.com/topics/medicine-and-dentistry/phragmoplast

**Comment by ValWood** [comment]
The phragmoplast is a plant cell specific cytoplasmic secretory module consisting of actin filaments, microtubules, membrane compartments and other structures to facilitate plate assembly and the formation of a new cell wall during late cytokinesis.
PMID:29074579, PMID: 28943203

**Comment by ValWood** [comment]
tweak to: 
The phragmoplast is a plant cell specific cytoplasmic structure composed of cytoskeletal polymers, membranes, and associated cytosolic proteins that functions as the focused secretory module for assembling the cell plate.
