### ISSUE TITLE
obsoletion: phragmosome (replace by GO:0009574  preprophase band)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24427]
Current
A flattened membranous vesicle containing cell wall components.

wikepedia
The phragmosome is a sheet of cytoplasm forming in highly vacuolated [plant cells](https://en.wikipedia.org/wiki/Plant_cell) in preparation for [mitosis](https://en.wikipedia.org/wiki/Mitosis).[[1]](https://en.wikipedia.org/wiki/Phragmosome#cite_note-1)

https://www.merriam-webster.com/dictionary/phragmosome#:~:text=phrag%C2%B7%E2%80%8Bmo%C2%B7%E2%80%8Bsome,phragmoplast%20and%20cell%20plate%20develop
a differentiated cytoplasmic diaphragm that develops from the strands of parietal cytoplasm during cell division in plant cells and forms a medium in which the phragmoplast and cell plate develop.

- [ ] Also add only in [Phragmoplastophyta](https://en.wikipedia.org/wiki/Phragmoplastophyta)

**Comment by ValWood** [comment]
@tberardini  @lreiser  I'm stuck here. These all sound quite different.
Minimally I want it to be clear that this is a plant-specific term.
Is it a vesicle? or does it contain vesicles?

**Comment by lreiser** [comment]
here is what I have found so far.
https://pubmed.ncbi.nlm.nih.gov/11171328/

"cytoplasmic linkages of microtubules and/or actin filaments
(phragmosome) that connect the nucleus to the PPB."


https://pubmed.ncbi.nlm.nih.gov/24972554/
discusses but I don't have access to the article

https://pubmed.ncbi.nlm.nih.gov/1854481/
also has info but I have no access

**Comment by lreiser** [comment]
Sinnott and Bloch (1940) observed that the nucleus-associated transvacuolar strands gradually realigned into a more or
less continuous baffle across the cell. This was termed the
phragmosome. 
https://rupress.org/jcb/article-pdf/110/4/1111/1060048/1111.pdf

**Comment by ValWood** [comment]
The. dictionary def sounds the best...

**Comment by ValWood** [comment]
Actually based on the papers it seems that "phragmosome" is an older term for preprophase band. It is referred to sometimes as 
phragmosome/preprophase band (as in the paper you provide above). 

ACTION: Suggest  obsolete phragmosome (no annotations) replace by preprophase band
https://www.ebi.ac.uk/QuickGO/term/GO:0009574

**Comment by ValWood** [comment]
I'm going to open a new ticket for the obsoletion so I have the checklist
