### ISSUE TITLE
Obsolete GO:1902699 pentose catabolic process to acetate & some siblings

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24429]
Similar to https://github.com/geneontology/go-ontology/issues/24353

These terms were created to capture data from a bioengineered Clostridia bacteria and there is no evidence that these are physiologically relevant.  

There are no annotations, no mappings, these terms are not present in any subsets. 

- [x] [GO:1902699 pentose catabolic process to acetate](http://amigo.geneontology.org/amigo/term/GO:1902699#display-lineage-tab)
- [x]  [GO:1902700 pentose catabolic process to butan-1-ol](http://amigo.geneontology.org/amigo/term/GO:1902700#display-lineage-tab)
- [x] [GO:1902698 pentose catabolic process to butyrate](http://amigo.geneontology.org/amigo/term/GO:1902698#display-lineage-tab)
- [x]  [GO:0044576 pentose catabolic process to ethanol](http://amigo.geneontology.org/amigo/term/GO:0044576#display-lineage-tab)
- [x]  [GO:1902701 pentose catabolic process to propan-2-ol](http://amigo.geneontology.org/amigo/term/GO:1902701#display-lineage-tab)

Thanks, Pascale

**Comment by raymond91125** [comment]
Also obsolete regulation terms
GO:1900509 regulation of pentose catabolic process to ethanol
GO:1900511 positive regulation of pentose catabolic process to ethanol
GO:1900510 negative regulation of pentose catabolic process to ethanol
