### ISSUE TITLE
rename term "protein body"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24425]
GO:0042735 protein body
Definition
A membrane-bounded plant organelle found in the developing endosperm, contains storage proteins.
-> rename to endosperm protein body

**Comment by ValWood** [comment]
@tberardini OK?

**Comment by pgaudet** [comment]
ping @tberardini

**Comment by tberardini** [comment]
ok

**Comment by tberardini** [comment]
Just for fun, I asked ChatGPT :). For this case, since the def specifically refers to the 'endosperm', renaming is sound.

![image](https://user-images.githubusercontent.com/4998871/205981508-3de8ccc0-e085-4d72-a00b-93b223b45aa1.png)
