### ISSUE TITLE
 obsoletion GO:0043265 ectoplasm

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24424]
from https://github.com/geneontology/go-ontology/issues/22279

is ectoplasm a useful term?
It has 1 experimental annotation.

It is defined
Granule free cytoplasm, lying immediately below the plasma membrane. PMID:12211103

The paper is describing the ectoplasm of a leech zygote
. For a general cell it is difficult to separate ectoplasm from cell cortex (and personally I have never seen the term used).
 Maybe it is more commonly used in an egg context "Zygotes consisted of a peripheral organelle-rich ectoplasm and an internal yolk-rich endoplasm. " in which case this term needs qualification

**Comment by ValWood** [comment]
Should I obsolete this term, or just close the ticket?

**Comment by ValWood** [comment]
@pgaudet Should I obsolete this term, or just close the ticket?

**Comment by ValWood** [comment]
@pgauget obsolete or leave?

**Comment by pgaudet** [comment]
This seem a term used in specific mammalian cells, for eg Sertoli cells  - see https://pubmed.ncbi.nlm.nih.gov/1785772/

It does seem redundant with cell cortex, as the single EXP from PMID:9003423 is co annotated to both terms.

**Comment by ValWood** [comment]
Maybe add the parent cell cortex, and keep in case there is some distinction

**Comment by pgaudet** [comment]
I would be in favor of obsoleting, since the annotations dont show that this is a distinct CC. 

Add as a NARROW synonym to cell cortex?

**Comment by ValWood** [comment]
OK will do.
