### ISSUE TITLE
Obsoletion request: obsoletion: phragmosome (equivalent to GO:0009574 preprophase band)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24437]
from
https://github.com/geneontology/go-ontology/issues/24427

Please provide as much information as you can:

* **GO term ID and Label**

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x] The reason for obsoletion is that this term is equivalent to another term
 ( GO:0009574 preprophase band)

* **"Replace by" term (ID and label)**

GO:0009574 preprophase band

* **Are there annotations to this term?**
- [x] How many EXP: 0

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
No mappings or cross references

* **Is this term in a subset? (check the AmiGO page for that term)**

No subsets
----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***

- [x] find external mappings (via IEAS), include in obsoletion notice   (NONE)

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
@tberardini  I thought I had asked about this but it was a different term. Do you agree?

**Comment by tberardini** [comment]
Hmmm, these articles, though from 2001 and 2003, describe them as two separate structures:

https://pubmed.ncbi.nlm.nih.gov/11171328/
https://pubmed.ncbi.nlm.nih.gov/14714204/

**Comment by ValWood** [comment]
Did you see the original ticket, I just spotted the link to it
https://github.com/geneontology/go-ontology/issues/24427

**Comment by ValWood** [comment]
I will close for now, but if you find they are the same pls reopen.
