### ISSUE TITLE
Taxon constraint:  hydrogenosome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24433]
transferred from an older ticket , more complicated taxon distribution

GO:0042566 hydrogenosome
parabasalid flagellates (e.g. [Trichomonas vaginalis](https://en.wikipedia.org/wiki/Trichomonas_vaginalis), [Tritrichomonas foetus](https://en.wikipedia.org/wiki/Tritrichomonas_foetus), [Histomonas meleagridis](https://en.wikipedia.org/wiki/Histomonas_meleagridis))
preaxostylid flagellates (e.g. [Trimastix pyriformis](https://en.wikipedia.org/w/index.php?title=Trimastix_pyriformis&action=edit&redlink=1))
heterolobosean amoeboflagellates (e.g. [Psalteriomonas lanterna](https://en.wikipedia.org/wiki/Psalteriomonas_lanterna))
anaerobic ciliates (e.g. [Nyctotherus ovalis](https://en.wikipedia.org/w/index.php?title=Nyctotherus_ovalis&action=edit&redlink=1), [Metopus palaeformis](https://en.wikipedia.org/w/index.php?title=Metopus_palaeformis&action=edit&redlink=1), [Trimyema compressum](https://en.wikipedia.org/w/index.php?title=Trimyema_compressum&action=edit&redlink=1), [Caenomorpha uniserialis](https://en.wikipedia.org/w/index.php?title=Caenomorpha_uniserialis&action=edit&redlink=1), [Dasytricha ruminantium](https://en.wikipedia.org/w/index.php?title=Dasytricha_ruminantium&action=edit&redlink=1))
anaerobic chytridiomycete fungi (e.g. [Neocallimastix](https://en.wikipedia.org/wiki/Neocallimastix) spp., [Piromyces](https://en.wikipedia.org/wiki/Piromyces) spp.)

**Comment by tberardini** [comment]
[Paper in 2005](https://academic.oup.com/bioscience/article/55/8/657/264621) says not in  plants. Can't find anything since then that says otherwise.

**Comment by ValWood** [comment]
- all good
