### ISSUE TITLE
astral spindle assembly (possible obsoletion)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24440]
Astral spindle assembly appears to be the same as 'normal spindle assembly'
as opposed to "anastral spindle asssembly'

It has only 3 EXP annotations (drosophila). @hattrill  can you comment on this term, and if it would be appropriate to migrate your annotations to the corresponding canonical spindle terms?

**Comment by ValWood** [comment]
Some context:

The spindle assembly organization in GO is independent of the type of MTOC:
<img width="468" alt="Screenshot 2022-11-25 at 07 43 05" src="https://user-images.githubusercontent.com/7359272/203927544-e0ece7d3-033b-4baa-bdca-17120f5091c1.png">

but then we have children:


GO:0090307    mitotic spindle assembly | is_a
GO:0051255    spindle midzone assembly | part_of
GO:0055048    anastral spindle assembly | is_a
GO:0055049    astral spindle assembly | is_a
GO:0090306    meiotic spindle assembly

so we have 2 axis of classification, anastral and astral are not much used. What do anastral spindles do? are they still:

The aggregation, arrangement and bonding together of a set of components to form the spindle, the array of microtubules and associated molecules that serves to move duplicated chromosomes apart.

**Comment by hattrill** [comment]
> 

I will have a look. Probably some phenotypic thing.

**Comment by hattrill** [comment]
Of the 3 annotations, 1 is FB, the other 2 are UniProt. 
FBgn0021761	Nup154 (UniProt)
FBgn0037301	Mms19 (UniProt)
FBgn0262598	mtsh (FlyBase)

Looking at them, I am happy for you to obsolete this term as there seems nothing special about this - for mtsh and Nup154, they are indirect/phenotypic. Mms19 is probably worth UniProt having another look at PMID:33211700 again to see what the best BPs are to describe it's action.

**Comment by ValWood** [comment]
@Antonialock  could you have a look at these 2 uniprot annotations?

**Comment by Antonialock** [comment]
I think the term can go?

I think the term might mean to distinguish between "inner spindle microtubules" and "astral microtubules"?
this paper mentions it (referenced in the mms19 paper):
https://www.sciencedirect.com/science/article/pii/S0960982219309418?via%3Dihub

this wikipedia graphic also shows the various MTs associating with spindles
![image](https://user-images.githubusercontent.com/12727506/218085199-ac00ec82-b7b8-4146-ad49-b4d334b30e06.png)


I moved the mms19 annotation to "astral microtubule organization"
based on
" It thus appears that Mms19 might bind along the surface of MTs, facilitating their assembly or stabilizing MTs, and possibly stimulating inter-MT contacts."

I deleted the nup154 annotation

**Comment by ValWood** [comment]
so it was referring to  the assembly/polymerization of 

GO:0061673  mitotic spindle astral microtubule

In that case good to obsolete because it's meaning was ambiguous (i.e a type of spindle, or part of the spindle)

**Comment by Antonialock** [comment]
I believe so.

**Comment by ValWood** [comment]
Action
obsolte 
GO:0055049    astral spindle assembly
and make it a related synonym of 
GO:0051225  spindle assembly

**Comment by ValWood** [comment]
Also GO:0055050    astral spindle assembly involved in male meiosis

**Comment by ValWood** [comment]
I didn't create an annotation spreadsheet as annotation were removed during the discussion.
