### ISSUE TITLE
Obsoletion request: GO:0035784 nickel cation homeostasis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24465]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0035784 nickel cation homeostasis

* **Reason for deprecation** Put an x in the appropriate box: 
 - [x] The reason for obsoletion is that the term is not clearly defined and usage has been inconsistent. For homeostasis terms, we would like to specify whether the homeostasis takes place intracellularly or at the level of the organism.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
 GO:0035785 cellular nickel ion homeostasis

* **Are there annotations to this term?**
- How many EXP: 1  EcoCyc 

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
No 

* **Is this term in a subset? (check the AmiGO page for that term)**
No 

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [x] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [x] paste the text in the ontology ticket

**Comment by raymond91125** [comment]
@pgaudet annotation ticket does not allow me to assign anyone but myself. Thanks.

**Comment by raymond91125** [comment]
Dear all, 

The proposal has been made to obsolete GO:0035784 nickel cation homeostasis.

* The reason for obsoletion is that the term is not clearly defined and usage has been inconsistent. For homeostasis terms, we would like to specify whether the homeostasis takes place intracellularly or at the level of the organism.

Annotations:
There are 1 experimental annotations to this term by
EcoCyc EXP 1

There are no mappings to this term.

This term is not present in any subset.

Annotations can be viewed here: https://github.com/geneontology/go-annotation/issues/4358

Annotations can be transferred to GO:0035785 cellular nickel ion homeostasis

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/24465. 
Unless objections are received by December 6, we will assume that you agree to this change.

Thanks, 

The GO-Ontology Editors

**Comment by amandamackie** [comment]
EcoCyc done
