### ISSUE TITLE
naming of mon,di,tri histone methyltransferases inconsistent:

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24469]
<img width="430" alt="Screenshot 2022-11-28 at 17 03 21" src="https://user-images.githubusercontent.com/7359272/204355541-fd80a8ea-8be3-40ab-8523-82c32fed4c6c.png">

**Comment by ValWood** [comment]
OK now I found
GO:0140942   histone H3K9 dimethyltransferase activity
isn't that the same as 
GO:0140947 histone H3K9me2 methyltransferase activity ?

**Comment by pgaudet** [comment]
No - the substrates are different

* GO:0140942 histone H3K9 dimethyltransferase activity : unmethylated substrate

* GO:0140947 histone H3K9me2 methyltransferase activity : dimethylated substrate. 

I thought the definitions were clear; please let me know if they can be improved (meanwhile I will close this, as there is no action). 
Thanks, Pascale
