### ISSUE TITLE
NTR: Histone H3K18 decrotonylase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24466]
Please provide as much information as you can: 

* **Suggested term label:**
Histone H3K18 decrotonylase activity

* **Definition (free text)**

Catalysis of the reaction: H2O + N6-(2E)-butenoyl-L-lysyl-[histone H3 position 18] + NAD+ = 2''-O-(2E)-but-2-enoyl-ADP-D-ribose + L-lysyl-[histone H3] + nicotinamide

maybe? I'm not sure where the position 18 / H3 slots in here, it's the first position specific decrotonylase term

* **Reference, in format PMID:#######**
pmid:34927582

* **Gene product name and ID to be annotated to this term**
SIR5 A0A0J9UVG7 Fusarium oxysporum f. sp. lycopersici

* **Parent term(s)**
GO:0160012 

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
2.3.1.-

* **Any other information**

**Comment by hdrabkin** [comment]
For enzymes, please provide RHEA and/or EC numbers.
2.3.1.-'

Please do NOT use EC:2.3.1.- for this leaf node activity. EC:2.3.1.- is  an EC mechanism class which includes all enzymes of EC:2.3.1.n
EC:2.3.1.- is 'Transferases: Acyltransferases transferring groups other than amino-acyl groups
3 digit ECs should NOT be used for leaf node activities ; only 4 digit ecs and/or rheas should be used. 
I would contact RHEA to make a term, patterning it after any of the other H3Kn activities
Typically if there is a RHEA reaction, they typically use the CHEBI id fo the lysine residue, and but label the entry more specifically.

**Comment by hdrabkin** [comment]
I know we still have many leaf node activities still we a 3 digit ec, which I remove as I come across them.

**Comment by pgaudet** [comment]
- [ ] GO: should be linked have database xref RHEA:69172 

Note that there is no specific RHEA for Histone H3K18 decrotonylase activity, so let's not put a cross reference on that new term (unless this activity will be created @amorgat @kaxelsen ? ) 

Thanks, Pascale

**Comment by hdrabkin** [comment]
Maybe one could use the RHEA as a broad xref, but as I pointed out before, I imagine that any term RHEA might make would still use the same CHEBI id ([CHEBI:137954](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=137954) for the residue. 
So for the time being, this term just won't have any xrefs. Not the first time.

**Comment by kaxelsen** [comment]
We will not create a specific reaction for histone as we already have RHEA:69172 (protein) that also covers histone.

**Comment by pgaudet** [comment]
@edwong57 Please create the term, with no cross references.

**Comment by pgaudet** [comment]
[Term]
id: GO:0170012
name: histone H3K18 decrotonylase activity
namespace: molecular_function
def: "Catalysis of the reaction: H2O + N6-(2E)-butenoyl-L-lysyl-[histone H3 position 18] + NAD+ = 2''-O-(2E)-but-2-enoyl-ADP-D-ribose + L-lysyl-[histone H3] + nicotinamide." [PMID:34927582]
is_a: GO:0160012 ! NAD-dependent histone decrotonylase activity
property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24466 xsd:anyURI
created_by: ew
creation_date: 2023-02-09T20:55:09Z
