### ISSUE TITLE
GO:0048872 'homeostasis of number of cells' causes conflicting taxon constraints

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#24471]
I can't regenerate the taxon constraints at the moment because of this entry: https://github.com/geneontology/go-ontology/blob/master/src/taxon_constraints/only_in_taxon.tsv#L878

(added in #24432)

'homeostasis of number of meristem cells' inherits 'only in Eumetazoa' from 'homeostasis of number of cells', but it inherits 'only in Viridiplantae' from 'meristem development'.

@ValWood which one should we remove? I'm guessing 'homeostasis of number of cells' can't be only in Eumetazoa.

**Comment by pgaudet** [comment]
it's only in multicellular organisms; do we have such a taxon? 

Otherwise we may need to use never in

**Comment by pgaudet** [comment]
Actually, GO:0048872 'homeostasis of number of cells'
is_a GO:0048871 multicellular organismal homeostasis

which has the following taxon constraints: 

* Never in Taxon | 2 | Bacteria |  
* Never in Taxon | 2157 | Archaea |  
* Never in Taxon | 4896 | Schizosaccharomyces pombe |  
* Never in Taxon | 4932 | Saccharomyces cerevisiae


so GO:0048872 'homeostasis of number of cells' does not need further taxon constraints. I removed the TC on GO:0048872.

Thanks, Pascale
