### ISSUE TITLE
Change 'ion/anion/cation' transport to monoatomic

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24479]
In https://github.com/geneontology/go-ontology/issues/24455 we decided that ChEBI 'ion', 'anion', 'cation' were grouping too many chemicals, and so we will change 
*  GO:0006811  ion transport ->>  monoatomic ion transport
* GO:0006812 cation transport ->> monoatomic cation transport
* GO:0006820 anion transport ->> monoatomic anion transport 
* GO:0098656  anion transmembrane transport ->> monoatomic anion transmembrane transport

- [x] adjust logical definitions accordingly
- [ ] adjust textual definitions accordingly

**Comment by pgaudet** [comment]
Same for 

- [ ] GO:0005216 ion channel activity ->>  monoatomic ion channel activity
- [ ] GO:0005253  anion channel activity  ->>  monoatomic anion channel activity
- [ ] GO:0005261  cation channel activity  ->>   monoatomic cation channel activity 
- [ ] GO:0008324  cation transmembrane transporter activity  ->>  monoatomic cation transmembrane transporter activity 
- [ ] GO:0008509 anion transmembrane transporter activity ->>   monoatomic anion transmembrane transporter activity 
- [ ] GO:0015075 ion transmembrane transporter activity  ->>   monoatomic ion transmembrane transporter activity
- [ ] GO:0022853  active ion transmembrane transporter activity ->>   active monoatomic ion transmembrane transporter activity 
- [ ] GO:0046583  cation efflux transmembrane transporter activity  ->>   monoatomic cation efflux transmembrane transporter activity 
- [ ] GO:0005221  intracellular cyclic nucleotide activated cation channel activity ->>    intracellular cyclic nucleotide activated monoatomic cation channel activity

**Comment by pgaudet** [comment]
- [ ] amino acid:cation antiporter activity ->> amino acid:monoatomic cation antiporter activity
- [ ] metal cation:cation antiporter activity ->>  metal cation:monoatomic cation antiporter activity 
- [ ] cation:proton antiporter activity  ->>  monoatomic cation:proton antiporter activity

**Comment by pgaudet** [comment]
- [ ]  solute:cation symporter activity  ->>  solute:monoatomic cation symporter activity
- [ ] 'acetate:cation symporter activity'  
- [ ] amino acid:cation symporter activity
- [ ] anion:cation symporter activity
- [ ] carbohydrate:cation symporter activity
- [ ] hexuronate:cation symporter activity
- [ ] nucleobase:cation symporter activity
- [ ] sialate:cation symporter activity

**Comment by pgaudet** [comment]
- [x] GO:0008381 mechanosensitive monoatomic ion channel activity
- [x] GO:0043854 cyclic nucleotide-gated mechanosensitive ion channel activity
- [x] GO:0140135 mechanosensitive cation channel activity
- [x] stretch-activated, cation-selective, calcium channel activity
- [x] stretch-activated, cation-selective, calcium channel activity involved in regulation of action potential
- [ ]

**Comment by pgaudet** [comment]
- [x] GO:0005244 voltage-gated ion channel activity
- [x]  GO:0008308 voltage-gated anion channel activity
- [x]  GO:0005247 voltage-gated chloride channel activity
- [x]  GO:0022843 voltage-gated cation channel activity
- [x]  GO:1905030 voltage-gated ion channel activity involved in regulation of postsynaptic membrane potential
- [x]  GO:0099508 voltage-gated ion channel activity involved in regulation of presynaptic membrane potential

**Comment by pgaudet** [comment]
- [ ] GO:0005217
-name: intracellular ligand-gated ion channel activity
+name: intracellular ligand-gated monoatomic ion channel activity

- [ ]  GO:0005230
-name: extracellular ligand-gated ion channel activity
+name: extracellular ligand-gated monoatomic ion channel activity

- [ ] GO:0005231
-name: excitatory extracellular ligand-gated ion channel activity
+name: excitatory extracellular ligand-gated monoatomic ion channel activity

- [ ] GO:0005237
-name: inhibitory extracellular ligand-gated ion channel activity
+name: inhibitory extracellular ligand-gated monoatomic ion channel activity

- [ ] GO:0015276
-name: ligand-gated ion channel activity
+name: ligand-gated monoatomic ion channel activity

- [ ] GO:0015454
-name: light-driven active ion transmembrane transporter activity
+name: light-driven active monoatomic ion transmembrane transporter activity

- [ ] GO:0019829
-name: ATPase-coupled cation transmembrane transporter activity
+name: ATPase-coupled monoatomic cation transmembrane transporter activity

- [ ] GO:0036081
-name: extracellular ammonia-gated ion channel activity
+name: extracellular ammonia-gated monoatomic ion channel activity

- [ ] GO:0036082
-name: extracellular phenylacetaldehyde-gated ion channel activity
+name: extracellular phenylacetaldehyde-gated monoatomic ion channel activity

- [ ] GO:0043855
-name: cyclic nucleotide-gated ion channel activity
+name: cyclic nucleotide-gated monoatomic ion channel activity

- [ ] GO:0099507
-name: ligand-gated ion channel activity involved in regulation of presynaptic membrane potential
+name: ligand-gated monoatomic ion channel activity involved in regulation of presynaptic membrane potential

- [ ] GO:0140829
-name: bicarbonate:anion antiporter activity
+name: bicarbonate:monoatomic anion antiporter activity

- [ ] GO:1904315
-name: transmitter-gated ion channel activity involved in regulation of postsynaptic membrane potential
+name: transmitter-gated monoatomic ion channel activity involved in regulation of postsynaptic membrane potential

- [ ] GO:1990760
-name: osmolarity-sensing cation channel activity
+name: osmolarity-sensing monoatomic cation channel activity

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
- GO:0005451 cation:proton antiporter activity  
- GO:0015298 solute:cation antiporter activity
- GO:0015299 solute:proton antiporter activity
- GO:0140323 solute:anion antiporter activity

The reason for obsoletion is that these grouping classes are too high level and not useful biologically. Moreover they cause ontology classification problems. 

There are 19 EXP annotations, as well as some Reactome and InterPro mappings, see 
https://github.com/geneontology/go-annotation/issues/4359


You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24479


Thanks, Pascale

**Comment by pgaudet** [comment]
Annotation checks here
https://docs.google.com/spreadsheets/d/1uXMaAat9-NNBSfjbtKv68kVuBsBg82MkYieL44EcW3E/edit#gid=0

**Comment by pgaudet** [comment]
I think this is complete

**Comment by rwst** [comment]
I agree the changes are not neutral and should have been verified. I mean, are the transported ions really all monoatomic? What am I missing here?

**Comment by pgaudet** [comment]
You are right, not all ions are monoatomic. 
The _intention_  was to distinguish small molecules from protonated amino acids, for example. Most compounds are ions in a cell. CheBI did not have 'small molecule', so we had to go for monoatomic. 

Did you find errors in the ontology due to this change?

**Comment by deustp01** [comment]
> Most compounds are ions in a cell.

glucose, ribose, ... ?

And amino acids are conventionally considered to be small molecules. Monoatomic ions like H+, Cl-, OK. Ions like PO4, more complicated. This looks like (yet another) gap and inconsistency in the ChEBI ontology, that we want to rely on but really can't.

**Comment by cmungall** [comment]
There are a few different strands in this discussion

@rwst raised the reasonable objection:
>  mean, are the transported ions really all monoatomic? What am I missing here?

We did in fact narrow the meaning of "GO:0006811 ion transport" and friends.

- previously it included classes like `thiamine transport` and `transferrin transport` as subclasses, as well as many more 
- now the subclasses are almost entirely monoatomic transport (with the exception of a couple of mistakes)

While normally this would necessitate an obsoletion, I believe our thinking here is that the current state reflects the original intent of the terms, but I would agree this is borderline.

I think the discussion about protonation states is largely tangential

- There is a related issue #30715, which came after and obsoletes protonation-based distinctions. It would be better to follow up there on anything protonation related
- For various complicated reasons explain in my simplifying CHEBI slide decks, protonation is somewhat relevant in that previously "ion transport" would auto-classify *anything which CHEBI thought to create protonation siblings for* (refer to the deck)

I propose that we leave this as closed, and accept that we were a bit close to the line on the decision as to rename vs obsolete.

**Comment by cmungall** [comment]
There are some lingering issues with the transition to monoatomic; e.g.

<img width="272" height="923" alt="Image" src="https://github.com/user-attachments/assets/28d02ee7-b19c-4648-9b29-7355fade99f1" />

**Comment by deustp01** [comment]
I don't know the biology here beyond what wikipedia says, but what gets transported is a multiatomic complex of sulfur atoms or ions and iron atoms or ions at least some of which are attached to one another by covalent bonds. If so, doesn't the term also need some sort of sulfur atom / ion parent for completeness? Or better, shouldn't the iron ion transport parent be removed, because the whole point of this transport is to move the whole package, to avoid interaction of other cellular components with the individual parts (which are reactive and toxic)? Just as it makes no sense to have carbon, hydrogen, and oxygen transport parents for glucose transport?
And so it's not monoatomic-anything transport. Not clear to me that that term is useful but even if it is, it's wrong as a parent here.

**Comment by cmungall** [comment]
@deustp01 exactly!

This branch is full of oddities, mostly caused by hidden GCIs:

<img width="1402" height="550" alt="Image" src="https://github.com/user-attachments/assets/aeb0cef2-8daa-4ea9-911f-90cde7beb828" />

<img width="1402" height="472" alt="Image" src="https://github.com/user-attachments/assets/9745428d-b06a-43c0-8418-bd939abe7841" />

<img width="1392" height="410" alt="Image" src="https://github.com/user-attachments/assets/e6b7efbd-ab66-4cbe-be31-caa9f063fdd7" />
