### ISSUE TITLE
NTR: [mitochondrial ribosomal large subunit binding]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#24488]
Please provide as much information as you can: 

* **Suggested term label:**
mitochondrial ribosomal large subunit binding

* **Definition (free text)**
Binding to mitochondrial a large ribosomal subunit.

* **Reference, in format PMID:#######**
PubMed=28892042

* **Gene product name and ID to be annotated to this term**
 MALSU1 UniProtKB/Q96EH3
* **Parent term(s)**
GO:0043021 ribonucleoprotein complex binding

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140978
+name: mitochondrial large ribosomal subunit binding
+namespace: molecular_function
+def: "Binding to a mitochondrial large ribosomal subunit." [PMID:28892042]
+synonym: "mitochondrial ribosomal large subunit binding" EXACT []
+is_a: GO:0097177 ! mitochondrial ribosome binding
+intersection_of: GO:0005488 ! binding
+intersection_of: has_input GO:0005762 ! mitochondrial large ribosomal subunit
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24488 xsd:anyURI
+created_by: pg
+creation_date: 2023-01-10T09:20:15Z
