### ISSUE TITLE
Textual definition update: typo in def. of GO:0002250 'adaptive immune response'

### ISSUE THREAD

**Issue by paola-scibite** [geneontology/go-ontology#24487]
* **GO term ID and label for which you request a definition update**
* GO:0002250 'adaptive immune response'

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
Def. currently reads
"An immune response mediated by cells expressing specific receptors _for antigen_ produced through a somatic diversification process, and allowing for an enhanced secondary response to subsequent exposures to the same antigen (immunological memory)." 
Source: [ISBN:0781735149](https://www.worldcat.org/search?q=bn%3A0781735149), GOC:add, [GO_REF:0000022](http://purl.obolibrary.org/obo/go/references/0000022)

Should it rather read "...expressing specific receptors _for an antigen_...", or "..._for antigens_..."?

Thanks,

Paola Roncaglia

**Comment by pgaudet** [comment]
Thanks for reporting this @paola-scibite

**Comment by addiehl** [comment]
I didn't really consider this an error, as antigen was used as an abstract mass noun in the original definition.  But the added 's' does not change the meaning so it is okay with me.
