### ISSUE TITLE
consider moving taxon constraints back into ontology

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#24490]
It might simplify the workflow to edit the taxon constraints directly within the ontology, rather than in TSVs. The challenge is that `never_in_taxon` annotations must be expanded into their logical form.

**Comment by cmungall** [comment]
Ah I see the challenge here - it's that the expanded form can't live in the .obo edit file it must live in an import

**Comment by pgaudet** [comment]
A suggestion from developers is that there would be a special keyword we could add in the PR that would automatically regenerate the imports

**Comment by pgaudet** [comment]
Maybe a GH action?

**Comment by pgaudet** [comment]
Related to https://github.com/geneontology/go-ontology/issues/24489

**Comment by pgaudet** [comment]
Discussion with @balhoff : the current system is easier for reasoning. We wont switch back (at least not now)
