### ISSUE TITLE
NTR: [neutral L-amino acid:basic L-amino acid antiporter activity]

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#24497]
Dear GO curators,

Please consider creating a generic broad-type GO term to map the amino acid transporter activity of P82251_SLC7A9_HUMAN:

new_GO neutral L-amino acid:basic L-amino acid antiporter activity

child of 
GO:0015297  antiporter activity
GO:0015174  basic amino acid transmembrane transporter activity
GO:0015175  neutral L-amino acid transmembrane transporter activity

definition 
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: basic L-amino acid(in) + neutral L-amino acid(out) = basic L-amino acid(in) + neutral L-amino acid(out).

synonyms
system b(0,+)-type activity
neutral L-amino acid:positively-charged polar L-amino acid antiporter activity
neutral L-amino acid:cationic L-amino acid antiporter activity
neutral L-amino acid:dibasic L-amino acid antiporter activity

refs
PMID:8663357 - https://pubmed.ncbi.nlm.nih.gov/8663357/ 
RHEA:71059 - https://www.rhea-db.org/rhea/71059; 
RHEA:71067 - https://www.rhea-db.org/rhea/71067; 
RHEA:71071 - https://www.rhea-db.org/rhea/71071
RHEA:71075 - https://www.rhea-db.org/rhea/71075
for review see PMID:23506863 - https://pubmed.ncbi.nlm.nih.gov/23506863/

*

Many thanks for your help.
Nevila Hyka-Nouspikel

**Comment by ValWood** [comment]
@nnouspikel thank you for the very clear ticket.
I didn't add the RHEA refs as these appear to be for the inputs and outputs not for the reaction.
Let me know if there is aa RHEA ID for the reaction.
I made the "system b(0,+)-type activity" synonym related because it looks a bit like a gene product. Let me know if that needs to change.

**Comment by pgaudet** [comment]
@ValWood Could you please paste the term stanza when you create a new term?

**Comment by pgaudet** [comment]
I suggest we rename this 'broad specificity neutral L-amino acid:basic L-amino acid antiporter activity' - otherwise we will be tempted to add specific neutral amino acid/amino acid transporters as chlidren, which would be wrong. 

OK ?

**Comment by pgaudet** [comment]
Also I misunderstood 
> I didn't add the RHEA refs 

I see you have added the xrefs. They need be source =skos:narrowMatch to avoid over propagation of annotations from UniProt entries having these specific reactions (because the GO term is broader in meaning than any of these RHEA reactions). 

Thanks, Pascale

**Comment by ValWood** [comment]
+[Term]
+id: GO:0180009
+name: neutral L-amino acid:basic L-amino acid antiporter activity
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: basic L-amino acid(in) + neutral L-amino acid(out) = basic L-amino acid(in) + neutral L-amino acid(out)." [PMID:23506863, PMID:8663357]
+synonym: "neutral L-amino acid:cationic L-amino acid antiporter activit" EXACT []
+synonym: "neutral L-amino acid:dibasic L-amino acid antiporter activity" EXACT []
+synonym: "neutral L-amino acid:positively-charged polar L-amino acid antiporter activity" EXACT []
+synonym: "system b(0,+)-type activity" RELATED []
+xref: RHEA:71059
+xref: RHEA:71067
+xref: RHEA:71071
+xref: RHEA:71075
+is_a: GO:0015174 ! basic amino acid transmembrane transporter activity
+is_a: GO:0015175 ! neutral L-amino acid transmembrane transporter activity
+is_a: GO:0015297 ! antiporter activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24497" xsd:anyURI
+created_by: vw
+creation_date: 2023-04-06T09:22:30Z

**Comment by ValWood** [comment]
But I did another commit where I removed the RHEA cross references.

I'm not sure how they should be added. I checked the docs and I couldn't see anything.
I don't understand where source =skos:narrowMatch goes.

I revised the label as part of my current branch issue-25186
but still need info  to add back the RHEA

**Comment by nnouspikel** [comment]
Hi Val and Pascale,

Thank you very much for the new term. I will try to create a generic RHEA for this antiporter activity, but it's not straightforward. Will let you know.

All the best,
Nevila

**Comment by pgaudet** [comment]
>  regarding 'broad specificity neutral L-amino acid:basic L-amino acid antiporter activity' - wouldn't that preclude use of this GO term for transporters that have narrow specificity?

Indeed, this is why we dont want to have specific children terms. The substrate-specific transporters would not be children of broad specificity transporters. 

This is what we decided on several ontology calls with @thomaspd and @cmungall . 


Thanks, Pascale

**Comment by balhoff** [comment]
> I'm not sure how they should be added. I checked the docs and I couldn't see anything. I don't understand where source =skos:narrowMatch goes.

@ValWood does this help? https://wiki.geneontology.org/Guidelines_for_database_cross_references

**Comment by nnouspikel** [comment]
Hi Alan,

Sorry for the late answer and thanks for your feedback. As a matter of fact I don’t need the generic reaction in UniProt. Nevertheless I tried to create one and realized that it is not feasible to create generics that structurally distinguish neutral amino acids from basic ones. Using skos:narrowMatch sounds ok. I let Val and Pascale decide.

All the best,
Nevila

**Comment by ValWood** [comment]
Outstanding from this ticket. I don't see how to do this part.
Please advise @pgaudet 
=======

I'm not sure how they should be added. I checked the docs and I couldn't see anything.
I don't understand where source =skos:narrowMatch goes.

I revised the label as part of my current branch issue-25186
but still need info to add back the RHEA
