### ISSUE TITLE
Obsoletion request: [GO:0031130:creation of an inductive signal]

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#24502]
* **GO:0031130:creation of an inductive signal** and child  
* **GO:0060511 creation of an inductive signal by a mesenchymal cell involved in lung induction**

* **Reason for deprecation**:
 - [x] The reason for obsoletion is that the term is not clearly defined and usage has been inconsistent.
 
-has not been used http://amigo.geneontology.org/amigo/term/GO:0031130 and is vague as inductive signaling is really any messgage from a cell via diffusion, intracellular communication or cell-cell contacts. Not really a groupable thing.

* **"Replace by" term (ID and label)**
None

* **"Consider" term(s) (ID and label)**
None
* **Are there annotations to this term?**
None

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
No

* **Is this term in a subset? (check the AmiGO page for that term)**
None

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [x] paste the text in the ontology ticket

**Comment by raymond91125** [comment]
Dear all,

The proposal has been made to obsolete GO:0031130 creation of an inductive signal
GO:0060511 creation of an inductive signal by a mesenchymal cell involved in lung induction

    The reason for obsoletion is that the term is not clearly defined and usage has been inconsistent
    -has not been used http://amigo.geneontology.org/amigo/term/GO:0031130 and is vague as inductive signaling is really any messgage from a cell via diffusion, intracellular communication or cell-cell contacts. Not really a groupable thing.

Annotations:
There are 0 experimental annotations to this term
Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/24502

Thanks,

The GO-Ontology Editors
