### ISSUE TITLE
Change label GO:0039648 modulation by virus of host protein ubiquitination 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24504]
- modulation by symbiont of host of protein ubiquitination
- Change def from:  Any process in which a virus modulates the frequency, rate or extent of protein ubiquitination in the host organism. Ubiquitination is the process in which one or more ubiquitin groups are added to a protein.
- 
to: Any process by which a symbiont increases or decreases ubiquitination of target proteins of a host organism.

@genegodbold

**Comment by genegodbold** [comment]
Hey @pgaudet, here are some examples from bacteria

1. Ank1U5 (OTBS0691) from Orientia tsutsugamushi, UniProt A5CD77: Ank1U5 localizes to the host nucleus where it mediates the ubiquitination and subsequent proteasomal degradation of host elongation factor 1 alpha. Direct binding of Ank1U5 to EF1alpha is observed. This has no significant effect on translation [PMID25166298].
2. AnkB (LegAU13; lpp2082) from Legionella pneumophila, UniProt Q5ZTL7: AnkB interacts specifically with the host E3 ubiquitin ligase TRIM21. The F-box domain of AnkB interacts with the host SCF1 E3 ubiquitin ligase that triggers the decoration of the Legionella containing vacuole (LCV) with K(48)-linked polyubiquitinated proteins that are targeted for proteasomal degradation. AnkB becomes rapidly polyubiquitinated within the host cell, and this modification is independent of the F-box domain of AnkB [PMID26483404]. AnkB is an effector protein of legionellae anchored to the cytosolic side of the legionellae containing vacuole (LCV). AnkB is translocated into the host cell via the Dot/Icm secretion system in an IcmSW-dependent manner and that the last three C-terminal amino acid residues are essential for translocation. AnkB mutant-containing phagosomes exclude late endosomal and lysosomal markers and their phagosomes are remodelled by the rough endoplasmic reticulum. Mutation of AnkB causes a severe growth defect in Legionellae in host cells [PMID18811729]. 
3. AvrA from Salmonella, UniProt O30621: AvrA is a deubiquitinase that acts on host IkappaBalpha and beta-catenin. AvrA blocks degradation of IkappaBalpha leading to the inhibition of NFkappaB and beta-catenin in epithelial cells to counter host immune signaling [PMID17690189]. This suppresses secretion of cytokines including IL-12, IFNgamma, and TNF [PMID20463922].  AvrA is allosterically activated by host inositol hexakisphosphate (IP6) which is absent from bacteria [PMID20430892]. 
4. Avirulence PtoB (AvrPtoB; HopAB2) from Pseudomonas syringae, UniProt Q8RSY1: AvrPtoB is a T3SS effector with E3 ubiquitin ligase activity that ubiquitinates the kinase domain of plant host CERK1 and thereby targets it for degradation in the host cell [PMID19249211].  AvrPtoB blocks all defense responses through this receptor which is critical for resistance to both fungal and bacterial pathogens [PMID19249211]. AvrPtoB targets host BAK1, a plasma-membrane localized receptor-like kinase involved in multiple immune signaling pathways that is also targeted by Pseudomonas syringae proteins AvrPto and HopF2 [PMID24237140].
5. Cell-cycle inhibiting factor (Cif) from E. coli, UniProt Q7WRZ5: Cif inhibits protein ubiquitination by deamidating Gln40 in both ubiquitin and the ubiquitin-like protein Nedd8. Deamidated ubiquitin is impaired in supporting the growth of ubiquitin chains. Deamidated Nedd8 abolishes the activity of neddylated E3 ubiquitin ligases of the Cullin type. Selective deamidation of Nedd8 by Cif is linked to EPEC infection-induced cell cycle arrest and actin stress fiber formation [PMID20688984].
6. Invasion plasmid antigen H1.4 (IpaH1.4) from Shigella, UniProtQ3YTD2: IpaH1.4 and IpaH2.5 are T3SS effectors of Shigella that interact directly with the multimeric host E3 ligase LUBAC that catalyzes linear ubiquitination of activated immune receptor signaling complexes via the HOIL-1L subunit. IpaH1.4 and IpaH2.5 thus direct the ubiquitination of host protein HOIP. HOIP ubiquitination leads to its proteasomal destruction which irreversibly inactivates linear ubiquitination. This in turn leads to the inhibition of NFkappaB activation by blocking its nuclear translocation in response to upstream immune signaling [PMID27572974].
7. Salmonella secreted effector L (SseL): SseL is a protease that serves as a deubiquitinase for Salmonella, reducing elimination of the bacteria by host cell xenophagy [PMID22719249].

There are more than 50 others that manipulate host ubiquitin dynamics (on/off) that I've got documented.

**Comment by edwong57** [comment]
Fixed.
