### ISSUE TITLE
Change labels and definitions 'cellular homeostasis' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24514]
To clarify the usage of these terms, the labels will be changed to 
'intracellular x homeostasis'
and the definition to 'A homeostatic process involved in the maintenance of a steady state level of a chemical within a cell."

'cellular chemical homeostasis'
'cellular abscisic acid homeostasis'
'cellular acyl-CoA homeostasis'
'cellular amino acid homeostasis'
'cellular arginine homeostasis'
'cellular aspartate homeostasis'
'cellular cysteine homeostasis'
'cellular glutamate homeostasis'
'cellular histidine homeostasis'
'cellular lysine homeostasis'
'cellular ornithine homeostasis'
'cellular threonine homeostasis'
'cellular ammonium homeostasis'
'cellular galactose homeostasis'
'cellular glucose homeostasis'
'cellular response to glucose stimulus'
'cellular monoatomic ion homeostasis'
'cellular monoatomic anion homeostasis'
'cellular monoatomic cation homeostasis'
'cellular nitric oxide homeostasis'
'cellular oxygen homeostasis'
'cellular phosphate ion homeostasis'
'cellular sphingolipid homeostasis'
'cellular sulfate ion homeostasis'
'cellular sulfide ion homeostasis'
'cellular triglyceride homeostasis'
'cellular water homeostasis'

**Comment by deustp01** [comment]
Now is probably not the best time to ask, but is there in fact evidence that at least some kinds of cells in some taxa have sensory and regulatory processes place to detect the abundance of each of these small molecules and to adjust transport and metabolic processes to restore a correct level?

**Comment by pgaudet** [comment]
I haven't seen anything like this. We can create the terms if needed - in this case 'extracellular x homeostasis' would work, I think.

**Comment by deustp01** [comment]
> is there in fact evidence

Different issue. What I'm fretting about is whether any cell ever does importing / exporting / sequestering / mobilizing things to ensure that its galactose level is maintained steady within a narrow concentration range. If not, is there such a things as galactose homeostasis? (That's also why I'm not sure this is a good time to raise this issue.)

**Comment by ukemi** [comment]
Maybe my memory isn't so bad.
PMID: 21621292

**Comment by pgaudet** [comment]
Added the reference to GO:0033502
 name: intracellular galactose homeostasis

Thanks both!

**Comment by pgaudet** [comment]
GO:0030642 cellular sulfate ion homeostasis ==> add reference PMID:24193406
