### ISSUE TITLE
go-lego currently not building

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#24517]
From @kltm's test pipeline:

## [viral capsid precursor transport to host cell nucleus](http://purl.obolibrary.org/obo/GO_0046752) SubClassOf [Nothing](http://www.w3.org/2002/07/owl#Nothing) ##

  - [viral capsid precursor transport to host cell nucleus](http://purl.obolibrary.org/obo/GO_0046752) SubClassOf [symbiont intracellular protein transport in host](http://purl.obolibrary.org/obo/GO_0030581)
    - [symbiont intracellular protein transport in host](http://purl.obolibrary.org/obo/GO_0030581) EquivalentTo [protein transport](http://purl.obolibrary.org/obo/GO_0015031) and ([occurs in](http://purl.obolibrary.org/obo/BFO_0000066) some [host cell](http://purl.obolibrary.org/obo/GO_0043657))
      - [protein transport](http://purl.obolibrary.org/obo/GO_0015031) SubClassOf [establishment of protein localization](http://purl.obolibrary.org/obo/GO_0045184)
        - [establishment of protein localization](http://purl.obolibrary.org/obo/GO_0045184) EquivalentTo [establishment of localization](http://purl.obolibrary.org/obo/GO_0051234) and ([has primary input](http://purl.obolibrary.org/obo/RO_0004009) some [protein](http://purl.obolibrary.org/obo/CHEBI_36080))
          - [establishment of localization](http://purl.obolibrary.org/obo/GO_0051234) SubClassOf [localization](http://purl.obolibrary.org/obo/GO_0051179)
          - [protein](http://purl.obolibrary.org/obo/CHEBI_36080) EquivalentTo [protein](http://purl.obolibrary.org/obo/PR_000000001)
  - [viral capsid precursor transport to host cell nucleus](http://purl.obolibrary.org/obo/GO_0046752) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [nuclear capsid assembly](http://purl.obolibrary.org/obo/GO_0039708)
    - [nuclear capsid assembly](http://purl.obolibrary.org/obo/GO_0039708) EquivalentTo [viral capsid assembly](http://purl.obolibrary.org/obo/GO_0019069) and ([occurs in](http://purl.obolibrary.org/obo/BFO_0000066) some [host cell nucleus](http://purl.obolibrary.org/obo/GO_0042025))
      - [viral capsid assembly](http://purl.obolibrary.org/obo/GO_0019069) EquivalentTo [viral process](http://purl.obolibrary.org/obo/GO_0016032) and ([results in assembly of](http://purl.obolibrary.org/obo/RO_0002588) some [viral capsid](http://purl.obolibrary.org/obo/GO_0019028))
        - [results in assembly of](http://purl.obolibrary.org/obo/RO_0002588) SubPropertyOf: [results in formation of](http://purl.obolibrary.org/obo/RO_0002297)
          - [results in formation of](http://purl.obolibrary.org/obo/RO_0002297) SubPropertyOf: [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295)
        - [viral capsid](http://purl.obolibrary.org/obo/GO_0019028) SubClassOf [virion component](http://purl.obolibrary.org/obo/GO_0044423)
          - [virion component](http://purl.obolibrary.org/obo/GO_0044423) SubClassOf [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some (not ([cellular organisms](http://purl.obolibrary.org/obo/NCBITaxon_131567)))
  - [native cell](http://purl.obolibrary.org/obo/CL_0000003) SubClassOf [cell](http://purl.obolibrary.org/obo/CL_0000000)
  - [cellular process](http://purl.obolibrary.org/obo/GO_0009987) SubClassOf [occurs in](http://purl.obolibrary.org/obo/BFO_0000066) some [cell](http://purl.obolibrary.org/obo/DDANAT_0000401)
  - [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [protein localization](http://purl.obolibrary.org/obo/GO_0008104) SubClassOf [cellular macromolecule localization](http://purl.obolibrary.org/obo/GO_0070727)
  - [cell](http://purl.obolibrary.org/obo/DDANAT_0000401) EquivalentTo [native cell](http://purl.obolibrary.org/obo/CL_0000003) and ([in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Dictyostelium discoideum](http://purl.obolibrary.org/obo/NCBITaxon_44689))
  - [protein localization](http://purl.obolibrary.org/obo/GO_0008104) EquivalentTo [localization](http://purl.obolibrary.org/obo/GO_0051179) and ([has primary input](http://purl.obolibrary.org/obo/RO_0004009) some [protein](http://purl.obolibrary.org/obo/PR_000000001))
  - [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)
  - [cellular localization](http://purl.obolibrary.org/obo/GO_0051641) SubClassOf [cellular process](http://purl.obolibrary.org/obo/GO_0009987)
  - [establishment of localization in cell](http://purl.obolibrary.org/obo/GO_0051649) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [cellular organisms](http://purl.obolibrary.org/obo/NCBITaxon_131567)
  - [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [cellular organisms](http://purl.obolibrary.org/obo/NCBITaxon_131567) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some (not ([cellular organisms](http://purl.obolibrary.org/obo/NCBITaxon_131567)))
  - [establishment of localization in cell](http://purl.obolibrary.org/obo/GO_0051649) EquivalentTo [establishment of localization](http://purl.obolibrary.org/obo/GO_0051234) and ([occurs in](http://purl.obolibrary.org/obo/BFO_0000066) some [cell](http://purl.obolibrary.org/obo/CL_0000000))
  - [cellular macromolecule localization](http://purl.obolibrary.org/obo/GO_0070727) SubClassOf [cellular localization](http://purl.obolibrary.org/obo/GO_0051641)
  - [part of](http://purl.obolibrary.org/obo/BFO_0000050) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162)

# Axiom Impact 
## Axioms used 1 times
- [protein](http://purl.obolibrary.org/obo/CHEBI_36080) EquivalentTo [protein](http://purl.obolibrary.org/obo/PR_000000001) [go-plus.owl]
- [cell](http://purl.obolibrary.org/obo/DDANAT_0000401) EquivalentTo [native cell](http://purl.obolibrary.org/obo/CL_0000003) and ([in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [Dictyostelium discoideum](http://purl.obolibrary.org/obo/NCBITaxon_44689)) [go-lego.owl]
- [protein localization](http://purl.obolibrary.org/obo/GO_0008104) EquivalentTo [localization](http://purl.obolibrary.org/obo/GO_0051179) and ([has primary input](http://purl.obolibrary.org/obo/RO_0004009) some [protein](http://purl.obolibrary.org/obo/PR_000000001)) [go-plus.owl]
- [viral capsid assembly](http://purl.obolibrary.org/obo/GO_0019069) EquivalentTo [viral process](http://purl.obolibrary.org/obo/GO_0016032) and ([results in assembly of](http://purl.obolibrary.org/obo/RO_0002588) some [viral capsid](http://purl.obolibrary.org/obo/GO_0019028)) [go-plus.owl]
- [symbiont intracellular protein transport in host](http://purl.obolibrary.org/obo/GO_0030581) EquivalentTo [protein transport](http://purl.obolibrary.org/obo/GO_0015031) and ([occurs in](http://purl.obolibrary.org/obo/BFO_0000066) some [host cell](http://purl.obolibrary.org/obo/GO_0043657)) [go-plus.owl]
- [nuclear capsid assembly](http://purl.obolibrary.org/obo/GO_0039708) EquivalentTo [viral capsid assembly](http://purl.obolibrary.org/obo/GO_0019069) and ([occurs in](http://purl.obolibrary.org/obo/BFO_0000066) some [host cell nucleus](http://purl.obolibrary.org/obo/GO_0042025)) [go-plus.owl]
- [establishment of protein localization](http://purl.obolibrary.org/obo/GO_0045184) EquivalentTo [establishment of localization](http://purl.obolibrary.org/obo/GO_0051234) and ([has primary input](http://purl.obolibrary.org/obo/RO_0004009) some [protein](http://purl.obolibrary.org/obo/CHEBI_36080)) [go-plus.owl]
- [establishment of localization in cell](http://purl.obolibrary.org/obo/GO_0051649) EquivalentTo [establishment of localization](http://purl.obolibrary.org/obo/GO_0051234) and ([occurs in](http://purl.obolibrary.org/obo/BFO_0000066) some [cell](http://purl.obolibrary.org/obo/CL_0000000)) [go-plus.owl]
- [native cell](http://purl.obolibrary.org/obo/CL_0000003) SubClassOf [cell](http://purl.obolibrary.org/obo/CL_0000000) [cl.owl,go-plus.owl]
- [protein localization](http://purl.obolibrary.org/obo/GO_0008104) SubClassOf [cellular macromolecule localization](http://purl.obolibrary.org/obo/GO_0070727) [go-plus.owl]
- [cellular process](http://purl.obolibrary.org/obo/GO_0009987) SubClassOf [occurs in](http://purl.obolibrary.org/obo/BFO_0000066) some [cell](http://purl.obolibrary.org/obo/DDANAT_0000401) [go-plus.owl]
- [protein transport](http://purl.obolibrary.org/obo/GO_0015031) SubClassOf [establishment of protein localization](http://purl.obolibrary.org/obo/GO_0045184) [go-plus.owl]
- [viral capsid](http://purl.obolibrary.org/obo/GO_0019028) SubClassOf [virion component](http://purl.obolibrary.org/obo/GO_0044423) [go-plus.owl]
- [virion component](http://purl.obolibrary.org/obo/GO_0044423) SubClassOf [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some (not ([cellular organisms](http://purl.obolibrary.org/obo/NCBITaxon_131567))) [go-plus.owl]
- [viral capsid precursor transport to host cell nucleus](http://purl.obolibrary.org/obo/GO_0046752) SubClassOf [symbiont intracellular protein transport in host](http://purl.obolibrary.org/obo/GO_0030581) [go-plus.owl]
- [viral capsid precursor transport to host cell nucleus](http://purl.obolibrary.org/obo/GO_0046752) SubClassOf [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [nuclear capsid assembly](http://purl.obolibrary.org/obo/GO_0039708) [go-plus.owl]
- [establishment of localization](http://purl.obolibrary.org/obo/GO_0051234) SubClassOf [localization](http://purl.obolibrary.org/obo/GO_0051179) [go-plus.owl]
- [cellular localization](http://purl.obolibrary.org/obo/GO_0051641) SubClassOf [cellular process](http://purl.obolibrary.org/obo/GO_0009987) [go-plus.owl]
- [establishment of localization in cell](http://purl.obolibrary.org/obo/GO_0051649) SubClassOf [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) some [cellular organisms](http://purl.obolibrary.org/obo/NCBITaxon_131567) [go-plus.owl]
- [cellular macromolecule localization](http://purl.obolibrary.org/obo/GO_0070727) SubClassOf [cellular localization](http://purl.obolibrary.org/obo/GO_0051641) [go-plus.owl]
- [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some [cellular organisms](http://purl.obolibrary.org/obo/NCBITaxon_131567) DisjointWith [in taxon](http://purl.obolibrary.org/obo/RO_0002162) some (not ([cellular organisms](http://purl.obolibrary.org/obo/NCBITaxon_131567))) [go-plus.owl]
- [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [ro.owl,go-plus.owl]
- [results in formation of](http://purl.obolibrary.org/obo/RO_0002297) SubPropertyOf: [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295) [ro.owl,go-plus.owl]
- [results in assembly of](http://purl.obolibrary.org/obo/RO_0002588) SubPropertyOf: [results in formation of](http://purl.obolibrary.org/obo/RO_0002297) [ro.owl,go-plus.owl]
- [part of](http://purl.obolibrary.org/obo/BFO_0000050) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [ro.owl,go-plus.owl]
- [results in developmental progression of](http://purl.obolibrary.org/obo/RO_0002295) o [in taxon](http://purl.obolibrary.org/obo/RO_0002162) SubPropertyOf: [in taxon](http://purl.obolibrary.org/obo/RO_0002162) [ro.owl,go-plus.owl]

# Ontologies used: 
- go-lego.owl (http://purl.obolibrary.org/obo/go/extensions/go-lego.owl)
- cl.owl (http://purl.obolibrary.org/obo/mirror/cl.owl)
- go-plus.owl (http://purl.obolibrary.org/obo/go/extensions/go-plus.owl)
- ro.owl (http://purl.obolibrary.org/obo/ro.owl)

**Comment by balhoff** [comment]
Here is the cause: https://github.com/geneontology/go-ontology/pull/24515/files#diff-4f6e0296bc084cd5c8a2ab6cda4ecd3e62bdce48fa7a67b74d22ff5737c7e635L95806-R95817

@pgaudet the Dicty cell was used by accident (we should fix the import to change its label, since this problem is nearly impossible to avoid in Protege). If the logical definition is changed to CL:cell, this problem can be seen in the GO edit file.

**Comment by pgaudet** [comment]
removed 
GO:0044417 translocation of molecules into host 
is_a GO:0015031 ! protein transport
