### ISSUE TITLE
NTR intracellular borate homeostasis 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24521]
PMID:15525507

LD: 'chemical homeostasis'
 and ('regulates levels of' some  CHEBI:41132 - tetrahydroxoborate(1−) ) 

Def: A homeostatic process involved in the maintenance of a steady state level of tetrahydroxoborate within a cell.

Synonyms: 
- intracellular boron homeostasis 
- intracellular tetrahydroxoborate homeostasis 

Thanks, Pascale

**Comment by raymond91125** [comment]
should LD be something like 'cellular homeostasis' 
 and ('regulates levels of' some 'tetrahydroxoborate(1-))? otherwise it does not get connected to 'cellular homeostasis'.

**Comment by pgaudet** [comment]
Sorry @raymond91125 I thought you had added the logical definition with 'intracellular' - I now fixed that, this ticket is now done.
