### ISSUE TITLE
Design pattern for molecular function regulator/activator/inhibitor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24530]
Hi @balhoff 

I will change the relations for 
https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/regulator_activity.yaml
https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/activator_activity.yaml
https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/inhibitor_activity.yaml

to use 'directly regulates', directly positively regulate' and 'directly negatively regulates' - but I wonder about the genus:
activator and inhibitor are using 'molecular function activator' and 'molecular function activator' - while in the BP 'regulation' branch we use 'regulation' for both positive and 'negative'. 

Is this intentional? should we aligns these two groups of patterns (mf regulator activity & bp regulation)? 

Thanks, Pascale

**Comment by balhoff** [comment]
I think it would make sense to align: use [molecular function regulator activity](http://purl.obolibrary.org/obo/GO_0098772) as the genus for all three patterns.

**Comment by pgaudet** [comment]
Done 

also updated DP 
https://github.com/geneontology/go-ontology/pull/24540
https://github.com/geneontology/go-ontology/pull/24539
https://github.com/geneontology/go-ontology/pull/24538
