### ISSUE TITLE
Obsolete GO:0044728 DNA methylation or demethylation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24545]
Unnecessary grouping class
No annotations

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0044728 DNA methylation or demethylation. The reason for obsoletion is that this is an unnecessary grouping term. There are no annotations, no mappings; this term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24545

Thanks, Pascale

**Comment by pfey03** [comment]
We had 3 annotations but we had functions and I deleted those

**Comment by pgaudet** [comment]
You had annotations to 'GO:0006306 DNA methylation' and  'GO:0032776  DNA methylation on cytosine' - these were not obsoleted (yet ;) - I need to make sure these are single step. 

Anyways, nice that you've annotated to more specific terms, thanks @pfey03 


[DNA methylation](http://amigo.geneontology.org/amigo/term/GO:0006306)'

**Comment by pfey03** [comment]
I always check QuickGO and those are true

**Comment by pgaudet** [comment]
Done in https://github.com/geneontology/go-ontology/pull/24549
