### ISSUE TITLE
NTR: Casparian strip formation

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24557]
Please provide as much information as you can: 

* **Suggested term label:**

Casparian strip formation

* **Definition (free text)**

A process that results in the assembly, arrangement of constituent parts, or disassembly of the Casparian strip, the region of plant cell wall specialised to act as a seal to prevent back leakage of secreted material (analogous to tight junction between epithelial cells). Found particularly where root parenchymal cells secrete solutes into xylem vessels. 

* **Reference, in format PMID:#######**
 PMID:28104889

* **Gene product name and ID to be annotated to this term**
Q84MD2
O65684

* **Parent term(s)**
GO:0009664 plant-type cell wall organization

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
@Antonialock 

Why not 'Casparian strip assembly'? (I imagine the assembly and disassembly pathways to be very different, not sure if the latter exists). 

In this case parents would be 
- is_a GO:0022607 cellular component assembly
- part_of GO:0071668 plant-type cell wall assembly

Thanks, Pascale

**Comment by Antonialock** [comment]
I meant to say that I had never heard of these structures until yesterday (so yes, feel free to make suggestions!)

The referenced paper suggested that there can be some development to casparian strips later in the plant's life if adverse soil conditions require it (contrary to old thinking that the strip forms and that's it) which made me think "rearrangement of parts" - but perhaps it is more like "reinforcement" which isn't really a dynamic restructuring.

Assembly is probably fine?

**Comment by pgaudet** [comment]
Let's ask @tberardini to comment

**Comment by tberardini** [comment]
Could we use 'Casparian strip formation' as that is the string that is more commonly used (vs. Casparian strip assembly). If it's cleaner to use assembly as the primary term name, that should be ok, if you can add formation as a synonym.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160073
+name: Casparian strip assembly
+namespace: biological_process
+def: "The aggregation, arrangement and bonding together of a set of components to form a Casparian strip, a region of plant cell wall specialised to act as a seal to prevent back leakage of secreted material." [PMID:28104889]
+synonym: "Casparian strip formation" EXACT []
+intersection_of: GO:0022607 ! cellular component assembly
+intersection_of: results_in_assembly_of GO:0048226 ! Casparian strip
+relationship: part_of GO:0071668 ! plant-type cell wall assembly
+created_by: rynl
+creation_date: 2023-01-10T00:56:06Z
