### ISSUE TITLE
NTR - primary active transporter activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24558]
* **Suggested term label:**
primary active transporter activity

* **Definition (free text)**
Catalysis of the movement of substances (such as solutes or lipids) from one side of a membrane or membrane leaflet to the other, powered by a primary energy source such as ATP hydrolysis, redox energy or photon energy. [GOC]
_(I've modified/generalized the definitions of the existing parent terms of the two children specified below)_

* **Parent term(s)**
transporter activity (GO:0005215)
catalytic activity (GO:0003824)

* **Synonym(s) (please specify, EXACT, BROAD, NARROW or RELATED)**
translocase activity [EXACT]

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
primary active transmembrane transporter activity (GO:0015399)
ATPase-coupled intramembrane lipid transporter activity (GO:0140326)

* **Cross-references**
EC:7.-.-.-

* **Any other information**
1. 'primary active transmembrane transporter activity' (GO:0015399) currently has EC:7.-.-.- xref, but the name & definition of this GO term excludes "ATPase-coupled intramembrane lipid transporter activity" (GO:0140326), which has xref of EC:7.6.2.1.
So EC:7.-.-.- should be removed from GO:0015399, and added to the proposed term above that groups both the catalytic transmembrane and the catalytic intramembrane transporters.

2. GO:0015399 and GO:0140326 do not currently have parentage in the 'catalytic activity' branch of the GO. This can be rectified by making them children of the NTR, which itself is proposed to a be a child of 'catalytic activity'.

@kaxelsen Please say if the above make sense to you?

**Comment by pgaudet** [comment]
GO:0015399 has part 'some 'catalytic activity'
GO:0140326 'has part' some 'ATP hydrolysis activity'

we cannot use is_a, see https://github.com/geneontology/go-ontology/projects/32

**Comment by pgaudet** [comment]
We should document this somewhere, we keep on getting confused about this

**Comment by pgaudet** [comment]
> What does NTR stand for?

New term request

**Comment by sjm41** [comment]
Thanks for explaining the 'has part' thing (again!) Pascale. I think my problem is that the tools I use for viewing the GO (FlyBase, QuickGO, the go-basic.obo file) don't show that relation, and queries using those tools don't retrieve things via 'has part'....

But I think the NTR (new term request) here still stands to correct the EC:7 xref issue and thus align with the EC translocase class?

**Comment by sjm41** [comment]
Thanks @kaxelsen. Following your comment, the alternative solution here would be to (i) not make the new grouping term, (ii) leave the EC:7 xref on GO:0015399, and (iii) make GO:0140326 a child of GO:0015399.

**Comment by pgaudet** [comment]
Sorry @sjm41 I just noticed - 


GO:0140326 | ATPase-coupled **intramembrane** lipid transporter activity is not a **transmembrane** transport, so we cannot add the relation you propose.

**Comment by kaxelsen** [comment]
> Sorry @sjm41 I just noticed -
> 
@pgaudet 
> GO:0140326 | ATPase-coupled **intramembrane** lipid transporter activity is not a **transmembrane** transport, so we cannot add the relation you propose.

Note that this transport is **intramembrane** since the lipid is inserted into the membrane so for P-type ATPases (flippases) this is a special case of transmembrane transport.
