### ISSUE TITLE
NTR:anthocyanin:proton antiporter activity

### ISSUE THREAD

**Issue by tberardini** [geneontology/go-ontology#24551]
* **Suggested term label:**
anthocyanin:proton antiporter activity

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: H+(out) + anthocyanin(in) = H+(in) + anthocyanin(out).

* **Reference, in format PMID:#######**
PMID:17601828

* **Gene product name and ID to be annotated to this term**
AGI_LocusCode:AT3G59030

* **Parent term**
    GO:0015078
    proton transmembrane transporter activity

**Comment by pgaudet** [comment]
Hi @tberardini 

I created a new term for the mammalian ortholog of MATE  (AGI_LocusCode:AT3G59030) in #24594; can you use that term ? this is also consistent with what is in the paper abstract: 

> the Arabidopsis thaliana transparent testa12 (tt12) mutant encoding a membrane protein of the multidrug and toxic efflux transporter family

[Term]
+id: GO:0140968
+name: polyspecific proton:organic cation antiporter activity

Thanks, Pascale

**Comment by tberardini** [comment]
I could use this MF term. Do you recommend doing that for the MF and instead having a term like 'flavonoid transport' for process?

**Comment by pgaudet** [comment]
Sure, I think that makes sense - ie the MF term describes the broad specificity of the activity, but within specific contexts it transports specific substances. Does that makes sense?

**Comment by tberardini** [comment]
I think we want to capture the biologically relevant specificity somewhere - either MF or BP, in some cases both, right? For this case, what would you/rest of team recommend: 'flavonoid:proton antiporter activity' (I made it more general) AND/OR a 'flavonoid transport' terms?
