### ISSUE TITLE
merge/add parent-child to "CoA pyrophosphatase activity" & "acyl-coenzyme A diphosphatase activity"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24569]
Looking at these two sister terms:

id: GO:0010945
name: CoA pyrophosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: coenzyme A or its derivatives + H2O = 3',5'-ADP + 4'-phosphopantetheine." [GOC:tb, PMID:10922370, PMID:16185196]
synonym: "conezyme A pyrophosphatase activity" RELATED []
xref: Reactome:R-HSA-6809354 "NUDT7 hydrolyses CoA-SH to 3',5'-ADP and PPANT"
xref: Reactome:R-HSA-6810474 "NUDT19 hydrolyses acyl-CoA to 3',5'-ADP and acyl-PPANT"
is_a: GO:0016462 ! pyrophosphatase activity

id: GO:0106399
name: acyl-coenzyme A diphosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: an acyl-CoA + H2O = adenosine 3',5'-bisphosphate + an acyl-4'-phosphopantetheine + 2 H+." [PMID:32915949, RHEA:50044]
xref: RHEA:50044
is_a: GO:0016462 ! pyrophosphatase activity

Should these be merged?
If not, then I think "CoA pyrophosphatase activity" (def says substrate is **coenzyme A or its derivatives**) should be a parent to "acyl-coenzyme A diphosphatase activity"

**Comment by sjm41** [comment]
Also see #19787 (GO:0010945 discussion) and #21216(GO:0106399 request)

**Comment by hdrabkin** [comment]
but using RHeA for the CHEBI, 
  CHEBI:58342  (ends in CH2-S-CO-R)  is not  CHEBI:15346 (coenzyme A); ends in CH2-SH
Even if the R group in 58342 is H, then CH2-S-COH (acyl CoA) is not CH2SH

GO:0010945 implies that one of the substrates is coenzyme A, whereas GO:0010945 implies it has to be some acyl-CoA

If we parallel parentage
I don't think acyl-CoA is_a CoA   in CHEBI (@kaxelsen  is this correct or am I reading the graph incorrectly); so the parentage you suggest does not align.


the PMIDs used for the def of GO:0010945
One indicates activity using CoA substrate PMID: 10922370
The other indicates activity towards acyl-CoA and derivatives (So maybe shouldn't be used for def).PMID: 16185196

Also note that the product of one is 
4'-phosphopantetheine
But the the other an  acyl-4'-phosphopantetheine

**Comment by sjm41** [comment]
OK, never mind!
Does that mean there should be a RHEA for GO:0010945 CoA pyrophosphatase activity??

**Comment by hdrabkin** [comment]
@sjm41 let me fly that by RHEA, using PMID: 10922370 as the reference. It seems it's not a very good substrate based on Km and Vmax 'enzyme has a 13-fold higher kcat/Km ratio for CoASSCoA compared
with CoA" (and figs 2 and 3).

**Comment by kaxelsen** [comment]
That is correct.  acyl-CoA has functional parent CoA, which has a different meaning than is_a

**Comment by pgaudet** [comment]
There is a new RHEA for GO:0010945  CoA pyrophosphatase activity
https://www.rhea-db.org/rhea/75715
(also mapped to MetaCyc:RXN-10811, so added that xref as well)

**Comment by pgaudet** [comment]
OK, looking at the annotations and the RHEA reactions, I think the merge was the better option, see #4796

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0106399 acyl-coenzyme A diphosphatase activity. The reason for obsoletion is that this represents the same activity as GO:0010945 CoA pyrophosphatase activity. There is a single EXP annotation to this term by UniProt. No action is needed, as GO:0106399 will be replaced by GO:0010945. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24569

Thanks, Pascale
