### ISSUE TITLE
 NTR piRNA-mediated transposon silencing and ~tRNA-mediated transposon silencing~

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24561]
NTR piRNA-mediated transposon silencing

    NTR tRNA-mediated transposon silencing

https://pubmed.ncbi.nlm.nih.gov/33789107/

Split from https://github.com/geneontology/go-ontology/issues/23135

@gantonazzo @hattrill

**Comment by hattrill** [comment]
@gantonazzo @hattrill Task: to look at factors that result in the 'negative regulation of transposition' and ask if this is the same as or can include 'RNA-mediated transposon silencing'

**Comment by hattrill** [comment]
Hi @gantonazzo think that we need to make a mini-topic of this and schedule some time to finish this. I feel that the piRNA silencing terms in #23135 cover the piRNA-mediated transposon silencing but I can see how we could also debate this.

**Comment by hattrill** [comment]
Looking at this again, I think that "tRNA-mediated transposon silencing" might be a misleading term to have. tRNAs can be used in reverse transcription of retrotransposons as the primer for the RT enzyme. In some cases, it would appear that these tRNA primers-bound to retrotransposon LTRs can be targetted by Asterix/Gtsf1 to promote the recruitment of piRNA loaded piwi for sliencing of retrotransposition and the process as a 'whole' is piRNA-mediated.
Additonally, fragments of tRNAs - tRNA-derived small RNAs (tRF) can bind target the tRNA primer binding site (PBS) and block RT.
PMC5551035

![Uploading Screenshot 2023-02-27 at 12.46.42.png…]()

**Comment by pgaudet** [comment]
Term requested following discussion with @hattrill @gantonazzo 

* retrotransposon silencing (change label of GO:0010526 negative regulation of transposition, RNA-mediated, see #23746)
* * retrotransposon silencing by heterochromatin formation
* * *   piRNA-mediated retrotransposon silencing by heterochromatin formation
* * *     siRNA-mediated retrotransposon silencing by heterochromatin formation (PMID:36570931)
* * *     DNA methylation-mediated retrotransposon silencing by heterochromatin formation (RdDM) pathway (PMID:36570931)
* *  retrotransposon silencing by mRNA destabilization 
* * *     piRNA-mediated retrotransposon silencing by mRNA destabilization

**Comment by pgaudet** [comment]
New terms added in https://github.com/geneontology/go-ontology/issues/25029
