### ISSUE TITLE
NTR: prevention of polyspermy during double fertilization

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#24579]
Please provide as much information as you can: 

* **Suggested term label:**
prevention of polyspermy during double fertilization

* **Definition (free text)**
The processes by which fertilization of either or both  the egg cell  or the central cell is limited to a single sperm nucleus during double fertilization.

* **Reference, in format PMID:#######**
PMID:27951463

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0080155
or 
GO:0009567 
* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
requesting this term because the only polyspermy block term in GO is animal specific (GO:0060468) and violates taxon constraint rules.

**Comment by raymond91125** [comment]
GO:0060468 prevention of polyspermy PART_OF GO:0007338 single fertilization, that has DEF: "The union of male and female gametes to form a zygote.", which is never_in_taxon Spermatophyta. I don't understand this exclusion. If single and double fertilizations are mutually exclusive, it's not clear in the definitions. I think double fertilization includes a part that is essentially single fertilization. https://en.wikipedia.org/wiki/Double_fertilization. Furthermore, there are mechanistic similarities between plant and animal polyspermy prevention. PMID:27951463

![image](https://user-images.githubusercontent.com/619520/208763500-76c45524-2257-4715-8e41-b280d6d5b372.png)

**Comment by lreiser** [comment]
I can certainly modify the definition I provided to refer to the pollen grain that fertilizes the egg cell v the one that fertilizes the central cell. that said I have read at least one paper that suggests there is also a polyspermy block at the central cell/endosperm. I am not sure where the taxon constraint came in either.

**Comment by raymond91125** [comment]
Indeed, a plant sperm with two nuclei and an animal sperm with one do carry out distinct processes of fertilization. Thus I agree it is useful to have specific terms for plants. However, not having a shared term for polyspermy prevention seems not ideal.
Please propose a more distinguishing (from animal) definition for prevention of polyspermy during double fertilization so that we can add the term in first and discuss the proper strategy of 'branching' later. Do you think that's a good solution? @lreiser Thanks.

**Comment by lreiser** [comment]
OK see the modification- opened up to either the egg cell or the central cell
