### ISSUE TITLE
NTR: polyspecific organic cation:proton antiporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24594]
Please provide as much information as you can: 

* **Suggested term label:**
polyspecific proton:organic cation antiporter activity

* **Definition (free text)**
Enables the transfer of various organic cations in exchange for a proton, according to the reaction: H+(out) + organic cation(in) = H+(in) + organic cation(out). The transported substrates are usually toxic molecules, drugs and xenobiotics.  

* **Reference, in format PMID:#######**
PMID:17047166
PMID:17509534

* **Gene product name and ID to be annotated to this term**
Q86VL8

* **Parent term(s)**
antiporter activity + normal design pattern

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
None - this is a broad specificity transporter

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
* * broad specificity organic cation:proton antiporter activity
*  * broad specificity proton:organic cation antiporter activity
* * polyspecific organic cation:proton antiporter activity

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.
* * TCBD: 2.A.66.1.20

* **Any other information**

**Comment by pgaudet** [comment]
We cannot add a logical definition for these kinds of terms, since there is no concept of 'polyspecificity' in ChEBI, and we dont want specific transporters to be children of polyspecific transporters

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140968
+name: polyspecific proton:organic cation antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of various organic cations in exchange for a proton, according to the reaction: H+(out) + organic cation(in) = H+(in) + organic cation(out). The transported substrates are usually toxic molecules, drugs and xenobiotics." [PMID:17047166, PMID:17509534]
+is_a: GO:0015297 ! antiporter activity
+relationship: has_primary_input CHEBI:24636 ! proton
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24594 xsd:anyURI
+created_by: pg
+creation_date: 2022-12-16T16:22:41Z
+

**Comment by deustp01** [comment]
> since there is no concept of 'polyspecificity' in ChEBI,

Naive question: there is a generic cation term cation ([CHEBI:36916](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A36916)) that has all sorts of monoatomic and polyatomic cations as is_a children, so is that a workaround here?

**Comment by pgaudet** [comment]
No, because it would add the children of cation term cation ([CHEBI:36916](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A36916)) - for example terms like calcium and sodium ion would end up there, and we dont want that - a calcium ion transporter is not a type of polyspecific transporter.
