### ISSUE TITLE
NTR: [AIM2 inflammasome complex assembly]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#24609]
Hi GO,

Happy new year!

I would need a bunch of terms related to the AIM2 inflammasome assembly.. A number of proteins are involved in the formation or inhibition of the AIM2 inflammasome assembly and I'd like to make some GO-CAM model for the AIM2 inflammasome.

Thanks

Sylvain

1)
Term: AIM2 inflammasome complex assembly
Definition: The aggregation, arrangement and bonding together of a set of components to form the AIM2 inflammasome complex, occurring at the level of an individual cell.
Child of: GO:0140632 inflammasome complex assembly
PMID:33467177

2)
Term: regulation of AIM2 inflammasome complex assembly
Definition: Any process that modulates the frequency, rate or extent of AIM2 inflammasome complex assembly. 
child of GO:XXXXXXX AIM2 inflammasome complex assembly
PMID:33467177

3)
Term: negative regulation of AIM2 inflammasome complex assembly
Definition: Any process that stops, prevents or reduces the frequency, rate or extent of AIM2 inflammasome complex assembly. 
child of GO:XXXXXXX regulation of AIM2 inflammasome complex assembly
PMID:33467177

4)
Term: positive regulation of AIM2 inflammasome complex assembly
Definition: Any process that activates or increases the frequency, rate or extent of AIM2 inflammasome complex assembly. 
child of GO:XXXXXXX regulation of AIM2 inflammasome complex assembly
PMID:33467177

**Comment by pgaudet** [comment]
Last login: Sun Dec 18 09:34:14 on console
➜  ~ git:(master) ✗ git cd repos/go-ontology 
git: 'cd' is not a git command. See 'git --help'.

The most similar commands are
	ca
	cm
➜  ~ git:(master) ✗ cd repos/go-ontology/src
➜  src git:(master) ✗ ls 
biochebi          ontology          taxon_constraints
design_patterns   sparql            util
➜  src git:(master) ✗ cd ontology
➜  ontology git:(master) ✗ git pull 
remote: Enumerating objects: 79, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 79 (delta 54), reused 57 (delta 39), pack-reused 0
Unpacking objects: 100% (79/79), done.
From https://github.com/geneontology/go-ontology
   4bdd5d27..d5bd797a  master                 -> origin/master
   c2786eee..d5bd797a  update-chebi-pH-7-3    -> origin/update-chebi-pH-7-3
 + 80b08e3f...494d956a update-design-patterns -> origin/update-design-patterns  (forced update)
   472e68d1..d5bd797a  update-taxon-constraints -> origin/update-taxon-constraints
Updating 4bdd5d27..d5bd797a
Fast-forward
 docs/patterns/activator_activity.md                |    12 +-
 docs/patterns/anatomical_structure_formation.md    |     4 +-
 docs/patterns/anatomical_structure_maturation.md   |     4 +-
 .../patterns/anatomical_structure_morphogenesis.md |     4 +-
 docs/patterns/anatomical_structure_organization.md |     8 +-
 docs/patterns/inhibitor_activity.md                |    12 +-
 docs/patterns/multi_organism_process.md            |     2 +-
 docs/patterns/regulator_activity.md                |     8 +-
 docs/patterns/single_organism_process.md           |     2 +-
 src/biochebi/chebi_pH7_3_mapping.tsv               |  3262 +-
 src/design_patterns/activator_activity.tsv         |    46 +
 .../anatomical_structure_development.tsv           |    86 +-
 .../anatomical_structure_formation.tsv             |    23 +-
 .../anatomical_structure_maturation.tsv            |    20 +
 .../anatomical_structure_morphogenesis.tsv         |    37 +-
 .../anatomical_structure_organization.tsv          |    18 +
 src/design_patterns/binding.tsv                    |    13 +-
 src/design_patterns/biosynthetic_process.tsv       |    30 +-
 src/design_patterns/catabolic_process.tsv          |    20 +-
 src/design_patterns/chemical_transport.tsv         |    12 +-
 src/design_patterns/export_across_membrane.tsv     |     7 +-
 src/design_patterns/import_across_membrane.tsv     |     7 +-
 .../import_across_plasma_membrane.tsv              |     5 +-
 src/design_patterns/inhibitor_activity.tsv         |    47 +
 src/design_patterns/involved_in_x_y.tsv            |     3 -
 src/design_patterns/metabolic_process.tsv          |    38 +-
 src/design_patterns/negative_regulation.tsv        |     9 +-
 src/design_patterns/positive_regulation.tsv        |     9 +-
 src/design_patterns/regulation.tsv                 |     9 +-
 src/design_patterns/regulation_by.tsv              |     1 -
 src/design_patterns/regulator_activity.tsv         |    34 +-
 .../transmembrane_import_into_cytosol.tsv          |     5 +-
 src/ontology/go-edit.obo                           |   255 +-
 src/ontology/imports/chebi_import.obo              |  5927 +-
 src/ontology/imports/chebi_import.owl              | 77000 ++++++++++++++++---
 src/ontology/imports/go-pattern-conformance.ttl    |   937 +-
 src/ontology/imports/ncbitaxon_import.obo          |    94 +-
 src/ontology/imports/ncbitaxon_import.owl          |   245 +-
 38 files changed, 76375 insertions(+), 11880 deletions(-)
➜  ontology git:(master) ✗ git checkout -b issue-24605
Switched to a new branch 'issue-24605'
➜  ontology git:(issue-24605) ✗ git diff 
➜  ontology git:(issue-24605) ✗ git commit -m 'fixed LD fixes #24605' go-edit.obo
[issue-24605 755925d4] fixed LD fixes #24605
 1 file changed, 9 insertions(+), 6 deletions(-)
➜  ontology git:(issue-24605) ✗ git push origin issue-24605
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.40 KiB | 476.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: 
remote: Create a pull request for 'issue-24605' on GitHub by visiting:
remote:      https://github.com/geneontology/go-ontology/pull/new/issue-24605
remote: 
To https://github.com/geneontology/go-ontology.git
 * [new branch]        issue-24605 -> issue-24605
➜  ontology git:(issue-24605) ✗ git checkout master 
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git pull 
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/geneontology/go-ontology
   d5bd797a..553474c0  master     -> origin/master
Updating d5bd797a..553474c0
Fast-forward
 src/ontology/go-edit.obo | 15 +++++++++------
 1 file changed, 9 insertions(+), 6 deletions(-)
➜  ontology git:(master) ✗ git branch -d issue-24605
Deleted branch issue-24605 (was 755925d4).
➜  ontology git:(master) ✗ git checkout -b issue-24570-2
M	src/ontology/go-edit.obo
Switched to a new branch 'issue-24570-2'
➜  ontology git:(issue-24570-2) ✗ git diff 
➜  ontology git:(issue-24570-2) ✗ git commit -m 'fixed comment for #24570' go-edit.obo  
[issue-24570-2 09a57a8d] fixed comment for #24570
 1 file changed, 4 insertions(+), 4 deletions(-)
➜  ontology git:(issue-24570-2) ✗ git push origin issue-24570-2
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.35 KiB | 689.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: 
remote: Create a pull request for 'issue-24570-2' on GitHub by visiting:
remote:      https://github.com/geneontology/go-ontology/pull/new/issue-24570-2
remote: 
To https://github.com/geneontology/go-ontology.git
 * [new branch]        issue-24570-2 -> issue-24570-2
➜  ontology git:(issue-24570-2) ✗ git checkout master 
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git pull 
Already up to date.
➜  ontology git:(master) ✗ git pull  
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/geneontology/go-ontology
   553474c0..8d248d19  master     -> origin/master
Updating 553474c0..8d248d19
Fast-forward
 src/ontology/go-edit.obo | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)
➜  ontology git:(master) ✗ git branch -d issue-24570-2
Deleted branch issue-24570-2 (was 09a57a8d).
➜  ontology git:(master) ✗ git checkout -b issue-24612
Switched to a new branch 'issue-24612'
➜  ontology git:(issue-24612) ✗ git diff 
➜  ontology git:(issue-24612) ✗ git commit -b 'obsoleted term fixes #24612' go-edit.obo
error: unknown switch `b'
usage: git commit [<options>] [--] <pathspec>...

    -q, --quiet           suppress summary after successful commit
    -v, --verbose         show diff in commit message template

Commit message options
    -F, --file <file>     read message from file
    --author <author>     override author for commit
    --date <date>         override date for commit
    -m, --message <message>
                          commit message
    -c, --reedit-message <commit>
                          reuse and edit message from specified commit
    -C, --reuse-message <commit>
                          reuse message from specified commit
    --fixup <commit>      use autosquash formatted message to fixup specified commit
    --squash <commit>     use autosquash formatted message to squash specified commit
    --reset-author        the commit is authored by me now (used with -C/-c/--amend)
    -s, --signoff         add Signed-off-by:
    -t, --template <file>
                          use specified template file
    -e, --edit            force edit of commit
    --cleanup <mode>      how to strip spaces and #comments from message
    --status              include status in commit message template
    -S, --gpg-sign[=<key-id>]
                          GPG sign commit

Commit contents options
    -a, --all             commit all changed files
    -i, --include         add specified files to index for commit
    --interactive         interactively add files
    -p, --patch           interactively add changes
    -o, --only            commit only specified files
    -n, --no-verify       bypass pre-commit and commit-msg hooks
    --dry-run             show what would be committed
    --short               show status concisely
    --branch              show branch information
    --ahead-behind        compute full ahead/behind values
    --porcelain           machine-readable output
    --long                show status in long format (default)
    -z, --null            terminate entries with NUL
    --amend               amend previous commit
    --no-post-rewrite     bypass post-rewrite hook
    -u, --untracked-files[=<mode>]
                          show untracked files, optional modes: all, normal, no. (Default: all)

➜  ontology git:(issue-24612) ✗ git commit -m 'obsoleted term fixes #24612' go-edit.obo
[issue-24612 deeee44b] obsoleted term fixes #24612
 1 file changed, 5 insertions(+), 7 deletions(-)
➜  ontology git:(issue-24612) ✗ git push origin issue-24612
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.31 KiB | 448.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: 
remote: Create a pull request for 'issue-24612' on GitHub by visiting:
remote:      https://github.com/geneontology/go-ontology/pull/new/issue-24612
remote: 
To https://github.com/geneontology/go-ontology.git
 * [new branch]        issue-24612 -> issue-24612
➜  ontology git:(issue-24612) ✗ git checkout master 
M	src/ontology/imports/go-catalytic-activities-participants.owl
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git pull 
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (6/6), done.
remote: Total 8 (delta 6), reused 6 (delta 6), pack-reused 2
Unpacking objects: 100% (8/8), done.
From https://github.com/geneontology/go-ontology
 + 494d956a...0ad0f201 update-design-patterns -> origin/update-design-patterns  (forced update)
Already up to date.
➜  ontology git:(master) ✗ git checkout -b issue-10899
M	src/ontology/imports/go-catalytic-activities-participants.owl
Switched to a new branch 'issue-10899'
➜  ontology git:(issue-10899) ✗ git diff 
➜  ontology git:(issue-10899) ✗ git commit -m 'created new term fixes #10899' go-edit.obo
[issue-10899 03d225cc] created new term fixes #10899
 1 file changed, 11 insertions(+)
➜  ontology git:(issue-10899) ✗ git push origin issue-10899
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.40 KiB | 479.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: 
remote: Create a pull request for 'issue-10899' on GitHub by visiting:
remote:      https://github.com/geneontology/go-ontology/pull/new/issue-10899
remote: 
To https://github.com/geneontology/go-ontology.git
 * [new branch]        issue-10899 -> issue-10899
➜  ontology git:(issue-10899) ✗ git checkout master 
M	src/ontology/imports/go-catalytic-activities-participants.owl
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git pull 
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/geneontology/go-ontology
   8d248d19..e0ee41f2  master     -> origin/master
Updating 8d248d19..e0ee41f2
Fast-forward
 src/ontology/go-edit.obo | 11 +++++++++++
 1 file changed, 11 insertions(+)
➜  ontology git:(master) ✗ git branch -d issue-24612          
error: The branch 'issue-24612' is not fully merged.
If you are sure you want to delete it, run 'git branch -D issue-24612'.
➜  ontology git:(master) ✗ git pull 
Already up to date.
➜  ontology git:(master) ✗ git branch -d issue-10899
Deleted branch issue-10899 (was 03d225cc).
➜  ontology git:(master) ✗ git checkout issue-24612
M	src/ontology/imports/go-catalytic-activities-participants.owl
Switched to branch 'issue-24612'
➜  ontology git:(issue-24612) ✗ git checkout master 
M	src/ontology/imports/go-catalytic-activities-participants.owl
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git pull 
Already up to date.
➜  ontology git:(master) ✗ git pull 
Already up to date.
➜  ontology git:(master) ✗ git checkout -b issue-24612-2
M	src/ontology/imports/go-catalytic-activities-participants.owl
Switched to a new branch 'issue-24612-2'
➜  ontology git:(issue-24612-2) ✗ git diff 
➜  ontology git:(issue-24612-2) ✗ git commit -m 'obsoleted term fixes #24612' go-edit.obo
[issue-24612-2 040f11e5] obsoleted term fixes #24612
 1 file changed, 5 insertions(+), 7 deletions(-)
➜  ontology git:(issue-24612-2) ✗ git checkout master 
M	src/ontology/imports/go-catalytic-activities-participants.owl
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  ontology git:(master) ✗ git checkout -b issue-24609
M	src/ontology/imports/go-catalytic-activities-participants.owl
Switched to a new branch 'issue-24609'
➜  ontology git:(issue-24609) ✗ git diff 
➜  ontology git:(issue-24609) ✗ git diff 

+namespace: biological_process
+def: "The aggregation, arrangement and bonding together of a set of components to form the AIM2 inflammasome complex." [PMID:33467177]
+intersection_of: GO:0065003 ! protein-containing complex assembly
+intersection_of: results_in_assembly_of GO:0097169 ! AIM2 inflammasome complex
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24609 xsd:anyURI
+created_by: pg
+creation_date: 2023-01-04T05:10:26Z
+
+[Term]
+id: GO:0140971
+name: regulation of AIM2 inflammasome complex assembly
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of AIM2 inflammasome complex assembly." [PMID:33467177]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: regulates GO:0140970 ! AIM2 inflammasome complex assembly
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24609 xsd:anyURI
+created_by: pg
+creation_date: 2023-01-04T05:12:54Z
+
+[Term]
+id: GO:0140972
+name: negative regulation of AIM2 inflammasome complex assembly
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of AIM2 inflammasome complex assembly." [PMID:33467177]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0140970 ! AIM2 inflammasome complex assembly
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24609 xsd:anyURI
+created_by: pg
+creation_date: 2023-01-04T05:14:04Z
+
+[Term]
+id: GO:0140973
+name: positive regulation of AIM2 inflammasome complex assembly
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of AIM2 inflammasome complex assembly." [PMID:33467177]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0140970 ! AIM2 inflammasome complex assembly
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24609 xsd:anyURI
+created_by: pg
+creation_date: 2023-01-04T05:15:31Z

**Comment by sylvainpoux** [comment]
Thanks @pgaudet !
