### ISSUE TITLE
'calcium activated cation channel activity' is unsatisfiable in CL

### ISSUE THREAD

**Issue by bvarner-ebi** [geneontology/go-ontology#24605]
Whilst reviewing CL release [v2022-12-15](https://github.com/obophenotype/cell-ontology/releases/tag/v2022-12-15), [many unsatisfiable classes were discovered](https://github.com/obophenotype/cell-ontology/issues/1782). All but one can be resolved [by removing a range restriction](https://github.com/obophenotype/cell-ontology/issues/1782#issuecomment-1363869711).

The remaining unsatisfiable class is **GO:0005227 'calcium activated cation channel activity'**. I think this needs to be fixed on the GO side.

As [proposed by @gouttegd](https://github.com/obophenotype/cell-ontology/issues/1782#issuecomment-1363920897):

>This one seems to be caused by regulated by (RO:0002334), which has both a domain and a range restriction to process (BFO:0000015) (so, a process is regulated by another process), where process is an occurrent.

>calcium activated cation channel activity is defined as gated channel activity (a process, OK) that is regulated by some calcium(2+) (not a process).

Can an editor please review and resolve?

**Comment by shawntanzk** [comment]
Think instead this is a RO issue, see this comment: https://github.com/obophenotype/cell-ontology/issues/1782#issuecomment-1363995278

**Comment by shawntanzk** [comment]
Proposal by @gouttegd:

> There is another set of relations intended for causal relations between a process on one side and a material entity on another side (RO:0002595 and its subclasses), the definition of calcium activated cation channel activity should probably use one of those instead.

**Comment by gouttegd** [comment]
Of note, my comment above is misleading. According to @dosumis the proper fix would be to keep using the `regulated_by` relation (RO:0002334), but to change the object to `calcium ion binding` (GO:0005509), which is ultimately a BFO process and would therefore satisfy the range constraint of RO:0002334.

**Comment by pgaudet** [comment]
Thanks, I changed the definition as suggested. 

I also added a logical definition to GO:0015269 calcium-activated potassium channel activity
'gated channel activity'
 and ('positively regulated by' some 'calcium ion binding')
 and ('has primary input' some 'potassium(1+)')

, and removed asserted classes: 
-is_a: GO:0005227 ! calcium activated cation channel activity
-is_a: GO:0005267 ! potassium channel activity
-relationship: has_primary_input CHEBI:29103 ! potassium(1+)


and changed the logical definitions of GO:0070089 'chloride-activated potassium channel activity'
from 
'gated channel activity' and ('regulated by' some 'potassium(1+)') and ('has primary input' some chloride)

to 'gated channel activity' and ('regulated by' some 'potassium ion binding') and ('has primary input' some chloride)
