### ISSUE TITLE
Taxon constraint:  multiple

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24608]
Please provide as much information as you can: 

* **GO term ID label:**

Never in fungi?
- [x] GO:0048870	cell motility
Motile cells in fungi
A zoospore is a motile asexual spore that uses a flagellum for locomotion. Also called a swarm spore, these spores are created by some protists, bacteria, and fungi to propagate themselves.
I won't add anything for this one

~Only in metazoan + plants
 GO:0030154    	cell differentiation 
 GO:2000736	regulation of stem cell differentiation~

- [ ] GO:0010098	suspensor development (organisms which have embryos - > metazoan?)
won't fix THIS ONE SHOULD FIX WHEN DEVELOPMENT IS MOVED UNDER MULTICELLULAR PROCESS

- [x] GO:0098727    	maintenance of cell number
Any process by which the numbers of cells of a particular type or in a tissue are maintained.
(This should be qualified as a multicellular term, its implied but not implicit)
won't fix THIS ONE SHOULD FIX WHEN DEVELOPMENT IS MOVED UNDER MULTICELLULAR PROCESS

Only in Taxon	33083	Dictyostelia (need to check with @pfey03  if these are suitable constraints)
- [ ] GO:0099120  	socially cooperative development 
- [ ] GO:0099136	chimeric non-reproductive fruiting body development 
- [ ] GO:0099137	altruistic, chimeric, non-reproductive fruiting body development 

* **Request to add a taxon constraint:**
* * **only in taxon: **
* * **never in taxon: **

* **Request to remove a taxon constraint:**
Please specify

* **Supporting evidence if available (e.g PMID):**

**Comment by pfey03** [comment]
@ValWood 
Only in metazoan + plants

  GO:0030154 cell differentiation 
WE have cell differentiation in Dicty!!!

**Comment by ValWood** [comment]
Hi Petra, I  was just listing some taxon violations from an analysis, but I didn't intend to deal with "cell differentiation " here , because there are multiple other tickets  about this. Once it is defined correctly, it should be possible to add the correct taxon defs.

Can you suggest an appropriate taxon restriction for the dicty specific terms ? If not I can add "never in yeast", but it seems some of these can be specific to dicty clade?

**Comment by pfey03** [comment]
Hi Val, when I have time I check if other small eukaryote also can use at least GO:0099120. Never in yeast is for sure save to do first and I will check if beyond Dictostelids this term or another can be used.

**Comment by ValWood** [comment]
GO:0099120 socially cooperative development
is defined
The process whose specific outcome is the progression of a non-reproductive fruiting body over time, from its formation to the mature structure.

**Comment by ValWood** [comment]
Actually, some fungi have fruiting bodies.  I'll close this ticket because it is  too complicated to add a restriction.

**Comment by pfey03** [comment]
@ValWood The problem at time was and I worked with David OS, that dicty development was under reproduction and he cleaned it all up and gave me that term and some others. Many fruiting bodies are reproductive. In Dicty cells only differentiate and about 20% become stalk and die (we also have cheater mutants that never become stalk in chimeras) and the rest will become durable spores.
