### ISSUE TITLE
Obsoletion notice: GO:0070218 sulfide ion homeostasis and GO:0070219 cellular sulfide ion homeostasis 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24618]
Dear all, 

The proposal has been made to obsolete GO:0070218 sulfide ion homeostasis and GO:0070219 cellular sulfide ion homeostasis. The reason for obsoletion is that this is a a GO process: sulfide is toxic to cells and there is no process to keep a constant level, instead, cells detoxify sulfide by oxidation or other mechanisms (see PMID:25747485, PMID:20077566). 

There is a single annotation to these terms by PomBase. Consider: GO:0140974 cellular detoxification of sulfide  There are no mappings; these terms are not in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24618

Thanks, Pascale

**Comment by pgaudet** [comment]
Consider: GO:0140974 cellular detoxification of sulfide - see https://github.com/geneontology/go-ontology/issues/24619

**Comment by Antonialock** [comment]
Fungi can assimilate inorganic sulfate (sulfate assimilation pathway, SAP). If things go wrong in this pathway, cells may accumulate toxic levels of hydrogen sulfate.  So another term to consider might be GO:0000103 sulfate assimilation

see figure 1a for reference https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9757880/
@ValWood
