### ISSUE TITLE
GO:0047531, EC number and Rhea reaction linked to this term have both been deleted

### ISSUE THREAD

**Issue by kaxelsen** [geneontology/go-ontology#24612]
By re-reading PMID:13125615, it has turned out the paper did not describe the reaction  shown in RHEA:16017 and in EC 2.6.1.8, so both thee two entries have now been deleted. This will become public in release 2023_02 scheduled for April 19.

So I think GO:0047531 should also be deleted.

**Comment by deustp01** [comment]
(As far as I can tell, Reactome has no annotations corresponding to RHEA:16017.)

**Comment by pgaudet** [comment]
There are no annotations. Other mappings: 

KEGG_REACTION
    [R03248](http://www.genome.jp/dbget-bin/www_bget?rn:R03248) 
MetaCyc
    [25-DIAMINOVALERATE-AMINOTRANSFERASE-RXN](http://biocyc.org/META/NEW-IMAGE?type=NIL&object=25-DIAMINOVALERATE-AMINOTRANSFERASE-RXN)

I presume these will also be deleted. I'll send the obsoletion notice.

Thanks, Pascale

**Comment by kaxelsen** [comment]
MetaCyc [25-DIAMINOVALERATE-AMINOTRANSFERASE-RXN] has already been deleted, it is just not public yet.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0047531 2,5-diaminovalerate transaminase activity. The reason for obsoletion is that this reaction is not the one described in the paper cited in the EC and RHEA entries. The EC and RHEA have been obsoleted as well. 

There are no annotations to this term. This term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24612


Thanks, Pascale
