### ISSUE TITLE
Obsoletion request: GO:0030685 : nucleolar preribosome

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24626]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0030685   nucleolar preribosome

* **Reason for deprecation** Put an x in the appropriate box: 

 - [ ]  The reason for obsoletion is that this term was added in error.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

preribosome

* **Are there annotations to this term?**

- How many EXP:
2 SGD
1 PomBse

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

~I think the preribosome is always nucleolar , so maybe "preribosome". can have the parent "nucleolus" (Need to check this)~ 

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
pre ribosomes  transit from the nucleolus to the nucleoplasm to the cytoplasm where they mature, so 
1) pre-ribosome can't have a nucleolar parent.

But, we
2) would not normally create location-specific terms for the same complex in different locations, so should obsolete "nucleolar pre ribosome" with 

consider:
GO:0030684  preribosome
or more likely
GO:0030686   90S preribosome (the earliest form of the pre ribosome)

and concurrent annotation to "nucleolus"

3)
@pgaudet it seems we can't use "occurs_in" to qualify the location of a complex, is that correct?

4) add pre-ribosome synonyms

**Comment by ValWood** [comment]
I can leave "nucleolar preribosome"
because preribosomes can also occur in the nucleoeoplasm

**Comment by ValWood** [comment]
Or should

**Comment by ValWood** [comment]
Or  probably i should merge. These aren't different complexes?
@pgaudet  please advise

**Comment by pgaudet** [comment]
You can do protein complex is_active in some cellular anatomical entity. 

So, if the nucleolar preribosome and the nuclear preribosome are the same complex, you can obsolete, and the localization can be captured with an extension.
