### ISSUE TITLE
term definition or name update GO:0140849    ATP-dependent H2AZ histone chaperone activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24638]
GO:0140849  ATP-dependent H2AZ histone chaperone activity

Is defined
A histone chaperone that mediates the exchange of histone H2A-H2B dimer and histone H2AZ-H2B dimers in a nucleosome,

COuld it be called 

ATP-dependent H2A/H2AZ histone chaperone activity

to make it clear from the name that it applies to both?

**Comment by ValWood** [comment]
@pgaudet  what do you think? It seems odd to reference only H2AZ in the term name?

**Comment by pgaudet** [comment]
I want to get @colinlog 's feedback. It's on my list of questions for him for Friday - but if he can answer before, great !

**Comment by colinlog** [comment]
Hi Val, if anything it would be a H2AZ-H2B chaperone activity. These complexes exchanges H2A.Z-H2B dimers (inot and out of the nucleosome). To my knowledge they do not chaperone H2A-H2B. Presumably those have FACT as their chaperone.

 The insertion of H2A.Z-H2B is coupled to H2A(.Z) and H4 acetylation by the ESA1/NuA4 HAT complexes. It is involved in transcription regulationbut also other accessible sites in chromosomes are decorated with H2A.Z
