### ISSUE TITLE
Obsolete GO:0052746 inositol phosphorylation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24634]
Single step process - 6 EXP.

**Comment by raymond91125** [comment]
Dear all,

The proposal has been made to obsolete GO:0052746 inositol phosphorylation,
see https://github.com/geneontology/go-ontology/issues/24634.

The reason for obsoletion is this is a single-step process. There maybe existing MF annotations.

Experimental annotations that need to be reviewed are here:
https://docs.google.com/spreadsheets/d/1qOLSbLu-_gOnM7aAi0ZRTRTY1-pkKnFY-ZAi_YeO28A

Impacted groups:
GeneDB 3
UniProt 1
TAIR 1
BHF-UCL 1

Mappings that need to be reviewed: None

We would like to effect the obsoletion by Jan 13, 2023.


Thanks.

**Comment by tberardini** [comment]
TAIR done

**Comment by pgaudet** [comment]
UniProt removed

**Comment by pgaudet** [comment]
@uliboehme can you please fix the GeneDB annotations?

**Comment by RLovering** [comment]
ucl done

**Comment by uliboehme** [comment]
GeneDB done
