### ISSUE TITLE
Obsolete: GO:2001020 regulation of response to DNA damage stimulus & positive + negactive children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24632]
- GO:2001020 regulation of response to DNA damage stimulus
- GO:2001021 negative regulation of response to DNA damage stimulus
-  GO:2001022 positive regulation of response to DNA damage stimulus 
should be obsoleted. This was brought up in 
https://github.com/geneontology/go-annotation/issues/3502

Genes annotated to these terms all seem to be pat of the response. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Can probably use 'replace by' GO:0006974 cellular response to DNA damage stimulus

**Comment by raymond91125** [comment]
Dear all,

The proposal has been made to obsolete:

    GO:2001020 regulation of response to DNA damage stimulus
    GO:2001021 negative regulation of response to DNA damage stimulus
    GO:2001022 positive regulation of response to DNA damage stimulus

The reason for obsoletion is that the meaning of the term is ambiguous; genes annotated to these terms all seem to be part of the response.

There are 43 experimental annotations to these terms

CACAO 1
ComplexPortal 4
FB 1
MGI 3 @krchristie
ParkinsonsUK-UCL 2
SGD 5
TAIR 5
UNIPROT 21
ZFIN 1

These terms are to be replaced by GO:0006974 cellular response to DNA damage stimulus.

Any comments can be  added to the issue: https://github.com/geneontology/go-ontology/issues/24632.

We are opening a comment period for this proposed obsoletion. We’d like to proceed and obsolete this term on 01/13/2023. Unless objections are received by January 12th, we will assume that you agree to this change.
