### ISSUE TITLE
Obsolete GO:1990898 meiotic DNA double-strand break clipping and GO:1990899 meiotic DNA double-strand break resectioning ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24639]
Hi @ValWood 

Should we obsolete 
GO:1990898 meiotic DNA double-strand break clipping and GO:1990899 meiotic DNA double-strand break resectioning ? 

I think these are MFs (nucleases) that could be annotated with 'happens during'? 

All EXP annotations are pombase. 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes go ahead,  I will fix now.

**Comment by pgaudet** [comment]
Dear all, 


The proposal has been made to obsolete GO:1990898 meiotic DNA double-strand break clipping and GO:1990899 meiotic DNA double-strand break resectioning. The reason for obsoletion is that these terms represent molecular functions. Annotations have been removed; there are no mapping, these terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24639

Thanks, Pascale
