### ISSUE TITLE
Obsoletion notice: GO:0055068 cobalt ion homeostasis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24658]
Dear all, 

The proposal has been made to obsolete GO:0055068 cobalt ion homeostasis. The reason for obsoletion is that this term does not distinguish between an intracellular and an organism-level process.

There is a single TAIR annotation to this term, see https://github.com/geneontology/go-annotation/issues/4398

There are no mappings; this term is not present in any subsets. You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24658

Thanks, Pascale

**Comment by lreiser** [comment]
done changed to GO:0010299

**Comment by rays22** [comment]
> The proposal has been made to obsolete GO:0055068 cobalt ion homeostasis. The reason for obsoletion is that this term does not distinguish between an intracellular and an organism-level process.

Could you kindly provide some explanation of why you regard organism and intracellular level cobalt ion homeostasis disjoint? What is the biological evidence for that?
I can see that there is a series of GO term obsoletions based on a perceived need for a strict separation of organism level and intracellular ion homeostasis processes, like for example https://github.com/geneontology/go-ontology/issues/24464.
However, I am not convinced why a broader category of ion homeostasis could not include a a more specific subcategory of intracellular homeostasis. Is there any documented organism level ion homeostasis process that does not involve some intracellular biological processes?
These ion homeostasis terms have been used for phenotype annotations. The phenotypes are often observed at the organism level, but they do involve intracellular homeostasis processes as well. These obsoletions put a burden on downstream users of these GO process terms, and it is not obvious to me what value the obsoletions provide for GO or GO users.
There is already a [GO:0006877 cellular cobalt ion homeostasis](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0006877) that can be used for intracellular level processes. Why not keep the broader [GO:0055068 cobalt ion homeostasis](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0055068&lang=en&viewMode=All&siblings=false) as well?

**Comment by thomaspd** [comment]
The disambiguation of these two uses of the word homeostasis is intended to make it clear to users that this same word is used to describe the homestasis of two different things: intracellular levels of a molecule (cellular), versus circulating levels of a molecule (organism). For each annotation, we need to be clear which one we are referring to.

Addressing your specific example of describing a phenotype, it isn't clear to me how having a less specific homeostasis term, which means "EITHER intracellular homeostasis OR circulating level homeostasis", would help with a phenotype annotation. Either the phenotype was measuring the change in intracellular level, or the circulating level.

Beyond that, we want to note that GO was designed to describe gene functions (including higher level biological programs, in the biological process branch), and not phenotypes. We are aware that in some cases the vocabulary could still be useful for phenotype annotation. We are happy to set up a discussion, where we could learn more about how you are using, or would like to use, GO.

**Comment by rays22** [comment]
I am afraid I do not find your explanation for the need of a strict separation of intracellular level versus circulating level homeostasis satisfactory.
Is there ever an organism level ion homeostasis that does not involve some sort of intracellular ion homeostasis?
If there is evidence for that, then please quote it in the obsoletion notice.
It is quite common to [infer gene function from mutant phenotypes](https://wiki.geneontology.org/Inferred_from_Mutant_Phenotype_(IMP)). As gene products can be involved in biological processes that involve both intracellular and organismal level, thus some valuable phenotypic information regarding gene functions will be lost as a result of the series of homeostasis term obsoletions. A less specific homeostasis term that includes both intra- and supracellular biological processes would allow to link phenotypic evidence to GO biological processes.
