### ISSUE TITLE
Obsoleton proposal: polysomal ribosome 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24651]
I have the following 2 errors in my GO error log:

    WARNING - Violates GO Rule: GORULE:0000061: Found violation of: Only certain gene product to term relations are allowed for a given GO term but was repaired: BFO:0000050 should be one of RO:0001025, RO:0002325, RO:0002432 -- PomBase SPAC4F10.14c btf3 part_of GO:0042788 PMID:17211518 IPI PomBase:SPAC4F10.14c C nascent polypeptide-associated complex beta subunit btt1|egd1|nac2 protein taxon:4896 20201126 PomBase

    WARNING - Violates GO Rule: GORULE:0000061: Found violation of: Only certain gene product to term relations are allowed for a given GO term but was repaired: BFO:0000050 should be one of RO:0001025, RO:0002325, RO:0002432 -- PomBase SPBC25H2.05 egd2 part_of GO:0042788 PMID:17211518 IPI PomBase:SPAC4F10.14c C nascent polypeptide-associated complex alpha subunit Egd2 nac1 protein taxon:4896 20201126 PomBase

1. I don't know how to fix a GP to term relationship
2. Is the term "polysomal ribosome" out of scope for GO? This is more of a statement about the arrangement of ribosomes for hightly expressed genes "a group of ribosomes bound to an mRNA". Presumably all ribosomal subunits would need to be annotated to it for completion, because ribosomes are sometimes polysomal.  At present the annotation is inconsistent, therefore not really useful:

144 annotations , 97 assigned by CAFA
should we obsolete?

**Comment by ValWood** [comment]
Also polysome GO:0005844

**Comment by ValWood** [comment]
Seems to be used sometimes for polysomal fractions, which doesn't seem to be the way to make a GO annotation!

@hdrabkin  what do you think about the terms polysome and polysomal ribosome? The seem to be out of scope.

**Comment by hdrabkin** [comment]
@ValWood , these are fine I think, but just remember my old bugaboo about free ribosomes not being a good term. There are subunits, and they assemble into a functional ribosome on the mRNA during initiation and then stay as a mRNA-bound ribosome during elongation, etc.  No free ribsomes; many old experiments were considered to be artifactual (what Mg levels were in the buffer, etc.; I can dig out the literature. ). 
This is my recollection from years ago when I was at the bench. 
I see now that there are a couple of terms floating around
Free vs bound ribosomes; this is imprecise.
There are membrane bound polysomes which put the new protein into the ER during synthesis and then 'free', meaning in the cytosol not associated with a membrane, that are making cytosolic proteins.

**Comment by pgaudet** [comment]
@RLovering looks like the 'functional complex is the polysome, but maybe the distinction is not useful? These terms could perhaps be merged.

**Comment by ValWood** [comment]
144 annotations , 97 assigned by CAFA
should we obsolete?

polysome  is multiple ribosomes on an mRNA
<img width="337" alt="Screenshot 2023-09-13 at 18 55 23" src="https://github.com/geneontology/go-ontology/assets/7359272/ee32ac7c-9672-402b-b803-557c3b6295e6">

so this is multiple translation events (lie a plural?)

this seems really out of scope for GO?

**Comment by ValWood** [comment]
It seems just weird. Wouldn't this be the case for all  highly translated genes? It seems to be a different level of component to what we are trying to capture (i.e. this organization is mRNA specific, so it would need to be part_of a messenger RNA, the complexity os including these terms as components is mind-boggling!)

**Comment by raymond91125** [comment]
To be clear, Is the decision to? 

- [ ] merge GO:0042788 polysomal ribosome into GO:0005840 ribosome
- [ ] merge GO:0005844 polysome into GO:0005840 ribosome

**Comment by ValWood** [comment]
Hi @raymond91125  it should probably be an obsoletion in case it has also been sued for elongation factors
(I would make it a 'related' synonym, as it's slightly out of scope for GO.)
@pgaudet  do you agree?

**Comment by pgaudet** [comment]
Yes, I agree. 

Anyway we dont merge anymore. 

If annotations are incorrect, you need to do an obsolete + consider, rather than replace_by. 

Thanks, Pascale
