### ISSUE TITLE
not for direct annotation term, GO:0052689 carboxylic ester hydrolase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24654]
GO:0052689 carboxylic ester hydrolase activity is blocked for direct annotation. This seems odd, because the less specific parent 
GO:0016788 (https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0016788/complete)
hydrolase activity, acting on ester bonds
 is not blocked

WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms -- PomBase SPCC417.12 SPCC417.12 enables GO:0052689 GO_REF:0000050 ISM Pfam:PF00135 F carboxylesterase, type B family protein protein taxon:4896 20080814 PomBase

**Comment by ValWood** [comment]
Alos IBA

WARNING - Violates GO Rule: GORULE:0000008: No annotations should be made to uninformatively high level terms -- PomBase SPAC8E11.04c SPAC8E11.04c enables GO:0052689 PMID:21873635 IBA fb:FBgn0042138,PANTHER:PTN000069162,RGD:3025,TAIR:locus:6530298215,UniProtKB:O75608,UniProtKB:O95372 F palmitoyl-(protein) hydrolase protein taxon:4896 20170228 GO_Central

**Comment by sjm41** [comment]
Discussed in:
https://github.com/geneontology/go-ontology/issues/21843
https://github.com/geneontology/go-ontology/pull/24238
https://github.com/geneontology/go-annotation/issues/4340

But I agree it seems odd to have 'do not annotate' on one term and not on its parent.

**Comment by pgaudet** [comment]
We'll remove the do_not_annotate flag - the children are quite specific, it can be useful to annotate to this term.
