### ISSUE TITLE
Obsoletion request: [GO ID:GO:0036473  cell death in response to oxidative stress] and non-programmed children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24652]
Please provide as much information as you can:

* **GO term ID and Label**
- [x] GO:0036473  cell death in response to oxidative stress
- [x] GO:1903201    regulation of oxidative stress-induced cell death
- [x] GO:0036475    neuron death in response to oxidative stress
- [x] GO:0036474    cell death in response to hydrogen peroxide
- [x] GO:1903209    positive regulation of oxidative stress-induced cell death
- [x] GO:1903202    negative regulation of oxidative stress-induced cell death
- [x] GO:1905206    positive regulation of hydrogen peroxide-induced cell death
- [x] GO:1903205    regulation of hydrogen peroxide-induced cell death
- [x] GO:0036476    neuron death in response to hydrogen peroxide
- [x] GO:1903206    negative regulation of hydrogen peroxide-induced cell death
- [x] GO:1903204    negative regulation of oxidative stress-induced neuron death
- [x] GO:1903208    negative regulation of hydrogen peroxide-induced neuron death
- [x] GO:1903203    regulation of oxidative stress-induced neuron death
- [x] GO:1903207    regulation of hydrogen peroxide-induced neuron death

<img width="452" alt="Screenshot 2023-01-09 at 14 20 55" src="https://user-images.githubusercontent.com/7359272/211330184-744a89af-be71-4a4d-95e6-c40058332ceb.png">

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x]  The reason for obsoletion is that this term represent an assay and not a GO process.
 - [x]  The reason for obsoletion is that this represents a phenotype.

Either move to "programmed cell death in response to oxidative stress", or delete?

To be included in GO annotation the  cell death must be programmed (otherwise it's just a  pathological process/readout). Many of the annotations represent mutations which are cytotoxic.

* **"Consider" term(s) (ID and label)**

Either move to "programmed cell death in response to oxidative stress", or,  remove if there is no evidence that the gene is part of an evolved cell death pathway. 

* **Are there annotations to this term?**
- How many EXP:  110

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
https://docs.google.com/spreadsheets/d/1IW38iS7D2am17r5SHmyT7ti0hq1ipTAlYTJdGb95ye4/edit#gid=0

- [x] create annotation review ticket: 
https://github.com/geneontology/go-annotation/issues/4417

- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
@pgaudet  do you agree that this represents only a phenotype and all annotations should be to "programmed cell death" or deeper? If so I will delete the relation to leave it in a stub, and then proceed to obsolete?

**Comment by ValWood** [comment]
Discussion with @pgaudet 
Will also obsolete the descendant
[GO:0036475](https://www.ebi.ac.uk/QuickGO/term/GO:0036475)    neuron death in response to oxidative stress
These appear to be apoptotic (or are not programmed)

The aim is to make sure that all "cell death" related terms in GO are programmed in some way (apoptotic, programmed necrotic etc). These terms should not be  available  for cells dying due to some toxic lesion, or insult.

**Comment by pfey03** [comment]
Dicty had 3 annotations and those have been updated or deleted.

**Comment by ValWood** [comment]
23-02-2022  annotation reviews still in progress

**Comment by ValWood** [comment]
Remaining
12 ARUK-UCL
9 BHF-UCL
27 Parkinsons-UCL
