### ISSUE TITLE
NTR: medium-chain fatty acid omega-hydroxylase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24661]
Please provide as much information as you can: 

* **Suggested term label:**
medium-chain fatty acid omega-hydroxylase activity

* **Definition (free text)**
Catalysis of the reaction: an omega-methyl-medium-chain fatty acid + O2 + reduced [NADPH--hemoprotein reductase] = an omega-hydroxy-medium-chain fatty acid + H+ + H2O + oxidized [NADPH--hemoprotein reductase].

(Based def on existing sibling terms for GO:0102033 long-chain fatty acid omega-hydroxylase activity & GO:0140692 very long-chain fatty acid omega-hydroxylase activity)

* **Reference, in format PMID:#######**
PMID:35934685

* **Gene product name and ID to be annotated to this term**
D. melanogaster Cyp6a8 (FBgn0013772, Q27593)

* **Parent term(s)**
fatty acid omega-hydroxylase activity (GO:0120250)
(also see #24664 for related issue with this term)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
 GO:0102116 laurate hydroxylase activity
 GO:0102114 caprate dehydroxylase activity
(laurate = C12, caprate = C10, so are classed as medium-chain)

Alternatively, could choose to obsolete these specific terms and effectively merge them into this NTR - see related ticket #24662.

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
EC:1.14.14.M34 (https://biocyc.org/META/NEW-IMAGE?type=EC-NUMBER&object=EC-1.14.14.M34)
MetaCyc:RXN-19719 (https://biocyc.org/META/NEW-IMAGE?type=REACTION&object=RXN-19719)

* **Any other information**

**Comment by pgaudet** [comment]
Hi @sjm41 

I dont think this enzyme is in EC, is it? I think I came across this missing term before, and was not sure what to do.

**Comment by sjm41** [comment]
Hi @pgaudet  It's a EC term specifically created by MetaCyc that should make it into the main EC set when they have time to make a specific request (I believe).  We've come across these 'temporary' ECs before, and @hdrabkin has said it's OK to include them as xrefs in the GO.  I think there are several examples in the current GO.  @kaxelsen may know more.

**Comment by pgaudet** [comment]
Thanks @sjm41 
I thought the temporary ECs were .nxx, for example 
https://enzyme.expasy.org/EC/1.14.14.n1 (this has already been transferred)

RIght now I would no add this one, because GO cannot make a xref to MetaCyc for an EC number. 

@kaxelsen Is EC going to make a temporary EC for this one? 

Thanks, Pascale

**Comment by sjm41** [comment]
But we can still make the term, omitting the EC xref, right?

**Comment by sjm41** [comment]
I believe the format/syntax of the last (temporary) character depends on which group requests/uses it - so it's different for MetaCyc vs UniProt.  Ron Caspi at MetaCyc told me this in an exchange last year:

_Several entities have come up with their own temporary EC numbers for enzymes that have not been classified yet by the EC. Uniprot uses N numbers, BRENDA uses B numbers, and MetaCyc uses M numbers. There is no coordination between the three of us, so in theory there could be multiple such numbers describing the same reaction._

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140981
+name: medium-chain fatty acid omega-hydroxylase activity
+namespace: biological_process
+def: "Catalysis of the reaction: an omega-methyl-medium-chain fatty acid + O2 + reduced [NADPH--hemoprotein reductase] = an omega-hydroxy-medium-chain fatty acid + H+ + H2O + oxidized [NADPH--hemoprotein reductase]." [PMID:35934685]
+xref: MetaCyc:RXN-19719
+is_a: GO:0120250 ! fatty acid omega-hydroxylase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24661 xsd:anyURI
+created_by: pg
+creation_date: 2023-01-10T14:42:33Z

**Comment by kaxelsen** [comment]
We do not create more preliminary EC numbers, as I now can submit real EC numbers. In other cases we just create Rhea reactions, and that is what we have chosen to do in this case. We have created:
RHEA:75279 an ω-methyl-medium-chain fatty acid + O2 + reduced [NADPH—hemoprotein reductase] = an ω-hydroxy-medium-chain fatty acid + H+ + H2O + oxidized [NADPH—hemoprotein reductase] 

The reaction will become public in release 2023_02 scheduled for 19.04.2023

**Comment by kaxelsen** [comment]
I should add that we have created RHEA:75279 (omega-hydroxylation) based on pmid:1723761 that is about a plant protein. pmid:35934685 is mainly about an (omega-1)-hydroxylase.
Generic (omega-1)-hydroxylation is covered by RHEA:44548 an (ω-1)-ethyl fatty acid + O2 + reduced [NADPH--hemoprotein reductase] = an (ω-1)-hydroxy fatty acid + H+ + H2O + oxidized [NADPH--hemoprotein reductase] and the specific reaction with dodecanoate described in the paper by RHEA:39751 dodecanoate + O2 + reduced [NADPH—hemoprotein reductase] = 11-hydroxydodecanoate + H+ + H2O + oxidized [NADPH—hemoprotein reductase]

**Comment by sjm41** [comment]
Just looking again at this ticket.

Seems we have the 'fatty acid omega-hydroxylase activity' branch in good shape:
```
fatty acid omega-hydroxylase activity GO:0120250 (RHEA:39023)
    |__medium-chain fatty acid omega-hydroxylase activity GO:0140981  (RHEA:75279)
    |__long-chain fatty acid omega-hydroxylase activity GO:0102033 (RHEA:56748, EC:1.14.14.80)
    |__very long-chain fatty acid omega-hydroxylase activity GO:0140692 (RHEA:67952)
```

But from Kristian's last comment, it seems I still need a new term to annotate D. melanogaster Cyp6a8 from PMID:35934685, since that describes omega-1 hydroxylation.
term label: medium-chain fatty acid omega-1 hydroxylase activity
Def: "Catalysis of the reaction: an (omega-1)-ethyl medium-chain fatty acid + O2 + reduced [NADPH-hemoprotein reductase] = an (omega-1)-hydroxy-medium-chain fatty acid + H+ + H2O + oxidized [NADPH-hemoprotein reductase.". [PMID:35934685]

There's not an existing RHEA that matches that, though there is RHEA:44548 that Kristian mentions that could be used as a parent term:
term label: fatty acid omega-1 hydroxylase activity
Def: "Catalysis of the reaction: an (omega-1)-ethyl fatty acid + O2 + reduced [NADPH--hemoprotein reductase] = an (omega-1)-hydroxy fatty acid + H(+) + H2O + oxidized [NADPH--hemoprotein reductase] [RHEA:44548]

We also have an existing term for long-chain fatty acid omega-1 hydroxylase activity (RHEA:60936) that would become a second child of the new term 'fatty acid omega-1 hydroxylase activity':
```
id: GO:0120319
name: long-chain fatty acid omega-1 hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: an (omega-1)-ethyl long-chain fatty acid + O2 + reduced [NADPH-hemoprotein reductase] = an (omega-1)-hydroxy-long-chain fatty acid + H+ + H2O + oxidized [NADPH-hemoprotein reductase." [GOC:nhn, PMID:18577768, PMID:22772592, PMID:24242247, RHEA:60936]
synonym: "cytochrome P450 fatty acid omega-1 hydroxylase activity" RELATED []
xref: RHEA:60936
is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/21648" xsd:anyURI
created_by: krc
creation_date: 2021-06-21T18:31:38Z
```


So, to summarise the outstanding tasks:
- [ ] NTR for 'medium-chain fatty acid omega-1 hydroxylase activity'
- [ ] NTR for parent term 'fatty acid omega-1 hydroxylase activity' [RHEA:44548]
- [ ] make existing GO:0120319 a child of NTR 'fatty acid omega-1 hydroxylase activity'
- [ ] Also, should changed the def xref on GO:0140981 from PMID:35934685 to RHEA:75279.



@kaxelsen I noticed that the def for RHEA:60936 is:
an (omega-1)-ethyl fatty acid + O2 + reduced [NADPH--hemoprotein reductase] = an (omega-1)-hydroxy-long-chain fatty acid + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]

Should that be changed to:
an (omega-1)-ethyl **long-chain** fatty acid + O2 + reduced [NADPH--hemoprotein reductase] = an (omega-1)-hydroxy-long-chain fatty acid + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]
?

**Comment by sjm41** [comment]
+[Term]
+id: GO:0120502
+name: fatty acid omega-1 hydroxylase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: an (omega-1)-ethyl fatty acid + O2 + reduced [NADPH--hemoprotein reductase] = an (omega-1)-hydroxy fatty acid + H+ + H2O + oxidized [NADPH--hemoprotein reductase]." [RHEA:44548]
+xref: RHEA:44548
+is_a: GO:0016712 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24661" xsd:anyURI
+created_by: sjm

+[Term]
+id: GO:0120502
+name: fatty acid omega-1 hydroxylase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: an (omega-1)-ethyl fatty acid + O2 + reduced [NADPH--hemoprotein reductase] = an (omega-1)-hydroxy fatty acid + H+ + H2O + oxidized [NADPH--hemoprotein reductase]." [RHEA:44548]
+xref: RHEA:44548
+is_a: GO:0016712 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24661" xsd:anyURI
+created_by: sjm
+creation_date: 2024-04-26T10:00:25Z
