### ISSUE TITLE
Issues with 'laurate hydroxylase activity' & 'caprate dehydroxylase activity' terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24662]
id: GO:0102116
name: laurate hydroxylase activity **[9 annotations, 1 experimental]**
def: "Catalysis of the reaction: dodecanoate + NADPH + O2 + H+ <=> 11-hydroxylaurate + NADP + H2O." [EC:1.14.13.-, GOC:pz]
xref: MetaCyc:RXN-11340 **[this points to EC:1.14.14.-]**
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen **[EC xref on this is EC:1.14.13.-]**

id: GO:0102114
name: caprate dehydroxylase activity **[no annotations]**
def: "Catalysis of the reaction: decanoate + NADPH + O2 + H+ <=> 10-hydroxycaprate + NADP + H2O." [EC:1.14.13.-, GOC:pz]
xref: MetaCyc:RXN-11325 **[this points to EC:1.14.14.M34]**
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen **[EC xref on this is EC:1.14.13.-]**

There are a few issues with these two terms:
1. Mismatch in using common vs systematic name in term name vs def
2. "caprate dehydroxylase activity" should probably be "caprate hydroxylase activity" to match sibling terms
3. Current GO parentage to GO:0016709 (EC:1.14.13.-) doesn't match parentage implied by MetaCyc xrefs, which would be GO:0016712 (EC:1.14.14.-)
4. They are examples of a 'medium-chain fatty acid omega-hydroxylase activity', so should be moved to be children of the NTR for that activity (see #24661)

Alternative to making the above fixes would be to obsolete the terms (merge into the NTR), especially since there's only a single experimental annotation involved.

**Comment by pgaudet** [comment]
I agree these should be obsoleted, they correspond to specific substrates for enzymes that have broad substrate specificity (at least the one annotated entry, https://www.uniprot.org/uniprotkb/Q5TCH4/entry). 

Thanks, Pascale
