### ISSUE TITLE
Obsolete: docosanoate omega-hydroxylase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24663]
* **GO term ID and label for which you request a new superclass**
docosanoate omega-hydroxylase activity (GO:0102207)

* **New superclass (parent) suggested**
This is currently a child of 'fatty acid omega-hydroxylase activity (GO:0120250)', but with C22, it should be child of the more specific 'very long-chain fatty acid omega-hydroxylase activity (GO:0140692)'.

https://en.wikipedia.org/wiki/Behenic_acid
https://en.wikipedia.org/wiki/Fatty_acid#Length_of_fatty_acids

![Screenshot 2023-01-10 at 12 45 10](https://user-images.githubusercontent.com/16306861/211560095-c5b67d6b-2827-445d-8115-a28d62b7cce7.png)

**Comment by sjm41** [comment]
@pgaudet Based on decision in #24662, should this term also be obsoleted rather than moved?  QuickGO says it has 15 annotations (2 experimental).

**Comment by pgaudet** [comment]
Obsoleted with https://github.com/geneontology/go-ontology/issues/24662

**Comment by pgaudet** [comment]
Weird, we dont have these EXP in AmiGO. Anyway, the annotations will be replaced.
