### ISSUE TITLE
Obsolete reference preventing ontology builds

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#24669]
Ontology builds getting jammed up, preventing all pipelines from running, on:
```
10:58:21  FAIL Rule ../sparql/obsolete-reference-violation.sparql: 1 violation(s)
10:58:21  obsolete
10:58:21  http://purl.obolibrary.org/obo/GO_0102207
```
Noticing some recent activity with that term:
https://github.com/geneontology/go-ontology/issues?q=is%3Aissue+0102207
Was this caused by recent ontology changes? Are checks not able to catch this?
Tagging @pgaudet @balhoff

**Comment by balhoff** [comment]
This is due to axioms in an external file. Changes that affect terms referenced in this file aren't checked well right now, since the file is pretty new and I haven't fully worked out the correct workflow. Relevant issues:
- #24289
- #24489
