### ISSUE TITLE
Obsoletion request: [non programmed cell death terms]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24680]
Please provide as much information as you can:

After discussion with @pgaudet  @sylvainpoux 

<img width="471" alt="Screenshot 2023-01-11 at 12 58 35" src="https://user-images.githubusercontent.com/7359272/211814635-c36b6d1f-73c1-4c08-8d1e-afb43ed02262.png">

So here will
obsolete 
GO:0008219 cell death
- [x] GO:0070265 necrotic cell death
- [x] GO:0070267 oncosis
So everything remaining will be under programmed cell death

https://github.com/geneontology/go-ontology/issues/24652

* **GO term ID and Label**

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x]  The reason for obsoletion is that this term represent an assay and not a GO process.
 - [x]  The reason for obsoletion is that this represents a phenotype.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

cell death 97
+ | − | (30) | TAIR
+ | − | (27) | UniProt
+ | − | (10) | FlyBase
+ | − | (9) | RGD
+ | − | (5) | EcoCyc
+ | − | (5) | MGI
+ | − | (4) | Xenbase
+ | − | (2) | CACAO
+ | − | (3) | dictyBase
+ | − | (1) | AgBase
+ | − | (1) | GeneDB
+ | − | (1) | PseudoCAP

consider  programmed cell death or descendant

necrotic cell death (12)
+ | − | (5) | UniProt
+ | − | (5) | WB
+ | − | (1) | RGD
+ | − | (1) | dictyBase

consider      programmed necrotic cell death or descendant

GO:0070267 oncosis
+ | − | (2) | UniProt

consider  programmed cell death or descendant

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

InterPro:IPR042377 -> programmed cell death?

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage

'cell death' is a category in MGI slim/ribbon and Alliance slim/ribbon <== could switch to 'programmed cell death' (shorten to 'cell death'?)
subset: goslim_agr
subset: goslim_chembl
subset: goslim_drosophila
subset: goslim_mouse
subset: goslim_plant

- [x] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
https://docs.google.com/spreadsheets/d/1sPkWZ3rNAFpUQRD0d9n2mzi4j7pd8ztBFb33OblWYWw/edit#gid=0

- [x] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/4412

- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
I forgot to include

		GO:0010941    regulation of cell death 
		GO:0060548    negative regulation of cell death 
		GO:0010942    positive regulation of cell death 
in this ticket, but these have no direct annotations, only inherited. I will update at the same time, and  update the announcement.

**Comment by pgaudet** [comment]
Actually there are hundereds of  EXP annotations : 
* 158 positive regulation of cell death 
* 151 negative regulation of cell death
* 26 regulation of cell death

**Comment by ValWood** [comment]
damn, I forget that AmiGO no longer displays regulation annotations by default.

**Comment by paolaroncaglia** [comment]
@ValWood @pgaudet 
Hi, I hope this finds you well :-)
I don't object to the obsoletion of non-programmed cell death terms. But in case it's helpful, here's the [relevant section of the Apoptosis Curation Manual](https://wiki.geneontology.org/Apoptosis_Curation_Manual#GO:0008219_cell_death).
Very happy for annotations to be revised! Thanks for your work and I look forward to seeing you in Padua, I hope.

**Comment by ValWood** [comment]
OK, we should update the manual to remove the references to annotating cell death when you do not know that it is programmed. It has encouraged the annotation of essential genes and cytotoxic mutations to cell death  (phenotypes and readouts), which are outside the scope of GO. It has also resulted in many annotation not being made to specific cell death pathways when they could be.

**Comment by ValWood** [comment]
Look forward to seeing you also!

**Comment by pfey03** [comment]
GO 2 updated and one deleted. I agree that programmed necrotic cell death for dicty is different than the examples given in GO term and it's difficult to decide. But when they add cAMP and then DIF-1 to atg1- cells they go into necrotic cell death and I think it qualifies as programmed.

**Comment by hattrill** [comment]
Hi Val, as obsoletion of cell death looks like it will cause some issues for phenotype (FlyBase/drosophila-phenotype-ontology#162), we would need a bit of time to sort this out. Could you keep the cell death parent until we've worked out a solution? (Perhaps mark as do not annotate for now?)

**Comment by pfey03** [comment]
For us phenotypes areas the bigger headache

**Comment by ValWood** [comment]
Note that you can use PATO to define cell lethality. You don't need to use this GO term in your  phenotype ontology logical definitions to define cell death.

In FYPO we use
'has part' some
('lethal (sensu genetics)'
and ('characteristic of' some 'fungal cell'))

for any old cell death (and various descendants)

I'm happy to postpone the obsoletion and add "do not annotate"  if it helps. I  will do that soon, and reorganize the ontology so this is a temporary "do not annotate" stub.

checking with @pgaudet  that this is OK..

**Comment by pfey03** [comment]
On the next UPHENO call I will bring examples and we will discuss patterns

**Comment by pfey03** [comment]
If anyone from Flybase would be on the call would help. The next call is on Thursday February 9 11am central time

**Comment by ValWood** [comment]
Hi Petra where is the sign up for these calls? I need to join them.

**Comment by pfey03** [comment]
There is no signup. Anyone can join it's Thursdays every two weeks, my time in Chicago at 11:00, for you in UK at 17:00. Here is the link to the records and to zoom: https://docs.google.com/document/d/1WrQanAMuccS-oaoAIb9yWQAd4Rvy3R3mU01v9wHbriM/edit

**Comment by hattrill** [comment]
So the next upheno is on the 9th Feb. I will join the next one as will some other members of FB.

**Comment by pfey03** [comment]
@ValWood @hattrill If you have any cell death or necrotic cell death phenotype annotations bring a few examples I also bring a few from Dicty

**Comment by ValWood** [comment]
>If you have any cell death or necrotic cell death phenotype annotations

I have 1662 https://www.pombase.org/results/from/id/22024c98-a4b1-4fc3-8e3d-1154e94bc916
That's the point, these don't belong in GO.

**Comment by pgaudet** [comment]
@ValWood I updated the wiki https://wiki.geneontology.org/Apoptosis_Curation_Manual to explain that we obsoleted some terms, and that we only recommend annotating when the mechanism of death is known.

**Comment by ValWood** [comment]
So, once all the annotations are removed, I'll remove all of the non-programmed cell death children. I'll keep  the"cell death" term for the time being with a "do not annotate" label until the phenotype ontologies have an alternative solution.

**Comment by pfey03** [comment]
@ValWood Thanks! I think we are close to solution in pheno.

**Comment by ValWood** [comment]
It will be obsoleted once uPHENO have an alternative mechanism to logically define phenotypes.

**Comment by sbello** [comment]
@ValWood This was discussed again at the UPheno call today (minutes here https://docs.google.com/document/d/1WrQanAMuccS-oaoAIb9yWQAd4Rvy3R3mU01v9wHbriM/edit?usp=sharing) and even if we can devise a plan for defining this using PATO we then lose the connection to the GO terms for programmed ell death and programmed necrotic cell death. We want to keep all the cell death terms grouped  UPheno. Would it not be possible to keep cell death as a grouping term for the programmed children? 
@dosumis

**Comment by ValWood** [comment]
Hi @sbello @dosumis Can discuss with @pgaudet  tomorrow. I don't think we would have a problem leaving it semi-indefinitely with a "do not annotate" flag, although it would seem odd, I guess we could add a comment why it is there. uPHENO might want to do something different eventually if you need a "real" logical definition for cell death (it doesn't have a logical definition in GO, so GO is providing the structure, but no content in terms of real equivalence axioms).

**Comment by dosumis** [comment]
We don't need a full logical definition* - just the subClassOf hierarchy.  Grouping terms for entities are often needed to define terms in phenotype ontologies - as what can be inferred from a phenotype is often vague.  GO is the only reference ontology we have for biological process, so a bias against keeping grouping terms leaves us in a bind.  Keeping them and adding 'do no annotate' for GO purposes would make our lives much easier. 

(*I think 'real' logical definitions should be used sparingly  - restricted to places where they do useful work, rather than being an end in themselves).

**Comment by addiehl** [comment]
+1 to David's comment about the value of grouping terms

**Comment by ValWood** [comment]
We are not proposing to get rid of grouping terms generally. We are keeping "cell death" term to be pragmatic for uPHENO because they want to use it to group non-programmed cell death phenotypes which are out of scope for GO.  However, "cell death' will be single inheritance which is not good ontology practice. Programmed cell death would be sufficient as a grouping term for GO.

**Comment by pfey03** [comment]
@ValWood There are other grouping terms that are do not annotate, but necessary for grouping. I understand that programmed cell death could serve this for GO but what makes it such a problem to keep cell death as a do not annotate. The non programmed necrotic cell death or such are gone and that's fine and cleans it up already.

**Comment by pfey03** [comment]
@Val, is cell death with these extensive comments now to stay? This would be awesome, please let us know.

**Comment by ValWood** [comment]
So in summary,
We don't have a problem with grouping terms per se, but the term "cell death" will no longer be a grouping term, because it is single inheritance, therefore completely unnecessary (an meaningless) in GO.
There is a possibility that "cell killing" may go under here, which will make it multiple inheritance and therefore a valid term
https://github.com/geneontology/go-ontology/issues/25174 if you have any thoughts on this please comment in the ticket.
this needs to be discussed at the editors meeting.

For now, we can keep the term with comments, even if it ends up as single inheritance, but it isn't  best practice.
Ideally there would be a better solution in the future.

**Comment by ValWood** [comment]
Because once the obsoletions are completed, "cell death" will have only one descendant, "programmed cell death".

**Comment by ValWood** [comment]
I think I am using the wrong terminology. I mean it only has a single sub-class.

**Comment by ValWood** [comment]
Hi @pgaudet  how do I flag the "cell death" term as "do not annotate"

**Comment by pgaudet** [comment]
See https://wiki.geneontology.org/Adding_a_Term_to_a_GO_Subset_(Slim)

**Comment by ValWood** [comment]
@pgaudet  I edited the comment 

from
This term should not be used for direct annotation. The only exception should be when experimental data (e.g., staining with trypan blue or propidium iodide) show that cell death has occurred, but fail to provide details on death modality (accidental versus programmed). When information is provided on the cell death mechanism, annotations should be made to the appropriate descendant of 'cell death' (such as, but not limited to, GO:0097300 'programmed necrotic cell death' or GO:0006915 'apoptotic process'). Also, if experimental data suggest that a gene product influences cell death indirectly, rather than being involved in the death process directly, consider annotating to a 'regulation' term.

to:
This term should not be used for direct annotation, it is currently kept in GO as a placeholder for describing cell death phenotypes in uPHENO.  When information is provided on a programmed cell death mechanism, annotations should be made to the appropriate descendant of 'cell death' (such as, but not limited to, GO:0097300 'programmed necrotic cell death' or GO:0006915 'apoptotic process'). Unintentional cell death, i.e. cell death caused by injury, ageing, or cell phenotypes observed as a result of a pathological mutation in an essential gene should NOT be annotated using GO terms.

**Comment by pgaudet** [comment]
@ValWood @sbello @dosumis 

Does UPHENO need to refer to GO 'cell death'? Keeping this is not ideal for GO
<img width="217" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/e79c0e74-f159-4f3e-8c5a-5f54858f6b8b">


Is there another way this can be handled? Even if we put 'do not annotate' tags on terms, depending on the tools, some groups still manage to get annotations through, so we go around adding/removing annotations.

**Comment by ValWood** [comment]
I think it would be a problem until the concept of "cell death" is  somewhere else. Could this go in PATO?

**Comment by ValWood** [comment]
I notice that PATO does have concepts around viability at the organism level (but not cell level)
https://www.ebi.ac.uk/ols4/ontologies/pato/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPATO_0001422?lang=en


I think the problem might have been a way to group all types of cell death (if this is required?)

**Comment by pgaudet** [comment]
OK - but 'viability' is very different from the GO concept of cell death. Seems quite misleading.

**Comment by ValWood** [comment]
Yes, but  it has been used in creating logical defs   for population viability for phenotype annotations for microrgs (mainly dicty), which is a completely different thing.

I tried to explain this (but probably not very well). We never added logical definitions for population death in FYPO for this reason.

I'm not sure what the other use cases are where a programmed cell death term can't be used.  Maybe things like cell lysis but this is still viability and it isn't what the GO "cell death" term means.
