### ISSUE TITLE
NTR:   histone H4K12 methyltransferase activity 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24695]
Please provide as much information as you can: 

* **Suggested term label:**

 histone H4K12 methyltransferase activity 

* **Definition (free text)**
Catalysis of the reaction: S-adenosyl-L-methionine + histone H4 L-lysine (position 12) = S-adenosyl-L-homocysteine + histone H4 N6-methyl-L-lysine (position 12). This reaction is the addition of a methyl group to the lysine residue at position 12of the histone H4 protein.

* **Reference, in format PMID:#######**
 31061526

* **Gene product name and ID to be annotated to this term**
Q9Y5N5
* **Parent term(s)**
GO:0140939 histone H4 methyltransferase activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140984
+name: histone H4K12 methyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: S-adenosyl-L-methionine + histone H4 L-lysine (position 12) = S-adenosyl-L-homocysteine + histone H4 N6-methyl-L-lysine (position 12). This reaction is the addition of a methyl group to the lysine residue at position 12 of the histone H4 protein." [PMID:12086618]
+comment: Note that in some species, the methyl group may be added to a lysine in a slightly different position of the histone H4 protein, but that this term still applies.
+synonym: "histone H4 lysine 12-specific methyltransferase activity" EXACT []
+synonym: "histone H4K12 methylase activity" BROAD []
+synonym: "histone H4K12 methylation" EXACT []
+synonym: "histone lysine N-methyltransferase activity (H4-K12 specific)" EXACT []
+synonym: "histone methylase activity (H4-K12 specific)" EXACT []
+synonym: "histone methyltransferase activity (H4-K12 specific)" EXACT []
+synonym: "histone-H4K12 methyltransferase activity" EXACT []
+is_a: GO:0140939 ! histone H4 methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24695 xsd:anyURI
+created_by: pg
+creation_date: 2023-01-12T13:58:00Z

**Comment by deustp01** [comment]
I'm missing something. I thought that function terms that specified the identity of the target (H2A, H3, etc) AND ALSO the identity of the target residue (lysine or arginine) undergoing modification were now deprecated and soon to be obsolete. What am I missing that distinguishes this new term from the deprecated group?

**Comment by pgaudet** [comment]
Hi @deustp01 


- We are removing the residue-specific axis of classification
- We are keeping the Histone-specific (H1, H2, H2, H3 etc) axis of classification. 

The rationale being that the different histones are more relevant to the chromatin remodeling than residues being modified, see https://docs.google.com/presentation/d/15fDBhmO54zSJms25aV5nX3kgSwsHMnWgdSuPdo-ukyw/edit#slide=id.gf4888089cb_1_3. 

Sorry about the confusion. 

Pascale

**Comment by deustp01** [comment]
> * We are removing the residue-specific axis of classification

Right. That's my confusion - it looks like the NTR involves a residue (to be removed) as well as a histone (to be kept)> Am I misreading the NTR?

**Comment by pgaudet** [comment]
Ah ! Got it. We are keeping residue/position specific terms. To illustrate: We use to have 


*  histone methyltransferase activity
* * 'histone H2A methyltransferase activity'
* * *  histone H2AR3 methyltransferase activity
*  histone lysine methyltransferase activity
* histone arginine N-methyltransferase activity >>>> **we are removing this axis of classification** 
* * * *  histone H2AR3 methyltransferase activity

but we are keeping specific leaf terms such as histone H2AR3 methyltransferase activity.

**Comment by deustp01** [comment]
> but we are keeping specific leaf terms such as histone H2AR3 methyltransferase activity.

Now I a=m deeply confused and also fairly angry, because as I understood the two requests for re-annotation of Reactome entities whose clean-up I seem to have wasted half a day on were to remove / obsolete EXACTLY these histone+residue combination leaf terms? What is going on? We don't have the bandwidth to do this once, let alone twice!

**Comment by Antonialock** [comment]
@deustp01 In my understanding the idea is to remove generic terms such as "histone lysine N-methyltransferase activity"
 and at the minimum move them to the less specific "histone methyltransferase" activity, 
where possible, we should specify the specific histone (h3, h4...), and if shown the position specific modification (h3k9 etc).
