### ISSUE TITLE
Missing parent:  GO:0019787 ubiquitin-like protein transferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24697]
* **GO term ID and label for which you request a new superclass**
GO:0019787 ubiquitin-like protein transferase activity

* **New superclass (parent) suggested**
GO:0016755 aminoacyltransferase activity (= EC:2.3.2.-)

Current parent of 'ubiquitin-like protein transferase activity' (GO:0019787) is 'transferase activity' (GO:0016740) = EC:2.-.-.-

But I notice that all the EC numbers relating to 'ubiquitin-like protein transferase activity' (either E2s or E3s) have a EC:2.3.2.- prefix:
2.3.2.23     E2 ubiquitin-conjugating enzyme = GO:0061631 ubiquitin conjugating enzyme activity
2.3.2.24     (E3-independent) E2 ubiquitin-conjugating enzyme
2.3.2.25     N-terminal E2 ubiquitin-conjugating enzyme
2.3.2.34     E2 NEDD8-conjugating enzyme

2.3.2.26     HECT-type E3 ubiquitin transferase
2.3.2.27     RING-type E3 ubiquitin transferase
2.3.2.31     RBR-type E3 ubiquitin transferase
2.3.2.33     RCR-type E3 ubiquitin transferase
2.3.2.36     RING-type E3 ubiquitin transferase (cysteine targeting)
2.3.2.32     cullin-RING-type E3 NEDD8 transferase

(also see ENZYME page for EC:2.3.2.- here: https://enzyme.expasy.org/EC/2.3.2.-

I think this means that the parent of 'ubiquitin-like protein transferase activity' (GO:0019787) could be changed to 'aminoacyltransferase activity (GO:0016755)', which equates to EC:2.3.2.-

Also see the 'Ubiquitination' section and Fig 1A here: https://www.nature.com/articles/ncomms15655

That said, EC only seems to have entries for ubiquitin and NEDD8 transferases, so I guess it's possible that transferases of other ubiquitin-like proteins (SUMO, UFM1, ISG15 etc) might be classified differently from EC:2.3.2.- ???

What do you think @hdrabkin @pgaudet @kaxelsen ?

**Comment by kaxelsen** [comment]
You're quite right, and I think it is a good idea.
