### ISSUE TITLE
Make GO:0046592 polyamine oxidase activity a parent of several GO classes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24701]
This is splitting from the ticket 
https://github.com/geneontology/go-ontology/issues/12432#issuecomment-1380200994

GO:0046592 polyamine oxidase activity EC removed - was mapped to EC:1.5.3.11, transferred to
Transferred entry: 1.5.3.13 GO:0052899, GO:0052904, GO:0052903, GO:0052902, and GO:0052901
Transferred entry: 1.5.3.14 GO:0052893, GO:0052896, and GO:0052900
OBSOLETED Transferred entry: 1.5.3.15 GO:0052898, and GO:0052897
Transferred entry: 1.5.3.16 GO:0052895, GO:0052894, and GO:0052901
Transferred entry: 1.5.3.17 GO:0052899, GO:0052904, GO:0052903, GO:0052902, GO:0052901,

GO:0046592 should be a parent of all classes mentioned above. 

Thanks, Pascale

**Comment by hdrabkin** [comment]
- [ ] GO:0046592 should be a parent of all classes mentioned above.

Done
