### ISSUE TITLE
Remove partial EC:1.3.3.- xref on GO:0016401 and GO:0044535

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24703]
Can you remove the partial 'EC:1.3.3.-' xref on the two entries below please?
(EC:1.3.3.- is correctly an xref on GO:0016634 oxidoreductase activity, acting on the CH-CH group of donors, oxygen as acceptor)

id: GO:0016401
name: palmitoyl-CoA oxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: palmitoyl-CoA + O2 = trans-2,3-dehydropalmitoyl-CoA + hydrogen peroxide." [GOC:jsg]
xref: EC:1.3.3.-
is_a: GO:0003997 ! acyl-CoA oxidase activity

id: GO:0044535
name: `very-long-chain fatty acyl-CoA oxidase activity`
namespace: molecular_function
def: "Catalysis of the reaction: very-long-chain fatty acyl-CoA (C22 - C24) + O2 = trans-2,3-dehydroacyl-CoA + hydrogen peroxide." [PMID:17458872]
synonym: "very long chain fatty-acyl-CoA oxidase activity" EXACT []
synonym: "very-long-chain acyl-CoA oxidase activity" EXACT []
synonym: "VLC fatty-acyl-CoA oxidase activity" EXACT []
xref: EC:1.3.3.-
is_a: GO:0003997 ! acyl-CoA oxidase activity

**Comment by hdrabkin** [comment]
Done
