### ISSUE TITLE
NTR: cyclic nucleotide phosphodiesterase activator activity

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#24706]
Please provide as much information as you can: 

* **Suggested term label:**
 cyclic nucleotide phosphodiesterase ~regulator~ activator activity

* **Definition (free text)**
Regulates or modulates the activity of cyclic nucleotide phosphodiesterase

* **Reference, in format PMID:6087882, PMID:6259174, PMID:6667031

* **Gene product name and ID to be annotated to this term**
calA, DDB_G0279407

* **Parent term(s)**
 GO:0004112: cyclic-nucleotide phosphodiesterase activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term? 
cyclic-nucleotide phosphodiesterase activator activity

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
There is only one MF: GO:0004112 cyclic-nucleotide phosphodiesterase activity and BP regulation children we have annotation to. Calmodulin seems to positively regulate cyclic nucleotide phosphodiesterase activity as the activity starts when adding calmodulin.
OF course the activity term has also more specific children but I won't need those regulator terms maybe others may need them.

**Comment by pfey03** [comment]
Hi @edwong57 could you please let me know if you plan to act on this?
Adding
- cyclic nucleotide phosphodiesterase regulator activity
- cyclic nucleotide phosphodiesterase activator activity

Many thanks!

**Comment by edwong57** [comment]
@pfey03 I'll take a look at this this week.

**Comment by edwong57** [comment]
@pfey03 just to clarify, you are asking for two new terms? 
1. cyclic nucleotide phosphodiesterase regulator activity as a child of GO:0004112:cyclic-nucleotide phosphodiesterase activity
2nd new term -- cyclic nucleotide phosphodiesterase activator activity as a child of NTR cyclic nucleotide phosphodiesterase regulator activity (not an existing term that should be moved?)

**Comment by pfey03** [comment]
These two terms would be great to add @edwong57 

Many thanks!!

**Comment by pgaudet** [comment]
I dont think we need the parent 'regulator activity' - let's only create the term for which we have evidence. 

Thanks, Pascale

**Comment by edwong57** [comment]
Okay. Sounds good.
