### ISSUE TITLE
histone H2AR3 methyltransferase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24707]
Please provide as much information as you can: 

* **Suggested term label:**
histone H2AR3 methyltransferase activity

* **Definition (free text)**
Catalysis of the reaction: S-adenosyl-L-methionine + histone H2A L-arginine (position 3) = S-adenosyl-L-homocysteine + histone H2A N6-methyl-L-arginine (position 3). This reaction is the addition of a methyl group to the arginine residue at position 3 of the histone H2A protein.

* **Reference, in format PMID:#######**
23451136

* **Gene product name and ID to be annotated to this term**
Q6NUA1

* **Parent term(s)**

histone H2A methyltransferase activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
This term already exists GO:0070612 
Is that right ? 

I'll add the reference you provided. 

Thanks, Pascale

**Comment by Antonialock** [comment]
odd I didn't see it!  yes it does
