### ISSUE TITLE
obsolete GO:0044028 DNA hypomethylation and GO:0044026 DNA hypermethylation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24709]
These are readouts

**Comment by pgaudet** [comment]
2 EXP: https://docs.google.com/spreadsheets/d/1vIoh1iIGFg22FdZto1BYHv7UZIuMqzB2N_U-rdbSXFw/edit#gid=0

**Comment by LiNiMGI** [comment]
mgi done.
