### ISSUE TITLE
TPV? GO:0106264 and GO:0106310 - identity of NTP in reaction

### ISSUE THREAD

**Issue by deustp01** [geneontology/go-ontology#24700]
[GO:0106264](https://www.ebi.ac.uk/QuickGO/term/GO:0106264) protein serine kinase activity (using **_GTP_** as donor) is_a [GO:0106310](https://www.ebi.ac.uk/QuickGO/term/GO:0106310) protein serine kinase activity, whose definition speciifes ATP, not GTP: "Catalysis of the reactions: ATP + protein serine = ADP + protein serine phosphate."

**Comment by pgaudet** [comment]
I dont know why and how that changed. I reverted to the original parent used by @hdrabkin in https://github.com/geneontology/go-ontology/issues/19523, is_a GO:0004672 protein kinase activity
