### ISSUE TITLE
Obsolete GO:0047486 chondroitin ABC lyase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24702]
Unnecessary grouping class. 
No annotations, no mappings, not present in any subsets.

**Comment by raymond91125** [comment]
There are two UniProt IDA annotations, same gene, two different paper.

**Comment by pgaudet** [comment]
Annotations are to a child, aren't they?

**Comment by raymond91125** [comment]
Oh, yeah, I mis-read. sorry

**Comment by raymond91125** [comment]
Dear all,

The proposal has been made to obsolete GO:0047486 chondroitin ABC lyase activity.

    The reason for obsoletion is that this term was an unnecessary grouping term.

There are no experimental annotations to this term.

There are no mappings to this term.

This term is not present in any subset.

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/24702

Thanks,
