### ISSUE TITLE
NTR methylation maintenance following cell division (or DNA replication)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24712]
To describe the function of DNMT1 
PMID:10551868
PMID:10551869
https://www.jstage.jst.go.jp/article/biochemistry1922/128/2/128_2_315/_pdf
https://pubmed.ncbi.nlm.nih.gov/11005794/

Def: 

@colinlog

**Comment by pgaudet** [comment]
Useful for some reannotations here: https://docs.google.com/spreadsheets/d/1vIoh1iIGFg22FdZto1BYHv7UZIuMqzB2N_U-rdbSXFw/edit#gid=0

**Comment by ValWood** [comment]
Sounds off to have a term with "methylation" in the term name considering we are removing methylation from process. 

Or maybe this is OK because it is "DNA methylation" (should be specific)

Would the parent be
GO:0040029   epigenetic regulation of gene expression

and  a descendant be
GO:0010216    negative regulation of gene expression via chromosomal DNA cytosine methylation

This is also a fit MF -like:
GO:1901538  changes to DNA methylation involved in embryo development

and these terms are not part of chromatin remodelling but presumably should be. I have more questions for next week.....

**Comment by ValWood** [comment]
I still think this term sounds strange , since we won't have methylation in process. Is there no way to describe this as an MF?

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141119
+name: genome methylation maintenance following DNA replication
+namespace: biological_process
+def: "The process that maintains methylated cytosine in newly synthesized DNA following DNA replication. After the establishment of novel DNA methylation marks, the newly created patterns must be faithfully transmitted by maintenance DNA methyltransferases during cell division." [PMID:20142834, PMID:26077819, PMID:34968368] {comment="PMID:11005794"}
+comment: CG methylation is maintained by two evolutionarily conserved core partners: (1) a maintenance DNA methyltransferase called DNMT1 in mammals and MET1 (DNA METHYLTRANSFERASE 1) in plants and (2) a cofactor named UHRF1 in mammals and VIM (VARIANT IN METHYLATION) in plants. In mammals, the maintenance of non-CG methylation typically involves DNMT3 enzymes. In plants, non-CG methylation is further divided in two classes of sequence, CHG and CHH, and requires distinct enzymatic machineries.
+synonym: "DNA methylation" BROAD []
+synonym: "DNA methylation maintenance" BROAD []
+synonym: "DNA methylation maintenance following cell division" EXACT []
+synonym: "DNA methylation maintenance following DNA replication" EXACT []
+is_a: GO:0006325 ! chromatin organization
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24712" xsd:anyURI
+created_by: pg
+creation_date: 2023-11-24T15:03:16Z

**Comment by pgaudet** [comment]
@ValWood I really dont think we can make that an MF, or else we won't have a process to attach to DNMT1 and UHRF1.

**Comment by pgaudet** [comment]
@colinlog we need to look into the parentage of the term. Now I made it 'is_a: GO:0006325 ! chromatin organization'

@ValWood had other suggestions above (https://github.com/geneontology/go-ontology/issues/24712#issuecomment-1382706245)

**Comment by ValWood** [comment]
> @ValWood I really dont think we can make that an MF, or else we won't have a process to attach to DNMT1 and UHRF1.

OK got it.

Any reason why "Genome methylation" rather than "DNA methylation maintenance"?

**Comment by pgaudet** [comment]
Fixed label to 'chromosomal DNA methylation maintenance following DNA replication'
