### ISSUE TITLE
Obsoletion notice: GO:0030104 water homeostasis

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24726]
Dear all, 

The proposal has been made to obsolete GO:0030104 water homeostasis. The reason for obsoletion is that this term does not specify whether the process is intracellular or organism-level. Consider: 
*  GO:0009992 intracellular water homeostasis
* GO:0050891 multicellular organismal-level water homeostasis 
* GO:0003091 renal water homeostasis

There are 30 annotations to this term see https://github.com/geneontology/go-annotation/issues/4407
Group | Number of annotations
-- | --
dictyBase | 1
FlyBase | 5
MGI | 5
TAIR | 3
UniProt | 8
WB | 4
ZFIN | 4

There are no mappings, this term is not in any subsets. 

You can comment on the ticket: 

Thanks, Pascale

**Comment by pfey03** [comment]
Dicty done

**Comment by raymond91125** [comment]
When I tried to obsolete GO:0030104 water homeostasis (Protege 5.5.0 Build beta-8, Edit->Deprecate entry...), I get errors for pull requests. I noticed that one strange thing is that although in Protege I see owl:deprecated true, there is no is_obsolete: true in the go-edit.obo file Protege saved. @pgaudet @balhoff Do you know why? Should I manually add that line?

```
diff --git a/src/ontology/go-edit.obo b/src/ontology/go-edit.obo
index cac26669..291d5910 100644
--- a/src/ontology/go-edit.obo
+++ b/src/ontology/go-edit.obo
@@ -25458,8 +25458,6 @@ def: "Renal process involved in the maintenance of an internal steady state of w
 synonym: "water homeostasis by the renal system" EXACT []
 is_a: GO:0003014 ! renal system process
 is_a: GO:0050891 ! multicellular organismal-level water homeostasis
-intersection_of: GO:0030104 ! water homeostasis
-intersection_of: occurs_in UBERON:0001008 ! renal system
 
 [Term]
 id: GO:0003092
@@ -137264,6 +137262,11 @@ def: "Synthesis and ordering of the envelope of pronuclei." [GOC:ems]
 is_a: GO:0006998 ! nuclear envelope organization
 relationship: part_of GO:0007338 ! single fertilization
 
+[Term]
+id: GO:0018987
+property_value: IAO:0000231 IAO:0000227
+is_obsolete: true
+
 [Term]
 id: GO:0018988
 name: obsolete molting cycle, protein-based cuticle
@@ -156089,16 +156092,12 @@ intersection_of: has_primary_input CHEBI:9937 ! vasopressin
 
 [Term]
 id: GO:0030104
-name: water homeostasis
+name: obsolete water homeostasis
 namespace: biological_process
-alt_id: GO:0018987
-def: "Any process involved in the maintenance of an internal steady state of water within an organism or cell." [GOC:dph, GOC:mah, GOC:tb]
+def: "OBSOLETE. Any process involved in the maintenance of an internal steady state of water within an organism or cell." [GOC:dph, GOC:mah, GOC:tb]
 synonym: "osmoregulation" RELATED []
 synonym: "regulation of osmotic pressure" EXACT []
 xref: Wikipedia:Osmoregulation
-is_a: GO:0048878 ! chemical homeostasis
-intersection_of: GO:0048878 ! chemical homeostasis
-intersection_of: regulates_levels_of CHEBI:15377 ! water
 
 [Term]
 id: GO:0030105
diff --git a/src/ontology/imports/uberon_import.owl b/src/ontology/imports/uberon_import.owl
index f5c764c4..64849b93 100644
--- a/src/ontology/imports/uberon_import.owl
+++ b/src/ontology/imports/uberon_import.owl
@@ -3543,7 +3543,9 @@
 
     <!-- http://purl.obolibrary.org/obo/GO_0030104 -->
 
-    <owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0030104"/>
+    <owl:Class rdf:about="http://purl.obolibrary.org/obo/GO_0030104">
+        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
+    </owl:Class>
     
 
 
@@ -145025,5 +145027,5 @@
 
 
 
-<!-- Generated by the OWL API (version 4.5.6) https://github.com/owlcs/owlapi -->
+<!-- Generated by the OWL API (version 4.5.7.2018-12-02T02:23:35Z) https://github.com/owlcs/owlapi -->

```

**Comment by pgaudet** [comment]
Looks like you have obsoleted the wrong term - 'Renal water homeostasis' was not supposed to be obsoleted - it was 'water homeostasis' 
https://github.com/geneontology/go-ontology/commit/fb2392cf9170bf9f71d9433943feaf88f4ffd452

You have consider 'GO:0003091' renal water homeostasis - this is a circular reference (because you accidentally obsoleted the wrong term, as fas as I can tell). 


(by the way I dont understand why GitHub gives the following message:: 
<img width="841" alt="image" src="https://user-images.githubusercontent.com/4782928/214584422-a4079e28-88e2-4625-852f-fb9386c4591d.png">

**Comment by raymond91125** [comment]
@pgaudet that was some mistake I had made earlier when I was scrambling to get things working. My question is regarding the above quoted <git diff> command output for an edit that I have not committed or pushed to github. In that output, you can see that in the stanza of [Term] id: GO:0030104, there is no "is_obsolete: true" line, despite the fact that it was obsoleted in Protege.

**Comment by raymond91125** [comment]
My feeling is that it has something to do with the related change in uberon. To be clear, that was made via Protege. I just want to report this problem, and know if I should add a line "is_obsolete: true" manually or perhaps I've done something wrong.

**Comment by pgaudet** [comment]
As far as I can tell, the problem is that this was merged with GO:0018987 (osmoregulation) 
so we need to restore and obsolete GO:0018987 (osmoregulation) ?? @balhoff is this right ?? 

(This must have happened before, I cannot remember how this should get resolved)

**Comment by balhoff** [comment]
@pgaudet do you mean like SOP, or technically how to bring it back? For the latter we could just copy the term stanza back in, or I could revert the PR that caused it.

**Comment by raymond91125** [comment]
Hi @balhoff just to recap. I was trying to obsolete GO:0030104 water homeostasis using Protege. One problem I noticed is that the resulting go-edit.obo file does not have the line "is_obsolete: true" in the stanza for GO:0030104. I wonder if there is something I did wrong or if this is a bug of the "Deprecate entity..." function. And if I should just simply add that line manually. The obsoletion also touched the uberon_import.owl file.

**Comment by raymond91125** [comment]
I think I finally understood what's going on. There is a bug in Protege "Deprecate entity ..." function. instead of writing information to go-edit.obo, it's writing to uberon_import.owl. The manual Protege obsoletion process works fine. No need to do anything about the merged term osmoregulation.

**Comment by pgaudet** [comment]
This is odd. I obsoleted other terms without any problem. Maybe the term is
present in both ontologies and we kept on obsoleting the wrong one?

Le ven. 27 janv. 2023, 20:40, Raymond Lee ***@***.***> a
écrit :

**Comment by raymond91125** [comment]
I don't understand what triggers the different behavior either. I thought the uberon_import.owl file is supposed to be a 'derived file' and should not be edited directly.

**Comment by raymond91125** [comment]
May I close this ticket?

**Comment by pgaudet** [comment]
Yes!

Le ven. 27 janv. 2023, 20:53, Raymond Lee ***@***.***> a
écrit :
