### ISSUE TITLE
Remove partial EC xref from GO:0016175 superoxide-generating NAD(P)H oxidase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24728]
id: GO:0016175
name: superoxide-generating NAD(P)H oxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: NAD(P)H + O2 = NAD(P)H + O2-." [GOC:ai, PMID:10806195]
synonym: "cytochrome B-245" RELATED []
xref: EC:1.6.3.-
is_a: GO:0050664 ! oxidoreductase activity, acting on NAD(P)H, oxygen as acceptor

EC:1.6.3.- is correctly an xref on "GO:0050664 oxidoreductase activity, acting on NAD(P)H, oxygen as acceptor" but should be removed from the term above.

**Comment by pgaudet** [comment]
GO:0106291 superoxide-generating NADH oxidase activity.

Remove period
