### ISSUE TITLE
chaperone complex (GO:0101031) missing children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24722]
chaperone complex (GO:0101031)
is defined

A protein complex required for the non-covalent folding or unfolding, maturation, stabilization or assembly or disassembly of macromolecular structures. Usually active during or immediately after completion of translation. Many chaperone complexes contain heat shock proteins. [PMID:21855797]

a) this is probably a strange grouping term because it , mixes different types of chaperone
and
b), if it is meant to cover all chaperons, there are many chaperone complexes that are missing this parentage
.
For example,  

Swr1 complex, CAF-1 complex, FACT complex (among others) are histone chaperones.

**Comment by pgaudet** [comment]
Hi @ValWood 

CAF-1 complex, FACT complex are not children of chaperone complex (GO:0101031)

I propose we rename 'chaperone complex (GO:0101031)' to match its definition, as well as the MF term 'GO:0044183
   protein folding chaperone' , so it's not ambiguous  anymore. Does that work ? 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes, I was going to suggest that. I think that works.
