### ISSUE TITLE
missing parent?: apyrase activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#2473]
I am trying to reconcile this.

I have somthing annotated to nucleotide diphosphatase
(PMID 12686557)

this statement suggests

whereas Spynd1p is an apyrase because it
hydrolyzed both nucleoside
tri and diphosphates

suggest there are some missing parents for
GO:0004050 apyrase activity?

Reported by: ValWood

Original Ticket: "geneontology/ontology-requests/2480":https://sourceforge.net/p/geneontology/ontology-requests/2480

**Comment by pgaudet** [comment]
@argout-puy requests that this term be resuscitated, since it corresponds to the specificity of ENTP1_HUMAN ( P49961)
