### ISSUE TITLE
Remove partial EC xref from GO:0042500 aspartic endopeptidase activity, intramembrane cleaving

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24730]
id: GO:0042500
name: aspartic endopeptidase activity, intramembrane cleaving
namespace: molecular_function
def: "Catalysis of the hydrolysis of nonterminal peptide bonds in a polypeptide chain, occurring within a membrane." [GOC:jl, ISBN:0198506732]
comment: Note that although GO generally avoids the use of localization information in terms, in this case an exception was made. This is because the fact that the cleavage occurs within the membrane is integral to its function, as it is the only thing that distinguishes this group from other aspartic endopeptidases.
xref: EC:3.4.23.-
xref: Reactome:R-HSA-8863101 "SPPL2a/b cleaves TNF(1-76)"
is_a: GO:0004190 ! aspartic-type endopeptidase activity

EC:3.4.23.- is correctly an xref on "GO:0004190 aspartic-type endopeptidase activity" and should be removed from the term above.

**Comment by hdrabkin** [comment]
I cannot find the EC:3.4.23.- associated with this GO term.  This might have been removed during another ticket.

**Comment by sjm41** [comment]
OK, good!
