### ISSUE TITLE
GO terms referencing EC:4.2.1.134 (very-long-chain (3R)-3-hydroxyacyl-CoA dehydratase)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24738]
There are 5 GO terms using EC:4.2.1.134 as an xref and/or definition attribution.

https://enzyme.expasy.org/EC/4.2.1.134
Name: very-long-chain (3R)-3-hydroxyacyl-CoA dehydratase.
Reaction: a very-long-chain (3R)-3-hydroxyacyl-CoA <=> a very-long-chain (2E)-enoyl-CoA + H2O

The xref on GO:0102158 (shown below) looks correct, although:
- [x] the definition ought to be changed to use "a very-long-chain (2E)-enoyl-CoA" in the right hand side (to match EC/Rhea)
- [x]  the '(3R)' bit should be included in the term name:

id: GO:0102158
name: very-long-chain 3-hydroxyacyl-CoA dehydratase activity  [9658 annotations, no EXP]
namespace: molecular_function
def: "Catalysis of the reaction: a very-long-chain (3R)-3-hydroxyacyl-CoA = H2O + a very-long-chain trans-2,3-dehydroacyl-CoA." [GOC:pz, RHEA:45812]
xref: EC:4.2.1.134
xref: MetaCyc:RXN-11750
xref: RHEA:45812
is_a: GO:0016836 ! hydro-lyase activity

----------

I think the other 4 (shown below) sh/could be obsoleted - the EC xref/attribution isn't accurate, none have any EXP annotations, and the all the non-EXP annotations are the same IEAs with EC2GO via EC:4.2.1.134.
But if they are retained, then the EC references should be removed, and they should become children (rather than sisters) of GO:0102158. The first one also appears to have a discrepancy in the substrate involved in the term name vs definition.

id: GO:0102343
name: 3-hydroxy-arachidoyl-CoA dehydratase activity  [6165 annotations, no EXP]
namespace: molecular_function
def: "Catalysis of the reaction: (R)-3-hydroxyicosanoyl-CoA <=> trans-2-icosenoyl-CoA + H2O." [EC:4.2.1.134, GOC:pz]
xref: EC:4.2.1.134
xref: MetaCyc:RXN-13302
is_a: GO:0016836 ! hydro-lyase activity

id: GO:0102344
name: 3-hydroxy-behenoyl-CoA dehydratase activity  [6165 annotations, no EXP]
namespace: molecular_function
def: "Catalysis of the reaction: (R)-3-hydroxybehenoyl-CoA <=> trans-2-docosenoyl-CoA + H2O." [EC:4.2.1.134, GOC:pz]
xref: EC:4.2.1.134
xref: MetaCyc:RXN-13303
is_a: GO:0016836 ! hydro-lyase activity

id: GO:0102345
name: 3-hydroxy-lignoceroyl-CoA dehydratase activity  [6165 annotations, no EXP]
namespace: molecular_function
def: "Catalysis of the reaction: (R)-3-hydroxylignoceroyl-CoA(4-) <=> trans-2-tetracosenoyl-CoA + H2O." [EC:4.2.1.134, GOC:pz]
xref: EC:4.2.1.134
xref: MetaCyc:RXN-13304
is_a: GO:0016836 ! hydro-lyase activity

id: GO:0102346
name: 3-hydroxy-cerotoyl-CoA dehydratase activity  [0 annotations]
namespace: molecular_function
def: "Catalysis of the reaction: (R)-3-hydroxycerotoyl-CoA(4-) <=> trans-2-hexacosenoyl-CoA(4-) + H2O." [EC:4.2.1.134, GOC:pz]
xref: MetaCyc:RXN-13305
is_a: GO:0016836 ! hydro-lyase activity

**Comment by sjm41** [comment]
Also, looks like GO:0102158 very-long-chain **(3R)**-3-hydroxyacyl-CoA dehydratase activity should be made a child of this term:

id: GO:0080023
name: 3R-hydroxyacyl-CoA dehydratase activity [5 EXP annotations]
namespace: molecular_function
def: "Catalysis of the reaction: 3R-hydroxyacyl-CoA = 2E-enoyl-CoA + H2O." [PMID:16982622]
xref: Reactome:R-HSA-5676637 "PTPLs dehydrate VLC3HA-CoA to VLCTDA-CoA"
is_a: GO:0016836 ! hydro-lyase activity

**Comment by sjm41** [comment]
Further (!), are these two terms referring to the same thing?:

id: GO:0080023
name: 3R-hydroxyacyl-CoA dehydratase activity [5 EXP annotations]
namespace: molecular_function
def: "Catalysis of the reaction: 3R-hydroxyacyl-CoA = 2E-enoyl-CoA + H2O." [PMID:16982622]
xref: Reactome:R-HSA-5676637 "PTPLs dehydrate VLC3HA-CoA to VLCTDA-CoA"
is_a: GO:0016836 ! hydro-lyase activity

id: GO:0018812
name: 3-hydroxyacyl-CoA dehydratase activity  [11 EXP annotations]
namespace: molecular_function
def: "Catalysis of the reaction: alkene-CoA + H2O = alcohol-CoA. Substrates are crotonoyl-CoA (producing 3-hydroxyacyl-CoA) and 2,3-didehydro-pimeloyl-CoA (producing 3-hydroxypimeloyl-CoA)." [UM-BBD_ruleID:bt0291]
xref: Reactome:R-HSA-8957389 "RPP14 (HTD2) dehydrates 3HA-CoA to t2E-CoA"
is_a: GO:0016836 ! hydro-lyase activity

I don't know if "3R-hydroxyacyl..." is different from "3-hydroxyacyl..."??

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
GO:0102343 3-hydroxy-arachidoyl-CoA dehydratase activity 
GO:0102344 3-hydroxy-behenoyl-CoA dehydratase activity 
GO:0102345 3-hydroxy-lignoceroyl-CoA dehydratase activity 
GO:0102346 3-hydroxy-cerotoyl-CoA dehydratase activity 

The reason for obsoletion is that these correspond to specific substrates of GO:0102158 very-long-chain 3-hydroxyacyl-CoA dehydratase activity. There are no EXP annotations to these terms. There is one mapping, EC:4.2.1.134, which corresponds to the more general activity described by GO:0102158. These terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24738

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
GO:0102343 3-hydroxy-arachidoyl-CoA dehydratase activity 
GO:0102344 3-hydroxy-behenoyl-CoA dehydratase activity 
GO:0102345 3-hydroxy-lignoceroyl-CoA dehydratase activity 
GO:0102346 3-hydroxy-cerotoyl-CoA dehydratase activity 

The reason for obsoletion is that these correspond to specific substrates of GO:0102158 very-long-chain 3-hydroxyacyl-CoA dehydratase activity. There are no EXP annotations to these terms. There is one mapping, EC:4.2.1.134, which corresponds to the more general activity described by GO:0102158. These terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24738

Thanks, Pascale

**Comment by pgaudet** [comment]
- [ ] GO:0080023 3R-hydroxyacyl-CoA dehydratase activity 
==  RHEA:26526 & EC:4.2.1.119

**Comment by sjm41** [comment]
Thanks Pascale!
Given GO:0018812 (3-hydroxyacyl-CoA dehydratase activity) is agnostic of the stereoisomer, should GO:0080023 (3R-hydroxyacyl-CoA dehydratase activity) be a child of it?

**Comment by pgaudet** [comment]
Yes, I've added this, thanks

We now have 

. '3-hydroxyacyl-CoA dehydratase activity'
. . '(3R)-3-hydroxyacyl-CoA dehydratase activity'
. . . '(3R)-3-hydroxybutyryl-CoA dehydratase activity'
. . . 'very-long-chain (3R)-3-hydroxyacyl-CoA dehydratase activity'

**Comment by sjm41** [comment]
Sorry, looks like there's some additional nesting to do here.  I think the tree needs to be arranged as shown below (terms not discussed so far in this ticket are shown in bold):

. '3-hydroxyacyl-CoA dehydratase activity' (GO:0018812)
**. . 'enoyl-CoA hydratase activity' (GO:0004300, EC:4.2.1.17) [34 EXP annotations]**
**. . 'long-chain-enoyl-CoA hydratase activity' (GO:0016508, EC:4.2.1.74) [8 EXP annotations]**
**. . '3-hydroxypropionyl-CoA dehydratase activity' (GO:0043956, EC:4.2.1.116)  [1 EXP annotation]***
. . '(3R)-3-hydroxyacyl-CoA dehydratase activity' (GO:0080023, EC:4.2.1.119)
. . . '(3R)-3-hydroxybutyryl-CoA dehydratase activity' (GO:0003859, 4.2.1.55)
. . . 'very-long-chain (3R)-3-hydroxyacyl-CoA dehydratase activity' (GO:0102158, EC:4.2.1.134)


Additional changes to those new terms:

id: GO:0004300
name: enoyl-CoA hydratase activity 
def: "Catalysis of the reaction: (3S)-3-hydroxyacyl-CoA = trans-2-enoyl-CoA + H2O." [EC:4.2.1.17]
xref: EC:4.2.1.17
xref: MetaCyc:ENOYL-COA-HYDRAT-RXN
xref: RHEA:16105
xref: UM-BBD_enzymeID:e0014
=> Change definition to match EC?
=> But maps to 3 different RHEAs: RHEA:16105, RHEA:20724, RHEA:34863

id: GO:0016508
name: long-chain-enoyl-CoA hydratase activity  [8 EXP annotations]
def: "Catalysis of the reaction: a long-chain (3S)-3-hydroxyacyl-CoA = a long-chain trans-2-enoyl-CoA + H2O. A long-chain acyl-CoA is an acyl-CoA thioester where the acyl chain contains 13 to 22 carbon atoms." [EC:4.2.1.74]
synonym: "long-chain enoyl coenzyme A hydratase activity" RELATED [EC:4.2.1.74]
synonym: "long-chain-(3S)-3-hydroxyacyl-CoA hydro-lyase activity" RELATED [EC:4.2.1.74]
xref: EC:4.2.1.74
xref: MetaCyc:LONG-CHAIN-ENOYL-COA-HYDRATASE-RXN
=> name and def in EC is "medium-chain" rather than "long-chain" (though "long-chain" is a synonym!)
=> add RHEA: 71647


id: GO:0043956
name: 3-hydroxypropionyl-CoA dehydratase activity
def: "Catalysis of the reaction: 3-hydroxypropionyl-CoA = acrylyl-CoA + H2O." [GOC:jl, PMID:11821399]
comment: Note that this function is one of the activities of the trifunctional enzyme propionyl-coenzyme A synthase. See PMID:11821399.
xref: EC:4.2.1.116
xref: MetaCyc:RXN-6383
xref: RHEA:26518
=> change product from 'acrylyl-CoA' to 'acryloyl-CoA' to match EC/RHEA
=> EC maps to RHEA:26558 (as well as RHEA:26518)


Do you want a separate ticket for any of this??

**Comment by pgaudet** [comment]
**GO:0004300 enoyl-CoA hydratase activity**

- [ ] Changed definition: 
-def: "Catalysis of the reaction: (3S)-3-hydroxyacyl-CoA = trans-2-enoyl-CoA + H2O." [EC:4.2.1.17]
+def: "Catalysis of the reaction: a (3S)-3-hydroxyacyl-CoA = a (2E)-2-enoyl-CoA + H2O." [EC:4.2.1.17]

- [ ] xrefs: 
* [RHEA:16105](https://www.rhea-db.org/rhea/16105) 	a (3S)-3-hydroxyacyl-CoA = a (2E)-enoyl-CoA + H2O [19,054 protein(s) (UniProtKB)](https://www.uniprot.org/uniprotkb/?query=rhea:16105)
* [RHEA:20724](https://www.rhea-db.org/rhea/20724) 	a 4-saturated-(3S)-3-hydroxyacyl-CoA = a (3E)-enoyl-CoA + H2O [19,049 protein(s) (UniProtKB)](https://www.uniprot.org/uniprotkb/?query=rhea:20724)
* [RHEA:34863](https://www.rhea-db.org/rhea/34863) 	(Z)-2,3-didehydroadipyl-CoA + H2O = 3-hydroxyadipyl-CoA 	==> No mappings; very specific substrate ===> do not map

**Comment by pgaudet** [comment]
We cannot put enoyl-CoA hydratase activity as a child of '3-hydroxyacyl-CoA dehydratase activity' (GO:0018812) but we can do the other way around: 


.  'enoyl-CoA hydratase activity' (GO:0004300, EC:4.2.1.17) [34 EXP annotations]
. . '3-hydroxyacyl-CoA dehydratase activity' (GO:0018812)

* 3-hydroxyacyl-CoA dehydratase activity' Catalysis of the reaction: a 3-hydroxy-fatty acyl-CoA = **a (2E)-enoyl-CoA** + H2O.
*  enoyl-CoA hydratase activity: (new def to match EC: ) Catalysis of the reaction: a 3-hydroxy-fatty acyl-CoA = a **enoyl-CoA** + H2O. This reaction usually occurs in the reverse direction, leading to the reduction of the double bound of enoyl-CoA in position 2 or 3. Specific reactions catalyzed include: a 4-saturated-(3S)-3-hydroxyacyl-CoA = a (3E)-enoyl-CoA + H2O and a (3S)-3-hydroxyacyl-CoA = a (2E)-enoyl-CoA + H2O.

**Comment by pgaudet** [comment]
Hi @sjm41 

@marcfeuermann  and I looked at these terms this morning, and we propose to obsolete

**GO:0080023 (3R)-3-hydroxyacyl-CoA dehydratase activity** -> 6 EXP 	
- very-long-chain (3r)-3-hydroxyacyl-coa dehydratase pthr11035
- peroxisomal multifunctional enzyme type 2-related pthr13078

**GO:0003859 (3R)-3-hydroxybutyryl-CoA dehydratase activity** -> 1 EXP

**GO:0102158 very-long-chain (3R)-3-hydroxyacyl-CoA dehydratase activity** -> 0 EXP, all IEAs RHEA/EC

GO:0016508 **long-chain-enoyl-CoA hydratase activity -**> 7 EXP 
- peroxisomal multifunctional enzyme type 2-related pthr13078
- trifunctional enzyme subunit alpha pthr43612

with 'replaced by' GO:0018812 3-hydroxyacyl-CoA dehydratase activity, as this appears to be the degree of specificity of the enzymes. These are all involved in beta-oxidation, and the exact composition of the substrate does not seem to be crucial. Moreover, if we keep these terms, we need to add way more to make the hierarchy complete - see for example, all the reactions in this entry: https://www.uniprot.org/uniprotkb/P51659/entry

What do you think ? 


Thanks, Pascale

**Comment by sjm41** [comment]
Sounds good to me - this would greatly simplify this complicated set of terms!
So, after these changes, I think the local tree would look like this, right?:
. 'enoyl-CoA hydratase activity' (GO:0004300, EC:4.2.1.17)
. . '3-hydroxyacyl-CoA dehydratase activity' (GO:0018812)
. . '3-hydroxypropionyl-CoA dehydratase activity' (GO:0043956, EC:4.2.1.116)

Maybe GO:0043956 should be obsoleted too? (Has a single EXP annotation according to QuickGO)

**Comment by pgaudet** [comment]
Good point - in fact GO:0043956 3-hydroxypropionyl-CoA dehydratase activity is not involved in beta oxidation, see UniProt:A4YI89 

> Plays a role in autotrophic carbon fixation via the 3-hydroxypropionate/4-hydroxybutyrate cycle. Catalyzes the reversible dehydration of 3-hydroxypropionyl-CoA to form acryloyl-CoA, and the reversible dehydration of (S)-3-hydroxybutyryl-CoA to form crotonyl-CoA. Inactive towards (R)-3-hydroxybutyryl-CoA

That seems a more specific reaction. OK ?

**Comment by alanbridge** [comment]
Hi, 

may be worth checking with @kaxelsen, @amorgat, and the Rhea team (including Lucila Aimo), as stereospecificity is thought to be important in fatty acid metabolism, 

e.g. FADB of ECOLI - https://www.uniprot.org/uniprotkb/P21177/entry

Catalyzes the formation of 3-oxoacyl-CoA from enoyl-CoA via L-3-hydroxyacyl-CoA. 

that is 2 Rhea reactions 

a (3S)-3-hydroxyacyl-CoA + NAD(+) = a 3-oxoacyl-CoA + H(+) + NADH
a (3S)-3-hydroxyacyl-CoA = a (2E)-enoyl-CoA + H2O

which when joined make 

(2E)-enoyl-CoA -> (3S)-3-hydroxyacyl-CoA -> 3-oxoacyl-CoA

FADB is stereospecific, it doesn't do this 

(2E)-enoyl-CoA -> (3R)-3-hydroxyacyl-CoA -> 3-oxoacyl-CoA

All the best, Alan

**Comment by pgaudet** [comment]
HI @alanbridge 

I asked @kaxelsen about this; the current ontology version is very very incomplete - 

<img width="457" alt="image" src="https://user-images.githubusercontent.com/4782928/215822309-c1aceaff-c545-40dc-bbcf-0866fb907efd.png">

There are two options, obsolete these pretty random terms, or add all other possible substrates, which would be a very long list, and not in scope for GO, since these various reactions represents substrates of the same/similar enzymes. FOr GO these would be best captured as GO CAM models. 

Thanks for the feedback, 

Pascale

**Comment by sjm41** [comment]
Hi @pgaudet
Shall we proceed with the additional obsoletions mentioned in https://github.com/geneontology/go-ontology/issues/24738#issuecomment-1403404076 and https://github.com/geneontology/go-ontology/issues/24738#issuecomment-1403427211?

There's also a couple of tasks in https://github.com/geneontology/go-ontology/issues/24738#issuecomment-1387006246 to finish off.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
GO:0080023 (3R)-3-hydroxyacyl-CoA dehydratase activity -> 6 EXP
GO:0003859 (3R)-3-hydroxybutyryl-CoA dehydratase activity -> 1 EXP
GO:0102158 very-long-chain (3R)-3-hydroxyacyl-CoA dehydratase activity -> 0 EXP, all IEAs RHEA/EC
GO:0016508 long-chain-enoyl-CoA hydratase activity -> 7 EXP

The reason for obsoletion is that these reactions are all more specific than the enzymes they represent. 

These terms will be replaced with GO:0018812 3-hydroxyacyl-CoA dehydratase activity, as this is the specificity of the activity. 

There are 10 EXP annotations to these terms; if your annotation tool does automatic replacement, there is no action needed on your part. Impacted groups: 

ComplexPortal : 1 EXP
MTBBASE : 1 EXP
Reactome: 2 EXP
RGD: 1 EXP
UniProt : 5 EXP

https://github.com/geneontology/go-annotation/issues/4488

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24738

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks @pgaudet I think we were going to add '3-hydroxypropionyl-CoA dehydratase activity' GO:0043956 to the obsoletion list too?

**Comment by pgaudet** [comment]
Marc and I proposed to keep this - see https://github.com/geneontology/go-ontology/issues/24738#issuecomment-1403431466

**Comment by sjm41** [comment]
Ah, I interpreted that comment as you were going to obsolete it along with the others!  No problem keeping it!

**Comment by pgaudet** [comment]
This term was obsoleted because it represents a specific substrate of 3-hydroxyacyl-CoA dehydratase activity ; GO:0018812.

**Comment by pgaudet** [comment]
Just wondering : EC:4.2.1.17 is named  'enoyl-CoA hydratase', with the comment, 'Acts in the reverse direction. ' Other terms in this branch are called 'dehydratase'; should I rename enoyl-CoA hydratase?

**Comment by sjm41** [comment]
Renaming to dehydratase makes sense to me (given the EC comment), but maybe it's always called a 'enoyl-CoA hydratase' in the field/literature.  What do you think @kaxelsen ?

**Comment by pgaudet** [comment]
Sounds good, most papers refer to enoyl-CoA hydratase, so I'll leave this as is. 

https://pubmed.ncbi.nlm.nih.gov/?term=enoyl-CoA+dehydratase

**Comment by kaxelsen** [comment]
In the EC list, lyase reactions (EC 4) are always written in the direction of dehydratase, so the name hydratase and the comment about that it "acts in the reverse direction" are supplementary pieces of information.

**Comment by deustp01** [comment]
If I remember correctly, EC naming follows the convention that all chemical reactions are in principle reversible, so as here names are kept consistent and don't necessarily indicate the physiological direction of a reaction (so that direction information needs to come from somewhere else, not through tweaking the name of the enzyme or (maybe) the names of associated GO MF terms.

**Comment by kaxelsen** [comment]
@depust01. That is actually not the case case. The "accepted name"s are often the names widely used in the scientific field. If the enzyme has not been described before IUBMB tries to coin a sensible name ( e.g. 5-hydroxybenzimidazole synthase for EC 4.1.99.23 or GTP 3',8-cyclase for EC 4.1.99.22).
The systematic name is the one that describes the reaction following formal rules that do not take the physiological direction into account.

**Comment by sjm41** [comment]
@pgaudet 

We obsoleted 'very-long-chain 3-hydroxyacyl-CoA dehydratase activity' (GO:0102158) (= EC:4.2.1.134) as part of this clean-up, but I now realise that one should have been retained as it describes the key third activity in Microsomal fatty acyl elongation.

Quoting from the EC:4.2.1.134 (https://enzyme.expasy.org/EC/4.2.1.134) entry:
_This is the third component of the elongase, a microsomal protein complex responsible for extending palmitoyl-CoA and stearoyl-CoA (and modified forms thereof) to very-long chain acyl CoAs. cf. EC 1.1.1.330, EC 1.3.1.93 and EC 2.3.1.199._ 

(And we have GO terms corresponding to the first, second and fourth components/ECs of the elongase complex.)

Can we re-instate GO:0102158 as a child of 3-hydroxyacyl-CoA dehydratase activity' (GO:0018812)?
Also, the definition ought to be tweaked to match EC/Rhea, and the '(3R)' bit should be included in the term name to match EC.

Here's how the entry used to look:
id: GO:0102158
name: very-long-chain 3-hydroxyacyl-CoA dehydratase activity
namespace: molecular_function
def: "Catalysis of the reaction: a very-long-chain (3R)-3-hydroxyacyl-CoA = H2O + a very-long-chain trans-2,3-dehydroacyl-CoA." [GOC:pz, RHEA:45812]
xref: EC:4.2.1.134
xref: MetaCyc:RXN-11750
xref: RHEA:45812
is_a: GO:0016836 ! hydro-lyase activity

**Comment by pgaudet** [comment]
Although I think we had it differently because the parent's definition states 

>  The stereospecifity of the hydroxyacyl in this reaction is not specified.

while GO:0102158 mentions 3R.

**Comment by sjm41** [comment]
Oh yes, I see.
Maybe that caveat isn't explicitly needed on the parent definition - it's implied anyway by its absence in the stated reaction.  Then it won't look odd for the child GO:0102158 term to specify 3R?

**Comment by pgaudet** [comment]
> Maybe that caveat isn't explicitly needed on the parent definition 

RIght - and  I now remember that @marcfeuermann mentioned that these enzymes are probably non-stereo-specific, but this captures substrates that have been tested. Probably best for the definition to be a bit more vague to avoid having to make a complex hierarchy.

**Comment by sjm41** [comment]
Hi @pgaudet 

Can we please re-instate this term:

id: GO:0080023
name: obsolete (3R)-3-hydroxyacyl-CoA dehydratase activity
namespace: molecular_function
def: "OBSOLETE. Catalysis of the reaction: a (3R)-3-hydroxyacyl-CoA = a (2E)-enoyl-CoA + H2O." [PMID:16982622, RHEA:26526]
comment: This term was obsoleted because it represents a specific substrate of 3-hydroxyacyl-CoA dehydratase activity ; GO:0018812.
synonym: "3R-hydroxyacyl-CoA dehydratase activity" EXACT []
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24738" xsd:anyURI
is_obsolete: true
replaced_by: GO:0018812


This term (=EC:4.2.1.119/RHEA:26526/MetaCyc:RXN-7699) represents the key 2nd reaction in the 4-step peroxisomal beta-oxidation pathway (e.g. see PMID:17028011, PMID:21320074).
We already have the GO term (also specific for the R-stereoisomer) for the 3rd reaction: GO:0106386 (3R)-3-hydroxyacyl-CoA dehydrogenase (NAD+) activity (EC:1.1.1.n12).

Steps 2 and 3 are performed by the same bifunctional enzyme (HSD17B4 in humans, Mfe2 in flies), as the UniProt summary for HSD17B4 says:
_Bifunctional enzyme acting on the peroxisomal fatty acid beta-oxidation pathway. Catalyzes two of the four reactions in fatty acid degradation: hydration of 2-enoyl-CoA (trans-2-enoyl-CoA) to produce (3R)-3-hydroxyacyl-CoA, and dehydrogenation of (3R)-3-hydroxyacyl-CoA to produce 3-ketoacyl-CoA (3-oxoacyl-CoA),_


Re-instating this term would change the local tree from this:

```
 |__enoyl-CoA hydratase activity (GO:0004300) [EC:4.2.1.17]
	|__3-hydroxyacyl-CoA dehydratase activity (GO:0018812) [RHEA:33767] [EC:4.2.1.119/RHEA:26526 narrowMatch]
		|__crotonyl-CoA hydratase activity (GO:0120092) [RHEA:45584]
		|__very-long-chain (3R)-3-hydroxyacyl-CoA dehydratase activity (GO:0102158) [EC:4.2.1.134, RHEA:45812]
```

to this:
```
|__enoyl-CoA hydratase activity (GO:0004300) [EC:4.2.1.17]
	|__3-hydroxyacyl-CoA dehydratase activity (GO:0018812) [RHEA:33767]
		|__crotonyl-CoA hydratase activity (GO:0120092) [RHEA:45584]
 		|__(3R)-3-hydroxyacyl-CoA dehydratase activity [EC:4.2.1.119/RHEA:26526]
			|__very-long-chain (3R)-3-hydroxyacyl-CoA dehydratase activity (GO:0102158) [EC:4.2.1.134/RHEA:45812]
```
(this keeps the GO parent-child relations in line with the RHEA hierarchy for these terms)


Also:
- since this enzyme works in the 'hydratase' direction, it would be good to give it a 'hydratase' name - the official EC name is "enoyl-CoA hydratase 2", which won't work, so how about "(2E)-enoyl-CoA hydratase activity", which is similar to an EC synonym and is the name used in PMID:21320074

**Comment by pgaudet** [comment]
Hi @sjm41 

I restored the term. 

I also changed the label of GO:0120092 crotonyl-CoA hydratase activity to (2E)-butenoyl-CoA hydratase activity , which seems more consistent. Please let me know if you think that wasn't right. 

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks!
