### ISSUE TITLE
Remove partial EC xref from GO:0004394 and GO:0017095

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24749]
EC:2.8.2.- is correctly an xref on "GO:0008146 sulfotransferase activity" and should be removed from the terms below.

id: GO:0004394
name: heparan sulfate 2-O-sulfotransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 3'-phosphoadenosine 5'-phosphosulfate + heparan sulfate = adenosine 3',5'-bisphosphate + heparan sulfate 2-O-sulfate; results in 2-O-sulfation of iduronic acid residues in heparan sulfate." [PMID:9153262]
synonym: "heparan-sulfate 2-O-sulphotransferase activity" EXACT []
synonym: "heparin 2-sulfotransferase activity" RELATED []
synonym: "heparin-sulphate 2-sulphotransferase activity" RELATED []
xref: EC:2.8.2.-
xref: Reactome:R-HSA-2076508 "HS2ST1 sulfates IdoA at C2 in heparan sulfate"
is_a: GO:0034483 ! heparan sulfate sulfotransferase activity

id: GO:0017095
name: heparan sulfate 6-O-sulfotransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 3'-phosphoadenosine 5'-phosphosulfate + heparan sulfate = adenosine 3',5'-bisphosphate + heparan sulfate 6-O-sulfate; results in 6-O-sulfation of glucosamine residues in heparan sulfate." [PMID:8631808]
synonym: "heparan sulphate 6-O-sulphotransferase activity" EXACT []
synonym: "heparin 6-O-sulfotransferase activity" RELATED []
xref: EC:2.8.2.-
xref: Reactome:R-HSA-2076419 "HS6STs sulfate GlcN at C6 in heparan sulfate/heparin"
is_a: GO:0034483 ! heparan sulfate sulfotransferase activity

**Comment by hdrabkin** [comment]
done
