### ISSUE TITLE
Obsolete GO:0098806 miRNA-mediated gene silencing by mRNA deadenylation? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24746]
Hi, 

@RLovering and I are looking at GO:0098806 miRNA-mediated gene silencing by mRNA deadenylation. This is the single child of 'miRNA-mediated gene silencing by mRNA destabilization' - as if there were no other mechanism for GO:0035279 miRNA-mediated gene silencing by mRNA destabilization. Also, looking at papers cited in term term def cross reference - PMID:21118121 and PMID:23209154 - this seems to be the mechanism by which GO:0035279 miRNA-mediated gene silencing by mRNA destabilization takes place. 

So we propose to obsolete GO:0098806  and replace by GO:0035279 

There are 6 EXP annotations - 2 BHF and 4 FlyBase. @hattrill @gantonazzo - are you OK with obsoleting GO:0098806 miRNA-mediated gene silencing by mRNA deadenylation? 

Thanks, 

Pascale & @RLovering

**Comment by gantonazzo** [comment]
Hi both,

That's fine by me. I'll change our "miRNA-mediated gene silencing by mRNA deadenylation" annotations to "miRNA-mediated gene silencing by mRNA destabilization". I just think it would maybe be good to include the deadenylation process somewhere in the definition of GO:0035279, or maybe even add it as a synonym?

**Comment by RLovering** [comment]
I think a synonym is better as I am not sure if deadenylation always occurs with mRNA destabilization and I wouldn't want to put curators off using the term if they felt there was no evidence for the process

**Comment by gantonazzo** [comment]
Makes sense, adding a synonym sounds good enough to me.
