### ISSUE TITLE
Obsoletion request: [GO:0010941, GO:0060548,  GO:0010942 cell death regulation terms]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24755]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0010941    regulation of cell death 
GO:0060548    negative regulation of cell death 
GO:0010942    positive regulation of cell death 

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x]  The reason for obsoletion is that this term represent an assay and not a GO process.
 - [x]  The reason for obsoletion is that this represents a phenotype.
 - [x]  The reason for obsoletion is that this term was added in error.
 - [x]  The reason for obsoletion is that more specific terms were created.
 - [x]  The reason for obsoletion is that this term was an unnecessary grouping term.
 

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

[GO:0043067](https://www.ebi.ac.uk/QuickGO/term/GO:0043067)    regulation of programmed cell death
or children

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
https://docs.google.com/spreadsheets/d/1-NnAiTGTdaRVjMJ7rwtYyMeISicM4upwe9By2sbUIQQ/edit#gid=0

- [x] create annotation review ticket: 
https://github.com/geneontology/go-annotation/issues/4415

- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by pfey03** [comment]
@ValWood 
Will GO:0012501 programmed cell death then the new parent and all children will stay? Or will the regulation terms there also be obsoleted? Thanks

**Comment by pfey03** [comment]
Great, thanks

**Comment by pfey03** [comment]
dicty done

**Comment by ValWood** [comment]
Hi @RLovering , let me know wehre you are with this one. There are 20 annotations with no resolution i nthe spreadsheet.
v

**Comment by RLovering** [comment]
Hi Val

thanks for the reminder, I thought I had done them all ;) now all done

Have a nice weekend

Ruth

**Comment by ValWood** [comment]
They are never ending. I keep finding more .....
