### ISSUE TITLE
Obsoletion request: GO:0070997 neuron death & children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24751]
Please provide as much information as you can:

* **GO term ID and Label**

- [ ] GO:0070997  neuron death
- [x] GO:0036475 neuron death in response to oxidative stress
- [ ] GO:1901214   regulation of neuron death
- [x] GO:1901215  negative regulation of neuron death
- [x] GO:1901216 positive regulation of neuron death

**Edited: additional terms to obsolete** 

- [x] GO:1903203 | regulation of oxidative stress-induced neuron death
- [x] GO:1903204 | negative regulation of oxidative stress-induced neuron death
- [x] GO:1903208 | negative regulation of hydrogen peroxide-induced neuron death
- [x] GO:1903223 | positive   regulation of oxidative stress-induced neuron death**

* **Reason for deprecation** Put an x in the appropriate box: 

 The reason for obsoletion is that this term often represents an assay, or a phenotype and not a GO process.

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

[GO:0051402](https://www.ebi.ac.uk/QuickGO/term/GO:0051402)    neuron apoptotic process

There is no "apoptotic neuron cell death" maybe this should be created first?

* **Are there annotations to this term?**
- How many EXP:

GO:0070997  neuron death
-- | --
+ | − | (15) | MGI
+ | − | (8) | RGD
+ | − | (2) | BHF-UCL

GO:0036475 neuron death in response to oxidative stress
-- | --
+ | − | (5) | MGI
+ | − | (1) | ARUK-UCL
+ | − | (1) | RGD

There are no annotations to the regulation terms

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

NO

* **Is this term in a subset? (check the AmiGO page for that term)**

NO

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology  ---   is parent of some terms but this will be removed on obsoletion
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***

- [x] create Annotation Review spreadsheet 
https://docs.google.com/spreadsheets/d/1QxcMlE5FVF9oAlMZmXDUduvu7DNhp7BGHo7K_ITUIf4/edit#gid=0

- [x] create annotation review ticket: 
https://github.com/geneontology/go-annotation/issues/4426

- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
GO:0036473 | cell death in response to oxidative stress | Never in Taxon | 4890 | Ascomycota
 but I guess this comes from the multicellular parentage?


[GO:0036473](https://www.ebi.ac.uk/QuickGO/term/GO:0036473)	cell death in response to oxidative stress	Never in Taxon	4890	Ascomycota

**Comment by ValWood** [comment]
Seems to be done @LiNiMGI  can you confirm for MGI, I see some are flagged as done but not others
Thanks!
val

**Comment by LiNiMGI** [comment]
@ValWood  MGI still ongoing, seems like MGI is not assigned. I found it through an transition email from Harold yesterday, will finish it today.

**Comment by ValWood** [comment]
also
neuron death in response to hydrogen peroxide
(no annotations, child of the oxidative stress term)

**Comment by ValWood** [comment]
@pgaudet  I will need your advice on this at some point. I need to obsolete some terms which have children which will be retained. I thought this would be easy (just remove the relations to the parents that will be obsoleted). In practice, I think some of these terms might be hard coded in logical definitions somewhere so it doesn't seem to be so easy. 
I restored  my attempt at this ticket and will go through it with you some time next week if that's oK> (Could also do later today if you are free)

**Comment by ValWood** [comment]
There are done
GO class direct
GO:0036475
GO:0070997

but some are not finished. Also I think I saw some regulation terms in Protege that do not appear to be listed, so need to double check these.

**Comment by ValWood** [comment]
Actually I think it is OK to go ahead, 
but need to check that these descendants
GO:1903204    negative regulation of oxidative stress-induced neuron death
GO:0036476    neuron death in response to hydrogen peroxide
GO:1903203    regulation of oxidative stress-induced neuron death
GO:1903223    positive regulation of oxidative stress-induced neuron death
GO:1903207    regulation of hydrogen peroxide-induced neuron death
GO:1903208    negative regulation of hydrogen peroxide-induced neuron death

a) are in another ticket
b) have no annotation
before proceeding

**Comment by pgaudet** [comment]
@ValWood I added the annotations to the terms above in the review ticket linked from here (https://github.com/geneontology/go-annotation/issues/4426)

**Comment by ValWood** [comment]
GO:1903203 | regulation of oxidative stress-induced neuron death
GO:1903204 | negative regulation of oxidative stress-induced neuron death
GO:1903208 | negative regulation of hydrogen peroxide-induced neuron death
GO:1903223 | positive regulation of oxidative stress-induced neuron death
were already in https://github.com/geneontology/go-ontology/issues/24751
so if you have done that ticket they don't need to be addressed here

**Comment by ValWood** [comment]
Corrected comment 
GO:1903203 | regulation of oxidative stress-induced neuron death
GO:1903204 | negative regulation of oxidative stress-induced neuron death
GO:1903208 | negative regulation of hydrogen peroxide-induced neuron death

were already in https://github.com/geneontology/go-ontology/issues/24652
so if you have done that ticket they don't need to be addressed here

**Comment by ValWood** [comment]
Still some to do @RLovering @slaulederkind @gthayman

Let me know how long you need for this so I can put a date to check back.
v

**Comment by ValWood** [comment]
Although assignees have been removed, so you might have already done it? I'm going by the spreadsheet.
v

**Comment by RLovering** [comment]
I still have 64 annotations to review. I have added a note 'on other sheet' for the oxidative etc annotations that are on another github ticket

**Comment by ValWood** [comment]
Looks like some of @RLovering  are still to do.
Check next week.

**Comment by RLovering** [comment]
Hi Val

sorry I have 63 annotations to check. I have done about 6 today, but probably need 2 weeks then if I don't get them done just delete them

Best

Ruth

**Comment by ValWood** [comment]
OK no hurry  I will look again  at the beginning of June.

**Comment by RLovering** [comment]
Hi Val

I think I have done all of these. However I also had to remove them from the AE field. This URL can be useful to find these:

https://www.ebi.ac.uk/QuickGO/annotations?extension=GO:0070997
If you change the GO term at the end then you can get all of the child terms

There are definately AEs  that RGD and I think Flybase need to correct, although maybe they have done these already

FYI I haven't edited the spreadsheet I just edited the records - but I think I got them all - well as many as QuickGO showed me.

Best

Ruth

**Comment by ValWood** [comment]
OK thanks Ruth. Do you mena these GO terms were used in extensions. We don't check that (I have been catching the PomBAse ones  in the erroro logsa after  the terms are obsoleted)

@pgaudet  maybe the script to identify the usage could also check annotation extensions?

**Comment by pgaudet** [comment]
I'll check with @kltm

**Comment by pgaudet** [comment]
This is now done
