### ISSUE TITLE
Add EC:2.3.1.255 xref to peptide alpha-N-acetyltransferase activity (GO:0004596)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24761]
I think EC:2.3.1.255 can be added as an xref to peptide alpha-N-acetyltransferase activity (GO:0004596)

id: GO:0004596
name: peptide alpha-N-acetyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: acetyl-CoA + peptide = CoA + N-alpha-acetylpeptide. This reaction is the acetylation of the N-terminal amino acid residue of a peptide or protein." [GOC:mah, PMID:30054468]
synonym: "acetyl-CoA:peptide alpha-N-acetyltransferase activity" EXACT []
synonym: "acetyl-CoA:peptide nalpha-acetyltransferase activity" EXACT []
synonym: "amino-terminal amino acid-acetylating enzyme activity" RELATED []
synonym: "beta-endorphin acetyltransferase activity" NARROW []
synonym: "N(alpha)-acetyltransferase activity" RELATED []
synonym: "nalpha-acetyltransferase activity" EXACT []
synonym: "NAT activity" RELATED []
synonym: "peptide acetyltransferase activity" RELATED []
synonym: "protein N-terminal acetyltransferase activity" EXACT []
xref: MetaCyc:PEPTIDE-ALPHA-N-ACETYLTRANSFERASE-RXN
xref: Reactome:R-HSA-6814090 "NatC acetylates ARFFRP1"
is_a: GO:0034212 ! peptide N-acetyltransferase activity

===

https://enzyme.expasy.org/EC/2.3.1.255

Accepted Name:
N-terminal amino-acid N(alpha)-acetyltransferase NatA.

Reaction catalysed:
acetyl-CoA + N-terminal glycyl-[protein] <=> CoA + H(+) + N-terminal N(alpha)-acetylglycyl-[protein]
acetyl-CoA + N-terminal L-alanyl-[protein] <=> CoA + H(+) + N-terminal N(alpha)-acetyl-L-alanyl-[protein]
acetyl-CoA + N-terminal L-seryl-[protein] <=> CoA + H(+) + N-terminal N(alpha)-acetyl-L-seryl-[protein]
acetyl-CoA + N-terminal L-valyl-[protein] <=> CoA + H(+) + N-terminal N(alpha)-acetyl-L-valyl-[protein]
acetyl-CoA + N-terminal L-cysteinyl-[protein] <=> CoA + H(+) + N-terminal N(alpha)-acetyl-L-cysteinyl-[protein]
acetyl-CoA + N-terminal L-threonyl-[protein] <=> CoA + H(+) + N-terminal N(alpha)-acetyl-L-threonyl-[protein]

Comments:
N-terminal-acetylases (NATs) catalyze the covalent attachment of an acetyl moiety from acetyl-CoA to the free alpha-amino group at the N-terminus of a protein.
This irreversible modification neutralizes the positive charge at the N-terminus and makes the N-terminal residue larger and more hydrophobic.
The NatA complex is found in all eukaryotic organisms, and specifically targets N-terminal Ala, Gly, Cys, Ser, Thr, and Val residues, that became available after removal of the initiator methionine.

**Comment by hdrabkin** [comment]
done
