### ISSUE TITLE
add xrefs to GO:0036307 23S rRNA (adenine(2030)-N(6))-methyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24772]
id: GO:0036307
name: 23S rRNA (adenine(2030)-N(6))-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + adenine(2030) in 23S rRNA = S-adenosyl-L-homocysteine + rRNA containing N(6)-methyladenine(2030) in 23S rRNA." [GOC:imk, PMID:22847818]
is_a: GO:0008988 ! rRNA (adenine-N6-)-methyltransferase activity

- [x] add xref EC:2.1.1.266 [23S rRNA (adenine(2030)-N(6))-methyltransferase]
- [x] add xref [RHEA:43736](https://www.rhea-db.org/rhea/43736)

**Comment by hdrabkin** [comment]
done
