### ISSUE TITLE
Tweaks to cytosine/cytidine methyltransferase terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24771]
id: GO:0106059
name: tRNA (cytidine 56-2'-O)-methyltransferase
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + cytidine56 in tRNA= S-adenosyl-L-homocysteine + 2'-O-methylcytidine56 in tRNA." [EC:2.1.1.206]
is_a: GO:0052666 ! tRNA (cytosine-2'-O-)-methyltransferase activity
- [x] add 'activity' to end of term name
- [x] add xref: EC 2.1.1.206 [tRNA (cytidine(56)-2'-O)-methyltransferase]
- [x] add xref: [RHEA:42968](https://www.rhea-db.org/rhea/42968)

==

id: GO:0106339
name: tRNA (cytidine 32-2'-O)-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + cytosine32 in tRNA= S-adenosyl-L-homocysteine + 2'-O-methylcytidine32 in tRNA." [PMID:25404562]
is_a: GO:0052666 ! tRNA (cytosine-2'-O-)-methyltransferase activity
- [x] maybe add xref EC 2.1.1.205 [tRNA (cytidine(32)/guanosine(34)-2'-O)-methyltransferase]?
- [x] maybe add xref [RHEA:42396](https://www.rhea-db.org/rhea/42396)?

==

id: GO:0016428
name: tRNA (cytosine-5-)-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + tRNA = S-adenosyl-L-homocysteine + tRNA containing 5-methylcytosine." [EC:2.1.1.29]
synonym: "S-adenosyl-L-methionine:tRNA (cytosine-5-)-methyltransferase activity" RELATED [EC:2.1.1.29]
synonym: "transfer ribonucleate cytosine 5-methyltransferase activity" RELATED [EC:2.1.1.29]
synonym: "transfer RNA cytosine 5-methyltransferase activity" RELATED [EC:2.1.1.29]
xref: Reactome:R-HSA-6782388 "NSUN2 methylates cytidine-34, cytidine-48 of unspliced tRNA(Leu)(CAA)"
xref: Reactome:R-HSA-6782419 "TRDMT1 (DNMT2) methylates cytidine-38 of tRNA(Asp)"
xref: Reactome:R-HSA-6785409 "NSUN2 methylates cytidine-48 and cytidine-49 of tRNA(Asp)(GUC)"
xref: Reactome:R-HSA-6785438 "NSUN2 methylates cytidine-40, cytidine-48, cytidine-49, cytidine-50 of tRNA(GLY)(GCC)"
xref: Reactome:R-HSA-8932765 "NSUN6 methylates cytidine-72 in tRNA(Cys) and tRNA(Thr)"
is_a: GO:0016427 ! tRNA (cytosine) methyltransferase activity
- [x] remove references to EC:2.1.1.29 (this is obsolete, transferred to [2.1.1.202], [2.1.1.203], [2.1.1.204]
- [x] maybe add xref EC 2.1.1.202 [multisite-specific tRNA:(cytosine-C(5))-methyltransferase]?

**Comment by hdrabkin** [comment]
Done; in the cases of the EC for GO:0106339 and GO:0016428, I made them 'related' xefs.  Same for RHEA for GO:0106339

**Comment by pgaudet** [comment]
Add RHEA:61468 to [tRNA (cytosine-5-)-methyltransferase activity](http://purl.obolibrary.org/obo/GO_0016428)

**Comment by pgaudet** [comment]
Fixed definition to Catalysis of the reaction: a cytidine in tRNA +  S-adenosyl-L-methionine = a 5-methylcytidine in tRNA + S-adenosyl-L-homocysteine + H+. This modification can occur on seversal residues, including cytidine(34), cytidine(40), cytidine(48), and cytidine(49).
