### ISSUE TITLE
Add RHEA to GO:0043813 phosphatidylinositol-3,5-bisphosphate 5-phosphatase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24773]
id: GO:0043813
name: phosphatidylinositol-3,5-bisphosphate 5-phosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: phosphatidylinositol-3,5-bisphosphate + H2O = phosphatidylinositol-3-phosphate + orthophosphate." [PMID:10806194, PMID:16607019]
synonym: "phosphatidylinositol 3,5-bisphosphate 5-phosphatase activity" EXACT []
xref: Reactome:R-HSA-1675836 "PI(3,5)P2 is dephosphorylated to PI3P by SYNJ at the plasma membrane"
xref: Reactome:R-HSA-1676005 "PI(3,5)P2 is dephosphorylated to PI3P by FIG4 at the Golgi membrane"
xref: Reactome:R-HSA-1676020 "PI(3,5)P2 is dephosphorylated to PI3P by FIG4 at the late endosome membrane"
xref: Reactome:R-HSA-1676174 "PI(3,5)P2 is dephosphorylated to PI3P by FIG4 at the early endosome membrane"
is_a: GO:0034595 ! phosphatidylinositol phosphate 5-phosphatase activity
is_a: GO:0106018 ! phosphatidylinositol-3,5-bisphosphate phosphatase activity

- [x] Add xref [RHEA:32955](https://www.rhea-db.org/rhea/32955)

**Comment by hdrabkin** [comment]
done
