### ISSUE TITLE
NTR: histone methyltransferase inhibitor activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24785]
Please provide as much information as you can: 

* **Suggested term label:**
histone methyltransferase inhibitor activity (It's H3K27 but that seems very specific? I'm annotating the methylase target protein in an extension)

* **Definition (free text)**
Binds to and stops, prevents or reduces the activity of histone methyltransferase, which catalyzes of the addition of a methyl group to histones, proteins complexed to DNA in chromatin and chromosomes

* **Reference, in format PMID:#######**
*  30923826

* **Gene product name and ID to be annotated to this term**
EZHIP

* **Parent term(s)**
* 
enzyme inhibitor activity
new? histone methyltransferase regulator activity 
~neg reg of histone methyltransferase activity~ will not add parent as  regulation of MF in BP are being obsoleted

**Comment by ValWood** [comment]
histone methyltransferase inhibitor activity GO180000

**Comment by ValWood** [comment]
@pgaudet  should I add this grouping term?
histone methyltransferase inhibitor activity

Note that although  "enzyme inhibitor activity" has an equivalence axion, none of the descendants do. This should be easy to add, but do you already  have design patterns for these?
