### ISSUE TITLE
Fix definition  GO:0016477 cell migration (was: Missing parent: GO:0001667 ameboidal-type cell migration)

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#24787]
* **GO term ID and label for which you request a new superclass**
GO:0001667 ameboidal-type cell migration has parent cell migration that is defined for multicellular organisms. However, Dictyostelium has ameboidal cell migration and I would either like to have a new term like the more simple or move the GO:0001667 under a different parent that is not multicellular.
* **New superclass (parent) suggested**
maybe move it under: GO:0048870 cell motility or add the new term "ameboidal cell migration" under cell motility.

* **Reference(s), if appropriate**
PMID: 17635933 and probably many more but need to check.

**Comment by ValWood** [comment]
This isn't under multicellular, so maybe this is fixed?

**Comment by pfey03** [comment]
GO:0016477 cell migration the parent is defined:
The controlled self-propelled movement of a cell from one site to a destination guided by molecular cues. Cell migration is a central process in the development and maintenance of multicellular organisms.
@ValWood Maybe this def needs to be changed then otherwise it's incorrect parent for ameboill-type cell migration.

**Comment by ValWood** [comment]
@pgaudet  how do you want to deal with this?

We could either make  GO:0016477 cell migration -> GO:0016477 cell migration in multicellular  organism tissue (with a better label), to fit the current definition, and make  it a sibling of [ameboidal-type cell migration]

OR we could relax the definition of "GO:0016477 cell migration" but it would not be able to be classified as a multicellular organismal process?

**Comment by pfey03** [comment]
Changing the def of Cell migration if possible would be the easiest and best solution

**Comment by pgaudet** [comment]
<img width="133" alt="image" src="https://user-images.githubusercontent.com/4782928/222498899-312cc96d-ab2f-430d-a7ec-54411621f130.png">

**Comment by pfey03** [comment]
@pgaudet Yes update the GO:0016477 cell migration def to not restrict to multicellular and then it will be fine. Send me the new def, once decided. Thanks!

**Comment by pgaudet** [comment]
I thought I should remove the second sentence "Cell migration is a central process in the development and maintenance of multicellular organisms." 

but now I see papers that talk about cell migration being a multicellular org process, such as https://pubmed.ncbi.nlm.nih.gov/33824176/
(and the wiki page cited in the term, https://en.wikipedia.org/wiki/Cell_migration) 

But the other part of the definition, "The controlled self-propelled movement of a cell from one site to a destination guided by molecular cues.", does  not exclude unicellular organisms (bacteria chemotax as well) - 

I just want to note that to me its' not clear why cell migration would be a multicellular organism process. If someone find an answer to that we can revert back the definiton (and remove the term from the prokaryote subset ;) 

Thanks, Pascale
