### ISSUE TITLE
NTR:  histone CENP-A methyltransferase activity 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24789]
Please provide as much information as you can: 

* **Suggested term label:**

histone CENP-A α-N-methyltransferase activity

* **Definition (free text)**
I'm unsure....but perhaps:

Catalysis of the reaction: S-adenosyl-L-methionine + (histone CENP-A)-α-N-amino acid= S-adenosyl-L-homocysteine +(histone CENP-A)-methyl-α-N-amino acid. Histone methylation generally occurs on either an arginine or a lysine residue, **but can also occur at the histone α-N amino acid, such as on a glycine after the initiator methionine is cleaved**

* **Reference, in format PMID:#######**
 26543159

* **Gene product name and ID to be annotated to this term**
* NTMT1 Q9BV86

* **Parent term(s)**

histone methyltransferase activity
new: protein α-N-methyltransferase activity?
(Human NRMT1 is the first α-N-methyltransferase identified in eukaryotes and methylates histone as well as nonhistone protein)

* **Any other information**
N terminus of CENP-A, a centromere-specific histone H3 variant, was shown to be trimethylated by NRMT1, an α-N-methyltransferase. This type of methylation has been proposed to prompt the phasing of CENP-A nucleosomes on centromeric α-satellite DNA ([Bailey et al. 2013](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4691888/#WUGAD270926C1)).

**Comment by Antonialock** [comment]
would appreciate it if someone could look at the paper and agree/disagree on specifying the "N-terminus" the paper does say the transferase has (N-terminal) protein targets other than histone CENP-A

α-N-methylations have been shown to occur in a wide range of proteins in both prokaryotes and eukaryotes. Human NRMT1 is the first α-N-methyltransferase identified in eukaryotes and methylates histone as well as nonhistone proteins. For example, in addition to CENP-A, the regulator of chromosome condensation 1 (RCC1), retinoblastoma protein, CENP-B, kelch-like protein 31, ribosomal protein L23a, myosin light chain 2, and myosin light chain 3 are all reported NRMT1 substrates ([Okada et al. 2007](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4691888/#WUGAD270926C12); [Tooley et al. 2010](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4691888/#WUGAD270926C14); [Bailey et al. 2013](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4691888/#WUGAD270926C1)). A sequence motif of “Xaa–Pro–Lys/Arg” (Xaa denotes small side chain amino acids) has been identified to be the recognition signature of NRMT1

**Comment by Antonialock** [comment]
there are some RHEA xrefed from the uniprot entry which might be helpful? but I can't see the glycine reaction in there so I might have misunderstood something.

 https://www.uniprot.org/uniprotkb/Q9BV86/entry

**Comment by pgaudet** [comment]
It seems this is not specific for histone? I would use GO:0071885 N-terminal protein N-methyltransferase activity, or do you think we need a histone-specific term? 

We do have a BP for the glycine N-terminal methylation (annotated to the same paper you cite), [N-terminal peptidyl-glycine methylation](http://amigo.geneontology.org/amigo/term/GO:0018013), this should be changed into a MF.

I dont think we need any new terms here - what do you think ?

**Comment by Antonialock** [comment]
is CENPA always single copy? (it is in yeast/human at least?) If so then I'm happy annotating target with annotation extension

**Comment by pgaudet** [comment]
Do you mean, to select the gene you will put in the extension?

**Comment by Antonialock** [comment]
yes

**Comment by ValWood** [comment]
There is only one CENP-A in human. I agree that this N-terminal modifiers  don't need per histone terms, and we should add as extensions.
