### ISSUE TITLE
Pombase slim term obsoleted- replacement

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24788]
GO:0055065   obsolete metal ion homeostasis
was obsoleted. Replace in PomBase slim with
GO:0098771   inorganic ion homeostasis

goslim_spombe

**Comment by ValWood** [comment]
Also adding
GO:0030643   intracellular phosphate ion homeostasis
to handle slim fall out

**Comment by ValWood** [comment]
I need to remove GO:0030643 intracellular phosphate ion homeostasis
it is covered by changing metal to GO:0098771 inorganic ion homeostasis

**Comment by pgaudet** [comment]
> GO:0098771 inorganic ion homeostasis

will be obsoleted - we are trying to split 'intracellular' and 'organism-level'. FOr unicellular I think you only need intracellular, I wouldn't change that .

**Comment by ValWood** [comment]
I need the term for
 GO:0098771 inorganic ion homeostasis

(generic ion homeostasis), there isn't an intracellular term for this yet....

**Comment by ValWood** [comment]
Anyway it's fine as it is, ignore
