### ISSUE TITLE
NTR: non-canonical inflammasome assembly

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#24798]
Hi GO,

I would need a bunch of terms related to the non-canonical inflammasome assembly.. A number of proteins are involved in the formation or inhibition of the non-canonical inflammasome assembly and I'd like to make some GO-CAM model for the non-canonical inflammasome.

Thanks

Sylvain

Term: non-canonical inflammasome complex assembly
Definition: The aggregation, arrangement and bonding together of a set of components to form the non-canonical inflammasome complex, at least composed of CASP4/Casp11 and PYCARD/ASC, occurring at the level of an individual cell.
Child of: GO:0140632 inflammasome complex assembly
PMID:22002608
PMID:26375259

Term: regulation of non-canonical inflammasome complex assembly
Definition: Any process that modulates the frequency, rate or extent of non-canonical inflammasome complex assembly.
child of GO:XXXXXXX non-canonical inflammasome complex assembly
PMID:22002608
PMID:26375259

Term: negative regulation of non-canonical inflammasome complex assembly
Definition: Any process that stops, prevents or reduces the frequency, rate or extent of non-canonical inflammasome complex assembly.
child of GO:XXXXXXX regulation of non-canonical inflammasome complex assembly
PMID:22002608
PMID:26375259

Term: positive regulation of non-canonical inflammasome complex assembly
Definition: Any process that activates or increases the frequency, rate or extent of non-canonical inflammasome complex assembly.
child of GO:XXXXXXX regulation of non-canonical inflammasome complex assembly
PMID:22002608
PMID:26375259

**Comment by pgaudet** [comment]
Hi @sylvainpoux 

Couple of points: 

1. We dont have the CC term 'non-canonical inflammosome', we need to first create this. Looking at PMID:33187725 this should be a sibling of 'inflammasome complex' and be defined as 'A cytosolic protein complex that is capable of activating caspase-4 and caspase-5. Note that casapse-4 is known as caspase-11 in mouse.'  It should also be 'capable of part of' some 'positive regulation of inflammatory response' 
2. Based on your comment, it looks like we only need the 'negative regulation of assembly' term for now; is this correct? 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi @pgaudet,

Many thanks, for the moment, I would limit this concept to CASP4, because I cannot find strong evidences for CASP5 in recent literature.

I would propose the following definition for the complex:

Term: non-canonical inflammasome complex
Definition: An inflammasome complex that consists of CASP4, PYCARD/ASC, and caspase-1. CASP4, known as caspase-11 in mouse, is the sensor of cytosolic lipopolysaccharide (LPS).
Child of GO:0061702 inflammasome complex

Thanks

Sylvain

**Comment by pgaudet** [comment]
Thanks for the quick reply. Just to confirm: inflammasome complex is "A cytosolic protein complex that is capable of activating caspase-1." (members are not mentioned, but caspase-1 doesn't seem to be part of it). Is that definition too narrow to include the non-canonical as a child? 

The paper I cited, PMID:33187725 mentions that the non-canonical inflammasome activates caps4 rather than casp-1. DO you have another reference then for a definition of the non-canonical inflammasome? 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
You are right, I made a stupid mistake. Thanks a lot for your vigilance!

Neither CASP1 nor PYCARD are involved in the non-canonical inflammasome (hence its name), I should have checked again.
Note that I made a GO-CAM model(http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A63a86a8600001653)

Term: non-canonical inflammasome complex
Definition: An inflammasome complex that consists of CASP4. CASP4, known as caspase-11 (Casp4) in mouse, is the sensor of cytosolic lipopolysaccharide (LPS) and directly activates Gasdermin-D (GSDMD).
Child of GO:0032991 protein-containing complex
Child of GO:0050729 positive regulation of inflammatory response

Sorry for the inconvenience

Sylvain

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160074
+name: non-canonical inflammasome complex
+namespace: cellular_component
+def: "An inflammasome complex that consists of CASP4. CASP4, known as caspase-11 (Casp4) in mouse, is the sensor of cytosolic lipopolysaccharide (LPS) and directly activates Gasdermin-D (GSDMD)." [PMID:33187725]
+is_a: GO:0032991 ! protein-containing complex
+relationship: capable_of_part_of GO:0050729 ! positive regulation of inflammatory response
+relationship: part_of GO:0005829 ! cytosol
+created_by: rynl
+creation_date: 2023-01-25T22:09:00Z
+
+[Term]
+id: GO:0160075
+name: non-canonical inflammasome complex assembly
+namespace: biological_process
+def: "The aggregation, arrangement and bonding together of a set of components to form a non-canonical inflammasome complex." [PMID: 27291964]
+intersection_of: GO:0065003 ! protein-containing complex assembly
+intersection_of: results_in_assembly_of GO:0160074 ! non-canonical inflammasome complex
+created_by: rynl
+creation_date: 2023-01-25T22:38:01Z
+
+[Term]
+id: GO:0160076
+name: negative regulation of non-canonical inflammasome complex assembly
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of non-canonical inflammasome complex assembly." [PMID:22002608, PMID:26375259]
+is_a: GO:0065007 ! biological regulation
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0160075 ! non-canonical inflammasome complex assembly
+created_by: rynl
+creation_date: 2023-01-25T23:10:56Z

**Comment by pgaudet** [comment]
Can we improve that definition? A complex can consist of a single protein. 

@sylvainpoux any suggestions? Minimally we can change 'consists' to 'contains'. 

Thanks, Pascale

**Comment by sylvainpoux** [comment]
Hi @raymond91125 and @pgaudet 

Thank you very much for your valuable input!

Does it sound better now?

non-canonical inflammasome complex
An inflammasome complex composed of CASP4, known as caspase-11 (Casp4) in mouse, which assembles upon cytosolic lipopolysaccharide-binding and directly activates Gasdermin-D (GSDMD)

**Comment by pgaudet** [comment]
Further fixed def to:

An inflammasome complex **containing** CASP4, known as caspase-11 (**Casp11**) in mouse, which assembles upon cytosolic lipopolysaccharide-binding and directly activates Gasdermin-D (GSDMD)

Thanks, Pascale
