### ISSUE TITLE
Missing parent: epigenetic regulation of gene expression

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24794]
* **GO term ID and label for which you request a new superclass**
GO:0040029  epigenetic regulation of gene expression

* **New superclass (parent) suggested**
GO:0006338 chromatin remodeling

* **Reference(s), if appropriate**

GO:0040029 states "A process that modulates the frequency, rate or extent of gene expression through chromatin remodelling" so it's odd not to have chromatin remodeling as a parent?
chromatin remodeling only mentions "active processes": "These changes allow DNA metabolic processes such as transcriptional regulation, DNA recombination, DNA repair, and DNA replication."

but heterochromatin organization is_a chromatin remodeling (and also "negative regulation of gene expression, epigenetic"

is there a reason for this relationship to not exist or is it missing?

**Comment by ValWood** [comment]
@ValWood following

**Comment by pgaudet** [comment]
epigenetic regulation of gene expression is currently 'part of' some 'chromatin organization' - I can move that to 'part of' 'chromatin remodeling'; however I dont think its should be is_a chromatin remodeling, as the regulation of gene expression is more than chromatin remodeling

**Comment by pgaudet** [comment]
Should it not be 
- epigenetic regulation of gene expression 'has part' some chromatin remodeling ? (although this relation is not super useful, since it's not visible in any tool)

**Comment by ValWood** [comment]
What are the other parts?

**Comment by pgaudet** [comment]
That's the thing - we typically dont have 'other parts' - 
for example dbTF has part DNA binding; but we dont explicitly describe the other part(s). If we wanted to describe this we could add something like adaptor activity (???) ie the rest is to participate to the recruitment of the polymerese, eventually... 

Do you think it's a problem to only have one 'part'?

**Comment by ValWood** [comment]
> Do you think it's a problem to only have one 'part'? 
Thats a question for @cmungall . I thought it was. I know that sometimes we have only had one has_part instantiated when we have known that another 'part' exists but we haven't been able to pin it down precisely.

However,   in my 'mental model ' of this process
epigenetic regulation of gene expression" (GO:0040029) precedes the actual _regulation_ of transcription

So I have

<img width="921" alt="Screenshot 2023-01-27 at 12 04 15" src="https://user-images.githubusercontent.com/7359272/215082319-3d699f51-49a2-4a23-b36f-bd64323baf88.png">

This is the intersection,
https://www.pombase.org/results/from/id/d26deb73-5e96-44ed-8465-a7cd7105dfd1
SAGA, and some of the modifiers are involved in both the  "epigenetic regulation of gene expression" (GO:0040029)"
and the subsequent "regulation of transcription. These are annotated to both terms.

I don't know if this is correct. INteredted what @colinlog  says...

**Comment by pgaudet** [comment]
With @colinlog, added parent as suggested : 
GO:0040029 epigenetic regulation of gene expression

is_a GO:0006338 chromatin remodeling
