### ISSUE TITLE
Missing parent: toll-like receptor signaling pathway

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#24819]
Make an is_a relationship between 
toll-like receptor signaling pathway GO:0002224 and cell surface receptor signaling pathway GO:0007166

<img width="569" alt="Screenshot 2023-01-27 at 10 54 30" src="https://user-images.githubusercontent.com/11865746/215069648-af3ac752-db59-4ae4-a33d-0e2f34a44430.png">

**Comment by pgaudet** [comment]
There are intracellular Toll receptors, see https://www.frontiersin.org/articles/10.3389/fimmu.2014.00461/full
> TLRs localize to the cell surface or to intracellular compartments such as the ER, endosome, lysosome, or endolysosome, and they recognize distinct or overlapping PAMPs such as lipid, lipoprotein, protein, and nucleic acid
