### ISSUE TITLE
NTR: [lipid droplet fusion]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#24814]
Hi GO,
I would need a new GO term related to lipid droplet fusion, an essentail process in adipocytes

Thanks

Sylvain

1)
lipid droplet fusion
Category: Process
The creation of a single lipid droplet from two or more lipid droplets. 
child of
GO:0034389 lipid droplet organization
GO:0048284 organelle fusion
PMID:34508658
PMID:36477540

2)
regulation of lipid droplet fusion
Any process that modulates the frequency, rate or extent of lipid droplet fusion
child of
lipid droplet fusion
PMID:36477540

3)
negative regulation of lipid droplet fusion
Any process that stops, prevents, or reduces the frequency, rate or extent of lipid droplet fusion
child of
regulation of lipid droplet fusion
PMID:36477540

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160077
+name: lipid droplet fusion
+def: "The process by which a single lipid droplet is created from the fusion of two or more lipid droplets." [PMID:34508658, PMID:36477540]
+comment: biological_process
+intersection_of: GO:0009987 ! cellular process
+intersection_of: results_in_fusion_of GO:0005811 ! lipid droplet
+created_by: rynl
+creation_date: 2023-01-31T00:34:32Z
+
+[Term]
+id: GO:0160078
+name: negative regulation of lipid droplet fusion
+namespace: biological_process
+def: "Any process that stops, prevents, or reduces the frequency, rate or extent of lipid droplet fusion." [PMID:36477540]
+is_a: GO:0065007 ! biological regulation
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0160077 ! lipid droplet fusion
+created_by: rynl
+creation_date: 2023-01-31T00:52:25Z

**Comment by raymond91125** [comment]
If "regulation of lipid droplet fusion" term is not yet needed for annotation, our current guideline is to not create the term at this time.
