### ISSUE TITLE
Obsoletion notice: regulation of transcription from RNA polymerase II promoter in response to DNA damage & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24817]
Dear all, 

The proposal has been made to obsolete 
GO:1990248 regulation of transcription from RNA polymerase II promoter in response to DNA damage
GO:0010767 regulation of transcription from RNA polymerase II promoter in response to UV-induced DNA damage
GO:0010768 negative regulation of transcription from RNA polymerase II promoter in response to UV-induced DNA damage

The reason for obsoletion is that these are precomposed terms that should be captured as GO-CAM models. 

There are 8 EXP annotations to these terms, see https://github.com/geneontology/go-annotation/issues/4425

BHF-UCL: 2
CGD: 1
FlyBase: 3
TAIR: 1
UniProt: 1

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/24817

Thanks, Pascale

**Comment by pgaudet** [comment]
+ negative regulation of transcription from RNA polymerase II promoter by transcription factor localization involved in response to DNA damage checkpoint signaling 1 pombase @ValWood

**Comment by ValWood** [comment]
negative regulation of transcription from RNA polymerase II promoter by transcription factor localization involved in response to DNA damage checkpoint signaling 1 pombase (DONE)
