### ISSUE TITLE
Obsoletion notice: GO:0070940 dephosphorylation of RNA polymerase II C-terminal domain

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24824]
Dear all, 

The proposal has been made to obsolete GO:0070940 dephosphorylation of RNA polymerase II C-terminal domain. The reason for obsoletion is that this represents a molecular function represented as a biological process.

Annotations:
There are 15 experimental annotations to this term by 
FlyBase - 2
TAIR - 1
SGD - 12

There are 2 InterPro2GO mappings to this term: InterPro:IPR039189 and InterPro:IPR039693
and 3 UniRules:  UniRule:UR001628777, UniRule:UR001419780 and UniRule:UR001253786

This term is not present in any subset.

Annotations can be viewed here: https://github.com/geneontology/go-annotation/issues/4428

Consider:  GO:0008420 RNA polymerase II CTD heptapeptide repeat phosphatase activity

Any comments can be  added to the issue: 
Unless objections are received by  February 3rd, we will assume that you agree to this change.

Thanks, 

The GO-Ontology Editors

**Comment by sarach06** [comment]
Dear Pascale,
Thank you very much for this. I have removed GO:0070940 from both entries, which already had GO:0008420 link to them. This will be visible in the next release, InterPro 93.0.
Best wishes,
Sara
