### ISSUE TITLE
GO:0050101, EC 3.5.1.61 has been transferred to EC 4.3.3.8

### ISSUE THREAD

**Issue by kaxelsen** [geneontology/go-ontology#24852]
EC 3.5.1.61 linked to GO:0070579 has now been transferred to EC 4.3.3.8. The new EC number is linked to a different Rhea reaction, RHEA:75355. The transfer will be public in release 2023_02 scheduled for April 26.

RHEA:75355  H2O + L-mimosine = 3-hydroxy-4H-pyrid-4-one + NH4+ + pyruvate

**Comment by hdrabkin** [comment]
Needed to change parent to amine-lyase activity (EC:4.3.3.-) to reflect EC (previous parent 3.5.1.-)
