### ISSUE TITLE
P-type potassium:proton exporter activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24853]
Unlike mammals, fungi may pump potassium out of cells, as they are sometimes exposed to very high K+ environments (living on lysed plant matter etc)
An example of this is pombe cta3 11932440 and S. occidentalis ENA2 9430707 (mainly IMP and complementation experiments, no hardcore biochemistry unfortunately)

Currently there is no MF for the exporting activity
the def for **P-type potassium transmembrane transporter activity** states
_Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + K+(out) = ADP + phosphate + K+(in)._ 

This is appropriate for mammalian transporters e.g. ATP4A
The gastric hydrogen potassium ATPase or H+/K+ ATPase is the proton pump of the stomach. It exchanges potassium from the intestinal lumen  with cytoplasmic hydronium

it also looks appropriate for bacteria e.g. kdpC
Part of the high-affinity ATP-driven potassium transport (or Kdp) system, which catalyzes the hydrolysis of ATP coupled with the electrogenic transport of potassium into the cytoplasm 

https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0008556&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

but not for the fungal exporting atpase (plant may also have this transporter)

there is a p-type sodium exporter  term: GO:0008554 P-type sodium transporter activity

**Can we have a term for the potassium exporter a la GO:0008554?**

I asked RHEA for advise and Kristian replied:

_GO:0008556 and RHEA:16777 describing a K+ importer is definitely not suitable
to use for a K+ exporter, so you should ask for a new GO term to cover your
activity. I will look at the evidence for CTA3 to see if it is well enough
characterised to create a new reaction. If I do create the reaction, it will
probably not include H+ counter transport since this has actually not been
shown it is only plausible theory.

I might take a little while before I can look at this issue, so don't wait for
the reaction._

@ValWood

**Comment by Antonialock** [comment]
Rhea created this reaction :

RHEA:75815 ATP + H2O + K+(in) = ADP + H+ + K+(out) + phosphate

**Comment by pgaudet** [comment]
Hi @Antonialock 

Right now we do have some 'efflux' and 'influx' MF terms, but these are redundant with BPs. Right now I would suggest using 'MF GO:0008900 P-type potassium:proton transporter activity' + BP GO:0097623 potassium ion export across plasma membrane (and maybe even GO:0030007 'intracellular potassium ion homeostasis'). 

Does that work for you? Or do you think the direction of the transport belongs in the MF?

**Comment by pgaudet** [comment]
ping @Antonialock

**Comment by Antonialock** [comment]
Thanks I swapped GO:0015079 with GO:0008900, I had already annotated to  GO:0097623

I don't think we need the direction in the MF if it is in the BP.
