### ISSUE TITLE
GO:0047626, EC number has been transferred and Rhea mapping has changed

### ISSUE THREAD

**Issue by kaxelsen** [geneontology/go-ontology#24855]
EC 3.3.1.2 has been transferred several times and has now landed at EC 4.4.1.42. The new EC number is linked to RHEA:21932 S-adenosyl-L-methionine = L-homoserine lactone + S-methyl-5'-thioadenosine 

The transfer and new mapping will become public in release 2023_02 scheduled for April 26.

**Comment by hdrabkin** [comment]
Hi @kaxelsen 
RHEA:21932 appears to be aalready ssociated with GO:0047625 adenosylmethionine cyclotransferase activity, and
 EC:2.5.1.4

RHEA:21932 is S-adenosyl-L-methionine = homoserine lactone + S-methyl-5'-thioadenosine

However, 
GO:0047625 adenosylmethionine cyclotransferase activity reaction is defined as 
S-adenosyl-L-methionine(1+) = S-methyl-5'-thioadenosine + homoserine lactone.
It's EC is defined as ' S-adenosyl-L-methionine <=> homoserine lactone + S-methyl-5'-thioadenosine

Are these two terms actually identical? or is  EC:2.5.1.4 incorrectly assigned? (note parent EC2.5.1 vs EC:4.4.1).

**Comment by kaxelsen** [comment]
Yes, I forgot to add that EC 2.5.1.4 also has been transferred to EC 4.4.1.42. I missed the mapping from RHEA:21932 to the GO term.

**Comment by hdrabkin** [comment]
So then these two GO terms are actually the same and should be merged?

**Comment by pgaudet** [comment]
Done in #25361
