### ISSUE TITLE
NTR:  histone H4K91 ubiquitin ligase activity 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24861]
Please provide as much information as you can: 

* **Suggested term label:**
histone H4K91 ubiquitin ligase activity 

* **Definition (free text)**

Catalysis of the transfer of a ubiquitin molecule to histone 4 at the lysine-91 residue. 

* **Reference, in format PMID:#######**

19818714

* **Gene product name and ID to be annotated to this term**

Q8TDB6 DTX3L

* **Parent term(s)**

GO:0140852

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141000
+name: histone H4K91 ubiquitin ligase activity
+namespace: molecular_function
+def: "Catalysis of the transfer of a ubiquitin molecule to histone 4 at the lysine-91 residue." [PMID:19818714]
+synonym: "histone H4-K91 ubiquitin ligase activity" EXACT []
+synonym: "histone ubiquitin ligase activity (H4-K91 specific)" EXACT []
+is_a: GO:0140852 ! histone ubiquitin ligase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24861 xsd:anyURI
+created_by: pg
+creation_date: 2023-02-28T13:00:50Z
