### ISSUE TITLE
NTR:  histone H3K4 trimethyltransferase activity 

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24866]
Please provide as much information as you can: 

* **Suggested term label:**

histone H3K4 trimethyltransferase activity

* **Definition (free text)**
Catalysis of the reaction: L-lysyl4-[histone H3] + 3 S-adenosyl-L-methionine = 2 H+ + N6,N6-trimethyl-L-lysyl4-[histone H3] + 3 S-adenosyl-L-homocysteine. This reaction is the successive addition of three methyl groups to the unmethylated lysine residue at position 4 of histone H3, producing histone ~H3K4me2~. **H3K4me3**

* **Reference, in format PMID:#######**
18375658

* **Gene product name and ID to be annotated to this term**
Q9C5X4 ATX1 (plant)

* **Parent term(s)**
GO:0042800

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140999
+name: histone H3K4 trimethyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-lysyl4-[histone H3] + 3 S-adenosyl-L-methionine = 2 H+ + N6,N6-trimethyl-L-lysyl4-[histone H3] + 3 S-adenosyl-L-homocysteine. This reaction is the successive addition of three methyl groups to the unmethylated lysine residue at position 4 of histone H3, producing histone H3K4me3." [PMID:18375658, RHEA:60260]
+synonym: "histone H3-K4 trimethylation" BROAD []
+synonym: "histone H3K4 trimethylase activity" EXACT []
+synonym: "histone H3K4 trimethylation" BROAD []
+synonym: "histone lysine N-trimethyltransferase activity (H3-K4 specific)" EXACT []
+xref: EC:2.1.1.354
+xref: RHEA:60260
+is_a: GO:0042800 ! histone H3K4 methyltransferase activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/22588 xsd:anyURI
+created_by: pg
+creation_date: 2023-02-28T12:52:48Z

**Comment by pgaudet** [comment]
Moved cross references 
EC:2.1.1.354 and  RHEA:60260 from parent term GO:0042800 histone H3K4 methyltransferase activity, which is the grouping term for the mono, di and trimethyl transferase. We didn't have a term for the trimethyl transferase.
