### ISSUE TITLE
NTR: [Stalled ribosome sensor activity]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#24865]
Hi GO,

I would need a term to describe proteins that sense stalled ribosomes. 2 proteins have now been identified that directly sense stalled ribosomes and trigger a response (MAP3K20 and GCN1)

Thanks

Sylvain

Name: Stalled ribosome sensor activity
Category: Function
Definition: A molecule that recognizes stalled ribosomes and initiates a signalling response.
Child of GO:0043022 ribosome binding
PMID:32610081
PMID:32289254
PMID:36638793

**Comment by sylvainpoux** [comment]
Hi @edwong57,

Any news on this request? I discussed with Paul Thomas and Pascale and we agreed to create this term (although we would like to represent these sensors in a different way in the future)  

Thanks

Sylvain

**Comment by edwong57** [comment]
@sylvainpoux, I'll work on it today.
