### ISSUE TITLE
histone H3R3 demethylase activity oddity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24868]
The annotations and synonyms of
histone H3R3 demethylase activity 
looks odd

synonym: histone demethylase activity (**H4**-R3 specific)

4 EXP annotations

JMJ20 Q67ZB6 : H4R3 demethylase
JMJD6 Q6NYC1 : H4R3 demethylase
lid Q9VMJ7 : H3K4 demethylase

**Comment by pgaudet** [comment]
Thanks for pointing that out @Antonialock 
In fact this used to be H4R3, see https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0033749#term=history

I made y typo when I updated the term here https://github.com/geneontology/go-ontology/issues/21089
