### ISSUE TITLE
ontology build failing the pipeline

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#24863]
The error reported is:

```
11:33:58  2023-02-02 19:33:58,017 ERROR (OWLAPIOwl2Obo:1064) Duplicate clause 'alt_id( GO:0007609)' generated in frame: GO:0009591
```

**Comment by balhoff** [comment]
These terms were merged in 2015: #1203

I looked at the full log; the actual error is:

```
 ERROR: definition-lacks-dbxref: GO:0050101
```

**Comment by balhoff** [comment]
The term looks fine in the edit file:

```
[Term]
id: GO:0050101
name: mimosinase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-mimosine + H2O = 3-hydroxy-4H-pyrid-4-one + L-serine." [RHEA:75355]
synonym: "mimosine amidohydrolase activity" RELATED []
xref: EC:4.3.3.8
xref: KEGG_REACTION:R04350
xref: MetaCyc:MIMOSINASE-RXN
xref: RHEA:75355
is_a: GO:0016843 ! amine-lyase activity
property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24852 xsd:anyURI
```

**Comment by pgaudet** [comment]
Is it still failing? 

There was a bad xref tag, that Harold fixed  
Also, I removed GOC:curators, since we have another source for the reference: 
https://github.com/geneontology/go-ontology/pull/24858/commits/20344e68a6a3dbc9b5ad1d755f0651e242ba206b

**Comment by balhoff** [comment]
I think it is still failing, but maybe it's something to do with a lag in the pipeline that we still may have. @kltm?

**Comment by balhoff** [comment]
@pgaudet I figured it out. We have a step that filters out unreleased/unknown Rhea IDs:

```
2023.02.03 02:58:26 [WARN] ammonite.$file.$up.util.filter$minusrhea$minusxrefs.$anonfun.applyOrElse:79:20 - No such Rhea identifier, filtering definition xref: RHEA:75355
```

That leaves the definition with no xref after that one is removed. Is there something that can be added?

**Comment by pgaudet** [comment]
ah I see, this is why Harold had added GOC:curators

I'll add that back.

**Comment by balhoff** [comment]
Thanks it worked!
