### ISSUE TITLE
NTR: multicellular organismal-level zinc ion homeostasis ?

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24879]
Please provide as much information as you can: 

I'm a bit unsure if HIZR-1 fits under the standard def of 'organismal level homeostasis, but is seems like an organismal level process even though HIZR-1 acts on an intracellular level.

The protein is expressed in intestinal cells, and senses absorption of zinc. It stimulates secretion into the intestinal lumen - and I suppose this promotes organismal excretion via defecation?

should this be annotated to both intracellular and  multicellular organismal-level zinc ion homeostasis?

_"Here we describe a novel Caenorhabditis elegans nuclear receptor, HIZR-1, that is a high zinc sensor in an animal and the master regulator of high zinc homeostasis. The essential micronutrient zinc acts as a HIZR-1 ligand, and activated HIZR-1 increases transcription of genes that promote zinc efflux and storage. "_

![image](https://user-images.githubusercontent.com/12727506/216954740-cfbe58e1-0386-4d33-ba90-f4f1b6789189.png)
_B. Molecular model. Dietary zinc (Z) enters intestinal cells, binds the LBD of HIZR-1 and promotes nuclear accumulation, HZA enhancer binding, and transcriptional activation. Increased levels of CDF-2 and TTM-1B promote zinc detoxification by sequestration in lysosome-related organelles and excretion into the intestinal lumen, respectively._

* **Suggested term label:**
multicellular organismal-level zinc ion homeostasis

* **Reference, in format PMID:#######**
28095401

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5240932/

**Comment by raymond91125** [comment]
hizr-1 is clearly involved in GO:0006882 intracellular zinc ion homeostasis but there does not seem to be evidence that it is part of a multicellular organismal-level zinc ion homeostasis process, albeit that it may be. Therefore we may not need to create the new term at this instance.

**Comment by pgaudet** [comment]
Hi @Antonialock 

Looking at the diagram here, this pathway is about the intracellular zinc homeostasis. The fact that it's eliminated in the intestinal lumen doesn't mean that this is regulating the level of zinc in the intestine. 

Does that make sense? 

Thanks, Pascale

**Comment by Antonialock** [comment]
Yes this was kind of what I was unsure about. I assumed it had to do with
the whole organismal level of zinc (since its a gut process, and I assume
all intestinal cells may make this decision depending on dietary levels of
zinc) but I see it’s kind of executed at a cellular level. I can annotate
to the intracellular level just wanted a second opinion thanks

**Comment by raymond91125** [comment]
Thanks!
