### ISSUE TITLE
Textual definition update: programmed cell death involved in cell development

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24884]
the def for  programmed cell death involved in cell development looks odd, it specifies "its" which would refer to the cell that is dying, rather than the organism?

* **GO term ID and label for which you request a definition update**
programmed cell death involved in cell development

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**

 The activation of endogenous cellular processes that result in the death of a cell as part of ~its~ development. 

also change parentage to include 
multicellular organismal process ?

**Comment by raymond91125** [comment]
Closing the issue. Please reopen if there are more comments. Thanks.
