### ISSUE TITLE
NTR - metabolism: [S-adenosyl-L-methionine:S-adenosyl-L-homocysteine antiporter activity]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#24887]
_Please provide as much information as you can:_ 

* **Suggested term label:**
S-adenosyl-L-methionine:S-adenosyl-L-homocysteine antiporter activity

* **ChEBI ID and label of the substance:**
[CHEBI:57856](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=57856)
[CHEBI:59789](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=59789)

* **Definition (free text)**
Catalysis of the reaction: S-adenosyl-L-homocysteine(out) + S-adenosyl-L-methionine(in) = S-adenosyl-L-homocysteine(in) + S-adenosyl-L-methionine(out).

* **Reference, in format PMID:#######**
PubMed:14674884
PMID:34375635
* **Gene product name and ID to be annotated to this term**
SLC25A26
* **Parent term(s)**
GO:0015297  antiporter activity
GO:0000095 S-adenosyl-L-methionine transmembrane transporter activity
* **Synonym(s) (please specify, EXACT, BROAD, NARROW or RELATED)**
_Other than the standard synonyms below_

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Cross-references**
* MetaCyc or KEGG pathways, can also provide Wikipedia or other links.
Not yet public: 
Reaction=S-adenosyl-L-homocysteine(out) + S-adenosyl-L-methionine(in) = S-adenosyl-L-homocysteine(in) + S-adenosyl-L-methionine(out) [Rhea:75479]

* **Any other information**

----

* **FOR ONTOLOGY EDITOR**

* **Logical definition**
* *  **substance metabolic process:**
'metabolic process'
 and ('has primary input or output' some [substance]
* * **substance biosynthetic process:**
'biosynthetic process'
 and ('has primary output' some [substance].
* * **substance catabolic process:**
'catabolic process'
 and ('has primary output' some [substance] 

* **Standard synonyms**
* *  **substance metabolic process:**
* * * EXACT: substance metabolism
* * **substance biosynthetic process:** 
* * * EXACT: substance anabolism
* * * EXACT: substance biosynthesis
* * * EXACT: substance formation
* * * EXACT: substance synthesis

* * **substance catabolic process:**    
* * * EXACT: substance breakdown
* * * EXACT: substance catabolism
* * * EXACT: substance degradation

**Comment by ValWood** [comment]
Added with logical def

'antiporter activity'
 and ('has primary input' some 'S-adenosyl-L-homocysteine zwitterion')
 and ('has primary input' some 'S-adenosyl-L-methionine zwitterion')

For db_xrefs I added Rhea:75479
If you can provide KEGG, MetaCyc etc I will add them later.

**Comment by lbreuza** [comment]
Hi Val, I could not find them.
