### ISSUE TITLE
adenosine deaminase EC/Rhea xrefs to add

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24880]
tRNA-specific adenosine-34 deaminase activity GO:0052717
+ EC:3.5.4.33     tRNA(adenine(34)) deaminase
+ RHEA:43168

tRNA-specific adenosine-37 deaminase activity	GO:0043829
+ EC:3.5.4.34     tRNA(Ala)(adenine(37)) deaminase
+ RHEA:50968

double-stranded RNA adenosine deaminase activity GO:0003726
+ EC:3.5.4.37     double-stranded RNA adenine deaminase
+ RHEA:10120

**Comment by hdrabkin** [comment]
Done

**Comment by sjm41** [comment]
Thanks Harold!
