### ISSUE TITLE
Missing parent: viral process

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24888]
* **GO term ID and label for which you request a new superclass**
viral process

A multi-organism process in which a virus is a participant. The other participant is the host. Includes infection of a host cell, replication of the viral genome, and assembly of progeny virus particles. In some cases the viral genetic material may integrate into the host genome and only subsequently, under particular circumstances, 'complete' its life cycle. 

* **New superclass (parent) suggested**
is there any reason this term is not under
biological process involved in symbiotic interaction
?

**Comment by raymond91125** [comment]
It was moved out of symbiotic interaction. https://github.com/geneontology/go-ontology/issues/20084

**Comment by pgaudet** [comment]
> is there any reason this term is not under biological process involved in symbiotic interaction

The reason is that not every viral process participate in the interaction with the host (for example viral genome replication only concerns the virus)
