### ISSUE TITLE
GO:1990699 palmitoleyl hydrolase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24890]
id: GO:1990699
name: palmitoleyl hydrolase activity
namespace: molecular_function
def: "Catalysis of a hydrolase reaction that removes a palmitoleyl moiety, a 16-carbon monounsaturated fatty acid (C16:1), from some substrate." [PMID:25731175]
is_a: GO:0052689 ! carboxylic ester hydrolase activity

All annotations to this term appear to be to 'Notum' orthologs, and the given reference PMID:25731175 specifies a Wnt protein as the substrate.

The GO term appears to correspond to the following EC, though EC has a tighter definition:
https://enzyme.expasy.org/EC/3.1.1.98
Entry: EC:3.1.1.98
Accepted Name: [Wnt protein] O-palmitoleoyl-L-serine hydrolase.
Alt name: Notum.
Reaction: [Wnt protein]-O-(9Z)-hexadecenoyl-L-serine + H2O <=> (9Z)-hexadecenoate + [Wnt protein]-L-serine + H(+)
Comments: The enzyme removes the palmitoleate modification that is introduced to specific L-serine residues in Wnt proteins

This is [RHEA:45340](https://www.rhea-db.org/rhea/45340)

I guess we could keep the GO term as it is and add the EC/RHEA as a narrow xref?  Or could make the GO term match the EC/RHEA definition and make them exact xrefs?

**Comment by hdrabkin** [comment]
I imagine when the term was made, the ' from some substrate.' was used assuming maybe there might be other protein substrates besides Wnt protein yet to be found? 
Noting EC AND RHEA specify Wnt as substrate. , I'm inclined to tweak the def

**Comment by sjm41** [comment]
That works for me. Guess you should tweak the name too?

**Comment by ukemi** [comment]
I think this activity also works on things like Ras to regulate its association with the membrane. You should check that.

**Comment by hdrabkin** [comment]
I was going to say, but  the term name seems very generic. ; if @ukemi is correct, then the xrefs will need to be narrow

**Comment by ukemi** [comment]
PMID: 21255728?

**Comment by hdrabkin** [comment]
FKBP12? looks like most existing annotations to cis-trans isomeraization
'promoting depalmitoylation through cis-trans isomerization of a peptidyl-prolyl bond in proximity to the palmitoylated cysteines; ; doesn't seem to actually be the activity that does the removal of the palmitoyl group?

**Comment by ukemi** [comment]
But I think the paper indicates the activity exists.

**Comment by ukemi** [comment]
Good point @deustp01. I missed the distinction.

**Comment by hdrabkin** [comment]
So maybe I'll just make the xrefs narrow match and leave term name as is.

**Comment by sjm41** [comment]
Yes, that seems the simplest thing to do for now! Thanks.

**Comment by hdrabkin** [comment]
Done
