### ISSUE TITLE
Fix transferred EC

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24905]
These 3 terms are mapped to EC:[5.4.2.1](https://enzyme.expasy.org/EC/5.4.2.1), now mapped to [5.4.2.11](https://enzyme.expasy.org/EC/5.4.2.11) and [5.4.2.12](https://enzyme.expasy.org/EC/5.4.2.12)

GO:0004619 phosphoglycerate mutase activity 
GO:0046537 2,3-bisphosphoglycerate-independent phosphoglycerate mutase activity 
GO:0046538 2,3-bisphosphoglycerate-dependent phosphoglycerate mutase activity

**Comment by pgaudet** [comment]
5.4.2.11  is phosphoglycerate mutase (2,3-diphosphoglycerate-dependent) GO:0046538 2,3-bisphosphoglycerate-dependent phosphoglycerate mutase activity
5.4.2.12  is phosphoglycerate mutase (2,3-diphosphoglycerate-independent) GO:0046537 2,3-bisphosphoglycerate-independent phosphoglycerate mutase activity


- kept mapping of RHEA [RHEA:15901](https://www.rhea-db.org/rhea/15901) on the parent GO:0004619 phosphoglycerate mutase activity since it links to both ECs, 
- mapped GO:0046538 2,3-bisphosphoglycerate-dependent phosphoglycerate mutase activity to [RHEA:21904](https://www.rhea-db.org/rhea/21904) since it only links to EC:5.4.2.11

**Comment by pgaudet** [comment]
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/4782928/218433505-df084028-70a7-4c79-b33d-4ebdf16f5224.png">

**Comment by pgaudet** [comment]
After discussion with @kaxelsen : 

He will remove EC:5.4.2.11 from [RHEA:21904](https://www.rhea-db.org/rhea/21904) and check whether RHEA:21904 (which *does* correspond to GO:0046538 really exists, as this reaction was removed from MetaCyc and EC.

**Comment by pgaudet** [comment]
Also, removed EC:3.1.3.80 from GO:0034416 bisphosphoglycerate phosphatase activity since this reaction descibes specifically the child with the 2-phosphoglycerate product, ie GO:0034417 'bisphosphoglycerate 3-phosphatase activity'

**Comment by pgaudet** [comment]
Next Action Item is for @kaxelsen  - to figure out whether RHEA:21904  (2R)-2,3-bisphosphoglycerate +   H2O =   (2R)-3-phosphoglycerate +   phosphate exists; if not, we'll obsolete  GO:0004083 bisphosphoglycerate 2-phosphatase activity

**Comment by pgaudet** [comment]
@kaxelsen looked at the evidence and has decided to obsolete RHEA:21904. I will remove it from GO.

**Comment by pgaudet** [comment]
I removed the 2 EXP annotations to GO:0004083. Ready to obsolete - no mappings, not present in any subsets.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0004083 bisphosphoglycerate 2-phosphatase activity'. The reason for obsoletion is that after review of the evidence by the RHEA team (PMID: 18413611), this activity is not believed to exist. There are no more annotations or mappings to this term; this term is not present in any subsets. 

You can comment on the ticket: 
https://github.com/geneontology/go-ontology/issues/24905

Thanks, Pascale

**Comment by pgaudet** [comment]
@kaxelsen 

Is it correct that there is no more difference between 

GO:0034417 'bisphosphoglycerate 3-phosphatase activity' (RHEA:27381/EC:3.1.3.80) from its parent GO:0034416 'bisphosphoglycerate phosphatase activity', which has no cross references ?

**Comment by kaxelsen** [comment]
> @kaxelsen
> 
> Is it correct that there is no more difference between
> 
> GO:0034417 'bisphosphoglycerate 3-phosphatase activity' (RHEA:27381/EC:3.1.3.80) from its parent GO:0034416 'bisphosphoglycerate phosphatase activity', which has no cross references ?

Yes, it is correct. As we have determined that "bisphosphoglycerate 2-phosphatase activity" does not exist, there is only "bisphosphoglycerate 3-phosphatase activity" left.
