### ISSUE TITLE
Shouln't phagocytosis be is_a endocytosis? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24907]
GO:0006909 phagocytosis: A vesicle-mediated transport process that results in the engulfment of external particulate material by phagocytes and their delivery to the lysosome. The particles are initially contained within phagocytic vacuoles (phagosomes), which then fuse with primary lysosomes to effect digestion of the particles.

GO:0006897 endocytosis: A vesicle-mediated transport process in which cells take up external materials or membrane constituents by the invagination of a small region of the plasma membrane to form a new membrane-bounded vesicle.

but these are siblings: 

<img width="246" alt="image" src="https://user-images.githubusercontent.com/4782928/218516537-8147306d-9455-4e3b-9dfe-9869b6feca47.png">

**Comment by addiehl** [comment]
I think this is a question of mechanism.  Phagocytosis does not rely on invagination of a small region of the plasma membrane, but rather a much larger region of the plasma membrane.

**Comment by addiehl** [comment]
[Difference Between Endocytosis and Phagocytosis](https://www.differencebetween.com/difference-between-endocytosis-and-vs-phagocytosis/)

**Comment by raymond91125** [comment]
That article also states: "Endocytosis is of three categories. Among them, phagocytosis and pinocytosis are the two most common types. Moreover, phagocytosis is a form of endocytosis."

**Comment by raymond91125** [comment]
We probably should remove the "small region" part of the definition.
New definition: A vesicle-mediated transport process in which cells take up external materials or membrane constituents by the invagination of a part of the plasma membrane to form a new membrane-bounded vesicle.
Add a reference [https://en.wikipedia.org/wiki/Endocytosis].
Then make phagocytosis a sub-type of endocytosis. Pinocytosis and receptor-mediated endocytosis are already types of endocytosis.

**Comment by addiehl** [comment]
I am happy with the definition change of 'endocytosis' if this change is going to be made.  I would also point out (as I thought I remembered), that 'phagocytosis' was a child of 'endocytosis' until 2018-12-25, per [QuickGO](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0006909#term=history), when its definition was changed and it was elevated to be a sibling of 'endocytosis'.

You might want to review **location of 'phagocytosis' in the ontology** #16576 and PR #16824 and hear back from @RLovering and @ukemi prior to making these changes. It's not a good look for GO to be flippy-floppy on these basic cell biology classes.

**Comment by RLovering** [comment]
Hi
Looking at the location of 'phagocytosis' in the ontology https://github.com/geneontology/go-ontology/issues/16576 ticket Alex identified. I think the point is that the term phagocytosis includes the fusion with a lysosome and that the term endocytosis does not. 
To me I think that GO:0006911 phagocytosis, engulfment is correctly placed as an is_a child of GO:0006897 endocytosis
And that some of the child terms of GO:0006909 phagocytosis
eg GO:0001845 phagolysosome assembly should not be child terms of endocytosis.

Although then I wonder if  GO:0001845 phagolysosome assembly should be a grandchild of GO:0016192 vesicle-mediated transport

Glad I don't do ontologies ;)

**Comment by ukemi** [comment]
Isn't endocytosis also used for recycling neurotransmitters? In that case, I don't think there is lysosomal fusion.

**Comment by pgaudet** [comment]
Hi @raymond91125 

I think this is exactly the issue. Can we not fix the definitions of all the terms to reflect that the end is at the intracellular vesicle formation? Looking quickly I dont think we'd need to move any terms, just update definitions. Does this sound right ? 

Thanks, Pascale

**Comment by ukemi** [comment]
I don't think the definition says that it ends with it, it just says what is part of the process to make it necessary and sufficient.
"A vesicle-mediated transport process in which cells take up external materials or membrane constituents by the invagination of a small region of the plasma membrane to form a new membrane-bounded vesicle. "

**Comment by pgaudet** [comment]
that's good - we only need to change the definition of children that encompass steps after that, then, such as phagocytosis? (other children also need to be checked)

**Comment by raymond91125** [comment]
I am confused. @ukemi I thought the supporting argument for moving phagocytosis out from under endocytosis per https://github.com/geneontology/go-ontology/issues/16576 is about phagocytosis extending beyond generating a new vesicle.
@pgaudet Not just the definition, phagolysosome assembly is presently part_of phagocytosis. I need to survey more.

**Comment by raymond91125** [comment]
In ontology editor meeting <https://wiki.geneontology.org/Ontology_meeting_2023-02-27>, we decided that it's better to follow the field consensus (e.g. that in Wikipedia) that phagocytosis is a type of endocytosis. Perhaps there was a conflation between the broad term endocytosis and receptor-mediated endocytosis that lead to the idea that 'endocytosis' is distinct from phagocytosis. Furthermore, the fact that phagocytosis has a part phagolysosome assembly does not contradict the sub-type relationship between phagocytosis and endocytosis.

**Comment by RLovering** [comment]
Hi 
I am glad that this decision has been made. 

However, I disagree with the suggestion that 'phagocytosis has a part phagolysosome assembly does not contradict the sub-type relationship between phagocytosis and endocytosis.'

The endocytosis definition: A vesicle-mediated transport process in which cells take up external materials or membrane constituents by the invagination of a part of the plasma membrane to form a new membrane-bounded vesicle. 

**Does not** cover the current aspect of phagocytosis which includes phagolysosome assembly.
The definition of  GO:0001845 phagolysosome assembly is:
The process that results in the fusion of a phagosome, a vesicle formed by phagocytosis, with a lysosome. 

Which I guess actually describes phagolysosome assembly as a process that occurs after phagocytosis rather than being a part of phagocytosis.

- Please now change the phagocytosis definition:

A vesicle-mediated transport process that results in the engulfment of external particulate material by phagocytes and their delivery to the lysosome. The particles are initially contained within phagocytic vacuoles (phagosomes), which then fuse with primary lysosomes to effect digestion of the particles. 

By adding this statement: The process of phagocytosis begins with the engulfment of external particulate material and ends with formation of a phagosome. The process of phagosome fusion with a lysosome is described by the term GO:0001845 phagolysosome assembly.

- Please then remove the part_of relationship between 

phagocytosis and GO:0001845 phagolysosome assembly

Many thanks

Ruth

**Comment by raymond91125** [comment]
I feel that we are going in a circle on these terms, given the history of past discussions and changes (noted by @addiehl above). @pgaudet should we have another discussion at Editor's meeting and invite @RLovering if possible?
I think the key points of contention are:
1. Whether phagocytosis ends at phagosome formation or phagolysosome formation? (albeit that phagosome ALWAYS goes on to fuse with lysosome)?
2. If phagocytosis indeed ends at phagolysosome formation, can it still a subtype of endocytosis (which ends effectively at phagosome formation)?

**Comment by pgaudet** [comment]
Hi @RLovering 

> However, I disagree with the suggestion that 'phagocytosis has a part phagolysosome assembly does not contradict the sub-type relationship between phagocytosis and endocytosis.'

On the ontology call, we noticed that the definition of endocytosis left open when the process ends,
(GO:0006897 endocytosis: A vesicle-mediated transport process in which cells take up external materials or membrane constituents by the invagination of a small region of the plasma membrane to form a new membrane-bounded vesicle.)

so the fact that 'phagocytosis has a part phagolysosome assembly is not contradictory with the definition of endocytosis.  Or are you suggesting that the parent should include start and end any any child should also have all the same steps?

**Comment by raymond91125** [comment]
How about we trim the definition to this:  "A vesicle-mediated transport process in which cells take up external materials or membrane constituents by the invagination of a part of the plasma membrane."
This would accommodate additional fusion events included in the transport processes of different forms of endocytosis.

**Comment by RLovering** [comment]
Hi 
I have 2 screenshots that explain why I don't think the majority of scientists would consider the full phagocytosis process to be a child of endocytosis
![Screenshot 2023-03-20 at 19 23 07](https://user-images.githubusercontent.com/12080010/226444953-b992eca7-ce60-4377-9376-b0c77661296c.png)
![Screenshot 2023-03-20 at 19 21 53](https://user-images.githubusercontent.com/12080010/226444964-4e102528-d292-4523-9a45-342434e9b23a.png)

**Comment by pgaudet** [comment]
@pfey03 Is is the same in Dicty? is phagocytosis is not a type of endocytosis ?

**Comment by raymond91125** [comment]
For reference, this is what we have as the definition for GO:0006909 phagocytosis A vesicle-mediated transport process that results in the engulfment of external particulate material by phagocytes and their delivery to the lysosome. The particles are initially contained within phagocytic vacuoles (phagosomes), which then fuse with primary lysosomes to effect digestion of the particles. Source: [ISBN:0198506732]

**Comment by raymond91125** [comment]
Current endocytosis def "A vesicle-mediated transport process in which cells take up external materials or membrane constituents by the invagination of a part of the plasma membrane to form a new membrane-bounded vesicle."

Current vesicle-mediated transport def "A cellular transport process in which transported substances are moved in membrane-bounded vesicles; transported substances are enclosed in the vesicle lumen or located in the vesicle membrane. The process begins with a step that directs a substance to the forming vesicle, and includes vesicle budding and coating. Vesicles are then targeted to, and fuse with, an acceptor membrane."

It seems to me the definitions together are sufficiently broad and complete. Any suggestions to make it more clear are welcome.

**Comment by pgaudet** [comment]
OK, looks like there is no more work needed here then. 

Thanks @raymond91125
