### ISSUE TITLE
Obsoletion request: GO:0110154   RNA decapping and children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24919]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0110154  RNA decapping
Cleavage of the 5'-cap of an RNA. 
and children
GO:0000290 deadenylation-dependent decapping of nuclear-transcribed mRNA
GO:0110155   NAD-cap decapping
GO:0110156   methylguanosine-cap decapping
GO:0031087 deadenylation-independent decapping of nuclear-transcribed mRNA
GO:0000290 deadenylation-dependent decapping of nuclear-transcribed mRNA
GO:0106289 negative regulation of deadenylation-dependent decapping of nuclear-transcribed mRNA
GO:0106288 regulation of deadenylation-dependent decapping of nuclear-transcribed mRNA
GO:1901835    positive regulation of deadenylation-independent decapping of nuclear-transcribed mRNA |
GO:1901834    regulation of deadenylation-independent decapping of nuclear-transcribed mRNA | regulates
GO:0036450   polyuridylation-dependent decapping of nuclear-transcribed mRNA
GO:1901835  positive regulation of deadenylation-independent decapping of nuclear-transcribed mRNA	
GO:1901834  regulation of deadenylation-independent decapping of nuclear-transcribed mRNA	regulates

NOTE: We will need a MF term(s) for mRNA decapping activity first

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x] The reason for obsoletion is that the data from the paper for which the term was requested can be accurately described using [appropriate GO term].

 

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by sjm41** [comment]
_NOTE: We will need a MF term(s) for mRNA decapping activity first_

See #24892
I believe we already have these:
. mRNA 5'-phosphatase activity (GO:0140818, EC:3.6.1.74)
. 5'-(N(7)-methylguanosine 5'-triphospho)-[mRNA] hydrolase activity (GO:0140933, EC:3.6.1.62)
. mRNA 5'-diphosphatase activity (GO:0034353, no EC)
. 5'-(N(7)-methyl 5'-triphosphoguanosine)-[mRNA] diphosphatase activity (GO:0140932, EC:3.6.1.59)

Maybe some term renames or added synonyms would make them clearer?
PMID:[30345629](https://pubmed.ncbi.nlm.nih.gov/30345629/) is a good review.

**Comment by ValWood** [comment]
Thanks @sjm41 of course! ( I hadn't actually looked yet!) , but I will add decapping synonyms to these terms to make them  findable!

**Comment by ValWood** [comment]
I'll close this one for now. I want to review some of the children like

deadenylation-independent decapping of nuclear-transcribed mRNA
deadenylation-dependent decapping of nuclear-transcribed mRNA

as it isn't clear if these are just describing different causal upstream processes, but this will be dealt with as I map out the pathways.
