### ISSUE TITLE
NTR H4K20me2 modified histone binding (was H4K20me3) 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24912]
NTR H4K20me2  ~H4K20me3~ modified histone binding (H4K20me3  already exists))

@pgaudet  do we want to precompose these or to use PRO?
I ask because we have :

GO:1990889 | H4K20me3 modified histone binding

crb2 (pombe)  and  53BP1  bind H4K20me2 but exclude H4K20me3 PMID:17190600

**Comment by raymond91125** [comment]
I think it is H4K20me2 in the title.

**Comment by pgaudet** [comment]
I think these are histone readers. We could change the terms 'histone x binding' to 'histone x reader activity'. 

I think this is what @colinlog wanted to do. This may be more useful than using PRO ? ie it's more than 'binding'.

**Comment by ValWood** [comment]
Can we discuss on an editors call so we are clear? I made a ticket about it somewhere (will try to locate) From a Noctua modelling perspective the "histone reader" term is a quite different because it is the opposite direction from the way  that we usually model in  a GO-CAM.


We always have
x has input y (i.e the modified of x form recruits y)
but a reader is y is input of x -modified form.
I think the SIB curators brought this up in a workshop you had once (I seem to remember you mentioning it, but I nev er heard any follow up).

i.e a "reader" is anything that is recruited by an adaptor. Maybe this is OK, and probably this is a good way to capture this clearly, but curators  need to be aware it's a bit different from the conventional input, and that it is necessafry  to make the annotation in both directions, one with the adaptor recruiting and one for the reader reading.

For example, here:
https://www.pombase.org/gene/SPAC1834.04
histone h1 phosphorylated on T3 recruits bir1 (we have always curated in this direction).

For the reader we would be annotating bir1 is a reader of H1-T3. Maybe this is OK. But would this convention be restricted to the histone and the CTD code?

Also, we still need to use PRO for the active form. In this example we can say that bir1  is histone H1-T3 reader, but how do we then indicate that the form of hht1 which acts as an adaptor for bit1 is the form which is phosphorylated on T3? MOD users need to see this information when they are looking at the histone annotation,  otherwise we lose this specificity:

<img width="377" alt="Screenshot 2023-04-04 at 10 14 15" src="https://user-images.githubusercontent.com/7359272/229745647-faadc9c9-3be7-4ea9-b27b-88048b3d6352.png">

**Comment by ValWood** [comment]
That's the ticket I'm happy to do it the "reader way". It is more in line with how scientists think about the histone code BUT  but it is fundamentally different from the causal model.

From a causal perspective,  the directionality goes

histone modifier has_input  --> histone
histone (adaptor) has_input --> recruited substrate

here, we turn it around and say
recruited substrate --> READS modified histone

so in a causal model, we seem to be creating a situation like this:

histone modifier has_input  --> histone
recruited substrate  <--  histone (adaptor)

I don't know if this will cause a problem for the logic.

Maybe @cmungall or @thomaspd  can comment?

**Comment by pgaudet** [comment]
Hi @ValWood 

Here are are describing 'entities' ("modifier"), not activities. The causal model would have

histone modifier activity has input some histone  >> directly provides input for histone reader activity (which is_a adaptor activity) has input the protein it adapts

ie the opposite from what you suggest
> recruited substrate <-- histone (adaptor)

Is that OK ?

**Comment by ValWood** [comment]
I'll make a Noctua model to show you what I mean. Might not be today.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0140005
+name: H4K20me2 histone reader activity
+namespace: molecular_function
+def: "A histone reader that recognizes a histone H4 dimethylated at lysine 20." [PMID:22150589]
+synonym: "H4K20me2 modified histone binding" NARROW []
+is_a: GO:0140566 ! histone reader activity
+relationship: has_part GO:0035064 ! methylated histone binding
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24912" xsd:anyURI
+created_by: pg
+creation_date: 2024-11-29T15:16:39Z
