### ISSUE TITLE
RNA polymerase II CTD heptapeptide repeat phosphatase activity descendents

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24910]
RNA polymerase II CTD heptapeptide repeat phosphatase activity
should have children to mirror the kinase branch:

RNA polymerase II C-terminal domain Y1 phosphatase activity |
RNA polymerase II C-terminal domain T4 phosphatase activity 
RNA polymerase II C-terminal domain S2  phosphatase activity 
RNA polymerase II C-terminal domain S7 phosphatase activity 
RNA polymerase II C-terminal domain S5 phosphatase activity

**Comment by ValWood** [comment]
Note to self:
[PMID:19026779]

**Comment by ValWood** [comment]
@pgaudet  I meant to tag you here to approve this.  DO we want to do these with GO terms, or PRO extensions?
I.e see https://github.com/geneontology/go-ontology/issues/23932

**Comment by pgaudet** [comment]
These will be done with terms - @colinlog says that the RNA polymerease C terminus as a 'code', similar to the histone code, that should captured. I am hoping these are the only 2 exceptions.

**Comment by ValWood** [comment]
RNA polymerase II CTD heptapeptide repeat phosphatase activity

Current def

Catalysis of the reaction: phospho-(DNA-directed RNA polymerase II) + H2O = (DNA-directed RNA polymerase II) + phosphate.

Should be
Catalysis of the reaction: phospho-RNA polymerase II large subunit CTD heptapeptide repeat (YSPTSPS) + H2O = (DNA-directed RNA polymerase II) + phosphate.

Children could be
Catalysis of the reaction: phospho-RNA polymerase II large subunit CTD heptapeptide repeat (position 1 tyrosine) + H2O = (DNA-directed RNA polymerase II) + phosphate.


note that GO:0140833 def has a typo -> phosphotyrosine
Catalysis of the reaction: ATP + RNA polymerase II large subunit CTD heptapeptide repeat (YSPTSPS) = ADP + H+ + RNA polymerase II large subunit **phosphotyrine** (position 1).

**Comment by pgaudet** [comment]
Hi @ValWood , you asked here https://github.com/geneontology/go-ontology/issues/24910#issuecomment-1431329570

>  I meant to tag you here to approve this. Do we want to do these with GO terms, or PRO extensions?

Do you mean, in the logical definition? I dont think we can create logical definition. I would not use PRO, since standard definitions talk about 'a human gene or a ortholog'. Unless you are sure this is valid?

**Comment by pgaudet** [comment]
Also, for the definitions, we should align with how we wrote them for histones, for eg GO:0140791 'histone H2S140 phosphatase activity': 
> Catalysis of the reaction: histone H2 serine phosphate (position 140) + H2O = histone serine (position 140) + phosphate.
ie, Catalysis of the reaction: RNA polymerase II large subunit CTD heptapeptide repeat-phospho-L-tyrosine (position 1) + H2O =RNA polymerase II large subunit CTD heptapeptide repeat-L-tyrosine (position 1)+ phosphate.

**Comment by ValWood** [comment]
OK re definition pattern.

**Comment by pgaudet** [comment]
I notice one definition lists the sequence of the heptapaptide: "Catalysis of the reaction: ATP + RNA polymerase II large subunit CTD heptapeptide repeat (YSPTSPS)" 

should we add this everywhere? Seems useful

**Comment by ValWood** [comment]
Could do...

**Comment by krchristie** [comment]
> I notice one definition lists the sequence of the heptapaptide: "Catalysis of the reaction: ATP + RNA polymerase II large subunit CTD heptapeptide repeat (YSPTSPS)"
> 
> should we add this everywhere? Seems useful

If you list the sequence, you should make it clear that YSPTSPS is the **consensus** sequence. While some repeats are an exact match there are many variations.

**Comment by ValWood** [comment]
i can add 'consensus' but in general when people refer to the heptad repeats they are referring to the consensus repeats, rather than the  rump where there is some variation. At least this is the case for pombe and _S. cerevisiae_. I'm not sure if other species have lots of differences but I think the consensus heptads are pretty well maintained

<img width="156" alt="Screenshot 2023-02-22 at 16 41 39" src="https://user-images.githubusercontent.com/7359272/220697010-0bff7399-17f5-484b-9ed7-6be0de6bb2fd.png">

**Comment by krchristie** [comment]
> i can add 'consensus' but in general when people refer to the heptad repeats they are referring to the consensus repeats, rather than the rump where there is some variation. At least this is the case for pombe and _S. cerevisiae_. I'm not sure if other species have lots of differences but I think the consensus heptads are pretty well maintained> 

Having read lots and lots of papers on the CTD when I was working on RNAP II from S. cerevisiae, it is my impression that all species have variations, and that it is not so clear cut that the variations are only in the "rump" as you've called it. It was not my impression that people meant ONLY the perfect matches when they talked about the heptad repeats, but rather that most people just simplified the language by referring to each repetition of the pattern as a repeat whether perfect or not. For example, people often said things like S. cerevisiae has 26 or 27 repeats, while human has 52 repeats. These numbers are the total number of heptads including the imperfect repeats.

**Comment by colinlog** [comment]
Hi all,
I agree with @krchristie :  in the field the variant heptad repeats are implicitly included when a researcher mentions the CTD repeats. Including the 'consensus' qualifier in the definition helps because it implies that we do know this takes place for consensus repeats but not for now know to what extent their modification (eg: of phosphorylation of the serine 5 of that heptad repeat or of the cis-trans isomerisation of one of the prolines) has any other function than it has on canonical YSTPSPS repeats.

There is primary literature on the potential and sometimes demonstrated function of the variant repeats, nevertheless.

**Comment by ValWood** [comment]
OK I will go ahead and add this to all the terms. I'll do it once the grouping MF term is in place then I won't miss any.

**Comment by pgaudet** [comment]
I added the grouping term yesterday, you can go ahead.

**Comment by ValWood** [comment]
The kinase definitons are like this:
Catalysis of the reaction: ATP + RNA polymerase II large subunit CTD heptapeptide repeat (YSPTSPS) = ADP + H+ + RNA polymerase II large subunit phosphoserine (position 2).

The phosphatase definitions are like this
Catalysis of the reaction: RNA polymerase II large subunit CTD heptapeptide repeat-phospho-L-serine (position 2)  + H2O = RNA polymerase II large subunit CTD heptapeptide repeat-L-serine (position 2) + phosphate.

should I change the phosphatase defs to to:

- [ ] Catalysis of the reaction: RNA polymerase II large subunit CTD heptapeptide repeat--phospho-L-serine  (consensus YSPTSPS)(position 2)  + H2O = RNA polymerase II large subunit  + phosphate.

- [ ] and add the word consensus to the (consensus YSPTSPS) for everything else?

- [ ] Also, standardize the kinase primary term labels to "CTD heptapeptide repeat"
