### ISSUE TITLE
GO:0000294    nuclear-transcribed mRNA catabolic process, endonucleolytic cleavage-dependent decay CLARIFICATION REQUIRED

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24917]
GO:0000294   nuclear-transcribed mRNA catabolic process, endonucleolytic cleavage-dependent decay

is defined
A minor degradation pathway nuclear-transcribed mRNAs that begins with an endonucleolytic cleavage to generate unprotected ends.

This definition doesn't seem to be necessary and sufficient to describe the pathway.

The term was intended for a pathway observed in S. cerevisiae ( PMID:14729943 )
The pathway operating in S. cerevisiae is MRP dependent , and so far is only known to operate on cyclin
RNase MRP cleaves the CLB2 mRNA to promote cell cycle progression: novel method of mRNA degradation.

It has subsequently been used for PMID:17158880 which appears to be describing 3'end processing, and I don't think should use this term at all.

It has 15 annotations
2 PomBase
12 SGD
1 MGI (UniProt)
1 human (Uniprot)

I would like to revise the term name and definition to:
nuclear-transcribed mRNA catabolic process, RNAase MRP -dependent
and remove all of the other  annotations up to  nuclear-transcribed mRNA catabolic process (or move them if they are describing processing). 

@srengel  do you have any objection to this?

I am aiming to resolve "GO:0000294    nuclear-transcribed mRNA catabolic process" into the well-characterised pathways, it will be easier to see what this term refers to, and if it belongs elsewhere if it refers to MRP as was originally intended.

@Antonialock  could you look at the 2 UniPRot annotations and see if they would be better on the parent. I will move the pombe ones (which are processing)

**Comment by srengel** [comment]
Hi Val, sounds fine (revise the term name and definition to: nuclear-transcribed mRNA catabolic process, RNAase MRP-dependent).  i agree that PMID:17158880 appears to be describing 3'end processing, and should not use this term at all. i've changed those annotations.

i will leave the annotations on PMID:14729943 as is so they get the new term name when it's changed.

**Comment by ValWood** [comment]
Thanks!

**Comment by ValWood** [comment]
@Antonialock could you move the 2 Uniprot annotations? I'll deal with the pombe ones and relabel this term and improve the definition.

**Comment by pgaudet** [comment]
Fixed UniProt annotations

**Comment by pgaudet** [comment]
Do we have a ticket to obsolete  the child term, GO:0043927  exonucleolytic nuclear-transcribed mRNA catabolic process involved in endonucleolytic cleavage-dependent decay ? 

No annotations

**Comment by ValWood** [comment]
I comment about this here:
https://github.com/geneontology/go-ontology/issues/22339
It probably does represent a specific pathway (the pathways are often called after the nuclease direction), so I was going to look and maybe clarify the labelling for some of these once I figured what they are. Although if there are no annotations, it might be easier to obsolete and begin afresh. 

GO:0043927 is one of the children of this term
https://www.ebi.ac.uk/QuickGO/term/GO:0000291
and this bunch of terms appear to represent the major pathways.

It should not have the parent [GO:0000294](https://github.com/geneontology/go-ontology/issues/24917#top)
though, I will remove that relation when I clarify the meaning of GO:0000294, and deal with it later.

**Comment by ValWood** [comment]
I'm not even so sure this is a separate process from 
XRN-mediated 3' decay:

Our results demonstrate that the endoribonuclease RNase MRP specifically cleaves the CLB2 mRNA in its 5'-UTR to allow rapid 5' to 3' degradation by the Xrn1 nuclease.

It could just be a first step, but I can come back to this later..... at least it is disambiguate.
It would be good to know where this process occurs, but I haven't been able to find that information.

**Comment by pgaudet** [comment]
GO:0043927 exonucleolytic nuclear-transcribed mRNA catabolic process involved in endonucleolytic cleavage-dependent decay has no annotation and no reference, if you are not sure I propose we obsolete, we can add a better term later?

**Comment by ValWood** [comment]
GO:0043927 exonucleolytic nuclear-transcribed mRNA catabolic process involved in endonucleolytic cleavage-dependent decay has no annotation and no reference, if you are not sure I propose we obsolete, we can add a better term later?

Yes I was just looking at this again. I kept it with it's other parent, but it isn't what I thought, it needs obsoleting. I will make a ticket. I think I just forgot about this because the original purpose of this ticket was to find out what  [GO:0000294](https://github.com/geneontology/go-ontology/issues/24917#top) was for.

**Comment by ValWood** [comment]
Term is relabelled.
