### ISSUE TITLE
NTR co-transcriptional polyadenylation dependent  mRNA 3'-end processing (or relabel GO:0006378   mRNA polyadenylation)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24921]
Starting to address 
https://github.com/geneontology/go-ontology/issues/24161
39+  terms !

We have LOTs of terms to represent cleavage/ or polyadenylation scattered around the ontology, but we do not appear to have a single term to represent this pathway.

~We need an explicit term
co-transcriptional polyadenylation dependent mRNA 3'-end processing
parent GO:0031124   mRNA 3'-end processing
Def
The transcription termination-coupled cotranscriptional 3’ processing of RNA polymerase II transcripts,  involves 3′ end cleavage of nascent mRNAs and addition of the poly(A) tail.
This pathway is required for the maturation of primary protein-encoding transcripts into functional mRNAs that can be exported from the nucleus and translated in the cytoplasm, but is also required for polyadenylation-dependent decay.
synonym "cotranscriptional 3’ processing of RNA polymerase II  transcripts" broad~
see below for final term

Note that we do have already equivalent terms for 
GO:0071051   polyadenylation-dependent snoRNA 3'-end processing
( I have an objection to this axis of classification because it seems to be the same pathway, but we can park this for now)

At least if we have this term we can remove a bunch of the "polyadenylation" and"cleavage" terms.

~We could   relabel
GO:0006378   mRNA polyadenylation
The enzymatic addition of a sequence of 40-200 adenylyl residues at the 3' end of a eukaryotic mRNA primary transcript.
which means pretty much the same thing (the renaming/revised definition would just make the purpose clearer because it includes the cleavage step)~
see below

This (GO:0006378) would otherwise need to be obsoeted in the clean up.

@pgaudet  what do you think? I prefer to rename and it doesn't really change the meaning. It gives people a clear place to house the cleavage step in process.

**Comment by ValWood** [comment]
I don't think we can repurpose 
GO:0006378 mRNA polyadenylation
because there is also cytoplasmic and mitochondrial polyadenylation pathways
That one will need to be obsoleted.

**Comment by ValWood** [comment]
NTR cytoplasmic polyadenylation
Cytoplasmic polyadenylation is the process by which dormant, translationally inactive mRNAs become activated via the elongation of their poly(A) tails in the cytoplasm. This process is regulated by the conserved cytoplasmic polyadenylation element binding (CPEB) protein family.
PMID: 21536428

**Comment by ValWood** [comment]
https://www.sciencedirect.com/science/article/pii/S0959440X18302185#:~:text=mRNA%203%E2%80%B2%2Dend%20processing%20occurs,tail%2C%20and%20trigger%20transcription%20termination.

we might not even need to specify "polyadenylation dependent"

"mRNA 3′-end processing occurs co-transcriptionally and involves more than 20 proteins to specifically recognize the polyadenylation site, cleave the pre-mRNA, add a poly(A) tail, and trigger transcription termination"

**Comment by ValWood** [comment]
This is what I was seeing at default browser width
<img width="1369" alt="Screenshot 2023-02-15 at 19 25 22" src="https://user-images.githubusercontent.com/7359272/219131927-45a7da47-ae91-47f7-a507-cfaa58c9f54c.png">

Maybe my font was a bit big on your site (I made it smaller now)
I used the magnifying glass , and when I put the UniProt ID in here I didn't find the list of all modified forms.

**Comment by ValWood** [comment]
Actually if my book mark was the front page I would have found it, but for some reason my bookmark was set to here
https://proconsortium.org/app/entry/PR%3A000027551/
So I was only seeing the menu bar and not the search box. (this page is very wide)

**Comment by ValWood** [comment]
co-transcriptional polyadenylation dependent mRNA 3'-end processing
is a bit misleading, it sounds as though polyaddenyation is required for this process, when it is in fact  a step in the process.

Instead  I will use
co-transcriptional mRNA 3'-end processing, cleavage and polyadenylation pathway 
(Happy to change this later, but I think it will help curators for the time being if the term explicitly mentions polyadenylation since these are the term we will remove)

**Comment by ValWood** [comment]
Also added
co-transcriptional RNA 3'-end processing, cleavage and polyadenylation pathway
so that I can move the sno & mRNA terms together.
However Protege won't let me add 

co-transcriptional mRNA 3'-end processing, cleavage and polyadenylation pathway
is_a
co-transcriptional RNA 3'-end processing, cleavage and polyadenylation pathway
it doesn't appear to recognise the new term yet?

**Comment by ValWood** [comment]
- [ ] move 
GO:0071051 polyadenylation-dependent snoRNA 3'-end processing under
co-transcriptional RNA 3'-end processing, cleavage and polyadenylation pathway

**Comment by ValWood** [comment]
+[Term]
+id: GO:0180010
+name: co-transcriptional mRNA 3'-end processing, cleavage and polyadenylation pathway
+namespace: biological_process
+def: "Any process involved in transcription termination-coupled  3’ processing of RNA polymerase II mRNA transcripts by the 3′ end cleavage  and addition of the poly(A) tail.\nThis pathway is required for the maturation of primary protein-encoding transcripts into functional mRNAs that can be exported from the nucleus and translated in the cytoplasm, but is also required for polyadenylation-dependent decay." [PMID:31499460]
+synonym: "cotranscriptional 3’ processing of RNA polymerase II mRNA transcripts" EXACT []
+is_a: GO:0031124 ! mRNA 3'-end processing
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24921 xsd:anyURI
+created_by: vw
+creation_date: 2023-02-23T11:56:19Z
+
+[Term]
+id: GO:0180011
+name: cytoplasmic polyadenylation
+namespace: biological_process
+def: "Any process by which dormant, translationally inactive mRNAs become activated via the elongation of their poly(A) tails in the cytosol." [PMID:21536428]
+is_a: GO:0031124 ! mRNA 3'-end processing
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24921 xsd:anyURI
+created_by: vw
+creation_date: 2023-02-23T12:11:43Z
+
+[Term]
+id: GO:0180012
+name: co-transcriptional RNA 3'-end processing, cleavage and polyadenylation pathway
+def: "Any process involved in transcription termination-coupled  3’ processing of RNA polymerase II RNA transcripts by the 3′ end cleavage  and addition of the poly(A) tail.\nThis pathway is required for the maturation of primary protein-encoding transcripts into functional RNAs that can be exported from the nucleus and translated in the cytoplasm, but is also required for polyadenylation-dependent decay." []
+synonym: "cotranscriptional 3’ processing of RNA polymerase II transcripts" EXACT []
+xref: PMID:31499460
+is_a: GO:0006396 ! RNA processing
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/24921 xsd:anyURI
+created_by: vw
+creation_date: 2023-02-23T12:18:59Z

**Comment by ValWood** [comment]
I am still unable to add the parent here:
<img width="784" alt="Screenshot 2023-02-24 at 09 38 20" src="https://user-images.githubusercontent.com/7359272/221145008-affac0ef-31aa-4cf6-820c-01adac1fb70d.png">

I am  copy pasting it directly from the it  rdf label?
@pgaudet  do you know why?

**Comment by pgaudet** [comment]
You need to escape the 'prime' (') with a backslash 


ie it should be 

3\'-end processing

**Comment by ValWood** [comment]
I didn't do this:
GO:0071051 polyadenylation-dependent snoRNA 3'-end processing under
co-transcriptional RNA 3'-end processing, cleavage and polyadenylation pathway

because it is defined:
Any process involved in forming the mature 3' end of a snoRNA molecule linked to prior polyadenylation of the 3'-end of the precursor snoRNA.

I don't know what this means. I thought that the polyadenylation is _part_ of the 3' end processing, so I need to find out what sort of "processing" occurs after polyadenylation. I will open a new ticket for this question.
