### ISSUE TITLE
EC xref on GO:0050253 retinyl-palmitate esterase activity  is obsolete

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24923]
GO:0050253 retinyl-palmitate esterase activity is linked to  EC:3.1.1.21 , which is obsolete. Minimally the xref should be removed,

There are 14 GO EXP annotations. GO:0050253 is linked to RHEA:21508, which have no direct links to entries, but 11 proteins associated with the more specific reaction: RHEA:31775

@kaxelsen should we rather link to RHEA:31775? 

Thanks, Pascale

**Comment by deustp01** [comment]
Reactome has reactions that use this GO term to annotate the activity of an enzyme. Let me look at them to see if the more specific RHEA reaction is better.

**Comment by deustp01** [comment]
I think I see a complication: RHEA:31775 specifies 11-cis retinol ([CHEBI:16302](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=16302)) as a reaction participant but we also have retinyl-palmitate esterase reactions with all-trans-retinol ([CHEBI:17336](https://www.ebi.ac.uk/chebi/searchId.do;jsessionid=6383BFDA9343BC7B1A92610B4D9C9DB1?chebiId=CHEBI%3A17336)) as a particiopant, corresponding to [RHEA:13993](https://www.rhea-db.org/rhea/13933)

**Comment by kaxelsen** [comment]
RHEA:21508 has two children, RHEA:13933 (producing all-trans-retinol) and RHEA:31775 (producing 11-cis-retinol). As the definition is written, RHEA:21508 is the best Rhea match as the other two are more specific.

RHEA:31775 is used for EC 3.1.1.64, retinoid isomerohydrolase, that in the process of hydrolysis changes the product from all-trans-retinol to 11-cis-retinol. This reaction is linked to GO:0052884.

RHEA:13933 (no EC number, but covered by EC 3.1.1.1) is linked to GO:0047376 

RHEA:21508 is: all-trans-retinyl hexadecanoate + H2O = H+ + hexadecanoate + retinol

**Comment by pgaudet** [comment]
Thanks for the detailed explanation @kaxelsen 

I removed EC:3.1.1.64 from GO:0047376 all-trans-retinyl-palmitate hydrolase, all-trans-retinol forming activity

Thanks, Pascale
