### ISSUE TITLE
Obsoletion request: RNA polyadenylation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24924]
Please provide as much information as you can:

Once https://github.com/geneontology/go-ontology/issues/24921
is done we can begin to obsolete

- [x] GO:0043631   RNA polyadenylation
- [x] GO:0006378    mRNA polyadenylation
- [x] GO:1900364    negative regulation of mRNA polyadenylation	
- [x] GO:1900365    positive regulation of mRNA polyadenylation	
- [x] GO:1900363    regulation of mRNA polyadenylation	
- [x] GO:0043629    ncRNA polyadenylation
(I will make sure there are direct  replacements for all of these)

- [x] GO:0043630    ncRNA polyadenylation involved in polyadenylation-dependent ncRNA catabolic process 
replace by -> GO:0043634  polyadenylation-dependent ncRNA catabolic process

- [x] GO:0071050    sno(s)RNA polyadenylation -> 
replace by GO:0071051    polyadenylation-dependent snoRNA 3'-end processing

Rehouse:
- [ ] GO:0097222    mitochondrial mRNA polyadenylation
- [ ] GO:0140235   RNA polyadenylation at postsynapse (this could probably move under cytoplasmic polyadenylation, need to check)
- [ ] GO:0039698    polyadenylation of viral mRNA by polymerase stuttering (this is something completely different nd ned rehoming)

* **GO term ID and Label**

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x] The reason for obsoletion is that this term represents a molecular function.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
https://docs.google.com/spreadsheets/d/1Dyb4jkJAqnHonfWw2-9u3zQcpAcVd5cd9p_I7ta2Muc/edit#gid=0

- [x]  Annotation review ticket https://github.com/geneontology/go-annotation/issues/4553
- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
waiting for terms in 
https://github.com/geneontology/go-ontology/issues/24921
to appear

**Comment by pfey03** [comment]
we had 5 ISS all changed or deleted.

**Comment by ValWood** [comment]
FOr now I moved
GO:0039698 polyadenylation of viral mRNA by polymerase stuttering  under 'viral process' 
and
 GO:0140235 RNA polyadenylation at postsynapse
under RNA processing

**Comment by ValWood** [comment]
[GO:0006378](https://www.ebi.ac.uk/QuickGO/term/GO:0006378)
is still present and has  79 EXP annotations

**Comment by ValWood** [comment]
[GO:0006378](https://www.ebi.ac.uk/QuickGO/term/GO:0006378)
is still present and has 78 EXP annotations
I wonder if this term somehow got excluded from the spreadsheet so I will create another one to finish this off.

**Comment by ValWood** [comment]
GO:1900364   negative regulation of mRNA polyadenylation
is also remaining but this can be obsoleted with the parent 
GO:0031441   negative regulation of mRNA 3'-end processing
as direct replacement

**Comment by ValWood** [comment]
I'm reopening this because some terms are still present. Will review and open a new ticket for the rest.

**Comment by ValWood** [comment]
I remember now I hadn't done 
GO:0006378  mRNA polyadenylation (depending whether nuclear of cytosolic)
because it was more complicated.

I  planned to keep  GO:0180011   cytoplasmic polyadenylation
in the short term because there appear to be a couple of pathways and  there is no good replacement yet (related to stability which needs to b e addressed separately.
SO I'll close this and open a ticket for "mRNA polyadenylation"
