### ISSUE TITLE
Split EC used in dbxref

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24932]
- [x] #24905
- [x]  [4.2.3.14  Transferred entry:  4.2.3.119 and 4.2.3.120.  ](https://github.com/geneontology/go-ontology/issues/26207)
- [x]  [3.6.1.30  Transferred entry:  3.6.1.59  and 3.6.1.62.](https://github.com/geneontology/go-ontology/issues/23290) 
- [ ] 2.7.1.69  Transferred entry:  2.7.1.191,  2.7.1.192,  2.7.1.193,  2.7.1.194,
- [ ] 2.4.2.23  Transferred entry:  2.4.2.2,  2.4.2.3 and 2.4.2.4.
- [ ] [2.3.1.119 Transferred entry:  1.1.1.330,  1.3.1.93, 2.3.1.199](https://github.com/geneontology/go-ontology/issues/25965) 
- [ ] 2.4.1.157 Transferred entry:  2.4.1.336 and 2.4.1.337.  
- [ ]  [1.7.99.4  Transferred entry:  1.7.1.1,  1.7.1.2,  1.7.1.3,  1.7.5.1,](https://github.com/geneontology/go-ontology/issues/25967)

**Comment by ValWood** [comment]
@pgaudet is this still in date?

**Comment by pgaudet** [comment]
Thanks! Looks like we fixed these already with the new QC checks.
