### ISSUE TITLE
NTR: mRNA 5'-diphosphatase activator activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24933]
Please provide as much information as you can: 

* **Suggested term label:**
 mRNA 5'-diphosphatase **activator** activity

I think I requested a similar term recently for an equivalent inhibitor but I can't find the ticket anywhere?

@pgaudet , I think you suggested a  "RNA phosphatase inhibitor" or similar?

So here could we have  "RNA phosphatase activator activity" to distinguish from protein phosphatases?
Needed for  PMID:22085934

Let me know if you know ewhere the other ticket is, I searched *everything*)

**Comment by sjm41** [comment]
#23290 / #24720 ?

**Comment by ValWood** [comment]
Yes, thank you @sjm41 !

**Comment by pgaudet** [comment]
@ValWood Can you copy the new term? and link the PR ? 

Thanks, Pascale

**Comment by ValWood** [comment]
It's this ticket?
https://github.com/geneontology/go-ontology/issues/24720
I'm not following?

**Comment by ValWood** [comment]
This was a duplicate.

**Comment by pgaudet** [comment]
Ha! Thanks.
