### ISSUE TITLE
NTR: [ATG8 complex]

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#24935]
Please provide as much information as you can: 

* **Suggested term label:**
ATG8 complex or ATG8-ATG7 complex or ATG8-ATG12 complex

* **Definition (free text)**
ATG complex rendered through ubiquitin-like conjugations

* **Reference, in format PMID:26246495, PMID:12626495

* **Gene product name and ID to be annotated to this term**
atg8, atg7, atg4, atg12,maybe atg5 and atg16 (atg5 with atg12 conjugation has been shown in PMID:12626495)
* **Parent term(s)**
GO:1990234 transferase complex

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
I'm not sure if I can use the yeast term  GO:0034274 Atg12-Atg5-Atg16 complex see conjugation comment above between atg5 and atg12. The picture below is from PMID:26246495 where they through protein binding found new interactions (and deciphered the ATG1-ULk1 complex members not shown here). 
If I need to use the yeast term then the def needs to be changed and I want the two papers cited here to be added to the term. Otherwise I want my own term that has been shown by direct binding.
![ATG8 complex](https://user-images.githubusercontent.com/1349602/219516021-fb5f55c8-3613-42b8-969c-8f8dd525e95c.png)

**Comment by pgaudet** [comment]
@marcfeuermann I think you are familiar with this topic - can you answer @pfey03 's question, 

> I'm not sure if I can use the yeast term GO:0034274 Atg12-Atg5-Atg16 complex see conjugation comment above between atg5 and atg12.

Thanks, Pascale

**Comment by marcfeuermann** [comment]
ATG8 as a ubiquitin-like modifier and the others are either E1 (ATG7), or E3 (ATG2-ATG5) enzymes. ATG4 is a peptidase that maturates ATG8. ATG8 is linked to phospatidylethanolamine or phosphatisylserine to tag membranes, it has no function within complexes with the other proteins apart from being their substrate. I do not think we should create complex terms for an enzyme and its substrate. Let me know if I did not understand the request. Best regards, Marc.

**Comment by pgaudet** [comment]
Hi @marcfeuermann Thanks for looking into this. Indeed we would not create a complex defined by its inclusion of t he substrate. The papers you cite are showing protein-protein interactions; it doesn't seem that the authors claim these are stable complexes. 

I'll close this.
