### ISSUE TITLE
NTR: [Egg-laying behavior]

### ISSUE THREAD

**Issue by sharan-gh** [geneontology/go-ontology#24944]
Please provide as much information as you can: 

* **Suggested term label:**
Egg-laying behavior

* **Definition (free text)**
The reproductive behavior consisting of the muscle system and nervous system processes involved in the regulation and execution of oviposition in response to internal and external stimuli. 

* **Reference, in format PMID:#######**
PMID: NA
https://www.ncbi.nlm.nih.gov/books/NBK19787/ 

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
has parent reproductive behavior (GO:00198098)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
RELATED to Oviposition (GO:0018991)

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
Suggested term to distinguish from existing term for Oviposition (GO:0018991). Redefinition request for oviposition has been submitted.

**Comment by raymond91125** [comment]
See also https://github.com/geneontology/go-ontology/issues/24942.
This proposal is to make a new term egg-laying behavior = (regulation of oviposition + oviposition).
