### ISSUE TITLE
Textual definition update: Oviposition (GO:0018991)

### ISSUE THREAD

**Issue by sharan-gh** [geneontology/go-ontology#24942]
* **GO term ID and label for which you request a definition update**
Oviposition (GO:0018991)

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
A reproductive behavior that results in the deposition of eggs (either fertilized or not) upon a surface or into a medium such as water.

* **Reference(s)**
PMID:NA
https://www.ncbi.nlm.nih.gov/books/NBK19787/ 

* **Additional information**
Previous definition did not clarify whether the process referred only to the muscle system process, or whether it included the associated nervous system processes. This adjustment accompanies a separate ticket with a new term request for 'egg-laying behavior' (comprising both muscle system and nervous system processes), where 'oviposition' is part_of 'egg-laying behavior'.

**Comment by pgaudet** [comment]
@hattrill 
@raymond91125 
Is this change OK with you ?

**Comment by raymond91125** [comment]
I don't think oviposition is a muscle system process per se. Oviposition is the act of 'transporting' eggs from the uterus, through an opening to the exterior. Although it probably involves some muscles, it is not a process entirely carried out withinin muscles. (muscle system process DEF: A [sic] organ system process carried out at the level of a muscle. Muscle tissue is composed of contractile cells or fibers.)
I think oviposition, which is a child of reproductive behavior, is the same as egg-laying behavior.

**Comment by raymond91125** [comment]
Insect oviposition reference PMID:31164023. PDF link: https://hal.science/hal-02368283/file/31164023_Curry,%20Prud'homme%20&%20Gompel,%202019.pdf

**Comment by hattrill** [comment]
Think that in terms of use, I would agree with @raymond91125 that it is generally egg-laying behavior rather than a muscle system process. Perhaps, if there are specific muscle processes to be annotated, then the appropriate muscle system process should be annotated an associated as occuring in a particular anat.
As for nervous system process, most behaviors are ns processses, but in the behavioural branch, I generally don't see this, so I would be inclined to stick to that pattern and that would allow more flexibility in that the the curator could decide whether to state that the behaviour is part_of ms or ns process.

**Comment by vanaukenk** [comment]
For @sharan-gh 's project, we've been trying to semantically model two C. elegans behaviors: egg-laying behavior and CO2 avoidance behavior.

In the course of doing this work, we felt that these behaviors had two main components: the nervous system processes that sense specific conditions and thus control/regulate when the second component, often, but maybe not exclusively, involving a muscle system process, is executed.

We were trying, then, to come up with a term for the muscle system process for egg-laying behavior and the current definition of oviposition led us to think this might actually be a good fit.  But, given the more general usage of 'oviposition, maybe oviposition is better as the overall behavior term (and we could add an additional synonym, egg-laying behavior) and we could create other terms to describe the muscle system processes that are 'part of' the egg-laying behavior.

**Comment by raymond91125** [comment]
Perhaps we could be more explicit --
part_of oviposition behavior
   muscle system process involved in oviposition behavior
   nervous system process involved in oviposition behavior

**Comment by pgaudet** [comment]
In the past this has not served us; ie in practice it's difficult to have the evidence that allows annotating to these terms.

**Comment by raymond91125** [comment]
With site of action experimental data, these annotations are possible.

**Comment by sharan-gh** [comment]
From a discussion yesterday, we have suggested the following:

1) Leaving the classification of 'oviposition' (GO:0018991) unchanged, but using the synonym 'egg-laying behavior' as the primary term name.

2) Requesting a new term, e.g. 'egg deposition' that describes only the mechanical aspects of the movement of an egg from within an organism to outside.

**Comment by raymond91125** [comment]
@sharan-gh please make a new NTR for 'egg deposition'. Thanks.

**Comment by raymond91125** [comment]
Definition: Any process that modulates the rate, frequency or extent of membrane depolarization. Membrane depolarization is the process in which membrane potential changes in the depolarizing direction from the resting potential, usually from negative to positive.
Rate is regarding the rate of change; frequency is about how frequent the occurrence; extent is about the magnitude and duration.

**Comment by raymond91125** [comment]
Changed the label of GO:0018991 (and regulation terms) from ovipositon to egg-laying behavior.

**Comment by raymond91125** [comment]
@hattrill Is FB OK with the changes? Thanks.

**Comment by raymond91125** [comment]
PMID:18050396 for egg-laying chapter in WormBook
