### ISSUE TITLE
NTR: [Adaptation of neuron to stimulus]

### ISSUE THREAD

**Issue by sharan-gh** [geneontology/go-ontology#24958]
Please provide as much information as you can: 

* **Suggested term label:**
Adaptation of neuron to stimulus

* **Definition (free text)**
Any process that results in a diminishing neural activity due to repeated or sustained interaction with a given stimulus.

* **Reference, in format PMID:#######**
PMID: 26365196

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
has parent negative regulation of membrane depolarization [GO1904180]

* **Any other information**

**Comment by raymond91125** [comment]
What is the difference between this and [Sensory adaptation in neuronal response to stimulus] https://github.com/geneontology/go-ontology/issues/24961?

**Comment by sharan-gh** [comment]
Sorry, this is a duplicate.
