### ISSUE TITLE
NTR: [Negative regulation of membrane excitability]

### ISSUE THREAD

**Issue by sharan-gh** [geneontology/go-ontology#24957]
Please provide as much information as you can: 

* **Suggested term label:**
Negative regulation of membrane excitability

* **Definition (free text)**
Any process that increases the propensity for a neuron to be depolarized by some input.

* **Reference, in format PMID:#######**
PMID: 33958801
PMID: 24431435

* **Gene product name and ID to be annotated to this term**
clh-3 [WBGene00000530]

* **Parent term(s)**
has parent negative regulation of membrane depolarization [GO:1904180]; has parent regulation of membrane excitability (new term)

* **Any other information**

From ref (2): 
"Because clh-3 encodes chloride channels, we reasoned that it might affect HSN activity by affecting HSN excitability. To test this, we crossed the clh-3 mutants with an integrated transgenic line that expresses Channelrhodopsin-2 (ChR2), the blue-light- activated cation channel (Nagel et al., 2005), in the HSNs ...We observed that the clh-3(n995gf) mutant laid significantly fewer eggs per stimulation than the wild-type and blue light stimulation elicited an egg-laying event significantly less frequently in mutant animals than in wild-type. Conversely, the clh-3(ok768 and ok763) mutants laid significantly more eggs than the wild-type and blue light stimulation elicited egg-laying events, including the laying of multiple eggs, more frequently than for the wild- type (Fig. 7C,D). Together, these data support a role for the clh- 3-encoded channels in inhibiting HSN excitability: increased channel activity inhibits HSN excitability whereas loss of the channel promotes HSN excitability.""

**Comment by ValWood** [comment]
Membrane excitability doesn't sound like a GO process (more like a 'state'). To me, a lot of these term requests seem like phenotypes, or mechanistic details. 

Note there are existing terms which might suffice:
GO:0098900   regulation of action potential
etc

**Comment by sharan-gh** [comment]
The proposal is for 'regulation of membrane excitability' to be a process, rather than membrane excitability itself. The activity of gene product for clh-3 enables this regulation.

**Comment by sharan-gh** [comment]
The proposal is for the regulation term to refer to a process, similar to regulation of action potential. I think GO:0098900 could work fine, except that for _C. elegans_ neurons it's generally understood that they don't have action potentials (just passive propagation of current).
