### ISSUE TITLE
NTR: [Regulation of membrane excitability]

### ISSUE THREAD

**Issue by sharan-gh** [geneontology/go-ontology#24955]
Please provide as much information as you can: 

* **Suggested term label:**
Regulation of membrane excitability

* **Definition (free text)**
Any process that changes the propensity for a neuron to be depolarized by some input.

* **Reference, in format PMID:#######**
PMID: 33958801

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
has parent regulation of membrane depolarization [GO:0003254]

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
How is this proposed new term different from GO:0003254 regulation of membrane depolarization DEF: Any process that modulates the rate, frequency or extent of membrane depolarization. Membrane depolarization is the process in which membrane potential changes in the depolarizing direction from the resting potential, usually from negative to positive?
Is this term intended to be specific to neurons, but not muscles or other cells (e.g. pacreatic beta cell PMID:17919183)?

**Comment by sharan-gh** [comment]
Hi Raymond,

The motivation for this is to model (with GO-CAM) results such as the one described in the additional notes for the proposed child term:

https://github.com/geneontology/go-ontology/issues/24957#issue-1590113002. 

In this case, it is tied to a gene, clh-3, which encodes a chloride ion channel. The idea here is that the activity of clh-3 doesn't hyperpolarize HSN to the extent that HSN activity is abolished (i.e. voltage-gated calcium ion channels cannot be opened) but that it reduces HSN activity. 

It is true that the existing definition covers this result, but doesn't distinguish modulatory from 'absolute' effects. The proposed term is intended to make this distinction.
