### ISSUE TITLE
Improve definiton Biological Process root term 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#24968]
Current def: A biological process represents a specific objective that the organism is genetically programmed to achieve. Biological processes are often described by their outcome or ending state, e.g., the biological process of cell division results in the creation of two daughter cells (a divided cell) from a single parent cell. A biological process is accomplished by a particular set of molecular functions carried out by specific gene products (or macromolecular complexes), often in a highly regulated manner and in a particular temporal sequence.

Proposed def: A biological process is a genetically-encoded biological module or program that consists of all the steps required to achieve a specific biological objective. A biological process is accomplished by a particular set of molecular functions carried out by specific gene products (or macromolecular complexes), often in a highly regulated manner and in a particular temporal sequence.

@thomaspd

**Comment by deustp01** [comment]
What limitations of the current definition is this new one intended to fix?

**Comment by addiehl** [comment]
The current definition basically says process = objective.  These are fundamentally different things from an ontological perspective. Whatever new definition is made should make clear that a biological process is a process in BFO sense.

**Comment by addiehl** [comment]
My first take at a proposed definition: A biological process is a process that results from the execution of a genetically-encoded biological module or program that consists of all the steps required to achieve a specific biological objective. A biological process is accomplished by a particular set of molecular functions carried out by specific gene products (or macromolecular complexes), often in a highly regulated manner and in a particular temporal sequence.

**Comment by pgaudet** [comment]
Working with @thomaspd - we propose this: 

A biological process is the execution of a genetically-encoded biological module or program. It consists of all the steps required to achieve the specific biological objective of the module. A biological process is accomplished by a particular set of molecular functions carried out by specific gene products (or macromolecular complexes), often in a highly regulated manner and in a particular temporal sequence.

Thanks, Pascale

**Comment by pgaudet** [comment]
Also removed unnecessary sentence from MF definiton "These actions are described from two distinct but related perspectives: (1) biochemical activity, and (2) role as a component in a larger system/process."
