### ISSUE TITLE
Adenine or adenosine in pyrimidine- and adenine-specific:sodium symporter activity?

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#24967]
If I got it right. GO:0015389 pyrimidine- and adenine-specific:sodium symporter activity was initially created on the basis of https://tcdb.org/search/result.php?tc=2.A.41.2.3

It was curated to the nucleoside symporters SLC28A1, 2 and 3. I would have expected to have adenosine instead of adenine in the term description and definition.
Alternatively the term could be deprecated as it does not correspond to any MF.

**Comment by pgaudet** [comment]
Changed term label and definition from 'adenine', which is the base, to 'adenosine', which is the nucleoside.
