### ISSUE TITLE
NTR: histone H2AS1 acetyltransferase activity/ histone H4S1 acetyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24963]
Please provide as much information as you can: 

* **Suggested term label:**
histone H2AS1 acetyltransferase activity

* **Definition (free text)**

Catalysis of the reaction: acetyl-CoA + histone H2A L-sering (position 1/N-terminal) = CoA + histone H2A S1-acetyl-L-lysine (position 1/N-terminal).

* **Reference, in format PMID:#######**

PMID:25619998
"N-terminal acetylation is among the most common protein modifications in eukaryotes and is mediated by evolutionarily conserved N-terminal acetyltransferases (NATs). NatD is among the most selective NATs; its only known substrates are histones H4 and H2A, containing the N-terminal sequence SGRGK in humans. "

* **Gene product name and ID to be annotated to this term**

Naa40/NatD 
https://www.pombase.org/gene/SPCC825.04c

* **Parent term(s)**

GO:0043998  histone H2A acetyltransferase activity
AND
GO:1990189 | peptide-serine-alpha-N-acetyltransferase activity

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

Also the equivalent  term for "histone H4S1 acetyltransferase activity"

**Comment by pgaudet** [comment]
I thought a similar term was requested recently, and that we had decided that this was a normal N-terminal acetylation, not a regulated PTM pr specific for histones. Also, the protein you propose to annotate to this term is not histone-specific. 

I dont think we should create this term.

**Comment by ValWood** [comment]
OK,  I do remember that now, I can add the histones as substrates.

**Comment by ValWood** [comment]
Naa40 is a histone-specific protein though, according to the paper I was annotating,
UniProt, https://www.uniprot.org/uniprotkb/Q86UY6/entry
and SGD https://www.yeastgenome.org/locus/YMR069W

**Comment by pgaudet** [comment]
Ah ok - also, I see there is a EC. 

However if we think of the scope of the histone code - should we also capture irreversible modifications as this one? 
(see the description here: https://enzyme.expasy.org/EC/2.3.1.257)

**Comment by ValWood** [comment]
I agree, the criteria should be if it is modified as part of the histone code

**Comment by ValWood** [comment]
hi @pgaudet I agreed with your rationale above, BUT the only problem this leaves us is that there are 2 ways to make the same annotation . This will result in inconsistent annotation, or the same annotation twice in different ways. So it might be better for curators to have the child instantiated to force consistency.

<img width="1256" alt="___GO_histone acetyltransferase" src="https://user-images.githubusercontent.com/7359272/221929881-f074f642-c2c1-41a2-bb5c-19c97c01485c.png">

**Comment by ValWood** [comment]
I know I didn't need to make the histone H2A  and H4 annotation, but those were already existing, and they are true.

**Comment by pgaudet** [comment]
It seems to me you should not use the high level terms
GO:0043998 histone H2A acetyltransferase activity
GO:0010485 histone H4 acetyltransferase activity

but rather the N-acetyltransferase term. We can add a comment if necessary.

**Comment by ValWood** [comment]
I think so. People wouldn't know otherwise. I suspect a lot of the annotations to this family are to these histone acetyltransferase terms  terms. The InterPro mapping is, for example
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR039949/
I would automatically search on histone acetyltransferase because this is specific, and we usually instantiate them.

**Comment by ValWood** [comment]
Although that mapping is weird, it seems much to specific for the family- the family os quite large
https://www.pombase.org/results/from/id/10b13d00-5713-4e93-872f-dd5933daed5d
