### ISSUE TITLE
RNA capping complex (GO:0098745) parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24966]
Dcp1-Dcp2 complex (GO:0098745)
is defined

Definition | Parents
-- | --
A protein complex consisting of a Dcp1 regulatory subunit and a Dcp2 catalytic subunit that has mRNA cap binding activity and is involved in decapping of nuclear-transcribed mRNA. [PMID:22323607]

It  is_a [RNA cap binding complex]
but not is_a 
mRNA cap binding complex (GO:0005845)

(I ask because i have annotation to both terms)

Would it make sense to rename to rename to   "Dcp2 mRNA decapping complex "
Add other synonyms

Edc1-Dcp1-Dcp2-Edc3 mRNA decapping complex PMID:29559651
Dcp1-Dcp2-Edc3 decapping complex PMID: 32396195

The decapping reaction is catalysed by a multi-protein complex formed by the Dcp2 catalytic subunit and its Dcp1 cofactor, a holoenzyme that is poorly active on its own and needs several accessory proteins (Lsm1-7 complex, Pat1, Edc1-2, Edc3 and/or EDC4) to be fully efficient. 
PMID: 30397101

**Comment by pgaudet** [comment]
see also #12853

**Comment by ValWood** [comment]
@pgaudet I think you worked on this term recently.

Should 
RNA capping complex (GO:0098745)
be is_a
mRNA cap binding complex (GO:0005845)
?

**Comment by ValWood** [comment]
I don't think so.
The meaning of  mRNA cap binding complex (GO:0005845) is supposed to be a specific complex, THE 
nuclear cap-binding protein complex
https://en.wikipedia.org/wiki/Nuclear_cap-binding_protein_complex

I don't think we should have a grouping term for any complex which binds to the cap, or it will get too confusing.
I'll make a new ticket with a plan.
