### ISSUE TITLE
Missing parent:  GO:0106335 tRNA (carboxymethyluridine(34)-5-O)-methyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24975]
* **GO term ID and label for which you request a new superclass**
GO:0106335 tRNA (carboxymethyluridine(34)-5-O)-methyltransferase activityv

id: GO:0106335
name: tRNA (carboxymethyluridine(34)-5-O)-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: carboxymethyluridine34 in tRNA + S-adenosyl-L-methionine = 5-(2-methoxy-2-oxoethyl)uridine34 in tRNA + S-adenosyl-L-homocysteine." [PMID:20123966, RHEA:43208]
xref: EC:2.1.1.229
xref: RHEA:43208
is_a: GO:0008168 ! methyltransferase activity
is_a: GO:0140101 ! catalytic activity, acting on a tRNA
created_by: hjd
creation_date: 2020-10-27T21:34:30Z

* **New superclass (parent) suggested**
Replace both current parents with single "tRNA methyltransferase activity  GO:0008175"

**Comment by ValWood** [comment]
-is_a: GO:0008168 ! methyltransferase activity
-is_a: GO:0140101 ! catalytic activity, acting on a tRNA
+is_a: GO:0008175 ! tRNA methyltransferase activity

**Comment by sjm41** [comment]
Thanks val!

**Comment by pgaudet** [comment]
Changed parent to GO:0016300 ! tRNA (uracil) methyltransferase activity
