### ISSUE TITLE
NTR: lysophosphatidylserine flippase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#24978]
Please provide as much information as you can: 

* **Suggested term label:**

lysophosphatidylserine flippase activity

* **Definition (free text)**

Catalysis of the movement of lysophosphatidylserine from the exoplasmic to the cytosolic leaftlet of a membrane, using energy from the hydrolysis of ATP

* **Reference, in format PMID:#######**

34645814

* **Gene product name and ID to be annotated to this term**
NEO1 cereiviae P40527

* **Parent term(s)**
GO:0140333 GO:0015247 ? I'm not sure of the exact classification.

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
Hi Antonia. NEO1 seems to be ATP-dependent which would make is a flippase or a floppase.

These have the comment
Comments
Nomenclature note. Flippases and floppases are ATP-dependent transbilayer lipid translocators. According to an extensively used, though not universal, nomenclature, they catalyze lipid transfer towards the inward monolayer (flippases) or towards the outward monolayer (floppases). Scramblases are ATP-independent, non-selective, inducing non-specific transbilayer movements across the membrane. The direction of the translocation should be taken into account for annotation (from the cytosolic to the exoplasmic leaftlet of a membrane).

Ao do you know if it's a flippase or a floppase? Can you provide the def and I should be able to add it later today.

**Comment by ValWood** [comment]
You said flippase so that answers 1 question!

**Comment by pgaudet** [comment]
Is this substrate specific for NEO1? ie do we need a new GO term, or should this substrate be captured as the input? 

Sorry I didnt have time to look at the paper very closely.

**Comment by ValWood** [comment]
Dnf1–Lem3 displays a preference for lyso-phospholipid substrate[50](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8514546/#CR50)

These data showed that the purified Neo1 was active and that the PS, PE, and lyso-PS are likely native substrates of the flippase.

We have terms for PS and PE. lyso-PS seems to be emerging as a major signalling molecule, so it might be useful to have this instantiated ?

Note:   for input or logical def:
lysophosphatidylserine ChEBI ID | CHEBI:68510

**Comment by ValWood** [comment]
Note also that  lysophosphatidylserine isn't a phosphatidylserine
<img width="560" alt="Screenshot 2023-02-23 at 10 38 25" src="https://user-images.githubusercontent.com/7359272/220883745-736518bd-5300-49c5-ad4d-3a3c0c6de37b.png">

**Comment by Antonialock** [comment]
so far for yeast I have substrates

**Comment by ValWood** [comment]
It would be a sibling of these terms, not a descendant:

<img width="560" alt="Screenshot 2023-02-23 at 10 38 25" src="https://user-images.githubusercontent.com/7359272/220884255-e43e3918-b95c-4783-b7f0-a46a10f265ce.png">

**Comment by Antonialock** [comment]
so far for yeat I have the following substrates
DRS2 - phosphatidylserine (with a note to read a paper saying it ahs minor activity on PE)
DNF1/2: glucosylceramide, phosphatidylcholine, phosphatidylethanolamine, and small amounts of phosphatidylserine (need to look at paper for lyso substrate)
DNF3: as yet haven't found a paper characterizing its substrate
NEO1: lysophosphatidylserine, phosphatidylethanolamine, and phosphatidylserine

**Comment by Antonialock** [comment]
filled in suggested def/name in the original post, I forgot those fields!

**Comment by ValWood** [comment]
@pgaudet  should I go ahead and add this? I think it makes sense based on the existence of sibling terms, and that this seems to be the major substrate?

**Comment by pgaudet** [comment]
Yes, go ahead

**Comment by ValWood** [comment]
+[Term]
+id: GO:0180013
+name: lysophosphatidylserine flippase activity
+namespace: molecular_function
+def: "Catalysis of the movement of a lysophosphatidylserine from the exoplasmic to the cytosolic leaftlet of a membrane, using energy from the hydrolysis of ATP." [PMID:34645814]
+is_a: GO:0140333 ! glycerophospholipid flippase activity
+intersection_of: GO:0140327 ! flippase activity
+intersection_of: has_primary_input CHEBI:68510 ! lysophosphatidylserine
+created_by: vw
+creation_date: 2023-02-23T14:32:13Z

**Comment by ValWood** [comment]
I added a logical def following the parent format.

I get this error
if [ -s 'tmp_referenced_chebi_nums_not_7_3.txt' ]; then echo "ERROR: CHEBI IDs should be mapped to pH 7.3:" && cat tmp_referenced_chebi_nums_not_7_3.txt && exit 1; else exit 0; fi
803
ERROR: CHEBI IDs should be mapped to pH 7.3:

I don't know what that means?
@pgaudet  any suggestions, or should i delete the logical def for now?

**Comment by ValWood** [comment]
that is lysophosphatidylserine(1−)
I tried it but it wasn't acceptable so I'll remove the logical def for now.

**Comment by balhoff** [comment]
@ValWood did you get the same error with CHEBI:68497? I expected it to pass. It has the chebi_ph7_3 subset tag.

**Comment by pgaudet** [comment]
@ValWood one way you cen tell is if there is a synonym with source UniPot in Chebi: 

CHEBI:68497 - lysophosphatidylserine(1−)


<img width="1128" alt="image" src="https://user-images.githubusercontent.com/4782928/220969668-a7cbe6ca-868c-4aa1-ba64-669ffef7e77b.png">

If the synonym is not there, then it's not in the pH 7.3 set of chemicals. 
Thanks, Pascale

**Comment by ValWood** [comment]
with CHEBI:68497 it was not accepted by protege as a CHEBI term so for now I removed the logical def

**Comment by ValWood** [comment]
@Antonialock  the term is in.

Thanks @balhoff  for the tip. I will add a logical def for this when I understand how ;)

**Comment by ValWood** [comment]
@pgaudet  does this CHEBI term need to be in the imports before I can add a logical def?

**Comment by pgaudet** [comment]
yes it has to be 

however I thought we had all the pH 7.3 terms

**Comment by pgaudet** [comment]
I can find it 

 'lysophosphatidylserine(1-)'

**Comment by ValWood** [comment]
Using the parent equivalence axion, and doing a direct substitution for the CHEBI compound part I get the red line of death:

<img width="637" alt="Screenshot 2023-02-24 at 13 50 26" src="https://user-images.githubusercontent.com/7359272/221194893-4a0f109e-f0d9-400c-8a9e-5b450346cf91.png">

**Comment by ValWood** [comment]
got it. I didn't think it would need quoting because it's a single string,

**Comment by pgaudet** [comment]
> I didn't think it would need quoting because it's a single string,


I think it's the parenthesis
