### ISSUE TITLE
NTR: [heme B transmembrane transporter activity]

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#24973]
Please provide as much information as you can: 

* **Suggested term label: heme B transmembrane transporter activity**

* **Definition (free text): Enables the transfer of heme B from one side of a membrane to the other**

* **Reference, in format PMID:32121449; PMID:15369674; PMID:20610401; PMID:9657107**

* **Gene product name and ID to be annotated to this term: Q9Y5Y0**

* **Parent term(s): GO:0015232; GO:0015291**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers: http://internal.rhea-db.org/rhea/75443. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information: **

Please consider creating a specific term for heme B to distinguish it from other heme types https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A30413.

Thank you very much for your help.
Nevila Hyka-Nouspikel

**Comment by edwong57** [comment]
Additional information - Here is some info for the new GO term request: heme B transmembrane transporter activity

 

CC CATALYTIC ACTIVITY:

Reaction=heme b(in) = heme b(out) [Rhea:75443]

Evidence={EXP|Ref.7, EXP|Ref.12}

PhysiologicalDirection=Left-to-right [Rhea:75444]

 

Supporting evidence: PMID:15369674; PMID:20610401

[55Fe]heme transport is tested in both papers

for 55Fe-Heme synthesis see PMID:2995365 -55FeHeme was synthesized by the nonenzymatic incorporation of [55Fe] (New England Nuclear) into 12 mg of protoporphyrin IX - CHEBI:57306 (Porphyrin Products, Logan, UT)

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=60344

 

other heme types relevant to mammalian proteins:

heme c cofactor cytochrome c1

https://www.uniprot.org/uniprotkb/Q9D0M3/entry

https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:61717

 

Thanks!

Nevila
