### ISSUE TITLE
Missing parent: GO:0042799 histone H4K20 methyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#24974]
* **GO term ID and label for which you request a new superclass**
GO:0042799 histone H4K20 methyltransferase activity

id: GO:0042799
name: histone H4K20 methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + histone H4 L-lysine (position 20) = S-adenosyl-L-homocysteine + histone H4 N6-methyl-L-lysine (position 20). This reaction is the addition of a methyl group to the lysine residue at position 20 of the histone H4 protein." [PMID:12086618]
is_a: GO:0140939 ! histone H4 methyltransferase activity

* **New superclass (parent) suggested**
histone lysine N-methyltransferase activity (GO:0018024)
or if that grouping term is going away (#24397), then:
protein-lysine N-methyltransferase activity (GO:0016279)

**Comment by pgaudet** [comment]
Will obsolete in #24397

**Comment by sjm41** [comment]
So, add "protein-lysine N-methyltransferase activity (GO:0016279)" as an additional parent instead?
