### ISSUE TITLE
Q difference between U2-type post-mRNA release spliceosomal complex (GO:0071008) & post-mRNA release spliceosomal complex (GO:0071014)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24982]
Hi  @krchristie  these 2 definitions sound the same to me, could  you clarify the differentia?

post-mRNA release spliceosomal complex (GO:0071014)
-- | --
A spliceosomal complex that is formed following the release of the spliced product from the post-spliceosomal complex and contains the excised intron and three snRNPs, including U5.

and its child
U2-type post-mRNA release spliceosomal complex (GO:0071008)
A spliceosomal complex that is formed following the release of the spliced product from the post-spliceosomal complex and contains the excised intron and the U2, U5 and U6 snRNPs.

**Comment by krchristie** [comment]
There are two types of spliceosomes, U2-type (the major spliceosome - present in all eukaryotes as far as I am aware) and U-12 (the minor spliceosome - lost independently in many different groups; S. cerevisiae does not have the minor spliceosome; humans do have it). The first term you mentioned, "post-mRNA release spliceosomal complex (GO:0071014)" is a parent term grouping the two specific complexes, either the U2-type or the U12-type. 

Here's the local ontology structure followed by the definitions with differences highlighted with bold italics:

-- post-mRNA release spliceosomal complex (GO:0071014)
--- [_is_a]_ U2-type post-mRNA release spliceosomal complex (GO:0071008)
--- [_is_a]_ U12-type post-mRNA release spliceosomal complex (GO:0071019)

* post-mRNA release spliceosomal complex (GO:0071014)
** A spliceosomal complex that is formed following the release of the spliced product from the post-spliceosomal complex and contains the excised intron and **_three snRNPs, including U5_**.

* U2-type post-mRNA release spliceosomal complex (GO:0071008)
** A spliceosomal complex that is formed following the release of the spliced product from the post-spliceosomal complex and contains the excised intron and the **_U2_**, U5 and **_U6_** snRNPs.

* U12-type post-mRNA release spliceosomal complex (GO:0071019)
** A spliceosomal complex that is formed following the release of the spliced product from the post-spliceosomal complex and contains the excised intron and the **_U12_**, U5 and **_U6atac_** snRNPs.

**Comment by ValWood** [comment]
Got it.
It would be clearer for curators if I changed the 
"and three snRNPs, including U5"
to
to and three snRNPs U2, U5 and either U6 or U6atac

so that anybody comparing GO:0071014 and GO:007100 can easily see the difference.

This is also useful information for the U12 type spliceosome:
The U12-type spliceosome is required for removal of the rarer class of [eukaryotic](https://en.wikipedia.org/wiki/Eukaryotic) [introns](https://en.wikipedia.org/wiki/Introns) (AT-AC, U12-type)

U6atac only seems to be present in Metazoa and plants so I could add a taxon restriction to this term too.

**Comment by krchristie** [comment]
> Got it. It would be clearer for curators if I changed the "and three snRNPs, including U5" to to and three snRNPs U2, U5 and either U6 or U6atac

If you change the definition of the grouping term, you would need to say "and three snRNPs either U2 or U12, U5, and either U6 or U6atac"


> so that anybody comparing GO:0071014 and GO:007100 can easily see the difference.
> 
> This is also useful information for the U12 type spliceosome: The U12-type spliceosome is required for removal of the rarer class of [eukaryotic](https://en.wikipedia.org/wiki/Eukaryotic) [introns](https://en.wikipedia.org/wiki/Introns) (AT-AC, U12-type)
> 
> U6atac only seems to be present in Metazoa and plants so I could add a taxon restriction to this term too.

**Comment by krchristie** [comment]
> This is also useful information for the U12 type spliceosome: The U12-type spliceosome is required for removal of the rarer class of [eukaryotic](https://en.wikipedia.org/wiki/Eukaryotic) [introns](https://en.wikipedia.org/wiki/Introns) (AT-AC, U12-type)
> 
> U6atac only seems to be present in Metazoa and plants so I could add a taxon restriction to this term too.

What have you checked to determine that U6atac is present only in Metazoa and plants? At some point I did some PAINT work on splicing and read some papers specifically about loss of the minor spliceosome. The simplest explanation seemed to be that an ancient ancestor had both spliceosomes but that the minor one has been lost independently many times. While cerevisiae does not have it, I am not sure that ALL fungi do NOT have the minor spliceosome.

**Comment by ValWood** [comment]
Rfam species distribution https://rfam.org/family/RF00619#tabview=tab4

**Comment by ValWood** [comment]
Also I'm not aware of  AT-AC introns  in any yeast/fungi, so if it did turn up it would be very novel. So I concluded that based on existing knowledge we could say never in fungi, but we could also keep as never in ascomycota.

There was also the slight possibility that this  U6atac exists but it very divergent in yeast, but I doscounted that based on the unusual phylogenetic distribution. If you can see  somthing conserved plants and metazoa but not in yeast  which are closer to metazoa the loss from the entire kingdom is the most parsimonious explanation.

**Comment by krchristie** [comment]
> Also I'm not aware of AT-AC introns in any yeast/fungi, so if it did turn up it would be very novel. So I concluded that based on existing knowledge we could say never in fungi, but we could also keep as never in ascomycota.
>
> There was also the slight possibility that this U6atac exists but it very divergent in yeast, but I doscounted that based on the unusual phylogenetic distribution. If you can see somthing conserved plants and metazoa but not in yeast which are closer to metazoa the loss from the entire kingdom is the most parsimonious explanation.

I do not think it is appropriate to say "never in fungi". I did PAINT on splicing factors. It is well established that there were multiple losses of the minor spliceosome.

Dávila López M, Rosenblad MA, Samuelsson T. Computational screen for spliceosomal RNA genes aids in defining the phylogenetic distribution of major and minor spliceosomal components. Nucleic Acids Res. 2008 May;36(9):3001-10. doi: 10.1093/nar/gkn142. Epub 2008 Apr 4. PMID: 18390578; PMCID: PMC2396436.

Bartschat S, Samuelsson T. U12 type introns were lost at multiple occasions during evolution. BMC Genomics. 2010 Feb 11;11:106. doi: 10.1186/1471-2164-11-106. PMID: 20149226; PMCID: PMC2846911.


![PMID-18390578-spliceosomePhylogeny](https://user-images.githubusercontent.com/10533218/221263447-888b2025-fdc3-4a51-8d11-601edb050a40.jpg)
