### ISSUE TITLE
Missing parent:GO:0106407 Glc2Man9GlcNAc2 oligosaccharide glucosidase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24984]
* **GO term ID and label for which you request a new superclass**

I'm not 100% sure about this but glucosidase II 
is
GO:0106407 Glc2Man9GlcNAc2 oligosaccharide glucosidase activity

I am picking up  automated mappings to [alpha-glucosidase activity](https://www.pombase.org/term/GO:0090599)
so I assume that 
Glc2Man9GlcNAc2 oligosaccharide glucosidase activity
should be is_a alpha-glucosidase activity

This appears to be the Rhea entry for 
https://www.rhea-db.org/rhea/55996
Glc2Man9GlcNAc2 oligosaccharide glucosidase 

<img width="1196" alt="Screenshot 2023-02-23 at 08 27 26" src="https://user-images.githubusercontent.com/7359272/220856162-536fdeb4-e158-4b2e-bfc3-8dbf089b7044.png">

@kaxelsen  is this correct?

**Comment by pgaudet** [comment]
The term def xref talk about glucosidase I

https://pubmed.ncbi.nlm.nih.gov/30389790/

The term has no annotations, no cross references to RHEA or EC - a bit suspicious.

**Comment by pgaudet** [comment]
You had opened another ticket about these 
#17674

**Comment by ValWood** [comment]
- GO:0106407 Glc2Man9GlcNAc2 oligosaccharide glucosidase activity  seems to be quite a new term  2021-10-30which is why it has no annotations? 
- The synonym  (broad) is Glucosidase II (I was annotating  glucisidase II)
- The paper I  was looking at  Glucosidase II (GII) plays a key role in glycoprotein biogenesis in the endoplasmic reticulum (ER). It is responsible for the sequential removal of the two innermost glucose residues from the glycan (Glc(3)Man(9)GlcNAc(2)) transferred to Asn residues in proteins.  says "Glucosidase II (GII) plays a key role in glycoprotein biogenesis in the endoplasmic reticulum (ER). It is responsible for the sequential removal of the two innermost glucose residues from the glycan (Glc(3)Man(9)GlcNAc(2)) transferred to Asn residues in proteins. "
- 
-

**Comment by ValWood** [comment]
This might be helpful
Glucosidase II ( a gene product) catalyses 2 steps
https://user-images.githubusercontent.com/7359272/62307214-1bafe480-b47b-11e9-9e18-8a2849513598.jpg

Maybe one problem is that 
Glc2Man9GlcNAc2 oligosaccharide glucosidase activity (GO:0106407)
is_a
Glc3Man9GlcNAc2 oligosaccharide glucosidase activity (GO:0004573)

this seems incorrect because these are sequential reactions? See figure above.

**Comment by ValWood** [comment]
@suzialeksander I might have given you incorrect information about updating ROT2 to
GO:0106407 | Glc2Man9GlcNAc2 oligosaccharide glucosidase activity, please follow this ticket to see it's fate.

**Comment by kaxelsen** [comment]
The EC list have the entries EC 3.2.1.106 and EC 3.2.1.207. 
EC 3.2.1.106 has the alternative name: trimming glucosidase I, and has the reaction Glc3Man9GlcNAc2-[protein] + H2O = Glc2Man9GlcNAc2-[protein] + β-D-glucopyranose, RHEA:55988. It is linked to MOGS_HUMAN, Q13724 and GCS1_SCHPO, O14255 and others

EC 3.2.1.207 has AN trimming glucosidase II, reactions:
(1) Glc2Man9GlcNAc2-[protein] + H2O = GlcMan9GlcNAc2-[protein] + β-D-glucopyranose, RHEA:55996
(2) GlcMan9GlcNAc2-[protein] + H2O = Man9GlcNAc2-[protein] + β-D-glucopyranose, RHEA:56000
and it linked to GANAB_HUMAN, Q14697 and GLU2A_SCHPO, Q9US55 and others

**Comment by pgaudet** [comment]
@ValWood based on @kaxelsen 's feedback, do you have actions to propose?

**Comment by ValWood** [comment]
She we have
1.

EC 3.2.1.106

RHEA	55988
H2O + N4-(alpha-D-Glc-(1->2)-alpha-D-Glc-(1->3)-alpha-D-Glc-(1->3)-alpha-D-Man-(1->2)-alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->6)]-alpha-D-Man-(1->6)]-beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-beta-D-GlcNAc)-L-asparaginyl-[protein] = beta-D-glucose + N4-(alpha-D-Glc-(1->3)-alpha-D-Glc-(1->3)-alpha-D-Man-(1->2)-alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->6)]-alpha-D-Man-(1->6)]-beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-beta-D-GlcNAc)-L-asparaginyl-[protein]


GO:0004573 Glc3Man9GlcNAc2 oligosaccharide glucosidase activity
Catalysis of the exohydrolysis of the non-reducing terminal glucose residue in the mannosyl-oligosaccharide Glc(3)Man(9)GlcNAc(2).

Synonym trimming glucosidase 1


And
2.
EC 3.2.1.207 
has AN trimming glucosidase II, reactions:

(1) Glc2Man9GlcNAc2-[protein] + H2O = GlcMan9GlcNAc2-[protein] + β-D-glucopyranose, RHEA:55996
H2O + N4-(alpha-D-Glc-(1->3)-alpha-D-Glc-(1->3)-alpha-D-Man-(1->2)-alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->6)]-alpha-D-Man-(1->6)]-beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-beta-D-GlcNAc)-L-asparaginyl-[protein] = beta-D-glucose + N4-(alpha-D-Glc-(1->3)-alpha-D-Man-(1->2)-alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->6)]-alpha-D-Man-(1->6)]-beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-beta-D-GlcNAc)-L-asparaginyl-[protein]


(2) GlcMan9GlcNAc2-[protein] + H2O = Man9GlcNAc2-[protein] + β-D-glucopyranose, 
RHEA:56000
H2O + N4-(alpha-D-Glc-(1->3)-alpha-D-Man-(1->2)-alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->6)]-alpha-D-Man-(1->6)]-beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-beta-D-GlcNAc)-L-asparaginyl-[protein] = beta-D-glucose + N4-(alpha-D-Man-(1->2)-alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->3)-[alpha-D-Man-(1->2)-alpha-D-Man-(1->6)]-alpha-D-Man-(1->6)]-beta-D-Man-(1->4)-beta-D-GlcNAc-(1->4)-beta-D-GlcNAc)-L-asparaginyl-[protein] (N-glucan mannose isomer 9A1,2,3B1,2,3)


Go seems to have 1 term to cover both reactions:
GO:0106407   
Glc2Man9GlcNAc2 oligosaccharide glucosidase activity
Catalysis of the reaction: Glc(2)Man(9)GlcNAc(2)-[protein] + H2O = GlcMan(9)GlcNAc(2)-[protein] + beta-D-glucopyranose. PMID:30389790
Comments
Trims Glc alpha 1,3 Glc bond in Glc2Man9GlcNAc2 oligosaccharide in inmature glycoproteins.


So my question was abiut 2.
 should GO:0106407  have
GO:0090599    alpha-glucosidase activity
As a parent 
Catalysis of the hydrolysis of terminal, non-reducing alpha-linked alpha-D-glucose residue with release of alpha-D-glucose.

I now see this mapping comes from another term used to describe Glucosidase II (this is used by most of the MODs, the mapping is multiply supported)

GO:0033919    glucan 1,3-alpha-glucosidase activity 
Catalysis of the hydrolysis of terminal (1->3)-alpha-D-glucosidic links in 1,3-alpha-D-glucans.



I'm completely lost here! I'm just trying to figure why we have annotations  for Glycosides II in these 2 different branches

Is it 
1) and annotation problem
2) an ontology problem or
3) not a problem

<img width="239" alt="Screenshot 2023-10-28 at 08 52 19" src="https://github.com/geneontology/go-ontology/assets/7359272/48b015e8-8ab3-4d5c-b11e-2aad615a6c36">

**Comment by ValWood** [comment]
Looking at these, are GO:0033919 and GO:0106407 2 ways of saying the same thing.

https://pubmed.ncbi.nlm.nih.gov/10929008/ is used for GO:0033919

https://www.pombase.org/reference/PMID:19605557
is used for 
GO:0106407 | Glc2Man9GlcNAc2 oligosaccharide glucosidase activity

**Comment by pgaudet** [comment]
Hi @ValWood 
You requested GO:0106407 here #17674, with broad synonym glycosidase II. 

Maybe we dont need the specific substrate? These terms dont have the same parents, and it looks like the nomenclature used is different. It's quite confusing

<img width="410" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/03b0c364-6bdc-4ac0-b8af-7546163d2bd5">

**Comment by ValWood** [comment]
I don't know, we have other precise substrates for the pathway in various places, 
e.g
alg8 https://www.pombase.org/term/GO:0042283
dpm1 https://www.pombase.org/term/GO:0004582
alg3 https://www.pombase.org/term/GO:0052925
gpt1 https://www.pombase.org/term/GO:0003980

and otherwise everything becomes 
"alpha-glucosidase part of protein glycosylation"
It will be difficult to build a pathway model without the specificity.
(that would be a  bit like describing all of the TCA cycle as oxidoreductase)

Here I am only thinking of the major conserved gapthways of glycosylation in the ER and GPI anchor biosynthesis.
I would not like to lose the  specificity we have already curated.
But we should see what  Frederique thinks is the best approach.

**Comment by ValWood** [comment]
Glucosidase I: 
An alpha-glucosidase that removes the terminal alpha-1,2-linked glucose residue from N-linked oligosaccharides.
represented in GO by by 
GO:0004573 Glc3Man9GlcNAc2 oligosaccharide glucosidase activity
Catalysis of the exohydrolysis of the non-reducing terminal glucose residue in the mannosyl-oligosaccharide Glc(3)Man(9)GlcNAc(2).

Glucosidase II
An alpha-glucosidase that sequentially removes the two innermost alpha-1,3-linked glucose residues from N-linked oligosaccharides.
represented in GO by
GO:0106407 Glc2Man9GlcNAc2 oligosaccharide glucosidase activity (gls2)
Catalysis of the reaction: Glc(2)Man(9)GlcNAc(2)-[protein] + H2O = GlcMan(9)GlcNAc(2)-[protein] + beta-D-glucopyranose. PMID:30389790


CURRENT ORGANIZATION

<img width="482" alt="Screenshot 2024-07-16 at 07 29 56" src="https://github.com/user-attachments/assets/a8cc74ef-6a26-4490-887d-59f803179dec">

ACTIONS
1. 
GO:0106407 Glc2Man9GlcNAc2 oligosaccharide glucosidase activity (gls2)
is under transferase, but it is a hydrolase
move to correct parent “ alpha glucosidase”

Note that Rhea has activities for the 2 steps catalysed by this reaction 
https://www.rhea-db.org/rhea/55996 
https://www.rhea-db.org/rhea/56000 
Which is probly why it is not currently mapped to Rhea
I will open a new ticket to deal with this as part of RHe alignment. For this ticket I only want to get the terms in the correct locations in the graph.

2.
GO:0102704 GDP-Man:Man2GlcNAc2-PP-dolichol alpha-1,6-mannosyltransferase activity
should be is_a 
GO:0033164	 glycolipid 1,6-alpha-mannosyltransferase activity
(note that this term is also used for bacterial “phosphatidylinositol mannoside biosynthesis“)
glycolipid 1,6-alpha-mannosyltransferase is a correct grouping term for both, but might be an unecessary grouping term. Right now I just want to 
ensure that there is only a single way to annotate GDP-Man:Man2GlcNAc2-PP-dolichol alpha-1,6-mannosyltransferase (currently both terms are used)

3. GO:0004573 Glc3Man9GlcNAc2 oligosaccharide glucosidase
should be is_a “alpha glucosidase” ( is already a glucosidase, but it is alpha (1,2)

4. 
remove alpha-glucosidase II as a 
related synonym of alpha-1,4-glucosidase activity
(alpha-glucosidase II is alpha-1,3 so it isn't helpful for this to come up in a search).
