### ISSUE TITLE
NTR: [Chloride Ion Import into cell]

### ISSUE THREAD

**Issue by sharan-gh** [geneontology/go-ontology#24993]
Please provide as much information as you can: 

* **Suggested term label:**
Chloride Ion Import into cell

* **Definition (free text)**
The directed movement of chloride ions into a cell.

* **Reference, in format PMID:#######**
PMID: 24431435

* **Gene product name and ID to be annotated to this term**
clh-3 (WBGene00000530)

* **Parent term(s)**
has parent import into cell [GO:0098657] 
has parent chloride transport [GO:0006821]

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
clh-3 has already been annotated with the MF GO:0005247 voltage-gated chloride channel activity.
Do we want to
1. Create a BP for what appears to be a single step process?
2. To specify the direction of flow in the term? Or should the direction information be specified during annotation?
Note that we do have a term GO:0098719 sodium ion import across plasma membrane.

**Comment by sharan-gh** [comment]
My thought was that it would be nice to have the direction specified in the term (an MF term), since there are other terms that explicitly say import vs. export. Also, it seems there are cases where voltage-gated chloride efflux is involved in depolarizing a neuron (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5811518/).

**Comment by sharan-gh** [comment]
Right, I see GO:0098718 is a BP. I think if this is not convenient from a GO point of view, it's not hugely consequential for CeN-CAM to leave it as is.

**Comment by raymond91125** [comment]
GO's current guideline is that NTR is assessed by specific use cases; we are reluctant to create terms that may be useful. Thanks for your suggestion.
