### ISSUE TITLE
Review: GO:0036260 RNA capping and descendants

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#24991]
Please provide as much information as you can:

* **GO term ID and Label**

GO:0036260 RNA capping and descendants

* **Reason for deprecation** Put an x in the appropriate box: 

 - [ ] The reason for obsoletion is that this term represents a molecular function.
 

* **"Replace by" term (ID and label)**

If all annotations can safely be moved to that term

move to
GO:0006396   RNA processing

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation
(also check that appropriate MF term is annotated)

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
@sjm41  @pgaudet   does this sound OK for these processes, should be captured as MF + appropriate RNA processing term?

**Comment by sjm41** [comment]
Not sure.
"GO:0036260 RNA capping" is defined as "The **sequence of enzymatic reactions** by which a cap structure is added to the 5' end of nascent RNA polymerase transcripts. Examples of RNA capping include 7-methyl-G caps found on all RNA polymerase II transcripts and nucleotide-containing cofactor caps, such as NAD(H) or FAD, found on bacterial trancripts."
The "sequence of enzymatic reactions" bit suggest this is a bona fide process term?

But I agree that the specific child terms look like MFs.

**Comment by ValWood** [comment]
OK  I will keep RNA capping  and deal with the children.
So is capping a multispet process? (I haven't looked at this in detail yet)

**Comment by sjm41** [comment]
So is capping a multispet process? (I haven't looked at this in detail yet)

Right. That's what the current def says, and here's a quote from PMID: 27317694 ("mRNA capping: biological functions and applications"):

_**Nuclear RNA capping** Capping is the first modification made to RNA polymerase II-transcribed RNA and takes place co-transcriptionally in the nucleus as soon as the first 25–30 nts are incorporated into the nascent transcript. Three enzymatic activities are required to generate the cap 0 structure, namely, RNA triphosphatase (TPase), RNA guanylyltransferase (GTase) and guanine-N7 methyltransferase (guanine-N7 MTase. Each of these enzyme activities carries out an essential step in the conversion of the 5′ triphosphate of nascent RNA to the cap 0 structure._

**Comment by ValWood** [comment]
So clearly  capping isn't single step.

I just  removed the child GO:0034471   ncRNA 5'-end processing 
which was wrong (ncRNA 5'-end processing  is broader) here https://github.com/geneontology/go-ontology/issues/26208

Now there will be 2 children or RNA capping
GO:0036261 7-methylguanosine cap hypermethylation
Hypermethylation of the 7-(mono)methylguanosine (m(7)G) cap structure at the 2' position of the guanosine residue to convert a mono-methylated cap to a 2,2,7-trimethylguanosine cap structure. This type of cap modification occurs on small nuclear RNAs (snRNAs) and small nucleolar RNAs (snoRNAs) and is dependent on prior guanine-N7 methylation. PMID:11983179 PMID:18775984

and
GO:0009452 7-methylguanosine RNA capping
The sequence of enzymatic reactions by which the 5' cap structure, an inverted 7-methylguanosine linked via a 5'-5' triphosphate bridge (m7G(5')ppp(5')X) to the first transcribed residue, is added to a nascent transcript. 

Q
The first one GO:0036261 7-methylguanosine cap hypermethylation
should probably be described as a MF term (@pgaudet  @sjm41 do you agree)?

Q
GO:0009452 7-methylguanosine RNA capping
is clearly a process, it describes a sequence of reactions. 
BUT if  GO:0036261 7-methylguanosine cap hypermethylation was obsoleted there  would then be only one child of RNA capping.
What should the siblings  be?

**ACTIONS SO FAR **
- [ ] make GO:0036260  RNA capping a descendent of 
GO:0000966   RNA 5'-end processing

**Comment by pgaudet** [comment]
Covered by other tickets
