### ISSUE TITLE
NTR: [Neuropeptide-ligand activity]

### ISSUE THREAD

**Issue by sharan-gh** [geneontology/go-ontology#24992]
Please provide as much information as you can: 

* **Suggested term label:**
Neuropeptide-ligand activity

* **Definition (free text)**
Activity of any secreted gene product with the capacity to bind cognate receptors to mediate functional changes in a neuron.

* **Reference, in format PMID:#######**
PMID: 18806786

* **Gene product name and ID to be annotated to this term**
flp-10 (WBGene00001453)
flp-17 (WBGene00001460)

* **Parent term(s)**
has parent receptor ligand activity [GO:0048018]

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

Ringstadt & Horvitz 2008:

"We also tested peptides for EGL-6 agonist activity in vitro. The coupling of GPCRs to G protein–activated inwardly rectifying K+ (GIRK) channels in heterologous expression systems has been used to match ligands to orphan GPCRs (for example, in ref. 27). We coexpressed EGL-6 and GIRKs in Xenopus laevis oocytes and tested pools of synthetic peptides corresponding to predicted and observed C. elegans neuropeptides25,26 for the ability to activate GIRK conductance using a two-electrode voltage clamp. We tested 55 peptides in five pools (Supplementary Table 2 online). Two pools, B and D, evoked inward currents (Fig. 4c) that were observed only in oocytes coexpressing EGL-6 and GIRKs (data not shown). These pools therefore contained EGL-6 agonists. Pool B contained the predicted flp-10 peptide product QPKARSGYIRFamide, and pool D contained both predicted flp-17 peptide products, KSAFVRFamide and KSQYIRFamide. Omitting these peptides from the active pools eliminated agonist activity; furthermore, each of these peptides could function as agonists when applied individually (Fig. 4d). flp-10 and flp-17 peptides were effective at nanomolar concentrations in this assay (Fig. 4e,f)....We concluded that flp-10 and flp-17 encode ligands for the EGL-6 receptor, because (i) the egg-laying defects caused by flp-10 and flp-17 overexpression required the egl-6 receptor gene in vivo, and (ii) flp-10 and flp-17 peptides activated the EGL-6 receptor in vitro."

**Comment by pgaudet** [comment]
Label should be neuropeptide activity

**Comment by raymond91125** [comment]
There is GO:0071855 neuropeptide receptor binding (DEF: Binding to a neuropeptide receptor.); should we also have neuropeptide activity?

Also, with regard to definition, neuropeptide binds to receptors on cells other than neurons -- EGL-6 is expressed in GLR, glial-like cells.

**Comment by sharan-gh** [comment]
I think GO:0071855 works well for us.

**Comment by raymond91125** [comment]
Good. We are all set then. Thanks.

**Comment by vanaukenk** [comment]
@sharan-gh @raymond91125 

Is 'neuropeptide receptor binding' enough of a differentia for what we need in the models?  We want to model the activity of gene products like FLP-17 that specifically act as ligands in contrast to other gene products that can bind receptors, e.g. to traffic them to the plasma membrane.

I'd still vote for a new 'neuropeptide activity' MF term.

**Comment by raymond91125** [comment]
It seems to me that we have a dichotomy in the ontology; it's not clear which branch should one take.
![image](https://user-images.githubusercontent.com/619520/222297621-42cbb3f4-071e-405f-a40f-cfee07f95596.png)

**Comment by vanaukenk** [comment]
I think we want this new term to be a child of 'receptor ligand activity' since we are describing a ligand activity.  It will then have a receptor binding parent, as well.

**Comment by ukemi** [comment]
+1, because receptor binding does not have to be a ligand the way GO has defined ligand activity.

**Comment by raymond91125** [comment]
It seems to me that receptor ligand activity 'implies' a BP whereas receptor binding is a more straight forward MF. Either annotation should probably be paired with a BP to make the annotation complete (if that's known). As the ontology is now, we have two separate branches for one to choose from which does not seem good.
@pgaudet what do you think?

**Comment by raymond91125** [comment]
How about term name "neuropeptide receptor-ligand activity", definition: "The receptor ligand activity of any peptide gene product made in, and secreted from a neuron." [DOI: 10.5772/intechopen.73504].
There is GO:0005184 neuropeptide hormone activity. But the definition includes central nervous system and brain, which seems unnecessarily restrictive. Otherwise this term seems to fit the proposal.

**Comment by pgaudet** [comment]
@raymond91125 I think you are right, GO:0005184 neuropeptide hormone activity's definition should be widened. The wiki page it links to (https://en.wikipedia.org/wiki/Neurohormone) also seems broader. 

Maybe we can remove 'hormone' from the term label. 

Thanks, Pascale

**Comment by raymond91125** [comment]
More thoughts:

The term neuropeptide hormone activity is_a hormone activity and thus must have (at least in part) action that is long range (from one organ to another, whole body). But its definition is confusing to me.

`The action characteristic of a neuropeptide hormone, any peptide hormone that acts in the central nervous system. A neuropeptide is any of several types of molecules found in brain tissue, composed of short chains of amino acids; they include endorphins, enkephalins, vasopressin, and others. They are often localized in axon terminals at synapses and are classified as putative neurotransmitters, although some are also hormones.`

If it "acts in the central nervous system", then it's not necessarily whole body. And "some are also hormones" also violates the is_a hormone relationship.

Thus I think this term has problems on its own and let's not use it for neuropeptide activity. It may be considered as a sub-type once its ambiguities are clarified in a separate ticket.

@sharan-gh Please consider my proposal for term label and definition.

**Comment by sharan-gh** [comment]
I think the new term definition works better than the original. I defer to ontology editors on parentage issues.

**Comment by raymond91125** [comment]
A good general for neuropeptide ref PMID:21922398

+[Term]
+id: GO:0160041
+name: neuropeptide activity
+namespace: biological_process
+def: "The receptor ligand activity of any polypeptide expressed in, and secreted from a neuron." [PMID:18806786, PMID:21922398]
+is_a: GO:0048018 ! receptor ligand activity
+relationship: has_part GO:0071855 ! neuropeptide receptor binding
+created_by: rynl
+creation_date: 2023-03-10T01:05:22Z

**Comment by pgaudet** [comment]
@raymond91125 I think your definition is missing "acting on neural substrates" - otherwise, maybe it will be confusing that any peptide secreted from a neuron is a neuropeptide. 


WRT 'neuropeptide hormone activity', you wrote 
> Thus I think this term has problems on its own and let's not use it for neuropeptide activity. It may be considered as a sub-type once its ambiguities are clarified in a separate ticket.


Did you create that ticket? Because having both terms is a bit confusing. 

Thanks, Pascale

**Comment by raymond91125** [comment]
Neuropeptides acts not only on neurons (is that what you mean b neural substrate?); receptors are expressed widely, e.g. <https://www.ncbi.nlm.nih.gov/books/NBK27941/>. The definition "The receptor ligand activity of any polypeptide expressed in, and secreted from a neuron" is restricted by the parent class receptor ligand activity "The activity of a gene product that interacts with a receptor to effect a change in the activity of the receptor", thus they cannot be any activity of any peptide secreted from a neuron. Neuropeptide is a rather broad class of genes, there are many 'exceptions to the rules', if you will. The definition I proposed seems to be of broad consensus (see https://en.wikipedia.org/wiki/Neuropeptide).
Some neuropeptides are also considered hormones, e.g. eclosion hormone in flies. And I think that may be the reason we have the neuropeptide hormone activity term. This view would make it is_a neuropeptide activity. If no one objects, I can just make the subsumption happen without further discussions.

**Comment by pgaudet** [comment]
No objections, thanks for the explanation.
