### ISSUE TITLE
Textual definition update: regulation of membrane depolarization (GO:0003254)

### ISSUE THREAD

**Issue by sharan-gh** [geneontology/go-ontology#24995]
* **GO term ID and label for which you request a definition update**
Regulation of membrane depolarization(GO:0003254)

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
No proposal for a new definition as yet - just a request to clarify the difference between rate and frequency in the definition. I am happy to propose new definitions for this and related terms if appropriate. 

* **Reference(s)**
PMID:nnnnnnn

* **Additional information**

**Comment by raymond91125** [comment]
Definition: Any process that modulates the rate, frequency or extent of membrane depolarization. Membrane depolarization is the process in which membrane potential changes in the depolarizing direction from the resting potential, usually from negative to positive.
Rate is regarding the rate of change; frequency is about how frequent the occurrence; extent is about the magnitude and duration.

**Comment by pgaudet** [comment]
Is there an action here? This is the standard definition for regulation.

**Comment by raymond91125** [comment]
@sharan-gh Can we close this issue or do you have a proposal to make?

**Comment by sharan-gh** [comment]
I think the use cases for splitting these are maybe too narrow to justify new terms.
