### ISSUE TITLE
Migrate GO editors to Protege 5.6.1

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#25019]
There is a new release of Protege which includes ELK 0.5 as well as dedicated support for ID ranges files. It also uses the latest OWL API, inline with the latest ROBOT and ODK. To avoid inconsistent file serializations, we should migrate to all of these simultaneously (Protege 5.6.1, ODK 1.4): editors' desktops, this repo QC actions, and GO pipeline.

cc @kltm

**Comment by kltm** [comment]
@balhoff Testing failed with https://build.geneontology.org/job/geneontology/job/pipeline/job/master/716/execution/node/230/log/
If you can't see that, let me know and I'll get the permissions straightened.

**Comment by kltm** [comment]
@pgaudet Putting this in misc for now.

**Comment by balhoff** [comment]
@kltm I think that pipeline failure is due to stricter handling from the new OWL API for bad term IRIs which were in reacto.owl. Fix is here: https://github.com/geneontology/pathways2GO/pull/234

**Comment by balhoff** [comment]
@pgaudet here's an issue with term IDs to follow: https://github.com/protegeproject/protege/issues/1108

**Comment by kltm** [comment]
@balhoff I believe I've propagated this change to all producing pipelines.
