### ISSUE TITLE
NTR: [egg deposition]

### ISSUE THREAD

**Issue by sharan-gh** [geneontology/go-ontology#25018]
Please provide as much information as you can: 

* **Suggested term label:**
egg deposition

* **Definition (free text)**
The multicellular organismal reproductive process that results in the movement of an egg from within an organism into the external environment.

* **Reference, in format PMID:#######**
PMID:31164023
PMID:18050396

* **Gene product name and ID to be annotated to this term**
unc-54 (WBGene00006789)

* **Parent term(s)**
is_a multicellular organismal reproductive process (GO:0048609), part_of oviposition/egg-laying behavior (GO:0018991)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
Proposed to delineate nervous system processes involved egg-laying behavior (GO:0018991) from the mechanics of egg deposition.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160027
+name: egg deposition
+namespace: biological_process
+def: "The multicellular organismal reproductive process that results in the movement of an egg from within an organism into the external environment." [PMID:18050396, PMID:31164023]
+is_a: GO:0048609 ! multicellular organismal reproductive process
+created_by: rynl
+creation_date: 2023-03-01T18:56:53Z
