### ISSUE TITLE
tRNA-dihydrouridine synthase EC xrefs to add

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25028]
id: GO:0102267
name: tRNA-dihydrouridine20b synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: a 5,6-dihydrouracil20b in tRNA + NAD(P) <=> H+ + a uracil20b in tRNA + NAD(P)H." [EC:1.3.1.90, GOC:pz]
xref: MetaCyc:RXN-12476
is_a: GO:0017150 ! tRNA dihydrouridine synthase activity

- [x] add EC:1.3.1.90 "tRNA-dihydrouridine(20a/20b) synthase [NAD(P)(+)]."

===

id: GO:0102262
name: tRNA-dihydrouridine16 synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: a 5,6-dihydrouracil16 in tRNA + NAD(P) <=> H+ + a uracil16 in tRNA + NAD(P)H." [EC:1.3.1.88, GOC:pz]
xref: MetaCyc:RXN-12454
is_a: GO:0017150 ! tRNA dihydrouridine synthase activity
is_a: GO:0140101 ! catalytic activity, acting on a tRNA

- [x] add EC:1.3.1.88 "tRNA-dihydrouridine(16/17) synthase [NAD(P)(+)]. "

**Comment by pgaudet** [comment]
Hi @edwong57 
A few more things I just noticed:

- [ ] reactions should have "=" and not "<=>" 

Also, it looks like we are missing some RHEA xrefs: https://www.rhea-db.org/rhea?query=ec%3A1.3.1.88 (2 RHEA per term, one for the NAD and one for the NADP-dependent reaction), both 'narrowMatch' 
- [ ] We cannot use the same defxref for several terms, so please remove EC:1.3.1.88 from the **defxref** of GO:0102262  and GO:0102263. 
- [ ] EC:1.3.1.88 should have source= skos:broadMatch in the cross references of GO:0102262  and GO:0102263. 
- [ ] likewise for terms with EC:1.3.1.90
- [ ] and please add RHEA xrefs: https://www.rhea-db.org/rhea?query=ec%3A1.3.1.90 

Thanks, Pascale
