### ISSUE TITLE
GO:0061733 'peptide-lysine-N-acetyltransferase activity': add RHEA xref

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25036]
[RHEA:53916](https://www.rhea-db.org/rhea/53916)
an acyl-CoA + L-lysyl-[protein] = CoA + H+ + N6-acyl-L-lysyl-[protein]

**Comment by sjm41** [comment]
I think the RHEA xref here should be:
[RHEA:45948](https://www.rhea-db.org/rhea/45948)
acetyl-CoA + L-lysyl-[protein] = CoA + H+ + N6-acetyl-L-lysyl-[protein]

....which RHEA says corresponds to EC 2.3.1.48 histone acetyltransferase....which is already an xref on GO:0004402
histone acetyltransferase activity

**Comment by pgaudet** [comment]
@amorgat @kaxelsen 
Can you please clarify? The RHEA reactions are described for a generic protein, not specifically for histone. Which GO term should we link to ?

**Comment by kaxelsen** [comment]
RHEA:53916 is more general than RHEA:45948 as an acyl covers many more compounds than acetyl, and the GO term specifies that it is a acetyltransferase.

EC 2.3.1.48 has two reactions attached RHEA:45948 for [protein] and RHEA:21992 for [histone]. The reason RHEA:45948 is also attached to this histone acetyltransferase is the comment: "Several of the enzymes can also acetylate lysines in other proteins". This comment has led to the IUBMB reaction being changed to the more general reaction using L-lysyl-[protein] as the substrate.

The reactions are related: RHEA:21992 is-a RHEA:45948 is-a RHEA:53916.
I would add RHEA:21992 to GO:0004402 histone acetyltransferase activity
and RHEA:45948 to GO:0061733 peptide-lysine-N-acetyltransferase activity

You could perhaps homogenize the two terms, as they dscribe parallel reactions e.g. change GO:0004402 to histone-lysine-N-acetyltransferase activity
