### ISSUE TITLE
polynucleotide 5'-hydroxyl-kinase activity terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25049]
There's a couple of xref issues, term name ambiguities and unnecessary (IMO) grouping classes in this tree:

```
polynucleotide 5'-hydroxyl-kinase activity (-) [17 EXP annotations]
|__GTP-dependent polynucleotide kinase activity (-) [3 EXP annotations]
|   |__GTP-dependent polydeoxyribonucleotide 5'-hydroxyl-kinase activity (-) [0 annotations]
|   |__GTP-dependent polyribonucleotide 5'-hydroxyl-kinase activity (-) [3 EXP annotations]
|__polydeoxyribonucleotide kinase activity (-) [5 EXP annotations]
|   |__GTP-dependent polydeoxyribonucleotide 5'-hydroxyl-kinase activity (-) [0 annotations]
|   |__polydeoxyribonucleotide 5'-hydroxyl-kinase activity (EC:2.7.1.78, RHEA:15669) [4 EXP annotations]
|__polynucleotide kinase activity (EC:2.7.1.78, RHEA:54580) [11 EXP annotations]
|   |__polydeoxyribonucleotide 5'-hydroxyl-kinase activity (EC:2.7.1.78, RHEA:15669) [4 EXP annotations]
|   |__polyribonucleotide 5'-hydroxyl-kinase activity (-) [7 EXP annotations]
|__polyribonucleotide kinase activity (-) [10 EXP annotations]
    |__GTP-dependent polyribonucleotide 5'-hydroxyl-kinase activity (-) [3 EXP annotations]
    |__polyribonucleotide 5'-hydroxyl-kinase activity (-) [7 EXP annotations]
```

**EC 2.7.1.78 = polynucleotide 5'-hydroxyl-kinase.**
a 5'-end dephospho-2'-deoxyribonucleoside-DNA + ATP <=> a 5'-end 5'-monophospho-2'-deoxyribonucleoside-DNA + ADP + H(+)
(Also acts on 5'-dephospho-RNA 3'-mononucleotides.)

**RHEA:15669**
a 5'-end dephospho-2'-deoxyribonucleoside-DNA + ATP = a 5'-end 5'-monophospho-2'-deoxyribonucleoside-DNA + ADP + H+

**RHEA:54580**
a 5'-end dephospho-ribonucleoside-RNA + ATP = a 5'-end 5'-monophospho-ribonucleoside-RNA + ADP + H+

Tasks:
- [x] remove RHEA:54580 from 'polynucleotide kinase activity' (GO:0051734)
- [ ] add EC:2.7.1.78 & RHEA:54580 to 'polyribonucleotide 5'-hydroxyl-kinase activity' (GO:0051736)
- [x] rename 'polynucleotide kinase activity' (GO:0051734) to 'ATP-dependent polynucleotide 5'-hydroxyl-kinase activity'
- [x] rename 'polydeoxyribonucleotide 5'-hydroxyl-kinase activity' (GO:0046404) to 'ATP-dependent polydeoxyribonucleotide 5'-hydroxyl-kinase activity'
- [x] rename 'polyribonucleotide 5'-hydroxyl-kinase activity' (GO:0051736) to 'ATP-dependent polyribonucleotide 5'-hydroxyl-kinase activity'
- [x] rename 'GTP-dependent polynucleotide kinase activity' (GO:0051735) to 'GTP-dependent polynucleotide 5'-hydroxyl-kinase activity'
- [ ] suggest removal of the 'polydeoxyribonucleotide kinase activity' (GO:0051733) and 'polyribonucleotide kinase activity' (GO:0051732) grouping terms/axes

Those changes would result in:

```
polynucleotide 5'-hydroxyl-kinase activity (-) [17 EXP annotations]
|__GTP-dependent polynucleotide 5'-hydroxyl-kinase activity (-) [3 EXP annotations]
|   |__GTP-dependent polydeoxyribonucleotide 5'-hydroxyl-kinase activity (-) [0 annotations]
|   |__GTP-dependent polyribonucleotide 5'-hydroxyl-kinase activity (-) [3 EXP annotations]
|__ATP-dependent polynucleotide 5'-hydroxyl-kinase activity (EC:2.7.1.78) [11 EXP annotations]
    |__ATP-dependent polydeoxyribonucleotide 5'-hydroxyl-kinase activity (EC:2.7.1.78, RHEA:15669) [5 EXP annotations]
    |__ATP-dependent polyribonucleotide 5'-hydroxyl-kinase activity (EC:2.7.1.78, RHEA:54580) [7 EXP annotations]
```

(Note I've already suggested in P2GO that the single EXP annotation made directly to "polydeoxyribonucleotide kinase activity" is changed to the child "polydeoxyribonucleotide 5'-hydroxyl-kinase activity" )

**Comment by sjm41** [comment]
@pgaudget The one I was disputing was for the deoxyribo term - i.e. the paper provides evidence for both "polydeoxyribonucleotide 5'-hydroxyl-kinase activity (GO:0046404)" and "polyribonucleotide 5'-hydroxyl-kinase activity (GO:0051736)"

**Comment by pgaudet** [comment]
Sorry - check again ?

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete 
'GO:0051733 polydeoxyribonucleotide kinase activity' and 'GO:0051732 polyribonucleotide kinase activity'. The reason for obsoletion is that these are unnnecesary grouping terms. There are no annotations to these terms; these terms are not in any subsets. RHEA and EC mappings  EC:2.7.1.78 & RHEA:54580  have been moved to to 'GO:0051736 polyribonucleotide 5'-hydroxyl-kinase activity'. 

GO:0051733 has 1 UniRule mapping UniRule:UR000107275 |

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25049


Thanks, Pascale

**Comment by pgaudet** [comment]
@sjm41 I made all changes you requested, except for EC:2.7.1.78 > I move this to the parent GO:0051734 rather than to the polyribonucleotide child (GO:0051734) that you had suggested. OK ?

**Comment by sjm41** [comment]
Thanks @pgaudet !

_except for EC:2.7.1.78 > I move this to the parent GO:0051734 rather than to the polyribonucleotide child (GO:0051734) that you had suggested. OK ?_
Yes, I think that's what I meant anyway!

**Comment by sjm41** [comment]
Actually, looking again, I meant that EC:2.7.1.78 c/should be an xref on all three of these terms (parent and both children):

```
|__ATP-dependent polynucleotide 5'-hydroxyl-kinase activity (GO:0051734)
    |__ATP-dependent polydeoxyribonucleotide 5'-hydroxyl-kinase activity (GO:0046404)
    |__ATP-dependent polyribonucleotide 5'-hydroxyl-kinase activity (GO:0051736)
```

EC 2.7.1.78 = polynucleotide 5'-hydroxyl-kinase.
a 5'-end dephospho-2'-deoxyribonucleoside-DNA + ATP <=> a 5'-end 5'-monophospho-2'-deoxyribonucleoside-DNA + ADP + H(+)
(Also acts on 5'-dephospho-RNA 3'-mononucleotides.)
