### ISSUE TITLE
NTR "tRNA adaptor activity"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25046]
I am trying to  describe the 'tRNA carrier activity" of eIF2 alpha.

This paper  https://www.pombase.org/reference/PMID:31048492 describes eIF2 alpha as a 
"Carrier methionylated initiator tRNA (Met-tRNAi) to the ribosomes"
Currently  we only have
methionyl-initiator methionine tRNA binding 

Would I describe this as a carrier, or an adaptor?

**Comment by pgaudet** [comment]
I think it's an adaptor - the carrier deliver its cargo to a specific location, while this is bringing to a complex. OK ?

**Comment by ValWood** [comment]
Yes!
