### ISSUE TITLE
NTR: SUMO ligase regulator activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25052]
Please provide as much information as you can: 

* **Suggested term label:**

SUMO ligase ~inhibitor~ regulator activity

* **Definition (free text)**

standard def 

* **Reference, in format PMID:#######**
PMID:19363481
PMID: 33446573

* **Gene product name and ID to be annotated to this term**

Rad60 https://www.pombase.org/gene/SPBC1921.02

Rad60 inhibits sumo ligase activity  by competitive inhibition (the SUMO domain mimics the substrate SUMO)

PMID:19363481 Title | Molecular mimicry of SUMO promotes DNA repair.

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
This was incorrect interpretation

**Comment by ValWood** [comment]
@robnash 
I will add this term later.
v

**Comment by ValWood** [comment]
+[Term]
+id: GO:0180016
+name: SUMO ligase regulator activity
+namespace: molecular_function
+def: "Binds to and modulates the activity of a ligase." [PMID:19363481, PMID:33446573]
+is_a: GO:0055103 ! ligase regulator activity
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/25052 xsd:anyURI

**Comment by pgaudet** [comment]
@ValWood 

The regulator activity terms should have a logical definition, please do not assert any relations, otherwise we may end up with different hierarchies in different part of the ontology. 

Thanks, Pascale

**Comment by ValWood** [comment]
So I don't add an is_a parent?

**Comment by sjm41** [comment]
@ValWood I think you need to include 'SUMO' in the term def too?

**Comment by ValWood** [comment]
yes, it was, that commit failed with identical defs
 ;)
edited above.

**Comment by ValWood** [comment]
I don't see this term yet, is there a problem with the snapshot?

**Comment by pgaudet** [comment]
The last snapshot was on March 4th, see
http://snapshot.geneontology.org/metadata/date.txt

Possibly this term just missed the snapshot.

**Comment by ValWood** [comment]
I still don't see this term, is there a  problem.
@kimrutherford  is the snapshot working OK?

**Comment by kimrutherford** [comment]
> @kimrutherford is the snapshot working OK?

The snapshot was last updated about a week ago: http://snapshot.geneontology.org/summary.txt

```
Runtime summary.

Sat Mar  4 00:01:17 PST 2023

Release notes: https://github.com/geneontology/go-site/tree/master/releases
Branch: snapshot
Start day: Saturday
Start date: 2023-03-04
Official release date: metadata/release-date.json
Official Zenodo archive DOI: metadata/release-archive-doi.json
TODO: Note software versions.
```
