### ISSUE TITLE
aldehyde decarbonylase activity / octadecanal decarbonylase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25056]
'aldehyde decarbonylase activity' has a single child term 'octadecanal decarbonylase activity':

id: GO:0071771
name: aldehyde decarbonylase activity [2 EXP annotations]
namespace: molecular_function
def: "Catalysis of the reaction: a C(n) aldehyde = C(n-1) alkane + CO." [GOC:kad, PMID:6593720, PMID:8718622]
synonym: "decarbonylase activity" EXACT [GOC:kad, GOC:mah]
is_a: GO:0016830 ! carbon-carbon lyase activity
created_by: mah
creation_date: 2010-04-01T12:02:50Z

id: GO:0009924
name: octadecanal decarbonylase activity [0 EXP annotations]
namespace: molecular_function
def: "Catalysis of the reaction: octadecanal = heptadecane + CO." [EC:4.1.99.5, GOC:tb]
synonym: "octadecanal alkane-lyase activity" EXACT []
xref: EC:4.1.99.5
xref: MetaCyc:OCTADECANAL-DECARBONYLASE-RXN
xref: RHEA:30415
is_a: GO:0071771 ! aldehyde decarbonylase activity

The RHEA:30415 xref on GO:0009924 looks ~correct:
H+ + 2 NADPH + O2 + octadecanal = formate + H2O + heptadecane + 2 NADP+

But the EC:4.1.99.5 xref on GO:0009924 is more general and looks like it should be moved to the parent GO:0071771:
name: aldehyde oxygenase (deformylating).
alt name: aldehyde decarbonylase.
def: a long-chain fatty aldehyde + H(+) + 2 NADPH + O2 <=> a long-chain alkane + formate + H2O + 2 NADP(+)

And there's a separate RHEA ([RHEA:21440](https://www.rhea-db.org/rhea/21440)) for that more general reaction
a long-chain fatty aldehyde + H+ + 2 NADPH + O2 = a long-chain alkane + formate + H2O + 2 NADP+

BUT note the EC:4.1.99.5/RHEA:21440 reaction defs don't quite match that currently given in GO:0071771....

Also, might want to obsolete GO:0009924 given it's the only child of GO:0071771 and it has 0 EXP annotations?

**Comment by sjm41** [comment]
Reviewing this, I see that the PMID:6593720 xref used in the def of 'aldehyde decarbonylase activity' is also listed on the  RHEA:21440 entry.

So I propose to go ahead with this and do the following:
- [ ] move the EC:4.1.99.5 xref to the parent term aldehyde decarbonylase activity
- [ ] add RHEA:21440 xref to the parent term aldehyde decarbonylase activity
- [ ] Re-define the parent term aldehyde decarbonylase activity based on the RHEA xref


@pgaudet Do you want to obsolete 'octadecanal decarbonylase activity'?

**Comment by sjm41** [comment]
Hmmm.  I think these two terms are both referring to EC:4.1.99.5/RHEA:21440 and need merging:

EC:4.1.99.5
name: aldehyde oxygenase (deformylating).
alt name: aldehyde decarbonylase.
def: a long-chain fatty aldehyde + H(+) + 2 NADPH + O2 <=> a long-chain alkane + formate + H2O + 2 NADP(+)

RHEA:21440 lists PMID:6593720 and PMID:22947199.


id: GO:0071771
name: aldehyde decarbonylase activity
namespace: molecular_function
def: "Catalysis of the reaction: a C(n) aldehyde = C(n-1) alkane + CO." [GOC:kad, PMID:6593720, PMID:8718622]
synonym: "decarbonylase activity" EXACT [GOC:kad, GOC:mah]
is_a: GO:0016830 ! carbon-carbon lyase activity
created_by: mah
creation_date: 2010-04-01T12:02:50Z

id: GO:1990465
name: aldehyde oxygenase (deformylating) activity
namespace: molecular_function
def: "Catalysis of the reaction a long-chain aldehyde + O2 + 2 NADPH = an alkane + formate + H2O + 2 NADP+." [GOC:mengo_curators, PMID:22947199, RHEA:21440]
xref: EC:4.1.99.5
xref: RHEA:21440
is_a: GO:0016830 ! carbon-carbon lyase activity
created_by: tt
creation_date: 2014-08-25T15:16:43Z

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete: GO:0009924 octadecanal decarbonylase activity. The reason for obsoletion is that this represents a specific substrate of the reaction GO:0071771 aldehyde decarbonylase activity. 

The proposal has also been made to obsolete GO:1990465 aldehyde oxygenase (deformylating) activity, since this represents the same reaction as GO:0071771 aldehyde decarbonylase activity. 

There are no annotations to these terms; these terms are not in any subset. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25056

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks!
