### ISSUE TITLE
Textual definition update: 2-hydroxyacyl-CoA lyase activity (GO:0106359)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25060]
* **GO term ID and label for which you request a definition update**
id: GO:0106359
name: 2-hydroxyacyl-CoA lyase activity
namespace: molecular_function
def: "Catalysis of the reaction: A 2-hydroxyacyl-CoA = formyl-CoA + a propanol." [PMID:21708296, PMID:28289220]
xref: EC:4.1.2.63

The product/substrates in the GO def don't match those in the EC:4.1.2.63 entry, which says reactions are:
1. a 2-hydroxy-3-methyl fatty acyl-CoA <=> a 2-methyl-branched fatty aldehyde + formyl-CoA (= RHEA:25375)
2. an (R)-2-hydroxy-long-chain-fatty acyl-CoA <=> a long-chain fatty aldehyde + formyl-CoA (= RHEA:67444)

So, change def to match EC?

Note the RHEA xrefs I showed above could also be added.

**Comment by sjm41** [comment]
Thanks @pgaudet. Though I noticed you wrote 'fatty acids' in the new def where it should be 'fatty aldehydes' (2 instances).

**Comment by sjm41** [comment]
Ah, I was focussing of the right-hand side of the reaction equations, but you're talking about the left-hand side (which does makes sense when the new def say 'acts on'.)

a 2-hydroxy-3-methyl fatty acyl-CoA <=> a 2-methyl-branched fatty aldehyde + formyl-CoA
an (R)-2-hydroxy-long-chain-fatty acyl-CoA <=> a long-chain fatty aldehyde + formyl-CoA

But the new def reads "Catalysis of the reaction: a 2-hydroxyacyl-CoA = a fatty aldehyde + formyl-CoA. The reaction acts on 3-methyl-branched fatty acids and 2-hydroxy long-chain fatty acids."

Might be better to say "Catalysis of the reaction: a 2-hydroxy **-fatty** acyl-CoA = a fatty aldehyde + formyl-CoA. The reaction acts on **2-hydroxy-**3-methyl-branched fatty **acyl-CoA** and 2-hydroxy long-chain fatty **acyl-CoA**."?

I'm not sure if fatty acyl-CoA is classed as a type of 'fatty acid'??
But maybe I'm reading too much into this....

**Comment by pgaudet** [comment]
Hi, I think you are right, acyl is broader than fatty acyl, see 
https://en.wikipedia.org/wiki/Acyl_group
