### ISSUE TITLE
Add EC xref to GO:0061663  NEDD8 ligase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25078]
Can you add EC:2.3.2.32 (cullin-RING-type E3 NEDD8 transferase) as an xref to this term?:

id: GO:0061663
name: NEDD8 ligase activity
namespace: molecular_function
def: "Catalysis of the transfer of NEDD8 to a substrate protein via the reaction X-NEDD8 + S --> X + S-NEDD8, where X is either an E2 or E3 enzyme, the X-NEDD8 linkage is a thioester bond, and the S-NEDD8 linkage is an isopeptide bond between the C-terminal amino acid of NEDD8 and the epsilon-amino group of lysine residues in the substrate." [GOC:dph]
synonym: "E3" RELATED [GOC:dph]
is_a: GO:0019788 ! NEDD8 transferase activity
is_a: GO:0061659 ! ubiquitin-like protein ligase activity
created_by: dph
creation_date: 2014-11-06T13:57:00Z

**Comment by pgaudet** [comment]
Hi @sjm41 
I added this as a narrow match, since this specifically mentions cullin as the target  - is this correct?

**Comment by sjm41** [comment]
Hi @pgaudet yes, narrow match looks correct. A review from 8 years ago (PMID: 25531226) says that cullins were the only validated target of NEDD8 E3s, but that other targets had been proposed. A quick search finds a lest one non-cullin target (PMID: 36834826).

But I think you modified the wrong term judging from the https://github.com/geneontology/go-ontology/commit/ab0781100199fedfe56dc71ddb210906bf075371 commit - the narrow match is for EC:2.3.2.32 and not EC:2.3.2.34?

**Comment by pgaudet** [comment]
Thanks!!!!
