### ISSUE TITLE
NTR: Purine nucleotide import into lysosome

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#25075]
Please provide as much information as you can: 

* **Suggested term label:**
Purine nucleotide import into lysosome

* **Definition (free text)**
The directed import of purine nucleotide from the cytosol, across the lysosomal membrane, into the lysosome.

* **Reference, in format PMID:#######**
PubMed=23876310, PubMed=18375752

* **Gene product name and ID to be annotated to this term**
SLC17A9

* **Parent term(s)**
GO:0015865  purine nucleotide transport
GO:1901679  nucleotide transmembrane transport

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141013
+name: purine nucleotide import into lysosome
+namespace: biological_process
+def: "The directed import of purine nucleotide from the cytosol, across the lysosomal membrane, into the lysosome." [PMID:18375752, PMID:23876310]
+intersection_of: GO:0055085 ! transmembrane transport
+intersection_of: has_primary_input CHEBI:35584 ! purine
+intersection_of: has_target_end_location GO:0043202 ! lysosomal lumen
+intersection_of: has_target_start_location GO:0005829 ! cytosol
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/25075 xsd:anyURI
+created_by: pg
+creation_date: 2023-03-07T09:03:49Z
