### ISSUE TITLE
cytokinesis, site selection and establishment of contractile ring localization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25071]
From https://github.com/geneontology/go-ontology/issues/16879

These are the current terms around cytokinesis, site selection and establishment of contractile ring localization

<img width="670" alt="Screenshot 2023-03-03 at 12 46 58" src="https://user-images.githubusercontent.com/7359272/222726860-6a1d296d-9e9a-4c8c-b8c0-71ce206d44b2.png">

Here is a proposal to standardize the defs and term meanings based on the biology and the term usage:

1. Definitions are ambiguous and inconsistent

- [x] GO:0036214 contractile ring localization
- [x] GO:0032187  actomyosin contractile ring localization

Are defined
The process in which a contractile ring is assembled and/or maintained in a specific location.

This could be interpreted the term includes assembly.
Change to 
**The process in which a contractile ring is ~assembled~ positioned and/or maintained in a specific location.**

2.
Then the descendants definitions change:

GO:0032188 establishment of actomyosin contractile ring localization 
GO:1903486  establishment of mitotic actomyosin contractile ring localization
GO:1903505  regulation of establishment of actomyosin contractile ring localization involved in mitotic cell cycle
GO:0071342  regulation of establishment of actomyosin contractile ring localization
**Any establishment of actomyosin contractile ring localization that is involved in mitotic cell cycle.**

These terms are about positioning, but the definitions are vague
These 2 terms are used only **3 times**
2 PomBase aniline + rng2
2 flybase anillin

3.
We also have other terms about positioning:

GO:0007105 cytokinesis, site selection
**The process of marking the place where cytokinesis will occur.**

This terms are also about positioning, but the term name and definition are suboptimal.

GO:0007105 cytokinesis, site selection
- [x] Rename to Cytokinesis, division site positioning
- [x] Improve the definition to align with the localisation terms
**The process in which a contractile ring is positioned in a specific location. This process is critical for both for both symmetric and asymmetric cell divisions.**
PMID: 26553932
PMID: 28162898 
- [x] exact_synonym division plane positioning 
- [x] exact_synonym cytokinesis, site selection

- [x] **Add parent "contractile ring localisation"**

4. GO:0007105 cytokinesis, site selection
This term has 2 axis of descendants

A
GO:1902408 mitotic cytokinesis, site selection
GO:1902472 regulation of mitotic cytokinesis, site selection
GO:1903617 positive regulation of mitotic cytokinesis, site selection

Which would become
- [x] GO:1902408 mitotic cytokinesis, division site positioning
- [x] GO:1902472 regulation of mitotic cytokinesis, division site positioning
- [x] GO:1903617 positive regulation of mitotic cytokinesis, division site positioning

B (these have the localisation, and the site selection ancestry)
**GO:1903486 establishment of mitotic actomyosin contractile ring localization
GO:0032188 establishment of actomyosin contractile ring localization
 Which would be obsoleted (see point2)**
The **3! annotations** would be mapped to a different descendant of GO:1902408 mitotic cytokinesis, division site positioning

**Comment by ValWood** [comment]
@vanaukenk  [no worm annotations]
@ukemi [no mouse annotations]
@hattrill  Fly annotation to anilllin 

Could you let me know if this works for you?
This is the previous ticket
https://github.com/geneontology/go-ontology/issues/16879
if any of this is still relevant please add to the issue.

[Another open question for later is why we need to say "actomyosin" in these terms because these don't work for plans, requiring actomyosis and non-actomyosin cytokinetic ring terms is a combinatorial nightmare]

**Comment by hattrill** [comment]
This works for me.

 (just adding this PMID for myself for future ref: PMID:19339546)

**Comment by ValWood** [comment]
I wonder whether we also need a function term to describe the molecular function as a "medial ring marker"
Anillin is part of the border process of ring positioning, and it acts as an adaptor to connect other ring components and signalling molecules to the cell division site. However, the adaptor annotation does not capture its function to  act as a spatial cue for these events. I  also always want to annotation the "cell end marker" tea1 to such a term. @hattrill I'll open a ticket to discuss  how to capture this activity and tag you.

**Comment by pgaudet** [comment]
Is this going to apply specifically to this protein? Is there any way we can make that activity a bit general ?

**Comment by ValWood** [comment]
I have done the dits above to standardize term names and definitions and get everything in the same branch.

One this is done I'll look again at the graph in Amigo to be sure the next steps are correct (some merges may be more appropriate)

**Comment by ValWood** [comment]
Terms are now in a common branch. Need to work out i) which are used ii) which are required iii) which are redundant
<img width="817" alt="Screenshot 2023-03-22 at 14 10 56" src="https://user-images.githubusercontent.com/7359272/226931406-0e77842c-a354-4063-a8f4-6aa908b83c8c.png">

[basket-ring-localization.txt](https://github.com/geneontology/go-ontology/files/11040924/basket-ring-localization.txt)

**Comment by ValWood** [comment]
remaining issues
https://github.com/geneontology/go-ontology/issues/25379
