### ISSUE TITLE
NTR: [Ribosome hibernation]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#25082]
Hi GO,

I would need a new term for Ribosome hibernation, a process that takes place in both prokaryotes and eukaryotes

Thanks

Sylvain

Term: Ribosome hibernation
Category: Process
Definition: A cellular process that results in the silencing of ribosomes in quiescent cells. Quiescence takes place when cells encounter unfavorable conditions and cease to grow in bacteria and yeast. It also takes place in some specialized cells in higher eukaryotes, such as eggs. Ribosomes in a hibernation state are kept silent via association with proteins with inhibitory and protective functions.
Synonym: Ribosome dormancy 
child of  GO:0042254 ribosome biogenesis

PMID:36653451
PMID:30177741
PMID:28468753

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141014
+name: ribosome hibernation
+namespace: biological_process
+def: "A cellular process that results in the silencing of ribosomes in quiescent cells. Quiescence takes place when cells encounter unfavorable conditions and cease to grow in bacteria and yeast. It also takes place in some specialized cells in higher eukaryotes, such as eggs. Ribosomes in a hibernation state are kept silent via association with proteins with inhibitory and protective functions." [PMID:28468753, PMID:30177741, PMID:36653451]
+is_a: GO:0090071 ! negative regulation of ribosome biogenesis
+property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/25082 xsd:anyURI
+created_by: pg
+creation_date: 2023-03-07T09:56:14Z

**Comment by pgaudet** [comment]
@sylvainpoux please note, I added this as is_a  'GO:0090071 ! negative regulation of ribosome biogenesis' - is that OK for you ?

**Comment by sylvainpoux** [comment]
Hi @pgaudet , Yes, it is perfect.
Many thanks
Sylvain

**Comment by ValWood** [comment]
Are you sure about this?

Ribosomes in a hibernation state are kept silent via association with proteins with inhibitory and protective functions

This is a process which acts on active ribosomes. Ribosome biogenesis is about the production of new ribosomes (although ribosome biogenesis is almost certainly also negatively regulated during stationary phase).
This seems that it should be more aptly a "negative regulation of translation"?

**Comment by pgaudet** [comment]
@sylvainpoux 

Do you agree I change the parent from 'negative regulation of ribosome biogenesis' to 'negative regulation of translation'? That makes sense based on the term definition.

**Comment by sylvainpoux** [comment]
Hi @pgaudet, 
Yes, I think it makes sense. Thanks
