### ISSUE TITLE
Obsoletion notice: GO:0044405 Detection of host 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25087]
GO:0044405 detection of host
No annotations, not a specific process

**Comment by mgiglio99** [comment]
Hi,
I realize that this term doesn't have any annotations, but I know that there are genes that are involved in this process from back in the PAMGO days. 
(And, if we were to keep it, I don't think it should be under 'response to host' but should just be out under 'biological process involved in interaction with host'.)
Are you thinking that proteins involved in binding to one host but not another would be annotated under some kind of receptor binding under Function? And then that the partner identified in the With field would be from a different species? 
I think the process can be more complex than just plain binding in some cases, although I'd have to look for examples.
Will you also be planning to obsolete 'detection of symbiont'?

adding @dsiegele and @genegodbold for their thoughts.

**Comment by pgaudet** [comment]
Hi Michelle, 

If this term is referring to which host a symbiont interacts with, would 'entry into host' be more appropriate as a BP, and indeed the MF would be some kind of protein binding between a symbiont and a host protein? 

Were you thinking of other situations as well ?

**Comment by mgiglio99** [comment]
Hi Pascale,
The thing is that not all symbionts enter their hosts so entry won't always work. And even when they enter, entry doesn't happen until one finds the correct host- but I see how finding can be considered part of entry.
I'm trying to find some of the examples that I remember from PAMGO days.

**Comment by edwong57** [comment]
@mgiglio99, have you been able to find some examples?

**Comment by addiehl** [comment]
This paper describes various ways in which parasitic worms detect their hosts:
Parasitic worms: strategies of host finding, recognition and invasion
https://www.sciencedirect.com/science/article/abs/pii/S0944200604701105
https://pubmed.ncbi.nlm.nih.gov/16351919/

This is a 20-year old review, so I am sure there has been a lot of follow up work.

**Comment by edwong57** [comment]
@addiehl @mgiglio99  @dsiegele @genegodbold do you have any concrete recommendations/reasonings for keeping this broad term?

**Comment by genegodbold** [comment]
Since it has no annotations AND it has problems, I'd obsolete it.

**Comment by mgiglio99** [comment]
I did look for some examples a while back and couldn't find the ones that I remember from PAMGO days.
Since I can't come up with anything, best thing is to obsolete - we can always bring it back if examples arise.

**Comment by pgaudet** [comment]
Thanks everyone for the feedback. Let's go ahead with the obsoletion.
