### ISSUE TITLE
"viral process" descendants

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#25083]
Hello,
I have a few fungal annotations flagged that seem to match the term def but now fail on taxon constraints ( is_a viral process) and I wonder what to do.

1. **evasion of host immune response** 
_A process by which an organism avoids the effects of the host organism's immune response. The host is defined as the larger of the organisms involved in a symbiotic interaction._

**C. albicans from pmid:34986357**  
C. albicans activates the alternative complement system, resulting in the deposition of complement proteins (i.e., C3) on the fungal cell surface, resulting in opsonophagocytosis. C. albicans can evade opsonophagocytosis through the binding of complement regulatory proteins to its cell surface, which inactivate the complement cascade. Here we show that C. albicans does adapt to estrogen and that this adaptation perturbs the host-pathogen interaction, inhibiting phagocytosis of the fungal pathogen. Avoidance of the innate immune system was mediated via the fungal cell surface protein, Gpd2, recruiting the human complement regulatory protein, Factor H, to the fungal cell surface, inactivating the alternative complement system.

**C. neoformans from pmid:30459196**
Chitin is an essential component of the cell wall of Cryptococcus neoformans. Mammalian hosts have evolved robust immunologic defense strategies to deal with chitin-containing microbes. Fungal chitin deacetylases deacetylate chitin, converting it to chitosan. The presence of chitosan in the cell wall protects yeast cells from host clearance.

**A.  fumigatus from pmid: 20498262**
Secreted Aspergillus fumigatus protease Alp1 degrades human complement proteins C3, C4, and C5. In summary, we identified a novel mechanism in A. fumigatus that contributes to evasion from the host complement attack. 

--> this one could move to "suppression by symbiont of host immune response"?

2. **symbiont defense to host-produced reactive oxygen species** is_a viral process
_Def: Any process in which a symbiont modulates the frequency, rate or extent of the production of reactive oxygen species as part of the defense response of the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction._ 

**C.neoformans SOD1 from pmid:12496163:** 
Superoxide dismutase (SOD) is an enzyme that converts superoxide radicals into hydrogen peroxide and molecular oxygen and has been shown to contribute to the virulence of many human-pathogenic bacteria through its ability to neutralize toxic levels of reactive oxygen species generated by the host. SOD has also been speculated to be important in the pathogenesis of fungal infections, but the role of this enzyme has not been rigorously investigated......The decreased virulence of the sod1 strain may be due to increased susceptibility to oxygen radicals within macrophages.

**Comment by pgaudet** [comment]
@ValWood 
We have 'never in Fungi' for 'evasion of host immune response'; any suggestions where this can be moved? Or do we need to do 
never in NCBITaxon:4895 | Schizosaccharomyces 
never in NCBITaxon:4930 Saccharomyces

?? 

Thanks, Pascale

**Comment by ValWood** [comment]
I would leave that taxon constraint off fungi altogether.  It could stay on fission yeast as far as I know but cerevisiae can be pathogenic to humans. It might get quite complicated to add taxon constraints, and it is unlikely people would try to transfer these annotations between species (one would hope!), since they are very species, (and even strain-) specific.

**Comment by pgaudet** [comment]
The taxon constraint hare removied for most fungi except

**Comment by pgaudet** [comment]
Ah no, I had only looked at the taxon constraints. I'll fix this now.
