### ISSUE TITLE
NTR: sulfate:chloride antiporter activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#25089]
Please provide as much information as you can: 

* **Suggested term label:**
sulfate:chloride antiporter activity

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: chloride(in) + sulfate(out) = chloride(out) + sulfate(in).

* **Reference, in format PMID:17442754
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
solute:inorganic anion antiporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160044
+name: sulfate:chloride antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: chloride(in) + sulfate(out) = chloride(out) + sulfate(in)." [PMID:17442754]
+intersection_of: GO:0015297 ! antiporter activity
+intersection_of: has_primary_input CHEBI:16189 ! sulfate
+intersection_of: has_primary_input CHEBI:17996 ! chloride
+created_by: rynl
+creation_date: 2023-03-13T23:40:47Z
