### ISSUE TITLE
Term merge GO:1904382 mannose trimming involved in glycoprotein ERAD pathway/GO:1904380 | endoplasmic reticulum mannose trimming

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25095]
GO:1904382   mannose trimming involved in glycoprotein ERAD pathway
An ERAD pathway whereby endoplasmic reticulum (ER)-resident glycoproteins are targeted for degradation. Includes differential processing of the glycoprotein sugar chains, retrotranslocation to the cytosol and degradation by the ubiquitin-proteasome pathway. A glycoprotein is a compound in which a carbohydrate component is covalently bound to a protein component. [[PMID:16079177](https://www.pombase.org/reference/PMID:16079177)]

GO:1904380 | endoplasmic reticulum mannose trimming
Any protein alpha-1,2-demannosylation that takes place in the endoplasmic reticulum quality control compartment (ERQC).

During the merge we should also remove the "protein modification" parentage

**Comment by ValWood** [comment]
We might also be able to remove
protein demannosylation (GO:0036507)
protein alpha-1,2-demannosylation (GO:0036508)

as this seems to be the only usage.

**Comment by pgaudet** [comment]
Under what term do you plan to move this? 

What about the two siblings 
'Golgi apparatus mannose trimming'
'mannose trimming involved in glycoprotein ERAD pathway'?

**Comment by ValWood** [comment]
GO:1904382   mannose trimming involved in glycoprotein ERAD pathway
Definition ([GO:1904382 GONUTS page](http://gowiki.tamu.edu/wiki/index.php/Category:GO:1904382))
The removal of one or more alpha 1,2-linked mannose residues from a mannosylated protein that occurs as part of glycoprotein ER-associated glycoprotein degradation (gpERAD). PMID:24519966

seems like the same thing too?

Golgi apparatus mannose trimming
seems unnecessary, it's an activity not a pathway , but I will need to read up on this. I don't know of any 
"mannose trimming" in the Golgi. There are only 3 TAS annotations....

**Comment by ValWood** [comment]
For the ER pathway the "trimming" is used to describe the sequential removal of 3 sugar residues.

The Golgi one :
http://europepmc.org/article/MED/10915796
Characterization of a cDNA encoding a novel human Golgi alpha 1, 2-mannosidase (IC) involved in N-glycan biosynthesis.


should be annotated
 alpha 1, 2-mannosidase part_of  N-glycan processing (narrow synonym N-glycan processing) occurs_in Golgi apparatus
(or similar)?

It's a GO-CAM.

**Comment by ValWood** [comment]
Closing. These are actually single-step processes and should be dealt with by the obsoletions of the protein modification branch?
