### ISSUE TITLE
NTR: oxalate:chloride antiporter activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#25090]
Please provide as much information as you can: 

* **Suggested term label:**
oxalate:chloride antiporter activity

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: chloride(out) + oxalate(in) = chloride(in) + oxalate(out)

* **Reference, in format PMID:17442754
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
solute:inorganic anion antiporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
This is to describe the same transporter as in  #25089
However there is no common parent in ChEBI, so I think we need to create both terms.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160046
+name: oxalate:chloride antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: chloride(out) + oxalate(in) = chloride(in) + oxalate(out)." [PMID:17442754]
+intersection_of: GO:0015297 ! antiporter activity
+intersection_of: has_primary_input CHEBI:17996 ! chloride
+intersection_of: has_primary_input CHEBI:30623 ! oxalate(2-)
+created_by: rynl
+creation_date: 2023-03-14T00:09:30Z

**Comment by raymond91125** [comment]
Thanks. @ValWood
