### ISSUE TITLE
GO:NEW | K11-linked deubiquitinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25104]
I would like to swap a ubiquitin protease annotation over from
GO:0035871 | protein K11-linked deubiquitination
to

GO:NEW | K11-linked deubiquitinase activity

We already have
GO:0061578 | K63-linked deubiquitinase activity
GO:1990380 K48-linked deubiquitinase activity

**Comment by pgaudet** [comment]
Go ahead and create the new term; however please leave the ubiquitination BPs for now. We need to figure out how to express mono versus polyubiquitination. 


Thanks, Pascale
