### ISSUE TITLE
Missing parent: GO:0072684   mitochondrial tRNA 3'-trailer cleavage, endonucleolytic

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25113]
* **GO term ID and label for which you request a new superclass**

GO:0072684   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0072684/complete)
mitochondrial tRNA 3'-trailer cleavage, endonucleolytic (this term will eventually go because it describes a MF, but I want it to be in the right place to figure replacements)

* **New superclass (parent) suggested**

mitochondrial RNA 3'end processing

**Comment by pgaudet** [comment]
The organization of RNA processing should be reviewed 

a nice review about tRNA processing: https://www.frontiersin.org/articles/10.3389/fgene.2019.00096/full

**Comment by ValWood** [comment]
the main parts of RNA processing are in other tickets. I'm trying to make it into managable chunks. It won't be so bad once the single-step processes (cleavage, polyadenylation and exo-endo nuclease specific ) are removed.  But in the meantime I will add any missing parents like this as it will make it harder to accidentally miss a term when handling a specific branch. I'll add this review (I have good reviews for most parts now, except tRNA prcessing). Also, have experts lined up to double-check any major changes after the weeding stage)
