### ISSUE TITLE
NTR: [purine nucleotide uniporter activity]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#25117]
Please provide as much information as you can: 

* **Suggested term label:**
purine nucleotide uniporter activity

* **Definition (free text)**
Catalysis of the active transport of purine nucleotides across a membrane by a mechanism involving conformational change, where energy for active transport is derived from membrane potential if the solute is charged.

* **Reference, in format PMID:#######**
(REQUIRED)
PubMed:18375752, PubMed:27477609

* **Gene product name and ID to be annotated to this term**
Slc17a9

* **Parent term(s)**
GO:0022810  membrane potential driven uniporter activity
GO:0015216  purine nucleotide transmembrane transporter activity
GO:0015292  uniporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160042
+name: purine nucleotide uniporter activity
+namespace: molecular_function
+def: "Catalysis of the active transport of purine nucleotides across a membrane by a mechanism involving conformational change, where energy for active transport is derived from membrane potential if the solute is charged." [PMID:18375752, PMID:27477609]
+intersection_of: GO:0022810 ! membrane potential driven uniporter activity
+intersection_of: has_primary_input CHEBI:26395 ! purine nucleotide
+created_by: rynl
+creation_date: 2023-03-11T00:58:42Z

**Comment by pgaudet** [comment]
Done
