### ISSUE TITLE
should "mRNA splice site selection"  be renamed?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25114]
from
https://github.com/geneontology/go-ontology/issues/23362

Note that in the 2nd image "mRNA splice site selection" isn't really about selecting alternative splice sites. It's children are
GO:0000389    mRNA 3'-splice site recognition 
GO:0000395    mRNA 5'-splice site recognition

Possibly this term should be renamed "mRNA splice site recognition"?

_Originally posted by @ValWood in https://github.com/geneontology/go-ontology/issues/15473#issuecomment-1462589762_

**Comment by ValWood** [comment]
@krchristie 
@pgaudet  let me know if that makes sense, I will do it tomorrow.

**Comment by krchristie** [comment]
works for me

**Comment by pgaudet** [comment]
These terms all seem to be substeps of mRNA splicing (= MFs??) 

GO:0000389 mRNA 3'-splice site recognition
GO:0000395 mRNA 5'-splice site recognition 
GO:0034403 alignment of 3' and 5' splice sites of mRNA

**Comment by ValWood** [comment]
Yes I think you are right, these seem to be MF.

**Comment by ValWood** [comment]
I change this term label to be consistent with the descendants and the sibling for brunch site recognition. Since splicing is in pretty good shape and I'm concentrating on the molecular functions in other areas of RNA metabolism I will close this for now we can look at MF's in splicing later
