### ISSUE TITLE
Obsoletion request: GO:0061915 | actin fusion focus localization

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25111]
Please provide as much information as you can:

* **GO term ID and Label**

GO:0061915 | actin fusion focus localization
 - [ ]  The reason for obsoletion is that this represents a phenotype.

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

0 annotations GO:0061915 | actin fusion focus localization

- [ ] check taxon constraints 

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [x] paste the text in the ontology ticket
https://github.com/geneontology/go-announcements/issues/499

**Comment by pgaudet** [comment]
Do you wan to remove "or maintained" from the definiton? 

A process in which a protein is transported to, or **maintained in**, a location within an actin fusion focus

**Comment by ValWood** [comment]
Yes thats what I meant to do. Will fix tomorrow.
