### ISSUE TITLE
NTR: [psammoma body]

### ISSUE THREAD

**Issue by brendamg** [geneontology/go-ontology#25126]
Please provide as much information as you can: 

* **psammoma body**

* **A psammoma body is a round collection of calcium, seen microscopically. The term is derived from the Greek word psammos meaning sand. Psammoma bodies are commonly seen in certain tumors**

* * Wikipedia**
(REQUIRED)

psammoma body is not a tissue, but I think it is a cellular component. So I will make it obsolete in the BRENDA Tissue Ontology.

**Comment by pgaudet** [comment]
Hi @brendamg 
As described, if this is only composed of calcium, this would be out of scope for GO, which describes cellular components where gene products locate. 

Also, these seem to be formed as a results of abnormal processes ( from wikipedia: 
Cause

Psammoma bodies are associated with the [papillary](https://en.wiktionary.org/wiki/papillary) (nipple-like) [histo](https://en.wikipedia.org/wiki/Histology)[morphology](https://en.wikipedia.org/wiki/Morphology_(biology)) and are thought to arise from,

    [Infarction](https://en.wikipedia.org/wiki/Infarction) and [calcification](https://en.wikipedia.org/wiki/Calcification) of papillae tips.
    Calcification of intralymphatic tumor thrombi.[[1]](https://en.wikipedia.org/wiki/Psammoma_body#cite_note-1)

**Comment by ValWood** [comment]
Closing, please reopen if there is evidence that this is an annotatable component .
