### ISSUE TITLE
NTR: [Muramyl dipeptide kinase activity]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#25141]
Hi GO,

I would need a new term reaction for a very interesting activity for NAGK (Q9UJ70) a known metabolic enzyme. A paper published in Nature last year shows that NAGK generates a ligand for NOD2, an essential pattern recognition receptor that plays an important role in gastrointestinal immunity (PubMed=36002575).

Note that I requested a Rhea reaction, I will let you know when it is available
 
Thanks

Sylvain

Term: Muramyl dipeptide kinase activity
Category: Function
Definition: Catalysis of the reaction: ATP + muramyl dipeptide = ADP + H(+) + 6-O-phospho-muramyl dipeptide
Child of GO:0019200 carbohydrate kinase activity
PMID:36002575

**Comment by raymond91125** [comment]
In CHEBI, muramyl dipeptide is_a glycopeptide [(is_a peptide) and (is_a carbohydrate derivative)] but not a a subclass of carbohydrate.
Thus, perhaps the best parent class is GO:0016301 kinase activity.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160047
+name: muramyl dipeptide kinase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: ATP + muramyl dipeptide = ADP + H(+) + 6-O-phospho-muramyl dipeptide." [PMID:36002575]
+is_a: GO:0016301 ! kinase activity
+created_by: rynl
+creation_date: 2023-03-17T22:29:32Z

**Comment by raymond91125** [comment]
@pgaudet  Should we always reference the ticket for new terms? I haven't been doing that.

**Comment by sylvainpoux** [comment]
Many thanks!
In the meantime, I received the Rhea cross-reference. It is Rhea:75935
Sylvain

**Comment by pgaudet** [comment]
> Should we always reference the ticket for new terms? I haven't been doing that.

Yes, I do - I find it's easier to find why we created terms. I usually link all tickets, unless the change is really trivial (for example I would not link for corrections of typos)
