### ISSUE TITLE
Update EC:2.7.7.n1 xref to EC:2.7.7.108

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25168]
See https://enzyme.expasy.org/EC/2.7.7.n1

So please update EC:2.7.7.n1 xref to EC:2.7.7.108 on the following term:

id: GO:0070733
name: protein adenylyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: ATP + protein = diphosphate + adenylyl-protein; mediates the addition of an adenylyl (adenosine 5'-monophosphate; AMP group) to specific residues of target proteins." [GOC:mah, PMID:19039103, PMID:19362538]
synonym: "adenosine monophosphate-protein transferase activity" EXACT [GOC:mah]
synonym: "AMPylator" RELATED [GOC:mah]
xref: EC:2.7.7.n1
is_a: GO:0070566 ! adenylyltransferase activity
relationship: part_of GO:0018117 ! protein adenylylation
created_by: mah
creation_date: 2009-06-18T01:09:15Z

Also, EC:2.7.7.108 maps to 3 RHEAS (RHEA:54288, RHEA:54292 and RHEA:58120), so add them as xrefs?

**Comment by pgaudet** [comment]
Added EC and RHEA xrefs 

Also removed the link to the single step  BP 'GO:0018117 ! protein adenylylation' 

Thanks, Pascale
