### ISSUE TITLE
Full ontology build does not seem to be able to run all checks to completion

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#25177]
Currently, on the `go-ontology-dev` branch of the pipeline that runs periodic full builds and checks, the checks hang (15hrs anyways) on 
```
robot explain -i ./merged.owl -M unsatisfiability --unsatisfiable all --explanation ./unsatisfiable_explanations_full.md
```
This used to be a fairly fast test, IIRC

Tagging @balhoff

**Comment by kltm** [comment]
Last good build was "Mar 17, 2023, 12:00 AM"

**Comment by kltm** [comment]
Found during https://github.com/geneontology/pipeline/issues/321

**Comment by balhoff** [comment]
@kltm does the actual build perform these same actions? I'm not sure we should be trying to run `robot reason` over this exact collection of inputs: https://github.com/geneontology/pipeline/blob/5f1009621648fe08de0ad37261ed39f1a6b76a12/Jenkinsfile#L421-L445

For example in the real ontology imports we use wbbt-base.owl, not wbbt.owl.

**Comment by kltm** [comment]
@balhoff This is coming in on the 3-times-a-day full build and check we use as a canary. From https://github.com/geneontology/pipeline/blob/5f1009621648fe08de0ad37261ed39f1a6b76a12/Jenkinsfile#L402

**Comment by balhoff** [comment]
I know, but I think it may be too sensitive. Just wondering what part of the build would fail if this exact step was not checked, since building of go-lego is checked in the step before.

**Comment by kltm** [comment]
@balhoff It's originating from sometime about a year ago. How else should unsatisfiable explanations be generated?

**Comment by kltm** [comment]
Talking to @balhoff , we're going to try and limit the messages generated/calculated with `random:2`.

**Comment by kltm** [comment]
We are now getting to an end! Thank you @balhoff
