### ISSUE TITLE
NTR disruption by symbiont of host cell-cell adhesion 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25172]
For GO-PATHGO alignment, we need a new term, NTR disruption by symbiont of host cell-cell adhesion

@genegodbold please provide a reference

**Comment by genegodbold** [comment]
- High temperature requirement A (HtrA; DegQ; protease DO) from Campylobacter jejuni: HtrA is a secreted, heat shock-induced, serine proteinase from C. jejuni involved in the stress response. HtrA triggers shedding of the extracellular, 90 kDa, N-terminal domain of E-cadherin in both polarized and non-polarized cultured cells. Bacteria which did not express HtrA, or which express a catalytically inactive mutant, were deficient in their ability to cross polarized epithelial cell layers [PMID22534208]. HtrA is transported into the extracellular space and cleaves host cell-to-cell junction factors like E-cadherin [PMID30345086]. HtrA of Campylobacter jejuni cuts the host tight junction component claudin-8 (UniProt:P56748), probably between Ala58 and Asn59 [PMID33364202].
- Beta2 toxin (CPB2) from Clostridium perfringens: When intestinal porcine epithelial cells (IPEC-J2) were treated with rCPB2, an increase in paracellular permeability was seen with degradation of zonula occludens-1 protein (ZO-1), claudin-1, and E-cadherein [PMID32649964]. Recombinant CPB2 treatment decreases the expression of ZO-1, claudin-12 and occludin involved in cell-cell adhesion [PMID32717305].
- Exfoliative toxin D (Etd) from Staphylococcus aureus: When injected into neonatal mice, recombinant exfoliative toxin D induced exfoliation of the skin with loss of cell-to-cell adhesion in the upper part of the epidermis as observed in histological examinations, just as was found in neonatal mice injected with ETA or ETB. In the skins of mice injected with ETD, cell surface staining of desmoglein-1, a cadherin type cell-to-cell adhesion molecule in desmosomes, was abolished without affecting that of desmoglein-3 [PMID12228315]. The crystal structures of Eta, Etb, and Etd have been solved [PMID26299923].

**Comment by pgaudet** [comment]
[Term]
id: GO:0141023
name: disruption by symbiont of host cell-cell adhesion
namespace: biological_process
def: "The process by which a symbiont disupts cell-cell adhesion in its host." [GOC:curators]
is_a: GO:0044068 ! modulation by symbiont of host cellular process
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25172" xsd:anyURI
created_by: pg
creation_date: 2023-04-06T09:29:32Z
