### ISSUE TITLE
NTR modification by symbiont of host focal adhesion 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25171]
For alignment of GO and PathGO, we need NTR modification by symbiont of host focal adhesion 

Child of GO:0052043 modification by symbiont of host cellular component

**Comment by pgaudet** [comment]
@genegodbold please provide a reference

**Comment by genegodbold** [comment]
- Certhrax toxin (Q4MV79): Certhrax toxin ADP-ribosylates Arg433 of the host cytoplasmic protein vinculin which disrupts host focal adhesions and redistributes vinculin to the cytoplasm [PMID24573681]. 
- Cell cycle inhibiting factor of Escherichia coli (Cif) is a bacterial effector of the T3SS that induces the formation of actin stress fibers through the recruitment of focal adhesions [PMID14651638].
- Hemorrhagic toxin (TcsH) of Paeniclostridium sordelli has highest enzymatic activity toward the mouse small GTPase Rac1, but it can also glucosylate RhoA, RhoB, RhoC, Cdc42, Rap2a, and RalC. This causes a rapid dephosphorylation of paxillin which precedes actin depolymerization in Vero cells. Focal adhesion components are redistributed into the cytosol [PMID24905543].
- CagA from Helicobacter pylori: CagA is targeted to focal adhesions by the CagL adhesin protein through its RGD motif. CagL appears to stimulate activity of the kinases (including Src) present at focal adhesions, thereby increasing the tyrosine kinase activity necessary for CagA activation [PMID17943123]. CagA is a T4SS effector injected into the host cytosol by Helicobacter pylori. It is then phosphorylated by a host Src kinase and causes cell elongation and increased motility. CagA both increases the Src kinase activity and stimulates the activity of the host phosphotyrosine phosphatase SHIP-2. This results in the dephosphorylation of (among other things) host cortactin. This dysregulates actin dynamics and can result in dramatic cytoskeletal changes [PMID16102958]
- Outer surface protein E1 (OspE1) from Shigella: OspE of S. flexneri is composed of two proteins OspE1 and OspE2. OspE is highly conserved among strains of E. coli, Citrobacter rodentium, and Salmonella. OspE interacts with the host integrin-linked kinase (ILK) at focal adhesions. The OspE-ILK complex interferes with the disassembly of focal adhesions. OspE expression in S. flexneri prevents cell rounding and detachment in culture upon infection, stabilizing integrin-containing sites of adhesion [PMID19489119]. OspE proteins interact with host PDLIM7 [PMID25124035].

**Comment by pgaudet** [comment]
[Term]
id: GO:0141029
name: disruption by symbiont of host focal adhesion
namespace: biological_process
def: "The process by which a symbiont disupts host focal adhesion in its host." [PMID:24573681]
is_a: GO:0044068 ! modulation by symbiont of host cellular process
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25171" xsd:anyURI
created_by: pg
creation_date: 2023-04-06T09:29:32Z
