### ISSUE TITLE
Update EC number for children of GO:0008373 sialyltransferase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25189]
- [x] EC:2.4.99.2 Transferred entry: EC:2.4.3.2 
- [x] EC:2.4.99.3 Transferred entry: EC:2.4.3.3
- [x] EC:2.4.99.4 Transferred entry: EC:2.4.3.4
- [x] EC:2.4.99.5 Transferred entry: EC:2.4.3.5
- [x] EC:2.4.99.6 Transferred entry: EC:2.4.3.6  GO:0008118
- [x] EC:2.4.99.7 Transferred entry: EC:2.4.3.7
- [x] EC:2.4.99.8 Transferred entry: EC:2.4.3.8
- [x] EC:2.4.99.9 Transferred entry: EC:2.4.3.9
- [x] 2.4.99.10 Transferred entry: 2.4.99.6, itself transferred EC:2.4.3.6
* EC:2.4.99.10 is xref of GO:0004513 
* EC:2.4.99.6 is xref of  GO:0008118
* both terms have RHEA xrefs
Add EC:2.4.3.6 as broadMatch to both
- [x] EC:2.4.99.11 Transferred to EC:2.4.99.1 and then to EC:2.4.3.1
EC:2.4.99.11 is GO:0047287 'lactosylceramide alpha-2,6-N-sialyltransferase activity'
and EC:2.4.99.1  is mapped to GO:0003835 'beta-galactoside alpha-2,6-sialyltransferase activity'
GO:0047287 'lactosylceramide alpha-2,6-N-sialyltransferase activity' has no annotations, I suggest we obsolete with replaced by 'GO:0003835 'beta-galactoside alpha-2,6-sialyltransferase activity'

- [x] parent class "GO:0008373 sialyltransferase activity":  add partial EC:2.4.3.-

**Comment by pgaudet** [comment]
Hi @edwong57 
I made some documentation for updating EC numbers here: https://wiki.geneontology.org/Updating_EC_mappings

Let me know if the documentation has enough information to update these, or how it could be improved. 

Thanks, Pascale

**Comment by sjm41** [comment]
Hi @edwong57 I've run into some issues computing metabolic pathways in BioCyc because of these out-dated sialyltransferase EC xrefs.  Would you be able to fix them in the GO sometime soon?  Many thanks, Steven.

**Comment by edwong57** [comment]
@sjm41 Apologies, I was out of town. I will take care of it this week.

**Comment by edwong57** [comment]
I am also going to obsoleted GO:0004513 'neolactotetraosylceramide alpha-2,3-sialyltransferase activity' since the 2.4.99.10 Transferred entry: 2.4.99.6, itself transferred EC:2.4.3.6 and then it became a duplicate of GO:0008118 'N-acetyllactosaminide alpha-2,3-sialyltransferase activity'. They both have no annotations, but GO:0008118 has the accepted name in Expasy.

**Comment by sjm41** [comment]
Thanks @edwong57 !

**Comment by pgaudet** [comment]
Hi @edwong57 
Just FYI I- the dbxrefs should be removed from the obsoleted terms - see https://wiki.geneontology.org/Obsoleting_an_Existing_Ontology_Term#5._Cross-references (I fixed this one) 

Thanks, Pascale

**Comment by edwong57** [comment]
Okay. Thank you!
________________________________
