### ISSUE TITLE
Obsoletion request: GO:0000469 cleavage involved in rRNA processing, GO:0000478 endonucleolytic cleavage involved in rRNA processing, GO:0000459 exonucleolytic trimming involved in rRNA processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25184]
Please provide as much information as you can:

* **GO term ID and Label**
- [x] GO:0000469 cleavage involved in rRNA processing
GO:0000478 endonucleolytic cleavage involved in rRNA processing
GO:0000459 exonucleolytic trimming involved in rRNA processing

Biological Process

Which term do you propose this term merge into? Provide GO ID and term label
GO:0006364 rRNA processing

Reason for merge

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x]  The reason for obsoletion is that this term is pre-composed and should be represented as a GO-CAM model.
 - [x] The reason for obsoletion is that this term represents a molecular function.

* **"Replace by" term (ID and label)**
GO:0006364 rRNA processing

* **Are there annotations to this term?**
- How many EXP:
GO:0000469 cleavage involved in rRNA processing (NO DIRECT ANNOTATIONS)
GO:0000478 endonucleolytic cleavage involved in rRNA processing (NO DIRECT ANNOTATIONS)
GO:0000459 exonucleolytic trimming involved in rRNA processing  (NO DIRECT ANNOTATIONS)

NOTe that there are other descendant terms that represent pathways and will be rehoused under RNA processing

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
rehouse

Rehouse
GO:0000467	exonucleolytic trimming to generate mature 3'-end of 5.8S rRNA from tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA)
GO:0000465	exonucleolytic trimming to generate mature 5'-end of 5.8S rRNA from tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA)
GO:0000449	endonucleolytic cleavage of tricistronic rRNA transcript (SSU-rRNA, LSU-rRNA, 5S)
GO:0000450	cleavage of bicistronic rRNA transcript (SSU-rRNA, LSU-rRNA)
GO:0000479	endonucleolytic cleavage of tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA)
GO:0000477	generation of mature 5'-end of LSU-rRNA from tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA)
GO:0000483	endonucleolytic cleavage of tetracistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, 2S rRNA, LSU-rRNA)

**Comment by ValWood** [comment]
rehoused
id: GO:0000449 endonucleolytic cleavage of tricistronic rRNA transcript (SSU-rRNA, LSU-rRNA, 5S)
-is_a: GO:0000478 ! endonucleolytic cleavage involved in rRNA processing
+is_a: GO:0006364 ! rRNA processing
 

 id: GO:0000450 name: cleavage of bicistronic rRNA transcript (SSU-rRNA, LSU-rRNA)
-is_a: GO:0000478 ! endonucleolytic cleavage involved in rRNA processing
+is_a: GO:0006364 ! rRNA processing

 id: GO:0000465 name: exonucleolytic trimming to generate mature 5'-end of 5.8S rRNA from tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA)
 namespace: biological_process
-is_a: GO:0000459 ! exonucleolytic trimming involved in rRNA processing
 ALREADY is_a: GO:0000967 ! rRNA 5'-end processing

 id: GO:0000467 exonucleolytic trimming to generate mature 3'-end of 5.8S rRNA from tricistronic rRNA transcript (SSU-rRNA, 5.8S rRNA, LSU-rRNA)
-is_a: GO:0000459 ! exonucleolytic trimming involved in rRNA processing
 ALREADY  is_a: GO:0031125 ! rRNA 3'-end processing
 
id: GO:0000470
name: generation of mature 5'-end of LSU-rRNA from tricistronic rRNA transcript
-is_a: GO:0000469 ! cleavage involved in rRNA processing
 ALREADY  is_a: GO:0000967 ! rRNA 5'-end processing

**Comment by ValWood** [comment]
GO:0000469   cleavage involved in rRNA processing
is still in the ontology?

**Comment by pgaudet** [comment]
It's obsoleted on my local branch. Are you sure you're on master and you 'git pulled'? 

Thanks, Pascale

**Comment by ValWood** [comment]
Phew . It's still in PomBAse I didn't check protege, I should have done that! They usually disappear from PomBAse in a few days so I guess the snapshot isn't updating?

**Comment by pgaudet** [comment]
Right we've been having issues with snapshot. The last successful one is from 03-30 

You can use this link to check the date of the current snapshot: 
http://snapshot.geneontology.org/metadata/date.txt

**Comment by pgaudet** [comment]
Close?
