### ISSUE TITLE
NTR: cyclic-di-AMP binding

### ISSUE THREAD

**Issue by danielhhaft** [geneontology/go-ontology#25203]
Please provide as much information as you can: 

* **cyclic-di-AMP binding**

* **Definition (free text)**
Binding to cyclic-di-AMP, cyclic dimeric adenosine monophosphate
* **Reference, in format PMID:#######**
(REQUIRED)
PMID:32843560
PMID:36629470

* **Gene product name and ID to be annotated to this term**
c-di-AMP-binding protein CbpB

* **Parent term(s)**
GO:0030551,  GO:0032559

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by danielhhaft** [comment]
This should become a sibling of GO:0035438, cyclic-di-GMP binding. So I'm hoping it will be pretty easy.

**Comment by ValWood** [comment]
- [x] I added "cyclic dimeric adenosine monophosphate" as an exact synonym.
- [x] Checked parentage in CHEBI

(it is a sib of GO:0035438)

**Comment by ValWood** [comment]
did not autclose?

+[Term]
+id: GO:0180001
+name: cyclic-di-AMP binding
+def: "Binding to a cyclic di-AMP nucleotide." [PMID:32843560, PMID:36629470]
+synonym: "cyclic dimeric adenosine monophosphate binding" EXACT []
+is_a: GO:0030551 ! cyclic nucleotide binding
+is_a: GO:0032559 ! adenyl ribonucleotide binding
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25203" xsd:string
