### ISSUE TITLE
Obsoletion request: GO:0060547 negative regulation of necrotic cell death GO:0010939 regulation of necrotic cell death GO:0010940 positive regulation of necrotic cell death

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25218]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0060547 negative regulation of necrotic cell death
GO:0010939 regulation of necrotic cell death
GO:0010940 positive regulation of necrotic cell death

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x]  The reason for obsoletion is that this represents a phenotype.

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP: 49

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***

- [x] create annotation review ticket: 
https://github.com/geneontology/go-annotation/issues/4530

- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by shurjenw** [comment]
If  "....necrotic cell death" represents a phenotype, then adding "programmed" to a phenotype term still makes it to represent a phenotype.

**Comment by ValWood** [comment]
The term has been used to frequently to annotate any cell death phenotypes, because it is not specific enough in scope.

You should only make a GO annotation, if the annotation represents an example of programmed necrotic cell death. If it is only necrotic cell death, then the annotation represents a phenotype and should not be annotated.

You need to check that the  annotation is part of some evolved pathway where the intended outcome  is cell death, and not just a phenotypic outcome of the loss of a gene product.

Probably the reason for obsoletion could be more explicit here:

e.g. The reason for obsoletion because as defined it is not clearly an evolved process.
@pgaudet 
is the current reason for obsoletion OK, it was the best fir that I could see.

**Comment by pgaudet** [comment]
Yes, this is right, necrotic cell death is not an 'evolved process'. See comment in GO:0070265 'necrotic cell death', which indicates that this term is outside the scope of GO (but we used to be less strict about 'evolved processes')

Note that the word necrosis has been widely used in earlier literature to describe forms of cell death which are now known by more precise terms, such as apoptosis. Necrosis can occur in a regulated fashion, involving a precise sequence of signals; in this case, consider annotating to GO:0097300 'programmed necrotic cell death' or to its more specific child GO:0070266 'necroptotic process'.

Thanks, Pascale

**Comment by shurjenw** [comment]
Thank you. That makes sense.
