### ISSUE TITLE
Ontology no longer builds due to file renaming in biopax.zip

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#25229]
Previously in https://reactome.org/download/current/biopax.zip, the "Homo sapiens.owl" file was named "Homo_sapiens.owl", which our pipeline is coded for. It seems that with the last release, all filenames have had underscores replaced with spaces.

We'd like to know if this was intentional and stable (in which case we'll have to update our pipeline) or if this was an oversight (in which case we'd wait for an upstream fix).

Personally, I think underscores are easier to handle in the world of scripts, subscripts, and pipeline code, so would be happy with a return to underscores.

**Comment by kltm** [comment]
This is a problem that prevents the running of production and ontology-related pipelines. Tagging @dustine32 and @balhoff .

**Comment by kltm** [comment]
@dustine32 has emailed @adamjohnwright

**Comment by adamjohnwright** [comment]
@dustine32 I have found the issue from the Reactome side of things: https://github.com/reactome/release-download-directory/blame/c31db25fc833bb0e5cd4672d99fb3a10cddd9f8d/src/main/java/org/reactome/release/downloaddirectory/Biopax.java#L102.

I believe the intent of this line was to replace the spaces in the name with underscores. If this is true it is clearly not working. I will add a fix. Future BioPax files should contain the fix.

**Comment by kltm** [comment]
@adamjohnwright Just to clarify our next actions, when you say "[f]uture BioPax files should contain the fix", does that mean the next release (we'll need to redo some of our pipeline code and then revert) or will this be fixed/updated in the "current" release?

**Comment by kltm** [comment]
Talked to @adamjohnwright and he said that: 1) one way or another having the underscore should be correct and 2) he's going to talk to the person who made the files and see if there is a short-term fix (i.e. the current) that can be put in within the next day or so and will let us know.

For now, I think we should just let the pipelines flail for a day or so, rather than changing and reverting. If we don't hear back (unlikely) or they cannot redeploy easily, we can change our code and put in a ticket for changing it back at the next release.

**Comment by kltm** [comment]
@adamjohnwright It looks like this issue has cropped up again? Our most recent build failed on looking for the file with the underscore.

**Comment by kltm** [comment]
Odd, the code looks right?
https://github.com/reactome/release-download-directory/blame/c31db25fc833bb0e5cd4672d99fb3a10cddd9f8d/src/main/java/org/reactome/release/downloaddirectory/Biopax.java#L91

**Comment by adamjohnwright** [comment]
You are correct. I will get the person that generated the file to fix this asap.

**Comment by adamjohnwright** [comment]
Looping him in here @jweiser

**Comment by adamjohnwright** [comment]
@kltm I just fixed this on production. I have actually been planning on working on modernizing our pipeline for generating these files. I have been promising this for a while. It is actually the next thing on my list.

**Comment by kltm** [comment]
@adamjohnwright Great! Thank you for all of your help.

**Comment by pgaudet** [comment]
I assume this is fixed. Ontology has successfully built since then.
