### ISSUE TITLE
EC:3.2.1.47 transferred to EC:3.2.1.22

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25227]
Hello, 

EC:3.2.1.47 transferred to [EC:3.2.1.22](https://enzyme.expasy.org/EC/3.2.1.22) , which corresponds to alpha-galactosidase

In GO **EC:3.2.1.47** is mapped to GO:0017041 'galactosylgalactosylglucosylceramidase activity':  Catalysis of the reaction: D-galactosyl-D-galactosyl-D-glucosyl-N-acylsphingosine + H2O = lactosyl-N-acylsphingosine + D-galactose.

and **EC:3.2.1.22** corresponds to GO:0004557 'alpha-galactosidase activity': Catalysis of the hydrolysis of terminal, non-reducing alpha-D-galactose residues in alpha-D-galactosides, including galactose oligosaccharides, galactomannans and galactolipids.
In RHEA  **EC:3.2.1.22** maps to RHEA:21112: globoside Gb3Cer (d18:1(4E)) + H2O = a beta-D-Gal-(1->4)-beta-D-Glc-(1<->1)-Cer(d18:1(4E)) + D-galactose, which seems more specific that the reaction described by EC, although there is no more general reaction for RHEA:21112. 

@kaxelsen what do you recommend we do?

**Comment by kaxelsen** [comment]
I don't know. The reaction for EC 3.2.1.47 is a specific instance of EC 3.2.1.22 that we are not able to create in Rhea so it is represented in UniProtKB entries by the text reaction you cite above. RHEA:21112 is linked to EC 3.2.1.22 as an non-IUBMB reaction. 

Unfortunately, I have no good idea how best to deal with this for GO.

**Comment by pgaudet** [comment]
Thanks for checking ! Much appreciated.

**Comment by pgaudet** [comment]
I will obsolete GO:0017041 'galactosylgalactosylglucosylceramidase activity with REPLACED BY GO:0004557 'alpha-galactosidase activity, because this is the specificity of the enzymes annotated, and I add both RHEAs to GO:0004557 'alpha-galactosidase activity as narrowMatches.
