### ISSUE TITLE
Question about deubiquitinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25231]
ubp8  is a deubiquitinase

<img width="954" alt="ubp8 report GO" src="https://user-images.githubusercontent.com/7359272/230021945-3e997a29-f451-476a-900c-532fc4bb7bcd.png">

There is a mapping to cysteine-type endopeptidase.

Should cysteine-type deubiquitinase be a cysteine-type endopeptidase? Otherwise the annotation transfer would seem to be incorrect?

**Comment by ValWood** [comment]
Who would know this?

**Comment by pgaudet** [comment]
Actually deubiquitinase cleaves isopeptide bonds, while an endopeptidase cleaves peptide bonds. So, cysteine-type deubiquitinase  is not a type of cysteine-type endopeptidase.
