### ISSUE TITLE
positive regulation of gene expression - no transcription child

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#25256]
Hi Pascale

Please would you check the transcription ontology. 

The term 
GO:0045944 positive regulation of transcription by RNA polymerase II
needs to be a child of positive regulation of gene expression

similarly GO:0000122 negative regulation of transcription by RNA polymerase II
needs to be a child of negative regulation of gene expression

I haven't checked the whole regulation ontology for this branch

Thanks
Ruth

**Comment by pgaudet** [comment]
Thanks for pointing that out. I added GO:0006355 'regulation of DNA-templated transcription' 
is_a GO:0010468 regulation of gene expression
(instead of 'regulates' some 'gene expression'... which I thought should be equivalent, but lets' see
