### ISSUE TITLE
tRNA (guanosine 34-2'-O)-methyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25257]
here
https://github.com/geneontology/go-ontology/issues/17665

https://github.com/geneontology/go-ontology/issues/17665#issuecomment-722692360

+id: GO:0106340
+name: tRNA (guanosine 32-2'-O)-methyltransferase activity
was added.
But it should have been

+name: tRNA (guanosine 34-2'-O)-methyltransferase activity

is it OK for this to just be edited? PomBase has the only current EXP annotation and

the referenced paper mentions G34 but not G32

CC @Antonialock

**Comment by Antonialock** [comment]
From table 2 in 36720500 it is in my understanding that across several species, trm7/ftsj1 methylates C and U at position 32 and C and G at position 34

**Comment by Antonialock** [comment]
so I would assume that the term can be edited, it looks like a typo

**Comment by ValWood** [comment]
That's what I thought,  did you need any additional terms?

**Comment by sjm41** [comment]
I think these xrefs can be added to this term (as narrow xrefs?):

EC 2.1.1.205 (https://enzyme.expasy.org/EC/2.1.1.205)
tRNA (cytidine(32)/guanosine(34)-2'-O)-methyltransferase

 = [RHEA:42396](https://www.rhea-db.org/rhea/42396)

**Comment by ValWood** [comment]
I fixed this.

@pgaudet  how should these RHEA and EC be added if they are narrow? Can we do that?
