### ISSUE TITLE
Missing parent: GO:0006897  endocytosis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25268]
* **GO term ID and label for which you request a new superclass**

GO:0006897  endocytosis
A vesicle-mediated transport process in which cells take up external materials or membrane constituents by the invagination of a part of the plasma membrane to form a new membrane-bounded vesicle.

* **New superclass (parent) suggested**
GO:0098657   import into cell

The directed movement of some substance from outside of a cell into a cell. This may occur via transport across the plasma membrane or via endocytosis.

**Comment by ValWood** [comment]
@pgaudet  agreed? it has to be right, based on the defs.

**Comment by ValWood** [comment]
has a logical def

'vesicle-mediated transport'
 and ('process has causal agent' some 'endocytic vesicle')

does something need adding to this?

**Comment by ValWood** [comment]
But should "import into cell "also be added as a parent?
I can't think of any reason that this parent would not be true.

**Comment by pgaudet** [comment]
Yes, I had done that as well (see [diff](https://github.com/geneontology/go-ontology/commit/df992602f0765cae04b0e9dea655d1c392e14454) : 

Added: 
[endocytosis](http://purl.obolibrary.org/obo/GO_0006897) SubClassOf [import into cell](http://purl.obolibrary.org/obo/GO_0098657)
