### ISSUE TITLE
Question GO:0042790,nucleolar large rRNA transcription by RNA polymerase I

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25266]
Should this term exist?
GO:0042790,nucleolar large rRNA transcription by RNA polymerase I

It isn't a different process from 
GO:0006360  transcription by RNA polymerase I

**Comment by krchristie** [comment]
These two terms are not actually synonymous as there are some species where RNAP I is involved in transcription of a select set of protein coding genes (has been observed in some Trypanosomes, if I remember correctly).

I was wondering if the more specific term "**nucleolar large rRNA transcription by RNA polymerase I (GO:0042790)**" was actually being used, and was surprised by the fact that there is significant annotation to this term. Here are a couple tables.


Here's a table by evidence code of all the terms that map up to "**transcription by RNA polymerase I (GO:0006360)**
![20230424-RNAP_I-txn-allAnnots-PT](https://user-images.githubusercontent.com/10533218/234137299-4c9d71dc-8574-4631-bcd2-cd2a51b71b80.jpg)

Here's a more detailed table of just the two terms in question that includes Contributor:

![20230424-RNAP_I-txn-allAnnots-PT-2ermsByContr](https://user-images.githubusercontent.com/10533218/234137317-d823f4c6-60b6-41fc-8217-8ef02a5af24e.jpg)

**Comment by ValWood** [comment]
OK can close this.
