### ISSUE TITLE
(possible) Term merge: GO:0043723,2.5-diamino-6-ribitylamino-4(3H)-pyrimidinone 5'-phosphate deaminase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25262]
* **Term to be merged: Provide GO ID and term label**

GO:0043723,**2.5-diamino-6-ribitylamino-4(3H)-pyrimidinone 5'-phosphate deaminase activity**
Catalysis of the reaction: 2,5-diamino-6-(5-phospho-D-ribitylamino)pyrimidin-4(3H)-one + H2O = 5-amino-6-(5-phospho-D-ribosylamino)uracil + ammonia.

with
GO:0008835 diaminohydroxyphosphoribosylaminopyrimidine deaminase activity
Catalysis of the reaction: 2,5-diamino-6-hydroxy-4-(5-phosphoribosylamino)-pyrimidine + H2O + H+ = 5-amino-6-(5-phosphoribosylamino)uracil + NH4.

has exact synonym
**2,5-diamino-6-(ribosylamino)-4(3H)-pyrimidinone 5'-phosphate deaminase activity**?

**Comment by pgaudet** [comment]
Yes, these should be merged. 

GO:0043723 maps to [MetaCyc:RXN-10058](https://biocyc.org/META/NEW-IMAGE?type=NIL&object=RXN-10058) which corresponds to EC:3.5.4.26 which is the EC mapping for GO:0008835 

GO:0008835 : 3 EXP
GO:0043723: 1 EXP


I propose we obsolete GO:0043723 & replace by GO:0008835
Move reference [PMID:11889103](http://www.ncbi.nlm.nih.gov/pubmed/11889103) to GO:0008835


Thanks, Pascale

**Comment by raymond91125** [comment]
Dear all,

The proposal has been made to obsolete GO:0043723 2.5-diamino-6-ribitylamino-4(3H)-pyrimidinone 5'-phosphate deaminase activity.

The reason for obsoletion is that this term represents the same function as GO:0008835 diaminohydroxyphosphoribosylaminopyrimidine deaminase activity.

The terms will be replaced by the parent, so no reannotation is needed (1 from SGD).

Annotation review ticket: https://github.com/geneontology/go-annotation/issues/4944

The term is not present in any subsets.

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25262
