### ISSUE TITLE
Fix def of  GO:0006357 'regulation of transcription by RNA polymerase II' to include bacteria more explicitely

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25260]
Requesst from @amandamackie in https://github.com/geneontology/go-annotation/issues/4532

> could the definition of that term be changed to make it clear that it includes bacterial-type RNA polymerase. I saw GO:0006357 but didn't think it was appropriate because it appears to be specific for RNA pol II which is a eukaryote-specific term.

> I can see that there are some molecular function terms specific for bacterial-type RNA polymerase eg. GO:0001108 bacterial-type RNA polymerase holo enzyme binding.

**Comment by krchristie** [comment]
"regulation of transcription by RNA polymerase II" is **DEFINITELY NOT** applicable to bacteria.

Bacteria have ONLY a single RNA polymerase. It is a multisubunit enzyme with a core composition referred to as beta beta' alpha (x2). The sigma subunit of bacterial RNAP is a promoter specificity subunit and there are several different ones with different sequence specificities. Some of the plant plastid RNA polymerases are multisubunit RNAPs with a bacterial type subunit composition.

All eukaryotes have three nuclear multisubunit RNA polymerases, RNAP I (rDNA), RNAP II (mRNA and some snRNAs), and RNAP III (tRNAs and some snRNAs). Plants have two additional multisubuit RNA polymerases, IV and V, both of which appear to be involved in transcription of various regulatory non-coding RNAs. 

There are conserved subunits between bacterial type multisubunit RNA polymerases and eukaryotic multisubunit RNA polymerases, but bacterial type RNAP enzymes are not a type of RNAP II. RNAP II specific terms should absolutely **NOT** be the parent term for RNA polymerase related terms that refer to any other specific RNAP enzyme

**Comment by pgaudet** [comment]
I was mentioning the wrong term in the annotation ticket, this is not relevant.
