### ISSUE TITLE
Missing parent: GO:0160007 | glutathione import into mitochondrion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25275]
* **GO term ID and label for which you request a new superclass**

GO:0160007 | glutathione import into mitochondrion

* **New superclass (parent) suggested**

GO:1990542 | mitochondrial transmembrane transport

* **Reference(s), if appropriate**
PMID:nnnnnnn

Should the reasoner add this?

**Comment by pgaudet** [comment]
yes, but the logical definitions are inconsistent. 

@balhoff is this flagged anywhere?

**Comment by pgaudet** [comment]
Hi @ValWood 
If you want to do this: the logical definition of 'mitochondrial transmembrane transport' should be 

transport
 and ('has target start location' some cytosol)
 and ('has target end location' some 'mitochondrial matrix')
 and ('results in transport across' some 'mitochondrial membrane')

This should make GO:0160007 | glutathione import into mitochondrion a child when you re-run the reasoner.  
Thanks, Pascale

**Comment by ValWood** [comment]
I changed the logical def as described and I still don't see this term under "mitochondrial transmembrane transport"

In fact, this is ALL that is there:
<img width="456" alt="Screenshot 2023-04-14 at 11 02 29" src="https://user-images.githubusercontent.com/7359272/233279355-d1ac41f2-0860-4786-bec8-c7bae411f390.png">

**Comment by ValWood** [comment]
Ignore, I was only looking at asserted
