### ISSUE TITLE
Add EC:2.7.1.174 to GO:0004143 diacylglycerol kinase activity ?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25280]
GO:0004143 diacylglycerol kinase activity already has EC:2.7.1.107 as an xref, which is:
EC:2.7.1.107
Name: diacylglycerol kinase (ATP) 
Reaction: a 1,2-diacyl-sn-glycerol + ATP <=> a 1,2-diacyl-sn-glycero-3-phosphate + ADP + H(+)

From the definition of GO:0004143, and the "CTP:diacylglycerol kinase activity" synonym, we should add EC:2.7.1.174 (or create two children terms for the ATP- vs CTP-dependent reactions):
EC:2.7.1.174
Name: diacylglycerol kinase (CTP)
Reaction: a 1,2-diacyl-sn-glycerol + CTP <=> a 1,2-diacyl-sn-glycero-3-phosphate + CDP + H(+)

id: GO:0004143
name: diacylglycerol kinase activity
namespace: molecular_function
def: "Catalysis of the reaction: NTP + 1,2-diacylglycerol = NDP + 1,2-diacylglycerol-3-phosphate." [EC:2.7.1.107, GOC:elh]
synonym: "1,2-diacylglycerol kinase (phosphorylating)" RELATED [EC:2.7.1.107]
synonym: "1,2-diacylglycerol kinase activity" RELATED [EC:2.7.1.107]
synonym: "arachidonoyl-specific diacylglycerol kinase activity" RELATED [EC:2.7.1.107]
synonym: "ATP:1,2-diacylglycerol 3-phosphotransferase activity" NARROW [EC:2.7.1.107]
synonym: "ATP:diacylglycerol phosphotransferase activity" NARROW [EC:2.7.1.107]
synonym: "CTP:diacylglycerol kinase activity" NARROW []
synonym: "DG kinase activity" RELATED [EC:2.7.1.107]
synonym: "DGK activity" RELATED [EC:2.7.1.107]
synonym: "diacylglycerol:ATP kinase activity" NARROW [EC:2.7.1.107]
synonym: "diglyceride kinase activity" RELATED [EC:2.7.1.107]
synonym: "sn-1,2-diacylglycerol kinase activity" RELATED [EC:2.7.1.107]
xref: EC:2.7.1.107
xref: MetaCyc:DIACYLGLYKIN-RXN
xref: RHEA:10272
is_a: GO:0001727 ! lipid kinase activity
is_a: GO:0016773 ! phosphotransferase activity, alcohol group as acceptor

**Comment by sjm41** [comment]
Thanks, makes sense.

Should we change the name of GO:0004143 to "ATP-dependent diacylglycerol kinase activity" (to match its EC/RHEA xrefs) and replace NTP with ATP in the definition?
Also remove its "CTP:diacylglycerol kinase activity" xref.

**Comment by pgaudet** [comment]
Added taxon constraint: 
GO:0141035 CTP-dependent diacylglycerol kinase activity NCBITaxon:4751 Fungi
