### ISSUE TITLE
acetyl-CoA C-acetyltransferase activity (GO:0003985) parentage

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25289]
We currently have this arrangement:

```
C-acyltransferase activity
|__acetyl-CoA C-acyltransferase activity (GO:0003988, EC:2.3.1.16, RHEA:21564)
	|__acetyl-CoA C-acetyltransferase activity (GO:0003985, EC:2.3.1.9, RHEA:21036)
```

GO:0003988/EC:2.3.1.16 is:
Catalysis of the reaction: acyl-CoA + acetyl-CoA = CoA + 3-oxoacyl-CoA.

And GO:0003985/EC:2.3.1.9 is: 
Catalysis of the reaction: 2 acetyl-CoA = CoA + acetoacetyl-CoA

But I don't think the latter is a sub-class of the former?
Supporting that, https://www.rhea-db.org/rhea/21564 doesn't list RHEA:21036 as a 'specific form of this reaction'.

So, I think the "is_a: GO:0003988 ! acetyl-CoA C-acyltransferase activity" should be removed from GO:0003985:

id: GO:0003985
name: acetyl-CoA C-acetyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2 acetyl-CoA = CoA + acetoacetyl-CoA." [EC:2.3.1.9]
synonym: "2-methylacetoacetyl-CoA thiolase" BROAD [EC:2.3.1.9]
synonym: "3-oxothiolase activity" RELATED [EC:2.3.1.9]
synonym: "acetoacetyl-CoA thiolase activity" RELATED [EC:2.3.1.9]
synonym: "acetyl coenzyme A thiolase activity" RELATED [EC:2.3.1.9]
synonym: "acetyl-CoA acetyltransferase activity" RELATED [EC:2.3.1.9]
synonym: "acetyl-CoA:acetyl-CoA C-acetyltransferase activity" RELATED [EC:2.3.1.9]
synonym: "acetyl-CoA:N-acetyltransferase activity" RELATED [EC:2.3.1.9]
synonym: "beta-acetoacetyl coenzyme A thiolase activity" RELATED [EC:2.3.1.9]
synonym: "thiolase II" RELATED [EC:2.3.1.9]
xref: EC:2.3.1.9
xref: MetaCyc:ACETYL-COA-ACETYLTRANSFER-RXN
xref: RHEA:21036
xref: UM-BBD_enzymeID:e0144
is_a: GO:0003988 ! acetyl-CoA C-acyltransferase activity
is_a: GO:0016453 ! C-acetyltransferase activity

**Comment by deustp01** [comment]
For what it's worth https://byjus.com/question-answer/is-acyl-and-acetyl-the-same/ says that an acetyl group is_a acyl group, specifically the one where the "R" moiety of the acyl is CH3.

**Comment by kaxelsen** [comment]
> @kaxelsen Isn't acetyl an acyl? why isn't RHEA:21036 a more specific reaction of RHEA:21564 ?
> 
> Thanks, Pascale

@pgaudet, Yes it is, and I have now added the relationship.
