### ISSUE TITLE
NTR: diphthine methyl ester synthase (EC:2.1.1.314)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25281]
diphthine synthase activity (GO:0004164) currently has EC:2.1.1.98 as an xref, which is specific for the archaeal enzyme.  Please add EC:2.1.1.314/RHEA:42652, which is for the eukaryotic enzyme.

EC:2.1.1.98
Name: diphthine synthase
Reaction: 2-[(3S)-amino-3-carboxypropyl]-L-histidyl-[translation elongation factor 2] + 3 S-adenosyl-L-methionine <=> diphthine-[translation elongation factor 2] + 3 H(+) + 3 S-adenosyl-L-homocysteine
Comments: This archaeal enzyme produces the trimethylated product diphthine, which is converted into diphthamide by EC 6.3.1.14.  Different from the eukaryotic enzyme, which produces diphthine methyl ester (cf. EC 2.1.1.314).

EC:2.1.1.314
Name: diphthine methyl ester synthase
Alt_name: diphthine methyltransferase
Reaction: 2-[(3S)-amino-3-carboxypropyl]-L-histidyl-[translation elongation factor 2] + 4 S-adenosyl-L-methionine <=> diphthine methyl ester-[translation elongation factor 2] + 3 H(+) + 4 S-adenosyl-L-homocysteine
Comments: This eukaryotic enzyme is part of the biosynthetic pathway of diphthamide.Different from the archaeal enzyme, which performs only 3 methylations, producing diphthine (cf. EC 2.1.1.98).

id: GO:0004164
name: diphthine synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + 2-(3-carboxy-3-aminopropyl)-L-histidine = S-adenosyl-L-homocysteine + 2-(3-carboxy-3-(methylammonio)propyl)-L-histidine." [PMID:15485916, PMID:20873788, PMID:3042777]
synonym: "diphthine methyltransferase activity" RELATED [EC:2.1.1.98]
synonym: "S-adenosyl-L-methionine:2-(3-carboxy-3-aminopropyl)-L-histidine methyltransferase activity" RELATED [EC:2.1.1.98]
synonym: "S-adenosyl-L-methionine:elongation factor 2 methyltransferase activity" RELATED [EC:2.1.1.98]
xref: EC:2.1.1.98
xref: MetaCyc:RXN-11370
xref: RHEA:36415
is_a: GO:0008757 ! S-adenosylmethionine-dependent methyltransferase activity

**Comment by sjm41** [comment]
Hmmm.
2 of the 3 current refs on the GO term are for yeast, and the other one is for an archeaon, so it seems to attempt to cover both enzymes/reactions.
Only 4 EXP annotations to the term: 3 to eukaryotes (human and yeast), one to an archeaon.

So, I guess we either keep a single GO term with a generic definition and have two narrow EC xrefs, or else we make the current GO term a general parent (no EC xrefs) and create two new specific child terms for each EC?

**Comment by sjm41** [comment]
Thinking some more about this one, I would prefer two separate GO terms, one for each EC.
Not sure if we want/need a grouping parent term for these two or not.

**Comment by sjm41** [comment]
Hi @pgaudet Can we proceed with this one? Thanks!

**Comment by sjm41** [comment]
Hi @pgaudet

Could we make the new term for "diphthine methyl ester synthase (EC:2.1.1.314)"?

Name: diphthine methyl ester synthase activity
Synonyms: diphthine methyltransferase [EC:2.1.1.314]
Def: Catalysis of the reaction: 2-[(3S)-amino-3-carboxypropyl]-L-histidyl-[translation elongation factor 2] + 4 S-adenosyl-L-methionine = diphthine methyl ester-[translation elongation factor 2] + 3 H+ + 4 S-adenosyl-L-homocysteine
Comment: The eukaryotic enzyme is different from the archaeal enzyme, which performs only 3 methylations, producing diphthine. See GO:0004164.
xrefs: EC:2.1.1.314, RHEA:42652, MetaCyc:RXN-15775


Also be good to add the EC:2.1.1.98 comment to GO:0004164 to clarifying things.

3 current manual annotations to GO:0004164 (the archaeal version) will need to be reviewed - two from SGD, one from reactome - they should use the NTR.

**Comment by pgaudet** [comment]
Thanks for the reminder! 

+[Term]
+id: GO:0141133
+name: diphthine methyl ester synthase activity
+namespace: Catalysis of the reaction: 2-[(3S)-amino-3-carboxypropyl]-L-histidyl-[translation elongation factor 2] + 4 S-adenosyl-L-methionine = diphthine methyl ester-[translation elongation factor 2] + 3 H+ + 4 S-adenosyl-L-homocysteine. {xref="RHEA:42652"}
+namespace: molecular_function
+comment: This is present in eukaryotes and is part of the biosynthetic pathway of diphthamide. Note that this is different from the archaeal enzyme, diphthine synthase activity ; GO:0004164 (EC:2.1.1.98), which performs only 3 methylations, producing diphthine.
+xref: EC:2.1.1.314
+xref: RHEA:42652
+is_a: GO:0008757 ! S-adenosylmethionine-dependent methyltransferase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25281" xsd:anyURI
+created_by: pg
+creation_date: 2023-12-20T09:06:24Z
+

**Comment by sjm41** [comment]
Thanks!
Sorry, meant to say that both these GO terms should have ''GO:0008276 protein methyltransferase activity" added as an additional parent.

**Comment by pgaudet** [comment]
- [ ] add taxon constraints

**Comment by pgaudet** [comment]
Also added comment to GO:0004164 diphthine synthase activity 

> This activity is present in archae and produces the trimethylated product diphthine, which is converted into diphthamide by diphthine-ammonia ligase activity ; GO:0017178 (EC:6.3.1.14). Note tha this is different from the eukaryotic enzyme diphthine methyl ester synthase activity ; GO:0141133 (EC:2.1.1.314), which produces diphthine methyl ester.
