### ISSUE TITLE
Obsoletion notice: GO:1901044 protein polyubiquitination involved in nucleus-associated proteasomal ubiquitin-dependent protein catabolic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25298]
Precomposed term; 2 Fly annotations: GO:1901044 protein polyubiquitination involved in nucleus-associated proteasomal ubiquitin-dependent protein catabolic process

@hattrill any objection?

**Comment by pgaudet** [comment]
@hattrill 
I think this term can be obsoleted and replaced by 'GO:0071630 nuclear protein quality control by the ubiquitin-proteasome system'; does that work for you ?

**Comment by hattrill** [comment]
@pgaudet 
It's certainly a long one. I'll recurate this paper - think it might be better annotated to signaling regulation and/or proteasome-mediated ubiquitin-dependent protein catabolic process rather than a QC system. 

No objection to obsoletion. Thanks

**Comment by raymond91125** [comment]
This term is a PART_OF child of 
GO:0071630 | nuclear protein quality control by the ubiquitin-proteasome system
Thus a merge would change the IS_A path. Should it be obsoleted without replacement? Also, do we still need a separate annotation review ticket?

**Comment by pgaudet** [comment]
Perhaps safer to use 'CONSIDER' then.
