### ISSUE TITLE
GO term(s) for EC 1.1.1.330 very-long-chain 3-oxoacyl-CoA reductase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25302]
EC 1.1.1.330
Accepted Name: very-long-chain 3-oxoacyl-CoA reductase
Reaction catalysed: a very-long-chain (3R)-3-hydroxyacyl-CoA + NADP(+) <=> a very-long-chain 3-oxoacyl-CoA + H(+) + NADPH

Which is RHEA:48680

Shall we create a new GO term for this general activity, with EC 1.1.1.330 and RHEA:48680 as xrefs, and then obsolete the current 4 specific GO terms that each have EC 1.1.1.330 as xref (and none of which have any EXP annotations)

id: GO:0102339
name: 3-oxo-arachidoyl-CoA reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: (R)-3-hydroxyicosanoyl-CoA(4-) + NADP(3-) <=> 3-oxoicosanoyl-CoA + NADPH + H+." [EC:1.1.1.330, GOC:pz]
xref: EC:1.1.1.330
xref: MetaCyc:RXN-13298
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

id: GO:0102340
name: 3-oxo-behenoyl-CoA reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: (R)-3-hydroxybehenoyl-CoA(4-) + NADP(3-) <=> 3-oxodocosanoyl-CoA + NADPH + H+." [EC:1.1.1.330, GOC:pz]
xref: EC:1.1.1.330
xref: MetaCyc:RXN-13299
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

id: GO:0102341
name: 3-oxo-lignoceroyl-CoA reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: (R)-3-hydroxylignoceroyl-CoA + NADP <=> 3-oxotetracosanoyl-CoA + NADPH + H+." [EC:1.1.1.330, GOC:pz]
xref: EC:1.1.1.330
xref: MetaCyc:RXN-13300
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

id: GO:0102342
name: 3-oxo-cerotoyl-CoA reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: (R)-3-hydroxycerotoyl-CoA + NADP <=> 3-oxohexacosanoyl-CoA + NADPH + H+." [EC:1.1.1.330, GOC:pz]
xref: EC:1.1.1.330
xref: MetaCyc:RXN-13301
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

**Comment by pgaudet** [comment]
Other terms with EC:1.1.1.-, no annotations, and that represent specific substrates: 

- [x]  GO:0102282 3-ketodihydrosphinganine (C18) reductase activity RXN-12641 removed from MetaCyc: >>OBSOLETE
- [x] GO:0102187  4alpha-carboxy,4beta,14alpha-dimethyl-9beta,19-cyclo-5alpha-cholest-24-en-3beta-ol dehydrogenase/C4-decarboxylase activity MetaCyc:RXN-11949 -> removed from MetaCyc >>OBSOLETE



Other changes:
- [x] GO:0102394 4-hydroxy-L-isoleucine dehydrogenase activity : MetaCyc:RXN-13637 added PMID from MetaCyc - no isolated gene encodes this activity
- [x]  L-glyceraldehyde 3-phosphate reductase activity GO:0103037: linked to [RXN0-5410](https://biocyc.org/META/NEW-IMAGE?type=NIL&object=RXN0-5410), which is linked to E. coli GPR (UniProtKB:Q46851). Added PMID:18620424





Do separately: 
- [ ] GO:0102727  3beta-hydroxysteroid dehydrogenase activity + RHEA:34775 (EC 1.1.1.170 and EC 1.1.1.418)
- [ ] 4alpha-carboxy-stigmasta-7,24(241)-dien-3beta-ol dehydrogenase/C4-decarboxylase activity GO:0102182 [RXN-11938](https://biocyc.org/META/NEW-IMAGE?type=NIL&object=RXN-11938)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141040
+name: very-long-chain 3-oxoacyl-CoA reductase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: a very-long-chain (3R)-3-hydroxyacyl-CoA + NADP+ = a very-long-chain 3-oxoacyl-CoA + H+ + NADPH." [RHEA:48680]
+xref: EC:1.1.1.330
+xref: RHEA:48680
+is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25302" xsd:anyURI
+created_by: pg
+creation_date: 2023-05-17T11:30:31Z

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms that represent specific substrates: 

- GO:0102339 3-oxo-arachidoyl-CoA reductase activity >> replace by GO:0141040 very-long-chain 3-oxoacyl-CoA reductase activity
- GO:0102340  3-oxo-behenoyl-CoA reductase activity  >> replace by GO:0141040 very-long-chain 3-oxoacyl-CoA reductase activity
- GO:0102341 3-oxo-lignoceroyl-CoA reductase activity  >> replace by GO:0141040 very-long-chain 3-oxoacyl-CoA reductase activity
- GO:0102342 3-oxo-cerotoyl-CoA reductase activity  >> replace by GO:0141040 very-long-chain 3-oxoacyl-CoA reductase activity
- GO:0102183 avenastenone reductase activity : MetaCyc[RXN-11939](https://biocyc.org/META/NEW-IMAGE?type=NIL&object=RXN-11939); links to 1.1.1.270, which corresponds to GO:0000253 '3-keto sterol reductase activity' >> OBSOLETE & REPLACE BY GO:0000253 '3-keto sterol reductase activity'
- GO:0102176 'cycloeucalenone reductase activity' also links to 1.1.1.270 >> OBSOLETE & REPLACE BY GO:0000253 '3-keto sterol reductase activity'

Obsolete with no replacements (reactions have been removed from other databases:) 
- GO:0102282 3-ketodihydrosphinganine (C18) reductase activity RXN-12641 removed from MetaCyc: >>OBSOLETE
- GO:0102187 4alpha-carboxy,4beta,14alpha-dimethyl-9beta,19-cyclo-5alpha-cholest-24-en-3beta-ol dehydrogenase/C4-decarboxylase activity MetaCyc:RXN-11949 -> removed from MetaCyc >>OBSOLETE
alpha-ketoglutarate reductase activity (NADH-dependent) GO:0102909: MetaCyc [RXN-8645](https://biocyc.org/META/NEW-IMAGE?type=NIL&object=RXN-8645) removed from MetCyc >>OBSOLETE

- GO:0103030 ethylglyoxal reductase (NADH-dependent, hydroxyacetone-forming) activity : physiological significance of the reaction is unknown, see PMID:16813561 >> OBSOLETE

**Comment by deustp01** [comment]
@pgaudet Is a table of affected annotations available?

**Comment by pgaudet** [comment]
Hi @deustp01 see this ticket - https://github.com/geneontology/go-annotation/issues/4578

There were no annotations to these terms. 

Thanks, Pascale
