### ISSUE TITLE
NTR:  surfactant secretion

### ISSUE THREAD

**Issue by aleixpuigb** [geneontology/go-ontology#25317]
Please provide as much information as you can: 

* **Suggested term label:**
`surfactant secretion`

* **Definition (free text)**
    The regulated release of surfactant by a cell or tissue.

* **Reference, in format PMID:#######**
[PMID:19824815](https://doi.org/10.1146/annurev.med.60.041807.123500)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
`secretion and ('has primary input' some 'surfactant')`

Consider the possibility for `surfactant homeostasis` as a parent term. Definition of `surfactant homeostasis`:
>Any process involved in the maintenance of a steady-state level of a surface-active agent that maintains the surface tension of a liquid.

**Comment by raymond91125** [comment]
Should this term be more specifically named as pulmonary surfactant secretion secretion and ('has primary input' some 'pulmonary surfactant')?

**Comment by aleixpuigb** [comment]
Thank you, @raymond91125. I need a generic 'surfactant secretion' for 'surfactant secreting cell'.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160069
+name: surfactant secretion
+namespace: biological_process
+def: "The regulated release of surfactant by a cell or tissue." [PMID:19824815]
+intersection_of: GO:0046903 ! secretion
+intersection_of: has_primary_input CHEBI:35195 ! surfactant
+relationship: part_of GO:0043129 ! surfactant homeostasis
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25317" xsd:anyURI
+created_by: rynl
+creation_date: 2023-05-15T15:43:34Z

**Comment by aleixpuigb** [comment]
Thank you @raymond91125!
