### ISSUE TITLE
Obsoletion request: GO:0008314 	gurken signaling pathway

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#25311]
Please provide as much information as you can:

GO:0008314 | gurken signaling pathway

[GO:0008314](https://www.ebi.ac.uk/QuickGO/term/GO:0008314) 	gurken signaling pathway

* **Reason for deprecation** Put an x in the appropriate box: 
 - [ ] The reason for obsoletion is that the term is not clearly defined and usage has been inconsistent.
 - [ ]  The reason for obsoletion is that this term is pre-composed and should be represented as a GO-CAM model.
 - [ ]  The reason for obsoletion is that this term represent an assay and not a GO process.
 - [ ]  The reason for obsoletion is that this represents a phenotype.
 - [ ] The reason for obsoletion is that the data from the paper for which the term was requested can be accurately described using [appropriate GO term].
 - [ ] The reason for obsoletion is that this term represents a molecular function.
 - [x]  The reason for obsoletion is that this term represents a gene product.
 - [ ] The reason for obsoletion is that this term refers to a class of proteins.
 - [ ]  The reason for obsoletion is that this term was added in error.
 - [ ]  The reason for obsoletion is that more specific terms were created.
 - [ ]  The reason for obsoletion is that this term was an unnecessary grouping term.
 - [ ]  The reason for obsoletion is that the meaning of the term is ambiguous.
 - [ ]  The reason for obsoletion is that is not known to be catalyzed by any gene product.
 - [ ]  The reason for obsoletion is that it more specific than the specificity of any known gene product.
 - [ ]  The reason for obsoletion is that there is no evidence that this function/process/component exists.

* **"Replace by" term (ID and label)**
GO:0007173	epidermal growth factor receptor signaling pathway

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP: 0

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

gurken is a fly EGFR ligand
Term never used.
GO:0007173	epidermal growth factor receptor signaling pathway is the BP term for the gurken gene product that should be used.
----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [x] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by pgaudet** [comment]
@hattrill Could we also obsolete     GO:0008317  gurken receptor binding ? This term is not used either. 
Thanks, Pascale

**Comment by hattrill** [comment]
Be my guest!
