### ISSUE TITLE
cholestenone 5-alpha-reductase activity GO:0047751

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25314]
cholestenone 5-alpha-reductase activity GO:0047751 has xref of EC:1.3.1.22, but that is for (at least nowadays) a more general reaction:

https://enzyme.expasy.org/EC/1.3.1.22
name: 3-oxo-5alpha-steroid 4-dehydrogenase (NADP(+))
alt_names: 3-oxo-5alpha-steroid 4-dehydrogenase, cholestenone 5alpha-reductase
reaction: a 3-oxo-5alpha-steroid + NADP(+) <=> a 3-oxo-Delta(4)-steroid + H(+) + NADPH

Should we remove the EC xref, or update the GO term and def to match EC? (I'd vote for the latter)

The current RHEA:24552 xref is accurate for 'cholestenone 5-alpha-reductase activity'.  If we make the GO term more general and match EC:1.3.1.22, then the RHEA xref should change to the more general [RHEA:54384](https://www.rhea-db.org/rhea/54384)

id: GO:0047751
name: cholestenone 5-alpha-reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: 5alpha-cholestan-3-one + NADP+ = cholest-4-en-3-one + H+ + NADPH." [EC:1.3.1.22, RHEA:24552]
synonym: "3-oxo-5alpha-steroid:NADP+ delta4-oxidoreductase activity" RELATED [EC:1.3.1.22]
synonym: "3-oxosteroid 5alpha-reductase activity" RELATED [EC:1.3.1.22]
synonym: "4-ene-3-oxosteroid 5alpha-reductase activity" RELATED [EC:1.3.1.22]
synonym: "4-ene-5alpha-reductase activity" RELATED [EC:1.3.1.22]
synonym: "cholest-4-en-3-one 5alpha-reductase activity" RELATED [EC:1.3.1.22]
synonym: "cholestenone 5a-reductase activity" EXACT []
synonym: "cholestenone 5alpha-reductase activity" RELATED [EC:1.3.1.22]
synonym: "delta4-3-ketosteroid 5alpha-oxidoreductase activity" RELATED [EC:1.3.1.22]
synonym: "reduced nicotinamide adenine dinucleotide phosphate:Delta4-3-ketosteroid 5alpha-oxidoreductase activity" RELATED [EC:1.3.1.22]
synonym: "steroid 5alpha-hydrogenase activity" RELATED [EC:1.3.1.22]
synonym: "testosterone delta4-5alpha-reductase activity" RELATED [EC:1.3.1.22]
synonym: "testosterone delta4-hydrogenase activity" RELATED [EC:1.3.1.22]
xref: EC:1.3.1.22
xref: KEGG_REACTION:R02610
xref: MetaCyc:CHOLESTENONE-5-ALPHA-REDUCTASE-RXN
xref: RHEA:24552
is_a: GO:0035671 ! enone reductase activity

**Comment by raymond91125** [comment]
id: GO:0047751
 name: cholestenone 5-alpha-reductase activity
 namespace: molecular_function
-def: "Catalysis of the reaction: 5alpha-cholestan-3-one + NADP+ = cholest-4-en-3-one + H+ + NADPH." [EC:1.3.1.22, RHEA:24552]
+def: "Catalysis of the reaction: 3-oxo-5alpha-steroid + NADP+ = a 3-oxo-Delta(4)-steroid + H(+) + NADPH" [EC:1.3.1.22, RHEA:54384]
+synonym: "3-oxo-5alpha-steroid 4-dehydrogenase (NADP(+))" RELATED []
 synonym: "3-oxo-5alpha-steroid:NADP+ delta4-oxidoreductase activity" RELATED [EC:1.3.1.22]
 synonym: "3-oxosteroid 5alpha-reductase activity" RELATED [EC:1.3.1.22]
 synonym: "3-oxosteroid delta4-dehydrogenase" BROAD [EC:1.3.1.22]
@@ -291900,8 +291901,9 @@ synonym: "testosterone delta4-hydrogenase activity" RELATED [EC:1.3.1.22]
 xref: EC:1.3.1.22
 xref: KEGG_REACTION:R02610
 xref: MetaCyc:CHOLESTENONE-5-ALPHA-REDUCTASE-RXN
-xref: RHEA:24552
+xref: RHEA:54384
 is_a: GO:0035671 ! enone reductase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25314" xsd:anyURI
 
 [Term]
 id: GO:0047753
@@ -307191,6 +307193,7 @@ xref: EC:1.3.1.30
 xref: MetaCyc:PROGESTERONE-5-ALPHA-REDUCTASE-RXN
 xref: RHEA:21952
 is_a: GO:0016628 ! oxidoreductase activity, acting on the CH-CH group of donors, NAD or NADP as acceptor
+is_a: GO:0047751 ! cholestenone 5-alpha-reductase activity

**Comment by sjm41** [comment]
Thanks @raymond91125 
Can you also change the GO:0047751 term name to match, i.e. change to "3-oxo-5alpha-steroid 4-dehydrogenase (NADP(+)) activity"

**Comment by pgaudet** [comment]
@raymond91125 
Related to this - EC:1.3.1.30 has been transferred to [1.3.1.22](https://enzyme.expasy.org/EC/1.3.1.22), see https://enzyme.expasy.org/EC/1.3.1.30

So GO:0050213 'progesterone 5-alpha-reductase activity' should be obsoleted and replaced by GO:0047751 (2 EXP by TAIR). In this case it seems like progesterone 5-alpha is one of the many substrates of the enzyme, hence out of scope for GO. 

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks @raymond91125 !
But why did you remove the RHEA:54384 xref?

[Term]
id: GO:0047751
name: 3-oxo-5alpha-steroid 4-dehydrogenase (NADP(+))
namespace: molecular_function
def: "Catalysis of the reaction: 3-oxo-5alpha-steroid + NADP+ = a 3-oxo-Delta(4)-steroid + H(+) + NADPH." [EC:1.3.1.22, RHEA:54384]
synonym: "3-oxo-5alpha-steroid:NADP+ delta4-oxidoreductase activity" RELATED [EC:1.3.1.22]
synonym: "3-oxosteroid 5alpha-reductase activity" RELATED [EC:1.3.1.22]
synonym: "3-oxosteroid delta4-dehydrogenase" BROAD [EC:1.3.1.22]
synonym: "4-ene-3-oxosteroid 5alpha-reductase activity" RELATED [EC:1.3.1.22]
synonym: "4-ene-5alpha-reductase activity" RELATED [EC:1.3.1.22]
synonym: "5alpha-reductase" BROAD [EC:1.3.1.22]
synonym: "cholest-4-en-3-one 5alpha-reductase activity" RELATED [EC:1.3.1.22]
synonym: "cholestenone 5-alpha-reductase activity" RELATED []
synonym: "cholestenone 5a-reductase activity" EXACT []
synonym: "cholestenone 5alpha-reductase activity" RELATED [EC:1.3.1.22]
synonym: "delta4-3-ketosteroid 5alpha-oxidoreductase activity" RELATED [EC:1.3.1.22]
synonym: "progesterone 5-alpha-reductase activity" NARROW []
synonym: "reduced nicotinamide adenine dinucleotide phosphate:Delta4-3-ketosteroid 5alpha-oxidoreductase activity" RELATED [EC:1.3.1.22]
synonym: "steroid 5alpha-hydrogenase activity" RELATED [EC:1.3.1.22]
synonym: "steroid 5alpha-reductase" BROAD [EC:1.3.1.22]
synonym: "testosterone 5alpha-reductase" BROAD [EC:1.3.1.22]
synonym: "testosterone delta4-5alpha-reductase activity" RELATED [EC:1.3.1.22]
synonym: "testosterone delta4-hydrogenase activity" RELATED [EC:1.3.1.22]
xref: EC:1.3.1.22
xref: KEGG_REACTION:R02610
xref: MetaCyc:CHOLESTENONE-5-ALPHA-REDUCTASE-RXN
is_a: GO:0035671 ! enone reductase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25314" xsd:anyURI

**Comment by raymond91125** [comment]
@sjm41 The RHEA ref is still in the definition. I deleted the extra RHEA because I had kept getting errors trying to commit the changes, complaining about RHEA not one-to-one.
@pgaudet Is there a preference for where the RHEA reference is, in definition or outside?

**Comment by sjm41** [comment]
Hmmm, I don't understand that error...  The match looks fine to me https://www.rhea-db.org/rhea/54384

We do need the RHEA to be an ref - I'm not sure if it should/should not be in the definition as well.

**Comment by raymond91125** [comment]
Added RHEA ref back.

**Comment by raymond91125** [comment]
@sjm41 Please reopen if you have more concerns. Thanks.

**Comment by pgaudet** [comment]
Hi @raymond91125 

I made a few edits WRT EC synonyms: they have done a massive purge in their synonyms and I removed with the synonym cross reference or the entire synonym - for example I dont think this type of nomenclature is used: 

> reduced nicotinamide adenine dinucleotide phosphate:Delta4-3-ketosteroid 5alpha-oxidoreductase activity

I also changed the scope of synonyms mentioning testosterone and cholestenone 5-alpha to NARROW and others that mention 'steroid' to BROAD. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@raymond91125 

We dont put parenthesis in the chemical  (ie we use H+, not H(+)), and we keep test small case (unless there are exceptions, but "Delta" should be "delta"

**Comment by pgaudet** [comment]
Sorry looks like this was fixed, I see it in the but it's OK in the ontology.
