### ISSUE TITLE
NTR: [regulation of adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway]

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#25329]
Please provide as much information as you can: 

* **Suggested term label:**
regulation of adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway
positive regulation of adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway
negative regulation of adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway

* **Definition (free text)**
Any process that modulates the frequency, rate or extent of the adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway
Any process that activates or increases the frequency, rate or extent of the adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway
Any process that stops, prevents or reduces the frequency, rate or extent of the adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway

* **Reference, in format PMID:#######**
28302905
8999903 

* **Gene product name and ID to be annotated to this term**
carA
rasD
acaA
and more 

* **Parent term(s)**
GO:0140582 adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
see above

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
discussion problems in GO-CAM it seems now we need regulatory terms as many relations can't be used.

**Comment by pgaudet** [comment]
@pfey03 

Shoudn't these genes be annotated to the pathways, not regulation ? at least carA and acaA (the receptor and the adenylate cyclase?) 

Also, it seems like rasG is downstream of the GPCR pathway - Fig 8 in PMID:28302905

<img width="469" alt="image" src="https://user-images.githubusercontent.com/4782928/237017501-55b7e7a4-a8b6-409c-9f6d-66af8938ed24.png">

so, it cannot be regulating the pathway (at least in this paper it's shown as regulating the PI3K signaling). 

What do you think?

**Comment by pfey03** [comment]
The problem is when we move to GO CAM. I have pathways there where a lot of processes and functions upstream regulate that pathway but this relation is not allowed

**Comment by pgaudet** [comment]
@pfey03 Can you please paste the link to the model you are trying to edit ?

**Comment by pgaudet** [comment]
ping @pfey03

**Comment by pfey03** [comment]
http://noctua.geneontology.org/editor/graph/gomodel:60d5209a00000328?barista_token=js0jrmbfcr15d3ntirql

**Comment by ukemi** [comment]
@pfey03, you shouldn't include the token part of the urls in your models.

**Comment by pfey03** [comment]
Thanks @ukemi 
http://noctua.geneontology.org/editor/graph/gomodel:59bee34700000000

**Comment by pgaudet** [comment]
Thanks @pfey03 
I still dont see in this model what you would annotate to 'regulation of adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway', it seems this represents the ' adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway'. 

Can you please specify?

**Comment by pgaudet** [comment]
@pfey03 Have you had a chance to look into this?

**Comment by pfey03** [comment]
I can't find the term anymore

**Comment by pfey03** [comment]
probably Bob has annotated these terms I cannot remember using this

**Comment by pgaudet** [comment]
OK thanks for checking
