### ISSUE TITLE
Updated definitions for three radial spoke terms

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#25321]
These three existing radial spoke terms need updates to their definitions and relationships. I worked in Protege 5.6.1, but don't have my authorization set up to commit to GitHub right now.

**old stanza**

> [Term]
> id: GO:0001534
> name: radial spoke
> namespace: cellular_component
> def: "Protein complex that links the outer microtubule doublet of the ciliary or flagellum axoneme with the sheath that surrounds the central pair of microtubules. Composed of a stalk that attaches to each doublet microtubule and a globular structure (spoke head) that projects toward the central pair of microtubules." [ISBN:0124325653, PMID:9450971]
> subset: goslim_pir
> xref: Wikipedia:Radial_spoke
> is_a: GO:0032991 ! protein-containing complex
> relationship: part_of GO:0005930 ! axoneme

**new stanza**

[Term]
id: GO:0001534
name: radial spoke
namespace: cellular_component
**def: "A protein structure involved in some types of beating motions of the cilium. The radial spoke is usually a T-shaped structure comprised of a short base that attaches to the A-microtubule of an axonemal outer microtubule doublet (MTD) of a cilium, an elongated stalk, a neck complex, and an orthogonal head structure that extends perpendicularly towards the inner sheath and the central pair (CP) microtubules. Groups of radial spokes (RSs) repeat along the MTD with regular spacing. In most organisms, each group of radial spokes is comprised of a triplet of spokes: RS1, RS2, and RS3. In some organisms (e.g. Chlamydomonas and Sarcophaga bullata), each group contains a doublet of radial spokes: RS1 and RS2, while RS3 is represented only as a stump (referred to as RS3S) attached to the A-microtubule but lacking the rest of the stalk structure and entirely lacking the head structure." [GOC:krc, ISBN:0124325653, PMID:22754630, PMID:25694453, PMID:34871179, PMID:9450971]**
subset: goslim_pir
xref: Wikipedia:Radial_spoke
is_a: GO:0032991 ! protein-containing complex
relationship: part_of GO:0005930 ! axoneme
**relationship: part_of GO:0097729 ! 9+2 motile cilium
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25321" xsd:string**

----

**old stanza**

> [Term]
> id: GO:0001535
> name: radial spoke head
> namespace: cellular_component
> def: "Protein complex forming part of eukaryotic flagellar apparatus." [GOC:cilia, GOC:hjd, GOC:krc] **=> This definition is not sufficiently specific.**
> synonym: "radial spokehead" EXACT []
> is_a: GO:0032991 ! protein-containing complex
> relationship: part_of GO:0001534 ! radial spoke
> relationship: part_of GO:0005930 ! axoneme 

**new stanza**

[Term]
id: GO:0001535
name: radial spoke head
namespace: cellular_component
**def: "The portion of the radial spoke that is orthogonal to the elongated stalk and which projects towards the central pair of microtubules within the ciliary axoneme." [GOC:cilia, GOC:hjd, GOC:krc, PMID:22754630, PMID:34871179]**
synonym: "radial spokehead" EXACT []
is_a: GO:0032991 ! protein-containing complex
relationship: part_of GO:0001534 ! radial spoke
relationship: part_of GO:0005930 ! axoneme
**relationship: part_of GO:0097729 ! 9+2 motile cilium**
**property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25321" xsd:string**

----

**old stanza**

> [Term]
> id: GO:0001536
> name: radial spoke stalk
> namespace: cellular_component
> def: "Globular portion of the radial spoke that projects towards the central pair of microtubules." [GOC:hjd] **=> This definition is wrong, looks like it was intended for GO:0001535**
> is_a: GO:0032991 ! protein-containing complex
> relationship: part_of GO:0001534 ! radial spoke
> relationship: part_of GO:0005930 ! axoneme 

**new stanza**

[Term]
id: GO:0001536
name: radial spoke stalk
namespace: cellular_component
**def: "The elongated portion of the radial spoke between the base which binds to the A microtubule and the neck which connects to the spoke head." [GOC:hjd, GOC:krc, PMID:22754630, PMID:34871179]**
is_a: GO:0032991 ! protein-containing complex
relationship: part_of GO:0001534 ! radial spoke
relationship: part_of GO:0005930 ! axoneme
**relationship: part_of GO:0097729 ! 9+2 motile cilium
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25321" xsd:string**

**Comment by raymond91125** [comment]
I think the generally guideline is for the definition to be in the form of genus+differentia that provides necessary and sufficient information for the term to be related but distinguished from other terms. The knowledge has progressed much and it makes good sense to add new references. But I don't see that the original definition is now incorrect, insufficient or overtly restrictive. Perhaps the new information could be added to Wikipedia. What do you think? @krchristie Thanks.

**Comment by krchristie** [comment]
> WRT GO:0001534 radial spoke, I think the generally guideline is for the definition to be in the form of genus+differentia that provides necessary and sufficient information for the term to be related to but distinguished from other terms. The knowledge has progressed much and it makes good sense to add new references. But I don't see that the original definition is now incorrect, insufficient or overtly restrictive. Perhaps the new information could be added to Wikipedia. What do you think? @krchristie Thanks.

While Chris likes to have the definitions in the form of genus+differentia, I often find definitions of that style relatively uninformative. In addition, I also thought that it was still allowed to have a descriptive portion in the definition, in addition to the genus+differential portion. 

Perhaps we could combine the two definitions to have a genus+differentia format and then include the more informative descriptive information. I would also update the original definition to say "A protein structure" rather than a "protein complex" as there are several protein complexes that are substructures of the radial spoke, so perhaps like this:

proposed def: "Protein structure that links the outer microtubule doublet of the ciliary or flagellum axoneme with the sheath that surrounds the central pair of microtubules. Composed of a stalk that attaches to each doublet microtubule and a globular structure (spoke head) that projects toward the central pair of microtubules. Radial spokes are involved in some types of beating motions of the cilium. The radial spoke is usually a T-shaped structure comprised of a short base that attaches to the A-microtubule of an axonemal outer microtubule doublet (MTD) of a cilium, an elongated stalk, a neck complex, and an orthogonal head structure that extends perpendicularly towards the inner sheath and the central pair (CP) microtubules. Groups of radial spokes (RSs) repeat along the MTD with regular spacing. In most organisms, each group of radial spokes is comprised of a triplet of spokes: RS1, RS2, and RS3. In some organisms (e.g. Chlamydomonas and Sarcophaga bullata), each group contains a doublet of radial spokes: RS1 and RS2, while RS3 is represented only as a stump (referred to as RS3S) attached to the A-microtubule but lacking the rest of the stalk structure and entirely lacking the head structure." [GOC:krc, ISBN:0124325653, PMID:22754630, PMID:25694453, PMID:34871179, PMID:9450971]

**Comment by pgaudet** [comment]
@krchristie Thanks for the feedback. 

Can we use 'protein complex' rather than 'Protein structure'? We don't define what is a protein structure in the ontology. Also, it may create confusion as to whether this is a complex or a cellular anatomical structure. 

Thanks, Pascale

**Comment by krchristie** [comment]
> @krchristie Thanks for the feedback.
> 
> Can we use 'protein complex' rather than 'Protein structure'? We don't define what is a protein structure in the ontology. Also, it may create confusion as to whether this is a complex or a cellular anatomical structure.
> 
> Thanks, Pascale

@pgaudet - 'protein complex' is fine as long as it's OK that the radial spoke is composed of numerous individual protein complexes.

**Comment by pgaudet** [comment]
@krchristie Is the radial spoke considered a non-membrane bound organelle or a protein complex? We need to be consistent with the parent.

**Comment by raymond91125** [comment]
PMID:22118931 It appears that radial spoke is part of 9+2 cilium (motile and non-motile) and not 9+0.

**Comment by krchristie** [comment]
> @krchristie Is the radial spoke considered a non-membrane bound organelle or a protein complex? We need to be consistent with the parent.

The radial spoke by itself is not an organelle of any kind, so I guess it's a protein complex.

**Comment by krchristie** [comment]
> PMID:22118931 It appears that radial spoke is part of 9+2 cilium (motile and non-motile) and not 9+0.

Yes, that is correct. I bolded the fact that I added that in my stanzas, but it looks like I forgot to specifically mention that I thought that part_of relationship should be added.

**Comment by raymond91125** [comment]
> > PMID:22118931 It appears that radial spoke is part of 9+2 cilium (motile and non-motile) and not 9+0.
> 
> Yes, that is correct. I bolded the fact that I added that in my stanzas, but it looks like I forgot to specifically mention that I thought that part_of relationship should be added.
Since radial spoke can be a part of both motile and non-motile 9+2 cilium, I added the has_part relationships (on the cilium terms), not part of.
