### ISSUE TITLE
NTR: cilium radial spoke terms

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#25320]
Hi,

I need numerous new terms for ciliary radial spoke components. I put these stanzas into Protege to make sure I had the relationships correct and saved back out. I used my number range so it won't conflict with what anyone else is doing.

Whoever puts these stanzas in could add them directly to the file. I've updated my Protege but don't currently have my authentication set up properly to commit to the Git repository. While, I've saved these out of Protege 5.6.1, it's probably still a good idea to save back out of Protege to make sure all the formatting is correct for the new version.

Thanks,

-Karen

[Term]
id: GO:0120333
name: radial spoke 1
namespace: cellular_component
def: "The radial spoke of each group of radial spokes, whether grouped as triplets or doublets, that is most proximal to the base of the cilium. Radial spoke 1 (RS1), similarly to radial spoke 2, is comprised of four domains: 1) a very short base anchored to the A microtubule, 2) an elongaged stalk, 3) a bifurcated neck, and 4) an orthogonal head. The base of RS1 is connected to the tail of the inner dynein arm a/d." [GOC:krc, PMID:22754630]
synonym: "RS1" RELATED [PMID:22754630]
is_a: GO:0001534 ! radial spoke
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25320" xsd:anyURI
created_by: krc
creation_date: 2023-04-26T22:13:01Z

[Term]
id: GO:0120334
name: radial spoke 2
namespace: cellular_component
def: "The radial spoke of each group of radial spokes, whether grouped as triplets or doublets, that is immediately distal to radial spoke 1 (RS1). Radial spoke 2 (RS2), similarly to RS1, is comprised of four domains: 1) a very short base anchored to the A microtubule, 2) an elongaged stalk, 3) a bifurcated neck, and 4) an orthogonal head. The base of RS2 is connected to the tail of the inner dynein arm c." [GOC:krc, PMID:22754630]
synonym: "RS1" RELATED [PMID:22754630]
is_a: GO:0001534 ! radial spoke
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25320" xsd:anyURI
created_by: krc
creation_date: 2023-04-26T22:14:02Z

[Term]
id: GO:0120335
name: radial spoke 3
namespace: cellular_component
def: "Radial spoke 3 (RS3), when present, is the most distal of each group of radial spokes, whether grouped as triplets or doublets. RS3 has significantly different morphology and protein composition than RS1 and RS2 and also extends at a slant from the microtubule doublet, rather than perpendicularly like RS1 and RS2. In some organisms (e.g. Chlamydomonas and Sarcophaga bullata), RS3 is represented only as a stump attached to the A-microtubule lacking the rest of the stalk structure and entirely lacking the head structure." [GOC:krc, ISBN:0124325653, PMID:22754630, PMID:25694453, PMID:9450971]
synonym: "RS1" RELATED [PMID:22754630]
is_a: GO:0001534 ! radial spoke
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25320" xsd:anyURI
created_by: krc
creation_date: 2023-04-26T22:15:03Z

[Term]
id: GO:0120336
name: radial spoke head 1
namespace: cellular_component
def: "The portion of the radial spoke 1 that is orthogonal to the elongated stalk and which projects towards the central pair of microtubules within the ciliary axoneme." [GOC:krc, PMID:22754630, PMID:348711799]
synonym: "radial spokehead 1" EXACT []
intersection_of: GO:0001535 ! radial spoke head
intersection_of: part_of GO:0120333 ! radial spoke 1
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25320" xsd:anyURI
created_by: krc
creation_date: 2023-04-26T22:16:04Z

[Term]
id: GO:0120337
name: radial spoke head 2
namespace: cellular_component
def: "The portion of the radial spoke 1 that is orthogonal to the elongated stalk and which projects towards the central pair of microtubules within the ciliary axoneme." [GOC:krc, PMID:22754630, PMID:348711799]
synonym: "radial spokehead 2" EXACT []
intersection_of: GO:0001535 ! radial spoke head
intersection_of: part_of GO:0120334 ! radial spoke 2
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25320" xsd:anyURI
created_by: krc
creation_date: 2023-04-26T22:17:05Z

[Term]
id: GO:0120338
name: radial spoke head 3
namespace: cellular_component
def: "The portion of the radial spoke 3 that is orthogonal to the elongated stalk and which projects towards the central pair of microtubules within the ciliary axoneme." [GOC:krc, PMID:22754630, PMID:348711799]
synonym: "radial spokehead 3" EXACT []
intersection_of: GO:0001535 ! radial spoke head
intersection_of: part_of GO:0120335 ! radial spoke 3
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25320" xsd:anyURI
created_by: krc
creation_date: 2023-04-26T22:18:06Z

[Term]
id: GO:0120339
name: radial spoke base
namespace: cellular_component
def: "The short portion of the radial spoke that is directly anchored to the A microtubule of an axonemal microtubule doublet" [GOC:krc, PMID:22754630, PMID:25694453]
is_a: GO:0032991 ! protein-containing complex
relationship: part_of GO:0001534 ! radial spoke
relationship: part_of GO:0005930 ! axoneme
relationship: part_of GO:0097729 ! 9+2 motile cilium
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25320" xsd:anyURI
created_by: krc
creation_date: 2023-04-26T22:19:07Z

[Term]
id: GO:0120340
name: radial spoke base 1
namespace: cellular_component
def: "The short portion of the radial spoke 1 (RS1) that is directly anchored to the A microtubule of an axonemal microtubule doublet" [GOC:krc, PMID:22754630, PMID:25694453]
intersection_of: GO:0120339 ! radial spoke base
intersection_of: part_of GO:0120333 ! radial spoke 1
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25320" xsd:anyURI
created_by: krc
creation_date: 2023-04-26T22:20:08Z

[Term]
id: GO:0120341
name: radial spoke base 2
namespace: cellular_component
def: "The short portion of the radial spoke 2 (RS2) that is directly anchored to the A microtubule of an axonemal microtubule doublet" [GOC:krc, PMID:22754630, PMID:25694453]
intersection_of: GO:0120339 ! radial spoke base
intersection_of: part_of GO:0120334 ! radial spoke 2
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25320" xsd:anyURI
created_by: krc
creation_date: 2023-04-26T22:21:09Z

[Term]
id: GO:0120342
name: radial spoke base 3
namespace: cellular_component
def: "The short portion of the radial spoke 3 (RS3 )that is directly anchored to the A microtubule of an axonemal microtubule doublet" [GOC:krc, PMID:22754630, PMID:25694453]
intersection_of: GO:0120339 ! radial spoke base
intersection_of: part_of GO:0120335 ! radial spoke 3
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25320" xsd:anyURI
created_by: krc
creation_date: 2023-04-26T22:22:10Z

[Term]
id: GO:0120343
name: radial spoke neck
namespace: cellular_component
def: "The radial spoke neck is a complex that connects the spoke stalk to the head." [GOC:krc, PMID:22754630]
is_a: GO:0032991 ! protein-containing complex
relationship: part_of GO:0001534 ! radial spoke
relationship: part_of GO:0005930 ! axoneme
relationship: part_of GO:0097729 ! 9+2 motile cilium
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25320" xsd:anyURI
created_by: krc
creation_date: 2023-04-26T22:23:11Z

**Comment by raymond91125** [comment]
@krchristie Your edits failed CI checks. Also as we discussed for https://github.com/geneontology/go-ontology/issues/25321, some of the relationships should be has_part, not part_of. Thanks.

**Comment by krchristie** [comment]
> @krchristie Your edits failed CI checks. Also as we discussed for #25321, some of the relationships should be has_part, not part_of. Thanks.

@raymond91125 - It might be sufficient to just do the '9+2 motile cilium has_part ____' relationships. Since kinocilia aren't motile, they aren't a subject for studying cilium motility and they could lose some parts of the radial spokes without consequence as they already aren't motile.

Let me know if you want any additional input from me to fix the relationships.
