### ISSUE TITLE
Build failing on checks relating to obsolete classes (GO:0004513  GO:0047287)

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#25338]
All pipeline builds are now failing on:
```
11:16:39  FAIL Rule ../sparql/obsolete-reference-violation.sparql: 2 violation(s)
11:16:39  obsolete
11:16:39  http://purl.obolibrary.org/obo/GO_0004513
11:16:39  http://purl.obolibrary.org/obo/GO_0047287
```
Tagging @pgaudet @balhoff

**Comment by balhoff** [comment]
Temporary fix: https://github.com/geneontology/go-ontology/pull/25337

**Comment by pgaudet** [comment]
What would be a permanent fix?

**Comment by kltm** [comment]
@pgaudet , @balhoff refers to: https://github.com/geneontology/go-ontology/issues/25339

**Comment by balhoff** [comment]
I think we can close this since we have #25339.
