### ISSUE TITLE
Some EC xrefs getting dropped from go-basic.obo?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25336]
Hi @balhoff - I think this might be in your domain? But please reassign if not.

I just noticed that some EC xrefs present on GO-MF terms in the go-edit.obo file seem to get dropped from the go-basic.obo file (which is the file that FlyBase consumes).  The two examples I've come across are given below - showing the current go-edit version first, followed by the go-basic version (releases/2023-04-01, with the Reactome xrefs removed for clarity).

In both examples, there are two EC xrefs on the term, so maybe that's the issue?  Or maybe it's because of the {source="skos:narrowMatch"} tag?  Would dropping the EC xrefs in either case be intended?  Any other insights?

id: GO:0016920
name: pyroglutamyl-peptidase activity
namespace: molecular_function
def: "Catalysis of the release of the N-terminal pyroglutamyl group from a peptide or protein." [GOC:mah, PMID:9920379]
xref: EC:3.4.19.3 {source="skos:narrowMatch"}
xref: EC:3.4.19.6 {source="skos:narrowMatch"}
is_a: GO:0008234 ! cysteine-type peptidase activity
is_a: GO:0008242 ! omega peptidase activity
>
id: GO:0016920
name: pyroglutamyl-peptidase activity
namespace: molecular_function
def: "Catalysis of the release of the N-terminal pyroglutamyl group from a peptide or protein." [GOC:mah, PMID:9920379]
is_a: GO:0008234 ! cysteine-type peptidase activity
is_a: GO:0008242 ! omega peptidase activity

id: GO:0004674
name: protein serine/threonine kinase activity
namespace: molecular_function
alt_id: GO:0004695
alt_id: GO:0004696
alt_id: GO:0004700
alt_id: GO:0106311
def: "Catalysis of the reactions: ATP + protein serine = ADP + protein serine phosphate, and ATP + protein threonine = ADP + protein threonine phosphate." [GOC:bf, PMID:2956925]
synonym: "protein kinase (phosphorylating) activity" NARROW [EC:2.7.11.1]
synonym: "protein phosphokinase activity" NARROW [EC:2.7.11.1]
synonym: "protein serine kinase activity" NARROW [EC:2.7.11.1]
synonym: "protein serine-threonine kinase activity" RELATED [EC:2.7.11.1]
synonym: "protein threonine kinase activity" NARROW []
synonym: "protein-serine kinase activity" NARROW [EC:2.7.11.1]
synonym: "serine kinase activity" NARROW [EC:2.7.11.1]
synonym: "serine protein kinase activity" NARROW [EC:2.7.11.1]
synonym: "serine(threonine) protein kinase activity" RELATED [EC:2.7.11.1]
synonym: "serine-specific protein kinase activity" NARROW [EC:2.7.11.1]
synonym: "serine/threonine protein kinase activity" RELATED [EC:2.7.11.1]
synonym: "threonine-specific protein kinase activity" NARROW [EC:2.7.11.1]
xref: EC:2.7.11.1 {source="skos:narrowMatch"}
xref: EC:2.7.11.1
is_a: GO:0004672 ! protein kinase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/20114" xsd:anyURI
>
id: GO:0004674
name: protein serine/threonine kinase activity
namespace: molecular_function
alt_id: GO:0004695
alt_id: GO:0004696
alt_id: GO:0004700
alt_id: GO:0106311
def: "Catalysis of the reactions: ATP + protein serine = ADP + protein serine phosphate, and ATP + protein threonine = ADP + protein threonine phosphate." [GOC:bf, PMID:2956925]
synonym: "protein kinase (phosphorylating) activity" NARROW [EC:2.7.11.1]
synonym: "protein phosphokinase activity" NARROW [EC:2.7.11.1]
synonym: "protein serine kinase activity" NARROW [EC:2.7.11.1]
synonym: "protein serine-threonine kinase activity" RELATED [EC:2.7.11.1]
synonym: "protein threonine kinase activity" NARROW []
synonym: "protein-serine kinase activity" NARROW [EC:2.7.11.1]
synonym: "serine kinase activity" NARROW [EC:2.7.11.1]
synonym: "serine protein kinase activity" NARROW [EC:2.7.11.1]
synonym: "serine(threonine) protein kinase activity" RELATED [EC:2.7.11.1]
synonym: "serine-specific protein kinase activity" NARROW [EC:2.7.11.1]
synonym: "serine/threonine protein kinase activity" RELATED [EC:2.7.11.1]
synonym: "threonine-specific protein kinase activity" NARROW [EC:2.7.11.1]
is_a: GO:0004672 ! protein kinase activity

tagging @hattrill

**Comment by balhoff** [comment]
@sjm41 yes the narrow xrefs are purposely filtered out of `go.obo` and `go-basic.obo`:
- https://github.com/geneontology/go-ontology/blob/ef12560160c7fb39d72a73816d177dffb1ccbaf5/src/ontology/Makefile#L258

But they are included in the mappings files:
- https://github.com/geneontology/go-ontology/blob/ef12560160c7fb39d72a73816d177dffb1ccbaf5/src/ontology/Makefile#L563-L567

I had to search back through issues to find the reasoning here; I think you supported this approach previously 😅: https://github.com/geneontology/go-ontology/issues/20770#issuecomment-770626191

**Comment by balhoff** [comment]
It would be great to hear your comments on how to reduce confusion with regard to xrefs and mappings. I know that @cmungall would like to revamp how these are published. I also don't know how critical it is for downstream consumers for us to be stripping "trailing qualifiers" from the OBO format files; perhaps some groups have parsers that can't handle those.

**Comment by sjm41** [comment]
Ah yes, thanks for digging out that other ticket and reminding me - I'd forgotten that we needed to maintain EC xrefs on merged terms (for EC2GO pipeline reasons), marking them as narrowMatch and then excluding them from go-basic.obo.  That still makes sense, and I'm not suggesting we change that.  I'll close this ticket.

The current system works well for FlyBase, and we haven't heard from any other groups that the current system is causing them problems AFAIK.  I'm sure FlyBase devs could code around it If the "trailing qualifiers" were included in go-basic, but I suspect it would cause issues for others who wouldn't be so aware.
