### ISSUE TITLE
NTR: [lipoate transmembrane transporter activity] and [lipoate transmembrane transport]t

### ISSUE THREAD

**Issue by LucillePo** [geneontology/go-ontology#25332]
Hello,
I would like to request the following terms

* **Suggested term label:**
F: lipoate transmembrane transporter activity 
* **Definition (free text)**
Enables the transfer   of lipoate from one side of a membrane to the other.
* **Reference**
PMID:20980265
PMID:25971966
* **Gene product name and ID to be annotated to this term**
Q9Y289

* **Suggested term label:**
P: lipoate transmembrane transport
* **Definition (free text)**
The process in which lipoate is transported across a membrane.
* **Reference**
PMID:20980265
PMID:25971966
* **Gene product name and ID to be annotated to this term**
Q9Y289

**Comment by pgaudet** [comment]
Hi @LucillePo 

Could the process be 'lipoate import into cell' ? Does that represent the data you want to capture? 

Thanks, Pascale

**Comment by LucillePo** [comment]
Hello Pascale,
I think there is not enough evidence to say that the transporter is unidirectional so I would just talk about "transmembrane transport"
Thanks
Lucille
