### ISSUE TITLE
Missing parents for histone kinase terms?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25331]
Just looking at the children of GO:0140996 histone H3 kinase activity (as an example), the child terms are specific for serine/threonine or tyrosine residues, but those child terms don't have parentage to the respective 'protein serine/threonine kinase activity' (GO:0004674) or 'protein tyrosine kinase activity (GO:0004713) terms.
Can the extra parent be added to each child term, or is this omission an intentional part of the recent refactoring?

![Screenshot 2023-05-02 at 12 55 35](https://user-images.githubusercontent.com/16306861/235659384-6c14f9da-2a48-494b-86b7-e4954ea6fec5.png)

![Screenshot 2023-05-02 at 12 57 41](https://user-images.githubusercontent.com/16306861/235659881-b5976d62-ab6b-4992-9baf-7c9065e859df.png)

**Comment by pgaudet** [comment]
thanks for the feedback!
