### ISSUE TITLE
Obsoletion request: [GO:0016580 Sin3 complex]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25357]
Please provide as much information as you can:

It is not clear which SIN3 complex this term refers to. In this respect, and based on the definition it should probably be obsolete and replace by
GO:0070822   Sin3-type complex

GO:0016580  Sin3 complex
Definition ([GO:0016580 GONUTS page](http://gowiki.tamu.edu/wiki/index.php/Category:GO:0016580))
A multiprotein complex that functions broadly in eukaryotic organisms as a transcriptional repressor of protein-coding genes, through the gene-specific deacetylation of histones. Amongst its subunits, the Sin3 complex contains Sin3-like proteins, and a number of core proteins that are shared with the NuRD complex (including histone deacetylases and histone binding proteins). The Sin3 complex does not directly bind DNA itself, but is targeted to specific genes through protein-protein interactions with DNA-binding proteins. PMID:10589671 PMID:11743021 PMID:12865422

* **Reason for deprecation** Put an x in the appropriate box: 
 - [x] The reason for obsoletion is that the term is not clearly defined and usage has been inconsistent.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

GO:0070822 Sin3-type complex

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

There are only 17 EXP annotations:
 

+ | − | (7) | TAIR
+ | − | (6) | UniProt
+ | − | (4) | BHF-UCL
+ | − | (1) | MGI

which is odd for
"functions broadly in eukaryotic organisms as a transcriptional repressor of protein-coding genes"
Curators may want to see if the specific HDAc can b e specified prior to obsolete and replace

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [ ] check taxon constraints 

***Check annotations***

Direct replacement, no annotation review spreadsheet necessary

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
@colinlog  do you agree with this? or is SIN3 complex referring to a specific complex (this is not clear from te definitions, and  is it likely it refers to one of: ?
https://github.com/geneontology/go-ontology/issues/25356

**Comment by colinlog** [comment]
SIN3 complex is most likely the RPD3L complex. Hence I agree with you Val that we do not need it (unless it really is a different complex from the RPD3S and RPD3L complexes, who have distinct functionality.

**Comment by pgaudet** [comment]
- [ ] fixed label of sibling: GO:0032221
-name: Rpd3S
+name: Rpd3S complex

**Comment by lreiser** [comment]
updated TAIR annotations

**Comment by colinlog** [comment]
Yes Val. Rpd3 amd Sin3 complexes are synonyms.
