### ISSUE TITLE
don't load Reactome xrefs into editor file imports

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#25352]
These make it hard to see the xrefs that are edited within the ontology. For the time being (prior to a larger project reviewing mappings workflow) we should merge this file in later during the ontology build.

**Comment by kltm** [comment]
@pgaudet @balhoff From the discussion earlier today, was the discussed action just for Reactome, or was it to be all mappings loaded in later on (so as not to bug the editors)?

**Comment by pgaudet** [comment]
@kltm Reactome is the only mapping present in the ontology editors file that is not managed there. All others are OK. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Thanks !!
