### ISSUE TITLE
Obsoletion notice: GO:0052812 phosphatidylinositol-3,4-bisphosphate 5-kinase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25355]
Dear all, 

The proposal has been made to obsolete 'GO:0052812 phosphatidylinositol-3,4-bisphosphate 5-kinase activity'. The reason for obsoletion is that there is no evidence that this activity exists. 

There are no more manual annotations to this term (1 incorrect EXP removed in https://github.com/geneontology/go-annotation/issues/4569); this term was incorrectly mapped to EC:2.7.1.153, which actually corresponds to GO:0046934 'phosphatidylinositol-4,5-bisphosphate 3-kinase activity'. This term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25355

Thanks, Pascale

**Comment by pgaudet** [comment]
Actually there is one Reactome reaction - https://reactome.org/content/detail/R-HSA-1675773
Need to check references

**Comment by pgaudet** [comment]
This Reactome reaction may correspond to a difference substrate of https://enzyme.expasy.org/EC/2.7.1.68

@sjm41 @deustp01 any thoughts on this?

**Comment by deustp01** [comment]
> This Reactome reaction may correspond to a difference substrate of https://enzyme.expasy.org/EC/2.7.1.68

Yes, that is how I read this part of the entry for 2.7.1.68 -

> Comment(s)
> --
> This enzyme can also phosphorylate PtdIns3P in the 4-position,     and PtdIns, PtdIns3P and PtdIns(3,4)P2 in the 5-position in vitro, but to a lesser extent. The last of these reactions occurs in vivo and is physiologically relevant.

The "last of these reactions" looks like the one that Mark Williams annotated for Reactome  https://reactome.org/content/detail/R-HSA-1675773. You'll see that, in agreement with the EC entry, Mark was not sure about the physiological role of this reaction.

@sjm41 @pgaudet  So practically, what do we do? Keep the current GO term? Keep the current Reactome reaction and its enzyme but use a different GO term? Either fix seems OK to me and there may be others I'm overlooking.

Thanks

**Comment by sjm41** [comment]
So [2.7.1.68](https://enzyme.expasy.org/EC/2.7.1.68) corresponds to GO:0016308 "1-phosphatidylinositol-4-phosphate 5-kinase activity", but the GO def (and the RHEA:14425 ref) are specific to the main reaction (1-phosphatidyl-1D-myo-inositol 4-phosphate -> 1-phosphatidyl-1D-myo-inositol 4,5-bisphosphate).

I don't see a specific entry for the "1-phosphatidyl-1D-myo-inositol 3,4-bisphosphate -> 1-phosphatidyl-1D-myo-inositol 3,4,5-trisphosphate" reaction in either EC or RHEA. Given this, and the fact the Reactome entry says "This is a minor reaction, however, and its physiological role is uncertain.", I'd suggest we go ahead with the obsoletion and Reactome reannotate with the parent term "GO:0052742 phosphatidylinositol kinase activity".

**Comment by deustp01** [comment]
> I'd suggest we go ahead with the obsoletion and Reactome reannotate with the parent term "GO:0052742 phosphatidylinositol kinase activity".

Re-annotation will be done today and will become publicly visible with our June release.
