### ISSUE TITLE
NTR: [Glycine receptor activity]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#25370]
Hi GO,

I would need a new GO term for an atypical member of the G-protein coupled receptor 3 family. GPR158 corresponds to the long sought metabotropic glycine receptor. It doesn't act as a G-protein coupled receptor, since it recruits and regulates the RGS7-GNB5 complex instead of activating G proteins. The term is therefore not linked to GO:0004930; F:G protein-coupled receptor activity.

Thanks

Sylvain

Term: Glycine receptor activity
Category: Molecular function
Definition: Combining with glycine and transmitting the signal from one side of the membrane to the other to initiate a change in cell activity.
child of GO:0004888 transmembrane signaling receptor activity
child of GO:0030594 neurotransmitter receptor activity
PMID:36996198

**Comment by raymond91125** [comment]
This reference is about a metabotropic glycine receptor, different from the classic ionotropic ones, PMID:15383648. There is no MF term for either. Do we want to add both at this time, in a way similar to GABA and glutamate receptor activity? Perhaps naming them ionotropic and metabotropic or something else?

**Comment by sylvainpoux** [comment]
Hi @raymond91125 
I'm fine with the "Metabotropic glycine receptor" name (it corresponds to the Recommended Name in UniProt).
Thanks
Sylvain

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160079
+name: metabotropic glycine receptor activity
+namespace: molecular_function
+def: "Combining with glycine and transmitting the signal across the membrane by changing the activity of intracellular G protein signalling." [PMID:36996198]
+synonym: "mGlyR" EXACT []
+is_a: GO:0004888 ! transmembrane signaling receptor activity
+is_a: GO:0030594 ! neurotransmitter receptor activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25370" xsd:anyURI
+created_by: rynl
+creation_date: 2023-05-16T17:21:47Z

**Comment by pgaudet** [comment]
Missing parent 'G protein-coupled receptor activity'

Also, for consistency, the term label should be 'G protein-coupled glycine receptor activity'
