### ISSUE TITLE
Obsoletion request: redundant descendants of [GO ID:GO:0032187 actomyosin contractile ring localization] 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25379]
Please provide as much information as you can:
Follow on from
https://github.com/geneontology/go-ontology/issues/21834

- [x]  GO:0032188  establishment of actomyosin contractile ring localization
Replace by -> GO:0007105 cytokinesis, division site positioning

- [x] GO:1903486  establishment of mitotic actomyosin contractile ring localization
Replace by -> GO:1902408    mitotic cytokinesis, division site positioning

- [x] GO:1901648  regulation of actomyosin contractile ring localization
Replace by  -> GO:2000073    regulation of cytokinesis, site selection

- [x] GO:1903505  regulation of establishment of actomyosin contractile ring localization involved in mitotic cell cycle
Replace by  ->  GO:1902472    regulation of mitotic cytokinesis, division site positioning

- [x] GO:1902471    regulation of mitotic actomyosin contractile ring localization
Replace by  -> GO:1902472    regulation of mitotic cytokinesis, division site positioning

- [x] GO:1901649    negative regulation of actomyosin contractile ring localization
Replace by  -> GO:2000075    negative regulation of cytokinesis, site selection

- [x] GO:1901650    positive regulation of actomyosin contractile ring localization
Replace by  ->  GO:2000076    positive regulation of cytokinesis, site selection

- [x]  GO:0071342    regulation of establishment of actomyosin contractile ring localization
Replace by  -> GO:2000073    regulation of cytokinesis, site selection

- [x] GO:1902405  	mitotic actomyosin contractile ring localization
Replace by -> GO:1902408    mitotic cytokinesis, division site positioning

Branch has only 10 EXP annotations
6 PomBase
1 CGD
3 FlyBase

* **GO term ID and Label**

* **Reason for deprecation** Put an x in the appropriate box: 
 - [ ] The reason for obsoletion is that the term is not clearly defined and usage has been inconsistent.
 Also there is an additional branch with terms with he same meaning 

* **"Replace by" term (ID and label)**

See above for replaced by

* **Are there annotations to this term?**
- How many EXP: 10

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
Direct replacement, no annotation review required

- [x] find external mappings (via IEAS), include in obsoletion notice  

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
@pgaudet  since this is a merge do I  don't need an annotation tracker ticket, correct? Just an obsoletion notice?

**Comment by ValWood** [comment]
I will go ahead with this today since there will be automatic replacement.

**Comment by ValWood** [comment]
Check graph
still need to deal with
GO:0032187 | actomyosin contractile ring localization
(this one has a taxon restriction)

**Comment by ValWood** [comment]
So, this list will be OK?
6 PomBase
1 CGD
3 FlyBase

Which groups don't use Noctua or P2GO apart from PomBase and PHI-base, 
Eco-Cyc?

**Comment by pgaudet** [comment]
EcoCyc
EcoWiki
TAIR 
CGD
ComplexPortal/IntAct
InterPro
Reactome
SP keywords
RNA central
SynGO
GeneDB
HPA
PseudoCAP
DisProt
SGN


I think that's about it

**Comment by ValWood** [comment]
Dear @marekskrzypek @jlewsmith

There is a single CGD annotation to 
IQG1 |   |   | actomyosin contractile ring localization |   | CGD | Candida albicans SC5314 | IMP

The branch  GO:0007105   cytokinesis, division site positioning
was duplicated with equivalent terms.

This term will be obsoleted with the replacement term:
GO:0007105   cytokinesis, division site positioning

We can no longer merge terms which are equivalent, they need to be obsoleted.

If the term was used to describe an evolved process you can just migrate the annotation to the remaining term.
Or, if the paper is describing detachment and migration of the ring after it is formed at a particular localization, this represents an aberrant mutant phenotype and not an evolved process.

**Comment by hattrill** [comment]
Hi @ValWood ,
Sorry, thought there was going to be a merge. Will review them now.

**Comment by ValWood** [comment]
Oh actually, it's OK, if. you use protein2GO they will be migrated to the new term. It isn't a merge but it's equivalent to a merge.

**Comment by hattrill** [comment]
Cool. Actually, good for me to look at them as one needed to be removed. All done now.

One thing I noticed was that we have a term for mitosis:
mitotic cytokinesis, division site positioning
but not the equivalent for the meiotic branch 

might be a deliberate ommission or something that isn't needed cos of GO-CAMs...but thought that I'd mention it.

**Comment by jlewsmith** [comment]
Hi Val,

I'll take a look at the paper and make the appropriate change.

Thanks,
Jodi


Jodi Lew-Smith Ph.D.
Senior Biocuration Scientist  |  Candida Genome Database
Department of Genetics
Stanford University School of Medicine
Stanford, CA 94305
***@***.***
________________________________

**Comment by ValWood** [comment]
> One thing I noticed was that we have a term for mitosis:
mitotic cytokinesis, division site positioning
but not the equivalent for the meiotic branch

The reason for this is that most of the work on cytokinesis has been done in yeast. In yeast the process of "cytokinesis" is very different,  (because basically the cell forms spores  around the segregated DNA, rather than an actomyosin contractile ring and a septum).  All of the yeast annotations are for mitotic cytokinesis.
There are only 160  EXP annotations to meiotic cytokinesis, so I suspect it's just that the terms have not been required yet due to depth of study.

**Comment by ValWood** [comment]
Will open another ticket for the remaining 3 terms that appear to be redundant.

**Comment by ValWood** [comment]
Follow up is in
https://github.com/geneontology/go-ontology/issues/25606
