### ISSUE TITLE
cellular senescence def update

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25380]
currently defined
A cell aging process stimulated in response to cellular stress, whereby normal cells lose the ability to divide through irreversible cell cycle arrest. PMID:28682291

I would like to add a taxon restriction
https://github.com/geneontology/go-ontology/issues/25261
 "never n fungi" but the current def does not restrict 
GO:0090399   replicative senescence 

Consider:
Cellular Senescence: Cellular senescence is an **irreversible** process in which individual cells within a multicellular organism lose their ability to divide and function properly. It is a mechanism that limits the proliferative potential of cells and helps prevent the development of cancer.

 Also add multicellular parentage GO:0032501   
multicellular organismal process

**Comment by ValWood** [comment]
It's a different process, there is a process called replicative senescence but it isn't the same thing
GO:0090399 replicative senescence
and also   GO:0044838  
cell quiescence which  is a specialized resting state in response to starvation.

They don't really do "senescence" which is a specialized process in eukaryotes as an anti-cancer mechanism.  If this happened in yeast the cell cycle would block and eventually the cells would lose viability

In multicellular organisms this is a programmed mechanism to prevent proliferation.

**Comment by ValWood** [comment]
Personally I don't think there is convincing evidence yet  that senescence is programmed. Interesting this is what GPC chat synergyses:

Senescence, referring to the biological process of aging and deterioration in living organisms, is not typically considered a programmed event in the strict sense. While there are genetic and cellular factors that contribute to senescence, it is primarily understood as a complex and multifactorial process influenced by a combination of genetic, environmental, and stochastic (random) factors.

The prevailing scientific consensus is that aging and senescence result from a combination of accumulated damage to cells and tissues over time, as well as the progressive decline in the body's ability to repair and maintain itself. This view is supported by a variety of scientific studies and observations, including the effects of genetic and environmental interventions on lifespan and healthspan.

However, it is important to note that there is ongoing research in the field of aging biology, and our understanding of senescence continues to evolve. There are theories, such as the programmed theories of aging, that propose specific genetic programs or mechanisms that contribute to the aging process. These theories suggest that aging may have evolved as an adaptive trait that benefits the population as a whole, even if it may be detrimental to individual organisms.

Overall, while there are programmed aspects to the aging process, the prevailing view in the scientific community is that senescence is a complex and multifaceted phenomenon resulting from a combination of genetic, environmental, and stochastic factors.

But cellular senescence isn't present in fungi. Cells which undergo arrest (i.e can't navigate a checkpoint) will die eventually (and the whole point of senescene is that it is **irreversable** - that should be added to the definition.

**Comment by addiehl** [comment]
There is some evidence that T cell senescence is an active process that is actually reversible:
[Reversible-Senescence-in-Human-CD4-CD45RA-CD27](https://journals.aai.org/jimmunol/article/187/5/2093/86088/Reversible-Senescence-in-Human-CD4-CD45RA-CD27)
[Senescence of T Lymphocytes: Implications for Enhancing Human Immunity](https://pubmed.ncbi.nlm.nih.gov/27720177/)

**Comment by ValWood** [comment]
In that case  the authors changed the definition of senescence, since senscence is aleways defined as "irreversible G0 state". (the GO definition is incomplete). 

A senescent cell can no longer replicate, although it can be metabolically active. 
https://pubmed.ncbi.nlm.nih.gov/27558094/#:~:text=In%20broader%20perspective%2C%20quiescence%20occurs,ensuing%20a%20certain%20cell%20death.

 Senscence is a irreversible G0 state 

If it's a reversible G0 state it is quiescence (which is senescence-like) but reversible.

If senescent cells are reactivated this appears to be associated with tumourigenisis
https://www.frontiersin.org/articles/10.3389/fcell.2021.645593/full
Although the cell cycle arrest in cellular senescence is believed to be irreversible, studies have recently shown that senescent cells can under certain circumstances re-enter the cell cycle such as in tumor cells ([Galanos et al., 2016]

i.e. not a normal process.

I think we could probably stick with the commonly used definition until there was good evidence for evolved pathways of reversibility (which would probably be relabelled anyway).

**Comment by addiehl** [comment]
We can ignore T cell senescence as perhaps a different type of process, but we won't be able to fix the language used by immunologists.

**Comment by ValWood** [comment]
I had a look at the paper you mention. Basically:
"We now show that T cell senescence associated with
DNA damage is reversible at least in part by blocking the p38
pathway" so they use a p38 inhibitor to switch of the arrest checkpoint. In this case a cessation of the arrest would be expected but this is an engineered rather than an evolved observation, so we probably don't need to worry about changing the definition of senescence.

If the situation does arise naturally, "cellular quiescence" would describe the  situation better

We still have quite a bit of inconsistency.
1. We have "cellular quiescence" defined as a phase but "cellular senescence" defined as a process
2. GO:0070314   G1 to G0 transition with exact synonym establishment of cell quiescence when this could also to senescence

**Comment by ValWood** [comment]
It seems that the annotations to "cellular senescence" are describing 
"entry into senescence"  
"cellular senescence" sounds more like a "state" than a "biological process"?

**Comment by ValWood** [comment]
I should add, that senescence (G0 arrest)  does occur in yeast, but there is no evidence that this is evolved. It would occur, for example, if a checkpoint cannot be satisfied (I guess cells indefinitely stuck in G0 senescence, as opposed to quiescence, would die eventually so it's an evolutionary dead end) . As far as i'm aware there is no evolved program to make this happen (I  guess there could be a mechanism to remove cells, but I never came across it).

The main reason for the taxon restriction here is to prevent inappropriate annotation transfer.

**Comment by ValWood** [comment]
Are there any objections to this change:

Consider:
Cellular Senescence: Cellular senescence is an irreversible process in which individual cells within a multicellular organism lose their ability to divide and function properly. It is a mechanism that limits the proliferative potential of cells and helps prevent the development of cancer.

Also add multicellular parentage GO:0032501
multicellular organismal process

This would fit the current widespread usage and prevent the use of "Cellular senescence" to represent  the reversible process (which is really quiescence). We could revisit this if anyone needs to annotate something which does not fit the commonly used definition and see how to resolve from there, but this would define the usage more clearly.

**Comment by ValWood** [comment]
@pgaudet  There are only 160 EXP annotation to "cellular senescence"
A lot are to mice  micro RNAs from 
https://europepmc.org/article/MED/25751060
Do you see how these are annotated to senescence? I can't see any mention in the publication.

**Comment by pgaudet** [comment]
Looks like they are looking at 'age-associated bone loss' in osteoblasts 


@LiNiMGI Can you please see if there is a better term for these annotations?

**Comment by ValWood** [comment]
maybe GO:0046849   bone remodeling (it seems that during aging the homeostatic processes in bone reformation break down?), but we want to annotate the 'normal' process, not the aging phenotype?

Note there is also GO:0001503 ossification/ bone formation, but oddly, in the GO graph bone formation and bone remodelling not connected.

**Comment by LiNiMGI** [comment]
@dms321  Would you please take a look of these annotations?
MGI J:222099, all annotations to "cellular senescence", thanks!

**Comment by ValWood** [comment]
I'm. a bit stuck with this one, it has a taxon restriction "never in Fungi" so although the definitions does not explicty exclude, it dealt with my immediate problem. The  parentage is also a bit strange (cellular metabolic process), and the definitions doesn't make much sense based on  the terms placement. 


I'm unassigning myself since my work on the ageing clean up is done.
and I'm happy to close until it becomes an issue for others.

The descendent terms look dodgy too.
" oncogene-induced cell senescence"
"stress-induced premature senescence" even though "cellular senscence" is already a descendent of "response to stress"

I'll leave this to somebody who works on organisms which do have senescence in this sense.

**Comment by ValWood** [comment]
I will Close this one, since it has the taxable constraint the type wanted if it causes problems in the future we can re-address
