### ISSUE TITLE
Term merge: [Cdc48p-Npl4p-Vms1p AAA ATPase complex ]

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25409]
* **Term to be merged: Provide GO ID and term label**

Cdc48p-Npl4p-Vms1p AAA ATPase complex (GO:0036266)
A multiprotein ATPase complex involved in the release of polyubiquitinated proteins, including those damaged by oxidative stress, from the outer mitochondria membrane into the cytoplasm where they are presented to the proteasome for proteolysis, a process also referred to as mitochondria-associated degradation (MAD). **In budding yeast, this complex includes Cdc48p, Npl4p and Vms1p.**

sounds the same as
VCP-NPL4-UFD1 AAA ATPase complex (GO:0034098)
A multiprotein ATPase complex required for the efficient dislocation of ER-lumenal degradation substrates, and their subsequent proteolysis by the proteasome. **In budding yeast, this complex includes Cdc48p, Npl4p and Ufd1p proteins.** In mammals, this complex includes a hexamer of VCP/p97 (a cytosolic ATPase) and trimers of each of its cofactors UFD1L and NPL4 (NPLOC4) (e.g. a 6:3:3 stoichiometry). [PMID:11813000, PMID:16179952]

**Comment by pgaudet** [comment]
@robnash originally requested GO:0036266 in 2015; GO:0034098
https://github.com/geneontology/go-ontology/issues/9785

The difference seems to be UFD1. 
@robnash do you remember if these are different complexes?
