### ISSUE TITLE
gene expression parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25418]
I was wondering why "gene expression" isn't a cellular process?

**Comment by ValWood** [comment]
@pgaudet  do you know why? Should this be added?

**Comment by pgaudet** [comment]
I added 'cellular biosynthetic process'
GO:0009059 'macromolecule biosynthetic process' is_a 'cellular biosynthetic process', so gene expression" (which is a child of  'macromolecule biosynthetic process' ) should now by indirectly a cellular process.
