### ISSUE TITLE
NTR: endoplasmic reticulum–interorganelle tether activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#25429]
Please provide as much information as you can: 

* **Suggested term label:**
endoplasmic reticulum–interorganelle tether activity

* **Definition (free text)**
The binding activity of a molecule that brings together two membranes, either via membrane lipid binding or by interacting with a membrane protein, to establish or maintain membrane contact sites and mediate interorganelle exchange and communication. 

* **Reference, in format PMID: 29858488
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0043495 protein-membrane adaptor activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
GO:0140506 endoplasmic reticulum-autophagosome adaptor activity
GO:0140474 mitochondrion-endoplasmic reticulum membrane tether activity
* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
@Argoudpuy 

I am not sure we can create this term, since we don't have the concept of 'interorganelle' in GO. We do have 'GO:0044232 organelle membrane contact site'.

Maybe we can create 'endoplasmic reticulum-organelle membrane tether activity'? 

@ValWood you have looked at these, any thoughts? 

Thanks, Pascale

**Comment by Argoudpuy** [comment]
@pgaudet 
ok to create endoplasmic reticulum-organelle membrane tether activity

**Comment by ValWood** [comment]
For now I have been using 
"protein-membrane adaptor"
with the tethering process term.
e.g https://www.pombase.org/gene/SPCC962.01

But I think there is a proposal to add these as MF instead
https://github.com/geneontology/go-ontology/issues/22181

**Comment by Argoudpuy** [comment]
Hi,
I would like to add a new teme request that could be a child of endoplasmic reticulum-organelle membrane tether activity.


    Suggested term label:
   endoplasmic reticulum–endosome tether activity
    Definition (free text)
   The binding activity of a molecule that brings together an endosome and an ER membrane either via membrane lipid binding or by interacting with an endosome  protein, to establish and facilitate organelle exchange.

    **Reference, in format PMID: 33124732
    (REQUIRED)

    Gene product name and ID to be annotated to this term

    Parent term(s)
    endoplasmic reticulum-organelle membrane tether activity (if its created)
    GO:0043495 protein-membrane adaptor activity

    Children terms (if applicable) Should any existing terms that should be moved underneath this new proposed term?
    

    Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)

    Cross-references

    For enzymes, please provide RHEA and/or EC numbers.

    Can also provide MetaCyc, KEGG, Wikipedia, and other links.

    Any other information
