### ISSUE TITLE
Missing parent: GO:0016192 vesicle-mediated transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25421]
should be is_a cellular process?

Or are there exceptions?

**Comment by pgaudet** [comment]
I dont know what happened. When I look at the change log in Quick GO, 


2022-01-12 | Deleted | RELATION | is a GO:0009987 (cellular process)
2020-03-15 | Added | RELATION | is a GO:0009987 (cellular process)

I suspect this has to do with changes to the logical definitions but I am not sure. 
I'll add the relation back.

**Comment by pgaudet** [comment]
The other weird thing is that we dont have a term that corresponds to 'cellular-level transport', so the classification of terms is quite inconsistent.
