### ISSUE TITLE
GO:0004362 glutathione-disulfide reductase (NADPH) activity - remove parent

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25458]
GO:0004362 glutathione-disulfide reductase (NADPH) activity has four is_a parents (shown below).
The "is_a: GO:0047134 ! protein-disulfide reductase (NAD(P)) activity" should be removed, since glutathione is not a protein.

id: GO:0004362
name: glutathione-disulfide reductase (NADPH) activity
namespace: molecular_function
def: "Catalysis of the reaction: 2 glutathione + NADP+ = glutathione disulfide + NADPH + H+." [EC:1.8.1.7, ISBN:0198506732]
comment: Note that this function was formerly EC:1.6.4.2.
xref: EC:1.8.1.7
xref: MetaCyc:GLUTATHIONE-REDUCT-NADPH-RXN
xref: RHEA:11740
is_a: GO:0015038 ! glutathione disulfide oxidoreductase activity
is_a: GO:0016209 ! antioxidant activity
is_a: GO:0016668 ! oxidoreductase activity, acting on a sulfur group of donors, NAD(P) as acceptor
is_a: GO:0047134 ! protein-disulfide reductase (NAD(P)) activity

**Comment by pgaudet** [comment]
Done in #17675
