### ISSUE TITLE
NTR epigenetic programming in the endosperm

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25455]
Child of 'epigenetic regulation of embryonic gene expression' 
Def: The global programming of epigenetic modifications following binucleate central cell fertilization. This involves DNA methylation at the silent allele. In the endosperm, some paternal genes are imprinted and only maternal genes are expressed.

References: 
PMID:16469697
PMID:16527743
PMID:18700816
PMID:10580004

**Comment by pgaudet** [comment]
- [ ] add TC plants

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141044
+name: epigenetic programming in the endosperm
+namespace: biological_process
+def: "The global programming of epigenetic modifications following binucleate central cell fertilization. This involves DNA methylation at the silent allele. In the endosperm, some paternal genes are imprinted and only maternal genes are expressed." [PMID:10580004, PMID:16469697, PMID:16527743, PMID:18700816]
+is_a: GO:0044725 ! epigenetic programming in the zygotic pronuclei
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25455" xsd:anyURI
+created_by: pg
+creation_date: 2023-05-26T13:22:06Z
+has_synonym_type: epigenetic reprogramming in the endosperm

**Comment by pgaudet** [comment]
This replaces plant annotations to 
GO:0006349 regulation of gene expression by genomic imprinting in plants, see https://docs.google.com/spreadsheets/d/1_UNkbERVawN324c8AExXcoCvjP1pkPePmTaV66CLmw8/edit#gid=0

@tberardini @lreiser does this new term seem OK to you ? 

Thanks, Pascale

**Comment by lreiser** [comment]
@pgaudet  sorry we did not comment - US holiday weekend here. Not sure if this part 'In the endosperm, some paternal genes are imprinted and only maternal genes are expressed' is necessary. Can  you add genomic imprinting as a synonym? Oh wait there is a term for that (http://amigo.geneontology.org/amigo/term/GO:0071514)- do we need one that is genomic imprinting in the endosperm?

**Comment by pgaudet** [comment]
Thanks for pointing that out. 

How about if I changed the def from "The global programming of epigenetic modifications following binucleate central cell fertilization. This involves DNA methylation at the silent allele. In the endosperm, some paternal genes are imprinted and only maternal genes are expressed." 

to "The global programming of epigenetic modifications following binucleate central cell fertilization in the endosperm, involving DNA methylation at the silent allele." - is this better ?

**Comment by pgaudet** [comment]
Hi @lreiser 

After discussion with @colinlog we made the following changes: 

- GO:0141044  epigenetic programming in the endosperm: changed definition to "The global programming of epigenetic modifications following binucleate central cell fertilization. This involves DNA methylation at the silent allele. In the endosperm, maternal genomes are hypomethylated compared with the paternal genome.", as described in Fig 1 of PMID: 28118754. 
-changed the label of the parent GO:0043045 from 'epigenetic regulation of embryonic gene expression' to 'post-fertilization epigenetic regulation of gene expression'
- created a new term for the central cell, as a child of 'GO:0071514 ! establishment of genomic imprinting' 
- +[Term]
+id: RO:0012001
+name: epigenetic programming in the central cell
+namespace: biological_process
+def: "The establishment of epigenetic modifications (imprints) in a plant central cell, leading to an asymmetry between the two maternal alleles and the paternal allele, and differential expression of the corresponding alleles. This can happen through heterochromatin formation or differential chromatin loop formation." [PMID:28118754]
+is_a: GO:0071514 ! establishment of genomic imprinting
+created_by: pg
+creation_date: 2023-06-09T12:27:08Z


Please let me know if this addresses your concerns. 

Thanks, Pascale

**Comment by pgaudet** [comment]
- [ ] add taxon restriction 'epigenetic programming in the central cell'

**Comment by lreiser** [comment]
Sure. It is on my list to update the annotations as soon as I can.
