### ISSUE TITLE
Missing parent: GO:0016972 thiol oxidase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25462]
* **GO term ID and label for which you request a new superclass**
id: GO:0016972
name: thiol oxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: 4 R'C(R)SH + O2 = 2 R'C(R)S-S(R)CR' + 2 H2O2." [RHEA:17357]
synonym: "sulfhydryl oxidase activity" RELATED [EC:1.8.3.2]
synonym: "thiol:oxygen oxidoreductase activity" RELATED [EC:1.8.3.2]
xref: EC:1.8.3.2
xref: MetaCyc:THIOL-OXIDASE-RXN
xref: RHEA:17357
xref: UM-BBD_reactionID:r1293
is_a: GO:0016670 ! oxidoreductase activity, acting on a sulfur group of donors, oxygen as acceptor

* **New superclass (parent) suggested**
Looks like this should have "GO:0015036 disulfide oxidoreductase activity" as an additional parent

**Comment by pgaudet** [comment]
Fix definition to match EC and RHEA: 

From: 'Catalysis of the reaction: 4 R'C(R)SH + O2 = 2 R'C(R)S-S(R)CR' + 2 H2O2.' 

to Catalysis of the reaction: 2 R'C(R)SH + O2 = R'C(R)S-S(R)CR' + 2 H2O2.
