### ISSUE TITLE
Textual definition update: GO:0016971  flavin-linked sulfhydryl oxidase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25461]
* **GO term ID and label for which you request a definition update**
id: GO:0016971
name: flavin-linked sulfhydryl oxidase activity
namespace: molecular_function
def: "Catalysis of the formation of disulfide bridges in proteins using FAD as the electron acceptor." [PMID:10899311]
is_a: GO:0015035 ! protein-disulfide reductase activity
is_a: GO:0016972 ! thiol oxidase activity

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
"Catalysis of the formation of disulfide bridges in proteins using FAD as a cofactor." [PMID:10899311]
or
"FAD-dependent catalysis of the formation of disulfide bridges in proteins."  [PMID:10899311]

Looking at the referenced paper (PMID:10899311) and UniProt records with an EXP annotation to this term (eg. P27882, O00391), FAD is not the electron acceptor in this reaction, but is rather present as a cofactor of the enzyme.  Oxygen is the electron acceptor, as indicated via parentage of the term through GO:0016972 ! thiol oxidase activity.

**Comment by pgaudet** [comment]
Ah ok - so then this is no different from its parent [GO:0016972 thiol oxidase activity](http://amigo.geneontology.org/amigo/term/GO:0016972#display-lineage-tab)? 

Given that GO:0016971 flavin-linked sulfhydryl oxidase activity has no cross-references, and all manually annotated entries also map to EC:1.8.3.2 (see [query](https://www.uniprot.org/id-mapping/uniprotkb/0ab1052193cc4756f001a8f88990d2edc3624426/overview))

**Comment by pgaudet** [comment]
what do you think @sjm41 ?

**Comment by sjm41** [comment]
GO:0016971 appears to be distinguished from GO:0016972 by its:
1. Dependence on FAD as a cofactor (which is probably not a sufficient distinction to merit a distinct GO term)
 
2. Apparent specificity for **protein** substrates (at least according to the current defs and parentages).
That is, GO:0016972 thiol oxidase activity is not necessarily specific to proteins, but GO:0016971 flavin-linked sulfhydryl oxidase activity apparently is specific to proteins.  If that's really true, that might be a reason to keep both terms to avoid having to co-annotate.

**Comment by pgaudet** [comment]
Thanks! So  GO:0016971 flavin-linked sulfhydryl oxidase activity likely corresponds to RHEA:59116, right ?

**Comment by sjm41** [comment]
Looks like it. The RHEA:59116 page doesn't explicitly mention FAD (though I don't know if RHEA normally mentions cofactors?) but the paper referenced on that page (PMID: 18393449) does use FAD in the assays.

**Comment by pgaudet** [comment]
Sorry, checking this again, I think the RHEA corresponds to the parent GO:0015035 'protein-disulfide reductase activity', which has no xref either....

**Comment by sjm41** [comment]
@deustp01 I think FAD is the electron acceptor (rather than a 'cofactor') in that example reaction, so that might be different?

**Comment by deustp01** [comment]
[exposes wobbliness on this definition about the definition of cofactor. Sorry]

**Comment by pgaudet** [comment]
OK, so GO:0016971 flavin-linked sulfhydryl oxidase activity does NOT corresponds to RHEA:59116, since this doesn't mention oxygen (or any acceptor).

**Comment by sjm41** [comment]
I see oxygen:
![Screenshot 2023-05-30 at 15 27 25](https://github.com/geneontology/go-ontology/assets/16306861/0404217b-679a-4907-8f20-ef0f071cc4b3)

**Comment by pgaudet** [comment]
Going over the RHEA reactions again: 

.. [RHEA:17357](https://www.rhea-db.org/rhea/17357): O2 + 2 R'C(R)SH = H2O2 + R'C(R)S-S(R)CR'
. .  [RHEA:59116](https://www.rhea-db.org/rhea/59116):   [protein]-dithiol + O2 = [protein]-disulfide + H2O2
. .   [RHEA:24112](https://www.rhea-db.org/rhea/24112):   2 glutathione + O2 = glutathione disulfide + H2O2


The two children reactions (non-protein substrate) has no entries associated with it; RHEA:24112 cites a paper that mentions human QSOX1, itself described as a https://www.uniprot.org/uniprotkb/O00391/entry

**Comment by pgaudet** [comment]
From the same branch: 

remove GO:0004362 glutathione-disulfide reductase (NADP) activity is_a GO:0047134 'protein-disulfide reductase (NAD(P)) activity' (glutathione is not a protein; the reaction is "Catalysis of the reaction: 2 glutathione + NADP+ = glutathione disulfide + NADPH + H+."

**Comment by sjm41** [comment]
Thanks @pgaudet
And I think you just fixed #25458 in the process, judging from your [comment](https://github.com/geneontology/go-ontology/issues/25461#issuecomment-1576923303) above!

**Comment by sjm41** [comment]
I believe this can be closed.
