### ISSUE TITLE
OTR: NTR cytosine nucleosidase activity-or combine with GO:0045437 uridine nucleosidase activity?

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/go-ontology#25469]
I'm looking at the YeastPathways import, and it seems we are describing cytosine nucleosidase (hydrolase) with the term "uridine nucleosidase activity" for lack of a better term.

![Screenshot 2023-05-30 at 12 22 54](https://github.com/geneontology/go-ontology/assets/13735608/f506b41f-c135-407c-b5c6-4fc3a8fc53c8)

GO:0045437 uridine nucleosidase activity has the definition "Catalysis of the reaction: H2O + uridine = ribofuranose + uracil.", but it's also being used to describe cytosine nucleosidase activity for yeast [URH1](https://www.yeastgenome.org/locus/S000002808/go):

> In the yeast Saccharomyces cerevisiae, uridine ribohydrolase activity is important for recycling, via the salvage pathway, pyrimidine deoxy- and ribonucleosides into uracil required for the growth of strains lacking the de novo pyrimidine synthesis pathway. We have shown that not only uridine and cytidine, but also 5-fluorouridine, 5-fluorocytidine and deoxycytidine are substrates for this enzyme. 
https://link.springer.com/article/10.1007/s00294-002-0296-9

MetaCyc lists this activity as a "unofficial reaction" for uridine nucleosidase: https://biocyc.org/META/NEW-IMAGE?type=EC-NUMBER&object=EC-3.2.2.3

I think this ticket is requesting a NT to include cytidine in the definition:
* **Suggested term label:**
cytidine nucleosidase activity
* **Definition (free text)**
Catalysis of the reaction: H2O + cytidine = ribofuranose + cytosine. 
* **Parent term(s)**
 GO:0050263  ribosylpyrimidine nucleosidase activity

But since the substrates are so similar, I could also see a term like cytosine/uridine nucleosidase activity. Either way these would still be children of [GO:0050263](http://amigo.geneontology.org/amigo/term/GO:0050263) ribosylpyrimidine nucleosidase activity

**Comment by pgaudet** [comment]
Hi @suzialeksander 

I see a newer paper that described URH1 as a 'pyrimidine nucleoside hydrolase' (PMID:23670538), so maybe the right EC for this activity is https://enzyme.expasy.org/EC/3.2.2.8 /RHEA:56816/GO:0050263 'ribosylpyrimidine nucleosidase activity' ? 


(also, I thought 'currency chemicals' were excluded from the reactions, like water - isn't this the case?) 

Thanks, Pascale

**Comment by deustp01** [comment]
> I thought 'currency chemicals' were excluded from the reactions

We certainly discussed this and agreed it would be a good idea, but I'm pretty sure we never figured out how to implement it, which would require a fair amount of testing of edge cases and we never did that. @ukemi ? @dustine32 ?

**Comment by ukemi** [comment]
They are certainly there in all of the imports. The discussion about how to handle them was way back when we were planning to completely align with Rhea and use Rhea to create logical definitions. We had done a few tests, but it was so long ago, I don't remember where we stood. AFAIK, that project is no longer in the picture.

**Comment by suzialeksander** [comment]
@pgaudet except the reaction is  2'-deoxycytidine + H20 -> cytosine + 2'-deoxyribose and [EC 3.2.2.8](https://enzyme.expasy.org/EC/3.2.2.8) says "2'-, 3'- and 5'-deoxynucleosides are not substrates", so that can't be it right?

Also, not an ontology issue but yes the "currency chemicals" are definitely in the imported models.

**Comment by pgaudet** [comment]
@suzialeksander Can you please provide a paper for that reaction? 

My hesitation is that yeast [URH1](https://www.yeastgenome.org/locus/S000002808/go) seems to be a broad specificity pyrimidine hydrolase or nucleosidase - we would not normally create reactions for each possible substrate. 

Thanks, Pascale
