### ISSUE TITLE
ATG8-related terms.

### ISSUE THREAD

**Issue by marcfeuermann** [geneontology/go-ontology#25472]
Hello
By working on the human autophagosome  assembly GO-CAM model I realized that there were some issues with ATG8-related terms.
ATG8 family proteins are ubiquitin-like modifiers, however they are **NOT tagging proteins** since their  C-terminal  glycine is **conjugated to phosphatidylethanolamine (PE) for their insertion to membranes**.
Their function is not protein tag but **"membrane tag"**.

**Would it be possible to create a new MF term "membrane tag" ?**

**Definition (transformed from Protein tag):**

A molecular function exhibited by a protein that is covalently attached (AKA tagged or conjugated) to a membrane where it acts as a marker, recognized by the cellular apparatus to target the tagged membrane for some cellular process such as formation of the autophagosome. The ATG8-PE conjugate mediates tethering between adjacent membranes and stimulates membrane hemifusion, leading to expansion of the autophagosomal membrane during autophagy (PubMed:17632063)

membrane tagging activity | exact
ubiquitin-like protein modifier | related
covalent modifier | related

Also, the term **"GO:0019786: Atg8-specific peptidase activity"** mixes 2 distinct activities as revealed by the synonyms... and the definition is totally wrong.

1- The protease activity is required for proteolytic activation of ATG8 family proteins and cleaves their C-terminal amino acid  to reveal a C-ter glycine required for its conjugation to phosphatidylethanolamine (PE) and insertion to membranes (PubMed:[11038174, PubMed:11100732, PubMed:11149920, PubMed:11904149, PubMed:16680092, PubMed:18701704).
We could change the former definition to this one and remove the synonym "APG8-PE hydrolase"

2- In addition to the protease activity, also catalyzes deconjugation of PE-conjugated forms of ATG8 during macroautophagy since ATG8 delipidation is required to release the protein from membranes, which facilitates multiple events during macroautophagy, (PubMed:22240591, PubMed:22652539, PubMed:28330855, PubMed:28821724, PubMed:28704456.
This second activity would correspond to the **"APG8-PE hydrolase"** synonym that should rather be **"ATG8-PE hydrolase"**.
We could also call it **"ATG8-PE deconjugation activity"**.

Hope this will be helpful to improve the "autophagy" ontology at the MF level.
Thanks a lot.
Regards,
Marc.

**Comment by pgaudet** [comment]
Discussion with @marcfeuermann about GO:0019786: Atg8-specific peptidase activity (ATG4 MF) -> this should be fixed to match the RHEA: [RHEA:67548](https://www.rhea-db.org/rhea/67548)

label:  protein-phosphatidylethanolamide deconjugating activity
narrow synonym: ATG8-PE hydrolase
narrow synonym: ATG8-PE deconjugation activity

definitinon: [protein]-C-terminal L-amino acid-glycyl-phosphatidylethanolamide + H2O = [protein]-C-terminal L-amino acid-glycine + a 1,2-diacyl-sn-glycero-3-phosphoethanolamine

**Comment by sjm41** [comment]
@pgaudet While you're dealing with this, might be worth also looking at https://github.com/geneontology/go-ontology/issues/17675

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141046
+name: Atg8-family conjugating enzyme activity
+namespace: molecular_function
+def: "Isoenergetic transfer of an Atg8 family modifer from one protein to a phosphatidylethanolamine or  phosphatidylserine on a membrane, via the reaction X-Atg8 + Y = Y-Atg8 + X." [PMID:11100732, PMID:17986448, PMID:18704115, PMID:28234446, PMID:33909989]
+synonym: "APG8 conjugating enzyme activity" EXACT []
+synonym: "Atg8 conjugating enzyme activity" NARROW []
+synonym: "Atg8-like conjugating activity" EXACT []
+synonym: "E2" BROAD []
+is_a: GO:0061650 ! ubiquitin-like protein conjugating enzyme activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/17675" xsd:anyURI
+created_by: pg
+creation_date: 2023-06-05T10:10:22Z

**Comment by sjm41** [comment]
Just noticed that the old parent term for GO:0019786 has the following def:

ubiquitin-like protein peptidase activity (GO:0019783)
An isopeptidase activity that cleaves ubiquitin or ubiquitin-like proteins (ULP; e.g. ATG8, ISG15, NEDD8, SUMO) from target proteins. PMID:19489724.

Given the changes made in this ticket, we should remove ATG8 from the list of examples in that def, right?

**Comment by sjm41** [comment]
Also, as Marc said, the old term definition of GO:0019786 mixed 2 activities of ATG4 proteins - the revised definition of GO:0019786 is now restricted to the ATG8 PE deconjugating activity (point 2 in Marc's original post). Did/should we make a distinct GO term for the separable ATG8 protease activity (point 1 in Marc's original post)?

**Comment by sjm41** [comment]
_Did/should we make a distinct GO term for the separable ATG8 protease activity (point 1 in Marc's original post)?_

I guess that activity is a subtype of:
GO:0016807 cysteine-type carboxypeptidase activity
Catalysis of the hydrolysis of a single C-terminal amino acid residue from a polypeptide chain by a mechanism in which the sulfhydryl group of a cysteine residue at the active center acts as a nucleophile. 

I can use that term to co-annotate the fly ATG4 proteins.

**Comment by marcfeuermann** [comment]
Yes, for the moment I've annotated the second activity under GO:0016807 cysteine-type carboxypeptidase activity
I am not convinced we need to create a more precise term, but the debate is open.

**Comment by pgaudet** [comment]
I propose we close for now, since there is no action needed.
