### ISSUE TITLE
Parentage of GO:0044762: negative regulation by symbiont term overly taxon restricted

### ISSUE THREAD

**Issue by jrr-cpt** [geneontology/go-ontology#25487]
Working on correcting an annotation we noticed that GO:0044762 negative regulation by symbiont of host neurotransmitter secretion term has an is_a relationship to ancestor terms that are restricted to Only in Eumetazoa. However, that is not the case where we think this term may often fit (bacterial toxin proteins) in this process. This falls under the multi-organism area @pgaudet 

Example is UniProt protein P04958 where annotation to GO:0044762 is the best fit. Instead, we will use GO:0044079 modulation by symbiont of host neurotransmitter secretion @dsiegele

**Comment by pgaudet** [comment]
TC is inherited from the links to the 'normal' host process terms, including 'regulation of neurotransmitter levels'. I will remove these links. 


@AndreaAuchincloss
