### ISSUE TITLE
NTR: protein-glutathione oxidoreductase (glutathione) activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25498]
* **Suggested term label:**
protein-glutathione oxidoreductase (glutathione) activity

* **Definition (free text)**
Catalysis of the reaction: glutathionylated protein (PSSG) + glutathione (GSH) = protein-dithiol (PSH) + glutathione disulfide (GSSG). The reaction may proceed via a 'monothiol' or 'dithiol' mechanism.

* **Reference, in format PMID:#######**
PMID:33932870 (figure 6)
PMID:36771108 (figure 3)
PMID:23397885 (figure 3)

* **Gene product name and ID to be annotated to this term**
All glutaredoxins, e.g. fly Grx1 (FBgn0036820/Q9VVT6), fly Grx5 (FBgn0030584/Q8SXQ5); human GLRX (P35754), human GLRX5 (Q86SX6)

* **Parent term(s)**
disulfide oxidoreductase activity (GO:0015036)
&
oxidoreductase activity, acting on a sulfur group of donors, disulfide as acceptor (GO:0016671) (= EC:1.8.4.-)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
n/a

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
glutaredoxin activity [BROAD]

* **Cross-references**
n/a

* **Any other information**
I think this term must be the same as the "glutathione oxidoreductase activity (GO:0097573)" term obsoleted in #23411, but that term wasn't well named/defined/used.

**Comment by ValWood** [comment]
CC @ValWood

**Comment by pgaudet** [comment]
+[Term]
+id: RO:0012001
+name: protein-glutathione oxidoreductase (glutathione) activity
+namespace: molecular_function
+def: "Catalysis of the reaction: glutathionylated protein (PSSG) + glutathione (GSH) = protein-dithiol (PSH) + glutathione disulfide (GSSG). The reaction may proceed via a 'monothiol' or 'dithiol' mechanism." []
+synonym: "glutaredoxin activity" BROAD []
+synonym: "glutathione oxidoreductase activity" BROAD []
+is_a: GO:0015036 ! disulfide oxidoreductase activity
+is_a: GO:0016671 ! oxidoreductase activity, acting on a sulfur group of donors, disulfide as acceptor
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25498" xsd:anyURI
+created_by: pg
+creation_date: 2023-06-07T06:13:18Z

**Comment by pgaudet** [comment]
Also. in that branch: 
GO:0050451 CoA-disulfide reductase activity: changed def to match EC and RHEA, this is NADP, not NAD: 
-def: "Catalysis of the reaction: 2 CoA + NAD+ = CoA-disulfide + NADH + H+." [EC:1.8.1.14, MetaCyc:COA-DISULFIDE-REDUCTASE-NADH-RXN]
+def: "Catalysis of the reaction: 2 CoA + NADP+ = CoA-disulfide + H+ + NADPH." [RHEA:14705]

**Comment by sjm41** [comment]
FYI @pgaudet Your previous comment fixes part of #25492 !

**Comment by sjm41** [comment]
Thanks for adding the new term. Can you add the 3 PMIDs I gave to the def? (And RO:0012001 -> GO:0012001 ?)

**Comment by pgaudet** [comment]
Yes yes - Protege is being weird, this is why I closed the PR, I am starting again

Also, I will add PMID:33932870  to some other terms, Figure 6 nicely explains the different reactions.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141049
+name: protein-glutathione oxidoreductase (glutathione) activity
+namespace: molecular_function
+def: "Catalysis of the reaction: glutathionylated protein (PSSG) + glutathione (GSH) = protein-dithiol (PSH) + glutathione disulfide (GSSG). The reaction may proceed via a 'monothiol' or 'dithiol' mechanism." [PMID:23397885, PMID:33932870, PMID:36771108]
+synonym: "glutaredoxin activity" BROAD []
+synonym: "glutathione oxidoreductase activity" BROAD []
+is_a: GO:0015036 ! disulfide oxidoreductase activity
+is_a: GO:0016671 ! oxidoreductase activity, acting on a sulfur group of donors, disulfide as acceptor
+is_a: GO:0140096 ! catalytic activity, acting on a protein
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25498" xsd:anyURI
+created_by: pg
+creation_date: 2023-06-07T06:36:33Z

**Comment by sjm41** [comment]
glutathione disulfide oxidoreductase activity (GO:0015038) is a grouping term in GO for these two specific activities:
```
glutathione disulfide oxidoreductase activity (GO:0015038) - no EC
|__glutathione dehydrogenase (ascorbate) activity (GO:0045174) -  EC:1.8.5.1
|__glutathione-disulfide reductase (NADP) activity (GO:0004362) - EC:1.8.1.7
```

glutathione disulfide oxidoreductase activity:
2 glutathione + electron acceptor = glutathione disulfide + electron donor

glutathione dehydrogenase (ascorbate) activity:
dehydroascorbate + 2 glutathione = L-ascorbate + glutathione disulfide

glutathione-disulfide reductase (NADP) activity:
2 glutathione + NADP+ = glutathione disulfide + NADPH + H+. 

In each case, glutathione is the substrate and is oxidized to glutathione disulfide (forward direction). Either dehydroascorbate (in the cases of GST-omega enzymes) or NADP (for Glutathione reductase enzymes) acts as the electron acceptor.  Neither is relevant for glutaredoxins AFAIK.


The NTR here is for the major reaction catalysed by (I believe) all glutaredoxins (see the reviews I referenced above):
protein-glutathione oxidoreductase (glutathione) activity
glutathionylated protein (PSSG) + glutathione (GSH) = protein-thiol (PSH) + glutathione disulfide (GSSG)

In this case, a protein-thiol (PSH) is the substrate and is oxidized to a protein-glutathione conjugate (PSSG), with glutathione disulfide acting as the electron acceptor (that's the reverse direction of that shown, but PSSG -> PSH  (i.e. deglutathionylation) is how it's more commonly presented in papers).

**Comment by sjm41** [comment]
@pgaudet Sorry, but I just noticed I wrote "protein-dithiol" in the definition, when it should be "protein-thiol"

**Comment by pgaudet** [comment]
Thanks, I fixed the definition to 'Catalysis of the reaction: glutathionylated protein (PSSG) + glutathione (GSH) = **protein-thiol** (PSH) + glutathione disulfide (GSSG). The reaction may proceed via a 'monothiol' or 'dithiol' mechanism.'

**Comment by marcfeuermann** [comment]
Yes indeed, I will put this in my list for PAINTing. 
Thanks.

**Comment by sjm41** [comment]
@marcfeuermann I think you'll want to look at (at least):
PTN000018533 (GLUTAREDOXIN 2 - PTHR45694)
PTN008497264 (GLUTAREDOXIN FAMILY MEMBER - PTHR10293)
Though you'll need to wait for revisions/additions to the sources first....
