### ISSUE TITLE
Move 'GO:0032989 cellular component morphogenesis'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25496]
The only parent for this term should be 'GO:0016043 cellular component organization'

**Comment by raymond91125** [comment]
Also removed asserted relationship ISA GO:0016043 cellular component organization, since that is inferred with LD.

**Comment by raymond91125** [comment]
I'm having a difficult time distinguishing between
cellular component organization or biogenesis
cellular component organization
cellular component morphogenesis
cell part morphogenesis

I thought morphogenesis is to generate a particular form (morphology) and it involves growth and removal, and patterning of constitutive parts.

The LD seems to be correct and I'm concerned about removing it would create more work down the line.

**Comment by raymond91125** [comment]
![image](https://github.com/geneontology/go-ontology/assets/619520/da16b277-0bf9-45b0-9b01-3e713f34f3bd)

**Comment by raymond91125** [comment]
Since the plan is to remove sub-celllar processes from developmental process, we should remove the relationship anatomical structure development ISA developmental process, and anatomical structure morphogenesis ISA developmental process.

**Comment by pgaudet** [comment]
Hi @raymond91125 

I am not clear why you say that 'anatomical structure' is related to what is being requested here. I removed the relation for the cellular components : removed

-intersection_of: GO:0009653 ! anatomical structure morphogenesis
-intersection_of: results_in_morphogenesis_of GO:0110165 ! cellular anatomical entity

Added back: 
+is_a: GO:0016043 ! cellular component organization

Thanks, Pascale
