### ISSUE TITLE
Question GO:0044804 autophagy of nucleus

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25507]
GO:0044804 autophagy of nucleus
A form of autophagy, by which damaged or non-essential parts of the nucleus, or even an entire nucleus is degraded. PMID:24013549

I am wondering why this isn't called "nucleophagy" to match other terms, including the child term
[GO:0044805]   late nucleophagy

(at present it is a related synonym, but the reason for that isn't clear)

**Comment by marcfeuermann** [comment]
The 2 terms are indeed exact synonyms. I totally agree with you Val, we should use "nucleophagy" as the main term and maybe keep "autophagy of nucleus" as an exact synonym.
I would also change "nucleus degradation" to a related synonym.

**Comment by pgaudet** [comment]
Also, shouldn't 'piecemeal microautophagy of the nucleus' be is_a nucleophagy?

**Comment by ValWood** [comment]
Thanks Marc, I meant to tag you,

**Comment by ValWood** [comment]
> Also, shouldn't 'piecemeal microautophagy of the nucleus' be is_a nucleophagy?

it is already.

**Comment by marcfeuermann** [comment]
No worries Val, Pascale manages this perfectly ;-) 
And yes 'piecemeal microautophagy of the nucleus'  is_a nucleophagy... in case it is not the case yet.
