### ISSUE TITLE
Textual name and definition update (minor)  GO:0140602    nucleolar ring

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25511]
* **GO term ID and label for which you request a definition update**

GO:0140602    nucleolar ring
Ring-like structures located at the nucleolar periphery where several nuclear factors are reversibly aggregated and sequestered during acute heat stress. PMID:33176152

* **New proposed NAME and definition (genus-differentia pattern, plus additional information if needed)**

Revised name: nucleolar peripheral inclusion body
Revised definition: Inclusion bodies located at the nucleolar periphery where several nuclear factors are reversibly aggregated and sequestered during acute heat stress or starvation. PMID:33176152
ADD narrow synonym "nucleolar ring"

* **Reference(s)**
PMID:37128864

* **Additional information**

The author of this newer paper pointed out 
" In addition, the ring-like localization pattern sometimes changed and factors become localized at two distinct peripheral regions. How should I annotate it? Should I give a different term such as “nucleolar peripheral structure”, which may be more general."

I suggested that since these are the same structures, we refine this term  and definition as above. So far is it only used by fission yeast.
The author also mentioned that they think this is similar to the **nucleolar cap** seen in higher eukaryotes.  This term does not exist at present, but if it is maybe it should be merged  as a narrow synonym with this term.

**Comment by ValWood** [comment]
@pgaudet  does this sound OK?

**Comment by pgaudet** [comment]
Sure - I dont know about this structure, and I cannot find much literature, so I dont have any argument against the proposed change. 

Thanks, Pascale
