### ISSUE TITLE
Please remove RHEA:26124 - GO:0051699 mapping

### ISSUE THREAD

**Issue by amorgat** [geneontology/go-ontology#25529]
RHEA:26124 was mapped to GO:0051699, please remove this mapping.
I set the status of RHEA:26124 to obsolete, it is replaced by [RHEA:23784](https://www.rhea-db.org/rhea/23784) (EC 1.5.5.2), the reaction catalyzed by PutA.
GO:0051699 is also mapped to RXN-821 which is now replaced by RXN-14903 
https://biocyc.org/META/NEW-IMAGE?type=NIL&object=RXN-821 is valid but redirected to RXN-14903

**Comment by pgaudet** [comment]
[RHEA:23784](https://www.rhea-db.org/rhea/23784) is mapped to GO:0004657 'proline dehydrogenase activity'

**Comment by pgaudet** [comment]
@ValWood Can you check that your annotation to GO:0051699 is correct ? This seems quite a minor activity, according to Table 1. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0051699 [proline oxidase activity](https://amigo.geneontology.org/amigo/term/GO:0051699). The reason for obsoletion is that this represents the same activity as GO:0004657 'proline dehydrogenase activity'. GO:0051699 will be replaced by GO:0004657. GO:0004657 already has the correct RHEA, EC and MetaCyc mappings.

There are 2 EXP annotations to this term, 1 UniProt, 1 PomBase. This term is mapped to MetaCyc:RXN-821 and RHEA:  26124, and these entries have been deleted. 

You can comment on the ticket: 
https://github.com/geneontology/go-ontology/issues/25529

Thanks, Pascale

**Comment by ValWood** [comment]
Since it is only 6.7% of the activity  demonstrated for L-pipecolate I can remove it.
I don't know much about  which ones are likely to be physiologically relevant based on substrate availability etc in vivo...we probably though it was worth reporting but I'm not sure if it is.....
