### ISSUE TITLE
coordinate with QuickGO on display of taxon constraints

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#25537]
QuickGO shows some inferred taxon constraints which is handy.

E.g https://www.ebi.ac.uk/QuickGO/term/GO:0031965

<img width="1206" alt="image" src="https://github.com/geneontology/go-ontology/assets/50745/a8dc711a-45a3-45cd-af69-41ef004d220b">

However, it is not using the same OWL inference procedure and property chains that are used in GO central.

See for example:

https://www.ebi.ac.uk/QuickGO/term/GO:0140676

No inferred TCs

However, TCs should be propagated over `SubClassOf has-part some`

<img width="396" alt="image" src="https://github.com/geneontology/go-ontology/assets/50745/91e0c3b4-fa92-4040-8902-216deb0eccef">

**Comment by pgaudet** [comment]
@alexsign

**Comment by pgaudet** [comment]
This information should be extracted from property chains from RO 

GO plans to calculate this information and make it available soon

**Comment by pgaudet** [comment]
GO ticket for this work is here: https://github.com/geneontology/go-ontology/issues/19759

**Comment by balhoff** [comment]
@alexsign the latest go-plus snapshot has precomputed taxon constraints added. They are all of this form, either:
- `<GO term> SubClassOf 'in taxon' some <taxon>`
- `<GO term> SubClassOf not ('in taxon' some <taxon>)`

The subclass axioms also have an annotation: `source "computed"` (in the RDF/XML file; this doesn't show up in the JSON file). The way they are precomputed, it should be possible to look directly at a term or its superclasses to get all its constraints (no need to traverse other relationships). In some cases there is redundancy or additional specificity compared to the manually asserted taxon constraints. Let me know if you have any feedback!

**Comment by pgaudet** [comment]
Looks like Alex has what he needs to deal with this.

**Comment by balhoff** [comment]
@alexsign I wanted to give you a heads up that taxon constraints using the relation [only in taxon](http://purl.obolibrary.org/obo/RO_0002160) will be replaced by [in taxon](http://purl.obolibrary.org/obo/RO_0002162), probably in the December release (there is a mix in the release which is probably coming out this week). Will this impact you?

**Comment by alexsign** [comment]
@balhoff Hi Jim, yes it will have an effect on GOA pipelines and checks, as well as on the QuickGO. My preferences that only_in_taxon remain as it is. However, if there is a real need to move it to in_taxon, no worries, I'll deal with it when new data break our pipelines.
