### ISSUE TITLE
Obsoletion notice: SMAD protein phosphorylation 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25531]
Dear all, 

For the work on signaling cassettes, we propose to obsolete the following terms:

- GO:0007182 common-partner SMAD protein phosphorylation - 7 EXP
- GO:0060389 pathway-restricted SMAD protein phosphorylation - 43 EXP
- GO:0060393 regulation of pathway-restricted SMAD protein phosphorylation - 4 EXP
- GO:0060394 negative regulation of pathway-restricted SMAD protein phosphorylation - 20 EXP
- GO:0010862 positive regulation of pathway-restricted SMAD protein phosphorylation - 66 EXP

Annotations are here: https://github.com/geneontology/go-annotation/issues/4612

assigned_by | Number of annotations
--
ARUK-UCL | 2
BHF-UCL | 81 + 2 extensions
FlyBase | 3
MGI | 4
RGD | 2
UniProt | 26
Xenbase | 1
ZFIN | 15

There are no mappings; these terms are not present in any subsets. 

The reason for obsoletion is that these represent readouts for the following terms: 

- GO:0060395 SMAD protein signal transduction
- GO:0060390 regulation of SMAD protein signal transduction
- GO:0060392 negative regulation of SMAD protein signal transduction
- GO:0060391 positive regulation of SMAD protein signal transduction
- GO:0007179 transforming growth factor beta receptor signaling pathway or regulation
- GO:0032924 activin receptor signaling pathway or regulation
- GO:0030509 BMP signaling pathway or regulation

Thanks, Pascale

 @gantonazzo @hattrill @RLovering

**Comment by lbreuza** [comment]
Hi,
I cannot find the link to the document explaining what is the motivation for obsoleting the BMP signaling pathway.
Best, Lionel

**Comment by pgaudet** [comment]
* GO:0007182 common-partner SMAD protein phosphorylation >>  consider: protein kinase activity, SMAD protein signal transduction, positive regulation of SMAD protein signal transduction
* GO:0060389 pathway-restricted SMAD protein phosphorylation >>  consider: protein kinase activity, SMAD protein signal transduction, positive regulation of SMAD protein signal transduction 
* GO:0060393 regulation of pathway-restricted SMAD protein phosphorylation >>  consider: protein kinase regulator activity, regulation of SMAD protein signal transduction 
*  GO:0060394 negative regulation of pathway-restricted SMAD protein phosphorylation >>  consider: protein kinase inhibitor activity, negative regulation of SMAD protein signal transduction 
* GO:0010862 positive regulation of pathway-restricted SMAD protein phosphorylation >>  consider: protein kinase activator activity, positive regulation of SMAD protein signal transduction
