### ISSUE TITLE
NTR: receptor ligand inhibitor activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#25538]
* **Suggested term label:**
* receptor ligand inhibitor activity

* **Definition (free text)**
Binds to and modulates the activity of a receptor ligand. 
A molecular function regulator that inhibits or decreases the activity of its target via non-covalent binding that does not result in covalent modification to the target. 

* **Reference, in format PMID: 17218603, (mouse) PMID: 12478285 (human)

* **Gene product name and ID to be annotated to this term**
NOG, Noggin, Q13253 (human), P97466 (mouse)

* **Parent term(s)**
is_a parent GO:0140678 molecular function inhibitor activity
negatively regulates parent: GO:0048018 receptor ligand activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
* broad? - ligand antagonist activity

* **Any other information**

additional parent to create the ontology structure that is similar to that of GO:0030547 signaling receptor inhibitor activity

is_a parent NTR * receptor ligand regulator activity
Definition: Binds to and modulates the activity of a receptor ligand. 

is_a parent GO:0098772 molecular function regulator activity
regulates parent: GO:0048018 receptor ligand activity

sorry if this term already exists I just couldn't find it.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141069
+name: receptor ligand inhibitor activity
+namespace: molecular_function
+def: "Binds to and decreases the activity of the ligand of a signaling receptor." [PMID:12478285, PMID:1721860]
+synonym: "signaling receptor ligand inhibitor activity" EXACT []
+intersection_of: GO:0140678 ! molecular function inhibitor activity
+intersection_of: directly_negatively_regulates GO:0038023 ! signaling receptor activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25538" xsd:anyURI
+created_by: pg
+creation_date: 2023-06-19T09:43:30Z
