### ISSUE TITLE
obsolete redundant terms in autophagy branch

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25541]
<img width="434" alt="Screenshot 2023-06-13 at 14 26 11" src="https://github.com/geneontology/go-ontology/assets/7359272/077e5e1a-3e98-4bf6-a381-9f327743dbb1">

1. mitochondrion disassembly is a strange term? It has a single child mitochondrion autophagy (should these be merged?)
2.  What is the difference between "autophagy of mitochondrion" and the child mitophagy?

3.  Types of mitophagy in GO are:
 -mitophagy
- macromitophagy
- mitophagy by induced vacuole formation 

However the paper I am reading describes 2 types of mitophagy

<img width="428" alt="Screenshot 2023-06-13 at 14 26 56" src="https://github.com/geneontology/go-ontology/assets/7359272/fde5a7f4-3b31-4d53-b7cb-9c7b9a25757a">

How do these relate to the GO terms?

4. Finally
GO:0061734   parkin-mediated stimulation of mitophagy in response to mitochondrial depolarization

seems a strange term. Is this a step in ubiquitin-mediated microphagy? There is only a regulation term and it's also a child of response to mitochondrial depolarization, but membranes need to be ruptured as part of mitophagy (mitochondria are fragmented to  make them a suitable size for engulfment).

Should this term be repurposed as "ubiquitin-dependent mitophagy" ? (and the regulation terms)?

Here is a nice 2018 review
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7255410/

CC @marcfeuermann @pgaudet

**Comment by ValWood** [comment]
Thanks Marc, hopefully, I will get to this soon. We had our first autophagy session at the recent fission yeast meeting (and a lovely keynote from  Yoshinori Ohsumi!). So we are now all over autphagy!

https://twitter.com/pombe2023/status/1668058034269208576?ref_src=twsrc%5Etfw%7Ctwcamp%5Eembeddedtimeline%7Ctwterm%5Escreen-name%3APomBase%7Ctwcon%5Es1

**Comment by marcfeuermann** [comment]
Good choice of topic :-) It is a well studied and well conserved process with many interesting specificities. 
Enjoy :-)

**Comment by pgaudet** [comment]
Chatting with Marc - we propose to reorganize the branch to clarify 


. autophagy 

. .  macroautophagy (add synonym: selective autophagy)
. . . mitophagy (add synonym: autophagy of mitochondrion)
. . . . mitophagy by induced vacuole formation
. . . nucleophagy
. . . . late nucleophagy (this may be the same as nucleophagy? )
. . . pexophagy (add synonym: autophagy of peroxisome)
. . . aggrephagy
. . . glycophagy
. . . lipophagy
. . . lysophagy
. . . proteaphagy
. . . reticulophagy
. . . ribophagy
. . . xenophagy

. . microautophagy (New term; PMID:22080117, PMID:32907930)  + add synonym: non-selective autophagy
. . . microlipophagy
. . . micromitophagy
. . . micropexophagy
. . . lysosomal microautophagy
. . . piecemeal microautophagy of the nucleus

. . chaperone-mediated autophagy
. . late endosomal microautophagy


autophagy of mitochondrion -> obsolete, unnecessary grouping class
autophagy of peroxisome -> obsolete, unnecessary grouping class
selective autophagy -> obsolete, unnecessary grouping class

**Comment by ValWood** [comment]
I will go ahead with the obsoletion notices for 
autophagy of mitochondrion -> obsolete, unnecessary grouping class
autophagy of peroxisome -> obsolete, unnecessary grouping class
selective autophagy -> obsolete, unnecessary grouping class

do I also obsolete "mitochondrion disassembly" as an unnecessary grouping term?

**Comment by ValWood** [comment]
I'm not sure abut the autophagy part.

But this is a bit crazy:
<img width="633" alt="Screenshot 2023-09-13 at 13 18 19" src="https://github.com/geneontology/go-ontology/assets/7359272/2cd5ad4d-21ea-4222-a5c6-464884e77a4d">

micropexophagy and pexophagy are siblings rather than parent child. This is because:

Comment: (on micropexophagy)
Note that this term is not a child of pexophagy because the community usually uses the latter to refer to the macroautophagy process.

<img width="633" alt="Screenshot 2023-09-13 at 13 18 19" src="https://github.com/geneontology/go-ontology/assets/7359272/48aa92bf-e8f4-40a7-8a26-673e212d7d82">

SO I think we need to leave this branch alone, or revise the solution.
Note that pexophagy and micropexophagy have different parents.

**Comment by ValWood** [comment]
Really, 
autophagy of the peroxisome should be renamed  => pexophagy
and
pexophagy renamed => macropexophagy

do you agree? otherwise it's too confusing.
The community might call  "macropexophagy" "pexophagy" but this is ambiguous and we are supposed to be disambiguating!

**Comment by ValWood** [comment]
selective autophagy
https://github.com/geneontology/go-ontology/issues/26115

autophagy of mitochondrion 
https://github.com/geneontology/go-ontology/issues/26111

awaiting decision on pexophagy

**Comment by ValWood** [comment]
Actually Comments

micromitophagy has the same comment.
Note that this term is not a child of mitophagy because the community genrally uses that latter to refer to the macroautophagy of mitochondria.

This is too confusing!

Awating decision

**Comment by ValWood** [comment]
Add
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5915032/
to terms

add comments explaining.

**Comment by ValWood** [comment]
Actions

- [ ] autophagy of mitochondrion -> obsolete, unnecessary grouping class https://github.com/geneontology/go-ontology/issues/26115
- [ ] autophagy of peroxisome -> obsolete, unnecessary grouping class
@pgaudet  there is still an issue here. "micropexophagy is a child of "autophagy of the peroxisome" which will merge into "pexophagy". I should just remove the connection between "micropexophagy" and "pexophagy" which will have exact synonym "macropexophagy" correct?
- [ ] selective autophagy -> obsolete, unnecessary grouping class https://github.com/geneontology/go-ontology/issues/26115
- [ ] mitochondrion disassembly -> obsolete, unnecessary grouping class

- [ ] Add https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5915032/
to terms add comments explaining macrophagy/mitophagy

**Comment by ValWood** [comment]
Q GO:0030398   peroxisomal membrane disassembly
no annotations. Is this required? It sounds odd?

**Comment by ValWood** [comment]
Also
defined
The controlled breakdown of the membranes of cargo-carrying vesicles formed during peroxisome degradation. PMID:11382760
?
Why cargo carrying?

**Comment by ValWood** [comment]
One more question @marcfeuermann & @pgaudet 

The parentage of all of the "microautophagy" terms is "lysosomal microautophagy" So I suspect yeast curators will no look under here (this is why it took me a while to find the microautophagy terms).
Is there any objection to relabeeling this term

lysosome microautophagy -> microautophagy 
with lysosomal microautophagy as a narrow synonym

and change the definition from

The transfer of cytosolic components into the lysosomal compartment by direct invagination of the lysosomal membrane without prior sequestration into an autophagosome. The engulfing membranes fuse, resulting in the lysosomal delivery of the cargo wrapped in a single membrane derived from the invaginated lysosomal membrane. In S. cerevisiae, the vacuole is the lysosomal compartment.

to

A type of autophagy  where,
cytosolic components  are transferred/ingested? into the lysosomal or vacuolar compartment by direct invagination of the ~lysosomal~ vacuolar  membrane without prior sequestration into an autophagosome. The engulfing membranes fuse, resulting in the lysosomal delivery of the cargo wrapped in a single membrane derived from the invaginated lysosomal membrane. ~In S. cerevisiae, the vacuole is the lysosomal compartment.~

because 'vacuole' is the more general term

**Comment by ValWood** [comment]
Oh not so fast.
Then we would be left with 
late endosomal microautophagy
The autophagy process by which cytosolic proteins targeted for degradation are tagged with a chaperone and are directly transferred into and degraded in a late endosomal compartment.

I don't immediately believe this one. Can an endosome degrade things? If a vesicle has degrading enzymes, isn't it, by definition, a vacuole?

**Comment by deustp01** [comment]
> Can an endosome degrade things?

A quick look in Wikipedia, stopping short of actual research papers confirms that late endosomes can become lysosomes. The boundary here may be fuzzy.

> If a vesicle has degrading enzymes, isn't it, by definition, a vacuole?

Is there a yeast - animal distinction here in the meaning of "vacuole"?

**Comment by ValWood** [comment]
OK late endosomal microautophagy is described:
https://europepmc.org/article/MED/21238931

perhaps we can broaden he definition of "microautophagy" above to include degradation by endosomes.

**Comment by ValWood** [comment]
>Is there a yeast - animal distinction here in the meaning of "vacuole"?

not really. vacuole is a parent of lysosome.

**Comment by deustp01** [comment]
> not really. vacuole is a parent of lysosome.

The animal cells I'm familiar with can have intracellular storage structures but they are not called vacuoles, so that parentage looks odd.

**Comment by ValWood** [comment]
Correction. There is a term yeast-type vacuole
GO:0000324   fungal-type vacuole
A vacuole that has both lytic and storage functions. 

The lysosome is defined as a lytic vacuole.

**Comment by ValWood** [comment]
...so the common parent would be "lytic vacuole"

**Comment by ValWood** [comment]
>lipid droplets, glycogen granules. Secretory and exocytic vesicles which, depending on the physiological state of the organism can persist for a long time before being used. I guess that last one may be a bit of a stretch.

OK. I think we are OK with existing vacuole definition for the reason described above, which basically says that vacuoles may or may not be storage compartments.

**Comment by pgaudet** [comment]
@marcfeuermann also proposes merging (obsoleting/replacing)  GO:0044805 late nucleophagy into [nucleophagy](http://purl.obolibrary.org/obo/GO_0044804); the difference is that this somehow happens more slowly, or is delayed compared to 'normal' autophagy, but it's the same mechanism, and all the same proteins are involved. 

Thanks, Pascale

**Comment by ValWood** [comment]
[GO:0035695](https://www.ebi.ac.uk/QuickGO/term/GO:0035695)    
mitophagy by induced vacuole formation 
-> merge into mitophagy
or 
mitophagy by internal vacuole formation

**Comment by ValWood** [comment]
- Used the definition of microautophagy above,
- Made lysosomal autophagy a "narrow synonym"
- Standardized microautophagy subtype definitions to
Degradation of a "blah" by microautophagy.
- changed label "mitophagy by induced vacuole formation" to mitophagy by internal vacuole formation" to make it clearer what there difference is. The definition seems to be a bit iffy compared to the paper (single annotation alert!)

**Comment by ValWood** [comment]
- moved wikepedia ref "macromitophagy" down to macromitophagy
- made mitophagy narrow synonym rather than 'related'

**Comment by ValWood** [comment]
We need a better definition of "autophagy" which is inclusive of nucleophagy.
Current def is
The cellular catabolic process in which cells digest parts of their own cytoplasm; allows for both recycling of macromolecular constituents under conditions of cellular stress and remodeling the intracellular structure for cell differentiation.

@pgaudet @marcfeuermann  suggestions?

**Comment by ValWood** [comment]
-moved late endosomal microautophagy under 'microautophagy'

**Comment by ValWood** [comment]
- added GO check "do not annotate' to 
autophagy of peroxisome
autophagy of mitochondrion

**Comment by ValWood** [comment]
Still to do. 
Correct autophagy definition so that it includes nucleophagy.


The cellular catabolic process in which cells digest parts of their own cytoplasm; allows for both recycling of macromolecular constituents under conditions of cellular stress and remodeling the intracellular structure for cell differentiation.

consider
The cellular catabolic process in which cells digest parts of their own cell by lytic vacuoles or lysosomes for both recycling of macromolecular constituents under conditions of cellular stress and remodeling the intracellular structure for cell differentiation.

**Comment by pgaudet** [comment]
> We need a better definition of "autophagy" which is inclusive of nucleophagy.

Current: The cellular catabolic process in which cells digest parts of their own cytoplasm; allows for both recycling of macromolecular constituents under conditions of cellular stress and remodeling the intracellular structure for cell differentiation.

Proposed: 

The cellular catabolic process in which cells digest cellular materials, such as organelles and other macromolecular constituents. Autophagy serves to provide essential nutrients under conditions of cellular stress; or can remodel intracellular structures during cell differentiation.

What do you think ?

**Comment by ValWood** [comment]
Sounds good!

**Comment by ValWood** [comment]
I used the suggested def extended by
"or non-self materials such as intracellular pathogens" because xenophagy is also under here.

I will now delete some of the unnecessary comments related to anomalies like
"rdfs:comment "Targeted macroautophagy sometimes targets regions of cytoplasm containing non-self, such as virus particles or components (e.g. see PMID:20159618). As this is essentially the same process as macroautophagy that encloses and digests only self, the term autophagy is still used despite the enclosure of some non-self (non-auto) entities."
because this is easily dealt with by extending the definition to be inclusive. 
i.e. just don't restrict to self-eating

**Comment by ValWood** [comment]
Also need a more succinct definition of maroautophagy:

Currently:
**The major inducible pathway for the general turnover of cytoplasmic constituents in eukaryotic cells, it is also responsible for the degradation of active cytoplasmic enzymes and organelles during nutrient starvation.** Macroautophagy involves the formation of double-membrane-bounded autophagosomes which enclose the cytoplasmic constituent targeted for degradation in a membrane-bounded structure. Autophagosomes then fuse with a lysosome (or vacuole) releasing single-membrane-bounded autophagic bodies that are then degraded within the lysosome (or vacuole). Some types of macroautophagy, e.g. pexophagy, mitophagy, involve selective targeting of the targets to be degraded.


Suggest:
The autophagic process that involves the bulk degradation of damaged or unnecessary cellular constituents or intracellular pathogens, and proceeds via an autophagosome which subsequently fuses with a lysosome or vacuole.

(we don't need to define the process details here)

**Comment by ValWood** [comment]
Or could be even more simply
"The autophagic process that  proceeds via an autophagosome"
(the autophagosome is the differential here from the sibling microautophagy terms

**Comment by ValWood** [comment]
deleted
While making xenophagy a subclass of (macro)autophagy may seem to directly contradict the definition of autophagy (literally self eating), it is clear that the same pathway is involved as in macroautophagy that doesn't target foreign material: formation of double-membrane-bounded autophagosomes that enclose a region of cytoplasm for degradation.
from xenophagy(fix by correcting definitions)

**Comment by ValWood** [comment]
I standardized the various definitions of all of the children of macrophagy to
The selective degradation of x by macroautophagy.

I can add some gloss or a comment if useful once macrophagy is correctly defined.

**Comment by ValWood** [comment]
- [x] Added Macroautophagy
"The autophagic process that proceeds via an autophagosome"

**Comment by ValWood** [comment]
Closing, everything remaining is in new tickets
