### ISSUE TITLE
GO:0031619   homologous chromosome orientation involved in meiotic metaphase I plate congression

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25546]
This term began life named

2005-09-29 | Added | TERM | homologous chromosome orientation during meiosis
but in 2010 was changed to

2010-05-05 | Updated | TERM | homologous chromosome orientation involved in meiotic metaphase I plate congression

Since "plate congression" appears to be a metazoan thing, and I can't quite work out which processes it refers to from
(seem to be more of an observation than a process, the place where metaphase chromosomes align)

I propose to rename this term  back to the more generic
homologous chromosome orientation during meiosis
(or more precisely homologous chromosome orientation during metaphase I)

We should also look at the other terms.

**Comment by ValWood** [comment]
@does this sound OK

**Comment by pgaudet** [comment]
@ValWood 

Who were you trying to tag ?

**Comment by ValWood** [comment]
I think I was going to tag you.

Actually the term is a bit confusing.

**Comment by ValWood** [comment]
The cell cycle process in which the sister centromeres of one chromosome attach to microtubules that emanate from the same spindle pole, which ensures that homologous maternal and paternal chromosomes are pulled in opposite directions at anaphase of meiosis I. PMID:15062096

propose
The cell cycle process in which the **centromeres of a pair of sister chromatids are fused and orientated towards the spindle** enabling attachment to microtubules that emanate from the same spindle pole (mono-oriented attachment). This orientation ensures that the homologous chromosomes are attached to opposite spindle poles (bi-orientated attachment) and segregated in opposite directions at anaphase of meiosis I. PMID:15062096

**Comment by pgaudet** [comment]
I am not super familiar with this process. It seems to me the processes in this branch of the ontology try to capture the mechanism chromosome segregation; several terms (including 'homologous chromosome orientation involved in meiotic metaphase I plate congression', don't seem to be distinct processes and my fit better in the definition of a more general term.

**Comment by pgaudet** [comment]
Sounds good. Maybe you can create a label under which to group all of these?

**Comment by ValWood** [comment]
This ticket will automatically close, but its the wrong one, remember to reopen

**Comment by ValWood** [comment]
I did this one here, and luckily the solution was the same:
https://github.com/geneontology/go-ontology/issues/25550
