### ISSUE TITLE
NTR: KNL1/SPC105 complex

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#25544]
Please provide as much information as you can: 

* **Suggested term label:**

* **Definition (free text)**
A multiprotein kinetochore subcomplex that binds to centromeric chromatin and forms part of the outer kinetochore. It helps to recruit outer kinetochore subunits that will bind to microtubules. In humans and yeast respectively, it consists of KNL1/SPC105 and ZWINT/KRE28. 

* **Reference, in format PMID:#######**
27881301

* **Gene product name and ID to be annotated to this term**
KNL1 and ZWINT

* **Parent term(s)**

outer kinetochore

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
no

**Comment by ValWood** [comment]
Note to self, this is pombe Spc7/Sos1 that Antonia mailed PomBase helpdesk about.
Deal with that during this ticket.

**Comment by ValWood** [comment]
Adding as
Knl1/Spc105 complex

**Comment by ValWood** [comment]
+[Term]
+id: GO:0180019
+name: Knl1/Spc105 complex
+namespace: cellular_component
+def: "A kinetochore subcomplex that binds to centromeric chromatin and forms part of the outer kinetochore. It helps to recruit outer kinetochore subunits that will bind to microtubules. In humans and yeast respectively, it consists of KNL1/Spc105p and ZWINT/Kre28p." [PMID:27881301]
+intersection_of: GO:0032991 ! protein-containing complex
+intersection_of: part_of GO:0000940 ! outer kinetochore
+relationship: part_of GO:0000940 ! outer kinetochore
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25544" xsd:anyURI
+created_by: vw
+creation_date: 2023-06-16T09:53:26Z
+

**Comment by ValWood** [comment]
Hi @pgaudet 
This term has somehow inherited 2 child terms (Ndc80 and DASH).

All 3 complexes are part of the outer kinetochore, but Ndc80 and DASH are not part of KNL/SPC105.

How do we remove this relation? Do I just delete the  relation?
It's odd because the equivalence axiom looks correct even though the parentage ends up wrong?

<img width="525" alt="Screenshot 2023-07-17 at 15 42 59" src="https://github.com/geneontology/go-ontology/assets/7359272/567293ce-7ce1-45a7-93bc-b68bdde41703">

**Comment by ValWood** [comment]
must come from
http://purl.obolibrary.org/obo/go/patterns/part_of_cell_component.yaml

**Comment by ValWood** [comment]
I need to remove logical defs and assert.

**Comment by ValWood** [comment]
deleted logical defs
