### ISSUE TITLE
Change term name: glutamate-ammonia ligase activity -> glutamine synthetase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25543]
Please change the GO:0004356 term name to "glutamine synthetase activity" (currently a synonym), since it is more commonly used in the literature (e.g. https://en.wikipedia.org/wiki/Glutamine_synthetase) and also matches the EC accepted name (https://enzyme.expasy.org/EC/6.3.1.2).

id: GO:0004356
name: glutamate-ammonia ligase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-glutamate + ATP + NH3 = L-glutamine + ADP + 2 H+ + phosphate." [EC:6.3.1.2, RHEA:16169]
synonym: "glutamine synthetase activity" EXACT []
synonym: "glutamylhydroxamic synthetase activity" RELATED [EC:6.3.1.2]
synonym: "L-glutamate:ammonia ligase (ADP-forming)" RELATED [EC:6.3.1.2]
synonym: "L-glutamine synthetase activity" RELATED [EC:6.3.1.2]
xref: EC:6.3.1.2
xref: KEGG_REACTION:R00253
xref: MetaCyc:GLUTAMINESYN-RXN
xref: RHEA:16169
is_a: GO:0016211 ! ammonia ligase activity

**Comment by pgaudet** [comment]
Also, fixed def to match RHEA: ATP + L-glutamate + NH4+ = ADP + H+ + L-glutamine + phosphate.

**Comment by pgaudet** [comment]
Let's also obsolete the regulation terms - there were 4 EXP, I changed 3 CAFA annotations, there is 1 ZFIN left.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
GO:1905479 negative regulation of glutamate-ammonia ligase activity
GO:1905480 positive regulation of glutamate-ammonia ligase activity
GO:1905478 regulation of glutamate-ammonia ligase activity 

The reason for obsoletion is that these should be captured as molecular function. There is 1 EXP annotation by ZFIN, see https://github.com/geneontology/go-annotation/issues/4627

These terms are not present in any subsets, there are no mappings. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25543 

Thanks, Pascale
