### ISSUE TITLE
New term request induction and suppression by symbiont of host MAPK signaling pathway  

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25572]
- suppression of host MAPK signaling pathway  
- induction by symbiont of host MAPK signaling pathway  
also, change label of 'pertubation of host innate immune response MAPK kinase signaling' to just  'pertubation of host MAPK kinase signaling'

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141070
+name: disruption of host MAPK signal transduction pathway
+namespace: biological_process
+def: "Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of a host MAPK signal transduction pathway. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:curators]
+synonym: "disruption of host MAP kinase signaling pathway" EXACT []
+synonym: "disruption of host MAPK signaling pathway" EXACT []
+is_a: GO:0052080 ! perturbation of host MAP signal transduction pathway
+created_by: pg
+creation_date: 2023-06-19T13:29:24Z
+
+[Term]
+id: GO:0141071
+name: induction by symbiont of host MAPK signal transduction pathway
+namespace: biological_process
+def: "A process in which an organism activates, maintains or increases the frequency, rate or extent of a host MAPK signal transduction pathway. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:curators]
+synonym: "activation by symbiont of host MAPK signal transduction pathway" NARROW []
+synonym: "induction by symbiont of host MAP kinase signal transduction pathway" EXACT []
+synonym: "induction of host MAPK kinase signaling pathway" EXACT []
+synonym: "stimulation by symbiont of host MAPK signal transduction pathway" NARROW []
+is_a: GO:0052027 ! perturbation of host signal transduction pathway
+is_a: GO:0052080 ! perturbation of host MAP signal transduction pathway
+created_by: pg
+creation_date: 2023-06-19T13:32:28Z
+

**Comment by genegodbold** [comment]
**Suppression of host MAPK activity by Eukaryotic Pathogen**:
- Antigen C10 (AgC10) from _Trypanosoma cruzi_: AgC10 is a GPI-anchored mucin from Trypanosoma cruzi that inhibits TNF secretion by activated macrophages [PMID:9366425]. AgC10 inhibits TNF, interleukin-10, and cyclooxygenase-2 synthesis by macrophages that have previously been activated with LPS and interferon-gamma. AgC10 destabilizes TNF and COX‐2 mRNA by inhibiting activation of p38 mitogen‐activated protein kinase and its substrate MAPK‐activated protein kinase‐2 [PMID:15162440].
- Tc52 from _Trypanosoma cruzi_: Tc52 is a 445 residue protein that targets the host p38 and extracellular-regulated kinase (ERK) in T cells which leads to increased secretion of host interleukin-10 and inhibition of IL-12 secretion. The protein is probably proteolyzed within the host cell into a 28 kDa cleavage fragment that mediates immunosignaling [PMID:12709028].

**Suppression of host MAPK activity by Bacterial Pathogen**:
- Lethal factor from _Bacillus anthracis_: Lethal factor is a protease active against nearly all forms of mitogen-activated protein kinase kinase (MAPKK), destruction of which prevents the phosphorylation of a wide variety of regulatory molecules including p38, extracellular-regulated kinase (ERK), and Jun N-terminal kinase (JNK). This prevents the downstream transcriptional activation in the immune cells that respond to bacterial invasion, limiting their ability to defend the host. Lethal factor is a Zn2+-dependent metalloprotease. It requires protective antigen for entry into a mammalian cell via one of two receptors. Lethal factor is active against nearly all forms of mitogen-activated protein kinase kinase (MAPKK), destruction of which prevents the phosphorylation of a wide variety of regulatory molecules including p38, extracellular-regulated kinase (ERK), and Jun N-terminal kinase (JNK). This prevents the appropriate transcriptional activation in the immune cells that respond to bacterial invasion, limiting their ability to defend the host [PMID:26978402]. 
- Yersinia outer protein J (YopJ) from _Yersinia pseudotuberculosis_: YopJ is a T3SS effector that inhibits activation of host MAPK (ERK1/2, JNK, p38)  and NFkappaB via acetylation of Ser and Thr residues on MAPKK and IKKbeta. Acetylation prevents their activation by upstream kinases [PMID:16728640] and [PMID:17116858]. YopJ is activated by  host inositol hexakisphosphate [PMID:20430892]. YopJ inhibits the response of host of macrophages to infection by diminishing the MAPK/ERK-mediated biosynthesis of prostaglandin E2 (PGE2) by host cyclooxygenase-2 (COX-2) [PMID:34319170].

**Suppression of host MAPK activity by Viral Pathogen**:
- Unique short 28 (US28) from Human herpesvirus 5 (HHV-6; human cytomegalovirus): US28, a cell surface GPCR resembling a host chemokine receptor, attenuates MAPK and NF-kappaB signaling to maintain a latent (hidden) infection in monocytes, even in the absence of chemokine binding [PMID:29208743]. US28 is expressed in both latent and lytic infection and is required for latent infection of hematopoietic progenitor cells [PMID:26719258]. The structure of HCMV US28 in combination with fractalkine, showing how it recognizes host chemokines has been solved [PMID:25745166].
- B1 kinase (VPK1) from Vaccinia virus: VPK1 modulates cellular responses via host JUN by two different mechanisms, either by direct phosphorylation or by modulation of upstream JIP1-MAPK complexes [PMID:16840345].
- M2 from Vaccinia virus: The M2L protein interferes with the phosphorylation of host ERK2 (MAP kinase) and the subsequent activation of an NFkappaB response.  Mutant viruses lacking M2 activate NFkappaB more readily during infection [PMID:19738427]. 
-

**Comment by genegodbold** [comment]
**Enhancement/Activation of host MAPK activity by Eukaryotic Pathogen**:
- GRA24 from _Toxoplasma gondii_: GRA24 is a dense granule protein released into the host cytoplasm that trafficks to the host nucleus and targets host p38alpha which leads to an unusually persistent autophosphorylation and activation of the host kinase in both humans and mice. This results in the upregulation of multiple proinflammatory cytokines including IL-12p40 and  MCP-1/CCL2 [PMID:24043761].

**Enhancement/Activation of host MAPK activity by Bacterial Pathogen**:
