### ISSUE TITLE
Change labels 'modulation by symbiont of host signal transduction pathway' & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25571]
'modulation by symbiont of host signal transduction pathway' -> perturbation of host... 
'modulation by symbiont of defense-related host salicylic acid-mediated signal transduction pathway' -> perturbation of host... 
'modulation by symbiont of host adenylate cyclase-mediated signal transduction' -> perturbation of host... 
'modulation by symbiont of host calcium or calmodulin-mediated signal transduction' -> perturbation of host... 
'modulation by symbiont of host cGMP-mediated signal transduction' -> perturbation of host... 
'modulation by symbiont of host I-kappaB kinase/NF-kappaB cascade' -> perturbation of host... 
'modulation by symbiont of host protein kinase-mediated signal transduction' -> perturbation of host... 
'modulation by symbiont of host receptor-mediated signal transduction' -> perturbation of host... 
'modulation by symbiont of host small GTPase mediated signal transduction' -> perturbation of host...

**Comment by pgaudet** [comment]
@genegodbold please provide references for induction of NF kappa B signaling in host

**Comment by genegodbold** [comment]
**Disruptors of NF-kappaB from eukaryotic pathogens**
- Leishmanolysin (glycoprotein 63; GP63; major surface protease; MSP) from _Leishmania_: Leishmanolysin is responsible for the degradation of both AP-1 and nuclear factor kappaB transcription factors in host macrophages [PMID:20976196]. Leishmanolysin is a GPI-linked, zinc-dependent metalloprotease, 75% of which is found on the surface of _Leishmania major_ and associated with lipid rafts [PMID:22442494]. 
- Rhoptry organelle protein 18 (ROP18; VIR3) from _Toxoplasma gondii_: ROP18 associates with host NFkappaB subunit p65, targeting the protein for ubiquitin-mediated degradation to suppress the human NFkappaB pathway. Its kinase activity is also essential for this suppression [PMID:24648522]. ROP18 phosphorylates a key tyrosine residue in the switch loop 1 of the host immunity-related GTPases Irga6 and Irgb6, disrupting their accumulation on the membrane of the parasitophorous vacuole and protecting the parasites from destruction [PMID21147463]. ROP18 mediates the proteasomal degradation of host proteins p38 MAPK and UBE2N/Ubc13 through phosphorylation. These protein can mediate immune signaling through activation of NFkappaB via different pathways [PMID:28087594]. 

**Disruptors of NF-kappaB from bacterial pathogens**
- Cell-cycle inhibiting factor from _Burkholderia pseudomallei_: When expressed in _B. thailandensis_, Cif inhibits NFkappaB activation when used to infect human embryonic kidney cells in culture. It also inhibits activation of NFkappaB induced by TNF [PMID:29848489].
- Non-locus of enterocyte effacement (LEE) encoded effector B1 (NleB1) from _Escherichia coli_: NleB works with NleE during infection with enteropathogenic _E. coli_ (EPEC) to stabilize host cell IkappaB upon treatment with tumor necrosis factor (TNF) and thereby inhibit NFkappaB activation. Full stabilization of IkappaB required expression of both NleE and NleB [PMID:20126447].  NleB1 from EHEC and EPEC block TNF-mediated NFkappaB pathway activation while NleB2 does not. NleB1 from EHEC and EPEC glycosylate both host GAPDH and host Fas-associated death domain protein (FADD) while NleB2 is not active against either substrate [PMID:28522607]. 
- Ank6 from _Orientia tsutsugamushi_: Ank1 and Ank6 are T1SS nucleomodulin effectors of _O. tsutsugamushi_ that inhibit NFkappaB signaling by getting the RelA p65 component excluded from the nucleus using host exportin-1 thereby preventing it from activating the transcription of proinflammatory genes. Ank1 and Ank6 can accomplish this even in cells under the influence of TNF [PMID:29734393]. 
- Salmonella plasmid virulence protein D (SpvD): SpvD is a cysteine protease (Cys73-His162-Asp182) that suppresses the NFkappaB signaling pathway [PMID:27789710] and [PMID:27232334].

**Disruptors of NF-kappaB from viral pathogens**
A238L from African swine fever virus: A238L mimics cellular IkappaB and inhibits the NFkappaB transcription factor that instigates cytokine production in infected macrophages. The A238L gene product also inhibits the transcription factor NFAT. This decreases transcription of cytokines and cell activation factors that are antiviral [PMID:11676616]. A238L prevents IFNalpha, TNF, and IL-8 gene expression [PMID:10217832]. A238L is resistant to phosphorylation and can thus irreversibly bind and inactivate NFkappaB [PMID:18250452].
Orf9b from SARS-CoV-2: ORF9b antagonizes the cellular antiviral response by targeting the NFkappaB essential modulator (NEMO, IKKgamma) in primary human pulmonary alveolar epithelial cells. ORF9b (PDB:6Z4U) interferes with NFkappaB activation by associating with NEMO. Deletion of the N-terminal 30 residues of ORF9b prevents this interaction. This association disrupts the polyubiquitination of NEMO and inhibits NFkappaB signaling [PMID:33567255].

**Comment by genegodbold** [comment]
**Activators/Enhancers/Inducers of NF-kappaB from eukaryotic pathogens**
- GRA15 from _Toxoplasma gondii_: The GRA15 dense granule protein is secreted into host cells upon invasion by the parasite and then localizes to the endoplasmic reticulum. GRA15 is sufficient for sustained activation of host NFkappaB signaling [PMID:21199955]. Activation of host NFkappaB occurs through direct interaction with TNF receptor-associated factors (TRAFs). Elimination of the TRAF binding sites in the GRA15 sequence reduces its ability to activate the NFkappaB pathway [PMID:31311877]. GRA15 promotes pro-inflammatory responses in the brains of mice infected with _Toxoplasma gondii_. GRA15 modulates expression of the IL-1 pathway and inclines the infected brain toward seizure activity, promoting a proconvulsant state [PMID:34154412].

**Activators/Enhancers/Inducers of NF-kappaB from viral pathogens**
- PB1-F2 from influenza virus A: PB1-F2 appears to increase NF-kappaB expression through MAVS (not through AP-1 and IRF3) though this is antagonized by NS1. It appears that most varieties of PB1-F2 exacerbate IFN-beta transcription in epithelial cells but not immune cells [PMID:20844191]. 
- Nucleocapsid (N) protein from SARS-CoV: The structural SARS-CoV N protein accelerates host NFkappaB-driven transcription [PMID:16143815]. The nucleocapsid protein upregulates the expression of IL-6 by facilitating the translocation of NFkappaB from the cytosol to nucleus where it also binds to the NFkappaB element on the host promoter [PMID:17490702].

**Activators/Enhancers/Inducers of NF-kappaB from bacterial pathogens**

**Comment by pgaudet** [comment]
Obsolete : [symbiont-mediated perturbation of host calcium or calmodulin-mediated signal transduction](http://purl.obolibrary.org/obo/GO_0075133) : no annotations, too general (we need to specify whether the pathway is activated or suppressed, this is an unnecessary grouping term).
