### ISSUE TITLE
NTR: [iodide channel activity]

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#25578]
Dear GO curators,

Could you please consider creating 

GO:new    iodide channel activity 
definition:Enables the facilitated diffusion of a iodide (by an energy-independent process) involving passage through a transmembrane aqueous pore or channel without evidence for a carrier-mediated mechanism.

child of 
GO:0015111    iodide transmembrane transporter activity
GO:0005253   monoatomic anion channel activity
PubMed=34910516, see  Fig. 3c,d. 
relevant to Q8NHS3_MFSD8_HUMAN

xref:https://www.rhea-db.org/rhea/66324

Thank you very much for your help,
Nevila Hyka-Nouspikel

**Comment by raymond91125** [comment]
MFSD8 is believed to function as a chloride channel. Although F and I ions are permeable, are these activities known to be physiologically relevant? If the answer is no, we may not want to create this term at the moment.

"CLN7 exhibits properties of chloride channels
Chloride channels are generally also permeable to other halides. To determine the permeability of CLN7, we replaced the 150 mM Cl− in the pipette solution with 150 mM F− or 150 mM I−. The currents recorded with Cl− were larger than those with F− but smaller than those with I−, indicating an approximate permeability sequence of I− > Cl− > F− ([Fig. 3, A to D](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8673761/figure/F3/))."

**Comment by raymond91125** [comment]
@nnouspikel Do you think iodide channel activity is physiological? Thanks.

**Comment by pgaudet** [comment]
I assumed this was physiological because (a) iodine has demonstrated physiological roles (b) the authors show better affinity of the transporter for I- than for Cl-, and conclude "These findings indicate that CLN7 is involved in the transport of iodide ions." 

@nnouspikel is that also your interpretation?

**Comment by nnouspikel** [comment]
Hi Raymond,

Thanks a lot for the feedback.

It’s common knowledge that chloride channels are permeable to other negatively charged ions, especially iodide ions - https://journals.physiology.org/doi/epdf/10.1152/ajprenal.2001.280.5.F748.

MFSD8 is expressed in thyroid glands so it’s likely to play a physiological role in thyroids where I- are critical for hormone synthesis - https://www.proteinatlas.org/ENSG00000164073-MFSD8/tissue.

In the paper authors mention:  “Lysosomal membranes have higher permeabilities to I− than they do to Cl− (47). Consistent with this characteristic, CLN7 is also more permeable to I− (Fig. 3, A to D). In addition to patch-clamp recordings, we also used an iodide-sensitive YFP variant to verify the permeability of CLN7 to I- in the present study (fig. S9, A and B). These findings indicate that CLN7 is involved in the transport of iodide ions. Since CLN7 mainly transports anions from the lysosomal cavity to the cytoplasm, KO of CLN7 may cause accumulation of I- in lysosomes, which may affect lysosomal enzymatic activities (48). Therefore, changes in I- balance may be related to the pathogenesis of CLN7-related diseases.” - PMID:24472; PMID:7359909

Fig. S13 shows that the pathogenic mutations E336Q and A157 change the selectivity of CLN7 to different halide ions.

It's true that the phenotype of patients with mutations in MFSD8 is not apparently reminiscent of hypothyroidy by iodide deficiency, still MFSD8 could be redundant with another I- channel. 

It’s up to you but I think it would be justified to create a new term.

All the best,
Nevila

**Comment by raymond91125** [comment]
Thanks for the clarification.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160081
+name: iodide channel activity
+namespace: molecular_function
+def: "Enables the facilitated diffusion of a iodide (by an energy-independent process) involving passage through a transmembrane aqueous pore or channel without evidence for a carrier-mediated mechanism." [PMID:34910516]
+xref: RHEA:66324
+intersection_of: GO:0015267 ! channel activity
+intersection_of: has_primary_input CHEBI:16382 ! iodide
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25578" xsd:anyURI
+created_by: rynl
+creation_date: 2023-07-12T18:10:32Z

**Comment by nnouspikel** [comment]
Thanks a lot!
