### ISSUE TITLE
Disruption of host signaling pathways

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25581]
Hi @genegodbold 

We have terms for these for viruses: 

- PATHGO:0000302 | disrupts JAK-STAT signaling in another organism [Gene--I provide eukaryotic and bacterial examples below]
- PATHGO:0000304 | disrupts PKR activity in another organism [Gene--all the examples I have are viral]
- PATHGO:0000306 | disrupts RIG-I signaling in another organism [Gene--I have one bacterial example below]
- PATHGO:0000306 | disrupts RIG-I signaling in another organism
- PATHGO:0000314 | modulates TRAF signaling in another organism [Gene--I provide eukaryotic and bacterial examples below]
- PATHGO:0000329 | modulates ISGylation in another organism (Gene--I only have viral which I have mentioned below)
- PATHGO:0000382 | suppresses interferon signaling in another organism (Gene--I've got one eukaryotic and one (maybe) bacterial, see below
-- | --

If you have examples of these outside viruses, I can create more general terms.

Thanks, Pascale

**Comment by pgaudet** [comment]
I also need references for PATHGO:0000300 | disrupts STING signaling in another organism

**Comment by genegodbold** [comment]
**Disrupts STING signaling in another organism (examples are all viral)**
- E7 from alpha papillomavirus: E7, via the Leu-Xxx-Cys-Xxx-Glu motif,  binds the host adaptor protein STING which is downstream of the intracellular DNA sensor cGAS, of the cGAS-STING pathway, and is crucial for detecting DNA and responding to viral infections [PMID:26405230]. 
- E1A from human adenovirus: E1A inhibits the cGAS-STING pathway by binding host STING through the E1A LXCXE motif [PMID:26405230].
- Infected cell protein 27 (ICP27) from human herpesevirus 1 (HHV-1): When expressed ectopically, ICP27 interacts with both TBK1 and STING to stop interferon induction downstream of TBK1 and upstream of IRF3 phosphorylation. ICP27 co-immunoprecipitates with TBK1, particularly activated TBK1 in the STING-TBK1 complex. ICP27 moves from the nucleus to the cytoplasm during infection with HSV-1 [PMID:27234299].
- Intermediate Early 86 (IE86; Unique long 122; UL122) from human herpesvirus-5 (HHV-5; human cytomegalovirus): IE86 mediates the proteasome dependent degradation of STING and inhibits STING-induced activation of TBK1. The N-terminal 289 residues of IE86 appear necessary for the degradation of STING [PMID:29018427].

**Comment by genegodbold** [comment]
**Mediates de-ISGylation of proteins in another organism (both viral)**
- Nonstructural protein 3 (NSP3; papain-like protease; Plpro) from SARS-CoV-2: PLpro/Nsp3 removes ubiquitin-like ISG15 protein modifications and, to a lesser extent, Lys48-linked ubiquitin from proteins in addition to processing the SARS-CoV2 polyprotein. ISG15 is a ubiquitin-like modification induced upon viral infection. Removal of these by the virus dampens inflammation and antiviral signaling [PMID:32845033]. 
- RNA-directed RNA polymerase L (L protein) from Crimean-Congo Hemorrhagic fever virus (CCHFV): L protein is a deubiquitinase that can also remove ISGylation from proteins. The L protein OTU domain inhibits activation of NFkappaB by TNF in cultured cells. By itself, the OTU domain of L protein can interfere with antiviral immune responses and increase the pathogenicity of a heterologous virus. Transgenic expression of the OTU domain in mice makes them more susceptible to Sindbis virus infection. Sindbis virus expressing recombinant OTU domain is more virulent in interferon-deficient mice and can overcome protection mediated by over-expression of ISG15 [PMID:18078692].

**Comment by genegodbold** [comment]
**Disrupts TRIM/TRIM-like signaling (eukaryotic)**
- ROP18 from _Toxoplasma gondii_: ROP18 interacts with human TRIM21, an E3 ligase induced by interferon-gamma, promoting its phosphorylation and subsequent degradation through the lysosomal pathway. TRIM21 is normally upregulated during infection with _Toxoplasma gondii_ [PMID:34124071]. 

**Disrupts TRIM/TRIM-like signaling (bacterial)**
- _Escherichia coli_ secreted protein L (EspL): EspL is a T3SS LEE effector cysteine proteinase that degrades the RHIM-containing proteins RIPK1, RIPK3, TRIF and ZBP1/DAI within the RHIM region during infection with attaching and effacing pathogens. Proteins that contain receptor interacting protein (RIP) homotypic interaction motifs (RHIM) play a key role in cell death and inﬂammatory signaling. Bacterial infection and/or ectopic expression of EspL leads to rapid inactivation of RIPK1, RIPK3, TRIF and ZBP1/DAI and inhibition of tumor necrosis factor (TNF), lipopolysaccharide or polyinosinic:polycytidylic acid (poly(I:C))-induced necroptosis and inﬂammatory signaling. EspL designates a family of T3SS cysteine protease effectors found in a range of bacteria and reveals a mechanism by which gastrointestinal pathogens directly target RHIM-dependent inﬂammatory and necroptotic signaling pathways [PMID:28085133]. 
- AnkB from _Legionella pneumophila_: AnkB interacts specifically with the host E3 ubiquitin ligase TRIM21. The F-box domain of AnkB interacts with the host SCF1 E3 ubiquitin ligase that triggers the decoration of the LCV with K(48)-linked polyubiquitinated proteins that are targeted for proteasomal degradation. AnkB becomes rapidly polyubiquitinated within the host cell, and this modification is independent of the F-box domain of AnkB [PMID:26483404].
- Protein tyrosine phosphatase A (PtpA) from _Mycobacterium tuberculosis_: PtpA is a secreted mycobacterial phosphatase required for the intracellular survival of M. tuberculosis. PtpA inhibits innate immunity by co-opting host ubiquitin dynamics. PtpA interacts with host TRIM27. TRIM27 is an E3 ubiquitin ligase that restricts survival of mycobacteria in macrophages by promoting innate immune responses and apoptosis. PtpA antagonizes TRIM27-promoted JNK/p38 MAPK activation and host cell apoptosis by competitively binding to the RING domain of TRIM27 [PMID:27698396].
- Salmonella outer protein A (SopA): SopA is a T3SS effector that serves as a HECT-like E3 ubiquitin transferase. SopA ubiquitinates host RING ligases TRIM56 and TRIM65, both of which are important for innate immune defense by stimulating type I interferon expression in conjunction with nucleic-acid sensing receptors such as STING, RIG-I, and MDA5. Ubiquitination of TRIM56 and TRIM65 thereby targets them for degradation by the host proteasome [PMID:27058235] and [PMID:28084320].
- Salmonella secreted effector K3: The SseKs are T3SS effectors with glycosyltransferase activity. They transfer a GlcNAc moiety onto a target Arg to modulate host function [PMID:29449376]. SseK3 interacts with host protein TRIM32, an E3 ubiqutin ligase, via the DxD motif of SseK3. SseK3 suppresses the TNF-stimulated activation of the NFkappaB pathway. Ectopically expressed SseK3 partially co-localises with TRIM32 at the trans-Golgi network, but SseK3 is not recruited to Salmonella induced vacuoles or Salmonella induced filaments during Salmonella infection [PMID:26394407]. 

**Disrupts TRIM/TRIM-like signaling (viral)**
- 3C proteinase from Human enterovirus A: The 3C proteinase of enterovirus-71 cleaves the host TRIF protein, decreasing the response from TLR3 in response to viral infection [PMID:21697485]. 
- Nonstructural protein 1 (NS1) from influenza virus A: NS1 interacts with the coiled coil domain of TRIM25, an E3 ubiquitin ligase, preventing the oligomerization of TRIM25 and subsequent ubiquitination of RIG-I. This will inhibit the activation of IRF3-dependent IFN secretion and is required for optimal replication of influenza A virus [PMID:19454348].
- NSP11 from Porcine reproductive and respiratory syndrome virus: The endoribonuclease domain of NSP11 interacts with the RING domain of host TRIM59. Overexpression of TRIM59 in simian Marc-145 inhibits PPRSV infection while TRIM59 knockdown with siRNA enhances viral production in pulmonary alveolar macrophages. TRIM59 is an E3 ubiquitin ligase that is important for antiviral immunity [PMID:31683196].

**Comment by genegodbold** [comment]
Disrupts ZBP-1 signaling: Let's hold off on this one--I only have two examples.

**Comment by genegodbold** [comment]
**Disrupts JAK-STAT signaling in another organism (eukaryotic)**
- Leishmanolysin from _Leishmania major_: Leishmanolysin directly activates host cytoplasmic protein tyrosine phosphatases to negatively regulate JAK/STAT and IFNgamma signaling [PMID:22919663].
- Rhoptry organelle protein 16 (ROP16; VIR4) from _Toxoplasma gondii_: ROP16 is a kinase, released from the apical parasite organelle known as a rhoptry and injected into host cells where it constitutively downregulates host interleukin-6 (IL-6) and interleukin-12 (IL-12) [PMID:17183270]. ROP16 phosphorylates human and mouse STAT3 [PMID:19901082]. ROP16 also phosphorylates human and mouse STAT6 on Tyr641 to accomplish the blockade of STAT transcription [PMID:20624917].
- _Toxoplasma gondii_ inhibitor of STAT1-dependent transcription: TgIST is a dense granule protein that binds activated host STAT1 dimers in the nucleus of cells treated with interferon-gamma [PMID:27503074]. TgIST also associates with the chromatin-modifying Mi2/NuRD complex [PMID:27414498]. The result is a blockade of IFN-gamma-dependent transcription by STAT1 which normally cycles on and off nuclear DNA activating multiple rounds of transcription but in the presence of TgIST stays associated with the host DNA [PMID:24478085]. Deletion of IST results in increased parasite clearance in interferon-gamma activated cells and reduced virulence in mice [PMID:27414498]. TgIST inhibits STAT1/STAT2-mediated transcription in infected cells to block type I interferon signaling [PMID:31413201]. 

**Disrupts JAK-STAT signaling in another organism (bacterial)**
-Salmonella anti-inflammatory response activator (SarA): Salmonella Typhimurium effector SarA associates with and activates host STAT3 in a murine lymphoblastoid cell line. It is both necessary and sufficient for STAT3 phosphorylation thereby activating host anti-inflammatory cytokine IL-10 production. Deletion eliminates IL-10 induction while introduction of a SarA encoding plasmid restores it. SarA activity promotes intracellular replication. It can be secreted by SPI-1 and SPI-2. SarA activation of STAT3 both promotes growth and immune evasion [PMID:27437422] and [PMID:29924996].

**Comment by genegodbold** [comment]
**Disrupts RIG-I signaling in another organism (bacterial)**
- SdhA from _Legionella pneumophila_: A mutant bacterium in which the gene encoding SdhA is deleted causes a hyper-induction of interferon in mice. This hyper-induction of IFN occurs through host macrophage cytosolic RNA sensing components Ips-1, RIG-I and MDA5. This occurs independent of toll-like receptors [PMID:19936053].

**Comment by genegodbold** [comment]
**Eukaryotic factors modulating TRAF signaling in another organism**
- GRA15 from _Toxoplasma gondii_: Activation of host NFkappaB occurs through direct interaction with TNF receptor-associated factors (TRAFs). Elimination of the TRAF binding sites in the GRA15 sequence reduces its ability to activate the NFkappaB pathway [PMID:31311877].
- -GRA7 from _Toxoplasma gondii_: GRA7 induces innate immune responses in macrophages by interacting with TRAF6 via the MyD88-dependent pathway. GRA7 forms a complex with MyD88 which promotes the activation of TRAF6 and the generation of reactive oxygen species which enhances the release of inflammatory mediators [PMID:26553469]. 

**Bacterial factors modulating TRAF signaling in another organism**
- TssM from _Burkholderia pseudomallei_: When overexpressed in HEK293T cells, TssM potently inhibits host TNF-mediated NFkappaB activation without harming the cells. Ubiquitinated forms of TRAF-3, TRAF-6 and IkappaB are diminished when incubated in vitro with TssM. Mice infected with B. pseudomallei in which the gene encoding TssM had been deleted exhibited significantly higher levels of TNF and IL-6 in their lungs. They also died earlier than those infected with wild type bacteria (after an average of four days compared to eight and a half days)[PMID:20335533].
- Translocated intimin receptor (Tir) from _Escherichia coli_: Tir recruits host SHP-1 to inhibit host TNFR-associated factor 6 (TRAF6) ubiquitination and suppress the host innate immune response [PMID:23707390].
- Salmonella outer protein B (SopB): SopB contributes to immune evasion by attenuating production of reactive oxygen species in mitochondria by binding to TRAF6 to prevent mitochondrial recruitment which is necessary for ROS generation [PMID:27473656].
- Outer surface protein I (OspI) from _Shigella_: OspI is a glutamine deamidase. OspI selectively deamidates Gln100 of ubiquitin conjugating enzyme13 (ubc13) to a glutamate, inhibiting the activation of TRAF6. OspI suppresses host cell inflammation by suppressing the TNF receptor-associated factor6 (TRAF6)-mediated signaling pathway. OspI activity inhibits NFkappaB activation [PMID:22407319].

**Comment by genegodbold** [comment]
**Eukaryotic factor disrupting interferon signaling**
- GRA12 from _Toxoplasma gondii_: A T. gondii mutant deficient in the dense granule protein GRA12 is significantly less virulent in a mouse model. GRA12 localizes to the intravacuolar network membranes and is essential for resistance to host interferon-gamma [PMID:31266861].

**Bacterial factor disrupting interferon signaling**
- TIR-domain containing protein from _Aeromonas hydrophila_ (TcpAh): TcpAh is a 192 residue protein that contains a Toll/Interleukin-1 like receptor (TIR) domain that is required for infection of zebrafish by Aeromonas hydrophila. TcpAH inhibits host Toll-like receptor (TLR) signaling pathways that involved the MyD88 adapter protein in a zebrafish model of infection. TcpAh inhibits interferon signaling pathways involving TRIF [PMID:34305858].  (Gene--maybe this should be under TRIM/TRIM-like signaling, IF TRIF is part of that.)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141074
+name: disruption of host cGAS-STING signal transduction
+synonym: "A process in which a virus interferes with, inhibits or stops cGAS/STING signal transduction in the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction." EXACT [PMID:26405230, PMID:27234299, PMID:29018427]
+synonym: "disruption of host cGAS-STING signaling" EXACT []
+synonym: "suppression of host cGAS-STING" EXACT []
+is_a: GO:0052029 ! disruption of host signal transduction pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25581" xsd:anyURI
+created_by: pg
+creation_date: 2023-06-28T10:48:25Z
+

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141077
+name: suppression of host interferon-mediated signaling pathway
+namespace: biological_process
+def: "Any process in which a symbiont stops, prevents, or reduces the frequency, rate or extent of interferon-mediated signaling in the host organism." [PMID:31266861]
+synonym: "inhibition of host interferon signaling pathway" RELATED []
+synonym: "negative regulation of host interferon-mediated signaling pathway" EXACT []
+synonym: "suppression of host IFN-mediated signaling pathway" EXACT []
+synonym: "suppression of host interferon-mediated signalling pathway" EXACT []
+is_a: GO:0039503 ! suppression by virus of host innate immune response
+intersection_of: GO:0019054 ! modulation by virus of host cellular process
+intersection_of: negatively_regulates GO:0140888 ! interferon-mediated signaling pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25581" xsd:anyURI
+created_by: pg
+creation_date: 2023-06-28T11:19:12Z

**Comment by pgaudet** [comment]
to be rediscussed for the remaining comments
- https://github.com/geneontology/go-ontology/issues/25581#issuecomment-1601386775
- https://github.com/geneontology/go-ontology/issues/25581#issuecomment-1601474608

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141078
+name: disruption of host RIG-I signaling pathway
+namespace: biological_process
+def: "A process in which a virus interferes with, inhibits or stops a host RIG-I signaling pathway. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:19936053]
+synonym: "disruption of host RIG-1 signaling pathway" EXACT []
+is_a: GO:0075111 ! disruption of host receptor-mediated signal transduction
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25581" xsd:anyURI
+created_by: pg
+creation_date: 2023-07-05T13:42:08Z

**Comment by pgaudet** [comment]
Decided to change 'disruption of host signaling pathway' to 'suppression'
So we now have: 
- **perturbation of x signaling pathway**: "A process in which a symbiont subverts the x signal transduction pathway in its host organism."
- - **symbiont-mediated suppression of host x signaling pathway:** "A process in which a symbiont interferes with, inhibits or disrupts the x signal transduction pathway in the host organism, preventing its normal execution."
- - **symbiont-mediated activation of host x signaling pathway:** "A process in which a symbiont initiates, promotes, or enhances the activation of the xx signal transduction pathway in the host organism."

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141081
+name: symbiont-mediated suppression of host inflammasome-mediated signal transduction
+namespace: biological_process
+def: "A process in which a symbiont interferes with, inhibits or stops an  inflammasome-mediated signal transduction pathway in the host organism by  interfering with its normal execution. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:26687278, PMID:27214553, PMID:29061850, PMID:34324582, PMID:36227980]
+synonym: "perturbation of host inflammasome-mediated signal transduction" BROAD []
+is_a: GO:0052028 ! symbiont-mediated activation of host signal transduction pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25685" xsd:anyURI
+created_by: pg
+creation_date: 2023-07-10T14:20:22Z

**Comment by pgaudet** [comment]
Change label: 

GO:0039579
-name: suppression by virus of host ISG15-protein conjugation
+name: symbiont-mediated suppression of host ISG15-protein conjugation
 namespace: biological_process
