### ISSUE TITLE
NTR disruption of host tumor necrosis factor-mediated signaling pathway

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25580]
For GO-PathGO alignment 

@genegodbold

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141072
+name: disruption of host tumor necrosis factor-mediated signaling pathway
+namespace: biological_process
+def: "Any process in which an organism stops, prevents, or reduces the frequency, rate or extent of a host tumor necrosis factor-mediated signaling pathway. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:curators]
+synonym: "disruption of host TNF-mediated signaling pathway" EXACT []
+synonym: "disruption of host TNFR-mediated signaling pathway" EXACT []
+synonym: "disruption of host tumor necrosis factor receptor-mediated signaling pathway" EXACT []
+is_a: GO:0052029 ! disruption of host signal transduction pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25580" xsd:anyURI
+created_by: pg
+creation_date: 2023-06-21T14:26:53Z
+

**Comment by pgaudet** [comment]
still need to add references

**Comment by genegodbold** [comment]
**Bacterial ACTIVATION (not disruption) of TNFR signaling**
- Protein A can bind to osteoblast TNFR-1 resulting in the activation of NFkappaB and the production of the proinflammatory interleukin-6 (IL-6). If TNFR-1 is silenced via siRNA, NFkappaB is not activated nor IL-6 released. Protein A activation of IL-6 release from osteoblasts results in the activation of the bone-resorbing osteoclasts. _Staphylococcus aureus_ is the most common cause of bone infections [PMID:23154968]. The CD4+ T-cell cytokine IL-16 is activated by protein A (SpA), at least partially through its activation of TNFR1. Production of IL-16 contributes to lung damage in a murine model of pneumonia [PMID:24736233].
- Chlamyidial protein associating with death domains (CADD): CADD associates with mammalian death receptors both in vitro and in vivo and can induce apoptosis in a number of mammalian cell lines. Apoptosis was blocked by inhibitors of caspase activation. CADD interacts with death domains of tumor necrosis factor family receptors TNFR1, Fas, DR4, and DR5 but not with downstream adaptors [PMID:11805081].

**Viral disruptors of TNFR signaling**
- Cytokine response modifier B (CrmB) from variola virus: CrmB is a secreted and soluble viral version of the host TNF receptor (TNFR). It binds both TNF and LT-alpha and inhibits their activity [PMID:10989308]. CrmB functions as a highly specific binding protein for several chemokines that mediate recruitment of immune cells to mucosal surfaces and the skin [PMID:16581912]. Variola CrmB forms a dimer in contrast to that of cowpox virus which remains a monomer [PMID:17070121]. Variola CrmB is particularly efficient at binding human TNF compared to that of monkeypox and cowpox virus [PMID:19961417].
- BZLF1 (Zta; ZEBRA; EB1) from Epstein-Barr virus: BZLF1 prevents activation of the host tumor necrosis factor by downregulating the promoter for its receptor, TNFR1, thereby reducing signaling from the cytokine. This inhibits activation of target genes, and TNF-induced cell death [PMID:14671137].
- LMP1 (BNLF1) from Epstein-Barr virus: Expression of BNLF1/LMP1 in mice inhibits host B cell differentiation [PMID:30137504].  LMP1 engages TNF receptor-associated factors (TRAFs) and TNFR1-associated death domain protein (TRADD), which are adaptors used by TNFR to activate the transcription of anti-apoptotic genes through NFkappaB and c-Jun N-terminal kinase-dependent signaling pathways [PMID:12407409].
- E3 14.7K from human adenovirus: E3 14.7 blocks exogenous death-inducing ligands such as TNF, FasL, and TRAIL induced apoptosis downstream of their corresponding receptors by inhibiting internalization of cell surface TNFR1 [PMID:19854227].
