### ISSUE TITLE
Taxon constraint: Bad constrain for GO:0006581 acetylcholine catabolic process

### ISSUE THREAD

**Issue by SuperManu74** [geneontology/go-ontology#25594]
Dear GOA curators,
I received this taxon constraint violations in annotations 

GO:0001505 only_in_taxon Eumetazoa protein B4FZ87 GO:0006581 acetylcholine catabolic process ECO:0000314 (IDA) PMID:15980188  4577 Zea mays

This enzyme is really an Acetylcholinesterase with activity toward acetylthiocholine and propionylthiocholine. So, reconsider the taxon constraint by adding at least Viridiplantae as this annotation should be applicable ;-)

Regards,
Emmanuel Boutet

**Comment by pgaudet** [comment]
Editors discussion:  @cmungall 
1. Remove neurotransmitter metabolic process is_a regulation of neurotransmitter level
2. Consider obsoleting 'neurotransmitter metabolic process' 
3. Consider obsoleting GO:0001505 regulation of neurotransmitter levels'

**Comment by deustp01** [comment]
> 2\. Consider obsoleting 'neurotransmitter metabolic process'

We only had one usage, now changed to "norepinphrine catabolic process", which is actually a better fit for us, with separate reactions making and degrading chemicals on the one hand, and releasing them into synaptic clefts on the other.

**Comment by pgaudet** [comment]
Create a new ticket for points 2-4 above
