### ISSUE TITLE
xylitol dehydrogenase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25590]
appears to be
GO:0046526   D-xylulose reductase activity

I was looking for this and Canto didn't find it. This is possible because it is a 'related' synonym. Should it be exact? I

**Comment by pgaudet** [comment]
Sure, go ahead and change it. All EC synonyms were made 'related' by default to be on the safe side, but I do change them to something else (Exact or narrow) when appropriate.
