### ISSUE TITLE
Textual definition update: GO:0010117

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#25593]
Hello,

For GO:0010117. Plants are not the only organisms that use photoprotection, oxygenic bacteria, i.e. cyanobacteria (cyanobacteriota in the new taxonomy terms) do too.

Can you update the description please to something like this please:

"Protection mechanism used by plants and cyanobacteria under conditions of excess energy absorption as a consequence of the light reactions of photosynthesis."

Here is a recent review:
PMID: 30765616

Thanks,  Andrea

**Comment by pgaudet** [comment]
Fixed, thanks
