### ISSUE TITLE
Obsoletion: salivary gland histolysis children

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25605]
Hi @hattrill 

Whilst cleanig up the cell death branch, we noticed 3 terms
salivary gland histolysis
salivary gland cell autophagic cell death
ecdysone-mediated induction of salivary gland cell autophagic cell death

<img width="404" alt="Screenshot 2023-06-23 at 13 40 53" src="https://github.com/geneontology/go-ontology/assets/7359272/f724266a-8769-4fe3-a6b0-8d849cbe6b72">

We wondered if these were really all the same process.

CC @pgaudet

**Comment by ValWood** [comment]
Pinging @hattrill  (no hurry, I have plenty of tickets)

**Comment by hattrill** [comment]
I'll put it on a list...

**Comment by ValWood** [comment]
Hi @hattrill  I'm putting a "low priority" tag on this until you get chance to look, so it disappears from my list.

**Comment by ValWood** [comment]
@hattrill ping (no hurry, just trying to find some quick tickets)

**Comment by hattrill** [comment]
I've got it on my list ;-)

**Comment by hattrill** [comment]
Hi @ValWood 
Finally got round to looking at this.

These two are the same:
salivary gland cell autophagic cell death 
ecdysone-mediated induction of salivary gland cell autophagic cell death

I don't need these terms, they can be obsoleted and I will assign them to  
either "autophagic cell death" or "salivary gland histolysis" or other more appropriate terms such as ecdysone signaling.

I want to keep the "salivary gland histolysis" term, as this process is composed of more than one cellular process: apoptotic and autophagic plus some other processes that act at the level of the tissue.

**Comment by ValWood** [comment]
ACTION
obsolete 
salivary gland cell autophagic cell death
ecdysone-mediated induction of salivary gland cell autophagic cell death

**Comment by ValWood** [comment]
@hattrill  what should I say for the reason? added in error?

**Comment by hattrill** [comment]
Have changed annotations for FB.

**Comment by ValWood** [comment]
Thanks, since FB was the only user, I will go ahead with this one today.
v
