### ISSUE TITLE
antiphagocytosis - change label to 'disruption of host phagocytosis' ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25617]
Hi @ValWood 

You requested that we change the label of "negative regulation by symbiont of entry into host cell via phagocytosis" to
"antiphagocytosis"  in  #17983

With @genegodbold we'd like to rename this 'disruption of host phagocytosis' (to match other terms in that branch) - are you OK with this? 

Also, the definition should encompass more than just 'evasion' /'avoidance' (as in the paper you cite, PMID:23084912)
"Any process in which a symbiont avoids phagocytosis by a host cell, for example a phagocyte or a macrophage. The host is defined as the larger of the organisms involved in a symbiotic interaction."

How about 
A process in which in a symbiont interferes with or inhibits host phagocytosis by targeting the phagocytic signaling or the cellular phagocytic machinery.

Is this OK ? 

Thanks, Pascale

**Comment by ValWood** [comment]
sounds good!
