### ISSUE TITLE
NTR disruption by symbiont of host opsonization

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25616]
For GO-PathGO alignment

@genegodbold please provide references

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141073
+name: disruption by symbiont of host opsonization
+namespace: biological_process
+def: "Any process in which a symbiont interferes with, inhibits or stops opsonization by the host. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:curators]
+is_a: GO:0044068 ! modulation by symbiont of host cellular process
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25616" xsd:anyURI
+created_by: pg
+creation_date: 2023-06-26T14:46:24Z

**Comment by genegodbold** [comment]
**Eukaryotic proteins disrupting opsonization**
- pH-regulated antigen 1 (Pra1) from _Candida albicans_: Pra1p binds host C3a and C3b generated by human convertases and blocks opsonophagocytosis and killing by human neutrophils [PMID:28860090]. {C3b is an opsonin--it binds to the surface of microbial cells and is recognized by the complement receptor CR1. C3b can also bind antibodies--presumably attached to antigens--via the Fc region to facilitate internalization.)

**Bacterial proteins disrupting opsonization**
- Outer surface protein B (OspB) from _Borrelia burgdorferi_: OspB is an abundant lipoprotein on the bacterial surface that allows the bacterium to resist phagocytosis by neutrophils. It significantly reduces the amount of complement component C3bi deposited on the bacterium when exposed to serum [PMID:18068388].
- Gelatinase E (GelE) from _Enterococcus faecium_: In an _in vitro_ assay using purified components of complement, GelE acted on host C3 similarly to a C3 convertase in the presence of factor I and factor H. GelE decreases the ability of neutrophils to opsonize _E. faecalis_ and inhibits complement-mediated phagocytosis of the bacterium by human neutrophils. GelE inhibits the host complement cascade by consuming the C3 present in normal human serum and/or by clearing C3bi from the bacterial surface [PMID:18941224].
- Dihydrolipoamide dehydrogenase (Lpd) from _Pseudomonas aeruginosa_: Lpd is a bacterial surface protein that binds to host complement factor H, host complement factor H-like protein 1, host complement factor H-related protein 1 and host plasminogen. Association with these host complement control proteins and complement-degrading proteins protects the bacterium from complement-mediated destruction and opsonization [PMID:23071278].
