### ISSUE TITLE
Textual definition update: GO:0004491 methylmalonate-semialdehyde dehydrogenase (acylating) activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#25638]
* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request a definition update**
GO:0004491 methylmalonate-semialdehyde dehydrogenase (acylating) activity

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
Could you please extend the definition to describe the fact that it is also able to metabolize malonate:
According to https://www.ebi.ac.uk/intenz/query?cmd=SearchEC&ec=1.2.1.27

EC 1.2.1.27
Comments:
Also converts 3-oxopropanoate into acetyl-CoA [3]. The reaction occurs in two steps with the decarboxylation process preceding CoA-binding [3]. Bicarbonate rather than CO2 is released as a final product [3].

There is a new Rhea for the reaction on malonate [Rhea:76615] which might be included as a cross-reference.

It might be worth mentioning also that it use NAD+ which makes it different from GO:0018478 malonate-semialdehyde dehydrogenase (acetylating) activity

* **Reference(s)**
PMID:2768248

* **Additional information**

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0102662 'malonate-semialdehyde dehydrogenase (acetylating, NAD+) activity'. The reason for obsoletion is that this corresponds to the same reaction as GO:0018478 'malonate-semialdehyde dehydrogenase (acetylating) activity'; the enzyme is not specific for NAD or NADP. 

There are no manual annotations to this term. This term is mapped to the partial EC:1.2.1.- (which will be removed), and to RHEA:22992, which will be added as a Narrow Match to GO:0018478. The term will be replaced by GO:0018478 malonate-semialdehyde dehydrogenase (acetylating) activity. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25638

Thanks, Pascale
