### ISSUE TITLE
NTR: indole phytoalexin transporter activity

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#25630]
Please provide as much information as you can: 

* **Suggested term label:**
Could also be indole containing compound efflux transporter  

* **Definition (free text)**
Enables the transfer of a indole based substance or related group of substances from the inside of the cell to the outside of the cell across a membrane.

* **Reference, in format PMID:#######**
PMID: 7146609

* **Gene product name and ID to be annotated to this term**

PEN3   AGI_LocusCode:AT1G59870

* **Parent term(s)**
is a GO:0015562

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
camalexin efflux transporter

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
Suggesting a more general term to cover IBA as well as camalexin efflux but could add a parent and then specific children.

**Comment by raymond91125** [comment]
PMID: 7146609 resolves to [Psychoanalysis in Italy today]. Is there a typo?

**Comment by ukemi** [comment]
PMID:37146609?

**Comment by lreiser** [comment]
yes sorry for the poor copy paste.

**Comment by raymond91125** [comment]
ABCG36/PDR8/PEN3 is an ABC-type transporter that transports both indole phytoalexin and Indole-3-butyric acid, which are indoles.
1. I think the main parent (for logical definiiton) should be ABC-type transporter activity
2. Should we make a new term "ABC-type indole transporter activity" to cover general indole substrates?
3. Or go more chemically specific to have two new terms?
@pgaudet any suggestions?

**Comment by raymond91125** [comment]
Alternatively, we could just have a camalexin transmembrane transporter activity with the LD 'transmembrane transporter activity'
 and ('has primary input' some camalexin)

**Comment by pgaudet** [comment]
@raymond91125 

I think the best solution is to create "ABC-type indole transporter activity" to cover general indole substrates, and only create more specific terms if it is shown that there are transporters that are more specific. 

How does that sound ? 

Thanks, Pascale

**Comment by lreiser** [comment]
Works for me!

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160080
+name: ABC-type indole transporter activity
+namespace: molecular_function
+def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + indole(in) = ADP + phosphate + indole(out)." [PMID:37146609]
+intersection_of: GO:0140359 ! ABC-type transporter activity
+intersection_of: has_primary_input CHEBI:35581 ! indole
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25630#" xsd:anyURI
+created_by: rynl
+creation_date: 2023-07-12T17:21:30Z
