### ISSUE TITLE
Obsoletion notice: GO:1905226 regulation of adhesion of symbiont to host epithelial cell and positive and negative children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25675]
Dear all, 

The proposal has been made to obsolete:
GO:1905226 regulation of adhesion of symbiont to host epithelial cell
GO:1905227 negative regulation of adhesion of symbiont to host epithelial cell
GO:1905228 positive regulation of adhesion of symbiont to host epithelial cell

The reason for obsoletion is that these terms are poorly defined and have been used inconsistently. There are 2 EXP annotations to these terms, see https://github.com/geneontology/go-annotation/issues/4664

These terms are not used in any any subsets or mappings. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25675

Thanks, Pascale

**Comment by pgaudet** [comment]
Create new term for PMID:28228557

which describes a host protein that prevents pathogen adhesion 

@ValWood @mgiglio99 Isn't this a case where we could use the term 'pathogen'?

**Comment by deustp01** [comment]
The authors of PMID:28228557 focused on physical interactions between a human protein and surface proteins of an infectious strain of E.coli. Not clear from the abstract whether they checked interactions with non-infectious strains, so it's a bit of a stretch to conclude that the evolved function of the human protein is prevention of pathogen adhesion?

**Comment by ValWood** [comment]
There seem to be quite a few papers along these lines for this protein:

[Human Surfactant Protein A Alleviates SARS-CoV-2 Infectivity in Human Lung Epithelial Cells.](https://pubmed.ncbi.nlm.nih.gov/37066146/)
Jacob IB, Gemmiti A, Xiong W, Reynolds E, Nicholas B, Thangamani S, Jia H, Wang G.
bioRxiv. 2023 Apr 3:2023.04.03.535215. doi: 10.1101/2023.04.03.535215. Preprint.
PMID: 37066146 Free PMC article.
Surfactant protein A (SP-A) is a collagen-containing C-type lectin, expressed by mucosal epithelial cells and mediates its antiviral activities by binding to viral glycoproteins. This study examined the mechanistic role of human SP-A in SARS-CoV-2 infectivity …

[macrophages.](https://pubmed.ncbi.nlm.nih.gov/36960051/)
Yau E, Yang L, Chen Y, Umstead TM, Atkins H, Katz ZE, Yewdell JW, Gandhi CK, Halstead ES, Chroneos ZC.
Front Immunol. 2023 Mar 7;14:919800. doi: 10.3389/fimmu.2023.919800. eCollection 2023.
PMID: 36960051 Free PMC article.
Influenza A virus infection (IAV) often leads to acute lung injury that impairs breathing and can lead to death, with disproportionate mortality in children and the elderly. Surfactant Protein A (SP-A) is a calcium-dependent opsonin that binds a variety of pathogens …

so it could be a generic "adhesion inhibitor"

we have a term
[cell adhesion mediator activity](https://www.pombase.org/term/GO:0098631)
to represent adhesins so maybe we could have an inhibitor term for this "immune " molecule, if this is the case?
The nitty gritty about the 'proposed' interactor will be captured in the extension and taxon fields.

**Comment by ValWood** [comment]
i.e. adhesion mediator inhibitor activity

@deustp01 has a good point about the evolved role, but this would seem something that a secreted protein involved in innate immune response might have evolved to do. It seems similar to the effectors and their antagonists that we see between fungal pathogens and plants.

**Comment by pgaudet** [comment]
@AndreaAuchincloss Did you ever come across this?

**Comment by pgaudet** [comment]
Thanks @deustp01 and @ValWood 
I will remove the annotation associated with PMID:28228557, since there is not sufficient evidence. 

The other gene annotated, UniProtKB:Q99YM9, also has weak evidence for that annotation.
