### ISSUE TITLE
Multiple GO terms with EC:3.1.2.14 xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25677]
Currently we have:
```
acyl-[acyl-carrier-protein] hydrolase activity (GO:0016297) xref: EC:3.1.2.14 (17 EXP annotations)
    |_oleoyl-[acyl-carrier-protein] hydrolase activity (GO:0004320) xref: EC:3.1.2.14 (C18 chain) (0 EXP annotations)
    |_palmitoyl-[acyl-carrier-protein] hydrolase activity (GO:0016296) xref: EC:3.1.2.14 (C16 chain) (3 EXP annotations*)
    |_myristoyl-[acyl-carrier-protein] hydrolase activity (GO:0016295) xref: EC:3.1.2.14 (C14 chain) (3 EXP annotations*)
    |_dodecanoyl-[acyl-carrier-protein] hydrolase activity (GO:0047381) xref: EC:3.1.2.21 (C12 chain) (4 EXP annotations**)

*Arabidopsis ALT1 & ALT3, and human OLAH
**Arabidopsis ALT1, ALT3 & ALT4, and human OLAH
```

The EC:3.1.2.14 entry says:
Accepted Name: oleoyl-[acyl-carrier-protein] hydrolase
Alternative Name(s): acyl-[acyl-carrier-protein] hydrolase, S-acyl fatty acid synthase thioesterase
Reaction catalysed: (9Z)-octadecenoyl-[ACP] + H2O <=> (9Z)-octadecenoate + H(+) + holo-[ACP]
Comment(s): **Acts on [acyl-carrier-protein] thioesters of fatty acids from C12 to C18, but the derivative of oleic acid is hydrolyzed much more rapidly than any other compound tested.**

From the EC definition, it seems most accurate for the EC:3.1.2.14 xref to be on the parent "acyl-[acyl-carrier-protein] hydrolase activity" GO term.

Do we want to keep the substrate-specific child terms?

**Comment by sjm41** [comment]
Also, the RHEA xref on the parent term should be removed: RHEA:30131 is specific for octanoyl-ACP as the substrate

https://www.rhea-db.org/rhea/30131

id: GO:0016297
name: acyl-[acyl-carrier-protein] hydrolase activity
namespace: molecular_function
alt_id: GO:0010281
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + H2O = [acyl-carrier protein] + a fatty acid." [EC:3.1.2.14, MetaCyc:RXN-7902]
synonym: "acyl-[acyl-carrier protein] hydrolase activity" EXACT []
synonym: "acyl-ACP hydrolase activity" EXACT []
synonym: "acyl-ACP thioesterase activity" EXACT []
synonym: "acyl-ACP-hydrolase activity" RELATED [EC:3.1.2.14]
synonym: "acyl-acyl carrier protein hydrolase activity" RELATED [EC:3.1.2.14]
synonym: "acyl-acyl-carrier-protein hydrolase activity" RELATED [EC:3.1.2.14]
synonym: "S-acyl fatty acid synthase thioesterase activity" RELATED [EC:3.1.2.14]
xref: EC:3.1.2.14
xref: MetaCyc:RXN-7902
xref: RHEA:30131

**Comment by pgaudet** [comment]
Keeping the children for now, since tthere is no RHEA grouping term. 

@kaxelsen could there be a parent for these reactions: 
https://www.rhea-db.org/rhea/?query=ec:3.1.2.14

Thanks, Pascale

**Comment by pgaudet** [comment]
- [ ] GO:0004320  oleoyl-[acyl-carrier-protein] hydrolase activity: changed definition to match RHEA's: "Catalysis of the reaction: (9Z)-octadecenoyl-[ACP] + H2O = (9Z)-octadecenoate + H+ + holo-[ACP]."
- [ ] removed xref: EC:3.1.2.14
- [ ] GO:0016295  myristoyl-[acyl-carrier-protein] hydrolase activity: changed definition to match RHEA's: "Catalysis of the reaction: tetradecanoyl-[ACP] + H2O = tetradecanoate + holo-[ACP] + H+."
- [ ] removed xref: EC:3.1.2.14
- [ ] GO:0016296  palmitoyl-[acyl-carrier-protein] hydrolase activity: Changed definition to match RHEA's: "Catalysis of the reaction: hexadecanoyl-[ACP] + H2O = H+ + hexadecanoate + holo-[ACP]." 
- [ ] removed xref: EC:3.1.2.14
- [ ] GO:0016297  acyl-[acyl-carrier-protein] hydrolase activity: removed xref: RHEA:30131

**Comment by sjm41** [comment]
Reviewing these terms again, I see there is now a grouping term in RHEA matching GO:0016297 (acyl-[acyl-carrier-protein] hydrolase activity (def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + H2O = [acyl-carrier protein] + a fatty acid."):

RHEA:44596 a fatty acyl-[ACP] + H2O = a fatty acid + H+ + holo-[ACP].

So we should add that xref and update the GO name and def to match.

Looking at all related terms here, the ontology currently looks like this:

```
 |__thiolester hydrolase activity
       |__acyl-[acyl-carrier-protein] hydrolase activity (GO:0016297, EC:3.1.2.14) <=17 EXP
           |__dodecanoyl-[acyl-carrier-protein] hydrolase activity (GO:0047381, EC:3.1.2.21, RHEA:30119) <=4 EXP annotations
           |__myristoyl-[acyl-carrier-protein] hydrolase activity (GO:0016295, RHEA:30123) <=3 EXP annotations
           |__oleoyl-[acyl-carrier-protein] hydrolase activity (GO:0004320, RHEA:15057) <=0 EXP annotations
           |__palmitoyl-[acyl-carrier-protein] hydrolase activity (GO:0016296, RHEA:41932) <=3 EXP annotations
       |__3-oxo-dodecanoyl-ACP hydrolase activity (GO:0102575, no EC/RHEA) <=0 annotations
       |__3-oxo-myristoyl-ACP hydrolase activity (GO:0102574, no EC/RHEA) <=0 annotations
       |__3-oxo-palmitoyl-ACP hydrolase activity (GO:0102576, no EC/RHEA) <=0 annotations
```

I suggest we obsolete almost all these terms, and just keep GO:0016297, so we'd end up with:

```
 |__thiolester hydrolase activity
       |__fatty acyl-[ACP] hydrolase activity (GO:0016297, RHEA:44596 (ExactMatch) EC:3.1.2.14 [NarrowMatch], EC:3.1.2.21 [NarrowMatch])
```

@pgaudet ?

**Comment by pgaudet** [comment]
Yes I agree.

**Comment by sjm41** [comment]
Hi @pgaudet I've added RHEA:44596 as xref to GO:0016297, and updated the GO term name and def to match.
I will leave the obsoletions to you :-)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms: 
dodecanoyl-[acyl-carrier-protein] hydrolase activity (GO:0047381, EC:3.1.2.21, RHEA:30119) <=4 EXP annotations
myristoyl-[acyl-carrier-protein] hydrolase activity (GO:0016295, RHEA:30123) <=3 EXP annotations
oleoyl-[acyl-carrier-protein] hydrolase activity (GO:0004320, RHEA:15057) <=0 EXP annotations
palmitoyl-[acyl-carrier-protein] hydrolase activity (GO:0016296, RHEA:41932) <=3 EXP annotations
3-oxo-dodecanoyl-ACP hydrolase activity (GO:0102575, no EC/RHEA) <=0 annotations
3-oxo-myristoyl-ACP hydrolase activity (GO:0102574, no EC/RHEA) <=0 annotations
3-oxo-palmitoyl-ACP hydrolase activity (GO:0102576, no EC/RHEA) <=0 annotations

The reason for obsoletion is that these represent specific substrates of their parent, GO:0016297 fatty acyl-[ACP] hydrolase activity. The terms will be replaced by the parent, so no reannotation is needed (all annotations are from UniProt). 
The terms are not present in any subsets. 

You can comment on the ticket: 
https://github.com/geneontology/go-ontology/issues/25677

Thanks, Pascale

**Comment by pgaudet** [comment]
Obsolete siblings  GO:0102327 3-oxoacyl-CoA hydrolase activity and GO:0102150 3-oxo-myristoyl-CoA hydrolase activity

**Comment by sjm41** [comment]
Thanks @pgaudet !
