### ISSUE TITLE
Obsolete positive regulation by symbiont of host inflammatory response

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25687]
Single protein annotated, see https://github.com/geneontology/go-ontology/issues/25685

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 'GO:0052035 positive regulation by symbiont of host inflammatory response'. The reason for obsoletion is that this term is poorly defined. There are 2 EXP annotations by UniProt,  to be replaced by a new term (GO:0141079 perturbation of host inflammasome-mediated signal transduction). There are no mappings; this term is not in any subset. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25687

Thanks, 

Pascale

**Comment by genegodbold** [comment]
Hey @pgaudet, this is just a reminder that the activity of the inflammasome is just **one** aspect of the "host inflammatory response". The activation of NFkappaB is pro-inflammatory. Pro-inflammatory cytokines include tumor necrosis factor, IFNgamma, IL-1a, IL-6, and IL-12--not just the IL-1b produced by the inflammasome. Each is responsible for bits of the inflammatory response so one term is unlikely to cover the large area covered by the admittedly flawed "positive regulation by symbiont of host inflammatory response".

**Comment by pgaudet** [comment]
@genegodbold We will get to that when looking at other immune response terms.
