### ISSUE TITLE
NTR: perturbation of host inflammasome-mediated signal transduction

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25685]
NTR: perturbation of host inflammasome-mediated signal transduction

**Comment by pgaudet** [comment]
@genegodbold please add a few references

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141079
+name: perturbation of host inflammasome-mediated signal transduction
+namespace: biological_process
+def: "A process in which a symbiont interferes with, inhibits or stops a host inflammasome-mediated signal transduction pathway. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:curators]
+is_a: GO:0052029 ! disruption of host signal transduction pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25685" xsd:anyURI
+created_by: pg
+creation_date: 2023-07-05T14:20:19Z

**Comment by pgaudet** [comment]
PMID:34155776

**Comment by pgaudet** [comment]
Note to self: reannotate PMID:28331908 and PMID:7689226 with this new term.

**Comment by genegodbold** [comment]
**Inflammasome _activation_ by bacteria**
- Anthrax lethal factor activates the mouse (but not human) nucleotide-binding domain leucine-rich repeat pyrin domain-containing 1B (NLRP1B) inflammasome by cleaving NLRP1B after Lys44 [PMID:30872531].
- Cell translocating kinase A (CtkA) from _Helicobacter pylori_ induces production of pro-inflammatory cytokines (TNF, IL-6, IL-1 beta) in gastric epithelial cells via activation of the host inflammasome [PMID:25172221]. CtkA produced by Helicobacter pylori and secreted by a specialized T4SS mediates pro-inflammatory signaling through NFkappaB in host gastric epithelial cells [PMID28759055]. Recombinant CtkA that is catalytically active produces enhanced phosphorylation of the NFkappaB p65 subunit at Ser276 in human epithelial cancer cells. This leads to enhanced activation of NFkappaB  [PMID21098302].
- Community-acquired respiratory distress syndrome (CARDS) toxin from _Mycoplasma pneumonia_ activates the host NLRP3 inflammasome by directly ADP-ribosylating it. This leads to subsequent release of interleukin-1beta and associated pathologies [PMID:25538194].

**Inflammasome _suppression_ by bacteria**
- Toll/interleukin-1 receptor (TIR)-domain containing protein (BtpA; Btp1; TcpB) from _Brucella abortus_ interacts with human caspase-4 and promotes ubiquitination (and subsequent destruction) of human caspase-1, caspase-4, and caspase-11. TcpB suppresses caspase-11-mediated secretion of IL-1beta in macrophages infected by brucellae thus attenuating non-canonical inflammasome-mediated pyroptosis and inflammatory responses in both human and mouse macrophages [PMID:29061850].
- Toll/interleukin-1 receptor domain-containing protein (TcpC) from _E. coli_ interacts directly with the NLRP3 inflammasome which is crucial for recognizing pathogens in the host cytosol. IL-1beta release is markedly increased during infection with mutant bacteria lacking TcpC. TcpC attenuates activation of the NLRP3 inflammasome by binding both NLRP3 and caspase-1, preventing the activation of caspase-1 [PMID:27214553]. 
- Inhibits caspase activation A (IcaA) from Coxiella burnetii inhibits inflammasome activation and subsequent caspase-1 activation in host macrophages by inhibiting host caspase-11-activation of the inflammasome somewhere upstream of caspase-11 [PMID:26687278].
- PtpB is a phosphoinositide phosphatase secreted by _Mycobacterium tuberculosis_ during infection which inhibits host NLRP3 inflammasome-mediated IL-1beta secretion.  PtpB dephosphorylates host plasma membrane PI4P and PI(4,5)P2 to inhibit membrane localization of the N-terminal cleavage fragment of gasdermin D which inhibits formation of inflammatory cytokine release and pyroptosis. Activation of phosphoinositide phosphatase activity requires the binding of host ubiquitin by the bacterial enzyme. PtpB inhibits host gasdermin D-dependent cytokine release and subsequent pyroptosis to promote intracellular survival of the bacteria in macrophages [PMID:36227980].
- Protein kinase F (PknF) from Mycobacterium tuberculosis is a serine/threonine kinase involved in suppression of the host NLRP3 inflammasome. A mutant bacterium in which PknF is not expressed induces increased production of IL-1beta through NLRP3, the adaptor protein ASC and caspase-1, when used to infect bone marrow-derived macrophages when compared to wild-type bacteria. In a macrophage model of infection, the mutant bacteria also increased pyroptosis relative to the wild-type bacteria. The working model of the authors is that the absence of PknF decreases activity of the ABC-like transporter protein Rv1747 which results in less secreted phosphatidyl-myo-innositol mannosides (PIMs) that cannot then limit inflammasome activation [PMID:34324582].

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141081
+name: symbiont-mediated suppression of host inflammasome-mediated signal transduction
+namespace: biological_process
+def: "A process in which a symbiont interferes with, inhibits or stops an inflammasome-mediated signal transduction pathway in the host organism by interfering with its normal execution. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:26687278, PMID:27214553, PMID:29061850, PMID:34324582, PMID:36227980]
+synonym: "perturbation of host inflammasome-mediated signal transduction" BROAD []
+is_a: GO:0052028 ! symbiont-mediated activation of host signal transduction pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25685" xsd:anyURI
+created_by: pg
+creation_date: 2023-07-10T14:20:22Z
