### ISSUE TITLE
NTR symbiont-mediated activation of host interferon signaling pathway

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25686]
@genegodbold to provide references

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141080
+name: symbiont-mediated activation of host interferon signaling pathway
+namespace: biological_process
+def: "A process in which a symbiont subverts an interferon-mediated signal transduction pathway in the host organism by initiating, promoting, or enhancing its activation." [] {comment="GOC:curators"}
+is_a: GO:0052027 ! perturbation of host signal transduction pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25686" xsd:anyURI
+created_by: pg
+creation_date: 2023-07-05T14:38:51Z

**Comment by genegodbold** [comment]
Pascale, all I have for this one is GRA7 from Toxoplasma gondii--maybe not enough to justify inclusion:

- Ectopic expression of GRA7 in human epithelial cell lines (HEK293T cells, HeLA cells) and a macrophage cell line (RAW264.7 cells) lines markedly reduces the replication of vesicular stomatitis virus, influenza A virus, coxsackievirus, herpes simplex virus, and adenovirus. This antiviral activity of GRA7 was attributed to the **induction of type I interferon (IFN) signaling**, resulting in the secretion of IFNs and pro-inflammatory cytokines [PMID:29076073]. 
- GRA7 induces innate immune responses in macrophages by interacting with TRAF6 via the MyD88-dependent pathway. GRA7 forms a complex with MyD88 which promotes the activation of TRAF6 and the generation of reactive oxygen species which enhances the release of inflammatory mediators [PMID:26553469]. 
- It isn't very well annotated in UniProt: https://www.uniprot.org/uniprotkb/O00933/entry

**Comment by genegodbold** [comment]
A protein I thought might induce interferon--SdhA from Legionella pneumophila--does not. Instead, it is responsible for enveloping the bacterium in an endosomal membrane where it is concealed from all the pattern recognition receptors that subsequently induce interferon. The mutant protein allows bacterial exposure.

**Comment by pgaudet** [comment]
There is also PMID: 22945920

**Comment by pgaudet** [comment]
and PMID:35182467
