### ISSUE TITLE
Merge?: "pole cell migration" into "germ cell migration"

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#25689]
* **Term to be merged: Provide GO ID and term label**
pole cell migration - GO:0007280

* **Which term do you propose this term merge into? Provide GO ID and term label**
germ cell migration - GO:0008354

* **Reason for merge**

All three of the reviews listed below talk about how embryonic germ cell migration is a very ancient process that occurs in  animals. They do also talk about how the process is quite variable in some details as body morphology changes. However, the only difference between these two terms is that insect germ cells are commonly referred to as "pole cells". At the level of details in these two terms, there isn't anything particularly significant to distinguish "**pole cell migration**" from "**germ cell migration**". In the absence of any other child terms under "**germ cell migration**", it doesn't seem like the term "**pole cell migration**" is useful.

>  Grimaldi C, Raz E. **Germ cell migration-Evolutionary issues and current understanding.** Semin Cell Dev Biol. 2020 
> Apr;100:152-159.  PMID: 31864795.
> 
>  Barton LJ, LeBlanc MG, Lehmann R. **Finding their way: themes in germ cell migration.** Curr Opin Cell Biol. 2016 
> Oct;42:128-137.  PMID: 27484857
> 
>  Richardson BE, Lehmann R. **Mechanisms guiding primordial germ cell migration: strategies from different organism**s. 
> Nat Rev Mol Cell Biol. 2010 Jan;11(1):37-49.  PMID: 20027186

* **Reference(s)**
PMID:31864795
PMID:27484857
PMID:20027186

* **Any other information**

If this merge is made, "**pole cell migration**" should be come a NARROW synonym.

**Comment by pgaudet** [comment]
@hattrill Is this OK for you ?

**Comment by pgaudet** [comment]
ping @hattrill

**Comment by raymond91125** [comment]
@krchristie Should we close this ticket for now? This is perhaps one example of the more general 'one child' problem.

**Comment by hattrill** [comment]
Hi @pgaudet and @krchristie 

Looking at FB anatomy, a pole cell is defined as a "primordial germ cell", so it is fine to merge pole cell migration into germ cell migration. The literature is clear that pole cell migration = germ cell migration.

Updating the synonym classification for germ cell migration from 'primordial germ cell migration' from "related" to "exact" or "narrow" would be appropriate as well, I think.
