### ISSUE TITLE
Textual definition update: ryanodine-sensitive calcium-release channel activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#25693]
* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request a definition update**
GO:0005219 ryanodine-sensitive calcium-release channel activity

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**

The definition is misleading as ryanodine and ryanodine class ligands are not the ligands that physiologically activate the calcium channel. According to PubMed=27733687, it is a cytosolic calcium-gated calcium channel of the sarcoplasmic reticulum.
I suggest to review the definition or delete that term or update the annotation to vertebrate RYR1, RYR2 and RYR3.

Potential new deifinition:
Enables the transmembrane transfer of a calcium ion by a calcium-gated channel that is sensitive to ryanodine class ligands.

* **Reference(s)**
PMID: 9085308

* **Additional information**

**Comment by raymond91125** [comment]
ryanodine-sensitive calcium-release channel activity IS_A calcium-induced calcium release activity
Proposed DEF: Enables transmembrane transfer of calcium ions from an intracellular store to the cytosol on induction by increased calcium concentration and is sensitive to the pharmacological agent ryanodine.  [PMID:22822064]

I don't know why transporter activity defs tend NOT to follow Genus-Differentia.

Also note, GO:0072346 cADPR-sensitive calcium-release channel activity (no annotation) is *probably* also RYR (PMID:35219154). The literature does not seem to commit to a definitive association.
