### ISSUE TITLE
NTR: [T cell exhaustion]

### ISSUE THREAD

**Issue by nana-amazs** [geneontology/go-ontology#25698]
Please provide as much information as you can: 

* **Suggested term label:**
T cell exhaustion

* **Definition (free text)**
A state of T cell dysfunction due to chronic antigen stimulation in which T cells lose their effector functions and ability to kill cells 

* **Reference, in format PMID:#######**
•	PMID: 21739672
•	PMID: 31570879
•	PMID: [32117960](https://pubmed.ncbi.nlm.nih.gov/32117960)

* **Gene product name and ID to be annotated to this term***

NFAT ([Q8NET5](https://www.uniprot.org/uniprotkb/Q8NET5/entry)) 
(TOX) ([O94900](https://www.uniprot.org/uniprotkb/O94900/entry))
Eomes, ([O95936](https://www.uniprot.org/uniprotkb/O95936/entry))
T-bet, [Q9UL17](https://www.uniprot.org/uniprotkb/Q9UL17/entry)
BATF, [Q16520](https://www.uniprot.org/uniprotkb/Q16520/entry)
Blimp-1 [O75626](https://www.uniprot.org/uniprotkb/O75626/entry)
PD-1 [Q15116](https://www.uniprot.org/uniprotkb/Q15116/entry)
CTLA-4 [P16410](https://www.uniprot.org/uniprotkb/P16410/entry)
TIM-3 [P35625](https://www.uniprot.org/uniprotkb/P35625/entry)
LAG-3 [P18627](https://www.uniprot.org/uniprotkb/P18627/entry)
TIGIT [Q495A1](https://www.uniprot.org/uniprotkb/Q495A1/entry)

* **Parent term(s)**
GO:0042098 T cell proliferation
GO:0042110 T cell activation
GO:0046651 lymphocyte proliferation
GO:0002667 regulation of T cell anergy 
GO:0002668 negative regulation of T cell anergy
GO:0002710 negative regulation of T cell mediated immunity 
GO:0002698 negative regulation of immune effector process
GO:0050777 negative regulation of immune response

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
n/a

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
T cell Anergy (related)
T cell dysfunction (exact)
T cell Tolerance (related)

* **Cross-references**
KEGG

**Comment by pgaudet** [comment]
Maybe this could be is_a   GO:0071216 cellular response to biotic stimulus ?

**Comment by nana-amazs** [comment]
I think that could definitely be a parent!

**Comment by raymond91125** [comment]
Is this a normal function or effects of an abnormal/diseased state?

**Comment by raymond91125** [comment]
It seems that T cell exhaustion IS_A T cell differentiation involved in immune response, similar to memory T cell differentiation. Inhibitory receptors like PD-1 positively regulate this form of T cell differentiation.
I am not sure if other proposed parents are direct superclasses as opposed to related concepts.

**Comment by pgaudet** [comment]
you think this should be is_a T cell differentiation? As I understood it, this happened in already differentiated T cells.

**Comment by raymond91125** [comment]
"Although the pathways involved remain to be fully defined, advances in the molecular delineation of T cell exhaustion are clarifying the underlying causes of this state of differentiation and also suggest promising therapeutic opportunities." PMID:21739672
It is the notion that this is a programmed, differentiated state that makes it a biological process, similar to apoptosis.
Perhaps IS_A T cell differentiation involved in immune response
![image](https://github.com/geneontology/go-ontology/assets/619520/85b7c436-91ea-4a61-92ea-e235e9d4f722)

**Comment by raymond91125** [comment]
http://purl.obolibrary.org/obo/CL_0011025 exhausted T cell "An effector T cell that displays impaired effector functions (e.g., rapid production of effector cytokines, cytotoxicity) and has limited proliferative potential."
What's weird is that this term is not found in Protege but other children of effector T cell are.

**Comment by raymond91125** [comment]
@balhoff Please help. I got an error message about Rhea ID running run.sh make imports/cl_import.obo. I am trying to add term http://purl.obolibrary.org/obo/CL_0011025. https://github.com/geneontology/go-ontology/pull/25747

**Comment by balhoff** [comment]
@raymond91125 I updated the import: #25754 I'm not sure why you got errors though.

**Comment by raymond91125** [comment]
It seems T cell anergy/tolerance and exhaustion are distinct. PMID:23298609.

+[Term]
+id: GO:0160083
+name: exhausted T cell differentiation
+namespace: biological_process
+def: "The process in which a relatively unspecialized thymocyte acquires specialized features of an exhausted T cell." [PMID:21739672, PMID:31570879]
+synonym: "T cell dysfuction" RELATED []
+synonym: "T cell exhaustion" EXACT []
+intersection_of: GO:0030154 ! cell differentiation
+intersection_of: results_in_acquisition_of_features_of CL:0011025 ! exhausted T cell
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25698" xsd:anyURI
+created_by: rynl
+creation_date: 2023-07-14T22:56:05Z

**Comment by addiehl** [comment]
Yes, T cell anergy and T cell exhaustion are distinct.  And then we haven't even considered [T cell senescence](https://github.com/geneontology/go-ontology/issues/25380#issuecomment-1549924533), which is another gene-driven program.

**Comment by raymond91125** [comment]
nana-amazs If the new term is acceptable, we can implement it. Thanks.

**Comment by nana-amazs** [comment]
Thanks for all the discussion, Raymond! I will send the new term to my team as well as see if they have any thoughts and respond asap!

**Comment by raymond91125** [comment]
PMID:23298609 T cell anergy, exhaustion, senescence and stemness in the tumor microenvironment.
Just for reference, a review that covers all the key words mentioned here.

**Comment by nana-amazs** [comment]
The use of the term 'relatively unspecialized' almost gives the impression that we're talking about naive/undifferentiated T cells. 
Saying something like the statement below is more accurate. 

"The process in which an activated T cell acquires specialized features of an exhausted T cell state."

**Comment by addiehl** [comment]
I agree that the definition should  reflect that differentiation to an exhausted T cell is a secondary differentiation after activation has occurred.

**Comment by raymond91125** [comment]
That makes sense.
@pgaudet do you have concern about a secondary differentiation IS_A cell differentiation?

**Comment by raymond91125** [comment]
The revised definition is: "The process in which an activated T cell acquires specialized features of an exhausted T cell".

**Comment by nana-amazs** [comment]
Ok that's great!

**Comment by pgaudet** [comment]
Hi @raymond91125 

You ask 
> do you have concerns about a secondary differentiation IS_A cell differentiation?

The definition of 'cell differentiation' starts with "The cellular developmental process in which a relatively unspecialized cell,...", so that seems inconsistent to me. As I mentioned this seems rather a response to stress than a differentiation program.

**Comment by raymond91125** [comment]
1. I think the ***relatively*** unspecialized cell is the "activated T cell" in the definition. I think differentiation does not always start from a totally naive cell.
2. exhausted T cell is a defined cell type in CL.
3. I think it is appropriate to model this primarily as an immune system process. Perhaps a secondary parentage could be part of the response to stress although the stressors are complex. But then perhaps much of the immune system is about responses to stress as well.

**Comment by raymond91125** [comment]
Term pulled in. We can re-open this ticket if needed. Thanks.
