### ISSUE TITLE
enoyl-[acyl-carrier-protein] reductase activity (GO:0016631) terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25699]
Currently we have this:
```
|_enoyl-[acyl-carrier-protein] reductase activity (GO:0016631) [no EC/RHEA] [20 EXP annot.]
    |_enoyl-[acyl-carrier-protein] reductase (NADPH, A-specific) activity (GO:0047117) [EC:1.3.1.39/no RHEA] [1 EXP annot.]
    |_enoyl-[acyl-carrier-protein] reductase (NADPH, B-specific) activity (GO:0004319) [EC:1.3.1.10/no RHEA] [2 EXP annot.]
    |_enoyl-[acyl-carrier-protein] reductase (NADH) activity (GO:0004318) [EC:1.3.1.9/RHEA:10240] [17 EXP annot.]
```

Some changes are required here to better align with EC/RHEA.  I think the tree/terms should change either to this:
```
|_enoyl-[acyl-carrier-protein] reductase (NAD(P)H) activity (GO:0016631) [no EC/RHEA]
    |_enoyl-[acyl-carrier-protein] reductase (NADPH) activity (NTR) [EC:1.3.1.104/RHEA:22564] -> replaces GO:0047117 & GO:0004319
    |_enoyl-[acyl-carrier-protein] reductase (NADH) activity (GO:0004318) [EC:1.3.1.9/RHEA:10240]

```

or this:
```
|_enoyl-[acyl-carrier-protein] reductase (NAD(P)H) activity (GO:0016631) [no EC/RHEA]
    |_enoyl-[acyl-carrier-protein] reductase (NADPH) activity (NTR) [EC:1.3.1.104/RHEA:22564]
        |_enoyl-[acyl-carrier-protein] reductase (NADPH, A-specific) activity (GO:0047117) [EC:1.3.1.39/RHEA:22564]
        |_enoyl-[acyl-carrier-protein] reductase (NADPH, B-specific) activity (GO:0004319) [EC:1.3.1.10/nRHEA:22564]
    |_enoyl-[acyl-carrier-protein] reductase (NADH) activity (GO:0004318) [EC:1.3.1.9/RHEA:10240]

```

So the tasks here would be:

- [x] Tweak GO:0016631 term name: "enoyl-[acyl-carrier-protein] reductase activity" -> "enoyl-[acyl-carrier-protein] reductase (NAD(P)H) activity"
- [x] add new GO term for EC:1.3.1.104/RHEA:22564 - either as grouping term for GO:0047117 & GO:0004319, or replacing those two terms (note all three correspond to RHEA:22564)
- [ ] change definitions of GO:0047117, GO:0004319 and GO:0004318 to match EC/RHEA defs.  Consider including EC comments about different reactions occurring in bacteria/yeast/mammals?

I'll copy the relevant EC and GO entries below:

**EC 1.3.1.104 (no GO) = RHEA:22564 (NADPH, mammals/yeast)**
Accepted Name: enoyl-[acyl-carrier-protein] reductase
Alternative Name(s): acyl-ACP dehydrogenase, enoyl-ACP reductase
Reaction catalysed: a 2,3-saturated acyl-[ACP] + NADP(+) <=> a (2E)-enoyl-[ACP] + H(+) + NADPH
Comment(s): The enzyme completes each cycle of fatty acid elongation by catalyzing the stereospecific reduction of the double bond at position 2 of a growing fatty acid chain, while linked to the acyl- carrier protein, in an NADPH-dependent manner. This entry stands for enzymes whose stereo-specificity with respect to NADP(+) is not known (cf. EC 1.3.1.39, EC 1.3.1.10 and EC 1.3.1.9).

**EC 1.3.1.39 = GO:0047117 = RHEA:22564 (NADPH, mammals)**
Accepted Name: enoyl-[acyl-carrier-protein] reductase (NADPH, Re-specific)
Alternative Name(s): acyl-ACP dehydrogenase, enoyl-[acyl-carrier-protein] reductase (NADPH, A-specific)
Reaction catalysed: a 2,3-saturated acyl-[ACP] + NADP(+) <=> a (2E)-enoyl-[ACP] + H(+) + NADPH
Comment(s): This enzyme completes each cycle of fatty acid elongation by catalyzing the stereospecific reduction of the double bond at position 2 of a growing fatty acid chain, while linked to an acyl- carrier protein. It is one of the activities of EC 2.3.1.85. The mammalian enzyme is Re-specific with respect to NADP(+) (cf. EC 1.3.1.10 and and EC 1.3.1.104). 

**EC 1.3.1.10 = GO:0004319 = RHEA:22564 (NADPH, yeast)**
Accepted Name: enoyl-[acyl-carrier-protein] reductase (NADPH, Si-specific)
Alternative Name(s): acyl-ACP dehydrogenase, enoyl-ACP reductase, enoyl acyl-carrier-protein reductase, NADPH 2-enoyl Co A reductase
Reaction catalysed: a 2,3-saturated acyl-[ACP] + NADP(+) <=> a (2E)-enoyl-[ACP] + H(+) + NADPH
Comment(s): One of the activities of EC 2.3.1.86, an enzyme found in yeasts (Ascomycota and the Basidiomycota). Catalyzes the reduction of enoyl-acyl-[acyl-carrier protein] derivatives of carbon chain length from 4 to 16. The yeast enzyme is Si-specific with respect to NADP(+). cf. EC 1.3.1.39 and EC 1.3.1.104 which describes enzymes whose stereo- specificity toward NADPH is not known. See also EC 1.3.1.9. 

**EC 1.3.1.9 = GO:0004318 = RHEA:10240 (NADH, bacteria)**
Accepted Name: enoyl-[acyl-carrier-protein] reductase (NADH)
Alternative Name(s): enoyl-ACP reductase, NADH-enoyl acyl carrier protein reductase, NADH-specific enoyl-ACP reductase
Reaction catalysed: a 2,3-saturated acyl-[ACP] + NAD(+) <=> a (2E)-enoyl-[ACP] + H(+) + NADH
Comment(s): The enzyme catalyzes an essential step in fatty acid biosynthesis, the reduction of the 2,3-double bond in enoyl-acyl-[acyl-carrier- protein] derivatives of the elongating fatty acid moiety. The enzyme from the bacterium Escherichia coli accepts substrates with carbon chain length from 4 to 18. The FAS-I enzyme from the bacterium Mycobacterium tuberculosis prefers substrates with carbon chain length from 12 to 24 carbons. 

**id: GO:0016631**
name: enoyl-[acyl-carrier-protein] reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + NAD(P)+ = trans-2,3-dehydroacyl-[acyl-carrier protein] + NAD(P)H + H+." [GOC:rb]
synonym: "enoyl-[acyl-carrier protein] reductase activity" EXACT []
synonym: "enoyl-ACP reductase activity" EXACT []
synonym: "enoyl-acyl carrier protein reductase" EXACT []
xref: MetaCyc:1.3.1.10-RXN
xref: MetaCyc:1.3.1.39-RXN
xref: MetaCyc:RXN1G-2527
xref: MetaCyc:RXN1G-2544
xref: MetaCyc:RXN1G-3232
xref: MetaCyc:RXN1G-3256
xref: MetaCyc:RXN1G-3613
xref: MetaCyc:RXN1G-3641
xref: MetaCyc:RXN1G-3667
xref: MetaCyc:RXN1G-3993
xref: MetaCyc:RXN1G-4140
xref: MetaCyc:RXN1G-45
xref: Wikipedia:Enoyl-acyl_carrier_protein_reductase
is_a: GO:0016628 ! oxidoreductase activity, acting on the CH-CH group of donors, NAD or NADP as acceptor
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25307" xsd:anyURI

**id: GO:0047117**
name: enoyl-[acyl-carrier-protein] reductase (NADPH, A-specific) activity
namespace: molecular_function
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + NADP+ = trans-D2-enoyl-[acyl-carrier protein] + NADPH + H+." [EC:1.3.1.39, MetaCyc:1.3.1.39-RXN]
synonym: "acyl-acyl-carrier-protein:NADP+ oxidoreductase (A-specific)" RELATED [EC:1.3.1.39]
synonym: "enoyl-[acyl-carrier protein] reductase (NADPH, A-specific) activity" EXACT []
synonym: "enoyl-ACP reductase (NADPH, A-specific) activity" EXACT []
synonym: "enoyl-ACp reductase activity" RELATED [EC:1.3.1.39]
synonym: "enoyl-acyl carrier protein (reduced nicotinamide adenine dinucleotide phosphate) reductase activity" RELATED [EC:1.3.1.39]
synonym: "enoyl-acyl-carrier-protein reductase (NADPH, A-specific)" RELATED [EC:1.3.1.39]
xref: EC:1.3.1.39
xref: MetaCyc:1.3.1.39-RXN
is_a: GO:0016631 ! enoyl-[acyl-carrier-protein] reductase activity

**id: GO:0004319**
name: enoyl-[acyl-carrier-protein] reductase (NADPH, B-specific) activity
namespace: molecular_function
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + NADP+ = trans-2,3-dehydroacyl-[acyl-carrier protein] + NADPH + H+." [EC:1.3.1.10]
synonym: "acyl-acyl-carrier-protein:NADP+ oxidoreductase (B-specific)" RELATED [EC:1.3.1.10]
synonym: "enoyl acyl-carrier-protein reductase activity" RELATED [EC:1.3.1.10]
synonym: "enoyl-[acyl-carrier protein] reductase (NADPH, B-specific) activity" EXACT []
synonym: "enoyl-ACP reductase (NADPH, B-specific) activity" EXACT []
synonym: "enoyl-acyl-carrier-protein reductase (NADPH, B-specific)" RELATED [EC:1.3.1.10]
synonym: "enoyl-acyl-carrier-protein reductase (NADPH2, B-specific)" RELATED [EC:1.3.1.10]
synonym: "NADPH 2-enoyl Co A reductase activity" RELATED [EC:1.3.1.10]
synonym: "reductase, enoyl-acyl carrier protein (reduced nicotinamide adenine dinucleotide phosphate)" RELATED [EC:1.3.1.10]
xref: EC:1.3.1.10
xref: MetaCyc:ENOYL-ACP-REDUCT-NADPH-RXN
is_a: GO:0016631 ! enoyl-[acyl-carrier-protein] reductase activity

**id: GO:0004318**
name: enoyl-[acyl-carrier-protein] reductase (NADH) activity
namespace: molecular_function
def: "Catalysis of the reaction: acyl-[acyl-carrier protein] + NAD+ = trans-2,3-dehydroacyl-[acyl-carrier protein] + NADH + H+." [EC:1.3.1.9]
synonym: "acyl-acyl-carrier-protein:NAD+ oxidoreductase" RELATED [EC:1.3.1.9]
synonym: "enoyl-[acyl-carrier protein] reductase (NADH) activity" RELATED [EC:1.3.1.9]
synonym: "enoyl-ACP reductase (NADH) activity" RELATED [EC:1.3.1.9]
synonym: "enoyl-acyl-carrier-protein reductase (NADH)" RELATED [EC:1.3.1.9]
synonym: "NADH-enoyl acyl carrier protein reductase activity" RELATED [EC:1.3.1.9]
synonym: "NADH-specific enoyl-ACP reductase activity" RELATED [EC:1.3.1.9]
xref: EC:1.3.1.9
xref: MetaCyc:ENOYL-ACP-REDUCT-NADH-RXN
xref: RHEA:10240
is_a: GO:0016631 ! enoyl-[acyl-carrier-protein] reductase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25307" xsd:anyURI

**Comment by Antonialock** [comment]
Thanks Steven, I have annotated to the parent GO:0016631 and will update MECR human and bovine Q9BV79 Q7YS70 with term corresponding to EC:1.3.1.104. when available.

**Comment by Antonialock** [comment]
or EC:1.3.1.39?

**Comment by Antonialock** [comment]
I asked Kristian for advise and he says
"
It is true that EC 1.3.1.39 was created to describe mammlian fatty acid
synthase (FAS_MOUSE), but MECR is a mitochondrial protein, so I think EC
1.3.1.104 is a better match in this case. EC 1.3.1.104 has also been used for
plant and fungal mitochondrial Enoyl-[acyl-carrier-protein] reductase."

**Comment by Antonialock** [comment]
so I think I will need a term created corresponding to EC 1.3.1.104 ? If someone could create it?

**Comment by pgaudet** [comment]
Thanks for the ping @Antonialock 

> enoyl-[acyl-carrier-protein] reductase (NADPH, A-specific) activity (GO:0047117) [EC:1.3.1.39/no RHEA] [1 EXP annot.]
 and enoyl-[acyl-carrier-protein] reductase (NADPH, B-specific) activity (GO:0004319) [EC:1.3.1.10/no RHEA] [2 EXP annot.]

As far as I can tell, the stereospecificity of the NADP should be outside the scope of GO. Also, RHEA descibes this as a single reaction. 
So, I propose we obsolete these two terms. 

The correct activity is indeed 1enoyl-[acyl-carrier-protein] reductase (NADPH) activity (NTR) [EC:1.3.1.104/RHEA:22564]', so I will create a new term for this and this new term will replace enoyl-[acyl-carrier-protein] reductase (NADPH, A-specific) activity (GO:0047117) and enoyl-[acyl-carrier-protein] reductase (NADPH, B-specific) activity (GO:0004319)

> GO:0016631 term name: "enoyl-[acyl-carrier-protein] reductase activity" -> "enoyl-[acyl-carrier-protein] reductase (NAD(P)H) activity"

I will change the label as suggested by @sjm41 , and add DO NOT ANNOTATE to this term, since it should be annotated to either NAD or NADP; again, as far as I can tell, enzymes are specific for either (see guidelines on NAD/NADP here: https://wiki.geneontology.org/Guidelines_for_new_Molecular_Functions#NAD/NADP_cofactors

Hopefully this works? 

Thanks, Pascale

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141148
+name: enoyl-[acyl-carrier-protein] reductase (NADPH) activity
+namespace: molecular_function
+def: "Catalysis of the reaction: a 2,3-saturated acyl-[ACP] + NADP+ = a (2E)-enoyl-[ACP] + H+ + NADPH." [RHEA:22564]
+xref: EC:1.3.1.10 {source="skos:narrowMatch"}
+xref: EC:1.3.1.104 {xref="skos:exactMatch"}
+xref: EC:1.3.1.39 {xref="skos:narrowMatch"}
+xref: RHEA:22564
+is_a: GO:0016631 ! enoyl-[acyl-carrier-protein] reductase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25699" xsd:anyURI
+created_by: pg
+creation_date: 2024-01-29T11:56:59Z
+

**Comment by pgaudet** [comment]
[enoyl-[acyl-carrier-protein] reductase (NADH) activity](http://purl.obolibrary.org/obo/GO_0004318): 
- edited definition to match RHEA's: Catalysis of the reaction: a 2,3-saturated acyl-[ACP] + NAD+ = a (2E)-enoyl-[ACP] + H+ +
 NADH." [RHEA:10240]
