### ISSUE TITLE
NTR snRNA 2'-O-ribose methyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25706]
we have
snRNA 2'-O-ribose methylation guide activity
and
U6 2'-O-snRNA methylation
but not
~snRNA 2'-O-ribose methyltransferase activity~

U6 snRNA 2'-O-ribose methyltransferase activity

(seems to be catalysed by fibrillarin:
The observed interaction between Bmc1 and snoZ30, coupled with the recently described function of mammalian LARP7 in facilitating snoRNA-guided 2′-O-methylation of U6 by the methyltransferase fibrillarin (26,27) provided initial clues as to the function of this new Bmc1- and U6-containing snRNP. 

and
see 
https://www.uniprot.org/uniprotkb/P22087/entry
Site specificity is provided by a guide RNA that base pairs with the substrate (By similarity).
Methylation occurs at a characteristic distance from the sequence involved in base pairing with the guide RNA (By similarity).
Probably catalyzes 2'-O-methylation of U6 snRNAs in box C/D RNP complexes (PubMed:[32017898](https://www.uniprot.org/citations/32017898)).
U6 snRNA 2'-O-methylation is required for mRNA splicing fidelity (PubMed:[32017898](https://www.uniprot.org/citations/32017898)).

**Comment by ValWood** [comment]
I'm checking 
PMID:37403782
Title | The fission yeast methyl phosphate capping enzyme Bmc1 guides 2'-O-methylation of the U6 snRNA.

**Comment by ValWood** [comment]
We need to decide on a specificity for these terms

There are existing residue specific U6 terms:

GO:0120048 | U6 snRNA (adenine-(43)-N(6))-methyltransferase activity | IMP | Pendleton KE et al. (2017)

but this residue is A37 in fission yeast:
S. pombe U6 residue A41 is 2’-O- methylated and is equivalent to human A47.
S. pombe U6 residue A64 is 2’-O- methylated and is equivalent to human A70.  
S. pombe U6 residue A37 is m6A methylated and is equivalent to human A43 

What should we do? We need to decide the appropriate level of specificity for modifications where residues are conserved, but not their absolute positions.

We could use the terms I guess, if it was really clear that the positions were human numbering...


[GO:0120048](https://www.pombase.org/term/GO:0120048)	
[U6 snRNA (adenine-(43)-N(6))-methyltransferase activity](https://www.pombase.org/term/GO:0120048)
[IMP](http://wiki.geneontology.org/index.php/Inferred_from_Mutant_Phenotype_(IMP))	[Pendleton KE et al. (2017)](https://www.pombase.org/reference/PMID:28525753)

**Comment by ValWood** [comment]
snRNA 2'-O-ribose methyltransferase activity
parent will be
GO:0062105   RNA 2'-O-methyltransferase activity

For not I will capture residues locally at PomBAse with residue = A43 etc, otherwise naming will be too complicated. We can add later if there is some community consensus.

**Comment by pgaudet** [comment]
Hi @ValWood 
The definition for GO:0180021 snRNA 2'-O-ribose methyltransferase activity seems wrong: 


> Catalysis of the reaction: S-adenosyl-L-methionine + snRNA = S-adenosyl-L-homocysteine + tRNA containing a 2'-O-nucleotide.

- tRNA is inconsistent with the term label
- there is no methyl group in the product
- are there any ECs or RHEAs for this term? https://www.rhea-db.org/rhea/63088 ? 
- but RHEA mentions U6... 
-

**Comment by ValWood** [comment]
It should be
U6 snRNA 2'-O-ribose methyltransferase activity

I couldn't find the docs how to do correct Rhea definition alignment (I think this is one of the only enzymes I have added)?.

I copied a sibling and did
Catalysis of the reaction: S-adenosyl-L-methionine + U6 snRNA = S-adenosyl-L-homocysteine + U6 containing a 3'-terminal 2'-O-methylnucleotide + H+.
