### ISSUE TITLE
GO entry terms are URLs

### ISSUE THREAD

**Issue by mirandajarnot** [geneontology/go-ontology#25708]
## Describe the issue/bug  
We have just inserted GO (data from 05_10_2023) into the Unified Medical Language System (UMLS) and found three GO ETs that are URLs instead of text strings.  

## Expected behavior
Are these strings legitimate ETs within the GO data, or are these mistakes?

## To Reproduce
[https://github.com/geneontology/go-ontology/issues/21791](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgeneontology%2Fgo-ontology%2Fissues%2F21791&data=05%7C01%7Cjarnotm%40mail.nlm.nih.gov%7C2313e9fe426949df36ec08db8127be96%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638245779957839839%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5Kq4JK%2BeokzpMbqxg9ZwP00NpovlMppVg%2F6ppd3L2aQ%3D&reserved=0) [GO2023_05_10/ET/[GO:0004303](https://unimed2.nlm.nih.gov/cgi-bin/ems3-concept-report-mid.pl?action=searchbycode&db=mid_prod&arg=GO:0004303)]

[https://github.com/geneontology/go-ontology/issues/24479](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgeneontology%2Fgo-ontology%2Fissues%2F24479&data=05%7C01%7Cjarnotm%40mail.nlm.nih.gov%7C2313e9fe426949df36ec08db8127be96%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638245779957839839%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AJ7cCeG599kuVm7fDA%2BTY7Y2LN0FtPdKkVkPojVYUio%3D&reserved=0) [GO2023_05_10/ET/[GO:0099099](https://unimed2.nlm.nih.gov/cgi-bin/ems3-concept-report-mid.pl?action=searchbycode&db=mid_prod&arg=GO:0099099)]

[https://github.com/geneontology/go-ontology/issues/24269](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgeneontology%2Fgo-ontology%2Fissues%2F24269&data=05%7C01%7Cjarnotm%40mail.nlm.nih.gov%7C2313e9fe426949df36ec08db8127be96%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638245779957996118%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eFzhb1kDHvqRW4oSaen5xFF%2FtXUGTxgeLb%2BWUrkAxlE%3D&reserved=0) [GO2023_05_10/OET/[GO:0046855](https://unimed2.nlm.nih.gov/cgi-bin/ems3-concept-report-mid.pl?action=searchbycode&db=mid_prod&arg=GO:0046855)]

Thanks,
Miranda Jarnot, UMLS Source Coordinator

**Comment by pgaudet** [comment]
Dear @mirandajarnot

Thank you for reporting this, I have now fixed the issues. 

Best regards, 

Pascale

@suzialeksander
