### ISSUE TITLE
RNA trimethylguanosine synthase activity (GO:0071164)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25717]
RNA trimethylguanosine synthase activity (GO:0071164) is the combination of RHEA:67620 + RHEA:67624.
E.g. see https://www.uniprot.org/uniprotkb/Q96RS0/entry

I'm not sure if we can put both those RHEAs as xrefs on GO:0071164, or if we'd need to create separate GO terms?

id: GO:0071164
name: RNA trimethylguanosine synthase activity
namespace: molecular_function
def: "Catalysis of two successive methyl transfer reactions from AdoMet to the N-2 atom of guanosine, thereby converting 7-methylguanosine in an RNA cap to 2,2,7 trimethylguanosine." [GOC:BHF, PMID:11983179, PMID:18775984]
synonym: "cap hypermethylase activity" EXACT [PMID:11983179]
synonym: "small nuclear RNA methyltransferase activity" RELATED [GOC:rl]
synonym: "snRNA methyltransferase activity" RELATED [GOC:rl]
is_a: GO:0008173 ! RNA methyltransferase activity
relationship: part_of GO:0036261 ! 7-methylguanosine cap hypermethylation
created_by: mah
creation_date: 2009-11-19T03:23:20Z

**Comment by pgaudet** [comment]
Yes, we can put 2 xrefs, see https://wiki.geneontology.org/Guidelines_for_database_cross_references

**Comment by edwong57** [comment]
https://github.com/geneontology/go-ontology/pull/25826 Fixed this issue

**Comment by sjm41** [comment]
Thanks @edwong57 But the latest pull request puts the two RHEA IDs as synonyms rather than as xrefs.  I think @pgaudet was saying we could put these both as xrefs?

**Comment by edwong57** [comment]
@sjm41 Apologies. Fixing it now.

**Comment by sjm41** [comment]
Thanks @edwong57 !

**Comment by pgaudet** [comment]
Just wondering, shouldn't the RHEA be 'narrow' rather than 'broad'? ie I think they represent each of the 2 successive steps, while the GO reaction represents the two steps in a single term?

**Comment by sjm41** [comment]
Yes, @pgaudet, you're right.
