### ISSUE TITLE
GO:0070735 protein-glycine ligase activity - add RHEA xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25720]
I think RHEA:67180 https://www.rhea-db.org/rhea/67180 can be added as an xref to GO:0070735.
Definition could also be updated to match RHEA.

id: GO:0070735
name: protein-glycine ligase activity
namespace: molecular_function
def: "Catalysis of the posttranslational transfer of one or more glycine residues to a specific glutamate residue on a target protein." [GOC:mah, PMID:19524510]
synonym: "protein glycylase activity" EXACT [GOC:mah]
is_a: GO:0016881 ! acid-amino acid ligase activity
is_a: GO:0140096 ! catalytic activity, acting on a protein
created_by: mah
creation_date: 2009-06-19T01:51:21Z

**Comment by ValWood** [comment]
ATP + glycine + L-glutamyl-[protein] = ADP + glycyl-L-glutamyl-[protein] + H+ + phosphate

**Comment by sjm41** [comment]
Thanks Val for fixing this (and the other tickets)!

For this one, I think you omitted the standard "Catalysis of the reaction: " prefix on the def?

**Comment by ValWood** [comment]
Yeah, I did miss it but it got fixed in the next commit. I realised after  your comment in the other ticket.
