### ISSUE TITLE
Missing parent: GO:0035621	 ER to Golgi ceramide transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25729]
* **GO term ID and label for which you request a new superclass**

GO:0035621 | ER to Golgi ceramide transport

* **New superclass (parent) suggested**
@pgaudet  do you think we could add a "membrane organization" parent to this. Maybe the term should refer  specifically to membrane ceramide (I have  a few annotations to GO:0035621 | ER to Golgi ceramide transport and they do not slim)

* **Reference(s), if appropriate**
PMID:nnnnnnn

will dig out tomorrow

**Comment by ValWood** [comment]
i.e.

The directed movement of a ceramide from the endoplasmic reticulum   (ER) **membrane** to the Golgi **membrane**. Ceramides are a class of **membrane** lipids composed of sphingosine linked to a fatty acid.

**Comment by ValWood** [comment]
@pgaudet  let me know what you think here.
v

**Comment by ValWood** [comment]
My understanding of this term is it is the  about the trafficking of ceramide that is already in the ER membrane into the Golgi. So I thought from this that because it will always be altering membrane composition of the 2 compartments, membrane organization would always be true ....but it might not be appropriate. 

We don't handle "membrane trafficking" very well (there is no term for this in GO).

**Comment by ValWood** [comment]
actually I just looked at the reference associated with the term
https://europepmc.org/article/MED/14685229

Synthesis and sorting of lipids are essential for membrane biogenesis; however, the mechanisms underlying the transport of membrane lipids remain little understood. Ceramide is synthesized at the endoplasmic reticulum and translocated to the Golgi compartment for conversion to sphingomyelin. The main pathway of ceramide transport to the Golgi is genetically impaired in a mammalian mutant cell line, LY-A. Here we identify CERT as the factor defective in LY-A cells. CERT, which is identical to a splicing variant of Goodpasture antigen-binding protein, is a cytoplasmic protein with a phosphatidylinositol-4-monophosphate-binding (PtdIns4P) domain and a putative domain for catalysing lipid transfer. In vitro assays show that this lipid-transfer-catalysing domain specifically extracts ceramide from phospholipid bilayers. CERT expressed in LY-A cells has an amino acid substitution that destroys its PtdIns4P-binding activity, thereby impairing its Golgi-targeting function. We conclude that CERT mediates the intracellular trafficking of ceramide **in a non-vesicular manner.**

So this isn't trafficking.

Discussion:
We have presented genetic and biochemical evidence that CERT is
central to ceramide-selective transport during the synthesis of SM.
To our knowledge, our study is the first example of the molecular
identification of a specific lipid-sorting factor that operates in the
synthesis of membrane phospholipids. For the transport of ceramide from the ER to the Golgi, CERT has two suitable domains: the
START domain, which specifically recognizes ceramide and mediates the intermembrane transfer of ceramide; and the PH domain,
which can target the Golgi apparatus where several types of PtdIns4-OH kinase are localized24,25. In addition, the MR domain of CERT
contains a motif for targeting the ER26.


This paper appears to be describing ceramide translocation, in which case it should merge with

GO:0099040   
ceramide translocation
The movement of a ceramide molecule from one leaflet of a membrane bilayer to the opposite leaflet.

This is a child of membrane organization so it would have the desired result, my annotation would be slimmed to membrane organization!

**Comment by ValWood** [comment]
I realize these are single steps.
Presumable eventually they will be curated as
"ER to Golgi ceramide transfer activity (does not exist) part_of membrane organization?

**Comment by pgaudet** [comment]
could be - most terms for ceramide transport are not convincing BPs... 
GO:0035627 ceramide transport
-  [GO:1902389 ceramide 1-phosphate transport](https://amigo.geneontology.org/amigo/term/GO:1902389#display-lineage-tab)
- [GO:0099040 ceramide translocation](https://amigo.geneontology.org/amigo/term/GO:0099040#display-lineage-tab)
-  [GO:0035621 ER to Golgi ceramide transport](https://amigo.geneontology.org/amigo/term/GO:0035621#display-lineage-tab)
-  [GO:1905572 ganglioside GM1 transport to membrane](https://amigo.geneontology.org/amigo/term/GO:1905572#display-lineage-tab)

For me ideally to be a BP we would at least need to say that its transmembrane (or what it is). Just x transport really does sound like a MF. 

Is there an immediate issues you're trying to solve? It seems like you'd like more biological context to that term?

**Comment by ValWood** [comment]
Closing, I would not to where to begin reorganizing and this should be covered by a larger review.
For the record most of the annotations appear to be to lipid transfer activity proteins (which would make this an intermembrane transport)
