### ISSUE TITLE
DO not annotate category appear as "SLIM"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25738]

**Comment by ValWood** [comment]
see



2023-06-13 | Added | SLIM | gocheck_do_not_annotate
https://www.ebi.ac.uk/QuickGO/term/GO:0018343#termHistory

Is that intentional.
Spotted here:
https://github.com/PHI-base/data/issues/15#issuecomment-1632190617

**Comment by pgaudet** [comment]
Yes, all subsets (slims) are treated the same way. 

Maybe we can ask QuickGO not to load the subsets that start with 'gocheck'? 

http://release.geneontology.org/2023-06-11/ontology/subsets/index.html

**Comment by ValWood** [comment]
But then curators using QuickGO would not see the "do not annotate" comment and that was the reason for adding, to prevent new annotations.
Maybe it's OK as it is. It is more of a labelling issue it seems (SUBSET would be better than slim?), but I doubt that many people would notice this.

**Comment by pgaudet** [comment]
So, is your request for QuickGO to change the label from 'GO slims'  to 'GO subsets'?

**Comment by ValWood** [comment]
I guess that would be the solution. It is a bit confusing to label them all SLIM
@alexsign

**Comment by pgaudet** [comment]
I emailed the QuickGO helpdesk. I'll follow up with Alex.
