### ISSUE TITLE
NTR: hypoxia-inducible factor-proline dioxygenase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25739]
* **Suggested term label:**
hypoxia-inducible factor-proline dioxygenase activity

* **Definition (free text)**
Catalysis of the reaction: 2-oxoglutarate + L-prolyl-[hypoxia-inducible factor alpha subunit] + O2 <=> CO2 + succinate + trans-4-hydroxy-L-prolyl-[hypoxia-inducible factor alpha subunit]

* **Reference, in format PMID:#######**
PMID: 11595184
PMID: 11598268

* **Gene product name and ID to be annotated to this term**
Examples:
-- fly Hph (FBgn0264785/Q8SX21)
-- human EGLN1/EGLN2/EGLN3 (Q9GZT9/Q96KS0/Q9H6Z9) & P4HTM (Q9NXG6)

* **Parent term(s)**
peptidyl-proline 4-dioxygenase activity (GO:0031545)

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
HIF hydroxylase [BROAD]
HIF prolyl hydroxylase [EXACT]

* **Cross-references**
EC 1.14.11.29, RHEA:48400

* **Any other information**
This similarly substrate-specific "sister" term already exists:
id: GO:0004656
name: procollagen-proline 4-dioxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: procollagen L-proline + 2-oxoglutarate + O2 = procollagen trans-4-hydroxy-L-proline + 
xref: EC:1.14.11.2
xref: KEGG_REACTION:R03219
xref: MetaCyc:1.14.11.2-RXN
xref: RHEA:18945
is_a: GO:0019798 ! procollagen-proline dioxygenase activity
is_a: GO:0031545 ! peptidyl-proline 4-dioxygenase activity

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160082
+name: hypoxia-inducible factor-proline dioxygenase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: 2-oxoglutarate + L-prolyl-[hypoxia-inducible factor alpha subunit] + O2 = CO2 + succinate + trans-4-hydroxy-L-prolyl-[hypoxia-inducible factor alpha subunit]" [PMID:11595184, PMID:11598268]
+synonym: "HIF hydroxylase" BROAD []
+synonym: "HIF prolyl hydroxylase" EXACT []
+xref: EC:1.14.11.29
+xref: RHEA:48400
+is_a: GO:0031545 ! peptidyl-proline 4-dioxygenase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25739" xsd:anyURI
+created_by: rynl
+creation_date: 2023-07-13T17:38:59Z

**Comment by sjm41** [comment]
Thanks Raymond!
