### ISSUE TITLE
Obsoletion notice: GO:0001505 regulation of neurotransmitter levels, GO:0045213 neurotransmitter metabolic process & related terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25736]
Following up on #25594

The ontology editors have proposed to obsolete:

- GO:0001505 regulation of neurotransmitter levels
- GO:0045213 neurotransmitter metabolic process
- GO:0042136 neurotransmitter biosynthetic process
- GO:0042135 neurotransmitter catabolic process
- GO:0045213 neurotransmitter receptor metabolic process
- GO:0097019 neurotransmitter receptor catabolic process
- GO:0042165 neurotransmitter binding

There are 53 EXP annotations to these terms, 2 InterPro, 2 SPKW, and 1 UniRule mapping, see

https://github.com/geneontology/go-annotation/issues/4675

The reason for obsoletion is that 'neurotransmitter' is unnecessary grouping in the metabolism branch of the ontology, and it creates true path violations.

**Comment by deustp01** [comment]
> * GO:0045213 neurotransmitter metabolic process

Typo? Should be **GO:0042133** neurotransmitter metabolic process?

**Comment by sandraorchard** [comment]
Can I just check - will 
GO:0042166                acetylcholine binding 
GO:0031626                beta-endorphin binding

remain. Is it just the parent GO:0042165 neurotransmitter binding which is going.
Sandra

**Comment by raymond91125** [comment]
> Can I just check - will GO:0042166 acetylcholine binding GO:0031626 beta-endorphin binding
> 
> remain. Is it just the parent GO:0042165 neurotransmitter binding which is going. Sandra

That's correct.

**Comment by raymond91125** [comment]
Should these be obsoleted along with neurotransmitter metabolic process?
GO:0045213 neurotransmitter receptor metabolic process
GO:0097019 neurotransmitter receptor catabolic process
GO:0042165 neurotransmitter binding

**Comment by raymond91125** [comment]
Neurotransmitter binding, yes. But I thought the receptor metabolic process would not create true path violations. I am not aware that there are receptors general metabolites and exist in organisms that lack a nervous system.

**Comment by pgaudet** [comment]
> But I thought the receptor metabolic process would not create true path violations. 

Yes it does, this was the original problem reported in https://github.com/geneontology/go-ontology/issues/25594

**Comment by raymond91125** [comment]
I thought #25594 was about the metabolism of neurotransmitters, not neurotransmitter receptors.

**Comment by pgaudet** [comment]
I think all these terms have the same issues, we might as well handle all of them at the same time.

**Comment by raymond91125** [comment]
obsoletion email sent
