### ISSUE TITLE
NTR: sperm migration through the uterotubal junction

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#25732]
Please provide as much information as you can: 

* **Suggested term label:**
sperm migration through the uterotubal junction

* **Definition (free text)**
The controlled self-propelled movement of a sperm cell from the uterus through the uterotubal junction (UTJ) into the oviduct, where interaction between the sperm and the UTJ acts as a major selective barrier for sperm, allowing only living, motile, uncapacitated, morphologically normal sperm with intact acrosomes to pass from the uterus into the oviduct.

* **Reference, in format PMID:#######**
[GOC:krc, PMID:34057175, PMID:32712384, PMID:31131960, PMID:29353867]

* **Gene product name and ID to be annotated to this term**
mouse genes: Ace, Adam1a, Adam2, Adam3, Calr3, Clgn, cystatin, Ly6k, Lypd4, Pdilt, Pgap1, Pmis2, Prss37, Rnase10, TEx101, Tmprss12, Tpst2, Prss55, Pate (see Figure 1 in Mahé C, et al. Sperm migration, selection, survival, and fertilizing ability in the mammalian oviduct. 2021. PMID:34057175)

-- Regarding Lypd4, see Wang D, et al. **LYPD4, mouse homolog of a human acrosome protein, is essential for sperm fertilizing ability and male fertility.** Biol Reprod. 2020 Apr 24;102(5):1033-1044. PMID: 32040177.

-- Regarding Pdilt, see Tokuhiro K, et al. **Protein disulfide isomerase homolog PDILT is required for quality control of sperm membrane protein ADAM3 and male fertility** [corrected]. Proc Natl Acad Sci U S A. 2012 Mar 6;109(10):3850-5. PMID: 22357757 
--- also see this ticket because the equivalence axiom of the existing term "germ cell migration" is too broad and would incorrectly encompass the new term requested in this ticket
---   #25651 

* **Parent term(s)**
is_a: cell migration ! GO:0016477
part_of: multicellular organismal reproductive process ! GO:0048609
has_part: name: flagellated sperm motility ! GO:0030317 (I know that C. elegans have amoeboid sperm but since this term refers to the junction between the uterus and the oviduct, I think flagellated sperm motility is likely appropriate.

If it's possible to specify the start and end locations, these terms may be helpful:
-- uterus ! UBERON:0000995
-- oviduct ! UBERON:0000993

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

sperm migration through the UTJ - RELATED
sperm migration from the uterus to the oviduct - EXACT

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
Hi @krchristie 
I was wondering how this
GO:0097722 sperm motility (if at all?). They sound like 2 sides of the same coin.


Definition ([GO:0097722 GONUTS page](http://gowiki.tamu.edu/wiki/index.php/Category:GO:0097722))
Any process involved in the controlled movement of a sperm cell.

**Comment by krchristie** [comment]
> Hi @krchristie I was wondering how this GO:0097722 sperm motility (if at all?). They sound like 2 sides of the same coin.
> 
> Any process involved in the controlled movement of a sperm cell.

Hi @ValWood - I have submitted a ticket about the fact that "cell migration" is incorrectly classified as a type of "cell motility". For a moment, think about elephants, elephant motility is methods of motility, e.g. walking, running, swimming. Elephant migration is the annual pattern of movements guided by external signals like rainfall patterns, food availability, etc. For details on this issue within GO, please see my comments in the ticket:
- #25650 

Also, note that GO:0097722 "**sperm motility**" is broader than the specific motility term that I have suggested for a has_part relationship to the new term I am requesting: 

> has_part: name: flagellated sperm motility ! GO:0030317 (I know that C. elegans have amoeboid sperm but since this term refers to the junction between the uterus and the oviduct, I think flagellated sperm motility is likely appropriate.

Also worth checking this ticket since the current logical definition of "germ cell migration" is too broad for its definition which is specific to the migration of primordial germ cells within an embryo:
-   #25651

**Comment by raymond91125** [comment]
It is a sticky one as to where to place 'sperm migration through the uterotubal junction'. A key element in the def of cell migration is "guided by molecular cues". Usually cell migration involves instructive cues that guide the direction of movement of the motile cell. It appears that sperm migration (an adopted term in literature) involves a combination of motility of the sperm with the selective environment set up by the female reproductive tract (Wikipedia:Cell_migration). There does not seem to be a conventional, 'instructive' cue.
Thus, I am in favor of placing the term under (is_a) 'sperm motility' but keeping the proposed term label 'sperm migration through the uterotubal junction'. Is this good? @krchristie

**Comment by raymond91125** [comment]
[Term]
id: GO:0160131
name: sperm migration through the uterotubal junction
namespace: biological_process
def: "The controlled self-propelled movement of a sperm cell from the uterus through the uterotubal junction (UTJ) into the oviduct, where interaction between the sperm and the UTJ acts as a major selective barrier for sperm, allowing only living, motile, uncapacitated, morphologically normal sperm with intact acrosomes to pass from the uterus into the oviduct." [GOC:krc, PMID:29353867, PMID:31131960, PMID:32712384, PMID:34057175]
synonym: "sperm migration from the uterus to the oviduct" EXACT []
synonym: "sperm migration through the UTJ" RELATED []
is_a: GO:0016477 ! cell migration
relationship: has_part GO:0030317 ! flagellated sperm motility
relationship: part_of GO:0048609 ! multicellular organismal reproductive process
created_by: rynl
creation_date: 2023-12-09T01:02:52Z
