### ISSUE TITLE
Multiple GO terms with EC:2.4.1.173 xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25771]
The 4 GO terms shown below all have an EC:2.4.1.173 xref.
The first one (GO:0016906) is correct, though the definition could be updated to match EC/RHEA.
The other three are all use specific substrates, and represent three of the 18 more specific reactions shown on the [RHEA:22724](https://www.rhea-db.org/rhea/22724) (equivalent to EC:2.4.1.173) page. Only one of these three more specific GO terms has been used in an experimental annotation (to Dicty ugt52).

I think GO:0102202, GO:0102203 and GO:0102205 should be obsoleted.

id: GO:0016906
name: sterol 3-beta-glucosyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: UDP-glucose + a sterol = UDP + an O-glucosylsterol." [EC:2.4.1.173, RHEA:22724]
synonym: "sterol 3beta-glucosyltransferase activity" RELATED [EC:2.4.1.173]
synonym: "sterol glucosyltransferase activity" EXACT []
synonym: "sterol-beta-D-glucosyltransferase activity" RELATED [EC:2.4.1.173]
synonym: "sterol:UDPG glucosyltransferase activity" EXACT []
synonym: "UDP-glucose-sterol beta-glucosyltransferase activity" RELATED [EC:2.4.1.173]
synonym: "UDP-glucose-sterol glucosyltransferase activity" RELATED [EC:2.4.1.173]
synonym: "UDP-glucose:sterol 3-O-beta-D-glucosyltransferase activity" RELATED [EC:2.4.1.173]
synonym: "UDP-glucose:sterol glucosyltransferase activity" EXACT []
synonym: "UDPG-SGTase activity" RELATED [EC:2.4.1.173]
synonym: "UDPG:sterol glucosyltransferase activity" EXACT []
synonym: "UDPglucose:sterol 3-O-beta-D-glucosyltransferase activity" RELATED [EC:2.4.1.173]
synonym: "uridine diphosphoglucose-poriferasterol glucosyltransferase activity" RELATED [EC:2.4.1.173]
synonym: "uridine diphosphoglucose-sterol glucosyltransferase activity" RELATED [EC:2.4.1.173]
xref: EC:2.4.1.173
xref: MetaCyc:STEROL-GLUCOSYLTRANSFERASE-RXN
xref: RHEA:22724
is_a: GO:0035251 ! UDP-glucosyltransferase activity

id: GO:0102202
name: soladodine glucosyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: UDP-alpha-D-glucose + solasodine <=> UDP + solasodine 3-O-beta-D-glucopyranoside + H+." [EC:2.4.1.173, GOC:pz, RHEA:61844]
xref: EC:2.4.1.173
xref: MetaCyc:RXN-12123
xref: RHEA:61844
is_a: GO:0016758 ! hexosyltransferase activity

id: GO:0102203
name: brassicasterol glucosyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: UDP-alpha-D-glucose + brassicasterol <=> UDP(3-) + 3-O-beta-D-glucosyl-brassicasterol + H+." [EC:2.4.1.173, GOC:pz, RHEA:61840]
xref: EC:2.4.1.173
xref: MetaCyc:RXN-12125
xref: RHEA:61840
is_a: GO:0016758 ! hexosyltransferase activity

id: GO:0102205
name: cholesterol alpha-glucosyltransferase activity
namespace: molecular_function
alt_id: GO:0051505
def: "Catalysis of the reaction: UDP-alpha-D-glucose + cholesterol = UDP + cholesteryl beta-D-glucoside + H+." [GOC:pz, RHEA:61848]
synonym: "cholesterol allpha-glucosyltransferase activity" EXACT []
synonym: "cholesterol UDP-glucosyltransferase activity" RELATED []
xref: EC:2.4.1.173
xref: MetaCyc:RXN-12127
xref: RHEA:61848
is_a: GO:0016758 ! hexosyltransferase activity

**Comment by sjm41** [comment]
This was previously reported in #17949, where it was decided that having these multiple ECs was OK. However, I believe current policy is that we shouldn't do this.

@pgaudet I can remove the EC xref on the 3 more specific terms, but I think it would be better to obsolete those. What do you think? 

EC:2.4.1.173 is:
a sterol + UDP-alpha-D-glucose = a sterol 3-beta-D-glucoside + H(+) + UDP

**Comment by balhoff** [comment]
Boomer output:

![4cc335ebf712c5ed2cbdeecfbf61f4864aa347cf43de4bb0f8617a57ba65a694](https://github.com/geneontology/go-ontology/assets/210210/4a14fd24-8230-4bff-a2e2-3814a291669f)

@sjm41 the gray lines here indicate a subclass relationship stated by Rhea (not boomer proposals).

**Comment by pgaudet** [comment]
Looking at the annotations, the children of [sterol 3-beta-glucosyltransferase activity](http://purl.obolibrary.org/obo/GO_0016906) represent specific substrates: 
'beta-sitosterol UDP-glucosyltransferase activity'
'ergosterol UDP-glucosyltransferase activity'
'stigmasterol UDP-glucosyltransferase activity'
'tomatidine UDP-glucosyltransferase activity'

https://www.rhea-db.org/rhea/22724 has even more reactions: 

- [RHEA:66284](https://www.rhea-db.org/rhea/66284) tomatidine + UDP-α-D-glucose = H+ + tomatidine 3-O-β-D-glucopyranoside + UDP
- [RHEA:66280](https://www.rhea-db.org/rhea/66280) solanidine + UDP-α-D-glucose = H+ + solanidine 3-O-β-D-glucopyranoside + UDP
- [RHEA:66276](https://www.rhea-db.org/rhea/66276) tigogenin + UDP-α-D-glucose = H+ + tigogenin 3-O-β-D-glucopyranoside + UDP
- [RHEA:61944](https://www.rhea-db.org/rhea/61944) 24-methylenecholesterol + UDP-α-D-glucose = 24-methylene cholesteryl β-D-glucoside + H+ + UDP
- [RHEA:61940](https://www.rhea-db.org/rhea/61940) 3β-hydroxy-16α,17α-epoxypregnenolone + UDP-α-D-glucose = 3β-hydroxy-16α,17α-epoxypregnenolone 3-β-D-glucoside + H+ + UDP
- [RHEA:61888](https://www.rhea-db.org/rhea/61888) diosgenin + UDP-α-D-glucose = diosgenin 3-O-β-D-glucoside + H+ + UDP
- [RHEA:61852](https://www.rhea-db.org/rhea/61852) campesterol + UDP-α-D-glucose = campesteryl 3-β-D-glucoside + H+ + UDP
- [RHEA:61848](https://www.rhea-db.org/rhea/61848) cholesterol + UDP-α-D-glucose = cholesteryl 3-β-D-glucoside + H+ + UDP
- [RHEA:61844](https://www.rhea-db.org/rhea/61844) solasodine + UDP-α-D-glucose = H+ + solasodine 3-β-D-glucoside + UDP
- [RHEA:61840](https://www.rhea-db.org/rhea/61840) brassicasterol + UDP-α-D-glucose = brassicasterol 3-β-D-glucoside + H+ + UDP
- [RHEA:61836](https://www.rhea-db.org/rhea/61836) ergosterol + UDP-α-D-glucose = ergosteryl 3-β-D-glucoside + H+ + UDP
- [RHEA:61832](https://www.rhea-db.org/rhea/61832) sitosterol + UDP-α-D-glucose = H+ + sitosteryl 3-β-D-glucoside + UDP
- [RHEA:61828](https://www.rhea-db.org/rhea/61828) stigmasterol + UDP-α-D-glucose = H+ + stigmasteryl 3-β-D-glucoside + UDP
- [RHEA:61824](https://www.rhea-db.org/rhea/61824) pregnenolone + UDP-α-D-glucose = H+ + pregnenolone 3-β-D-glucoside + UDP
- [RHEA:61820](https://www.rhea-db.org/rhea/61820) 3β-hydroxy-5α-androstan-17-one + UDP-α-D-glucose = epiandrosterone 3-β-D-glucoside + H+ + UDP
- [RHEA:61816](https://www.rhea-db.org/rhea/61816) 16,17-didehydropregnenolone + UDP-α-D-glucose = 16,17-didehydropregnenolone 3-β-D-glucoside + H+ + UDP
- [RHEA:61812](https://www.rhea-db.org/rhea/61812) 3β-hydroxyandrost-5-en-17-one + UDP-α-D-glucose = dehydroepiandrosterone 3-β-D-glucoside + H+ + UDP
- [RHEA:19329](https://www.rhea-db.org/rhea/19329) nuatigenin + UDP-α-D-glucose = H+ + nuatigenin 3-β-D-glucopyranoside + UDP

**Comment by pgaudet** [comment]
Annotations are here: 
https://github.com/geneontology/go-annotation/issues/5281

4 dictyBase
1 TAIR

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete

GO:0051507 beta-sitosterol UDP-glucosyltransferase activity
GO:0051506 ergosterol UDP-glucosyltransferase activity
GO:0051508 stigmasterol UDP-glucosyltransferase activity
GO:0051509 tomatidine UDP-glucosyltransferase activity


The reason for obsoletion is that these represent specific substrates of GO:0016906 sterol 3-beta-glucosyltransferase activity. There are 5 manual annotations to these terms, by dictyBase and TAIR, see https://github.com/geneontology/go-annotation/issues/5281.

You can comment on the ticket:  https://github.com/geneontology/go-ontology/issues/25771

Thanks, Pascale
