### ISSUE TITLE
NTR: [N(7)-methylguanine-containing RNA reader activity and Internal mRNA (guanine-N7-)-methyltransferase activity]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#25788]
Hi GO,
I would need two terms related to N(7)-methylguanine (m7G) modification. I think that some existing definitions and ontology should also be updated. Instead of "Modified RNA binding", we should instead use the term reader activity, since it represents the real activity of these proteins that 'read' post-transcriptional modifications.

Thanks

Sylvain

1) 
N(7)-methylguanine-containing RNA reader activity
Molecular Function
Definition: A protein adaptor that recognizes and binds an RNA molecule modified by N(7)-methylguanine (m7G), a modification present at internal sites of mRNAs and some non-coding RNAs.
child of:
has_part GO:0003723 RNA binding
is_a GO:0140517 protein-RNA adaptor activity
PMID:37379838

Please note that GO:0062153 and GO:1990247 ontology and definitions should also be updated

GO:0062153 C5-methylcytidine-containing RNA reader activity
A protein adaptor that recognizes and binds an RNA molecule modified by C5-methylcytidine
child of:
has_part  GO:0003723 RNA binding
is_a  GO:0140517 protein-RNA adaptor activity

GO:1990247 N6-methyladenosine-containing RNA reader activity
A protein adaptor that recognizes and binds an RNA molecule modified by N6-methyladenosine (m6A), a modification present at internal sites of mRNAs and some non-coding RNAs.
child of:
has_part  GO:0003723 RNA binding
is_a  GO:0140517 protein-RNA adaptor activity

2)
internal mRNA (guanine-N7-)-methyltransferase activity
Molecular Function
Definition: Catalysis of the reaction: a guanosine in mRNA + S-adenosyl-L-methionine = an N(7)-methylguanosine in mRNA + S-adenosyl-L-homocysteine 
Child of
GO:0036265 RNA (guanine-N7)-methylation
GO:0008173 RNA methyltransferase activity
PMID:31031084
PMID:37379838
RHEA:60508

Note:
This activity takes place internally in mRNAs should not be mixed up with Cap mRNA (guanine-N7-)-methyltransferase activity occurring at mRNA 5' cap. 

We should also update the name of the existing  mRNA (guanine-N7-)-methyltransferase activity, since it is specific for the 5' cap
Rename: 
GO:0004482 mRNA (guanine-N7-)-methyltransferase activity
into:
GO:0004482 Cap mRNA (guanine-N7-)-methyltransferase activity

**Comment by raymond91125** [comment]
GO:0062153 C5-methylcytidine-containing RNA reader activity has been used to annotate Arabidopsis thaliana ALKBH6 which is a potential RNA demethylase PMID: 32933187 rather than an adaptor.

**Comment by sylvainpoux** [comment]
Hi,
Your comment is related to some annotation error and it is not related to my request. Please contact TAIR for an update.
Could you tell me when I will get the GO term requested? Because I would need them to make a GO-CAM model
Thanks
Sylvain

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160089
+name: internal N(7)-methylguanine-containing RNA reader activity
+namespace: molecular_function
+def: "A protein adaptor that recognizes and binds an RNA molecule modified by N(7)-methylguanine (m7G), a modification present at internal sites of mRNAs and some non-coding RNAs." [PMID:37379838]
+is_a: GO:0140517 ! protein-RNA adaptor activity
+relationship: has_part GO:0003723 ! RNA binding
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25788" xsd:anyURI
+created_by: rynl
+creation_date: 2023-08-08T22:12:09Z
+
+[Term]
+id: GO:0160090
+name: internal mRNA (guanine-N7-)-methyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: a guanosine in mRNA + S-adenosyl-L-methionine = an N(7)-methylguanosine in mRNA + S-adenosyl-L-homocysteine." [PMID:31031084, PMID:37379838, RHEA:60508]
+is_a: GO:0008174 ! mRNA methyltransferase activity
+relationship: part_of GO:0036265 ! RNA (guanine-N7)-methylation
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25788" xsd:anyURI
+created_by: rynl
+creation_date: 2023-08-08T22:40:38Z

**Comment by raymond91125** [comment]
If everything looks kosher, I'll merge the pull request. Thanks.

**Comment by raymond91125** [comment]
merged. Please reopen if needed. thanks.
