### ISSUE TITLE
phosphoglycerate mutase activity xrefs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25780]
Currently we have:

```
phosphoglycerate mutase activity
    |_2,3-bisphosphoglycerate-independent phosphoglycerate mutase activity
    |_2,3-bisphosphoglycerate-dependent phosphoglycerate mutase activity
```

id: GO:0004619
name: phosphoglycerate mutase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2-phosphoglycerate = 3-phosphoglycerate." [RHEA:15901]
xref: MetaCyc:3PGAREARR-RXN
xref: RHEA:15901
is_a: GO:0016868 ! intramolecular transferase activity, phosphotransferases

id: GO:0046537
name: 2,3-bisphosphoglycerate-independent phosphoglycerate mutase activity
def: "Catalysis of the reaction: 2-phospho-D-glycerate = 3-phospho-D glycerate; this reaction does not require the cofactor 2,3-bisphosphoglycerate." [EC:5.4.2.12]
xref: EC:5.4.2.12 {source="skos:exactMatch"}
is_a: GO:0004619 ! phosphoglycerate mutase activity

id: GO:0046538
name: 2,3-bisphosphoglycerate-dependent phosphoglycerate mutase activity
def: "Catalysis of the reaction: 2-phospho-D-glycerate = 3-phospho-D-glycerate; this reaction mechanism uses 2,3-bisphosphoglycerate as a phosphate donor." [EC:5.4.2.11]
xref: EC:5.4.2.11 {source="skos:exactMatch"}
xref: KEGG_REACTION:R01516
is_a: GO:0004619 ! phosphoglycerate mutase activity

---------------

- [x] MetaCyc:3PGAREARR-RXN (https://biocyc.org/META/NEW-IMAGE?object=3PGAREARR-RXN) corresponds to EC:5.4.2.12, so should be moved from GO:0004619 to GO:0046537

- [x] MetaCyc:RXN-15513 (https://biocyc.org/META/NEW-IMAGE?type=REACTION&object=RXN-15513) corresponds to EC:5.4.2.11, so should be added to GO:0046538

- [ ] RHEA:15901 (https://www.rhea-db.org/rhea/15901) covers both EC:5.4.2.11 and EC:5.4.2.12, so it's probably fine to have that on the parent term (GO:0004619), though it would be accurate to also add it to both child terms (GO:0046537, GO:0046538)

**Comment by sjm41** [comment]
@pgaudet I tried adding RHEA:15901 to both child terms (as well as the parent) but it seems this isn't allowed.

**Comment by sjm41** [comment]
No need to add RHEA:15901 to both child terms (as well as the parent) - closing.

**Comment by pgaudet** [comment]
Editors' discussion:  proposal to merge the two specific terms into the parent

**Comment by pgaudet** [comment]
More details on the subreactions here: https://www.enzyme-database.org/query.php?ec=5.4.2.12

**Comment by pgaudet** [comment]
Annotations are here: https://github.com/geneontology/go-annotation/issues/5503

**Comment by sjm41** [comment]
Thanks @raymond91125 !
