### ISSUE TITLE
NTR: [Formation of circular RNA]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#25791]
Hi GO,
I would need a term for the formation of circular RNAs.

Thanks

Sylvain

Name: Formation of circular RNA
Biological Process
Definition: Formation of circular RNAs (circRNAs) by back-splicing circularization of pre-mRNAs in a spliceosome-dependent process.
child of  GO:0000398 mRNA splicing, via spliceosome
PMID:25768908
PMID:28625552

**Comment by raymond91125** [comment]
https://en.wikipedia.org/wiki/Circular_RNA, there seems to be multiple types of circular RNAs.

**Comment by sylvainpoux** [comment]
Hi @raymond91125 
You are right, there are multiple types of circular RNAs but their formation is spliceosome-dependent. Moreover, the term I request is quite generic, so I think that the ontology is correct and will apply to the different types of circRNAs.
Thanks
Sylvain

**Comment by raymond91125** [comment]
Aren't there mRNA and spliceosome-independent circular RNA formation? e.g. PMID:14624003 The ability to form full-length intron RNA circles is a general property of nuclear group I introns.
Perhaps we could make the term name more specific to match the definition. e.g. spliceosome-dependent, circular RNA formation from pre-mRNA.

**Comment by deustp01** [comment]
@raymond91125 @sylvainpoux   A retired colleague, Mark Rush, is an authority on the formation and function of small circular RNAs. If you'd like, I'd be happy to give you his e-mail (rather not put it in a GitHub ticket)

**Comment by raymond91125** [comment]
@deustp01 Thanks, Peter. I think the discussion here is whether we'd go with something more general or more specific and match the term label and definition and references accordingly.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160091
+name: spliceosome-depend formation of circular RNA
+namespace: biological_process
+def: "Formation of circular RNAs (circRNAs) by back-splicing circularization of pre-mRNAs in a spliceosome-dependent process." [PMID:25768908, PMID:28625552]
+is_a: GO:0000398 ! mRNA splicing, via spliceosome
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25791" xsd:anyURI
+created_by: rynl
+creation_date: 2023-08-11T16:21:21Z
