### ISSUE TITLE
Suggested revisions to 'dentate gyrus mossy fiber'

### ISSUE THREAD

**Issue by bvarner-ebi** [geneontology/go-ontology#25796]
TERM: **['dentate gyrus mossy fiber'](http://purl.obolibrary.org/obo/GO_0044302)**
Context: https://github.com/obophenotype/cell-ontology/issues/2012#issuecomment-1633906422

--

- [x] delete has_exact_synonym “granule cell axon” **or** make it a broad synonym

Reason: Granule cells are part of brain structures other than only the dentate gyrus, [most notably the cerebellum](https://doi.org/10.3389/fncir.2020.611841). Since granule cell axons are also part of parallel fibers in the cerebellum, it seems inaccurate to consider "granule cell axon" to be an exact syn of 'dentate gyrus mossy fiber'. Consider removing this annotation or at least making the syn broad.

--

- [x] Edit axiom to have more specificity:

**CURRENT**: 'part of' some 'granule cell'
**PROPOSED**: 'part of' some 'dentate gyrus of hippocampal formation granule cell’ (to be relabelled 'dentate gyrus granule cell' in the next CL release).

--

- [x] Reconsider hierarchy and text defintion:

Is it accurate to assert that '[hippocampus mossy fiber](http://purl.obolibrary.org/obo/GO_0097457)' is a subclass of '[dentate gyrus mossy fiber](http://purl.obolibrary.org/obo/GO_0044302)'?

While there may be debate on whether the dentate gyrus is considered part of the hippocampus or rather a distinct structure of the hippocampus, [the former has been referred to as a subregion of the latter](https://www.nature.com/articles/s41583-023-00710-z), not the other way around.

Also, [the database cross reference](https://pubmed.ncbi.nlm.nih.gov/17765709/) states:
"The dentate gyrus is a simple cortical region that is an integral portion of the larger functional brain system called the hippocampal formation."

Indeed, the text definition of 'hippocampal mossy fiber' is (emphasis added):

"**Axon of dentate gyrus granule cell** projecting to hippocampal area CA3, characterized by expansions (mossy fiber expansions) giving the fibers a mossy appearance. These unmyelinated axons were first described by Ramon y Cajal."

Is the term meant to represent only the parts of the mossy fiber that extend into CA3?

'dentate gyrus mossy fiber' also has an overly broad text def and would benefit from revision to include more specificity:

CURRENT: "Distinctive, unmyelinated axons produced by granule cells."

At the least, this definition can be updated to:

"Distinctive, unmyelinated axons produced by dentate gyrus granule cells."

**Comment by raymond91125** [comment]
@balhoff I still get an error doing ./run.sh make imports/cl_import.obo
The output is shared here https://drive.google.com/file/d/1Xp_M65m4mp7pWCANOPusJ-L4V64iRyUG
Thanks.

**Comment by balhoff** [comment]
@raymond91125 do you have some local changes to definition xrefs? This is the problem:

```
Filtering unknown Rhea ID from definition xref for annotation would remove all definition xrefs:
AnnotationAssertion(Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "RHEA:69819"^^xsd:string) <http://purl.obolibrary.org/obo/IAO_0000115> <http://purl.obolibrary.org/obo/GO_0047822> "Catalysis of the reaction: H+ + hypotaurine + NADPH + O2 = H2O + NADP+ + taurine."^^xsd:string)
```

**Comment by raymond91125** [comment]
@balhoff Thanks. I think that was generated before by a docker run.

**Comment by raymond91125** [comment]
NIF has Dentate gyrus mossy fiber a synonym of Hippocampal mossy fiber
https://scicrunch.org/scicrunch/interlex/view/ilx_0105016
I suggest we merge them in GO.

**Comment by raymond91125** [comment]
I also wonder if hippocampal granule cell and dentate gyrus granule cell should be exact synonyms. https://github.com/obophenotype/cell-ontology/issues/2012
Are there hippocampal granule cells not in dentate gyrus? https://en.wikipedia.org/wiki/Hippocampus_anatomy

**Comment by pgaudet** [comment]
Do we need to open a CL ticket ? 

And I think we can close the ticket here, the change does not need intervention from a GO ontology editor.

**Comment by raymond91125** [comment]
I think we do need to handle the CC terms in GO, no? There is already a CL ticket https://github.com/obophenotype/cell-ontology/issues/2012.

**Comment by cmungall** [comment]
Yes of course but embedded information about the cell type should be
derived directly from CL

**Comment by raymond91125** [comment]
https://github.com/obophenotype/cell-ontology/issues/2012#issuecomment-1653483543
"A cursory online literature search revealed at least one instance of granule cells described in the hippocampus outside of the DG: https://doi.org/10.1523/JNEUROSCI.5602-09.2010"
Interesting. This paper says that these CA3 granule cells (not dentate gyrus granule cells) also have mossy fibers in the same region as those MF from DG granule cells. This then calls into question the definition of Hippocampal mossy fiber. "Axon of dentate gyrus granule cell projecting to hippocampal area CA3, characterized by expansions (mossy fiber expansions) giving the fibers a mossy appearance. These unmyelinated axons were first described by Ramon y Cajal." It is too narrow.
@bvarner-ebi Do you agree?

**Comment by raymond91125** [comment]
Oh, found another exception.
"Dentate mossy fibers innervate CA2 pyramidal cells" per PMID:24336151. So another def proposal for Hippocampal mossy fiber: 
"Axon of a granule cell, including dentate gyrus granule cell and CA3 granule cell, characterized by expansions (mossy fiber expansions) giving the fibers a mossy appearance. These unmyelinated axons were first described by Ramon y Cajal." [PMID:17765709, NIF_Subcellular:nlx_subcell_100312, PMID:20554881, PMID:24336151]

**Comment by raymond91125** [comment]
A useful resource for references https://hippocampome.org/.

**Comment by bvarner-ebi** [comment]
> "Axon of a granule cell, including dentate gyrus granule cell and CA3 granule cell, characterized by expansions (mossy fiber expansions) giving the fibers a mossy appearance.

@raymond91125, consider starting with "Axon of a **hippocampal** granule cell... "

**Comment by raymond91125** [comment]
Thanks for all the help. Please reopen issue if something has been missed.

**Comment by bvarner-ebi** [comment]
Thanks, @raymond91125!
