### ISSUE TITLE
MetaCyc xref on GO:0140681 histone H3K36me2/H3K36me3 demethylase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25808]
id: GO:0140681
name: histone H3K36me2/H3K36me3 demethylase activity
def: "Catalysis of the removal of a methyl group from a tri- or a dimethyl-lysine residue at position 36 of the histone H3 protein. This is a dioxygenase reaction that is dependent on Fe(II) and 2-oxoglutarate." [PMID:21914792]
synonym: "histone H3-tri/dimethyl-lysine-36 demethylase activity" EXACT []
synonym: "histone H3K36me2 demethylase activity" BROAD []
synonym: "histone H3K36me3 demethylase activity" RELATED []
xref: EC:1.14.11.69 {source="skos:exactMatch"}
xref: MetaCyc:RXN-8660
xref: RHEA:60236
is_a: GO:0051864 ! histone H3K36 demethylase activity

MetaCyc:RXN-8660 corresponds to more general reaction so should be removed.
It can be replaced with RXN-20643, which corresponds to EC:1.14.11.69 (https://biocyc.org/META/NEW-IMAGE?type=REACTION&object=RXN-20643)

**Comment by cmungall** [comment]
Thanks! But we should be doing transitive propagation automatically....
