### ISSUE TITLE
Missing parent: GO:0061605 molybdopterin-synthase adenylyltransferase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#25802]
Is this not true?

* **GO term ID and label for which you request a new superclass**

GO:0061605 molybdopterin-synthase adenylyltransferase activity

* **New superclass (parent) suggested**
 GO:0070733 protein adenylyltransferase activity

@sjm41

**Comment by raymond91125** [comment]
It seems that this case is about the term name implies something broader than its definition. We could rename it to something like "protein L-serine/L-threonine/L-tyrosine residue adenylyltransferase activity". Is that desirable, though?

**Comment by sjm41** [comment]
@raymond91125 Yes, it would be useful if the name didn't suggest it was a broad grouping term. I see EC says that "AMPylase" is an alternative name, so maybe the GO term name could be "AMPylase activity" (and keep the current definition)?

@Antonialock Given this, will the UniProt annotation to P38820 (yeast UBA4) have to change to 'adenylyltransferase activity'?

**Comment by raymond91125** [comment]
Renamed to AMPylase activity. Should this be closed? Thanks.

**Comment by raymond91125** [comment]
Please reopen if needed. Thanks.
