### ISSUE TITLE
Term merge: butyrate-CoA ligase activity & medium-chain fatty acid-CoA ligase activity?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25800]
I _think_ the two terms below should be merged - GO:0047760 should be made an alt_id of GO:0031956
- both have EC:6.2.1.2 (medium-chain acyl-CoA ligase) as an xref
- butyryl-CoA synthetase is a synonym of EC:6.2.1.2 (medium-chain acyl-CoA ligase)

Not sure why RHEA:24336 is currently an xref on GO:0047760 - that appears to be a much more general reaction - so omit that from the merged term.
Also, MetaCyc:BUTYRATE--COA-LIGASE-RXN doesn't appear to specify a chain length, so I'd also omit that xref.

id: GO:0047760
name: butyrate-CoA ligase activity
namespace: molecular_function
def: "Catalysis of the reaction: ATP + an acid + CoA = AMP + diphosphate + an acyl-CoA." [EC:6.2.1.2, MetaCyc:BUTYRATE--COA-LIGASE-RXN]
synonym: "acyl-activating enzyme activity" RELATED [EC:6.2.1.2]
synonym: "butanoate:CoA ligase (AMP-forming)" RELATED [EC:6.2.1.2]
synonym: "butyryl-CoA synthetase activity" RELATED [EC:6.2.1.2]
synonym: "butyryl-coenzyme A synthetase activity" RELATED [EC:6.2.1.2]
synonym: "fatty acid activating enzyme" RELATED [EC:6.2.1.2]
synonym: "fatty acid thiokinase (medium chain) activity" RELATED [EC:6.2.1.2]
synonym: "fatty acyl coenzyme A synthetase activity" RELATED [EC:6.2.1.2]
synonym: "L-(+)-3-hydroxybutyryl CoA ligase activity" RELATED [EC:6.2.1.2]
synonym: "medium chain acyl-CoA synthetase activity" RELATED [EC:6.2.1.2]
synonym: "short-chain acyl-CoA synthetase activity" RELATED [EC:6.2.1.2]
xref: EC:6.2.1.2
xref: MetaCyc:BUTYRATE--COA-LIGASE-RXN
xref: RHEA:24336
is_a: GO:0016405 ! CoA-ligase activity
is_a: GO:0016878 ! acid-thiol ligase activity

id: GO:0031956
name: medium-chain fatty acid-CoA ligase activity
namespace: molecular_function
def: "Catalysis of the reaction: ATP + a medium-chain fatty acid + CoA = AMP + diphosphate + an acyl-CoA. A medium-chain fatty acid is a fatty acid with an aliphatic tail of 6 to 12 carbons." [GOC:mah, RHEA:48340]
synonym: "medium-chain fatty acid activation" RELATED []
synonym: "medium-chain fatty-acid-CoA ligase activity" EXACT [GOC:bf]
synonym: "medium-chain-fatty-acid-CoA ligase activity" EXACT []
xref: EC:6.2.1.2
xref: RHEA:48340
is_a: GO:0015645 ! fatty acid ligase activity
is_a: GO:0016405 ! CoA-ligase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/14783" xsd:anyURI
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/18967" xsd:anyURI
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/23497" xsd:anyURI

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0047760 butyrate-CoA ligase activity and replace it by GO:0031956
medium-chain fatty acid-CoA ligase activity. The reason for obsoletion is that butyrate represents a specific substrate. Both terms share the same EC. 

There are 15 EXP annotations, by BHF, RGD (1 each) and UniProt (13), see https://github.com/geneontology/go-annotation/issues/5190 but these will be automatically replaced. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25800

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks @pgaudet !
