### ISSUE TITLE
GO terms for EC:2.1.1.10 (GO:0008898 & GO:0061627)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25824]
EC:2.1.1.10 (https://enzyme.expasy.org/EC/2.1.1.10) says:

Name: homocysteine S-methyltransferase
Reaction: L-homocysteine + S-methyl-L-methionine <=> H(+) + 2 L-methionine
Comment: The enzyme uses S-adenosyl-L-methionine as methyl donor less actively than S-methyl-L-methionine.

So I think it would be appropriate to add EC:2.1.1.10 as a xref (maybe 'broad?') to both GO:0008898 & GO:0061627 (shown below).

Also, can add MetaCyc:MMUM-RXN xref to GO:0061627.

------
id: GO:0008898
name: S-adenosylmethionine-homocysteine S-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + L-homocysteine = S-adenosyl-L-homocysteine + L-methionine." [EC:2.1.1.10, GOC:BHF, GOC:dph]
synonym: "adenosylmethionine transmethylase activity" RELATED [EC:2.1.1.10]
synonym: "adenosylmethionine:homocysteine methyltransferase activity" RELATED [EC:2.1.1.10]
synonym: "homocysteine methyltransferase activity" RELATED [EC:2.1.1.10]
synonym: "homocysteine transmethylase activity" RELATED [EC:2.1.1.10]
synonym: "L-homocysteine S-methyltransferase activity" RELATED [EC:2.1.1.10]
synonym: "S-adenosyl-L-methionine:L-homocysteine methyltransferase activity" RELATED [EC:2.1.1.10]
synonym: "S-adenosyl-L-methionine:L-homocysteine S-methyltransferase activity" RELATED [EC:2.1.1.10]
synonym: "S-adenosylmethionine homocysteine transmethylase activity" RELATED [EC:2.1.1.10]
synonym: "S-adenosylmethionine-homocysteine transmethylase activity" RELATED [EC:2.1.1.10]
synonym: "S-adenosylmethionine:homocysteine methyltransferase activity" RELATED [EC:2.1.1.10]
xref: MetaCyc:HOMOCYSTEINE-S-METHYLTRANSFERASE-RXN
xref: RHEA:21820
is_a: GO:0008172 ! S-methyltransferase activity
is_a: GO:0008757 ! S-adenosylmethionine-dependent methyltransferase activity

id: GO:0061627
name: S-methylmethionine-homocysteine S-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-methyl-L-methionine + L-homocysteine = 2 L-methionine + H+." [EC:2.1.1.10, GOC:BHF, GOC:dph]
synonym: "homocysteine methyltransferase activity" RELATED [EC:2.1.1.10]
synonym: "homocysteine transmethylase activity" RELATED [EC:2.1.1.10]
synonym: "methylmethionine:homocysteine methyltransferase activity" RELATED [EC:2.1.1.10]
synonym: "S-methylmethionine homocysteine transmethylase activity" RELATED [EC:2.1.1.10]
xref: RHEA:26337
is_a: GO:0008172 ! S-methyltransferase activity
created_by: dph
creation_date: 2014-05-14T14:32:02Z

**Comment by pgaudet** [comment]
Changed def xrefs from EC to RHEA, since EC are not unique.
