### ISSUE TITLE
Logical definition of role causing cyclic dependency

### ISSUE THREAD

**Issue by bvarner-ebi** [geneontology/go-ontology#25821]
**Term**: [role](http://purl.obolibrary.org/obo/BFO_0000023)
**Context**: https://github.com/obophenotype/cell-ontology/issues/2065

After investigating the issue linked above, it appears that GO imports [role](http://purl.obolibrary.org/obo/BFO_0000023) from RO and then asserts it to be equivalent to the CHEBI term [role](http://purl.obolibrary.org/obo/CHEBI_50906). This is reportedly causing the issue mentioned in the linked ticket.

Can you kindly investigate? Should the equivalence axiom be removed and instead be made a database cross reference annotation?

**Comment by balhoff** [comment]
Thanks for pointing this out, @bvarner-ebi. GO has had this equivalence for a long time, and then more recently a mapping was added to COB. I think we can start importing COB and remove the assertion from GO. Do you know where the subClassOf axiom is coming from in CL? COB asserts CHEBI:role to be a subclass of PATO:quality, which should be sufficient for us, but doesn't explain the CL situation.

**Comment by bvarner-ebi** [comment]
> Thanks for pointing this out, @bvarner-ebi. GO has had this equivalence for a long time, and then more recently a mapping was added to COB. I think we can start importing COB and remove the assertion from GO. Do you know where the subClassOf axiom is coming from in CL? COB asserts CHEBI:role to be a subclass of PATO:quality, which should be sufficient for us, but doesn't explain the CL situation.

Thanks for the prompt reply, @balhoff.

It appears to come from RO.
See https://www.ebi.ac.uk/ols4/ontologies/ro/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000023.

**Comment by bvarner-ebi** [comment]
Hi @balhoff, checking in if there is anything you need from CL's side before making the edits.

**Comment by balhoff** [comment]
Thanks @bvarner-ebi, fixed in #25873. This should appear in the August GO release.
