### ISSUE TITLE
TRAMP complex - New component ontology term

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#2583]
Hi,

I would like to propose the following complex term be added to the 
component ontology as an instance of protein complex 
(GO:43234) and a child term of nucleus (GO:5634):

Term: TRAMP complex 
Synonyms:  Trf4p-Air2p-Mtr4p polyadenylation complex; Trf4 
poly(A) polymerase complex; Trf4 complex

Definition: A multiprotein complex in yeast consisting of Trf4p, 
Air1p or Air2p and Mtr4p. This nuclear RNA surveillance and 
quality control complex is involved in the distributive 
polyadenylation of substrates that include: hypomodified and 
incorrectly folded tRNAs, snoRNA precursors and rRNA 
precursors. It is also required for the degradative activity of the 
nuclear exosome in vivo.

Definition_references: 
PMID: 15828860
PMID: 15935758

Thanks,
Rob

Reported by: rnash

Original Ticket: "geneontology/ontology-requests/2590":https://sourceforge.net/p/geneontology/ontology-requests/2590

**Comment by ValWood** [comment]
I would like to revert TRAMP complex to this definition.
There are a couple of old papers referring to en-processing but this appears to be a phenotype of stuffing up non-functional RNA decay (I will double check this)

**Comment by ValWood** [comment]
ignore
