### ISSUE TITLE
NTR: SKA complex

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#25850]
Please provide as much information as you can: 

* **Suggested term label:**

SKA complex

* **Definition (free text)**
An outer kinetochore complex involved in the attachment of microtubule ends to the chromosomes during mitosis. It contains the subunits SKA1, SKA2 and SKA3.

* **Reference, in format PMID:#######**
PMID:19289083
PMID:22483620

* **Gene product name and ID to be annotated to this term**
 SKA1, SKA2 and SKA3. Q8WVK7 Q96BD8 Q8IX90

* **Parent term(s)**
part_of GO:0000940 outer kinetochore
is_a protein-containing complex GO:0032991
capable of_of GO:0051010 microtubule +end binding

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
SKA1 complex EXACT

**Comment by edwong57** [comment]
Should ComplexPortal IDs be added as cross-references? There are three SKA1 complexes - https://www.ebi.ac.uk/complexportal/complex/search?query=ska1&page=1 
CPX-5642 
CPX-5700
CPX-811

**Comment by Antonialock** [comment]
I don't have any objections to adding those xrefs? I think? I'm never sure what goes in the xrefs.

But perhaps tweak the def to include "in human, the complex consists of ska1, ska2, and ska3" - I believe I see from the complex portal annotations that worm ska complex contains 2xska1 and 1xska3?

**Comment by sandraorchard** [comment]
I wish we could get rid of those lists of components in the definitions as they are (i) species specific so not helpful for everyone else and (ii) never get updated when new components are found or wrong ones no longer considered part of the complex. But that's just a personal gripe.

**Comment by Antonialock** [comment]
I think it can be useful to know what the core complex is when the complex transiently binds other proteins...? But yes, it's not useful if incorrect/incomplete!

**Comment by pgaudet** [comment]
We don't put cpx as cross references,  these are annotations.

Thanks,  Pascale

**Comment by edwong57** [comment]
It is looking like Ndc80 complex (GO:0031262) is being added as a parent. Is the fix changing the parent terms in the Ncd80 complex? Moving them from 'Equivalent To' to the 'SubClass Of' section? 
![image](https://github.com/geneontology/go-ontology/assets/526428/0aa464d5-bc18-4c31-950d-f90786096382)

**Comment by edwong57** [comment]
This has been resolved
