### ISSUE TITLE
Was http://geneontology.org/doc/GO.xrf_abbs replaced?

### ISSUE THREAD

**Issue by bvarner-ebi** [geneontology/go-ontology#25854]
Uberon PR QC checks are failing with the following output:

```
--2023-07-27 08:25:14--  http://geneontology.org/doc/GO.xrf_abbs
Resolving geneontology.org (geneontology.org)... 185.199.108.153, 185.199.109.153, 185.199.111.153, ...
Connecting to geneontology.org (geneontology.org)|185.199.108.153|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-07-27 08:25:14 ERROR 404: Not Found.

make: *** [uberon.Makefile:725: tmp/GO.xrf_abbs] Error 8
Error: Process completed with exit code 2.
```

The full output can be viewed here: https://github.com/obophenotype/uberon/actions/runs/5678228541/job/15388031337

Going to http://geneontology.org/doc/GO.xrf_abbs does indeed result in a 404 error.
Was this link updated?

FYI: @matentzn

**Comment by pgaudet** [comment]
@kltm

**Comment by bvarner-ebi** [comment]
FYI: @udp helped investigate and found that the current link is now: http://current.geneontology.org/metadata/GO.xrf_abbs

I will close this ticket as the fix needed probably has to happen on Uberon's side.

**Comment by kltm** [comment]
@bvarner-ebi While the previous URL has been restored on the server side for now (apologies for the confusion), I would definitely recommend the http://current.geneontology.org/metadata/GO.xrf_abbs URL moving forward and for future development.

**Comment by cmungall** [comment]
better yet remove all dependence on this file https://github.com/obophenotype/uberon/issues/2999
