### ISSUE TITLE
NTR: melatonin secretion

### ISSUE THREAD

**Issue by aleixpuigb** [geneontology/go-ontology#25855]
Please provide as much information as you can: 

* **Suggested term label:**
melatonin secretion

* **Definition (free text)**
The regulated release of melatonin into the circulatory system in response to darkness.

* **Reference, in format PMID:#######**
[PMID:16817850](https://febs.onlinelibrary.wiley.com/doi/10.1111/j.1742-4658.2006.05322.x)
[PMID:25705578](https://pubmed.ncbi.nlm.nih.gov/25705578)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
[endocrine hormone secretion](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0060986?lang=en)
`secretion and ('has primary input' some 'melatonin')`

* **Any other information**

**Comment by raymond91125** [comment]
Is it intentional that autocrine/paracrine secretion of melatonin is excluded? If so, perhaps it is better to specify "endocrine melatonin secreation". Should there be a taxon restriction as well?

**Comment by raymond91125** [comment]
Is there an example of genes involved in melatonin secretion? I cannot seem to find a description of a pathway in the literature. There is plenty about synthesis but release (from pineal gland) is described as immediate.

**Comment by raymond91125** [comment]
@aleixpuigb Could you comment? Thanks.

**Comment by aleixpuigb** [comment]
Apologies @raymond91125, I was away last week.
> Is it intentional that autocrine/paracrine secretion of melatonin is excluded? If so, perhaps it is better to specify "endocrine melatonin secreation". 

You are correct, while seratonin secretion is primarily endocrine, there can be also paracrine or autocrine secretion ([doi:10.1073/pnas.2113852118](https://doi.org/10.1073/pnas.2113852118)). Therefore the parent term should be [hormone secretion](http://purl.obolibrary.org/obo/GO_0046879).

> Should there be a taxon restriction as well?

I think there shouldn't be a taxon restriction, since it can be found in animals, plants, bacteria, etc.

> Is there an example of genes involved in melatonin secretion? I cannot seem to find a description of a pathway in the literature. There is plenty about synthesis but release (from pineal gland) is described as immediate.

That is also what I have found. There are genes involved in their synthesis or degradation([PMID: 31841296](https://www.ncbi.nlm.nih.gov/books/NBK550972/#:~:text=Melatonin%20(N%2Dacetyl%2D5,for%20the%20transformation%20of%205%2D), [PMID: 25369242](https://doi.org/10.1111/jpi.12189)), but literature describes immediate secretion into the bloodstream once available.

**Comment by raymond91125** [comment]
@aleixpuigb Thanks for the reply.
Yes. Melatonin is quite membrane permeable [PMID:26712850]. Thus its secretion per se may not be regulated. GO defines secretion as "The controlled release of a substance by a cell or a tissue". I think secretion that is not regulated is similar to a chemical reaction that naturally happens without the catalysis of any enzymes. In these cases, our guideline is that we do not create a GO term. What would be your use case for the term?

**Comment by aleixpuigb** [comment]
We are updating the pattern of endocrine cells in CL in [this ticket](https://github.com/obophenotype/cell-ontology/issues/1886) with subClassOf capable_of some ('XX secretion' and ('has target end location' some 'circulatory system')), and I was requesting 'melatonin secretion' for `pinealocyte`. However, I agree that it doesn't fit with the secretion definition. Maybe `melatonin release` would be more appropriate, but in GO 'signal release' is under 'secretion by cell', so there is the same problem. Thank you for looking into it. Would you like me to close the ticket as not planned?

**Comment by raymond91125** [comment]
I see. That's a tough one as in this case, it seems that it's the synthesis that matters, not secretion. I do also wonder about the steroid hormones that can freely diffuse through membranes but I have not been able to find a clear picture of how those 'secretion' works.
You may certainly close the ticket unless there is more we can do. Thanks!
