### ISSUE TITLE
NTR: spermatid cytoplasm removal during spermiation

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#25853]
Please provide as much information as you can: 

* **Suggested term label:**
spermatid cytoplasm removal during spermiation

* **Definition (free text)**
The process of removing the majority of the cytoplasm and organelles from a spermatid as it develops into a mature sperm cell.

* **Reference, in format PMID:#######**
(REQUIRED)
PMID:21866274 = O'Donnell L, Nicholls PK, O'Bryan MK, McLachlan RI, Stanton PG. Spermiation: The process of sperm release. Spermatogenesis. 2011 Jan;1(1):14-35. doi: 10.4161/spmg.1.1.14525. 

* **Gene product name and ID to be annotated to this term**
mouse genes Spem1, Ehd1, Capza3

* **Parent term(s)**
is_a: developmental process involved in reproduction - GO:0003006
part_of: spermatogenesis - GO:0007283

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
NA

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
* spermatid cytoplasm elimination during spermiation [EXACT]

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
Is this term intended to be specific to mouse, vertebrates, or animals?

**Comment by raymond91125** [comment]
Seems mammals have their special process.
PMID:464324 Spermatid-Sertoli tubulobulbar complexes as devices for elimination of cytoplasm from the head region late spermatids of the rat 
PMID:3825964 Comparative study of cytoplasmic elimination in spermatids of selected mammalian species 
PMID: 33459394 Process of cytoplasm elimination during spermiogenesis in Octopus tankahkeei : Polarized development of the spermatid and discarding of the residual body

**Comment by krchristie** [comment]
> Is this term intended to be specific to mouse, vertebrates, or animals?

It's definitely more general than just mouse as it's fairly conserved between mouse, rat, & human.

All animals is probably too broad as C. elegans have amoedoid sperm so no flagellum and probably no elimination of cytoplasm as it seems to me that amoedoid sperm would still need cytoplasm for the cytoskeletal rearrangements necessary for amoeboid locomotion.

I don't really know the appropriate taxon scope. Thanks for all the great refs you've posted. I'll take a look at those and see if I can help you figure out what makes sense for GO.

Thanks!

**Comment by raymond91125** [comment]
It looks like the tubulobulbar maybe something unique to mammals thus the mechanism of spermatid cytoplasm removal is perhaps mammalian specific.

**Comment by krchristie** [comment]
> It looks like the tubulobulbar maybe something unique to mammals thus the mechanism of spermatid cytoplasm removal is perhaps mammalian specific.

I agree that the tubulobulbar mechanism of cytoplasmic removal might be mammal specific.

However, in the quick glance I did at two of the first three papers you listed, I think that this term, as I've suggested with this broad definition might be applicable for spermiation of any flagellated sperm:

- **Suggested term label:** spermatid cytoplasm removal during spermiation
- **Definition (free text):** The process of removing the majority of the cytoplasm and organelles from a spermatid as it develops into a mature sperm cell.

We could consider making the term label more obviously specific and call it **spermatid cytoplasm removal during spermiation of flagellated sperm**, and narrow the definition appropriately (we might want to do that anyway) so that it will exclude amoeboid sperm and immotile plant sperm, but then be general enough for any kind of cytoplasm removal during spermiation. 

- **Suggested term label:** spermatid cytoplasm removal during spermiation of flagellated sperm
- **Definition (free text):** The process of removing the majority of the cytoplasm and organelles from a spermatid as it develops into a mature flagellated sperm cell.

My understanding of sperm is that there is a lot of variation across taxa. I think trying to come up with a really precise taxonomic range could be a quagmire. I also don't really want to do a lot of research to understand exactly what types of "cytoplasm removal during spermiation" processes occur in species I am not currently annotating.  If we need something more specific in the future due to taxonomic differences, it should be simple to migrate the mouse annotations to the appropriate more specific term. So maybe having a broad term is good enough for now.

**Comment by raymond91125** [comment]
Thanks for the suggestions. I wonder if the word spermiation is rather specific to mammals as in PMID:21866274.
How about "spermatid cytoplasm removal during flagellated sperm development" DEF "The process of removing the majority of the cytoplasm and organelles from a spermatid as it develops into a mature flagellated sperm cell." [PMID:21866274, PMID:23087837]

**Comment by raymond91125** [comment]
NV. Spermiation is not specific to mammals, e.g. PMID:19416498.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160087
+name: spermatid cytoplasm removal during spermiation of flagellated sperm
+namespace: biological_process
+def: "The process of removing the majority of the cytoplasm and organelles from a spermatid as it develops into a mature flagellated sperm cell." [PMID:21866274, PMID:23087837]
+is_a: GO:0003006 ! developmental process involved in reproduction
+relationship: part_of GO:0007283 ! spermatogenesis
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25853" xsd:anyURI
+created_by: rynl
+creation_date: 2023-08-03T00:23:44Z
