### ISSUE TITLE
NTR: protein localization to polar microtubule

### ISSUE THREAD

**Issue by manulera** [geneontology/go-ontology#25862]
Please provide as much information as you can: 

* **Suggested term label:** protein localization to polar microtubule

* **Definition (free text)** A process in which a protein is transported to, or maintained in, a location within a polar microtubule. 

* **Reference, in format PMID:#######** PMID:34080538
(REQUIRED)

* **Gene product name and ID to be annotated to this term** 

* **Parent term(s)** GO:1902889

* **Any other information** should be a sibling of protein localization to astral microtubule

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160086
+name: protein localization to polar microtubule
+namespace: biological_process
+def: "A process in which a protein is transported to, or maintained in, a location within a polar microtubule." [PMID:34080538]
+intersection_of: GO:0008104 ! protein localization
+intersection_of: has_target_end_location GO:0005827 ! polar microtubule
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25862" xsd:anyURI
+created_by: rynl
+creation_date: 2023-07-28T23:20:48Z
