### ISSUE TITLE
GO terms defined solely by obsolete MetaCyc xrefs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25865]
The following GO terms appear to be defined solely by a MetaCyc ID that is obsolete, suggesting that the GO terms should also be obsoleted. The GO terms have been used in zero or very few annotations, as indicated.

Molecular functions:
- [x] GO:0047410 | N-formylmethionylaminoacyl-tRNA deformylase activity | 0 annotations
- [x] GO:0050562 | lysine-tRNA(Pyl) ligase activity | 0 annotations
- [x] GO:0102030 | dTDP-L-rhamnose synthetase activity | 0 annotations
- [x] GO:0102184 | cycloartenol 4alpha-methyl oxidase activity | 0 annotations
- [x] GO:0102185 | 4alpha-hydroxymethyl,4beta,14alpha-dimethyl-9beta,19-cyclo-5alpha-cholest-24-en-3beta-ol-4alpha-methyl oxidase activity | 0 annotations
- [x] GO:0102186 | 4alpha-formyl,4beta,14alpha-dimethyl-9beta,19-cyclo-5alpha-cholest-24-en-3beta-ol-4alpha-methyl oxidase activity | 0 annotations
- [x] GO:0102188 | 4alpha-methyl-5alpha-cholesta-7,24-dien-3beta-ol-4alpha-methyl oxidase activity | 0 annotations
- [x] GO:0102189 | 4alpha-hydroxymethyl-5alpha-cholesta-7,24-dien-3beta-ol-4alpha-methyl oxidase activity | 0 annotations - obsoleted in  #26101
- [x] GO:0102190 | 4alpha-formyl-5alpha-cholesta-7,24-dien-3beta-ol-4alpha-methyl oxidase activity | 0 annotations
- [x] GO:0102278 | N,N'-diacetylchitobiose synthase activity | 0 annotations
- [x] GO:0102783 | beta-carotene oxygenase activity | 0 annotations
- [x] GO:0043826 | sulfur oxygenase reductase activity | 0 annotations >> same as [sulfur oxygenase/reductase activity](http://purl.obolibrary.org/obo/GO_0033755)
- [x] GO:0043841 | (S)-lactate 2-kinase activity | 1 NOT annotation >> activity way wrong, corresponds to [phospholactate guanylyltransferase activity](http://purl.obolibrary.org/obo/GO_0043814), see https://pubmed.ncbi.nlm.nih.gov/30952857/

**KEEP:** 
- [x] GO:0080049 | L-gulono-1,4-lactone dehydrogenase activity | 2 EXP annotations >> keep and add RHEA:47248 & PMID:30112455
- [x] GO:0102053 | (-)-jasmonoyl-isoleucine synthetase activity | 4 EXP annotations
- same EC and RHEA as 'jasmonoyl-leucine synthetase activity' and 'jasmonoyl-valine synthetase activity'  >> see https://github.com/geneontology/go-ontology/issues/26578
- [ ] GO:0018657 | toluene 3-monooxygenase activity : 0 annotations
- [x] GO:0018644 toluene 2-monooxygenase activity:  0 annotations >> but has EC and RHEA
- [x] GO:0018638 toluene 4-monooxygenase activity also has 0 annotations >> EC:1.14.13.236 & RHEA:41380 (missing from GO) 

Biological processes:
- [x] GO:0019426 | bisulfite reduction | 0 annotations
- [x] GO:0009444 | pyruvate oxidation | 1 EXP annotation
- [x] GO:0019424 | sulfide oxidation, using siroheme sulfite reductase | 2 EXP annotations

**Comment by sjm41** [comment]
If we obsolete this one:
GO:0019424 | sulfide oxidation, using siroheme sulfite reductase | 2 EXP annotations
, which has the obsolete MetaCyc xref P223-PWY, then should also remove 'MetaCyc:P223-PWY' from the definition of the parent term:

id: GO:0019418
name: sulfide oxidation
namespace: biological_process
def: "The chemical reactions and pathways resulting in the conversion of sulfide to elemental sulfur in a higher oxidation state, or to sulfite or sulfate." [MetaCyc:P222-PWY, MetaCyc:P223-PWY, MetaCyc:PWY-5274, MetaCyc:PWY-5285]
synonym: "sulphide oxidation" EXACT []
xref: MetaCyc:P222-PWY
is_a: GO:0006790 ! sulfur compound metabolic process

**Comment by pgaudet** [comment]
Dear all, 
The proposal has been made to obsolete GO:0009444 pyruvate oxidation because it represents a molecular function.

**Comment by pgaudet** [comment]
Obsolete [toluene 3-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018657), no evidence that the reaction exists; not in RHEA, not in EC, not in MetaCyc nor in KEGG.
