### ISSUE TITLE
Term merge: GO:0018492 carbon-monoxide dehydrogenase (acceptor) activity & GO:0043885 carbon-monoxide dehydrogenase (ferredoxin) activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25872]
* **Term to be merged: Provide GO ID and term label**
GO:0018492 carbon-monoxide dehydrogenase (acceptor) activity

* **Which term do you propose this term merge into? Provide GO ID and term label**
GO:0043885 carbon-monoxide dehydrogenase (ferredoxin) activity

* **Reason for merge**
-- both terms have same EC and MetaCyc xrefs  (note the MetaCyc xref needs updating to '1.2.7.4-RXN')
-- both those xrefs specify the acceptor as ferredoxin
-- the RHEA:21040 xref on GO:0018492 also specifies the acceptor as ferredoxin

* **Other information**
If it's not appropriate to merge, then GO:0043885 should be made a child of GO:0018492

id: GO:0018492
name: carbon-monoxide dehydrogenase (acceptor) activity
def: "Catalysis of the reaction: CO + H2O + acceptor = CO2 + reduced acceptor." [EC:1.2.7.4]
synonym: "anaerobic carbon monoxide dehydrogenase activity" RELATED [EC:1.2.7.4]
synonym: "carbon monoxide dehydrogenase activity" BROAD []
synonym: "carbon-monoxide:acceptor oxidoreductase activity" RELATED [EC:1.2.7.4]
xref: EC:1.2.7.4
xref: MetaCyc:CARBON-MONOXIDE-DEHYDROGENASE-RXN
xref: RHEA:21040
xref: UM-BBD_enzymeID:e0415
is_a: GO:0016903 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors

id: GO:0043885
name: carbon-monoxide dehydrogenase (ferredoxin) activity
def: "Catalysis of the reaction: CO + H2O + oxidized ferredoxin = CO2 + reduced ferredoxin." [EC:1.2.7.4]
synonym: "carbon monoxide dehydrogenase (ferredoxin) activity" EXACT []
synonym: "carbon monoxide dehydrogenase activity" BROAD []
synonym: "carbon-monoxide dehydrogenase activity" BROAD [EC:1.2.7.4]
synonym: "carbon-monoxide,water:ferredoxin oxidoreductase activity" EXACT []
synonym: "carbon-monoxide:(acceptor) oxidoreductase activity" EXACT []
synonym: "CO dehydrogenase activity" EXACT []
synonym: "CO-dehydrogenase (ferredoxin) activity" EXACT []
synonym: "CO-dehydrogenase activity" EXACT []
synonym: "CODH" RELATED []
xref: EC:1.2.7.4
xref: MetaCyc:CARBON-MONOXIDE-DEHYDROGENASE-RXN
is_a: GO:0016625 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors, iron-sulfur protein as acceptor

**Comment by pgaudet** [comment]
https://amigo.geneontology.org/amigo/term/GO:0043885 >> no annotations.
