### ISSUE TITLE
NTR: hemozoin formation complex

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#25878]
Please provide as much information as you can: 

* **Suggested term label:**
hemozoin formation complex

* **Definition (free text)**
*  In Plasmodium genus, the hemozoin formation complex is involved in hemoglobin degradation and detoxification of heme in the food vacuole during the asexual blood stage. It is composed of at least falcipains FP2A and/or FP2B, plasmepsins PMII, PMIII/HAP and PMIV, heme detoxifying protein HDP and falcilysin FLN.

* **Reference, in format PMID:23471987**
(REQUIRED)

* **Gene product name and ID to be annotated to this term**
UniProt ID
Q8I6U4
Q8I6U5
Q8I6V3
Q8IM16
Q8IL04
Q8IM15
Q76NL8

* **Parent term(s)**
GO:0032991

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160092
+name: hemozoin formation complex
+namespace: cellular_component
+def: "A protein-containing complex involved in hemoglobin degradation and detoxification of heme in the food vacuole during the asexual blood stage of a Plasmodium. It is composed of at least falcipains FP2A and/or FP2B, plasmepsins PMII, PMIII/HAP and PMIV, heme detoxifying protein HDP and falcilysin FLN." [PMID:23471987]
+is_a: GO:0032991 ! protein-containing complex
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25878" xsd:anyURI
+created_by: rynl
+creation_date: 2023-08-16T17:14:30Z
