### ISSUE TITLE
GO:0019726, EC number linked to this term has been deleted

### ISSUE THREAD

**Issue by kaxelsen** [geneontology/go-ontology#25880]
The EC number (EC 1.1.1.33) has been deleted based on pmid:4463942 where the enzyme has been shown to actually belong to EC 1.1.1.2. The change will become public in release 2024_01 scheduled for January 17 2024.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete  GO:0019726 mevaldate reductase (NADPH) activity. The reason for obsoletion is that the associated EC number has been deleted (EC 1.1.1.33), based on PMID:4463942 where the enzyme has been shown to actually belong to EC 1.1.1.2.


There are no manual annotations to this term. This term is not in any subset. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25880

Thanks, Pascale
