### ISSUE TITLE
please help add missing cell-cell signaling terms

### ISSUE THREAD

**Issue by LiNiMGI** [geneontology/go-ontology#25933]
With the decision to eliminate the 'involved in' terms and convert them to GO-CAM models( go-annotation: Check annotations to signaling involved in x https://github.com/geneontology/go-annotation/issues/4681 ) we are missing some cell-cell signal terms in the GO, please help add them:

For obsolete "epiblast cell-extraembryonic ectoderm cell signaling involved in anterior/posterior axis specification GO:0060802, 

please add:
epiblast cell-extraembryonic ectoderm cell signaling
Definition: Any process that mediates the transfer of information from an epiblast cell to an extraembryonic ectoderm cell.
Please add as a child term of cell-cell signaling GO:0007267 

For obsolete "cerebellar Purkinje cell-granule cell precursor cell signaling involved in regulation of granule cell precursor cell proliferation GO:0021937, 

please add:
cerebellar Purkinje cell-granule cell precursor cell signaling
Definition: Any process that mediates the transfer of information from Purkinje cells to granule cell precursors.
Please add  as a child term of cell-cell signaling GO:0007267 

Thanks,
Li

**Comment by raymond91125** [comment]
https://github.com/geneontology/go-annotation/issues/4681
https://github.com/geneontology/go-ontology/issues/25766

**Comment by LiNiMGI** [comment]
feel free to revise the term label and definition, thanks!

**Comment by raymond91125** [comment]
May have to wait for @pgaudet to comment.

**Comment by pgaudet** [comment]
@LiNiMGI 
We are discussing this on the ontology call: 

> epiblast cell-extraembryonic ectoderm cell signaling involved in anterior/posterior axis specification GO:0060802

Do you know if this type of signaling only occurs in anterior/posterior axis specification  ? (in this case we improve the label and definition of the existing term, and not obsolete.

**Comment by LiNiMGI** [comment]
@pgaudet Sorry I am not an expert on that.
However, David found a paper that might be helpful: PMID:16793258.
Thanks
