### ISSUE TITLE
NTR: cuproptosis

### ISSUE THREAD

**Issue by paulacalipho** [geneontology/go-ontology#25942]
Please provide as much information as you can: 

* **Suggested term label:**
cuproptosis

* **Definition (free text)**
Programmed cell death resulting from mitochondrial proteotoxic stress mediated by copper and FDX1.

* **Reference**
PMID:35354936

* **Gene product name and ID to be annotated to this term**
FDX1 (P10109)

* **Parent term(s)**
GO:0012501

* **Children terms (if applicable)** -

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)** -

* **Cross-references** -

* **Any other information** -

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160119
+name: cuproptosis
+namespace: biological_process
+def: "A programmed cell death process that is induced by intracellular copper accumulation." [PMID:35298263, PMID:35354936]
+is_a: GO:0012501 ! programmed cell death
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25942" xsd:anyURI
+created_by: rynl
+creation_date: 2023-10-27T21:19:19Z
