### ISSUE TITLE
Obsoletion request: GO:0060820 - inactivation of X chromosome by heterochromatin formation

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#25959]
Please provide as much information as you can:

* **GO term ID and Label**
 GO:0060820 - inactivation of X chromosome by heterochromatin formation

* **Reason for deprecation** Put an x in the appropriate box: 
 - [ ]  The reason for obsoletion is that the meaning of the term is ambiguous.

All X chromosome inactivation (XCI) in theria involves heterochromatin formation, whether imprinted or random. In addition, heterochromatin formation is not part of the initiating event, but a downstream step required for maintenance. Thus this term does not represent a distinct process, but a step that occurs in both types of XIC that occur in theria, perhaps also in "**dosage compensation by hypoactivation of X chromosome**", the form of sex chromosome dosage compensation that occurs in C. elegans.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term - **NO**

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

- GO:0060820 - inactivation of X chromosome by heterochromatin formation
- GO:0060816 - random inactivation of X chromosome

* **Are there annotations to this term?**
- How many EXP:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/krc/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/krc/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Term   & Contributor | IMP | ISS | TAS | Grand Total
-- | -- | -- | -- | --
inactivation of X chromosome   by heterochromatin formation | 2 | 1 | 2 | 5
ARUK-UCL |   |   | 2 | 2
GO_Central | 1 |   |   | 1
UniProt | 1 | 1 |   | 2

</body>

</html>

** Reannotation comments
*** ARUK-UCL - should be "random X chromosome inactivation" since annotations are to human genes
*** UniProt - probably just delete this annotation since MGI and UniProt annotated the same paper and I've already reannotated to most specific terms
*** GO_Central - This is a C. elegans paper, which might suggest should use "GO:0042464 - dosage compensation by hypoactivation of X chromosome"

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by pgaudet** [comment]
Obsoleted - 2 UCL annotations to review here: https://github.com/geneontology/go-annotation/issues/4714
