### ISSUE TITLE
Update term name: "dosage compensation" GO:0007549

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#25961]
We should update the name of the term "**dosage compensation**" (GO:0007549) to be consistent with its definition that is specific to "**sex chromosome dosage compensation**", as the phrase "dosage compensation" is also used in other contexts, e.g. rDNA copies (see below).

**Proposed changes:**

- [x] change name from "dosage compensation" to "sex-chromosome dosage compensation"
- [x] add EXACT synonym "sex chromosome dosage compensation"
- [x] update Wikipedia xref to current name: Wikipedia:https://en.wikipedia.org/wiki/Sex-chromosome_dosage_compensation

----

Razzaq A, Bejaoui Y, Alam T, Saad M, El Hajj N. **Ribosomal DNA Copy Number Variation is Coupled with DNA Methylation Changes at the 45S rDNA Locus.** Epigenetics. 2023 Dec;18(1):2229203. doi: 10.1080/15592294.2023.2229203. PMID:37368968

**Abstract:** 
> The human ribosomal DNA (rDNA) copy number (CN) has been challenging to analyse, and its sequence has been excluded from reference genomes due to its highly repetitive nature. The 45S rDNA locus encodes essential components of the cell, nevertheless rDNA displays high inter-individual CN variation that could influence human health and disease. CN alterations in rDNA have been hypothesized as a possible factor in autism spectrum disorders (ASD) and were shown to be altered in Schizophrenia patients. We tested whether whole-genome bisulphite sequencing can be used to simultaneously quantify rDNA CN and measure DNA methylation at the 45S rDNA locus. Using this approach, we observed high inter-individual variation in rDNA CN, and limited intra-individual copy differences in several post-mortem tissues. Furthermore, we did not observe any significant alterations in rDNA CN or DNA methylation in Autism Spectrum Disorder (ASD) brains in 16 ASD vs 11 control samples. Similarly, no difference was detected when comparing neurons form 28 Schizophrenia (Scz) patients vs 25 controls or oligodendrocytes from 22 Scz samples vs 20 controls. However, our analysis revealed a strong positive correlation between CN and DNA methylation at the 45S rDNA locus in multiple tissues. This was observed in brain and confirmed in small intestine, adipose tissue, and gastric tissue. **This should shed light on a possible dosage compensation mechanism that silences additional rDNA copies to ensure homoeostatic regulation of ribosome biogenesis.**

**Keywords:** Autism spectrum disorder; Copy number; DNA methylation; **Dosage compensation**; Ribosomal DNA; Schizophrenia.

**Comment by pgaudet** [comment]
Also added references about birds and reptiles to explain dosage compensation in these species (does not involved X chromosomes) .
