### ISSUE TITLE
NTR: transforming growth factor beta receptor superfamily signaling pathway

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#25962]
Please provide as much information as you can: 

* **Suggested term label:**

transforming growth factor beta receptor superfamily signaling pathway

* **Definition (free text)**

The series of molecular signals initiated by an extracellular ligand binding to a member of the transforming growth factor receptor superfamily, and ending with the regulation of a downstream cellular process, e.g. transcription.

* **Reference, in format PMID:#######**

PMID: 28096268
PMID: 22651914

* **Gene product name and ID to be annotated to this term**

This will be used to annotate some C. elegans genes, e.g. daf-1, a Type I receptor, that participate in signaling pathways that don't necessarily neatly map on to one of the existing subclasses of TGFbeta superfamily signaling, i.e. activin, BMP, or TGFbeta.

* **Parent term(s)**

GO:0007178. transmembrane receptor protein serine/threonine kinase signaling pathway

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

activin receptor signaling pathway (GO:0032924)
BMP receptor signaling pathway (GO:0030509)
transforming growth factor beta receptor signaling pathway (GO:0007179)

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

Please also see:  https://github.com/geneontology/go-ontology/issues/23449

**Comment by ValWood** [comment]
perhaps  "only in metazoa"?  (at lerast never in fungi ?)
