### ISSUE TITLE
GO:0008940 nitrate reductase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25967]
id: GO:0008940
name: nitrate reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: nitrite + acceptor = nitrate + reduced acceptor." [EC:1.7.99.4]
synonym: "nitrate reductase (acceptor)" RELATED [EC:1.7.99.4]
synonym: "nitrite:(acceptor) oxidoreductase" RELATED [EC:1.7.99.4]
synonym: "nitrite:acceptor oxidoreductase" RELATED [EC:1.7.99.4]
synonym: "respiratory nitrate reductase activity" NARROW [EC:1.7.99.4]
xref: EC:1.7.99.4
xref: MetaCyc:NITRATREDUCT-RXN
xref: RHEA:21068
is_a: GO:0016661 ! oxidoreductase activity, acting on other nitrogenous compounds as donors

EC:1.7.99.4 (and MetaCyc:NITRATREDUCT-RXN) are obsolete (also see #24932) and should be removed from this GO term.
The RHEA:21068 looks good though, and should be used as the reference for the definition - just need to add H2O on the left-hand side of the reaction (https://www.rhea-db.org/rhea/21068)

EC:1.7.99.4 has been transferred to:
EC 1.7.1.1 = GO:0009703 nitrate reductase (NADH) activity
EC 1.7.1.2 = GO:0050463 nitrate reductase [NAD(P)H] activity
EC 1.7.1.3 = GO:0050464 nitrate reductase (NADPH) activity
EC 1.7.5.1 = (not in GO)
EC 1.7.7.2 = GO:0047889 ferredoxin-nitrate reductase activity

GO:0050463 is already a child of GO:0008940, so I'd suggest the other 3 GO terms are also made children, and then we retain 
GO:0008940 as a grouping term, rather than obsoleting it. (There are 24 EXP annotations directly to GO:0008940, and these can all be retained if we keep it as a grouping term.)

**Comment by raymond91125** [comment]
https://github.com/geneontology/go-ontology/issues/27410

**Comment by raymond91125** [comment]
Also transferred to EC:1.9.6.1 = GO:0050140

**Comment by pgaudet** [comment]
Obsolete child GO:1903264 nitrate reductase activity involved in anaerobic electron transport chain 

MF part of BP
No annotations.
