### ISSUE TITLE
NTR:  How to annotatate intron specific splicing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#25978]
I have a splicing paper and I don't know which GO term to use.

PMID:36095128
--
Title | Splicing of branchpoint-distant exons is promoted by Cactin, Tls1 and the ubiquitin-fold-activated Sde2.
Authors | Anil AT, Choudhary K, Pandian R, Gupta P, Thakran P, Singh A, Sharma M, Mishra SK
Publication date | 2022 09 12

Basically, the authors show very clearly that a set of 3 conserved proteins are required for intron-specific splicing.
Sde2 (A ubiquitin fusion protein, ubiquitin is removed from the active form) (human SDE2) 
Tls1 (human C9orf78/TLS1) and
Cay1 (human cactin)

In their absence constitutive splicing is fine, but introns with a longer branch site to acceptor distance are spliced inefficiently.

In humans TLS1 has been shown to facilitate alternative splicing but in fission yeast, it is probably only required to excise these **"weak"** introns with longer branch to acceptor distance. It is possible that this could be regulating splicing in some way but this isn't clear to me if it is regulation in the "GO" sense.

So which term would I use to describe this process? Just 

GO:0045292 | mRNA cis splicing, via spliceosome
doesn't seem sufficient.  But I don't see anything suitable under here.

Any suggestions?

@pgaudet @vanaukenk @krchristie 

Requirement is quite precise:
This result indicated that Sde2-C becomes critical for using the 3′ss at ≥21 nt from the BP (Figure 3C).

**Comment by Antonialock** [comment]
Hmm yes, I only annotated to the general term "mRNA cis splicing, via spliceosome".

The UniProt text descriptions ended up looking slightly different for pombe and human, but perhaps  "mRNA 3'-splice site recognition " would fit both descriptions, do you agree?

**POMBE**
**Plays a role in pre-mRNA splicing by facilitating excision of introns featuring long spacing between the branchpoint and 3'-splice site** (PubMed:[36095128](https://www.uniprot.org/citations/36095128)).
Assists the splicing of several components involved in chromatin organization, such as several shelterin complex subunits (PubMed:[25245948](https://www.uniprot.org/citations/25245948), PubMed:[36095128](https://www.uniprot.org/citations/36095128)).

**HUMAN**
**Plays a role in pre-mRNA splicing by promoting usage of the upstream 3'-splice site at alternative NAGNAG splice sites; these are sites featuring alternative acceptor motifs separated by only a few nucleotides** (PubMed:[35241646](https://www.uniprot.org/citations/35241646)).
May also modulate exon inclusion events (PubMed:[35241646](https://www.uniprot.org/citations/35241646)).
Plays a role in spliceosomal remodeling by displacing WBP4 from SNRNP200 and may act to inhibit SNRNP200 helicase activity (PubMed:[35241646](https://www.uniprot.org/citations/35241646)).
Binds U5 snRNA (PubMed:[35241646](https://www.uniprot.org/citations/35241646)).
Required for proper chromosome segregation (PubMed:[35167828](https://www.uniprot.org/citations/35167828)).
Not required for splicing of shelterin components (PubMed:[35167828](https://www.uniprot.org/citations/35167828)).

**Comment by ValWood** [comment]
OK , I will annotate to  GO:0045292 | mRNA cis splicing, via spliceosome for now. I have phenotypes for  the branch distance part so it would be easy to update if new terms are added later.

**Comment by krchristie** [comment]
Is this term appropriate?

[Term]
id: GO:0000380
name: alternative mRNA splicing, via spliceosome
namespace: biological_process
def: "The process of generating multiple mRNA molecules from a given set of exons by differential use of exons from the primary transcript(s) to form multiple mature mRNAs that vary in their exon composition." [GOC:krc, PMID:12110900]
comment: Note that this process most commonly occurs in cis, selecting or skipping exons from the same primary transcript, but it has also been observed to occur in trans at low frequency, at least in some mammals.
synonym: "alternative nuclear mRNA splicing, via spliceosome" EXACT [GOC:vw]
synonym: "splice site selection" BROAD []
is_a: GO:0000398 ! mRNA splicing, via spliceosome

**Comment by ValWood** [comment]
Hmm, I think it could be used for human, but there isn't any evidence in pombe that there is alternative splicing controlled by this process. The targets appear to be genes involved in heterochromatin assembly, and  seems likely that there is a regulatory role  (controlled processing of sde2 to initiate correct splicing when these are components are  required. The mispliced proteins are  short and truncated truncated). For now I will stick with just splicing. 

For the alternative splicing  I noticed that it isn't under cis splicing which may explain why it was missed. There is a comment
"Note that this process most commonly occurs in cis, selecting or skipping exons from the same primary transcript, but it has also been observed to occur in trans at low frequency, at least in some mammals." does anyone know the source of that comment and if it definitely results in functional proteins.  I know that sequencing can occasionally produce chimeras with look like trans-spliced products, and it seems that by definition alternative splicing must be cis  (  alternative trans splicing woulfd be just 'trans splicing' to as different exon.

Alternative splicing is a cellular process in which exons **from the same gene** are joined in different combinations, leading to different, but related, mRNA transcripts.

**Comment by krchristie** [comment]
> For the alternative splicing I noticed that it isn't under cis splicing which may explain why it was missed. There is a comment "Note that this process most commonly occurs in cis, selecting or skipping exons from the same primary transcript, but it has also been observed to occur in trans at low frequency, at least in some mammals." does anyone know the source of that comment and if it definitely results in functional proteins. I know that sequencing can occasionally produce chimeras with look like trans-spliced products, and it seems that by definition alternative splicing must be cis ( alternative trans splicing woulfd be just 'trans splicing' to as different exon.

Considering the GO ID and the fact that I am cited as a definition dbxref, I am probably the source of that comment. It has been a very long time since I worked on those terms, so I no longer remember why I wrote it, but I'm sure there must have been indications in the literature that alternative splicing was occasionally observed in trans-splicing.

**Comment by ukemi** [comment]
PMID:14522953?

**Comment by ValWood** [comment]
Thanks!
So there should probably be 2 terms
alternative cis-splicing and alternative trans-splicing?

**Comment by ValWood** [comment]
OK, in that case  I will go with alternative splicing, but since  I try to keep all our splicing annotation under "cis splicing" is there any objection if I add
alternative cis-splicing and alternative trans-splicing?

Seems that it could be useful to separate these. The Drosophila example appears to use the allele on the opposite strand which is very funky and most likely involves different machinery?

**Comment by ValWood** [comment]
I'll do a bit of digging and look at the existing annotations before I add anything.

**Comment by ValWood** [comment]
there is already a descendant
GO:0000366   intergenic mRNA trans splicing

**Comment by krchristie** [comment]
> there is already a descendant GO:0000366 intergenic mRNA trans splicing

This isn't explicitly stated to be alternative splicing, only a different type of trans splicing than its sibling term "[mRNA trans splicing, SL addition" (GO:0045291)

**Comment by ValWood** [comment]
It (GO:0000366 intergenic mRNA trans splicing) is a descendant of alternative splicing though...so implicitly it is...(maybe shouldn't be)?

**Comment by krchristie** [comment]
> It (GO:0000366 intergenic mRNA trans splicing) is a descendant of alternative splicing though...so implicitly it is...(maybe shouldn't be)?

One of the papers cited for the definition calls it trans-splicing in the abstract (the other is a review). I's suggest checking that paper and make sure that this term is appropriate for your needs or whether you need a new term.

**Comment by ValWood** [comment]
It seems I meant to close this as a duplicate but didn't
