### ISSUE TITLE
GO:0050155 ornithine(lysine) transaminase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25975]
id: GO:0050155
name: ornithine(lysine) transaminase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2-oxoglutarate + L-ornithine = H2O + L-glutamate + 3,4-dihydro-2H-pyrrole-2-carboxylate." [MetaCyc:ORNITHINELYSINE-AMINOTRANSFERASE-RXN]
synonym: "L-ornithine(L-lysine):2-oxoglutarate-aminotransferase activity" EXACT []
synonym: "L-ornithine:2-oxoglutarate-aminotransferase activity" EXACT []
synonym: "lysine/ornithine:2-oxoglutarate aminotransferase activity" EXACT []
synonym: "ornithine(lysine) aminotransferase activity" EXACT []
xref: EC:2.6.1.13
xref: MetaCyc:ORNITHINELYSINE-AMINOTRANSFERASE-RXN
is_a: GO:0008483 ! transaminase activity

This term is defined by (and has an xref to) an obsolete MetaCyc ID (ORNITHINELYSINE-AMINOTRANSFERASE-RXN).

I suggest the following:

- [ ] Change name to match current EC:2.6.1.13 name, "ornithine aminotransferase activity"
- [ ] Change def to match current EC:2.6.1.13 def, "a 2-oxocarboxylate + L-ornithine <=> an L-alpha-amino acid + L-glutamate 5-semialdehyde"
- [ ] Change MetaCyc xref to MetaCyc:ORNITHINE--OXO-ACID-AMINOTRANSFERASE-RXN
- [ ] Add RHEA:13877 xref

FYI, there are just 2 EXP annotations to this GO term (to human OAT (P04181) by UniProt)

**Comment by raymond91125** [comment]
Isn't this the same MF as GO:0004587 ornithine-oxo-acid transaminase activity? @sjm41

**Comment by raymond91125** [comment]
https://en.wikipedia.org/wiki/Ornithine(lysine)_transaminase 
https://www.enzyme-database.org/query.php?ec=2.6.1.68 got split in two
EC:2.6.1.13 GO:0004587 ornithine-oxo-acid transaminase activity
EC:2.6.1.36 GO:0045484 L-lysine 6-transaminase activity
Perhaps we should obsolete GO:0050155 ornithine(lysine) transaminase activity with consider GO:0004587, GO:0045484.

**Comment by sjm41** [comment]
Thanks @raymond91125 !
Can you also tweak the GO def so it matches the EC/RHEA def, so:
"Catalysis of the reaction: a 2-oxocarboxylate + L-ornithine <=> an L-alpha-amino acid + L-glutamate 5-semialdehyde"
