### ISSUE TITLE
Fix labels for GO:0052151 positive regulation by symbiont of host apoptotic process  GO:0052150 modulation by symbiont of host apoptotic process  GO:0033668 suppression by symbiont of host apoptotic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#25986]
- [x] GO:0052151 positive regulation by symbiont of host apoptotic process  >> symbiont-mediated induction of host apoptosis
- [x] GO:0052150 modulation by symbiont of host apoptotic process  >> symbiont-mediated perturbation of host apoptosis
- [x] GO:0033668 suppression by symbiont of host apoptotic process >> symbiont-mediated suppression by symbiont of host apoptotic process >> 'symbiont-mediated suppression of host apoptosis'
- [x] GO:0052040 modulation by symbiont of host programmed cell death >> 'symbiont-mediated perturbation of host programmed cell death'
- [x] GO:0052042 induction by symbiont of host programmed cell death >> 'symbiont-mediated activation of host programmed cell death'
- [x] GO:0052150 modulation by symbiont of host apoptotic process >> 'symbiont-mediated perturbation of host apoptosis'
- [x] GO:0034053 modulation by symbiont of host defense-related programmed cell death >> 'symbiont-mediated perturbation of host defense-related programmed cell death'
- [x] GO:0052041 suppression by symbiont of host programmed cell death >> 'symbiont-mediated suppression of host programmed cell death'

Change definitions to 
"A process in which a symbiont gene product affects/inhibits/activates host programmed cell death/apoptosis, leading to a decrease in the frequency, rate or extent of programmed cell death /apoptosis in the host cell. The host is defined as the larger of the organisms involved in a symbiotic interaction.

**Comment by pgaudet** [comment]
@genegodbold 
for activation we dont have references; can you please provide some?

**Comment by pgaudet** [comment]
PR is here: https://github.com/geneontology/go-ontology/pull/25987/commits/4e9330bb4e156108c5fb2d821b00638ea01de5eb

**Comment by genegodbold** [comment]
**Bacterial**
- **Hemolyin co-regulated protein** (Hcp) from _Aeromonas hydrophila_: Hcp induces apoptosis via induction of caspase-3 [PMID:18037263].
- **Flagellar secreted protein A2** (FspA2) from _Campylobacter jejuni_: FspA2 is secreted via the T3SS of C. jejuni into the supernatant. FspA2 binds to INT407 cells and, after a 4h incubation, causes apoptosis which is much faster than the apoptosis induced by the cytolethal distending toxin of C. jejuni [PMID:17517862].
- **Chlamyidial protein associating with death domains** (CADD, CT610) from _Chlamydia trachomatis_: CADD associates with mammalian death receptors both in vitro and in vivo and can induce apoptosis in a number of mammalian cell lines. Apoptosis was blocked by inhibitors of caspase activation. CADD interacts with death domains of tumor necrosis factor family receptors TNFR1, Fas, DR4, and DR5 but not with downstream adaptors [PMID:11805081].
- _Clostridioides difficile_ transferase, subunit A (**CDTa**): CDT induces apoptosis of blood eosinophils in mice during _C. difficile_ infection [PMID:27573114].
- **Bundle-forming pilus A** (BfpA) from _Escherichia coli_: Mutant bacteria in which BfpA was not expressed did not induce apoptosis in host cells with which they were associated [PMID:15963045].
- **EspF** from _Escherichia coli_ is T3SS LEE effector that is directed to the host mitochondria via its N terminal sequence and is involved in mitochondrial membrane permeabilization [PMID:15533930]. EspF induces release of cytochrome c and cleavage of caspases 3 and 9. EspF is thus responsible for instigation of host cell death in a process that resembles (at least partially) apoptosis. Entry of EspF into the mitochondria is crucial for EPEC infection. EPEC that express a nonfunctional EspF are severely attenuated in their ability to cause host cell death [PMID:15469437]. 
- **Intracellular growth locus C** (IglC; Hcp; FTN_1322) from _Francisella tularensis_: IglC induces apoptosis in macrophage-like cells [PMID:15519043].
- **CtkA** from _Helicobacter pylori_ is a an autophosphorylating serine/threonine kinase that induces apoptosis in cultured mouse macrophages (RAW264.7 cells)[PMID:25172221].

**Viral**
- **E183L** (p54) from African swine fever virus: E183L (p54) that lacks a 13 residue host dynein-binding motif loses the ability to induce the initiation of apoptosis through host caspase-9 and host caspase-3. p54 interacts with one of the light chains of host cytoplasmic dynein to enable viral transport through the cytosol along microtubules. Transiently expressed p54 is able to induce apoptosis in Vero cells [PMID:15225638].
- **Nonstructural protein 3** (NS3) from Dengue flavivirus: NS3 induces apoptosis in transiently transfected Vero cells [PMID:12867651].
- **E1A** from human adenovirus stabilizes host p53 and induces p53-dependent apoptosis [PMID:16037790].
- **Infected cell protein 27** (ICP27) from Human herpesvirus 1: When expressed ectopically in HeLa cells, ICP27 induces host p38 MAPK signaling and subsequent apoptosis [PMID:19073744]. ICP27 induces apoptosis when expressed in HEK293T cells by promoting the mitochondrial translocation of host Bax. ICP27 promotes this translocation by its inhibition of the 14-3-30 protein which normally sequesters Bax. ICP27 increases the acetylation of host 14-3-30 by increasing its interaction with host SIRT2 [PMID:28256197].

**Eukaryotic** (Note that there are dozens if not hundreds of virulence factors from fungal plant pathogens that induce some form of programmed cell death. But I'm picking two mammalian pathogens)
- **Giardipain-1** from _Giardia duodenalis_: Upon exposure to the purified cysteine protease giardipain-1, epithelial cells (IEC-6) bleb membrane and expose phosphatidylserine on the outer cell surface, both indications of apoptosis [PMID:29571981].
- **Programmed cell death 5** (PDCD5) from _Toxoplasma gondii_: PDCD5 from Toxoplasma gondii enhances apoptosis of uninfected host macrophages. Addition of recombinant PDCD5 to culture medium enhances host cell apoptosis triggered by etoposide in the macrophage cell line J774A.1. PDCD5 can also induce apoptosis in the presence of interferon-gamma [PMID:18406478]. Overexpression of PDCD5 in a strain of T. gondii leads to increased apoptosis in interferon-gamma treated macrophages [PMID:19801898].
