### ISSUE TITLE
Add RHEA xref to GO:0052590 sn-glycerol-3-phosphate:ubiquinone oxidoreductase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25984]
Add [RHEA:28755](https://www.rhea-db.org/rhea/28755) xref to this term:

id: GO:0052590
name: sn-glycerol-3-phosphate:ubiquinone oxidoreductase activity
namespace: molecular_function
def: "Catalysis of the reaction: sn-glycerol 3-phosphate + a ubiquinone = glycerone phosphate + a ubiquinol." [MetaCyc:RXN0-5260]
comment: Note that enzymes classified as EC:1.1.5.3 have several activities. They should be annotated with the terms GO:0004368, GO:0052590 and GO:0052591.
xref: EC:1.1.5.3
xref: MetaCyc:RXN0-5260
is_a: GO:0004368 ! glycerol-3-phosphate dehydrogenase (quinone) activity

**Comment by pgaudet** [comment]
Hi @sjm41 

Just wondering - we have this structure, with single children in each case
 GO:0004368 glycerol-3-phosphate dehydrogenase (quinone) activity (11 EXP) > RHEA:18977 
-  GO:0052590 sn-glycerol-3-phosphate:ubiquinone oxidoreductase activity  (1 EXP) > RHEA:28755
- - GO:0052591 sn-glycerol-3-phosphate:ubiquinone-8 oxidoreductase activity > RHEA:28751 

All 3 are linked to  EC:1.1.5.3, but have different RHEAs, but the two more specific RHEAs (RHEA:28751 and RHEA:28755) have no entries mapped to it. 

The GO comment "Note that enzymes classified as EC:1.1.5.3 have several activities. They should be annotated with the terms GO:0004368, GO:0052590 and GO:0052591." is strange, as it refers to these 3 terms, which are parent/children. 

I would like to propose obsoletion of GO:0052590  and GO:0052591, unless you have a reason to keep them?

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete  GO:0052590 sn-glycerol-3-phosphate:ubiquinone oxidoreductase activity and  GO:0052591 sn-glycerol-3-phosphate:ubiquinone-8 oxidoreductase activity. The reason for obsoletion is that these represent specific substrates, beyond the specificity of characterized enzymes. These will be replaced by the parent class: 
 GO:0004368 glycerol-3-phosphate dehydrogenase (quinone) activity. There is 1 RCA and 1 EXP to GO:0052590 sn-glycerol-3-phosphate:ubiquinone oxidoreductase activity by EcoCyc. 

There are no mappings; these terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/25984

Thanks, Pascale
