### ISSUE TITLE
GO:0018753 cyanuric acid amidohydrolase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25982]
id: GO:0018753
name: cyanuric acid amidohydrolase activity
namespace: molecular_function
def: "Catalysis of the reaction: cyanuric acid + H2O = biuret + CO2." [EC:3.5.2.15]
xref: EC:3.5.2.15
xref: MetaCyc:RXN-20062
xref: RHEA:14641
xref: UM-BBD_reactionID:r0116
is_a: GO:0016812 ! hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in cyclic amides

The EC and MetaCyc xrefs here match each other, but don't match the GO def.
In contrast, the RHEA xref here matches the GO def but doesn't match the EC/MetaCyc xref.
The EC:3.5.2.15 entry includes the comment "The product was initially thought to be bioret, but was later shown to be 1-carboxybioret", which is likely the root cause of the confusion.

EC:3.5.2.15 def is: cyanurate + H2O <=> 1-carboxybiuret + H(+)  <-- this is [RHEA:70363](https://www.rhea-db.org/rhea/70363)
MetaCyc:RXN-20062 def matches EC:3.5.2.15
RHEA:14641 def: cyanurate + H2O = biuret + CO2

I think the tasks here are:

- [ ] Change GO def to match current EC:3.5.2.15 def
- [ ] Change RHEA xref from RHEA:14641 to RHEA:70363

**Comment by sjm41** [comment]
Confirming the proposal above:

GO:0018753 has been used in 1,104 annotations (no EXP):
- 515 via EC:3.5.2.15
- 589 via UniRule:UR000540784 (which is associated with EC:3.5.2.15/Rhea:70363)

There are zero annotations to RHEA:14641 in UniProt

**Comment by pgaudet** [comment]
I am reopening because I would like to check with RHEA (@kaxelsen or @amorgat ) 
https://www.rhea-db.org/rhea/14641 is a multi-step reaction: RHEA:70363 and RHEA:70355; but only RHEA:70363 is annotated (as mentioned by @sjm41 ) 

Is this right ?

**Comment by kaxelsen** [comment]
Yes it is right as EC 3.2.1.15 in 2019 was updated by IUBMB from 
cyanuric acid + H2O = biuret + CO2 (RHEA:14641) to
cyanurate + H2O <=> 1-carboxybiuret + H(+) (RHEA:70363)
The second step of the RHEA:14641 reaction
1-carboxybiuret + H+ = biuret + CO2 (RHEA:70355) can occur spontaneously according to e.g. pmid:33172891, Fig. 2

**Comment by pgaudet** [comment]
ok thank you!
