### ISSUE TITLE
GO:0044689 7,8-didemethyl-8-hydroxy-5-deazariboflavin synthase activity - def/xref mismatch

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25983]
id: GO:0044689
name: 7,8-didemethyl-8-hydroxy-5-deazariboflavin synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: 5-amino-6-(D-ribitylamino)uracil + 4-hydroxyphenylpyruvate + 2 S-adenosyl-L-methionine + H2O = 7,8-didemethyl-8-hydroxy-5-deazariboflavin + 2 5'-deoxyadenosine + 2 L-methionine + oxalate + ammonia + 4 H+." [GOC:mengo_curators, PMID:11948155, PMID:14593448]
synonym: "FO synthase" EXACT []
xref: EC:2.5.1.147
xref: MetaCyc:RXN-19229
xref: RHEA:55200
is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups
created_by: jl
creation_date: 2012-08-15T14:33:17Z

The GO def here doesn't match the EC:2.5.1.147/RHEA:55200/MetaCyc:RXN-19229 def:
5-amino-6-(D-ribitylamino)uracil + L-tyrosine + S-adenosyl-L-methionine = 2-iminoacetate + 5'-deoxyadenosine + 5-amino-5-(4-hydroxybenzyl)-6-(D-ribitylimino)-5,6-dihydrouracil + H+ + L-methionine

I'm not sure if the GO def should stay and the xrefs removed, or the GO def should be changed to match EC/RHEA...

There are ~5,000 annotations to GO:0044689, of which the vast majority are IEA via the EC xref.  There are only 2 EXP annotations from PMID:14593448.

**Comment by pgaudet** [comment]
This issue is that  EC:2.5.1.77 was split into EC:2.5.1.147 and EC:4.3.1.32, but this was not handled correctly in GO (we have the mapping to EC:2.5.1.147 and the definition of EC:4.3.1.32).

**Comment by pgaudet** [comment]
- [x] Fixed xrefs and definition on GO:0044689: 
-def: "Catalysis of the reaction: 5-amino-6-(D-ribitylamino)uracil + 4-hydroxyphenylpyruvate + 2 S-adenosyl-L-methionine + H2O = 7,8-didemethyl-8-hydroxy-5-deazariboflavin + 2 5'-deoxyadenosine + 2 L-methionine + oxalate + ammonia + 4 H+." [GOC:mengo_curators, PMID:11948155, PMID:14593448]
+def: "Catalysis of the reaction: 5-amino-5-(4-hydroxybenzyl)-6-(D-ribitylimino)-5,6-dihydrouracil + S-adenosyl-L-methionine = 5'-deoxyadenosine + 7,8-didemethyl-8-hydroxy-5-deazariboflavin + H+ + L-methionine + NH4+." [PMID:14593448, RHEA:55204]


- [x] Fixed parent from is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups to is_a: GO:0016841 ! ammonia-lyase activity
- [x] Created new term to describe activity of EC:2.5.1.147

+id: GO:0141093
+name: 5-amino-6-(D-ribitylamino)uracil--L-tyrosine 4-hydroxyphenyl transferase activity
+namespace: molecular_function
+xref: Catalysis of the reaction: 5-amino-6-(D-ribitylamino)uracil + L-tyrosine + S-adenosyl-L-methionine = 2-iminoacetate + 5'-deoxyadenosine + 5-amino-5-(4-hydroxybenzyl)-6-(D-ribitylimino)-5\,6-dihydrouracil + H+ + L-methionine. {xref="RHEA:55200", xref="PMID:25781338", xref="PMID:23072415", xref="PMID:11948155"}
+xref: EC:2.5.1.147
+xref: RHEA:55200
+is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25983" xsd:anyURI
+created_by: pg
+creation_date: 2023-09-07T11:46:06Z
+

**Comment by sjm41** [comment]
Thanks @pgaudet 
I'm going to re-open this to fix the MetaCyc xref:
- MetaCyc:RXN-19229 belongs on the new term GO:0141093 (EC:2.5.1.147)
- MetaCyc:RXN-19230 is the xref for GO:0044689 (EC:4.3.1.32)
