### ISSUE TITLE
GO:0033771 licodione synthase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#25989]
id: GO:0033771
name: licodione synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: H+ + liquiritigenin + NADPH + O2 = H2O + licodione + NADP+." [EC:1.14.14.140, RHEA:15697]
synonym: "(2S)-flavanone 2-hydroxylase activity" RELATED [EC:1.14.14.140]
synonym: "liquiritigenin,NADPH:oxygen oxidoreductase (licodione-forming) activity" RELATED [EC:1.14.14.140]
xref: EC:1.14.14.140
xref: KEGG_REACTION:R07198
xref: MetaCyc:RXN-19660
xref: RHEA:15697
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

The ExplorEnz site (https://www.enzyme-database.org/query.php?ec=1.14.14.140) and the MetaCyc:RXN-19660 page (https://biocyc.org/META/NEW-IMAGE?type=EC-NUMBER&object=EC-1.14.14.162) say that EC:1.14.14.140 has been transferred to (now included within) EC:1.14.14.162.

(The ExplorEnz page says this was done in 2018, so I'm not sure why this isn't reflected on the expasy site (https://enzyme.expasy.org/EC/1.14.14.140) @kaxelsen ?)

Assuming the ExplorEnz info is correct:

- [x] change EC xref to EC:1.14.14.162
- [x] change RHEA xref to [RHEA:57584](https://www.rhea-db.org/rhea/57584)
- [x] change MetaCyc xref to MetaCyc:RXN-19645
- [x] change GO name to match EC:1.14.14.162 (flavanone 2-hydroxylase)
- [x] change GO def to match EC:1.14.14.162 (a flavanone + [reduced NADPH—hemoprotein reductase] + O2 = a 2-hydroxyflavanone + H+ + [oxidized NADPH—hemoprotein reductase] + H2O)
- [x] remove EC:1.14.14.140-based synonyms
- [x] Change parent to GO:0016712 (oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen) = EC:1.14.14.-

There are only 9 annotations to GO:0033771 - 8 are IEA from EC:1.14.14.140, 1 is IEA from RHEA:15697

**Comment by sjm41** [comment]
Email reply from @kaxelsen :

As ExplorEnz is the official site for IUBMB EC nomenclature, it is a regrettable mistake in ENZYME that I'm thankful for you pointing out to me. It is being corrected this instance and will be public in release 2024_01 (January 17).

**Comment by kaxelsen** [comment]
As ExplorEnz is the official site for IUBMB EC nomenclature, it is a regrettable mistake in ENZYME that I'm thankful for you pointing out to me. It's being corrected this instance and will be public in release 2024_01 (January 17).

**Comment by sjm41** [comment]
Hi @pgaudet  I've made most of the fixes here, but I wasn't sure how to change the parent - could you do that (or tell me how to do it)? Thanks.

BTW, my pull request for the other changes failed, but I don't know why...error message wasn't helpful...so we'll need to sort that out too.

**Comment by sjm41** [comment]
@pgaudet I just re-ran the job, and it now seems fine - so the tasks I checked off are now in the master. I'll reassign to you for the parent change.

**Comment by pgaudet** [comment]
HI @sjm41 
I know why your PR failed yesterday - if you change a term label, you must keep the old label as a synonym. Can you add this back? Or it is incorrect? 

Thanks, Pascale

**Comment by sjm41** [comment]
Aha.  Now added as narrow match synonym.
Thanks!
