### ISSUE TITLE
clean up of transcriptional regulation terms: p53 signaling

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26003]
Finishing off https://github.com/geneontology/go-ontology/issues/12739

There are some terms related to the p53 pathway:

GO:0006978 | DNA damage response, signal transduction by   p53 class mediator resulting in transcription of p21 class mediator
GO:1902163 | negative regulation of DNA damage response, signal transduction by p53   class mediator resulting in transcription of p21 class mediator
GO:1902162 | regulation of DNA damage response, signal transduction by p53 class   mediator resulting in transcription of p21 class mediator
GO:1902164 | positive regulation of DNA damage response, signal transduction by p53   class mediator resulting in transcription of p21 class mediator

25 EXP, 2 extensions, no mappings 
see https://github.com/geneontology/go-annotation/issues/4721

**Comment by pgaudet** [comment]
Hi @raymond91125 

GO:0030330 DNA damage response, signal transduction by p53 class mediator has 2 children: 
- GO:0006977 DNA damage response, signal transduction by p53 class mediator resulting in cell cycle arrest and GO:0006978 DNA damage response, signal transduction by p53 class mediator resulting in transcription of p21 class mediator

Can you see if you find evidence that these are 2 different pathways? or are they different read outs for the same pathway? 

Thanks, Pascale

**Comment by raymond91125** [comment]
PMID:26931810 There are p21-dependent and independent cell cycle arrest caused by p53.

**Comment by pgaudet** [comment]
So then should it be merged with GO:0006977 DNA damage response, signal transduction by p53 class mediator resulting in cell cycle arrest? 

https://www.nature.com/articles/ncomms14728#:~:text=By%20inhibiting%20CDK%20activity%2C%20p21,DNA%20damage%20is%20less%20clear.

**Comment by raymond91125** [comment]
p21 does have functions other than cell cycle arrest PMID:31438587. I'm not quite sure how that would affect our decision.

I wonder if we should simply pare the single child leaf terms.

**Comment by raymond91125** [comment]
Perhaps not surprisingly, DNA damage response is broad and complex with cross talking.
Per PMID:36207426, DNA damage response, signal transduction by p53 class mediator can result in cell cycle arrest (p21-dependent and independent), apoptosis (p21-independent), and cellular senescence (p21-dependent and independent).
I suggest that we merge up to GO:0030330 DNA damage response, signal transduction by p53 class mediator since it has only one child after merging GO:0006978 into GO:0006977.
Although the siblings of GO:0030330, GO:0000077 DNA damage checkpoint signaling, and GO:0042772 DNA damage response, signal transduction resulting in transcription, are also in part mediated by p53.

**Comment by pgaudet** [comment]
Sounds good. Thanks for looking into this!

**Comment by raymond91125** [comment]
To summarize, we shall obsolete/replace these terms:
GO:0006978 DNA damage response, signal transduction by p53 class mediator resulting in transcription of p21 class mediator
GO:1902163 negative regulation of DNA damage response, signal transduction by p53 class mediator resulting in transcription of p21 class mediator
GO:1902162 negulation of DNA damage response, signal transduction by p53 class mediator resulting in transcription of p21 class mediator
GO:1902164 positive regulation of DNA damage response, signal transduction by p53 class mediator resulting in transcription of p21 class mediator
GO:0006977 DNA damage response, signal transduction by p53 class mediator resulting in cell cycle arrest
