### ISSUE TITLE
GO:0052665 tRNA (uracil-2'-O-)-methyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26016]
id: GO:0052665
name: tRNA (uracil-2'-O-)-methyltransferase activity
def: "Catalysis of the reaction: S-adenosyl-L-methionine + tRNA = S-adenosyl-L-homocysteine + tRNA containing 2'-O-methyluracil." [PMID:25626150, RHEA:43100]
synonym: "S-adenosyl-L-methionine:tRNA (uracil-2'-O-)-methyltransferase activity" RELATED [EC:2.1.1.34]
synonym: "S-adenosyl-L-methionine:tRNA uracil-2'-O-methyltransferase activity" RELATED [EC:2.1.1.211]
synonym: "transfer ribonucleate uracil 2'-methyltransferase activity" RELATED [EC:2.1.1.34]
synonym: "tRNA (uracil 2')-methyltransferase activity" RELATED [EC:2.1.1.211]
synonym: "tRNA uracil 2'-methyltransferase activity" RELATED [EC:2.1.1.211]
synonym: "tRNA uracil-2'-O-methyltransferase activity" RELATED [EC:2.1.1.211]
xref: EC:2.1.1.34
xref: MetaCyc:RXN0-5143
xref: RHEA:43100
is_a: GO:0016300 ! tRNA (uracil) methyltransferase activity
is_a: GO:0106050 ! tRNA 2'-O-methyltransferase activity
created_by: ai
creation_date: 2010-10-11T01:05:35Z

A few problems here:

- [x]  RHEA:43100 xref here looks OK, but it's for a more specific reaction than that given in the GO term name/def: "S-adenosyl-L-methionine + uridine44 in tRNASer = 2'-O-methyluridine44 in tRNASer + H+ + S-adenosyl-L-homocysteine"
- [x] EC:2.1.1.34 xref here is a mistake (= 'tRNA (guanosine(18)-2'-O)-methyltransferase', and it's correctly an xref on GO:0009020).
- [ ] Correct EC xref would be EC:2.1.1.211 to match RHEA:43100 (and be consistent with sources of synonyms listed above
- [ ] MetaCyc:RXN0-5143 is obsolete -  RXN-12368 would match EC:2.1.1.211 xref
- [ ] PMID:25626150 doesn't appear to mention this activity - remove
- [ ] 

Either need to re-name/re-define GO:0052665 to be more specific (consistent with RHEA:43100) and add correct EC/MetaCyc xrefs, or remove those xrefs and add those to a new child term.

**Comment by sjm41** [comment]
There are 2 EXP annotations to this term:
UniProtKB:P0AE01	trmJ 		IMP	PMID:16848900
UniProtKB:P0AGJ7	trmL	IDA	PMID:20855540

PMID:16848900 title is "The yfhQ gene of Escherichia coli encodes a tRNA:Cm32/Um32 methyltransferase "
PMID:20855540 title is "YibK is the 2'-O-methyltransferase TrmL that modifies the wobble nucleotide in Escherichia coli tRNA(Leu) isoacceptors"

So it seems it wouldn't be correct to annotate to "tRNA(Ser) (uridine(44)-2'-O)-methyltransferase "

So, better solution here is to:

- [ ] Keep current name and def on GO:0052665, keeping it as a more general term.
- [ ] Remove all current xrefs on GO:0052665
- [ ] Remove all current EC-based synonyms on GO:0052665
- [ ] Make new child term for the specific reaction corresponding to EC:2.1.1.211 / RHEA:43100 / RXN-12368

**Comment by pgaudet** [comment]
We should just obsolete GO:0052665 tRNA (uracil-2'-O-)-methyltransferase activity
This is too many changes

**Comment by sjm41** [comment]
Hi @pgaudet

I just ran into the above issues again.
Do you want to go ahead and obsolete GO:0052665 as you proposed above?


Looking at the current go-edit file, we currently have these two terms:

id: GO:0052665
name: tRNA (uracil-2'-O-)-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + tRNA = S-adenosyl-L-homocysteine + tRNA containing 2'-O-methyluracil." [PMID:25626150, RHEA:43100]
synonym: "tRNA (uracil 2')-methyltransferase activity" RELATED [EC:2.1.1.211]
synonym: "tRNA uracil 2'-methyltransferase activity" RELATED [EC:2.1.1.211]
synonym: "tRNA uracil-2'-O-methyltransferase activity" RELATED [EC:2.1.1.211]
xref: MetaCyc:RXN0-5143
is_a: GO:0016300 ! tRNA (uridine) methyltransferase activity
is_a: GO:0106050 ! tRNA 2'-O-methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26016" xsd:anyURI
created_by: ai
creation_date: 2010-10-11T01:05:35Z


id: GO:0141101
name: tRNA(Ser) (uridine(44)-2'-O-)-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: Catalysis of the reaction: S-adenosyl-L-methionine + uridine44 in tRNASer = 2'-O-methyluridine44 in tRNASer + H+ + S-adenosyl-L-homocysteine." [PMID:18025252, RHEA:43100]
synonym: "tRNA(Ser) (uracil(44)-2'-O-)-methyltransferase activity" EXACT []
xref: EC:2.1.1.211
xref: MetaCyc:RXN-12368
xref: RHEA:43100
is_a: GO:0016300 ! tRNA (uridine) methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26145" xsd:anyURI
created_by: pg
creation_date: 2023-09-19T10:20:05Z

**Comment by deustp01** [comment]
So is the fix to take our current annotations of human and budding yeast TRMT44 (Q8IYL2) to GO:0052665 / RHEA:43100 and re-annotate them to GO:0141101 / RHEA:43100?
Thanks.
