### ISSUE TITLE
MetaCyc:RXN0-5143 / GO:0052666 tRNA (cytosine-2'-O-)-methyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26018]
MetaCyc:RXN0-5143, an xref on the following grouping term, is obsolete:

id: GO:0052666
name: tRNA (cytosine-2'-O-)-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + tRNA = S-adenosyl-L-homocysteine + tRNA containing 2'-O-methylcytosine." [GOC:hjd]
synonym: "S-adenosyl-L-methionine:tRNA (cytosine-2'-O-)-methyltransferase activity" EXACT []
synonym: "S-adenosyl-L-methionine:tRNA cytosine-2'-O-methyltransferase activity" EXACT []
synonym: "transfer ribonucleate cytosine 2'-methyltransferase activity" EXACT []
synonym: "tRNA (cytosine 2')-methyltransferase activity" EXACT []
synonym: "tRNA cytosine 2'-methyltransferase activity" EXACT []
synonym: "tRNA cytosine-2'-O-methyltransferase activity" EXACT []
xref: MetaCyc:RXN0-5143
is_a: GO:0016427 ! tRNA (cytosine) methyltransferase activity
created_by: ai
creation_date: 2010-10-11T01:05:47Z

- [x] Remove MetaCyc:RXN0-5143 xref from GO:0052666

GO:0052666 has two more specific child terms, and MetaCyc xrefs can be added to them:

- [x] add MetaCyc:RXN-11869 to GO:0106059 tRNA (cytidine 56-2'-O)-methyltransferase activity
- [x] add MetaCyc:RXN-11866 to GO: 0106339 tRNA (cytidine 32-2'-O)-methyltransferase activity

**Comment by pgaudet** [comment]
I think we can improve this a bit more: 
1. obsolete the grouping term [tRNA (cytosine-2'-O-)-methyltransferase activity](http://purl.obolibrary.org/obo/GO_0052666), since neither MetaCyc, EC or RHEA have an equivalent concept
2. Add taxon constraints: 
- [tRNA (cytidine 56-2'-O)-methyltransferase activity](http://purl.obolibrary.org/obo/GO_0106059) only in Archae
- [tRNA (cytidine 32-2'-O)-methyltransferase activity](http://purl.obolibrary.org/obo/GO_0106339) never in Archae

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete  GO:0052666 tRNA (cytosine-2'-O-)-methyltransferase activity. The resson for obsoletion is that this is an unnecessary grouping term. Annotations should be moved to children: 

- GO:0106339 tRNA (cytidine 32-2'-O)-methyltransferase activity (eukaryotes and bacteria)
- GO:0106059 tRNA (cytidine 56-2'-O)-methyltransferase activity (archae)

There are 7 EXP annotations to this term by EcoCyc, FlyBase, and Reactome, see https://github.com/geneontology/go-annotation/issues/4730. There are no mappings to this term (mappings are to the more precise terms). 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/26018

Thanks, Pascale
