### ISSUE TITLE
Obsoletion request: [GO:0070209]ASTRA complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26022]
Please provide as much information as you can:

* **GO term ID and Label**

[GO:0070209]ASTRA complex

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x] The reason for obsoletion is that the data from the paper for which the term was requested can be accurately described using TTT complex.

The science has moved on here. 
This complex is a chaperone and this ASTRA designation includes the substrate. 
The complex is now referred to as  TTT complex GO:0110078
A protein complex responsible for the stabilisation of protein levels of the phosphatidylinositol 3-kinase-related protein kinase (PIKK) family proteins. The TTT complex can also be found as part of the ASTRA complex (GO:0070209). PMID:20810650 PMID:22505622 PMID:28827813

ASTRA complex was identified  using a non-functional tagged version of Tra1, that sticks abnormally strongly to Rvb1, Rvb2, Tel2, Tti1, Tti2, and Asa1.  
This observation was also published as info in PMID: 21642955, clearly stating to take this with a grain of salt because this is observed using a version of Tra1 that is incapable of assembling into SAGA (because of the presence of a tag in C-ter).

Now the field admits TTT as the name for this complex and a recent structural paper confirms it as a bona fide biochemical entity (PMID: 34233195). To conclude, ASTRA is obsolete and refers to something that is not totally accurate.

(I will suggest appropriate updates to TTT complex in another ticket)

* **"Consider" term(s) (ID and label)**

TTT complex GO:0110078
(I have put "consider", because  care must be taken to exclude substrates)

* **Are there annotations to this term?**
- How many EXP:

14
~(7) | PomBase~ DONE
(7) | SGD

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 

Not required, all EXP removed above
No IEA

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by srengel** [comment]
SGD done.

**Comment by ValWood** [comment]
Removed
has_part some "TTT complex"

**Comment by ValWood** [comment]
https://github.com/geneontology/go-announcements/issues/592

**Comment by ValWood** [comment]
Isn't obsoleted?

**Comment by pgaudet** [comment]
Are you sure you did it? It's not part of the PR: https://github.com/geneontology/go-ontology/commit/036ad24bb32305243c112da9045ce98808aaeec8

**Comment by ValWood** [comment]
I  mustn't have. Will also check the others in that pull request.
