### ISSUE TITLE
Taxon constraint: GO:0080188 gene silencing by RNA-directed DNA methylation

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#26020]
@pgaudet  Would be good to put a constraint on 
GO:0080188  gene silencing by RNA-directed DNA methylation
"This process has been shown in plants and in yeasts, but so far has not been detected in vertebrates, organisms that lack RNA-dependent RNA polymerase."

as found some mouse and fly genes annotated with this term (I will make an annotation ticket for this)

Add a taxon constraint: 
* * **only in taxon: <strike>Fungi and</strike> Viridiplantae
* * **~never in taxon: metazoa~ (not necessary based on only in Viridiplantae

**Comment by ValWood** [comment]
There is no DNA methylation in yeast.
please add never in fungi too.

**Comment by ValWood** [comment]
<br class="Apple-interchange-newline">

+ | − | (31) | Arabidopsis thaliana
-- | -- | -- | --
+ | − | (31) | Viridiplantae
+ | − | (9) | Metazoa
+ | − | (7) | Drosophila melanogaster
+ | − | (2) | Mammalia
+ | − | (2) | Mus musculus
+ | − | (2) | Vertebrata

Annotations need reviewing and comment needs updating.
Should it be only in plants (needs RNA-dependent RNA polymerase AND DNA methylation)

**Comment by hattrill** [comment]
@pgaudet update comment to reflect Val's input:

"This process has been shown in plants, but has not been detected in metazoans and fungi."
