### ISSUE TITLE
Obsoletion notice: GO:0044278 disruption of cell wall in another organism

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26049]
Unnecessary grouping term; plant cell walls are only disrupted by from fungal and bacterial symbionts; bacterial cell walls are disrupted by phages, but there are no known non-symbiont predator toxins poisons that act on cell walls.

**Comment by Antonialock** [comment]
Pascale I'm not sure about this, at least this paper says that bees express an antimicrobial peptide called waprin active against fungi and bacteria. 

" It recognized carbohydrates in the microbial cell wall molecules and bound to the live microbial surfaces. The binding action of Amwaprin produced its microbicidal activity by inducing structural damage to bacterial and fungal cell walls."

both vertebrates and other insects cotain waprin homologs (at least a quick uniprot search suggests so)

**Comment by Antonialock** [comment]
sorry that's https://www.sciencedirect.com/science/article/pii/S1532045623000169

**Comment by pgaudet** [comment]
Thanks for this @Antonialock !! I'll add the reference.

**Comment by Antonialock** [comment]
from a google search, it also looks like bacteria prey on fungi
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6776036/
_Proteolytic myxobacteria are associated with feeding on a broad range of soil bacteria and fungi...Outer-membrane vesicles (OMVs) derived from the cell envelope of Gram-negative bacteria play important roles in diverse bacterial functions. Notably, OMVs of M. xanthus are directly involved in the lysis of prey cells..... Here, we show that a novel OM β-1,6-glucanase GluM, belonging to a yet unknown glycoside hydrolase family, is a key factor in the predation of the rice pathogen Magnaporthe oryzae. GluM attacks cell walls of M. oryzae and reduces virulence_

and also examples of fungi preying on fungi (I haven't read the paper, it's old so probably doesn't contain easily annotatable information)
https://www.microbiologyresearch.org/content/journal/micro/10.1099/00221287-135-3-675

**Comment by Antonialock** [comment]
microbes behaving like....animals? ;-)

**Comment by Antonialock** [comment]
although I suppose the bacterium would fit into "symbiont-mediated disruption of host cell wall"
perhaps the fungal one too? though it doesn't clearly fit the "larger organism" part of the def

**Comment by Antonialock** [comment]
I deleted a couple of comments because I realized those examples would probably fit the "symbiont/host" (although in this case I think predator/prey would be more accurate) model.

I suppose the real difference is whether it's a defensive or offensive action

**Comment by Antonialock** [comment]
@pgaudet this term is still obsoleted? GO:0044278 I thought you put it back based on the above publication on Waprin?

**Comment by pgaudet** [comment]
thanks for the ping @Antonialock 
I just restored the term.
