### ISSUE TITLE
NTR: ligand-activated transcription repressor activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26077]
Please provide as much information as you can: 

* **Suggested term label:**
ligand-activated transcription repressor activity

* **Definition (free text)**

* **Reference, in format PMID:#######**
PMID:21555518
* **Gene product name and ID to be annotated to this term**
O14867 BACH1

* **Parent term(s)**
'DNA-binding transcription repressor activity'
ligand-activated transcription factor activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141096
+name: ligand-activated transcription repressor activity
+namespace: molecular_function
+def: "A DNA-binding transcription repressor activity regulated by binding to a ligand and that inhibits the transcription of specific genes and gene sets." [PMID:21555518]
+is_a: GO:0001217 ! DNA-binding transcription repressor activity
+is_a: GO:0098531 ! ligand-activated transcription factor activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26077" xsd:anyURI
+created_by: pg
+creation_date: 2023-09-11T08:07:51Z

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141097
+name: ligand-activated transcription activator activity
+namespace: molecular_function
+def: "A DNA-binding transcription activator activity regulated by binding to a ligand and that activates the transcription of specific genes and gene sets." [GOC:pg]
+is_a: GO:0001216 ! DNA-binding transcription activator activity
+is_a: GO:0098531 ! ligand-activated transcription factor activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26077" xsd:anyURI
+created_by: pg
+creation_date: 2023-09-11T08:11:03Z
+

**Comment by ValWood** [comment]
Aren't all gene-specific transcription activators going to be ligand-activated in some way?

**Comment by pgaudet** [comment]
are they?
