### ISSUE TITLE
NTR: tRNA (cytidine(34)-2'-O)-methyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26084]
Please provide as much information as you can: 

* **Suggested term label:**
tRNA (cytidine(34)-2'-O)-methyltransferase activity

* **Definition (free text)**
cytidine(34) in tRNA + S-adenosyl-L-methionine = 2'-O-methylcytidine(34) in tRNA + H(+) + S-adenosyl-L-homocysteine

* **Reference, in format PMID:#######**
PMID: 31943105

* **Gene product name and ID to be annotated to this term**
Dmel Trm7-34 (FBgn0038861)

* **Parent term(s)**
is_a: GO:0016427 ! tRNA (cytosine) methyltransferase activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
EC 2.1.1.207
[RHEA:43084](https://www.rhea-db.org/rhea/43084)

* **Any other information**
Need to this reannotate as per https://github.com/geneontology/go-annotation/issues/4730

**Comment by pgaudet** [comment]
Good catch ! 
+[Term]
+id: GO:0141098
+name: tRNA (cytidine(34)-2'-O)-methyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: cytidine(34) in tRNA + S-adenosyl-L-methionine = 2'-O-methylcytidine(34) in tRNA + H(+) + S-adenosyl-L-homocysteine." [PMID:31943105, RHEA:43084]
+synonym: "tRNA (cytidine 34-2'-O)-methyltransferase activity" EXACT []
+xref: EC 2.1.1.207
+xref: RHEA:43084
+is_a: GO:0016427 ! tRNA (cytidine) methyltransferase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26084" xsd:anyURI
+created_by: pg
+creation_date: 2023-09-11T13:53:59Z
+

**Comment by pgaudet** [comment]
I also changed the label of some neighboring terms to be consistent - let me know if that was not right: 

- GO:0016427 tRNA (cytosine) methyltransferase activity >> changed to  tRNA (cytidine) methyltransferase activity
- GO:0106339 name: tRNA (cytidine 32-2'-O)-methyltransferase activity >> changed to  tRNA (cytidine(32)-2'-O)-methyltransferase activity
- GO:0106059 tRNA (cytidine 56-2'-O)-methyltransferase activity >> changed to  tRNA (cytidine(56)-2'-O)-methyltransferase activity
- GO:0052735 tRNA (cytosine-3-)-methyltransferase activity >>> tRNA (cytidine-3-)-methyltransferase activity
- GO:0016428  tRNA (cytosine-5-)-methyltransferase activity >>  tRNA (cytidine-5-)-methyltransferase activity
