### ISSUE TITLE
EC:1.3.5.1 succinate dehydrogenase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26087]
Currently we have this:

id: GO:0008177
name: succinate dehydrogenase (ubiquinone) activity
alt_id: GO:0019737
def: "Catalysis of the reaction: succinate + ubiquinone = fumarate + ubiquinol." [RHEA:13713]
synonym: "succinate:ubiquinone oxidoreductase activity" RELATED [EC:1.3.5.1]
synonym: "succinic dehydrogenase activity" BROAD [EC:1.3.5.1]
xref: EC:1.3.5.1
xref: KEGG_REACTION:R02164
xref: MetaCyc:SUCCINATE-DEHYDROGENASE-UBIQUINONE-RXN
xref: RHEA:13713
is_a: GO:0000104 ! succinate dehydrogenase activity

But EC:1.3.5.1 reaction is less specific: a quinone + succinate <=> a quinol + fumarate
And EC:1.3.5.1 comments include: "The enzyme interacts with the quinone produced by the organism, such as ubiquinone, menaquinone, caldariellaquinone, thermoplasmaquinone, rhodoquinone etc."

The current RHEA:13713 xref is specific for ubiquinone (so matches the current def); RHEA:40523 is the equivalent to EC:1.3.5.1

Proposals:

- [x] rename GO:0008177 to "succinate dehydrogenase (quinone) activity"
- [x] redefine GO:0008177 to match EC:1.3.5.1
- [x] change RHEA xref to RHEA:40523
- [x] change MetaCyc xref to MetaCyc:RXN-14971
- [x] obsolete the related (more-specific) term "GO:0102040 fumarate reductase (menaquinone)", which also has EC:1.3.5.1 xref (and only has 2 EXP annotations)

**Comment by pgaudet** [comment]
@amandamackie 
The E. coli frdC and fdrD are the only two genes annotated to [fumarate reductase (menaquinone)](https://amigo.geneontology.org/amigo/term/GO:0102040). As far as I can tell, this reaction used to be EC:1.3.5.4, which has been transferred to the more general 1.3.5.1, which uses the more general 'quinone' as donor.

Is that reaction necessary, or is GO:0008177 succinate dehydrogenase (ubiquinone) activity sufficient to describe the activity? 

Thanks, Pascale

**Comment by pgaudet** [comment]
> I always thought that EC numbers represented enzymes (not reactions) and if that's the case the fumarate reductase from E. coli should have a different EC number.

This is usually right, I dont know why EC merged that into EC:1.3.5.1

@kaxelsen do you know ?

**Comment by pgaudet** [comment]
GO does not describe enzymes, but reactions. From what I can tell, this is the same reaction, but part of different BPs. 

I think @sjm41 's suggestion is correct to obsolete (+ replace by GO:0008177 succinate dehydrogenase (ubiquinone) activity)

**Comment by amandamackie** [comment]
Thanks everyone for the clarification. I will remove GO:0102040 fumarate reductase and replace with GO:0008177 sdh (quinone) in EcoCyc.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0102040 fumarate reductase (menaquinone). The reason for obsoletion is that the corresponding EC has been merged into the related opposite reaction, GO:0008177 succinate dehydrogenase (ubiquinone) activity. Annotations have been changed. This term is not present in any subsets. 

You can comment on the ticket: 
https://github.com/geneontology/go-ontology/issues/26087

Thanks, Pascale
