### ISSUE TITLE
GO:0047385, Rhea reaction now available for this term

### ISSUE THREAD

**Issue by kaxelsen** [geneontology/go-ontology#26088]
This term, linked to EC 3.1.3.52, now has a Rhea reaction defined:
RHEA:77247 H2O + O-phospho-L-seryl-[3-methyl-2-oxobutanoate dehydrogenase] = L-seryl-[3-methyl-2-oxobutanoate dehydrogenase] + phosphate 

The Rhea reaction will become public in release 2024_01 scheduled for January 17.

**Comment by pgaudet** [comment]
Thanks, added the xref and updated the definition to match RHEA's.
