### ISSUE TITLE
EC:4.2.1.3 aconitate hydratase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26091]
Further to a previous discussion in 2011 (#8602):

**EC:4.2.1.3**
Name: aconitate hydratase 
Reaction: citrate <=> D-threo-isocitrate
Comment: Besides interconverting citrate and cis-aconitate, it also interconverts cis-aconitate with isocitrate and, hence, interconverts citrate and isocitrate.
RHEA xref: RHEA:10336

We currently have 3 GO terms relating to EC:4.2.1.3 aconitate hydratase - here's a summary:
- GO:0003994 aconitate hydratase activity xref: EC:4.2.1.3, RHEA:10336
-- this is for the overall reaction: citrate <=> D-threo-isocitrate
-- 55 GO EXP annotations, 52,576 RHEA annotations in UP)
- GO:0047780 citrate dehydratase activity xref EC:4.2.1.3, RHEA:10228
-- this is for the first sub-reaction: citrate = cis-aconitate + H2O
-- 0 GO EXP annotations, 1 RHEA annotation in UP
- GO:0052633 isocitrate hydro-lyase (cis-aconitate-forming) activity xref: RHEA:22144
-- this is for the second sub-reaction: cis-aconitate + H2O = D-threo-isocitrate
-- 0 GO EXP annotations, 2 RHEA annotations in UP)

I'd suggest we obsolete the two sub-reaction terms (GO:0047780 and GO:0052633).

However, if there's a good reason for keeping them, then EC:4.2.1.3 should be a narrowMatch xref on both GO:0047780 and GO:0052633.

And regardless, please add MetaCyc:RXN-14047 as an xref to GO:0003994

==

id: GO:0003994 (55 EXP annotations)
name: aconitate hydratase activity
namespace: molecular_function
def: "Catalysis of the reaction: citrate = isocitrate. The reaction occurs in two steps: (1) citrate = cis-aconitate + H2O, (2) cis-aconitate + H2O = isocitrate. This reaction is the interconversion of citrate and isocitrate via the labile, enzyme-bound intermediate cis-aconitate. Water is removed from one part of the citrate molecule and added back to a different atom to form isocitrate." [EC:4.2.1.3, GOC:pde, GOC:vw]
comment: This is a process composed of two reactions represented by the terms 'GO:0052632 : citrate hydro-lyase (cis-aconitate-forming) activity' and 'GO:0052633 : isocitrate hydro-lyase (cis-aconitate-forming) activity'.
synonym: "aconitase activity" EXACT []
synonym: "cis-aconitase activity" RELATED [EC:4.2.1.3]
synonym: "citrate hydro-lyase activity" BROAD [EC:4.2.1.3]
synonym: "citrate(isocitrate) hydro-lyase (cis-aconitate-forming)" RELATED [EC:4.2.1.3]
synonym: "citrate(isocitrate) hydro-lyase activity" RELATED [EC:4.2.1.3]
xref: EC:4.2.1.3
xref: RHEA:10336
is_a: GO:0016836 ! hydro-lyase activity

id: GO:0047780 (0 EXP annotations)
name: citrate dehydratase activity
namespace: molecular_function
alt_id: GO:0052632
def: "Catalysis of the reaction: citrate = cis-aconitate + H2O." [EC:4.2.1.3]
comment: This term is also a sub-reaction of 'aconitate hydratase activity ; GO:0003994 (EC:4.2.1.3)'.
synonym: "aconitate hydratase activity" BROAD [EC:4.2.1.3]
synonym: "citrate hydro-lyase (cis-aconitate-forming)" RELATED [EC:4.2.1.3]
synonym: "citrate hydro-lyase (cis-aconitate-forming) activity" EXACT []
synonym: "citrate hydro-lyase activity" BROAD [EC:4.2.1.3]
xref: EC:4.2.1.3
xref: KEGG_REACTION:R01325
xref: MetaCyc:ACONITATEDEHYDR-RXN
xref: RHEA:10228
is_a: GO:0016836 ! hydro-lyase activity
relationship: has_part GO:0003994 ! aconitate hydratase activity

id: GO:0052633 (0 EXP annotations)
name: isocitrate hydro-lyase (cis-aconitate-forming) activity
namespace: molecular_function
def: "Catalysis of the reaction: cis-aconitate + H2O = isocitrate." [EC:4.2.1.3, GOC:pde, GOC:vw, MetaCyc:ACONITATEHYDR-RXN]
synonym: "aconitate hydratase activity" BROAD [EC:4.2.1.3]
synonym: "cis-aconitase activity" BROAD [EC:4.2.1.3]
synonym: "citrate hydro-lyase activity" BROAD [EC:4.2.1.3]
synonym: "citrate(isocitrate) hydro-lyase (cis-aconitate-forming)" BROAD [EC:4.2.1.3]
synonym: "citrate(isocitrate) hydro-lyase activity" BROAD [EC:4.2.1.3]
xref: KEGG_REACTION:R01900
xref: MetaCyc:ACONITATEHYDR-RXN
xref: RHEA:22144
is_a: GO:0016836 ! hydro-lyase activity
relationship: has_part GO:0003994 ! aconitate hydratase activity

**Comment by sjm41** [comment]
@deustp01 This relates to our earlier discussion about sub-reactions

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0047780 citrate dehydratase activity and GO:0052633 isocitrate hydro-lyase (cis-aconitate-forming) activity. The reason for obsoletion is that these represent sub-reactions. There are no annotations to these terms; these terms are not in any subsets. There are mappings to RHEA, EC and KEGG. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/26091

Thanks, Pascale
