### ISSUE TITLE
GO:0004809 tRNA (guanine-N2-)-methyltransferase activity and GO:0016429  tRNA (adenine-N1-)-methyltransferase activity map to transferred ECs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26104]
**GO:0004809 tRNA (guanine-N2-)-methyltransferase activity**, maps to [EC:2.1.1.32](https://enzyme.expasy.org/EC/2.1.1.32), transferred to 

- [ ] Transferred entry: [2.1.1.213](https://enzyme.expasy.org/EC/2.1.1.213) & [RHEA:43124](https://www.rhea-db.org/rhea/43124)
- [ ] Transferred entry: [2.1.1.214](https://enzyme.expasy.org/EC/2.1.1.214) & [RHEA:43128](https://www.rhea-db.org/rhea/43128)
- [ ] Transferred entry: [2.1.1.215](https://enzyme.expasy.org/EC/2.1.1.215) & [RHEA:43124](https://www.rhea-db.org/rhea/43124)
- [ ] Transferred entry: [2.1.1.216](https://enzyme.expasy.org/EC/2.1.1.216) & [RHEA:43140](https://www.rhea-db.org/rhea/43140)

**GO:0016429  tRNA (adenine-N1-)-methyltransferase activity:** maps to [EC:2.1.1.36](https://enzyme.expasy.org/EC/2.1.1.36), transferred to 

- [ ] Transferred entry: [2.1.1.217](https://enzyme.expasy.org/EC/2.1.1.217) & [RHEA:43144](https://www.rhea-db.org/rhea/43144)
- [ ] Transferred entry: [2.1.1.218](https://enzyme.expasy.org/EC/2.1.1.218) & [RHEA:43148](https://www.rhea-db.org/rhea/43148)
- [x] Transferred entry: [2.1.1.219](https://enzyme.expasy.org/EC/2.1.1.219) & [RHEA:41740](https://www.rhea-db.org/rhea/41740) >>>  [tRNA (adenine(57)-N1-/adenine(58)-N1-)-methyltransferase activity](http://purl.obolibrary.org/obo/GO_0043827)
- [ ] Transferred entry: [2.1.1.220](https://enzyme.expasy.org/EC/2.1.1.220) & [RHEA:43152](https://www.rhea-db.org/rhea/43152)

Action needed: 

- [x] create the 8 new GO terms
- [ ] obsolete GO:0004809 and GO:0016429

**Comment by raymond91125** [comment]
GO:0043827 tRNA (adenine(57)-N1-)/(adenine(58)-N1-)-methyltransferase activity EC xref has a typo.

**Comment by pgaudet** [comment]
[Term]
id: GO:0160101
name: tRNA (guanine(10)-N(2))-dimethyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: guanosine(10) in tRNA + 2 S-adenosyl-L-methionine = 2 H(+) + N(2)-dimethylguanosine(10) in tRNA + 2 S-adenosyl-L-homocysteine." [EC:2.1.1.213]
synonym: "N(2),N(2)-dimethylguanosine tRNA methyltransferase" EXACT []
xref: EC:2.1.1.213
xref: RHEA:43124
is_a: GO:0008170 ! N-methyltransferase activity
is_a: GO:0016423 ! tRNA (guanosine) methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26104" xsd:string
created_by: rynl
creation_date: 2023-09-14T00:15:09Z

[Term]
id: GO:0160102
name: tRNA (guanine(10)-N(2))-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: guanosine(10) in tRNA + S-adenosyl-L-methionine = H(+) + N(2)-methylguanosine(10) in tRNA + S-adenosyl-L-homocysteine." [EC:2.1.1.214]
xref: EC:2.1.1.214
xref: RHEA:43128
is_a: GO:0008170 ! N-methyltransferase activity
is_a: GO:0016423 ! tRNA (guanosine) methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26104" xsd:string
created_by: rynl
creation_date: 2023-09-14T00:20:53Z

[Term]
id: GO:0160103
name: tRNA (guanine(26)-N(2)/guanine(27)-N(2))-dimethyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: guanosine(26)/guanosine(27) in tRNA + 4 S-adenosyl-L-methionine = 4 H(+) + N(2)-dimethylguanosine(26)/N(2)-dimethylguanosine(27) in tRNA + 4 S-adenosyl-L-homocysteine." [EC:2.1.1.215]
xref: EC:2.1.1.215
xref: RHEA:43136
is_a: GO:0008170 ! N-methyltransferase activity
is_a: GO:0016423 ! tRNA (guanosine) methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26104" xsd:string
created_by: rynl
creation_date: 2023-09-14T00:24:30Z

[Term]
id: GO:0160104
name: tRNA (guanine(26)-N(2))-dimethyltransferase
namespace: molecular_function
def: "Catalysis of the reaction:guanosine(26) in tRNA + 2 S-adenosyl-L-methionine = 2 H(+) + N(2)-dimethylguanosine(26) in tRNA + 2 S-adenosyl-L-homocysteine." [EC:2.1.1.216]
synonym: "tRNA (m(2)2G26)dimethyltransferase" EXACT []
xref: EC:2.1.1.216
xref: RHEA:43140
is_a: GO:0008170 ! N-methyltransferase activity
is_a: GO:0016423 ! tRNA (guanosine) methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26104" xsd:string
created_by: rynl
creation_date: 2023-09-14T00:28:33Z

[Term]
id: GO:0160105
name: tRNA (adenine(22)-N(1))-methyltransferase  activity
namespace: molecular_function
def: "Catalysis of the reaction: adenosine(22) in tRNA + S-adenosyl-L-methionine = H(+) + N(1)-methyladenosine(22) in tRNA + S-adenosyl-L-homocysteine." [EC:2.1.1.217]
xref: EC:2.1.1.217
xref: RHEA:43144
is_a: GO:0016426 ! tRNA (adenine) methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26104" xsd:string
created_by: rynl
creation_date: 2023-09-14T00:42:44Z

[Term]
id: GO:0160106
name: tRNA (adenine(9)-N(1))-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: adenosine(9) in tRNA + S-adenosyl-L-methionine = H(+) + N(1)-methyladenosine(9) in tRNA + S-adenosyl-L-homocysteine." [EC:2.1.1.218]
synonym: "tRNA m(1)A(9)-methyltransferase" EXACT []
synonym: "tRNA(m(1)G(9)/m(1)A(9))-methyltransferase" EXACT []
xref: EC:2.1.1.218
xref: RHEA:43148
is_a: GO:0016426 ! tRNA (adenine) methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26104" xsd:string
created_by: rynl
creation_date: 2023-09-14T00:53:53Z

[Term]
id: GO:0160107
name: tRNA (adenine(58)-N(1))-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: adenosine(58) in tRNA + S-adenosyl-L-methionine = H(+) + N(1)-methyladenosine(58) in tRNA + S-adenosyl-L-homocysteine." [EC:2.1.1.220]
synonym: "tRNA (m(1)A(58)) methyltransferase" EXACT []
synonym: "tRNA m(1)A(58) methyltransferase" EXACT []
xref: EC:2.1.1.220
xref: RHEA:43152
is_a: GO:0016426 ! tRNA (adenine) methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26104" xsd:string
created_by: rynl
creation_date: 2023-09-14T00:57:53Z
