### ISSUE TITLE
Update EC and add RHEA    GO:0018637  1-hydroxy-2-naphthoate hydroxylase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26102]
GO:0018637  1-hydroxy-2-naphthoate hydroxylase activity corresponds to

- [ ]  EC:1.14.13.135 (exactMatch) and to 
- [ ] RHEA:31271 and RHEA:31571 (narrowMatch)
- [ ] definition should also have NAD(P) / NAD(P)H
- [ ] add references PMID:20727010 and PMID:21545490

Thanks, Pascale

**Comment by raymond91125** [comment]
It appears that there cannot be two RHEA dbxref to one GO term.

**Comment by pgaudet** [comment]
Yes, you can add it, you need to add an annotation to the dbxref and add skos=narrowMatch 
This is described step-by-step here: https://wiki.geneontology.org/Guidelines_for_database_cross_references#Adding_database_cross-reference_types

Thanks, Pascale

**Comment by raymond91125** [comment]
Thanks.
