### ISSUE TITLE
Obsoletion request: GO:0000422 autophagy of mitochondrion  (has direct replacement)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26111]
Please provide as much information as you can:

See https://github.com/geneontology/go-ontology/issues/25541 for background

* **GO term ID and Label**

GO:0000422 autophagy of mitochondrion 
GO:1903146  regulation of autophagy of mitochondrion
GO:1903147    negative regulation of autophagy of mitochondrion
GO:1903599    positive regulation of autophagy of mitochondrion

* **Reason for deprecation** 

 - [ ]  The reason for obsoletion is that this term was an unnecessary grouping term.
 

* **"Replace by" term (ID and label)**

GO:0000423   mitophagy
and appropriate regulation children

* **Are there annotations to this term?**

(91) autophagy of mitochondrion
(11)	positive regulation of autophagy of mitochondrion
(19)	regulation of autophagy of mitochondrion
(5) | negative regulation of autophagy of mitochondrion

can be migrated automatically to GO:0000423   mitophagy and regulation children

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

None

* **Is this term in a subset? (check the AmiGO page for that term)**

No

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***

- [x] create Annotation Review spreadsheet 

https://docs.google.com/spreadsheets/d/1BXQOaXNawXVxH6k-QIoUAfJIvIzgTM3BaiC9tVg-2Oo/edit#gid=0

- [x] https://github.com/geneontology/go-annotation/issues/4752

***Notification***
- [x] https://github.com/geneontology/go-announcements/issues/599
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
sigh

Comments
Note that this term is not a child of mitophagy because the community genrally uses that latter to refer to the macroautophagy of mitochondria.

**Comment by pgaudet** [comment]
so, should we do that ?
