### ISSUE TITLE
GO:0047101 / EC:1.2.1.25 branched-chain alpha-keto acid dehydrogenase

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26124]
id: GO:0047101
name: 2-oxoisovalerate dehydrogenase (acylating) activity
namespace: molecular_function
def: "Catalysis of the reaction: NAD+ + CoA + 2-keto-isovalerate = NADH + CO2 + isobutyryl-CoA." [EC:1.2.1.25, MetaCyc:1.2.1.25-RXN]
synonym: "2-oxoisovalerate dehydrogenase activity" RELATED [EC:1.2.1.25]
synonym: "3-methyl-2-oxobutanoate:NAD+ 2-oxidoreductase (CoA-methyl-propanoylating)" RELATED [EC:1.2.1.25]
xref: EC:1.2.1.25
xref: MetaCyc:1.2.1.25-RXN
xref: RHEA:13997
is_a: GO:0016620 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor

This term is defined and xreffed to EC:1.2.1.25, which says: 
**Name**: branched-chain alpha-keto acid dehydrogenase system
**Alt_names**: 2-oxoisovalerate dehydrogenase (acylating), branched-chain alpha-keto acid dehydrogenase complex
**Reaction**: 3-methyl-2-oxobutanoate + CoA + NAD(+) <=> 2-methylpropanoyl-CoA + CO2 + NADH
**Comments include**:
This enzyme system catalyzes the oxidative decarboxylation of branched-chain alpha-keto acids derived from L-leucine, L-isoleucine, and L-valine to branched-chain acyl-CoAs.
The system also acts on (S)-3-methyl-2-oxopentanoate and 4-methyl-2- oxopentanoate.
The reaction catalyzed by this system is the sum of three activities: EC 1.2.4.4, EC 2.3.1.168 and EC 1.8.1.4.

Based on this, I propose:

- [x] Change GO term name to "branched-chain alpha-keto acid dehydrogenase activity"
- [x] Change GO def to something like "Catalysis of the reaction: [a branched alpha-keto acid]  + CoA + NAD(+) = [a branched-chain acyl-CoA] + CO2 + NADH. This enzyme system catalyzes the oxidative decarboxylation of branched-chain alpha-keto acids derived from L-leucine, L-isoleucine, and L-valine."
- [x] Make RHEA:13997 a narrowMatch xref.
- [x] (Could also add RHEA:30907 and RHEA:25177 as narrowMatch xrefs)
- [x] Obsolete GO:0102006 4-methyl-2-oxopentanoate dehydrogenase activity (=RHEA:25177), which is for a specific substrate, and has zero GO/RHEA annotations.

**Comment by deustp01** [comment]
> id: GO:0047101 name: 2-oxoisovalerate dehydrogenase (acylating) activity namespace: molecular_function def: "Catalysis of the reaction: NAD+ + CoA + 2-keto-isovalerate = NADH + CO2 + isobutyryl-CoA." [EC:1.2.1.25, MetaCyc:1.2.1.25-RXN] synonym: "2-oxoisovalerate dehydrogenase activity" RELATED [EC:1.2.1.25] synonym: "3-methyl-2-oxobutanoate:NAD+ 2-oxidoreductase (CoA-methyl-propanoylating)" RELATED [EC:1.2.1.25] xref: EC:1.2.1.25 xref: MetaCyc:1.2.1.25-RXN xref: RHEA:13997 is_a: GO:0016620 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor
> 
> This term is defined and xreffed to EC:1.2.1.25, which says: **Name**: branched-chain alpha-keto acid dehydrogenase system **Alt_names**: 2-oxoisovalerate dehydrogenase (acylating), branched-chain alpha-keto acid dehydrogenase complex **Reaction**: 3-methyl-2-oxobutanoate + CoA + NAD(+) <=> 2-methylpropanoyl-CoA + CO2 + NADH **Comments include**: This enzyme system catalyzes the oxidative decarboxylation of branched-chain alpha-keto acids derived from L-leucine, L-isoleucine, and L-valine to branched-chain acyl-CoAs. The system also acts on (S)-3-methyl-2-oxopentanoate and 4-methyl-2- oxopentanoate. The reaction catalyzed by this system is the sum of three activities: EC 1.2.4.4, EC 2.3.1.168 and EC 1.8.1.4.
> 
> Based on this, I propose:
> 
>     * [ ]  Change GO term name to "branched-chain alpha-keto acid dehydrogenase activity"
> 
>     * [ ]  Change GO def to something like "Catalysis of the reaction: [a branched alpha-keto acid]  + CoA + NAD(+) = [a branched-chain acyl-CoA] + CO2 + NADH. This enzyme system catalyzes the oxidative decarboxylation of branched-chain alpha-keto acids derived from L-leucine, L-isoleucine, and L-valine."
> 
>     * [ ]  Make RHEA:13997 a narrowMatch xref. (Could also add RHEA:30907 and RHEA:25177 as narrowMatch xrefs)
> 
>     * [ ]  Obsolete GO:0102006 4-methyl-2-oxopentanoate dehydrogenase activity (=RHEA:25177), which is for a specific substrate, and has zero GO/RHEA annotations.

@ukemi a property of this enzyme complex, conserved from eubacteria to mammals, is its ability to act on all three substrates, so a 3:1 mapping of RHEA reactions to GO MF terms seems exactly right. (And the equally well conserved ability of alpha-ketoglutarate dehydrogenase to act both in the TCA cycle and on an intermediate in lysine catabolism would yield a 2:1 mapping. I'm raising this here because we have previously thought about trying to avoid deviations form 1:1 and (statement against interest, as the lawyers would say) these look like two cases where deviation is right: an intrinsic evolved property of the enzyme is to mediate more than one function. So this might fit somewhere in a more general discussion ofedge cases in making mappings between RHEA reactions and GO MF terms.

**Comment by sjm41** [comment]
@raymond91125 @pgaudet I've done most of the changes above. I tried adding the other two RHEAs as narrowMatch xrefs, but got an error upon merging, so I haven't done that.
Also still need to obsolete GO:0102006.
