### ISSUE TITLE
alpha-ketoglutarate (aka 2-oxoglutarate) dehydrogenase complex terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26122]
Currently we have:

```
dihydrolipoyl dehydrogenase complex (GO:0045240)
|__cytosolic alpha-ketoglutarate dehydrogenase complex (GO:0045241)
|__mitochondrial alpha-ketoglutarate dehydrogenase complex (GO:0005947)
	|__mitochondrial oxoglutarate dehydrogenase complex (GO:0009353)
|__oxoglutarate dehydrogenase complex (GO:0045252)
        |__cytosolic oxoglutarate dehydrogenase complex (GO:0045248)
        |__mitochondrial oxoglutarate dehydrogenase complex (GO:0009353)
```

There are a few issues here:

1. The parent term (dihydrolipoyl dehydrogenase complex) is defined as "A protein complex that possesses alpha-ketoglutarate dehydrogenase activity.", so I'd suggest renaming the term to "alpha-ketoglutarate dehydrogenase complex" to match the definition. That said, I'm not convinced we need this grouping term at all. Obsolete?

2. There are zero annotations to and there is no reference for "cytosolic alpha-ketoglutarate dehydrogenase complex (GO:0045241)".  Obsolete?

3. 'mitochondrial alpha-ketoglutarate dehydrogenase complex (GO:0005947)' seems like a confusing and unnecessary grouping term with only one child term. So I'd obsolete GO:0005947 too.

4. There are 15 direct EXP annotations using GO:0005947 for human/rat/cerevisiae proteins.  All the human and rat proteins are components of the 'branched-chain alpha-keto acid dehydrogenase' complex (PMID: 3593587, PMID: 9582350, PMID: 10745006), so I think we need a new GO term specifically for that complex - see #26121.  The remaining 4 yeast annotations from PMID:25165143 (made by ComplexPortal) should be moved to the current child term mitochondrial oxoglutarate dehydrogenase complex (GO:0009353).

**Comment by deustp01** [comment]
> 2\. There are zero annotations to and there is no reference for "cytosolic alpha-ketoglutarate dehydrogenase complex (GO:0045241)".  Obsolete?

All three alpha-ketoglutarate dehydrogenase complexes occur in eubacteria and animals (and probably plants - local gap in knowledge about plants), so we need a parent term that is agnostic about subcellular location or uses cytoplasm as a location term that can apply to bacteria and animals. As far as I know, in any organism that has mitochondria all three dehydrogenase complexes are located in the mitochondrial matrix. (Tangential question - what happens to these complexes in yeasts that lose their mitochondria - are they also lost or do they re-locate?)

Here is one annotation (seach in QuickGO for usages of GO:0045240[ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0045240/complete) that turns up dihydrolipoyl dehydrogenase complexfor E. coli that uses [GO:0045248](https://www.ebi.ac.uk/QuickGO/term/GO:0045248)
cytosolic oxoglutarate dehydrogenase complex , just to muddy things

<img width="1273" alt="Screenshot 2023-09-13 at 12 48 52 PM" src="https://github.com/geneontology/go-ontology/assets/12737623/134bba7a-b975-48b8-a02e-cab41a5ef65a">

Once we have the cytoplasmic / agnostic location, do we also need a child term for the mitochondrial form found in eukaryotes, or is that handled OK at the level of annotation?

**Comment by sjm41** [comment]
Hi @deustp01 

I'm really not sure what "cytosolic alpha-ketoglutarate dehydrogenase complex (GO:0045241)" is meant to represent. The def is "Cytosolic complex that possesses alpha-ketoglutarate dehydrogenase activity. [GOC:mah, GOC:mtg_sensu]" and has 0 annotations.

alpha-ketoglutarate and 2-oxoglutarate are synonyms, right?  And we already have "cytosolic oxoglutarate dehydrogenase complex (GO:0045248)" with def "A cytosolic complex of multiple copies of three enzymatic components: oxoglutarate dehydrogenase (lipoamide) (E1), dihydrolipoamide S-succinyltransferase (E2) and dihydrolipoamide dehydrogenase (E3); catalyzes the overall conversion of 2-oxoglutarate to succinyl-CoA and carbon dioxide (CO2)." [GOC:mtg_sensu, PMID:10848975]". This has the single annotation you identified above.

So I think "cytosolic alpha-ketoglutarate dehydrogenase complex (GO:0045241)" is at best redundant with "cytosolic oxoglutarate dehydrogenase complex (GO:0045248)" 

_All three alpha-ketoglutarate dehydrogenase complexes occur in eubacteria and animals...so we need a parent term that is agnostic about subcellular location or uses cytoplasm as a location term that can apply to bacteria and animals_

We might want a new grouping term for the three alpha-keto**acid** dehydrogenase complexes:
pyruvate dehydrogenase complex (GO:0045254)
oxoglutarate dehydrogenase complex (GO:0045252)
branched-chain alpha-keto acid dehydrogenase complex (NTR #26121)

Or maybe the existing "dihydrolipoyl dehydrogenase complex (GO:0045240)" term (see above) could be co-opted for that purpose? Would need to rename and broaden definition. Probably better to make new grouping term.

**Comment by deustp01** [comment]
> alpha-ketoglutarate and 2-oxoglutarate are synonyms, right?

Yes - I think the first term is preferred by US biochemists and the second by UK and maybe everyone else, but the chemical is the same.

Looking at the histories of the two terms (last items on their QuickGO pages), it looks like the two terms were created to deal with bacterial versus eukaryotic forms of the complex and that distinction has gotten lost as strategies for handling taxon-specific differences in GO have changed. I don't see any need for both terms now.

And a grouping term would be good - among other things it would automatically force the ancestries of all these terms to align completely, leaving only the distinction among the complexes of range of substrates at the bottom-most leaf level.

@ukemi OK as to history and biochemistry?

**Comment by sjm41** [comment]
@raymond91125 / @pgaudet - this is more complicated than I first appreciated. Could we arrange a VC to discuss/address?

Looking more deeply at the parentage of "mitochondrial oxoglutarate dehydrogenase complex (GO:0009353)", I find additional problems/redundancies, as well as inconsistencies with how the related alpha-ketoacid dehydrogenase complexes (mitochondrial pyruvate dehydrogenase complex [GO:0005967] & branched-chain alpha-keto acid dehydrogenase complex [GO:0160120]) are dealt with.

The parentage involves is_a, part_of, and 'capable_of' relationships, but I'll just focus on the 'is_a' problems for now.

Here's a representation of the current is_a hierarchy for "mitochondrial oxoglutarate dehydrogenase complex (GO:0009353)" (and its sister term "cytosolic oxoglutarate dehydrogenase complex (GO:0045248)"):

```
|__protein-containing complex
     |__mitochondrial protein-containing complex
         |__mitochondrial tricarboxylic acid cycle enzyme complex
             |__mitochondrial alpha-ketoglutarate dehydrogenase complex
                 |__mitochondrial oxoglutarate dehydrogenase complex
     |__catalytic complex
         |__tricarboxylic acid cycle enzyme complex
             |__mitochondrial tricarboxylic acid cycle enzyme complex
                 |__mitochondrial alpha-ketoglutarate dehydrogenase complex
                     |__mitochondrial oxoglutarate dehydrogenase complex
             |__cytosolic tricarboxylic acid cycle enzyme complex
                 |__cytosolic alpha-ketoglutarate dehydrogenase complex
             |__dihydrolipoyl dehydrogenase complex
                 |__cytosolic alpha-ketoglutarate dehydrogenase complex
                 |__mitochondrial alpha-ketoglutarate dehydrogenase complex
                     |__mitochondrial oxoglutarate dehydrogenase complex
                 |__oxoglutarate dehydrogenase complex
                     |__cytosolic oxoglutarate dehydrogenase complex
                     |__mitochondrial oxoglutarate dehydrogenase complex
         |__oxidoreductase complex                                     
             |__dihydrolipoyl dehydrogenase complex
                 |__mitochondrial alpha-ketoglutarate dehydrogenase complex
                     |__mitochondrial oxoglutarate dehydrogenase complex
                 |__oxoglutarate dehydrogenase complex
                     |__mitochondrial oxoglutarate dehydrogenase complex
         |__transferase complex
             |__oxoglutarate dehydrogenase complex
                     |__mitochondrial oxoglutarate dehydrogenase complex
```

I suggest we change to this:
```
|__protein-containing complex
     |__mitochondrial protein-containing complex
         |__mitochondrial oxoglutarate dehydrogenase complex
     |__catalytic complex
         |__oxidoreductase complex                                     
             |__alpha-ketoacid dehydrogenase complex [NEW NAME FOR "dihydrolipoyl dehydrogenase complex"]
                 |__oxoglutarate dehydrogenase complex
                     |__mitochondrial oxoglutarate dehydrogenase complex
                     |__cytosolic oxoglutarate dehydrogenase complex
                     |__plastid oxoglutarate dehydrogenase complex [NTR]

```
 
Reasoning:

1. "mitochondrial alpha-ketoglutarate dehydrogenase complex" is the same as "mitochondrial oxoglutarate dehydrogenase complex" => merge (just keep latter)
2. "cytosolic alpha-ketoglutarate dehydrogenase complex" is the same as "cytosolic oxoglutarate dehydrogenase complex" => merge (just keep latter)
3. Remove "transferase complex" parentage since overall, this is an oxidoreductase complex not a transferase complex
4. Remove "tricarboxylic acid cycle enzyme complex" axis - not necessary, better done with a BP relation?
5. "dihydrolipoyl dehydrogenase complex" is currently defined as "A protein complex that possesses alpha-ketoglutarate dehydrogenase activity.", which would mean that term is only applicable to the alpha-ketoglutarate dehydrogenase complex (aka oxoglutarate dehydrogenase complex). But term name suggests it refers to any complex containing the DLD (aka E3) protein, which is common to all three alpha-ketoacid complexes. Indeed, current annotations include 'branched-chain alpha-keto acid dehydrogenase complex' subunits. Suggest rename term to 'alpha-ketoacid dehydrogenase complex', and make this a parent to all three of the related complexes, which would be a logical and useful grouping.

**Comment by pgaudet** [comment]
Would next week's ontology call work ?

**Comment by sjm41** [comment]
Sure! As long as you don't think this is too detailed to try to discuss with everyone at once.

**Comment by deustp01** [comment]
> Reasoning:
> 
>     1. "mitochondrial alpha-ketoglutarate dehydrogenase complex" is the same as "mitochondrial oxoglutarate dehydrogenase complex" => merge (just keep latter) ...

Perhaps if people get this much of the discussion proposal (which all looks good to me, for whatever that's worth) in advance, they'd be primed to reach agreement without getting overwhelmed (and motivated to raise objections in advance on the ticket if there's some horrible flaw)?

**Comment by pgaudet** [comment]
Hi @raymond91125 

Can you start on this before next Monday, so we can discuss any remaining points at the ontology call? Some of Steven's suggestion seem to be clear enough to implement right away.

**Comment by sjm41** [comment]
For the new "alpha-ketoacid dehydrogenase complex" definition, I'd suggest:

A multi-enzyme complex that catalyzes the oxidative decarboxylation of an alpha-ketoacid - pyruvate, a branched-chain alpha-ketoacid or alpha-ketoglutarate (also known as 2-oxoglutarate). The complex comprises multiple copies of three enzymes referred to as E1, E2 and E3: a dihydrolipoyl transacylase (E2) forms the core of the complex, with an alpha-ketoacid dehydrogenase (E1) and a dihydrolipoamide dehydrogenase (E3) attached through non-covalent bonds. The E1 and E2 components are specific to different alpha-ketoacid dehydrogenase complexes, whereas the E3 component is the same. Additional proteins may also be present. (PMID:10745006.)

**Comment by deustp01** [comment]
> * "mitochondrial alpha-ketoglutarate dehydrogenase complex" is the same as "mitochondrial oxoglutarate dehydrogenase complex" => merge (just keep latter)

I think 2-oxoacid and alpha-ketoacid are alternative names for the identical chemical structures, with alpha-ketoacid preferred in the US and 2-oxoacid preferred most other places.

**Comment by raymond91125** [comment]
I have drafted the proposed changes in the pull request above (not merged). Except for plastid oxoglutarate dehydrogenase complex [NTR], which we can do with a new ticket or punt it until it's needed for annotations.
Proper procedures for obsolete with replacement will be carried out once the final decision is made.
Note some of the relationships are by inference only. Thanks.

**Comment by sjm41** [comment]
Thanks @raymond91125 !

I see the changes you've checked off on https://github.com/geneontology/go-ontology/issues/26122#issuecomment-1897567091 in the [10e3b9e](https://github.com/geneontology/go-ontology/commit/10e3b9e589c483515c90e2c874847d40ec03ff46) commit, and these all look good.

For the other commit ([704bf10](https://github.com/geneontology/go-ontology/commit/704bf104593d1e71d66c761bca62a94b6855ccd7)), I just see many changes like "<owl:annotatedTarget rdf:nodeID="genid3077"/>" in the diff.  I don't know how to interpret those - are they the changed 'relationships by inference only'?
I guess the two unchecked tasks on https://github.com/geneontology/go-ontology/issues/26122#issuecomment-1897567091 might be included in those changes?

Is there a way for me to see/load the changes in Protege, or do I need to wait for the merge before I can do that?

**Comment by raymond91125** [comment]
@sjm41 The commit 704bf10 is about a taxon constraint that I had to delete due to term merge. It doesn't affect the ontology per se.
You can obtain this version by a specific checkout in git.
1. In the go-ontology git folder, do "git checkout 704bf10".
2. "git log" should now show the commits that I made on top.
3. In Protege, open the go-edit.obo in this repo.
4. Afterwards, do "git checkout master" to go back to that branch.

**Comment by sjm41** [comment]
Hi @raymond91125. Thanks for those instructions on how to checkout and view your commit - very helpful!

The changes look good, except that 'alpha-ketoacid dehydrogenase complex' (GO:0045240) doesn't appear to have any children.  It should have 'oxoglutarate dehydrogenase complex (GO:0045252)' according to my proposals above. In addition, please also make 'pyruvate dehydrogenase complex' (GO:0045254) and 'branched-chain alpha-keto acid dehydrogenase complex' (GO:0160120) children of 'alpha-ketoacid dehydrogenase complex'.

**Comment by sjm41** [comment]
_Remove "transferase complex" parentage since overall, this is an oxidoreductase complex not a transferase complex This relationship is inferred from (in LD) dihydrolipoyllysine-residue succinyltransferase activity._
'oxoglutarate dehydrogenase complex (GO:0045252)' currently has 3 'capable_of' relationships, corresponding to the 3 separate activities of the 3 components of the complex (known as 'E1', 'E2' and 'E3'). The overall activity of the complex is described by a 4th GO term: oxoglutarate dehydrogenase (NAD+) activity (GO:0034602).
In contrast, the related term 'pyruvate dehydrogenase complex' (GO:0045254), which similarly has E1, E2 and E3 components with distinct activities, only has one 'capable_of' relation to the single GO term (pyruvate dehydrogenase (NAD+) activity (GO:0034604)) that describes the overall catalytic activity of that complex.
So....I propose that we deal with these two complexes in the same way, and have a single 'capable_of oxoglutarate dehydrogenase (NAD+) activity (GO:0034602)' relation on 'oxoglutarate dehydrogenase complex (GO:0045252)'.

Similarly, 'branched-chain alpha-keto acid dehydrogenase complex' (GO:0160120) should have a single 'capable_of branched-chain alpha-keto acid dehydrogenase activity (GO:0047101)'.

**Comment by sjm41** [comment]
_Remove "tricarboxylic acid cycle enzyme complex" axis - not necessary, better done with a BP relation? This also comes from inference._

For this, I was suggesting we obsolete the "tricarboxylic acid cycle enzyme complex" grouping term - I don't think it's necessary/useful, the current children are inaccurate, and it seems this type of relation would be better managed via a 'capable of part of' relation between the relevant GO-CC and GO-BP terms. But I'll make a separate ticket for this once we've sorted out the other issues!

**Comment by raymond91125** [comment]
> alpha-ketoacid dehydrogenase complex

To see these relationships, you need to turn on the reasoner ELK 0.5.0 and look at the inferred class hierarchy.

**Comment by raymond91125** [comment]
I was trying to provide a proper LD for GO:0045240 alpha-ketoacid dehydrogenase complex perhaps as "protein-contaiing complex capable of some alpha-ketoacid dehydrogenase activity". I discovered this old merge https://github.com/geneontology/go-ontology/issues/21144 where alpha-ketoacid dehydrogenase activity was merged into GO:0003863 3-methyl-2-oxobutanoate dehydrogenase (2-methylpropanoyl-transferring) activity. Is GO:0003863 too narrow?

**Comment by raymond91125** [comment]
This is what I have now: "git checkout d1172c3". Note that I've removed LD from alpha-ketoacid dehydrogenase complex so that relationships are now asserted rather than inferred.

**Comment by sjm41** [comment]
Thanks @raymond91125. Your latest version looks good. Yes, I think we have to dispense with a LD for alpha-ketoacid dehydrogenase complex (GO:0003863 is too narrow - that's only applicable to the E1 component of the 'branched-chain alpha-keto acid dehydrogenase complex').

Only issue I see now is that 'oxoglutarate dehydrogenase complex' now has a single 'capable_of some oxoglutarate dehydrogenase (NAD+) activity' (as requested) but its 2 child terms still have assertions to the 3 separate enzymatic activities rather than just to 'oxoglutarate dehydrogenase (NAD+) activity'. Can you fix that?

**Comment by raymond91125** [comment]
@sjm41 I've had problems avoiding git conflicts thus I restarted the edits and merged into master. We can make more edits if required. Thanks.

**Comment by sjm41** [comment]
Hi @raymond91125 I just reviewed the changes in the master and they all look good. Thanks again.

The outstanding issues here are now:
1. Propose obsoletion of the "tricarboxylic acid cycle enzyme complex" grouping term - I will make a separate ticket for this.
2. There's currently only one term for the "branched-chain alpha-keto acid dehydrogenase complex" (which actually describes the mitochondrial complex). We'll need to have a general parent term for this and then the two cyto and mito forms as children - I will also make a separate ticket for this. 
3. 'pyruvate dehydrogenase complex' (and children) has a very useful comment about the GO MF terms for the individual components of the complex - I will add similar comments to the other terms discussed here.
4. I think we'll need to check and ask for annotation reviews once we're done, right?

**Comment by pgaudet** [comment]
@sjm41 

Minor point: can you start the definition by "A complex that" (rather than "Complex") - to be consistent with other definitions. 

Thanks, Pascale

**Comment by sjm41** [comment]
@raymond91125 I've added/updated the comments and changed the name of "branched-chain alpha-keto acid dehydrogenase complex" -> "mitochondrial branched-chain alpha-keto acid dehydrogenase complex" and merged into master.

**Comment by sjm41** [comment]
@pgaudet I don't think Raymond or I have changed any of these definitions, but I will review them all and make sure they start with "A complex that".
I see some start with "A multi-enzyme complex that..." or "A cytosolic complex that..." Is that format OK?

**Comment by pgaudet** [comment]
yes ! thanks

**Comment by sjm41** [comment]
> I will review them all and make sure they start with "A complex that".

Done

**Comment by sjm41** [comment]
Hi @raymond91125 

I just noticed that GO:0045254 pyruvate dehydrogenase complex has "relationship: part_of GO:0005737 ! cytoplasm", but the sister term GO:0045252 oxoglutarate dehydrogenase complex does not have that relationship. They should both be the same. Which is correct?

**Comment by raymond91125** [comment]
cytoplasm is not a very useful location. I'll remove it.

**Comment by deustp01** [comment]
> I just noticed that GO:0045254 pyruvate dehydrogenase complex has "relationship: part_of GO:0005737 ! cytoplasm", but the sister term GO:0045252 oxoglutarate dehydrogenase complex does not have that relationship. They should both be the same. Which is correct?

The issue here looks like a taxon issue. Quoting Lester Reed, the authority (PMID: 2188967), "In eukaryotic cells, the alpha-keto acid dehydrogenase complexes are located in mitochondria within the inner membrane- matrix compartment." This does put them in the cytoplasm is the sense that mitochondria are parts of cytoplasm. But cytoplasm in eukaryotes covers a different range of parts than in prokaryotes. So two terms, one for prokaryotic and one for eukaryotic complexes, or one term with some sort of note that describes this distinction?

**Comment by deustp01** [comment]
> alpha-ketoglutarate and 2-oxoglutarate are synonyms, right?

Yes - US usage (alppha-keto...) vs rest of world (2-oxo...)

**Comment by pgaudet** [comment]
> cytoplasm is not a very useful location. I'll remove it.

Just to be clear, this is not 'useful' but it does classify terms under [intracellular protein-containing complex](http://purl.obolibrary.org/obo/GO_0140535), so it may be useful for the organization of complex terms in the ontology.

**Comment by deustp01** [comment]
> Just to be clear, this is not 'useful' but it does classify terms

I vaguely remember that bacteriologists I talked to found it inappropriate as a term to describe "everything contained within the plasma membrane" of a prokaryotic cell", but I may be mis-remembering. @dsiegele , any thoughts here?

**Comment by raymond91125** [comment]
Since we obsoleted "location-specific" dehydrogenase complexes (https://github.com/geneontology/go-ontology/issues/26881), is this ticket also completed?

**Comment by sjm41** [comment]
Yes, I think we are done!
For the record, this is the is_a tree we finished up with:
```
|__protein-containing complex
     |__catalytic complex
         |__oxidoreductase complex                                     
             |__alpha-ketoacid dehydrogenase complex
                 |__branched-chain alpha-ketoacid dehydrogenase complex
                 |__oxoglutarate dehydrogenase complex
                 |__pyruvate dehydrogenase complex
```
:-)
