### ISSUE TITLE
NTR: branched-chain alpha-keto acid dehydrogenase complex

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26121]
* **Suggested term label:**
branched-chain alpha-keto acid dehydrogenase complex

* **Definition (free text)**
A mitochondrial complex that catalyzes the oxidative decarboxylation of branched-chain alpha-keto acids derived from L-leucine, L-isoleucine, and L-valine to branched-chain acyl-CoAs. The complex  is organized around a 24-meric cubic core of the dihydrolipoyl transacylase (E2) with multiple (∼6–12) copies of the branched-chain α-ketoacid dehydrogenase (E1, consisting of alpha and beta subunits), ∼6 copies of the dimeric dihydrolipoyl dehydrogenase (E3), and a small number of copies of the E1-specific kinase and phosphatase. (PMID: 10745006)

* **Reference, in format PMID:#######**
PMID: 3593587, PMID: 9582350, PMID: 10745006

* **Gene product name and ID to be annotated to this term**
E.g. Human proteins: BCKDHA, BCKDHB, DBT, DLD

* **Parent term(s)**
GO:0098798 mitochondrial protein-containing complex
GO:1990204 oxidoreductase complex

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
 BCKD complex (exact)

* **Any other information**
The complex is 'capable of' the overall reaction defined by GO:0047101 (EC:1.2.1.25), and the following subsections:
E1: GO:0003863 3-methyl-2-oxobutanoate dehydrogenase (2-methylpropanoyl-transferring) activity (EC:1.2.4.4)
E2: GO:0043754 dihydrolipoyllysine-residue (2-methylpropanoyl)transferase activity (EC:2.3.1.168)
E3: GO:0004148 dihydrolipoyl dehydrogenase activity (EC:1.8.1.4)

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160120
+name: branched-chain alpha-keto acid dehydrogenase complex
+namespace: cellular_component
+def: "A mitochondrial complex that catalyzes the oxidative decarboxylation of branched-chain alpha-keto acids derived from L-leucine, L-isoleucine, and L-valine to branched-chain acyl-CoAs. The complex is organized around a 24-meric cubic core of the dihydrolipoyl transacylase (E2) with multiple (about 6 to12) copies of the branched-chain alpha-ketoacid dehydrogenase (E1, consisting of alpha and beta subunits), about 6 copies of the dimeric dihydrolipoyl dehydrogenase (E3), and a small number of copies of the E1-specific kinase and phosphatase." [PMID:10745006, PMID:3593587, PMID:9582350]
+synonym: "BCKD complex" EXACT []
+is_a: GO:0098798 ! mitochondrial protein-containing complex
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26121" xsd:anyURI
+created_by: rynl
+creation_date: 2023-10-27T23:46:26Z

**Comment by raymond91125** [comment]
Note: had to remove non-ascii characters in definition.
