### ISSUE TITLE
Term name, definition, synonyms update: axonemal outer doublet - GO:0097545

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#26128]
* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request updates**
axonemal outer doublet - GO:0097545

* **GO term name change**

Based on most common usage via PubMed searches, I recommend changing the term string.
**new name string:** "axonemal doublet microtubule"

**PubMed search results:**
axonemal "doublet microtubule"	 58
axonemal "doublet microtubules"	246

axonemal "outer doublet"	138
axonemal "outer doublets"	 60

axonemal "microtubule doublet"	 27
axonemal "microtubule doublets"	100	

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
"Part of an axoneme consisting of a doublet microtubule (DMT). Each DMT consists of a circular A tubule composed of thirteen tubulin protofilaments composed of alpha-beta tubulin heterodimers and a partial B tubule composed of ten tubulin protofilaments. The partial B tubule is joined to the A tubule at the outer junction (OJ) and inner junction (IJ). The three DMTs of the A tubule that separate the lumens of the A and B tubules are called the ribbon. The outer surface of a DMT is associated with a repetitve series of axonemal complexes, the exact composition of which depends on the type of cilium (motile versus non-motile and 9+0 versus 9+2), but may include inner dynein arms (IDA), radial spokes (RS), outer dynein arms (ODA), and nexin-dynein regulatory complexes (N-DRC). Also depending on the type of cilium, the lumens of the A and B tubules are associated with a variety of microtubule inner proteins (MIPs) that are important for the stability of the DMT." [GOC:cilia, GOC:krc, GOC:pr, PMID:5044758, PMID:5664206, PMID:37295417, Wikipedia:Axoneme]

current def: "Part of an axoneme consisting in a doublet microtubule. Nine of these outer doublets form the 9+0 axoneme, while the 9+2 axoneme also contains a central pair. Dynein arms attached to the doublets provide the mechanism of movement of the cilium."

NOTE CORRECTION in 1st sentence:  change "in" to "of"

I don't think that the explanation of where microtubule doublets are found is needed here as the various cilia terms have that info. What I've suggested here is info about the structure of a microbutule doublet.

* **Reference(s)**
add PMID:37295417 in addition to existing

* **Additional synonyms to add:**
synonym: "axoneme doublet microtubule" EXACT
synonym: "DMT" RELATED
synonym: "axonemal outer doublet" EXACT
synonym: "axonemal microtubule doublet" EXACT
synonym: "axoneme microtubule doublet" EXACT

**Comment by krchristie** [comment]
I've noticed one more thing I think we should fix for this term. 

This term is defined in a way that I would expect that the "axonemal doublet microtubule" is_a "axonemal microtubule":
> id: GO:0005879
> name: **axonemal microtubule**
> namespace: cellular_component
> def: "A microtubule in the axoneme of a eukaryotic cilium or flagellum; **an axoneme contains nine modified doublet microtubules**, which may or may not surround a pair of single microtubules." [GOC:cilia, ISBN:0815316194]
> is_a: GO:0005874 ! microtubule
> intersection_of: GO:0005874 ! microtubule
> intersection_of: part_of GO:0005930 ! axoneme
> relationship: part_of GO:0005930 ! axoneme

Therefore, I would make this change in the is_a parentage for GO:0097545
- from: is_a: GO:0110165 ! cellular anatomical entity
- to: is_a: GO:0005879 ! axonemal microtubule

> id: GO:0097545
> name: axonemal outer doublet
> namespace: cellular_component
> def: "Part of an axoneme consisting in a doublet microtubule. Nine of these outer doublets form the 9+0 axoneme, while the 9+2 axoneme also contains a central pair. Dynein arms attached to the doublets provide the mechanism of movement of the cilium." [GOC:cilia, GOC:krc, GOC:pr, PMID:5044758, PMID:5664206, Wikipedia:Axoneme]
> synonym: "axoneme outer doublet" EXACT []
> synonym: "outer doublet" BROAD []
> synonym: "outer-doublet microtubules" RELATED []
> is_a: GO:0110165 ! cellular anatomical entity
> relationship: has_part GO:0097649 ! A axonemal microtubule
> relationship: has_part GO:0097650 ! B axonemal microtubule
> relationship: part_of GO:0005930 ! axoneme
> created_by: pr
> creation_date: 2013-12-12T11:19:29Z


Regarding the **axonemal microtubule** term, I think we could add some useful info to the definition from:

> def: "A microtubule in the axoneme of a eukaryotic cilium or flagellum; **an axoneme contains nine modified doublet microtubules**, which may or may not surround a pair of single microtubules." [GOC:cilia, ISBN:0815316194]

to this:
> proposed new def: "A microtubule in the axoneme of a eukaryotic cilium or flagellum; an axoneme contains nine modified doublet microtubules **comprised of a complete A tubule joined with a partial B tubule**, which may or may not surround a pair of single microtubules **referred to as C1 and C2**." [GOC:cilia, ISBN:0815316194]

**Comment by raymond91125** [comment]
I am troubled by 'a doublet of X is an X'.

**Comment by krchristie** [comment]
I see your point but think that your comment brings up that we already have a problem in the current children of "**axonemal microtubule**"

-- axonemal microtubule
--- A axonemal microtubule
--- B axonemal microtubule
--- C1 axonemal microtubule
--- C2 axonemal microtubule

where the A and B tubules are part_of the doublet microtubule (DMT), and thus not individual microtubules.

Here's a proposal to consider. Here's the definition of the term "**microtubule**":

**Term:** microtubule
**ID:** GO:0005874
**Def:** Any of the long, generally straight, hollow tubes of internal diameter 12-15 nm and external diameter 24 nm found in a wide variety of eukaryotic cells; each consists (usually) of 13 protofilaments of polymeric tubulin, staggered in such a manner that the tubulin monomers are arranged in a helical pattern on the microtubular surface, and with the alpha/beta axes of the tubulin subunits parallel to the long axis of the tubule; exist in equilibrium with pool of tubulin monomers and can be rapidly assembled or disassembled in response to physiological stimuli; concerned with force generation, e.g. in the spindle.

This definition of "**microtubule**" doesn't really fit the A or B tubules. They are not hollow because they are filled with inner sheath microtubule inner proteins (MIPs) that stabilize them to deal with repeated bending. It probably doesn't work for the C1 or C2 tubules either as they also need to bend with the cilium, but I haven't seen any literature about that. The research for the inner sheath of the A & B tubules is pretty recent, around 2017. Anyway, we could update the "**microtubule**" term to something like this:

**Term:** microtubule structure
**ID:** GO:0005874
**Def:** Any of the long tubular structures of internal diameter 12-15 nm and external diameter 24 nm found in a wide variety of eukaryotic cells; each consists (usually) of 13 protofilaments of polymeric tubulin, staggered in such a manner that the tubulin monomers are arranged in a helical pattern on the microtubular surface, and with the alpha/beta axes of the tubulin subunits parallel to the long axis of the tubule; exist in equilibrium with pool of tubulin monomers and can be rapidly assembled or disassembled in response to physiological stimuli; concerned with force generation, e.g. in the spindle. Some microtubule structures are composed of modified microtubules structures such as the axonemal doublet microtubules where both the A and the B tubules are stabilized by an inner sheath of microtubule inner proteins (MIPs) to resist repeated bending to generate ciliary motion.

Also, this portion of the current definition "exist in equilibrium with pool of tubulin monomers and can be rapidly assembled or disassembled in response to physiological stimuli" may be more relevant to hollow cytoplasmic microtubule than axonemal MTs. While axonemal MTs are assembled and disassembled, they are much more stable and possibly not assembled & disassembled as much.

An alternative would be to change the term "axonemal microtubule" to accomodate the fact that axonemal  microtubules don't seem to have been fully understood when the current definition of "**microtubule**" was written. I think it would be better if the "**microtubule**" term was broad enough to accomodate the axonemal microtubules as the ciliary community calls them microtubules. In addition, there are triplet microtubules in the centriole/basal body; these apparently have a very similar structure as the DMT where the third microtubule is very similar to the B tubule.

**Comment by raymond91125** [comment]
@krchristie You brought up several good points. I'm not sure that I can make a quick decision on this.
I do think part of the problem is that when a definition goes beyond what is necessary and sufficient it has a better chance of becoming too restrictive as 'new' variants are discovered.

**Comment by pgaudet** [comment]
We will keep the definitions as described in the guidelines here: https://wiki.geneontology.org/Protein_complexes#Textual_definition_for_protein-containing_complex_terms

**Comment by raymond91125** [comment]
What we have now:
![image](https://github.com/geneontology/go-ontology/assets/619520/de4fe8ff-c5c4-463c-8e7e-8803fd243d4e)

**Comment by raymond91125** [comment]
I think there is a conflation of microtubule and a collection of microtubules as different types of MT are really part of MT. I've done some revisions requested. If we want to embark on a comprehensive review of microtubule-related terms, we should open a different ticket. Thanks, @krchristie.
