### ISSUE TITLE
Obsoletion request: GO:0019071 viral DNA cleavage involved in viral genome maturation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26134]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0019071 viral DNA cleavage involved in viral genome maturation

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x]  The reason for obsoletion is that this term is pre-composed and should be represented as a GO-CAM model.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP: 1

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [x] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by pgaudet** [comment]
Single annotation by CACAO
consider: [double-stranded DNA endonuclease activity](http://purl.obolibrary.org/obo/GO_1990238) and [viral genome maturation](http://purl.obolibrary.org/obo/GO_0019070)
