### ISSUE TITLE
Obsoletion request: GO:0090305 nucleic acid phosphodiester bond hydrolysis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26133]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0090304 nucleic acid metabolic process
Has 3 children 
DNA metabolic process
RNA metabolic process
And the unnecessary (and misleading( grouping term)
nucleic acid phosphodiester bond hydrolysis (GO:0090305)

nucleic acid phosphodiester bond hydrolysis (GO:0090305)
**Has only 26 EXP annotations.**

All of the children of 
nucleic acid phosphodiester bond hydrolysis (GO:0090305)
Have other parents (or should have once I add
i) DNA metabolic process to "meiotic DNA double-strand break formation"
AND

ii) Obsolete 
GO:0019071 viral DNA cleavage involved in viral genome maturation
A single annotation (I'll open another ticket for this pre-composed term)

<img width="975" alt="Screenshot 2023-09-14 at 11 25 22" src="https://github.com/geneontology/go-ontology/assets/7359272/d8540b5a-6626-4319-a32a-ef38aeaed121">

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x] The reason for obsoletion is that this term represents a molecular function.
 - [x]  The reason for obsoletion is that this term was an unnecessary grouping term.
 - [x]  The reason for obsoletion is that the meaning of the term is ambiguous.
 

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

GO:0090304 nucleic acid metabolic process

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
*  See below

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [ ] check taxon constraints 

***Check annotations***

- [x] https://github.com/geneontology/go-annotation/issues/4765
- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
Changed parent of  GO:0042138 meiotic double-strand break formation
from GO:0090305 nucleic acid phosphodiester bond hydrolysis
to GO:0006259 DNA metabolic process

Changed parent of  GO:0019071   viral DNA cleavage involved in viral genome maturation
from GO:0090305 nucleic acid phosphodiester bond hydrolysis
to GO:0006259 DNA metabolic process
(this term should be obsoleted later)

Removed  superclass GO:0090305 nucleic acid phosphodiester bond hydrolysis
from GO:0031087   deadenylation-independent decapping of nuclear-transcribed mRNA
already has GO:0016070   RNA metabolic process ancestry via another branch

**Comment by pgaudet** [comment]
Is this merged? I wonder why it's not closed?

**Comment by ValWood** [comment]
I did not obsolete it yet because there are annotations which need manually migrating and many mappings to deal with, but the children have been rehoused.
