### ISSUE TITLE
Parent-relationship query: Clathrin-coated pit GO:0005905

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#26136]
GO:0005905 Clathrin-coated pit

is part_of plasma membrane region

but these can form in the TGN so this is not always true?

ref:
https://pubmed.ncbi.nlm.nih.gov/9242916/

**Comment by ValWood** [comment]
Where does it say that? I scanned the chapter but I thought they only form on the plasma membrane ?  (obviously the clathrin coated vesicles occur in the TGN, but do they definitely form there? that wouldn't make sense if clathrin is restricted to endocytosis?)

**Comment by Antonialock** [comment]
https://pubmed.ncbi.nlm.nih.gov/8567724/
https://pubmed.ncbi.nlm.nih.gov/17284835/
https://pubmed.ncbi.nlm.nih.gov/12589051/

**Comment by Antonialock** [comment]
These dynamic steps have been investigated mainly in endocytosis on the cell membrane in living cells by fluorescent microscopy, and the behavior of clathrin-coated pits (CCPs) and the accumulation and dissociation of coat components on the pits have been described. However, the behavior of clathrin during pit formation at the TGN has received less attention.
