### ISSUE TITLE
FYI: Cell Ontology (CL) is obsoleting 'somatic cell'

### ISSUE THREAD

**Issue by bvarner-ebi** [geneontology/go-ontology#26141]
CL is obsoleting the class 'somatic cell' as detailed in https://github.com/obophenotype/cell-ontology/issues/1150.

This issue is an FYI for GO since there are some terms, like '[somatic cell DNA recombination](http://purl.obolibrary.org/obo/GO_0016444)', that invoke the term "somatic cell".

There may be no action item for this issue, but spreading the word in an effort to keep ontologies aligned.

CC @cmungall

**Comment by pgaudet** [comment]
Thanks for the info @bvarner-ebi !

**Comment by pgaudet** [comment]
Actually, I dont see that we refer to CL:somatic cell in GO (we do have terms that have this label, but I cannot find a link to CL). '[somatic cell DNA recombination](http://purl.obolibrary.org/obo/GO_0016444)', does not link to CL.

Closing, please reopen if I missed something.

**Comment by bvarner-ebi** [comment]
@pgaudet, thank your for addressing this ticket. 
I did not identify any GO terms cross-linked to CL, but "somatic cell" is used in at least one text definition. This is just an FYI to GO that the class "somatic cell" is in the process of being obsoleted in CL.
