### ISSUE TITLE
NTRs: new CC terms for substructures of axonemal doublet microtubule

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#26148]
Please provide as much information as you can: 

id: new
name: axonemal microtubule doublet inner sheath
namespace: cellular_component
def: "The structural network of microtubule inner proteins (MIPs) inside the lumens of the A and B tubules of the axonemal microtuble doublet that help stabilize the doublet microtubule and which has a repeat unit length of 48 nanometers, half of the 96 nanometer repeat unit of the structures attached to the outside of the microtubule doublet." [GOC:krc, PMID:29430673, PMID:37295417]
is_a: GO:0110165 ! cellular anatomical entity
relationship: part_of GO:0097545 ! axonemal doublet microtubule

id: new
name: axonemal A tubule inner sheath
namespace: cellular_component
def: "The structural network of microtubule inner proteins (MIPs) inside the lumen of the A tubule of the axonemal microtuble doublet that help stabilize the A tubule." [GOC:krc, PMID:29430673, PMID:37295417]
is_a: GO:0110165 ! cellular anatomical entity
relationship: part_of new ! axonemal microtubule doublet inner sheath
relationship: part_of GO:0097649 ! A axonemal microtubule

id: new
name: axonemal B tubule inner sheath
namespace: cellular_component
def: "The structural network of microtubule inner proteins (MIPs) inside the lumen of the B tubule of the axonemal microtuble doublet that help stabilize the B tubule." [GOC:krc, PMID:29430673, PMID:37295417]
is_a: GO:0110165 ! cellular anatomical entity
relationship: part_of new ! axonemal microtubule doublet inner sheath
relationship: part_of GO:0097650 ! B axonemal microtubule

id: new
name: axonemal microtubule doublet ribbon
namespace: cellular_component
def: "The 3 protofilaments A11, A12, and A13 of the A tubule along with associated inner sheath microtuble inner proteins (MIPs), either in the lumen of the A tubule or of the B tubule, which stabilize these three filiments within the axonemal doublet microtubule. The ribbon protofilaments separate the lumens of the A and B tubules." [GOC:krc, PMID:1262413, PMID:29430673]
is_a: GO:0005874 ! GO:0110165 ! cellular anatomical entity
relationship: part_of GO:0097545 ! axonemal doublet microtubule

id: new
name: axonemal microtubule doublet inner junction
namespace: cellular_component
def: "The structure which joins the B10 protofilament of the B tubule to the A1 protofilament of the A tubule within an axonemal microtubule doublet" [GOC:krc, PMID:29430673, PMID:37295417]
is_a: GO:0005874 ! GO:0110165 ! cellular anatomical entity
relationship: part_of GO:0097545 ! axonemal doublet microtubule

id: new
name: axonemal microtubule doublet outer junction
namespace: cellular_component
def: "The structure which joins the B1 protofilament of the B tubule to the A10 and A11 protofilaments of the A tubule within an axonemal microtubule doublet" [GOC:krc, PMID:29430673, PMID:37295417]
is_a: GO:0005874 ! GO:0110165 ! cellular anatomical entity
relationship: part_of GO:0097545 ! axonemal doublet microtubule

**Comment by raymond91125** [comment]
I wonder if it should be
axonemal A tubule inner sheath IS_A axonemal microtubule doublet inner sheath
axonemal B tubule inner sheath IS_A axonemal microtubule doublet inner sheath
as opposed to PART_OF

**Comment by raymond91125** [comment]
The Sarkosyl ribbon apparently consists of three to four protofilaments depending on the source PMID:24794867. Perhaps it is better to be less specific in the definition.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160110
+name: axonemal microtubule doublet inner sheath
+namespace: cellular_component
+def: "A structural network of microtubule inner proteins (MIPs) located inside 
the lumens of the A and B tubules of the axonemal microtuble doublet that helps 
stabilize the doublet microtubule." [GOC:krc, PMID:29430673, PMID:37295417]
+is_a: GO:0110165 ! cellular anatomical entity
+relationship: part_of GO:0097545 ! axonemal outer doublet
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/
issues/26148" xsd:anyURI
+created_by: rynl
+creation_date: 2023-09-19T17:41:57Z
+
+[Term]
+id: GO:0160111
+name: axonemal A tubule inner sheath
+namespace: cellular_component
+def: "A structural network of microtubule inner proteins (MIPs) located inside the lumen of the A tubule of the axonemal microtubule doublet that helps stabilize the A tubule." [GOC:krc, PMID:29430673, PMID:37295417]
+is_a: GO:0110165 ! cellular anatomical entity
+relationship: part_of GO:0097649 ! A axonemal microtubule
+relationship: part_of GO:0160110 ! axonemal microtubule doublet inner sheath
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26148" xsd:string
+created_by: rynl
+creation_date: 2023-09-19T17:50:09Z
+
+[Term]
+id: GO:0160112
+name: axonemal B tubule inner sheath
+namespace: cellular_component
+def: "A structural network of microtubule inner proteins (MIPs) located inside the lumen of the B tubule of the axonemal microtubule doublet that helps stabilize the B tubule." [GOC:krc, PMID:29430673, PMID:37295417]
+is_a: GO:0110165 ! cellular anatomical entity
+relationship: part_of GO:0097649 ! A axonemal microtubule
+relationship: part_of GO:0160110 ! axonemal microtubule doublet inner sheath
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26148" xsd:anyURI
+created_by: rynl
+creation_date: 2023-09-19T18:06:17Z
+
+[Term]
+id: GO:0160113
+name: axonemal microtubule doublet inner junction
+namespace: cellular_component
+def: "The structure which joins the B10 protofilament of the B tubule to the A1 protofilament of the A tubule within an axonemal microtubule doublet." [GOC:krc, PMID:29430673, PMID:37295417]
+is_a: GO:0110165 ! cellular anatomical entity
+relationship: part_of GO:0097545 ! axonemal outer doublet
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26148" xsd:anyURI
+created_by: rynl
+creation_date: 2023-09-20T22:22:35Z
+
+[Term]
+id: GO:0160114
+name: axonemal microtubule doublet outer junction
+namespace: cellular_component
+def: "The structure which joins the B1 protofilament of the B tubule to the A10 and A11 protofilaments of the A tubule within an axonemal microtubule doublet." [GOC:krc, PMID:29430673, PMID:37295417]
+is_a: GO:0110165 ! cellular anatomical entity
+relationship: part_of GO:0097545 ! axonemal outer doublet
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26148" xsd:anyURI
+created_by: rynl
+creation_date: 2023-09-20T22:26:23Z
+
+[Term]
+id: GO:0160115
+name: axonemal microtubule doublet ribbon
+namespace: cellular_component
+def: "The 3 protofilaments A11, A12, and A13 of the A tubule along with associated inner sheath microtuble inner proteins (MIPs), either in the lumen of the A tubule or of the B tubule, which stabilize these three filiments within the axonemal doublet microtubule. The ribbon protofilaments separate the lumens of the A and B tubules." [GOC:krc, PMID:1262413, PMID:29430673]
+is_a: GO:0110165 ! cellular anatomical entity
+relationship: part_of GO:0097545 ! axonemal outer doublet
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26148" xsd:anyURI
+created_by: rynl
+creation_date: 2023-09-20T22:28:52Z

**Comment by raymond91125** [comment]
I merged the pull request. i.e. The terms are in. We can make appropriate revisions.

**Comment by raymond91125** [comment]
A clear picture confirming "inner" (junction) means closer to axoneme center. Perhaps that should be a main part of the definition.
![image](https://github.com/geneontology/go-ontology/assets/619520/723aa379-fb3b-4117-aff1-d0cfdba454c3)
