### ISSUE TITLE
NTR: [Broken chromosome tethering]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#26156]
Hi GO,

Two recent papers describe the role of CIP2A and TOPBP1 in the response to genome instability generated by the presence of acentric chromosome fragments derived from shattered chromosomes within micronuclei.

The role of this complex is to tether chromosome fragments during mitosis to ensure clustered segregation of the fragments to a single daughter cell nucleus, facilitating religation with limited chromosome scattering and loss.

For the moment, I wouldn't create any GO molecular function to describe the activity of the CIP2A-TOPBP1 complex, since it is still unclear how tethering is done. But it would be useful to create Biological Process terms related to the 'repair' of broken chromosomes to preserve genome integrity.

Thanks

Sylvain

PS: Please note that I will be absent from September 22nd to the 16th of October

Description: Broken chromosome tethering
Definition: A process that tethers broken chromosomes to prevent the scattering and loss of chromosomes fragments derived from shattered chromosomes. Broken chromosome tethering during mitosis ensures clustered segregation of the fragments to a single daughter cell nucleus, facilitating re-ligation with limited chromosome scattering and loss.

Child of GO:0051276 chromosome organization
Child of GO:0006974 DNA damage response

RX PubMed=37165191; DOI=10.1038/s41586-023-05974-0
RA Lin Y.F., Hu Q., Mazzagatti A., Valle-Inclan J.E., Maurais E.G., Dahiya R., Guyer A., Sanders J.T., Engel J.L., Nguyen G., Bronder D., Bakhoum S.F., Cortes-Ciriano I., Ly P.
RT Mitotic clustering of pulverized chromosomes from micronuclei.
RL journal article: Nature 618:1041-1048 (2023)

RX PubMed=37316668; DOI=10.1038/s41586-023-06216-z
RA Trivedi P., Steele C.D., Au F.K.C., Alexandrov L.B., Cleveland D.W.
RT Mitotic tethering enables inheritance of shattered micronuclear chromosomes.
RL journal article: Nature 618:1049-1056 (2023)

**Comment by pgaudet** [comment]
@ValWood 's feedback

> Yes it's early days so it's difficult to know. I wonder if this is just a general version of the nuclear envelope tethering of DNA damage (it would come detached in metazoa at nuclear breakdown).
It's difficut to know what the normal process would be  because this is in cancer cells.
It's probably related to 
https://github.com/geneontology/go-ontology/issues/25072
(Which I never got back to yet, it will require quite a big review)
I think these tethering processes are multistep because they likely involve specific modifications....The SUMOYlation pathway is involved

**Comment by pgaudet** [comment]
Discussed with @sylvainpoux 
Agreed to name this term 'broken chromosome clustering'

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141112
+name: broken chromosome clustering
+namespace: biological_process
+def: "The process of bringing together chromosomes fragments resulting from DNA damage. Broken chromosome tethering during mitosis ensures clustered segregation of the fragments to a single daughter cell nucleus, facilitating re-ligation with limited chromosome scattering and loss and enhancing genome integrity." [PMID:37165191, PMID:37316668]
+is_a: GO:0051276 ! chromosome organization
+relationship: part_of GO:0006974 ! DNA damage response
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26156" xsd:anyURI
+created_by: pg
+creation_date: 2023-10-31T12:21:09Z
+
