### ISSUE TITLE
Term name update: intramolecular transferase subclasses

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26155]
I think the following 4 grouping terms could have more succinct names, as indicated below.
@pgaudet if you agree, I could make the changes myself.

id: GO:0016867
name: intramolecular transferase activity, transferring acyl groups
def: "Catalysis of the transfer of an acyl group from one position to another within a single molecule." [GOC:mah]
xref: EC:5.4.1.-
=> intramolecular acyltransferase activity

id: GO:0016868
name: intramolecular transferase activity, phosphotransferases
def: "Catalysis of the transfer of a phosphate group from one position to another within a single molecule." [GOC:mah]
xref: EC:5.4.2.-
=> intramolecular phosphotransferase activity

id: GO:0016869
name: intramolecular transferase activity, transferring amino groups
def: "Catalysis of the transfer of an amino group from one position to another within a single molecule." [GOC:mah]
xref: EC:5.4.3.-
=> intramolecular aminotransferase activity

id: GO:0050486
name: intramolecular transferase activity, transferring hydroxy groups
def: "Catalysis of the transfer of a hydroxyl group from one position to another within a single molecule." [GOC:mah]
xref: EC:5.4.4.-
=> intramolecular hydroxytransferase activity

**Comment by pgaudet** [comment]
Sounds good. Remember to add the old labels as EXACT synonyms. 

Thanks, Pascale
