### ISSUE TITLE
transcription initiation-coupled chromatin remodeling (GO:0045815) parentage query

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26161]
CC @colinlog @pgaudet 

transcription initiation-coupled chromatin remodeling (GO:0045815)
Should this have a parent to transcription initiation, or was it an explicit decision not to add this?

Note that 
transcription elongation-coupled chromatin remodeling (GO:0140673)
Does have a parent to
transcription elongation by RNA polymerase II (GO:0006368)

But maybe there is a reason for the difference. 
Apologies if I asked about this before.

**Comment by pgaudet** [comment]
I feel like this was brought up before. As far as I recall, this occurs before initiation, so we cannot add a relation 'part of initiation of transcription' 

to be confirmed with @colinlog

**Comment by ValWood** [comment]
OK, I think my problem is that I annotated SAGA by IC to "transcription elongation-coupled chromatin remodeling" but SAGA isn't chromatin remodelling and it should only be annotated to 
"positive regulation of transcription initiation by RNA polymerase II (GO:0060261)"
like mediator.
@colinlog is that correct?

**Comment by colinlog** [comment]
Chromatin remodelling comes in two forms: nucleosomal histone post
translational modification GO:0140993 and ATP-dependent nucleosome
remodelling. SAGA belongs to the former as it has the GCN5 histone
acetylase. So, I would include it in remodelling ( GO:0140993). This is in
addition to the GO:0060261 annotation.

**Comment by pgaudet** [comment]
Created a new ticket requesting the same parentage 
https://github.com/geneontology/go-ontology/issues/26319

So this ticket here is now a duplicate.

**Comment by ValWood** [comment]
I  also wanted to record that some of my community who work on chromatin-related processes   have objected to  SAGA being classed as a chromatin remodeller. They say that most of the community would refer to SAGA as  "chromatin re-organization" but not "chromatin remodelling"  which is restricted to the ATP-dependent remodelers.
I tried  explain that as a process we define chromatin remodelling more broadly as"A dynamic process of chromatin reorganization resulting in changes to chromatin structure." and it is not in GO restricted to processes involving ATP-dependent chromatin remodeler activity (GO:0140658)
but I wonder if this use might be quite confusing for many in the field?

**Comment by pgaudet** [comment]
What do you suggest? 

A BP is 'coordinated biological module'; that can not be limited to any activity using ATP. We can add comments and clarify the definitions, but I dont think we can make ATP-dependent activities a BP.

**Comment by ValWood** [comment]
I agree! In the proposed view "chromatin remodelling" is analogous to "chromatin modification"  (this was how they described it   "modifiers and remodelers".  This would mean we would not have "remodelling" in the process ontology, it would be a related synonym of the remodelling activities, and the chromatin remodelling BP terms would be renamed "reorganization" and could have e remodelling as a narrow synonym. 
I don't know how prevalent this stricter view of "chrome atin remodelling"  is,  so we. can keep as is for now. I wanted to report so that if it is raised again we know what the issue is and that there is a solution.

For what it's worth, Wikipedia used the broader view of remodelling 
https://en.wikipedia.org/wiki/Chromatin_remodeling so I think we can ignore for now and reconsider if we get more negative feedback on this issue.

**Comment by colinlog** [comment]
Yes Val, as described in the wiki page you refer to and in the literature, it is consensual to consider both nucleosomal histone (de)modification and ATP-dependent remodelling (slide, dismantle, replace a histone with another histone variant) as 'chromatin remodelling' activities, which is part of the chromatin organisation BP. Hence SAGA should have both a coTF (MF) and a remodelling activity (MF) annotations as well as the transcription intiation BP and the chromatin remdelling/chromatin organisation BPs.

Remodeling is the activity term that the field uses, rather than organisation. There are often many such activities that work in cascades to perform the process remodelling. Perhaps it is better to call the process 'chromatin organisation' than chromatin remodelling? To me these are broad synonyms when talking about the process.

The view that only dbTFs and their coTFs are part of the regulation branch is also consensual I believe.

**Comment by ValWood** [comment]
OK,
and this  was one of my main remaining questions to answer:

>The view that only dbTFs and their coTFs are part of the regulation branch is also consensual I believe.


So I will open PAINT tickets for the violations.
CC @marcfeuermann
