### ISSUE TITLE
    GO:0140658 ATP-dependent chromatin remodeler activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26160]
Please add English spelling remodeller to 
  GO:0140658 ATP-dependent chromatin remodeler activity
and children

also add
 blah remodelling/remodeling activity 
as exact synonym 

and  add remodeller/remodelling all of the "remodeler/remodeling' terms as exact synonyms

Thanks!

**Comment by pgaudet** [comment]
Done - I also fixed other terms containing remodeling (but not all - there are many tissue remodeling terms)

**Comment by pgaudet** [comment]
Got all of them, AFAIK. I didn't try to add synonyms to the synonyms (upregulation of modeling... for example)

**Comment by ValWood** [comment]
I agree, who says "upregulation"?
