### ISSUE TITLE
remove Do not annotate from GO:0006506 GPI anchor biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26171]
GO:0006506 GPI anchor biosynthetic process has a "do not annotate" flag?
I'm not sure why that was added. There is no alternative?

**Comment by pgaudet** [comment]
When we marked all children of 'protein modification process' as do not annotate, as if we were going to obsolete, that wa a bit over enthusiastic. 

Thanks for reporting this. Removing.

**Comment by pgaudet** [comment]
What about children? 
'GPI anchor biosynthetic process via N-alanyl-glycosylphosphatidylinositolethanolamine'
'GPI anchor biosynthetic process via N-asparaginyl-glycosylphosphatidylinositolethanolamine'
'GPI anchor biosynthetic process via N-aspartyl-glycosylphosphatidylinositolethanolamine'
etc? 

are these MFs?

**Comment by pgaudet** [comment]
They have no annotations. I'll obsolete.

**Comment by ValWood** [comment]
Yes, I never really understood what these terms were for so I  never used them.

There is another descendant term that sounds a bit like an MF although I am not so sure about this one
https://www.pombase.org/term/GO:0006506

see  [attachment of GPI anchor to protein](https://www.pombase.org/term/GO:0016255)
but it has quite a few annotations so it could be a BP?

**Comment by ValWood** [comment]
That seems to be another way of saying
GO:0003923 | GPI-anchor transamidase activity

[GO:0003923](https://www.pombase.org/term/GO:0003923)	
[GPI-anchor transamidase activity](https://www.pombase.org/term/GO:0003923)
https://www.pombase.org/results/from/id/b092ab5b-3b00-4e89-b240-a91518faf90d

**Comment by deustp01** [comment]
> What about children?
> 'GPI anchor biosynthetic process via N-alanyl-glycosylphosphatidylinositolethanolamine'

That looks like a specific variant of a process with a few different ways to reach its endpoint.
