### ISSUE TITLE
GO:0018064 & GO:0003908 - missing parent?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26174]
I think these two terms need 'GO:0008276 protein methyltransferase activity' as an additional parent?

id: GO:0018064
name: protein-L-histidine N-tele-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-histidyl-[protein] + S-adenosyl-L-methionine = N(tele)-methyl-L-histidyl-[protein] + S-adenosyl-L-homocysteine." [RHEA:19369]
synonym: "actin-specific histidine methyltransferase activity" RELATED [EC:2.1.1.85]
synonym: "peptidyl-histidine N-methyltransferase activity" EXACT []
synonym: "protein (histidine) methyltransferase activity" RELATED [EC:2.1.1.85]
synonym: "protein methylase IV activity" NARROW [EC:2.1.1.85]
synonym: "protein-histidine N-methyltransferase activity" BROAD []
synonym: "S-adenosyl methionine:protein-histidine N-methyltransferase activity" RELATED [EC:2.1.1.85]
synonym: "S-adenosyl-L-methionine:protein-L-histidine N-tele-methyltransferase activity" RELATED [EC:2.1.1.85]
xref: EC:2.1.1.85
xref: MetaCyc:2.1.1.85-RXN
xref: RHEA:19369
is_a: GO:0008170 ! N-methyltransferase activity
is_a: GO:0008757 ! S-adenosylmethionine-dependent methyltransferase activity

id: GO:0003908
name: methylated-DNA-[protein]-cysteine S-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: DNA (containing 6-O-methylguanine) + (protein)-L-cysteine = DNA (without 6-O-methylguanine) + protein S-methyl-L-cysteine." [EC:2.1.1.63]
synonym: "6-O-methylguanine-DNA methyltransferase activity" RELATED [EC:2.1.1.63]
synonym: "DNA-6-O-methylguanine:[protein]-L-cysteine S-methyltransferase activity" EXACT []
synonym: "DNA-6-O-methylguanine:protein-L-cysteine S-methyltransferase activity" RELATED [EC:2.1.1.63]
synonym: "methylated-DNA-protein-cysteine S-methyltransferase activity" RELATED [EC:2.1.1.63]
synonym: "MGMT" EXACT []
synonym: "O-6-methylguanine-DNA-alkyltransferase activity" RELATED [EC:2.1.1.63]
synonym: "O6-alkylguanine-DNA alkyltransferase" BROAD []
xref: EC:2.1.1.63
xref: MetaCyc:2.1.1.63-RXN
xref: RHEA:24000
is_a: GO:0008172 ! S-methyltransferase activity

**Comment by pgaudet** [comment]
Hi @sjm41 
No problem for GO:0018064  protein-L-histidine N-tele-methyltransferase activity; 

however for GO:0003908 methylated-DNA-[protein]-cysteine S-methyltransferase activity, it seems like the goal of the reaction is not to methlyate the protein, but to demethylate (e repair) the DNA. Therefor the protein is not really a substrate, it's an acceptor, so I would not add the 'protein methylase activity' parent. 

What do you think ? 

Thanks, Pascale

**Comment by sjm41** [comment]
Hi @pgaudet I see what you mean about GO:0003908...
Though the GO term does seem to be classed as a "methyltransferase" (in the term name, current parentage, EC classification) rather than a "demethylase", so adding the extra "protein methyltransferase activity" parent (in addition to the current "S-methyltransferase activity" parent) doesn't seem wrong?
("protein methyltransferase activity" def: Catalysis of the transfer of a methyl group (CH3-) to a protein.)

Not a biggie either way....

**Comment by sjm41** [comment]
@pgaudet OK if I go ahead and add the suggested parent to these two terms myself?

**Comment by pgaudet** [comment]
yes, sure!
