### ISSUE TITLE
Incorrect parent  GO:0070865 investment cone

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26172]
GO:0070865 investment cone

is_a cellular anatomical entity, 
part_of protein-containing complex 
AND 
part_of cytoskeleton, (which is_a cellular anatomical entity)

This seems wrong; a cellular anatomical entity should not be part of a complex? 

<img width="317" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/acac3db2-4c03-4fe5-b60d-d5a72e50d8ab">

@hattrill 
Is this a protein complex or an organelle? 

Thanks, Pascale

**Comment by hattrill** [comment]
the problem is with sperm individualization complex, I think - that is not a "complex" but a cytosketal structure. We fix it at that level, should be ok.

**Comment by raymond91125** [comment]
It appears that investment cone is an actin-rich cytoskeletal structure "The last steps in Drosophila spermiogenesis are the individualization ([Fig. 1C](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3469442/figure/F1/)) and coiling of mature sperm. Individualization proceeds via formation of the individualization complex (IC), which consists of 64 investment cones rich in filamentous actin" PMID:23087837. Whereas the individualization complex is a membrane-cytoskeletal complex PMID:9550716.

A model figure PMID:10588662
![image](https://github.com/geneontology/go-ontology/assets/619520/1ba6dd97-b84c-49a6-a2a2-891a9df637aa)
[Figure 10](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC25762/figure/F10/)

Model for the role of 95F myosin during individualization. 95F myosin (myosin VI; purple) functions during individualization to recruit vesicles (green circles) to the actin-rich cortex underlying the spermatid plasma membrane. 95F myosin transports vesicles a short distance along these actin filaments to the advancing edge of the investment cone. Once the vesicles arrive, they are incorporated into the remodeled membrane, which will enclose each sperm. The accumulation of 95F myosin-rich vesicles at the site of incorporation leads to 95F myosin enrichment in a ring at the base of the actin cone.

**Comment by pgaudet** [comment]
@hattrill : the actions would be to change
-  GO:0070864   sperm individualization complex is_a [GO:0032991 protein-containing complex](https://amigo.geneontology.org/amigo/term/GO:0032991#display-lineage-tab) to is a cellular anatomical entity
- change the definition of GO:0070864   sperm individualization complex from "A macromolecular complex that includes cytoskeletal components and part of the cell membrane" to "A cellular structure that includes... " 

Is this right? 

Thanks, Pascale

**Comment by hattrill** [comment]
That sounds good to me @pgaudet
