### ISSUE TITLE
Parentage of chromatin vs nucleolar chromatin

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#26175]
nucleolar chromatin GO:0030874
is classed as part_of
chromatin GO:0000785

but should be an is_a

<img width="686" alt="Screenshot 2023-09-26 at 16 38 32" src="https://github.com/geneontology/go-ontology/assets/11865746/1e6d9e6a-474a-473c-8f72-ac30ac82bd06">

Also chromatin
is_a protein-DNA complex

whereas nucleolar chromatin
is_a cellular anatomical entity

Not sure which one is correct, I think I would lean to chromatin being a cellular anatomical entity as it is not a discrete unit.

**Comment by pgaudet** [comment]
>  I think I would lean to chromatin being a cellular anatomical entity as it is not a discrete unit.

Anyone has a strong feeling about this? That affects whether we can annotate occurs_in, or not

**Comment by ValWood** [comment]
I assume we can only use occurs_at with cellular anotomical entities?
I would say "cellular anotomical entitiy"  rather than protein DNA complex (which actually sounds quite strange)

**Comment by hattrill** [comment]
Looks like it. With the transcription guidelines, I believe the rules say to annotate as occurs in chromatin.
