### ISSUE TITLE
Obsoletion request: polysome binding & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26170]
Please provide as much information as you can:
Following up on https://github.com/geneontology/go-ontology/issues/24651

* **GO term ID and Label**
'polysome binding' <http://purl.obolibrary.org/obo/GO_1905538>
'regulation of polysome binding' <http://purl.obolibrary.org/obo/GO_1905696>
'negative regulation of polysome binding' <http://purl.obolibrary.org/obo/GO_1905697>
'positive regulation of polysome binding' <http://purl.obolibrary.org/obo/GO_1905698>

* **Reason for deprecation** Put an x in the appropriate box: 
Outside the scope of GO; this is a high level complex of ribosomes, and doesn't provide any additional information compared to 'GO:0043022 ribosome binding'

* **"Replace by" term (ID and label)**
- GO:1905538 polysome binding >> replace by GO:0043022 ribosome binding
- regulation of binding need to be looked at; I cannot suggest a replacement

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP: 20

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [x] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [x] paste the text in the ontology ticket

**Comment by raymond91125** [comment]
Shouldn't this be included in the pending discussion? https://github.com/geneontology/go-annotation/issues/4750

**Comment by lreiser** [comment]
2 TAIR annotations removed.

**Comment by raymond91125** [comment]
Dear all,

The proposal has been made to obsolete
GO:1905538 polysome binding
GO:1905696 regulation of polysome binding
GO:1905698 positive regulation of polysome binding
GO:1905697 negative regulation of polysome binding

    The reason for obsoletion is that the terms are outside the scope of GO.

Annotations:
There are X experimental annotations to this term by
UniProt 11
MGI 4 (removed)
TAIR 2
SGD 1 (removed)
UCL 1 (removed)

There are no mappings to this term.

This term is not present in any subset.

Annotations can be viewed here: https://docs.google.com/spreadsheets/d/1ETWpaqztdAmlvRhUOv-MqUsK0bGMkVYAKQT3VkEtols/edit#gid=0

GO:1905538 polysome binding is being replaced by GO:0043022 ribosome binding.

Any comments can be added to the issue: https://github.com/geneontology/go-ontology/issues/26170

Thanks,
