### ISSUE TITLE
NTR symbiont-mediated suppression of host toll-like receptor signal transduction

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26183]
For GO-PATHGO alignment

@genegodbold to provide references

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141105
+name: symbiont-mediated suppression of host toll-like receptor signal transduction
+namespace: biological_process
+def: "A process in which a symbiont interferes with, inhibits or disrupts a toll-like receptor signaling pathway in the host organism. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:curators]
+synonym: "symbiont-mediated disruption of host toll-like receptor signaling pathway" EXACT []
+synonym: "symbiont-mediated suppression of host toll-like receptor signaling pathway" EXACT []
+is_a: GO:0052029 ! symbiont-mediated suppression of host signal transduction pathway
+created_by: pg
+creation_date: 2023-09-27T14:37:00Z

**Comment by genegodbold** [comment]
- Phosphatidylinositol-specific phospholipase C (PI-PLC; 1-phosphatidylinositol phosphodiesterase) from _Bacillus anthracis_: PI-PLC of B_anthracis decreases host dendritic cell function and T cell responses, possibly by cleaving GPI-anchored proteins that are important for the toll-like receptor-mediated activation. Treatment of host cells with PI-PLC inhibits activation of dendritic cells by TLR ligands such as lipopolysaccharide, peptidoglycan, and CpG DNA [PMID:15944308].
- Macrophage migration inhibitory factor (PfMIF) from _Plasmodium falciparum_: Treatment with recombinant PfMIF decreases surface expression of TLR2, TLR4, and CD86 on human monocytes [PMID:17299722]. PfMIF binds to the host MIF receptor (CD74), which is highly expressed on the surface of host antigen-presenting cells [PMID:21406224]. 
- I329 from African swine fever virus: I329L is a heavily glycosylated protein expressed on the host cell membrane which acts as a toll-like receptor 3 (TLR3) and TLR4 homolog inhibiting the induction of host interferon normally triggered through these receptors. It inhibits dsRNA-stimulated activation of NFkappaB, interferon response factor 3 (IRF3), interferon-beta, and the CCL5 chemokine. This inhibition of immune responses could be overcome by overexpression of host TRIF, an intracellular mediator of TLR3 activity [PMID:21203785].
- Toll/interleukin-1 receptor (TIR)-domain containing protein (BtpA; Btp1; TcpB; BAB1_0279; BruAb1_0274) from _Brucella abortus_: TcpB has a phosphoinositide phosphate-binding domain at its N terminus and TIR domain at its C terminus. TcpB suppresses TLR2- and TLR4-mediated signaling along with the expression of proinflammatory cytokines [PMID:18327267]. TcpB induces the ubiquitination and subsequent destruction of the TLR2/4 adaptor protein TIRAP to suppress TLR signaling [PMID:19196716]. TcpB suppresses LPS-induced activation of NFkappaB [PMID:20471373]. TcpB interacts with host MAL, MyD88, and TLR4 but interferes "...only with the MAL-TLR4 interaction" [PMID:24265315].
- Toll/interleukin-1 receptor domain-containing protein (TcpC) from _Escherichia coli_: TcpC binds to the host MyD88 adaptor protein in vitro. TcpC suppresses TNF secretion in MyD88 positive cells but not in MyD88 deficient cells [PMID:18327267]. TcpC inhibits both LPS-driven, host MyD88 dependent TNF secretion and LPS-driven, MyD88 independent TNF secretion in murine macrophages. TcpC increases bacterial burden in the urinary tract, abscess formation in the kidneys, and tissue pathology in a mouse model of urinary tract infection. Bacterial counts were lower and kidney pathology was not present in mice lacking host Tlr4 and the MyD88 adaptor protein [PMID:20886104]. The crystal structure reveals that TcpC directly associates with MyD88 and TLR4 to reduce the TLR-induced cytokine induction [PMID:23569230].
