### ISSUE TITLE
TPV: ncRNA 5' end-processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26208]
<img width="409" alt="GO-----parent fix URGENT" src="https://github.com/geneontology/go-ontology/assets/7359272/ce421bdd-a1fa-425a-b076-dc9aea2cdd5c">

Is a descendant of "RNA capping"

This seems incorrect? ncRNA 5' end-processing (unless they are equivalent, what  are the other parts of 5' processing"?

@sjm41 
@pgaudet

**Comment by ValWood** [comment]
5' and 3' end processing are both complicated and important pathways with different effects on gene expression. We definitely need them both for mRNA, **ncRNA**, tRNA. 

For the rRNA I'm not so sure that these are separate pathways, especially since the  5' end of one species is sometimes the 3' end of another one  and so I agree that just  **rRNA processing**  would probably be better here. Some of these terms do seem to be activities describing specific cleavage events. However,  I remember when I looked at the annotations they often have a lot of annotations (IMP) as though everything which blocks at each cleavage event is annotated to the cleavage process. I was going to review rRNA processing until the nuclear surveillance pathways are done (I know little about this).

**Comment by pgaudet** [comment]
The problem is that 5' and 3' end processing can lead to either maturation or degradation, and now the ontology is very unclear about this, which seems the most important biological aspect.

**Comment by ValWood** [comment]
Yes, that's what I was thinking. Some of this is there, but not all.
It's unfortunate also that we have lots of separate terms for the same process (nuclear  5' end processing of mRNA  ncRNA and cryptic transcripts appear to use  the same pathway).  I still didn't finish removing the single steps yet. I'll return to that tomorrow.  I'll remove the incorrect parent here though because it will cause problems for analyses and annotate lots of gene products to capping inappropriately.

**Comment by ValWood** [comment]
deleted equivalence axiom
'RNA capping' and ('has primary input' some ncRNA)

**Comment by ValWood** [comment]
git commit -m ‘closes #26208’

(not sure why it didn't close automatically?)
