### ISSUE TITLE
Obsolete GO:0018600 alpha-pinene dehydrogenase activity?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26207]
id: GO:0018600
name: alpha-pinene dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: alpha-pinene + O2 + 2 H+ + 2 e- = H2O + myrtenol." [UM-BBD_reactionID:r0709]
xref: EC:1.14.-.-
xref: UM-BBD_reactionID:r0709
is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen

The EC:1.14.-.- xref should be removed from GO:0018600 (it's already correctly on GO:0016705).
Actually, GO:0018600 could be obsoleted since it has no annotations and no obvious EC/RHEA term

**Comment by pgaudet** [comment]
Hi @emanuel-schmid
Looking at the eawag-bbd entry for this: http://eawag-bbd.ethz.ch/servlets/pageservlet?ptype=r&reacID=r0709
it cites this paper https://pubmed.ncbi.nlm.nih.gov/10192895/
I dont have access to the full text, but is there evidence that this activity exists? It seems from the abstract that some cell extracts gave some products, but it could be multi-steps reactions catalyzed by multiple proteins. 

It may be more appropriate to map to  'GO:0033074 pinene catabolic process' and 'GO:0046249 alpha-pinene catabolic process' , since we dont have direct evidence of the enzymatic activity described by  GO:0018600 alpha-pinene dehydrogenase activity. 

What do you think? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Removed EC
Added references for pienene catabolic process

**Comment by pgaudet** [comment]
[alpha-pinene monooxygenase [NADH] activity](http://purl.obolibrary.org/obo/GO_0018634) is incorrectly mapped: 
The reaction described is "Catalysis of the reaction: alpha-pinene + NADH + H+ + O2 = NAD+ + H2O + alpha-pinene oxide." and is correctly mapped to [UM-BBD_reactionID:r0742](http://eawag-bbd.ethz.ch/servlets/pageservlet?ptype=r&reacID=r0742)


However we have a related term, [alpha-pinene monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018595), describing [UM-BBD_reactionID:r0716](http://eawag-bbd.ethz.ch/servlets/pageservlet?ptype=r&reacID=r0716): Catalysis of the reaction: alpha-pinene + O2 + 2 H+ + 2 e- = H2O + pinocarveol.
GO and UM-BBD match; however that term has EC:1.14.13.155 and RHEA:32891, that correspond to [alpha-pinene monooxygenase [NADH] activity](http://purl.obolibrary.org/obo/GO_0018634) . 

- [ ] Move EC and RHEA from GO:0018595 to GO:0018634
- [ ] question for @emanuel-schmid: should we obsolete  [alpha-pinene monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018595), or is there evidence for that reaction?

**Comment by pgaudet** [comment]
[pinene synthase activity](http://purl.obolibrary.org/obo/GO_0050550) : EC:4.2.3.14 : transferred to [EC:4.2.3.119](https://enzyme.expasy.org/EC/4.2.3.119) and [4.2.3.120](https://enzyme.expasy.org/EC/4.2.3.120) . 

However it seems that most enzymes can produce both the alpha and the beta form, sometimes one more efficiently than the other, but for now we can keep these as NARROW xrefs of GO:0050550. 

Also add NARROW Xrefs [RHEA:25488](https://www.rhea-db.org/rhea/25488) and [RHEA:25496](https://www.rhea-db.org/rhea/25496)

**Comment by pgaudet** [comment]
Discussed with Kathrin at EAWAG-BBD, and she agrees that there is no biochemical evidence for the two reactions being questionned: 
GO:0018600 alpha-pinene dehydrogenase activity
GO:0018847 alpha-pinene lyase activity 

Papers cited characterized the degradation of pinene, but the reactions are not know. 

Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
GO:0018600 alpha-pinene dehydrogenase activity
GO:0018847 alpha-pinene lyase activity

The reason for the obsoletion is that there is no evidence that these reactions exist. There are no annotations to these terms; these terms are not present in any subsets. The reactions have cross references to BBD database, but  papers cited have no biochemical evidence.

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/26207

Thanks, Pascale
