### ISSUE TITLE
Textual definition update: GO:0061759 alpha-ketoglutarate reductase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26213]
Looking at these 3 terms relating to EC:1.1.99.2:
```
2-hydroxyglutarate dehydrogenase activity GO:0047545
    |_2-hydroxyglutarate dehydrogenase activity, forward reaction GO:0061758
    |_alpha-ketoglutarate reductase activity GO:0061759
```

id: GO:0047545
name: 2-hydroxyglutarate dehydrogenase activity
def: "Catalysis of the reaction: (S)-2-hydroxyglutarate + acceptor = 2-oxoglutarate + reduced acceptor." [EC:1.1.99.2, MetaCyc:2-HYDROXYGLUTARATE-DEHYDROGENASE-RXN]
xref: EC:1.1.99.2
xref: MetaCyc:2-HYDROXYGLUTARATE-DEHYDROGENASE-RXN
xref: RHEA:21252
is_a: GO:0016614 ! oxidoreductase activity, acting on CH-OH group of donors

id: GO:0061758
name: 2-hydroxyglutarate dehydrogenase activity, forward reaction
def: "Catalysis of the reaction: (S)-2-hydroxyglutarate + acceptor -> 2-oxoglutarate + reduced acceptor." [EC:1.1.99.2, GOC:dph, MetaCyc:2-HYDROXYGLUTARATE-DEHYDROGENASE-RXN]
xref: RHEA:21253
is_a: GO:0047545 ! 2-hydroxyglutarate dehydrogenase activity

- [x] Remove EC:1.1.99.2 & MetaCyc:2-HYDROXYGLUTARATE-DEHYDROGENASE-RXN] (=bidirectional) from the def
- [x] Add RHEA:21253 as the def xref

id: GO:0061759
name: alpha-ketoglutarate reductase activity
def: "Catalysis of the reaction: 2-oxoglutarate + reduced acceptor = (S)-2-hydroxyglutarate + acceptor." [EC:1.1.99.2, GOC:dph, PMID:26774271, RHEA:21254]
xref: RHEA:21254
is_a: GO:0047545 ! 2-hydroxyglutarate dehydrogenase activity

- [x] The '=' sign in the GO:0061759 def should be changed to '->' to match RHEA:21254 and differentiate it from the def of the parent term.
- [x] Remove EC:1.1.99.2 (=bidirectional) from the def

**Comment by pgaudet** [comment]
Hi @sjm41 

* the GO rule is to map to the non-direction RHEA, so that would be RHEA:21252 (and without the -> in the textual definition)
* I think in GO these terms should be merged, unless there is a reason to keep all 3 reactions?

**Comment by sjm41** [comment]
Hi @pgaudet

_the GO rule is to map to the non-direction RHEA, so that would be RHEA:21252 (and without the -> in the textual definition)_
Yes, RHEA:21252 is correctly on the parent (non-directional) term GO:0047545.

_I think in GO these terms should be merged, unless there is a reason to keep all 3 reactions?_
I think this is a rare case where we do need to keep both directional terms as the two reaction directions are catalysed by different enzymes (LDH and L2HGDH) and have opposite effects on lactate metabolism. This is true in flies at least (see PMID: 28115720) and I guess in other species too - the PMID:26774271 reference David originally used for defining GO:0061759 is from yeast.

**Comment by sjm41** [comment]
I was wondering about that....
There are only 14 EXP annotations to the parent term, so they could certainly be reviewed to see if they could all be moved to a child.
One complication is that the EC number and MetaCyc xref are (correctly) for the non-directional reaction - would making the parent 'do not annotate' create a problem for EC2GO (or does it just apply to manual annotations)? Maybe the EC number should be a (narrow?) xref on both children?

A similar-ish example is GO:0004743 pyruvate kinase activity - here the GO definition asserts the (physiological) reaction direction, and the RHEA:18159 xref is also specifically for that direction. But the EC:2.7.1.40 xref is non-directional.  This is a simpler example, since the reverse direction is not thought to occur in vivo, so we only have one GO term involved here.

**Comment by deustp01** [comment]
A fuzzy general strategy question is whether the physiological reaction direction needs to be part of the GO definition of a molecular function, or whether its sufficient to allow that direction can be specified at the time a reaction is annotated in a process / pathway context? @ukemi

**Comment by ukemi** [comment]
Historically, if the reaction was thought to never proceed in both directions, we made the MF directional.
