### ISSUE TITLE
Obsoletion notice: some gated channel activities

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26210]
- [ ] GO:0022859 'dephosphorylation-gated channel activity'
- [ ]  GO:0022828  phosphorylation-gated channel activity
>> no reference, no annotation, not an activity, describes part of a signaling pathway

- [ ] [G-protein gated monoatomic ion channel activity](http://purl.obolibrary.org/obo/GO_0099099)
- [ ] [G-protein gated monoatomic cation channel activity](http://purl.obolibrary.org/obo/GO_0099100)
This is a ion channel that is activated by G-protein coupled signal transduction, it's not directly responsive to a G-protein
see https://www.sciencedirect.com/science/article/pii/S0085253815591722

**Comment by raymond91125** [comment]
GO:0022859 and GO:0022828 referenced Molecular biology of the cell. I could not find these terms in the 6th edition. These terms don't appear to be popular in literature. Google search positive hits are mostly about lecture notes.
GO:0099099 and GO:0099100 are supported in literature, e.g. PMID:3151174, see https://en.wikipedia.org/wiki/G_protein-gated_ion_channel.

**Comment by pgaudet** [comment]
A more recent reference: PMID:35704701
