### ISSUE TITLE
Missing parent: tRNA threonylcarbamoyladenosine metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26218]
* **GO term ID and label for which you request a new superclass**
tRNA threonylcarbamoyladenosine metabolic process

* **New superclass (parent) suggested**

tRNA  metabolic process

**Comment by ValWood** [comment]
This is weird, it has a logical def<  would have expected this to place under "tRNA metabolic process"

<img width="674" alt="Screenshot 2023-10-04 at 13 41 56" src="https://github.com/geneontology/go-ontology/assets/7359272/0b76317a-3694-4e53-a0ea-e0aa23937fc9">

anyway I added it manually, not sure if that is the correct thing to do. The logical def is still there.

**Comment by ValWood** [comment]
@pgaudet

**Comment by pgaudet** [comment]
The problem is that the parent class [tRNA metabolic process](http://purl.obolibrary.org/obo/GO_0006399) uses a SO term rather than a CHEBI term in the logical definition, so the reasoner cannot infer that there is a link. 

So for now it's OK to assert this.
