### ISSUE TITLE
NTR: membrane grommet activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26228]
Please provide as much information as you can: 

* **Suggested term label:**

membrane grommet activity

* **Definition (free text)**

An activity in which a protein, or group of proteins is inserted into a fenestration in a membrane, acting as a'lining' to preserve the integrity of the membrane (i.e. restrict the diameter of the hole). An example of this molecular function is performed by ESCRT III at the nuclear envelope of fission yeast during anaphase B.

* **Reference, in format PMID:#######**

PMID:37783794

Title | An **ESCRT grommet** cooperates with a diffusion barrier to maintain nuclear integrity.
Authors | Ader NR, Chen L, Surovtsev IV, Chadwick WL, Rodriguez EC, King MC, Lusk CP

* **Gene product name and ID to be annotated to this term**

All ESCRT III subunits with contributes_to (extensions  BP, @nuclear envelope during "anaphase B")

* **Parent term(s)**

molecular _function? Or structural molecule activity?

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by nuclear** [comment]
Absolutely, thanks for the tag 👌

**Comment by ValWood** [comment]
Author suggestion:
An activity in which a protein, or group of proteins, acts to restrict the size of a fenestration in a membrane or membrane system (i.e. restrict the diameter of a hole in a membrane). An example of this is molecular function is performed by ESCRT-III proteins at the nuclear envelope of fission yeast during anaphase B. 

(While we could imagine the ESCRTs being “in” the fenestration, it’s certainly possible that they function on the outer or inner nuclear membrane and restrict the membrane by acting there. If possible, I think the language should be intentionally ambiguous as to the structural nature of the grommet, and focus solely on the role)
