### ISSUE TITLE
GO:1990116   ribosome-associated ubiquitin-dependent protein catabolic process (add synonym or change label)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26232]
This process is universally (it seems) referred to as
"Ribosome-associated Quality Control " (RQC)
I struggled to find "ribosome-associated ubiquitin-dependent protein catabolic process"  which seems to refer to this process

can we add "Ribosome-associated Quality Control" as exact synonym (or ideally primary term name?)

GO:0006515   protein quality control for misfolded or incompletely synthesized proteins
should be a parent

**Comment by pgaudet** [comment]
Sounds good. The paper cited seems consistent with this -
https://pubmed.ncbi.nlm.nih.gov/23358411/

**Comment by ValWood** [comment]
out of date, see
https://github.com/geneontology/go-ontology/issues/26238
(I think we probably need to add
ribosome-associated quality control as a grouping term)
