### ISSUE TITLE
NTR: RQC-trigger complex (RQT complex)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26239]
Please provide as much information as you can: 

* **Suggested term label:**

RQT complex

* **Definition (free text)**

A ribosome  disassembly  complex which dissociates stalled ribsome subunits as part of the ribosome quality control pathway.
RQT complex is composed of a RNA helicase-family protein  Yeast Rqt2 (human ASCC3), a ubiquitin-binding protein  yeast Rqt3, (human ASCC2),  and Rqt4 (Human TRIP4)

* **Reference, in format PMID:#######**

PMID:28757607
PMID:32099016

* **Gene product name and ID to be annotated to this term**

RNA helicase-family protein  Yeast Rqt2,  human ASCC3
ubiquitin-binding protein  yeast Rqt3, human ASCC2
Rqt4 . Human TRIP4

* **Parent term(s)**

protein containing complex 

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
RQC-trigger complex

**Comment by ValWood** [comment]
@pgaudet I don't see this term yet? I usually see them within a few days. Is there a problem?
the snapshot is dated 20/10 https://snapshot.geneontology.org/metadata/date.txt
but I don't see the term In canto or QuickGO?

**Comment by pgaudet** [comment]
For reference 

[Term]
id: GO:0180022
name: RQC-trigger complex
namespace: cellular_component
def: "A ribosome disassembly complex which dissociates stalled ribsome subunits as part of the ribosome quality control pathway. RQT complex is composed of a RNA helicase-family proteiny yeast Rqt2 (human ASCC3), a ubiquitin-binding protein yeast Rqt3, (human ASCC2), and Rqt4 (Human TRIP4)." [PMID:28757607, PMID:32099016]
synonym: "RQT complex" EXACT []
is_a: GO:0032991 ! protein-containing complex
property_value: creation_dat "2023-10-11T11:40:08Z" xsd:dateTime
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26239" xsd:anyURI
created_by: vw

**Comment by pgaudet** [comment]
Are you sure you merged this correctly? I dont see it in the go-edit version of the ontology.

**Comment by pgaudet** [comment]
The pull request is still open: 
https://github.com/geneontology/go-ontology/pull/26250
