### ISSUE TITLE
Stop generating ProDom mapping file; resource deprecated

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26236]
Hello, 

There is a ProDom2GO file being generated at each release, see 
http://release.geneontology.org/2023-07-27/ontology/external2go/prodom2go

However that resource is no longer maintained, and the file is empty (since these mappings were provided by InterPro, and they stopped making them). 

Can we stop generating this file? 

Thanks, Pascale

**Comment by kltm** [comment]
@balhoff IIRC, these files are generated during the ontology build, correct?

**Comment by balhoff** [comment]
I think we just download this one: https://github.com/geneontology/go-ontology/blob/3070f8a045f421703812a365119b087bf1bc1c23/src/ontology/Makefile#L573

**Comment by kltm** [comment]
@pgaudet I guess that can just be commented out then?

**Comment by kltm** [comment]
@balhoff If you could PR that, @pgaudet can accept.

**Comment by pgaudet** [comment]
Yes! thanks :)
