### ISSUE TITLE
'protein insertion into membrane' should be is_a localization, not an organelle transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26244]
Hi @edwong57 

To resolve #26201

We need to review some related top level terms

'GO:0051204 protein insertion into mitochondrial membrane' is incorrectly placed under 'mitochondrial transport' because of its logical definition, the genera should not be is_a transport (probably is_a localization would work) 

Please also check the related terms: 
* GO:0051205 protein insertion into membrane
* * [GO:0045048 protein insertion into ER membrane](https://amigo.geneontology.org/amigo/term/GO:0045048#display-lineage-tab)
* * [GO:0032978 protein insertion into membrane from inner side](https://amigo.geneontology.org/amigo/term/GO:0032978#display-lineage-tab)
* * [GO:0071210 protein insertion into membrane raft](https://amigo.geneontology.org/amigo/term/GO:0071210#display-lineage-tab)
* * [GO:0051204 protein insertion into mitochondrial membrane](https://amigo.geneontology.org/amigo/term/GO:0051204#display-lineage-tab)
* * [GO:0098737 protein insertion into plasma membrane](https://amigo.geneontology.org/amigo/term/GO:0098737#display-lineage-tab)

Thanks, Pascale

**Comment by edwong57** [comment]
I removed is_a 'transport' from the logical definitions of 'protein insertion into mitochondrial membrane' and "protein insertion into mitochondrial inner membrane from matrix" and changed it to 'protein insertion into membrane', as it was for some of the other related terms. None of the others and their children in this list had 'transport' in their logical definitions.
