### ISSUE TITLE
Missing parent: GO:0160103   tRNA (guanine(26)-N2/guanine(27)-N2)-dimethyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26257]
* **GO term ID and label for which you request a new superclass**

GO:0160103   tRNA (guanine(26)-N2/guanine(27)-N2)-dimethyltransferase activity

* **New superclass (parent) suggested**

shouldn't this be is_a
GO:0004809 | tRNA (guanine-N2-)-methyltransferase activity

* **Reference(s), if appropriate**

See PAINT, not filtered
https://www.pombase.org/gene/SPBC25D12.05

**Comment by pgaudet** [comment]
This term will be obsoleted GO:0004809 | tRNA (guanine-N2-)-methyltransferase activity

**Comment by ValWood** [comment]
Oh yes!
