### ISSUE TITLE
Taxon constraint: GO:0009926   auxin polar transport

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26267]
Please provide as much information as you can: 

* **GO term ID label:**
GO:0009926   auxin polar transport
 and regulation

* **Request to add a taxon constraint:**
* * **only in taxon: **

plant

* **Supporting evidence if available (e.g PMID):**

**Comment by ValWood** [comment]
probably GO:0060918 auxin transport from def?

**Comment by pgaudet** [comment]
This term is_a [GO:0060918 auxin transport](https://amigo.geneontology.org/amigo/term/GO:0060918#display-lineage-tab)

GO:0060918 auxin transport could have a TC only in Viridiplantae

**Comment by ValWood** [comment]
GO:0060918  auxin transport  NCBITaxon:33090	Viridiplantae
GO:2000012  regulation of auxin polar transport  NCBITaxon:33090  Viridiplantae
GO:0080161  auxin transmembrane transporter activity  NCBITaxon:33090  Viridiplantae
(GO:2000012 is the ony regulation term)

**Comment by ValWood** [comment]
done
