### ISSUE TITLE
Taxon constraint: GO:0030334  regulation of cell migration

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26271]
Please provide as much information as you can: 

* **GO term ID label:**
GO:0030334  regulation of cell migration

* * **never in taxon: ascomycota

* **Request to remove a taxon constraint:**
Please specify

* **Supporting evidence if available (e.g PMID):**

**Comment by cmungall** [comment]
We have a never-in for this taxon on "cell migration". I guess we don't propagate tcs over regulates because of inter-species regulation, but it would be good to have a general solution for this so we don't have to manually recapitulate tcs in the regulation branch. cc @balhoff

**Comment by pgaudet** [comment]
The solution is to change the relation - see my PR in RO: https://github.com/oborel/obo-relations/issues/760

When we can use 'regulates in another organism' then the normal regulates will be fine for propagating TCs.

**Comment by pfey03** [comment]
I don't know if we have the regulation term but Dicty has cell migration

**Comment by raymond91125** [comment]
@pgaudet Could this be closed now?

**Comment by ValWood** [comment]
Yes, I see the taxon constraint.
