### ISSUE TITLE
NTR: Lysosomal bis(monoacylglycero)phosphate synthase

### ISSUE THREAD

**Issue by SHS111** [geneontology/go-ontology#26277]
Please provide as much information as you can: 
* **Suggested term label:**
Lysosomal bis(monoacylglycero)phosphate synthase

* **Definition (free text)**
Catalyzes the synthesis of bis(monoacylglycero)phosphate (BMP) via transacylation of 2 molecules of lysophosphatidylglycerol (LPG).

* **Reference, in format PMID:37708259

Gene name: CLN5
ID:  CLN5_human (UniProt:[O75503](https://www.uniprot.org/uniprotkb/O75503/entry))

Rhea:77619
EC=2.3.1.-

**Comment by pgaudet** [comment]
The RHEA reaction is 

"a 3-acyl-sn-glycero-1-phospho-(1'-sn-glycerol) = a 3-acyl-sn-glycero-1-phospho-(3ʼ-acyl-1ʼ-sn-glycerol) + sn-glycero-1-phospho-(1'-sn-glycerol)"

I would not include "Lysosomal" in the term label, this should belong in the cellular component annotation. 

OK? 

Thanks, Pascale

**Comment by raymond91125** [comment]
@pgaudet  I am not able to find the RHEA:77619 page. Is it pre-release? What should be the parent term? Thanks.

**Comment by SHS111** [comment]
Hi Pascale,
I agree, thanks.
Wishing u a nice day
Cheers
Shyamala

**Comment by pgaudet** [comment]
Hi @SHS111 
What should be the parent of this reaction? 

<img width="932" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/0e0a24ee-e072-4f19-b206-d65b5318598b">

**Comment by SHS111** [comment]
Hi Pascale,
http://internal.rhea-db.org/rhea/77619
is the parent Rhea reaction.
Cheers
Shyamala

**Comment by pgaudet** [comment]
Clarified with  @SHS111 by email

the parent should be [acyltransferase activity, transferring groups other than amino-acyl groups](http://purl.obolibrary.org/obo/GO_0016747)

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160121
+name: bis(monoacylglycero)phosphate synthase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: 2 3-acyl-sn-glycero-1-phospho-(1'-sn-glycerol) = 3-acyl-sn-glycero-1-phospho-(3'-acyl-1'-sn-glycerol) + sn-glycero-1-phospho-(1'-sn-glycerol)." [PMID:37708259, RHEA:77619]
+xref: RHEA:77619
+is_a: GO:0016747 ! acyltransferase activity, transferring groups other than amino-acyl groups
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26277" xsd:anyURI
+created_by: rynl
+creation_date: 2023-10-30T17:31:01Z
