### ISSUE TITLE
taxon violation "mating projection assembly"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26279]
GO:1902917   positive regulation of mating projection assembly
GO:1904600  mating projection actin fusion focus assembly

due to "cell projection organization"
being misplaced under "cell population proliferation"

GO:0008284 | positive regulation of cell population proliferation 

@edwong57 please let SGD know to ignore these log errors

I must have done this by mistake last week, because I edited this branch

**Comment by ValWood** [comment]
@pgaudet  I was going to do this one quickly because it will cause errors.

However I get this error
error: Your local changes to the following files would be overwritten by merge:
	src/ontology/imports/go-pattern-conformance.ttl
Please commit your changes or stash them before you merge.
Aborting

and I can't remember how to deal with that?

**Comment by pgaudet** [comment]
type 'git stash' 
you can safely ignore changes to src/ontology/imports/go-pattern-conformance.ttl

**Comment by pfey03** [comment]
Dicty has mating types when they have sexual activities

**Comment by pgaudet** [comment]
@pfey03 does it also have mating **projections**?

**Comment by ValWood** [comment]
I don't think that this would change the fact that this term shouldn't be under cell population proliferation?


The multiplication or reproduction of cells, results in the expansion of a cell population.
Comment: This term was moved out from being a child of 'cellular process' because it is a cell population-level process, and cellular processes are restricted to those processes that involve individual cells. Also note that this term is intended to be used for the proliferation of cells within a multicellular organism, not for the expansion of a population of single-celled organisms.

it didn't used to be there. I was assuming I did it in error.

mating projection assembly is a  single cell process

"cell population proliferation" should be is-a
GO:0032501   multicellular organismal process

**Comment by pgaudet** [comment]
OK, so this is a parentage problem, not a taxon problem, correct?

**Comment by pfey03** [comment]
@pgaudet 
mating projection we have never used, but from the definition it s probably more for fungi. I have to look into these papers and report more

**Comment by ValWood** [comment]
Wrong ticket ID in close message

**Comment by ValWood** [comment]
I think this was fixed but if so the violation is back. I think it comes from UBERON, so I don't know how to fix it?
