### ISSUE TITLE
Taxon constraint: toll-like receptor signaling pathway

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#26270]
* **GO term ID label: GO:0002224 toll-like receptor signaling pathway**

* **Request to add a taxon constraint:**
* * **never in taxon: Drosophila Taxid:7215**

* **Supporting evidence if available (e.g PMID):PMID:30034391 Toll-Like Receptors, Associated Biological Roles, and Signaling Networks in Non-Mammals.**

**Comment by raymond91125** [comment]
the order of Drosophila NCBI... seems reversed. I fixed it in https://github.com/geneontology/go-ontology/pull/26311
GO:0002224 toll-like receptor signaling pathway Drosophila NCBITaxon:7215 PMID:30034391
