### ISSUE TITLE
Missing parent: import across plasma membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26273]
Should it be a child of "import into cell?"
<img width="461" alt="Screenshot 2023-10-12 at 16 14 26" src="https://github.com/geneontology/go-ontology/assets/7359272/d0fabbca-d238-4359-9c78-64686d3ff65e">

**Comment by pgaudet** [comment]
Yeah the issue is about organisms with cell walls. Can you not import into the periplasmic space? 


I dont know how to get around this one... Maybe 'transmembrane import into cell???

**Comment by ValWood** [comment]
I would think that even if you have a cell wall the "import" is across the PM. 
i.e  until you cross the plasma  (cytoplasmic) membrane you are outside the cell

maybe?

**Comment by ValWood** [comment]
OK to add.

in bacteria with an outer and inner membrane, the inner membrane is the plasma membrane  (and  the periplasmic space is outside the cell)
