### ISSUE TITLE
NTR: isopentenyl pyrophosphate transporter activity/ import into mitochondrion

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26285]
Please provide as much information as you can: 

* **Suggested term label:**

MF isopentenyl pyrophosphate transporter activity
BP isopentenyl pyrophosphate  import into mitochondrion

* **Definition (free text)**

Standard definitions

* **Reference, in format PMID:#######**

PMID: 37813972

* **Gene product name and ID to be annotated to this term**

hem25

* **Parent term(s)**

?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

BP term IPP import into mitochondria
BP term isopentenyl pyrophosphate  import into mitochondria

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

@edwong57  will assign to you since you are looking at the branch, and it's an S. cerevisiae paper (I'd like to ISO to)

**Comment by edwong57** [comment]
I took a look at the paper. Just to clarify, are you asking for two terms? 
1. isopentenyl pyrophosphate transporter activity, MF term? Would 'isopentenyl pyrophosphate transmembrate transporter activity' be more appropriate? with parent 'transmembrane transporter activity' (GO:0022857)?
2. isopentenyl pyrophosphate import into mitochondrion, a BP term; with parent mitochondrial transmembrane transport (GO:1990542)

**Comment by ValWood** [comment]
Hi @edwong57  yes thats correct, I should have clearly specified that it was 2 terms.
I didn't specify the defs because these will presumably be modelled on the eventual parents

I agree 
isopentenyl pyrophosphate transmembrane transporter activity
is more appropriate

tks!
