### ISSUE TITLE
NTR: 	 phosphatidylinositol 4-phosphate biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26283]
Please provide as much information as you can: 

* **Suggested term label:**

phosphatidylinositol 4-phosphate biosynthetic process

* **Definition (free text)**

The chemical reactions and pathways resulting in the formation of phosphatidylinositol-4-phosphate, a phosphatidylinositol monophosphate carrying the phosphate group at the 4-position.

* **Reference, in format PMID:#######**

PMID:37815455

* **Gene product name and ID to be annotated to this term**

pik1/ncs1

* **Parent term(s)**

phosphatidylinositol phosphate biosynthetic process

* **Any other information**

Phosphatidylinositol (PI)-4-phosphate (PI4P) is a lipid found at the plasma membrane (PM) and Golgi in cells from yeast to humans. PI4P is generated from PI by PI4-kinases and can be converted to PI-4,5-bisphosphate [PI(4,5)P2].

(the Golgi pool appears to be separate and does not get converted to  [PI(4,5)P2] (if I understood correctly), it seems to be an end-poin in addition to being an intermediate

"We conclude that pik1-11 cells lack a Golgi PI4P pool, and have reduced PM PI4P that does not result in a corresponding decrease in PM PI(4,5)P2."

**Comment by ValWood** [comment]
@pgaudet  does that sound OK?


also
GO:0004430	1-phosphatidylinositol 4-kinase activity
Add exact
PI4-kinase
PI4 kinase

**Comment by pgaudet** [comment]
activity is OK 

I think the processes will be removed as single steps? I still need to look into it. If you have expertise in that area please let me know!

**Comment by ValWood** [comment]
I thought the same  at first, but it seems that  (see above) "the Golgi pool appears to be separate and does not get converted to [PI(4,5)P2] (if I understood correctly), it seems to be an end-point in addition to being an intermediate",

i.e  phosphatidylinositol 4-phosphate biosynthetic process is a valid term because the end point PI4P  has a role in its own right  (not all destined to become  PI(4,5)P2) and this appears to depend on cellular location.

I'm not an expert in this, but I should be because we have a lot of papers on it and it seems to be very active area.

However, It is s possible I am a bit confused about  what the plan is with metabolic pathways. I guess I assumed that every "end-point" would have a process. Maybe that is a misunderstanding.

**Comment by ValWood** [comment]
I guess we could just use
GO:0046854   phosphatidylinositol phosphate biosynthetic process
with the function terms. I don't know if we would lose any discrimination by doing this. Perhaps not.
Happy to leave this for now if the other children of GO:0046854   phosphatidylinositol phosphate biosynthetic process
are going obsolete.

**Comment by deustp01** [comment]
The larger issue here is that there are many phosphatidylinositol phosphates, defined by their exact phosphorylation patterns, they are synthesized from one another by various kinases. Some are endpoints - used for, e.g., membrane assembly and never phosphorylated further, while others may only be intermediates for further phosphorylation reactions to generate other phosphatidylinositol phosphates, while still others may be both endpoints and intermediates. A comprehensive metabolic chart provided by an expert (definitely not me - any ideas @sjm41 @kaxelsen ?) that showed all the interconversion steps and tagged each phosphatidylinositol phosphate with its role (endpoint, intermediate, both) would at least be a starting point for a systematic, consistent way of moving beyond simply using GO:0046854 phosphatidylinositol phosphate biosynthetic process for the whole network of interconversions with appropriate MF terms for the activity of each participating kinase. If there is a good reason to do that - the simple solution doesn't look bad.

**Comment by kaxelsen** [comment]
> A comprehensive metabolic chart provided by an expert (definitely not me - any ideas @sjm41 @kaxelsen ?)

I would love to see such a chart, but I don't know who could provide it.

**Comment by ValWood** [comment]
@pgaudet  can I add this, since it seems to be an end point?

**Comment by pgaudet** [comment]
Yes sure

**Comment by ValWood** [comment]
duplicate of https://github.com/geneontology/go-ontology/issues/28898
