### ISSUE TITLE
Incorrect Synonyms for GO:0042735 & GO:0004540

### ISSUE THREAD

**Issue by SaverimuttuS** [geneontology/go-ontology#26292]
Hi, 

Just bringing to your attention two GO terms with incorrect synonyms.

1)
GO ID - GO:0042735
GO Term Name - endosperm protein body
Incorrect synonym - `https://github.com/geneontology/go-ontology/issues/24425`

2) 
GO ID - GO:0004540 
GO Term Name - RNA nuclease activity
Incorrect synonym - `https://github.com/geneontology/go-ontology/issues/24408`

**Comment by balhoff** [comment]
Thank you @SaverimuttuS; the property used should be changed to [term tracker item](http://purl.obolibrary.org/obo/IAO_0000233).
