### ISSUE TITLE
Missing parent: should protein folding chaperone and RNA folding chaperone have a common parent?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26296]
* **GO term ID and label for which you request a new superclass**

See
<img width="625" alt="Screenshot 2023-10-20 at 13 41 11" src="https://github.com/geneontology/go-ontology/assets/7359272/a0ab1dee-3514-49c0-a724-04b82fb16e81">

both are directly under molecular function

* **New superclass (parent) suggested**

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by ValWood** [comment]
that would work.

**Comment by raymond91125** [comment]
I have trouble defining macromolecular folding chaperone. Perhaps what you want is a term like 'protein/RNA folding chaperone'?
I am not sure what should be the limit of macromolecules. CHEBI:33839 A macromolecule is a molecule of high relative molecular mass, the structure of which essentially comprises the multiple repetition of units derived, actually or conceptually, from molecules of low relative molecular mass.
I don't think the types of proteins (or RNAs PMID: 27791471) are similar between RNA folding chaperones and protein folding chaperones thus this grouping class may not be very useful.

**Comment by ValWood** [comment]
Hi @raymond91125 

The term  GO:0140691  RNA folding chaperone
Binding to an RNA or an RNA-containing complex to assist the folding process. PMID:31165735

is describing proteins which act as chaperones for correct  RNA folding, not for RNA's acting as chaperones for protein folding (as in PMID: 27791471) .

I'm not sure that my thinking is correct here, but I think what we are trying to group is "activity" not mechanism,
and the 'activity' of an "RNA folding chaperone" and a "protein folding chaperone" are broadly aligned as they are both 
binding the protein  (or RNA) to stabilize various folding intermediates ensure correct folding by preventing non specific binding or aggregation.  

That said, I also cannot easily think of a suitable grouping term, which might be why they were never grouped. They may be different enough to keep separate, and they are relatively easy to locate as they are both direct children of molecular function.

I'm happy for this to close, as it isn't critical.

**Comment by raymond91125** [comment]
Closed for now. Thanks.
