### ISSUE TITLE
make clathrin adaptor an activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26298]
In PomBase, clathrin adaptor appears under "binds"

<img width="728" alt="Screenshot 2023-10-20 at 17 12 05" src="https://github.com/geneontology/go-ontology/assets/7359272/0a599079-ea1b-4a81-9133-ecc88cd929b8">

but the parent " cargo adaptor" appears as an activity

<img width="914" alt="Screenshot 2023-10-20 at 17 11 29" src="https://github.com/geneontology/go-ontology/assets/7359272/f675d3a6-09a3-4a4d-b8e9-5924d8063c83">

should the binds relationship be has_part?

**Comment by pgaudet** [comment]
sure.

**Comment by raymond91125** [comment]
To confirm, do you mean to change 'clathrin adaptor activity is_a clathrin binding to 'clathrin adaptor activity has_part clathrin binding'? There is no binds relationship.

**Comment by pgaudet** [comment]
Hi @raymond91125 
clathrin adaptor activity is_a clathrin binding: 

<img width="463" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/f5ccb020-b15a-478b-8461-4775e32d8064">


The request was to change that to 'has part' clathrin binding.

**Comment by ValWood** [comment]
Apologies. For MF we separate the activities into  binds and non-binds (the aim for us is to depacate the use of "protein binding" for GO and replace with MFs which represent activities, so I spot those which are only in the "binding" branch.

**Comment by raymond91125** [comment]
Thanks.
