### ISSUE TITLE
Taxon constraint: GO:0017015 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26297]
Please provide as much information as you can: 

* **GO term ID label:**
GO:0017015   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0017015/complete)
regulation of transforming growth factor beta receptor signaling pathway

* **Request to add a taxon constraint:**

never in fungi

* * **only in taxon: **
* * **never in taxon: **

* **Request to remove a taxon constraint:**
Please specify

* **Supporting evidence if available (e.g PMID):**

**Comment by raymond91125** [comment]
Also added never in Fungi to positive and negative regulation terms.
