### ISSUE TITLE
NTR: tRNA methyltransferase + activator activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#26306]
Hello, this paper came up in my log files so I took a look at the paper, so I'm requesting these terms to the best of my knowledge. I see there is some ongoing refactoring in these activities.

* **Suggested term label:**
1.  tRNA (guanine(6)-N2)-methyltransferase activity 
 2. tRNA (guanine(7)-N2)-methyltransferase activity 
 3. tRNA (guanine(6)-N2)-methyltransferase activator activity 
4. tRNA (guanine(7)-N2)-methyltransferase activator activity 
5. 
* **Definition (free text)**
standard

* **Reference, in format PMID:#######**
 PMID:34669960 
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8599901

THUMPD3 is responsible for tRNA: m2G6 formation in human cells. However, THUMPD3 alone could not modify tRNAs. Instead, multifunctional methyltransferase subunit TRM112-like protein (TRMT112) interacts with THUMPD3 to activate its methyltransferase activity. 

THUMPD3–TRMT112 could methylate all the 26 tested G6-containing human cytoplasmic tRNAs by recognizing the characteristic 3′-CCA of mature tRNAs. We also showed that m2G7 of tRNATrp was introduced by THUMPD3–TRMT112.

* **Gene product name and ID to be annotated to this term**
1 and 2 for THUMPD3
3 and 4 for TRMT112

* **Parent term(s)**

standard

**Comment by Antonialock** [comment]
ah thanks, I did not see guanine(6)-N(2))-methyltransferase activity 
I did not request the rhea
@kaxelsen 

activators: that makes sense, thanks!

**Comment by raymond91125** [comment]
[Term]
id: GO:0160117
name: tRNA (guanine(6)-N2)-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: guanosine(6) in tRNA + S-adenosyl-L-methionine = H(+) + N(2)-methylguanosine(6) in tRNA + S-adenosyl-L-homocysteine." [EC:2.1.1.256, PMID:34669960]
synonym: "m(2)G6 methyltransferase" EXACT []
synonym: "methyltransferase Trm14" EXACT []
xref: EC:2.1.1.256
xref: RHEA:51116
is_a: GO:0008170 ! N-methyltransferase activity
is_a: GO:0016423 ! tRNA (guanine) methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26306" xsd:anyURI
created_by: rynl
creation_date: 2023-10-26T23:14:33Z

[Term]
id: GO:0160118
name: tRNA (guanine(7)-N2)-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: guanosine(7) in tRNA + S-adenosyl-L-methionine = H(+) + N(2)-methylguanosine(7) in tRNA + S-adenosyl-L-homocysteine." [PMID:34669960]
is_a: GO:0008170 ! N-methyltransferase activity
is_a: GO:0016423 ! tRNA (guanine) methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26306" xsd:anyURI
created_by: rynl
creation_date: 2023-10-26T23:24:47Z
