### ISSUE TITLE
Missing parent:  inositol phosphate kinase (add new superclass)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26309]
* **GO term ID and label for which you request a new superclass**

It would be useful to have a grouping term for all of the inositol phosphate kinases
<img width="336" alt="Screenshot 2023-10-25 at 15 18 16" src="https://github.com/geneontology/go-ontology/assets/7359272/30d32181-6e7d-4fa0-a0b6-2b7d0a84a25e">

* **New superclass (parent) suggested**
Inositol phosphate kinase activity

* **Reference(s), if appropriate**
PMID:nnnnnnn

We do have such a term for "inositol phosphate phosphatases"  e.g. https://www.pombase.org/term/GO:0052745

**Comment by ValWood** [comment]
I found some more, but I'm not sure that I found them all. It would be much easier for curation if these were all under a common parent a bit more specific than "kinase activity"

<img width="474" alt="Screenshot 2023-10-25 at 15 24 31" src="https://github.com/geneontology/go-ontology/assets/7359272/fc7760e6-5ea8-474c-92f8-460d46e1586e">

**Comment by ValWood** [comment]
<img width="925" alt="Screenshot 2023-10-25 at 15 30 48" src="https://github.com/geneontology/go-ontology/assets/7359272/a88ca0d6-c9a4-49af-b3ee-c0443990ed68">

**Comment by ValWood** [comment]
@pgaudet  do you agree to add this grouping term? All of the "inositol kinases" are had to find because "kinase activity" is the only common grouping

**Comment by pgaudet** [comment]
yes sure

**Comment by ValWood** [comment]
The will be the is_a children
GO:0051766
GO:0019140
GO:0035299
GO:0051765
GO:0052836
GO:0052839
GO:0033857
GO:0000827
GO:0000828
GO:0000829
