### ISSUE TITLE
 logical inconsistency  in tRNA processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26303]
charged-tRNA amino acid modification (GO:0019988)
Definition
The covalent alteration of an amino acid charged on a tRNA before it is incorporated into a protein, as in N-formylmethionine, selenocysteine or pyrrolysine.

is a descendent of  tRNA processing GO:0008033 which is defined:
The process in which a pre-tRNA molecule is converted to a mature tRNA, ready for addition of an aminoacyl group. [PMID:12533506]

**Comment by pgaudet** [comment]
Why is this inconsistent? Do you mean that the amino acid is *not* a part of the tRNA?

**Comment by ValWood** [comment]
Ignore, I misread it.
