### ISSUE TITLE
NTR: [positive regulation of cGAS/STING signaling pathway]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#26301]
Hi GO,

I would need a regulation term for a GO-CAM model. We already have a term for negative regulation of cGAS/STING signaling pathway (GO:0160049) but not for the positive regulation. Would it be possible create a GO term?
Thanks
Sylvain

positive regulation of cGAS/STING signaling pathway
 Any process that activates or increases the frequency, rate or extent of of cGAS/STING signaling pathway.
Child of GO:0140896 cGAS/STING signaling pathway
PMID:37802025

**Comment by pgaudet** [comment]
+[Term]
+id: RO:0012002
+name: positive regulation of cGAS/STING signaling pathway
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of of cGAS/STING signaling pathway." [PMID:37802025]
+is_a: GO:0065007 ! biological regulation
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26301" xsd:anyURI
+created_by: pg
+creation_date: 2023-10-23T15:27:08Z
+
