### ISSUE TITLE
Function process links causing regulation term violation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26308]
This relationship:
<img width="545" alt="Screenshot 2023-10-25 at 14 17 48" src="https://github.com/geneontology/go-ontology/assets/7359272/a42816aa-e8f7-4372-a357-7cf6b42186b6">

causes "regulation of process" from the GOC MF-BP pipeline.

<img width="1025" alt="Screenshot 2023-10-25 at 14 22 02" src="https://github.com/geneontology/go-ontology/assets/7359272/b853c23d-871b-4f35-afab-4cf02e659cef">

<img width="1038" alt="Screenshot 2023-10-25 at 14 24 31" src="https://github.com/geneontology/go-ontology/assets/7359272/0816f6a6-16b5-4af7-8763-32952fa31c95">

**Comment by ValWood** [comment]
I think the solution is proba bly that elongation factor should not be is_a regulator?

**Comment by pgaudet** [comment]
It still had the superclass 'part_of GO:0006355 ! regulation of DNA-templated transcription' 

Despite what it said here: 
https://github.com/geneontology/go-ontology/issues/14398

Thanks for pointing that out. Hopefully this is now fixed. 

Pascale
