### ISSUE TITLE
NTR 'symbiont-mediated perturbation of host signal transduction pathway via antagonism of host cell surface receptor'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26310]
'symbiont-mediated perturbation of host signal transduction pathway via antagonism of host cell surface receptor'
child of 'perturbation of host signal transduction pathway'

@genegodbold to provide references

**Comment by genegodbold** [comment]
1. **Extracellular complement-binding protein** (**Ecb** also known as **Ehb** for Efb-homologous proteins, see below) from _Staphylococcus aureus_:  Ecb completely inhibits direct binding of C3d to complement receptor 2 (CR2). This can inhibit the activation and maturation of B cells. Ecb readily forms a saturated complex with C3d. Only a slight excess is necessary for this effect [PMID:19017934]. _Pascale, I realize this isn't antagonism, but it is messing with receptor binding_.
2. **Extracellular fibrinogen binding protein** (**Efb**, **Fib**) from _Staphylococcus aureus_: Efb completely inhibits direct binding of C3d to complement receptor 2 (CR2). This can inhibit the activation and maturation of B cells. Efb readily forms a saturated complex with C3d. Only a slight excess is necessary for this effect [PMID:19017934]. _Pascale, ditto_.  
3. **Staphylococcal superantigen-like protein 4** (**Ssl4**): Ssl4 binds to TLR2 (toll-like receptor 2) extracellularly and inhibits signaling from the receptor [PMID:22714643].
4. **Enteroaggregative heat-stable toxin 1** (**EAST1**; **AstA**) from _Escherichia coli_: EAST1 binds to the cell surface guanylate cyclase C receptor on the endothelia of the intestines and agonizes it to contribute to intestinal secretion of water and electrolytes [PMID:27735786]. _Okay Pascale, I realize this is agonism, NOT antagonism, but that was within the scope of the original PathGO term._

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141129
+name: symbiont-mediated perturbation of host signal transduction pathway via antagonism of host cell surface receptor
+namespace: biological_process
+def: "A process by which a symbiont alters or subverts a host cell surface receptor-mediated signal transduction pathway by binding to and inhibiting the receptor of the pathway. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:10221874, PMID:22714643]
+is_a: GO:0052027 ! symbiont-mediated perturbation of host signal transduction pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26310" xsd:anyURI
+created_by: pg
+creation_date: 2023-12-14T12:16:15Z

**Comment by pgaudet** [comment]
this could be improved..

**Comment by genegodbold** [comment]
Yes, it's a mouthful. However, I don't think you need to include the "perturbation of host signal transduction pathway". Whatever happens after the antagonism doesn't need to be spelled out. 

So I think this could be: "symbiont-mediated **antagonism** of host cell surface receptor" (binding and **blocking** host receptor)
And it should also have a corresponding: "symbiont-mediated **agonism** of host cell surface receptor" (binding and **activating** host receptor)

Having both of these means you're pharmacologically correct :-)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141134
+name: symbiont-mediated activation of host signal transduction pathway via agonism of host cell surface receptor
+namespace: biological_process
+def: "A process in which a symbiont subverts a signal transduction pathway in the host organism by binding to and enhancing the activation of the receptor of the pathway. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:10221874, PMID:18563600]
+synonym: "symbiont-mediated perturbation of host signal transduction pathway via antagonism of host cell surface receptor" BROAD []
+is_a: GO:0052028 ! symbiont-mediated activation of host signal transduction pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26310" xsd:anyURI
+created_by: pg
+creation_date: 2023-12-20T14:49:23Z
