### ISSUE TITLE
Is GO:0038031 non-canonical WNT signaling via JNK the same as GO:0060071 Wnt signaling pathway, planar cell polarity pathway ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26335]
@hattrill and @gantonazzo will review whether  non-canonical WNT signaling via JNK and [Wnt signaling pathway, planar cell polarity pathway](http://purl.obolibrary.org/obo/GO_0060071)
represent the same pathway. This review suggests that this is the case: 
https://link.springer.com/article/10.1007/s12015-023-10610-5

<img width="497" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/7f2ba770-a622-49fa-963c-6dc81c55db7e">

Papers cited in the term & annotated: 

- [ ] [PMID:19137009](http://www.ncbi.nlm.nih.gov/pubmed/19137009)
- [ ]  [PMID:20032469](http://www.ncbi.nlm.nih.gov/pubmed/20032469)
- [ ] [PMID:26754771](https://amigo.geneontology.org/amigo/reference/PMID:26754771)
- [ ] [PMID:19188438](http://www.ncbi.nlm.nih.gov/pubmed/19188438)

**Comment by hattrill** [comment]
couple of refs:
[Planar cell polarity in development and disease](https://www.nature.com/articles/nrm.2017.11)
[The cell biology of planar cell polarity](https://doi.org/10.1083/jcb.201408039)

**Comment by pgaudet** [comment]
After discussion with @hattrill and @gantonazzo 

- [ ] removed GO:0060071 Wnt signaling pathway, planar cell polarity pathway is_a 'regulation of establishment of planar polarity'

**Comment by pgaudet** [comment]
To answer the original question, GO:0038031 non-canonical WNT signaling via JNK  and GO:0060071 Wnt signaling pathway, planar cell polarity pathway  describe the same or very similar pathways. GO:0038031 was obsoleted in #26300

We now have 3 non-canonical Wnt pathways: 

- 'Frizzled Nuclear Import pathway'
- 'Wnt signaling pathway, calcium modulating pathway'
- 'Wnt signaling pathway, planar cell polarity pathway'


Pascale
-

**Comment by hattrill** [comment]
Hi @pgaudet a suggested change to the definition from a discussion from https://github.com/geneontology/go-annotation/issues/4800 to Wnt signaling pathway, planar cell polarity pathway

Definition: The series of molecular signals initiated by binding of a Wnt protein to a frizzled family receptor on the surface of the target cell resulting in the activation small G proteins such as Rho, Rac, and Cdc42 which, in turn activate effectors including C-Jun N-terminal kinase (JNK) and Rho kinase (Rok) and ending in a change in the transcription of target genes and/or reorganisation of the cytoskeleton.

PMID: 23140633.

**Comment by pgaudet** [comment]
Thanks. I have updated all definitions in that branch to also apply the 'genera-differentia' principle: 


GO:0016055 Wnt signaling pathway
OLD def: "The series of molecular signals initiated by binding of a Wnt protein to a frizzled family receptor on the surface of the target cell and ending with a change in cell state." [GOC:dph, GOC:go_curators, PMID:11532397]
NEW def: "The series of molecular signals initiated by binding of a Wnt protein to a frizzled family receptor on the surface of a target cell and ending with a change in cell state." [GOC:dph, GOC:go_curators, PMID:11532397]

GO:0060070  canonical Wnt signaling pathway
OLD def: "The series of molecular signals initiated by binding of a Wnt protein to a frizzled family receptor on the surface of the target cell, followed by propagation of the signal via beta-catenin, and ending with a change in transcription of target genes. In this pathway, the activated receptor signals via downstream effectors that result in the inhibition of beta-catenin phosphorylation, thereby preventing degradation of beta-catenin. Stabilized beta-catenin can then accumulate and travel to the nucleus to trigger changes in transcription of target genes." [GOC:bf, GOC:dph, PMID:11532397, PMID:19619488]
NEW def: "A type of Wnt signaling pathway in which Wnt binding to its receptor on the surface of a target cell results in the by propagation of the molecular signals via beta-catenin, and end with a change in transcription of target genes. In this pathway, the activated receptor signals via downstream effectors that result in the inhibition of beta-catenin phosphorylation, thereby preventing degradation of beta-catenin. Stabilized beta-catenin can then accumulate and travel to the nucleus to trigger changes in transcription of target genes." [GOC:bf, GOC:dph, PMID:11532397, PMID:19619488]


GO:0035567 non-canonical Wnt signaling pathway
OLD def: "The series of molecular signals initiated by binding of a Wnt protein to a frizzled family receptor on the surface of the target cell, followed by propagation of the signal via effectors other than beta-catenin." [PMID:37804416]
NEW def: "A type of Wnt signaling pathway in which Wnt binding to its receptor on the surface of a target cell results in the by propagation of the molecular signals via effectors other than beta-catenin." [PMID:37804416]


GO:0007223 Wnt signaling pathway, calcium modulating pathway
OLD def: "The series of molecular signals initiated by binding of a Wnt protein to a receptor on the surface of the target cell where activated receptors leads to an increase in intracellular calcium and activation of protein kinase C (PKC)." [PMID:11532397, PMID:37804416]
NEW def: "A type of non-canonical Wnt signaling in which Wnt binding to its receptor on the surface of a target cell leads to an increase in intracellular calcium and activation of protein kinase C (PKC)." [PMID:11532397, PMID:37804416]

GO:0060071 Wnt signaling pathway, planar cell polarity pathway
OLD def: "The series of molecular signals initiated by binding of a Wnt protein to a receptor on the surface of the target cell where activated receptors signal via downstream effectors including C-Jun N-terminal kinase (JNK). In some instances, may be involved in reorganize the cytoskeleton organization and/or in the establishment of planar cell polarity pattern orientation." [PMID:11532397, PMID:25349257, PMID:28293032, PMID:37804416]
NEW def: "A type of non-canonical Wnt signaling pathway in which Wnt binding to its receptor on the surface of a target cell results in the activation small G proteins such as Rho, Rac, and Cdc42 which, in turn activate effectors, including C-Jun N-terminal kinase (JNK) and Rho kinase (Rok). The signaling ends with change in the transcription of target genes and/or reorganisation of the cytoskeleton." [PMID:11532397, PMID:25349257, PMID:28293032, PMID:37804416]

Please reopen if you'd like to suggest more edits. 

Thanks, Pascale
