### ISSUE TITLE
Obsoletion request:  GO:0005845  mRNA CAP binding complex 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26347]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0005845 mRNA cap binding complex

* **Reason for deprecation** Put an x in the appropriate box: 

 - [ ]  The reason for obsoletion is that this term was an unnecessary grouping term.

<img width="618" alt="Screenshot 2023-10-31 at 13 37 11" src="https://github.com/geneontology/go-ontology/assets/7359272/781a3ba7-7e34-433c-b6b9-ee23f8330501">

We should keep the grouping term "RNA cap binding complex"  for the bacterial Cap binding complex (assuming there is one), but make it clear this is for **THE** cap binding complex

and obsolete 
GO:0005845 mRNA cap binding complex
Any protein complex that binds to an mRNA cap at any time in the lifetime of the mRNA.

(otherwise, we would need to group the missing   "complexes which bind to the cap" like RNA de capping complexes under here, and find a way to make it clear that this term was not the CBC)

and remove  any descendants that do not refer to **THE** CAP binding complex

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
- [x] https://github.com/geneontology/go-annotation/issues/4832

- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by pgaudet** [comment]
Are you planning to do the same with [mRNA cap binding](http://purl.obolibrary.org/obo/GO_0098808) ? (and [regulation of mRNA cap binding](http://purl.obolibrary.org/obo/GO_1905610))

**Comment by ValWood** [comment]
I wasn't going to touch the binding terms. I was only looking at  the complex terms which  wee confusing as it was difficult to know which complexes there referred to (because  the grouping term matched and actual complex name).
I hadn't thought beyond solving that problem,  which could end up with misleading annotations.

To be honest I largely ignore binding terms because we try not to use them at all if possibe.

**Comment by pgaudet** [comment]
OK, I wanted to see if we could keep the ontology consistent. No big deal for bindings, I agree.

**Comment by ValWood** [comment]
I thought the binding terms were OK though, they refer to the structure being bound (mRNA cap etc).

The complex is a bit different because of the clunky naming, (its like actually calling a  specific complex "DNA binding complex"), when there are many types. The binding terms aren't confusing.

**Comment by ValWood** [comment]
@blazaropinto 
@esperetta
