### ISSUE TITLE
TPV: Incorrect parentage "mRNA destabilization"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26342]
mRNA destabilization
is not always "regulation of translation" (especially nuclear polyadenylation-dependent RNA catabolic process)
<img width="566" alt="__________GO- TICKET parentScreenshot 2023-10-29 at 07 40 15" src="https://github.com/geneontology/go-ontology/assets/7359272/e78cac1d-f215-4a71-a8fa-6eb4f93b862b">

**Comment by ValWood** [comment]
A nice example of where regulation of translation isn't true.
See the "cautionary note". on te UniProt entry
https://www.uniprot.org/uniprotkb/Q9BYJ9/entry

@Antonialock  I like these cautionary notes! I  was doing a S. pombe Matrix review have seen a lot of these cautionary notes  on the proteins which tend to get mis-annotated with indirect processes in the intersections. They should be  really helpful to prevent people from putting removed legacy annotations back.

**Comment by ValWood** [comment]
This is more complicated than I thought.

The GO definition of "mRNA destabilization" is 

Any process that decreases the stability of an mRNA molecule, making it more vulnerable to degradative processes. Messenger RNA is the intermediate molecule between DNA and protein. It includes UTR and coding sequences. It does not contain introns.

This implies this term is only for "processed mRNAs". If this was the case, the parentage to regulation of translation is not so bad. However based on the fact that 
"nuclear-transcribed mRNA catabolic process, deadenylation-dependent decay" is a child of this term, I have to remove the "regulation of translation" parentage to prevent incorrect inferences.

I will do that now and close this . I will need to revisit mRNA destabilization and children as part of the RNA processing review.

**Comment by pgaudet** [comment]
Can we look at this together? I have came across this for the transcription refactoring

**Comment by ValWood** [comment]
I just removed the incorrect parent for now because it is creating incorrect inferences. There is a whole bunch to do in this branch. I will make a proposal but I still need to get some input  from experts on the relationship between surveillance and degradation. I agree we should do the RNA processing together though, because it's very complex.

**Comment by Antonialock** [comment]
> @Antonialock I like these cautionary notes! I was doing a S. pombe Matrix review have seen a lot of these cautionary notes on the proteins which tend to get mis-annotated with indirect processes in the intersections. They should be really helpful to prevent people from putting removed legacy annotations back.

Yes they are also used for pseudo-enzymes that have lost catalytic activity.
