### ISSUE TITLE
Taxon Constraint for GO:0061008 hepaticobiliary system development 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#26352]
* **GO:0061008 hepaticobiliary system development**

* * **only in taxon: Vertebrata Taxonomy ID: 7742** 

* **This paper has a couple of figures with livers/bile and vertebrate evolution:PMC7970152**

**Comment by pgaudet** [comment]
We now get this automatically via the new computer taxon constraints: 
http://snapshot.geneontology.org/ontology/imports/go-computed-taxon-constraints.obo

These should be in the upcoming release
