### ISSUE TITLE
NTR: [Structural constituent of nuclear lamina]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#26350]
Hi GO,

I think it would be worth creating a term for the function of lamin cytoskeleton, Note that there is a term for the nuclear lamina (GO:0005652).

Thanks

Sylvain

Name: Structural constituent of nuclear lamina
Category: Molecular Function
Definition: The action of a molecule that contributes to the structural integrity of nuclear lamina structure. 

child of GO:0005200; F:structural constituent of cytoskeleton
PMID:28241138
PMID:31434876

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160123
+name: structural constituent of nuclear lamina
+namespace: molecular_function
+def: "The action of a molecule that contributes to the structural integrity of nuclear lamina." [PMID:2824113, PMID:31434876]
+is_a: GO:0005198 ! structural molecule activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26350" xsd:anyURI
+created_by: rynl
+creation_date: 2023-11-13T19:59:15Z
