### ISSUE TITLE
Taxon constraint: periplasmic space GO:0042597

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#26353]
Please provide as much information as you can: 

* **GO:0042597 periplasmic space:**

* **Request to add a taxon constraint:**
* * **only in taxon:Bacteria, taxon ID:2 & Fungi, taxon ID:4751 **

**Comment by pgaudet** [comment]
Also added archae, see PMID:15803654 
> GO:0042597 periplasmic space NCBITaxon:Union_0000023 Fungi or Bacteria or Archaea PMID:15803654
