### ISSUE TITLE
Clean-up of GO:0016197 endosomal transport and GO:0098927 vesicle-mediated transport between endosomal compartments

### ISSUE THREAD

**Issue by EBIDaveC** [geneontology/go-ontology#26386]
Hi
I've been annotating some proteins involved in endosome maturation and found that the associated GO term relations may benefit from a clean-up.
![image](https://github.com/geneontology/go-ontology/assets/143006397/78029b14-5e02-498b-90a6-bed7e6eb23be)

1. GO:0016197 endosomal transport and GO:0098927 vesicle-mediated transport between endosomal compartments seem to be redundant and could possibly be merged or relation added GO:0098927 is_a GO:0016197 (This relation seems to have been deleted twice but I am unsure of why).

2. Currently GO:0016197 endosomal transport occurs_in GO:0005622 intracellular anatomical structure. This could be refined to occurs_in GO:0005737 cytoplasm.

3. GO:0016482 cytosolic transport is defined as "The directed movement of substances or **organelles** within the cytosol."
GO:0005829 cytosol is defined as "The part of the cytoplasm that does **not contain organelles** but which does contain other particulate matter, such as protein complexes."
GO:0016482 should be renamed cytoplasmic transport and defined as "The directed movement of substances or organelles within the cytoplasm." Its relation occurs_in GO:005829 cytosol should be changed to occurs_in GO:0005737 cytoplasm.

4. The two child terms of GO:0098927 (GO:0045022 early endosome to late endosome transport and GO:0061502 early endosome to recycling endosome transport) both have the relation occurs_in GO:0005829 cytosol. These should be removed as they both occur in cytoplasm. occurs_in GO:0005737 cytoplasm would be better but would be superfluous if one of their parent terms is already annotated occurs_in GO:0005737 cytoplasm.

5. GO:0045022 early endosome to late endosome transport can be given the synonym "endosome maturation" (PMID 21878991). The definition may need to be updated to reflect that the process is one of vesicle maturation (early endosomes become late endsomes acquiring different properties as they traffic deeper into the cell) as opposed to vesicles shuttling between two distinct compartments. This could be slightly more complicated as multivesicular body formation could also form part of endosome maturation.

This is the first time I am raising an issue like this so please feel free to correct me if any of my assumptions are incorrect.

**Comment by raymond91125** [comment]
> 3\. GO:0016482 cytosolic transport is defined as "The directed movement of substances or **organelles** within the cytosol."
>         GO:0005829 cytosol is defined as "The part of the cytoplasm that does **not contain organelles** but which does contain other particulate matter, such as protein complexes."
>         GO:0016482 should be renamed cytoplasmic transport and defined as "The directed movement of substances or organelles within the cytoplasm." Its relation occurs_in GO:005829 cytosol should be changed to occurs_in GO:0005737 cytoplasm.

There are further implications to change the definition of cytosolic transport.
Compare occurs_in cytosol 

![cytosol](https://github.com/geneontology/go-ontology/assets/619520/48802a6a-1fb9-47f8-bea2-b06367789042)
vs. occurs_in cytoplasm
![cytoplasm](https://github.com/geneontology/go-ontology/assets/619520/c85ef7ea-6d53-4141-9e12-ac81a819bd50)

In the latter case, it seems that every form of intracellular transport would be a child. I don't know if this is the intention of the term.

**Comment by Antonialock** [comment]
@ValWood

**Comment by ValWood** [comment]
I wonder if "cytosolic transport" is a bit of a problematic grouping term @pgaudet ?

"The directed movement of substances or organelles within the cytosol"

this is grouping apples and oranges (and bananas)

**Comment by EBIDaveC** [comment]
The problem arises due to ambiguous use of the terms Cytosol and Cytoplasm. These are used interchangeably in the literature and even in some textbooks. If sticking to the definitions of GO:005829 cytosol and GO:0005737 cytoplasm then almost all cytosolic transport that involves vesicular or organelle trafficking would more correctly be defined as occurs_in cytoplasm.

**Comment by pgaudet** [comment]
I agree, let's obsolete 'GO:0016482 cytosolic transport as well as the regulation terms: 
- GO:1903649 regulation of cytoplasmic transport (0 annotation) 
- [GO:1903650 negative regulation of cytoplasmic transport](https://amigo.geneontology.org/amigo/term/GO:1903650#display-lineage-tab) (0 annotation) 
- [GO:1903651 positive regulation of cytoplasmic transport](https://amigo.geneontology.org/amigo/term/GO:1903651#display-lineage-tab)) (0 annotation) 
We also need to obsolete or rename and move other children: 
- [GO:1903652 modulation by virus of host cytoplasmic transport](https://amigo.geneontology.org/amigo/term/GO:1903652#display-lineage-tab): obsolete? 1 EXP, CACAO
- [GO:0099636 cytoplasmic streaming](https://amigo.geneontology.org/amigo/term/GO:0099636#display-lineage-tab) >> move under parent intracellular transport
-  GO:0007303 cytoplasmic transport, nurse cell to oocyte: mostly fly annotations: @hattrill Is this an intracellular transport? 

@raymond91125 what do you think ? 

Thanks, Pascale

**Comment by hattrill** [comment]
GO:0007303 cytoplasmic transport, nurse cell to oocyte is via **intercellular** bridges, so is cytoplasmic.
 I will shift these up to "ovarian nurse cell to oocyte transport" as GO:0007303 is not intracellular. Feel free  to obsolete GO:0007303 cytoplasmic transport, nurse cell to oocyte

**Comment by raymond91125** [comment]
> 1. GO:0016197 endosomal transport and GO:0098927 vesicle-mediated transport between endosomal compartments seem to be redundant and could possibly be merged or relation added GO:0098927 is_a GO:0016197 (This relation seems to have been deleted twice but I am unsure of why).

vesicle-mediated transport between endosomal compartments is a subtype of endosomal transport because endosomal transport also includes transport from endosome to non-endosomes.

**Comment by raymond91125** [comment]
> 2\. Currently GO:0016197 endosomal transport occurs_in GO:0005622 intracellular anatomical structure. This could be refined to occurs_in GO:0005737 cytoplasm.

The difference between intracellular anatomical structure and cytoplasm is nucleus. It appears that there is endosome to nucleus transport, e.g. PMID:26356418 "Nuclear envelope-associated endosomes deliver surface proteins to the nucleus".

**Comment by raymond91125** [comment]
> 4\. The two child terms of GO:0098927 (GO:0045022 early endosome to late endosome transport and GO:0061502 early endosome to recycling endosome transport) both have the relation occurs_in GO:0005829 cytosol. These should be removed as they both occur in cytoplasm. occurs_in GO:0005737 cytoplasm would be better but would be superfluous if one of their parent terms is already annotated occurs_in GO:0005737 cytoplasm.

done.

**Comment by raymond91125** [comment]
> 5\. GO:0045022 early endosome to late endosome transport can be given the synonym "endosome maturation" (PMID 21878991). The definition may need to be updated to reflect that the process is one of vesicle maturation (early endosomes become late endsomes acquiring different properties as they traffic deeper into the cell) as opposed to vesicles shuttling between two distinct compartments. This could be slightly more complicated as multivesicular body formation could also form part of endosome maturation.

From the literature, there seems to be two processes going on between early and late endosomes: vesicle transport (PMID:8970738) and maturation (https://www.jove.com/science-education/11888/maturation-of-endosomes). It seems that they are distinct. Is that not true? @EBIDaveC

**Comment by raymond91125** [comment]
GO:0016482 cytosolic transport really is defined as 'cytoplasmic transport' and has been used as such. Cytoplsmic transport is different from intracellular transport because it excludes nucleus. I suggest that we simply rename cytosolic transport to cytoplasmic transport. Do you think that's OK? @pgaudet

**Comment by EBIDaveC** [comment]
> > 5. GO:0045022 early endosome to late endosome transport can be given the synonym "endosome maturation" (PMID 21878991). The definition may need to be updated to reflect that the process is one of vesicle maturation (early endosomes become late endsomes acquiring different properties as they traffic deeper into the cell) as opposed to vesicles shuttling between two distinct compartments. This could be slightly more complicated as multivesicular body formation could also form part of endosome maturation.
> 
> From the literature, there seems to be two processes going on between early and late endosomes: vesicle transport (PMID:8970738) and maturation (https://www.jove.com/science-education/11888/maturation-of-endosomes). It seems that they are distinct. Is that not true? @EBIDaveC

The idea that proteins are transported from early endosomes to late endosomes by vesicle transport is slightly outdated in my opinion. The current accepted model is that late endosome formation is one of vesicle maturation, which involves the movement of vesicles deeper into the cell  (PMID 21878991).

Endosomal maturation involves many other process too, including changes in phospholipid makeup of the lipid membrane, changes in the repertoire of proteins associated with the membrane, endosomal acidification and formation of intraluminal vesicles to form multivesicular bodies. Once fully mature late endosomes undergo homotypic fusion to form larger late endosomes that eventually fuse with lysosomes. 

I guess endosomal maturation could be defined as a type of vesicle trafficking carrying proteins through the endolysosomal pathway or something that happens during vesicle transport of proteins through the endolysosomal pathway.

**Comment by pgaudet** [comment]
> GO:0016482 cytosolic transport really is defined as 'cytoplasmic transport' and has been used as such. Cytoplsmic transport is different from intracellular transport because it excludes nucleus. I suggest that we simply rename cytosolic transport to cytoplasmic transport. Do you think that's OK? @pgaudet

How would you define 'cytoplasmic transport'? When I Google I only get 73 results, mainly to GO:0016482 - cytoplasmic streaming. Otherwise I get 'nucleocytoplasmic transport'. 

I am not sure what cytosolic transport or cytoplasmic transport represent in the literature... ?

**Comment by pgaudet** [comment]
Note that I think we should also obsolete 'GO:0051169 nuclear transport'; there are only 3 EXP, one should have been annotated to nucleocytoplasmic transport, and the other 2 capture downstream events.

**Comment by raymond91125** [comment]
> The idea that proteins are transported from early endosomes to late endosomes by vesicle transport is slightly outdated in my opinion. The current accepted model is that late endosome formation is one of vesicle maturation, which involves the movement of vesicles deeper into the cell (PMID 21878991).

@EBIDaveC Would you say that then "The directed movement of substances, in membrane-bounded vesicles, from the early sorting endosomes to the late sorting endosomes; transport occurs along microtubules and can be experimentally blocked with microtubule-depolymerizing drugs." does not occur? That is, vesicles do not bud off from an early endosome, get transported via cytoskeleton, and then fuse with an existing late endosome. Is there a reference? I understand that there is an endosome maturation process but I would like to make sure that there is NOT a vesicle-mediated transport process in parallel. Thanks!
![Screenshot from 2023-11-20 10-28-01](https://github.com/geneontology/go-ontology/assets/619520/02fba317-cff4-4e53-9e35-86645509bcac)
(Molecular Biology of The Cell, 1994. This is the reference cited by GO:GO:0045022 early endosome to late endosome transport)

**Comment by EBIDaveC** [comment]
@raymond91125 The description  "The directed movement of substances, in membrane-bounded vesicles, from the early **sorting** endosomes to the late **sorting** endosomes; transport occurs along microtubules and can be experimentally blocked with microtubule-depolymerizing drugs." is technically correct because it uses **sorting** endosomes as the origin and destination and this process definitely occurs. The vesicles doing the transporting are themselves usually considered endosomes. These can bud from larger sorting endosomes or can be the entire sorting endosome as I understand it. I am not aware of evidence favouring one over the other and they are not mutually exclusive. This is why I suggested "endosome maturation" should be a synonym for early to late endosome transport.
Alternatively;
Following the example of GO:0016188 synaptic vesicle maturation,
"endosome maturation" could be a new term that Is_a GO:0007032 endosome organization and Part_of GO:0045022 early endosome to late endosome transport.
Definition: The steps and processes whereby early endosomes become late endosomes and acquire their properties.

So just to summarise my current view. Early endosome to late endosome trafficking **IS** a vesicle-mediated transport process and endosome maturation is part of that process. Sorry if there was any confusion.

**Comment by raymond91125** [comment]
@EBIDaveC Thanks much for your clarification. After a bit more digging, I found a newer, 2018 review article PMID:29980602 that has a fitting title "The enigmatic endosome – sorting the ins and outs of endocytic trafficking". It concludes: "The challenge in defining LEs comes, at least in part, from the disparate models of endosome biogenesis: are LEs generated by evolution of dynamic EEs that shed some markers and acquire others as they perhaps generate ILVs, detach as ECVs/MVBs and slowly become more LE-like in nature? Or are the EEs and LEs more static, with budding, fission and fusion of vesicles from earlier less-specialized endosomes being delivered to a later endosomal compartment? These questions largely remain, despite significant advances in recent years, but answering them is essential for a complete understanding of the endosomal compartment."
So, I would prefer that we go back to your original proposal, add "endosome maturation" as a RELATED synonym. This seems most consistent with the state of the field.

**Comment by raymond91125** [comment]
Thanks for all the comments. I believe all issues are resolved. But if not, please reopen.
