### ISSUE TITLE
Fix branch 'modulation of complement activation in another organism'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26389]
These terms have no annotations: 

'modulation of complement activation in another organism' & children: 
- 'modulation of complement activation, alternative pathway in another organism'
- 'negative regulation of complement activation, alternative pathway in another organism'
- 'positive regulation of complement activation, alternative pathway in another organism'
- 'modulation of complement activation, classical pathway in another organism'
- 'negative regulation of complement activation, classical pathway in another organism'
- 'positive regulation of complement activation, classical pathway in another organism'
- 'modulation of complement activation, lectin pathway in another organism'
- 'negative regulation of complement activation, lectin pathway in another organism'
- 'positive regulation of complement activation, lectin pathway in another organism'

Need to check 

- [ ] if we need to describe the 3 pathways
- [ ] obsolete all  positive regulation of complement activation
- [ ] see how GO:0039573 suppression by virus of host complement activation fit in 

Action for @genegodbold 
- describe the terms needed to define the mechanisms by which complement is suppressed or evaded

**Comment by genegodbold** [comment]
**Unknown mechanism**:
- **Burkholderia pseudomallei autotransporter C** (BpaC): A _B. pseudomallei_ mutant in which the gene encoding BpaC is deleted suffers a 64-fold increase in the median lethal dose (LD50) in a BALB/c mouse model of intraperitoneal infection compared to the isogenic parent strain. The bacterial mutant was attenuated in intracellular replication and was more sensitive to host complement-mediated killing through the classical and/or lectin pathway. Complementation via plasmid-expressed BpaC restored wild-type serum resistance. BpaC also increases survival in macrophages [PMID:25830295]. 
- **Phospholipase D** from _Acinetobacter baumannii_: A mutant _A. baumannii_ in which the gene for PLD is deleted has a decreased ability to survive and proliferate in serum [PMID:20194595].

**Inhibits activation of the C1 complement complex**:
- **BBK32** of _Borrelia burgdorferi_ inhibits host complement activation by blocking activation of the C1 complement complex. The C terminal globular domain of BBK32 binds with high affinity to C1 and C1r. This may be the first report of a biomolecule that specifically and noncovalently inhibits C1/C1r [PMID:26808924].
- **Vag8** from _Bordetella bronchiseptica_: Bordetella pertussis autotransporter Vag8 is a serine protease that binds human host C1 esterase inhibitor and confers serum resistance. Vag8 was disrupted in two different _B. pertussis_ strains, BP338 and 18-323, and the mutants were tested for their ability to bind C1inh in a surface-binding assay. Neither mutant strain was capable of binding C1inh, whereas a complemented strain successfully bound C1inh [PMID:21695123]. Vag8 binding to human C1inh inhibits C1inh binding to C1s, C1r and MASP-2 resulting in the release of active proteinases that subsequently cut C2 and C4 _away from the surface of the bacterium_. This depletion of complement components result in decreased complement deposition on the bacteria and also less complement-mediated bacterial killing [PMID:28742139].

**Uses host complement control proteins as a shield to inhibit destruction by complement**
- **Bacillus collagen-like protein of anthracis** (**BclA**): BclA, a component of spores of _Bacillus anthracis_, mediates the attachment of host complement factor H, a complement control protein, to the bacterial spore. This produces a down-regulation of host complement both _in vitro_ and in a mouse model of infection. BclA is the most abundant protein in the exosporium, the outermost layer of B. anthracis spores. BclA improves persistence in mouse lungs and appears to downregulate antibody responses to spores. Both these effects are dependent on its activity against complement through factor H binding [PMID:27304426].
- **BhCRASP-1** (**CspH**) of _Borrelia hermsii_ binds host complement regulators factor H and factor H-related protein 1 (FHR-1) but not factor H-like protein 1 (FHL-1). BhCRASP-1 interacts with the short consensus repeat 20 of the mammalian factor H. Ectopic expression of the protein in a serum-sensitive strain of _B burgdorferi_ rendered it more resistant to human serum. BhCRASP-1 also binds host plasminogen/plasmin [PMID:17513779].

Other
- **Ubiquitous surface protein A1** (and A2) of _Moraxella catarrhalis_: Both UspA2 and UspA1 inhibit the generation of the anaphylatoxin C3a [PMID:21270401].

**Comment by genegodbold** [comment]
**Inhibits complement activation by direct association with complement proteins**:
- **Bordetella serum-resistance killing protein** (**BrkA**): BrkA from _Bordetella pertussis_ provides serum resistance by inhibiting the host classical pathway of complement activation. It prevents deposition of host C3 and accumulation of deposited C4 while not affecting C1 deposition [PMID:11292725]. A B. pertussis mutant strain in which the gene encoding BrkA is deleted exhibits a severe defect in colonization of the respiratory tract that manifests after three days following inoculation in a mouse model of infection. BrkA resists both antibody-dependent and -independent killing by complement. However, C3-deficient mice are still more effectively colonized by wild type bacteria when compared to mutants in which BrkA is deleted. Thus the colonization defect does not appear to be related to the ability of BrkA to provide serum resistance [PMID:15385494].
- **Complement inhibitor via C4 binding protein** (CihC) from _Borrelia recurrentis_: CihC is expressed on the outer surface of the bacterium in a patch-like manner. Expression of CihC significantly increases the serum resistance of the bacteria. CihC binds to both the C4 binding protein and the C1 inhibitor protein--the activity of both is retained upon binding. The central domain extends from residues 145 to 185 and mediates these interactions [PMID:20532227].
- **BBK32** of _Borrelia burgdorferi_ inhibits host complement activation by blocking activation of the C1 complement complex. The C terminal globular domain of BBK32 binds with high affinity to C1 and C1r. This may be the first report of a biomolecule that specifically and noncovalently inhibits C1/C1r [PMID:26808924].
- **Vag8** from _Bordetella bronchiseptica_: Bordetella pertussis autotransporter Vag8 is a serine protease that binds human host C1 esterase inhibitor and confers serum resistance. Vag8 was disrupted in two different _B. pertussis_ strains, BP338 and 18-323, and the mutants were tested for their ability to bind C1inh in a surface-binding assay. Neither mutant strain was capable of binding C1inh, whereas a complemented strain successfully bound C1inh [PMID:21695123]. Vag8 binding to human C1inh inhibits C1inh binding to C1s, C1r and MASP-2 resulting in the release of active proteinases that subsequently cut C2 and C4 _away from the surface of the bacterium_. This depletion of complement components result in decreased complement deposition on the bacteria and also less complement-mediated bacterial killing [PMID:28742139]. 
- **Collagen binding protein** (Cna) from _Staphylococcus aureus_: Cna binds to host complement protein C1q (UniProtP02745) and inhibits activation of the classical pathway of complement fixation on the bacterial surface [PMID:23720782].

**Inhibits complement activation indirectly**
- **Complement-inhibitor and Plg-binding protein** of _Acinetobacter baumannii_ (CipA) is a host plasminogen-binding protein. Plasminogen bound to the surface of A. baumannii by CipA, upon conversion to plasmin, degrades both host fibrinogen and host complement C3b and contributes to serum resistance. Besides its ability to bind plasminogen, CipA inhibits the alternative pathway of complement activation in vitro. Inactivation of CipA renders the bacterium sensitive to serum. CipA interacts with host plasminogen through its C terminal 18 residues [PMID26681776].
- **Cronobacter plasminogen activator** (Cpa) from _Cronobacter sakazakii_: Cpa can activate plasminogen and is required for resistance to complement-mediated killing. A mutant C. sakazakii in which the gene encoding Cpa was deleted demonstrated decreased serum resistance as the concentration of serum increased [PMID:21245266].

Other
- **Ubiquitous surface protein A1** (and A2) of _Moraxella catarrhalis_: Both UspA2 and UspA1 inhibit the generation of the anaphylatoxin C3a [PMID:21270401].

**Comment by pgaudet** [comment]
NTR 
- 1. **suppression of complement activation in another organism** 
- - (def) by inhibition of complement protein activity either by binding (sequestering) and inhibiting complement protein, or by cleaving it and inactivating it, or or by binding and inhibiting complement control protein
- 2. **premature activation of complement proteins** 
- - (def) complement not yet assembled, such that the complement doesn't reach the microbe surface  
- 3. **sequestration of complement away from the microbial surface**
- - 4. **direct sequestration** can either be  (microbial proteins hold the host complement away from the surface) 
- - 5. **indirect sequestration** (microbial protein binds a host complement control protein)
- - - (def) complement control protein (CCP) prevents complement activation, such that if a microbial surface protein bind to a CCP, the complement will fail to activate on the microbial surface (https://en.wikipedia.org/wiki/Complement_control_protein)

**Comment by pgaudet** [comment]
+
+[Term]
+id: GO:0141115
+name: suppression of complement activation by another organism by inactivation of complement p
roteins
+namespace: biological_process
+def: "A process in which another organism another organism disrupts or prematurely activates complement so that its microbial-destroying activities fail." [PMID:24312361, PMID:34305859]
+is_a: GO:0141114 ! suppression of complement activation by another organism
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26389" xsd:anyURI
+created_by: pg
+creation_date: 2023-11-22T15:32:58Z
+
+[Term]
+id: GO:0141116
+name: suppression of complement activation by another organism by complement sequestering
+namespace: biological_
+def: "A process in which another organism prevents the activation of complement by sequestering it away from its surface." [PMID:18323455]
+is_a: GO:0141114 ! suppression of complement activation by another organism
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26389" xsd:anysd:anyURI
+created_by: pg
+creation_date: 2023-11-22T15:34:16Z
+
+[Term]
+id: GO:0141117
ntrol protein
+namespace: biological_process
ctivate." [PMID:17513779, PMID:22540535, PMID:24129254, PMID:27304426]
+is_a: GO:0141114 ! suppression of complement activation by another organism
sd:anyURI
+created_by: pg
+creation_date: 2023-11-22T15:35:52Z

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 

GO:0044645  modulation of complement activation in another organism
GO:0044630  modulation of complement activation, lectin pathway in another organism
GO:0044627  modulation of complement activation, classical pathway in another organism
GO:0044633  modulation of complement activation, alternative pathway in another organism
GO:0044632  negative regulation of complement activation, lectin pathway in another organism
GO:0044631  positive regulation of complement activation, lectin pathway in another organism
GO:0044629  negative regulation of complement activation, classical pathway in another organism
GO:0044628  positive regulation of complement activation, classical pathway in another organism
GO:0044634  negative regulation of complement activation, alternative pathway in another organism
GO:0044635  positive regulation of complement activation, alternative pathway in another organism
GO:0044646  envenomation resulting in modulation of complement activation in another organism
GO:0044639  envenomation resulting in modulation of complement activation, lectin pathway in another organism
GO:0044636  envenomation resulting in modulation of complement activation, classical pathway in another organism
GO:0044642  envenomation resulting in modulation of complement activation, alternative pathway in another organism
GO:0044640  envenomation resulting in negative regulation of complement activation, lectin pathway in another organism
GO:0044641  envenomation resulting in positive regulation of complement activation, lectin pathway in another organism
GO:0044637  envenomation resulting in negative regulation of complement activation, classical pathway in another organism
GO:0044638  envenomation resulting in positive regulation of complement activation, classical pathway in another organism
GO:0044644  envenomation resulting in negative regulation of complement activation, alternative pathway in another organism
GO:0044643  envenomation resulting in positive regulation of complement activation, alternative pathway in another organism


The reason for obsoletion is that we are replacing these terms by 
GO:0141114  suppression of complement activation by another organism
GO:0141116  suppression of complement activation by another organism by complement sequestering
GO:0141115  suppression of complement activation by another organism by inactivation of complement proteins
GO:0141117  suppression of complement activation by another organism by recruitment of complement control protein

There are no annotations to these terms; these terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/26389

Thanks, Pascale

**Comment by pgaudet** [comment]
Changing back to 'symbiont-mediated' xx

**Comment by genegodbold** [comment]
Let's do this  @pgaudet!!!  🥇🥇🥇
