### ISSUE TITLE
Taxon constraint: Spemann organizer formation

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#26413]
Add taxon restiction to fit definition: Formation of the specialized region on the dorsalmost side of the embryo that acts as the main signaling center establishing the vertebrate body plan.

* **GO term ID label: GO:0060061 Spemann organizer formation**

* **Request to add a taxon constraint:**
* * **only in taxon: Vertebrata Taxonomy ID: 7742**

**Comment by pgaudet** [comment]
Hi Helen, 

We already have this taxon constraint, where do you see that it's missing ?

**Comment by hattrill** [comment]
came across it in QuickGO:
![Screenshot 2023-11-13 at 18 00 37](https://github.com/geneontology/go-ontology/assets/11865746/a5809cdd-e525-4d82-8eaa-cb56a182bfd2)
It's gone from P2GO now as asked Ruth to remove it.
Can only see 
Never in Taxon | 4895 | Schizosaccharomyces in QuickGO

![Screenshot 2023-11-13 at 18 02 07](https://github.com/geneontology/go-ontology/assets/11865746/12890e85-2c4e-48c4-b333-a91b1b7321ba)

**Comment by pgaudet** [comment]
We now have taxon constraints imported from Uberon and other ontologies. These should be available in QuickGO at the next  QuickGO release.
