### ISSUE TITLE
NTR: guanyl nucleotide exchange factor activator activity

### ISSUE THREAD

**Issue by EBIDaveC** [geneontology/go-ontology#26416]
Please provide as much information as you can: 

* **Suggested term label:**
Guanyl nucleotide exchange factor activator activity.

* **Definition (free text)**
Binds to and increases the activity of a guanyl nucleotide exchange factor.

* **Reference, in format PMID:#######**
PMID:37463208
Shows binding of Rab5 to the Mon1-Ccz1 complex activates the Rab7 GEF activity of the Mon1-Ccz1 complex in drosophila and yeast.

* **Gene product name and ID to be annotated to this term**
Rab5 (Q9V3I2)
Ypt10 (P38146)

* **Parent term(s)**
Could be is_a GO:0030234 enzyme regulator activity as is the case for the reciprocal function GO:199624 guanyl nucleotide exchange factor inhibitor activity. Alternatively could be is_a GO:0008047 enzyme activator activity, in which case the reciprocal function GO:199624 guanyl nucleotide exchange factor inhibitor activity should be is_a GO:0004857 enzyme inhibitor activity. Alternatively, the new term (Guanyl nucleotide exchange factor activator activity) and GO:199624 guanyl nucleotide exchange factor inhibitor activity (and possibly GO:0005091 Guanyl-nucleotide exchange factor adaptor activity) could be grouped as is_a (new term) Guanyl nucleotide exchange factor regulatory activity, which is_a GO:0030234 enzyme regulator activity.

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
Not that I am currently aware of.

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
Alternative to GO:1905099 (BP) positive regulation of guanyl-nucleotide exchange factor activity, which has the restriction "This term should not be used for direct annotation"

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160124
+name: guanyl nucleotide exchange factor activator activity
+namespace: molecular_function
+def: "Binds to and increases the activity of a guanyl nucleotide exchange factor." [PMID:37463208]
+is_a: GO:0008047 ! enzyme activator activity
+created_by: rynl
+creation_date: 2023-11-13T22:46:29Z
