### ISSUE TITLE
Changes in upstream file locations breaks ontology build

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#26426]
At least one mapping file has changed location and is breaking the build

Was
https://ftp.ebi.ac.uk/pub/databases/Rfam/CURRENT/rfam2go/rfam2go

Now (apparently)
https://ftp.ebi.ac.uk/pub/databases/Rfam/CURRENT/rfam2go

Tagging @balhoff

**Comment by kltm** [comment]
Making https://github.com/geneontology/go-ontology/pull/26427

**Comment by kltm** [comment]
Fixed

**Comment by balhoff** [comment]
Thanks!
