### ISSUE TITLE
Suggested "do not annotate" terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26424]
See
https://github.com/geneontology/go-annotation/issues/4115
Also GOC presentation. This is a selection of high-level terms used in annotation.
- [x] GO:0034641 cellular nitrogen compound metabolic process [56 direct annotation,  56 ARBA IEA,  0 EXP]
- [x] GO:0006807 nitrogen compound metabolic process [597 direct annotation, IEAs from InterPro, CGD, 97 PAINT IBA,  53 EXP]
- [x] GO:1901564 organonitrogen compound metabolic process [81 direct annotation,  All ARBA IEA]
- [x] GO:0044238 primary metabolic process  [241 direct annotation, 239 ARBA IEA, 2 EXP]
- [x] GO:0071704 organic substance metabolic process [231 direct annotation,  229 ARBA IEA,  2 EXP]
- [x] GO:0043170 macromolecule metabolic process [383 direct annotation,  377 IEA, 122 ARBA IEA,  3 EXP]
- [x] GO:0110165 cellular anatomical entity [1507 direct annotation,  1505 ARBA IEA,  EXP 2]
- [x] GO:0048588 developmental cell growth [70 direct annotation,  52 TAIR IEA,  7 EXP]
- [x] GO:0048856 anatomical structure development [2425 direct annotation,  719 ARBA IEA,   1673 PAINT IBA, 33 EXP]
- [ ] GO:0098771 inorganic ion homeostasis [87 direct annotation,  IEA TAIR 78, 1 EXP]
TAIR  from https://amigo.geneontology.org/amigo/reference/PMID:34562334 (these are predictions)
- [ ] GO:0060560 developmental growth involved in morphogenesis [74 direct annotation,  54 TAIR IEA,  8 EXP]
TAIR from https://amigo.geneontology.org/amigo/reference/PMID:34562334 (these are predictions)

[XXX direct annotation,  ARBA IEA,  EXP]

GO:0043231 intracellular membrane-bounded organelle HOLDING OFF ON THIS ONE HAS 14198 annotations 879 EXP, I wonder why??? 724 are HPA, are these useful? what does it mean?
10,794 are IBA?

- [x] GO:0043414 macromolecule methylation (2 direct) (already present)
- [x] changed "metabolic process" from "do not manually annotate" to "do not annotate"
- [x] GO:1901564 organonitrogen compound metabolic process [101, ARBA IEA]
- [x]  organonitrogen compound catabolic process [2 EXP]
- [x] organonitrogen compound biosynthetic  process [ 46 ALl IEA]
- [x] GO:0032879 regulation of localization [19 direct annotation,  4 EXP]

- [x] GO:0016310 phosphorylation AND ALL CHILDREN? (for now I did only the term)
- [x] GO:0016311 dephosphorylation AND ALL CHILDREN? (for now I did only the term)
- [x] GO:0046483   heterocycle metabolic process  [48 direct annotation,  7  EXP]

**Comment by ValWood** [comment]
@pgaudet  do you agree with these? I can check the direct annotation numbers before proceeding and flag the ones with not so many annotations (usually they only have a small number)

**Comment by ValWood** [comment]
also

lip2 | GO:1901576 | organic  substance biosynthetic process | IEA with ARBA00026382 |   | GO_REF:0000117 | 



</body></html>[lip2](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.pombase.org%2Fgene%2FSPAC4F10.05c&data=05%7C02%7Cvw253%40cam.ac.uk%7C70b7bc89eb2d4c58284d08dc0d65cd03%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638399978077787624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Db6p7Y9%2BnX3Hj%2BkCJZOq7pwUT6mAj1BipFfS%2BES5ot8%3D&reserved=0)
	[GO:1901576](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.pombase.org%2Fterm%2FGO%3A1901576&data=05%7C02%7Cvw253%40cam.ac.uk%7C70b7bc89eb2d4c58284d08dc0d65cd03%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638399978077787624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Fzllt0ZlG2sDLnsOaRP0cHHWidTBRNaOtNSYUXlnKnE%3D&reserved=0) 	
[organic substance biosynthetic process](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.pombase.org%2Fterm%2FGO%3A1901576&data=05%7C02%7Cvw253%40cam.ac.uk%7C70b7bc89eb2d4c58284d08dc0d65cd03%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638399978077787624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Fzllt0ZlG2sDLnsOaRP0cHHWidTBRNaOtNSYUXlnKnE%3D&reserved=0)
	[IEA](https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwiki.geneontology.org%2Findex.php%2FInferred_from_Electronic_Annotation_(IEA)&data=05%7C02%7Cvw253%40cam.ac.uk%7C70b7bc89eb2d4c58284d08dc0d65cd03%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638399978077787624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YL0ddGIY9JldpogH5nTMLRjvrm4xLQBDnlhV%2BL42NOQ%3D&reserved=0) with ARBA00026382 	
	[GO_REF:0000117](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.pombase.org%2Freference%2FGO_REF%3A0000117&data=05%7C02%7Cvw253%40cam.ac.uk%7C70b7bc89eb2d4c58284d08dc0d65cd03%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638399978077787624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4Jvz1FaJ%2BE5k9jCat8MJ3QW9KAE%2F5KfmxDrzLULTJBU%3D&reserved=0) 	[2479](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.pombase.org%2Fterm%2FGO%3A1901576&data=05%7C02%7Cvw253%40cam.ac.uk%7C70b7bc89eb2d4c58284d08dc0d65cd03%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638399978077787624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Fzllt0ZlG2sDLnsOaRP0cHHWidTBRNaOtNSYUXlnKnE%3D&reserved=0)

**Comment by ValWood** [comment]
@pgaudet  can I add these?
I think most have no annotations but it will prevent future function predictions (at least we can explain /filter them).
I think most of these came from function prediction evaluation.

**Comment by pgaudet** [comment]
Yes yes

**Comment by ValWood** [comment]
- [ ] Response  to organic substance
- [ ] macromolecule modification

**Comment by ValWood** [comment]
- [ ] ion binding
+ | − | (46) | DisProt
-- | -- | -- | --
+ | − | (4) | RGD

**Comment by gthayman** [comment]
4 RGD annotations moved.

**Comment by ValWood** [comment]
Thanks @gthayman 

Closing this one,  MODs can  fix from the logs.

@pgaudet  is this currently a soft check or a hard check?

**Comment by pgaudet** [comment]
soft check

**Comment by ValWood** [comment]
Could it be made a hard check for IEA maybe?
