### ISSUE TITLE
Query : GO:0006794 phosphorus utilization 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26429]
GO:0006794 **phosphorus** utilization zero annotations

Should this be **phosphate** utilization ?

**Comment by pgaudet** [comment]
Maybe it's ok? https://grammarist.com/spelling/phosphorous-phosphorus/
I suppose bacteria would use the mineral form?

**Comment by ValWood** [comment]
OK!
We don't have phosphate utilization .... that's what I was looking for...

**Comment by pgaudet** [comment]
add as synonym? I dont have a very strong feeling. 

If you have references that'd be useful.

**Comment by ValWood** [comment]
For my purposes phosphate ion homeostasis will suffice.

https://pubmed.ncbi.nlm.nih.gov/?term=%22phosphate+homeostasis%22+and+fission+yeast&sort=date&size=50

(I will keep this ticket open to add synonyms"
phosphate homeostasis
Pi homeostasis

**Comment by ValWood** [comment]
Also add synonyms to cellular phosphate ion homeostasis chid
