### ISSUE TITLE
Textual definition update:  nuclear protein quality control by the ubiquitin-proteasome system (GO:0071630)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26433]
from https://github.com/geneontology/go-ontology/issues/26432

* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request a definition update**

"nuclear protein quality control by the ubiquitin-proteasome system (GO:0071630)"
The chemical reactions and pathways resulting in the breakdown of misfolded proteins via a mechanism in which the proteins are transported to the nucleus for ubiquitination, and then targeted to proteasomes for degradation. PMID:20080635 PMID:21211726 PMID:21324894

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**

The chemical reactions and pathways resulting in the breakdown of misfolded, **damaged or unassembled** proteins via a mechanism in which the proteins are ~transported to the nucleus for~ ubiquitinated, and then targeted to nuclear proteasomes for degradation. 

* These pathways are not only for misfolded proteins, they can be proteins present in none stoichiometric amounts (unassembled into complexes), or damaged. This makes some of the parents inappropriate.

* **Reference(s)**

Remove the first reference, keep the second 2

* **Additional information**

I don't think we can use https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2824284/ to support the degradation of non nuclear resident substrates because it is using an artificial construct for the assay.

The second reference says
In yeast, the nuclear-localized ubiquitin ligase San1 specifically ubiquitinates abnormal nuclear proteins for proteasome degradation ([Gardner et al., 2005](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3042722/#R12))

The third reference
https://pubmed.ncbi.nlm.nih.gov/21324894/
talks about nuclear substrates.

**Comment by ValWood** [comment]
@pgaudet does this sound OK? I'll do these few ERD edits in my next session because they seem more straightforward that I thought.

**Comment by pgaudet** [comment]
Hi @ValWood 
To follow the genus-differentia guideline, I suggest you start the definition with "**A protein quality control pathway that** results in the breakdown of misfolded proteins via a mechanism in which the proteins are transported to the nucleus for ubiquitination, and then targeted to proteasomes for degradation. " 

Otherwise this is all good for me - always good to review references. 

Thanks, Pascale

**Comment by ValWood** [comment]
"A protein quality control pathway that results in the breakdown of misfolded, damaged or unassembled proteins via a mechanism in which the proteins are ubiquitinated, and then targeted to nuclear proteasomes for degradation.
