### ISSUE TITLE
Obsoletion request: GO:1990124 messenger ribonucleoprotein complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26431]
Please provide as much information as you can:

* **GO term ID and Label**

* **Reason for deprecation** Put an x in the appropriate box: 
 - [x] The reason for obsoletion is that the term is not clearly defined and usage has been inconsistent.

(There are no descendent terms)

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

Quick scan  of the annotations - these could move to the various correct specific  complex term in most cases

 More explanation of why it is a problem term below.

* **Are there annotations to this term?**
- How many EXP: 44

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***

- [x] https://github.com/geneontology/go-annotation/issues/4920
- [x] find external mappings (via IEAS), include in obsoletion notice  

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
@pgaudet  do you agree? (no hurry, I have lots in progress)

**Comment by pgaudet** [comment]
I dont have strong opinions about complexes, but that seems to be used in the iterature? 
https://pubmed.ncbi.nlm.nih.gov/?term=mRNP+complex

**Comment by hattrill** [comment]
@ValWood think that we can live without this term - just a handful of annotations to review and if we need specific terms, I will request. As it has no children and is vague, I am pro obsoletion.

**Comment by ValWood** [comment]
I didn't tag wormbase... @vanaukenk  could you look at yours? 5 annotations.
Thanks!

**Comment by vanaukenk** [comment]
@ValWood 

WB annotations done

**Comment by ValWood** [comment]
All annotations removed, process to obsoletion
