### ISSUE TITLE
Textual definition update: fatty acid/acyl chain length in GO terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26445]
I came across some discrepancies in acyl chain length within GO definitions, so decided to do a systematic check.

I realise that labelling acyl chains as short/medium/long/very long is somewhat arbitrary, but those labels are well used in the literature, and I see there is agreement (thankfully!) in CHEBI and [MetaCyc](https://biocyc.org/META/NEW-IMAGE?type=ECOCYC-CLASS&object=Fatty-Acids) about what they indicate:
- short-chain fatty acid (CHEBI:26666): chain length of less than C6.
- medium-chain fatty acid (CHEBI:59554): chain length of between C6 and C12.
- long-chain fatty acid (CHEBI:15904): chain length ranging from C13 to C22.
- very long-chain fatty acid (CHEBI:27283): chain length greater than C22.

I attach a file with all the GO terms I could find whose defs specifically define the number of carbons comprising a short/medium/long/very long chain.  I've summarised the results below. The main discrepancies within GO are for 'long chain' and 'very long chain'. I propose we make these definitions internally consistent and match the CHEBI/MetaCyc classification. (I guess that might necessitate an annotation review, even though the main discrepancy in 'long' vs 'very long' is really only about the C22/C23 border)

**SHORT CHAIN (7 GO terms):**
- "less than 6 carbons" (7 terms) => agrees with CHEBI/MetaCyc

**- MEDIUM CHAIN (10 GO terms):**
- "6 to 12 carbons" (9 terms) => agrees with CHEBI/MetaCyc
- "between eight and twelve carbons" (1 term) => change to 6-12

**LONG CHAIN (22 GO terms):**
- "between C13 and C22" (4 terms) => agrees with CHEBI/MetaCyc
- "13 to 21 carbons"  (15 terms) => change to 13-22
- "C13 or more/greater than 12 carbons" (3 terms) => change to 13-22

**VERY LONG CHAIN (12 GO terms):**
- "greater than C22" (5 terms) = agrees with CHEBI/MetaCyc
- "22 or more carbons"  (6 terms) => change to >22
- "greater than C18." (1 term) => change to >22

@pgaudet @deustp01 @ukemi 

[GO_terms_defining_chain_length.txt](https://github.com/geneontology/go-ontology/files/13390320/GO_terms_defining_chain_length.txt)

**Comment by sjm41** [comment]
@pgaudet Shall I go ahead and update the affected definitions, as suggested?

**Comment by pgaudet** [comment]
Yes, go ahead 👍

**Comment by sjm41** [comment]
@pgaudet I think it would be a good idea to reference the corresponding CHEBI id in the updated definitions. Is it OK for me to add "CHEBI:59554" etc as an additional reference xref, or would that cause problems?

**Comment by pgaudet** [comment]
I dont like using CHEBI in the xref, because this is not what they mean - xref means this is a term equivalent to this GO term. 

These are already in the reaction participants, if there is a RHEA link, for eg: 

[long-chain fatty acid-CoA ligase activity](http://purl.obolibrary.org/obo/GO_0004467)
<img width="460" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/504be069-3af6-439e-aa49-1acaf3b1206d">


Do you think that's not sufficient?

**Comment by deustp01** [comment]
> xref means this is a term equivalent to this GO term.

But the ChEBI information is relevant - For instance CHEBI:15904 - long-chain fatty acid has the definition "A fatty acid with a chain length ranging from C13 to C22". Could it be brought in, if not as an xref of the GO term then as an xref of the "has participant some long-chain fatty acid anion" (so the xref should actually be to long-chain fatty acid anion ([CHEBI:57560](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A57560)))?

This exact specification is worth preserving here because, I think, fatty acid chain length terms are often used inexactly in the literature so if GO wants to make exact chain lengths part of MF definitions, xrefs to ChEBI terms used by biochemists is a good and authoritative way to do it.

**Comment by pgaudet** [comment]
Hi @sjm41 

> Could it be brought in, if not as an xref of the GO term then as an xref of the "has participant some long-chain fatty acid anion"

This is what is is; it's just that for readability, we display 'long chain fatty acid anion' and not the ChEBI ID. If you click, you'll get to the ChEBI term imported in the ontology, and you can view the ID by typing control+U, where you see: 

<img width="611" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/6256f244-0caa-4d7d-b1e9-561b24289336">

Can you find it?

**Comment by sjm41** [comment]
Previous comment was from Peter, not from me!

**Comment by pgaudet** [comment]
oups !

**Comment by sjm41** [comment]
@pgaudet Note I was suggesting adding the CHEBI ID specifically as a **definition** xref (should that make a difference to your view!).  I think it's useful for GO users to explicitly see where the classification of different chain lengths (short, medium etc) in GO terms has come from.  All the current GO terms already contain a unattributed definition of chain length, and that's probably the main reason for the current inconsistencies.

If it's unwise/against policy to add CHEBI IDs as **definition** xref, would it work to just reference the CHEBI ID in the definition, like "A short-chain fatty acid has an aliphatic tail containing fewer than 6 carbons (CHEBI:26666)."?

Not a big deal if not. As you say, the CHEBI IDs are implicitly there via the RHEA xref.  I just thought explicitly mentioning the CHEBI ID as the source of chain length classification would be helpful and save some headaches down the line.

**Comment by pgaudet** [comment]
Def xrefs are a bit similarly unappropriate, in the sense that they are supposed to mean, this is where the term definition comes from, but this descibes one of the reactants, not the reaction itself. 

We could consider this, but then how would users know that for this specific case we cite ChEBI, but not for any other term; would they expect to see the ChEBIs in other def xrefs? 

---

How about using a **comment**? Saying that while there is not universal consensus on the lengths of short- medium. long fatty acids, GO is applying the same definition as CHEBI, and there you could link the ChEBI ID? 

Sorry I only thought about this now!

**Comment by sjm41** [comment]
_How about using a comment? Saying that while there is not universal consensus on the lengths of short- medium. long fatty acids, GO is applying the same definition as CHEBI, and there you could link the ChEBI ID?_

OK, that works for me.

In terms of doing this in Protege, do I:
1. Add annotation of type 'rdfs:comment' and add the comment text.
2. Then add a database_cross_reference to that comment of the form 'CHEBI:26666'
?

**Comment by deustp01** [comment]
> If you click, you'll get to the ChEBI term imported in the ontology, and you can view the ID by typing control+U,

Probably a feature request for the future: for a user who is not running the Protege editor, how is this information to be found?

**Comment by pgaudet** [comment]
@sjm41 
I dont know if you can put an xref annotation on a comment, usually, for PMIDs, we have been just putting the PMID directly as text. Does that work?

**Comment by pgaudet** [comment]
@deustp01 I create a ticket for the display of LDs and reaction participants in AmiGO https://github.com/geneontology/amigo/issues/706

**Comment by sjm41** [comment]
@pgaudet I think this is the final decision here:
- Retain (correcting where necessary) the text in the definition that defines the chain length.
- update the def if I see something doesn't match EC/RHEA
- Add a new **comment** to each term like "While there is not universal consensus on the lengths of short-, medium-, long- and very-long-chain fatty acids, the GO has used the definitions in ChEBI (see CHEBI:26666, CHEBI:59554, CHEBI:15904 and CHEBI:27283)."


Example:

id: GO:0008922
name: long-chain fatty acid [acyl-carrier-protein] ligase activity
def: "Catalysis of the reaction: ATP + an acid + [acyl-carrier protein] = AMP + diphosphate + acyl-[acyl-carrier protein]. A long-chain fatty acid is a fatty acid with an aliphatic tail of 13 to 21 carbons." [EC:6.2.1.20]

>

id: GO:0008922
name: long-chain fatty acid [acyl-carrier-protein] ligase activity
def: "Catalysis of the reaction: a long-chain fatty acid + ATP + holo-[ACP] = a long-chain fatty acyl-[ACP] + AMP + diphosphate. A long-chain fatty acid has an aliphatic tail containing 13 to 22 carbons." [EC:6.2.1.20]
comment: While there is not universal consensus on the lengths of short-, medium-, long- and very-long-chain fatty acids, the GO has used the definitions in ChEBI (see CHEBI:26666, CHEBI:59554, CHEBI:15904 and CHEBI:27283).

OK?

**Comment by sjm41** [comment]
Seems I missed a couple - need to update defs and add comments to these two:

id: GO:0004466
name: long-chain-acyl-CoA dehydrogenase activity
def: "Catalysis of the reaction: a long-chain 2,3-saturated fatty acyl-CoA + H+ + oxidized [electron-transfer flavoprotein] = a long-chain (2E)-enoyl-CoA + reduced [electron-transfer flavoprotein]." [RHEA:17721]

id: GO:0016937
name: short-chain fatty acyl-CoA dehydrogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: a short-chain 2,3-saturated fatty acyl-CoA + H+ + oxidized [electron-transfer flavoprotein] = a short-chain (2E)-enoyl-CoA + reduced [electron-transfer flavoprotein]." [RHEA:47196]
