### ISSUE TITLE
NTR: pH-gated channel activity terms

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#26444]
New terms for pH-gated ion channels

There is one pH-gated ion channel term: 
pH-gated chloride channel activity GO:0061797

it is under the term gated channel activity GO:0022836

Requesting terms for:
pH-gated sodium channel activity
and
pH-gated calcium channel activity

* **pH-gated calcium channel activity term**

A gated channel activity that enables the transmembrane transfer of a calcium ion by a channel that opens in response to a change in pH. 

is_a gated channel activity GO:0022836
is_a calcium channel activity GO:0005262

* **pH-gated sodium channel activity term**

A gated channel activity that enables the transmembrane transfer of a sodium ion by a channel that opens in response to a change in pH. 

is_a gated channel activity GO:0022836
is_a sodium channel activity GO:0005272

* **Gene product name and ID to be annotated to this term**
Recs1; FBgn0038209

Not sure if new parent term is needed or not.

**Comment by pgaudet** [comment]
@hattrill can you please provide references for these activities?

**Comment by hattrill** [comment]
Sorry, @pgaudet: PMID:34767445

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160125
+name: pH-gated sodium channel activity
+namespace: molecular_function
+def: "A gated channel activity that enables the transmembrane transfer of a sodium ion by a channel that opens in response to a change in pH." [PMID:34767445]
+is_a: GO:0022836 ! gated channel activity
+relationship: has_primary_input CHEBI:29101 ! sodium(1+)
+property_value: term_tracker_item "" xsd:anyURI
+created_by: rynl
+creation_date: 2023-11-21T00:50:09Z
+
+[Term]
+id: GO:0160126
+name: pH-gated calcium channel activity
+namespace: molecular_function
+def: "A gated channel activity that enables the transmembrane transfer of a calcium ion by a channel that opens in response to a change in pH." [PMID:30930064, PMID:34767445]
+is_a: GO:0022836 ! gated channel activity
+relationship: has_primary_input CHEBI:29108 ! calcium(2+)
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26444" xsd:anyURI
+created_by: rynl
+creation_date: 2023-11-21T00:56:00Z

**Comment by pgaudet** [comment]
@hattrill 

Looking at the paper again, it seems this is not 'gating', but regulation. The paper talk about 

> pH-dependent calcium and sodium channel

**Comment by hattrill** [comment]
Would be consistent with Ca2+ act term, so fine with that. 

A lot of papers use gating and activation/regulation interchangably. But, if we use activated for ions and gating for molecules, that is consistent.

**Comment by raymond91125** [comment]
It's pH-dependent, not necessarily pH-activated. (C, black squares)
![image](https://github.com/geneontology/go-ontology/assets/619520/64c6a8a2-4d99-4b45-a958-500a570a262e)

**Comment by raymond91125** [comment]
I think X-dependent ion channel and X-gated ion channel are synonymous. PMID: 30930064 states: "Protonation of Asp171 leads to an open-state structure." This is consistent with the notion that pH changes is gating the channel. It is however true that these articles don't necessary use the word "gate". We could add "pH-dependent" and "pH-sensitive" as equivalent synonyms.

**Comment by pgaudet** [comment]
Thanks for the feedback Raymond. 

That works for me. To me the confounding issue is that we have both 'gated' and 'activated' channels, with no clear reason why there is an inconsistency. For example 'activated' includes  
GO:0015275 stretch-activated, monoatomic cation-selective, calcium channel activity >> OK ? 

The following should be changed to 'gated'? 
GO:0005222 intracellular cAMP-activated cation channel activity  
'calcium-activated cation channel activity'
'calcium-activated potassium channel activity'
'chloride-activated potassium channel activity'

I think for calcium the gating is not via direct calcium binding, but the terms are under 'gated channel activity'. 

If we could be more consistent that'd be great. 

Thanks, Pascale

**Comment by lbreuza** [comment]
Hi,
could we also add a parent term pH-gated channel activity for channels that a re not substrate specific like ZACN (PubMed=26872532).
Ligand-gated cation channel permeable to the sodium and potassium monoatomic cations and gated by zinc (Zn2+), copper (Cu2+) and pH.
"We demonstrate that Cu2+ and H+ also are agonists of ZAC, which consequently should be considered
a Zn2+, Cu2+- and pH-sensing receptor." I guess one can replace sensing by gated in that sentence of the paper.
Best, Lionel

**Comment by pgaudet** [comment]
Hi @raymond91125 

Are you planning to create the grouping class, pH-gated channel activity, as requested by @lbreuza ? 

Thanks, Pascale

**Comment by lbreuza** [comment]
Hi @raymond91125,
pH-gated ion channels are also called proton-gated ion channels PMID: 38002313. Could you please add this synonym?
Thanks, Lionel

**Comment by raymond91125** [comment]
A family tree of ion channels https://www.guidetopharmacology.org/GRAC/ReceptorFamiliesForward?type=IC
![image](https://github.com/geneontology/go-ontology/assets/619520/46ef8ff9-0939-4aa6-9617-dfecec41e091)

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160128
+name: pH-gated channel activity
+namespace: molecular_function
+def: "Enables the transmembrane transfer of a solute by a channel that opens in response to a change in proton concentration (pH)." [PMID:17167423, PMID:29513651]
+synonym: "acid-sensing ion channel activity" RELATED []
+synonym: "proton-gated ion channel activity" RELATED []
+is_a: GO:0022836 ! gated channel activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26444" xsd:anyURI
+created_by: rynl
+creation_date: 2023-11-29T00:03:01Z

**Comment by pgaudet** [comment]
Hi @raymond91125 

Would you please change the asserted classes to a logical definition for the 3 new terms?

**Comment by pgaudet** [comment]
@lbreuza 
Sorry, I just noticed this, but since all children of the grouping class 'pH-gated channel activity' transport monoatomic ions, could we change the label and definition of the GO:0160128 pH-gated channel activity  to reflect that?

**Comment by raymond91125** [comment]
https://github.com/geneontology/go-ontology/issues/26520

> Also, please add a comment on 'GO:0160128 pH-gated channel activity' to explain that while the term suggest this activity may be proton-gated, the mechanism of pH-gating for transporters is by protonation of specific residues in the protein, and not by H+ binding.
> 
> Thanks, Pascale

I'm not sure if there is a difference between proton binding and protonation in this context, though. PMID:34136464.

**Comment by lbreuza** [comment]
> #26520
> 
> > Also, please add a comment on 'GO:0160128 pH-gated channel activity' to explain that while the term suggest this activity may be proton-gated, the mechanism of pH-gating for transporters is by protonation of specific residues in the protein, and not by H+ binding.
> > Thanks, Pascale
> 
> I'm not sure if there is a difference between proton binding and protonation in this context, though. PMID:34136464.

I would suggest "pH-gated channel activity and proton-gated channel activity are often used interchangeably as they refer to the same mechanism of activation of a channel through protonation of some residues upon decrease in pH"
