### ISSUE TITLE
PARENTAGE QUERY: GO:0031126 snoRNA 3' end processing 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26459]
(Can we have a generic  template for Superclass query?)

<img width="819" alt="Screenshot 2023-11-19 at 18 37 52" src="https://github.com/geneontology/go-ontology/assets/7359272/088bab34-bff3-4bf5-9d36-9413324195f3">

snoRNA 3' end processing is under 
"regulatory ncRNA-mediated gene silencing"

Also, what do we mean by "regulatory ncRNA" it seems a bit vague

CC @pgaudet

**Comment by ValWood** [comment]
I have removed this realtionship.

@pgaudet  aside, In general, from reviewing processing/surveillance so far, I think it's a big problem to group anything by ncRNA because it groups apples and oranges and pears
i.e tRNA (pol III)
 rRNA (pol I)
lncRNA (pol II) and 
snoRNA/snRNA  (except U6 that is transcribed by pol III)
but most of the processing pathways are linked to specific polymerases occur co-transcriptionally.
I think we should remove the "ncRNA grouping"  because it isn't biologically relevant, and focus on the specific classes, it will be more meaningful. But more about this later. Just thought I would mention it for consideration.

**Comment by pgaudet** [comment]
> I think it's a big problem to group anything by ncRNA because i

I agree, this is why I had started to change some of the terms to *regulatory* ncRNA

**Comment by pgaudet** [comment]
Note that I requested a SO term to help classifying GO terms, https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/616
