### ISSUE TITLE
NTR: calcium-activated sodium channel activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#26462]
* **NTR**
calcium-activated sodium channel activity

* **Definition**
Enables the calcium concentration-regulatable energy-independent passage of sodium ions across a lipid bilayer down a concentration gradient. **

* **Reference**
PMID:31629603

* **Gene product name and ID to be annotated to this term**
FBgn0053349 
ppk25

* **Parent term(s)**
is_a
is_a
-calcium-activated cation channel activity
GO:0005227
-ligand-gated sodium channel activity
GO:0015280

**Comment by pgaudet** [comment]
Is this a 'gated' activity? It seems calcium activates the channel (via calmodulin binding) 

> Mechanistically, PPK25 operates as a transduction channel: its activation requires odor-induced Ca2+ influx and a calmodulin binding motif (CBM) in the N-terminal intracellular domain. This result therefore highlights a novel mechanism whereby DEG/ENaCs can be activated by second messengers

but I dont this it's 'calcium gated' - see 

https://www.news-medical.net/health/Importance-of-Ion-Channels-in-the-Body.aspx

**Comment by hattrill** [comment]
ok - that sounds reasonable.
Don't make it an is_a 'ligand-gated sodium channel activity'
GO:0015280
is more inline with other ion-regulated channels.

**Comment by pgaudet** [comment]
See also https://github.com/geneontology/go-ontology/issues/26444#issuecomment-1822673586

if there really is a difference between 'gated' and 'activated', then we need to look at the other 'calcium-activated' terms and move them out of 'gated channel activity'. 

Thanks, Pascale

**Comment by hattrill** [comment]
I think that I was originally more concerned with the "ligand" component of ligand-gated ion channel.

**Comment by hattrill** [comment]
Looking at the textual definitions in https://tcdb.org/ they use gating and activating interchangeably. Perhaps we should be clear that activating/gating is the main means of activating the channel under physiological conditions.

**Comment by hattrill** [comment]
To complicate the Ca2+ activation/gating question, I have just been looking at the "Mitochondrial calcium uniporter" which conducts Ca2+ in response to increase Ca2+ ion channel -  this is the GO:1990246 uniplex complex (not a uniporter in the GO sense which is a secondary transporter, but a passive transmembrane transporter). In this instance, the channel is closed by non-membrane complex component that blocks the channel. 
<img width="205" alt="Screenshot 2023-12-01 at 08 51 36" src="https://github.com/geneontology/go-ontology/assets/11865746/b5b10bcd-83e6-4c18-bf20-c238cb41b8c5">

So, this is simialar to the request above - calcium-activated sodium channel activity.

Looking at the guide that @raymond91125 put up on https://github.com/geneontology/go-ontology/issues/26444  - I don't see these examples of Ca2+ gating represented; nor do I see them on this guide: https://www.cell.com/cell/pdf/S0092-8674(17)30826-7.pdf

So, I am wondering that this is more of capturing the allosteric regulation of the channel via annotating the Ca2+ binding subunit with channel activator activity GO:0099103 will do for now.

However, looking at the term calcium-activated potassium channel activity (there are 97  exp evidenced annotations in QuickGO https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0015269&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants)
many are small conductance Ca-activated potassium (SK) channels which are "gated" via a regulatory Ca2+ binding subunit.

<img width="1040" alt="Screenshot 2023-12-01 at 09 09 31" src="https://github.com/geneontology/go-ontology/assets/11865746/370086fa-ee34-41de-bf5e-8378484f79f9">

https://www.nature.com/articles/s12276-018-0043-z encapsulates that issue of classification of classification:

"The International Union of Pharmacology has now grouped all Ca2+-activated K+ channels into one gene family, including large conductance Ca2+- and voltage-activated K+ (BK) channels, intermediate conductance Ca2+-activated K+ channels (IK), and small-conductance Ca2+-activated K+ (SK) channels, which are sensitive to apamin. SK channels consist of six transmembrane regions (TMs) and a single pore loop, with four subunits around a central pore. Both N-termini and C-termini are oriented toward the cytoplasm. The hypothesis that Ca2+-activated K+ channels link free intracellular Ca2+ to the opening of K+ channels is long-standing, and could explain several effects of free cytosolic Ca2+ on TM currents. SK channels have no charged amino acids in the fourth TM domain, which is usually an important component of a voltage sensor. The activity of BK channels is induced both by Ca2+ and voltage, whereas SK channels and IK channels are activated and deactivated solely as a consequence of Ca2+ binding or release.

SK channel gating depends on the interplay between the pore-forming α subunits and Ca2+-binding protein calmodulin (CaM)"

Sorry, that is rather a lot of text with very little decision.

I think this may be comes down to how GO classifies the gated activity rather than family classification. Is a gated channel activity a channel which is shut in the absence of a stumulus or a channel that subunit that has to simultaneously sense the stimulus and form a pore?
In terms of annotations, perhaps we can use "contributes_to" in annotation when the sensor SU is not a pore SU?

**Comment by raymond91125** [comment]
@hattrill Should we close this NTR? Noted that there may be expanded use of the term calcium-activated potassium channel activity. At least in the case of BK channels, Ca2+ binds to and regulate the channel directly. https://en.wikipedia.org/wiki/BK_channel.
Expanding the meaning of 'activated' to include indirect sensing, I am concerned that is a slippery slope.

**Comment by hattrill** [comment]
@raymond91125 yes, let's close this. The blurring of sensing vs gating is too problematic.
