### ISSUE TITLE
Missing parent: RNA trimethylguanosine synthase activity (GO:0071164)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26464]
* **GO term ID and label for which you request a new superclass**

RNA trimethylguanosine synthase activity (GO:0071164)

* **New superclass (parent) suggested**

~GO:0008757 | S-adenosylmethionine-dependent methyltransferase activity~
done

* **Reference(s), if appropriate**
PMID:nnnnnnn

Definition refers to AdoMet:

Catalysis of two successive methyl transfer reactions from AdoMet to the N-2 atom of guanosine, thereby converting 7-methylguanosine in an RNA cap to 2,2,7 trimethylguanosine.

**Comment by pgaudet** [comment]
Hi @ValWood 

We have a couple of inconsistencies here: 
- RNA trimethylguanosine synthase activity (GO:0071164):  This modification seems to occur on the 5'end, should this be in the term label?  
-  the RHEA cross refs for this term mentions mRNA; do we need specific terms for all types of RNAs? 
- I thought we should put RNA trimethylguanosine synthase activity (GO:0071164) under RNA 5'-methyltransferase activity (GO:1990276); however the reference and the annotations to this term specifically mention snRNA  as a substrate; should we specify this? and add a xref to https://www.rhea-db.org/rhea/58780? 
- 
Thanks, Pascale

**Comment by ValWood** [comment]
PMID: 17284461
says
A subset of capped RNAs contain one or two additional methyl groups attached to the exocyclic N2 of the cap guanosine. A 2,2,7-trimethylguanosine (TMG) cap is found on many small noncoding eukaryal RNAs such as small nuclear (sn) and small nucleolar (sno) RNAs and telomerase RNA ([14](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1865056/#B14),[15](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1865056/#B15)) and on nematode mRNAs that undergo trans-splicing of a 5′-capped leader sequence ([16](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1865056/#B16)). A 2,7-dimethylguanosine (DMG) cap is detected in the mRNAs of two RNA viruses: Sindbis virus and Semliki Forest virus ([17](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1865056/#B17),[18](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1865056/#B18)).

So probably the definition should be broader?

2. I agree
RNA trimethylguanosine synthase activity -> 
RNA cap 2,2,7-trimethylguanosine synthase activity

os even better
RNA cap 2,2,7-trimethylguanosine methylase activity

3. RNA 5'-methyltransferase activity (GO:1990276)
 is different. This is the transfer of a methyl group from S-adenosyl-L-methionine to the 5'-gamma-phosphate
not to the guanosine
https://en.wikipedia.org/wiki/Five-prime_cap
i.e.
https://www.pombase.org/term/GO:1990276
https://www.pombase.org/gene/SPBC2A9.10
Although still snos  as substrates

But the term label could be more explicit to match the definition? I 

RNA 5'-gamma-phosphate methyltransferase activity?

**Comment by ValWood** [comment]
Updated comment above

**Comment by pgaudet** [comment]
1) 
> So probably the definition should be broader?

Is is the same activity? ie are there other RHEA and ECs for other substrates? 

2) Renaming 
> RNA trimethylguanosine synthase activity ->
RNA cap 2,2,7-trimethylguanosine synthase activity

Is it the cap that is modified? or the 5' end, to produce the cap? 

3) RNA 5'-methyltransferase activity (GO:1990276)
Yes, it would be good to have more explicit labels (and definitions if needed), to represent the substrate 
Looks like that one corresponds to RHEA:58656 (and not [RHEA:58780](https://www.rhea-db.org/rhea/58780)?

**Comment by ValWood** [comment]
2. 
RNA trimethylguanosine synthase activity   is methylating the cap on these 3 residues:

<img width="446" alt="Screenshot 2023-12-01 at 09 58 32" src="https://github.com/geneontology/go-ontology/assets/7359272/d06cf477-848c-44f4-96c2-ee73c135e381">

**Comment by ValWood** [comment]
Actually that wasn't clear... maybe they are.... need to check

**Comment by ValWood** [comment]
There are 4 annotations to this term :
PomBase (2) 
TAIR  (1) (IGI to SGD, presumably from a complemetnation although that annotation is not made at SGD) (1) 
human (1)
All for TGS1/orthologs.

The human annotation is for u snRNPs:
The snRNAs U1, U2, U4, and U5 are transcribed by RNA polymerase II in the nucleus as snRNA
precursors containing a 5 terminal 7-monomethylguanosine cap structure and are then transported to the cytoplasm by the CRM1/RanGTP pathway using the U snRNA–
specific adaptor PHAX (Ohno et al., 2000).
Results
hTGS1 Is Required for Hypermethylating the m7G Cap of U snRNAs

So this enzyme seems to be specific for mRNA and snRNA
It is definitely pol II specific modification

**Comment by ValWood** [comment]
[CAUTION GPC CHAT]
SnoRNAs (small nucleolar RNAs) do not typically have a 5' m7G cap like messenger RNAs (mRNAs). Instead, they undergo different modifications and are often characterized by a unique 2,2,7-trimethylguanosine (TMG) cap structure

but this was the same info I got at the RNA central meeting, so for now will describe as mRNA/snRNA

**Comment by ValWood** [comment]
[CAUTION GPC CHAT] 
The 5' m7G cap and 2,2,7-trimethylguanosine (TMG) cap are similar modifications found at the 5' ends of different types of RNA molecules, but they are not exactly the same.

The 5' m7G cap refers to the 7-methylguanosine cap found at the 5' end of many eukaryotic messenger RNAs (mRNAs) and some small nuclear RNAs (snRNAs). This modification consists of a guanosine nucleotide with a methyl group (CH3) attached at the 7th position of the guanine base.

On the other hand, the 2,2,7-trimethylguanosine (TMG) cap is a modification specifically found at the 5' end of some small nucleolar RNAs (snoRNAs). This cap structure also involves a guanosine nucleotide, but in this case, it has three methyl groups (CH3) attached at the 2nd, 2nd, and 7th positions of the guanine base, hence the name "2,2,7-trimethylguanosine."

While both caps serve roles in stabilizing and protecting the RNA molecules, they are distinct modifications found in different types of RNAs and may have specific functions related to the processing, stability, and recognition of these RNAs within the cellular machinery.

**Comment by ValWood** [comment]
RIght, I had not read the ticket properly. My head drained over christma, we were discussing
RNA cap 2,2,7-trimethylguanosine synthase activity
here

1. rename 
RNA trimethylguanosine synthase activity ->
RNA cap 2,2,7-trimethylguanosine methylase activity (because synthase seems to includes the preceding steps too)
(NB, not to 5' because although it is at the 5' end  of the RNA it's not methylating the 5' residue it is methylating the cap

2. for this reason, I don't  think we should put under 
 RNA 5'-methyltransferase activity (GO:1990276) because  this is
"Catalysis of the transfer of a methyl group from S-adenosyl-L-methionine to the 5'-gamma-phosphate in an RNA molecule."

3.  add parent GO:0008757 | S-adenosylmethionine-dependent methyltransferase activity

4. RNA 5'-methyltransferase activity (GO:1990276)  rename to RNA 5'-gamma-phosphate methyltransferase activity?

5. add a comment to GO:0071164
"A 2,2,7-trimethylguanosine (TMG) cap is found on many RNA polymerase II transscribed small noncoding RNAs including small nuclear RNA (snRNA), small nucleolar RNA (snoRNA) and telomerase RNA. It is also found on nematode mRNAs that undergo trans-splicing of a 5′-capped leader sequence.
"
because of this is it's probably OK that the Rhea xref mentions mRNAs although this is not  a common substrate?

6. Check the Rhea x-references

@pgaudet Does that sound OK ?
@sjm41  I think you looked at capping enzymes recently. Did this activity come onto your radar?

**Comment by ValWood** [comment]
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0071164
the RHEAs added in July and look correct

still need to locate Rhea for 
https://www.ebi.ac.uk/QuickGO/term/GO:1990276
Pascale noted above "Looks like that one corresponds to RHEA:58656 (and not [RHEA:58780](https://www.rhea-db.org/rhea/58780)?"

**Comment by ValWood** [comment]
Looks like that one corresponds to RHEA:58656 (and not [RHEA:58780](https://www.rhea-db.org/rhea/58780)?"
RHEA:58656 is deleted
RHEA:58780  refers to a 5'-end triphospho-guanosine-ribonucleotide-snRNA so it is too narrow?

**Comment by ValWood** [comment]
- [ ] rename 7-methylguanosine cap hypermethylation (GO:0036261)
into
2,2,7-trimethylguanosine sno/snRNA capping

the existing term describes the activity rather than the process (this term can then also be used for the previous steps too)
and will be a more appropriate sibling to
7-methylguanosine mRNA capping GO:0006370

If I have understood correctly all snRNA/snoRNA/mRNA have the 
7-methylguanosine RNA cap 
but then it is differentially modified to provide the final cap in different species (although mRNA final version can be just 7-methylguanosine).

**Comment by ValWood** [comment]
see https://github.com/geneontology/go-ontology/issues/26934
