### ISSUE TITLE
NTR: [nitric oxide dioxygenase activity, heme protein as donor]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#26482]
Please provide as much information as you can: 

* **Suggested term label:**
nitric oxide dioxygenase activity, heme protein as donor

* **Definition (free text)**
Catalysis of the reaction: Fe(II)-heme b-[protein] + nitric oxide + O2 = Fe(III)-heme b-[protein] + nitrate.

* **Reference, in format PMID:#######**
PubMed:20511233

* **Gene product name and ID to be annotated to this term**
CYGB

* **Parent term(s)**
GO:0016675  oxidoreductase activity, acting on a heme group of donors

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
[Rhea:78091] The reaction is not yet public.

* **Any other information**
GO:0008941 nitric oxide dioxygenase activity catalysis a similar reaction but the electron donor is different (NADPH).

**Comment by pgaudet** [comment]
Should I add 'Cytoglobin' as a synonym?

**Comment by lbreuza** [comment]
Literature suggest this is an activity shared by several globins.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141118
+name: nitric oxide dioxygenase activity, heme protein as donor
+namespace: molecular_function
+def: "Catalysis of the reaction: Fe(II)-heme b-[protein] + nitric oxide + O2 = Fe(III)-heme b-[protein] + nitrate." [PMID:20511233]
+comment: Note that this activity is similar to nitric oxide dioxygenase activity ; GO:0008941, but GO:000894 uses NADPH as the electron donor.
+xref: RHEA:78091
+is_a: GO:0016675 ! oxidoreductase activity, acting on a heme group of donors
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26482" xsd:anyURI
+created_by: pg
+creation_date: 2023-11-23T12:37:09Z

**Comment by pgaudet** [comment]
Add xref: GO:0106316 nitrite reductase NADH activity 
add xref: EC:1.7.1.15

**Comment by pgaudet** [comment]
obsolete [nitrite reductase NADPH activity](http://purl.obolibrary.org/obo/GO_0106314); activity not known to exist
There are either NAD(P)H (eukaryotes; EC:1.7.1.4) or NADH-dependent (bacteria; EC:1.7.1.15)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete [GO:0106314 nitrite reductase NADPH activity](https://amigo.geneontology.org/amigo/term/GO:0106314#display-lineage-tab). The reason for obsoletion is that this activity is not known to exist. There are no annotations or mappings to this term; this term is not present in any subset. 

You can comment on the ticket: 
https://github.com/geneontology/go-ontology/issues/26482

Thanks, Pascale
