### ISSUE TITLE
Obsoletion request:     GO:0038008 TRAF-mediated signal transduction

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26498]
GO:0038008 TRAF-mediated signal transduction

TRAF is an adaptor that is part of other signaling pathways, such as NF-KB (PMID:26776522) and TNF 

2 EXP

**Comment by deustp01** [comment]
A ling time ago, we annotated a series of multi-step processes in chicken involving TRAF signaling (and released them, so there are more than two EXP annotations). Not sure whether we'd do it this way now, but here are links to the pathways, for possible use in a discussion of whether TRAF signaling is a sufficiently extensive process to rate its own independent cassette. I'm not the local expert on this but I'm pretty sure that the answer would be "yes".
[TRAF mediated activation of IRF](https://reactome.org/content/detail/R-GGA-1227882)
[NFkB and MAPK activation mediated by TRAF6](https://reactome.org/content/detail/R-GGA-433822)
[TRAF6 mediated NF-kB activation](https://reactome.org/content/detail/R-GGA-1227892)
[TRAF6 mediated IRF7 activation](https://reactome.org/content/detail/R-GGA-933541)

**Comment by pgaudet** [comment]
Dear all,

The proposal has been made to obsolete

GO:0038008 TRAF-mediated signal transduction (https://github.com/geneontology/go-ontology/issues/26498)
GO:0019932 second-messenger-mediated signaling (https://github.com/geneontology/go-ontology/issues/26503)
GO:0071848 positive regulation of ERK1 and ERK2 cascade via TNFSF11-mediated signaling and GO:0071847 TNFSF11-mediated signaling pathway (https://github.com/geneontology/go-ontology/issues/26499)
GO:0061359 regulation of Wnt signaling pathway by Wnt protein secretion (https://github.com/geneontology/go-ontology/issues/26404)
GO:0007227 signal transduction downstream of smoothened (https://github.com/geneontology/go-ontology/issues/26496)

The reason for obsoletion is that these represent parts of other signaling pathways.  There are 19 annotations to these terms, see https://github.com/geneontology/go-annotation/issues/4853

Group | Number of EXP 
-- | --
BHF-UCL | 5
MGI | 9
RGD | 1
UniProt | 1 (Done)
WB | 1
ZFIN | 2


There are some HAMAP mappings. These terms are not present in any subsets. You can comment on the tickets (see individual links above). 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @deustp01 

Discussing this with @hattrill and @gantonazzo 
Looking at the UniProt description of TRAF6, it says "Adapter protein that seems to play a role in signal transduction initiated via TNF receptor, IL-1 receptor and IL-17 receptor (PubMed:[8837778](https://www.uniprot.org/citations/8837778), PubMed:[19825828](https://www.uniprot.org/citations/19825828), PubMed:[12140561](https://www.uniprot.org/citations/12140561)).", which is consistent with the Reactome pathways you show above. 

So, we still understand TRAF6 to be an adaptor that plays roles in multiple pathways. Unless you can help us define a module or a cassette with TRAF6 ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Proposals for Reactome annotations: 

- [TRAF mediated activation of IRF](https://reactome.org/content/detail/R-GGA-1227882) >> [tumor necrosis factor-mediated signaling pathway](http://purl.obolibrary.org/obo/GO_0033209)
- [NFkB and MAPK activation mediated by TRAF6](https://reactome.org/content/detail/R-GGA-433822) >> induction by lipopolysaccharide; this must be a toll-like receptor signaling pathway
- [TRAF6 mediated NF-kB activation](https://reactome.org/content/detail/R-GGA-1227892) >> [RIG-I signaling pathway](http://purl.obolibrary.org/obo/GO_0039529)
- [TRAF6 mediated IRF7 activation](https://reactome.org/content/detail/R-GGA-933541) >> 'computationally inferred', >> 'parent' pathway (https://reactome.org/content/detail/R-HSA-933541) seems to describe [RIG-I signaling pathway](http://purl.obolibrary.org/obo/GO_0039529)

**Comment by VShamovsky** [comment]
I've edited Reactome annotations to remove any reference to GO:0038008 TRAF-mediated signal transduction.
Now, TRAF-mediated chicken events are covered by the GO term of their respective parent pathway:

- [TRAF mediated activation of IRF](https://reactome.org/content/detail/R-GGA-1227882) under [MDA-5 signaling pathway](http://purl.obolibrary.org/obo/GO_0039530)
- [TRAF6 mediated NF-kB activation](https://reactome.org/content/detail/R-GGA-1227892) under [MDA-5 signaling pathway](http://purl.obolibrary.org/obo/GO_0039530)
- [NFkB and MAPK activation mediated by TRAF6](https://reactome.org/content/detail/R-GGA-433822) under [MyD88-dependent toll-like receptor signaling pathway](https://www.ebi.ac.uk/QuickGO/term/GO:0002755)
