### ISSUE TITLE
Obsoletion request: GO:0032015 regulation of Ran protein signal transduction  & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26504]
- [ ] GO:0032016 negative regulation of Ran protein signal transduction >> no annotations 
- [ ] GO:0032017 positive regulation of Ran protein signal transduction  >> no annotations
- [ ]  GO:0032015 regulation of Ran protein signal transduction >> no annotations
- [ ] GO:0090226regulation of microtubule nucleation by Ran protein signal transduction

Process not known to be regulated

**Comment by pgaudet** [comment]
Hi @deustp01 

Thanks for the feedback. Unfortunately I dont have access to the Bioassays paper. However from the abstract it looks like they are talking about GAFs and GAPs, is this right ? I would have classified this as part of the Ran signaling pathway, not part of its regulation? (otherwise Ran itself is the Ram signaling pathway? )

**Comment by deustp01** [comment]
OK. The paper talks about GAFs and GAPs, yes, so as you say the pathway boundary can be drawn to make their activities part-of the process, not regulators of it.

**Comment by pgaudet** [comment]
Nice paper by the way!
