### ISSUE TITLE
NTR: single strand DNA repair

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#26500]
Please provide as much information as you can: 

* **Suggested term label:**  single strand DNA repair

* **Definition (free text)** The repair of single strand DNA. A variety of different single strand DNA (ssDNA) repair pathways have been reported that include single strand break repair, the repair of methylated, alkylated and damaged ssDNA and the  removal of uracil.

* **Reference, in format PMID:#######:** PMID: 18775698, PMID: 31981739

* **Gene product name and ID to be annotated to this term**: ALKBH3 Q96Q83, FTO Q9C0B1, NEIL3 Q8TAT5, UNG (UNG2) P13051

* **Parent term(s)**:  GO:0006281 DNA repair

* **Children terms (if applicable)** : GO:0000012 single strand break repair

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
*  EXACT: single-strand DNA repair
*  EXACT: ssDNA repair

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
- ALKBH3 Q96Q83 EC:1.14.11.54
- FTO Q9C0B1 EC:1.14.11.53
- NEIL3 Q8TAT5 EC:4.2.99.18
- UNG (UNG2) P13051 EC:3.2.2.27

* **Any other information**: this term is required if the GO terms GO:0080111 DNA demethylation and GO:0035552 oxidative single-stranded DNA demethylation are being obsoleted. Also note I am assuming that GO:0006307 DNA dealkylation involved in DNA repair will be obsoleted.

**Comment by pgaudet** [comment]
Hi @RLovering 
It would be great to align to DNA repair pathways - 
- ALKBH3 Q96Q83: BP seems to be truly missing, something like 'reversal of alkylating DNA damage ? See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2262034/) 
- FTO Q9C0B1 EC:1.14.11.53: same as for ALKBH3
- NEIL3 Q8TAT5 is involved in GO:0036297 interstrand cross-link repair (does single-stranded make sense? 
- UNG (UNG2) P13051 EC:3.2.2.27is involved in base-excision repair (GO:0006284): I can create a 'single-strand' version of this pathway? 
- 
What do you think ? 

Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale

your suggestion seems very sensible. I am not sure how useful having a term for ssDNA mechanisms v just DNA mechanisms would be. Maybe this would just increase the number of terms unneccessarily. But some enzymes do seem to prefer ssDNA rather than dsDNA so maybe this is useful?

The article you found is very nice, I always try to get more recent articles in case there has been a change in the understanding. So all but one of the pathways in their Figure 1 are covered by GO terms:
(1) the direct reversal pathway, (2) the mismatch repair (MMR) pathway GO:0006298, (3) the nucleotide excision repair (NER) pathway, GO:0006283 (4) the base excision repair (BER) pathway GO:0006284, (5) the homologous recombination (HR) pathway, GO:0000725 (GO has terms for ss and ds repair here) and (6) the non-homologous end joining (NHEJ) pathway GO:0006303.

Note that the term GO:0006307 DNA dealkylation involved in DNA repair does exist, so perhaps the new term you suggest (reversal of alkylating DNA damage) is not needed? the term you suggest could be added as a synonym? It just wasn't clear that this term would be kept.

Therefore, I will associate the term GO:0006307 DNA dealkylation involved in DNA repair with the ALKBH3 and FTO - if you decide to remove this term presumably the annotations can be moved to 'reversal of alkylating DNA damage' if that is a new terms. And I will make sure the other proteins are associated with the terms you suggest.

Other than DNA repair other DNA modifications need to be put into context of the processes they contribute to.
We also need to link DNA methylation and demethylation with regulation of gene expression/epigenetics https://www.abcam.com/epigenetics/dna-methylation-and-demethylation : 'Active DNA demethylation occurs in a cycle, starting with 5mC and finishing with an unmodified C. 5mC is initially oxidized to 5-hydroxymethlcytosine (5hmC), which is further oxidized to 5-formylcytosine (5fC), and finally, this is oxidized once more to 5-carboxylcytosine (5caC). 5fC and 5caC can be removed from DNA by thymine DNA glycosylase (TDG) in combination with base excision repair (BER) to result in an unmodified C.'

Obviously demethylation pathway ends with BER but the repair was not to 'damaged DNA' but part of changing the epigenetics status of the DNA.

So for this there are: 
GO:0044027 negative regulation of gene expression via CpG island methylation 
GO:0044029 positive regulation of gene expression via CpG island demethylation
Although only 4 genes are associated with these terms, based on expt data, and I don't think any are demethylases. So looking at Wikipedia: https://en.wikipedia.org/wiki/DNA_demethylation and then the UniProt records and PubMed the following human genes need to be associated with the GO:0044029 positive regulation of gene expression via CpG island demethylation term:
TET1 Q8NFU7 - UniProt
OGG1 O15527 - https://pubmed.ncbi.nlm.nih.gov/35098021/
EGR1 P18146 - https://pubmed.ncbi.nlm.nih.gov/35098021/; https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6715719/
TET2 Q6N021 - UniProt; https://pubmed.ncbi.nlm.nih.gov/24315485/
TET3 O43151 - UniProt

Will also see if I can do these annotations easily too

Ruth

**Comment by RLovering** [comment]
PS for RNA repair is it worth having GO:0042245 RNA repair is_a child: RNA dealkylation involved in RNA repair? I haven't looked at other mechanisms of RNA repair but FTO is supposed to be involved in this process

**Comment by RLovering** [comment]
PPS I am leaving oxidative single-stranded DNA demethylation for now - waiting for you to confirm is ssDNA terms will be created

**Comment by RLovering** [comment]
Good point it might be difficult to decide, when curating, if the repair is ss or ds, but remember changing a modificated base is not a break repair. GO:0000012 single strand break repair already exists, probably needs the exact synonyms to be added:
Single-Strand Break Repair pathway 
SSBR pathway 

So some of the modified bases are methylated and may be demethylated -which are part of epigenetic modifications therefore not repair, others are modified due to damage. https://pubmed.ncbi.nlm.nih.gov/18775698/ and https://pubmed.ncbi.nlm.nih.gov/31981739/

**Comment by pgaudet** [comment]
@ValWood according to @colinlog, ChatGPT was a bit creative here, these pathways are for dsDNA, it is not clear that single-stranded DNA is repaired in cells, but it seems like people use this in assays, for some reason.

**Comment by pgaudet** [comment]
According to Colin, this is not physiological.

**Comment by MarijaOM** [comment]
Reactome does not show SSBR as an independent pathway but as a component of base excision repair (BER), nucleotide excision repair (NER) and mismatch repair (MMR) pathways. In all three cases, SSBs are enzymatically created either upon removal of damaged bases (BER) or in the process of excision of damaged (NER) or mismatched (MMR) nucleotides. This is followed by gap filling by DNA polymerases and, finally, ligation of the nick by DNA ligases. The combinations of endonucleases that create SSBs and DNA polymerases that fill in the gaps differ between BER, NER, and MMR. If there is an SSB with no additional damage to surrounding bases, it is likely just simply ligated, which on its own does not constitute a pathway. The involvement of DSBR mechanisms in SSBR is true only in the sense that a DSB is nothing more than two SSBs across each other in close proximity. In essence, different SSBR mechanisms exist as subpathways of other DNA repair pathways. When SSBs occur on their own, with no additional damage, is their sealing a physiological process or just a molecular function of DNA ligases?

**Comment by colinlog** [comment]
I'd say the DNA polymerisation and ligation catalytic steps are MFs within
each of these DNA repair processes (BER, MMS, NER).

What Pascale and I were trying to convey, is that although the cellular
reactants on which the enzymes catalyse reactions are formally speaking
single DNA strands, they are in fact base paired with a second antiparallel
complementary DNA strand. That is what was damged in the first place and
that is what the repair pathway products are. These are therefore double
strand DNA repair pathways.

It is not the case that two 'loose single strands get ligated' or that
3'OH group of a n unpaired single DNA strand is used to add nucleotides, as
can be seen when RNA polyadenylase or terminal transferases add adenosine
to the 3'end of a single strand nucleic acid polymers.

**Comment by pgaudet** [comment]
Thanks for the comments - my understanding is that we have all the terms that we need. Closing this one,
