### ISSUE TITLE
GO:0008422 has exo and endo children, but description is exo

### ISSUE THREAD

**Issue by Artoria2e5** [geneontology/go-ontology#26519]
The definition for GO:0008422 goes...
```
id: GO:0008422
name: beta-glucosidase activity
namespace: molecular_function
def: "Catalysis of the hydrolysis of terminal, non-reducing beta-D-glucose residues with release of beta-D-glucose." [EC:3.2.1.21, PMID:12594539]
```

But despite asking for "non-reducing terminal", it has a bunch of children with "endo" in their names, as is visible on the AmiGO tree. That seems unusual.
```
[is_a relation] GO:0033913 glucan endo-1,2-beta-glucosidase activity
[is_a relation] GO:0042973 glucan endo-1,3-beta-D-glucosidase activity
[is_a relation] GO:0052859 glucan endo-1,4-beta-glucosidase activity
[is_a relation] GO:0046557 glucan endo-1,6-beta-glucosidase activity
```

**Comment by pgaudet** [comment]
Dear @Artoria2e5 

Thanks for pointing out this error. I removed the terms from the incorrect parent class.

**Comment by pgaudet** [comment]
Obsolete [glucan endo-1,4-beta-glucosidase activity](http://purl.obolibrary.org/obo/GO_0052859)

Created by error, cross references EC:3.2.1.75, which is glucan endo-1,6-beta-glucosidase

Replace by [glucan 1,4-beta-glucosidase activity](http://purl.obolibrary.org/obo/GO_0031217)

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0052859 glucan endo-1,4-beta-glucosidase activity. The reason for obsoletion is that this term was created by mistake;  the reaction does not correspond  to the EC number to which it was associated (EC:3.2.1.75; glucan endo-1,6-beta-glucosidase). There are no annotations to this term; the only mapping was the incorrect EC. This term is not present in any subsets. 

You can comment on the ticket: 
https://github.com/geneontology/go-ontology/issues/26519

Thanks, Pascale
