### ISSUE TITLE
Update of: disruption of tissue in another organism   AND  NTR: Dermonecrosis in another organism   AND  some changes for GO:0044523

### ISSUE THREAD

**Issue by FJungo** [geneontology/go-ontology#26513]
Hello,
I wanted to suggest this new term : Necrosis in another organism
but it is similar to: GO:0141062; disruption of tissue in another organism

As a consequence, I suggest to use 
GO:0141062; disruption of tissue in another organism
and to keep its definition, but add new PMID

* Definition:
The disruption of a tissue of another organism, leading to damage or temporary subversion of that tissue.

* Reference, in format PMID:
(PMID:27416066, PMID:34346770, PMID:26355030, PMID:11895956 = to keep)
PMID:28194160 = to add

* Parent term(s): 
GO:0141060; disruption of anatomical structure in another organism 

* Children terms: 
GO:xxx; dermonecrosis in another organism (to create)
GO:0044521; ~muscle damage in another organism (has to be updated)

----------

* New term:
GO;xxx; Dermonecrosis in another organism

* Definition:
The disruption of the skin of another organism, leading to damage or temporary subversion of the skin.

* Reference, in format PMID:
PMID:28194160

* Parent term(s): 
GO:0141062; disruption of tissue in another organism 

* Children terms: 
no

--------

the term
GO:0044523; ~damage of muscle extracellular matrix in another organism

should be the child of both
GO:0044521; ~ muscle damage in another organism  (this relation is already indicated) AND 
GO:0141041; disruption of extracellular matrix of another organism (this relation has to be added)

* Reference, in format PMID:
PMID:21150580 (to keep), 
PMID:10620318 (to delete), 
PMID:20398688 (to add), 
PMID:33460638 (to add)

**Comment by pgaudet** [comment]
Obsolete GO:0141062 disruption of tissue in another organism - unnecessary grouping class.
