### ISSUE TITLE
Old gorel information propagates into ontology build (was "AmiGO does not display the current definition of biological_process")

### ISSUE THREAD

**Issue by addiehl** [geneontology/go-ontology#26516]
While working with a student today (@giacomodecolle), I discovered that AmiGO does not display the current definition of biological_process ([GO:0008150](https://amigo.geneontology.org/amigo/term/GO:0008150)).  The current definition of biological process resulted from a discussion [here](https://github.com/geneontology/go-ontology/issues/24968) as implemented by this [PR](https://github.com/geneontology/go-ontology/pull/25025) on February 27, 2023.

Oddly enough, QuickGO **does** display the current definition of biological process ([GO:0008150](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0008150)), and the term history shows that definition was changed on 2023-03-06.

At the bottom of the AmiGO page, it states "Last file loaded on 2023-10-10."  Perhaps this refers to the annotations and not the ontology, although I always thought it referred to both.  Nevertheless, it is of some concern that AmiGO is displaying an old definition of biological_process, and perhaps of other terms in BP.

Thanks, Alex

(in the old days, I would be concerned that this is a browser cache issue, but the old definition is shown on three different browsers on my computer, and on my student's computer, so it seems rather unlikely to be an issue on the client side)

**Comment by pgaudet** [comment]
@balhoff WHat's the status on this one? I dont know how to QC this. 

On AmiGO-staging, the definition of 'biological_process' looks OK.

Thanks, Pascale

**Comment by balhoff** [comment]
> On AmiGO-staging, the definition of 'biological_process' looks OK.

I think that's probably good then.
