### ISSUE TITLE
Obsoletion request: GO:0044736 acid-sensing ion channel activity & regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26520]
Dear all, 

The proposal has been made to obsolete GO:0044736 acid-sensing ion channel activity & its regulation children. The reason for obsoletion is that this activity represents a gene family with GO:0160128 pH-gated channel activity. 

Replacements: 
GO:0044736 acid-sensing ion channel activity >> GO:0160128 pH-gated channel activity

Consider:
GO:1901585 regulation of acid-sensing ion channel activity >>   GO:0099106 ion channel regulator activity
GO:1901586 negative regulation of acid-sensing ion channel activity >> GO:0008200 ion channel inhibitor activity
GO:1901587 positive regulation of acid-sensing ion channel activity  >> GO:0099103 channel activator activity (0 annotations). 

There are 9 annotations to these terms, see https://github.com/geneontology/go-annotation/issues/4849
by UniProt, MGI and FlyBase. 
There is one Reactome mapping. 
These terms are not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/26520

Thanks

**Comment by pgaudet** [comment]
Detailed review of the literature by @lbreuza : 

Searched for "proton-gated" in pubmed 292 results
https://pubmed.ncbi.nlm.nih.gov/?term=%22proton-gated%22&sort=date&page=3
Most of them concern ASICs. I checked ASICS activation mechanism and a few examples of other ‘proton-gated’ channels.
 
PMID: 35108041 - proton-activated chloride channel ASOR
 
The proton-activated chloride channel ASOR (TMEM206/PAC) permeates anions across cellular membranes in response to acidification, thereby enhancing acid-induced cell death and regulating endocytosis. The molecular mechanisms of pH-dependent control are not understood, in part because structural information for an activated conformation of ASOR is lacking. Here, we reconstitute function from purified protein and present a 3.1-Å-resolution cryo-electron microscopy structure of human ASOR at acidic pH in an activated conformation. The work contextualizes a previous acidic pH structure as a desensitized conformation. Combined with electrophysiological studies and high-resolution structures of resting and desensitized states, the work reveals mechanisms of proton sensing and ion pore gating. Clusters of extracellular acidic residues function as pH sensors and coalesce when protonated. Ensuing conformational changes induce metamorphosis of transmembrane helices to fashion an ion conduction pathway unique to the activated conformation. The studies identify a new paradigm of channel gating in this ubiquitous ion channel.
 
 
 
 
PMID: 34753824 - proton-gated bacterial potassium channel KcsA
"we examine how the prototypical, proton-gated bacterial potassium channel KcsA"
But what is indeed measure is activation by pH "The reconstituted channels were incubated at pHs between 7 and 4 (in the delay loop) for 320 ms, close to the time for maximal activity for each pH, and then tested for open channels using the initial slope of the fluorescence quench time course as a measure of activity ([Fig. 1A](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8609545/figure/fig01/); protocol in [SI Appendix, Fig. S2](https://www.pnas.org/lookup/suppl/doi:10.1073/pnas.2113229118/-/DCSupplemental)). The initial slope (Activity) is plotted as function of pH and fit with a standard Hill function yielding the pH at the midpoint of activation (pH0.5)  (….)"
 
PMID: 24344244  - ASICs activation mechanism
 
 
"Protonation controls ASIC1a activity via coordinated movements in multiple domains"
ASIC activity is due to protonation of critical residues that result in conformational changes and opening of the channel
 
Therefore the most commonly qualified proton-gated channel is simply pH-gated (protonation and not binding of H+).
 
PMID: 24167270 - GLIC
 
 
“we favor the notion that the structural model of the T25′A mutant represents the proton-bound closed-channel conformation” (…)
 
“We crystallized two loss-of-function mutants of GLIC at pH ∼4.0, a concentration of protons that elicits a nearly maximal current response from the wild-type channel (14), and hence, that is expected to keep the wild-type’s activation-relevant ionizable side chains (that is, those side chains whose pKa values increase upon opening) fully protonated. When expressed heterologously in HEK-293 cells, the two mutants displayed a much reduced closed ⇌ open equilibrium constant, to the extent that currents could not be elicited upon application of pH jumps.”
 
Another proton-gated channel as stated by authors that use indifferently proton-binding and protonation (in the text) and which is in fact a pH-gated channel
 
Conclusion : I could only find in the literature some examples of 'proton-gated' channels that open upon protonation of critical residues (not binding of a proton in a pocket). Proton-gated channels are therefore pH-gated channels.
I would suggest to remove the term GO:0044736 acid-sensing ion channel activity (it represents a protein family) OR move it as child of pH-gated activity as it is not strictly ‘ligand-bound’.

**Comment by pgaudet** [comment]
@raymond91105 
I am assigning you to make sure we dont have any conflicts in the ontology. Announcements have been sent, so you can proceed with this by the end of the week. 

Also, please add a comment on 'GO:0160128 pH-gated channel activity' to explain that while the term suggest this activity may be proton-gated, the mechanism of pH-gating for transporters is by protonation of specific residues in the protein, and not by H+ binding. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @deustp01 
I shoudl have said, this term was just created yesterday, it will take a few days to be available, depending on where you get the ontology from. Snapshot has not built since Nov 6th :(

**Comment by deustp01** [comment]
Now fixed - change will become visible in March 2024 release.

**Comment by raymond91125** [comment]
A Chemistry professor friend said:
"Going to your question, it is matter of semantics but yes, protonation (formation of a covalent bond) can be defined as proton binding, but not always proton binding (e.g. binding in a protein pocket) results in protonation (though only in few cases). Based on this consideration in my opinion I would say that pH-activated ion channels are 'ligand' activated."

**Comment by pgaudet** [comment]
hi @raymond91125 

if you think this is more appropriate as a ligand-gated channel please go ahead and move it, we just need to clearly explain what we mean. 

Also, based on what you write above, the synonym 'proton-gated ion channel activity' should be 'exact'. 

Thanks, Pascale
