### ISSUE TITLE
NTR: mRNA cap methyltransferase RNMT:RAMAC complex

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#26548]
Please provide as much information as you can: 

* **Suggested term label:**
mRNA cap methyltransferase RNMT:RAMAC complex

* **Definition (free text)**

A protein complex that consists of RAMAC and RNMT and is involved in mRNA cap methylation.

* **Reference, in format PMID:#######**
 22099306

* **Gene product name and ID to be annotated to this term**
RAMAC
RNMT

* **Parent term(s)**

methyltransferase complex

* **Any other information**

it looks different from the existing
mRNA cap methyltransferase complex

**Comment by raymond91125** [comment]
RNMT and RAMAC are both annotated with GO:0031533 mRNA cap methyltransferase complex. How is this new complex different? We would like to make the distinction clear.
@ValWood What do you think?

**Comment by Antonialock** [comment]
RAMAC is not a mRNA guanylyltransferase, it doesn't seem to have any
enzymatic activity ?

The def for mRNA cap methyltransferase complex says "A protein complex that
consists of an RNA 5' triphosphatase and a guanyl transferase "

**Comment by ValWood** [comment]
I haven't looked much at this but

1.
https://www.pombase.org/term_genes/GO:0006370
7-methylguanosine mRNA capping (GO:0006370)
is a mutistep process see
https://github.com/geneontology/go-ontology/issues/26464

Cap synthesis entails three enzymatic reactions: (i) the 5′ triphosphate end of the pre-mRNA is hydrolyzed to a diphosphate by RNA triphosphatase; (ii) the diphosphate RNA end is capped with GMP by RNA guanylyltransferase; and (iii) the GpppN cap is methylated by RNA (guanine-N7) methyltransferase ([1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1865056/#B1)).

2. RNMT is  the  RNA (guanine-N7) methyltransferase 

This paper seems to confirm
https://pubmed.ncbi.nlm.nih.gov/29719263/
mRNA Cap Methyltransferase, RNMT-RAM, Promotes RNA Pol II-Dependent Transcription

(note to self, I haven't annotated pcm1 to  mRNA cap methyltransferase complex  , only to P-TEFb-cap methyltransferase complex , possibly in error)

**Comment by ValWood** [comment]
3. Yes something is weird here, @Antonialock  is correct

mRNA cap methyltransferase complex (GO:0031533)

Definition | Parents
-- | --
A protein complex that consists of an RNA 5' triphosphatase and a guanyl transferase (Cet1p and Ceg1p in S. cerevisiae; Pct1 and Ceg1 in S. pombe) and is involved in mRNA capping. [PMID:10347220]

Definition	Parents
A protein complex that consists of an RNA 5' triphosphatase and a guanyl transferase (Cet1p and Ceg1p in S. cerevisiae; Pct1 and Ceg1 in S. pombe) and is involved in mRNA capping. [[PMID:10347220](https://www.pombase.org/reference/PMID:10347220)]

@sjm41  did you look at these recently?
Is this definition of mRNA cap methyltransferase complex
correct, or is it defined differently for yeast and metazoa

**Comment by ValWood** [comment]
This looks useful
https://www.cell.com/trends/biochemical-sciences/fulltext/S0968-0004(19)30002-7?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0968000419300027%3Fshowall%3Dtrue


and shows how the complexes are recruited to the pol II CTD, the problem is that there are multiple complexes that could be described as mRNA CAP methyltransferases. These need to be disambiguated. I would name them after the principal activity with  "mRNA cap methyltransferase" as a related synonym

<img width="695" alt="Screenshot 2023-12-05 at 08 29 56" src="https://github.com/geneontology/go-ontology/assets/7359272/d3dfd376-5580-401d-95c5-9ae28201c5bd">


@pgaudet

**Comment by pgaudet** [comment]
Hi @ValWood - I see you tagged me - how can I help?

**Comment by ValWood** [comment]
I wondered if you had any input, but probably @raymond91125  can take it from here. It seems the existing term labels and defs  just need to be more precise.

**Comment by raymond91125** [comment]
To summarize:
1. For mRNA capping, there are two activities RNA guanylyltransferase and 5' phospatase encoded by a single gene in vertebrates (RNGTT), worm (cel-1), and fly (mRNA-cap), but by two genes in the yeasts.
2. For mRNA cap methylation in mammals, there is a complex of RNA guanine-7 methyltransferase (RNMT) and RNA guanine-7 methyltransferase activating subunit (RAMAC).

**Comment by ValWood** [comment]
1. I see ceg1/pct1, it is a single subunit in human. I didn't spot that.

2. mRNA (guanine-N7) methyltransferase complex is  an exact synonym of mRNA cap methyltransferase complex (GO:0031533), the names could just be swapped.

3. Functionally RNMT:RAMAC is  mRNA (guanine-N7) methyltransferase complex, just that in higher eukaryotes there is an additional regulatory subunit. in GO we would not create a separate complex for that, but make [RNMT:RAMAC complex](https://github.com/geneontology/go-ontology/issues/26548#top) a narrow synonym, and adjust the definition to say there is an additional subunit in human.
(possibly RAM is present in yeast but with sequence similarity is low. I' have a look for it).

**Comment by ValWood** [comment]
I'm also not sure which term we should be using for the 

mRNA guanylyltransferase activity here.
PomBase have used GO:0004484  mRNA guanylyltransferase activity
but that is  defined
Catalysis of the reaction: GTP + (5')pp-Pur-mRNA = diphosphate + G(5')ppp-Pur-mRNA; G(5')ppp-Pur-mRNA is mRNA containing a guanosine residue linked 5' through three phosphates to the 5' position of the terminal residue.

and so is incorrect for RNMT?

**Comment by ValWood** [comment]
deleted last comment

**Comment by raymond91125** [comment]
[Term]
id: GO:0160130
name: mRNA cap methyltransferase RNMT:RAMAC complex
namespace: cellular_component
def: "A protein complex that consists of RNA guanine-7 methyltransferase (RNMT) and RNA guanine-7 methyltransferase activating subunit (RAMAC) and is involved in mRNA cap methylation." [PMID:22099306]
is_a: GO:0034708 ! methyltransferase complex
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26548" xsd:anyURI
created_by: rynl
creation_date: 2023-12-08T01:33:31Z

**Comment by raymond91125** [comment]
@ValWood I am now quite confused. I renamed GO:0031533 to "mRNA capping enzyme complex". Is this not correct? That's what the definition says. Therefore, GO:00315333 is not "mRNA cap methyltransferase complex", nor "mRNA (guanine-N7) methyltransferase complex" 

What it is now:
[Term]
id: GO:0031533
name: mRNA capping enzyme complex
def: "A protein complex that consists of an RNA 5' triphosphatase and a guanyl transferase (Cet1p and Ceg1p in S. cerevisiae; Pct1 and Ceg1 in S. pombe) and is involved in mRNA capping." [GOC:vw, PMID:10347220, PMID:12455993, PMID:9345280]

**Comment by raymond91125** [comment]
@ValWood Are you saying that this new term should not be made?
> [Term] 
> id: GO:0160130 
> name: mRNA cap methyltransferase RNMT:RAMAC complex 
> namespace: cellular_component 
> def: "A protein complex that consists of RNA guanine-7 methyltransferase (RNMT) and RNA guanine-7 methyltransferase activating subunit (RAMAC) and is involved in mRNA cap methylation." [PMID:22099306] 
> is_a: GO:0034708 ! methyltransferase complex 
> property_value: term_tracker_item "#26548" xsd:anyURI 
> created_by: rynl 
> creation_date: 2023-12-08T01:33:31Z

**Comment by ValWood** [comment]
Hi  @raymond91125  I think this term is fine. The pombe and S. cerevisiae RNMT are single subunit. I suspect that is because we have not detected RAMAC yet. It isn't very conserved.

I agree that the name of  GO:0031533  is confusing and I agree it should not mention methyltransferase.  I think this is a conflation because it is involved in methyl cap formation. In fact, in fission yeast these 2 enzymes do not even form a complex....they seem to be independent.

**Comment by raymond91125** [comment]
Thanks, @ValWood

**Comment by Antonialock** [comment]
@raymond91125 Should this term be available now? I cannot see it in amigo? Thanks

**Comment by raymond91125** [comment]
Very weird. It appears that the created term has not gotten in although the git log says it did.
https://github.com/geneontology/go-ontology/pull/26604/commits/1a60a0930416f7b029c86756c01d7f27666d503d

**Comment by raymond91125** [comment]
Added back. Thanks for the alert. @Antonialock
