### ISSUE TITLE
NTR:  FMRP-CYFIP1 Complex

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#26546]
Please provide as much information as you can: 

* **Suggested term label:**

 FMRP-CYFIP1 Complex

* **Definition (free text)**

A protein complex that inhibits translation initiation by binding to the eIF4F complex. It consists of FMRP and CYFIP1. 

* **Reference, in format PMID:#######**
 18805096

* **Gene product name and ID to be annotated to this term**

 FMRP-CYFIP1

* **Parent term(s)**
intracellular protein-containing complex ?

![image](https://github.com/geneontology/go-ontology/assets/12727506/4b09846c-c588-4028-a61e-3e7b565dddf6)

**Comment by raymond91125** [comment]
Apologies for the delay.

+[Term]
+id: GO:0160209
+name: FMRP-CYFIP1 complex
+namespace: cellular_component
+def: "A protein-containing complex that contains the fragile X mental retardation protein (FMRP) and cytoplasmic FMRP Interacting protein 1 (CYIFIP1), and is capable of inhibiting translation initiation by binding to the eIF4F complex." [PMID:18805096, PMID:28183735]
+is_a: GO:0140535 ! intracellular protein-containing complex
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26546" xsd:anyURI
+created_by: rynl
+creation_date: 2024-08-26T23:29:42Z
