### ISSUE TITLE
Change electron transfer activity parentage and definition

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#26572]
Hi,
I would suggest to review the parentage and definition of the following term : 
GO:0009055  electron transfer activity
Ferredoxins and cytochromes are proteins with an electron transfer activity, but these are not enzymes/oxidoreductases.
CYGB, for instance, is part of an electron transfer chain that result in activation of cytoglobin (PubMed=28671819), through its electron transfer activity. If "Any molecular entity that serves as an electron acceptor and electron donor in an electron transport chain. An electron transport chain is a process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors" applies, "to generate a transmembrane electrochemical gradient" does not. Moreover, it is not an enzyme, so the parent term GO:0016491  oxidoreductase activity does not apply as well. 
I add @kaxelsen to the discussion as he suggested me not to use that term.
Best, Lionel

**Comment by pgaudet** [comment]
- moved term directly under molecular_function
- removed comment that it only applies to electron transport chain 
- fixed definition to  "A molecular function in which a molecular entity that serves as an electron acceptor and an electron donor during a chemical reaction or in an electron transport chain. Ferredoxins and cytochromes mediate electron transfer in a range of metabolic reactions. An electron transport chain is a process in which a series of electron carriers operate together to transfer electrons from donors to any of several different terminal electron acceptors to generate a transmembrane electrochemical gradient." [Wikipedia:Electron_transfer]

@lbreuza 
please let me know if this can be improved further. 

Thanks, 
Pascale
