### ISSUE TITLE
NTR: extracellular defense response

### ISSUE THREAD

**Issue by pfey03** [geneontology/go-ontology#26590]
Please provide as much information as you can: 

* **Suggested term label:**
extracellular defense response

* **Definition (free text)**
Excreted proteins with bacteriolytic activity to destroy pathogenic bacteria extracellular.

* **Reference, in format PMID:
* PMID:38017607

* **Gene product name and ID to be annotated to this term**
noxA / DDB_G0289653
aplA / DDB_G0284043

* **Parent term(s)*
* GO:0006968 cellular defense response
* or GO:0006952 defense response

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
* extracellular lysis

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
* It's know that even human has extracellular killing of bacteria but it hasn't been sudied much. In Dicty they see in this paper when Pseudomonas aeruginosa comes near Dicty cells in majority of cases they are extracellular killed. Only 12% are internalized and kil2 / DDB_G0279183 is neccessary to kill them in phagocytes efficiently.

**Comment by pgaudet** [comment]
Hi @pfey03 

This is mixing a BP and a CC. How about using 'GO:0031640 killing of cells of another organism' + CC = extracellular; would that work? 

Thanks, Pascale

**Comment by pfey03** [comment]
Hi @pgaudet Can I link then the two annotations? I will check in P2GO how to link them best and write it here.

Thanks for giving me that killing term.
Petra

**Comment by vanaukenk** [comment]
I'm interested more generally in how we want to annotate processes like this.

We seem to have several potential aspects of classification, and corresponding terms, in the ontology:

where (extracellular in this case)
what (defense response, in this case to a Gram negative bacterium)
how (cell killing seemingly by different mechanisms?)

It'd be helpful to have a consistent way to capture this information.

**Comment by pfey03** [comment]
I have annotated for noxA
'GO:0031640 killing of cells of another organism as main term
part_of cellular defense response
occurs_in extracellular region

I also need to annotate other genes
