### ISSUE TITLE
NTR: [Sequence-Specific RNA Reader Activity]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#26603]
Please provide as much information as you can: 

* **Suggested term label:**
Sequence-Specific RNA Reader Activity

* **Definition (free text)**
A molecular function characterized by the capacity to selectively recognize and interact with RNA molecules in a sequence-specific manner. Entities possessing this activity typically exhibit discerning binding preferences for specific nucleotide sequences within RNA molecules, enabling the identification and engagement of distinct RNA motifs or structural elements. This function is integral to various biological processes, including RNA processing, transport, and regulatory mechanisms, contributing to the specificity and precision of cellular RNA-related activities.

* **Reference, in format PMID:#######**
PMID:17036044, PMID:14749727

* **Gene product name and ID to be annotated to this term**
CPSF4, SRSF3

* **Parent term(s)**
 GO:0140517   protein-RNA adaptor activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
tagging myself to update some annotations @ValWood

**Comment by raymond91125** [comment]
Should this term be named "sequence-specific RNA binding", in a way similar to GO:0043565 sequence-specific DNA binding? 
PMID:17036044: "The sequence-specific RNA-binding proteins SRp20 and 9G8 are the smallest members of the serine- and arginine-rich (SR) protein family, well known for their role in splicing".

**Comment by pgaudet** [comment]
Hi @raymond91125 

We want to make these clearer functions than just 'binding', so 'reader' is correct. A larger refactoring will be to rename and move 'modified histone binding' terms to 'histone readers (GO:0070577 lysine-acetylated histone binding, GO:0035064 methylated histone binding, GO:0106153 phosphorylated histone binding, GO:0061649 ubiquitin modification-dependent histone binding ). So, this new term label is in agreement with this way of representing the functions of these proteins.

**Comment by ValWood** [comment]
I think I agree with @raymond91125  here. Do these publications refer to these protein RNA adaptors as readers?
I ask because a histone reader is a bit different. The readers don't read sequence, they read **modifications** (are also referred to as PTM readers), and so they are changing over time and **context dependent**.
I would say this sequence -specific recognition shouldn't be confused with a reader and 
"protein-RNA sequence-specific adaptor" might be a better label?

**Comment by raymond91125** [comment]
> Hi @raymond91125
> 
> We want to make these clearer functions than just 'binding', so 'reader' is correct. A larger refactoring will be to rename and move 'modified histone binding' terms to 'histone readers (GO:0070577 lysine-acetylated histone binding, GO:0035064 methylated histone binding, GO:0106153 phosphorylated histone binding, GO:0061649 ubiquitin modification-dependent histone binding ). So, this new term label is in agreement with this way of representing the functions of these proteins.

1. Are we also planning to change "sequence-specific DNA binding" to "sequence-specific DNA reader activity"? 
2. The PMID references don't mention "reader".
3. The histone readers are used in the context of writers and erasers so that is a bit different. There is parallel m6A RNA methylation reader/writer/eraser PMID:24662220.

**Comment by pgaudet** [comment]
Hi both, 

Thanks for the feedback. Discussing with @lbreuza, @ValWood 's suggestion to label this term "protein-RNA sequence-specific adaptor"  seems appropriate. 

It also clarifies the definition of 'reader' to mean a modified residue. 

Thanks, Pascale

**Comment by ValWood** [comment]
I have also only seen reader used when multiple different modifications can apply combinatorially  (for instance in the CTD code for polymerase I , or Spt5, or the histone code). I've never seen it used more generally when a phosphorylated residue creates a binding site for a binding partner.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160134
+name: protein-RNA sequence-specific adaptor activity
+namespace: molecular_function
+def: "A protein adaptor activity characterized by the capacity to selectively recognize and interact with RNA molecules in a sequence-specific manner. Entities possessing this activity typically exhibit discerning binding preferences for specific nucleotide sequences within RNA molecules, enabling the identification and engagement of distinct RNA motifs or structural elements. This function is integral to various biological processes, including RNA processing, transport, and regulatory mechanisms, contributing to the specificity and precision of cellular RNA-related activities." [PMID:14749727, PMID:17036044]
+is_a: GO:0140517 ! protein-RNA adaptor activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26603" xsd:anyURI
+created_by: rynl
+creation_date: 2023-12-14T23:39:47Z
