### ISSUE TITLE
NTR: bicarbonate channel activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#26601]
Please provide as much information as you can: 

* **Suggested term label:**
bicarbonate channel activity

* **Definition (free text)**
Enables the facilitated diffusion of a Bicarbonate (by an energy-independent process) involving passage through a transmembrane aqueous pore or channel without evidence for a carrier-mediated mechanism. 

* **Reference, in format PMID:18400985
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**

GO:0015267 channel activity
* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. [Rhea:28695]
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160133
+name: bicarbonate channel activity
+namespace: molecular_function
+def: "Enables the facilitated diffusion of a bicarbonate (by an energy-independent process) involving passage through a transmembrane aqueous pore or channel without evidence for a carrier-mediated mechanism." [PMID:18400985]
+intersection_of: GO:0015267 ! channel activity
+intersection_of: has_primary_input CHEBI:17544 ! hydrogencarbonate
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26601" xsd:anyURI
+created_by: rynl
+creation_date: 2023-12-13T00:09:44Z
