### ISSUE TITLE
Query : difference between GO:0071507 pheromone response MAPK cascade and GO:0010969 regulation of pheromone-dependent signal transduction involved in conjugation with cellular fusion ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26612]
Hi @srengel @jlewsmith 

Are these two term representing the same pathway? 

GO:0010969 regulation of pheromone-dependent signal transduction involved in conjugation with cellular fusion 
GO:0071507 pheromone response MAPK cascade

Thanks, Pascale

**Comment by srengel** [comment]
this may well be the same thing, but i need to look around a bit and confer with other SGD peeps to be sure.

**Comment by robnash** [comment]
I consider GO:0071507 pheromone response MAPK cascade to be part of GO:0000750 pheromone-dependent signal transduction involved in conjugation with cellular fusion. If the idea is to be able to annotate MAPK cascades independently, especially if they are shared between signaling transduction cascades and also be able to tether these MAPK cascades to a larger pathway then both terms are useful. 

![Ancestor chart for GO_0071507 and GO_0000750](https://github.com/geneontology/go-ontology/assets/12737663/7b62c048-2603-403c-b126-18830412da52)


If the idea to simplify the MAPK terms (especially if components are shared), then I suppose an annotation to GO:0000165 MAPK cascade, as part of GO:0000750 pheromone-dependent signal transduction involved in conjugation with cellular fusion could work.

**Comment by pgaudet** [comment]
Check Fig.1 in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2031910/

**Comment by pgaudet** [comment]
Updated definition: GO:0071507 pheromone response MAPK cascade 
A MAPK cascade containing at least the Fus3 MAP kinase. It starts with the activation of Ste20, a MAP4K, which activates Ste11, a MAP3K, which in turn activate Ste7, a MAP2K, which activates Fus3. The kinases in each tier phosphorylate and activate the kinases in the downstream tier. This MAPK cascade is triggered by a pheromone activating its G protein-coupled receptor, and results in cellular responses that lead to conjugation with cellular fusion.

**Comment by pgaudet** [comment]
For the cassettes work, I only updated the definition of  GO:0071507 pheromone response MAPK cascade. 

There are other tickets dealing with the other terms
https://github.com/geneontology/go-ontology/issues/20417
https://github.com/geneontology/go-ontology/issues/20309

Thanks, Pascale
