### ISSUE TITLE
NTR: symbiont-mediated activation of host T-cells 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26638]
Please provide as much information as you can: 

* **Suggested term label:**
symbiont-mediated activation of host T-cells

* **Definition (free text)**

* **Reference, in format PMID:#######**
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
[perturbation of host T-cell mediated immune response](http://purl.obolibrary.org/obo/GO_0052156) ??? the activation of the T-cells is a side-effect

@genegodbold please provide a definition and some references

**Comment by genegodbold** [comment]
Hey Pascale, for the title, I think it should be "symbiont-mediated NONSPECIFIC activation of host T-cells" to distinguish this process. This term is intended for annotation of bacterial **superantigens**. Superantigens bind major histocompatibility complex class II molecules (MHC-II) and T-cell receptors (TCR) of the host in a nonconventional manner, inducing T-cell activation that leads to production of cytokines such as tumor necrosis factor and interleukin-2, which can generate acute toxic shock. 
- **Staphylococcal enterotoxin G** (EntG; SEG)--also staphylococcal enterotoxins I, L, M, N, O, and U: Examination of SEG in mice found that murine Vbeta8.2 cells were strongly stimulated when compared to other staphylococcal superantigens of the SEB subfamily. Analysis of the SEG crystal structure found that it has an affinity for those those murine T cells that is 40-100 -fold greater than that of other superantigens of the SEB subfamily [PMID:17427250]. The group of superantigens with the highest prevalence is the so-called enterotoxin gene cluster (egc) which includes SEG, SEI, SEM, SELN, SELO and SELU. The proteins are produced in very low amounts. Recombinant proteins were generated and compared in their ability to activate T cells compared to the canonical staphylococcal superantigen, SEB. SEB could activate T cells and induce proliferation of human peripheral blood  monocytes at concentrations as low as **_1 picogram/mL_**. SEI and SELN could induce proliferation at a concentration as low as 0.1 picograms/ml while SEG and SELM showed potency down to a concentration of 0.1 nanogram/ml [PMID:27801832]. 
- **Staphylococcal enterotoxin I** (SEI): Recombinant SEI was lethal to rabbits when administered orally at a dose of 10 ng [PMID:27801832]. 
- Staphylococcal enterotoxin M** (SEM): When a house musk shrew was given an intraperitoneal injection (IP) of 100, 500, or 1000 micrograms of purified SEM in 0.1 molar phosphate-buffered saline, 9 of 18 animals vomited within between 18 and 117 minutes. The great majority had multiple emetic episodes from the single injection. The proportion of animals vomiting did not vary with the dose and the timing did not appear dependent on the dose [PMID:28042656]. When staphylococcal enterotoxin M was administered nasogastrally to cynomolgus monkeys at a dose of 100 micrograms per kilogram, it induced an emetic reaction in one of seven monkeys within 1.9 hours. Three vomiting events were observed for that monkey  [PMID:23876808].
- **Staphylococcal enterotoxin-like toxin X** (SelX): SelX is a classical superantigen that exhibits T-cell activation in a Vβ-specific manner, and contributes to the pathogenesis of necrotizing pneumonia. SelX can stimulate T-cell proliferation, thereby behaving as a superantigen [PMID:28880920].
- **Streptococcal superantigen SpeA**: The best characterized superantigens belong to the pyrogenic family. These include streptococcal superantigen, and the streptococcal pyrogenic toxins A, C, G, H, I, J, K, L, M, SmeZ, and SSA. All of these are capable of inducing toxic shock syndrome and share a common structure [PMID:14620148]. Superantigens are potent inducers of CD8+ T cells which produce the regulatory cytokine IL-10 [PMID:22043981]. The classic superantigen characteristic is its ability to cause an expansion of T lymphocyte populations expressing particular TCR Vbeta chains [PMID:11544350]. Superantigens can cause a massive and lethal reaction of the host immune system [PMID:12679262].

**Comment by addiehl** [comment]
+1 to Gene's comment about the term name.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141128
+name: symbiont-mediated non-specific activation of host T-cells
+namespace: biological_process
+def: "A process by which a symbiont superantigen elicits a strong immune response by activating a large number of T cells in a non-specific manner. Unlike conventional antigens, which activate T cells by interacting with specific receptors on the surface of these cells, superantigens can stimulate T cells by binding to regions outside the antigen-binding site. Superantigens can activate a large proportion of T cells, leading to an exaggerated immune response. This excessive activation can result in the release of a large amount of cytokines such as tumor necrosis factor and interleukin-2. The massive cytokine release can lead to an acute toxic shock, causing symptoms such as fever and organ damage." [PMID:12679262, PMID:17427250, PMID:28880920]
+synonym: "symbiont-mediated nonspecific activation of host T-cells" EXACT []
+is_a: GO:0044068 ! modulation by symbiont of host cellular process
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26638" xsd:anyURI
+created_by: pg
+creation_date: 2023-12-14T07:58:16Z
