### ISSUE TITLE
NTR: [Phospholipase C-activating endothelin receptor signaling pathway]

### ISSUE THREAD

**Issue by MariaLivia** [geneontology/go-ontology#26635]
* **Suggested term label:**
Phospholipase C-activating endothelin receptor signaling pathway

* **Definition (free text)**
A phospholipase C-activating receptor G protein-coupled receptor signaling pathway initiated by endothelin 1 binding to its receptor on the surface of a target cell, and ending with the regulation of a downstream cellular process, e.g. transcription. 

* **Reference, in format PMID:#######**
PMID:35284927

* **Gene product name and ID to be annotated to this term**
PLCB4 Q15147

* **Parent term(s)**
GO:0007200 phospholipase C-activating G protein-coupled receptor signaling pathway

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160135
+name: phospholipase C-activating endothelin receptor signaling pathway
+namespace: biological_process
+def: "A phospholipase C-activating receptor G protein-coupled receptor signaling pathway initiated by endothelin binding to its receptor on the surface of a target cell, and ending with the regulation of a downstream cellular process, e.g. transcription." [PMID:35284927]
+is_a: GO:0007200 ! phospholipase C-activating G protein-coupled receptor signaling pathway
is_a: GO:0086100 ! endothelin receptor signaling pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26635" xsd:anyURI
+created_by: rynl
+creation_date: 2023-12-15T00:15:01Z

**Comment by pgaudet** [comment]
Hi @raymond91125 @MariaLivia 
Sorry I just now noticed that we had 'GO:0086100 ! endothelin receptor signaling pathway' - looking at annotations, it seems like the only pathway for endothelin is a GPCR; is this correct? When I look at annotations of endothelin receptors they are all G protein coupled. In this case we could have changed GO:0086100 ! endothelin receptor signaling pathway'


Thanks, Pascale

**Comment by MariaLivia** [comment]
Hi @pgaudet and @raymond91125,
I was wondering if endothelin receptor signaling goes only through the activation of phospholipase C. Quickly checking in PubMed I've found this old review https://pubmed.ncbi.nlm.nih.gov/16434725/. According to Fig.2 endothelin binding to its receptor activates at least four different G protein pathways, including the one activating phospholipase C.
Cheers, Livia

**Comment by raymond91125** [comment]
![image](https://github.com/geneontology/go-ontology/assets/619520/4d37f091-eb08-4cd5-bb53-8c3ce625fb62)
