### ISSUE TITLE
Add EC xrefs to DNA 5'-3' DNA exonuclease activity terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26645]
EC has these four main DNA exonuclease terms:
EC:3.1.11.1
Exonucleolytic cleavage in the 3'- to 5'-direction to yield nucleoside 5'-phosphates. Preference for single-stranded DNA.
EC:3.1.11.2
Exonucleolytic cleavage in the 3'- to 5'-direction to yield nucleoside 5'-phosphates. Preference for double-stranded DNA.
EC:3.1.11.3
Exonucleolytic cleavage in the 5'- to 3'-direction to yield nucleoside 5'-phosphates. Preference for double-stranded DNA.
EC:3.1.11.4
Exonucleolytic cleavage in the 5'- to 3'-direction to yield nucleoside 5'-phosphates. Preference for single-stranded DNA.

- [x] I think EC:3.1.11.3 should be added as xref to GO:0051908
- [x] GO:0051908 also needs its name updating to match sister terms, ie 'double-stranded DNA 5'-3' DNA exonuclease activity'

id: GO:0051908
name: double-stranded DNA 5'-3' exodeoxyribonuclease activity
namespace: molecular_function
def: "Catalysis of the sequential cleavage of mononucleotides from a free 5' terminus of a double-stranded DNA molecule." [GOC:ai]
synonym: "double-stranded DNA specific 5'-3' exodeoxyribonuclease activity" RELATED []
is_a: GO:0008309 ! double-stranded DNA exodeoxyribonuclease activity
is_a: GO:0035312 ! 5'-3' DNA exonuclease activity

- [x] And EC:3.1.11.4 should be added as xref to GO:0045145:

id: GO:0045145
name: single-stranded DNA 5'-3' DNA exonuclease activity
def: "Catalysis of the sequential cleavage of nucleotides (such as mononucleotides or dinucleotides) from a free 5' terminus of a single-stranded DNA molecule." [GOC:ai, GOC:elh, PMID:20086101]
synonym: "single-stranded DNA specific 5'-3' exodeoxyribonuclease activity" RELATED []
synonym: "ssDNA-specific 5'-3' exodeoxyribonuclease activity" RELATED [GOC:mah]
is_a: GO:0008297 ! single-stranded DNA exodeoxyribonuclease activity
is_a: GO:0035312 ! 5'-3' DNA exonuclease activity

Consistent with above, EC:3.1.11.1 and EC:3.1.11.2 are already xrefs on the following two GO terms:

id: GO:0008310
name: single-stranded DNA 3'-5' DNA exonuclease activity
def: "Catalysis of the sequential cleavage of mononucleotides from a free 3' terminus of a single-stranded DNA molecule." [GOC:mah, PMID:22562358]
synonym: "exonuclease I activity" NARROW []
synonym: "single-stranded DNA 3'-5' exodeoxyribonuclease activity" EXACT []
synonym: "single-stranded DNA specific 3'-5' exodeoxyribonuclease activity" RELATED []
synonym: "ssDNA-specific 3'-5' exodeoxyribonuclease activity" RELATED [GOC:mah]
xref: EC:3.1.11.1
xref: MetaCyc:3.1.11.1-RXN
is_a: GO:0008296 ! 3'-5'-DNA exonuclease activity
is_a: GO:0008297 ! single-stranded DNA exodeoxyribonuclease activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24408" xsd:anyURI

id: GO:0008311
name: double-stranded DNA 3'-5' DNA exonuclease activity
def: "Catalysis of the sequential cleavage of mononucleotides from a free 3' terminus of a double-stranded DNA molecule." [GOC:mah, PMID:22562358]
synonym: "double-stranded DNA 3'-5' exodeoxyribonuclease activity" EXACT []
synonym: "double-stranded DNA specific 3'-5' exodeoxyribonuclease activity" RELATED []
synonym: "exonuclease III activity" NARROW []
synonym: "exoribonuclease III activity" NARROW []
xref: EC:3.1.11.2
xref: MetaCyc:3.1.11.2-RXN
is_a: GO:0008296 ! 3'-5'-DNA exonuclease activity
is_a: GO:0008309 ! double-stranded DNA exodeoxyribonuclease activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24408" xsd:anyURI

Sound OK to you @pgaudet ?

**Comment by pgaudet** [comment]
Yes, this seems fine, thanks !
