### ISSUE TITLE
Add EC/RHEA xrefs to GO:0052642 lysophosphatidic acid phosphatase activity (?)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26658]
id: GO:0052642
name: lysophosphatidic acid phosphatase activity
def: "Catalysis of the reaction: lysophosphatidic acid + H2O = phosphate + monoacylglycerol." [PMID:20045079, PMID:7966317]
synonym: "LPA phosphatase activity" EXACT []
synonym: "lysophosphatidate phosphatase activity" EXACT []
is_a: GO:0016791 ! phosphatase activity

I think this is the same as https://enzyme.expasy.org/EC/3.1.3.106 / https://www.rhea-db.org/rhea/33155:
EC:3.1.3.106
Name:2-lysophosphatidate phosphatase
Alt_name:1-acyl-sn-glycerol 3-phosphatase
Reaction:a 1-acyl-sn-glycero-3-phosphate + H2O <=> a 1-acyl-sn-glycerol + phosphate

Would you agree @kaxelsen @pgaudet ?

I see UniProt has Q9SRQ6 (arabidopsis NPC3) annotated to EC:3.1.3.106/RHEA:33155 and GO:0052642 from PMID: 20045079

**Comment by pgaudet** [comment]
Looks ok to me

**Comment by sjm41** [comment]
OK, thanks.
From the ontology call the other day, it sounded like I need to add 'activity' to the end of the EC names when adding them as synonyms??

**Comment by pgaudet** [comment]
Yes, this is how we have been doing this, let's stay consistent. Hopefully the future script to maintain the synonyms up to date can fix all these to match the EC names.
