### ISSUE TITLE
NTR: histone H3K79 mono and dimethyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26657]
Please provide as much information as you can: 

* **Suggested term label:**
histone H3K79 monomethyltransferase activity
histone H3K79 dimethyltransferase activity

* **Definition (free text)**
Catalysis of the reaction: L-lysyl79-[histone H3] + S-adenosyl-L-methionine = H+ + N6-methyl-L-lysyl79-[histone H3] + S-adenosyl-L-homocysteine

Catalysis of the reaction: L-lysyl79-[histone H3] + 2 S-adenosyl-L-methionine = 2H+ + N6,N6-methyl-L-lysyl79-[histone H3] + 2 S-adenosyl-L-homocysteine

* **Reference, in format PMID:#######**
PMID: 15371351, PMID: 14732680

* **Gene product name and ID to be annotated to this term**
Fly gpp (FBgn0264495, Q8INR6)

* **Parent term(s)**
histone H3K79 methyltransferase activity GO:0031151

* **Cross-references**
histone H3K79 monomethyltransferase activity = RHEA:60332 (no EC)
histone H3K79 dimethyltransferase activity - no RHEA/EC for this

* **Other information**
Quoting from PMID: 15371351 :
In yeast, K79 is mono-, di-, and trimethylated and Dot1 is responsible for all three modifications ([Feng et al. 2002]); [van Leeuwen et al. 2002])....However, in fly tissue culture cells, the mono- and di- but not the trimethylated form is observed ([Mckittrick et al. 2004]). Since database searches indicate that gpp is the only fly Dot1 homolog, it should also be the sole fly protein in this class that methylates histone H3 on K79. Consistent with this suggestion, discs and other tissues isolated from gpp mutant larvae have little if any H3 mono- or dimethyl K79.

**Comment by sjm41** [comment]
@pgaudet OK if I go ahead and make these two terms?

**Comment by pgaudet** [comment]
Yes!

**Comment by sjm41** [comment]
+[Term]
+id: GO:0120505
+name: histone H3K79 monomethyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-lysyl79-[histone H3] + S-adenosyl-L-methionine = H+ + N6-methyl-L-lysyl79-[histone H3] + S-adenosyl-L-homocysteine." [PMID:14732680, PMID:15371351, RHEA:60332]
+xref: RHEA:60332
+is_a: GO:0031151 ! histone H3K79 methyltransferase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26657" xsd:anyURI
+created_by: sjm
+creation_date: 2024-04-30T12:26:45Z
+
+[Term]
+id: GO:0120506
+name: histone H3K79 dimethyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-lysyl79-[histone H3] + 2 S-adenosyl-L-methionine = 2H+ + N6,N6-methyl-L-lysyl79-[histone H3] + 2 S-adenosyl-L-homocysteine." [PMID:14732680, PMID:15371351]
+is_a: GO:0031151 ! histone H3K79 methyltransferase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26657" xsd:anyURI
+created_by: sjm
+creation_date: 2024-04-30T12:30:23Z
+
