### ISSUE TITLE
Obsoletion request: GO:0039668 viral entry into host cell via pilus basal pore and GO:0039669 viral entry into host cell via pilus retraction and membrane fusion

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26669]
GO:0039667 viral entry into host cell via pilus retraction, 
GO:0039668 viral entry into host cell via pilus basal pore  > 4 annotations CAFA, will be remapped
GO:0039669 viral entry into host cell via pilus retraction and membrane fusion > 0 annotations

are more granular than the ViralZone term. Replace by  
[virion attachment to host cell pilus](http://purl.obolibrary.org/obo/GO_0039666)
which corresponds to the VZ term, https://viralzone.expasy.org/981

**Comment by pgaudet** [comment]
Obsolete GO:0035635 entry of bacterium into host cell >> 10 manual annotations

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following 'entry into host cell terms: 
GO:0039667 viral entry into host cell via pilus retraction > Replace by GO:0039666 virion attachment to host cell pilus 
GO:0039668 viral entry into host cell via pilus basal pore > Replace by GO:0039666 virion attachment to host cell pilus
GO:0039669 viral entry into host cell via pilus retraction and membrane fusion > Replace by GO:0039666 virion attachment to host cell pilus
GO:0035635 entry of bacterium into host cell > replace by GO:0046718 symbiont entry into host cell
GO:0039707 virus-mediated pore formation in host cell membrane >  replace by GO:0044694 symbiont entry into host cell via pore formation in plasma membrane


There are 16 EXP annotations, 2 Reactome mappings, 6 InterPro and 1 HAMAP mapping, see https://docs.google.com/spreadsheets/d/1xxoNItZwF1bKUQe0q1DgkshH07J2es8FdBcduG9ezYY/edit#gid=0

Impacted groups: 
| Database    | Count |
|-------------|-------|
| AgBase      |   4   |
| CACAO       |   1   |
| GO_Central  |   1   |
| MGI         |   2   |
| CAFA        |   4   |
| UniProt     |   2   |
| Reactome    |   2   |
| InterPro   |   6   |
| HAMAP    |   1   |


You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/26669

Thanks, Pascale

**Comment by deustp01** [comment]
> GO:0035635 entry of bacterium into host cell > replace by GO:0046718 symbiont entry into host cell

This line seems wrong. GO:0046718 is "viral entry into host cell", and I can't find a term with the name "symbiont entry into host cell" nor any plausible children of GO:0044409 "entry into host".

Help!

**Comment by deustp01** [comment]
> Obsolete GO:0035635 entry of bacterium into host cell >> 10 manual annotations >> replace by [symbiont entry into host cell](http://purl.obolibrary.org/obo/GO_0046718)

Same discrepancy in immediately preceding comment, above. The text says "symbiont" but the link points to a term for "virus"

**Comment by pgaudet** [comment]
Hi @deustp01 
I have renamed the terms, but I agree for now this is confusing.

**Comment by deustp01** [comment]
> Hi @deustp01 I have renamed the terms, but I agree for now this is confusing.

I'm OK with being confused. So I should use GO:0046718 to replace the existing terms and the "viral" name will get corrected the next time we update our local copy of GO against the central one?

**Comment by pgaudet** [comment]
That's right. GO:0046718 is now 'symbiont entry into host cell'; this will show up with the next snapshot. 

Pascale
