### ISSUE TITLE
Parentage GO:0052593 tryptamine:oxygen oxidoreductase (deaminating) activity 

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#26688]
Hi,
why do you consider tryptamine has an aliphatic amine and not an aromatic amine. One should maybe change to GO:0008131 | primary amine oxidase activity. 
Best. Lionel

**Comment by pgaudet** [comment]
The confusion may have come from RHEA: 
https://www.rhea-db.org/rhea/59419
which has 
> More general form(s) of this reaction
   [RHEA:16156](https://www.rhea-db.org/rhea/16156)
    an aliphatic amine + H2O + O2 <=> an aldehyde + H2O2 + NH4+



A question for @kaxelsen ?

**Comment by pgaudet** [comment]
In GO we have  xx reactions with the same EC: 
'aliphatic amine oxidase activity' <http://purl.obolibrary.org/obo/GO_0052595>
'aminoacetone:oxygen oxidoreductase(deaminating) activity' <http://purl.obolibrary.org/obo/GO_0052594>
'phenethylamine:oxygen oxidoreductase (deaminating) activity' <http://purl.obolibrary.org/obo/GO_0052596>
'primary amine oxidase activity' <http://purl.obolibrary.org/obo/GO_0008131>
'tryptamine:oxygen oxidoreductase (deaminating) activity' <http://purl.obolibrary.org/obo/GO_0052593>

**Comment by kaxelsen** [comment]
> The confusion may have come from RHEA: https://www.rhea-db.org/rhea/59419 which has
> 
> > More general form(s) of this reaction
> > [RHEA:16156](https://www.rhea-db.org/rhea/16156)
> > an aliphatic amine + H2O + O2 <=> an aldehyde + H2O2 + NH4+
> 
> A question for @kaxelsen ?

RHEA:16153 used the wrong amine compound. The reaction has just been updated to use "a primary methyl amine" CHEBI:228804, which is equivalent to "a primary amine" and more general than "an aliphatic amine". The updated reaction will become public in 2024_03 scheduled for May 10.
