### ISSUE TITLE
Additions or updates to UniProt keyword mappings - viral/symbiont terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26681]
Hi @Antonialock 

I am reviewing mappings between UniProtKW and GO for viral terms; 
Would you please update the following mappings: 

- [x] KW-0688	Ribosomal frameshifting >> Add GO:0075523 viral translational frameshifting
- [x] KW-1149 T=147 icosahedral capsid protein >> Add GO:0039627 T=147 icosahedral capsid
- [x] KW-1173	Viral penetration via permeabilization of host membrane	>> remove 	GO:0039665:permeabilization of host organelle membrane involved in viral entry into host cell, GO:0099008:viral entry via permeabilization of inner membrane	& add GO:0140267 'symbiont entry into host cell via permeabilization of host membrane'
- [x] KW-1182	Viral ion channel	>> Remove	GO:0005216:monoatomic ion channel activity, GO:0033644:host cell membrane, GO:0039707:pore formation by virus in membrane of host cell, GO:0051259:protein complex oligomerization	& add GO:0015267 'channel activity' ; GO:0033644:host cell membrane
- [x] KW-1087 Inhibition of host complement factors by virus > move to GO:0042784 symbiont-mediated suppression of host complement activation (current mapped term 'GO:0039573 | suppression by virus of host complement activation >, will be obsoleted)
- [x] KW-1100 Inhibition of host NF-kappa-B by virus >> change to GO:0085034  'symbiont-mediated suppression of host NF-kappaB cascade' (current mapping is GO:0039644 suppression by virus of host NF-kappaB cascade)
- [x] KW-1074 Activation of host NF-kappa-B by virus > >> change to [symbiont-mediated activation of host NF-kappaB signal transduction](http://purl.obolibrary.org/obo/GO_0085033) (current mapping is induction by virus of host NF-kappaB cascade | GO:0039652 )
- [x] KW-1087 Inhibition of host complement factors by virus > change to GO:0042784 'symbiont-mediated suppression of host complement activation' (current mapping is GO:suppression by virus of host complement activation ; GO:0039573)
- [x] KW-1121 Modulation of host cell cycle by virus > change to [symbiont-mediated perturbation of host cell cycle progression](http://purl.obolibrary.org/obo/GO_0044071) (current mapping is  GO:perturbation by virus of host cell cycle progression ; GO:0060153)
- [x] KW-1117: remove  GO:0039588 suppression by virus of host antigen processing and presentation; ~add GO:0046776 suppression by virus of host antigen processing and presentation of peptide antigen via MHC class I~ 
**Do not add new KW, we dont have a good equivalence**

Thanks, Pascale

**Comment by Antonialock** [comment]
done
