### ISSUE TITLE
GO:0006540  glutamate decarboxylation to succinate, MF parts as subclasses

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26689]
GO:0006540  glutamate decarboxylation to succinate

CURRENT (non standard) def
The chemical reactions and pathways resulting in the formation of succinate from glutamate. Also known as GABA (gamma-aminobutyrate) shunt since it channels glutamate into the TCA cycle bypassing two steps of that cycle. There are three enzymes involved in the GABA shunt: glutamate decarboxylase (GAD), GABA aminotransferase (GABA-TA), and succinate semialdehyde dehydrogenase (SSADH). These three enzymes acting in concert to convert glutamate into succinate. The GABA shunt is predominantly associated with neurotransmission in the mammalian brain. It is also present in nonneuronal cells, in plants, in unicellular eukaryotes, and in prokaryotes. PMID:12740438

This term has two children:
[GO:0036242](https://www.ebi.ac.uk/QuickGO/term/GO:0036242)    glutamate catabolic process to succinate via 2-oxoglutarate-dependent GABA-transaminase activity	is_a
[GO:0019549](https://www.ebi.ac.uk/QuickGO/term/GO:0019549)    glutamate catabolic process to succinate via succinate semialdehyde	is_a

(NO annotations to either term)

But these two terms are  the steps in the pathway described above (2-oxoglutarate-dependent GABA-transaminase activity is 
 GABA aminotransferase (GABA-TA) (the MF term needs this as a synonym)

**Comment by ValWood** [comment]
Also consider:
GABA (gamma-aminobutyrate) shunt
as a primary name?
(check usage)

**Comment by ValWood** [comment]
GO:0009450 | gamma-aminobutyric acid catabolic process
appears to be a pathway intermediate here describing the second step:
<img width="931" alt="Screenshot 2023-12-21 at 12 45 23" src="https://github.com/geneontology/go-ontology/assets/7359272/7d8d7984-384a-4ab0-9d50-52df5b370120">

**Comment by ValWood** [comment]
I might have this wrong, possible pombe uga1 has the incorrect function.
Wil check in the New Year

**Comment by ValWood** [comment]
Seems OK, the other glutamate deradation pathway is unrelated.
TODO I still need to look into why the MF terms used are different.

**Comment by deustp01** [comment]
There is a tangential but possibly important question here: can processes have other processes as parts? This relationship seems plausible. The work to identify cassettes in signaling processes fits well with this view: a ligand binding and receptor activation sequence feeds into a MAP kinase cascade feeds into modification of gene expression.

And there's the worked-out example of kinds of glycolysis. GO:0061620 "glycolytic process through glucose-6-phosphate", defined as the chemical reactions and pathways resulting in the breakdown of a carbohydrate into pyruvate, occurring through a glucose-6-phosphate intermediate, with the concomitant production of a small amount of ATP. This process has children GO:0061621 canonical glycolysis (the glycolytic process that begins with the conversion of glucose to glucose-6-phosphate by glucokinase activity. Glycolytic processes are the chemical reactions and pathways resulting in the breakdown of a carbohydrate into pyruvate, with the concomitant production of a small amount of ATP), GO:0061622 glycolytic process through glucose-1-phosphate (The chemical reactions and pathways through a glucose-1-phosphate intermediate that result in the catabolism of a carbohydrate into pyruvate, with the concomitant production of a small amount of ATP), and GO:0061633 transport-coupled glycolytic process through glucose-6-phosphate (the chemical reactions and pathways resulting in the breakdown of glucose into pyruvate, in which the glucose is converted to glucose-6-phosphate intermediate coupled to transmembrane transport) @ukemi

**Comment by ValWood** [comment]
A more fundamental problem, Pombe doesn't appear to have  GAD1  so I don't know how we get from
glutamate to 4-aminobutonoate.  I will need to extend further for sure.

**Comment by ValWood** [comment]
Closing, I don't think this is a blocker, and I know little about the pathway
