### ISSUE TITLE
Missing parent: cytoplasm to vacuole transport by the NVT pathway (GO:0120113) does not have "transport" superclass

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26697]
* **GO term ID and label for which you request a new superclass**

cytoplasm to vacuole transport by the NVT pathway (GO:0120113)

* **New superclass (parent) suggested**

Add parent "GO:0007034 vacuolar transport"

This is because "protein targeting" is not is_a transport (probably due to ongoing reorganisation of targeting)

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by ValWood** [comment]
@pgaudet  will it interfere with anything you are doing if I add this?

**Comment by pgaudet** [comment]
No, you can go ahead

**Comment by ValWood** [comment]
I put "protein targeting to vacuole" under "vacuolar transport"
vacuolar transport is defined
The directed movement of substances into, out of or within a vacuole.

(this also works for the CVT pathway)
