### ISSUE TITLE
Missing parent: GO:0035694   mitochondrial protein catabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26701]
not sure about this one:

* **GO term ID and label for which you request a new superclass**

GO:0035694   mitochondrial protein catabolic process
The chemical reactions and pathways resulting in the breakdown of a mitochondrial protein. This process is necessary to maintain the healthy state of mitochondria and is thought to occur via the induction of an intramitochondrial lysosome-like organelle that **acts to eliminate the damaged oxidised mitochondrial proteins** without destroying the mitochondrial structure. PMID:21264221 PMID:21264228

* **New superclass (parent) suggested**

GO:0006515   protein quality control for misfolded or incompletely synthesized proteins

* **Reference(s), if appropriate**

based on the definition of  GO:0035694   mitochondrial protein catabolic process

**Comment by pgaudet** [comment]
It doesn't seem like this is how it's always been used, see for eg 
https://amigo.geneontology.org/amigo/reference/PMID:21264221

"MALM is involved in the degradation of oxidized mitochondrial proteins, leading to increased ATP synthesis and decreased reactive oxygen species generation."

So, this is not misfolded or incompletely synthesized, but damaged.

**Comment by ValWood** [comment]
OK, good point!

**Comment by ValWood** [comment]
Thats what the def says too!

**Comment by ValWood** [comment]
sorry, I agreed, forgot to close
