### ISSUE TITLE
	3-oxo-5alpha-steroid 4-dehydrogenase (NADP+)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26703]
3-oxo-5alpha-steroid 4-dehydrogenase (NADP+)
[3-oxo-5alpha-steroid 4-dehydrogenase (NADP+)](https://www.ebi.ac.uk/QuickGO/term/GO:0047751)

a) is not appended by "activity"

b)  is not related to 3-oxo-5-alpha-steroid 4-dehydrogenase activity
[3-oxo-5-alpha-steroid 4-dehydrogenase activity](https://www.ebi.ac.uk/QuickGO/term/GO:0003865)

**Comment by pgaudet** [comment]
Good catch! These two are the same... with a hyphen as the difference. 

We need to obsolete one and replace by the other.

**Comment by pgaudet** [comment]
Likewise, this pair of terms correspond to the same activity: 
'3-oxo-delta(4,5)-steroid 5-beta-reductase activity'
'delta4-3-oxosteroid 5beta-reductase activity'

On MetaCyc both point to EC:1.3.1.3

Also need an obsoletion and with replace by.

**Comment by raymond91125** [comment]
> Good catch! These two are the same... with a hyphen as the difference.
> 
> We need to obsolete one and replace by the other.

GO:0047751 3-oxo-5alpha-steroid 4-dehydrogenase (NADP+) and GO:0003865 3-oxo-5-alpha-steroid 4-dehydrogenase activity are related but of different ECs and RHEAs.

**Comment by raymond91125** [comment]
> The grouping term 'GO_0035671 enone reductase activity' also needs to be obsoleted, it's mapping to the general EC:1.3.1.-, which is actually GO:0016628 oxidoreductase activity, acting on the CH-CH group of donors, NAD or NADP as acceptor.
> 
> Thanks, Pascale

GO_0035671 enone reductase activity specifies enones thus is a subset of GO:0016628 oxidoreductase activity, acting on the CH-CH group of donors, NAD or NADP as acceptor. We may remove the XREF EC:1.3.1.- to avoid the confusion.

**Comment by raymond91125** [comment]
> Likewise, this pair of terms correspond to the same activity: '3-oxo-delta(4,5)-steroid 5-beta-reductase activity' 'delta4-3-oxosteroid 5beta-reductase activity'
> 
> On MetaCyc both point to EC:1.3.1.3
> 
> Also need an obsoletion and with replace by.

Done.

**Comment by pgaudet** [comment]
Hi @raymond91125 
thanks for looking into this more closely. I think these are the remaining tasks here: 

- [ ] GO:0047751 3-oxo-5alpha-steroid 4-dehydrogenase (NADP+) and GO:0003865 3-oxo-5-alpha-steroid 4-dehydrogenase activity are of different ECs and RHEAs. GO:0047751 should be a child of GO:0003865.
- OK
- **GO:0003865 3-oxo-5-alpha-steroid 4-dehydrogenase activity**  currently does not have a RHEA, as far as I can tell, we should add [RHEA:13805](https://www.rhea-db.org/rhea/13805) 
- [ ] append 'activity' to the term label of GO:0047751 3-oxo-5alpha-steroid 4-dehydrogenase (NADP+) 
- [ ]  At least remove the partial EC from GO_0035671 enone reductase  activity 
Thanks, Pascale
