### ISSUE TITLE
NTR: [GDF15-GFRAL signaling pathway]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#26708]
Hi GO!

Happy new year!

I would need a bunch of new signaling pathways term for the glial cell-derived neurotrophic factor receptor signaling pathways.

We should first update the definition of GO:0035860 to indicate that it constitutes a family of coreceptors and describe the signaling.

Then it would be great to create 5 children terms, one per signaling pathway. In each case, there is one GDNF ligand (GDNF, NRTN, ARTN, PSPN and GDF15) and its corresponding GDNFR coreceptor (GFRA1, GFRA2, GFRA3, GFRA4 and GFRAL, respectively). 

Note that the GDF15-GFRAL aversive pathway, a very interesting signaling pathway triggerred in response to various stresses and that causes an aversive response, is under the spotlight these days because GDF15, the cytokine/hormone that triggers the signaling is the probable cause of nausea during pregnancy. 

I would also need some terms for the regulation of this pathway

Thanks

Sylvain

1) Update the name and definition of GO:0035860
Name
FROM:
GO:0035860 glial cell-derived neurotrophic factor receptor signaling pathway
to:
GO:0035860 glial cell-derived neurotrophic factor receptor family signaling pathway

Definition
FROM:
The series of molecular signals initiated by a ligand binding to a glial cell-derived neurotrophic factor receptor. PMID:12953054 
TO:
The series of molecular signals initiated by a GDNF ligand (GDNF, NRTN, ARTN, PSPN OR GDF15) binding to its glial cell-derived neurotrophic factor receptor (GFRA1, GFRA2, GFRA3, GFRA4 OR GFRAL, respectively), triggering RET autophosphorylation and activation, leading to activation of downstream signaling pathways, including the MAPK- and AKT-signaling pathways. PMID:12953054

1) New term
Name: GDF15-GFRAL signaling pathway
Category: Biological Process
Definition:
The series of molecular signals initiated by GDF15 binding to GFRAL coreceptor in response to stress, triggering a RET receptor-dependent aversive response, characterized by nausea, vomitting, and/or loss of appetite.

child of GO:0033554 cellular response to stress
child of GO:0035860 glial cell-derived neurotrophic factor receptor signaling pathway
PMID:30639358
PMID:31535977
PMID:33593916
PMID:37437602

2) New term
Name: regulation of GDF15-GFRAL signaling pathway
Category: Biological Process
Definition: Any process that modulates the frequency, rate or extent of Kit signaling pathway. 
child of GDF15-GFRAL signaling pathway
PMID:35177851

3) New term
Name: negative regulation of GDF15-GFRAL signaling pathway
Category: Biological Process
Definition: Any process that stops, prevents or reduces the frequency, rate or extent of GDF15-GFRAL signaling pathway
child of regulation of GDF15-GFRAL signaling pathway
PMID:35177851

4) New term
Name: GDNF-GFRA1 signaling pathway
Category: Biological Process
Definition:
The series of molecular signals initiated by GDNF binding to GFRA1 coreceptor, triggering a RET receptor-dependent response that promotes the survival of many types of neurons.
child of GO:0035860 glial cell-derived neurotrophic factor receptor signaling pathway
PMID:31535977

5) New term
Name: NRTN-GFRA2 signaling pathway
Category: Biological Process
Definition:
The series of molecular signals initiated by NRTN binding to GFRA2 coreceptor, triggering a RET receptor-dependent response that promotes the development and maintenance of homeostasis of the central and peripheral neurons of the nervous system.
child of GO:0035860 glial cell-derived neurotrophic factor receptor signaling pathway
PMID:31535977

6) New term
Name: ARTN-GFRA3 signaling pathway
Category: Biological Process
Definition:
The series of molecular signals initiated by ARTN binding to GFRA3 coreceptor, triggering a RET receptor-dependent response that promotes the development and maintenance of homeostasis of the central and peripheral neurons of the nervous system.
child of GO:0035860 glial cell-derived neurotrophic factor receptor signaling pathway
PMID:31535977

7) New term
Name: PSPN-GFRA4 signaling pathway
Category: Biological Process
Definition:
The series of molecular signals initiated by PSPN binding to GFRA4 coreceptor, triggering a RET receptor-dependent response that promotes the survival of promotes the survival of ventral midbrain dopaminergic neurons.
child of GO:0035860 glial cell-derived neurotrophic factor receptor signaling pathway
PMID:9491986
PMID:11116144

**Comment by raymond91125** [comment]
It seems that the GDNF and GDNFR interactions are not necessarily one-to-one.

PMID:12953054 Figure 1B
![image](https://github.com/geneontology/go-ontology/assets/619520/52507750-78f0-43c8-b77d-295aa6cc87d1)

PMID:29245123
"However, this ligand-specific binding to GFRα co-receptors at times is promiscuous with a GFL ligand capable of interacting and functionally signaling with one of other nonpreferred GFRα proteins. GDNF can also bind to GFRα2, NRTN to GFRα1, and ARTN to GFRα1 [16], [17]."

**Comment by sylvainpoux** [comment]
Hi @raymond91125 
You are righet, they are not one to one and form a 2:2:2 2:2:2 ternary complex composed of GDNF (GDNF, NRTN, ARTN, PSPN OR GDF15), GDNFR (FRA1, GFRA2, GFRA3, GFRA4 OR GFRAL, respectively) and RET. I think the definition I provide address this point "The series of molecular signals initiated by GDNF binding to GFRA1 coreceptor, triggering a RET receptor-dependent "
Does it answer your question?
Sylvain

**Comment by raymond91125** [comment]
Thanks @sylvainpoux. My concern is that whether it is necessary to go into such granularity for glial cell-derived neurotrophic factor receptor signaling pathway in the ontology, if there is essentially one shared mechanism. It's all about a GDNF ligand binding to a GDNF receptor and followed by recruiting RET. The exact interactions may be specified in annotations of specific gene products. Would that work for you?

**Comment by sylvainpoux** [comment]
Hi @raymond91125 
I think it is really important in light of recent discoveries concerning GDF15. Please note that I initially only planned to request terms for GDF15-GFRAL and that I submitted the whole list of terms following discussion with Pascale.
If you think it is not needed to create all these terms, please consider the GDF15-GFRAL aversive pathway.
Thanks
Sylvain

**Comment by raymond91125** [comment]
@sylvainpoux Thanks for the clarification. Let's add what's immediately needed for annotations. More may be added later.
Please note:
1. We don't usually add "family" in the term name. The meaning is implied.
2. The signalling pathway starts at ligand/receptor binding and ends at the regulation of a cellular process such as transcription.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160144
+name: GDF15-GFRAL signaling pathway
+namespace: biological_process
+def: "The series of molecular signals initiated by GDF15 binding to GFRAL coreceptor, triggering RET autophosphorylation and activation, in response to stress." [PMID:30639358, PMID:31535977, PMID:33593916, PMID:37437602]
+is_a: GO:0033554 ! cellular response to stress
+is_a: GO:0035860 ! glial cell-derived neurotrophic factor receptor signaling pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26708" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-12T18:40:57Z
+
+[Term]
+id: GO:0160145
+name: negative regulation of GDF15-GFRAL signaling pathway
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of GDF15-GFRAL signaling pathway." [PMID:35177851]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0160144 ! GDF15-GFRAL signaling pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26708" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-12T20:00:40Z

**Comment by pgaudet** [comment]
Hi @raymond91125 

Does anything need to be done to complete and close this ticket?

**Comment by raymond91125** [comment]
I was waiting to see if there are further comments. If not, we should close this.
