### ISSUE TITLE
Obsoletion request: GO:1902621   actomyosin contractile ring disassembly/GO:1990274  mitotic actomyosin contractile ring disassembly

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26711]
Please provide as much information as you can:

* **GO term ID and Label**
 - [x] GO:1902621  actomyosin contractile ring disassembly
 - [x] GO:1990274  mitotic actomyosin contractile ring disassembly
 - [x] GO:0120151   positive regulation of mitotic actomyosin contractile ring disassembly
 - [x] GO:0120150  regulation of mitotic actomyosin contractile ring disassembly

* **Reason for deprecation** Put an x in the appropriate box: 

 - [ ] The reason for obsoletion is that the data from the paper for which the term was requested can be accurately described using another term 👍 
 - [x] GO:0000916   actomyosin contractile ring contraction
 - [x] GO:1902404    mitotic actomyosin contractile ring contraction
 - [x] GO:1903471    regulation of mitotic actomyosin contractile ring contraction
 - [x] GO:1903473  positive regulation of mitotic actomyosin contractile ring contraction

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **Are there annotations to this term?**
- How many EXP: 6
PomBase 4
SGD 2

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

No

* **Is this term in a subset? (check the AmiGO page for that term)**

No
* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [ ] check taxon constraints 

***Check annotations***

Annotation review ticket
https://github.com/geneontology/go-annotation/issues/4915

- [x] find external mappings (via IEAS), include in obsoletion notice  

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
I asked some experts and they don't see any difference between constriction and disassembly. The ring disassembles as it constricts

**Comment by ValWood** [comment]
proceed to obsoletion, annotations will be remapped.

remove taxon constraint
GO:0000916 | actomyosin contractile ring contraction | Only in Taxon | 2759 | Eukaryota
(@pgaudet  will I be able to do this? before xmas  we were told to wait for taxon constraints until some change was implemented, otherwise I could go ahead with this)

**Comment by pgaudet** [comment]
I think you can go ahead and remove the taxon constraint - right @balhoff ?

**Comment by balhoff** [comment]
Yes, go ahead, it's no problem.

**Comment by ValWood** [comment]
Thanks!
