### ISSUE TITLE
Textual definition update:  GO and Rhea def different:  GO:0003933 GTP cyclohydrolase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26710]
* **GO term ID and label for which you request a definition update**

 GO:0003933 GTP cyclohydrolase activity

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**

<img width="1302" alt="GO def and Rhea different" src="https://github.com/geneontology/go-ontology/assets/7359272/99fabd4b-6a7a-4bae-80dc-96f3a21d455c">

GO def has +3H

**Comment by pgaudet** [comment]
Fixed the whole branch: 

- [ ] 'GTP cyclohydrolase activity': removed ECs in the defxref, which were the ECs of the children
- [ ] 'archaeal-specific GTP cyclohydrolase activity': fixed def to match RHEA's, added RHEA & EC; changed label to   GTP cyclohydrolase IV activity; added xref: EC:3.5.4.39 and xref: RHEA:25860
- [ ] 'GTP cyclohydrolase I activity' : fixed def to match RHEA's
- [ ] 'GTP cyclohydrolase II activity' : fixed def to match RHEA's
- [ ] 'GTP cyclohydrolase IIa activity' : fixed def to match RHEA's

**Comment by pgaudet** [comment]
@ValWood I think you were talking about GO:0003935  GTP cyclohydrolase II activity ?

**Comment by ValWood** [comment]
I was referring to
GO:0003933 GTP cyclohydrolase activity
in the example

**Comment by pgaudet** [comment]
Looks like were not looking at the same thing. The definition I see if very different: 
<img width="1140" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/7b43d067-e4fd-42ca-abbc-7ab211eb1878">

**Comment by ValWood** [comment]
oh yes,  you are right, GTP cyclohydrolase was the parent!
