### ISSUE TITLE
Make 'toxin transport' GO:1901998 do-not-annotate (or obsolete it)

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#26720]
"toxin transport" is very vague. There is no mechanism or direction specified. I think it should be in the do not annotate subset (or even obsoleted). 

it should always be possible to have a more specific activity, e.g.

GO:0000269 ! toxin export channel activity
GO:0019534 ! toxin transmembrane transporter activity

There are 26 experimental direct annotations to it https://amigo.geneontology.org/amigo/term/GO:1901998

Many any ARUK-UCL where the transmembrane part is implicit in extensions

[has target start location](http://purl.obolibrary.org/obo/RO_0002338) [external side of plasma membrane](http://amigo.geneontology.org/amigo/term/GO:0009897)
[has target end location](http://purl.obolibrary.org/obo/RO_0002339) [cytoplasmic side of plasma membrane](http://amigo.geneontology.org/amigo/term/GO:0009898) 	

For others like the E coli, it's obvious this is transmembrane

See also

- #4618. 

There is also regulation of toxin transport, but this has a single annotation
https://amigo.geneontology.org/amigo/term/GO:1902007

This seems to be (inter-organism) regulating import (and the direction should be positive)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC167169/

Although this doesn't seem to be the evolved function - the mutants don't import the toxin - so more likely a mechanism that has been hijacked

**Comment by pgaudet** [comment]
This term could probably be replaced by 'GO:1990748 cellular detoxification'

**Comment by raymond91125** [comment]
@pgaudet Is the recommendation to obsolete?

**Comment by pgaudet** [comment]
Yes

**Comment by pgaudet** [comment]
I think this is ready for obsoletion.
