### ISSUE TITLE
GO:0039588 suppression by virus of host antigen processing and presentation: Change labels to symbiont-mediated 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26738]
- GO:0039588 suppression by virus of host antigen processing and presentation >> change label to  symbiont-mediated  antigen presentation ('processing' not needed in the label) 
- 'suppression by virus of host antigen processing and presentation of peptide antigen via MHC class I'
- 'suppression by virus of host antigen processing and presentation of peptide antigen via MHC class II'
- as well as parent: GO:0039504 suppression by virus of host adaptive immune response

**Comment by pgaudet** [comment]
@genegodbold to provide bacterial references

**Comment by genegodbold** [comment]
- The S1 subunit of pertussis toxin from _Bordetella pertussis_ (UniProt:P04977) inhibits antigen presentation by suppressing the expression of antigen-presenting molecules [PMID:16598657] and [PMID:14977950].
- EsxG and EsxH from _Mycobacterium tuberculosis_: The EsxG-EsxH heterodimer impairs the ability of the major histocompatibility complex class II (MHC-II) to present antigen. This appears to be a result of its ability to antagonize the ESCRT system [PMID:24204276].
- Lipoprotein A (LprA); Rv1270c) from _Mycobacterium tuberculosis_: When incubated with macrophages, LprA induces production of the host cytokines IL-10 and tumor necrosis factor (TNF).  Acylated LprA induces the maturation of dendritic cells, induces cytokine production, and inhibits antigen processing [PMID:16785538]. 
- Lipoprotein p19 (LpqH; Rv3763) from Mycobacterium tuberculosis: LpqH inhibits host MHC-II processing and presentation in murine macrophages that is induced by interferon-gamma. LpqH acts via host TLR2 [PMID:12900278]. 
- SteD from Salmonella: The Salmonella effector SteD localizes to the Golgi network and vesicles containing the E3 ubiquitin ligase MARCH8 and mature MHCII. It causes the MARCH8-dependent ubiquitination and depletion of surface MHCII. One of two transmembrane domains and the C-terminal cytoplasmic region of SteD mediated binding to MARCH8 and MHCII, respectively. Infection of dendritic cells resulted in SteD-dependent depletion of surface MHCII, the co-stimulatory molecule B7.2, and suppression of T cell activation. SteD also accounted for suppression of T cell activation during Salmonella infection of mice. SteD appears to function as an adaptor, forcing inappropriate ubiquitination of mMHCII by MARCH8 and thereby suppressing T-cell activation [PMID:27832589].
