### ISSUE TITLE
NTR: symbiont-mediated disruption of host mucosa

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26745]
Please provide as much information as you can: 

* **Suggested term label:**

* **Definition (free text)**

* **Reference, in format PMID:#######**
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
'disruption of anatomical structure in another organism'

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
@genegodbold will provide references

**Comment by genegodbold** [comment]
**Bacterial proteins causing mucosal barrier dysfunction**:
- **C2 toxin, component I** (C2I) from _Clostridium botulinum_ (UniProt:D4N871): The C2 binary toxin ADP-ribosylates globular actin which has the effect of depolymerizing filamentous actin capped by the modified actin in sensitive cells. This induces cell rounding and dermonecrosis. C2 toxin induces dermonecrosis and hermorrhagic enterocolitis in avians but rarely in animals [PMID:28800062].
- **Iota toxin Ia** from _Clostridium perfringens_: The enzymatic Ia iota toxin subunit is an ADP-ribosyltransferase that targets host actin at Arg177. Its activity blocks the formation of filamentous actin in cells, disrupts the cytoskeleton, and leads to cell rounding [PMID:30297616]. The cytoskeletal dysfunction induced by iota toxin Ia ultimately kills the intoxicated cell. The iota toxin alters intestinal permeability by destruction of the mucosal epithelium and altering intestinal motility [PMID:28764997].
- **Shigella extracellular protease A** (Serine protease A, Serine protease autotransporter, SepA) from _Shigella_: SepA facilitates invasion into the host by opening the epithelial barrier. Shigella strains carrying SepA, but not the isogenic deletion mutants, caused lesions on the intestinal barrier indicated by epithelial desquamation in which the cells are shed from the tips of the villi [PMID:28598765].
- **Phospholipase A2** (VvPlpA) from _Vibrio vulnificus_: VvPlpA is essential for virulence in mice. It is secreted via a type II secretion system. Mice infected with a bacterial mutant in which the gene encoding PlpA was deleted have greater survival percentages than those infected with the wild type bacterium though bacterial survival in vitro is not affected. VvPlpA is essential for lysis and necrotic death of INT-407 mouse epithelial cells. Phospholipase A2s hydrolyze a fatty acid from the sn-2 position of the glycerol moiety. The recombinant PlpA protein has hemolytic activity toward both human and horse red blood cells with phosphatidylcholine the specific target. The proposed mechanism of action involves the disruption of intestinal epithelial cells, allowing the bacterium to reach the blood stream and invade other organs. The gene is induced when exposed to human intestinal cells [PMID:28855258].
- **Yersinia outer protein J** (YopJ) from _Yersinia pseudotuberculosis_: YopJ is a T3SS effector that inhibits activation of host MAPK (ERK1/2, JNK, p38) and NFkappaB via acetylation of Ser and Thr residues on MAPKK and IKKbeta. Acetylation prevents  their activation by upstream kinases [PMID:16728640]-[PMID:17116858]. YopJ is activated by  host inositol hexakisphosphate [PMID:20430892]. YopJ increases gut permeability and allows bacterial translocation from the gut during _Y. pseudotuberculosis_ infection. This increases mortality in a mouse model of infection. YopJ acetylates host proteins RICK and TAK1 thereby inhibiting them. This provokes a defect in the intestinal barrier [PMID:22520462].

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141139
+name: symbiont-mediated disruption of host mucosa
+namespace: biological_process
+def: "The disruption of the host mucosa by a symbiont, leading to damage or temporary subversion of that tissue. The mucosa is a membrane that lines various cavities in the body of an organism and covers the surface of internal organs." [PMID:22520462, PMID:28598765, PMID:28764997]
+is_a: GO:0141062 ! disruption of tissue in another organism
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26745" xsd:anyURI
+created_by: pg
+creation_date: 2024-01-16T09:44:42Z
