### ISSUE TITLE
Obsoletion request: GO:0052064 symbiont-mediated activation of reactive oxygen species production in host cell

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26746]
GO:0052064 symbiont-mediated activation of reactive oxygen species production in host cell

There is no evidence that this process exists; the host produces ROS as a defense mechanisms against pathogens. 

@genegodbold

**Comment by genegodbold** [comment]
Reactive oxygen species (ROS) might be produced as a result of the detection of a microbe where it shouldn't be through pattern recognition receptors [or by evidence of microbial activity such as cytoskeletal alterations or cellular permeability) but I haven't seen evidence that microbes activate these microbe-destroying molecular species by direct activity. On the other hand, there are plenty of examples of microbes **suppressing** the generation of ROS and there are even more examples of them expressing detoxifying enzymes (like superoxide dismutases and catalases) to downgrade their calamitous effects on the microbe.

**Comment by pgaudet** [comment]
2 EXP, removed
