### ISSUE TITLE
Align subsets.yaml to match the schema

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26752]
Hi, 

I have made a yaml schema for subsets, see 
https://github.com/geneontology/go-ontology/issues/26751

I will align the subsets.yaml file to match the schema

**Comment by pgaudet** [comment]
Hi @jlewsmith 

I am replacing Marek as the contact person for the Aspergillus and Candida slims: 
(http://release.geneontology.org/2023-11-15/ontology/subsets/goslim_aspergillus.yaml)
http://release.geneontology.org/2023-11-15/ontology/subsets/goslim_candida.yaml

Can you confirm that these are still used? I see that the aspergillus slim is no getting generated anymore; if these are being use I will open a ticket to look into that. 

Thanks, Pascale

**Comment by pgaudet** [comment]
All done

**Comment by jlewsmith** [comment]
Hi Pascale,

The Aspergillus database is no longer maintained and/or available, as the site had security issues.

CGD does require updating.

Thanks,
Jodi
________________________________

**Comment by pgaudet** [comment]
Thanks for the reply Jodi! I made the aspergillus slim obsolete.
