### ISSUE TITLE
Obsoletion: check these ncRNA terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26761]
ie these terms should be checked and possibly obsoleted 
- [x] 'ncRNA 5\'-end processing' <http://purl.obolibrary.org/obo/GO_0034471>
- [x]  'ncRNA catabolic process' <http://purl.obolibrary.org/obo/GO_0034661>
- [x]   'ncRNA deadenylation' <http://purl.obolibrary.org/obo/GO_0110008>
- [x]  'ncRNA export from nucleus' <http://purl.obolibrary.org/obo/GO_0097064>
'ncRNA metabolic process' <http://purl.obolibrary.org/obo/GO_0034660>
- [x]  'ncRNA processing' <http://purl.obolibrary.org/obo/GO_0034470>
- [x] 'ncRNA transcription associated with protein coding gene TSS/TES' <http://purl.obolibrary.org/obo/GO_0098790>
'ncRNA transcription' <http://purl.obolibrary.org/obo/GO_0098781>
- [x] 'nuclear ncRNA surveillance' <http://purl.obolibrary.org/obo/GO_0071029>

_Originally posted by @pgaudet in https://github.com/geneontology/go-ontology/issues/26459#issuecomment-1885552256_

**Comment by ValWood** [comment]
There might be a need  for a "lncRNA" terms if direct annotations do not map to existing descendants.

I'l do this soon as it will make the RNA processing/decay/surveillance  work easier

**Comment by ValWood** [comment]
Rationale: ncRNA groups everything that isn't an mRNA, which isn't necessarily a biologically relevant grouping. Grouping by common pathways would be more appropriate.

**Comment by pfey03** [comment]
what about miRNA catabolic process? microRNA should also be excluded.

Petra

**Comment by ValWood** [comment]
"miRNA catabolic process" will still exist (with different grouping term), it's only the grouping term that's problematic. It is basically "everything that isn't a mRNA"  which is bad ontology practice.

**Comment by RLovering** [comment]
Hi Val

UCL has 2 annotations using GO:0110008 ncRNA deadenylation. TERC (a lncRNA) is being deadenylated by PARN, PMIDs:26482878; 26950371. TERC ID has been added to the AE field. Will there be an RNA deadenylation term? No other direct annotations to these terms.

Thanks

Ruth

**Comment by ValWood** [comment]
GO:0110008 ncRNA deadenylation will go but for a different reason.... most will have a replacement with lncRNA (or an existing term). 
This one won't  be replaced because GO:0110008 ncRNA deadenylation is really only describing the  MF.
The correct BP would be "GO:0031123 RNA 3'-end processing"

The annotation would be something  like:
PARN  poly(A)-specific ribonuclease activity has_input TERC part_of  GO:0031123 RNA 3'-end processing (or  lncRNA 3' end processing)

We don't currently have "lncRNA 3' end processing", but we need to create this because we have all the other subtypes.

Does that make sense?

**Comment by RLovering** [comment]
Yes perfect. let me know when the lncRNA 3' end processing term is available so that I can revise the annotations. I don't want to delete them until the new term is available otherwise I will forget what to edit - unless you want me to do this sooner.
;)

**Comment by ValWood** [comment]
Don't worry, I'll make sure the replacement terms are available before obsoletion.

**Comment by ValWood** [comment]
@pgaudet  we will need a term forthese regulatory RNAs in E.coli.
Any suggestions? https://pubmed.ncbi.nlm.nih.gov/16980588/

**Comment by ValWood** [comment]
For  ncRNA catabolic process/ncRNA deadenylation'
https://github.com/geneontology/go-ontology/issues/26988

For ncRNA 5'-end processing
https://github.com/geneontology/go-ontology/issues/26983
https://github.com/geneontology/go-ontology/issues/26940

**Comment by ValWood** [comment]
- [x]  removed all the children of "ncRNA surveillance" out  so they are directly under RNA surveillance

**Comment by ValWood** [comment]
Please provide as much information as you can:

* **GO term ID and Label**

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x]  The reason for obsoletion is that this term was an unnecessary grouping term.
 

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

Replace by RNA parent term, but most people will want to remove existing annotations to the  more specific terms

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

No

* **Is this term in a subset? (check the AmiGO page for that term)**

No

* **Any other information**


----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
- [x] create annotation review ticket: h
- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation 

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket
