### ISSUE TITLE
modification of the name of GO:0160133 bicarbonate channel activity 

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#26780]
Hi,
could you please take into account the following modification concerning the name of GO:0160133:
FROM:
bicarbonate channel activity
TO:
hydrogencarbonate channel activity
and could you please  add as synonym: bicarbonate channel activity 
Many thanks
Guilaine

**Comment by pgaudet** [comment]
Note that we use 'bicarbonate' for many other terms: 

'bicarbonate binding' <http://purl.obolibrary.org/obo/GO_0071890>
'bicarbonate channel activity' <http://purl.obolibrary.org/obo/GO_0160133>
'bicarbonate transmembrane transporter activity' <http://purl.obolibrary.org/obo/GO_0015106>
'bicarbonate transport' <http://purl.obolibrary.org/obo/GO_0015701>
'bicarbonate:monoatomic anion antiporter activity' <http://purl.obolibrary.org/obo/GO_0140829>
'zinc:bicarbonate symporter activity' <http://purl.obolibrary.org/obo/GO_0140412>
'zinc:bicarbonate:selenite symporter activity' <http://purl.obolibrary.org/obo/GO_0140413>
'sodium,bicarbonate:chloride antiporter activity' <http://purl.obolibrary.org/obo/GO_0140892>
'sodium:bicarbonate symporter activity' <http://purl.obolibrary.org/obo/GO_0008510>
'sulfate:bicarbonate antiporter activity' <http://purl.obolibrary.org/obo/GO_0015383>
'chloride:bicarbonate antiporter activity' <http://purl.obolibrary.org/obo/GO_0140900>
'monoatomic cation:bicarbonate symporter activity' <http://purl.obolibrary.org/obo/GO_0140410>

**Comment by pgaudet** [comment]
Hi @Argoudpuy 

Do you want this change to match the IUAPAC  'official' nomenclature? It seem bicarbonate is much more widely used: https://en.wikipedia.org/wiki/Bicarbonate

We just want to make sure that the term labels reflect general usage, not specialized terminology.

**Comment by Argoudpuy** [comment]
Hi pascale,
ok, so nothing to do, if the term labels have to reflect general usage, not specialized terminology

**Comment by pgaudet** [comment]
@edwong57 Can you check that we have 'hydrogencarbonate' synonyms of all the term above? 
https://github.com/geneontology/go-ontology/issues/26780#issuecomment-1891447473

Thanks, Pascale
