### ISSUE TITLE
Multiple EC xrefs on GO:0106029 tRNA pseudouridine synthase activity - make 8 new specific child terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26797]
@raymond91105 
I see that "**tRNA** pseudouridine synthase activity (GO:0106029)" has a similar issue to "**rRNA** pseudouridine synthase activity" (#26618) and so I think it needs a similar solution. Main issue is that there are several specific ECs associated with the general term. Tasks are as follows:

- [x] make a set of 8 new child terms corresponding to the 8 EC xrefs and make them children of GO:0106029 (add RHEA xrefs)
- [x] remove the narrow synonyms based on specific ECs from GO:0106029
- [x] remove the current RHEA:22376 and MetaCyc:TRNA-PSEUDOURIDINE-SYNTHASE-I-RXN xrefs and associate with the new term for EC:5.4.99.12
- [x] add [RHEA:54572](https://www.rhea-db.org/rhea/54572) to GO:0106029 as the correct RHEA xref

id: GO:0106029
name: tRNA pseudouridine synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: tRNA uridine = tRNA pseudouridine. Conversion of uridine in a tRNA molecule to pseudouridine by rotation of the C1'-N-1 glycosidic bond of uridine in RNA to a C1'-C5." [PMID:11095668]
synonym: "Mitochondrial tRNA pseudouridine(27/28) synthase" NARROW [EC:5.4.99.44]
synonym: "transfer ribonucleate pseudouridine synthetase activity" EXACT []
synonym: "transfer RNA pseudouridine synthetase activity" EXACT []
synonym: "tRNA pseudouridine(13) synthase" NARROW [EC:5.4.99.27]
synonym: "tRNA pseudouridine(31) synthase" NARROW [EC:5.4.99.42]
synonym: "tRNA pseudouridine(32) synthase" NARROW [EC:5.4.99.28]
synonym: "tRNA pseudouridine(38-40) synthase" NARROW [EC:5.4.99.12]
synonym: "tRNA pseudouridine(38/39) synthase" NARROW [EC:5.4.99.45]
synonym: "tRNA pseudouridine(55) synthase" NARROW [EC:5.4.99.25]
synonym: "tRNA pseudouridine(65) synthase" NARROW [EC:5.4.99.26]
synonym: "tRNA pseudouridylate synthase I activity" NARROW [EC:5.4.99.12]
synonym: "tRNA-pseudouridine synthase activity" EXACT []
synonym: "tRNA-pseudouridine synthase I activity" NARROW [EC:5.4.99.12]
synonym: "tRNA-uridine isomerase activity" EXACT []
synonym: "tRNA-uridine uracilmutase activity" EXACT []
xref: EC:5.4.99.12
xref: EC:5.4.99.25
xref: EC:5.4.99.26
xref: EC:5.4.99.27
xref: EC:5.4.99.28
xref: EC:5.4.99.42
xref: EC:5.4.99.44
xref: EC:5.4.99.45
xref: MetaCyc:TRNA-PSEUDOURIDINE-SYNTHASE-I-RXN
xref: RHEA:22376
is_a: GO:0009982 ! pseudouridine synthase activity
is_a: GO:0140101 ! catalytic activity, acting on a tRNA
created_by: hjd
creation_date: 2017-06-26T17:37:30Z

**Comment by sjm41** [comment]
Here are the new terms:

name: tRNA pseudouridine(38-40) synthase activity
def: Catalysis of the reaction: uridine38/39/40 in tRNA = pseudouridine38/39/40 in tRNA.
synonym: PSUI activity [EC:5.4.99.12]
synonym: tRNA pseudouridylate synthase I activity [EC:5.4.99.12]
xref: EC:5.4.99.12
xref: RHEA:22376
xref: MetaCyc:TRNA-PSEUDOURIDINE-SYNTHASE-I-RXN 

name: tRNA pseudouridine(55) synthase activity
def: Catalysis of the reaction: uridine55 in tRNA = pseudouridine55 in tRNA.
xref: EC:5.4.99.25
xref: RHEA:42532

name: tRNA pseudouridine(65) synthase activity
def: Catalysis of the reaction: uridine65 in tRNA = pseudouridine65 in tRNA.
xref: EC:5.4.99.26
xref: RHEA:42536

name: tRNA pseudouridine(13) synthase activity
def: Catalysis of the reaction: uridine13 in tRNA = pseudouridine13 in tRNA.
xref: EC:5.4.99.27
xref: RHEA:42540

name: tRNA pseudouridine(32) synthase activity
def: Catalysis of the reaction: uridine32 in tRNA = pseudouridine32 in tRNA.
xref: EC:5.4.99.28
xref: RHEA:42544

name: tRNA pseudouridine(31) synthase activity
def: Catalysis of the reaction: uridine31 in tRNA = pseudouridine31 in tRNA
xref: EC:5.4.99.42
xref: RHEA:42552

name: mitochondrial tRNA pseudouridine(27/28) synthase activity
def: Catalysis of the reaction: uridine27/28 in mitochondrial tRNA = pseudouridine27/28 in mitochondrial tRNA.
xref: EC:5.4.99.44
xref: RHEA:42560

name: tRNA pseudouridine(38/39) synthase activity
def: Catalysis of the reaction: uridine38/39 in tRNA = pseudouridine38/39 in tRNA.
xref: EC:5.4.99.45
xref: RHEA:42564

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160147
+name: tRNA pseudouridine(38-40) synthase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: uridine(38/39/40) in tRNA = pseudouridine(38/39/40) in tRNA." [EC:5.4.99.12]
+synonym: "PSUI activity" EXACT [EC:5.4.99.12]
+synonym: "tRNA pseudouridylate synthase" EXACT [EC:5.4.99.12]
+xref: EC:5.4.99.12
+xref: MetaCyc:TRNA-PSEUDOURIDINE-SYNTHASE-I-RXN
+xref: RHEA:22376
+is_a: GO:0106029 ! tRNA pseudouridine synthase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26797" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-17T01:55:49Z

+[Term]
+id: GO:0160148
+name: tRNA pseudouridine(55) synthase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: uridine(55) in tRNA = pseudouridine(55) in tRNA." [EC:5.4.99.25]
+xref: EC:5.4.99.25
+xref: RHEA:42532
+is_a: GO:0106029 ! tRNA pseudouridine synthase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26797" xsd:any
URI
+created_by: rynl
+creation_date: 2024-01-17T18:49:10Z
+
+[Term]
+id: GO:0160149
+name: tRNA pseudouridine(65) synthase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: uridine(65) in tRNA = pseudouridine(65) in tRNA." [EC:5.4.99.26]
+xref: EC:5.4.99.26
+xref: RHEA:42536
+is_a: GO:0106029 ! tRNA pseudouridine synthase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26797" xsd:any
URI
+created_by: rynl
+creation_date: 2024-01-17T18:52:17Z
+
+[Term]
+id: GO:0160150
+name: tRNA pseudouridine(13) synthase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: uridine(13) in tRNA = pseudouridine(13) in tRNA." [EC:5.4.99.27]
+xref: EC:5.4.99.27
+xref: RHEA:42540
+is_a: GO:0106029 ! tRNA pseudouridine synthase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26797" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-17T18:54:10Z
+
+[Term]
+id: GO:0160151
+name: tRNA pseudouridine(32) synthase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: uridine(32) in tRNA = pseudouridine(32) in tRNA." [EC:5.4.99.28]
+xref: EC:5.4.99.28
+xref: RHEA:42544
+is_a: GO:0106029 ! tRNA pseudouridine synthase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26797" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-17T19:03:23Z
+
+[Term]
+id: GO:0160152
+name: tRNA pseudouridine(31) synthase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: uridine(31) in tRNA = pseudouridine(31) in tRNA." [EC:5.4.99.42]
+xref: EC:5.4.99.42
+xref: RHEA:42552
+is_a: GO:0106029 ! tRNA pseudouridine synthase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26797" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-17T19:05:18Z
+
+[Term]
+id: GO:0160153
+name: mitochondrial tRNA pseudouridine(27/28) synthase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: uridine(27/28) in mitochondrial tRNA = pseudouridine(27/28) in mitochondrial tRNA." [EC:5.4.99.44]
+xref: EC:5.4.99.44
+xref: RHEA:42560
+is_a: GO:0106029 ! tRNA pseudouridine synthase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26797" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-17T19:07:07Z
+
+[Term]
+id: GO:0160154
+name: tRNA pseudouridine(38/39) synthase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: uridine(38/39) in tRNA = pseudouridine(38/39) in tRNA." [EC:5.4.99.45]
+xref: EC:5.4.99.45
+xref: RHEA:42564
+is_a: GO:0106029 ! tRNA pseudouridine synthase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26797" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-17T19:11:20Z

**Comment by raymond91125** [comment]
Thanks. @sjm41

**Comment by sjm41** [comment]
Great! Thanks @raymond91125 !
