### ISSUE TITLE
Obsoletion request:GO:0031098 stress-activated protein kinase signaling cascade,  GO:0051403 stress-activated MAPK cascade and regulation children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26810]
Dear all, 

The proposal has been made to obsolete the following terms: 

- GO:0031098 stress-activated protein kinase signaling cascade
- GO:0051403 stress-activated MAPK cascade (replace by: GO:0000165 MAPK cascade) 
- GO:0032872 regulation of stress-activated MAPK cascade (replace by: GO:0043408 regulation of MAPK cascade)
- GO:0070302 regulation of stress-activated protein kinase signaling cascade
- GO:0032873 negative regulation of stress-activated MAPK cascade (replace by: GO:0043409 negative regulation of MAPK cascade)
- GO:0070303 negative regulation of stress-activated protein kinase signaling cascade
- GO:0032874 positive regulation of stress-activated MAPK cascade (replace by: GO:0043410 positive regulation of MAPK cascade)
- GO:0070304 positive regulation of stress-activated protein kinase signaling cascade

The reason for obsoletion is that these terms represent protein names, and most/all of the protein annotated respond to stress, but also respond to other stimuli. 

There are 159 annotations (including extensions) to these terms, see https://github.com/geneontology/go-annotation/issues/4930

Impacted groups: 
BHF-UCL	7
CAFA	7
CGD	8
dictyBase	1
FlyBase	12
MGI	38
PomBase	12
RGD	12
SGD	3
UniProt	57
WB	1

For the above groups, no action is needed if you agree with the automated replacement. 

+ 1 Reactome mapping, 2 InterPro and 2 UniRule. 

You can comment on the ticket: 

Thanks, Pascale

**Comment by pgaudet** [comment]
Copy-pasting an e-mail exchange onto the ticket

> I don’t think it is a good idea to obsolete these terms. The stress-activated signaling cascade is a well-known mechanism described in thousands of publications. It involves a specific family of protein kinases and it is really useful to build GO-CAM models.
We will definitively lose useful knowledge if we deprecate these terms. The stress response signaling are essential.
Thanks
Sylvain

> I agree with Sylvain. Here is a case where a name that sounds protein-specific has been applied to a class, and we need the class, perhaps with additional comments on proper usage.
Peter

**Comment by pgaudet** [comment]
Thanks for the feedback. Can you point to a specific pathway that we could describe in the term definitions? I am happy to keep terms if they can be defined accurately. The current definition of [stress-activated protein kinase signaling cascade](http://purl.obolibrary.org/obo/GO_0031098) is simply 
> The series of molecular signals in which a stress-activated protein kinase (SAPK) cascade relays a signal.

while other MAPK pathways are more more precise, for example: [p38MAPK cascade](http://purl.obolibrary.org/obo/GO_0038066): 
> A MAPK cascade containing at least the p38MAPK (MAPK14) MAP kinase, or Hog1 in yeast. It starts with the activation of a MAP3K, and the consecutive activation of a MPK2K and of p38MAPK. The cascade can also contain an additional tier: the upstream MAP4K. The kinases in each tier phosphorylate and activate the kinases in the downstream tier. The p38MAPK cascade is activated by stress signals, including hyperosmolarity, as well as by G protein-coupled receptors, growth factors, and cytokines, and results in cellular responses such as cell proliferation, cell differentiation, apoptosis and inflammation.


Also, looking at  annotations, it seems like SAPK often represents JNK, and there is a child of MAPK cascade that could be more appropriate: GO:0007254 JNK cascade. There are 67 EXP annotations to SAPK and stress-activated MAPK signaling, and at least 30 of these are to MAPK. 

Again, I am happy to keep the term if we can clearly describe the pathway, and how it differs from the parent MAPK cascade. 

Thanks, Pascale

**Comment by pgaudet** [comment]
I am removing the 'do not annotate' check on [response to stress](http://purl.obolibrary.org/obo/GO_0006950), to allow capturing this as an extension. After discussion we agreed that while this term is quite general, sometimes this describes the BP in which a protein is involved; more precise children would reflect the experimental details rather than the biology.

**Comment by suzialeksander** [comment]
Annotation Review is out-of-date and was closed
