### ISSUE TITLE
NTR: symbiont-mediated disruption of host neutrophil extracellular traps

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26811]
Please provide as much information as you can: 

* **Suggested term label:**

* **Definition (free text)**

* **Reference, in format PMID:#######**
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
- 'symbiont-mediated disruption of host cellular anatomical entity'

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
@genegodbold to provide references

**Comment by genegodbold** [comment]
These two **_blocks NET formation_**: 
- **Toll/interleukin-1 receptor domain-containing protein** (**TcpC**) from _Escherichia coli_: Recombinant TcpC enters neutrophils and blocks formation and release of neutrophil extracellular traps (NETs) which can form in the presence of bacteria, lipopolysaccharide (LPS), viruses, and PMA. Histone citrullination mediated by the peptidylarginine deiminase 4 (PAD4) is an essential step in NETosis. TcpC suppresses NETosis by promoting degradation of PAD4 via ubiquitination. TcpC is an E3 ubiquitin ligase that promotes ubiquitination of PAD4 [PMID:34108482].
- **Extracellular adherence protein** (Eap; MHC class II analog protein) from _Staphylococcus aureus_: EAP can bind and aggregate DNA. This suppresses the formation of host neutrophil extracellular traps (NETs)[PMID:30038902]. 

These are less weird:
- **Nuc** from _Neisseria gonorrhoeae_ enhances bacterial escape from killing by bactericidal neutrophil extracellular traps (NETs) by cleaving the nucleic acid fibers that compose the traps. Primary human neutrophils release NETs following contact with  N. gonorrhoeae, but NET integrity declines over time when Nuc-expressing bacteria are present [PMID:25605868].
- **_Streptococcus pyogenes_ nuclease A** (SpnA; Spy0747): SpnA is is a surface-anchored nuclease (DNase) critical for the destruction of neutrophil extracellular traps.  Both domains are required for activity and the C terminal DNase domain is 549-851. SpnA allows _S. pyogenes_ to survive and proliferate when exposed to whole blood killing assays. SpnA helps _S. pyogenes_ survive and proliferate to higher numbers when subjected to human neutrophil killing assays. Expression of SpnA by the non-pathogenic _Lactococcus lactis_ gives this bacterium the ability to degrade extracellular DNA, escape NETs and increase survival time in whole blood killing assays and neutrophil killing assays [PMID:21231972]. 
- **Endonuclease A** (EndA) from _Streptococcus pneumoniae_: EndA allows _S. pneumoniae_ to resist killing by the innate immune response.  It degrades neutrophil extracellular traps (NETs) in vitro [PMID:20846957]. S. pneumoniae strains expressing EndA are more invasive than non-EndA producing strains, penetrating tissues and reaching higher numbers in the lower respiratory tract and blood [PMID:16488875].
- **Sda1** from _Streptococcus pyogenes_: Sda1 is a deoxyribonuclease that helps group A streptococcus (GAS) escape from neutrophil extracellular traps, facilitating extracellular spread of the bacterium [PMID:22496650].

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141144
+name: symbiont-mediated disruption of host neutrophil extracellular traps
+namespace: biological_process
+def: "A process in which a symbiont damages or impairs host neutrophil extracellular traps.  The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:16488875, PMID:21231972, PMID:25605868]
+synonym: "symbiont-mediated perturbation of host neutrophil extracellular traps" EXACT []
+is_a: GO:0052008 ! symbiont-mediated disruption of host cellular anatomical entity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26811" xsd:anyURI
+created_by: pg
+creation_date: 2024-01-24T06:22:48Z
+
+[Term]
+id: GO:0141145
+name: symbiont-mediated suppression of host neutrophil extracellular trap formation
+namespace: biological_process
+def: "A process in which a symbiont inhibits or disrupts the formation of neutrophil extracellular traps by the host cell. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:30038902, PMID:34108482]
+synonym: "symbiont-mediated perturbation of host neutrophil extracellular trap formation" RELATED []
+synonym: "symbiont-mediated suppression of host neutrophil extracellular traps formation" EXACT []
+is_a: GO:0044068 ! symbiont-mediated perturbation of host cellular process
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26811" xsd:anyURI

**Comment by pgaudet** [comment]
https://github.com/geneontology/go-ontology/pull/26856
