### ISSUE TITLE
NTR: symbiont-mediated disruption of host tissue (was: symbiont-mediated disruption of host cell adhesion to extracellular matrix)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26814]
~+[Term]
+id: GO:0141143
+name: symbiont-mediated disruption of host cell adhesion to extracellular matrix
+namespace: biological_process
+def: "A process in which a symbiont alters or subverts cell adhesion to the extracellular matrix in its host. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:22534208, PMID:30345086]
+synonym: "disruption by symbiont of host cell-cell adhesion" EXACT []
+is_a: GO:0044068 ! symbiont-mediated perturbation of host cellular process
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25172" xsd:anyURI
+created_by: pg
+creation_date: 2024-01-17T15:47:43Z~

For GO-PathGO alignment

@genegodbold to provide references

**Comment by genegodbold** [comment]
So Pascale, I think I was mistaken about the term--most of these are NOT causing detachment of host cells from the host ECM but they DO seem to cause cell rounding and impaired association with other cells of the surrounding tissue.

- **Nonstructural protein 3** (NSP3; papain-like protease; Plpro) from SARS-CoV2: Inhibiting Nsp3 catalysis impairs the cytopathogenic effects of viral infection [PMID:32726803].
- Nonstructural protein 1 (NS1) from Dengue flavivirus: The NS1 of flaviviruses is a glycoprotein of 46-55 kDa necessary for viral replication in the host ER. NS1 homodimerizes in the ER, traffics through the Golgi, and is expressed on the surface of the infected cell. Some forms trimerize into soluble hexamers that get secreted [PMID:23523765]. Secreted NS1 from Dengue virus is recognized by host TLR4 molecules in both mouse macrophages and human peripheral blood mononuclear cells. in an _in vitro_ vascular model, NS1 from dengue virus induced leakage through disruption of the integrity of the endothelial monolayer. This leakage was inhibited by a TLR4 antagonist and by anti-TLR4 antibodies [PMID:26355031], [PMID:28220810]. Secreted NS1 can bind to the surface of endothelial cells and disrupt blood-tissue barriers by degrading the host glycocalyx [PMID:26355030]-[PMID:27416066], [PMID:34346770].
- **Cell-cycle inhibiting factor** (Cif) from _Escherichia coli_: Cif has a cytopathic effect on intestinal epithelial cells. This is characterized by a progressive recruitment of focal adhesion plaques leading to the assembly of stress fibers and inhibition of the cell cycle at the G2/M phase transition. Cells in this state do not mitose but continue to replicate DNA. EPEC and EHEC strains that lack Cif expression do not produce a cytopathic effect upon infection of host cells. This effect is restored upon complementation with functional Cif [PMID:14651638].
- **_Escherichia coli_ secreted protein C** (EspC): EspC is a serine protease autotransporter (class I SPATE) that was identified in enteropathogenic Escherichia coli (EPEC) as an enterotoxin that is cytotoxic/cytopathic for rat jejunal tissue in a manner similar to the plasmid-encoded toxin (Pet) from E. coli [PMID:11119520]. The damage caused to HEp-2 epithelial cells only manifests after four hours of exposure to recombinant EspC (900 nanomolar) and involves vacuolization, cell contraction with cytoplasm loss and actin filament loss, and cell rounding. EspC must enter the cell for these effects to arise [PMID:15155671]. Efficient delivery of EspC into the host cytoplasm by one hour requires contact with the host cell and a functional EPEC T3SS [PMID:18547338].
- **_Escherichia coli_ secreted protein G** (EspG): EspG1 of EPEC induces depletion of host tight junction protein tricellulin in a manner dependent on host microtubules. This leads to a significant loss of transepithelial resistance in Caco-2 cell monolayers. Effectors EspF, Map, and EspH had no effect on tricellulin disruption. Overexpression of tricellulin increases transepithelial resistance [PMID:27795363].
- **Extracellular serine protease** (EspP, protease secreted by STEC, PssA) from _Escherichia coli_: EspP/PssA is a plasmid-encoded serine protease secreted from that is cytotoxic to Vero cells and causes changes in actin morphologies [PMID:9379905]. It is a class-1 SPATE protein that proved to be only cytopathic and not cytotoxic to other cell lines [PMID:23689588]. EspP can polymerize and form cable-like structures that correlate with the cytopathic effects on cultured epithelial cells [PMID:20688909].

These DO cut extracellular matrix: Exfoliative toxin A and B are the specific virulence factors responsible for Staphylococcal scalded skin syndrome, a generalized blistering skin disease induced by S. aureus [PMID:11982763].
- **Exfoliative toxin A** from _Staphylococcus aureus_ cleaves desmoglein 1, a desmosomal adhesion molecule. Inactivation of desmoglein 1 results in the formation of blisters [PMID:11982763]. Desmoglein-1 plays a key role in maintaining the structure and barrier function of the epidermis.  Exfoliative toxins cleave a single peptide bond in the extracellular domain of desmoglein 1 and do not cleave the closely related molecules desmoglein 3 or E-cadherin. Loss of desmoglein 1 results in the loss of intercellular adhesion and allows bacteria to form blisters under the epithelial sheet, providing protective niches in which they can survive and proliferate. Exfoliative toxins produced by S. aureus rapidly diffuse into the skin tissue [PMID:16102958]. ETA causes disorganization and disruption of the startus spinosum and the stratum granulosum, two cellular layers of epidermis [PMID:9261066].
- **Exfoliative toxin C** (ExhC) from Staphylococcus sciuri: ExhC targets swine desmoglein, a cell-cell adhesion molecule in desmosomes predominantly found in skin keratinocytes, for proteolytic destruction [PMID:16238811].
- **Fragilysin** (_Bacteroides fragilis_ toxin; BFT): Fragilysin is a divalent zinc cation-dependent proteinase with autocatalytic activity. There are three variants of the metalloprotease. It has type IV collagenase activity. Fragilysin has in vitro proteolytic activity toward the cytoskeletal/ extracellular matrix proteins actin, gelatin, casein and, to a lesser degree, tropomyosin and fibrinogen. Fragilysin does not hydrolyze collagen I and V, fibronectin, laminin, elastin, human IgA, or bovine serum albumin [PMID:10994529]. Fragilysin cleaves host cadherin, resulting in the dissociation of tight junction components and the increased permeability of endothelial cell monolayers [PMID:11093933].

**Comment by pgaudet** [comment]
We will create a more general term instead: 

+[Term]
+id: GO:0141146
+name: symbiont-mediated disruption of host tissue
+namespace: biological_process
+def: "The process in which an organism effects a change that impairs the structure or function of a host tissue. This can occur via the disruption of the extracellular matrix, or the detachment of cells from the extracellular matrix, or the dissociation of the cells composing that tissue. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:11982763, PMID:14651638, PMID:26355030]
+synonym: "cytopathogenic effect" RELATED []
+is_a: GO:0052111 ! symbiont-mediated disruption of host anatomical structure
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26814" xsd:anyURI
+created_by: pg
+creation_date: 2024-01-24T15:36:58Z

& obsolete GO:0141143
+name: symbiont-mediated disruption of host cell adhesion to extracellular matrix with replace_by GO:0141146
+name: symbiont-mediated disruption of host tissue
