### ISSUE TITLE
Change parent and definition 'GO:0070360 actin polymerization-dependent cell migration in host' 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26813]
GO:0070360 actin polymerization-dependent cell migration in host'  should be is_a  'GO:0106259 cell-to-cell migration in host'

**Comment by pgaudet** [comment]
@genegodbold to provide references for the new term 'symbiont-mediated migration across host tissue barrier'

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141142
+name: symbiont-mediated migration across host tissue barrier
+namespace: biological_process
+def: "A process in which a symbiont moves across a tissue barrier of the host to transports itself across an extracellular cellular matrix barrier or between cells. This involves the temporary or permanent breaching of the tissue barrier." [GOC:curators]
+is_a: GO:0044001 ! migration in host
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26813" xsd:anyURI
+created_by: pg
+creation_date: 2024-01-17T15:32:41Z
+

**Comment by genegodbold** [comment]
These are mostly bacterial with a few viral--these are taken from a category I have called "Dissemination in Host" so they might not all breach tissue barriers. But they all allow dissemination in the host.

- **Collagenase A** (**ColA**) from _Leptospira sp_ (UniProt:A0A098MT76): A bacterial mutant in which the colA gene is deleted is attenuated for transcytosis through HEK293 and HUVEC monolayers. In a hamster model of leptospiral disease, the mutant leptospires were less disseminated and the median lethal dose was reduced by 25-fold [PMID:24277745].
- **Anthrolysin O** from _Bacillus anthracis_: Anthrolysin O can disrupt intestinal tissue barrier function in a mouse model of infection. Barrier disruption and bacterial invasion into tissues requires anthrolysin O [PMID:20188700].
- **Complement-inhibitor and Plg-binding protein** of _Acinetobacter baumannii_ (**CipA**): Attachment and subsequent activation of host plasminogen by CipA allows the bacteria to penetrate epithelial layers. Bacteria that do not encode CipA are defective at penetrating epithelial monolayers _in vitro_ [PMID:26681776].
- **BslA** from _Bacillus anthracis_: BslA contributes to the penetration of the blood-brain barrier [PMID:19820089].
- **Exolysin** (ExlA, TpsA) from _Pseudomonas aeruginosa_: ExlA endows the bacteria with the ability to proliferate in lungs and to disseminate from lungs to other organs: liver, spleen, kidney and brain. The rupture of the alveolo-capillary barrier induced by ExlA opens the passage to the blood compartment allowing bacterial dissemination [PMID:29120408].
- **A36** from Vaccinia virus: Phosphorylation of vaccinia virus protein A36 at Tyr112 and  Tyr132 is necessary for the recruitment of host Grb2 which stabilizes a protein complex consisting of host Nck, WIP, and N-WASP beneath the virus. This eventually stimulates the actin-nucleating activity of the host Arp2/3 complex resulting in the formation of an actin tail and projecting a virion into neighboring cells [PMID:12007418], [PMID:19262673] [PMID:8832396].
- **Glycoprotein E** (US8) and **Glycoprotein I** (US7) from human herpesvirus 1 (HHV-1): The gE-gI complex seems to mediate cell-to-cell spread of HHV-1 across cell junctions by interacting with host components of the cell junctions [PMID:9765438], [PMID:11134295].
- Hemolysin/Cytolysin **Vvha** and **Repeats-in-toxin A** (RtxA, Multifunctional-autoprocessing repeats-in-toxin, MARTX, peptidase C80) from _Vibrio vulnificus_: It is thought that the activity of MARTX and VvhA help the bacteria invade across the colonic epithelium during infection [PMID:22457618].
- **Macrophage infectivity potentiator** (Mip; lpg0791) from _Legionella pneumophila_: Mip adheres to ECM collagen (types 1-6) and allows the bacteria to transmigrate across lung epithelial cells growing on an ECM barrier. Mip is a peptidyl prolyl cis-trans isomerase and inhibition of this activity prevented transmigration. In a guinea pig model of infection, Mip contributes to the bacterial dissemination within the lung tissue and the spread of bacteria to the spleen [PMID:16953800].

**Comment by pgaudet** [comment]
Added references to the term definition.
