### ISSUE TITLE
Term merge: 4-hydroxybenzoate polyprenyltransferase GO terms (EC:2.5.1.39)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26830]
EC:2.5.1.39 is:
name: 4-hydroxybenzoate polyprenyltransferase
reaction: 4-hydroxybenzoate + an all-trans-polyprenyl diphosphate <=> a 4-hydroxy-3-all-trans-polyprenylbenzoate + diphosphate
Comments include: The number of isoprenoid subunits in the side chain varies in different species. The enzyme does not have any specificity concerning the length of the polyprenyl tail, and accepts tails of various lengths with similar efficiency. 

So I think the three GO terms with EC:2.5.1.39 xref (shown below) need to be merged into a new term (with RHEA:44504 & MetaCyc:RXN-11368 xrefs):

name: 4-hydroxybenzoate polyprenyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 4-hydroxybenzoate + an all-trans-polyprenyl diphosphate = a 4-hydroxy-3-all-trans-polyprenylbenzoate + diphosphate. [RHEA:44504]
synonym: [include all synonyms from merged terms, exact/broad as appropriate?]
xref: EC:2.5.1.39
xref: MetaCyc:RXN-11368
xref: RHEA: 44504
is_a: GO:0002094 ! polyprenyltransferase activity

===

id: GO:0008412 (5 EXP annotations, to ubiA, COQ2 and ppt1)
name: 4-hydroxybenzoate octaprenyltransferase activity
namespace: molecular_function
alt_id: GO:0000043
alt_id: GO:0048043
alt_id: GO:0048044
def: "Catalysis of the reaction: farnesylfarnesylgeranyl diphosphate + p-hydroxybenzoate = 3-octaprenyl-4-hydroxybenzoate + diphosphate." [RHEA:27782]
synonym: "4-HB polyprenyltransferase activity" EXACT []
synonym: "para-hydroxybenzoate transferase activity" EXACT []
synonym: "para-hydroxybenzoate-polyprenyl diphosphate transferase activity" EXACT []
synonym: "para-hydroxybenzoate:polyprenyltransferase activity" EXACT []
synonym: "PHB polyprenyl diphosphate transferase activity" EXACT []
xref: EC:2.5.1.39
xref: MetaCyc:4OHBENZOATE-OCTAPRENYLTRANSFER-RXN
xref: RHEA:27782
is_a: GO:0002094 ! polyprenyltransferase activity

id: GO:0047293 (1 EXP annotation to PPT1)
name: 4-hydroxybenzoate nonaprenyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: p-hydroxybenzoate + solanesyl pyrophosphate = nonaprenyl-4-hydroxybenzoate + diphosphate." [EC:2.5.1.39, MetaCyc:2.5.1.39-RXN]
synonym: "4-hydroxybenzoate transferase activity" RELATED [EC:2.5.1.39]
synonym: "nonaprenyl-4-hydroxybenzoate transferase activity" RELATED [EC:2.5.1.39]
synonym: "p-hydroxybenzoate dimethylallyltransferase activity" RELATED [EC:2.5.1.39]
synonym: "p-hydroxybenzoate polyprenyltransferase activity" RELATED [EC:2.5.1.39]
synonym: "p-hydroxybenzoic acid-polyprenyl transferase activity" RELATED [EC:2.5.1.39]
synonym: "p-hydroxybenzoic-polyprenyl transferase activity" RELATED [EC:2.5.1.39]
synonym: "solanesyl-diphosphate:4-hydroxybenzoate nonaprenyltransferase activity" RELATED [EC:2.5.1.39]
xref: EC:2.5.1.39
xref: MetaCyc:2.5.1.39-RXN
xref: RHEA:17709
is_a: GO:0002094 ! polyprenyltransferase activity

id: GO:0002083 (3 EXP annotations, to COQ2 and ppt1)
name: 4-hydroxybenzoate decaprenyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: all-trans-decaprenyl diphosphate + 4-hydroxybenzoate = 3-decaprenyl-4-hydroxybenzoate + diphosphate." [MetaCyc:RXN-9230]
xref: EC:2.5.1.39
xref: MetaCyc:RXN-9230
xref: RHEA:44564
is_a: GO:0002094 ! polyprenyltransferase activity

**Comment by sjm41** [comment]
@pgaudet I think this 3-way merge is straightforward - are you OK to take this, or should I reassign @raymond91105 ?

**Comment by sjm41** [comment]
Yes! That would also work.

**Comment by pgaudet** [comment]
Sibling: [1,4-dihydroxy-2-naphthoate octaprenyltransferase activity](http://purl.obolibrary.org/obo/GO_0046428)
Fix RHEA to more general reaction RHEA:26478

Fix label: from  1,4-dihydroxy-2-naphthoate octaprenyltransferase activity to 1,4-dihydroxy-2-naphthoate polyprenyltransferase activity

Fix definition to match RHEA: from Catalysis of the reaction: 1,4-dihydroxy-2-naphthoate + polyprenylpyrophosphate = dimethylmenaquinone + diphosphate + CO2." [RHEA:30099] to 
+def: "Catalysis of the reaction: 1,4-dihydroxy-2-naphthoate + an all-trans-polyprenyl diphosphate + H+ = a 2-demethylmenaquinol + CO2 + diphosphate."
