### ISSUE TITLE
Term merge: Prenyltransferase term merges

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26832]
Whilst working on #26829, I found that the following pairs of terms are identical and need merging:

GO:0010356 & GO:0102551
GO:0102661 & GO:0010357
GO:0047294 & GO:0043889
GO:0043888 & GO:0047295

====

id: GO:0010356
name: homogentisate geranylgeranyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: homogentisic acid + geranylgeranyl diphosphate = 2-methyl-6-geranylgeranylplastoquinol." [PMID:16989822]
xref: EC:2.5.1.116
is_a: GO:0010354 ! homogentisate prenyltransferase activity

id: GO:0102551
name: homogentisate geranylgeranyl transferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2-trans,6-trans,10-trans-geranylgeranyl diphosphate + homogentisate + H+ = diphosphoric acid + 2-methyl-6-geranylgeranyl-1,4-benzoquinol + carbon dioxide." [EC:2.5.1.116, GOC:pz]
xref: EC:2.5.1.116
xref: MetaCyc:RXN-14929
xref: RHEA:38003
is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups

===

id: GO:0102661
name: homogentisate solanyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: all-trans-nonaprenyl diphosphate + homogentisate + H+ = 2-methyl-6-all-trans-nonaprenyl-1,4-benzoquinone + carbon dioxide + diphosphoric acid." [EC:2.5.1.117, GOC:pz]
xref: EC:2.5.1.117
xref: MetaCyc:RXN-2761
is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups

id: GO:0010357
name: homogentisate solanesyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: all-trans-nonaprenyl diphosphate + H(+) + homogentisate = 2-methyl-6-all-trans-nonaprenylbenzene-1,4-diol + CO2 + diphosphate. 2-methyl-6-solanyl-1,4-benzoquinonone is also known as 2-methyl-6-solanesylplastoquinol and all-trans-nonaprenyl diphosphate as solanesyl diphosphate." [PMID:16989822, RHEA:37995]
xref: EC:2.5.1.117
xref: RHEA:37995
is_a: GO:0010354 ! homogentisate prenyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26829" xsd:anyURI

===

id: GO:0047294
name: phosphoglycerol geranylgeranyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: sn-glycerol 1-phosphate + all-trans-geranylgeranyl diphosphate = sn-3-O-(geranylgeranyl)glycerol 1-phosphate + diphosphate." [EC:2.5.1.41, RHEA:23404]
synonym: "geranylgeranyl diphosphate:sn-glyceryl phosphate geranylgeranyltransferase activity" RELATED [EC:2.5.1.41]
synonym: "geranylgeranyl-transferase activity" RELATED [EC:2.5.1.41]
synonym: "glycerol phosphate geranylgeranyltransferase activity" RELATED [EC:2.5.1.41]
xref: EC:2.5.1.41
xref: KEGG_REACTION:R04158
xref: MetaCyc:2.5.1.41-RXN
xref: RHEA:23404
is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups

id: GO:0043889
name: (S)-3-O-geranylgeranylglyceryl phosphate synthase activity
namespace: molecular_function
def: "Catalysis of the reaction:(2E,6E,10E)-geranylgeranyl diphosphate + sn-glycerol 1-phosphate = diphosphate + sn-3-O-(geranylgeranyl)glycerol 1-phosphate." [PMID:12801917, PMID:17253090, PMID:8408023, RHEA:23404]
comment: This function is involved in archaeal lipid synthesis.
synonym: "(S)-3-O-geranylgeranylglycerylphosphate synthase activity" EXACT []
synonym: "(S)-GGGP synthase activity" EXACT []
synonym: "GGGP synthase activity" EXACT []
synonym: "GGGPS" EXACT []
xref: EC:2.5.1.41
is_a: GO:0004659 ! prenyltransferase activity

===

id: GO:0043888
name: (S)-2,3-di-O-geranylgeranylglyceryl phosphate synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: (2E,6E,10E)-geranylgeranyl diphosphate + sn-3-O-(geranylgeranyl)glycerol 1-phosphate = 2,3-bis-O-(geranylgeranyl)-sn-glycerol 1-phosphate + diphosphate." [PMID:15356000, PMID:16494480, RHEA:18109]
comment: This function is involved in archaeal lipid synthesis.
synonym: "2,3-dGGGPS" EXACT []
synonym: "DGGGP synthase activity" EXACT []
synonym: "DGGGPS" EXACT []
synonym: "UbiA" RELATED []
xref: EC:2.5.1.42
is_a: GO:0002094 ! polyprenyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26829" xsd:anyURI

id: GO:0047295
name: geranylgeranylglycerol-phosphate geranylgeranyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: sn-3-O-(geranylgeranyl)glycerol 1-phosphate + all-trans-geranylgeranyl diphosphate = 2,3-di-O-(geranylgeranyl)glycerol 1-phosphate + diphosphate." [EC:2.5.1.42, RHEA:18109]
synonym: "geranylgeranyl diphosphate:sn-3-O-(geranylgeranyl)glycerol 1-phosphate geranylgeranyltransferase activity" RELATED [EC:2.5.1.42]
synonym: "geranylgeranyloxyglycerol phosphate geranylgeranyltransferase activity" RELATED [EC:2.5.1.42]
synonym: "geranylgeranyltransferase II" RELATED [EC:2.5.1.42]
xref: EC:2.5.1.42
xref: KEGG_REACTION:R04520
xref: MetaCyc:2.5.1.42-RXN
xref: RHEA:18109
is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups

**Comment by raymond91125** [comment]
Dear all,

The proposal has been made to obsolete GO:0102551homogentisate geranylgeranyl transferase activity.

    The reason for obsoletion is that this term is equivalent to GO:0010356 homogentisate geranylgeranyl transferase activity.

There are no experimental annotations to this term.
There are no mappings to this term.
This term is not present in any subset.

This term is being replaced by GO:0010356 homogentisate geranylgeranyl transferase activity.

Any comments can be added to the issue: geneontology/go-ontology#26832

Thanks,

Raymond

**Comment by raymond91125** [comment]
Dear all,

The proposal has been made to obsolete GO:0102661 homogentisate solanyltransferase activity.

    The reason for obsoletion is that this term is equivalent to GO:0010357 homogentisate solanesyltransferase activity

There are no experimental annotations to this term.

There are no mappings to this term.

This term is not present in any subset.

This term is being replaced by GO:0010357 homogentisate solanesyltransferase activity.

Any comments can be added to the issue: geneontology/go-ontology#26832.

Thanks,

**Comment by raymond91125** [comment]
Dear all,

The proposal has been made to obsolete GO:0043889 (S)-3-O-geranylgeranylglyceryl phosphate synthase activity.

    The reason for obsoletion is that this term is equivalent to GO:0047294 phosphoglycerol geranylgeranyltransferase activity.

There are no experimental annotations to this term.
There are no mappings to this term.
This term is not present in any subset.

This term is being replaced by GO:0047294 phosphoglycerol geranylgeranyltransferase activity.

Any comments can be added to the issue: geneontology/go-ontology#26832

Thanks,

**Comment by raymond91125** [comment]
Dear all,

The proposal has been made to obsolete GO:0043888 (S)-2,3-di-O-geranylgeranylglyceryl phosphate synthase activity.

    The reason for obsoletion is that this term is equivalent to GO:0047295 geranylgeranylglycerol-phosphate geranylgeranyltransferase activity.

There are no experimental annotations to this term.
There are no mappings to this term.
This term is not present in any subset.

This term is being replaced by GO:0047295 geranylgeranylglycerol-phosphate geranylgeranyltransferase activity.

Any comments can be added to the issue: geneontology/go-ontology#26832

**Comment by sjm41** [comment]
Thanks @raymond91125 !
