### ISSUE TITLE
decaprenyl diphosphate synthase complex (GO:0032476)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26833]
I was looking at these 3 terms:
```
decaprenyl diphosphate synthase complex (GO:0032476) [13 annotations]
   |_heterotetrameric decaprenyl diphosphate synthase complex (GO:0032478) [0 annotations]
   |_homodimeric decaprenyl diphosphate synthase complex (GO:0032477) [0 annotations]
```
id: GO:0032476
name: decaprenyl diphosphate synthase complex
def: "A complex that possesses di-trans,poly-cis-decaprenylcistransferase activity; involved in ubiquinone biosynthesis." [GOC:mah, PMID:14519123]
subset: goslim_pir
intersection_of: GO:1902494 ! catalytic complex
intersection_of: capable_of GO:0008834 ! di-trans,poly-cis-decaprenylcistransferase activity

id: GO:0032477
name: homodimeric decaprenyl diphosphate synthase complex
def: "A homodimeric complex that possesses di-trans,poly-cis-decaprenylcistransferase activity; involved in ubiquinone biosynthesis." [PMID:14519123]
is_a: GO:0032476 ! decaprenyl diphosphate synthase complex
relationship: part_of GO:0005737 ! cytoplasm

id: GO:0032478
name: heterotetrameric decaprenyl diphosphate synthase complex
def: "A heterotetrameric complex located in the mitochondrial inner membrane that possesses di-trans,poly-cis-decaprenylcistransferase activity; involved in ubiquinone biosynthesis. In S. pombe it is a heterotetramer of Dlp1 and Dps1." [PMID:14519123]
is_a: GO:0032476 ! decaprenyl diphosphate synthase complex
relationship: part_of GO:0005743 ! mitochondrial inner membrane
relationship: part_of GO:0031966 ! mitochondrial membrane

The only EXP or Swiss-Prot annotations to the parent term are from PMID:14519123 for these two pombe genes (@ValWood ):
UniProtKB:O13851 	dlp1
UniProtKB:O43091 	dps1

This reveals a few problems:
- PMID:14519123 says the pombe enzyme generates ubiquinone-10, but the GO defs above refer to "di-trans,poly-cis-decaprenylcistransferase activity" (= GO:0008834, EC:2.5.1.31), which generates "di-trans-poly-cis-undecaprenyl diphosphate", where "undeca" means 11.
- Morevoer, the UniProt pages for the pombe proteins have EC:2.5.1.91 (= GO:0097269, all-trans-decaprenyl-diphosphate synthase activity)
- A later paper on the mouse & human enzymes (PMID:16262699) shows that they produce ubiquinone-9 or ubiquinone-10, respectively. Those proteins were annotated with:
Mouse Pdss1/Pdss2:
- GO:0000010	trans-hexaprenyltranstransferase activity (EC:2.5.1.30) - WRONG
- GO:0052923	all-trans-nonaprenyl-diphosphate synthase (geranyl-diphosphate specific) activity (EC:2.5.1.84) - CORRECT
Humans PDSS1/PDSS2:
- GO:0000010	trans-hexaprenyltranstransferase activity (EC:2.5.1.30) - WRONG
- GO:0097269	all-trans-decaprenyl-diphosphate synthase activity (EC:2.5.1.91) - CORRECT

Ontology Tasks:
- [x] change name of GO:0008834 from "di-trans,poly-cis-decaprenylcistransferase activity" to "di-trans,poly-cis-undecaprenyl-diphosphate synthase activity" to match EC and format of sister terms
- [x] change name of GO:0032476 and two children from "decaprenyl diphosphate synthase complex" to "polyprenyl diphosphate synthase complex" (to take account of mouse data)
- [x] generalise the def on GO:0032476 and children so it says "...that possesses polyprenyl diphosphate synthase activity involved in the synthesis of the isoprenoid chain of ubiquinone whose length varies between organisms" and add PMID:16262699 as a reference.
- [x] change capable_of relation on GO:0032476 to more general GO:0004659 prenyltransferase activity term

Annotation tasks (should I make a separate ticket on the annotation tracker for these??):
- [x] remove incorrect GO:0000010 annotations from PMID:16262699
- [x] improve annotation of human and mouse proteins in PMID:16262699 from "transferase complex" to GO:0032478
- [x] improve annotation of pombe proteins in PMID:14519123 from "decaprenyl diphosphate synthase complex" to GO:0032478
- [x] change MF annotations on pombe proteins in PMID:14519123 from "di-trans,poly-cis-decaprenylcistransferase activity" to "all-trans-decaprenyl-diphosphate synthase activity"

**Comment by ValWood** [comment]
Pombe done, Thanks!

**Comment by ValWood** [comment]
@RLovering is still working ;)

**Comment by RLovering** [comment]
Hi Steven
thanks for the update. The correct terms were not available in 2006 ;) but great to see that better terms are now available. I have updated these as you suggested. As the qualifier I had used was more appropriate I have updated these rather than deleting them. 
HGNU are for the annotations that myself and Varsha created while HGNC was at UCL, HGNC annotations are those created once HGNC moved to EBI. 
Yes probably the only unpaid curator still weirdly trying to address the back log of annotations that need to be revised. Please remove the alerts from these annotations.
Best
Ruth

**Comment by ValWood** [comment]
So this is what retirement looks like ;)

**Comment by sjm41** [comment]
Hi @RLovering ! Glad you're keeping busy!
Thanks for updating the annotations, but they are the wrong way way round - the two mouse proteins (Q33DR2 and Q33DR3) should have "all-trans-nonaprenyl-diphosphate synthase (geranyl-diphosphate specific) activity" while the two human proteins (Q5T2R2 and Q86YH6) should have "all-trans-decaprenyl-diphosphate synthase activity". Can you amend? Thanks!

**Comment by RLovering** [comment]
Oh dear, now that MGI and SwissProt have updated their annotations I have to delete these. I should have paid more attention, obviously ;)

Thanks for letting me know

Ruth

**Comment by sjm41** [comment]
OK, thanks @RLovering !

**Comment by sjm41** [comment]
For this term:

id: GO:0032476
name: polyprenyl diphosphate synthase complex
namespace: cellular_component
def: "A complex that possesses polyprenyl diphosphate synthase activity involved in the synthesis of the isoprenoid chain of ubiquinone whose length varies between organisms." [GOC:mah, PMID:14519123, PMID:16262699]
subset: goslim_pir
synonym: "decaprenyl diphosphate synthase complex" NARROW []
intersection_of: GO:1902494 ! catalytic complex
intersection_of: capable_of GO:0004659 ! prenyltransferase activity

Should update the capable_of to use the new term "GO:0120531 prenyl diphosphate synthase activity"
