### ISSUE TITLE
NTR: virus-like capsid

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#26842]
* **Suggested term label:**
* virus-like capsid

* **Definition (free text):**
* A protein coat that surrounds nucleic acid to form a structure similar to a virus capsid.  Virus-like capsids are non-infectious and are encoded by endogenous (non-viral) genes. Fly and tetrapod Arc (ancestrally-related to retrotransposon Gag) are examples of  proteins that can self-assemble into capsid-like structures which encapsulate Arc mRNA and mediate the intercellular transmission of RNA.  

* **Reference"**
* PMID:29328916

* **Gene product name and ID to be annotated to this term:**
* Arc1, FBgn0033926

* **Parent term(s):**
* Not sure where this should sit:
GO:0032991 protein-containing complex?
as these are incorporarted in to extracellular vesicles, could be "part of" GO:1903561 

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
* virus-like particle (NARROW)

* **Any other information**
* I've suggested virus-like capsid as the term rather than virus-like particle, as this term can also be used for bacteriophages and is used to describe pharma-type delivery systems.

**Comment by edwong57** [comment]
Cellular anatomical entity seemed a reasonable parent for this term. I didn't add "part of" GO:1903561 as it wasn't clear to me that these were always incorporated into extracellular vesicles.

**Comment by cmungall** [comment]
This is a pretty interesting gene!

@hatrill, are you also requesting a process term too (assembly)? IMO a
high-level CC annotation for this gene doesn't add much. The uniprot entry
has quite a rich yet concise function statement (
https://www.uniprot.org/uniprotkb/Q7K1U0/entry)

"Master regulator of synaptic plasticity that self-assembles into
virion-like capsids that encapsulate RNAs and mediate intercellular RNA
transfer from motorneurons to muscles"

Is "virus-like capsid" the best label? Might this encompass too much? In
general "other" or "X-like" terms are a bad smell in ontologies.

It looks like the fly protein shares a domain with a yeast protein that is
classified as GO:0000943 ! retrotransposon nucleocapsid, also under
cellular anatomical entitu
https://www.uniprot.org/uniprotkb/Q12173/entry

Wouldn't it be true to say this is also both a capsid, and virus-like, and
hence a virus-like capsid? In fact the uniprot text description says
"virus-like particle (VLP)". In which case this would
be classified under the new term?

Would instead the following make sense:

- capsid (NEW)
---- viral or virion capsid (EXISTS)
---- retrotransposon nucleocapsid (EXISTS)
---- host genome encoded / domesticated capsid (THIS TERM)

Not sure if it's always clear when a TE is domesticated though?

My proposed structure above also conflates capsid and nucleocapsid. But
isn't the term under discussion also a nucleocapsid (shell + enclosed RNA)?

I'm a bit confused about GO's own views on this as we classify "viral
nucleocapsid" as a part-of of "viral capsid" but that seems like
classifying an egg as being part of an eggshell. I don't quite get when one
would annotate a gene to nucleocapsid vs capsid.

Interesting!

**Comment by hattrill** [comment]
1. For the name, I considered virus-like particle but so I chose it as a synonym rather than the name as this term often used for bacteriophage capsids (and in pharmacological preparations). Virus-like capsid was also used in the literature to describe this structure, so went with this and is accurate for use. Another alternative name I considered was "endogenous capsid" or "host capsid", but I have never seen them in use and they seem a bit subjective. So, I still think "virus-like capsid" is the best compromise here.

2. I think that the process described here best comes under intercellular transport rather than an assembly BP. There is some intersection with extracellular vesicle/exosomes-mediated processes. Marked this down as something to explore in the future as this field is more defined now - but will have to find an expert or experts.

3. I like the suggestion of placing it under a generic capsid parent:

- capsid (NEW)
	|__viral capsid
	|__retrotransposon nucleocapsid
	|__virus-like capsid

but also agree that "viral capsid" should be part_of "viral nucleocapsid".

The viral nucleocapsid is the capsid + nucleic acid + other proteins that may complex with the nucleic acid inside or other things needed to kick off immediately upon infection.

Looking at the experimental annotations to "viral nucleocapsid" they have mainly been used for nucleic acid interacting proteins rather than capsid compoments. Perhaps we could review these and make viral nucleocapsid the term "on top"

For consistency we may want to have "nucleocapsid" as the parent across, but then we would also want to have terms that represented the capsid as part of the structure as well.

This would look like:
_nucleocapsid
  	|__viral nucleocapsid
           ___(p)viral capsid
	|__retrotransposon nucleocapsid
           ___(p)retrotransposon capsid (NEW)
	|__virus-like nucleocapsid
           ___(p)retrotransposon capsid (NEW)
  __(p)capsid (NEW)
	|___viral capsid
	|___retrotransposon capsid
	|___virus-like capsid

May be over-kill for the handful of virus-like/retrotransposon proteins, but for viruses, would be worth the effort. Think that is a question I would punt back to GO! @cmungall

**Comment by cmungall** [comment]
We're a bit outside the scope of the original (closed) issue so I made a new one: #26910
