### ISSUE TITLE
Term name & textual & definition update: GO:0009331 glycerol-3-phosphate dehydrogenase complex

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26862]
* **GO term ID and label for which you request a definition update**
GO:0009331 glycerol-3-phosphate dehydrogenase complex

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
Current def is "An enzyme complex that catalyzes the dehydrogenation of sn-glycerol 3-phosphate to form glycerone phosphate. PMID:7576488", with a 'capable of' relation to GO:0004368 glycerol-3-phosphate dehydrogenase (quinone) activity (= EC:1.1.5.3)

PMID:7576488 is specifically about a heterotrimeric bacterial enzyme that has EC:1.1.5.3 activity.
As far as I can tell, the eukaryotic EC:1.1.5.3 enzyme is not a complex, but a single protein (e.g. human GPD2/P43304).

So, I think the name and def of GO:0009331 need improving to reflect all this.

- [ ] Improve def to "A heterotrimeric enzyme complex present in bacteria that is essential for anaerobic growth on glycerol-3-phosphate. It catalyzes the dehydrogenation of sn-glycerol 3-phosphate to form glycerone phosphate. PMID:3286606, PMID:7576488"

- [ ] Change name to "anaerobic glycerol-3-phosphate dehydrogenase complex"

- [ ] Might also want a taxon constraint and need an annotation review @pgaudet ?

* **Additional information**
See https://github.com/geneontology/go-annotation/issues/4952 for related InterPro2GO issue.

**Comment by pgaudet** [comment]
Thanks @sjm41 

**EXP:** There is a single bacterial annotation to the term, see https://github.com/geneontology/go-annotation/blob/master/reports/4953/GO_0009331.tsv

**Mappings:**  seem to cause problems. I will request changes here: https://github.com/geneontology/go-annotation/issues/4953

**Comment by pgaudet** [comment]
Added Taxon constraint 'only in prokaryotes' , since in Archae this is also a complex, see  PMID:30583977

**Comment by sjm41** [comment]
"GO:0009331 glycerol-3-phosphate dehydrogenase complex" is for the EC:1.1.5.3 (quinone-dependent) complex - which appears to be a heterotrimer found in bacteria.
PMC6450551 is about the different (but related!) EC:1.1.1.8 (NAD-dependent) complex, which appears to be a homodimer. I don't think we have a GO-CC term for this (and I'm not proposing we make one).

**Comment by sjm41** [comment]
> EXP: There is a single bacterial annotation to the term, see https://github.com/geneontology/go-annotation/blob/master/reports/4953/GO_0009331.tsv

That annotation is to E.coli glpD from PMID:18296637, where it's described as a homodimer with EC:1.1.5.3 (quinone-dependent) activity. Also see https://www.uniprot.org/uniprotkb/P13035/entry.

So we need to decide if "GO:0009331 glycerol-3-phosphate dehydrogenase complex" is meant to only describe the heterotrimeric (glpA-glpB-glpC) EC:1.1.5.3 complex (as per the PMID:7576488 reference in the original def), or is also meant to encompass the homodimeric glpD EC:1.1.5.3 enzyme.

**Comment by sjm41** [comment]
@pgaudet We decided above that GO:0009331 should have the taxon constraint "only in prokaryotes", but QuickGO says that the current constraint is "only in cellular organisms" (https://www.ebi.ac.uk/QuickGO/term/GO:0009331).
Can you check please?

**Comment by pgaudet** [comment]
Thanks @sjm41 

Looks like this wasn't done!
