### ISSUE TITLE
Obsoletion request: GO:0061778 intracellular chloride channel activity and child GO:0005229 intracellular calcium activated chloride channel activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26874]
GO:0061778 intracellular chloride channel activity
and child GO:0005229 intracellular calcium activated chloride channel activity

The reason for obsoletion is that these represent a mix of a MF + a CC. 

Replace by parent: GO:0005254 chloride channel activity

Thanks, Pascale

**Comment by raymond91125** [comment]
@pgaudet Do you not agree that intracellular calcium activated chloride channel activity and it's regulations should be kept? These channels are a sub-type of intracellularly calcium-gated channel activity, a term you recently created. Thanks.

**Comment by pgaudet** [comment]
Hi @raymond91125 

The regulation terms need to go for sure, because for the BO refactor we want to obsolete all children of 'regulation of MF'. 

I need to look more into the term' intracellular chloride channel activity', it seems we are mixing a MF and a CC.

**Comment by raymond91125** [comment]
> I need to look more into the term' intracellular chloride channel activity', it seems we are mixing a MF and a CC.

I agree. I moved intracellular calcium activated chloride channel activity from under 'intracellular chloride channel activity'. 'intracellular calcium activated chloride channel activity' is about plasma membrane Cl- channels that have an intracellular Ca2+-binding site. Thus I would keep the term 'intracellular calcium activated chloride channel activity'.

**Comment by pgaudet** [comment]
> intracellular calcium activated chloride channel activity' is about plasma membrane Cl- channels that have an intracellular Ca2+-binding site.


Oh - I was capturing these as 'intracellularly gated' - is that what you mean here?

**Comment by raymond91125** [comment]
> Oh - I was capturing these as 'intracellularly gated' - is that what you mean here?

That's right. I regard activated and gated synonymous.

**Comment by pgaudet** [comment]
OK sounds good - can you rename 'intracellular calcium activated chloride channel activity' to the same pattern as the siblings, ie 'intracellularly calcium-gated chloride channel activity'? 

Thanks, Pascale
