### ISSUE TITLE
NTR: Crinophagy

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#26875]
Crinophagy terms:
crinophagy and secretory granule-lysosome fusion 

Term 1
* **Suggested term label:**
crinophagy

* **Definition (free text)**
The autophagic process which involves the direct fusion of abnormal, excess or obsolete secretory granules with lysosomes. This pathway is often associated associated with maintaining homeostasis in endocrine cells and exocrine cells.

* **Reference, in format PMID:#######**
PMID:29066608
Snapshot review: PMID: 35452619

* **Gene product name and ID to be annotated to this term**
Rab2
FBgn0014009

* **Parent term(s)**

autophagy GO:0006914

Term 2:

* **Suggested term label:**
secretory granule-lysosome fusion

* **Definition (free text)**
The fusion of secretory granules and lysosome to form crinosomes.

* **Reference, in format PMID:#######**
PMID:29066608

* **Gene product name and ID to be annotated to this term**
Syx13, FBgn0036341
Snap29, FBgn0034913
Vamp7, FBgn0266186

* **Parent term(s)**

vesicle fusion GO:0006906

* **part_of**
crinophagy

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160155
+name: crinophagy
+namespace: biological_process
+def: "The autophagic process which involves the direct fusion of abnormal, excess or obsolete secretory granules with lysosomes. This pathway is often associated with maintaining homeostasis in endocrine and exocrine cells." [PMID:29066608, PMID:35452619]
+is_a: GO:0006914 ! autophagy
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26875" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-25T22:51:56Z
+
+[Term]
+id: GO:0160156
+name: secretory granule-lysosome fusion
+namespace: biological_process
+def: "The cellular process that results in the fusion of secretory granules with lysosomes to form crinosomes." [PMID:29066608, PMID:35452619]
+is_a: GO:0006906 ! vesicle fusion
+relationship: part_of GO:0160155 ! crinophagy
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26875" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-25T23:02:38Z
