### ISSUE TITLE
Remove relationship GO:0044754 autolysosome is_a GO:0005776 autophagosome

### ISSUE THREAD

**Issue by EBIDaveC** [geneontology/go-ontology#26885]
While an autolysosome is formed when an autophagosome fuses with a lysosome is it correct to define an autolysosome as still being an autophagosome?

I think that the is_a GO:0005776 autophagosome relationship of GO:0044754 autolysosome should be removed.

According to PMID: 24657946 (https://pubmed.ncbi.nlm.nih.gov/24657946) autolysosomes also form when lysosomes fuse with amphisomes, so the definition for GO:0044754 autolysosome can be changed from:

A type of secondary lysosome in which a primary lysosome has fused with the outer membrane of an autophagosome. It is involved in the second step of autophagy in which it degrades contents with acidic lysosomal hydrolases.

To:

A type of secondary lysosome in which a primary lysosome has fused with the outer membrane of an autophagosome or amphisome. It is involved in the second step of autophagy in which it degrades contents with acidic lysosomal hydrolases.

**Comment by raymond91125** [comment]
Also remove autophagolysosome as an exact synonym. We would create the term when there are annotations to autophagolysosomes.
"Some people writing papers on the topic of autophagy use the terms “autolysosome” and “autophagolysosome” interchangeably. We contend that these words should be used to denote 2 different compartments, and that it is worthwhile maintaining this distinction—the autophagolysosome has a particular origin in the process of xenophagy that makes it distinct from an autolysosome."
