### ISSUE TITLE
NTR: "branched-chain alpha-keto acid dehydrogenase complex" terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26881]
Hi @raymond91105 

Related to #26122, please make the following two terms:

name: branched-chain alpha-keto acid dehydrogenase complex
namespace: cellular_component
def: "A multi-enzyme complex that catalyzes the oxidative decarboxylation of branched-chain alpha-keto acids derived from L-leucine, L-isoleucine, and L-valine to branched-chain acyl-CoAs. The complex comprises three main components: branched-chain alpha-ketoacid dehydrogenase (E1, consisting of alpha and beta subunits), dihydrolipoyl transacylase (E2), and dihydrolipoyl dehydrogenase (E3)." [PMID:10745006, PMID:10464218]
comment: Note that this term represents a location and not a function; the activity possessed by this complex is mentioned in the definition for the purpose of describing and distinguishing the complex. The catalytic activities of the individual components of this complex are represented by the molecular function terms '3-methyl-2-oxobutanoate dehydrogenase (2-methylpropanoyl-transferring) activity ; GO:0003863' (E1), 'dihydrolipoyllysine-residue (2-methylpropanoyl)transferase activity ; GO:0043754' (E2), and 'dihydrolipoyl dehydrogenase activity ; GO:0004148' (E3). The overall catalytic activity of the complex is represented by the molecular function term 'branched-chain alpha-keto acid dehydrogenase activity (GO:0047101)'.
is_a: GO:0045240 ! alpha-ketoacid dehydrogenase complex
intersection_of: GO:0032991 ! protein-containing complex
intersection_of: capable_of GO:0047101 ! branched-chain alpha-keto acid dehydrogenase activity

name: cytosolic branched-chain alpha-keto acid dehydrogenase complex
namespace: cellular_component
def: "A complex that catalyzes the oxidative decarboxylation of branched-chain alpha-keto acids derived from L-leucine, L-isoleucine, and L-valine to branched-chain acyl-CoAs.  It is composed of four polypeptides, E1alpha, E1beta, E2, and E3. [PMID: 10464218]
comment: Note that this term represents a location and not a function; the activity possessed by this complex is mentioned in the definition for the purpose of describing and distinguishing the complex. The catalytic activities of the individual components of this complex are represented by the molecular function terms '3-methyl-2-oxobutanoate dehydrogenase (2-methylpropanoyl-transferring) activity ; GO:0003863' (E1), 'dihydrolipoyllysine-residue (2-methylpropanoyl)transferase activity ; GO:0043754' (E2), and 'dihydrolipoyl dehydrogenase activity ; GO:0004148' (E3). The overall catalytic activity of the complex is represented by the molecular function term 'branched-chain alpha-keto acid dehydrogenase activity (GO:0047101)'.
synonym: "BKDH complex" EXACT []
intersection_of: GO:0045254 ! branched-chain alpha-keto acid dehydrogenase complex
intersection_of: part_of GO:0005829 ! cytosol

Also, please then change the relations on the existing "mitochondrial branched-chain alpha-keto acid dehydrogenase complex" (GO:0160120) as follows (I think):

is_a: GO:0045240 ! alpha-ketoacid dehydrogenase complex
is_a: GO:0098798 ! mitochondrial protein-containing complex
intersection_of: GO:0032991 ! protein-containing complex
intersection_of: capable_of GO:0047101 ! branched-chain alpha-keto acid dehydrogenase activity
>
is_a: GO:0098798 ! mitochondrial protein-containing complex
intersection_of: GO:0032991 ! branched-chain alpha-keto acid dehydrogenase complex
intersection_of: part_of GO:0005739 ! mitochondrion
relationship: part_of GO:0005759 ! mitochondrial matrix

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160157
+name: branched-chain alpha-keto acid dehydrogenase complex
+namespace: cellular_component
+def: "A protein complex that catalyzes the oxidative decarboxylation of branched-chain alpha-keto a
cids derived from L-leucine, L-isoleucine, and L-valine to branched-chain acyl-CoAs. The complex com
prises three main components: branched-chain alpha-ketoacid dehydrogenase (E1, consisting of alpha a
nd beta subunits), dihydrolipoyl transacylase (E2), and dihydrolipoyl dehydrogenase (E3)." [PMID:10464218, PMID:10745006]
+comment: Note that this term represents a location and not a function; the activity possessed by this complex is mentioned in the definition for the purpose of describing and distinguishing the complex. The catalytic activities of the individual components of this complex are represented by the molecular function terms '3-methyl-2-oxobutanoate dehydrogenase (2-methylpropanoyl-transferring) activity ; GO:0003863' (E1), 'dihydrolipoyllysine-residue (2-methylpropanoyl)transferase activity ; GO:0043754' (E2), and 'dihydrolipoyl dehydrogenase activity ; GO:0004148' (E3). The overall catalytic activity of the complex is represented by the molecular function term 'branched-chain alpha-keto acid dehydrogenase activity (GO:0047101)'.
+is_a: GO:0045240 ! alpha-ketoacid dehydrogenase complex
+intersection_of: GO:0032991 ! protein-containing complex
+intersection_of: capable_of GO:0047101 ! branched-chain alpha-keto acid dehydrogenase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26881" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-26T18:18:12Z
+
+[Term]
+id: GO:0160158
+name: cytosolic branched-chain alpha-keto acid dehydrogenase complex
+namespace: cellular_component
+def: "A protein complex that catalyzes the oxidative decarboxylation of branched-chain alpha-keto acids derived from L-leucine, L-isoleucine, and L-valine to branched-chain acyl-CoAs. It is composed of four polypeptides, E1alpha, E1beta, E2, and E3." [PMID:10464218]
+comment: Note that this term represents a location and not a function; the activity possessed by this complex is mentioned in the definition for the purpose of describing and distinguishing the complex. The catalytic activities of the individual components of this complex are represented by the molecular function terms '3-methyl-2-oxobutanoate dehydrogenase (2-methylpropanoyl-transferring) activity ; GO:0003863' (E1), 'dihydrolipoyllysine-residue (2-methylpropanoyl)transferase activity ; GO:0043754' (E2), and 'dihydrolipoyl dehydrogenase activity ; GO:0004148' (E3). The overall catalytic activity of the complex is represented by the molecular function term 'branched-chain alpha-keto acid dehydrogenase activity (GO:0047101)'
+synonym: "BKDH complex" EXACT []
+is_a: GO:0045240 ! alpha-ketoacid dehydrogenase complex
+intersection_of: GO:0032991 ! protein-containing complex
+intersection_of: capable_of GO:0047101 ! branched-chain alpha-keto acid dehydrogenase activity
+intersection_of: part_of GO:0005829 ! cytosol
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26881" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-26T18:30:05Z


This is how it looks (inferred)
![Screenshot from 2024-01-26 11-00-14](https://github.com/geneontology/go-ontology/assets/619520/0f9b12e3-4adf-41d5-8dfb-a40c97f0520b)

**Comment by raymond91125** [comment]
@sjm41 Please re-open if needed. Thanks.

**Comment by sjm41** [comment]
Thanks @raymond91125 .
Inferred view looks good.
Asserted view looks a bit odd/inconsistent though:
![Screenshot 2024-01-27 at 11 05 00](https://github.com/geneontology/go-ontology/assets/16306861/0db18d03-38ce-4fc5-bc94-ab49be6883fb)

I think we need to remove/replace the "+is_a: GO:0045240 ! alpha-ketoacid dehydrogenase complex" from GO:0160158 cytosolic branched-chain alpha-keto acid dehydrogenase complex?

And maybe the relations on "mitochondrial branched-chain alpha-keto acid dehydrogenase complex" (GO:0160120)" should be similar to the relations on the other two mitochondrial complex terms (GO:0009353 & GO:0005967)?

**Comment by deustp01** [comment]
As for #26122, all three oxo/keto-dehydrogenases have the same subsellular localization, intramitochondrial for eukaryotes and intracellular for prokaryotes. My recollection from poking around in the ontology several years ago and asking microbiologists is that the use of "cytoplasmic" to describe the interior of a bacterial cell is frowned upon. I didn't manage then to get a clear idea what a better term would be, beyond "intracellular". For eukaryotes, "cytoplasmic" works for these complexes because the cytoplasm includes mitochondria so it is true but not specific. Note that, as far as Lester Reed knows, there is no cytosolic form of any of these enzyme complexes - the active forms under normal conditions are strictly mitochondrial, we have no need to allow for them in term definitions.

**Comment by pgaudet** [comment]
Hi, 

sorry to be jumping in late, but according to our guidelines, here: https://wiki.geneontology.org/Protein_complexes, which were recently reviewed on an ontology call, I would say we should not have species-specific terms in this case, see point #3
> Complexes should be as species-agnostic as possible; for example if an homologous complex is present in different species and has different subunit composition, the definition should either be more vague about the number of subunits, or explain how the complex differs in different species.

So, we should probably collapse all these complexes under a single term. 

Likewise for #26122. 

I will add this to today's ontology call. 

Thanks, Pascale

**Comment by raymond91125** [comment]
Made a new pull request, obsoleting the subcellular-location-specific forms. Please let me know if it's good to merge into master.

**Comment by sjm41** [comment]
Thanks again @raymond91125 ! The new arrangement of these terms (both asserted and inferred) looks good.
Now this is much simplified, I can see there are a few tidying tasks to make the term entries complete and consistent (with each other and with the 'alpha-ketoacid dehydrogenase complex' parent):

GO:0045254 pyruvate dehydrogenase complex
- [ ] Remove first sentence of comment (no longer needed)
- [ ] remove synonym: "dihydrolipoyl dehydrogenase complex" BROAD [] (already correctly on parent)
- [ ] change def to: "A multi-enzyme complex that catalyzes the oxidative decarboxylation of pyruvate to form acetyl-CoA. The complex comprises multiple copies of three enzymes referred to as E1, E2 and E3: pyruvate dehydrogenase (E1, which may be a homodimer or a heterotetramer of two alpha and two beta subunits, depending on species), dihydrolipoamide S-acetyltransferase (E2), and dihydrolipoamide dehydrogenase (E3). Additional proteins may also be present." [PMID: 36863425]
(note new, replacement reference!)

GO:0045252 oxoglutarate dehydrogenase complex
- [ ] Remove first sentence of comment (no longer needed)
- [ ] add xref: Wikipedia:Oxoglutarate_dehydrogenase_complex (to match GO:0045254 entry)
- [ ] add synonyms: "KGDHC" EXACT [], "alpha-ketoglutarate dehydrogenase complex" EXACT []
- [ ] change def to: "A multi-enzyme complex that catalyzes the oxidative decarboxylation of alpha-ketoglutarate (also known as 2-oxoglutarate) to form succinyl-CoA. The complex comprises multiple copies of three enzymes referred to as E1, E2 and E3: oxoglutarate dehydrogenase (lipoamide) (E1), dihydrolipoamide S-succinyltransferase (E2) and dihydrolipoamide dehydrogenase (E3). Additional proteins may also be present." [PMID:10672230]
(note new, replacement reference!)

GO:0160157 branched-chain alpha-keto acid dehydrogenase complex
- [ ] Remove first sentence of comment (no longer needed)
- [ ] make 'keto acid' one word in name, so change to "branched-chain alpha-ketoacid dehydrogenase complex"
- [ ] add synonyms: "BCKD complex" EXACT [], "BKDH complex" EXACT []
- [ ] add xref: Wikipedia:Branched-chain_alpha-keto_acid_dehydrogenase_complex  (to match GO:0045254 entry)
- [ ] change def to: "A multi-enzyme complex that catalyzes the oxidative decarboxylation of branched-chain alpha-ketoacids derived from L-leucine, L-isoleucine, and L-valine to branched-chain acyl-CoAs. The complex comprises multiple copies of three enzymes referred to as E1, E2 and E3: branched-chain alpha-ketoacid dehydrogenase (E1, a heterotetramer of two alpha and two beta subunits), dihydrolipoyl transacylase (E2), and dihydrolipoamide dehydrogenase (E3). Additional proteins may also be present." [PMID:10464218, PMID:10745006, PMID:3593587]
(note additional reference!)

**Comment by raymond91125** [comment]
Shouldn't we do without the comments all together since now they are rather similar to the corresponding definitions?

**Comment by raymond91125** [comment]
There may be another redundant existing term:
GO:0017086 3-methyl-2-oxobutanoate dehydrogenase (lipoamide) complex has exact synonym branched-chain alpha-ketoacid dehydrogenase complex.

**Comment by sjm41** [comment]
> There may be another redundant existing term:
GO:0017086 3-methyl-2-oxobutanoate dehydrogenase (lipoamide) complex has exact synonym branched-chain alpha-ketoacid dehydrogenase complex.

I agree. Merge with GO:0160157 branched-chain alpha-keto acid dehydrogenase complex. "3-methyl-2-oxobutanoate dehydrogenase (lipoamide)" activity is the activity of the E1 component of this complex.
There's only 2 annotations to GO:0017086:
- Dicty "bkdA" (Q54M22) IC
- Plasmodim "Dihydrolipoyl dehydrogenase" (Q8I5A0) IDA from PMID:15612914
Both of these are components of the branched-chain alpha-keto acid dehydrogenase complex.

**Comment by sjm41** [comment]
> Shouldn't we do without the comments all together since now they are rather similar to the corresponding definitions?

I'd rather keep the comments (minus their first sentence) as it clearly explains that there's one GO-MF term for the overall activity of the complex (which is the one we've used in the 'capable_of' relation) as well as separate GO-MF terms for each enzymatic component (E1, E2, E3).

**Comment by raymond91125** [comment]
If all looks good, I can start the obsoletion process to complete this ticket.

**Comment by sjm41** [comment]
Yep, looks good to me. Thanks again @raymond91125 !
