### ISSUE TITLE
tricarboxylic acid cycle enzyme complex (GO:0045239) hierarchy

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26882]
I'm trying to work with this term and its children, and struggling:

id: GO:0045239
name: tricarboxylic acid cycle enzyme complex
namespace: cellular_component
def: "Any of the heteromeric enzymes that act in the TCA cycle." [GOC:mah]
subset: goslim_pir
synonym: "TCA cycle enzyme complex" EXACT []
is_a: GO:0032991 ! protein-containing complex
is_a: GO:1902494 ! catalytic complex
relationship: part_of GO:0005737 ! cytoplasm

Here are its asserted and inferred children (in the current GO master):
```
tricarboxylic acid cycle enzyme complex
|__cytosolic tricarboxylic acid cycle enzyme complex [constraint:PROKARYOTA]
    |__cytosolic isocitrate dehydrogenase complex (NAD+)
|__isocitrate dehydrogenase complex (NAD+)
    |__cytosolic isocitrate dehydrogenase complex (NAD+)
    |__mitochondrial isocitrate dehydrogenase complex (NAD+)
|__mitochondrial tricarboxylic acid cycle enzyme complex [constraint:EUKARYOTA]
    |__mitochondrial isocitrate dehydrogenase complex (NAD+)
    |__succinate-CoA ligase complex (GDP-forming)
|__succinate-CoA ligase complex
    |__succinate-CoA ligase complex (ADP-forming)
    |__succinate-CoA ligase complex (GDP-forming)
```

Option 1 is to keep this hierarchy, but try to fix/improve it as follows:

- [x] GO:0045239 term name suggests the term is for any TCA complex, but def says it's only for **heteromeric** complexes. Assuming the def represents the intended usage, then the term name should be updated to match. Otherwise, users/curators may reasonably expect to find GO terms for the **homomeric** complexes of the TCA cycle in this hierarchy. Indeed, there is an 'incorrect' InterPro2GO annotation (IPR005677) directly to GO:0045239 for Fumarate hydratase (a homotetramer).

- [ ] Again, assuming the def is correct, then I think GO:0045239 (and its two main subgroups, 'cytosolic/mitochondrial tricarboxylic acid cycle enzyme complex') should be 'do not annotate' terms. There are only 4 annotations direct to these terms:
InterPro:IPR005677 GO:0045239 IEA (InterPro)
UniProtKB:P14165 GO:0045239 IDA (PseudoCAP)
UniProtKB:Q9I5E3 GO:0045239 IDA (PseudoCAP)
UniProtKB:Q8I0X1 GO:0030062 ISS (GeneDB)

- [x] Actually, I'd suggest eliminating the orthogonal classification by cytosolic/mitochondrial complex - that classification gets especially tricky for the succinate-CoA ligase complex terms, where the ADP-forming complex is found in both bacteria and eukaryotes, meaning that term can't be classified as either a mitochondrial or cytosolic TCA complex. (This is supported by @pgaudet's comment here: https://github.com/geneontology/go-ontology/issues/26881#issuecomment-1914424444)

- [x] "succinate dehydrogenase complex" terms are missing from this hierarchy:
succinate dehydrogenase complex (ubiquinone)
    |__mitochondrial respiratory chain complex II, succinate dehydrogenase complex (ubiquinone)
    |__plasma membrane succinate dehydrogenase complex (ubiquinone)

- [x] "oxoglutarate dehydrogenase complex" term is missing from this hierarchy:
oxoglutarate dehydrogenase complex

Option 2 is to delete this grouping term (and its two main subgroups, 'cytosolic/mitochondrial tricarboxylic acid cycle enzyme complex') - I'm not convinced it's a useful/necessary grouping, and it's difficult to group the child terms accurately/completely. Would it be better to have "capable_of_part_of" relations between applicable complex terms to the BP term "GO:0006099 tricarboxylic acid cycle"?

What do others think? @deustp01 ? @ukemi?

**Comment by deustp01** [comment]
See comment on subcellular localization and describing it in eukaryotes vs prokaryotes on ticket #26122

**Comment by sjm41** [comment]
Based on the discussion/decision in #26881, the following 4 terms mentioned above should be obsoleted:

- [ ] cytosolic tricarboxylic acid cycle enzyme complex GO:0045246 [taxon constraint:PROKARYOTA] "Any of the heteromeric enzymes, located in the cytosol, that act in the tricarboxylic acid (TCA) cycle."

- [ ] mitochondrial tricarboxylic acid cycle enzyme complex GO:0030062 [constraint:EUKARYOTA] "Any of the heteromeric enzymes, located in the mitochondrion, that act in the tricarboxylic acid (TCA) cycle."

- [ ] cytosolic isocitrate dehydrogenase complex (NAD+) GO:0045243 [taxon constraint:prokaryote] "Cytosolic complex that possesses isocitrate dehydrogenase (NAD+) activity."

- [ ] mitochondrial isocitrate dehydrogenase complex (NAD+) GO:0005962 [constraint:EUKARYOTA] "Mitochondrial complex that possesses isocitrate dehydrogenase (NAD+) activity."

(We should keep the general "isocitrate dehydrogenase complex (NAD+)" term, of course:
isocitrate dehydrogenase complex (NAD+) GO:0045242 [no taxon constraint] "Complex that possesses isocitrate dehydrogenase (NAD+) activity")

After those obsoletions are done, we'll still need to decide whether "tricarboxylic acid cycle enzyme complex (GO:0045239)" should be restricted to heteromeric complexes and if it is a useful grouping for the remaining terms:
```
tricarboxylic acid cycle enzyme complex
|__isocitrate dehydrogenase complex (NAD+)
|__succinate-CoA ligase complex
    |__succinate-CoA ligase complex (ADP-forming)
    |__succinate-CoA ligase complex (GDP-forming)
|__succinate dehydrogenase complex (ubiquinone)
    |__mitochondrial respiratory chain complex II, succinate dehydrogenase complex (ubiquinone)* [EUKARYOTA]
    |__plasma membrane succinate dehydrogenase complex (ubiquinone)* [PROKARYOTA]
|__oxoglutarate dehydrogenase complex
```

* Not sure if these starred complexes should be retained as a 'special case' or if they should also be obsoleted

**Comment by raymond91125** [comment]
@sjm41 Please check to see if the changes achieve desired result.

**Comment by sjm41** [comment]
Looks good @raymond91125, thanks.
I think we should go ahead with these changes and keep this 'tricarboxylic acid cycle enzyme complex' grouping term in the ontology, at least for now. But I think we should tweak the name to 'tricarboxylic acid cycle heteromeric enzyme complex' to match the def and children.

@pgaudet and I chatted about the logic (or otherwise) of keeping the two mitochondrial/plasma_membrane children of 'succinate dehydrogenase complex (ubiquinone)'.  The complication with that complex is that it is both a TCA complex and a respiratory chain complex, meaning we should also consider the GO terms for the other respiratory chain complexes.  I'll make a separate ticket for that issue.

**Comment by raymond91125** [comment]
Having trouble figuring out how to merge into master given changes in taxon constraint owl. Have to start from scratch.

**Comment by sjm41** [comment]
Thanks @raymond91125 

One more thing...I think GO:0045239 should be a "do not annotate" term.  Would you agree?
I see only 2 IDA annotations to the term assigned by "PseudoCAP" (P14165/gltA & Q9I5E3/prpC) and a single InterPro2GO annotation via IPR005677) which I'll make a ticket for now.

**Comment by sjm41** [comment]
This is all done.
