### ISSUE TITLE
NTR: positive regulation of N-acetylmuramic acid catabolic process, nicotine catabolic process, and propanediol catabolic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26905]
Hello, 

Requested by @JervenBolleman to convert old UniPathway mappings in GO annotations: 3 new regulation terms

- [ ] positive regulation of N-acetylmuramic acid catabolic process: PMID:18723630
- (N-acetylmuramic acid catabolic process = GO:0097173)
- [ ]  positive regulation of nicotine catabolic process: PMID: 15838033
- (nicotine catabolic process = GO:0019608)
- [ ] positive regulation of propanediol catabolic process: PMID:9023178 & PMID:7559322
- (propanediol catabolic process = GO:0051144 )

Thanks, Pascale

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160159
+name: positive regulation of N-acetylmuramic acid catabolic process
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of N-acetylmuramic acid catabolic process." [PMID:18723630]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0097173 ! N-acetylmuramic acid catabolic process
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26905" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-30T22:43:05Z
+
+[Term]
+id: GO:0160160
+name: positive regulation of nicotine catabolic process
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of nicotine catabolic process." [PMID:15838033]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0019608 ! nicotine catabolic process
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26905" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-30T22:43:05Z
+
+[Term]
+id: GO:0160161
+name: positive regulation of propanediol catabolic process
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of propanediol catabolic process." [PMID:7559322, PMID:9023178]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0051144 ! propanediol catabolic process
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26905" xsd:anyURI
+created_by: rynl
+creation_date: 2024-01-30T22:43:05Z
