### ISSUE TITLE
NTR: symbiont-mediated suppression of host-directed shutoff of host translation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26918]
Please provide as much information as you can: 

* **Suggested term label:**
* symbiont-mediated suppression of host-directed shutoff of host translation

* **Definition (free text)**

* **Reference, in format PMID:#######**
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
GO:0019057 ! symbiont-mediated perturbation of host translation

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Improved definition for GO:0039580 symbiont-mediated suppression of host PKR/eIFalpha signaling
-def: "A process in which a symbiont inhibits or disrupts a host PKR (Protein Kinase regulated by RNA) signaling. Host PKR signaling includes targets such as the translation initiation factor eIF2alpha, inhibiting protein synthesis as an antiviral response. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:15207627]
+def: "A process in which a symbiont inhibits or disrupts host PKR (Protein Kinase regulated by RNA) signaling. PKR phosphorylates host targets such as the translation initiation factor eIF2alpha that inhibits protein synthesis as an antimicrobial response. Inhibition of host PKR signaling maintains the host ability to translate mRNA. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:15207627]

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141154
+name: symbiont-mediated suppression of host-directed shutoff of host translation
+namespace: biological_process
+def: "A process in which a symbiont inhibits or disrupts the host shutoff of host translation, a host response that prevents mRNA in the cell to be translated, to prevent the symbiont from expressing its genes. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:pg]
+is_a: GO:0019057 ! symbiont-mediated perturbation of host translation
+created_by: pg
+creation_date: 2024-01-31T14:53:32Z

**Comment by pgaudet** [comment]
@genegodbold to provide references for 
GO:0141154  symbiont-mediated suppression of host-directed shutoff of host translation
and GO:0039580 symbiont-mediated suppression of host PKR/eIFalpha signaling

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141155
+name: symbiont-mediated suppression of host translation elongation
+namespace: biological_process
+def: "A process in which a symbiont inhibits or disrupts the translation elongation of host mRNA into protein, for example by directly inhibiting elongation factors. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:pg]
+is_a: GO:0039604 ! symbiont-mediated suppression of host translation
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26918" xsd:anyURI
+created_by: pg
+creation_date: 2024-01-31T15:24:57Z

**Comment by genegodbold** [comment]
**Viral proteins suppressing PKR/eIFalpha signaling**:
- **VP35 from Ebola virus**: VP35 inhibits protein kinase R (PKR) through an RNA-independent mechanism, preventing the phosphorylation and inactivation of eIF2alpha [PMID:22238300].
- **Unique long 13** (UL13) from human herpesvirus-1 (HHV-1):  UL13 is a tegument protein and a viral serine/threonine protein kinase that appears to act mostly on viral proteins [PMID:33374862]. However, it also has a role in phosphorylation of host protein kinase R (PKR) in supporting viral protein synthesis along with the US3 viral protein kinase [PMID:32221365].
- Unique, short 11 (US11) from human herpesvirus-1 (HHV-1/HSV-1): US11 is produced abundantly, late in HSV-1 infection. It associates with host dsRNA and also with host protein kinase R (PKR) to inhibit its activation [PMID:11070019], [PMID:11836380].
- **Sigma3** (σ3) from orthoreovirus: The sigma3 protein is a dsRNA binding protein that prevents activation of host protein kinase R (PKR). When expressed alone, wild-type sigma3 forms a dimer. Strangely, dsRNA binding by sigma3 is not necessary for inhibition of PKR. While the K287T and R296T mutants lost the ability to bind dsRNA, viruses expressing the R296T mutant retained the ability to inhibit host PKR. Viruses expressing those sigma3 mutants produced more viral mRNA in association with stress granules than those expressing wildtype protein. Mice inoculated with the virus expressing the sigma3 K287T mutant did not develop myocarditis unlike those mice infected with wildtype virus [PMID:34237110].
- **Nonstructural protein S** (**NSs**) from Rift Valley Fever virus: NSs is a 31 kDa protein that is found in both the host cytoplasm and nucleus. NSs induces the degradation of the anti-viral protein kinase R (PKR). This ability to cause PKR disappearance is separate from its ability to block transcription [PMID:27711108]. Interaction of NSs with the host ubiquitin ligases FBXW11 and Beta-TRCP1 is required to destroy PKR in virus-infected cells [PMID:27122577].

**Comment by genegodbold** [comment]
**Here are some proteins** that qualify for "Symbiont-mediated suppression of host-directed shutoff of host translation"
- **Infected cell protein 34.5** (ICP34.5) from human herpesvirus 1 (HHV-1): ICP34.5 includes a GADD34 homology region that allows the phosphorylation of host eIF2alpha to be abrogated via recruitment of host protein phosphatase-1alpha. This prevents premature shutoff of protein synthesis in HHV-1 infected human cells [PMID:8523596]. ICP34.5 interacts with host eIF2alpha through residues 233-248 [PMID:21622569].
- **Immediate early protein 63** (IE63) from Varicella zoster virus (HHV-3): In response to interferon, IE63 inhibits the phosphorylation of the host eukaryotic initiation factor 2-alpha (eIF2alpha) thus inhibiting host translational shutdown [PMID:20563710].
- **PthXo7** (TalBM) from _Xanthomonas oryzae_: PthXo7 is a T3SS TALE that induces expression of the transcription initiation factor OsTFIIAgamma1. This is a means by which the _X. oryzae_ bacterium overcomes the host resistance that is the result of a point mutation [PMID:27472897]. The xa5 mutation of the gene OsTFIIAgamma5 in the rice variety IRBB5 which disrupts the ability of TALEs to interact with the (gamma5) basal transcription factor [PMID:15597740]. By expressing the paralog (gamma1), PthXo7 can restore normal TALE function [PMID:17563377].

**Comment by genegodbold** [comment]
**Viral proteins that suppress a host translation elongation factor**:
- **Nucleocapsid** (N) protein from SARS-CoV: N protein targets the host translation elongation factor eEF1A for inactivation, thereby inhibiting protein synthesis, cell proliferation, and cytokinesis [PMID:22002165]. The C terminus of the nucleocapsid protein (residues 251-422) binds to human elongation factor 1alpha (EF1alpha) resulting in its aggregation and inhibiting protein translation [PMID:18448518]. 

**Bacterial proteins that suppress a host translation elongation factor**:
- **Diphtheria toxin** from _Corynebacterium diphtheriae_: Diphtheria toxin transfers an adenosine diphosphate ribose moiety from NAD to elongation factor-2 (EF-2) at a conserved Cys residue, thereby preventing it from participating in protein synthesis at the ribosome. The site on EF-2 that is prone to ADP-ribosylation of DT is a post-translationally modified His residue that occurs at only one conserved position in EF-2 from eukaryotes and archae [PMID:10657208].
- **Legionella glucosylating toxin 1** (Lgt1) from _Legionella pneumophila_: Lgt1 is one of three glucosylating toxins of _Legionella pneumophila_. These act by adding a single glucose moiety from UDP-glucose to serine53 of the host eukaryotic elongation factor 1A (eEF1A). This modification blocks protein synthesis at the ribosome and results in the death of intoxicated cells [PMID:18281405].
- **Substrate of Icm/Dot I** (**SidI**; lpg2504) from _Legionella pneumophila_: SidI inhibits protein translation both in vitro and in cells infected with _L. pneumophila_. SidI binds host elongation factors eEF1A and also eEF1Bgamma. As little as 30 ng SidI was able to block translation in an in vitro system. The following SidI mutants, when expressed in yeast, were not toxic: Glu482Lys, Arg453Leu and Arg453Pro. They weren't completely devoid of the ability to inhibit protein synthesis as indicated by the in vitro translation system [PMID:19386084].
- **Pseudomonas exotoxin A** (PEA, ExoA, ETA) from _Pseudomonas aeruginosa_: ExoA is a single-chain polypeptide of 69 kDa and three subdomains that kills host cells by inhibiting protein synthesis. ExoA enters cells through receptor-mediated endocytosis and then ADP-ribosylates the diphthamide residue of host eukaryotic elongation factor 2 (EF2) [PMID:21585657].

**Comment by pgaudet** [comment]
GO:0141155 symbiont-mediated suppression of host translation elongation

Changed parent from ' symbiont-mediated suppression of host translation ' to 'symbiont-mediated suppression of host defenses'
