### ISSUE TITLE
NTR: symbiont-mediated perturbation of vesicle-mediated transport

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26919]
Please provide as much information as you can: 

* **Suggested term label:**
symbiont-mediated perturbation of vesicle-mediated transport

* **Definition (free text)**

* **Reference, in format PMID:#######**
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
This would be to map to PATHGO:0000321 modulates endosomal vesicle trafficking in another organism
 
@genegodbold to provide references

**Comment by genegodbold** [comment]
**Rhoptry aplical surface protein 2** (TgRASP2; TGGTI_315160) from _Toxoplasma gondii_: RASP2 binds specifically to phosphatidic acid (PA) and phosphatidylinositol 4,5 diphosphate (PIP2) via its calcium lipid-binding-like domain and a pleckstrin homology-like domain. Both PA and PIP2 are lipids that accumulate at exocytic sites and participate in membrane fusion events during vesicle exocytosis. TgRASP2 is required for rhoptry secretion and the lipid binding domains are involved. Depletion of TgRASP2 results in the loss of rhoptry secretion and blocks invasion of the parasite for Toxoplasma. RASP2 may be required for opening of the pore between the rhoptry and the host cell [PMID:31492901].


**Bacterial modulators of endosomal vesicle trafficking**:
- **Chlamydia promoter of survival** (CpoS; CT_229): CpoS is a chlamydial T3SS effector that recruits host Rab small GTPases and Rab effectors to the periphery of the inclusion body in infected cells. In doing so it redirects and intercepts host clathrin-coated vesicles from the recycling pathway to the periphery of the inclusion [PMID:30893609].
- **IncE** (CT_116) from _Chlamydia trachomatis_: Retromer complex and sorting nexins (SNXs) regulate retrograde endosomal traffic from endosomes to the trans Golgi network (TGN) in mammalian cells. SNXs regulate the retromer complex which consists of VPS26, VPS29, and VPS35. IncE is an integral membrane protein of the chlamydial inclusion and T3SS effector that specifically associates with SNX5 and SNX6 via their phox homology domains. Overexpression of IncE in mammalian cells inhibits retromer and SNX5/6-mediated endosomal trafficking [PMID:26118995]. IncE inhibits retromer transport through its direct interaction with SNX5/6. This inhibition correlates with its ability to separate the cargo and the retromer. SNX5/6 appears to contribute to the recognition of the cation-independent mannose-6-phosphate receptor cargo by the retromer while IncE prevents this association [PMID:29263922].
- **Coxiella vacuolar protein A (CvpA, Cbu0665)** (CvpA, Cbu0665): CvpA is a T4SS effector that localizes to the membrane of the CCV and subverts clathrin-dependent vesicular transport in infected host cells. The endocytic sorting motifs in CvpA binds the host clathrin adaptor complex AP2 [PMID:24248335].
- **Escherichia coli secreted protein G (EspG)**: Both EspG and EspG2 function as GTPase activating proteins for Rab1 to inhibit autophagy and vesicular traffic from the ER to the Golgi [PMID:22425230]. EspG is a GTPase activating protein for the host small GTPase Rab. It inactivates Rab1 and blocks host interleukin-8 (IL-8) secretion in cells infected by EPEC [PMID:11349072].  Both EspG and EspG2 are cytotoxic to host cells, but only in the absence of another effector--Tir from Escherichia coli [PMID:22425230]. 
- **Vacuolating cytotoxin autotransporter** (VacA) from _Helicobacter pylori_: VacA triggers the formation of large cytoplasmic vacuoles that originate from late endocytic compartments. VacA interference with the late endocytic pathway results in both the mis-sorting of lysosomal hydrolases to the extracellular medium and interference with normal lysosomal degradation of proteins, thus inhibiting antigen processing [PMID:12814772]. VacA induces a major alteration in vesicular traffic that co-segregates early and late endosomes with mitochondria [PMID:20431599]. 
- **VipA** (lpg0390) from _Legionella pneumophila_: The VipA effector is an actin-nucleating protein that co-localizes with both actin filaments and early endosomes in infected macrophages. It interferes with the trafficking of host organelles [PMID:26626407]. When expressed in yeast, VipA interferes with trafficking to the lysosome [PMID:15781869].

**Comment by pgaudet** [comment]
Reused the term GO:1990215 negative regulation by symbiont of host intracellular transport >> changed label to symbiont-mediated perturbation of host vesicle-mediated transport : reference cited in the term is for vesicle-mediated, and there are no annotations.
