### ISSUE TITLE
Obsoletion request: GO:0008153  para-aminobenzoic acid biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26927]
Please provide as much information as you can:

* **GO term ID and Label**

GO:0008153  para-aminobenzoic acid biosynthetic process

The chemical reactions and pathways resulting in the formation of para-aminobenzoic acid, **an intermediate** in the synthesis of folic acid, a compound which some organisms, e.g. prokaryotes, eukaryotic microbes, and plants, can synthesize de novo. Others, notably mammals, cannot. In yeast, it is present as a factor in the B complex of vitamins. PMID:11377864 PMID:11960743

* **Reason for deprecation** Put an x in the appropriate box: 

 - [ ] The reason for obsoletion is that the data from the paper for which the term was requested can be accurately described using [appropriate GO term].

I'm picking up IBA mappings to this term, but it seems to be describing an intermediate according to the definition? I annotated only to 
GO:0046656 | folic acid biosynthetic process

 - [ ]  The reason for obsoletion is that this term was added in error.
 

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by cmungall** [comment]
I don’t get the rationale

It’s a distinct pathway? The product of the pathway could feed into other
pathways… but that’s true of many more?

https://biocyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-6543

**Comment by ValWood** [comment]
I hadn't looked in detail yet but I'm basing on
1. says intermediate in the def (we don't include pathway intermediates for linear pathways)
2. The only thing annotated to this seems to be  "para-aminobenzoate synthase" so it seems to be a single step in a linear pathway to folic acid, will double check this

**Comment by ValWood** [comment]
It's the left hand branch here.
<img width="485" alt="Screenshot 2024-02-01 at 16 33 53" src="https://github.com/geneontology/go-ontology/assets/7359272/26ccd4b5-1bc4-47cf-b820-004ba8ad4c46">

@deustp01  will probably know if this goes anywhere else other than folate....

**Comment by deustp01** [comment]
> @deustp01 will probably know if this goes anywhere else other than folate

No such luck. [Here](https://pubmed.ncbi.nlm.nih.gov/8454223/) is a PubMed citation suggesting that it can be metabolized but we don't have any annotations - our relevant ones start with uptake of dietary folate, derived from organisms that can synthesize it.

**Comment by ValWood** [comment]
I can't find any evidence that PABA is used for anything other than folate biosynthesis and onwardly for tetrahydrofolate,  so it does seem to be an intermediate in a linear pathway.
However, it seems that humans can make PABA but not folic acid (they are missing the conversion enzyme), which implies there is another role for PABA?

**Comment by deustp01** [comment]
> However, it seems that humans can make PABA

I don't know of any evidence for this (which definitely is not proof it doesn't happen). Wikipedia describes its synthesis by human gut organisms, so we could get it from there -

> 4-Aminobenzoic acid - Wikipedia
> PABA is an intermediate in the synthesis of folate by bacteria, plants, and fungi. Many bacteria, including those found in the human intestinal tract such as E. coli, generate PABA from chorismate by the combined action of the enzymes 4-amino-4-deoxychorismate synthase and 4-amino-4-deoxychorismate lyase.

**Comment by cmungall** [comment]
https://biocyc.org/compound?orgid=META&id=P-AMINO-BENZOATE#RXNS

various other end-products there

**Comment by ValWood** [comment]
ok thanks
not to self [ubiquinol-6 biosynthesis from 4-aminobenzoate (yeast)](https://biocyc.org/META/NEW-IMAGE?type=PATHWAY&object=PWY-7230)

**Comment by pgaudet** [comment]
It seems like Para-Aminobenzoic Acid may have a physiological role? 
https://pubmed.ncbi.nlm.nih.gov/34607467/

Also about intermediates, we need to be careful to check that it's not a branch point; in this case the term could be useful.

**Comment by ValWood** [comment]
It is a branch point, in yeast for ubiquinol-6 biosynthesis and folic acid

**Comment by pgaudet** [comment]
> It is a branch point, in yeast for ubiquinol-6 biosynthesis and folic acid

OK, better to keep it
