### ISSUE TITLE
Missing parent: mRNA 5'-phosphatase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26929]
* **GO term ID and label for which you request a new superclass**

mRNA 5'-phosphatase activity](https://www.pombase.org/term/GO:0140818)

* **New superclass (parent) suggested**

GO:0004651 | polynucleotide 5'-phosphatase activity

* **Reference(s), if appropriate**

2022-05-26 | Deleted | RELATION | is a GO:0004651 (polynucleotide 5'-phosphatase activity)

**Comment by ValWood** [comment]
check history first

**Comment by ValWood** [comment]
According to
https://github.com/geneontology/go-ontology/issues/23319
this parent was incorrect but I can't figure out why?
@sjm41  @pgaudet

**Comment by ValWood** [comment]
I see, would it be better here to switch 
mRNA 5'-triphosphate monophosphatase activity (exact synonym) 
to be the primary name (even if this is not  preferred community usage?)

**Comment by sjm41** [comment]
Hi @ValWood Sounds like you figured out the history/reasoning here from looking at https://github.com/geneontology/go-ontology/issues/23319 - comes down to the difference between EC:3.6.1-type phosphatases vs EC:3.1.3-type phosphates.

Changing the term name to 'mRNA 5'-triphosphate monophosphatase activity' sounds reasonable to me.
