### ISSUE TITLE
Obsoletion request: GO:0035553  oxidative single-stranded RNA demethylation and GO:0035552 'oxidative single-stranded DNA demethylation

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26935]
The proposal has been made to obsolete    GO:0035553  oxidative single-stranded RNA demethylation
& replace by parent oxidative RNA demethylation

---

After review of the annotations, these 2 terms will be obsoleted because thy are redundant with the MFs 
	
GO:0035515 oxidative RNA demethylase activity
GO:0035516 broad specificity oxidative DNA demethylase activity

**Comment by RLovering** [comment]
Hi UCL has 4 annotations - I have revised 2 RNA ones, but there is no DNA parent oxidative DNA demethylation. Is this just going to DNA demethylation?

**Comment by pgaudet** [comment]
You're faster than I am  (not difficult) !! Suggestions will be coming soon... Colin and I are working on this. 

Thanks, Pascale

**Comment by suzialeksander** [comment]
Noting that as of today, GO:0035515 oxidative RNA demethylase activity &
GO:0035516 broad specificity oxidative DNA demethylase activity are still valid (not-obsoleted) terms
