### ISSUE TITLE
NTR: snoRNA and snRNA  2,2,7-trimethylguanosine (TMG) cap formation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26940]
Please provide as much information as you can: 

* **Suggested term label:**
snoRNA 2,2,7-trimethylguanosine (TMG) cap formation
snRNA 2,2,7-trimethylguanosine (TMG) cap formation

will be required before

GO:0036261 | 7-methylguanosine cap hypermethylation
can be obsoleted

* **Definition (free text)**

* **Reference, in format PMID:#######**
https://www.pombase.org/reference/PMID:15590684

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
These are the first 3 steps:
https://github.com/geneontology/go-ontology/issues/26939
but cannot be used currently for snRNA and snoRNA

**Comment by ValWood** [comment]
I have found a term "snRNA capping" but it is incorrectly/vaguely defined as 

The addition of a methylphosphate cap at the 5'-end of 7SK snRNA (7SK RNA). Capping 7SK RNA stabilizes it.

(i.e gene product specific, this only applies to a single eukaryote specific snRNA)

@pgaudet  should I broaden this term to match the label? is that allowed?

**Comment by pgaudet** [comment]
>  should I broaden this term to match the label? is that allowed?

Yes, this is fine

**Comment by ValWood** [comment]
[Term]
id: GO:0180031
name: snoRNA 2,2,7-trimethylguanosine (TMG) capping
namespace: biological_process
def: "The sequence of enzymatic reactions by which a 2,2,7-trimethylguanosine cap structure is added to the 5' end of an snoRNA. The snoRNA capping includes the formation of 7-methyl-G caps found on all RNA polymerase II transcripts, followed by hypermethylation at the 2' position of the guanosine residue to convert a mono-methylated cap to a 2,2,7-trimethylguanosine cap structure. Note that the pol III transcribed snoRNAs are also TMG capped." [GOC:vw, PMID:15590684]
synonym: "snoRNA 2,2,7-trimethylguanosine (TMG) cap formation" EXACT []
synonym: "snoRNA capping" EXACT []
is_a: GO:0036260 ! RNA capping
is_a: GO:0043144 ! sno(s)RNA processing
intersection_of: GO:0000966 ! RNA 5'-end processing
intersection_of: has_primary_input SO:0000275 ! snoRNA
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26940" xsd:anyURI
created_by: vw
creation_date: 2024-02-07T13:55:54Z
