### ISSUE TITLE
MetaCyc transport reaction xrefs to add to GO-MF transporter terms.

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#26941]
I downloaded existing GO-RHEA associations for RHEA transport reactions (using the RHEA site). This revealed ~60 MetaCyc xrefs present on the RHEA terms that could be added to the corresponding GO terms.  This exercise also found a few mis-mappings and obsolete MetaCyc xrefs to be corrected. All are listed below.

RHEA_ID | GO_ID | MetaCyc_xref_to_add | Notes
-- | -- | -- | --
RHEA:28967 | GO:0005298 | TRANS-RXN-118 |  
RHEA:28699 | GO:0005384 | RXN0-16 |  
RHEA:29351 | GO:0005385 | RXN0-12 |  
RHEA:18105 | GO:0005388 | TRANS-RXN-194 |  
RHEA:11484 | GO:0008121 | RXN-15816 | Also remove existing: MetaCyc:1.10.2.2-RXN (SUBTYPE)
RHEA:28747 | GO:0008519 | RXN-9615 |  
RHEA:12132 | GO:0008551 | RXN-21035 | Keep existing: MetaCyc:3.6.3.3-RXN (SAME TRANSPORT REACTION)
RHEA:16777 | GO:0008556 | TRANS-RXN-2 |  
RHEA:22044 | GO:0008900 | 3.6.3.10-RXN |  
RHEA:29671 | GO:0015085 | TRANS-RXN-144 |  
RHEA:28578 | GO:0015087 | TRANS-RXN-141A |  
RHEA:28486 | GO:0015093 | TRANS-RXN-8 |  
RHEA:29827 | GO:0015095 | TRANS-RXN-141 |  
RHEA:29831 | GO:0015099 | TRANS-RXN-141B |  
RHEA:32807 | GO:0015117 | TRANS-RXN-496 |  
RHEA:28458 | GO:0015225 | TRANS-RXN0-240 |  
RHEA:29667 | GO:0015250 | TRANS-RXN-145 |  
RHEA:29675 | GO:0015254 | TRANS-RXN-131 |  
RHEA:37047 | GO:0015333 | RXN-14653 | Make RHEA and MetaCyc xrefs = narrow
RHEA:29251 | GO:0015385 | TRANS-RXN-129 |  
RHEA:29467 | GO:0015386 | TRANS-RXN-42 |  
RHEA:28490 | GO:0015387 | TRANS-RXN-3 |  
RHEA:14613 | GO:0015411 | ABC-64-RXN | Also remove existing: MetaCyc:ABC-70-RXN (WRONG)
RHEA:24440 | GO:0015415 | ABC-27-RXN |  
RHEA:18065 | GO:0015416 | 3.6.3.28-RXN | Also remove existing: MetaCyc:ABC-23-RXN (SUBTYPE)
RHEA:29999 | GO:0015417 | ABC-24-RXN | Make MetaCyc:ABC-24-RXN & RHEA:29999 xrefs - narrow
RHEA:11036 | GO:0015418 | RXN-8638 | Also remove existing: MetaCyc:RXN-8665 (WRONG)
RHEA:10192 | GO:0015419 | ABC-70-RXN | Also remove existing: MetaCyc:3.6.3.25-RXN (OBSOLETE)
RHEA:17873 | GO:0015420 | 3.6.3.33-RXN | Also remove existing: MetaCyc:ABC-5-RXN (SUBTYPE)
RHEA:22132 | GO:0015423 | ABC-16-RXN | Also remove existing: MetaCyc:3.6.3.19-RXN (OBSOLETE)
RHEA:19121 | GO:0015431 | TRANS-RXN-358 |  
RHEA:19261 | GO:0015439 | 3.6.3.41-RXN | Also remove existing:TRANS-RXN0-162 (WRONG)
RHEA:14429 | GO:0015440 | 3.6.3.23-RXN | existing RHEA xref is wrong - remove. Move existing MetaCyc:3.6.3.43-RXN to GO:0015433. Put 3.6.3.23-RXN on GO:0015421
RHEA:29679 | GO:0015499 | TRANS-RXN-1 |  
RHEA:29031 | GO:0015501 | TRANS-RXN-122 |  
RHEA:29023 | GO:0015535 | TRANS-RXN-20 |  
RHEA:28987 | GO:0015538 | TRANS-RXN-25 |  
RHEA:29995 | GO:0015594 | ABC-25-RXN |  
RHEA:15181 | GO:0015607 | 3.6.3.47-RXN |  
RHEA:29899 | GO:0015614 | ABC-33-RXN |  
RHEA:29795 | GO:0015633 | ABC-63-RXN |  
RHEA:29943 | GO:0015649 | TRANS-RXN-113 |  
RHEA:29283 | GO:0015655 | TRANS-RXN-125 |  
RHEA:49296 | GO:0022871 | RXN-15172 | Make RHEA xref = narrow. Add more general MetaCyc xref (RXN-15094) to GO.
RHEA:32783 | GO:0031459 | TRANS-RXN-283 |  
RHEA:32779 | GO:0032778 | TRANS-RXN-459 |  
RHEA:32795 | GO:0033230 | RXN0-3 |  
RHEA:29779 | GO:0033232 | RXN0-4522 | Wrong RHEA xref - change to RHEA:29767/TRANS-RXN0-202
RHEA:32747 | GO:0034228 | TRANS-RXN0-476 |  
RHEA:33163 | GO:0034257 | TRANS-RXN0-481 |  
RHEA:29427 | GO:0044667 | TRANS-RXN-100 |  
RHEA:29811 | GO:0048502 | ABC-32-RXN |  
RHEA:32143 | GO:0061459 | RXN66-448 |  
RHEA:30011 | GO:0102014 | ABC-18-RXN |  
RHEA:61716 | GO:0103116 | TRANS-RXN-333 | Also remove existing: MetaCyc:TRANS-RXN0-491 (SUBTYPE)
RHEA:30403 | GO:0140571 | RXN-15598 | Also remove existing MetaCyc:1.10.2.1-RXN (OBSOLETE)
RHEA:25792 | GO:0140581 | RXN-14455 |  
RHEA:66820 | GO:0140613 | RXN-20940 |  
RHEA:14633 | GO:0140679 | RXN-17739 |  
RHEA:35027 | GO:1901238 | TRANS-RXN-242B |

</google-sheets-html-origin>

**Comment by cmungall** [comment]
This is great Steven

My question for the rest of the group is why aren’t we doing this
automatically

**Comment by deustp01** [comment]
> My question for the rest of the group is why aren’t we doing this automatically

Truly slow Monday morning question - what exactly did Steven do, and how would I apply that to my favorite groups of reactions? (Manually to start, then automatically later as a check on newly annotated material.)

**Comment by cmungall** [comment]
skos:exactMatch is transitive so we can assert inferences from this. GO:x
exactMatch RHEA:y exactMatch MetaCyc:z ==> GO:x exactMatch MetaCyc:z

**Comment by sjm41** [comment]
> My question for the rest of the group is why aren’t we doing this automatically

Right. @pgaudet and I discussed this recently and also thought that grabbing other DB xrefs (for catalytic and transporter MF terms) c/should be done automatically and regularly, using RHEA as our 'source of truth'.  Would be good if a curator/editor looked over a report of such automated updates to sanity-check the changes - as noted above, 16/60 cases needed a bit of manual investigation (including a couple of tickets to RHEA).

The bigger issue here is how to accurately and efficiently associate GO transporter terms that have **no** current RHEA xref with their matching RHEA (and thereby other xrefs).  That would be a separate ticket, unless this exercise is already underway somewhere?
