### ISSUE TITLE
dopamine receptor signaling pathway is_a GPCR

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26959]
As far as @hattrill and I can tell, all dopamine receptors are GPCRs.

Please 

- [ ] change label 
- [ ] move under [G protein-coupled receptor signaling pathway](http://purl.obolibrary.org/obo/GO_0007186)
- [ ] change definition to match those of new siblings

**Comment by hattrill** [comment]
My initial thoughts are after having a quick look that:
We have specific terms for the pathway that the GPCR is coupled to 
e.g.  GO:0030845 phospholipase C-inhibiting G protein-coupled receptor signaling pathway
in some cases we have the receptor-specific pathway name:
GO:0071880 adenylate cyclase-activating adrenergic receptor signaling pathway
GO:0071881 phospholipase C-activating adrenergic receptor signaling pathway

So, if DA receptors have a similar pattern of receptors coupled to different heterotrimeric G-proteins we could have a  type of "β-arrestin dependent G protein-coupled receptor signaling pathway" and expand the definition of G-protein receptor to include β-arrestin.

It looks like β-arrestin signaling does not occur in concert with the more classical Galpha-route, so it does look like a separate pathway. Think that we'd have to be careful with what we mean by a "β-arrestin dependent GPCR signaling pathway" e.g. careful to distinguish when arrestin acts as a regulator or regulates receptor-mediated endocytosis vs a signaling pathway.

Alternatively, we keep dopamine receptor signaling pathway where it is and have two flavours: 
dopamine receptor G protein-coupled signaling pathway
dopamine receptor β-arrestin dependent signaling pathway
and make dopamine receptor signaling pathway a "DO NOT ANNOTATE"

I would like to do a bit more reading to see how prevalent this mode of GPCR action is.

**Comment by raymond91125** [comment]
PMID:30120413 more recent evidence of G-protein independent, beta arresting-mediated DA signalling.

**Comment by pgaudet** [comment]
Thanks @raymond91125 

We don't have any arrestin signaling pathway, this seems relatively new, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5591062/

@hattrill should we go over this one more time?

**Comment by hattrill** [comment]
@pgaudet yes, sounds like a good idea. I'll have a read over these for our Monday meeting, if that's ok?

**Comment by pgaudet** [comment]
Replaced by https://github.com/geneontology/go-ontology/issues/28005
