### ISSUE TITLE
Taxon constraint: GO:0043045   post-fertilization epigenetic regulation of gene expression

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26951]
Please provide as much information as you can: 

* **GO term ID label:**

GO:0043045   post-fertilization epigenetic regulation of gene expression

* **Request to add a taxon constraint:**
* * **only in taxon: **

metazoa

**Comment by ValWood** [comment]
OK will add "never in fungi"

**Comment by pgaudet** [comment]
Thanks for the comments @cmungall 

In fact @colinlog and I just recently discussed merging 
GO:0043045 post-fertilization epigenetic regulation of gene expression with is child:  GO:0044725 epigenetic programming in the zygotic pronuclei. 

I am not sure to what extend you'd like to reduce this branch.

**Comment by cmungall** [comment]
> In fact @colinlog and I just recently discussed merging
> GO:0043045 post-fertilization epigenetic regulation of gene expression with is child: GO:0044725 epigenetic programming in the zygotic pronuclei.

Does that definitely work with existing annotations? The text definition says "during embryonic development" which is very broad and I'm pretty sure some of the existing annotations describe things after the zygote.

Additionally we have a classic lopsided christmas tree structure:

* [] GO:0040029 ! epigenetic regulation of gene expression
    * [i] **GO:0043045 ! post-fertilization epigenetic regulation of gene expression**
        * [i] GO:0044725 ! epigenetic programming in the zygotic pronuclei
            * [i] GO:0141044 ! epigenetic programming in the endosperm
            * [i] GO:0044727 ! epigenetic programing of male pronucleus
            * [i] GO:0044726 ! epigenetic programing of female pronucleus

"zygotic pronuclei" sounds metazoan but it's actually for animals or plants. However, plants annotate one level below. Animals annotate one level below if it's known if it's male or female.

**Comment by pgaudet** [comment]
@cmungall 

To answer the 'easy' part of your comment above 

> If I was a user and I was interested in this concept I’d intersect all dna
methylation genes, histone deac genes, with genes expressed during
embryogenesis, then if I was interested in persistence of state further
intersecting using genomic data. I believe this would get me a more
accurate gene set than querying on the odd GO grouping.

This is what the grand-parent class [epigenetic regulation of gene expression](http://purl.obolibrary.org/obo/GO_0040029) represents. 

The challenge is to describe imprinting in plants and in animals.

**Comment by pgaudet** [comment]
After reviewing annotations, @colinlog and I have decided to change the label of 

to 'epigenetic programming of gene expression' GO:0043045 ! post-fertilization epigenetic regulation of gene expression. 

We have also moved [genomic imprinting](http://purl.obolibrary.org/obo/GO_0071514) as a child of this term.

**Comment by ValWood** [comment]
right, I misunderstood. 

I thought
GO:0043045 post-fertilization epigenetic regulation of gene expression
was the term you were relabelling.
ignore.

**Comment by pgaudet** [comment]
No, you're right !! Correct label is epigenetic programming of gene expression

**Comment by pgaudet** [comment]
> 'epigenetic programming of gene expression' GO:0043045
sounds as though it could also be used by yeast... it's also very similar to
'epigenetic regulation of gene expression'

The distinction is the 'programming' part, ie there are some changes being made to the DNA that occur in early development and that persist in the organism, and that has the potential for regulating gene expression. 
Maybe some 'developmental' aspect is missing from the label, but it is in the definition. 

Suggestions for improvement as welcome! 

Pascale

**Comment by ValWood** [comment]
Maybe  yeast people don't use the term"programming", it will be fine since it s taxon restricted, and its clear from the definition.
