### ISSUE TITLE
NTR: [Gasoreceptor activity]

### ISSUE THREAD

**Issue by GasoreceptorAtlas** [geneontology/go-ontology#26963]
Please provide as much information as you can: 

* **Suggested term label:**
Gasoreceptor activity

* **Definition (free text)**
Interacting with a gaseous signaling molecule or gasotransmitter or its solute and transmitting a signal via an additional catalytic domain or DNA binding transcriptional activity.

* **Reference, in format PMID:#######**
(REQUIRED)
PMID 38231000

* **Gene product name and ID to be annotated to this term**
https://amigo.geneontology.org/amigo/gene_product/MGI:MGI:2660877
https://amigo.geneontology.org/amigo/gene_product/WB:WBGene00001555
https://amigo.geneontology.org/amigo/gene_product/UniProtKB:P76129
https://amigo.geneontology.org/amigo/gene_product/FB:FBgn0038295
https://amigo.geneontology.org/amigo/gene_product/UniProtKB:P0A9E5

* **Parent term(s)**
Parent: GO:0007154 cell communication

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
GO:0007263
GO:0019826
GO:0038060

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
classical oxygen signaling, oxygen sensor activity, classical nitric oxide signaling, 

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

[KEGG: K14986 ](https://www.genome.jp/entry/K14986)
[KEGG: CELE_T04D3.4 ](https://www.genome.jp/entry/cel:CELE_T04D3.4)
[KEGG: 2977   ](https://www.genome.jp/entry/hsa:2977)
[KEGG eco:b1489] https://www.genome.jp/entry/eco:b1489

* 

* **Any other information**

**Comment by suzialeksander** [comment]
Noting they also supplied us with a GH repo of gasoreceptor proteins based on GO ID-based data mining: https://github.com/GasoreceptorAtlas
ZENODO: Gasoreceptor Atlas v1.0.0. doi: [10.5281/zenodo.10619030](https://doi.org/10.5281/zenodo.10619030)

OP was referred by Xenbase.

**Comment by pgaudet** [comment]
Dear @GasoreceptorAtlas 
Thank you for contacting GO. 
We have terms that represent this function: 

'GO:0019826 oxygen sensor activity'
'GO:0070027 carbon monoxide sensor activity'

We can add a broad synonym, "gasoreceptor activity", it would help find the correct terms. Does this work ? 

Thanks, Pascale

**Comment by GasoreceptorAtlas** [comment]
Dear Pascale, 

I strongly believe a new GO TERM is needed for 'gasoreceptor activity'. This will unite gasoreceptors for numerous gaseous signaling molecules and associated pathways from archaea to humans under a single new GO TERM. 
Moreover, as gases/gasotransmitters can diffuse across cells, a new term will allow us to add it below other parent terms related to cell signaling and/or cellular functions. 

The following GO terms will be under the new term 'gasoreceptor activity'. 
'GO:0019826 oxygen sensor activity'
'GO:0070027 carbon monoxide sensor activity'
'GO:0035991 nitric oxide sensor activity' 
'GO:0003031 detection of carbon dioxide' 
'GO:0038199 ethylene receptor activity'


Finally, if you check the GO:0140442; peroxide sensor activity, currently there are only two proteins in. But we have GO term for it. In the case of the GO term 'gasoreceptor activity' will most likely constitute many gasoreceptors. Hence, in my opinion, we need a GO TERM and broad synonym is simply not enough. 

Hope this clarifies the complexity of gasoreceptors and the need for the new GO term. 

Thanks,
Savani

**Comment by pgaudet** [comment]
Thanks for the feedback @GasoreceptorAtlas 

I will bring this up with the ontology editors at our next meeting and get back to you. 

Best regards, 

Pascale

**Comment by GasoreceptorAtlas** [comment]
Dear Pascale,

I understand you. But unnecessary complexity in the ontology was not cited
as a reason when new terms such as gravitrophic receptor or
mechanoreceptor or photoreceptor were introduced.
Please see poster on gasoreceptor here:
https://zenodo.org/doi/10.5281/zenodo.10668509
It is time that GO consider gaseous chemicals differently.

best wishes,
Savani

**Comment by GasoreceptorAtlas** [comment]
![Uploading Savani_Poster_gasoreceptor_pages-to-jpg-0001.jpg…]()
