### ISSUE TITLE
Obsoletion request: GO:0036363 transforming growth factor beta activation & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26977]
Dear all, 

The proposal has been made to obsolete & replaced by either by 'x regulator activity' or maybe in this case, regulation of the TGF pathway.

GO:0036363 transforming growth factor beta activation
GO:1901389 negative regulation of transforming growth factor beta activation
GO:1901390 positive regulation of transforming growth factor beta activation
GO:1901388 regulation of transforming growth factor beta activation
GO:0036364 transforming growth factor beta1 activation
GO:0036365 transforming growth factor beta2 activation
GO:0036366 transforming growth factor beta3 activation
GO:1901393 negative regulation of transforming growth factor beta1 activation
GO:1901394 positive regulation of transforming growth factor beta1 activation
GO:1901392 regulation of transforming growth factor beta1 activation
GO:1901396 negative regulation of transforming growth factor beta2 activation
GO:1901397 positive regulation of transforming growth factor beta2 activation
GO:1901395 regulation of transforming growth factor beta2 activation
GO:1901399 negative regulation of transforming growth factor beta3 activation
GO:1901400 positive regulation of transforming growth factor beta3 activation
GO:1901398 regulation of transforming growth factor beta3 activation

The reason for obsoletion is that these represent molecular functions. 

Annotations are here: https://github.com/geneontology/go-annotation/issues/4984

**Comment by edwong57** [comment]
- [ ] GO:0036363 transforming growth factor beta activation
- [ ] GO:1901389 negative regulation of transforming growth factor beta activation
- [ ] GO:1901390 positive regulation of transforming growth factor beta activation
- [ ] GO:1901388 regulation of transforming growth factor beta activation
- [ ] GO:0036364 transforming growth factor beta1 activation
- [ ] GO:0036365 transforming growth factor beta2 activation
- [ ] GO:0036366 transforming growth factor beta3 activation
- [ ] GO:1901393 negative regulation of transforming growth factor beta1 activation
- [ ] GO:1901394 positive regulation of transforming growth factor beta1 activation
- [ ] GO:1901392 regulation of transforming growth factor beta1 activation
- [ ] GO:1901396 negative regulation of transforming growth factor beta2 activation
- [ ] GO:1901397 positive regulation of transforming growth factor beta2 activation
- [ ] GO:1901395 regulation of transforming growth factor beta2 activation
- [ ] GO:1901399 negative regulation of transforming growth factor beta3 activation
- [ ] GO:1901400 positive regulation of transforming growth factor beta3 activation
- [ ] GO:1901398 regulation of transforming growth factor beta3 activation
