### ISSUE TITLE
Obsoletion request:  GO:0061610 glycerol to glycerone phosphate metabolic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26974]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0061610 glycerol to glycerone phosphate metabolic process

* **Reason for deprecation** Put an x in the appropriate box: 
 
 - [ ] The reason for obsoletion is that this term represents a molecular function.

Defined as "The chemical reactions and pathways in which glycerol, 1,2,3-propanetriol, is converted to glycerone phosphate.", which corresponds to the MF GO:0141152 glycerol-3-phosphate dehydrogenase (NAD+) activity (this is the reaction in eukaryotes)

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP: 7, SGD, consider 'glycerol catabolic process' at least for PMID:22979944

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by raymond91125** [comment]
Aren't there two enzymes involved?
![image](https://github.com/geneontology/go-ontology/assets/619520/a989bd77-061a-4ea8-8c9c-29d54198c68b)

**Comment by raymond91125** [comment]
@pgaudet Can we have two-step (two-enzyme) process in MF?

**Comment by pgaudet** [comment]
Hi @raymond91125 

Can you tell me where that figure is from? 

In fact I came across these terms because we had two BPs with the same logical definitions, see https://github.com/geneontology/go-ontology/issues/21790#issuecomment-1929694137

The term yeast genes annotated to https://amigo.geneontology.org/amigo/term/GO:0061610
are 	Dihydroxyacetone kinase and 	Glycerol dehydrogenase; as far as I can tell these are not the same as the pathway you show above? 

If you can formulate the pathway that 'GO:0061610 glycerol to glycerone phosphate metabolic process' is supposed to represent (start end end, and maybe all the steps would be useful here), then it's fine to keep this term. 

Thanks for looking into this. 

Pascale

**Comment by raymond91125** [comment]
> Can you tell me where that figure is from?

https://chem.libretexts.org/Courses/Brevard_College/CHE_301_Biochemistry/09%3A_Metabolism_of_Lipids/9.03%3A_Glycerol_Metabolism
Also good figures in PMID:30883020.

> If you can formulate the pathway that 'GO:0061610 glycerol to glycerone phosphate metabolic process' is supposed to represent (start end end, and maybe all the steps would be useful here), then it's fine to keep this term.

I thought the definition is pretty clear for the start (glycerol) and end (glycerone phosphate). MF GO:0141152 glycerol-3-phosphate dehydrogenase (NAD+) activity seems to be the second part of GO:0061610 glycerol to glycerone phosphate metabolic process.

**Comment by raymond91125** [comment]
@pgaudet Should I close this ticket or proceed with obsoletion?

**Comment by pgaudet** [comment]
Thanks @raymond91125 

OK, this looks like a pathway. The reason why I ran into is in https://github.com/geneontology/go-ontology/issues/21790

The logical definition was 

'glycerol metabolic process'
 and ('has part' some 'glycerol-3-phosphate dehydrogenase [NAD(P)+] activity')
 and ('starts with' some 'glycerol kinase activity')
 and ('has primary output' some 'glycerone phosphate(2-)')
 and ('has primary input' some glycerol)

Which I removed because it was conflicting with the glycerol shuttle
A few issues: 
- the primary input = 'glycerol' will classify this as a catabolic process; is that OK ? 
- 'has part' some 'glycerol-3-phosphate dehydrogenase [NAD(P)+] activity') is the bacterial enzyme; the LD should use [glycerol-3-phosphate dehydrogenase (NAD+) activity](http://purl.obolibrary.org/obo/GO_0141152)
- also that [glycerol-3-phosphate dehydrogenase (NAD+) activity](http://purl.obolibrary.org/obo/GO_0141152) activity should be using the relation 'ends with' 


The logical definition of '[glycerophosphate shuttle](http://purl.obolibrary.org/obo/GO_0006127) should also be reviewed. 

Thanks, Pascale

**Comment by raymond91125** [comment]
GO:0061610 glycerol to glycerone phosphate metabolic process == 
'metabolic process'
and ('starts with' some 'glycerol kinase activity') 
and ('ends with' some 'glycerol-3-phosphate dehydrogenase (NAD+) activity')
and ('has primary input' some glycerol)
and ('has primary output' some 'glycerone phosphate(2-)')

**Comment by raymond91125** [comment]
https://en.wikipedia.org/wiki/Glycerol_phosphate_shuttle
![image](https://github.com/geneontology/go-ontology/assets/619520/d80a4d00-483f-4d3c-9aae-c5b30e2b080d)
Make the LD more complete.
glycerophosphate shuttle ==
'metabolic process' 
and ('has part' some 'glycerol-3-phosphate dehydrogenase (quinone) activity') 
and ('has part' some 'glycerol-3-phosphate dehydrogenase (NAD+) activity') 
and ('has participant' some 'sn-glycerol 3-phosphate(2-)') 
and ('has participant' some 'glycerone phosphate(2-)') 
and ('has primary output' some 'NAD(1-)')
and ('has primary input' some 'NADH(2-)')
and ('has primary output' some 'hydroquinones')
and ('has primary input' some '1,4-benzoquinones')
