### ISSUE TITLE
NTR: (1) 'symbiont-mediated suppression of host phagosome maturation' (2) symbiont-mediated suppression of host phagosome acidification, (3) disruption of host phagosome

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26987]
Please provide as much information as you can: 
For GO-PATHGO alignment 
PATHGO:0000241
and  PATHGO:0000239

* **Suggested term label:**
1. **symbiont-mediated suppression of host phagosome maturation**: child of GO:0044068 ! symbiont-mediated perturbation of host cellular process
2. **symbiont-mediated suppression of host phagosome acidification**: child of GO:0044068 ! symbiont-mediated perturbation of host cellular process
3. **symbiont-mediated disruption of host phagosome**

* **Reference, in format PMID:#######**
maturation: PMID:21501366

**Comment by pgaudet** [comment]
@genegodbold to provide references

**Comment by pgaudet** [comment]
PR is here: https://github.com/geneontology/go-ontology/pull/26986

**Comment by genegodbold** [comment]
**Bacterial proteins arresting phagosome maturation**
- **Ehrlichia translocated factor-2** (Etf-2; Ech0261): Etf-2 is a T4aSS effector that localizes to ehrlichial inclusions and sequesters the host Rab5 small GTPase in its GTP-bound form. Etf-2 delays Rab5 dissociation from (and Rab7 localization to) phagosomes from endosomes. Binding of Etf-2 to Rab5-GTP delays Rab5 inactivation and avoids routing of ehrlichial inclusions to host phagosomes [PMID:30181274].
- **Region allowing vacuole co-localization D** (RavD): RavD is a translocated effector of the Dot/Icm T4BSS of _Legionella pneumophila_. It binds host phosphatidylinositol-3-phosphate and facilitates the suppression of endolysosomal maturation of the Legionella-containing vacuole (LCV) [PMID:30733336].
- **Glyceraldehyde-3-phosphate dehydrogenase** (GADPH; Lmo2459) from _Listeria monocytogenes_: GADPH from within the phagosomal membrane recruits host Rab5a to bacteria-containing vacuoles and ADP-ribosylates the host small GTPase. This also results in the inhibition of guanine exchange factor activity. The effect is to block maturation of the phagosome [PMID:18088303].
- **PE_PGRS62** (Rv3812) from _Mycobacterium tuberculosis_: When a mutant _M. smegmatis_ bacterium expressing the cell wall protein PE_PGRS62 is used to infect murine macrophages, it induces an arrest in the host phagosome maturation pathway, acquiring the host small GTPase Rab5 but not Rab7 or LAMP-1. When expressed ectopically in yeast, PE-PGRS62 disrupts vacuolar protein sorting [PMID:23167250]. When a macrophage cell line is infected with M. smegmatis expressing PE_PGRS62, host phagolysosome fusion is disrupted and bacterial survival is enhanced [PMID:30937925].

**Bacterial proteins mediating escape from the host phagosome**
- **Burkholderia outer protein A** (BopA): BopA is required for efficient escape of bacteria from phagosomes into the cytosol. BopA may play a direct role in disruption of the phagosome membrane, facilitating escape of the sequestered bacteria into the host cytosol [PMID:21412437]. 
- **OpiA** from _Francisella tularensis_ is encoded by a gene located outside the Francisella pathogenicity island (FPI). OpiA has phosphatidylinositol-3 kinase activity and it produces phosphotidylinositol-3-phosphate on late-endosome-like Francisella-containing phagosomes, facilitating the escape of the bacteria into the cytoplasm of the infected host cell. OpiA can selectively bind to PI(3)P which might account for its localization on the cytoplasmic face of early endosome-like vacuoles. OpiA maintains PI(3)P on the Francisella-containing phagosome (FCP) even as the vacuole matures [PMID:30057173].
- **IglG** from _Francisella tularensis_ is absolutely required for Francisella escape into the host cytosol. IglG is a metal-binding PAAR-like protein, a member of the DUF4280 family with four conserved Cys residues that are critical for IglG function. IglG also interacts with IglF and is required for the secretion of IglC. IglG is secreted by the T6SS [PMID:27602570].
- **Listeriolysin O** (LLO) from _Listeria monocytogenes_: Listeriolysin allows the bacterium to escape from the vacuole created when it propels itself via an actin rocket-tail into a new cell from a neighboring cell. LLO is secreted as a monomer, diffuses to the membrane, and then assembles with up to 50 other monomers into a pore up to 3 micrometers in diameter that allows bacterial entry into the cytoplasm. LLO is responsible for the release of the pathogen from the phagocytic vacuole. Listeria are five orders of magnitude less virulent in the absence of the gene encoding LLO [PMID:17720603]. The activity of LLO is controlled by pH [PMID:22652164]. LLO works in concert with two phospholipase C proteins to allow bacterial entry into the cytoplasm from the phagocytic vacuole: phosphatidylinositol (PI) PLC and phosphatidylcholine (PC) PLC. These enzymes work synergistically with LLO in lysing primary and secondary vacuoles [PMID:15487949].

**Comment by pgaudet** [comment]
@genegodbold 

For acidification, I added these 2 references: PMID:22087003, PMID:33505976

I also modified the definition to include example of mechanisms for disruption of acidification:  "A process in which a symbiont inhibits or disrupts the normal acidification of host phagosomes. **Mechanisms by which a symbiont prevents host phagosome acidification include the inhibitition of host V-ATPase, the proton pump that acidifies the phagosome, or disruption of the phagosome membrane by pore-forming toxin.** "

Thanks, Pascale

**Comment by genegodbold** [comment]
These are bacterial proteins that disrupt phagosomal acidification--you have a reference for the second one (PMID:22087003):
- **Substrate of Icm/Dot K** (SidK; lpg0968) from _Legionella pneumophila_: SidK is a bacterial effector that blocks vacuolar proton-ATPase hydrolysis and proton translocation by interacting with VatA (Vma1), the ATP-hydrolyzing subunit. Macrophages in which SidK is overexpressed show defects in phagosome acidification and bacterial killing [PMID:20333253].
- **Protein tyrosine phosphatase A** (PtpA) from _Mycobacterium tuberculosis_: PtpA can prevent fusion of host lysosomes with the phagosome by dephosphorylating host VPS33B [PMID:18474358]. PtpA prevents phagosome acidification by binding to subunit H of the macrophage vacuolar ATPase complex to block trafficking of the ATPase [PMID:22087003].
