### ISSUE TITLE
Obsoletion request: GO:1902938 regulation of intracellular calcium activated chloride channel activity & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26980]
To complete https://github.com/geneontology/go-ontology/issues/26874

[GO:1902939 negative regulation of intracellular calcium activated chloride channel activity](https://amigo.geneontology.org/amigo/term/GO:1902939#display-lineage-tab)
 [GO:1902940 positive regulation of intracellular calcium activated chloride channel activity](https://amigo.geneontology.org/amigo/term/GO:1902940#display-lineage-tab)
 [GO:1902938 regulation of intracellular calcium activated chloride channel activity](https://amigo.geneontology.org/amigo/term/GO:1902938#display-lineage-tab)

**Comment by raymond91125** [comment]
@pgaudet please confirm
The reason for obsoletion is that this term represents regulation of a molecular function.

**Comment by pgaudet** [comment]
Yes
