### ISSUE TITLE
NTR: "lncRNA 3' end processing & lncRNA processing & lncRNA surveillance

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#26988]
Please provide as much information as you can: 

* **Suggested term label:**

- [x] "lncRNA 3' end processing added in https://github.com/geneontology/go-ontology/issues/27000
relabel to "co-transcriptional lncRNA 3' end processing, cleavage and polyadenylation pathway"

- [x] lncRNA processing
- [x] lncRNA surveillance 

* **Definition (free text)**

standard def

* **Gene product name and ID to be annotated to this term**

TERC (a lncRNA)

* **Parent term(s)**

* **Any other information**

required for https://github.com/geneontology/go-ontology/issues/26761
@RLovering

**Comment by pgaudet** [comment]
Can you paste the new term stanza in the ticket? (generally) - makes it easier to keep track. 

Thanks, Pascale

**Comment by ValWood** [comment]
[Term]
id: GO:0180035
name: lncRNA processing
namespace: biological_process
def: "Any process involved in the conversion of one or more primary lncRNA transcripts into one or more mature lncRNA molecules." [PMID:31276588]
is_a: GO:0006396 ! RNA processing
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26988" xsd:anyURI
created_by: vw
creation_date: 2024-02-14T14:46:35Z

[Term]
id: GO:0180036
name: nuclear lncRNA surveillance
namespace: biological_process
def: "A process that identifies and degrades defective or aberrant lncRNAs within the nucleus." [GOC:vw]
is_a: GO:0071027 ! nuclear RNA surveillance
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26988" xsd:anyURI
created_by: vw
creation_date: 2024-02-14T15:37:20Z

[Term]
id: GO:0180034
name: co-transcriptional lncRNA 3' end processing, cleavage and polyadenylation pathway
namespace: biological_process
def: "Any process involved in transcription termination-coupled 3' processing of RNA polymerase II lncRNA transcripts by the 3' end cleavage and addition of a poly(A) tail." [PMID:31276588]
synonym: "lncRNA 3' end processing" BROAD []
synonym: "lncRNA 3'-end processing" BROAD []
is_a: GO:0180012 ! co-transcriptional RNA 3'-end processing, cleavage and polyadenylation pathway
is_a: GO:0180035 ! lncRNA processing
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26988" xsd:anyURI

**Comment by ValWood** [comment]
I had to revert
polyadenylation-dependent snoRNA 3'-end processing
 and move it out from under
co-transcriptional RNA 3'-end processing, cleavage and polyadenylation pathway

It seems that snoRNA processing is very different (there might be multiple pathways?) some pathways involve TARAMP/exosome which is not the case for 
co-transcriptional RNA 3'-end processing, cleavage and polyadenylation pathway
I'm trying to locate good reviews but we will need to deal with this separately.
