### ISSUE TITLE
NTR: symbiont-mediated suppression of host exocytosis 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#26985]
For GO-PATHGO alignment - PATHGO:0000047

* **Suggested term label:**
symbiont-mediated suppression of host exocytosis 

* **Definition (free text)**

* **Reference, in format PMID:#######**
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
'symbiont-mediated perturbation of host vesicle-mediated transport' <http://purl.obolibrary.org/obo/GO_1990215>

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141157
+name: symbiont-mediated suppression of host exocytosis
+namespace: biological_process
+def: "A process in which a symbiont inhibits or disrupts the normal execution of  host exocytosis. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:pg]
+is_a: GO:1990215 ! symbiont-mediated perturbation of host vesicle-mediated transport
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26985" xsd:anyURI
+created_by: pg
+creation_date: 2024-02-07T15:18:55Z

**Comment by pgaudet** [comment]
Still need to add references

**Comment by genegodbold** [comment]
@pgaudet, I'm afraid I'm not going to be able to get to these until next week.

**Comment by genegodbold** [comment]
**Botulinum neurotoxin A** (botulinum neurotoxin type A; Bont/A; neurotoxin subtype A; peptidase M27); this also includes all versions of botulinum neurotoxin (subtypes B, C, D, E, F, and G)
- The light chains of the botulinum neurotoxins are zinc metallopeptidases that cut one of three host soluble N-ethylmaleimide-sensitive fusion protein attachment protein receptors (SNARE) proteins: (a) vesicle associated membrane protein (VAMP/ synaptobrevin, (b) synaptosomal-associated protein of 25 kDa (SNAP25) or (c) syntaxin. These host molecules regulate vesicle fusion. Cleavage of any of these three host proteins prevents the release of neurotransmitters from synaptic vesicles into the synaptic cleft and effectively shuts down neurotransmission from that nerve cell [PMID:17185412].
- The heavy chains of the botulinum neurotoxins mediate specific binding to host neurons, uptake by receptor-mediated endocytosis, and transport of the catalytic light chains across the endosomal membrane into the cytosol where they encounter one of the three SNARE proteins. Host gangliosides act as co-receptors [PMID:17185412]. The main determinant of the neurospecificity of the clostridial neurotoxins is encoded in the C terminus of the heavy chain. The C terminal domain of the heavy chain contains four distinct carbohydrate-binding regions which mediate the association with surface lipids containing sialic acid and, possibly, with neuronal glycoproteins. Both the tetanus and botulinum toxins bind to polysialogangliosides [PMID:15649138]. 

**Tetanus toxin** is expressed as a 150kDa polypeptide that is post-translationally cleaved into a heavy (100 kDa) and light (50kDa) chain linked by a disulfide bond. The heavy chain mediates attachment and invasion of the toxin into a peripheral neuron which is then transported to neurons of the central nervous system. The catalytic light chain is a zinc-dependent metalloprotease that cuts members of the host SNARE family. Cleavage of presynaptic SNAREs prevents formation of secretory vesicles responsible for neurotransmission [PMID:28645943].
- The heavy chain of tetanus toxin binds to polysialogangliosides on host cells. One receptor for tetanus toxin may be the GD1b ganglioside [PMID:14731268]. Synaptic proteins are also probably receptors or co-receptors for the toxin [PMID:19602728]. These might include the host synaptic vesicle proteins SV2A and SV2B [PMID:21124874]. Host nidogens, also called entactins, at the neuromuscular junction play a role in tetanus toxin internalization [PMID:25430769]. 
- Tetanus neurotoxin is recruited to the axonal retrograde transport pathway and reaches the cell bodies of motor neurons in the spinal cord. It is then targeted to inhibitory interneurons where it blocks the release of glycine [PMID:15649138].

**Comment by pgaudet** [comment]
Hi @genegodbold 

It seems like we have effect both on exocytosis and on endocytosis here; maybe some of these references should go to [symbiont-mediated perturbation of host receptor-mediated endocytosis](http://purl.obolibrary.org/obo/GO_0044077) ?

**Comment by pgaudet** [comment]
Also, we could consider creating a symbiont equivalent term for [envenomation resulting in modulation of transmission of nerve impulse in another organism](http://purl.obolibrary.org/obo/GO_0044487)

**Comment by genegodbold** [comment]
1. Endocytosis is necessary for uptake of the toxins, but I don't think it subsequently affects host endocytosis.
2. I don't think I've ever felt I *needed* an endocytosis term.
3. I know I would use an "symbiont-mediated altered host endosomal trafficking" term. (There are lots of weirdnesses I would label with that one.)
4. You mentioned authoring a new "symbiont-mediated suppression of host secretion". I think I *would* use that term, but I don't know if I have any candidates for that without a wholesale search of the spreadsheet. And since I note "secretion systems" I have thousands of entries I would have to check in detail.

**Comment by pgaudet** [comment]
Based on @genegodbold 's comments, this can be closed.
