### ISSUE TITLE
Missing parent: GO:0038066   p38MAPK cascade

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27008]
* **GO term ID and label for which you request a new superclass**

GO:0038066   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0038066/complete)
p38MAPK cascade

* **New superclass (parent) suggested**

GO:0051403   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0051403/complete)
stress-activated MAPK cascade

* **Reference(s), if appropriate**

Currenlty , all of the yeast MAPK cacases are under stress-activated MAPK cascade, except for  p38MAPK cascade
which is the major stress-activated MAPK (i.e Sty1 in pombe /HOG1 in S. cerevisiae)

**Comment by pgaudet** [comment]
I proposed to obsolete GO:0031098 stress-activated protein kinase signaling cascade and GO:0051403 stress-activated MAPK cascade see 
https://github.com/geneontology/go-ontology/issues/26810

Is this OK for you? 

p83 is not only involved in response to stress, this is why I moved it out of there for now.

**Comment by ValWood** [comment]
Yes, sorry, I forgot that. I got some unexpected automated mappings to 
GO:0031098 stress-activated protein kinase signaling cascade
now it is no longer a child, but they will go away.
