### ISSUE TITLE
phosphate ion transmembrane transporter activity (GO:0015114) discrepancies

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27012]
There are several discrepancies with this (grouping) term:

```id: GO:0015114
name: phosphate ion transmembrane transporter activity
namespace: molecular_function
alt_id: GO:1901677
def: "Enables the transfer of phosphate (PO4 3-) ions from one side of a membrane to the other." [GOC:ai]
synonym: "phosphate transmembrane transporter activity" RELATED [GOC:vw]
xref: RHEA:32823
intersection_of: GO:0022857 ! transmembrane transporter activity
intersection_of: has_primary_input CHEBI:35780 ! phosphate ion
relationship: part_of GO:0035435 {http://purl.org/dc/terms/source="GO_REF:0000090"} ! phosphate ion transmembrane transport
created_by: pr
creation_date: 2012-11-22T15:43:10Z
```

1. Definition specifies PO4(3-) ions (which is CHEBI:18367)
2. The RHEA xref is for "phosphate(in) = phosphate(out)" where phosphate = CHEBI:43474 = HPO4(2-) ion.
3. The CHEBI:35780 ID in the "intersection_of: has_primary_input " line looks like it's for a generic 'phosphate ion', I think (i.e. no charge specified).

Anyone know which CHEBI ID is correct here?
I'm thinking that the generic one (CHEBI:35780) specified in the "has_primary_input" line is correct, given this is a grouping term?
If that's true, then the definition needs tweaking and the RHEA xref needs removing (or made a narrowMatch).

@deustp01 ?

**Comment by pgaudet** [comment]
The ph7.3 ChEBI should be used, ie the one used by RHEA.

**Comment by pgaudet** [comment]
Updated CHEBI for phosphate in all terms. 

@sjm41 anything else that needs fixing here? 

Thanks, Pascale

**Comment by sjm41** [comment]
Thanks @pgaudet 
Just need to update the text def of GO:0015114 to match, so change "phosphate (PO4 3-) ions" to "phosphate (HPO4 2-) ions"?

**Comment by deustp01** [comment]
> Just need to update the text def of GO:0015114 to match, so change "phosphate (PO4 3-) ions" to "phosphate (HPO4 2-) ions"?

Agreed. Here are some quotes from Hunter T. Why nature chose phosphate to modify proteins. Philos Trans R Soc Lond B Biol Sci. 2012 Sep 19;367(1602):2513-6. PMID: 22889903; PMCID: PMC3415839.

> Phosphate has three pKas (2.2, 7.2 (5.8 as an ester) and 12.4) and is highly soluble in water, forming a large hydrated ionic shell. ... Because of its three pKas, phosphate is dianionic at pH 7, the physiological intracellular pH.

**Comment by sjm41** [comment]
Hi @pgaudet 

> Updated CHEBI for phosphate in all terms.

I was just looking at this term:

id: GO:0005436
name: sodium:phosphate symporter activity
namespace: molecular_function
alt_id: GO:0015321
def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: Na+(out) + phosphate(out) = Na+(in) + phosphate(in)." [TC:2.A.1.14.6]
synonym: "sodium-dependent phosphate transmembrane transporter activity" RELATED []
synonym: "sodium/phosphate symporter activity" EXACT []
xref: TC:2.A.1.14.6
intersection_of: GO:0015293 ! symporter activity
intersection_of: has_primary_input CHEBI:26020 ! phosphate
intersection_of: has_primary_input CHEBI:29101 ! sodium(1+)
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/18577" xsd:anyURI
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/23132" xsd:anyURI

Based on discussion above, should "intersection_of: has_primary_input CHEBI:26020 ! phosphate" by changed to "intersection_of: has_primary_input **CHEBI:43474 ! hydrogenphosphate**"
