### ISSUE TITLE
Missing parent:  GO:0055104 ligase inhibitor activity

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#27010]
* **GO term ID and label for which you request a new superclass**
* GO:1990948 ubiquitin ligase inhibitor activity

* **New superclass (parent) suggested**
GO:0055104 ligase inhibitor activity

Thanks
Ruth

**Comment by ValWood** [comment]
We probably shoudn't do this , because the ubiquitin ligase catalyses a transferase reaction

https://www.ebi.ac.uk/QuickGO/term/GO:0061630
