### ISSUE TITLE
Obsoletion request: 'GO:0031668 cellular response to extracellular stimulus'  and 'GO:0009991 - response to extracellular stimulus'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27020]
'GO:0031668 cellular response to extracellular stimulus' >> this term is too vague. 

Replace by [cellular response to stimulus](http://purl.obolibrary.org/obo/GO_0051716)

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @edwong57 
I'm sorry, I hadn't noticed the child GO:000991 - response to extracellular stimulus
We also need to obsolete one, we can replace by 'response to stimulus'. 

Thanks, Pascale

**Comment by slaulederkind** [comment]
RGD finished.

**Comment by edwong57** [comment]
@pascale I obsoleted the terms and replaced them in the term logical definitions. I debated changing the term names and removing 'extracellular' from them, but wasn't sure what the protocol for this was, or if it would be confusing for people.

**Comment by edwong57** [comment]
Changing the logical definitions made GO:0048584 ==  GO:0032106 and GO:0048585 == GO:0032105.  GO:0048584 and GO:0048585 have no direct EXP annotations have any annotations and can be obsoleted.

**Comment by edwong57** [comment]
I also see that there is GO:009605 response to external stimulus. Would it be better to use that to replace GO:000991 - response to extracellular stimulus instead of 'response to stimulus?'

**Comment by pgaudet** [comment]
Hi @edwong57 

Sorry my request was not clear in the first comment. The problem was 'extracellular'. 

We should obsolete
GO:0009991 response to extracellular stimulus
GO:0031668 cellular response to extracellular stimulus
GO:0032104 regulation of response to extracellular stimulus
GO:0032105 negative regulation of response to extracellular stimulus
GO:0032106 positive regulation of response to extracellular stimulus

and we can replace all by 'response to cellular stimulus'. There are no direct annotations to either of these terms. see https://github.com/geneontology/go-annotation/issues/5162, so we can proceed right away. 


Thanks, Pascale
