### ISSUE TITLE
Add FlyBase anatomy terms in GOREL for annotating extensions in P2GO 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27030]
- [x] part_of FBbt:10000000 anatomical entity
- [x] part_of FBdv:00007012 life stage
- [x] part_of FBbt:00007002 cell
- [x] occurs_in FBbt:10000000 anatomical entity
- [x] occurs_in FBbt:00007002 cell
- [x] happens_during FBdv:00007012 life stage

- [x] existence_overlaps FBdv:00007012 life stage
- [x] exists_during FBdv:00007012 life stage
- [x] existence_starts_and_ends_during FBdv:00007012 life stage
- [x] has_start_location FBbt:00007002 cell
- [x] has_start_location FBbt:10000000 anatomical entity

- [x] results_in_determination_of FBbt:00007002 cell
- [x] results_in_commitment_to FBbt:00007002 cell

- [x] results_in_movement_of FBbt:00007002 cell
- [x] results_in_specification_of FBbt:00007002 cell
- [x] results_in_morphogenesis_of FBbt:00007002 cell

- [x] results_in_maturation_of FBbt:00007002 cell
- [x] results_in_division_of FBbt:00007002 cell
- [x] results_in_formation_of FBbt:00007002 cell

- [x] results_in_development_of FBbt:00007002 cell
- [x] results_in_development_of FBbt:10000000 anatomical entity
- [x] results_in_morphogenesis_of FBbt:10000000 anatomical entity
- [x] results_in_maturation_of FBbt:10000000 anatomical entity
- [x] results_in_formation_of FBbt:10000000 anatomical entity

- [x] results_in_acquisition_of_features_of FBbt:00007002 cell
- [x] acts_on_population_of FBbt:00007002 cell

**Comment by pgaudet** [comment]
@hattrill @alexsign

**Comment by pgaudet** [comment]
@balhoff can you regenerate GORELs in the next release & snapshot ? 

Thanks, Pascale

**Comment by balhoff** [comment]
@pgaudet #27031.
