### ISSUE TITLE
NTR: [Mitochondrial protein quality control]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#27044]
Hi GO,

I would need a term for Mitochondrial protein quality control process. There is a good review (PMID:38280230) that describes the proteins involved in this process. Note that we already have terms for other subcellular localizations (cytoplasm and nucleus)

Thanks

Sylvain

Mitochondrial protein quality control
Definition: The chemical reactions and pathways resulting in the breakdown of misfolded proteins in the mitochondrion, which are targeted for degradation. 
Child of : GO:0006515 protein quality control for misfolded or incompletely synthesized proteins
XRef: PMID:38280230

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141164
+name: mitochondrial protein quality control
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the breakdown of misfolded proteins in the mitochondrion, which are targeted for degradation." [PMID:38280230]
+is_a: GO:0006515 ! protein quality control for misfolded or incompletely synthesized proteins
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27044" xsd:anyURI
+created_by: pg
+creation_date: 2024-02-14T07:11:38Z
+
