### ISSUE TITLE
NTR: [Hair bundle reversal]

### ISSUE THREAD

**Issue by MariaLivia** [geneontology/go-ontology#27056]
Please provide as much information as you can: 

* **Suggested term label:**
* Reversal of hair-bundle orientation

* **Definition (free text)**
Coordinated organization of stereociliary bundles into two populations that differ by 180 degrees defining a line of polarity reversal (LPR) across which hair cells are arranged in opposite orientations.

* **Reference, in format PMID:#######**
PMID:10900087
PMID:34646115
PMID:32965215
PMID:34001891

* **Gene product name and ID to be annotated to this term**
* Emx2  Q04744
* Gpr156 Q6PCP7

* **Parent term(s)**
* GO:0001736 ???
* GO:0060121 ???

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by MariaLivia** [comment]
Hi, 
any news about this term request? I see there is no assignee.

**Comment by pgaudet** [comment]
For parents, I dont think  GO:0001736 establishment of planar polarity is right; it would make it a child of
GO:0001738 morphogenesis of a polarized epithelium and GO:0002009 morphogenesis of an epithelium. 

The other suggestion seems more appropriate: GO:0060121 vestibular receptor cell stereocilium organization (althouh I didn't look closely and I dont know this process).  Would this is is_a or part_of the process? 

The issue I see that that this term would be the only child of 'GO:0060121 vestibular receptor cell stereocilium organization'. 
If this new proposed term should be is_a GO:0060121 vestibular receptor cell stereocilium organization, then are there other possible mechanisms or organization patterns? 

If this new proposed term should be part_of GO:0060121 vestibular receptor cell stereocilium organization, then are there other subparts of this process? 

Thanks, Pascale

**Comment by raymond91125** [comment]
vestibular receptor cell stereocilium organization is a form of establishment of planar polarity <https://en.wikipedia.org/wiki/Planar_cell_polarity>.

**Comment by raymond91125** [comment]
The fish emx2 is already annotated with GO:0060121 vestibular receptor cell stereocilium organization based on PMID:28266911 regarding LPR. We should have a more general term "sensory hair cell stereocilium organization" to cover the shared process in all hair cells. We may decide on having more granular terms (LPR vs non-LPR aspects of organization) later. @MariaLivia Do you think this is good?

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160194
+name: stereocilium bundle organization
+namespace: biological_process
+def: "A process that is carried out at the cellular level which results in the assembly, arrangement of constituent parts, or disassembly of a sensory hair cell stereocilium bundle." [PMID:28266911, PMID:6978627]
+intersection_of: GO:0016043 ! cellular component organization
+intersection_of: results_in_organization_of GO:0032421 ! stereocilium bundle
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27056" xsd:anyURI
+created_by: rynl
+creation_date: 2024-07-08T20:47:33Z

**Comment by raymond91125** [comment]
I'm closing this ticket for now. Please feel free to reopen if more action is needed. Thanks!

**Comment by MariaLivia** [comment]
The new term is fine for me. Thank you !
