### ISSUE TITLE
Remove logical definition from  GO:0022414 reproductive process 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27054]
Remove logical definition from  GO:0022414 reproductive process

**Comment by cmungall** [comment]
This is a band-aid over the fact that having two concepts for "reproductive process" and "reproduction" only makes sense to ontologists (insofar as we have these two concepts, the logical definition is actually correct).

My favored solutions in order:

1. obsolete "reproductive process". It provides zero information.
2. place a do_not_annotate on "reproductive process"
3. remove the logical definition

But any solution is better than none.

These are the direct annotations by evidence:

<img width="371" alt="image" src="https://github.com/geneontology/go-ontology/assets/50745/29181661-bae8-49c2-af46-b907925c5f1f">


All the experimentals are unsurprisingly IMP:

<img width="362" alt="image" src="https://github.com/geneontology/go-ontology/assets/50745/162f5a53-8f7f-49b1-a0fc-67687dd48590">

I think these can easily be moved down to reproduction. This means there is no obstacles to either 1 or 2.

**Comment by pgaudet** [comment]
OK - last time I checked I got stuck in the of moving all children to other parents; they cannot all move to is_a reproduction (but this is the general for a x process terms, for example this is why we have 'apoptotic process' and not 'apoptosis' 

'acrosome reaction'
'cellular process involved in reproduction in multicellular organism'
dehiscence
'developmental process involved in reproduction'
'embryo implantation'
'embryonic process involved in female pregnancy'
fertilization
'fetal process involved in parturition'
'gamete generation'
'gonad development'
'mammalian oogenesis stage'
'maternal process involved in female pregnancy'
'maternal process involved in parturition'
'mating plug formation'
'meiotic cell cycle'
'meiotic cell cycle process'
'meiotic drive'
'menstrual cycle'
'mucilage extrusion from seed coat'
'multi-organism reproductive process'
'multicellular organismal reproductive process'
ovulation
'ovulation cycle'
'ovulation cycle process'
'penile erection'
pollination
'positive regulation of flagellated sperm motility involved in capacitation'
'premature acrosome loss'
'reproductive process in single-celled organism'
'reproductive shoot system development'
'seed maturation'
'seminal clot liquefaction'
'sperm ejaculation'
'sperm motility'

**Comment by pgaudet** [comment]
I removed the LD for reproductive process. I'll leave this open for obsoletion of reproductive process, but I am not sure where to move all the children.

**Comment by raymond91125** [comment]
> I removed the LD for reproductive process. I'll leave this open for obsoletion of reproductive process, but I am not sure where to move all the children.

https://github.com/geneontology/go-ontology/pull/27063

**Comment by raymond91125** [comment]
I actually think "reproductive process" is a better term than "reproduction" as defined: "A biological process that directly contributes to the process of producing new individuals by one or two organisms. The new individuals inherit some proportion of their genetic material from the parent or parents." In fact, "reproduction" has an exact synonym "reproductive physiological process". I suggest that we obsolete reproduction as it has the mixed meaning of the end goal and the process with the definition "The production of new individuals that contain some portion of genetic material inherited from one or more parent organisms."

**Comment by pgaudet** [comment]
Ontology call: agree to replace "reproduction" by "reproductive process"

**Comment by pgaudet** [comment]
Also please replace 
[GO:0032505 reproduction of a single-celled organism] by (https://amigo.geneontology.org/amigo/term/GO:0032505#display-lineage-tab)GO:0022413 reproductive process in single-celled organism

**Comment by pgaudet** [comment]
Add DO NOT ANNOTATE on GO:0022414 reproductive process
and other GO:0032504 multicellular organism reproduction  and GO:0032505 reproduction of a single-celled organism b

**Comment by raymond91125** [comment]
@pgaudet Should I simply transfer the slims over to reproductive process?

**Comment by pgaudet** [comment]
@raymond91125 
> Should I simply transfer the slims over to reproductive process?

Yes, thanks
