### ISSUE TITLE
NTR: epigenetic 5-methylcytosine DNA demethylation 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27078]
For the transcription refactoring - epigenetic pathways, we have created the following terms to describe the demethylation of cytosine residues in the genome: 

+[Term]
+id: GO:0141166
+name: epigenetic 5-methylcytosine DNA demethylation
+namespace: biological_region
+def: "A process that chemically modifies 5-methylcytosine (5meC) to make it a substrate for the base excision repair pathway, which then restores the unmodified cytosine." []
+synonym: "epigenetic DNA demethylation" RELATED []
+is_a: GO:0006259 ! DNA metabolic process
+created_by: pg
+creation_date: 2024-02-16T12:48:28Z

+[Term]
+id: GO:0141167
+name: epigenetic 5-methylcytosine DNA demethylation, oxidation pathway
+namespace: biological_region
+def: "An epigenetic cytosine DNA demethylation pathway that starts with the enzymatic oxidation of the 5-methylcytosine (5meC) to generate 5-hydroxymethylcytosine (5hmC), which successively converted to 5-formylcytosine (5fC) and 5-carboxylcytosine (5caC). A DNA glycosylase (e. g. TDG) recognizes the intermediate bases 5fC and 5caC and cleaves the glycosidic bond resulting in an apyrimidinic site (AP site). The AP site is processed by the base excision DNA repair pathway, to restore an unmodified cytosine." [PMID:21862972, PMID:29875631]
+comment: A similar pathway may also convert chromosomal DNA N6-methyladenosine to adenosine but little evidence exists for this pathway.
+synonym: "epigenetic DNA demethylation, oxidation pathway" RELATED []
+is_a: GO:0141166 ! epigenetic 5-methylcytosine DNA demethylation
+created_by: pg
+creation_date: 2024-02-16T13:09:04Z
+
+[Term]
+id: GO:0141168
+name: epigenetic 5-methylcytosine DNA demethylation, oxidative deamination pathway
+namespace: biological_region
+def: "An epigenetic cytosine DNA demethylation pathway that includes a deamination step to produce either a thymine (T), or a 5-hydroxymethyluracil (5hmU), if the 5meC had first been converted to 5hmC. A DNA glycosylase (e. g. TDG) recognizes the T mispaired with a G or the 5hmC and cleaves the glycosidic bond resulting in an apyrimidinic site (AP site). The AP site is processed by the base excision DNA repair pathway, to restore an unmodified cytosine." [PMID:21862972, PMID:29875631]
+comment: A similar pathway may also convert chromosomal DNA N6-methyladenosine to adenosine but little evidence exists for this pathway.
+synonym: "epigenetic DNA demethylation, oxidative deamination pathway" RELATED []
+is_a: GO:0141166 ! epigenetic 5-methylcytosine DNA demethylation
+created_by: pg
+creation_date: 2024-02-16T13:11:58Z

**Comment by pgaudet** [comment]
There is also a plant-specific pathway: 

 
+[Term]
+id: GO:0141169
+name: epigenetic 5-methylcytosine DNA demethylation, direct 5-methylcytosine excision pathway
+namespace: biological_process
+def: "An epigenetic cytosine DNA demethylation pathway that involves a DNA glycosylase that directly excises 5-methylcytosine (5-meC) to initiate its replacement with unmethylated cytosine through base excision repair. This pathway is known to occur in plants." [PMID:21862972, PMID:31546611, PMID:36478523]
+is_a: GO:0141166 ! epigenetic 5-methylcytosine DNA demethylation
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27078" xsd:anyURI
+created_by: pg
+creation_date: 2024-02-16T14:20:55Z

**Comment by pgaudet** [comment]
NTR positive regulation of 5-methylcytosine DNA demethylation, direct 5-methylcytosine excision pathway

**Comment by pgaudet** [comment]
- [ ] Add taxon constraint
- [ ] check if we can add some epigenetic regulation of gene expression parent

**Comment by ValWood** [comment]
should
+id: GO:0141166 have "pathway" otherwise it sounds like an activity.

Is the namespace +namespace: biological_region new?

**Comment by pgaudet** [comment]
*  [epigenetic 5-methylcytosine DNA demethylation, direct 5-methylcytosine excision pathway](http://purl.obolibrary.org/obo/GO_0141169) >> added parent: positive regulation of gene expression, epigenetic, because in plants there are other sites than CpG islands that are used a epigenetic marks. 

* [epigenetic 5-methylcytosine DNA demethylation, oxidation pathway](http://purl.obolibrary.org/obo/GO_0141167) >> change parent to 'positive regulation of gene expression via chromosomal CpG dinucleotide demethylation'
* because evidence indicates that this is the pathway by which CpG islands are maintained in a demethylated  state to allow gene expression.

**Comment by pgaudet** [comment]
Added parents: 
 .'chromosomal 5-methylcytosine DNA demethylation, oxidation pathway'
- added is_a: GO:0141137 ! positive regulation of gene expression, epigenetic


. .'chromosomal 5-methylcytosine DNA demethylation, oxidative deamination pathway'
added is_a: GO:0006281 ! DNA repair
