### ISSUE TITLE
Obsoletion request: GO:0140080 class III/IV DNA-(apurinic or apyrimidinic site) endonuclease activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27071]
```id: GO:0140080
name: class III/IV DNA-(apurinic or apyrimidinic site) endonuclease activity
namespace: molecular_function
def: "Catalysis of the cleavage of an AP site 3' and 5' of the baseless site, generating a 3'-phosphate and a 5'-OH." [PMID:2519777]
comment: Note that this term is does not have parentage in the 'nuclease activity' branch of the ontology because both GO and the Enzyme Commission define nuclease activity as a type of hydrolysis. Class II AP endonuclease is a nuclease, but not Class I, III and IV.
synonym: "endonuclease III" RELATED []
synonym: "endonuclease IV" RELATED []
xref: Wikipedia:AP_endonuclease
is_a: GO:0003906 ! DNA-(apurinic or apyrimidinic site) endonuclease activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/22262" xsd:anyURI
created_by: pg
creation_date: 2017-07-24T11:48:18Z
```

I think this term should be deleted.

The given reference (PMID:2519777), which is the same paper pointed to from the Wikipedia xref, says: "There are four possible incision sites for AP endonucleases, and the enzymes have been classified according to their sites of incision: class I and class II AP endonucleases incise 3' and 5', respectively, to the AP site, both leaving 3'-OH and 5'-P termini; class III and IV enzymes cleave 3' and 5', respectively, to the AP site, generating 3'-P and 5'-OH termini. All known class I enzymes are glycosylase-AP endonucleases, and these have been discussed above. Most AP endonucleases are of class II. **There is only one known example of class III AP endonucleases, the Drosophila AP endonuclease, and no known examples of class IV enzymes.**"

The only known example of class III/IV AP endonuclease referred to is an activity described in a single paper from 1986 (PMID:2419327) that has never been reproduced or associated with a defined gene/protein (see http://flybase.org/reports/FBgn0019639).

There is only one annotation to the term in QuickGO - S. pombe apn1 (P50525) from PMID:9524207 and that should either be re-annotated to "class II DNA-(apurinic or apyrimidinic site) endonuclease activity" (like other members of the 'endonuclease IV family' - see PMID:2519777 or PMID:1698278), or perhaps deleted (as I don't easily see the IDA evidence in that paper)? @ValWood

**Comment by sjm41** [comment]
Related tidying-up:

- [ ] The current def xref for the 'class II DNA-(apurinic or apyrimidinic site) endonuclease activity' (GO:0052720) is PMID:19401441 , which isn't great. Better to swap that for the same def xref as on the sister term 'class I DNA-(apurinic or apyrimidinic site) endonuclease activity' (GO:0140078) = PMID:1698278. That paper gives a nice summary of the two major classes of DNA AP endonuclease in its intro, including a picture!
- [ ] add 'AP lyase activity' and 'class I AP endonuclease activity' as synonyms to 'class I DNA-(apurinic or apyrimidinic site) endonuclease activity' (GO:0140078)
- [ ] -add 'class II AP endonuclease activity' as synonym to 'class II DNA-(apurinic or apyrimidinic site) endonuclease activity' (GO:0052720)
- [ ] rename the related term 'apurinic/apyrimidinic endoribonuclease activity' (GO:0052719) term to 'RNA-(apurinic or apyrimidinic site) endonuclease activity' to match the style of the DNA terms. (Though I note there are zero annotations to the RNA term.)

**Comment by ValWood** [comment]
Agreed, I wonder if the curator intended this to be a negative annotation- "Rather surprisingly, no detectable AP endonuclease activity was found in extracts prepared from three different S. pombe wild-type strains SP720, FW9, and Q353 ([Table 1]"
Crude extract derived from S. pombe bearing the pART1 vector contained no measurable AP endonuclease activity ([Table 1]"

However this is complicated because it appears that the lack of activity is due to a mutation in the lab strain rather than the 
absence of activity  in fission yeast. There is an isoform  with low expression which 
 does have residual activity in  the laboratory strain https://www.pombase.org/reference/PMID:21193357
I will delete the queried annotation, and make the correct annotation using PMID:21193357

**Comment by raymond91125** [comment]
Are annotatoins shown in QuickGO more up to date than those shown in AmiGO?

**Comment by sjm41** [comment]
Thanks @raymond91125 

> Are annotatoins shown in QuickGO more up to date than those shown in AmiGO?
They will certainly be more up-to-date for any groups making annotations using Protein2GO.
But the issue you may be seeing here is probably because the single FlyBase annotation is to a unsequenced genetic locus (ApI, FBgn0019639), meaning that it's not shown at all in QuickGO (because there's no corresponding UniProt ID) whereas it is  shown in AmiGO.
