### ISSUE TITLE
remove /Taxon constraint: diphthine synthase activity (GO:0004164)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27085]
Please provide as much information as you can: 

* **GO term ID label:**

diphthine synthase activity (GO:0004164)
has only in archaea, but is used by SGD?

https://www.yeastgenome.org/locus/S000004162

(I ISS'd to it)

**Comment by sjm41** [comment]
See:
https://github.com/geneontology/go-annotation/issues/4886
https://github.com/geneontology/go-ontology/issues/25281

**Comment by ValWood** [comment]
OK! I remember now.
