### ISSUE TITLE
MetaCyc pathway xrefs to add (carbohydrate metabolism)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27107]
glycogen biosynthetic process (GO:0005978)
ADD:
glycogen biosynthesis II (from UDP-D-Glucose) (MetaCyc:PWY-5067)
glycogen biosynthesis III (from α-maltose 1-phosphate) (MetaCyc:PWY-7900)

glycogen catabolic process (GO:0005980)
ADD:
glycogen degradation II (MetaCyc:PWY-5941)
glycogen degradation III (via anhydrofructose) (MetaCyc:PWY-7662)

pentose-phosphate shunt, non-oxidative branch (GO:0009052)
REMOVE:
pentose phosphate pathway (partial) (MetaCyc:P21-PWY)
ADD:
pentose phosphate pathway (non-oxidative branch) II (MetaCyc:PWY-8178)

pentose-phosphate shunt, oxidative branch (GO:0009052)
ADD:
pentose phosphate pathway (oxidative branch) II (PWY-7796)

hyaluronan catabolic process (GO:0030214)
ADD:
hyaluronan degradation (MetaCyc:PWY-7645)

heparan sulfate proteoglycan biosynthetic process (GO:0015012)*
ADD:
heparan sulfate biosynthesis (MetaCyc:PWY-6558)

chondroitin sulfate biosynthetic process (GO:0030206)
ADD:
chondroitin sulfate biosynthesis (MetaCyc:PWY-6567)

dermatan sulfate biosynthetic process (GO:0030208)
ADD:
dermatan sulfate biosynthesis (MetaCyc:PWY-6568)

chondroitin sulfate catabolic process (GO:0030207)
ADD:
chondroitin sulfate degradation (metazoa) (MetaCyc:PWY-6573)
chondroitin sulfate degradation I (bacterial) (MetaCyc:PWY-6572)

dermatan sulfate catabolic process (GO:0030209)
ADD:
dermatan sulfate degradation (metazoa) (MetaCyc:PWY-6576)
dermatan sulfate degradation I (bacterial) (MetaCyc:PWY-7646)

D-glucuronate catabolic process	(GO:0042840)
ADD:
β-D-glucuronide and D-glucuronate degradation (PWY-7247)
D-glucuronate degradation I (PWY-5525)
D-glucuronate degradation II (PWY-6501)
D-glucuronate degradation III (PWY-8390)

chitin biosynthetic process (GO:0006031)
ADD:
chitin biosynthesis (MetaCyc:PWY-6981)

chitin catabolic process (GO:0006032)
ADD:
chitin deacetylation (MetaCyc:PWY-7118)
chitin degradation I (archaea) (MetaCyc:PWY-6855)
chitin degradation II (Vibrio) (MetaCyc:PWY-6902)
chitin degradation III (Serratia) (MetaCyc:PWY-7822)

mannose catabolic process (GO:0019309)
ADD:
D-mannose degradation II (MetaCyc:PWY3O-1743)

N-acetylglucosamine catabolic process (GO:0006046)
ADD:
N-acetylglucosamine degradation I (MetaCyc:GLUAMCAT-PWY)
N-acetylglucosamine degradation II (MetaCyc:PWY-6517)

O-glycan processing (GO:0016266)
ADD:
mucin core 1 and core 2 O-glycosylation (MetaCyc:PWY-7433)

protein O-linked mannosylation (GO:0035269)
ADD:
protein O-mannosylation I (yeast) (MetaCyc:PWY-7921)
protein O-mannosylation II (mammals, core M1 and core M2) (MetaCyc:PWY-7922)
protein O-mannosylation III (mammals, core M3) (MetaCyc:PWY-7979)

GDP-mannose biosynthetic process (GO:0009298)
ADD:
GDP-mannose biosynthesis (MetaCyc:PWY-5659)

UDP-N-acetylgalactosamine biosynthetic process (GO:0019277)
REMOVE:
UDP-N-acetyl-D-glucosamine biosynthesis II (MetaCyc:UDPNACETYLGALSYN-PWY)
ADD:
UDP-N-acetyl-D-galactosamine biosynthesis I (MetaCyc:PWY-5512)
UDP-N-acetyl-D-galactosamine biosynthesis II (MetaCyc:PWY-5514)
UDP-N-acetyl-D-galactosamine biosynthesis III (MetaCyc:PWY-8013)

UDP-N-acetylglucosamine biosynthetic process (GO:0006048)
ADD:
UDP-N-acetyl-D-glucosamine biosynthesis II (MetaCyc:UDPNACETYLGALSYN-PWY)

UDP-galactose biosynthetic process (GO:0052574)
ADD:
UDP-α-D-galactose biosynthesis (MetaCyc:PWY-7344)

UDP-glucuronate biosynthetic process (GO:0006065)
ADD:
UDP-α-D-glucuronate biosynthesis (from UDP-glucose) (MetaCyc:PWY-7346)

**Comment by ukemi** [comment]
Good idea. I already did a bit of this to make the glycogen metabolism mouse models.
http://noctua.geneontology.org/editor/graph/gomodel:623d156d00000029
http://noctua.geneontology.org/editor/graph/gomodel:623d156d00000699
http://noctua.geneontology.org/editor/graph/gomodel:623d156d00000752
http://noctua.geneontology.org/editor/graph/gomodel:623d156d00000939

All of these were based on the Reactome import.

**Comment by sjm41** [comment]
FYI, the two glycogen-related terms now look like this (after adding the missing MetaCyc xrefs):

id: GO:0005978
name: glycogen biosynthetic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the formation of glycogen, a polydisperse, highly branched glucan composed of chains of D-glucose residues." [ISBN:0198506732]
synonym: "glycogen anabolism" EXACT []
synonym: "glycogen biosynthesis" EXACT []
synonym: "glycogen formation" EXACT []
synonym: "glycogen synthesis" EXACT []
xref: MetaCyc:GLYCOGENSYNTH-PWY
xref: MetaCyc:PWY-5067
xref: MetaCyc:PWY-7900
is_a: GO:0005977 ! glycogen metabolic process
is_a: GO:0009250 ! glucan biosynthetic process
intersection_of: GO:0009058 ! biosynthetic process
intersection_of: has_primary_output CHEBI:28087 ! glycogen
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27107" xsd:anyURI

id: GO:0005980
name: glycogen catabolic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the breakdown of glycogen, a polydisperse, highly branched glucan composed of chains of D-glucose residues." [ISBN:0198506732]
synonym: "glycogen breakdown" EXACT []
synonym: "glycogen catabolism" EXACT []
synonym: "glycogen degradation" EXACT []
synonym: "glycogenolysis" EXACT [GOC:sl]
xref: MetaCyc:GLYCOCAT-PWY
xref: MetaCyc:PWY-5941
xref: MetaCyc:PWY-7662
intersection_of: GO:0009056 ! catabolic process
intersection_of: has_primary_input CHEBI:28087 ! glycogen
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27107" xsd:anyURI
