### ISSUE TITLE
Obsoletion request:     GO:0043621 protein self-association

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27101]
Please provide as much information as you can:
GO:0043621 protein self-association

* **GO term ID and Label**

* **Reason for deprecation** Put an x in the appropriate box: 
Out of scope; capture mechanistic information about binding

**Comment by edwong57** [comment]
Should the child term, [GO:0032840 intramolecular proline-rich ligand binding](https://amigo.geneontology.org/amigo/term/GO:0032840) be obsoleted as well? There are no annotations, and given that 'protein self-association' is out of scope, then it would seem that this child term is as well. Or at the very least it is redundant with GO:0070064 proline-rich region binding once the 'protein self-association' is removed.

**Comment by pgaudet** [comment]
Yes, this term should also be obsoleted.
