### ISSUE TITLE
NTR: [Nucleosome acidic patch]

### ISSUE THREAD

**Issue by MariaLivia** [geneontology/go-ontology#27118]
Please provide as much information as you can: 

* **Suggested term label:**
Nucleosome acidic patch

* **Definition (free text)**
A highly contoured and negatively charged binding interface on the nucleosome surface formed from six H2A and two H2B residues.  A particularly striking feature of the nucleosome surface is the cluster of eight acidic residues (E56, E61, E64, D90, E91, E92 of H2A and E102, E110 of H2B). 

* **Reference, in format PMID:#######**
PMID:23446052
PMID:35390161

* **Gene product name and ID to be annotated to this term**
VRK1
Q99986

* **Parent term(s)**
GO:0000786 Nucleosome

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
Hi @MariaLivia  "acidic patch" is out of scope for GO because it is describing an attribute of a complex.
