### ISSUE TITLE
Textual definition update: trehalose BP terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27111]
Trehalose is important in insect metabolism, but the related BP defs suggest it's only relevant to 'lichens and fungi'.
I suggest the "a disaccharide isomeric with sucrose and obtained from certain lichens and fungi." bit is replaced with "a disaccharide consisting of two molecules of glucose and that is isomeric with sucrose." in each case.

id: GO:0005991
name: trehalose metabolic process
namespace: biological_process
def: "The chemical reactions and pathways involving trehalose, a disaccharide isomeric with sucrose and obtained from certain lichens and fungi." [GOC:jl, ISBN:0028623819]

id: GO:0005992
name: trehalose biosynthetic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the formation of trehalose, a disaccharide isomeric with sucrose and obtained from certain lichens and fungi." [GOC:jl, ISBN:0028623819]

id: GO:0005993
name: trehalose catabolic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the breakdown of trehalose, a disaccharide isomeric with sucrose and obtained from certain lichens and fungi." [GOC:jl, ISBN:0028623819]

id: GO:0015771
name: trehalose transport
namespace: biological_process
def: "The directed movement of trehalose into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore. Trehalose is a disaccharide isomeric with sucrose and obtained from certain lichens and fungi." [GOC:ai, PMID:17606922, PMID:20035867]

id: GO:0090062
name: regulation of trehalose metabolic process
def: "Any process that modulates the frequency, rate or extent of trehalose metabolism, the chemical reactions and pathways involving trehalose, a disaccharide isomeric with sucrose and obtained from certain lichens and fungi." [GOC:dph, GOC:tb]

**Comment by pgaudet** [comment]
Yeah it's always the risk of giving additional information; do you want to update the defs, or remove mention of the organisms? 

Thanks, 
Pascale

**Comment by sjm41** [comment]
I was proposing to update the defs by removing the organisms! (As well as providing the other bit of useful info that trehalose is a disaccharide of 2x glucose.)
If OK with you, I'll go ahead with those updates.

**Comment by pgaudet** [comment]
Yes OK - perfect!!
