### ISSUE TITLE
rename and move: GO:0015862 uridine transport  to uridine transmembrane transport 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#27119]
looks like GO:0015862 uridine transport can be safely changed to uridine transmembrane transport, as all entries with exp evidenced annotations to this term are also a annotated with uridine transmembrane transporter activity.

https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0015862&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

and moved under GO:1901642 nucleoside transmembrane transport

**Comment by edwong57** [comment]
Added  and ('results in transport across' some membrane) to the logical definition. Reasoner made it a subclass of 'nucleoside transmembrane transport'
