### ISSUE TITLE
Obsoletion request:  GO:0015114 phosphate ion transmembrane transporter activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27121]
Dear all, 

The proposal has been made to obsolete  GO:0015114 phosphate ion transmembrane transporter activity

The reason for obsoletion is that it represents the same activity as GO:0005315 (inorganic) phosphate transmembrane transporter activity (phosphate ion == inorganic phosphate). 

There are 15 EXP annotations to this term, see https://github.com/geneontology/go-annotation/issues/5071: 

Group | Number of annotations
-- | --
RGD | 1
TAIR | 8
UniProt | 5
ZFIN | 1

No action is needed, as these will be automatically replaced by GO:0005315 phosphate transmembrane transporter activity 

Thanks, Pascale

**Comment by slaulederkind** [comment]
RGD annotation has been removed.
