### ISSUE TITLE
NTR: [Receptor clustering activity]

### ISSUE THREAD

**Issue by pmasson55** [geneontology/go-ontology#27123]
Please provide as much information as you can: 

* **Suggested term label:**
* 
Receptor clustering activity

* **Definition (free text)**

Structural component of specialized membrane microdomains which act as platforms for receptor clustering and signaling

* **Reference, in format PMID:#######**

PMID:28487417

* **Gene product name and ID to be annotated to this term**

CD37_HUMAN (CD37) P11049
CD53_HUMAN (CD53) P19397

* **Parent term(s)**

 GO:0030674 protein-macromolecule adaptor activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141175
+name: receptor clustering activity
+namespace: molecular_function
+def: "A protein-protein adaptor that acts as a platform for receptor clustering, often serving to amplify the sensitivity of a signaling response." [PMID:19747931, PMID:21453460, PMID:33597156]
+is_a: GO:0030674 ! protein-macromolecule adaptor activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27123" xsd:anyURI
+created_by: pg
+creation_date: 2024-02-26T11:54:52Z
+
