### ISSUE TITLE
New child terms of alcohol dehydrogenase (NAD+) activity (GO:0004022)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27136]
The following terms are currently direct children of "oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor (GO:0016616)" but should be moved to be direct children of the more specific term:
alcohol dehydrogenase (NAD+) activity (GO:0004022)
Def:Catalysis of the reaction: an alcohol + NAD+ = an aldehyde or ketone + NADH + H+.[ EC:1 ]

This fits with their relationships in RHEA (see https://www.rhea-db.org/rhea/10736)

id: GO:0004552
name: octanol dehydrogenase activity
RHEA:24620
NAD+ + octan-1-ol = H+ + NADH + octanal

id: GO:0047978
name: hexadecanol dehydrogenase activity
RHEA:22056
hexadecan-1-ol + NAD+ = H+ + hexadecanal + NADH

id: GO:0004745
name: NAD-retinol dehydrogenase activity
RHEA:21284
all-trans-retinol + NAD+ = all-trans-retinal + H+ + NADH

id: GO:0050093
name: methanol dehydrogenase activity
RHEA:19401
methanol + NAD+ = formaldehyde + H+ + NADH

id: GO:0047018
name: indole-3-acetaldehyde reductase (NADH) activity
RHEA:14873
indole-3-ethanol + NAD+ = H+ + indole-3-acetaldehyde + NADH

id: GO:0018456
name: aryl-alcohol dehydrogenase (NAD+) activity
RHEA:12076
an aromatic primary alcohol + NAD+ = an aromatic aldehyde + H+ + NADH

id: GO:0018457
name: perillyl-alcohol dehydrogenase activity
RHEA:10664
NAD+ + perillyl alcohol = H+ + NADH + perillyl aldehyde

(This list isn't exhaustive - there may be other, similar cases)

**Comment by pgaudet** [comment]
Thanks @sjm41 
For consistency: should we add 'NAD+' in the term label? For example as in ''L-xylulose reductase (NAD+) activity' (note that we are also inconsistent about that, sometimes it says 'NAD+-dependent) 

Thanks, Pascale

**Comment by sjm41** [comment]
Hi @pgaudet
Sure, adding '(NAD+)' to the name makes sense to me.
Another consistency question - are we consistent if we write (NAD+), (NAD) or (NADH) in these cases?

**Comment by sjm41** [comment]
> Based on the definition it seems like NAD+ would be right, is this also your conclusion?

Well, given the GO reactions are (almost) always given with an undefined reaction direction, you could say that these reactions are either "NAD+" or "NADH"-dependent.  That is, they are NAD+-dependent in one direction, and NADH-dependent in the other direction.
So I think we just need to make a decision on GO policy/convention here and then be consistent.

The current guidelines (https://wiki.geneontology.org/Guidelines_for_new_Molecular_Functions#NAD/NADP_cofactors) aren't explicit about this point, though they suggest that "NAD" (and "NADP") is the preferred usage, even though that's currently used in only 4 terms?
Using just 'NAD' gets around the problem that reactions are either NAD+/NADH-dependent, depending on which direction you're looking at....

**Comment by sjm41** [comment]
Also, just noting that for GO grouping terms, we seem to just use 'NAD/NADP', for example:
oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor (GO:0016620)
oxidoreductase activity, acting on the CH-CH group of donors, NAD or NADP as acceptor (GO:0016628)
oxidoreductase activity, acting on metal ions, NAD or NADP as acceptor (GO:0016723)

**Comment by sjm41** [comment]
But the EC description in that example is different from GO:
EC:1.2.1.- is "With NAD(+) or NADP(+) as acceptor", whereas the corresponding GO term has "...NAD or NADP as acceptor".
So GO has removed the "(+)" in these cases.

So...we could decide to align with EC in our labels (for grouping classes and leaf terms), which I think means GO would consistently use "NAD+" and NADP+"?
or
We could decide to consistently do what we already do for GO grouping terms, and consistently use "NAD" and "NADP"?

**Comment by pgaudet** [comment]
oh yes yes, - I though you were refering to the parenthesis around the NAD/NADH. 

NAD+ / NADP+ seems the most consistent with how we label other chemicals (we have removed all parenthesis around H(+) as well, for instance, to use H+). 


WRT directionality: For example we have 'GO:0052874 FMN reductase (NADH) activity' >> definition = Catalysis of the reaction: FMNH2 + NAD+ = FMN + NADH + 2 H+.

So, NAD+ would be more appropriate in the label? But our label and definitions match EC: https://enzyme.expasy.org/EC/1.5.1.42

I am not sure what you mean by 
> Using just 'NAD' gets around the problem that reactions are either NAD+/NADH-dependent, depending on which direction you're looking at....

you would put NAD on both sides?

**Comment by sjm41** [comment]
I was only talking about GO term names/labels above. I was certainly not proposing that GO definitions should use just 'NAD'!

My point was that we should be consistent about whether we use 'NAD', 'NAD+' or 'NADH' in term labels where the reaction has 'NAD+' on one side of the reaction and 'NADH' on the other side. (Or 'NADP', 'NADP+' or 'NADPH' for reactions involving NADP+/NADPH.) And we should ensure the editors manual section about these types of reaction reflects the final decision.

- Using 'NAD+' (or 'NADP+) in term labels has the advantage that it's what most GO term labels already use (from your stats above) and it seems to be the usual (though not ubiquitous) convention at EC.
- Using just 'NAD' (or 'NADP') in term labels has the advantage that it reflects the non-directionality of the GO terms - that is, all these terms could be said to be either 'NAD+ dependent' or 'NADH dependent' based on which direction you're looking at, so just using 'NAD' in the term label gets around that issue. Also, as mentioned above, the GO grouping terms (e.g. GO:0016620) seem to already use this convention of just using 'NAD', and the current guidelines suggest that 'NAD' is the preferred usage in term labels.

So, looking at the first term in the list at the top of this ticket, for example:
id: GO:0004552
name: octanol dehydrogenase activity
def: Catalysis of the reaction: 1-octanol + NAD+ = 1-octanal + H+ + NADH.
The new term label could be either: 'octanol dehydrogenase (NAD+) activity' or 'octanol dehydrogenase (NAD) activity'
(EC is no help to use here as their term name is just plain 'octanol dehydrogenase'.

My own preference is to use 'NAD' rather than 'NAD+' in GO term labels, except in any rare cases where the GO term is specifically for a directional reaction.

**Comment by sjm41** [comment]
I realise now that I was overlooking an important point in my previous comments: yes, the **definition** of these oxidoreductase GO terms is (nearly) always non-directional, but the the *term names* are necessarily directional - ie. term names are like "[substrate] dehydrogenase" or "[substrate] reductase". It therefore makes complete sense to specify NADH/NAD+ or NADPH/NADP+ in the term names, and to mirror the EC names in this regard (whenever available. From that point of view, it also makes sense that the grouping terms (e.g. "oxidoreductase activity, acting on metal ions, NAD or NADP as acceptor") only say 'NAD/NADP' as those grouping term names really are non-directional.

So, I will:
1. Go ahead with the 7 new parent-child relationships proposed at the top of this ticket.
2. Add ('NAD+)' to the names of those 7 terms in cases where it's currently missing.
3. Make a separate ticket to clean-up and fix other term labels where only 'NAD' or 'NADP' is specified, or where we use a different format (e.g. 'NADH-dependent'), or where the term label has NADH when it should be NAD+ (etc) - I just checked, and found several such cases.

**Comment by sjm41** [comment]
I also updated a few other term names and relationships under 'alcohol dehydrogenase (NAD+) activity' and 'alcohol dehydrogenase (NADP+) activity'

**Comment by deustp01** [comment]
> the **definition** of these oxidoreductase GO terms is (nearly) always non-directional, but the the **term names** are necessarily directional

A tangential thought. This can be generalized - aldolase - and, worse, the name can be backwards - pyruvate kinase. For human usability, I expect GO needs to respect accepted names, and capture the physiological reaction details only in the definition, with clauses and comments as needed to flag cases where physiology and nomenclature diverge.
