### ISSUE TITLE
NTR: tRNA N1-methyladenine (m1A58) demethylase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27143]
Please provide as much information as you can: 

* **Suggested term label:**
tRNA N1-methyladenine (m1A58) demethylase activity
I am not quite sure how the label should be constructed?

* **Definition (free text)**

Catalysis of the removal of N1-methyladenine from position 58 (m1A58) of a tRNA molecule.

* **Reference, in format PMID:#######**
PMID:27745969

* **Gene product name and ID to be annotated to this term**

https://www.pombase.org/gene/SPBC13G1.04c (by ISS)
https://www.uniprot.org/uniprotkb/Q13686/entry  (@Antonialock )

* **Parent term(s)**

tRNA demethylase activity (GO:1990984)

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

current thinking according to Uniprot:

Mainly acts as a tRNA demethylase by removing N1-methyladenine from various tRNAs, with a preference for N1-methyladenine at position 58 (m1A58) present on a stem loop structure of tRNAs (PubMed:[27745969](https://www.uniprot.org/citations/27745969)).

but this protein does not have the specific term annotated

I was annotating a pombe paper PMID:35901126 which described ALKBH1 as a 
<img width="953" alt="Screenshot 2024-02-23 at 15 28 31" src="https://github.com/geneontology/go-ontology/assets/7359272/e8849981-501a-43d4-bd14-52d1ab72877f">
and I wanted to ISS to it.

**Comment by ValWood** [comment]
@sjm41 @pgaudet  doe this name/label look OK?
I can't locate anything in Rhea for tRNA demethylases?

**Comment by sjm41** [comment]
I see the methyltranferase reaction (https://www.rhea-db.org/rhea/43152) but not the demethylase reaction per se  in RHEA.
I guess the demethylase reaction is different from the methyltranferase reaction in the reverse direction??  That is, would RHEA actually make a separate reaction for the demethylase?

**Comment by ValWood** [comment]
I think so, it's a different enzyme (like histone demethylases) . Will check if there is a reason
@amorgat @kaxelsen

**Comment by kaxelsen** [comment]
Correct, the demethylation takes place by a dioxygenase reaction, i.e., O2 is used to kick off the methyl group that is liberated as formaldehyde

**Comment by kaxelsen** [comment]
A general demethylase reaction is6
 RHEA:54576 2-oxoglutarate + an N1-methyladenosine in tRNA + O2 = an adenosine in tRNA + CO2 + formaldehyde + succinate

We have now also created 
RHEA:79019 2-oxoglutarate + N1-methyladenosine58 in tRNA + O2 = adenosine58 in tRNA + CO2 + formaldehyde + succinate 
It will become publicly available in release 2024_03 scheduled for May 22

**Comment by ValWood** [comment]
Thank you @kaxelsen

**Comment by pgaudet** [comment]
Hi @ValWood 

Discussing with @kaxelsen here in Geneva - 
This is a very non-specific dioxygenase/demethylase; should we create terms for all substrates? 
On the other hand, the methylases seem more specific.

**Comment by ValWood** [comment]
It's OK I can use "tRNA demethylase activity (GO:1990984)" if you think this is the more appropriate level (or whatever you suggest).

**Comment by ValWood** [comment]
Closing. I stuck with 
GO:1990984 | tRNA demethylase activity
and recorded tRNA N1-methyladenine (m1A58) demethylase in the product.
Thanks!
v
