### ISSUE TITLE
Textual definition update: GO:0003896   DNA primase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#27176]
* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request a definition update**
GO:0003896  DNA primase activity

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**

Catalysis of the synthesis of a short RNA or DNA primer on a DNA template, providing a free 3'-OH that can be extended by DNA-directed DNA polymerases. PMID:26184436, PMID:29608762

* **Reference(s)**
PubMed=29608762

* **Additional information**
It turns out that PRIMPOL UniProtKB/Q96LW4 has a primase activity but preferentially uses DNA primers instead of RNA primers.

**Comment by pgaudet** [comment]
Also edited the corresponding GO:0006269 BP term [DNA replication, synthesis of primer](http://purl.obolibrary.org/obo/GO_0006269)


- [ ] Changed label to DNA replication, synthesis of primer
- [ ] Fixed definition from "The synthesis of a short RNA polymer, usually 4-15 nucleotides long, using one strand of unwound DNA as a template; the RNA then serves as a primer from which DNA polymerases extend synthesis." [PMID:11395402] to  "The synthesis of a short RNA polymer, usually 4-15 nucleotides long, using one strand of unwound DNA as a template; the RNA then serves as a primer from which DNA polymerases extend synthesis. In some cases the primer can be made of DNA." [PMID:11395402, PMID:29608762]

**Comment by pgaudet** [comment]
@ValWood Are you OK with obsoletion of the children 
GO:1902295 synthesis of RNA primer involved in cell cycle DNA replication >> 1 pombase TAS
GO:1902330 synthesis of RNA primer involved in bacterial-type DNA replication >> no annotation
GO:1902318 synthesis of RNA primer involved in nuclear cell cycle DNA replication >> no annotation

These are precomposed terms, the proper DNA replication term should be sufficient. What do you think ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@lbreuza 

Looking at this more closely, in fact the parentage is now incorrect: GO:0003896 DNA primase activity is a 
GO:0003899 DNA-directed 5'-3' **RNA** polymerase activity

So, it seems we may need a new term for this activity. How is this represented in RHEA? 

Thanks, Pascale

**Comment by pgaudet** [comment]
yes, but here Lionel is asking that we also include DNA primers, so wouldn't that make it a DNA polymerase as well?

**Comment by lbreuza** [comment]
There is no Rhea but please have a look there : https://enzyme.expasy.org/EC/2.7.7.102

**Comment by ValWood** [comment]
I'm a bit confused. I thought  that the definition of primase was the activity of adding RNA molecules using a DNA template, because the primer for repliciation is defined as an RNA sequence.

If it is adding DNA molecules isn't it  a DNA polymerase? so in this case it would have both primase or polymerase activities?

i.e
A primer is a short nucleic acid sequence that provides a starting point for DNA synthesis. **In living organisms, primers are short strands of RNA******. A primer must be synthesized by an enzyme called primase, which is a type of RNA polymerase, before DNA replication can occur.

or is this an out of date view?

**Comment by pgaudet** [comment]
It seems some primases make a DNA primer under certain conditions, see the paper cited by @lbreuza  PubMed=29608762(and you can find many more in PubMed)

**Comment by ValWood** [comment]
OK, I didn't know that ! I don't think there's a yeast ortholog as far as I can tell.

**Comment by pgaudet** [comment]
- [ ] Changed label: GO:0006269  DNA replication, synthesis of RNA primer to  DNA replication, synthesis of primer
- [ ] GO:0006269 Changed definition: from: "The synthesis of a short RNA polymer, usually 4-15 nucleotides long, using one strand of unwound DNA as a template; the RNA then serves as a primer from which DNA polymerases extend synthesis." [PMID:11395402] 
to :  "The synthesis of a short nucleotide polymer, usually a RNA molecule between 4-15 nucleotides long, using
 one strand of unwound DNA as a template. This primer is extend by DNA polymerases for DNA synthesis. In certai
n conditions, for example in response to DNA damage, some primases synthesize a DNA primer." [PMID:11395402, PM
ID:38203225, PMID:38492718]
- [ ] DNA primase activity: changed definition from "Catalysis of the synthesis of a short RNA primer on a DNA template, providing a free 3'-OH that can be extended by DNA-directed DNA polymerases." [GOC:mah, GOC:mcc, ISBN:0716720094, PMID:26184436] to  "Catalysis of the synthesis of a short RNA primer on a DNA template, providing a free 3'-OH that can be extended by DNA-directed DNA polymerases. In certain conditions, for example in response to DNA damage, some primases synthesize a DNA primer." [GOC:mah, GOC:mcc, PMID:11395402, PMID:26184436, PMID:38203225, PMID:38492718]
- [ ] Added EC:2.7.7.102 {source="skos:narrowMatch"}
- [ ] Made  EC:2.7.7.101 "skos:narrowMatch"


Thanks, Pascale
