### ISSUE TITLE
Clean-up of term names specifying NAD+/NADH or NADP+/NADPH as cofactor.

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27180]
Following on from discussion in #27136:
I looked at all current GO term names that include the string '(NAD' (=187 terms) to check for instances of:
- just 'NAD', when NAD+/NADH or NADP+/NADPH or NAD(P)+/NAD(P)H should be specified => 15 cases found
- 'NAD-dependent' instead of the preferred format of "NAD+" etc. => 6 cases
- 'NAD+/NADP+/NAD(P)+' where it should be 'NADH/NADPH/NAD(P)H - these can be spotted fairly easily since term names of the format "[susbstrate} dehydrogenase" should include 'NAD+/NADP+/NAD(P)+' whereas those of the format "[susbstrate} reductase" should include 'NADH/NADPH/NAD(P)H' => 14 cases

Proposed changes are below. (These were all verified by checking the reaction and EC name, where available)

CURRENT NAME | NEW NAME
-- | --
name: mevaldate reductase (NAD+) activity | name: mevaldate reductase (NADH) activity
name: L-xylulose reductase (NAD+) activity | name: L-xylulose reductase (NADH) activity
name: glyoxylate reductase (NAD+) activity | name: glyoxylate reductase (NADH) activity
name: trans-2-enoyl-CoA reductase (NAD+) activity | name: trans-2-enoyl-CoA reductase (NADH) activity
name: dihydroorotate dehydrogenase (NADH) activity | name: dihydroorotate dehydrogenase (NAD+) activity
name: indolelactate dehydrogenase (NADH) activity | name: indolelactate dehydrogenase (NAD+) activity
name: glyoxylate reductase (NADP+) activity | name: glyoxylate reductase (NADPH) activity
name: 2-alkenal reductase (NADP+) activity | name: 2-alkenal reductase (NADPH) activity
name: acryloyl-CoA reductase (NADP+) activity | name: acryloyl-CoA reductase (NADPH) activity
name: L-xylulose reductase (NADP+) activity | name: L-xylulose reductase (NADPH) activity
name: biliverdin reductase (NADP+) activity | name: biliverdin reductase (NADPH) activity
name: (R)-4-hydroxyphenyllactate dehydrogenase (NADPH) activity | name: (R)-4-hydroxyphenyllactate dehydrogenase (NADP+) activity
name: dihydroorotate dehydrogenase (NADPH) activity | name: dihydroorotate dehydrogenase (NADP+) activity
name: biliverdin reductase (NAD(P)+) activity | name: biliverdin reductase (NAD(P)H) activity
name: aryl-aldehyde dehydrogenase (NAD) activity | name: aryl-aldehyde dehydrogenase (NAD+) activity
name: valine dehydrogenase (NAD) activity | name: valine dehydrogenase (NAD+) activity
name: D-xylose 1-dehydrogenase (NAD) activity | name: D-xylose 1-dehydrogenase (NAD+) activity
name: (3R)-hydroxyacyl-CoA dehydrogenase (NAD) activity | name: (3R)-hydroxyacyl-CoA dehydrogenase (NAD+) activity
name: RNA NAD-cap (NAD-forming) hydrolase activity | name: RNA NAD+-cap (NAD+-forming) hydrolase activity
name: aldo-keto reductase (NADP) activity | name: aldo-keto reductase (NADPH) activity
name: glutathione-disulfide reductase (NADP) activity | name: glutathione-disulfide reductase (NADPH) activity
name: thioredoxin-disulfide reductase (NADP) activity | name: thioredoxin-disulfide reductase (NADPH) activity
name: trypanothione-disulfide reductase (NADP) activity | name: trypanothione-disulfide reductase (NADPH) activity
name: glyceraldehyde dehydrogenase (NADP) activity | name: glyceraldehyde dehydrogenase (NADP+) activity
name: valine dehydrogenase (NADP) activity | name: valine dehydrogenase (NADP+) activity
name: CoA-disulfide reductase (NADP) activity | name: CoA-disulfide reductase (NADPH) activity
name: CoA-glutathione reductase (NADP) activity | name: CoA-glutathione reductase (NADPH) activity
name: selenodiglutathione-disulfide reductase (NADP) activity | name: selenodiglutathione-disulfide reductase (NADPH) activity
name: protein-disulfide reductase (NAD(P)) activity | name: protein-disulfide reductase (NAD(P)H) activity
name: L-idonate 5-dehydrogenase activity (NAD-dependent) | name: L-idonate 5-dehydrogenase (NAD+) activity
name: choline monooxygenase activity (NADP-dependent) | name: choline monooxygenase (NADP+) activity
name: methylglyoxal reductase (NADH-dependent) activity | name: methylglyoxal reductase (NADH) activity
name: methylglyoxal reductase (NADPH-dependent) activity | name: methylglyoxal reductase (NADPH) activity
name: methylglyoxal reductase (NADPH-dependent, acetol producing) | name: methylglyoxal reductase (NADPH) (acetol producing) activity
name: nitric oxide reductase activity (NAD(P)H-dependent) activity | name: nitric oxide reductase (NAD(P)H) activity

**Comment by pgaudet** [comment]
**- GO:0035798 2-alkenal reductase (NADPH) activity:** 
add xref EC:1.3.1.102 and RHEA:13737

- GO:0032440 2-alkenal reductase (NAD(P)H) activity
add xref: RHEA:13737 {source="skos:narrowMatch"} and xref: RHEA:36731 {source="skos:narrowMatch"}

**Comment by pgaudet** [comment]
IUBMB writes NAD(P) in brackets, to avoid double parentheses. I've added this to the documentation: 


https://wiki.geneontology.org/Guidelines_for_new_Molecular_Functions#Meaning_of_NAD%28P%29H_in_GO_and_in_IUBMB
