### ISSUE TITLE
NTR: negative regulation of chromatin looping

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#27188]
* **Suggested term label:**
‘negative regulation of chromatin looping’

* **Definition (free text)**
Any process that stops, prevents or reduces the frequency, rate or extent of chromatin looping. 

* **Reference, in format PMID:#######**
 PMID:34856126

* **Gene product name and ID to be annotated to this term**

HGNC:37191 JPX, URS000075CF99_9606

* **Parent term(s)**
is_a negative regulation of chromatin organization GO:1905268
negatively_regulates chromatin looping GO:0140588

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160164
+name: negative regulation of chromatin loopin
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of chromatin looping." [PMID:34856126]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0140588 ! chromatin looping
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27188" xsd:anyURI
+created_by: rynl
+creation_date: 2024-03-04T21:34:39Z

**Comment by vanaukenk** [comment]
Hi - I was just doing some random testing on noctua-dev and noticed a typo in the term label for this term.

https://amigo.geneontology.org/amigo/term/GO:0160164

loopin -> looping

@raymond91125  Thanks.
