### ISSUE TITLE
Do not annotate flag

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27189]
- [x] GO:0043603 amide metabolic process  
- [x] GO:0019538 protein metabolic process
- [x] GO:0022411 cellular component disassembly
- [x] GO:0051641 cellular localization
- [x] GO:0071840 cellular component organization or biogenesis
GO:0016043 cellular component organization (already added)
- [x] GO:0006996 organelle organization
- [x] GO:0009059 macromolecule biosynthetic process
- [x] GO:0032501 multicellular organismal process
- [x] GO:0031327   negative regulation of cellular biosynthetic process 
- [x] GO:0031326 regulation of cellular biosynthetic process
- [x] GO:0031328 positive regulation of cellular biosynthetic process
- [x] GO:0031330 negative regulation of cellular catabolic process 
- [x] GO:0031329 regulation of cellular catabolic process
- [x] GO:0031331 positive regulation of cellular catabolic process
- [x] GO:0031324 negative regulation of cellular metabolic process 
- [x] GO:0031323 regulation of cellular metabolic process
- [x] GO:0031325 positive regulation of cellular metabolic process
- [x] GO:0042325  regulation of phosphorylation
- [x] GO:0001934  positive regulation of protein phosphorylation
- [x] GO:0042326  negative regulation of phosphorylation

**Comment by ValWood** [comment]
@pgaudet These are done, I used goc_do_not_annotate

but for some (i.e regulation of phosphorylation) which will eventually be obsoleted should I use
go_check_obsoletion_candidate (or is this going away).

I know we talked about this recently. I think it is a good idea to flag if the reason for do_not_annotate is that obsoletion is pending...

**Comment by pgaudet** [comment]
- Did you use goc_do_not_annotate ? I dont think this is a thing (but I dont find it) 

- go_check_obsoletion_candidate  was just created recently, but is not yet implement in P2GO (or Notcua) and hasn't been used much. It's fine to use it. 
Thanks, Pascale

**Comment by ValWood** [comment]
I used  gocheck_do_not_annotate

I could also add 
go_check_obsoletion_candidate 
to the "regulation of phosphorylation" terms ^*. The others seem to be  valid/useful grouping terms.

I also added:
Note that this term is in the subset of terms that should not be used for direct gene product annotation. Instead, select a child term or, if no appropriate child term exists, please request a new term. Direct annotations to this term may be amended during annotation QC.

* I have a long list of "regulation of modification" terms to  block, but I'll try OntoBot for those. This way is looong
