### ISSUE TITLE
Obsoletion request (?):GO:0004495 mevaldate reductase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27183]
The two 'mevaldate reductase activity' terms shown below reference transferred ECs (in their def and/or xref) - EC:1.1.1.32 and EC:1.1.1.33 have been transferred to EC:1.1.1.1, EC:1.1.1.2, respectively.
Also, there are no GO annotations to either term.
But the RHEA and MetaCyc xrefs are still valid.

So, either obsolete the two terms, or at least remove the references to the old ECs.

id: GO:0004495
name: mevaldate reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: (R)-mevalonate + acceptor = mevaldate + reduced acceptor." [EC:1.1.1.32, EC:1.1.1.33]
is_a: GO:0016616 ! oxidoreductase activity, acting on the CH-OH group of donors, NAD or NADP as acceptor

id: GO:0019727
name: mevaldate reductase (NAD+) activity
namespace: molecular_function
def: "Catalysis of the reaction: (R)-mevalonate + NAD+ = H+ + mevaldate + NADH." [EC:1.1.1.32, RHEA:13221]
xref: EC:1.1.1.32
xref: KEGG_REACTION:R02246
xref: MetaCyc:MEVALDATE-REDUCTASE-RXN
xref: RHEA:13221
is_a: GO:0004495 ! mevaldate reductase activity

**Comment by raymond91125** [comment]
https://github.com/geneontology/go-ontology/issues/27410

**Comment by pgaudet** [comment]
GO:0019727 mevaldate reductase (NADH) activity should also be obsoleted (same reason)

**Comment by sjm41** [comment]
The MEVALDATE-REDUCTASE-RXN page (http://metacyc.ai.sri.com/reaction?orgid=META&id=MEVALDATE-REDUCTASE-RXN) equates the reaction to EC:1.1.1.1 and although says:

(R)-mevalonate + NAD+ ← (R)-mevaldate + NADH + H+
Note that this reaction equation differs from the official Enzyme Commission reaction equations for this EC entry, which can be found here and here.
**No enzyme has been identified for this reaction in this database.**

So I think GO:0019727 can be obsoleted.
