### ISSUE TITLE
Obsoletion request: GO:0004023 alcohol dehydrogenase activity, metal ion-independent

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27182]
id: GO:0004023
name: alcohol dehydrogenase activity, metal ion-independent
namespace: molecular_function
def: "Catalysis of the reaction: an alcohol + NAD+ = an aldehyde or ketone + NADH + H+; can proceed in the absence of a metal ion." [EC:1.1.1.1, GOC:mah]
is_a: GO:0004022 ! alcohol dehydrogenase (NAD+) activity

There are no annotations to this term, and its definition is effectively the same as its parent term.

Note: There are two similarly-worded sister-terms, which I guess is why GO:0004023 was created:

id: GO:0004024
name: alcohol dehydrogenase activity, zinc-dependent
namespace: molecular_function
def: "Catalysis of the reaction: an alcohol + NAD+ = an aldehyde or ketone + NADH + H+, requiring the presence of zinc." [EC:1.1.1.1, GOC:mah]
is_a: GO:0004022 ! alcohol dehydrogenase (NAD+) activity

[Term]
id: GO:0004025
name: alcohol dehydrogenase activity, iron-dependent
namespace: molecular_function
def: "Catalysis of the reaction: an alcohol + NAD+ = an aldehyde or ketone + NADH + H+, requiring the presence of iron." [EC:1.1.1.1, GOC:mah]
is_a: GO:0004022 ! alcohol dehydrogenase (NAD+) activity

**Comment by pgaudet** [comment]
Done here https://github.com/geneontology/go-ontology/issues/28393
