### ISSUE TITLE
Do not annotate terms and obsoletions (high level grouping terms)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27194]
The obsoletions in thei ticket are

- [x]  The reason for obsoletion is that this term was an unnecessary grouping term.

GO:0042221  response to chemical
has 
Restrictions
This term should not be used for direct manual annotation; it may, however, be used for mapping to external vocabularies in order to create electronic annotations.
See comment below for further information.

~should that be removed and a general do not annotate applied?~ is already the general term

Also for   do not annotate
- [x] GO:0010033   response to organic substance
- [x] GO:1901698	response to nitrogen compound
- [x] GO:1901699 cellular response to nitrogen compound
- [x] GO:0010243	response to organonitrogen compound
- [x] GO:1901700	response to oxygen-containing compound

**Comment by ValWood** [comment]
GO:0030003 | intracellular monoatomic cation homeostasis

**Comment by pgaudet** [comment]
I think some of these terms could be obsoleted? For example
'organic substance biosynthetic process' <http://purl.obolibrary.org/obo/GO_1901576>
'organic substance catabolic process' <http://purl.obolibrary.org/obo/GO_1901575>
'organic substance metabolic process' <http://purl.obolibrary.org/obo/GO_0071704>
'organic substance transport' <http://purl.obolibrary.org/obo/GO_0071702>
'response to organic substance' <http://purl.obolibrary.org/obo/GO_0010033>
'detection of organic substance' <http://purl.obolibrary.org/obo/GO_0071703>
'response to inorganic substance' <http://purl.obolibrary.org/obo/GO_0010035>
'cellular response to organic substance' <http://purl.obolibrary.org/obo/GO_0071310>
'cellular response to inorganic substance' <http://purl.obolibrary.org/obo/GO_0071241>

What do you think ?

**Comment by ValWood** [comment]
absolutely!

**Comment by pgaudet** [comment]
> GO:1901564 organonitrogen compound metabolic process

Obsoletion? 


Please include these as well: 
'organonitrogen compound biosynthetic process' <http://purl.obolibrary.org/obo/GO_1901566>
'organonitrogen compound catabolic process' <http://purl.obolibrary.org/obo/GO_1901565>
'organonitrogen compound metabolic process' <http://purl.obolibrary.org/obo/GO_1901564>
'organonitrogen heterocyclic compound' <http://purl.obolibrary.org/obo/CHEBI_38101>
'response to organonitrogen compound' <http://purl.obolibrary.org/obo/GO_0010243>
'cellular response to organonitrogen compound' <http://purl.obolibrary.org/obo/GO_0071417>

**Comment by pgaudet** [comment]
Bad results, AmiGO evidence not available. This will need to b re-ran after the next GO release.
