### ISSUE TITLE
NTR: oxoadipate dehydrogenase complex

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27207]
Related to #27202:

name: oxoadipate dehydrogenase complex
namespace: cellular_component
def: "A multi-enzyme complex that catalyzes the oxidative decarboxylation of 2-oxoadipate to glutaryl-CoA, thereby acting in the final step of lysine and tryptophan catabolism in mitochondria. The complex comprises multiple copies of three enzymes referred to as E1, E2 and E3: 2-oxoadipate dehydrogenase (E1), dihydrolipoamide S-succinyltransferase (E2) and dihydrolipoamide dehydrogenase (E3)." [PMID:29191460, PMID:32695416]
comment: The catalytic activities of the individual components of this complex are represented by the molecular function terms '2-oxoadipate dehydrogenase activity ; GO:0160166' (E1), 'dihydrolipoyllysine-residue succinyltransferase activity ; GO:0004149' (E2), and 'dihydrolipoyl dehydrogenase activity ; GO:0004148' (E3).
synonym: "OADHC" EXACT []
is_a: GO:0045240 ! alpha-ketoacid dehydrogenase complex
intersection_of: GO:0032991 ! protein-containing complex

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160167
+name: oxoadipate dehydrogenase complex
+namespace: cellular_component
+def: "A multi-enzyme complex that catalyzes the oxidative decarboxylation of 2-oxoadipate to glutaryl-CoA, thereby acting in the final step of lysine and tryptophan catabolism in mitochondria. The complex comprises multiple copies of three enzymes referred to as E1, E2 and E3: 2-oxoadipate dehydrogenase (E1), dihydrolipoamide S-succinyltransferase (E2) and dihydrolipoamide dehydrogenase (E3)." [PMID:29191460, PMID:32695416]
+comment: The catalytic activities of the individual components of this complex are represented by the molecular function terms '2-oxoadipate dehydrogenase activity ; GO:0160166' (E1), 'dihydrolipoyllysine-residue succinyltransferase activity ; GO:0004149' (E2), and 'dihydrolipoyl dehydrogenase activity ; GO:0004148' (E3).
+synonym: "OADHC" EXACT []
+is_a: GO:0045240 ! alpha-ketoacid dehydrogenase complex
+intersection_of: GO:0032991 ! protein-containing complex
+intersection_of: capable_of GO:0160166 ! 2-oxoadipate dehydrogenase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27207" xsd:anyURI
+created_by: rynl
+creation_date: 2024-03-07T00:52:16Z
