### ISSUE TITLE
NTR: T=9 icosahedral viral capsid

### ISSUE THREAD

**Issue by enyahoxha** [geneontology/go-ontology#27206]
Please provide as much information as you can: 

Suggested term label: T=9 icosahedral viral capsid

Definition: The protein coat that surrounds the infective nucleic acid in some virus particles where the subunits (capsomeres) are arranged to form an icosahedron with T=9 symmetry. The T=9 capsid is composed of 12 pentameric and 80 hexameric capsomeres.

Reference: PMID: 37138077

Gene product name and ID to be annotated to this term:

There are many gene products that can be annotated to this term in this paper, one example is:

Major capsid protein gp32 (MCP)(UniprotKB:A0A385DVU6)

Parent term(s):
GO:0019030 
icosahedral viral capsid

Cross-references:
(https://viralzone.expasy.org/5316)

This is for the CACAO class, @jrr-cpt, and @dsiegele

**Comment by pgaudet** [comment]
@SIBVirus Is this term in ViralZone? I cannot find it. 

Thanks, Pascale

**Comment by SIBvirus** [comment]
Oui, on l’a sous:

https://viralzone.expasy.org/5316

A+
Chantal

**Comment by pgaudet** [comment]
@raymond91125 please add cross reference VZ:5316

Thanks, Pascale

**Comment by pgaudet** [comment]
@raymond91125 can you please create all the capsids we are missing: 

- [ ] T=21/pseudo21 icosahedral capsid VZ:833
- [ ] T=27/pseudo27 icosahedral capsid VZ:1556
- [ ] T=28 icosahedral capsid VZ:6057
- [ ] T=31/pseudo31 icosahedral capsid VZ:7036 

Thanks, Pascale

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160168
+name: T=9 icosahedral viral capsid
+namespace: cellular_component
+def: "The protein coat that surrounds the infective nucleic acid in some virus particles where the subunits (capsomeres) are arranged to form an icosahedron with T=9 symmetry. The T=9 capsid is composed of 12 pentameric and 80 hexameric capsomeres." [PMID:37138077]
+xref: VZ:5316
+is_a: GO:0019030 ! icosahedral viral capsid
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27206" xsd:anyURI
+created_by: rynl
+creation_date: 2024-03-13T17:09:29Z
+
+[Term]
+id: GO:0160169
+name: T=21/pseudo21 icosahedral capsid
+namespace: cellular_component
+def: "The protein coat that surrounds the infective nucleic acid in some virus particles where the subunits (capsomeres) are arranged to form an icosahedron with T=21 or pseudo T=21 symmetry." [VZ:833]
+xref: VZ:833
+is_a: GO:0019030 ! icosahedral viral capsid
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27206" xsd:anyURI
+created_by: rynl
+creation_date: 2024-03-13T17:27:52Z
+
+[Term]
+id: GO:0160170
+name: T=27/pseudo27 icosahedral capsid
+namespace: cellular_component
+def: "The protein coat that surrounds the infective nucleic acid in some virus particles where the subunits (capsomeres) are arranged to form an icosahedron with T=27 or pseudo T=27 symmetry." [VZ:1556]
+xref: VZ:1556
+is_a: GO:0019030 ! icosahedral viral capsid
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27206" xsd:anyURI
+created_by: rynl
+creation_date: 2024-03-13T17:36:35Z
+
+[Term]
+id: GO:0160171
+name: T=28 icosahedral capsid
+namespace: cellular_component
+def: "The protein coat that surrounds the infective nucleic acid in some virus particles where the subunits (capsomeres) are arranged to form an icosahedron with T=28 symmetry." [VZ:6057]
+xref: VZ:6057
+is_a: GO:0019030 ! icosahedral viral capsid
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27206" xsd:anyURI
+created_by: rynl
+creation_date: 2024-03-13T21:03:24Z
+
+[Term]
+id: GO:0160172
+name: T=31/pseudo31 icosahedral capsid
+namespace: cellular_component
+def: "The protein coat that surrounds the infective nucleic acid in some virus particles where the subunits (capsomeres) are arranged to form an icosahedron with T=31 or pseudo T=31 symmetry." [VZ:7036]
+xref: VZ:7036
+is_a: GO:0019030 ! icosahedral viral capsid
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27206" xsd:anyURI
+created_by: rynl
+creation_date: 2024-03-13T21:05:10Z
