### ISSUE TITLE
Ensure that names for biosynthesis/catabolism match logical definitions

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#27211]
Names and definitions for metabolic terms should match up to the yaml DPs

**Comment by balhoff** [comment]
@cmungall did you mean for your PR to close this issue completely, or were you looking for a more general solution here?

**Comment by raymond91125** [comment]
Sorry, not my intention.

**Comment by pgaudet** [comment]
I am not sure what happenned, we now have ChEBI showing up with their IDs only, and not the label ? 

There were way more changes in the diff than what was changed by @cmungall ; was it ready to be merged?
