### ISSUE TITLE
NTR: negative regulation of pheromone response MAPK cascade 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27218]
Please provide as much information as you can: 

* **Suggested term label:**

NTR regulation of pheromone response MAPK cascade 
NTR negative regulation of pheromone response MAPK cascade 
we have: positive regulation of pheromone response MAPK cascade 

* **Definition (free text)**

* **Reference, in format PMID:#######**
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Is there evidence for negative regulation? 

In our most recent guidelines, we try not to create terms that are not going to be used, or are not needed as grouping classes. 

If there is a 'regulation' term, people often us it rather than the specific positive or negative child. 

Thanks, Pascale

**Comment by ValWood** [comment]
I wanted it for 
https://www.pombase.org/gene/SPBC24C6.06
to replace 
[negative regulation of MAPK cascade](https://www.pombase.org/term/GO:0043409)
and
[pheromone response MAPK cascade](https://www.pombase.org/term/GO:0071507)

**Comment by ValWood** [comment]
@pgaudet  for tgis one, do I need to add the disign patterns

dcterms:conforms to
http://purl.obolibrary.org/obo/go/patterns/regulation.yaml

(I never did a regulates term before)

**Comment by balhoff** [comment]
@ValWood this will be updated automatically.

**Comment by ValWood** [comment]
+[Term]
+id: GO:0180039
+name: regulation of pheromone response MAPK cascade
+namespace: biological_process
+def: "Any process that modulates the frequency, rate or extent of a pheromone response MAPK cascade." [] {comment="GOC:vw"}
+is_a: GO:0065007 ! biological regulation
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: regulates GO:0071507 ! pheromone response MAPK cascade
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27218" xsd:anyURI
+created_by: vw
+creation_date: 2024-03-21T15:08:05Z
+
+[Term]
+id: GO:0180040
+name: negative regulation of pheromone response MAPK cascade
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of a pheromone response MAPK cascade." [GOC:vw]
+is_a: GO:0065007 ! biological regulation
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0071507 ! pheromone response MAPK cascade
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27218" xsd:anyURI
+created_by: vw
+creation_date: 2024-03-21T15:19:43Z

**Comment by pgaudet** [comment]
Hi @ValWood 
> @pgaudet for this one, do I need to add the design patterns
dcterms:conforms to
http://purl.obolibrary.org/obo/go/patterns/regulation.yaml

No, these get added automatically if they match a design pattern. 

I think you can close this.

**Comment by ValWood** [comment]
Yep, used!
