### ISSUE TITLE
NTR: gene silencing by piRNA-directed DNA methylation/retrotransposon silencing by piRNA-directed DNA methylation; update silencing by RNA-directed DNA methylation

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#27238]
The current definition for silencing by RNA-directed DNA methylation  GO:0080188 is for an siRNA-guided process:
"A small RNA-based gene silencing process in which small interfering RNAs (siRNAs) guide DNA methylation to the siRNA-generating genomic loci and other loci that are homologous to the siRNAs for de novo DNA methylation....."

piRNAs can also mediate DNA methylation https://pubmed.ncbi.nlm.nih.gov/33419460/  but with different factors.

So, think we need separate terms for piRNA-mediated process and update the existing terms to make them explict for siRNA-guided processes

1.
* **Update term labels:**
change silencing by RNA-directed DNA methylation GO:0080188 -> gene silencing by siRNA-directed DNA methylation
change retrotransposon silencing by RNA-directed DNA methylation GO:0141010 -> retrotransposon silencing by siRNA-directed DNA methylation

2.
* **Suggested  new term label:**
gene silencing by piRNA-directed DNA methylation 

* **Definition (free text)**
A small RNA-based gene silencing process in which Piwi-associated RNAs (piRNAs) guide de novo DNA methylation. This results in a heterochromatin assembly, a chromatin conformation that is refractory to transcription.

* **Reference, in format PMID:#######**
PMID:32674113, PMID:38359823

* **Parent term(s)**
* is_a GO:0140966 piRNA-mediated heterochromatin formation

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
EXACT piRNA-directed de novo DNA methylation

3.
* **Suggested  new term label:**
retrotransposon silencing by piRNA-directed DNA methylation 

* **Definition (free text)**
A retrotransposon silencing process in which Piwi-associated RNAs (piRNAs) guide de novo DNA methylation. This results in a heterochromatin assembly, a chromatin conformation that is refractory to transcription.

* **Reference, in format PMID:#######**
PMID:32674113, PMID:38359823

* **Parent term(s)**
* is_a GO:0141006 piRNA-mediated retrotransposon silencing by heterochromatin formation
* is_a gene silencing by piRNA-directed DNA methylation  (new)

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
EXACT piRNA-directed de novo retrotransposon DNA methylation

**Comment by hattrill** [comment]
examples for proteins to annotate:
Spocd1(Mus musculus)SPOC domain-containing protein 1 (UniProtKB:B1ASB6)
Dnmt3a(Mus musculus)DNA (cytosine-5)-methyltransferase 3A (UniProtKB:P0DOY1)

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141176
+name: gene silencing by piRNA-directed DNA methylation
+namespace: biological_process
+def: "A small RNA-based gene silencing process in which Piwi-associated RNAs (piRNAs) guide de novo DNA methylation. This results in a heterochromatin assembly, a chromatin conformation that is refractory to transcription." [PMID:32674113, PMID:38359823]
+is_a: GO:0140966 ! piRNA-mediated heterochromatin formation
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27238" xsd:anyURI
+created_by: pg
+creation_date: 2024-03-11T13:47:09Z
+
