### ISSUE TITLE
Textual definition update: azurophil granule

### ISSUE THREAD

**Issue by addiehl** [geneontology/go-ontology#27231]
I would kindly request that the GO term ['azurophil granule' GO:0042582](https://amigo.geneontology.org/amigo/term/GO:0042582) be redefined to make it less specific, per the discussion in the [CL issue tracker](https://github.com/obophenotype/cell-ontology/issues/2309).

The original definition is too specific in implying azurophil granules are found only in neutrophils, when in fact they are found in both immature and mature granulocytes of all types ([PMID:5914694](https://pubmed.ncbi.nlm.nih.gov/5914694/)), as well as in NK cells and T cells ([PMID:28717070](https://pubmed.ncbi.nlm.nih.gov/28717070/)).

Suggested new definition (based on [wikipedia](https://en.wikipedia.org/wiki/Azurophilic_granule) and other sources):
"An azurophilic granule is a primary lysosome readily stainable with a Romanowsky stain."

This is of course based on classical hematology methods.

* **Reference(s)**
[PMID:5914694](https://pubmed.ncbi.nlm.nih.gov/5914694/), [PMID:28717070](https://pubmed.ncbi.nlm.nih.gov/28717070/), [PMID:17152095](https://pubmed.ncbi.nlm.nih.gov/17152095/), [wikipedia](https://en.wikipedia.org/wiki/Azurophilic_granule)

Thanks, Alex

**Comment by raymond91125** [comment]
What would be the proper PART_OF relation for azurophil granule then, granulocytopoietic cell? Or there is not a narrow yet encompassing CL class?

**Comment by addiehl** [comment]
Thanks Raymond!
