### ISSUE TITLE
NTR: symbiont-mediated evasion of recognition by host innate immune effector & children 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27250]
+[Term]
+id: GO:0141177
+name: symbiont-mediated evasion of recognition by host innate immune effector
+namespace: biological_process
+def: "A process by which a symbiont mitigates the effects of recognition by a host innate immune effector. Effectors have a direct activity against a symbiont and include complement, antimicrobial peptides, and bacterial restriction enzymes. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:pg]
+synonym: "evasion of symbiont recognition by host innate immune effector" EXACT []
+is_a: GO:0141043 ! symbiont-mediated evasion of host innate immune response
+created_by: pg
+creation_date: 2024-03-12T13:23:48Z
+
+[Term]
+id: GO:0141178
+name: symbiont-mediated evasion of recognition by host complement
+namespace: biological_process
+def: "A process by which a symbiont avoids the effects of recognition by host  complement by altering molecules on the symbiont surface. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:pg]
+synonym: "symbiont-mediated evasion of host complement" EXACT []
+is_a: GO:0141177 ! symbiont-mediated evasion of recognition by host innate immune effector
+created_by: pg
+creation_date: 2024-03-12T14:01:12Z
+
+[Term]
+id: GO:0141179
+name: symbiont-mediated evasion of recognition by host antimicrobial peptide
+namespace: biological_process
+def: "A process by which a symbiont avoids the effects of recognition by a host  antimicrobial peptide by altering molecules on the symbiont surface. The host is defined as the larger of the organisms involved in a symbiotic interaction." [GOC:pg]
+is_a: GO:0141177 ! symbiont-mediated evasion of recognition by host innate immune effector
+created_by: pg
+creation_date: 2024-03-12T14:09:42Z
+

**Comment by pgaudet** [comment]
@genegodbold I need references for these 3 new terms.

**Comment by pgaudet** [comment]
Other changes in this branch:

- [ ]  changed labels to add 'symbiont-mediated evasion'
- [ ] moved terms under new grouping term GO:0141177 symbiont-mediated evasion of recognition by host innate immune effector: 
- GO:0039699   symbiont-mediated evasion of mRNA degradation by host via mRNA cap methylation
-  GO:0099016 symbiont-mediated evasion of DNA end degradation by host
- GO:0099018 symbiont-mediated evasion of host restriction-modification system

**Comment by genegodbold** [comment]
You didn't ask for these, but here are some viral sequences for...
GO:0039699 symbiont-mediated evasion of mRNA degradation by host via mRNA cap methylation
- **Nonstructural protein 14** from _SARS-CoV_: Host RIG-like receptors use the presence of a 5' cap to distinguish viral RNA from host mRNA. NSP14 has guanine N7-methyltransferase activity that can produce a cap structure on viral RNA [PMID:19208801].
- **Nonstructural protein 16** from _SARS-CoV_: NSP16 of SARS-CoV further modifies the viral mRNA cap with its 2’-O-methyl-transferase activity, allowing the virus to efficiently evade recognition by host MDA5 [PMID21085181].
- **Nonstructural protein 16** from _SARS-CoV-2_: NSP16 is a 2'-O-methyltransferase that forms part of the replication-transcription complex. NSP16 mimics human cap-specific mRNA methyltransferase CMTr1 in capping mRNA, except it caps viral mRNA to confound host recognition receptors IFIT and RIG-1. [PMID:33330873]
- **Nonstructural protein 10** from _SARS-CoV-2_: NSP16 requires NSP10 to recognize its cofactors and mRNA ligand. NSP10 promotes the opening of the NSP16 binding regions. [PMID:33330873]

**Bacterial sequences for GO:0141178** (symbiont-mediated evasion of recognition by host complement)
- **Lag-1** from _Legionella pneumophila_ is an O-acetyltransferase for lipopolysaccharide modification found in all major clades of Legionella pneumophila. It confers resistance to complement-mediated killing by human serum by inhibiting deposition of molecules of the classical pathway on the bacterial surface. When C1q was depleted in serum, Legionellae which did not express the gene encoding Lag-1 were not killed at a greater rate than wild type bacteria. Lag-1 expression also enhances resistance to bacterial phagocytosis by neutrophils and survival in a murine model of pulmonary legionellosis [PMID:34887398].
- The presence of the **periplasmic protease** (Prc) from _Escherichia coli_ results in a higher bacteremia in uropathogenic Escherichia col. Prc plays a role in serum resistance of the bacterium. Mutant bacterium lacking Prc are targeted by host complement activation pathways that are both independent and dependent of antibody. Proteolytically active Prc appears to act on the E. coli membrane components to reduce the effectiveness of the host membrane attack complex in destroying the bacterial cells. Residues Ser430, Asp411, and Lys455 are essential for Prc catalytic activity [PMID:22825444].
- **Lipooligosaccharide phosphoethanolamine transferase A** (LptA) from Neisseria gonorrhoeae catalyzes the transfer of phosphoethanolamine (PEA) to the 4' phosphate group of lipid A of gonococcal lipooligosaccharide (LOS), an abundant surface constituent of the bacterium. Loss of LptA leads to a decrease in the bacteria's ability to resist killing by host complement, cationic antimicrobial peptides, and neutrophil extracellular traps [PMID:25537831].

**Bacterial sequences for GO:0141179** (symbiont-mediated evasion of recognition by host antimicrobial peptide)
-  **Lipooligosaccharide phosphoethanolamine transferase A** (LptA) from Neisseria gonorrhoeae catalyzes the transfer of phosphoethanolamine (PEA) to the 4' phosphate group of lipid A of gonococcal lipooligosaccharide (LOS), an abundant surface constituent of the bacterium. Loss of LptA leads to a decrease in the bacteria's ability to resist killing by host complement, cationic antimicrobial peptides, and neutrophil extracellular traps [PMID:25537831].
- **Resistance to cationic microbial peptides** (Rcp) from _Legionella pneumophila_: Mutations in Rcp, which resembles Salmonella PagP, were defective for growth intracellular growth in amebae and U937 macrophages. Rcp renders the encoding bacterium resistant to cationic antimicrobial peptides [PMID:11401964].
-  **NaxD** (N-acetylhexosamine deacetylase; FTT_0453; FTN_0544) from _Francisella tularensis_: This deacetylase modifies lipid A of LPS so the bacterial membrane is more resistant to antibacterial peptides [PMID22966934].
