### ISSUE TITLE
Taxon constraint:  GO:0102483 scopolin beta-glucosidase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27259]
Please provide as much information as you can: 

* **GO term ID label:**

GO:0102483 scopolin beta-glucosidase activity

Scopolin is a [glucoside](https://en.wikipedia.org/wiki/Glucoside) of [scopoletin](https://en.wikipedia.org/wiki/Scopoletin) formed by the action of the [enzyme](https://en.wikipedia.org/wiki/Enzyme) [scopoletin glucosyltransferase](https://en.wikipedia.org/wiki/Scopoletin_glucosyltransferase).[[1]](https://en.wikipedia.org/wiki/Scopolin#cite_note-1) It occurs in [Chamaemelum nobile](https://en.wikipedia.org/wiki/Chamaemelum_nobile).[[2]](https://en.wikipedia.org/wiki/Scopolin#cite_note-2)

https://en.wikipedia.org/wiki/Scopolin

I'm going to suggest only in plants?
@pgaudet ?

* **Request to add a taxon constraint:**
* * **only in taxon: **
* * **never in taxon: **

* **Request to remove a taxon constraint:**
Please specify

* **Supporting evidence if available (e.g PMID):**

**Comment by ValWood** [comment]
The EC mapping is transferring quite widely:

IEA with 3.2.1.21



[IEA](http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA)) with [3.2.1.21](https://enzyme.expasy.org/EC/3.2.1.21)

**Comment by ValWood** [comment]
https://www.sciencedirect.com/topics/chemistry/scopolin
scopolin appears to be an anti-fungal plant compound

**Comment by pgaudet** [comment]
These are difficult, bacteria and fungus may metabolize the compound. Unless you know that this is strictly used for biosynthesis?

**Comment by pgaudet** [comment]
Indeed many bacterial genes annotated 

<img width="477" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/a601fc6d-3da3-4418-9740-f4150b6d757f">

**Comment by ValWood** [comment]
Ah ok,  maybe this is a true yeast activity then, will close
