### ISSUE TITLE
Obsoletion request: GO:0006069	 ethanol oxidation

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27260]
Please provide as much information as you can:

* **GO term ID and Label**

GO:0006069 | ethanol oxidation

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x] The reason for obsoletion is that this term represents a molecular function.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

I filtered this term for Pombase to remove electronic mappings

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [x] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [x] paste the text in the ontology ticket

**Comment by pgaudet** [comment]
MetaCyc calls this ethanol degradation 
see META&id=PWY66-21, PWY66-161, PWY66-162

This term seems to have the same meaning as [GO:0019431 acetyl-CoA biosynthetic process from ethanol](https://amigo.geneontology.org/amigo/term/GO:0019431#display-lineage-tab)


Actions: 

- [ ] obsolete GO:0006069 ethanol oxidation
- [ ] [GO:0019431 acetyl-CoA biosynthetic process from ethanol](https://amigo.geneontology.org/amigo/term/GO:0019431#display-lineage-tab): ad parent GO:0006091 generation of precursor metabolites and energy
- [ ] GO:0019431 : Add xrefs: [MetaCyc:PWY66-21](https://biocyc.org/META/NEW-IMAGE?type=NIL&object=PWY66-21), [MetaCyc:PWY66-161](https://biocyc.org/META/NEW-IMAGE?type=NIL&object=PWY66-161), [MetaCyc:PWY66-162](https://biocyc.org/META/NEW-IMAGE?type=NIL&object=PWY66-162)



OK? 

Thanks, Pascale

**Comment by deustp01** [comment]
This is getting close to annotating biological purpose, and in a taxon-specific way. For mammals, it's also legitimate to classify ethanol as a toxin and its metabolism to acetyl-CoA as an (expensive) detoxification process. It's certainly not a major source of acetyl-CoA (as a precursor metabolite or an energy source). And for the elementary textbook fungi I know about, ethanol is a metabolic endproduct generated to consume otherwise unusable reducing equivalents under anaerobic growth conditions.

**Comment by pgaudet** [comment]
Thanks @deustp01 
Note that we also have 'ethanol catabolic process', would that work for you for the detoxification aspect ?

**Comment by deustp01** [comment]
[Reactome pathway instance](https://reactome.org/content/detail/R-HSA-71384) patched with GO:0006068 'ethanol catabolic process'
