### ISSUE TITLE
Add response terms to gocheck_do_not_annotate

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#27272]
Hey, Ontobot! appy:

* add GO:0042221 to subset gocheck_do_not_annotate
* add GO:0010033 to subset gocheck_do_not_annotate
* add GO:1901698 to subset gocheck_do_not_annotate
* add GO:0010243 to subset gocheck_do_not_annotate
* add GO:1901700 to subset gocheck_do_not_annotate
* add GO:0030003 to subset gocheck_do_not_annotate
* add GO:0016043 to subset gocheck_do_not_annotate

Fixes #27194

**Comment by pgaudet** [comment]
I think the command is 'apply' - created new ticket 
https://github.com/geneontology/go-ontology/issues/27274
