### ISSUE TITLE
Add response terms to gocheck_do_not_annotate

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27274]
Hey, Ontobot! apply:

    add GO:0042221 to subset gocheck_do_not_annotate
    add GO:0010033 to subset gocheck_do_not_annotate
    add GO:1901698 to subset gocheck_do_not_annotate
    add GO:0010243 to subset gocheck_do_not_annotate
    add GO:1901700 to subset gocheck_do_not_annotate
    add GO:0030003 to subset gocheck_do_not_annotate
    add GO:0016043 to subset gocheck_do_not_annotate

Fixes https://github.com/geneontology/go-ontology/issues/27194

**Comment by ValWood** [comment]
Did this work? I am trying one now...

**Comment by pgaudet** [comment]
Done here: https://github.com/geneontology/go-ontology/issues/27272
