### ISSUE TITLE
Missing parent: amino acid biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27304]
* **GO term ID and label for which you request a new superclass**

* **New superclass (parent) suggested**

Has lost its superclass "amino acid metabolic process" causing lots of things to lose their slim catagory

**Comment by ValWood** [comment]
I instantiated this because of the affect on slims, and analysis, but maybe there is a problem with the equivalence axiom?

<img width="561" alt="Screenshot 2024-03-15 at 15 31 19" src="https://github.com/geneontology/go-ontology/assets/7359272/16585641-6dd5-47d0-933b-d62415e48d4c">

**Comment by pgaudet** [comment]
We should not have to infer something like this, this is very high level, ChEBI should do the work for us.

**Comment by pgaudet** [comment]
Fixed to  and ('has primary output' some 'amino acid zwitterion') to match the parent 'amino acid metabolic process'

**Comment by pgaudet** [comment]
did the same for amino acid catabolic process
