### ISSUE TITLE
Full ontology build fails in pipeline due to "missing file" gocheck_do_not_manually_annotate.owl 

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#27316]
I believe there has been recent changes around the "do not annotate" stuff recently. It looks like we're now failing on something like a rename or filename issue?

```
17:08:34  ROBOT_JAVA_ARGS=-Xmx48G robot --catalog catalog-v001.xml annotate -i build/subsets/gocheck_do_not_manually_annotate.owl --annotation owl:versionInfo 2024-03-15 -o subsets/gocheck_do_not_manually_annotate.owl convert -o subsets/gocheck_do_not_manually_annotate.obo convert -o subsets/gocheck_do_not_manually_annotate.json
17:08:35  org.semanticweb.owlapi.io.OWLOntologyInputSourceException: java.io.FileNotFoundException: build/17:08:34  ROBOT_JAVA_ARGS=-Xmx48G robot --catalog catalog-v001.xml annotate -i build/subsets/gocheck_do_not_manually_annotate.owl --annotation owl:versionInfo 2024-03-15 -o subsets/gocheck_do_not_manually_annotate.owl convert -o subsets/gocheck_do_not_manually_annotate.obo convert -o subsets/gocheck_do_not_manually_annotate.json
17:08:35  org.semanticweb.owlapi.io.OWLOntologyInputSourceException: java.io.FileNotFoundException: build/subsets/gocheck_do_not_manually_annotate.owl (No such file or directory)
17:08:35  Use the -vvv option to show the stack trace.
17:08:35  Use the --help option to see usage information.
17:08:35  
17:08:35  real	0m0.972s
17:08:35  user	0m2.343s
17:08:35  sys	0m0.224s
17:08:35  make: *** [Makefile:307: subsets/gocheck_do_not_manually_annotate.owl] Error 1(No such file or directory)
17:08:35  Use the -vvv option to show the stack trace.
17:08:35  Use the --help option to see usage information.
17:08:35  
17:08:35  real	0m0.972s
17:08:35  user	0m2.343s
17:08:35  sys	0m0.224s
17:08:35  make: *** [Makefile:307: subsets/gocheck_do_not_manually_annotate.owl] Error 1
```

**Comment by kltm** [comment]
According to @pgaudet on slack: "The subset has been removed".

**Comment by kltm** [comment]
@pgaudet According to the README (https://github.com/geneontology/go-ontology/blob/master/src/ontology/subsets/README.md), the folder is derived? That said, I can see edits recently.

My best guess here is that https://github.com/geneontology/go-ontology/blob/4e96203f7552a651e90a08c8f78ec4f1f9b21bac/src/ontology/Makefile#L298 need to have `gocheck_do_not_manually_annotate` removed, as it is hinting the system try and build something that is no longer generated.

**Comment by kltm** [comment]
@pgaudet @balhoff Potential fix at https://github.com/geneontology/go-ontology/pull/27319, but it would be good to have verification and, hopefully, documentation.

**Comment by pgaudet** [comment]
@kltm I made a first attempt here: 
https://wiki.geneontology.org/Adding_and_Removing_GO_Subsets_(Slims)#Removing_a_subset

which states 
 > Add a task on the corresponding ticket to edit the Makefile to remove the subset. ' 

but please add more details; we should specific which makefile we are talking about, where that is located, and who has permissions to do that. 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet I've added a little more detail. Permissions are controlled by whatever the GH rules are for `go-ontology` and the ontology group.

**Comment by pgaudet** [comment]
Where are these rules? Can I edit them when I change the subsets?

**Comment by kltm** [comment]
I'm not sure I quite follow, but access for the repo is managed here: https://github.com/geneontology/go-ontology/settings/access
It's a bit messy; I'd probably start by cleaning everybody out into proper groups.

**Comment by kltm** [comment]
@balhoff I believe the discussion here is moot, due to your work on https://github.com/geneontology/go-ontology/issues/27269 ?

**Comment by balhoff** [comment]
QC check is operational.
