### ISSUE TITLE
Obsolete & replace equivalent classes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27310]
Hello, 

When changing the logical definitions of the following terms to the ChEBI 7.3 term, we end up with equivalent terms: 
see https://github.com/geneontology/go-ontology/issues/27059#issuecomment-2000102591

Please obsolete the following terms with replace by the terms on the right of the ==
- [ ] beta-glucoside transport GO_0015759 == cellobiose transport GO_0019533
- [ ] beta-glucoside transmembrane transporter activity GO_0015573 ==cellobiose transmembrane transporter activity GO_0019191 
- [ ] beta-glucoside metabolic process GO_1901804 == cellobiose metabolic process GO_2000891 
- [ ]  beta-glucoside catabolic process GO_1901805 == cellobiose catabolic process GO_2000892
- [ ] allose metabolic process GO_0019313 == D-allose metabolic process GO_0019314
- [ ] allose biosynthetic process GO:0046366  ==  D-allose biosynthetic process GO:0019315 
- [ ] allose catabolic process GO_0046367 == D-allose catabolic process GO:0019316
- [ ] 
Thanks, Pascale

**Comment by raymond91125** [comment]
@pgaudet If I'm understanding it correctly, you're requesting to obsolete beta-glucoside transport, with replaced_by cellobiose transport (0 child/0 annotation). But cellubiose is a sub type of beta-glucoside and GO_0015759 has child classes that have annotations. Wouldn't it make more sense to make cellulose transport IS_A beta-glucoside transport? Or perhaps obsolete cellulose transport, replaced_by beta-glucoside transport. Same arguments apply to three other similar pairs.
For allose vs D-allose, I posit it is D-allose terms that we keep.

**Comment by pgaudet** [comment]
Hi @raymond91125 

In fact I have been trying to figure out what is beta-glucoside; it is not in the ChEBI 7.3 list. It seems a grouping class that we may not need. ChEBI has no definition but wikipedia states "A glucoside is a glycoside that is chemically derived from glucose."; we dont group chemicals by what they derive form in GO. Maybe the better solution would be to obsolete the terms that mention  beta-glucoside. Or do you have another solution to propose? 

Thanks, Pascale

**Comment by raymond91125** [comment]
β-D-glucoside https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:22798 **It is in chebi_ph7_3**
We should change beta-glucoside to beta-D-glucoside used in LDs.

(cellobiose https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:17057 It looks like ia β-D-glucoside but not so classified in Chebi.)

**Comment by pgaudet** [comment]
Good point, thanks for finding this one. 

However β-D-glucoside https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:22798 (and derivatives) represent a group, not a chemical. It beta-glucoside an appropriate substrate for a transport/metabolic reaction? 
- in transport, it is not used, so I would still obsolete this as an unnecessary grouping term. 
- for biosynthesis/catabolism: it's only used for catabolism, and looking at the annotation, it seems that what is being described is really the MF, ie which bond is being cleaved, rather than which compound is hydrolyzed. 
Again I would be tempted to obsolete the metabolic process terms. 


Thanks, Pascale

**Comment by raymond91125** [comment]
If we obsolete beta-glucoside terms, I think we should merge up to the parent term, like  GO:0042946 glucoside transport rather than to that of cellobiose.

**Comment by raymond91125** [comment]
> * for biosynthesis/catabolism: it's only used for catabolism, and looking at the annotation, it seems that what is being described is really the MF, ie which bond is being cleaved, rather than which compound is hydrolyzed.
>       Again I would be tempted to obsolete the metabolic process terms.

In GO hierarchy, there is no relationship between GO:0008422 beta-glucosidase activity and a BP. My guess is that curators wanted to have the gene connected to both branches and can only do so by direct annotations. beta-glucosidase works on many different substrates (e.g. https://biocyc.org/META/substring-search?type=NIL&object=3.2.1.21#REACTION) thus there may be a value to keep beta-glucoside catabolic process even as a grouping term. Or is this value not worth it? Thanks.

**Comment by pgaudet** [comment]
We would need to look into this more closely. It looks like all descendent terms have a better, more informative parent. We might be better off without these 'chemical groups' grouping terms. 

We can fix the ChEBI to β-D-glucoside https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:22798  and close this for now. 

Thanks, Pascale

**Comment by raymond91125** [comment]
> We can fix the ChEBI to β-D-glucoside https://www.ebi.ac.uk/chebi/chebiOntology.do?chebiId=CHEBI:22798 and close this for now.

That has been done. https://github.com/geneontology/go-ontology/commit/48dba3fffce8e17156f0ce6d129a4b890858fb4e

Thanks.
