### ISSUE TITLE
NTR: [UFM1 ligase-substrate adaptor activity] [UFM1 modified protein reader activity]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#27325]
Hi GO,

I would need a couple of terms related to ufmylation in order to make a complete model of ufmylation in GO CAM.

Please note that I also propose to modify the definition of GO:0140030 modification-dependent protein binding and child terms. The current name and definition is not relevant in my opinion; proteins that recognize and bind modified proteins should be considered as readers of modifications.

Thanks

Sylvain

1) 
Name: UFM1 ligase-substrate adaptor activity
Category: Molecular function
Definition: The binding activity of a molecule that brings together a UFM1 ligase and its substrate.

child of GO:0140767 enzyme-substrate adaptor activity
PubMed=38383785
PubMed=36121123

2)
Name: UFM1 modified protein reader activity
Category: Molecular function
Definition:
A protein that recognizes and binds a target protein modified by UFM1.
child of GO:0140035 ubiquitination-like modification-dependent protein binding (please see below for propositions to change name and definitions of related terms)

PubMed=38383785
PubMed=38383789
PubMed=32537488
PubMed=36848233

3) As explained above, I think we should reformulate the name and definition of protein modification readers

FROM:
GO:0140030 modification-dependent protein binding
TO:
Modified protein reader activity
FROM:
Binding to a protein upon post-translation modification of the target protein.
TO:
Binding to a protein upon post-translation modification of the target protein.

It would be good to change all child terms of GO:0140030 (i.e. GO:0140034, GO:0140035 etc.)

FROM:
GO:0140034 methylation-dependent protein binding
TO:
Methylated protein reader activity
FROM:
Binding to a protein upon methylation of the target protein.
TO:
A protein that recognizes and binds a target protein modified by methylation.

FROM:
GO:0140033 acetylation-dependent protein binding
TO:
Acetylated protein reader activity
FROM:
Binding to a protein upon acetylation of the target protein.
TO:
A protein that recognizes and binds a target protein modified by acetylation.

FROM:
GO:0140035 ubiquitination-like modification-dependent protein binding
TO:
Ubiquitin-like modified protein reader activity
FROM:
Binding to a protein upon modification by a ubiquitin-like protein of the target protein.
TO:
A protein that recognizes and binds a target protein modified by a ubiquitin-like.

etc. etc.

**Comment by pgaudet** [comment]
@sylvainpoux I will need your help for the larger proposal of modification-dependent protein binding. I made a spreadsheet with all annotations to 
GO:0140035 ubiquitination-like modification-dependent protein binding
GO:0140037 sumo-dependent protein binding
GO:0140036 ubiquitin-dependent protein binding

See https://docs.google.com/spreadsheets/d/18dk19bOMaRqBYBmsAde6_mWQCPxA4Y39RVgwbHlO57Q/edit#gid=0

Most are Uniprot; could you review them (at least the UniProt; I can do the others) and confirm that it would be consistent with the renaming of the terms to 'reader activity? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Change labels, definition and parents for 

**GO:0140035 ubiquitination-like modification-dependent protein binding**
- changed label to ubiquitin-like protein reader activity
- changed definition from  "Binding to a protein upon modification by a ubiquitin-like protein of the target protein." [PMID:26060076] to: 
+def: "A molecular adaptor that recognizes and binds a target protein containing a ubiquitin-like modification and that brings the target protein into contact with another protein to allow those proteins to function in a coordinated way." 
- changed parent to is_a: GO:0030674 ! protein-macromolecule adaptor activity

**GO:0140037 sumo-dependent protein binding**
- changed label to SUMO-modified protein reader activity
- changed definition to "A molecular adaptor that recognizes and binds a target protein containing a SUMO modification and that brings the target protein into contact with another protein to allow those proteins to function in a coordinated way."

**GO:0141185  UFM1-modified protein reader activity**
 namespace: molecular_function
- changed definition to "A molecular adaptor recognizes and binds a target protein containing a UFM1 modification and brings the target protein into contact with another protein to allow those proteins to function in a coordinated way." [PMID:32537488,

**GO:0140036 ubiquitin-dependent protein binding**
- changed label to ubiquitin-modified protein reader activity
- changed definition to "A molecular adaptor recognizes and binds a target protein containing a ubiquitination modification and brings the target protein into contact with another protein to allow those proteins to function in a coordinated way."

**GO:0061649 ubiquitin modification-dependent histone binding**
- changed label to  ubiquitin-modified histone reader activity
- changed definition to : "A molecular adaptor that recognizes and binds a histone protein containing a ubiquitination modification and that brings the target protein into contact with another protein to allow those proteins to function in a coordinated way." [GOC:dph, PMID:24526689]

@sylvainpoux please let me know if you spot anything that should be changed. 

Thanks, Pascale
