### ISSUE TITLE
glucose transmembrane transporter relationships

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27326]
Something not quite right here:

id: GO:0005355
name: glucose transmembrane transporter activity
def: "Enables the transfer of the hexose monosaccharide glucose from one side of a membrane to the other." [GOC:ai, GOC:mtg_transport, ISBN:0815340729]
intersection_of: GO:0022857 ! transmembrane transporter activity
intersection_of: has_primary_input CHEBI:4167 ! D-glucopyranose
relationship: part_of GO:1904659 ! glucose transmembrane transport

id: GO:0055056
name: D-glucose transmembrane transporter activity
def: "Enables the transfer of the D-enantiomer of the hexose monosaccharide glucose from one side of a membrane to the other." [GOC:jid, GOC:jsg, GOC:mah]
intersection_of: GO:0022857 ! transmembrane transporter activity
intersection_of: has_primary_input CHEBI:17634 ! D-glucose

This ends up with up this inferred hierarchy in GO:
```
hexose transmembrane transporter activity
       |__D-glucose transmembrane transporter activity
           |__glucose transmembrane transporter activity
```
when, from the names/defs, the two glucose terms should have the opposite parent-child relations?

Looks like the 'has_primary_input' on 'GO:0005355 glucose transmembrane transporter activity' should be changed to 'CHEBI:17234 = glucose' (https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17234).

CHEBI has this hierarchy:
```
[CHEBI:17234 glucose]
    |_[CHEBI:17634 D-glucose]
        |_[CHEBI:4167 D-glucopyranose]
```

(I guess the alternative explanation is that 'GO:0005355 glucose transmembrane transporter activity' really is referring to 'D-glucopyranose', in which case the GO name and def need changing to reflect that.)

**Comment by sjm41** [comment]
From ontology call (18th march) - 
CHEBI:17234 glucose was intentionally replaced with CHEBI:4167 D-glucopyranose
(see https://docs.google.com/spreadsheets/d/196YJakCj77UmQklmNb5WpE2i-8PCVxHpFd587G6JceM/edit#gid=0)

But the two terms above still have the parent-child relationship the wrong way round.

**Comment by pgaudet** [comment]
L-glucose doesn't seem to be physiologically relevant: https://en.wikipedia.org/wiki/L-Glucose
should we merge this into the D-glucose term?

**Comment by sjm41** [comment]
Merging GO:0005355 and GO:0055056 sounds good.
Keeping "has_primary_input CHEBI:17634 ! D-glucose" (rather than the more specific CHEBI:4167 D-glucopyranose)?

**Comment by pgaudet** [comment]
The problem with CHEBI:17634 ! D-glucose is that it's the the ph7.3 form, so this is not aligned with RHEA. 

What would be useful would be to implement the UniProt synonyms, see 
https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:4167

**Comment by deustp01** [comment]
> The problem with CHEBI:17634 ! D-glucose is that it's the the ph7.3 form

Something odd here - common monosaccharides, like glucose, don't ionize at anything like physiological pH, certainly not pH 7.3, so they don't have predominant pH 7.3 states (as opposed to phosphorylated monosaccharides, which do)

**Comment by pgaudet** [comment]
This is a question for RHEA

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0005355 glucose transmembrane transporter activity & replace it by the more specific GO:0055056 D-glucose transmembrane transporter activity. The reason for obsoletion is that L-glucose has no known physiological role, so the parent term is unnecessary, as we are not planning a term for L-glucose transport. 

There are 72 EXP annotations, most will be automatically replaced, exceptof r some CGD and GeneDB, see https://github.com/geneontology/go-annotation/issues/5143
There are also 6 InterPro mappings, 1 UniRule and 2 Reactome. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/27326

**Comment by pgaudet** [comment]
Also change labels for the regulation terms: 

'regulation of glucose transmembrane transport'
'negative regulation of glucose transmembrane transport'
'positive regulation of glucose transmembrane transport'

'regulation of glucose import'
'negative regulation of glucose import'
'positive regulation of glucose import'

**Comment by pgaudet** [comment]
ah OK - thanks @deustp01 !

**Comment by pgaudet** [comment]
Also obsolete: GO:0005356 glucose:proton symporter activity, replace by [GO:0055055 D-glucose:proton symporter activity](https://amigo.geneontology.org/amigo/term/GO:0055055#display-lineage-tab), which oddly, is the parent. All annotations are UniProt - will be automatically updated.

**Comment by ValWood** [comment]
in these cases
GO:0005356 glucose:proton symporter activity, replace by [GO:0055055 D-glucose:proton symporter activity](https://amigo.geneontology.org/amigo/term/GO:0055055#display-lineage-tab),

if the *intent* was D-glucose, can't you just rename?

**Comment by pgaudet** [comment]
@ValWood I cannot rename because we end up with 2 identical terms
- [GO:0055055 D-glucose:proton symporter activity](https://amigo.geneontology.org/amigo/term/GO:0055055#display-lineage-tab)
- GO:0005356 glucose:proton symporter activity
