### ISSUE TITLE
GO:0015117 thiosulfate transmembrane transporter activity - which CHEBI?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27324]
We noticed that the QuickGO page for [GO:0015117 thiosulfate transmembrane transporter activity](https://www.ebi.ac.uk/QuickGO/term/GO:0015117) lists two different CHEBI IDs in the 'Cross-ontology relations' section 

Relation | Other Ontology | ID | Term
-- | -- | -- | --
has_participant | CHEBI | CHEBI:33542 | trioxidosulfanidosulfate(1-)
has_primary_input | CHEBI | CHEBI:26977 | thiosulfate

This is how the term looks in go-edit.obo:
```
id: GO:0015117
name: thiosulfate transmembrane transporter activity
namespace: molecular_function
def: "Enables the transfer of thiosulfate ions, S2O3(2-), from one side of a membrane to the other." [GOC:ai]
synonym: "thiosulfate permease activity" RELATED []
synonym: "thiosulphate transporter activity" EXACT []
xref: MetaCyc:TRANS-RXN-496
xref: RHEA:32807
intersection_of: GO:0022857 ! transmembrane transporter activity
intersection_of: has_primary_input CHEBI:26977 ! thiosulfate
relationship: part_of GO:0015709 ! thiosulfate transport
```

And RHEA:32807 is:
`
thiosulfate(in) = thiosulfate(out)
`
(where 'thiosulfate' here = CHEBI:33542 = trioxidosulfanidosulfate(1−)

My understanding is that the 'has_primary_input CHEBI:26977 thiosulfate' statement is a manually asserted statement made by the GO editor, while the 'has_participant CHEBI:33542 | trioxidosulfanidosulfate(1-)' is pulled in from the RHEA xref.
is that correct?

The immediate question here is, which CHEBI is correct?:
- the 'has_primary_input' statement, specifying CHEBI:26977 = thiosulfate 
- the RHEA xref, specifying CHEBI:33542 = trioxidosulfanidosulfate(1−)
- or the GO def specifying "thiosulfate ions, S2O3(2-)", which is a third chemical, CHEBI:16094 = thiosulfate(2−)

I'm guessing RHEA is correct (i.e. that the form that is found at pH 7.3), and the GO term 'primary input' and def need updating?

The wider question here is do we have a QC check to check for mismatches between the CHEBI(s) specified as a 'has_primary_input' and the CHEBI(s) specified via the RHEA xref (if present)?  If not, it might be instructive to add this check?

@rozaru

**Comment by balhoff** [comment]
CHEBI:26977 (thiosulfate) seems to be one of those terms in #27059 that don't have a pH 7.3 mapping, and so aren't blocked from usage.

**Comment by deustp01** [comment]
But it has at least three different charge states:
thiosulfate(2−) ([CHEBI:16094](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A16094)) is conjugate base of thiosulfate(1−) ([CHEBI:33541](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A33541)) is conjugate base of thiosulfuric acid ([CHEBI:33540](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A33540))
so we need to know what the predomina t microspecies at pH 7.3 is, and, perhaps, get that useful information propagated into the ChEBI entry for that species. Alan Bridge and Ralf Stephan, whose GitHub tags I have forgotten, would be helpful here.

**Comment by sjm41** [comment]
From ontology call (18th march) - 
CHEBI:33542 | trioxidosulfanidosulfate(1-) is the one in use by UniProt, so is the pH 7.3 form.
So we should change the GO term def and logical def to match that.

**Comment by pgaudet** [comment]
Maybe ask ChEBI to the synonyms  ?

**Comment by cmungall** [comment]
@sjm41:

>  Though looking again now, I notice that it's CHEBI:16094 = thiosulfate(2−) that has most of the synonyms (from KEGG, IUPAC, PDBeChem) and it's the only one of the 3 terms mentioned here that is annotated with "has role human metabolite"...

I believe that this is pretty arbitrary, just as it is that the -2 form has the text definition and the exact synonym "thiosulfate", whereas the -1 one has no definition and a related synonym "thiosulfate"

I asked if there was any reason here:
https://github.com/ebi-chebi/ChEBI/issues/4492

**Comment by sjm41** [comment]
Thanks @cmungall. I have contacted CHEBI twice about this via their website help form, but without reply.
I suspect you're right about how the synonyms/xrefs are distributed - I was more influenced by the fact that CHEBI annotates CHEBI:16094 = thiosulfate(2−)as "has role human metabolite". In theory, that label should apply to the pH 7.3 form, no?

**Comment by alanbridge** [comment]
Hi all, 

I suspect that the assignment of roles may occur to any charge state, and as ChEBI is used to identify metabolites in metabolomics data in MetaboLights too, these roles might also be derived from or influenced by the data in that resource, though Adnan could confirm that. 

The pH 7.3 form of this metabolite (i.e. CHEBI:33542) could be assigned the role of "human metabolite" too (as revealed by this search in UniProt):

https://www.uniprot.org/uniprotkb?query=%28cc_catalytic_activity%3A%22CHEBI%3A33542%22%29&facets=reviewed%3Atrue%2Cmodel_organism%3A9606

I don't know how the roles are derived in ChEBI, whether by curation or by sourcing annotations from resources like MetaboLights (that uses ChEBI as a base) or a knowledgebase like UniProt (leveraging Rhea annotations). If it is the former then it may be very difficult for ChEBI to keep up.

Hope that helps, Alan

**Comment by amalik01** [comment]
Hi, 

Esters of thiosulfuric acid are also called 'thiosulfates'. You can remove CHEBI:26977 from the quickGO page as this is the entry for the esters of thiosulfuric acid. CHEBI:33542 is the major microspecies at pH 7.3 according to Marvin pKa predictor hence this is the entry you should be using.

**Comment by sjm41** [comment]
Thanks @amalik01 !  I'll update the GO textual and logical defs to use CHEBI:33542.

**Comment by sjm41** [comment]
@balhoff @cmungall I still think it would be good to have a check for mismatches between CHEBI IDs listed in the LD vs the 'has_participant' (via RHEA), at least for transporters - i.e. check that chemical given in the LD is found among the has_participants list. (I just stumbled across another mismatch in GO:0015446.)
If you agree, shall I make a separate ticket for that?
