### ISSUE TITLE
Clarify use of YAML files in src/ontology/subsets

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#27336]
@cmungall @balhoff We were looking at the contents of src/ontology/subsets and were hoping for a little clarification on the use of the YAML files here.

During the build process, OBO, TSV, OWL, etc files are created for the subsets. It looks like the YAML files are after-(before?)-the-fact descriptions of the subsets. Is this true? Also, is the reason these are separate that this data is hard to store directly in the ontology?

Tagging @pgaudet

**Comment by kltm** [comment]
Naturally, we'll document what we "find" above.

**Comment by pgaudet** [comment]
@kltm Can this be closed ?
