### ISSUE TITLE
request to modify a GO-term label  (GO:0005220)

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#27339]
Hi,
I would like that you modify a GO  term label  to a one more appropriate.
From:
inositol 1,4,5-trisphosphate-sensitive calcium-release channel activity (GO:0005220)
To:
inositol 1,4,5-trisphosphate gated calcium channel activity (GO:0005220)

and add inositol 1,4,5-trisphosphate-sensitive calcium-release channel activity as a synonym
Many thanks
Guilaine

**Comment by raymond91125** [comment]
Is "inositol-1,4,5-trisphosphate receptor activity" a better term label?

**Comment by Argoudpuy** [comment]
@raymond91125 
I think no, because its molecular function corresponds to a channel activity and not to a  receptor activity, 
It is a channel that opens when inositol 1,4,5-trisphosphate (IP3) is bound, leading to calcium release.
So I think that inositol 1,4,5-trisphosphate gated calcium channel activity would be more appropriate and more coherent with the the parent term intracellularly gated calcium channel activity.
I suggest to keep the definition and to add a new recent paper, PMID: 28416699 to replace PMID:8660280.
I hope that helps.
Guilaine

**Comment by pgaudet** [comment]
Hi @raymond91125 

To be consistent with other terms, the label should have a hyphen before "gated" 

Thanks, Pascale

**Comment by raymond91125** [comment]
Done. Thanks.
