### ISSUE TITLE
Glycophagy GO term 

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#27333]
Hello,

I was looking a the GO term glycophagy (GO:0061723) -The selective degradation of glycogen by macroautophagy- and I was wondering why the relationship - is a GO:0005980 (glycogen catabolic process)- has been deleted?

glycogen catabolic process definition:
The chemical reactions and pathways resulting in the breakdown of glycogen, a polydisperse, highly branched glucan composed of chains of D-glucose residues.

Thank you

Rossana

**Comment by pgaudet** [comment]
@ValWood Did you change this ? The date of this change (Oct 2023, see https://www.ebi.ac.uk/QuickGO/term/GO:0061723) corresponds to the time when you were working on this. 

Can we restore this relation?

**Comment by ValWood** [comment]
It was clearly me, but I don't know why it was deleted, I'll reinstate it.

**Comment by pgaudet** [comment]
Thanks !
