### ISSUE TITLE
Write documentation for rolling builds of the ontology

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27344]
https://wiki.geneontology.org/Daily_version_of_the_Gene_Ontology

**Comment by pgaudet** [comment]
@kltm Can you please have a look and let me know if this is what you were looking for? 
It seems short, but I'm not sure what else to add.

**Comment by kltm** [comment]
Okay, I think it might be good to touch bases on this again, as I think both the words "daily" and "version" are misleading at best. It's important here to pass on the right understanding of what this is to prevent confusion, both internally and externally. Shouldn't this be with the rest of the pipeline/snapshot/release info? For my take on it, I have something here: https://github.com/geneontology/pipeline?tab=readme-ov-file#functional-branches

**Comment by pgaudet** [comment]
this has been addressed
