### ISSUE TITLE
Update EC on GO:0002950 ceramide phosphoethanolamine synthase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27352]
id: GO:0002950
name: ceramide phosphoethanolamine synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: CDP-ethanolamine + a ceramide = CMP + a ceramide phosphoethanolamine." [EC:2.7.8.n3, PMID:25667419]
xref: EC:2.7.8.n3
is_a: GO:0016780 ! phosphotransferase activity, for other substituted phosphate groups
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/23370" xsd:anyURI
created_by: hjd
creation_date: 2016-08-16T13:41:21Z

 EC:2.7.8.n3 has been transferred to EC 2.7.8.48

- [x] update dbxref
- [x] update def xref
- [ ] add RHEA:45892 as narrowMatch xref
- [x] add RHEA:45896 as exactMatch xref
- [x] update GO def to match EC/RHEA

**Comment by alanbridge** [comment]
45892 looks like a narrow match, as the base is specified (unlike in GO:0002950)

an N-acylsphing-4-enine + CDP-ethanolamine = an N-acylsphing-4-enine 1-phosphoethanolamine + CMP + H(+)

but 45896 looks like an exact match to GO:0002950 as the base isn't specified

an N-acyl-sphingoid base + CDP-ethanolamine = an N-acyl-sphingoid 1-phosphoethanolamine + CMP + H(+)

the latter seems to match exactly the EC definition too

**Comment by sjm41** [comment]
Thanks @alanbridge . I agree, which makes me realise the GO def should be updated to match EC/RHEA too.
