### ISSUE TITLE
xrefs for GO:1990698 palmitoleoyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27365]
id: GO:1990698
name: palmitoleoyltransferase activity
namespace: molecular_function
def: "Catalysis of the transfer of a palmitoleyl group, a 16-carbon monounsaturated fatty acid (C16:1), to an acceptor molecule." [PMID:17141155, PMID:25731175]
is_a: GO:0016747 ! acyltransferase activity, transferring groups other than amino-acyl groups
created_by: sp
creation_date: 2015-03-13T08:58:25Z

Add these as narrowMatch xrefs:
EC:2.3.1.250 [Wnt protein] O-palmitoleoyl transferase
RHEA:45336

**Comment by pgaudet** [comment]
@sjm41 I think you want these xrefs on the more specific GO term [O-palmitoyltransferase activity](http://purl.obolibrary.org/obo/GO_0016416)

**Comment by sjm41** [comment]
Yes, I think you're right.
But I see I missed this because "GO:1990698 palmitoleoyltransferase activity" has no children terms, and is maybe the same as the parent to the O-palmitoyltransferase activity term you suggest!  That is:

id: GO:0016409
name: palmitoyltransferase activity
namespace: molecular_function
def: "Catalysis of the transfer of a palmitoyl (CH3-[CH2]14-CO-) group to an acceptor molecule." [GOC:ai]
is_a: GO:0016747 ! acyltransferase activity, transferring groups other than amino-acyl groups


??

**Comment by sjm41** [comment]
Looking at this again...I see that "**palmitoleoyl**transferase activity" is different from "**palmitoyl**transferase activity".

Chemically:
palmitoleoyl group: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:25837
palmitoyl group: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:45021

And I see there's a caution comment on the top of the UniProt page for human PORCN (Q9H237) that says:
_Was initially thought to mediate **palmitoylation** of Wnt proteins (PubMed:[24292069](https://www.uniprot.org/citations/24292069)).
It was later shown that instead it acts as a serine O-**palmitoleoyl**transferase that mediates the attachment of palmitoleate, a 16-carbon monounsaturated fatty acid (C16:1), to Wnt proteins_

So, it's correct to add these 2 narrowMatch xrefs to GO:1990698 **palmitoleoyl**transferase activity:
EC:2.3.1.250 [Wnt protein] O-palmitoleoyl transferase
RHEA:45336 (9Z)-hexadecenoyl-CoA + [Wnt protein]-L-serine = [Wnt protein]-O-(9Z)-hexadecenoyl-L-serine + CoA

Also, I see there's a typo in the def of GO:1990698: "palmitoleyl" should be "palmitoleoyl".


I expect this subtle difference in the term name may have caused some annotation confusion.  I think a comment on each term might help a bit, something like "Do not confuse with XXX".

E.g. GO:1990698 palmitoleoyltransferase activity has just 2 annotations, to mouse Cpt1a and Porcn. I think the annotation to Cpt1a should be changed to GO:0004095 carnitine O-palmitoyltransferase activity. - I've disputed this in P2GO (it's a UP annotation).

E.g. Fly por is currently annotated to GO:0016409 palmitoyltransferase activity - this should be changed to GO:1990698 palmitoleoyltransferase activity - I'll sort this out.
