### ISSUE TITLE
NTR: somatic muscle attachment to cuticle

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#27368]
* **Suggested term label:**
* somatic muscle attachment to chitin-containing cuticle

* **Definition (free text)**
* The developmental process in which a somatic muscle attaches the cuticle. In insects, this may occur via a specialized epithelial cell adherence to the chitinous extracellular matrix and to muscle cells through their basement membrane. 

* **Reference, in format PMID:#######**
* PMID:35675426

* **Gene product name and ID to be annotated to this term**
Chitin deacetylase 1
UniProt:A7U8C9

* **Parent term(s)**
*  GO:0007525 somatic muscle development

* **Any other information**

Only in taxon: Taxonomy ID: 6656

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160175
+name: somatic muscle attachment to chitin-based cuticle
+namespace: biological_process
+def: "The developmental process in which a somatic muscle attaches to the chitin-based cuticle. In insects, this may occur via a specialized epithelial cell adherence to the chitinous extracellular matrix and to muscle cells through their basement membrane." [PMID:35675426]
+is_a: GO:0007525 ! somatic muscle development
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27368" xsd:anyURI
+created_by: rynl
+creation_date: 2024-03-22T23:14:08Z
