### ISSUE TITLE
NTR: cortical rotation

### ISSUE THREAD

**Issue by Xenbase22** [geneontology/go-ontology#27366]
Please provide as much information as you can: 

* **Suggested term label:**
cortical rotation

* **Definition (free text)**
A process by which the cortical layer of an oocyte/egg's cytoplasm rotates with respect to the deeper layers of an oocyte/eggs cytoplasm. In amphibian eggs, the cortical layer rotates c. 30o [degrees] with respect to the heavier, deeper yolk so that the cortex moves towards the animal pole on the dorsal side.
(or something like this) 

* **Reference, in format PMID:#######**
PMID:37983969 
Azbazdar and De Robertis 2024 The early dorsal signal in vertebrate embryos requires endolysosomal membrane trafficking. Bioessays 2024 Jan 01;461:e2300179. doi: 10.1002/bies.202300179.
Also:
PMID: 1879356
PMID: 332452
PMID: 24798204
PMID: 9037034
PMID: 3289985
PMID: 332453

* **Gene product name and ID to be annotated to this term**

ctnnb1.L Xenopus Gene ID:399274(http://www.ncbi.nlm.nih.gov/entrez/query.fcgi?db=gene&cmd=Retrieve&dopt=full_report&list_uids=399274). (Xenbase:XB-GENE-6254184)

* **Parent term(s)**
GO: BP
GO_0030866: cortical actin cytoskeleton organization

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
Add fish PMID:22949618 and worm PMID:25077289 references. IS_A GO:0048869 cellular developmental process.

**Comment by raymond91125** [comment]
[Term]
id: GO:0160174
name: cortical rotation
namespace: biological_process
def: "A cellular developmental process by which the outer layer of the cell (the cortex) rotates relative to the inner cytoplasm." [PMID:22949618, PMID:25077289, PMID:37983969]
is_a: GO:0048869 ! cellular developmental process
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27366" xsd:anyURI
created_by: rynl
creation_date: 2024-03-22T21:44:06Z
