### ISSUE TITLE
test ontobot  GO:0016043 to subset gocheck_do_not_annotate

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27371]
Hey ontobot! apply:

- add GO:0016043 to subset gocheck_do_not_annotate

Fixes https://github.com/geneontology/go-ontology/issues/27194

(4 EXP, 339 IEA)

**Comment by ValWood** [comment]
The Go do_not_annotate subset did not appear in the ontology? @pgaudet

**Comment by ValWood** [comment]
Do you know what I did wrong?

**Comment by pgaudet** [comment]
This looks right to me 

<img width="1048" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/d24f9f33-29aa-417e-b60a-0d77570b91af">

**Comment by pgaudet** [comment]
Maybe you did not 'git pull' on your local copy?

**Comment by ValWood** [comment]
Yes, it's there...
