### ISSUE TITLE
NTR: positive regulation of autophagosome-lysosome fusion

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#27376]
* **Suggested term label:**
* positive regulation of autophagosome-lysosome fusion

* **Definition (free text)**
Any process that activates or increases the rate which autophagosomes fuse with a vacuole (yeast) or lysosome (e.g. mammals and insects).

* **Reference, in format PMID:#######**
PMID:38360932

* **Gene product name and ID to be annotated to this term**
FBgn0029911, detr

* **Parent term(s)**
GO:0061909 autophagosome-lysosome fusion

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160177
+name: positive regulation of autophagosome-lysosome fusion
+namespace: biological_process
+def: "Any process that activates or increases the rate which autophagosomes fuse with a vacuole (yeast) or lysosome (e.g. mammals and insects)." [PMID:38360932]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0061909 ! autophagosome-lysosome fusion
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27376" xsd:anyURI
+created_by: rynl
+creation_date: 2024-03-27T22:51:49Z
