### ISSUE TITLE
GO:0001734  mRNA (N6-adenosine)-methyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27389]
id: GO:0001734
name: mRNA (N6-adenosine)-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + RRACH = S-adenosyl-L-homocysteine + RRm6ACH; R is a purine, and H is C, A, or U." [GOC:hjd]
is_a: GO:0008174 ! mRNA methyltransferase activity

This corresponds to EC:2.1.1.348:
EC 2.1.1.348
Accepted Name: mRNA m(6)A methyltransferase
Reaction catalysed: an adenosine in mRNA + S-adenosyl-L-methionine <=> an N(6)-methyladenosine in mRNA + H(+) + S-adenosyl-L-homocysteine
Comment(s): This enzyme, found in eukaryotes, methylates adenines in mRNA with the consensus sequence RRACH.

- [x] add  EC:2.1.1.348 xref
- [x] also add RHEA:55584 and MetaCyc:RXN-19346 xrefs
- [x] Change def to match EC/RHEA, and include EC comment in def.
- [x] Change GO name to match EC

**Comment by sjm41** [comment]
@pgaudet According to the EC comment, this term should have a taxon constraint of 'only in eukaryotes'. Would you be able to take care of that point?

**Comment by pgaudet** [comment]
Is the mRNA nomenclature different from the tRNA nomenclature? 

See [tRNA (adenine(9)-N1)-methyltransferase activity](http://purl.obolibrary.org/obo/GO_0160106) and 
https://enzyme.expasy.org/EC/2.1.1.218

**Comment by pgaudet** [comment]
TC added.

**Comment by kaxelsen** [comment]
There are two things at play here, numbering of the atoms in the single nucleotides and numbering of the nucleotides in the RNA chain:
m(6)A means methylation at position 6 in adenine. This is (of course) the same for all A's whether they are found in RNA or DNA. LIkewise for m(1)A.
Regarding the numbering of the different RNA chains there is a crucial difference. For tRNA's there is a unified numbering system, so all tRNA species have the same numbers, e.g. the anticodon loop is always position 32-34. You can see more about this in Sprinzl et al. (1998), https://academic.oup.com/nar/article/26/1/148/2376733
Contrary to this, rRNA, mRNA etc have no unified numbering so position 1026 is human 26S rRNA is not the same in yeast or sometimes not even in mouse.
An example is EC 2.1.1.260. The comment states: "It recognizes Ψ914 in 16S rRNA from the archaeon Methanocaldococcus jannaschii, Ψ1191 in yeast 18S rRNA, and Ψ1248 in human 18S rRNA."

So, in Rhea, we try to always have a generic reaction for rRNA substrates so we can use the same reaction for all species, as for example the reaction for EC 2.1.1.260 actually only is valid for the yeast entry.
