### ISSUE TITLE
GO:0019010 farnesoic acid O-methyltransferase activity & GO:0035049 juvenile hormone acid methyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27388]
These two entries both correspond to EC:2.1.1.325 and need a few additions.

id: GO:0019010
name: farnesoic acid O-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: farnesoic acid + S-adenosyl-methionine = methyl farnesoate + S-adenosyl-L-homocysteine." [PMID:12135499]
synonym: "S-adenosyl-methionine:farnesoic acid O-methyltransferase activity" EXACT []
is_a: GO:0008171 ! O-methyltransferase activity
is_a: GO:0008757 ! S-adenosylmethionine-dependent methyltransferase activity
=> EXP ANNOTATIONS TO Q9FYC4/FAMT, Q767F1/JHAMT, Q9VJK8/jhamt

- [x] add MetaCyc:RXN-11587 and RHEA:43700 xrefs
- [x] add EC:2.1.1.325 as broadMatch xref
- [ ] change def to match RHEA: (2E,6E)-farnesoate + S-adenosyl-L-methionine = methyl (2E,6E)-farnesoate + S-adenosyl-L-homocysteine

id: GO:0035049
name: juvenile hormone acid methyltransferase activity
namespace: molecular_function
def: "Catalysis of the transfer of a methyl group to juvenile hormone acid." [GOC:bf]
is_a: GO:0008168 ! methyltransferase activity
=> EXP ANNOTATIONS TO Q767F1/JHAMT, Q9VJK8/jhamt

- [x] add MetaCyc:RXN-11771 and RHEA:43720 xrefs
- [x] add EC:2.1.1.325 as broadMatch xref
- [ ] change def to match RHEA: juvenile hormone III carboxylate + S-adenosyl-L-methionine = juvenile hormone III + S-adenosyl-L-homocysteine
- [ ] add "juvenile hormone-III synthase" as exact synonym from EC
- [x] add PMID:14530389] and PMID:18549957 as def xrefs
- [ ] change parent to is_a: GO:0008171 ! O-methyltransferase activity & GO:0008757 ! S-adenosylmethionine-dependent methyltransferase activity

---
Here's the EC info for the record:

EC:2.1.1.325
NAME: juvenile hormone-III synthase
ALT_NAMES: farnesoic acid methyltransferase, juvenile hormone acid methyltransferase
REACTIONS:
- (2E,6E)-farnesoate + S-adenosyl-L-methionine <=> methyl (2E,6E)-farnesoate + S-adenosyl-L-homocysteine
- juvenile hormone III carboxylate + S-adenosyl-L-methionine <=> juvenile hormone III + S-adenosyl-L-homocysteine
ANNOTATED TO:
- Q9FYC4, FAMT_ARATH
- Q767F1, JHAMT_BOMMO
- Q9VJK8, JHAMT_DROME

**Comment by sjm41** [comment]
@pgaudet Or would it be better to merge these two entries, since no enzyme is known that does one activity but not the other?

**Comment by pgaudet** [comment]
Merging makes sense, and aligning with EC, ie renaming the term 'juvenile hormone-III synthase ' 

Which term do you think we should merge into the other? (ie we'd keep one term, and obsolete the other with a 'replaced by' the term we keep). 

Thanks, Pascale

**Comment by sjm41** [comment]
OK, let's merge. Which means I'll have to reassign this to you....
I don't think it matters which term is kept, but we could choose GO:0019010 given it has slightly more current annotations.

**Comment by pgaudet** [comment]
Merged terms, added EC, RHEAs, KEGGs and MetaCyc xrefs

 **id: GO:0019010 farnesoic acid O-methyltransferase activity**
-old def: "Catalysis of the reaction: farnesoic acid + S-adenosyl-methionine = methyl farnesoate + S-adenosyl-L-homocysteine." [PMID:12135499]
+new def: "Catalysis of the reaction: (2E,6E)-farnesoate + S-adenosyl-L-methionine = methyl (2E,6E)-farnesoate + S-adenosyl-L-homocysteine. Also converts juvenile hormone III carboxylate into juvenile hormone-III." [EC:2.1.1.325, PMID:12135499, PMID:14530389, PMID:18549957]
**Added synonyms:** 
+synonym: "juvenile hormone acid methyltransferase activity" EXACT []
+synonym: "juvenile hormone-III synthase activity" EXACT []

**Added xrefs:**
+xref: EC:2.1.1.325 {source="skos:exactMatch"}
+xref: KEGG_REACTION:R08147 {source="skos:narrowMatch"}
+xref: KEGG_REACTION:R08151 {source="skos:narrowMatch"}
+xref: MetaCyc:RXN-11587 {source="skos:narrowMatch"}
+xref: MetaCyc:RXN-11771 {source="skos:narrowMatch"}
+xref: RHEA:43700 {source="skos:narrowMatch"}
+xref: RHEA:43720 {source="skos:narrowMatch"}
