### ISSUE TITLE
Obsoletion request: unnecessary grouping terms

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27386]
- [x] 'organic substance biosynthetic process' http://purl.obolibrary.org/obo/GO_1901576

- [x] 'organic substance catabolic process' http://purl.obolibrary.org/obo/GO_1901575

- [x] 'organic substance metabolic process' http://purl.obolibrary.org/obo/GO_0071704
- [x] 'organic substance transport' http://purl.obolibrary.org/obo/GO_0071702
- [x] 'response to organic substance' http://purl.obolibrary.org/obo/GO_0010033
- [x] 'detection of organic substance' http://purl.obolibrary.org/obo/GO_0071703
- [x] 'response to inorganic substance' http://purl.obolibrary.org/obo/GO_0010035
- [x] 'cellular response to organic substance' http://purl.obolibrary.org/obo/GO_0071310
- [x] 'cellular response to inorganic substance' http://purl.obolibrary.org/obo/GO_0071241

See https://github.com/geneontology/go-ontology/issues/27194

Thanks, Pascale

**Comment by ValWood** [comment]
Could we add

GO:1901361    organic cyclic compound catabolic process
GO:1901362    organic cyclic compound biosynthetic process
GO:1901360    organic cyclic compound metabolic process

to this list
thanks,

Val

**Comment by raymond91125** [comment]
GO:0034097 response to cytokine has only one parent GO:0010033 response to organic substance.
Move to GO:1901652 response to peptide. Preferably there is a cytokine term to be used in an LD.

GO:0072728 response to Gentian violet, added LD 'response to chemical' and ('has primary input' some 'crystal violet cation')
