### ISSUE TITLE
Add/remove subsets

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27395]
Hi @balhoff 
For the GO ribbons projects I have created 4 new subsets; can you add them to the ontologymalke file so that they get built? 

It's 
- goslim_prokaroyte_ribbon
- goslim_plant_ribbon
- goslim_euk_cellular_processes_ribbon
- ([goslim_flyBase_ribbon.yaml](https://ontology-build.geneontology.org/subsets/goslim_flyBase_ribbon.yaml) is already being produced) 

Also, can you remove: [goslim_flyBase_bibbon.yaml](https://ontology-build.geneontology.org/subsets/goslim_flyBase_bibbon.yaml)? That was a typo; I changed the file name but somehow this is still produced. 

Thanks, Pascale

**Comment by balhoff** [comment]
Done in #27397. I can't find any mention of 'bibbon' though.
