### ISSUE TITLE
NTR: U6 snRNA adenosine m6 methytransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27391]
Please provide as much information as you can: 

* **Suggested term label:**
U6 snRNA adenosine m6 methyltransferase activity

* **Definition (free text)**
Catalysis of the reaction: adenosine in U6 snRNA + S-adenosyl-L-methionine = H+ + N(6)-methyladenosine in U6 snRNA + S-adenosyl-L-homocysteine. [RHEA:52808]

* **Reference, in format PMID:#######**
PMID: 32266935

* **Gene product name and ID to be annotated to this term**
Human Q86W50 (METTL16)
Fly CG7544

* **Parent term(s)**
snRNA methyltransferase activity GO:0106346

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
EC:2.1.1.346
RHEA:52808
MetaCyc:RXN-18779

* **Any other information**

**Comment by ValWood** [comment]
Isn't this it?
U6 snRNA (adenine-(43)-N(6))-methyltransferase activity (GO:0120048)

**Comment by sjm41** [comment]
Thanks @ValWood - well-spotted! I think you're right.

id: GO:0120048
name: U6 snRNA (adenine-(43)-N(6))-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + adenine(43) in U6 snRNA = S-adenosyl-L-homocysteine + N(6)-methyladenine(43) in U6 snRNA." [PMID:28525753]
is_a: GO:0106346 ! snRNA methyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/13569" xsd:anyURI
created_by: krc
creation_date: 2017-06-02T20:37:40Z


- GO:0120048 has been used in 5 EXP annotations to Swiss-Prot entries, 3 of which are to human METTL16/Q86W50, with sources including PMID:28525753 and PMID:32266935.
- And METTL16/Q86W50 is the only human protein annotated with RHEA:52808 in UniProt

So I think the task here is to rename and redefine GO:0120048 based on EC/RHEA, and add the xrefs indicated above.
Are you happy to take care of those things?

**Comment by ValWood** [comment]
Yep, this is good practice for me. I haven't really done any GO/Rhea def alignment.
