### ISSUE TITLE
Delete subsets.yaml files 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27394]
Hello, 

We need to delete all files in this directory: 
https://github.com/geneontology/go-ontology/tree/master/src/ontology/subsets

**EXCEPT FOR** 
https://github.com/geneontology/go-ontology/blob/master/src/ontology/subsets/README.md
https://github.com/geneontology/go-ontology/blob/master/src/ontology/subsets/go_subsets_metadata.yaml
https://github.com/geneontology/go-ontology/blob/master/src/ontology/subsets/subsets.schema.yaml

I'm not sure how to do this. 

@balhoff @kltm @cmungall 

Can you do that for me? 

Thanks, Pascale

**Comment by balhoff** [comment]
@pgaudet sure, check #27396.
