### ISSUE TITLE
error in term name: GO:0106348 U2 snRNA adenosine m6 methytransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27392]
id: GO:0106348
name: U2 snRNA adenosine m6 methytransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: a adenosine in U2 snRNA + S-adenosyl-L-methionine = an N6-methyl-adenosine in U2 snRNA + S-adenosyl-L-homocysteine + H+." [PMID:32637152]
is_a: GO:0106346 ! snRNA methyltransferase activity
created_by: hjd
creation_date: 2020-12-18T15:12:57Z

- [x] add the missing 'l' in the term name

**Comment by pgaudet** [comment]
@sjm41 

Any idea whyn the label is 'U2 snRNA adenosine **m6** methytransferase activity' rather than U2 snRNA adenosine **N6** methytransferase activity?

**Comment by pgaudet** [comment]
OK - I see that name is used in the literature - I think it refers to the already present modification
