### ISSUE TITLE
NTR: RNA ligase (GTP) activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27418]
Please provide as much information as you can: 

* **Suggested term label:**
RNA ligase (GTP) activity 

* **Definition (free text)**
Catalysis of the joining of an RNA with 3'-phosphate or 2',3'-cyclic-phosphate ends to an RNA with 5'-hydroxy ends according to either (i) a 3'-end 3'-phospho-ribonucleotide-RNA + a 5'-end dephospho-ribonucleoside-RNA + GTP = a ribonucleotidyl-ribonucleotide-RNA + diphosphate + GMP; or (ii) a 3'-end 2',3'-cyclophospho-ribonucleotide-RNA + a 5'-end dephospho-ribonucleoside-RNA + GTP + H2O = a ribonucleotidyl-ribonucleotide-RNA + diphosphate + GMP + H+.

* **Reference, in format PMID:#######**
PMID: 21311021

* **Gene product name and ID to be annotated to this term**
Worm rtcb-1 (P90838)
Human RTCB (Q9Y3I0)
fly RtcB (Q9VIW7)

* **Parent term(s)**
RNA ligase activity (GO:0008452)

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
3'-phosphate/5'-hydroxy nucleic acid ligase activity (EXACT)

* **Cross-references**
EC:6.5.1.8 (exactMatch)
RHEA:68076 (narrowMatch)
RHEA:68080 (narrowMatch)
MetaCyc:RXN-17905 (narrowMatch)
MetaCyc:RXN0-6566 (narrowMatch)

* **Any other information**

There is a related EC/GO term, which seems to have caused some confusion:

id: GO:0003972
name: RNA ligase (ATP) activity
namespace: molecular_function
def: "Catalysis of the reaction: ATP + ribonucleotide(n) + ribonucleotide(m) = AMP + diphosphate + ribonucleotide(n+m)." [EC:6.5.1.3]
synonym: "poly(ribonucleotide):poly(ribonucleotide) ligase (AMP-forming)" RELATED [EC:6.5.1.3]
synonym: "polyribonucleotide ligase activity" RELATED [EC:6.5.1.3]
synonym: "polyribonucleotide synthase (ATP) activity" RELATED [EC:6.5.1.3]
synonym: "ribonucleic ligase activity" BROAD [EC:6.5.1.3]
xref: EC:6.5.1.3
xref: MetaCyc:RNA-LIGASE-ATP-RXN
is_a: GO:0008452 ! RNA ligase activity

Note the def for GO:0003972 should be updated to the current EC def: 
"ATP + (ribonucleotide)n-3'-hydroxyl + 5'-phospho-(ribonucleotide)m <=> (ribonucleotide)n+m + AMP + diphosphate"
Which then also makes it clear that this activity acts on 3' hydroxyl and 5' phospho ends (in contrast to EC:6.5.1.8, which is the other way round)

So there may be some related annotation issues to be checked and maybe fixed too.
E.g.
1. Human RTCB (Q9Y3I0) is annotated to EC:6.5.1.8/RHEA:68076/RHEA:68080 in UniProt from PMID: 21311021 but is annotated with 'RNA ligase (ATP) activity (GO:0003972)' (=EC:6.5.1.3) from same paper. @
2. Worm rtcb-1 (P90838) is annotated to EC:6.5.1.8/RHEA:68076/RHEA:68080 in UniProt from PMID: 25366321 but is annotated with 'RNA ligase (ATP) activity (GO:0003972)' (=EC:6.5.1.3) from same paper.
3. "IPR027513 RNA-splicing ligase RtcB homologue, eukaryotic" has associated EC of EC:6.5.1.8 but is annotated with  'RNA ligase (ATP) activity (GO:0003972)' (=EC:6.5.1.3)'

This also affects PTN000122119, but fixing the above human and worm annotations will fix that.

---

I also see there are these related BP terms, that look like they describe MFs? - not sure they should be kept?

id: GO:0000970 tRNA exon ligation utilizing GTP as source of linkage phosphate
=> 0 annotations

GO:0000969 tRNA exon ligation utilizing ATP as source of linkage phosphate
=> 0 annotations

GO:0000971 tRNA exon ligation utilizing 2',3' cyclic phosphate of 5'-exon as source of linkage phosphate
=> 1 EXP annotation

**Comment by edwong57** [comment]
I added RNA ligase (GTP) activity and updated the definition for GO:0003972. I left the GO:0000970, GO:0000969, and GO:0000971 alone since it seems like these obsoletions should probably be made into new tickets.

**Comment by pgaudet** [comment]
Thanks @edwong57 

Would you please you create an annotation review ticket for the incorrect annotations you spotted above? 
(maybe all annotations need to be reviewed, I let you judge).

Thanks, Pascale

**Comment by sjm41** [comment]
Hi @pgaudet What do you think about the 3 related BP terms I mentioned at the bottom of the original comment - would those be considered MFs?  I didn't want to make a separate obsoletion ticket for those without some feedback.

**Comment by sjm41** [comment]
Realised that the def of the parent term 'GO:0008452 RNA ligase activity' also needed tweaking:

def: "Catalysis of the formation of a phosphodiester bond between a hydroxyl group at the end of one RNA chain and the 5'-phosphate group at the end of another." 
>
def: "Catalysis of the formation of a phosphodiester bond between a hydroxyl group at the end of one RNA chain and the phosphate group at the end of another." 

I just made that change.

**Comment by sjm41** [comment]
> So there may be some related annotation issues to be checked and maybe fixed too.
1. Human RTCB (Q9Y3I0) is annotated to EC:6.5.1.8/RHEA:68076/RHEA:68080 in UniProt from PMID: 21311021 but is annotated with 'RNA ligase (ATP) activity (GO:0003972)' (=EC:6.5.1.3) from same paper. @
2. Worm rtcb-1 (P90838) is annotated to EC:6.5.1.8/RHEA:68076/RHEA:68080 in UniProt from PMID: 25366321 but is annotated with 'RNA ligase (ATP) activity (GO:0003972)' (=EC:6.5.1.3) from same paper.
3. "IPR027513 RNA-splicing ligase RtcB homologue, eukaryotic" has associated EC of EC:6.5.1.8 but is annotated with 'RNA ligase (ATP) activity (GO:0003972)' (=EC:6.5.1.3)'
3. This also affects PTN000122119, but fixing the above human and worm annotations will fix that.

1. I disputed the human annotations in P2GO and Sylvain has updated these.

2. @vanaukenk - can you review the rtcb-1 (P90838) annotation from PMID: 25366321 - I think it should be changed to the new term GO:0170057 RNA ligase (GTP) activity, or else the parent 'RNA ligase activity (GO:0008452)' term.

3. IPR027513 issue has been fixed in https://github.com/geneontology/go-annotation/issues/5152

4. PAINT issue is documented in https://github.com/geneontology/go-annotation/issues/5166

**Comment by sjm41** [comment]
Yep, as noted above!

**Comment by pgaudet** [comment]
I made checkboxes - that's easier for me ;)

**Comment by pgaudet** [comment]
> This also affects PTN000122119, but fixing the above human and worm annotations will fix that.

I am less sure about that ; the PAINT annotation cannot be automatically changed in primary annotations change. The only automatic change is if there is an obsolete with replace_by. 

Do we need a ticket for that one?

**Comment by sjm41** [comment]
Yes! From my comment above:

> PAINT issue is documented in https://github.com/geneontology/go-annotation/issues/5166

**Comment by vanaukenk** [comment]
I've updated the C. elegans rtcb-1 annotation.
