### ISSUE TITLE
NTR: [magnesium ion transport from cytosol to endoplasmic reticulum]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#27413]
Please provide as much information as you can: 

* **Suggested term label:**
magnesium ion transport from cytosol to endoplasmic reticulum

* **Definition (free text)**
The directed movement of magnesium ion from cytosol to endoplasmic reticulum. 

* **Reference, in format PMID:#######**
PMID:38513662

* **Gene product name and ID to be annotated to this term**
TMEM94

* **Parent term(s)**
GO:1903830 magnesium ion transmembrane transport

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
@lbreuza PMID:38513662 describes a single-step process carried out by TMEM94. Thus, instead of a BP, perhaps we should make an MF, e.g. "P-type magnesium ion endoplasmic reticulum transporter activity", child of GO:0015444 P-type magnesium transporter activity.
https://wiki.geneontology.org/Guidelines_for_new_Molecular_Functions

**Comment by lbreuza** [comment]
Hi,
I had the same doubt but as I found  an existing term: calcium ion transport from cytosol to endoplasmic reticulum, I thought it would be fine.
If I read the documentation you pointed out I would not create the term you suggested. "Cellular structures are not functions. Many cellular component references have been made obsolete in the function ontology. For example, a mitochondrial primase needs only be primase activity because annotators can assign location to gene products by annotating with appropriate terms from the cellular component ontology."
I already curated GO:0015444 P-type magnesium transporter activity with that paper, but how to capture the fact that it is involved in magnesium entry within the ER.
Maybe @pgaudet can help me with that annotation.
Thanks a lot for looking into this.
Best, Lionel

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160176
+name: magnesium ion transport from cytosol to endoplasmic reticulum
+namespace: biological_process
+def: "The directed movement of magnesium ion from cytosol to endoplasmic reticulum." [PMID:38513662]
+intersection_of: GO:0006810 ! transport
+intersection_of: has_primary_input CHEBI:18420 ! magnesium(2+)
+intersection_of: has_target_end_location GO:0005783 ! endoplasmic reticulum
+intersection_of: has_target_start_location GO:0005829 ! cytosol
+intersection_of: results_in_transport_across GO:0016020 ! membrane
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27413" xsd:anyURI
+created_by: rynl
+creation_date: 2024-03-27T22:02:27Z
