### ISSUE TITLE
Fix terms mapping to obsolete or transferred EC

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27410]
Hi @raymond91105 
I extracted only the non-obsolete terms from https://github.com/geneontology/go-ontology/issues/21347

- The list of tern /xrefs that need to be reviewed is below. 
- The SOP for the review procedure is here: https://docs.google.com/document/d/1YZeKpDjSecKu7P7IQsOzcdnxRDWSUYqoyyCBhvHvU3g/edit  (note that each case is different; this procedure may be incomplete. Feel free to add or ask questions if needed)
- Check GO terms and EC to make sure there is no other existing ticket; if so, check if the other ticket can also be closed. 

Let me know if you have other questions. 

- [x] GO:0019727  has an xref to an obsolete EC: "EC:1.1.1.32"
- [x] GO:0016720  has an xref to an obsolete EC: "EC:1.14.99.33"
- [x] GO:0050136  has an xref to an obsolete EC: "EC:1.6.5.11"
- [x] GO:0008940  has an xref to an obsolete EC: "EC:1.7.99.4"
- [x] GO:0047228  has an xref to an obsolete EC: "EC:2.4.1.157"
- [x] GO:0047232  has an xref to an obsolete EC: "EC:2.4.1.164"
- [x] GO:0047847  has an xref to an obsolete EC: "EC:2.4.2.23"
- [x] GO:0047625  has an xref to an obsolete EC: "EC:2.5.1.4"
- [x] GO:0103111  has an xref to an obsolete EC: "EC:2.7.1.69"
- [x] GO:0050405  has an xref to an obsolete EC: "EC:2.7.11.27"
- [x] GO:0008668  has an xref to an obsolete EC: "EC:2.7.7.58"
- [x] GO:0047844  has an xref to an obsolete EC: "EC:3.5.4.14"
- [x] GO:0047442  has an xref to an obsolete EC: "EC:4.1.2.30"
- [x] GO:0050548  has an xref to an obsolete EC: "EC:4.2.1.101"
- [x] GO:0050271  has an xref to an obsolete EC: "EC:4.4.1.6"
- [x] GO:0004121  has an xref to an obsolete EC: "EC:4.4.1.8"
- [x] GO:0047826  has an xref to an obsolete EC: "EC:5.4.3.4"
- [x] GO:0004495  has a definition xref to an obsolete EC: "EC:1.1.1.32"
- [x] GO:0019727  has a definition xref to an obsolete EC: "EC:1.1.1.32"
- [x] GO:0004495  has a definition xref to an obsolete EC: "EC:1.1.1.33"
- [x] GO:0010277  has a definition xref to an obsolete EC: "EC:1.13.12.14"
- [x] GO:0052606  has a definition xref to an obsolete EC: "EC:1.13.12.14"
- [x] GO:0052607  has a definition xref to an obsolete EC: "EC:1.13.12.14"
- [x] GO:0090489  has a definition xref to an obsolete EC: "EC:1.14.13.125"
- [x] GO:0036190  has a definition xref to an obsolete EC: "EC:1.14.13.137"
- [x] GO:0036192  has a definition xref to an obsolete EC: "EC:1.14.13.139"
- [x] GO:0036193  has a definition xref to an obsolete EC: "EC:1.14.13.140"
- [x] GO:0051777  has a definition xref to an obsolete EC: "EC:1.14.13.79"
- [x] GO:0051778  has a definition xref to an obsolete EC: "EC:1.14.13.79"
- [x] GO:0051779  has a definition xref to an obsolete EC: "EC:1.14.13.79"
- [x] GO:0016720  has a definition xref to an obsolete EC: "EC:1.14.99.33"
- [x] GO:0018516  has a definition xref to an obsolete EC: "EC:1.3.1.63"
- [x] GO:0050136  has a definition xref to an obsolete EC: "EC:1.6.5.11"
- [x] GO:0031679  has a definition xref to an obsolete EC: "EC:1.6.99.6"
- [x] GO:0008940  has a definition xref to an obsolete EC: "EC:1.7.99.4"
- [x] GO:0030792  has a definition xref to an obsolete EC: "EC:2.1.1.138"
- [x] GO:0008988  has a definition xref to an obsolete EC: "EC:2.1.1.48"
- [x] GO:0047159  has a definition xref to an obsolete EC: "EC:2.3.1.104"
- [x] GO:0047228  has a definition xref to an obsolete EC: "EC:2.4.1.157"
- [x] GO:0047232  has a definition xref to an obsolete EC: "EC:2.4.1.164"
- [x] GO:0003851  has a definition xref to an obsolete EC: "EC:2.4.1.45"
- [x] GO:0047847  has a definition xref to an obsolete EC: "EC:2.4.2.23"
- [x] GO:0047625  has a definition xref to an obsolete EC: "EC:2.5.1.4"
- [x] GO:0103111  has a definition xref to an obsolete EC: "EC:2.7.1.69"
- [x] GO:0050405  has a definition xref to an obsolete EC: "EC:2.7.11.27"
- [x] GO:0008668  has a definition xref to an obsolete EC: "EC:2.7.7.58"
- [x] GO:0047844  has a definition xref to an obsolete EC: "EC:3.5.4.14"
- [x] GO:0102014  has a definition xref to an obsolete EC: "EC:3.6.3.17"
- [x] GO:0047442  has a definition xref to an obsolete EC: "EC:4.1.2.30"
- [x] GO:0050548  has a definition xref to an obsolete EC: "EC:4.2.1.101"
- [x] GO:0050555  has a definition xref to an obsolete EC: "EC:4.2.99.19"
- [x] GO:0050312  has a definition xref to an obsolete EC: "EC:4.4.1.12"
- [x] GO:0050271  has a definition xref to an obsolete EC: "EC:4.4.1.6"
- [x] GO:0004121  has a definition xref to an obsolete EC: "EC:4.4.1.8"
- [x] GO:0047467  has a definition xref to an obsolete EC: "EC:5.2.1.11"
- [x] GO:0047826  has a definition xref to an obsolete EC: "EC:5.4.3.4"

**Comment by sjm41** [comment]
I removed - [x] GO:0002950  has a definition xref to an obsolete EC: "EC:2.7.8.n3" since that was fixed in https://github.com/geneontology/go-ontology/issues/27352

**Comment by pgaudet** [comment]
Thanks @sjm41

**Comment by raymond91125** [comment]
> * GO:0102014  has a definition xref to an obsolete EC: "EC:3.6.3.17"
No such case. No term references EC:3.6.3.17.

**Comment by pgaudet** [comment]
Looks like this is all done? Can this ticket be closed?

**Comment by balhoff** [comment]
Think so—I have merged in the QC check.
