### ISSUE TITLE
RNA ligases

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27437]
Hi @edwong57 

Thanks for creating the new RNA ligase term in #27418

Can you please

- [x] make  GO:0008452 RNA ligase activity 'do not annotate'? EcoCyc should change their annotation to [rtcB](https://amigo.geneontology.org/amigo/gene_product/UniProtKB:P46850) to the new RNA ligase (GTP) activity term
- [ ] check whether [2'-5'-RNA ligase activity](http://purl.obolibrary.org/obo/GO_0008664) should be obsoleted (and obsolete if needed?) The one gene annotated to this term is https://www.uniprot.org/uniprotkb/P37025/entry, and UniProt states "Was originally thought to be a 2',5'-RNA ligase."
- also, both this protein and the corresponding InterPro entry annotate both GO terms ' GO:0004113 JSON
2',3'-cyclic-nucleotide 3'-phosphodiesterase activity' and '2'-5'-RNA ligase activity'; I am not sure the latter really is correct
- [ ] GO:0004113 2',3'-cyclic-nucleotide 3'-phosphodiesterase activity : add RHEA:11828 and EC:3.1.4.58

Thanks, Pascale

**Comment by edwong57** [comment]
GO:0004113 has [EC:3.1.4.57](https://enzyme.expasy.org/EC/3.1.4.57) as a database cross-ref and also associated with a number of related synonyms. It doesn't seem right to me, but I'm not an expert. Should these be removed or should the database_cross_ref just be replaced with EC:3.1.4.38?

**Comment by edwong57** [comment]
2'-5' RNA ligases seem to be a thing in bacteria and archea. Not sure if it should be obsoleted.
https://pubmed.ncbi.nlm.nih.gov/12798681/
https://pubs.acs.org/doi/10.1021/ja028774y

**Comment by pgaudet** [comment]
I will change the label, definition and parent of GO:0008664 2'-5'-RNA ligase activity 

- There is 1 EXP by EcoCyc  P37025 and 1 InterPro mapping [InterPro:IPR004175](http://www.ebi.ac.uk/interpro/entry/IPR004175)

This gene was originally thought to have 2'-5'-RNA ligase activity, but newer evidence indicates that it has RNA 2',3'-cyclic 3'-phosphodiesterase activity. 

see PMID: 25239919 and UniProt entry (https://www.uniprot.org/uniprotkb/P37025/entry)

- [ ] new label: RNA 2',3'-cyclic 3'-phosphodiesterase activity
- [ ] changed definition to Catalysis the reaction: a 3'-end 2',3'-cyclophospho-ribonucleotide-RNA + H2O = a 3'-end 2'-phospho-ribonucleotide-RNA + H+." [PMID:25239919, RHEA:11828]
- [ ] add xref  EC:3.1.4.58 and  RHEA:11828
- [ ] changed parent to is_a: GO:0008081 ! phosphoric diester hydrolase activity
