### ISSUE TITLE
NTR: transmembrane dipeptide transport from lysosomal lumen to cytosol

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#27439]
Please provide as much information as you can: 

* **Suggested term label:**
transmembrane dipeptide transport from lysosomal lumen to cytosol

* **Definition (free text)**
The directed movement of dipeptide from the lysosomal lumen across the lysosomal membrane and into the cytosol.

* **Reference, in format PMID:#######**
PMID:38507452

* **Gene product name and ID to be annotated to this term**
MFSD1 UniProtKB/Q9H3U5

* **Parent term(s)**
GO:0007041 Lysosomal transport AND GO:0035442  dipeptide transmembrane transport

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by lbreuza** [comment]
Hi,
nothing happened with this ticket since I submitted it 3 weeks ago. 
Thanks

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141204
+name: dipeptide transmembrane transport from lysosomal lumen to cytosol
+namespace: biological_process
+def: "The directed movement of dipeptide from the lysosomal lumen across the lysosomal membrane and into the cytosol." [PMID:38507452]
+synonym: "dipeptide export from lysosomal lumen" EXACT []
+synonym: "dipeptide export from lysosome" EXACT []
+synonym: "transmembrane dipeptide transport from lysosomal lumen to cytosol" EXACT []
+intersection_of: GO:0055085 ! transmembrane transport
+intersection_of: has_primary_input CHEBI:90799 ! dipeptide zwitterion
+intersection_of: has_target_end_location GO:0005829 ! cytosol
+intersection_of: has_target_start_location GO:0043202 ! lysosomal lumen
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27439" xsd:anyURI
+created_by: pg
+creation_date: 2024-05-02T08:07:26Z

**Comment by pgaudet** [comment]
thanks for the ping @lbreuza
