### ISSUE TITLE
NTR: dipeptide uniporter activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#27431]
Please provide as much information as you can: 

* **Suggested term label:**
dipeptide uniporter activity

* **Definition (free text)**
Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: dipeptide(out) = dipeptide(in).

* **Reference, in format PMID:#######**
PMID:38507452

* **Gene product name and ID to be annotated to this term**
MFSD1

* **Parent term(s)**
GO:0015292  uniporter activity AND  GO:0071916 dipeptide transmembrane transporter activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.
Reactions to be created in Rhea

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160178
+name: dipeptide uniporter activity
+namespace: molecular_function
+def: "Catalysis of the transport of a dipeptide across a membrane; transport is independent of the movement of any other molecular species." [PMID:38507452]
+is_a: GO:0015292 ! uniporter activity
+is_a: GO:0071916 ! dipeptide transmembrane transporter activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27431" xsd:anyURI
+created_by: rynl
+creation_date: 2024-03-28T00:36:21Z
+

**Comment by pgaudet** [comment]
Hi @raymond91125 

Can you please make a logical defintion for this term? 
genera = transporter mechanism (uniporter) 
has primary input dipeptide

and remove unnecessary asserted classes. 

Thanks, Pascale
