### ISSUE TITLE
Obsoletion request: GO:0034641    cellular nitrogen compound metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27445]
Please provide as much information as you can:

* **GO term ID and Label**

- [x] GO:0034641    cellular nitrogen compound metabolic process
- [x] GO:0044270    cellular nitrogen compound catabolic process 
- [x] GO:0044271    cellular nitrogen compound biosynthetic process
No regulation terms

* **Reason for deprecation** Put an x in the appropriate box: 

 
 - [ ]  The reason for obsoletion is that this term was an unnecessary grouping term.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

related GO:0008152   metabolic process

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by jlewsmith** [comment]
CGD done

**Comment by ValWood** [comment]
change parent
GO:0034641 cellular nitrogen compound metabolic process
to
GO:0008152    metabolic process


for

GO:0034641
GO:0006139    nucleobase-containing compound metabolic process	is_a
GO:0072527    pyrimidine-containing compound metabolic process	is_a
GO:0018876    benzonitrile metabolic process	is_a
GO:0072521    purine-containing compound metabolic process	is_a
GO:0006577    amino-acid betaine metabolic process	is_a
GO:0044270    cellular nitrogen compound catabolic process	is_a
GO:0019331    anaerobic respiration, using ammonium as electron donor	is_a
GO:0072524    pyridine-containing compound metabolic process	is_a
GO:0019332    aerobic respiration, using nitrite as electron donor	is_a
GO:0044271    cellular nitrogen compound biosynthetic process	is_a
GO:0052803    imidazole-containing compound metabolic process	is_a
GO:0042726    flavin-containing compound metabolic process	is_a
GO:0018865    acrylonitrile metabolic process	is_a
GO:0042430    indole-containing compound metabolic process	is_a
GO:0019409    aerobic respiration, using ammonia as electron donor	is_a
GO:0019499    cyanide metabolic process	is_a
GO:0018938    2-nitropropane metabolic process	is_a
GO:0009439    cyanate metabolic process	is_a
GO:0070408    carbamoyl phosphate metabolic process

**Comment by ValWood** [comment]
@pgaudet  GO:0034641 cellular nitrogen compound metabolic process was in a 'chembl subset' 
I deleted this but I don't  know if I am supposed to do any follow up with this information?
