### ISSUE TITLE
Resolving inconsistencies pi/siRNAgene silencing 

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#27454]
Hi @pgaudet, now that https://github.com/geneontology/go-annotation/issues/5100 is done, I think that we can resolve some of the inconsistencies between siRNA and piRNA-mediated gene silencing via heterochromatin formation.

For siRNA-silencing:
```
GO:0031048 regulatory ncRNA-mediated heterochromatin formation
    |_GO:0080188 	gene silencing by siRNA-directed DNA methylation 	
    |_GO:0140727 	siRNA-mediated pericentric heterochromatin formation 	
    |_GO:1902795 	siRNA-mediated facultative heterochromatin formation
```
these three sibling terms describe different processes and I think that the structure is ok.

for piRNAs, we have:
```
GO:0031048 regulatory ncRNA-mediated heterochromatin formation
	|_GO:0140966 piRNA-mediated heterochromatin formation
		|_GO:0141006 piRNA-mediated retrotransposon silencing by heterochromatin formation
		|_GO:0141176 gene silencing by piRNA-directed DNA methylation
```

After https://github.com/geneontology/go-annotation/issues/5100, everything under GO:0141006 piRNA-mediated retrotransposon silencing by heterochromatin formation is just via post-transcriptional modification of chromatin proteins, namely histones. 
I have also reannotated everything that was directly to GO:0140966 piRNA-mediated heterochromatin formation, so this has no manual annotations.

Therefore, following a similar pattern to the siRNAs, I suggest that we:
1. obsolete term GO:0140966 piRNA-mediated heterochromatin formation

2. Rename 
GO:0141006 piRNA-mediated retrotransposon silencing by heterochromatin formation
to 
piRNA-mediated facultative heterochromatin formation
(as they are the same mechanism, and this is the term pattern used to describe the small ncRNA-mediated chromatin protein modification formation of heterochromatin).

3. Add the parent: GO:0006346 DNA methylation-dependent heterochromatin formation 
for GO:0141176 gene silencing by piRNA-directed DNA methylation

**Comment by pgaudet** [comment]
For 
> 1. obsolete term GO:0140966 piRNA-mediated heterochromatin formation

@hattrill and I decided to actually create a grouping class, so that this branch is consistent with the 'post-transcription gene silencing' branch.


<img width="528" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/8d3959c5-815f-4e93-ae09-823a2671b399">

**Comment by pgaudet** [comment]
- [ ] We agreed to obsolete [retrotransposon silencing by DNA methylation-dependent heterochromatin formation](http://purl.obolibrary.org/obo/GO_0141095) with replace by [retrotransposon silencing by siRNA-directed DNA methylation](http://purl.obolibrary.org/obo/GO_0141010); these represent the same pathway, one of them was created by error. 

Single annotation by UniProt.

**Comment by pgaudet** [comment]
> Rename
GO:0141006 piRNA-mediated retrotransposon silencing by heterochromatin formation
to
piRNA-mediated facultative heterochromatin formation

In fact to keep the retrotransposon and the non-retrotransposon branches consistent, we have decided to create a new term

**Comment by pgaudet** [comment]
> Add the parent: GO:0006346 DNA methylation-dependent heterochromatin formation

Done

**Comment by pgaudet** [comment]
Also created 

+[Term]
+id: GO:0141196
+name: retrotransposon silencing by piRNA-directed DNA methylation
+def: "A retrotransposon silencing mechanism mediated by Piwi-associated RNA (piRNA)-directed DNA methylation. This results in a heterochromatin assembly, a chromatin conformation that is refractory to transcription." [PMID:32674113]
+xref: biological_process
+is_a: GO:0141005 ! retrotransposon silencing by heterochromatin formation
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27454" xsd:anyURI
+created_by: pg
+creation_date: 2024-04-22T13:49:06Z

**Comment by pgaudet** [comment]
The new hierarch for retrotransposon silencing is 

<img width="557" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/9c4d3764-fbe3-4fd8-9735-1904ee6ec297">

**Comment by hattrill** [comment]
Hi @pgaudet just one more thing - looks like "piRNA-mediated facultative heterochromatin formation" needs to be also made a child of 'piRNA-mediated heterochromatin formation' (GO:0140966)

**Comment by pgaudet** [comment]
Thanks for pointing these out!
