### ISSUE TITLE
Synchronization issue between /subset folder and ontology build? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27464]
Hi @kltm 

The .yaml files for each individual subset were removed, see https://github.com/geneontology/go-ontology/tree/master/src/ontology/subsets
(PR is here: https://github.com/geneontology/go-ontology/pull/27414)

However these 'old' yaml files are still in the build: 
https://ontology-build.geneontology.org/

Is there a specific process that we need to do to remove them? 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet I think this will flush out once we have ontology build occurring again.

**Comment by kltm** [comment]
See: https://github.com/geneontology/go-ontology/issues/27470
