### ISSUE TITLE
NTR: telomerase RNA 3'-end processing

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#27469]
Please provide as much information as you can: 

* **Suggested term label:**
telomerase RNA 3'-end processing

* **Definition (free text)**

 Any process involved in forming the mature 3' end of a telomerase RNA molecule.  

* **Reference, in format PMID:#######**
 31488579

* **Gene product name and ID to be annotated to this term**
Q6NZY4  ZCCHC8

* **Parent term(s)**
GO:0031123 
nucleic acid catabolic process ? 

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
SO:0000390 

* **Any other information**

**Comment by ValWood** [comment]
We wouldn't create a telomerase (i.e gene product)  specific term, but does this work ?

   co-transcriptional lncRNA 3' end processing, cleavage and polyadenylation pathway

(this is the 3' processing pathway that uses the exosome), is it somehow post cleavage and polyadenylation?

**Comment by Antonialock** [comment]
I'll go with that...thanks
