### ISSUE TITLE
NTR: borate channel activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#27487]
* **Suggested term label:**

borate channel activity

* **Definition (free text)**

Enables the facilitated diffusion of borate (by an energy-independent process) involving passage through a transmembrane aqueous pore or channel without evidence for a carrier-mediated mechanism.  
The form of boric acid, B(OH3) via facilitated diffusion through the nodulin 26-like intrinsic proteins (NIPs)

* **Reference, in format PMID:#######**
PMID:21710975

* **Gene product name and ID to be annotated to this term**

UniProtKB:Q8LAI1 ; NIP7-1

* **Parent term(s)**

is_a inorganic anion transmembrane transporter activity
is_a channel activity
part _of GO:0035445 borate transmembrane transport

* **Cross-references**
* CHEBI:33118 boric acid

* **Any other information**

Once this term is made:
UniProtKB:Q8LAI1 ; NIP7-1
UniProtKB:Q9SAI4	NIP6-1
UniProtKB: Q9SV84 NIP5-1 
which are annotated with GO:0046715 active borate transmembrane transporter activity should be reannotated with this term.

**Comment by hattrill** [comment]
#27495

**Comment by ValWood** [comment]
I will do this one, it's easier

**Comment by pgaudet** [comment]
@ValWood can you please paste new terms in the ticket? It's easier to follow afterwards. 

Also, please link the ticket in the term. 

Thanks, Pascale

**Comment by ValWood** [comment]
Yes sorry. This was a random term I added to fix a problem with a term that I didn't need  but couldn't delete. I got in a panic.
Will add before closing

**Comment by pgaudet** [comment]
ok ;)

**Comment by ValWood** [comment]
[Term]
id: GO:0180044
name: borate channel activity
namespace: molecular_function
def: "Enables the facilitated diffusion of borate (by an energy-independent process) involving passage through a transmembrane aqueous pore or channel without evidence for a carrier-mediated mechanism." [PMID:21710975]
comment: https://github.com/geneontology/go-ontology/issues/27487
is_a: GO:0015103 ! inorganic anion transmembrane transporter activity
is_a: GO:0015267 ! channel activity
created_by: vw
creation_date: 2024-07-05T11:36:39Z
