### ISSUE TITLE
Obsoletion request: GO:1990483	 Clr6 histone deacetylase complex I''

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27509]
Please provide as much information as you can:

* **GO term ID and Label**
[GO:1990483](https://www.pombase.org/term/GO:1990483)	
[Clr6 histone deacetylase complex I''](https://www.pombase.org/term/GO:1990483)

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x]  The reason for obsoletion is that there is no evidence that this function/process/component exists.

We think this is an artefact, and is covered by other complex terms

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP: 
-12 , all PomBase

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***
- [x] Annotation review not required, PomBAse annotations already fixed
- [x] find external mappings (via IEAS), include in obsoletion notice  

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by pgaudet** [comment]
Can you 'replace by' the parent [histone deacetylase complex](http://purl.obolibrary.org/obo/GO_0000118)? 

there are some IBA annotations that could be moved automatically.

**Comment by ValWood** [comment]
It seems that clr6" was an artefact with members of another complex, so any annotation transfer would not be safe.

They should all be covered by the correct complexes (Rpd3s, Rpd3L,  Rpd3L-extended though, this would be redundant). I don't think the generic complexes are particularly useful.....

**Comment by ValWood** [comment]
background: https://github.com/pombase/curation/issues/3670
