### ISSUE TITLE
NTR: [protein branched polyubiquitination] and [Negative regulation of HRI-mediated signaling]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#27503]
Hi GO,

I would need a couple of terms, one should be pretty easy (negative regulation of...), while the other is more complex. We start to have more and more examples of E3 ligases that mediate branched ubiquitination. As we have terms for linear ubiquitination, I think it would make sense to create the term.

Thanks

Sylvain

Name: protein branched polyubiquitination
Definition: A protein ubiquitination process in which ubiquitin monomers are attached to a protein,
and then ubiquitin polymers are formed by linkages between lysine residues at various positions of the ubiquitin monomers, forming branched linkages, such as K11/K48- or K11/K63-linked chains. 
Category: Biological Process
Snonym: protein mixed polyubiquitination
Synonym: protein heterotypic polyubiquitination
Child of GO:0000209 protein polyubiquitination
PMID:27746020
PMID:29033132
PMID:29378950

2)

Name: Negative regulation of HRI-mediated signaling
Definition: Any process that stops, prevents, or reduces the frequency, rate or extent of HRI-mediated signaling.
Category: Biological Process
child of GO:0140468 HRI-mediated signaling
PMID:38297121

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141191
+name: negative regulation of HRI-mediated signaling
+namespace: biological_process
+def: "Any process that stops, prevents, or reduces the frequency, rate or extent of HRI-mediated signaling." [PMID:38297121]
+is_a: GO:0065007 ! biological regulation
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27503" xsd:anyURI
+created_by: pg
+creation_date: 2024-04-09T06:36:57Z

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141198
+name: protein branched polyubiquitination
+namespace: biological_process
+def: "A protein ubiquitination process in which ubiquitin monomers are attached to a protein, and then ubiquitin polymers are formed by linkages between lysine residues at various positions of the ubiquitin monomers, forming branched linkages, such as K11/K48- or K11/K63-linked chains." [PMID:29033132, PMID:29378950, PMID:31998699, PMID:37325469]
+is_a: GO:0000209 ! protein polyubiquitination
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27503" xsd:anyURI
+created_by: pg
+creation_date: 2024-04-26T06:08:52Z
