### ISSUE TITLE
Changes related to GO:0141189 G protein-mediated opsin signaling pathway

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#27505]
Hi @pgaudet 

I've come across some issues when reviewing the annotations related to https://github.com/geneontology/go-ontology/issues/27415

I will just list them here. Happy to leave this until Monday meeting on the 15th.

1. I came across a GO:0016056 'rhodopsin mediated signaling pathway' which I think should be merged into GO:0141189 'G protein-mediated opsin signaling pathway'. Both are in the GPCR branch.
GO:0016056 'rhodopsin mediated signaling pathway' is a 'part_of' phototransduction, visible light but 'G protein-mediated opsin signaling pathway' is_a 'phototransduction'. [As ](https://en.wikipedia.org/wiki/Opsin) suggest that there are opsins that can be activated by UV light, so the more general 'phototransduction' seems more correct.
![Screenshot 2024-04-04 at 14 42 36](https://github.com/geneontology/go-ontology/assets/11865746/cd828ad4-0168-41a5-920e-1b912230f08c)

![Screenshot 2024-04-04 at 14 43 20](https://github.com/geneontology/go-ontology/assets/11865746/270e3fd3-b408-4877-9563-1ee524f2aac2)

2. GO:0141189 'G protein-mediated opsin signaling pathway' has a is_a relationship with GO:0007200 'phospholipase C-activating G protein-coupled receptor signaling pathway', but as we now have a transducin and phospholipase C-activating  children the parentage needs to be re-jigged, something like:
![Screenshot 2024-04-04 at 15 17 37](https://github.com/geneontology/go-ontology/assets/11865746/9071f8cf-8077-4d74-a620-a9df46cd51e4)

3. Think that we could just obsolete GO:0016060 metarhodopsin inactivation - these are all D.mel annotations, so I can move these.

4. I could do with a new regulation term 'negative regulation of phospholipase C-activating phototransduction signaling pathway'

**Comment by pgaudet** [comment]
Thanks @hattrill 

I will obsolete the new term GO:0141189 'G protein-mediated opsin signaling pathway' and replace it by GO:0016056 'rhodopsin mediated signaling pathway'. Annotation by Flybase and ZFIN will be automatically replaced.

**Comment by pgaudet** [comment]
After discussion with @hattrill , I will rename GO:0016060 metarhodopsin inactivation  >> negative regulation of phospholipase C-activating opsin-mediated signaling pathway, since this is what this term describes.
