### ISSUE TITLE
GO:0022880 - incorrect parent

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27517]
id: GO:0022880
name: protein-N(PI)-phosphohistidine-N-acetylglucosamine phosphotransferase system transporter activity
namespace: molecular_function
def: "Catalysis of the PEP-dependent, phosphoryl transfer-driven transport of substances across a membrane. The transport happens by catalysis of the reaction: protein N-phosphohistidine + N-acetylglucosamine(out) = protein histidine + N-acetylglucosamine phosphate(in). This differs from primary and secondary active transport in that the solute is modified during transport." [GOC:mtg_transport, ISBN:0815340729]
synonym: "N-acetylglucosamine PTS transporter activity" EXACT []
is_a: GO:0008982 ! protein-N(PI)-phosphohistidine-sugar phosphotransferase activity
is_a: GO:0015572 ! N-acetylglucosamine transmembrane transporter activity
is_a: GO:0015574 ! trehalose transmembrane transporter activity

The "is_a: GO:0015574 ! trehalose transmembrane transporter activity" relation here must be a mistake - remove.

**Comment by sjm41** [comment]
This appears to be a problem with the logical definition, where 'trehalose' is being specified in a couple of places instead of 'N-acetylglucosamine'.
I'm not sure how to fix this - could you take a look @raymond91105 ?

**Comment by raymond91125** [comment]
Are there other superfluous trehalose connections @sjm41 you've noticed? Thanks.

**Comment by sjm41** [comment]
Thanks @raymond91125. This was the only problem I noticed. I'll close this ticket.
