### ISSUE TITLE
NTR - metabolism: [UTP thiamine diphosphokinase activity]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#27518]
In vertebrates Thiamin pyrophosphokinase 1, UniProtKB/Q9H3S4, TPK1 is using UTP and not ATP as a P donor to produce thiamine diphosphate. PubMed=38547260.
We can either change the definition of GO:0004788  thiamine diphosphokinase activity so that it also includes UTP in addition of ATP. However TPK1 is specific for UTP, so it could make sense to have both GO terms. One should also update GO:0004788 to :
ATP thiamine diphosphokinase activity

* **Suggested term label:**
UTP thiamine diphosphokinase activity

* **ChEBI ID and label of the substance:**
UTP [CHEBI:46398](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=46398)
UMP [CHEBI:57865](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=57865)

* **Definition (free text)**
Catalysis of the reaction: UTP + thiamine = UMP + thiamine diphosphate.

based on [Rhea:79423] which is not yet public
UTP [CHEBI:46398](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=46398)
UMP [CHEBI:57865](http://www.ebi.ac.uk/chebi/searchId.do?chebiId=57865)

* **Reference, in format PMID:#######**
PMID:38547260

* **Gene product name and ID to be annotated to this term**
TPK1

* **Parent term(s)**
GO:0016778

* **Synonym(s) (please specify, EXACT, BROAD, NARROW or RELATED)**
_Other than the standard synonyms below_

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Cross-references**
* MetaCyc or KEGG pathways, can also provide Wikipedia or other links.

* **Any other information**

----

* **FOR ONTOLOGY EDITOR**

* **Logical definition**
* *  **substance metabolic process:**
'metabolic process'
 and ('has primary input or output' some [substance]
* * **substance biosynthetic process:**
'biosynthetic process'
 and ('has primary output' some [substance].
* * **substance catabolic process:**
'catabolic process'
 and ('has primary output' some [substance] 

* **Standard synonyms**
* *  **substance metabolic process:**
* * * EXACT: substance metabolism
* * **substance biosynthetic process:** 
* * * EXACT: substance anabolism
* * * EXACT: substance biosynthesis
* * * EXACT: substance formation
* * * EXACT: substance synthesis

* * **substance catabolic process:**    
* * * EXACT: substance breakdown
* * * EXACT: substance catabolism
* * * EXACT: substance degradation

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141200
+name: UTP thiamine diphosphokinase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: UTP + thiamine = UMP + thiamine diphosphate." [PMID:38547260, RHEA:79423]
+xref: RHEA:79423
+is_a: GO:0016778 ! diphosphotransferase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27518" xsd:anyURI
+created_by: pg
+creation_date: 2024-04-30T07:07:13Z

**Comment by pgaudet** [comment]
@lbreuza 

I am not sure about this suggestion: 

> One should also update GO:0004788 to : ATP thiamine diphosphokinase activity

ATP is the phosphate group donor; why would this go in the term label? 

Thanks, Pascale

**Comment by lbreuza** [comment]
I am not sure either. Just thought it was good to make it consistent with UTP thiamine diphosphokinase activity where UTP is the P donnor.

**Comment by pgaudet** [comment]
I see. It seems like this is specified because it is an unusual donor? The donor is not in the term label for 
'GTP diphosphokinase activity'
'ribose phosphate diphosphokinase activity'
'nucleotide diphosphokinase activity'

I think these are more or less copied from EC. 


Thanks, Pascale
