### ISSUE TITLE
BP term with RHEA xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27520]
id: GO:0051470
name: ectoine transport
namespace: biological_process
def: "The directed movement of ectoine into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore. Ectoine (1,4,5,6-tetrahydro-2-methyl-4-pyrimidinecarboxylic acid) is a tetrahydropyrimidine commonly synthesized by halophilic bacteria." [GOC:ai, RHEA:32791]
xref: RHEA:32791
intersection_of: GO:0006810 ! transport
intersection_of: has_primary_input CHEBI:58515 ! ectoine zwitterion
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/24076" xsd:anyURI

I assume this is an error, and we shouldn't have a RHEA xref on a BP term. (This is the only such case in the ontology.)
The related issue here is that there doesn't appear to be a MF term for "ectoine transporter activity" - should there be?
(Though even if we make that term, RHEA:32791 shouldn't be a xref on it because it's "L-ectoine(in) = L-ectoine(out)" which is specifically for channels/uniporters and is not a generic/grouping class.)

I will remove the xref from GO:0051470.

**Comment by sjm41** [comment]
For the record, just noting that there is this ATPase-coupled ectoine transporter term:

id: GO:0033286
name: ATPase-coupled ectoine transmembrane transporter activity
namespace: molecular_function
alt_id: GO:0051471
def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + ectoine(out/in) = ADP + phosphate + ectoine(in/out)." [GOC:mlg, RHEA:32787]
synonym: "ATP-dependent ectoine transmembrane transporter activity" EXACT []
synonym: "ectoine transmembrane transporter activity" BROAD []
synonym: "ectoine-transporting ATPase activity" EXACT []
xref: RHEA:32787
intersection_of: GO:0042626 ! ATPase-coupled transmembrane transporter activity
intersection_of: has_primary_input CHEBI:58515 ! ectoine zwitterion
relationship: part_of GO:0051470 ! ectoine transport

**Comment by pgaudet** [comment]
Also changed labels: 

GO:0051470 ectoine transport
to ectoine transmembrane transport


GO:0033308 hydroxyectoine transport
to hydroxyectoine transmembrane transport
