### ISSUE TITLE
peptide alpha-N-acetyltransferase (NAT) terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27532]
We currently have this hierarchy and EC/RHEA xrefs:
```
peptide alpha-N-acetyltransferase activity (GO:0004596) (EC:2.3.1.255)
    |__peptide-alanine-alpha-N-acetyltransferase activity (GO:0008999) (EC:2.3.1.267 narrow, RHEA:43752 narrow, RHEA:43756 exact)
    |__peptide-serine-alpha-N-acetyltransferase activity (GO:1990189)
    |__peptide-glutamate-alpha-N-acetyltransferase activity (GO:1990190)
```

The parent GO term is defined as:
id: GO:0004596
name: peptide alpha-N-acetyltransferase activity
def: "Catalysis of the reaction: acetyl-CoA + peptide = CoA + N-alpha-acetylpeptide. This reaction is the acetylation of the N-terminal amino acid residue of a peptide or protein." [GOC:mah, PMID:30054468]
xref: EC:2.3.1.255

EC:2.3.1.255 is:
Name: N-terminal amino-acid N(alpha)-acetyltransferase NatA
Comments: The NatA complex is found in all eukaryotic organisms, and specifically targets N-terminal Ala, Gly, Cys, Ser, Thr, and Val residues, that became available after removal of the initiator methionine.

EC:2.3.1.267 / RHEA:43752 is:
Name: [ribosomal protein uS5]-alanine N-acetyltransferase
Reaction: acetyl-CoA + N-terminal L-alanyl-[ribosomal protein uS5] <=> CoA + H(+) + N-terminal N(alpha)-acetyl-L-alanyl-[ribosomal protein uS5]

And RHEA:43756 (which maps to EC:2.3.1.266) is:
acetyl-CoA + N-terminal L-alanyl-[ribosomal protein bS18] = CoA + H(+) + N-terminal N(alpha)-acetyl-L-alanyl-[ribosomal protein bS18]

There are a few related issues here (PMID: [30054468](https://pubmed.ncbi.nlm.nih.gov/30054468) is a useful review):

---

- [x] Add [RHEA:21028](https://www.rhea-db.org/rhea/21028) as exactMatch xref on GO:0004596:
acetyl-CoA + an N-terminal L-α-aminoacyl-[protein] = CoA + H+ + N-terminal Nα-acetyl-L-α-aminoacyl-[protein]

---

- [x] Resolve xrefs on peptide-alanine-alpha-N-acetyltransferase activity (GO:0008999)

RHEA:43756 is not an exact match to GO:0008999 - its a narrow match -> anyway, remove both the current RHEAs and replace with RHEA:50500 acetyl-CoA + N-terminal L-alanyl-[protein] = CoA + H(+) + N-terminal N(alpha)-acetyl-L-alanyl-[protein]
Also add EC:2.3.1.266 as another narrowMatch xref

---

- [x] Add EC:2.3.1.257 as a narrowMatch xref to peptide-serine-alpha-N-acetyltransferase activity (GO:1990189)

EC:2.3.1.257
Name: N-terminal L-serine N(alpha)-acetyltransferase NatD
Comments: NatD is found in all eukaryotic organisms, and acetylates solely the serine residue at the N-terminus of histones H2A or H4.

---

- [x] Assuming we want to retain child terms for specific N-terminal amino acids, then we should make a new term for 'peptide-methionine-alpha-N-acetyltransferase activity'. This would have the following xrefs:

RHEA:75239 (exactMatch)
acetyl-CoA + N-terminal L-methionyl-[protein] = CoA + H(+) + N-terminal N(alpha)-acetyl-L-methionyl-[protein]

EC:3.3.1.254 (narrowMatch)
Name: N-terminal methionine N(alpha)-acetyltransferase NatB
Comments: The NatB complex is found in all eukaryotic organisms, and specifically targets N-terminal L-methionine residues attached to Asn, Asp, Gln, or Glu residues at the second position. 

EC:2.3.1.256 (narrowMatch)
Name: N-terminal methionine N(alpha)-acetyltransferase NatC
Comments: The NatC complex is found in all eukaryotic organisms, and specifically targets N-terminal L-methionine residues attached to bulky hydrophobic residues at the second position, including Leu, Ile, Phe, Trp, and Tyr residues.

EC:2.3.1.258 (narrowMatch)
Name: N-terminal methionine N(alpha)-acetyltransferase NatE
Comments: It specifically targets N-terminal L-methionine residues attached to Lys, Val, Ala, Tyr, Phe, Leu, Ser, and Thr.

EC:2.3.1.259 (narrowMatch)
Name: N-terminal methionine N(alpha)-acetyltransferase NatF 
Comments: NatF targets N-terminal L-methionine residues attached to Lys, Ser, Val, Leu, Gln, Ile, Tyr and Thr residues. 

---

- [x] Make a new child term of GO:0004596 for this related EC entry:

EC: 2.3.1.308
Name: tubulin N-terminal N-acetyltransferase NAT9
Comments: The enzyme, characterized from the fruit fly (Drosophila melanogaster), acetylates the N-terminal of both alpha- and beta- tubulin

This is [RHEA:69607](https://www.rhea-db.org/rhea/69607).
Needed to annotate Dmel Mnat9 and human NAT9.

**Comment by sjm41** [comment]
@pgaudet Do the proposals above look OK to you?

**Comment by pgaudet** [comment]
Looks good, sorry about being so slow to respond. This branch needs work - one obvious merge is here: 
https://github.com/geneontology/go-ontology/issues/28466

**Comment by pgaudet** [comment]
Reported by a user of the GO helpdesk email: 

I noticed an error in the in the most recent archived version of ec2go.txt (uploaded 2024-11-03).
Line 3336 reads:
EC:3.3.1.254 > GO:peptide-methionine-alpha-N-acetyltransferase activity ; GO:0120518
The actual EC number associated with this GO term should be 2.3.1.254.
EC:3.3.1.254 does not exist.
 
Kind regards,
Helen

**Comment by sjm41** [comment]
Oops, sorry for this typo. Thanks for fixing @pgaudet !
