### ISSUE TITLE
Obsolete GO:0102966 arachidoyl-CoA:1-dodecanol O-acyltransferase activity (or remove EC xref)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27542]
The following two GO terms have the same EC xref.
The xref on GO:0047196 is correct.
The xref on GO:0102966 should be removed. The source for GO:0102966 appears to be MetaCyc:RXN-9356, and that entry says that the GO:0102966 reaction is an 'unofficial' (ie. more specific) version of GO:0047196/EC:2.3.1.75.

So, we either need to remove the EC dbxref and ref xref from GO:0102966 and make it a child of GO:0047196, or we could just obsolete it because it's a substrate-specific version of GO:0047196 and because it has zero EXP annotations.
What do you think @pgaudet ?

id: GO:0047196
name: long-chain-alcohol O-fatty-acyltransferase activity
namespace: molecular_function
alt_id: GO:0103095
def: "Catalysis of the reaction: a long-chain-alcohol + acyl-CoA = a long-chain ester + CoA." [EC:2.3.1.75, MetaCyc:2.3.1.75-RXN]
synonym: "acyl-CoA:long-chain-alcohol O-acyltransferase activity" RELATED [EC:2.3.1.75]
synonym: "wax ester synthase activity" EXACT []
synonym: "wax synthase activity" RELATED [EC:2.3.1.75]
synonym: "wax-ester synthase activity" RELATED [EC:2.3.1.75]
xref: EC:2.3.1.75
xref: MetaCyc:2.3.1.75-RXN
xref: MetaCyc:RXNQT-4193
xref: RHEA:38443
is_a: GO:0008374 ! O-acyltransferase activity

id: GO:0102966
name: arachidoyl-CoA:1-dodecanol O-acyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: icosanoyl-CoA + dodecan-1-ol = arachidoyl dodecanoate + coenzyme A." [EC:2.3.1.75, GOC:pz]
xref: EC:2.3.1.75
xref: MetaCyc:RXN-9356
is_a: GO:0016747 ! acyltransferase activity, transferring groups other than amino-acyl groups

**Comment by pgaudet** [comment]
Hi @sjm41 
Let's obsolete GO:0102966 because it's a substrate-specific version of GO:0047196.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0102966 arachidoyl-CoA:1-dodecanol O-acyltransferase activity. The reason for obsoletion is that this represents a specific substrate of  GO:0047196 long-chain-alcohol O-fatty-acyltransferase activity. There are no annotations  or mappings to this term; this term is not present in any subset. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/27542

Thanks, Pascale
