### ISSUE TITLE
Term merge: GO:0070290 & GO:0102200

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27559]
id: GO:0070290
name: N-acylphosphatidylethanolamine-specific phospholipase D activity
namespace: molecular_function
def: "Catalysis of the release of N-acylethanolamine from N-acyl-phosphatidylethanolamine (NAPE) to generate N-acylethanolamine (NAE)." [GOC:elh, PMID:14634025, PMID:15878693]
subset: goslim_chembl
synonym: "N-acyl-phosphatidylethanolamine-specific phospholipase D activity" EXACT []
synonym: "NAPE-specific phospholipase D activity" EXACT []
xref: EC:3.1.4.4
is_a: GO:0004620 ! phospholipase activity
is_a: GO:0008081 ! phosphoric diester hydrolase activity
intersection_of: GO:0004620 ! phospholipase activity
intersection_of: has_primary_input CHEBI:62537 ! N-acylphosphatidylethanolamine(1-)

=> I think the EC:3.1.4.4 xref here should be EC:3.1.4.54 (perhaps the result of a simple typo, or because EC:3.1.4.4 is correctly an xref on GO:0004630 phospholipase D activity, which is a related reaction)

EC:3.1.4.54/RHEA:33159 is already an xref on GO:0102200, and I think these two GO terms should be merged. E.g. The reactions look the same, and the two PMIDs in the GO:0070290 def are sources for EC/RHEA terms.

id: GO:0102200
name: N-acetylphosphatidylethanolamine-hydrolysing phospholipase activity
namespace: molecular_function
def: "Catalysis of the reaction: H2O + an N-acylphosphatidylethanolamine = H+ + an N-acylethanolamine + a 1,2-diacyl-sn-glycerol 3-phosphate." [GOC:pz, RHEA:33159]
xref: EC:3.1.4.54
xref: MetaCyc:RXN-12116
xref: RHEA:33159
is_a: GO:0008081 ! phosphoric diester hydrolase activity

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0102200 N-acetylphosphatidylethanolamine-hydrolysing phospholipase activity. The reason for obsoletion is that this represents the same activity as GO:0070290 N-acylphosphatidylethanolamine-specific phospholipase D activity.  There are no annotations; this term is not present in any subset. 

RHEA:33159 and MetaCyc:RXN-12116 will be moved to GO:0070290
EC will be fixed to EC:3.1.4.54. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/27559

Thanks, Pascale

**Comment by sjm41** [comment]
I see that CHEBI classifies N-acylphosphatidylethanolamine (CHEBI:62537) as a "anionic phospholipid".
So I think the parentage to 'phospholipase activity' here is OK?

**Comment by pgaudet** [comment]
OK yes thanks!

**Comment by sjm41** [comment]
Thanks for fixing!
