### ISSUE TITLE
xrefs for GO:0018423 protein C-terminal leucine carboxyl O-methyltransferase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27556]
id: GO:0018423
name: protein C-terminal leucine carboxyl O-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + protein L-leucine = S-adenosyl-L-homocysteine + protein L-leucine methyl ester. This modification occurs only at the oxygen atoms of the free alpha carboxyl group of a leucine residue at the C-terminus of the protein." [PMID:8514774]
synonym: "protein phosphatase methyltransferase activity" NARROW []
synonym: "protein-leucine O-methyltransferase activity" EXACT []
is_a: GO:0003880 ! protein C-terminal carboxyl O-methyltransferase activity
is_a: GO:0008757 ! S-adenosylmethionine-dependent methyltransferase activity

As per the narrow synonym "protein phosphatase methyltransferase activity", EC:2.1.1.233 / RHEA:48544 could be added to this term as narrowMatch xrefs. That reaction is:
[phosphatase 2A protein]-C-terminal L-leucine + S-adenosyl-L-methionine = [phosphatase 2A protein]-C-terminal L-leucine methyl ester + S-adenosyl-L-homocysteine

Note:
GO:0018423 has only be used in one EXP annotation, and that's to cerevisiae PPM1 (Protein Phosphatase Methyltransferase 1), so it looks like this GO term reflects the specificity of the EC/RHEA entry in practice...

**Comment by sjm41** [comment]
Also adding:
MetaCyc:RXN-12317 {source="skos:narrowMatch"}

**Comment by pgaudet** [comment]
Changed 'protein' to '[protein]-' in the defintion, since this is how we did it elsewhere. 

@sjm41 right?
