### ISSUE TITLE
replication factor proteolysis or replisome cleavage

### ISSUE THREAD

**Issue by CP-SB** [geneontology/go-ontology#27555]
Please provide as much information as you can: 

* **name: replisome cleavage**

* **Definition (process replisome substrates during DNA synthesis in an ATP-dependent manner.)**

* **Reference, in format PMID:38554706,
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
HI @CP-SB
are you requesting an activity, or a process?

I think in this situation the correct MF would be

GO:0004176  ATP-dependent peptidase activity  (or similar)
you would add the replisome substrates as inputs (we don't create terms  activity terms to describe specific substrates)


so your annotation would be something like:
MF GO:0004176  ATP-dependent peptidase activity has_input(gene)|has_input(gene)
part_of GO:0031297 replication fork processing

**Comment by CP-SB** [comment]
Thanks Val, will use that recommendation.

**Comment by ValWood** [comment]
Were you annotating  the  activity of the  complex "protein complex composed of AAA+ ATPases SPATA5-SPATA5L1 together with heterodimeric partners C1orf109-CINP (55LCC)." or the protease?

The complex might be better described as a "dissagregase activity"
https://www.ebi.ac.uk/QuickGO/term/GO:0140545
ATP-dependent protein disaggregase activity
An ATP-dependent molecular chaperone activity that mediates the solubilization of ordered protein aggregates. PMID:26312418
but we might need to extend the definition here to include complexes.

Note that this complex appears to have a similar activity during ribosome assembly, where it extracts RSL24D1 from pre-60S subunits


https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9004343/
 SPATA5 and SPATA5L1 (Figure S6D), further suggesting that these proteins carry out non-overlapping functions in removing RSL24D1 from pre-60S subunits. Phylogenetic analysis shows that CINP and C1ORF109 are likely related to one another. Orthologs of these proteins are not present in yeast, but CINP-like proteins are found in Drosophila and C. elegans, among other species. Matchmaker alignments of AlphaFold predictions (Meng et al., 2006; Senior et al., 2020) indicate that CINP and C1ORF109 share remarkably similar structure......

So, it should have the same MF term for both processes, coupled to different substrates for the respective biological  processes.

**Comment by CP-SB** [comment]
Hi Val, I was trying to annotate the activity of the complex and have tagged it with GO:0140545 but requested the additional term to capture the activity of protease...thinking to separate the processes.

**Comment by ValWood** [comment]
@CP-SB I discussed this one with @pgaudet 
We are trying to avoid terms which describe proteases as processes, and historical terms which described proteolysis in this way have been/are being obsoleted

see for example https://github.com/geneontology/go-ontology/issues/28575 GO:0097304 lipoprotein biosynthetic process via signal peptide cleavage
and 

GO:0000469   obsolete cleavage involved in rRNA processing |  
-- | --
GO:1901308   obsolete regulation of sterol regulatory element binding protein cleavage

[GO:0000469](https://www.ebi.ac.uk/QuickGO/term/GO:0000469)   obsolete cleavage involved in rRNA processing	
[GO:1901308](https://www.ebi.ac.uk/QuickGO/term/GO:1901308)   obsolete regulation of sterol regulatory element binding protein cleavage

so the correct way to annotate this  protease would be
MF GO:0004176  ATP-dependent peptidase activity has_input(gene)|has_input(gene)
part_of GO:0031297 replication fork processing (or replication termination)
