### ISSUE TITLE
Cross references on obsolete GO terms - guidelines need clarification

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27564]
This is coming from edits in _Originally posted by @pgaudet in https://github.com/geneontology/go-ontology/issues/21347#issuecomment-1993991113_

The issue reported by @raymond91105 s that the obsolete EC:1.1.1.128 has several mentions in the synonyms and cross references of the obsolete GO term 'obsolete L-idonate 2-dehydrogenase activity' <http://purl.obolibrary.org/obo/GO_0050027>

Current Ontology editors documentation states that references and definition cross references from Reactome, RHEA, EC, MetaCyc  should be removed from GO terms, see
https://wiki.geneontology.org/Obsoleting_an_Existing_Ontology_Term#5._Cross-references
We have discussed more recently that maybe they are not a problem if they are on obsolete terms. 
**AI: If we change the guidelines, we need to update the documentation.**

gtom @raymond91105 
> More generally, I am not sure about the benefit of dealing with ECs that are referenced in obsoleted GO terms. 
This way they dont show up in reports, but maybe reports could exclude obsolete terms. 

> we could use a script to remove them all at once.

to be discussed with GO editors.

**Comment by sjm41** [comment]
Just to note that the RHEA xref that was kept on this obsolete GO term DID cause a problem:
https://github.com/geneontology/go-ontology/issues/26441#issuecomment-2110538398

**Comment by pgaudet** [comment]
We decided NOT to keep cross references on obsolete terms, see https://wiki.geneontology.org/Guidelines_for_database_cross_references
