### ISSUE TITLE
Three GO terms with EC:3.2.1.169 xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27560]
EC:3.2.1.169 (protein O-GlcNAcase) has two associated reactions:
    3-O-(N-acetyl-beta-D-glucosaminyl)-L-seryl-[protein] + H2O <=> L-seryl-[protein] + N-acetyl-D-glucosamine
    3-O-(N-acetyl-beta-D-glucosaminyl)-L-threonyl-[protein] + H2O <=> L-threonyl-[protein] + N-acetyl-D-glucosamine

And we have EC:3.2.1.169 as an xref on three related GO terms:

id: GO:0102571
name: [protein]-3-O-(N-acetyl-D-glucosaminyl)-L-serine/L-threonine O-N-acetyl-alpha-D-glucosaminase activity
namespace: molecular_function
def: "Catalysis of the reaction: H2O + an N-acetyl-alpha-D-glucosaminyl-[glycoprotein] = N-acetyl-alpha-D-glucosaminide + a [glycoprotein]-(L-serine/L-threonine)." [EC:3.2.1.169, GOC:pz]
xref: EC:3.2.1.169
xref: MetaCyc:RXN-15215
is_a: GO:0004553 ! hydrolase activity, hydrolyzing O-glycosyl compounds

id: GO:0102166
name: [protein]-3-O-(N-acetyl-D-glucosaminyl)-L-threonine O-N-acetyl-alpha-D-glucosaminase activity
namespace: molecular_function
def: "Catalysis of the reaction: H2O + an N-acetyl-alpha-D-glucosaminyl-L-threonine-[glycoprotein] = N-acetyl-alpha-D-glucosaminide + a [protein]-L-threonine." [EC:3.2.1.169, GOC:pz]
xref: EC:3.2.1.169
xref: MetaCyc:RXN-11891
xref: RHEA:48892
is_a: GO:0004553 ! hydrolase activity, hydrolyzing O-glycosyl compounds

id: GO:0102167
name: [protein]-3-O-(N-acetyl-D-glucosaminyl)-L-serine O-N-acetyl-alpha-D-glucosaminase activity
namespace: molecular_function
def: "Catalysis of the reaction: H2O + an N-acetyl-alpha-D-glucosaminyl-L-serine-[glycoprotein] = N-acetyl-alpha-D-glucosaminide + a [protein]-L-serine." [EC:3.2.1.169, GOC:pz]
xref: EC:3.2.1.169
xref: MetaCyc:RXN-11892
xref: RHEA:48876
is_a: GO:0004553 ! hydrolase activity, hydrolyzing O-glycosyl compounds

What's the best resolution here?:
1. Obsolete GO:0102166 and GO:0102167, and then make RHEA and MetaCyc xrefs narrowMatch on GO:0102571?
2. Keep GO:0102166 and GO:0102167, and make EC:3.2.1.169 a narrowMatch on them?  If keeping these terms, then they should be made children of GO:0102571.

I vote for 1.

Also, the term def of GO:0102571 should be changed to:
"Catalysis of the reaction: 3-O-(N-acetyl-beta-D-glucosaminyl)-L-seryl/L-threonyl-[protein] + H2O <=> L-seryl//L-threonyl-[protein] + N-acetyl-D-glucosamine."

**Comment by pgaudet** [comment]
I will obsolete GO:0102166 and GO:0102167.

**Comment by pgaudet** [comment]
@sjm41 Note that we dont use ' <=> ' in definitons. I used '='.

**Comment by pgaudet** [comment]
@sjm41 
For RHEA we dont capture specific reactions as cross references; so for MetaCyc I dont think we should include the narrow xrefs RXN-11891 and RXN-11892. OK with you?

**Comment by sjm41** [comment]
> @sjm41 Note that we dont use ' <=> ' in definitons. I used '='.

Yep, I was just being lazy and just copied and pasted the reaction from the Expasy site.....

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0102166 name: [protein]-3-O-(N-acetyl-D-glucosaminyl)-L-threonine O-N-acetyl-alpha-D-glucosaminase activity and GO:0102167 [protein]-3-O-(N-acetyl-D-glucosaminyl)-L-serine O-N-acetyl-alpha-D-glucosaminase activity. The reason for obsoletion is that these represent specific substrates of GO:0102571
name: [protein]-3-O-(N-acetyl-D-glucosaminyl)-L-serine/L-threonine O-N-acetyl-alpha-D-glucosaminase activity, so they will be replaced by GO:0102571 [protein]-3-O-(N-acetyl-D-glucosaminyl)-L-serine/L-threonine O-N-acetyl-alpha-D-glucosaminase activity. 

There are no annotations to these terms. RHEA mappings will be moved as NARROW matches on GO:0102571. These terms are not present in any subsets.

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/27560

Thanks, Pascale

**Comment by sjm41** [comment]
> For RHEA we dont capture specific reactions as cross references; so for MetaCyc I dont think we should include the narrow xrefs RXN-11891 and RXN-11892. OK with you?

Sure.
Does that mean that the final remaining term here (GO:0102571) won't have any RHEA refs?

**Comment by sjm41** [comment]
Couple of questions about when we update an enzyme def to match the EC/RHEA reaction def:
1. Is there a preference whether we add the EC or RHEA ID as the def xref?
2. Is there a need/desire to preserve def xrefs like "[GOC:pz]" if the revised def is based solely on EC/RHEA?

**Comment by pgaudet** [comment]
Hi @sjm41 

The current guidelines are here: 
https://wiki.geneontology.org/Guidelines_for_GO_textual_definitions

I added this to the next ontology call to get some clarification.
