### ISSUE TITLE
Definition cross reference on GO:0036193 2-hydroxy-1,4-benzoxazin-3-one monooxygenase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27578]
Hi @raymond91105 
As we have in the documentation, RHEA is the preferred definition xreference: https://wiki.geneontology.org/Guidelines_for_GO_textual_definitions#Cross-references_for_definitions

Can you make sure that if there is a RHEA, and that the GO term defintion matches, that the RHEA is also a def xrefs? 
Looks like it's missing from 
GO:0036193 2-hydroxy-1,4-benzoxazin-3-one monooxygenase activity

Thanks, Pascale

**Comment by raymond91125** [comment]
Fixed, thanks.

**Comment by pgaudet** [comment]
Thank you!!
