### ISSUE TITLE
Cross references on GO:0050572 'L-idonate 5-dehydrogenase activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27573]
(note that IDs are confusing: 
GO:0050572 L-idonate 5-dehydrogenase activity
GO:0050027 obsolete L-idonate 2-dehydrogenase activity) 

This is coming from discussions in https://github.com/geneontology/go-ontology/issues/21347#issuecomment-1993991113

[obsolete L-idonate 2-dehydrogenase activity](http://purl.obolibrary.org/obo/GO_0050027) was obsoleted  in #21347 as part of the obsolete EC clean up, with the comment that this reaction corresponds to [EC:1.1.1.264](https://enzyme.expasy.org/EC/1.1.1.264). 
A valid RHEA cross reference remains on that term, RHEA:21176. 

As @raymond91105 points out, this could be a case for automatic replacement of xreferences, 
> Mapping from EC to RHEA could be queried directly. e.g. https://www.rhea-db.org/rhea?query=ec%3A1.1.1.264.

@cmungall @balhoff Can this be done? 

Querying EC:1.1.1.264 in RHEA gives 2 reactions, see screenshot
<img width="1084" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/a359c2c0-9b7d-436e-bbe6-5c928bc63479">

* [RHEA:21176](https://www.rhea-db.org/rhea/21176) L-idonate + **NADP**+ = 5-dehydro-D-gluconate + H+ + NADPH >> maps to the obsolete GO term
* [RHEA:21172](https://www.rhea-db.org/rhea/21172) is correctly mapped to [L-idonate 5-dehydrogenase (NAD+) activity](http://purl.obolibrary.org/obo/GO_0102198)

As far as I can tell, the actions would be to 
1. Add RHEA:21176 to GO:0050572 'L-idonate 5-dehydrogenase activity' 
2. GO:0050572 'L-idonate 5-dehydrogenase activity'  should be renamed 'L-idonate 5-dehydrogenase activity (NADP+)' 
3. EC:1.1.1.264 on GO:0050572 'L-idonate 5-dehydrogenase activity'  should have skos:narrowMatch
4. EC:1.1.1.264 should be added to GO:0102198 L-idonate 5-dehydrogenase (NAD+) activity as skos:narrowMatch

Could a script do this? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Talking to @cmungall , we cannot easily write a script that will be able to make the correct call reliably. 

For now we need to do this kinds of more complex mappings manually.

**Comment by raymond91125** [comment]
The situation here is
GO:0050572 L-idonate 5-dehydrogenase activity -> EC:1.1.1.264 NAD or NADP -> RHEA:21172 + RHEA:21176
GO:0102198 L-idonate 5-dehydrogenase (NAD+) activity -> EC:1.1.1.366 NAD specific -> RHEA:21172

**Comment by pgaudet** [comment]
Hi @raymond91125 

I think some edits are not been done? 

- [ ] RHEA:21176 should be removed from obsolete GO:0050027 obsolete L-idonate 2-dehydrogenase activity
- [ ] MetaCyc def cross reference should be removed from  GO:0050572 'L-idonate 5-dehydrogenase activity' (as discussed Monday, we want a single database xref for definitions)
- [ ] GO:0050572 'L-idonate 5-dehydrogenase activity' should be renamed 'L-idonate 5-dehydrogenase activity [NAD(P)+]'

Thanks, Pascale

**Comment by sjm41** [comment]
> GO:0050572 'L-idonate 5-dehydrogenase activity' should be renamed 'L-idonate 5-dehydrogenase activity [NAD(P)+]'

This should be 'L-idonate 5-dehydrogenase [NAD(P)+] activity', right?

**Comment by pgaudet** [comment]
Ha ! I think you're right! We haven't finished to standardize these, so I copied from the wrong one. 

Did we say that we always used NAD+/NADP+?

**Comment by sjm41** [comment]
My take on this is described in #27180 where I tried to make term names using NAD consistent.

I think there is still some inconsistency in use of "[NAD(P)+] " vs "(NAD(P)+)" (i.e. square vs round brackets).

**Comment by raymond91125** [comment]
Thanks. Assuming it's good to close.
