### ISSUE TITLE
Obsoletion request: GO:0043402 glucocorticoid mediated signaling pathway

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27594]
Dear all, 

The proposal has been made to obsolete  GO:0043402 glucocorticoid mediated signaling pathway, because that term has the same meaning as [glucocorticoid receptor signaling pathway](http://purl.obolibrary.org/obo/GO_0042921). 

There is a single annotation to this term by RGD and one InterPro mapping. This term is not present in any subset. 

You can comment on the ticket: 

Thanks, Pascale

**Comment by gthayman** [comment]
Annotation addressed.

**Comment by ValWood** [comment]
This looks ready?

**Comment by pgaudet** [comment]
* GO:1900169 regulation of glucocorticoid mediated signaling pathway>> replace by GO:2000322 regulation of glucocorticoid receptor signaling pathway
* GO:1900170 negative regulation of glucocorticoid mediated signaling pathway >> replace by negative regulation of glucocorticoid receptor signaling pathway ; GO:2000323
* GO:1900171 positive regulation of glucocorticoid mediated signaling pathway >> replace by positive regulation of glucocorticoid receptor signaling pathway ; GO:2000324
