### ISSUE TITLE
NTR: nuclear receptor signaling pathway

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27599]
+[Term]
+id: GO:0141193
+name: nuclear receptor signaling pathway
+namespace: biological_process
+def: "The series of molecular signals initiated by a signaling molecule binding to its nuclear receptor inside the cell, and ending with the regulation of a downstream cellular process, e.g. transcription." [PMID:25614732]
+is_a: GO:0030522 ! intracellular receptor signaling pathway
+created_by: pg
+creation_date: 2024-04-12T13:08:13Z

To group 

- 'androgen receptor signaling pathway'
- 'ecdysone receptor-mediated signaling pathway'
- 'intracellular corticosteroid receptor signaling pathway'
- 'intracellular glucocorticoid receptor signaling pathway'
- 'intracellular mineralocorticoid receptor signaling pathway'
- 'intracellular estrogen receptor signaling pathway'
- 'progesterone receptor signaling pathway'
- [peroxisome proliferator activated receptor signaling pathway](http://purl.obolibrary.org/obo/GO_0035357)
- [vitamin D receptor signaling pathway](http://purl.obolibrary.org/obo/GO_0070561)
- [thyroid hormone mediated signaling pathway](http://purl.obolibrary.org/obo/GO_0002154)

@colinlog

**Comment by pgaudet** [comment]
Updated defintion: The series of molecular signals initiated by a signaling molecule binding to its nuclear receptor inside the cell, regulating the transcription of specific target genes.

**Comment by pgaudet** [comment]
Human nuclear receptors: https://docs.google.com/spreadsheets/d/1tRta_XFQWZ35cbJYjFw4tvQj90hufxLTDM8qF5BbJn0/edit#gid=0

**Comment by pgaudet** [comment]
Added is_a hormone-mediated signaling pathway to 

'retinoic acid receptor signaling pathway'
'vitamin D receptor signaling pathway'

**Comment by deustp01** [comment]
> Added is_a hormone-mediated signaling pathway to
>  'vitamin D receptor signaling pathway'

Naive question: does vitamin D fit the definition of hormone? Or does anything whose action is mediated via a nuclear receptor count as a hormone?

**Comment by pgaudet** [comment]
Hi @deustp01 

Vitamin D seems to be viewed as a hormone: 
- https://en.wikipedia.org/wiki/Calcitriol
- https://pubmed.ncbi.nlm.nih.gov/26681795/
- https://my.clevelandclinic.org/health/articles/22464-hormones

**Comment by pgaudet** [comment]
Change labels to be consistent: 
0002155
-name: regulation of thyroid hormone mediated signaling pathway
+name: regulation of thyroid hormone **receptor** signaling pathway
