### ISSUE TITLE
Obsoletion request: anaerobic/aerobic fructose catabolic process (GO:0019325/GO:0019576)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27618]
Please provide as much information as you can:

* **GO term ID and Label**

id: GO:0019325
name: anaerobic fructose catabolic process
def: "The chemical reactions and pathways resulting in the breakdown of fructose that occurs in the absence of oxygen." [GOC:ai]
xref: MetaCyc:ANAEROFRUCAT-PWY
is_a: GO:0006001 ! fructose catabolic process
is_a: GO:0019317 ! fucose catabolic process

id: GO:0019576
name: aerobic fructose catabolic process
def: "The chemical reactions and pathways resulting in the breakdown of fructose that occurs in the presence of oxygen." [GOC:ai]
is_a: GO:0006001 ! fructose catabolic process

* **Reason for deprecation** Put an x in the appropriate box: 
 - [x] The reason for obsoletion is that the term is not clearly defined.
 - [x]  The reason for obsoletion is that the meaning of the term is ambiguous.

GO:0019325 is based on MetaCyc:ANAEROFRUCAT-PWY, which is "homolactic fermentation" (glucose -> lactate, via pyruvate), and which is already (correctly) an xref on "GO:0019661 glucose catabolic process to lactate via pyruvate"

Also, GO:0019325 has incorrect parent of "fucose catabolic process"

* **Are there annotations to this term?**
0 annotations to either term.

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
No

* **Is this term in a subset? (check the AmiGO page for that term)**
No

* **Any other information**
OK with @deustp01 and @ukemi if we obsolete these two terms? They are sister terms to other fructose catabolic process that are actually used and well-defined:
```
fructose catabolic process
|__aerobic fructose catabolic process
|__anaerobic fructose catabolic process
|__fructose catabolic process to hydroxyacetone phosphate and glyceraldehyde-3-phosphate
|__glycolytic process from fructose through fructose-6-phosphate
|__glycolytic process through fructose-1-phosphate
```
----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by deustp01** [comment]
Quick sanity check on this and #27616 during the weeds call this Thursday?

**Comment by sjm41** [comment]
Decision on call (with @deustp01 and @ukemi) was that we should proceed with obsoletion.

**Comment by pgaudet** [comment]
Please don't hesitate to ping the tickets that have been inactive!
