### ISSUE TITLE
NTR: piperine biosynthetic process

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#27622]
Please provide as much information as you can: 

* **Suggested term label:**
piperine biosynthetic process

* **Definition (free text)**

The chemical reactions and pathways resulting in the formation of piperine, a pungent alkaloid and phenolamide produced in for example black pepper.

* **Reference, in format PMID:#######**
33833371

33435446

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7826766/
![image](https://github.com/geneontology/go-ontology/assets/12727506/4a63a48d-e0d1-4ba0-a800-8ccb5776acb5)

* **Gene product name and ID to be annotated to this term**
A0A7T9QPQ1
P0DO56
P0DO57

* **Parent term(s)**

GO:0044550
I'm not sure what else

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

GO:0050199 could ahve some relationship

**Comment by Antonialock** [comment]
could also add kw to
GO:0050199

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160181
+name: piperine biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of piperine." [PMID:33435446, PMID:33833371]
+intersection_of: GO:0009058 ! biosynthetic process
+intersection_of: has_primary_output CHEBI:28821 ! piperine
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27622" xsd:anyURI
+created_by: rynl
+creation_date: 2024-04-24T20:31:20Z

This term follows a design pattern https://raw.githubusercontent.com/geneontology/go-ontology/master/src/design_patterns/biosynthetic_process.yaml.
In general, I don't see that we have the individual steps (MF) connected to the BP with part_of or has_part relations. Perhaps those are usually made with (GO-CAM) annotations.
I don't know what "add kw" means. Let me know if more should be done.

**Comment by Antonialock** [comment]
but now I'm unsure what kw I was going to map, maybe I was having a moment!
