### ISSUE TITLE
Add pre obsoletion "do not annotate" flag to "regulation of modification" terms

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27626]
Add the pre-obsoletion do not annotate flag

GO:1904285    regulation of protein-pyridoxal-5-phosphate linkage
GO:1904286    negative regulation of protein-pyridoxal-5-phosphate linkage	
GO:0010799    regulation of peptidyl-threonine phosphorylation
GO:0010800    positive regulation of peptidyl-threonine phosphorylation	
GO:0010801    negative regulation of peptidyl-threonine phosphorylation	
GO:1903719    regulation of I-kappaB phosphorylation
GO:1903721    positive regulation of I-kappaB phosphorylation
GO:1903720    negative regulation of I-kappaB phosphorylation
GO:0033135    regulation of peptidyl-serine phosphorylation
GO:0033137    negative regulation of peptidyl-serine phosphorylation	
GO:0033138    positive regulation of peptidyl-serine phosphorylation
GO:0033139    regulation of peptidyl-serine phosphorylation of STAT protein	
GO:0033140    negative regulation of peptidyl-serine phosphorylation of STAT protein
GO:0033141    positive regulation of peptidyl-serine phosphorylation of STAT protein
GO:0001934    positive regulation of protein phosphorylation
GO:0001933    negative regulation of protein phosphorylation
GO:0001932    regulation of protein phosphorylation
GO:0043538    regulation of actin phosphorylation
GO:0060734    regulation of endoplasmic reticulum stress-induced eIF2 alpha phosphorylation
GO:0060735    regulation of eIF2 alpha phosphorylation by dsRNA
GO:1904323    regulation of inhibitory G protein-coupled receptor phosphorylation
GO:1904325    positive regulation of inhibitory G protein-coupled receptor phosphorylation
GO:1904324    negative regulation of inhibitory G protein-coupled receptor phosphorylation
GO:0010999    regulation of eIF2 alpha phosphorylation by heme
GO:0031952    regulation of protein autophosphorylation	
GO:0050730    regulation of peptidyl-tyrosine phosphorylation
GO:0031953    negative regulation of protein autophosphorylation
GO:0031954    positive regulation of protein autophosphorylation
GO:1900084    regulation of peptidyl-tyrosine autophosphorylation
GO:1900085    negative regulation of peptidyl-tyrosine autophosphorylation
GO:0061097    regulation of protein tyrosine kinase activity
GO:0050732    negative regulation of peptidyl-tyrosine phosphorylation
GO:0050731    positive regulation of peptidyl-tyrosine phosphorylation
GO:0010533    regulation of activation of Janus kinase activity
GO:0042509    regulation of tyrosine phosphorylation of STAT protein
GO:1904806    regulation of protein oxidation
GO:1904808    positive regulation of protein oxidation
GO:1904807    negative regulation of protein oxidation
GO:2000539    regulation of protein geranylgeranylation
GO:2000540    negative regulation of protein geranylgeranylation
GO:2000541    positive regulation of protein geranylgeranylation
GO:1901983    regulation of protein acetylation
GO:2000758    positive regulation of peptidyl-lysine acetylation
GO:2000761    positive regulation of N-terminal peptidyl-lysine acetylation
GO:2000759    regulation of N-terminal peptidyl-lysine acetylation
GO:2000760    negative regulation of N-terminal peptidyl-lysine acetylation
GO:2000757    negative regulation of peptidyl-lysine acetylation
GO:1902390    regulation of N-terminal peptidyl-serine acetylation
GO:1902391    positive regulation of N-terminal peptidyl-serine acetylation
GO:1901985    positive regulation of protein acetylation
GO:1901984    negative regulation of protein acetylation
GO:1904663    regulation of N-terminal peptidyl-methionine acetylation
GO:2000756    regulation of peptidyl-lysine acetylation
GO:1904665    positive regulation of N-terminal peptidyl-methionine acetylation
GO:1904664    negative regulation of N-terminal peptidyl-methionine acetylation
GO:2000170    positive regulation of peptidyl-cysteine S-nitrosylation
GO:1902083    negative regulation of peptidyl-cysteine S-nitrosylation
GO:1904286    negative regulation of protein-pyridoxal-5-phosphate linkage
GO:1904287    positive regulation of protein-pyridoxal-5-phosphate linkage
GO:1904285    regulation of protein-pyridoxal-5-phosphate linkage
GO:2000169    regulation of peptidyl-cysteine S-nitrosylation
GO:1901873    regulation of post-translational protein modification
GO:1901874    negative regulation of post-translational protein modification
GO:1901875    positive regulation of post-translational protein modification
GO:0060051    negative regulation of protein glycosylation
GO:1904098    regulation of protein O-linked glycosylation
GO:0060050    positive regulation of protein glycosylation
GO:1904099    negative regulation of protein O-linked glycosylation
GO:1904100    positive regulation of protein O-linked glycosylation
GO:2000169    regulation of peptidyl-cysteine S-nitrosylation
GO:1901873    regulation of post-translational protein modification
GO:0060049    regulation of protein glycosylation
GO:0031401    positive regulation of protein modification process
GO:0031400    negative regulation of protein modification process
GO:0035304    regulation of protein dephosphorylation
GO:1903059    regulation of protein lipidation
GO:1903059    regulation of protein lipidation
GO:1902662    regulation of peptidyl-L-cysteine S-palmitoylatin
GO:0060254    regulation of N-terminal protein palmitoylation
GO:1903061    positive regulation of protein lipidation
GO:1903060    negative regulation of protein lipidation
GO:1902664    positive regulation of peptidyl-L-cysteine S-palmitoylation
GO:1902663    negative regulation of peptidyl-L-cysteine S-palmitoylation
GO:0060262    negative regulation of N-terminal protein palmitoylation
GO:0120093    regulation of peptidyl-lysine crotonylation
GO:0120094    negative regulation of peptidyl-lysine crotonylation
GO:1903344    regulation of protein polyglycylation
GO:1903346    positive regulation of protein polyglycylation
GO:1903345    negative regulation of protein polyglycylation
GO:0010734    negative regulation of protein glutathionylation	
GO:0010733    positive regulation of protein glutathionylation
GO:0010732    regulation of protein glutathionylation
GO:0090311    regulation of protein deacetylation
GO:0090043    regulation of tubulin deacetylation	
GO:0090312    positive regulation of protein deacetylation
GO:0090044    positive regulation of tubulin deacetylation
GO:1900722    regulation of protein adenylylation
GO:1900723    negative regulation of protein adenylylation
GO:1900724    positive regulation of protein adenylylation

**Comment by deustp01** [comment]
Is there some discussion someplace of the rationale for these pre-obsoletions? Is this part of a broader clean-up? What is it aimed at? I.e., it would be really helpful to know, not just for legacy maintenance but for planning future curation, to understand what makes a process in or out of scope for GO.

**Comment by ValWood** [comment]
The "modification" branch in process has been slated for obsoletion for a long time, (was originally proposed by Suzi Lewis probably almost a decade ago and ratified in Montreal IIRC (note that the histone modifications/regulation of histone modifications are already removed).  So for this particular branch I was assuming that  has been fairly widely communicated for a long time. 

Instead of annotating to "phosphorylation/regulation of phosphorylation", which isn't biologically informative, you would annotate to the specific process that is being regulated by the phosphorylation event (for example ", signalling pathway x and/or regulation of chromosome segregation", etc). This helps to prevent multiple different types of process annotations to describe the identical process and make annotation more consistent, and improves the biological representation.

The pre-obsoletion is just a clearer version of "do not annotate" which is applied largely to high-level grouping terms.  This is effectively a heads up (soft check) to help curators make a decision when annotating and prevent new annotations accumulating until the obsoletion is eventually actioned.  We have to do the obsoletions in a step-wide manner because if the entire branch was obsoleted now it would be too much work for curators to review all in one go.

Note that most of the branch already has "do not annotate" flag pending obsoletion, here I am filling in the missing 'regulation' ones (and using the more specific pre-obsoletion flag). One reason I am eager to flag these terms is to prevent function prediction annotations because it is difficult to communicate why we haven't made annotations to these terms if they are not flagged in some way.

Does that make sense? Probably this is something that should be highlighted on and annotation  call @vanaukenk

**Comment by ValWood** [comment]
@pgaudet  is there a quick way to add the pre-obsoletion  flag to these terms?
