### ISSUE TITLE
NTR: [paracellular transport at tight junction]

### ISSUE THREAD

**Issue by nnouspikel** [geneontology/go-ontology#27621]
Dear GO curators,

I would like to discuss with you the possibility of creating a biological process term for epithelial paracellular transport at tight junctions;
it’s relevant to channel-forming claudins 
https://www.tcdb.org/browse.php
https://www.tcdb.org/search/index.php?query=claudin%202&type=system
review: PMID:30665499; PMID:28869648; PMID:28605828; PMID:21365189

new GO term: paracellular transport at tight junction
definition: The movement of solutes through a paracellular channel formed in the tight junction strands.
child of GO:0006810 transport
synonyms: paracellular epithelial permeability; pore pathway; tight junction-mediated paracellular transport

Maybe we can create the related molecular function term as well:
new GO term: paracellular channel activity
definition: A pore channel activity that enables size- and charge-selective transport of solutes through a tight junction barrier across the epithelium.
child of GO:0022842 narrow pore channel activity PMID:21365189
synonym: claudin pore

Thank you for your help and all the best,
Nevila Hyka-Nouspikel

**Comment by pgaudet** [comment]
Hi Nevila, 

Would it be a sibling of these terms: 
- GO:0010496 intercellular transport
- - GO:1990349 gap junction-mediated intercellular transport
- - GO:0010497 plasmodesmata-mediated intercellular transport
- -  GO:0110077 vesicle-mediated intercellular transport 

? 

Thanks, Pascale

**Comment by nnouspikel** [comment]
Hi Pascale,

Yes GO:0010496 intercellular transport is the most appropriate parent term. 

Thanks a lot,
Nevila

**Comment by ValWood** [comment]
I was curious what it is Google:

https://pubmed.ncbi.nlm.nih.gov/12609869/
"Unlike conventional ion channels, which mediate ion transport across lipid bilayers, the tight junction channels must orient parallel to the plane of the plasma membranes to support paracellular ion movements"

it seems the critical differentia is "facilitates the transport of ions between separate extracellular compartments" 

see image in
https://www.researchgate.net/publication/314233504_Nanoformulation_and_administration_of_PUFA-rich_systems_for_applications_in_modern_healthcare/figures?lo=1

<img width="1062" alt="Screenshot 2024-04-17 at 10 15 34" src="https://github.com/geneontology/go-ontology/assets/7359272/b16a236e-49b4-4a3f-998c-476bb6dbd4d7">

I think we should just have "paracellular transport"  for process (exclude location at ticght junction, can be captured with extension,
and MF "tight junction ion channel"

would be more  flexible for other types of paracellular transport
(which needs to be defined somehow as *between cells* not *inter* cells

**Comment by nnouspikel** [comment]
Thank you Val. 

"paracellular transport" for process and "paracellular channel activity" for molecular function – sounds all right, but up to you to decide; note that tight junction channels are permeable to uncharged molecules like water

All the best,
Nevila

**Comment by ValWood** [comment]
They are different:

Intercellular: Intercellular communication or processes occur within the cell itself or involve direct interactions between cells.

Paracellular: This term refers to the movement of substances between cells through the space that exists between adjacent cells. it's the passage of molecules or ions through the intercellular space without actually passing through the cell membrane. 

Paracellular isn't going in

**Comment by nnouspikel** [comment]
I agree, they are different. Here is a schematic depicting gap and tight junction channels:
https://ars.els-cdn.com/content/image/1-s2.0-S0022283614005713-gr4_lrg.jpg (PMID:25451028)

**Comment by raymond91125** [comment]
![image](https://github.com/geneontology/go-ontology/assets/619520/8ecef59d-8ddd-4156-8635-323e529068e1)

**Comment by raymond91125** [comment]
I am not sure what the parent should be for MF "tight junction channel activity". It cannot be a child of GO:0015267 channel activity because it's not of transmembrane transport; or a child of GO:0005215 transporter activity because it's not transporting in/out/between cells (I think between here means inter cellular).

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160184
+name: paracellular transport
+namespace: biological_process
+def: "The directed movement of substance through the space in between adjacent cells, rather than through the cells themselves." [PMID:28452575, WIki:Paracellular_transport]
+is_a: GO:0006810 ! transport
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27621" xsd:anyURI
+created_by: rynl
+creation_date: 2024-04-29T23:13:30Z

**Comment by raymond91125** [comment]
GO:0005215 transporter activity DEF "Enables the directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells".
Should we change that to "Enables the directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells, or through the space in between adjacent cells."?
The original definition was referenced to GOC:dgf, GOC:ai. Can we consult them? @pgaudet

**Comment by raymond91125** [comment]
@pgaudet Do you think we need to revise the definition of GO:0005215 transporter activity to accommodate "paracellular tight junction channel activity"?

**Comment by pgaudet** [comment]
I would add this as a direct child of transporter activity: 
<img width="281" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/93629a93-98c1-45c0-9e9e-0b0d17a3cd29">

**Comment by pgaudet** [comment]
I see the definiton is "Enables the directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, or between cells."

Change to 
"Enables the directed movement of substances (such as macromolecules, small molecules, ions) into, out of or within a cell, **across or in between** cells."

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160187
+name: paracellular tight junction channel activity
+namespace: molecular_function
+def: "Enables size- and charge-selective transport of solutes through a tight junction barrier paracellularly, across the epithelium." [PMID:30665499]
+synonym: "claudin pore" EXACT []
+is_a: GO:0005215 ! transporter activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27621" xsd:anyURI
+created_by: rynl
+creation_date: 2024-05-14T00:31:01Z

**Comment by raymond91125** [comment]
Please let me know if anything else is needed. Thanks.

**Comment by pgaudet** [comment]
Look good!

**Comment by nnouspikel** [comment]
Thank you!
