### ISSUE TITLE
TPV: processing

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27633]
has the parent
[nucleic acid catabolic process](https://www.pombase.org/term/GO:0141188)?

**Comment by ValWood** [comment]
sno(s)RNA processing (GO:0043144)
has the parent [nucleic acid catabolic process](https://www.pombase.org/term/GO:0141188)?

**Comment by ValWood** [comment]
tRNA processing (GO:0008033)
has the parent [nucleic acid catabolic process](https://www.pombase.org/term/GO:0141188)?

**Comment by ValWood** [comment]
Something weird.
Might be related to 
https://github.com/geneontology/go-ontology/issues/27408

**Comment by ValWood** [comment]
@pgaudet  processing shouldn't be under "catabolic"

v

**Comment by ValWood** [comment]
Hi @pgaudet  if you can could you look at this one? It's causing a lot of problem propagation because it is quite a 'high level' error.

**Comment by pgaudet** [comment]
Thanks for pointing that out @ValWood 

I fixed the LDs of GO:0141187 nucleic acid biosynthetic process and  GO:0141188 nucleic acid catabolic process (had the wrong genera). 

Also - do you think it's OK if I make 
RNA processing
part_of RNA biosynthetic process (rather than metabolic process?) 

Thanks, Pascale

**Comment by ValWood** [comment]
Re: Also - do you think it's OK if I make
RNA processing
part_of RNA biosynthetic process (rather than metabolic process?)

I'm not sure about that.  I feel that synthesis and processing/maturation are really considered separate steps in green expression. It doesn't feel right to me (i.e. splicing == RNA biosynthesis??).....I think we should ask experts before we make that connection.
