### ISSUE TITLE
NTR: [intestinal iron absorption]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#27630]
Please provide as much information as you can: 

* **Suggested term label:**
intestinal iron absorption

* **Definition (free text)**
Uptake of iron into the blood by absorption from the small intestine. 

* **Reference, in format PMID:#######**
PMID:16054062

* **Gene product name and ID to be annotated to this term**
SLC40A1, HEPH

* **Parent term(s)**
GO:0050892   intestinal absorption

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160179
+name: intestinal iron absorption
+namespace: biological_process
+def: "A process in which iron is taken up from the contents of the intestine." [PMID:16054062, PMID:17729393]
+intersection_of: GO:0050892 ! intestinal absorption
+intersection_of: has_primary_input CHEBI:24875 ! iron cation
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27630" xsd:anyURI
+created_by: rynl
+creation_date: 2024-04-17T22:55:31Z
