### ISSUE TITLE
Inconsistencies in parentage of mitochondrial complex I/III/IV activities

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27641]
Mitochondrial complexes I/III/IV are all "oxidoreduction-driven active transmembrane transporters", transporting H+ into the mitochondrial intermembrane space.
However, the parentage on the three corresponding GO-MF terms is inconsistent.

Main question is whether these GO terms should have is_a parentage to 'oxidoreductase activity' or not. Two of them do (though this may be for historical reasons, related to when they were transferred from EC:1 to the EC:7 class) but one of them (GO:0008137) now does not, after the changes described in https://github.com/geneontology/go-ontology/issues/20616#issuecomment-2060074004.

As pointed out in https://github.com/geneontology/go-ontology/issues/20616#issuecomment-2061884254:
> GO:0015453 (oxidoreduction-driven active transmembrane transporter activity) has LD 'primary active transmembrane transporter activity' and ('has part' some 'oxidoreductase activity'). Perhaps the connection to oxidoreductase branch could be fleshed out via the LD some how.

**MITOCHONDRIAL COMPLEX I**
id: GO:0008137
name: NADH dehydrogenase (ubiquinone) activity
def: "Catalysis of the reaction: NADH + ubiquinone + 5 H+(in) = NAD+ + ubiquinol + 4 H+(out)." [RHEA:29091]
xref: EC:7.1.1.2
xref: MetaCyc:NADH-DEHYDROG-A-RXN
xref: RHEA:29091
is_a: GO:0009055 ! electron transfer activity
is_a: GO:0015453 ! oxidoreduction-driven active transmembrane transporter activity

=> this has no is_a parentage in the 'oxidoreductase activity' branch, whereas other 2 terms have this.
=> this also lacks the 'is_a: GO:0015078 ! proton transmembrane transporter activity' parent present on the other 2 terms below.

**MITOCHONDRIAL COMPLEX III**
id: GO:0008121
name: ubiquinol-cytochrome-c reductase activity
def: "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: CoQH2 + 2 ferricytochrome c = CoQ + 2 ferrocytochrome c + 2 H+." [RHEA:11484]
xref: EC:7.1.1.8
xref: MetaCyc:RXN-15816
xref: RHEA:11484
is_a: GO:0009055 ! electron transfer activity
is_a: GO:0015078 ! proton transmembrane transporter activity
is_a: GO:0015453 ! oxidoreduction-driven active transmembrane transporter activity
is_a: GO:0016679 ! oxidoreductase activity, acting on diphenols and related substances as donors

**MITOCHONDRIAL COMPLEX IV**
id: GO:0004129
name: cytochrome-c oxidase activity
def: "Catalysis of the reaction: 4 ferrocytochrome c + O2 + 4 H+ = 4 ferricytochrome c + 2 H2O." [RHEA:11436]
xref: EC:7.1.1.9
xref: MetaCyc:CYTOCHROME-C-OXIDASE-RXN
xref: RHEA:11436
is_a: GO:0009055 ! electron transfer activity
is_a: GO:0015078 ! proton transmembrane transporter activity
is_a: GO:0015453 ! oxidoreduction-driven active transmembrane transporter activity
is_a: GO:0016675 ! oxidoreductase activity, acting on a heme group of donors

**Comment by raymond91125** [comment]
Add (back) relationships:
GO:0008137 is_a GO:0016655 oxidoreductase activity, acting on NAD(P)H, quinone or similar compound as acceptor
GO:0008137 is_a GO:0015078 ! proton transmembrane transporter activity

**Comment by raymond91125** [comment]
@sjm41 Let me know if this is insufficient. Thanks.

**Comment by sjm41** [comment]
Thanks @raymond91125. This at least makes things consistent amongst these related terms.
