### ISSUE TITLE
Missing parent - mitochondrial iron-sulfur cluster assembly complex

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27652]
This term:

id: GO:0099128
name: mitochondrial iron-sulfur cluster assembly complex
namespace: cellular_component
def: "A protein complex consisting of frataxin, cysteine desulfurase, an accessory protein and a Fe-S scaffold protein. In human these genes correspond to FXN, NFS1, ISD11 and ISCU respectively. This complex assembles Fe-S clusters onto the scaffolding protein using the substrates ferrous iron, electrons, and sulfur from l-cysteine." [PMID:27519411]
is_a: GO:0098798 ! mitochondrial protein-containing complex

should have the additional parent:

id: GO:1990229
name: iron-sulfur cluster assembly complex
namespace: cellular_component
def: "A protein complex capable of assembling an iron-sulfur (Fe-S) cluster." [GOC:bhm, PMID:17350958]
synonym: "Fe-S cluster assembly complex" NARROW [GOC:bhm]
synonym: "SufBCD complex" NARROW [GOC:bhm]
intersection_of: GO:0032991 ! protein-containing complex
intersection_of: capable_of_part_of GO:0016226 ! iron-sulfur cluster assembly
relationship: part_of GO:0005829 ! cytosol
created_by: bhm
creation_date: 2013-11-12T09:15:03Z

**Comment by sjm41** [comment]
Also, add a 'is capable of' 'GO:0031071 cysteine desulfurase activity' relation?

**Comment by ValWood** [comment]
Should it also be named  more precisely
mitochondrial [2Fe-2S] iron-sulfur cluster assembly complex

to distinguish clearly from 
[[4Fe-4S] cluster assembly ? (different pathway)

**Comment by sjm41** [comment]
WRT complex terms, I only see the two terms mentioned above, that don't mention whether they distinguish between a  [2Fe-2S] or [4Fe-2S] iron-sulfur cluster assembly, at least in their defs.  I don't know whether these existing terms are meant to be specific for one or the other, or if that's a biologically meaningful distinction we want to make in the GO - I guess I'll have to go look at the annotations and read some reviews....

**Comment by sjm41** [comment]
There is this third 'iron-sulfur cluster assembly complex' term:

id: GO:1904564
name: Nbp35-Cfd1 ATPase complex
def: "An iron-sulfur cluster assembly complex that is capable of weak ATPase activity. In yeast it consists of two subunits, Nbp35 and Cfd1." [GO_REF:0000088, GOC:bhm, GOC:rb, GOC:TermGenie, PMID:26195633]
is_a: GO:0032991 ! protein-containing complex
relationship: capable_of GO:0016887 ! ATP hydrolysis activity
relationship: capable_of_part_of GO:0016226 ! iron-sulfur cluster assembly

Interestingly, this does get classified under 'iron-sulfur cluster assembly complex'.

So, for the 'GO:0099128 mitochondrial iron-sulfur cluster assembly complex', it looks like we should add:
relationship: capable_of_part_of GO:0016226 ! iron-sulfur cluster assembly
?

**Comment by ValWood** [comment]
Also  another one
CIA complex (GO:0097361)

**Comment by ValWood** [comment]
we partly resolved 
[[2Fe-2S] cluster assembly](https://www.pombase.org/term/GO:0044571)
and
[[4Fe-4S] cluster assembly](https://www.pombase.org/term/GO:0044572)
pathways

https://www.pombase.org/term/GO:0016226
I see that 
which is how  I see that the mitochondrial one is [2Fe-2S]

**Comment by ValWood** [comment]
GPC chat says
For [2Fe-2S] cluster assembly, one common pathway involves the protein complex called the Iron-Sulfur Cluster (ISC) machinery, which is present in both prokaryotes and eukaryotes. In this pathway, the ISC machinery typically involves proteins such as IscS (cysteine desulfurase), IscU (the scaffold protein), and other accessory proteins. IscS provides the sulfur, which is derived from cysteine, and IscU acts as a scaffold for assembling the iron and sulfur atoms into the cluster.

For [4Fe-4S] cluster assembly, there are multiple pathways depending on the organism and cellular context. One well-known pathway is the nitrogen fixation (NIF) system, which is primarily found in nitrogen-fixing bacteria. Another pathway involves the NIF-like (NFL) system, which is present in certain bacteria and archaea. In eukaryotes, such as yeast and humans, the mitochondrial ISC machinery is also involved in [4Fe-4S] cluster assembly.

which I think is about right.   Iron-Sulfur Cluster (ISC) machinery is [[2Fe-2S] cluster assembly](https://www.pombase.org/term/GO:0044571)
v

**Comment by ValWood** [comment]
Sounds good. I will look at this because i think we will use iron sulfur cluster assembly as test example pathway for GO-CAM.

Note current HGNC names:

CIA complex
CFD1=NUBP2
CIAPIN1m= CIAPIN1
IOP1 CIAO3
CIA2A = CIAO2A

ISCU complex
ISD11 = LYRM4
ACPM =???

Cluster transfer complex
HSC20=HSCB
ALR= ???

**Comment by sjm41** [comment]
+[Term]
+id: GO:0120510
+name: ISA complex
+namespace: cellular_component
+def: "A protein complex capable of condensing two 2Fe–2S clusters into one 4Fe–4S center in mitochondria. In humans it consists of ISCA1, ISCA2, IBA57 and NFU1." [PMID:34660592]
+synonym: "iron-sulfur assembly complex" RELATED [PMID:34660592]
+is_a: GO:0098798 ! mitochondrial protein-containing complex
+is_a: GO:1990229 ! iron-sulfur cluster assembly complex
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27652" xsd:anyURI
+created_by: sjm
+creation_date: 2024-05-11T10:05:45Z
+

**Comment by sjm41** [comment]
Need to re-define the CIA complex since the components listed in the table 2 of PMID:34660592 are not just the complex components, but also assembly factors etc. Also add PMID:23891004 as def xref.
CIA components: CIAO1, CIAO2A, CIAO2B, CIAO3 and MMS19
Electron donors: CIAPIN1, NDOR1
Separate complex: NUBP1, NUBP2 (= Nbp35-Cfd1 ATPase complex (GO:1904564))

Should also improve synonyms and def of Nbp35-Cfd1 ATPase complex (GO:1904564)

**Comment by sjm41** [comment]
Similarly, need to remove FDX1/2 from def of ISCU complex (GO:0099128), since that is also the electron donor and not thought to be an integral part of the complex.

**Comment by sjm41** [comment]
@pgaudet I was prioritising brevity over explicitness in the term name, but I appreciate your point.  I'll see if I can change the term names in this branch to be more explicit/spelt out.

**Comment by sjm41** [comment]
Also, need to remove/qualify IBA57 and NFU1 in def of ISA complex (GO:0120510) as it's unclear if they are part of the stable ISCA1-ISCA2 complex or not. Add PMID: 33711344 and PMID: 25347204 and PMID: 29079644.

**Comment by sjm41** [comment]
Final tree:
```
iron-sulfur cluster assembly complex (GO:1990229)
   |_cytosolic [4Fe-4S] assembly scaffold complex (GO:1904564)
   |_cytosolic [4Fe-4S] assembly targeting complex (GO:0097361)
   |_mitochondrial [4Fe-4S] assembly complex (GO:0120510)
   |_mitochondrial [2Fe-2S] assembly complex (GO:0099128)
   |_IscS-IscU complex (GO:1990330)
```
