### ISSUE TITLE
Term merge: molybdopterin synthase complex & MPT synthase complex

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27655]
From the defs and annotations, I believe these are referring to the same thing.
(and note the references given below all say it's a heterotetramer, not a heterodimer).

id: GO:0019008
name: molybdopterin synthase complex
namespace: cellular_component
alt_id: GO:0019009
def: "A protein complex that possesses molybdopterin synthase activity. In E. coli, the complex is a heterotetramer consisting of two MoaD and two MoaE subunits." [GOC:mah, PMID:12571227, PMID:15709772]
subset: goslim_metagenomics
synonym: "molybdopterin converting factor complex" EXACT []
is_a: GO:0140535 ! intracellular protein-containing complex
is_a: GO:1902494 ! catalytic complex

=> EXP annotations to human MOCS2 and fly Mocs2B (= orthologs of E.coli MoaE) by ComplexPortal, UniProt and FlyBase

id: GO:1990140
name: MPT synthase complex
namespace: cellular_component
def: "A heterodimeric protein complex which catalyses sulfur transfer from the sulfur carrier subunit of MPT synthase to precursor Z to synthesize MPT as part of molybdopterin cofactor (Moco) biosynthesis. In E. coli the subunits are MoaE and MoaD; in human, MOCS2B and MOCS2A. Moco biosynthesis and its constituent molecules are evolutionarily conserved." [GOC:bhm, PMID:11135669, PMID:16669776, Reactome:R-HSA-947581]
synonym: "molybdopterin cofactor (Moco) biosynthesis sulfurtransferase complex" RELATED []
is_a: GO:1990228 ! sulfurtransferase complex
relationship: part_of GO:0005829 ! cytosol
created_by: pr
creation_date: 2013-07-11T08:32:29Z

=> EXP annotations to E.coli moaD and moaE by ComplexPortal

**Comment by deustp01** [comment]
@ukemi Didn't you work on this part of the ontology at the same time as the reorganization of glycolysis pathways? Anything to add from that?

**Comment by sjm41** [comment]
@ukemi Any objections to this one?

**Comment by pgaudet** [comment]
@raymond91125 I think this can be closed?
