### ISSUE TITLE
Term update: GO:0050547 vanillin synthase activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-ontology#27660]
GO:0050547 vanillin synthase activity has a definition xref RHEA:18725. However, RHEA:18725 is part of a multi-step rxn RHEA:62412. https://www.rhea-db.org/rhea/18725.
Also, GO:0050547 has an xref to EC:4.1.2.61 that is feruloyl-CoA hydratase/lyase, also corresponds to RHEA:62412.

Thus I propose to change GO:0050547 term label and definition to fit EC:4.1.2.61 and RHEA:62412.

**Comment by pgaudet** [comment]
Hi @raymond91125 

This is a complicated one - RHEA maps 4 reactions to EC:4.1.2.61

https://www.rhea-db.org/rhea/?query=ec:4.1.2.61 

* [RHEA:14517](https://www.rhea-db.org/rhea/14517) is part of RHEA:62412., so we should not include a mapping, but I think [RHEA:36307](https://www.rhea-db.org/rhea/36307) and [RHEA:62416](https://www.rhea-db.org/rhea/62416) should be made narrow xrefs? 
* 
Thanks, Pascale
