### ISSUE TITLE
Question mappings to GO:0008109 'N-acetyllactosaminide beta-1,6-N-acetylglucosaminyltransferase activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27677]
Hi, 

GO:0008109 'N-acetyllactosaminide beta-1,6-N-acetylglucosaminyltransferase activity' is mapped to https://enzyme.expasy.org/EC/2.4.1.150 

However that EC maps to 2 RHEA terms: 

<img width="1281" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/1dab6f1b-03cf-490c-a529-7692a64ff7a2">

but GO only maps to the RHEA with no associations. 

@kaxelsen which one should we map to? Both? 

Thanks, Pascale

**Comment by kaxelsen** [comment]
RHEA:17413 is an older more simple version of the reaction for EC 2.4.1.150. RHEA:54820 is a RHEA:17413. Just link to RHEA:54820.
