### ISSUE TITLE
NTR: expansin-mediated plant cell wall loosening

### ISSUE THREAD

**Issue by IvanTsers** [geneontology/go-ontology#27674]
* **Suggested term label:**
expansin-mediated plant cell wall loosening

* **Definition (free text)**
Non-enzymatic disruption of the non-covalent binding between cellulose microfibrils and matrix glucans (presumably, xyloglucan), mediated by expansins.

* **Reference**
PMID:11607483
PMID:11014181
PMID:26057089

* **Gene product name and ID to be annotated to this term**
I suggest adding this term to all expansins found in SwissProt.
[Here is the link to the table of proteins I'm talking about.](https://www.uniprot.org/uniprotkb?facets=reviewed%3Atrue&fields=accession%2Cgene_oln%2Creviewed%2Cprotein_name%2Corganism_name%2Cgo_id%2Corganism_id&query=expansin&view=table) (accessed on 4.21.2024)
* **Parent term(s)**
(is_a) [GO:0009828] plant-type cell wall loosening

* **Children terms (if applicable)**
None

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
RELATED [GO:0009936] obsolete expansin
BROAD biomechanical loosening
EXACT expansin action

* **Cross-references**
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR002963/
https://en.wikipedia.org/wiki/Expansin

**Comment by pgaudet** [comment]
Hi @IvanTsers 

Thanks for suggesting this. To be consistent with GO usage, we would not use "expansin-mediated", as this describes a gene product; possibly a gene product's activity in this case? Biological processes aim to represent the sum of coordinated activities between different proteins; here it seems you want to describe the function of expansins in cell growth? 

@tberardini I am curious to know how TAIR annotates expansing?

**Comment by IvanTsers** [comment]
Hi @pgaudet 

Thank you for your response. Indeed, I'd seen the "GO:0009936 obsolete expansin" that was obsoleted as describing a gene product rather than a BP. Sorry, I thought it was just about phrasing, but now that you've pointed it out, I realize that the suggested term retains the drawbacks of the obsolete expansin term.

What I tried to do was to clarify "GO:0009828 plant-type cell wall loosening". This process is a result of "sub-processes" involving both enzymes (e.g. xyloglucan endo-transglycosylase/hydrolase) and/or non-enzyme proteins (the expansins). At the same time, the loosening is not restricted to a single mechanism. The problem is, that the disruption of non-covalent bonds in the cell wall does not have its own name as an enzymatic reaction would do. And I don't see any opportunities to fit the expansins' activity into the current structure of the Molecular Function graph.

Now I agree, the proposed term is not much better than the obsolete one. 

So instead a new term, I'd like to suggest adding the term "GO:0009828 plant-type cell wall loosening" to the all SwissProt expansins (listed at the link). Now only three of them have this annotation assigned. Would that be possible?

**Comment by pgaudet** [comment]
Hi @IvanTsers 
I suggested to Swiss-Prot plant curator to annotate these.
