### ISSUE TITLE
Cross references to GO:0047442 17-alpha-hydroxyprogesterone aldolase activity need to be checked

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27671]
Following up on changes to GO:0047442 17-alpha-hydroxyprogesterone aldolase activity in 
https://github.com/geneontology/go-ontology/issues/27410

In the PR here https://github.com/geneontology/go-ontology/commit/cadb632b821aa377c796a83f92eb3b4418600428#commitcomment-140994117
EC:4.1.2.30 was updated to EC:1.14.14.32

GO:0047442 mapping to https://www.rhea-db.org/rhea/14753 was left unchanged (which may be OK); however this RHEA maps to 2 ECs: 

EC:1.14.14.19 steroid 17alpha-monooxygenase
EC:1.14.14.32 17alpha-hydroxyprogesterone deacetylase

We have another GO term that maps to [steroid 17-alpha-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0004508)

- [ ] RHEA:14753 should probably be mapped to both GO:0004508 and GO:0047442 as broadMatch

However, EC:1.14.14.19 maps to 4 RHEAs; 
https://www.rhea-db.org/rhea?query=ec%3A1.14.14.19+

Looking quickly I am not sure what the action should be , but this needs to be reviewed. 

Thanks, Pascale

**Comment by raymond91125** [comment]
Seems like a rather complicated story. Not sure I understand it.
1 gene name CYP17A1
2 EC 1.14.14.32, 1.14.14.19
4 UniProtKB groups
5 RHEA https://www.rhea-db.org/rhea?query=ec%3A1.14.14.19
Inferring from RHEA, EC 1.14.14.32 is a subclass of EC 1.14.14.19.
I think perhaps for the 2 GO terms (one for each EC), each defined by the EC reaction(s), and XREF with skos:relatedMatch to RHEAs.
What do you think? @pgaudet

**Comment by pgaudet** [comment]
It seems like all RHEA reactions associated with https://www.rhea-db.org/rhea/?query=ec:1.14.14.19
should be specific reactions of [RHEA:65760](https://www.rhea-db.org/rhea/65760): 
1. [RHEA:46308](https://www.rhea-db.org/rhea/46308)	O2 + progesterone + reduced [NADPH—hemoprotein reductase] = 17α-hydroxyprogesterone + H+ + H2O + oxidized [NADPH—hemoprotein reductase]
2. [RHEA:50236](https://www.rhea-db.org/rhea/50236)	O2 + pregnenolone + reduced [NADPH—hemoprotein reductase] = 17α-hydroxypregnenolone + H+ + H2O + oxidized [NADPH—hemoprotein reductase]
3. [RHEA:50244](https://www.rhea-db.org/rhea/50244)	17α-hydroxypregnenolone + O2 + reduced [NADPH—hemoprotein reductase] = 3β-hydroxyandrost-5-en-17-one + acetate + 2 H+ + H2O + oxidized [NADPH—hemoprotein reductase]
4. [RHEA:14753](https://www.rhea-db.org/rhea/14753)	17α-hydroxyprogesterone + O2 + reduced [NADPH—hemoprotein reductase] = acetate + androst-4-ene-3,17-dione + 2 H+ + H2O + oxidized [NADPH—hemoprotein reductase]


Since 17α-hydroxyprogesterone  and progesterone are both C21 sterols, as far as I can tell from ChEBI. Right now only RHEA:46308 and RHEA:50236 are specific forms of RHEA:65760.

@kaxelsen does that sound right? 

----

WRT GO terms - as you point out @raymond91125 these 2 ECs represent the same gene/activity (CP17A), and in ChEBI there are only 2 children of CHEBI:61313 - C21-steroid_ 

- 17α-hydroxy-C21-steroid ([CHEBI:138141](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A138141)) is a C21-steroid ([CHEBI:61313](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A61313))
- 17α-hydroxypregn-5-ene-3,20-dione ([CHEBI:63843](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A63843)) is a C21-steroid ([CHEBI:61313](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A61313))

I would propose obsoleting GO:0047442 17-alpha-hydroxyprogesterone aldolase activity (2 EXP) and replace it with the more general GO:0004508 steroid 17-alpha-monooxygenase activity
- EC:1.14.14.19 would be an exact match
- EC:1.14.14.32 would be a narrow match
- RHEA:65760 seems the appropriate exact match. Other RHEA reactions would hopefully be specific reactions of RHEA:65760 (see above). 

What do you think?

**Comment by sjm41** [comment]
You're probably aware, but FYI in case it helps:

1. I see GO:0047442 has only been used in 3 EXP annotations, so could check the 2 associated pubs in case they help - PMID:25533464, PMID:24140098
2. I find that the hand-written MetaCyc summaries can sometimes help (assuming you have access....):
https://biocyc.org/META/NEW-IMAGE?type=EC-NUMBER&object=EC-1.14.14.19
https://biocyc.org/META/NEW-IMAGE?type=EC-NUMBER&object=EC-1.14.14.32

**Comment by pgaudet** [comment]
Copying the relevant part of the MEtCyc comment 

> A microsomal cytochrome P-450 (heme-thiolate) protein that catalyses two independent reactions at the same active site 

So, as per GO's guidelines, this would be a single term.

**Comment by raymond91125** [comment]
![image](https://github.com/geneontology/go-ontology/assets/619520/eeec82ff-fe9f-4b4b-a91b-77869e746326)
PMID:31362062 Essential accessory proteins are also indicated: cytochrome b5 (b5); cytochrome P450 oxidoreductase (POR); ferredoxin (FDX); ferredoxin reductase (FDXR); hexose-6-phosphate dehydrogenase (H6PDH); PAPS synthase 2 (PAPSS2); steroidogenic acute regulatory protein (StAR).
