### ISSUE TITLE
NTR: nitrate reductase (quinone)

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27675]
Hi @sjm41 @raymond91125 

Following up on https://github.com/geneontology/go-ontology/issues/25967
I think we want to create a GO term for EC:1.7.5.1 nitrate reductase (quinone)
RHEA:56144 

I didn't see in the other ticket why we shouldn't. There seem to exist proteins with this specific activity, for example https://www.uniprot.org/uniprotkb/P0AF32/entry.

Thanks, Pascale

**Comment by sjm41** [comment]
Sounds fine to me.
It would be worth letting the appropriate community (@dsiegele ?) know about this new term to ensure it gets used!

**Comment by pgaudet** [comment]
It should at least get automated RHEA annotations

**Comment by pgaudet** [comment]
But of course, manual would be much better!!

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160182
+name: nitrate reductase (quinone) activity
+namespace: molecular_function
+def: "Catalysis of the reaction: a quinol + nitrate = a quinone + H2O + nitrite." [RHEA:56144]
+synonym: "dissimilatory nitrate reductase" RELATED [EC:1.7.5.1]
+synonym: "dissimilatory nitrate reductase activity" RELATED [EC:1.7.5.1]
+synonym: "nitrate reductase A activity" RELATED [EC:1.7.5.1]
+synonym: "nitrate reductase Z activity" RELATED [EC:1.7.5.1]
+synonym: "quinol-nitrate oxidoreductase activity" RELATED [EC:1.7.5.1]
+xref: EC:1.7.5.1
+xref: RHEA:56144
+is_a: GO:0008940 ! nitrate reductase activity
+is_a: GO:0052586 ! oxidoreductase activity, acting on other nitrogenous compounds as donors, with a quinone or similar compound as acceptor
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27675" xsd:anyURI
+created_by: rynl
+creation_date: 2024-04-24T22:45:01Z
+
