### ISSUE TITLE
Missing parent: exchange factors

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27684]
* **GO term ID and label for which you request a new superclass**

should these have a common parent?
<img width="919" alt="Screenshot 2024-04-22 at 11 36 59" src="https://github.com/geneontology/go-ontology/assets/7359272/f120b071-5191-4d74-a158-608b0b2dac50">

* **New superclass (parent) suggested**

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by pgaudet** [comment]
I fixed the logical definition of GO:0000774  adenyl-nucleotide exchange factor activity
to match that of [guanyl-nucleotide exchange factor activity](http://purl.obolibrary.org/obo/GO_0005085): 
+intersection_of: GO:0060590 ! ATPase regulator activity
+intersection_of: directly_negatively_regulates GO:0043531 ! ADP binding
+intersection_of: directly_positively_regulates GO:0005524 ! ATP binding

**Comment by pgaudet** [comment]
Both are under 'molecular function regulator activity' (although in your screenshot we mostly see the 'binding' parents). 

Is it useful to have a 2-term grouping class? (generally I dont think it's useful to have so many intermediate levels, it often leads to too-general annotation)

**Comment by ValWood** [comment]
Maybe it isn't useful, but it seems odd  that they are doing the same thing but they are not close.

**Comment by pgaudet** [comment]
The changes in logical definitions should make the parentage more consistent.
