### ISSUE TITLE
NTR: DNA helicase inhibitor activity

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-ontology#27686]
Please provide as much information as you can: 

Suggested term label: DNA helicase inhibitor activity

Definition: Binds to and stops, prevents or reduces the activity of a DNA helicase.

Reference, in format PMID: 38613387

Gene product name and ID to be annotated to this term: 
CDC13/YDL220C (S000002379)  in S. cerevisiae, CPX-15

Parent term(s): [GO:0004857 enzyme inhibitor activity](https://amigo.geneontology.org/amigo/term/GO:0004857#display-lineage-tab)

No child terms

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
This term is needed since negative regulation of DNA helicase activity is now 'Do Not Annotate'

**Comment by pgaudet** [comment]
@edwong57 feel free to create the term if you have time.

**Comment by edwong57** [comment]
@pgaudet, ok, thanks!

**Comment by edwong57** [comment]
Sorry, @pgaudet. Now that I'm looking more closely at the related terms and definitions, I don't think this term is needed, yet. Cdc13 doesn't actually bind to the the helicase to prevent the activity. It binds to the DNA, physically preventing the helicase from binding to do the unwinding. All the definitions for the molecular function regulator activity say specifically that the gene product 'binds to'. I think I can use [GO:1905463](https://amigo.geneontology.org/amigo/term/GO:1905463): negative regulation of DNA duplex unwinding instead.
