### ISSUE TITLE
Ontology build allows erroneous entries into subsets

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#27687]
From @suzialeksander , from Alliance query.

```obo
[Term]
id: GO:0009059
name: macromolecule biosynthetic process
namespace: biological_process
alt_id: GO:0043284
def: "The chemical reactions and pathways resulting in the formation of a macromolecule, any molecule of high relative molecular mass, the structure of which essentially comprises the multiple repetition of units derived, actually or conceptually, from molecules of low relative molecular mass." [GOC:mah]
comment: Note that this term is in the subset of terms that should not be used for direct gene product annotation. Instead, select a child term or, if no appropriate child term exists, please request a new term. Direct annotations to this term may be amended during annotation QC.
subset: gocheck_do_not_annotate
subset: goslim_pir
subset: https://github.com/geneontology/go-ontology/issues/27189
synonym: "biopolymer biosynthetic process" EXACT [GOC:mtg_chebi_dec09]
synonym: "macromolecule anabolism" EXACT []
synonym: "macromolecule biosynthesis" EXACT []
synonym: "macromolecule formation" EXACT []
synonym: "macromolecule synthesis" EXACT []
is_a: GO:0043170 ! macromolecule metabolic process
is_a: GO:0044249 ! cellular biosynthetic process
is_a: GO:1901576 ! organic substance biosynthetic process
property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/15249 xsd:anyURI
property_value: term_tracker_item https://github.com/geneontology/go-ontology/issues/25418 xsd:anyURI
```
Is this legal? Specifically, the GH URL for subset.
Noting:
```sjcarbon@moiraine:/tmp$:) grep subset: go.obo | sort | uniq -c
   1685 subset: gocheck_do_not_annotate
     53 subset: goslim_agr
     86 subset: goslim_candida
    296 subset: goslim_chembl
    173 subset: goslim_drosophila
     61 subset: goslim_euk_cellular_processes_ribbon
     44 subset: goslim_flybase_ribbon
    141 subset: goslim_generic
    111 subset: goslim_metagenomics
     45 subset: goslim_mouse
    441 subset: goslim_pir
     97 subset: goslim_plant
     62 subset: goslim_plant_ribbon
     61 subset: goslim_pombe
     97 subset: goslim_prokaryote
     49 subset: goslim_prokaryote_ribbon
    357 subset: goslim_synapse
    163 subset: goslim_yeast
      1 subset: https://github.com/geneontology/go-ontology/issues/27189
```

Expression in AmiGO:

![image](https://github.com/geneontology/go-ontology/assets/2687900/91a0643c-0a1b-4e11-9620-afd262bdd26c)

**Comment by kltm** [comment]
Also tagging @pgaudet

**Comment by suzialeksander** [comment]
Noting here that this broke *something*, not sure what, at the Alliance.

**Comment by kltm** [comment]
It looks like @balhoff may have gotten to this earlier today https://github.com/geneontology/go-ontology/pull/27634/files

@balhoff can you confirm?

That said, this would have gotten into the `release` and `snapshot`s we just did. @pgaudet considering that this is causing problems for consumers, is it worth getting another release out soon?

**Comment by kltm** [comment]
Origin of issue: https://github.com/geneontology/go-ontology/commit/af506e4a8a7b7717aca67b0a410791da6e73ef5d

**Comment by kltm** [comment]
@suzialeksander Regardless, the most recent (and healthier in this case) ontology build should be available with the rolling build.
https://wiki.geneontology.org/Rolling_build_of_the_Gene_Ontology
https://ontology-build.geneontology.org/
The next `snapshot` would also have the fix.

**Comment by balhoff** [comment]
Oh no, it's too bad I missed this release! I opened the PR several days ago but forgot to merge it because I was traveling. I also have a check for this implemented but it isn't quite merged yet. This is going to cause problems for folks using the old OBO parser, including ZFIN.

**Comment by cmungall** [comment]
@balhoff in order to prevent this in future, there is already a robot check - did we deliberately suppress this?

https://github.com/ontodev/robot/edit/master/robot-core/src/main/resources/report_queries/missing_subset_declaration.rq

**Comment by balhoff** [comment]
@cmungall the Makefile runs `robot verify` with a list of SPARQL queries, but not `robot report`. Unfortunately I never noticed the distinction until now. ☹️

**Comment by kkarra** [comment]
It appear not just for subset:  but in other places as well where it doesn't seem to make sense. 

this type of URL is used in **comment:  subset: synonym: and xref:**  — am guessing it is valid only for comment but not these other categories.

**Comment by pgaudet** [comment]
OK with me if you want to make another release. 

Many sources are still unchanged, reducing the likelihood that there will be problems. 

Thanks, Pascale

**Comment by ValWood** [comment]
oh crap sorry that was me
subset: https://github.com/geneontology/go-ontology/issues/27189
can we have a check for text in that field?

**Comment by balhoff** [comment]
@ValWood we've got a check now.

**Comment by ValWood** [comment]
.....sorry!
