### ISSUE TITLE
Question on Revised D-glucosamine PTS permease activity,

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27694]
Hi @raymond91125 

For  #27410 you updated GO:0103111  D-glucosamine PTS permease activity to narrowEC xref: [2.7.1.191] (https://enzyme.expasy.org/EC/2.7.1.191) (protein-N(pi)-phosphohistidine--D-**mannose** phosphotransferase)

How did you choose that one? Given that the previous EC matches many new ECs: 
Transferred entry: [2.7.1.191](https://enzyme.expasy.org/EC/2.7.1.191)
Transferred entry: [2.7.1.192](https://enzyme.expasy.org/EC/2.7.1.192)
Transferred entry: [2.7.1.193](https://enzyme.expasy.org/EC/2.7.1.193)
Transferred entry: [2.7.1.194](https://enzyme.expasy.org/EC/2.7.1.194)
Transferred entry: [2.7.1.195,2.7.1.196](https://enzyme.expasy.org/EC/2.7.1.195,2.7.1.196)
Transferred entry: [2.7.1.197](https://enzyme.expasy.org/EC/2.7.1.197)
Transferred entry: [2.7.1.198](https://enzyme.expasy.org/EC/2.7.1.198)
Transferred entry: [2.7.1.199](https://enzyme.expasy.org/EC/2.7.1.199)
Transferred entry: [2.7.1.200](https://enzyme.expasy.org/EC/2.7.1.200)
Transferred entry: [2.7.1.201,2.7.1.202](https://enzyme.expasy.org/EC/2.7.1.201,2.7.1.202)
Transferred entry: [2.7.1.203](https://enzyme.expasy.org/EC/2.7.1.203)
Transferred entry: [2.7.1.204](https://enzyme.expasy.org/EC/2.7.1.204)
Transferred entry: [2.7.1.205](https://enzyme.expasy.org/EC/2.7.1.205)
Transferred entry: [2.7.1.206](https://enzyme.expasy.org/EC/2.7.1.206)
Transferred entry: [2.7.1.207](https://enzyme.expasy.org/EC/2.7.1.207)
Transferred entry: [2.7.1.208](https://enzyme.expasy.org/EC/2.7.1.208)

Also, the EC you picked corresponds to a RHEA that is different from the one we have a the GO term. 

- EC:2.7.1.191 is mapped by RHEA to [RHEA:49232](https://www.rhea-db.org/rhea/49232)	D-mannose(out) + Nπ-phospho-L-histidyl-[protein] = D-mannose 6-phosphate(in) + L-histidyl-[protein]
- GO:0103111  D-glucosamine PTS permease activity maps to RHEA:37359 (no EC mapped), in which glucosamine is a substrate, which seems more consistent with the GO term. 

Can you confirm that this is the correct new EC mapping for this term?

**Comment by raymond91125** [comment]
Because of MetaCyc https://www.biocyc.org/reaction?orgid=META&id=TRANS-RXN-167A.
RHEA:37539 is an XREF but it doesn't specify the protein being a PTS enzyme. Thus I am not sure if RHEA should be used to replace the definition.

**Comment by pgaudet** [comment]
I'll put this on next Monday's agenda. I would like to understand how you selected MetaCyc as the source of truth here - and how that relates to the changes you've implemented. 

Originally there were 3 xrefs: 
xref: EC:2.7.1.69
xref: MetaCyc:TRANS-RXN-167A
xref: RHEA:37359

And you changed EC:2.7.1.69 to EC:2.7.1.191, and left the other two cross references. 
Also, MetaCyc mentions mannose and the GO def mentions glucosamine. 

MetaCyc has this comment: "Note that this reaction equation differs from the official Enzyme Commission reaction equation for this EC entry, which can be found [her](http://metacyc.ai.sri.com/reaction?orgid=META&id=RXN-15087)" 

For reference, changes are here: https://github.com/geneontology/go-ontology/pull/27688/commits/d3b519ba4f4ea6c10517e5bdfa90e269c3df2da7

Thanks, Pascale

**Comment by raymond91125** [comment]
EC 2.7.1.193, RHEA:49240
