### ISSUE TITLE
Missing parent: autophagosome adaptor activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#27704]
Note editted from original:
* **New Parent term suggested term label:**
*  autophagosome adaptor activity
* is_a protein-membrane adaptor activity GO:0043495

* * **Definition (free text)**
The binding activity of a molecule that brings together a target membrane and an autophagosome during autophagy. 

Ref: PMID:30544615 has a good summary of these adaptors

* **Children terms (if applicable)** 
* (NEW) endoplasmic reticulum autophagosome adaptor activity
* GO:0140580 mitochondrion autophagosome adaptor activity

------

Add synonym for: endoplasmic reticulum-autophagosome adaptor activity GO:0140506

* ER-phagy receptor (EXACT)

**Comment by ValWood** [comment]
A grouping term would be useful
https://www.pombase.org/term/GO:0140580
mitochondrion autophagosome adaptor activity (GO:0140580)
there may be others....

**Comment by hattrill** [comment]
@ValWood - Yes, that is it! Could not find it yesterday. I will just change this to add a parent as probably are other selective autophagy process that have specific receptors, plus add some synonyms for endoplasmic reticulum-autophagosome adaptor activity

**Comment by hattrill** [comment]
From PMID:30544615 looks like there are others:
<img width="870" alt="Screenshot 2024-04-24 at 08 45 30" src="https://github.com/geneontology/go-ontology/assets/11865746/84c7b5c8-4468-4fe2-bb98-7558835ae5b4">

I will have a look later and see if there are some other adaptor terms that should be made.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160183
+name: autophagosome adaptor activity
+namespace: molecular_function
+def: "The binding activity of a molecule that brings together a target membrane and an autophagosome during mitophagy." [PMID:30544615]](def: "The binding activity of a molecule that brings together a target membrane and an autophagosome during mitophagy." [PMID:30544615, PMID:36635405]
+is_a: GO:0043495 ! protein-membrane adaptor activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27704" xsd:anyURI
+created_by: rynl
+creation_date: 2024-04-25T00:20:20Z

**Comment by pgaudet** [comment]
For consistency with neighboring terms, should we not name this "autophagosome-**membrane** adaptor activity"? all other adaptor terms name the two things they adapt.
