### ISSUE TITLE
PAS complex - wrong parent

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27700]
The following term currently has "is_a: GO:0035032 ! phosphatidylinositol 3-kinase complex, class III", but the term def (and the cited papers) say the complex has "phosphatidylinositol-3-phosphate 5-kinase" activity (i.e. not a "phosphatidylinositol-phosphate **3**-kinase" activity.)

- [x] So I think the parent will have to go up one level, to "transferase complex, transferring phosphorus-containing groups".

- [x] Also change def bit that says "A class III phosphatidylinositol 3-kinase complex that..." to "A phosphatidylinositol kinase complex that..."

(previous discussion of this term is in #11120)

id: GO:0070772
name: PAS complex
namespace: cellular_component
def: "A class III phosphatidylinositol 3-kinase complex that contains a phosphatidylinositol-3-phosphate 5-kinase subunit (Fab1p in yeast; PIKfyve in mammals), a kinase activator, and a phosphatase, and may also contain additional proteins; it is involved in regulating the synthesis and turnover of phosphatidylinositol 3,5-bisphosphate. In mammals the complex is composed of PIKFYVE, FIG4 and VAC14. In yeast it is composed of Atg18p, Fig4p, Fab1p, Vac14p and Vac7p." [PMID:18950639, PMID:19037259, PMID:19158662]
synonym: "autophagy-specific phosphatidylinositol 3-kinase complex" RELATED [PMID:24165940]
is_a: GO:0035032 ! phosphatidylinositol 3-kinase complex, class III
relationship: part_of GO:0005773 ! vacuole
relationship: part_of GO:0005774 ! vacuolar membrane
relationship: part_of GO:0016020 ! membrane
created_by: mah
creation_date: 2009-06-30T11:13:32Z

**Comment by pgaudet** [comment]
No objection, but I am not too familiar with these complexes.
