### ISSUE TITLE
Taxon constraint: GO:0015039 | NADPH-adrenodoxin reductase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27715]
Please provide as much information as you can: 

* **GO term ID label:**

These annotations are still present, I will raise a taxon restriction for
GO:0015039 | NADPH-adrenodoxin reductase activity
I need to double check species distribution. Andredoxin seems to be present in some fungi, but not pombe or cerevisiae.

* **Request to add a taxon constraint:**
* * **only in taxon: **
* * **never in taxon: **

* **Request to remove a taxon constraint:**
Please specify

* **Supporting evidence if available (e.g PMID):**

**Comment by ValWood** [comment]
From a quick glance, adrenodoxin reductase seems to be a gene-product specific name for ferridoxin-reductase?

<img width="353" alt="Screenshot 2024-04-24 at 09 35 04" src="https://github.com/geneontology/go-ontology/assets/7359272/bb406251-48bc-47a3-be16-cbe5f6f8f00f">

NADPH-adrenodoxin reductase activity also has a comment:
Note that this term specifically refers to the reaction proceeding in the direction shown; under physiological conditions adrenodoxin reduction by adrenodoxin reductase is coupled with electron transfer from AdR to P450, which catalyzes an irreversible monooxygenation reaction. This term should therefore be used to annotate gene products that catalyze the reduction of oxidized adrenodoxin; also consider annotating to the molecular function term 'ferredoxin-NADP+ reductase activity; GO:0004324'.

I haven't yet found out exactly which cytochrome  adrenodoxin refers to and if yeast have it. I keep finding adrenodoxin == ferridoxin...

**Comment by ValWood** [comment]
@deustp01 do you know anything about 
NADPH-adrenodoxin reductase activity

**Comment by deustp01** [comment]
My vague overview understanding is that many enzymes that mediate oxidation-reductiion reactions on small-molecule substrates (sterols and drugs are popular ones) have bound cofactors like iron-sulfur clusters and others I know even less about, that are reduced-oxidized in the course of the reaction. That of course inactives the enzyme. For reactivation it needs to undergo a reaction in which that bound cofactor is re-oxidized or re-reduced. Adrenodoxins (which also definitely exist in mammals - see [this UniProt entry for a human one](https://www.uniprot.org/uniprotkb/P22570/entry)), and examine its first linked RHEA reaction](https://www.rhea-db.org/rhea/42312).

Beyond that, I am also still struggling to understand how these things work.

**Comment by ValWood** [comment]
Since adrenodoxin appears to be a speicific type of ferridoxin, found in adrenal cells, I will add a taxon restriction for fungi

**Comment by pgaudet** [comment]
There already is a TC - did you forget to link the ticket when you did the work? 

Thanks, Pascale

**Comment by ValWood** [comment]
I probably did it when I was trying to edit  taxon constraints in VSC (which meant they got pulled into a pull request , but might not of had a term tracker item)
I now do these in the web editor again, which is OK, and easier to keep track of  I think my issue was that I didn't realise there was a final tab in the file!

Anyway closing this. I still think this should probably be is_a ferredoxin but  I'll leave that to somebody who knows more.....
