### ISSUE TITLE
pentose-phosphate shunt, non-oxidative branch

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27719]
The following term has a textual def saying that the pathway starts with "ribulose 5-P", which agrees with the given MetaCyc xrefs.

But the LD has:
**intersection_of: has_primary_input CHEBI:78679 ! D-ribose 5-phosphate**
which is the second metabolite in the pathway.

Looks like that should be changed to:
has_primary_input CHEBI:58121 ! D-ribulose 5-phosphate(2-)

@ukemi @deustp01 ?
@rozaru

id: GO:0009052
name: pentose-phosphate shunt, non-oxidative branch
namespace: biological_process
def: "The branch of the pentose-phosphate shunt which does not involve oxidation reactions. It comprises a series of sugar phosphate interconversions, starting with ribulose 5-P and producing fructose 6-P and glyceraldehyde 3-P." [ISBN:0198506732, MetaCyc:NONOXIPENT-PWY]
synonym: "pentose phosphate pathway, non-oxidative branch" EXACT []
synonym: "pentose phosphate shunt, non-oxidative branch" EXACT []
synonym: "pentose-phosphate pathway, non-oxidative branch" EXACT []
xref: MetaCyc:NONOXIPENT-PWY
xref: MetaCyc:PWY-8178
is_a: GO:0006091 ! generation of precursor metabolites and energy
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_part GO:0004750 ! D-ribulose-phosphate 3-epimerase activity
intersection_of: has_part GO:0004751 ! ribose-5-phosphate isomerase activity
intersection_of: has_part GO:0004801 ! transaldolase activity
intersection_of: has_part GO:0004802 ! transketolase activity
intersection_of: has_primary_input CHEBI:78679 ! D-ribose 5-phosphate
intersection_of: has_primary_output CHEBI:58027 ! glyceraldehyde 3-phosphate(2-)
intersection_of: has_primary_output CHEBI:78697 ! D-fructose 6-phosphate
relationship: part_of GO:0006098 ! pentose-phosphate shunt
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27107" xsd:anyURI

**Comment by ukemi** [comment]
This seems perfectly reasonable. Let's also have a look at any existing pathways to see if they need modification. This would be a good thing to coordinate. I can make the mouse model/s if it/they haven't been made yet. Shall we make a plan on the weeds call?

**Comment by rozaru** [comment]
For the same pathway:
GO term [pentose-phosphate shunt, oxidative branch](https://www.ebi.ac.uk/QuickGO/term/GO:0009051) maybe has_primary_input CHEBI:58121 ! D-ribulose 5-phosphate(2-) could be added as well?

I am not able to see the logical definition for a GO term so this is based of what I see on QuickGO.

**Comment by sjm41** [comment]
You can see the LDs in the 'bleeding-edge' go-edit.obo file, which is here:
https://raw.githubusercontent.com/geneontology/go-ontology/master/src/ontology/go-edit.obo

Here's how the current entry looks:
id: GO:0009051
name: pentose-phosphate shunt, oxidative branch
namespace: biological_process
def: "The branch of the pentose-phosphate shunt which involves the oxidation of glucose 6-P and produces ribulose 5-P, reduced NADP+ and carbon dioxide (CO2)." [ISBN:0198506732, MetaCyc:OXIDATIVEPENT-PWY]
synonym: "oxidative branch, pentose pathway" EXACT []
synonym: "oxidative pentose phosphate pathway" EXACT []
synonym: "pentose phosphate pathway, oxidative branch" EXACT []
synonym: "pentose phosphate shunt, oxidative branch" EXACT []
synonym: "pentose-phosphate pathway, oxidative branch" EXACT []
xref: MetaCyc:OXIDATIVEPENT-PWY
xref: MetaCyc:PWY-7796
is_a: GO:1901135 ! carbohydrate derivative metabolic process
intersection_of: GO:0008152 ! metabolic process
intersection_of: ends_with GO:0004616 ! phosphogluconate dehydrogenase (decarboxylating) activity
intersection_of: has_part GO:0004341 ! gluconolactonase activity
intersection_of: has_primary_input CHEBI:58247 ! beta-D-glucose 6-phosphate(2-)
intersection_of: has_primary_input CHEBI:58349 ! NADP(3-)
intersection_of: has_primary_output CHEBI:57783 ! NADPH(4-)
intersection_of: starts_with GO:0004345 ! glucose-6-phosphate dehydrogenase activity
relationship: part_of GO:0006098 ! pentose-phosphate shunt
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27107" xsd:anyURI

Did you mean you wanted "has_primary_**output** CHEBI:58121 ! D-ribulose 5-phosphate(2-)" ?

**Comment by rozaru** [comment]
yes!  it should be "has_primary_output CHEBI:58121 ! D-ribulose 5-phosphate(2-)"

**Comment by sjm41** [comment]
As discussed on our call, I'll update  D-ribose 5-phosphate to D-ribulose 5-phosphate(2-) for GO:0009052, but leave GO:0009051 alone (since the LD is 'necessary and sufficient' as it stands).

**Comment by sjm41** [comment]
Finally, change this:
intersection_of: has_primary_output CHEBI:78697 ! D-fructose 6-phosphate
to this:
intersection_of: has_primary_output CHEBI:57634 ! beta-D-fructofuranose 6-phosphate(2-)

to make it a pH 7.3 form, consistent with the RHEA participant on the corresponding GO MF terms:
GO:0004801transaldolase activity
GO:0004802transketolase activity
