### ISSUE TITLE
NTR: negative regulation of midbody abscission

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#27722]
Please provide as much information as you can: 

* **Suggested term label:**

negative regulation of midbody abscission

* **Definition (free text)**
Any process that stops, prevents, or reduces the frequency, rate or extent of midbody abscission. 

24814515 

* **Reference, in format PMID:#######**
24814515 and others (see link below)

* **Gene product name and ID to be annotated to this term**
see
https://www.ebi.ac.uk/QuickGO/annotations?goId=GO:0009838&goUsageRelationships=is_a,part_of,occurs_in&goUsage=descendants&taxonId=40674&taxonUsage=descendants&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

* **Parent term(s)**

GO:0061952
GO:0048519

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
Hi @Antonialock  these seem to be part_of abscission rather than regulation (i.e  within pathway regulation).
(although they may exert a negative effect)

**Comment by Antonialock** [comment]
ok, I moved the mammalian abscission annotations to midbody abscission.
