### ISSUE TITLE
Enzymatic complexes lacking a 'capable of' relation

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27727]
While reviewing annotations to fly metabolic enzyme complexes, I noticed that while most of the corresponding terms have a useful 'capable of X activity' relation in their definition, the terms listed below do not.

Question: I see two types of 'capable of X activity' relations in the obo file:
i) "relationship: capable_of X" (e.g. GO:0045271 respiratory chain complex I)
ii) "intersection_of: capable_of X" (e.g. GO:0045275 respiratory chain complex III)

Do they appear like (i) if this is asserted, and like (ii) if they are inferred?

---
aminoacyl-tRNA synthetase multienzyme complex ; GO:0017101
- [x] add aminoacyl-tRNA ligase activity GO:0004812
---
EKC/KEOPS complex ; GO:0000408
- [x] add N(6)-L-threonylcarbamoyladenine synthase activity GO:0061711
---
glutamyl-tRNA(Gln) amidotransferase complex ; GO:0030956
- [x] add glutaminyl-tRNA synthase (glutamine-hydrolyzing) activity GO:0050567
---
respiratory chain complex IV ; GO:0045277
- [x] add cytochrome-c oxidase activity GO:0004129
---
molybdopterin synthase complex ; GO:0019008
- [x] molybdopterin synthase activity GO:0030366
---
N-terminal protein acetyltransferase complex GO:0031414
- [x] add peptide alpha-N-acetyltransferase activity (GO:00045960)

**Comment by pgaudet** [comment]
Hi @sjm41 

There is some documentation here: https://wiki.geneontology.org/Guidelines_for_logical_definitions (that needs some work, as usual). But t answer the first question: 

> Question: I see two types of 'capable of X activity' relations in the obo file:
i) "relationship: capable_of X" (e.g. GO:0045271 respiratory chain complex I)
ii) "intersection_of: capable_of X" (e.g. GO:0045275 respiratory chain complex III)

In the OBO file, what you see as **"relationship:"** blahblah' is an asserted relation, and what you see as **"intersection_of:"** blahblah is a logical definition/equivalence axiom.
