### ISSUE TITLE
Change ferritin complex (GO:0070288) and intracellular ferritin complex (GO:0008043) definitions

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#27758]
Hello,

The definition of ferritin complex, GO:0070288, says: "A protein complex that binds iron and acts as a major iron storage system. Intracellular and extracellular ferritin complexes have different ratios of two types of ferritin monomer, the L (light) chain and H (heavy) chain."
In eukaryotes only the heavy chain has ferroxidase activity.

This is not true for ferritin complexes in bacteria, where they are often but not always homooligomers, and at least in Pseudomonas aeruginosa both subunits have ferroxidase activty, see this review PMID 37451083. In P.aeruginosa the ratio of the 2 types of subunit (which are not called light and heavy) varies with oxygen content of the growth medium.
I'd like to suggest removing the second sentence in the definition, which would make it easier to apply to organisms with only 1 type of storage protein, or where the stoichiometry is unknown or where they have other names.
"A protein complex that binds iron and acts as a major iron storage protein."

Similarly in GO:0008043, intracellular ferritin complex, change to
"A ferritin complex located in the cell. Intracellular ferritin complexes contain 24 subunits."

I usually only annotate bacteria and archaea, and to my (limited) knowledge they don't have extracellular ferritin complexes, so I don't know if that definition (GO:0070289) needs changing or not.
Thanks,
Andrea

**Comment by pgaudet** [comment]
Hi @AndreaAuchincloss 

Looking at a few reviews: https://pubmed.ncbi.nlm.nih.gov/33881539/ and https://pubmed.ncbi.nlm.nih.gov/26825805/


In this paper, https://pubmed.ncbi.nlm.nih.gov/20304033/ that authors state that 
> The ratio of H to L subunits within the assembled ferritin protein varies depending on tissue type and developmental stage. 

So this is not limited to extracellular versus intracellular ferritin. 


From https://pubmed.ncbi.nlm.nih.gov/33881539/: 
> The ferritin protein superfamily can be divided into three major subclasses: the classical ferritins (Ftn), the heme-containing bacterioferritins (Bfr) and the DNA-binding proteins from starved cells (Dps). Ftn and Bfr are made of 24 subunits, whereas Dps are smaller with 12 subunits. Ftn is found in plants, bacteria and animals, while Bfr and Dps are
restricted to prokaryotes.

Also, all annotations are to  GO:0008043 intracellular ferritin complex (there are none to the parent "ferritin complex"or to the sibling "GO:0070289 extracellular ferritin complex"

Based on this, I see no evidence that the intracellular and extracellular forms are distinguishable, so it seems like these terms are mixing a complex and its location. I would propose merging both terms into the parent  ferritin complex (GO:0070288), and update the definition to "A protein complex that binds iron and acts as a major iron storage system. There are three major subclasses of ferritins: the classical ferritins (Ftn), the heme-containing bacterioferritins (Bfr) and the DNA-binding proteins from starved cells (Dps). Ftn and Bfr are made of 24 subunits, whereas Dps are smaller with 12 subunits. Ftn is found in plants, bacteria and animals, while Bfr and Dps are restricted to prokaryotes."


What do you think ? 

Thanks, Pascale
