### ISSUE TITLE
Add response to terms to gocheck_obsoletion_candidate

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27762]
Hey, Ontobot! apply:

* add GO:0042221 to subset gocheck_obsoletion_candidate
*  add GO:0010033 to subset gocheck_obsoletion_candidate
* add GO:1901698 to subset gocheck_obsoletion_candidate
* add GO:0010243 to subset gocheck_obsoletion_candidate
* add GO:1901700 to subset gocheck_obsoletion_candidate
* add GO:0030003 to subset gocheck_obsoletion_candidate
* add GO:0016043 to subset gocheck_obsoletion_candidate

**Comment by pgaudet** [comment]
I think the subset is not in the ontology products yet.

**Comment by balhoff** [comment]
@pgaudet instead of:

- `Hey, Ontobot! apply:`

use:

- `Hey Ontobot! apply:` (no comma)

I just tested this out (I also didn't capitalize "ontobot" but I think that's okay).
