### ISSUE TITLE
Missing parent: GO:1905318  meiosis I spindle assembly checkpoint signaling

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27765]
* **GO term ID and label for which you request a new superclass**

GO:1905318   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:1905318/complete)
meiosis I spindle assembly checkpoint signaling

* **New superclass (parent) suggested**

GO:0060629   regulation of homologous chromosome segregation
(this is "regulation of homologous chromosome segregation" so I can add this as an exact synonym?)

remove parent
GO:0051755 meiotic sister chromatid arm separation

GO:0060629   regulation of homologous chromosome segregation
should be is_a
GO:1905132  regulation of meiotic chromosome separation

(there are a lot of terms in this branch which could be removed later but I want to make the inferences correct for modelling)

**Comment by ValWood** [comment]
need "negative regulation of homologous chromosome segregation"

**Comment by ValWood** [comment]
for now I removed
GO:0051755 meiotic sister chromatid arm separation
but the rest needs a more consistent overhaul. It's a mess and I don't know how we should deal with checkpoints but  we probably should not encode the processes they regulate  in the ontology...

**Comment by pgaudet** [comment]
Can this close?

**Comment by ValWood** [comment]
yes its for the future
