### ISSUE TITLE
Taxon constraint:  isoprenoid pathways

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27778]
Please provide as much information as you can: 

<img width="550" alt="pathway taxon restrictions" src="https://github.com/geneontology/go-ontology/assets/7359272/0dc0a6ef-dae2-41a5-9e58-e82e5733a239">

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5031371/

* **GO term ID label:**

* **Request to add a taxon constraint:**
* * **only in taxon: **
* * **never in taxon: **

* **Request to remove a taxon constraint:**
Please specify

* **Supporting evidence if available (e.g PMID):**

**Comment by amandamackie** [comment]
Thanks, GO:1902767 is an incorrect annotation in EcoCyc and I've removed it

Amanda
________________________________
