### ISSUE TITLE
Change label GO:0106259 cell-to-cell migration in host to symbiont-mediated cell-to-cell migration in host

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27786]
Change label GO:0106259 cell-to-cell migration in host to symbiont-mediated cell-to-cell migration in host

For GO-PATHGO alignment (and for consistency)

@genegodbold to provide more references

**Comment by genegodbold** [comment]
- **Movement and RNA silencing protein** from Banana bunchy top virus (BBTV): This movement protein of 117 residues transports the viral genome to neighboring plant cells through plasmosdesmata, without any budding necessary. This allows cell to cell propagation, bypassing the host cell wall barrier. A begomovirus genome is shuttled out of nucleus by host nuclear shuttle protein (NSP) and the viral movement protein transports the DNA-NSP complex to cell plasmodesmata and facilitates further movement across the cell wall. [PMID:19816653]
- **Intracellular spread A** (IcsA, VirG) from _Shigella flexneri_: The IcsA protein is localized to the outer membrane of the Shigella bacterium in a polarized distribution, with the highest concentration at the pole from which actin polymerizes.  It is essential for the motility of _S. flexneri_ in infected cells [PMID:15694855]. IcsA activates the host actin-regulatory protein N-WASP which in turn recruits the Arp2/3 complex which nucleates host actin to initiate bacterial motility [PMID:18456802]
- **A36** from vaccinia virus: Phosphorylation of vaccinia virus protein A36 at Tyr112 and  Tyr132 is necessary for the recruitment of host Grb2 which stabilizes a protein complex consisting of host Nck, WIP, and N-WASP beneath the virus. This eventually stimulates the actin-nucleating activity of the host Arp2/3 complex resulting in the formation of an actin tail and projecting a virion into neighboring cells [PMID:19262673].
