### ISSUE TITLE
Obsoletion request: GO:0033383 geranyl diphosphate metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27797]
Please provide as much information as you can:

* **GO term ID and Label**

~[GO:0033386](https://www.ebi.ac.uk/QuickGO/term/GO:0033386)    geranylgeranyl diphosphate biosynthetic process~

GO:0033383 geranyl diphosphate metabolic process

* **Reason for deprecation** Put an x in the appropriate box: 

 - [ ]  The reason for obsoletion is that this term was an unnecessary grouping term. (pathway intermediate)
 
(pathway intermediate, only has 3 pombe annotations)

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by pgaudet** [comment]
> The reason for obsoletion is that this term was an unnecessary grouping term.

Is it? There are 2 MetaCyc pathway
and there are no children.. how is it a grouping class?

**Comment by ValWood** [comment]
well, unnecessary specificity, either way, it doesn't seem necessary; it's an intermediate in multiple pathways (between FPP and squalene), but it doesn't appear to be a branch point... I will look closer.

It only seems to be used for geranyltranstransferase activity

**Comment by ValWood** [comment]
After discussion with @pgaudet  also look at
	•	'geranyl diphosphate metabolic process' http://purl.obolibrary.org/obo/GO_0033383
	•	'geranyl diphosphate biosynthetic process' http://purl.obolibrary.org/obo/GO_0033384
 
 
	•	'geranylgeranyl diphosphate catabolic process' http://purl.obolibrary.org/obo/GO_1902247
	•	'geranylgeranyl diphosphate metabolic process' http://purl.obolibrary.org/obo/GO_0033385
	•	'geranylgeranyl diphosphate biosynthetic process' http://purl.obolibrary.org/obo/GO_0033386
 
 
	•	'farnesyl diphosphate catabolic process' http://purl.obolibrary.org/obo/GO_0045339
	•	'farnesyl diphosphate metabolic process' http://purl.obolibrary.org/obo/GO_0045338
	•	'farnesyl diphosphate biosynthetic process' http://purl.obolibrary.org/obo/GO_0045337
 
 
	•	'farnesyl diphosphate biosynthetic process, mevalonate pathway' http://purl.obolibrary.org/obo/GO_0010142
 
 
And these look like MFs, but I haven’t checked.
	•	'peptidyl-S-geranylgeranyl-L-cysteine biosynthetic process from peptidyl-cysteine' http://purl.obolibrary.org/obo/GO_0018228
	•	'peptidyl-S-farnesyl-L-cysteine biosynthetic process from peptidyl-cysteine' http://purl.obolibrary.org/obo/GO_0018226
	•	'peptidyl-S-12-hydroxyfarnesyl-L-cysteine biosynthetic process from peptidyl-cysteine' http://purl.obolibrary.org/obo/GO_0018227


(NOTE "I think  farnesyl diphosphate biosynthetic process, mevalonate pathway" is OK (major branch point, FPP is the precursor for  farnesylation, dolichol,  heme A ubiquinone, gernylgerenylation, and precedes squalene the first dedicated step in sterol biosynthesis) but will review the others. It seems the catabolism terms have been used to model consumption of the metabolite by the next pathway component  (i..e NOT catabolism).

**Comment by ValWood** [comment]
@pgaudet  what should the obsoletion  reason be? as you say it isn't really grouping class, it's pathway intermediate (but in this case it is sometimes used as grouping for preceding steps, but it  isn't an 'end point')

**Comment by ValWood** [comment]
Actually @pgaudet  I think most of these are OK
geranyl diphosphate biosynthetic process'
and
geranyl diphosphate biosynthetic process'
are  end points.

I was only questioning [GO:0033386 geranylgeranyl diphosphate biosynthetic process](https://github.com/geneontology/go-ontology/issues/27797#top)
which does not seem to be.

I will double check this with EcoCyc, I can't find good reviews for these few steps and it is complicated by the enzymes being multipuctional and having paralogs, and the chemical names being inconsistent and difficult to interpret.

The catabolic ones look dodgy, most seem to be used to annotate the preceding synthase so maybe I will begin with those.

**Comment by ValWood** [comment]
GO:0033386 geranylgeranyl diphosphate biosynthetic process
was added here
https://github.com/geneontology/go-ontology/issues/4233

I will just remove the annotations I had made, and review the catabolic.

**Comment by ValWood** [comment]
GO:0033386 geranylgeranyl diphosphate biosynthetic process is fine
GO:0033383  geranyl diphosphate metabolic process is questionable? (20EXP)

<img width="372" alt="Screenshot 2024-05-01 at 09 30 08" src="https://github.com/geneontology/go-ontology/assets/7359272/eef972c0-6cdb-42c0-aafb-33447438bc96">

**Comment by pgaudet** [comment]
HI Val, 

I am still unsure this/these term/s should be obsoleted, as. they have annotations and especially cross references. I am not sure why you point to the ticket where these terms were added (based on MetaCyc); what should I look for in https://github.com/geneontology/go-ontology/issues/4233 ?  

**GO:0033386  geranylgeranyl diphosphate biosynthetic process maps to 2 MetaCyc:** 

1. PWY-5121 superpathway of geranylgeranyl diphosphate biosynthesis II (via MEP)
2. PWY-5120, which is a smaller pathway. In that entry, MetaCyc states 

> In plants, [geranylgeranyl diphosphate](http://metacyc.ai.sri.com/compound?orgid=META&id=GERANYLGERANYL-PP) is an intermediate in the biosynthesis of essentail compounds such as chlorophylls, carotenoids, tocopherols, plastoquinones, and gibberellins [[RodriguezConcep02](http://www.ncbi.nlm.nih.gov/pubmed/12427975)], as well as a variety of secondary metabolites. In addition, GGPP is also used in posttranslational modifications of proteins (geranylgeranylation) which is important for membrane adhesion as well as the function of some proteins [[Caldelari01](http://www.ncbi.nlm.nih.gov/pubmed/11500541), [Johnson05](http://www.ncbi.nlm.nih.gov/pubmed/16183844)].

So, that seems a useful intermediate (branch point). 

**GO [farnesyl diphosphate biosynthetic process, mevalonate pathway](http://purl.obolibrary.org/obo/GO_0010142)** maps to PWY-922, which seems to be a different pathway. 
(although that xref is also shared with [isopentenyl diphosphate biosynthetic process, mevalonate pathway](http://purl.obolibrary.org/obo/GO_0019287))

**Comment by pgaudet** [comment]
If you can explain why the MetaCyc pathways are incorrect then we can consider obsoletion.

**Comment by ValWood** [comment]
yes I requested the wrong term - I meant
GO:0033383 geranyl diphosphate metabolic process


(the reactions are all performed by the same enzyme PANTHER	FARNESYL-PYROPHOSPHATE SYNTHETASE)

GO:0033386 geranylgeranyl diphosphate biosynthetic is OK
GO:0045337 farnesyl diphosphate biosynthetic process is OK.

It sees that "GO:0033383 geranyl diphosphate metabolic process" was requested because curators probably wanted a  specific process to match the 'output' of each reaction,  but GPP doesn't need one (see image above)

I will change the title.

**Comment by pgaudet** [comment]
OK. I think this was created because it was standard to create the metabolic/biosynthetic/catalytic triad for any compound. 

Depending on the group, 'metabolism' may mean synthesis or degradation :(

**Comment by ValWood** [comment]
I am not so sure about this. The annotations are for bacteria.  Although this isn't an end point in eukaryotes as far as I can see, it might be an end point in bacteria.
