### ISSUE TITLE
Obsoletion request: GO:0019115 benzaldehyde dehydrogenase (NAD(P)+) activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27817]
GO:0019115 benzaldehyde dehydrogenase (NAD(P)+) activity

Unnecessary grouping class; all annotations are to children (NAD+ or NADP+-specific)

**Comment by pgaudet** [comment]
[pyruvate dehydrogenase [NAD(P)+] activity](http://purl.obolibrary.org/obo/GO_0034603) 
Unnecessary grouping class; all annotations are to child [pyruvate dehydrogenase (NADP+) activity]

**Comment by pgaudet** [comment]
Won't do - we have these grouping terms in other places.

**Comment by deustp01** [comment]
> [pyruvate dehydrogenase [NAD(P)+] activity](http://purl.obolibrary.org/obo/GO_0034603)
> Unnecessary grouping class; all annotations are to child [pyruvate dehydrogenase (NADP+) activity]

Maybe a tangent, but this assertion is biochemically incorrect: mammalian (and fly?) pyruvate dehydrogenase converts pyruvate to acetyl CoA coupled to the reduction of NAD+ (never NADP+) to NADH. What am I missing here? @sjm41

**Comment by sjm41** [comment]
I think Pascale may have meant that all **EXP** annotations are to child [pyruvate dehydrogenase **(NAD+)** activity]??

Here's what I see in QuickGO:
```
pyruvate dehydrogenase [NAD(P)+] activity (GO:0034603)
    |_pyruvate dehydrogenase (NADP+) activity (GO:0050243) (EC:1.2.1.51/RHEA:17425)
	=> 69 annotations to bacterial species (all EC/RHEA-to-GO)
	=> 0 EXP annotations
    |_pyruvate dehydrogenase (NAD+) activity (GO:0034604) (EC:1.2.1.104/RHEA:28042)
	=> 284 annotations
	=> 7 EXP annotations to human and mouse PDH complex subunits
```

Which all looks fine to me, and the current GO tree should stay as it is.
