### ISSUE TITLE
Remove/replace references to EC:1.6.1.2

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#27814]
I refreshed the list of obsolete ECs (in #27812), and a new one has been added:

- ERROR: <http://purl.obolibrary.org/obo/GO_0008746> has a definition xref to an obsolete EC: "EC:1.6.1.2"
- ERROR: <http://purl.obolibrary.org/obo/GO_0008746> has a synonym xref to an obsolete EC: "EC:1.6.1.2"
- ERROR: <http://purl.obolibrary.org/obo/GO_0008750> has an xref to an obsolete EC: "EC:1.6.1.2"
- ERROR: <http://purl.obolibrary.org/obo/GO_0008750> has a definition xref to an obsolete EC: "EC:1.6.1.2"
- ERROR: <http://purl.obolibrary.org/obo/GO_0008750> has a synonym xref to an obsolete EC: "EC:1.6.1.2"

**Comment by raymond91125** [comment]
This is a bit complicated issue.
EC:1.6.1.1 NAD(P)(+) transhydrogenase (Si-specific) has other name NAD(P)(+) transhydrogenase (B-specific) RHEA:11692
EC:1.6.1.2 NAD(P)+ transhydrogenase (Re/Si-specific) is transferred to
EC 7.1.1.1 proton-translocating NAD(P)(+) transhydrogenase  RHEA:47992
EC:1.6.1.3 NAD(P)(+) transhydrogenase RHEA:11692

GO:0008746 NAD(P)+ transhydrogenase activity XREF to EC:1.6.1.1/EC:1.6.1.2/RHEA:11692

... GO:0008750 NAD(P)+ transhydrogenase (AB-specific) activity XREF to EC:1.6.1.2. Also XREF MetaCyc:PYRNUTRANSHYDROGEN-RXN suggests it is about EC:1.6.1.1 and EC:1.6.1.3
... GO:0003957 NAD(P)+ transhydrogenase (B-specific) activity XREF to EC:1.6.1.1 (NOT RHEA:11692)

**Comment by pgaudet** [comment]
**For GO:0008746 NAD(P)+ transhydrogenase activity** XREF to EC:1.6.1.1/EC:1.6.1.2/RHEA:11692
- [ ] Obsolete ; this is the general case that corresponds to https://enzyme.expasy.org/EC/1.6.1.3, which states "This entry stands for enzymes whose stereo-specificity with respect to NADPH is not known"; this is associated with the same RHEA as 1.6.1.1 and has no genes associated with it. It seems like the stereospecificity is always known. 

**Child GO:0008750 NAD(P)+ transhydrogenase (AB-specific) activity** :  
- [ ] Change general cross references to EC 7.1.1.1 proton-translocating NAD(P)(+) transhydrogenase and RHEA:47992
- [ ] Change definition to match RHEA 
- [ ] Change definition cross reference to RHEA:47992
- [ ] remove the link to "pubs.acs...."  in the def xref that (dead link) 

**Child GO:0003957 NAD(P)+ transhydrogenase (B-specific) activity** XREF to EC:1.6.1.1 
- [ ] Xrefs should be to  EC:1.6.1.1  and [RHEA:11692](https://www.rhea-db.org/rhea/11692)
- [ ] Definition should be adjusted to match RHEA's. 

Does that seem right ? 

Thanks, Pascale

**Comment by raymond91125** [comment]
(based on UniProt catalytic activity)
GO:0008746 NAD(P)+ transhydrogenase activity, there are 6 experimental annotations. I reported an AmiGO bug https://github.com/geneontology/amigo/issues/718. Of those 6, there is a mixture of Rhea:47992, Rhea:11692, and Rhea:10824 (incorrect GO annotation?).
GO:0003957 NAD(P)+ transhydrogenase (B-specific) activity The only annotation PntAA is actually of Rhea:47992.

Since GO doesn't have EC:1.6.1.3, this issue may not be relevant. This comment "This entry stands for enzymes whose stereo-specificity with respect to NADPH is not known", I interpret it to mean that EC:1.6.1.3 is different from EC:1.6.1.1 rather than EC:1.6.1.1 is a subclass.

**Comment by pgaudet** [comment]
Hi @raymond91125 
Is my suggestion above not working What do you propose to do? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@raymond91125 
See @amandamackie 's input in the annotation ticket: https://github.com/geneontology/go-annotation/issues/5218

GO:0003957 NAD(P)+ transhydrogenase (B-specific) activity 's definition and the parent ''proton transmembrane transporter activity'' should be removed. 

Thanks, Pascale
