### ISSUE TITLE
Missing parent: inconsistent parentage in RNA processing branch

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27828]
rRNA modification/tNRA modification are under RNA processing
snRNA  modification is not under snRNA processing

<img width="1180" alt="Screenshot 2024-05-03 at 12 28 15" src="https://github.com/geneontology/go-ontology/assets/7359272/12f27049-3285-47ce-8bee-523ba48be500">

* **GO term ID and label for which you request a new superclass**

* **New superclass (parent) suggested**

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by pgaudet** [comment]
Also - processing should not be under 'catabolic process' 
It *should* mean biosynthetic process/maturation. But we need to check that the annotations are consistent with this. 

Thanks, Pascale

**Comment by ValWood** [comment]
Note the catabolism problem was due to a logical def issue and only appeared recently. Was dealt with in 
https://github.com/geneontology/go-ontology/issues/27633

**Comment by ValWood** [comment]
Note that the modification terms have logical defs but the ones which are correctly positioned under their  RNA processing
terms have this relation instantiated so I have done the same for snoRNA. Maybe one day the "RNA modification" terms will go, but this makes everything in the correct place.
