### ISSUE TITLE
GDP-mannose pyrophosphorylase complex

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27827]
* **Suggested term label:**
GDP-mannose pyrophosphorylase complex

* **Definition (free text)**
A protein complex capable of catalyzing the reaction of GTP and mannose-1-phosphate to form GDP-mannose. The complex is a homodimer in most bacteria, whereas it is a heterodimer in most eukaryotes, composed of a catalytic beta subunit (GMPPB) and a non-catalytic alpha subunit (GMPPA).

* **Reference, in format PMID:#######**
PMID: 33986552

* **Gene product name and ID to be annotated to this term**
Human GMPPA and GMPPB (and orthologs).

* **Parent term(s)**
is_a  GO:1990234 transferase complex
capable_of MF  GO:0004475 mannose-1-phosphate guanylyltransferase (GTP) activity
capable_of_part_of GO:0009298 GDP-mannose biosynthetic process

* **Synonym(s) (please specify, EXACT, BROAD, NARROW or RELATED)**
GMPPA–GMPPB complex [EXACT]

**Comment by deustp01** [comment]
> * a non-catalytic alpha subunit (GMPPA)

Would "regulatory alpha subunit (GMPPA)" be appropriate?

**Comment by sjm41** [comment]
+[Term]
+id: GO:0120508
+name: GDP-mannose pyrophosphorylase complex
+namespace: cellular_component
+def: "A protein complex capable of catalyzing the reaction of GTP and mannose-1-phosphate to form GDP-mannose. The complex is a homodimer in most bacteria and a heterodimer in most eukaryotes. In humans, it is composed of a catalytic beta subunit (GMPPB) and a regulatory alpha subunit (GMPPA)." [GOC:sjm, PMID:33986552]
+synonym: "GMPPA–GMPPB complex" EXACT []
+is_a: GO:1990234 ! transferase complex
+relationship: capable_of GO:0004475 ! mannose-1-phosphate guanylyltransferase (GTP) activity
+relationship: capable_of_part_of GO:0009298 ! GDP-mannose biosynthetic process
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27827" xsd:anyURI
+created_by: sjm
+creation_date: 2024-05-04T08:30:37Z
