### ISSUE TITLE
NTR: Negative regulation of GDP-mannose biosynthetic process

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#27835]
Please provide as much information as you can: 

* **Suggested term label:**
Negative regulation of GDP-mannose biosynthetic process

* **Definition (free text)**
Any process that stops, prevents, or reduces the frequency, rate or extent of the chemical reactions and pathways resulting in the formation of GDP-mannose.

* **Reference, in format PMID:#######**
PMID: 33986552

* **Gene product name and ID to be annotated to this term**
Human GMPPA and orthologs

* **Parent term(s)**
is_a GO:0009298: GDP-mannose biosynthetic process
Currently the term "GDP-mannose biosynthetic process" doesn't have a regulatory GO term.
Should a "regulation of GDP-mannose biosynthetic process" be created before as a parent?

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
Note to self, update
https://www.pombase.org/gene/SPBC13G1.02

**Comment by ValWood** [comment]
Hi @rozaru 

I'm not sure about this one. 
is GMPPA  seems to be part of 
GO:0009298 | GDP-mannose biosynthetic process
What is its activity?  I maybe have it annotated incorrectly.


[GO:0009298](https://www.pombase.org/term/GO:0009298)	
[GDP-mannose biosynthetic process](https://www.pombase.org/term/GO:0009298)

**Comment by ValWood** [comment]
Agreed,  we would not usually capture 'within-pathway' regulates relations as a "regulation of process" term; these are part of the process.  "regulation of process" terms are for regulation. (i.e control, rather than affect)  that occurs upstream of the module in question.
Thanks!
will close.
