### ISSUE TITLE
Taxon constraint: GO:0042597

### ISSUE THREAD

**Issue by RLovering** [geneontology/go-ontology#27838]
Hi

I keep getting an error report for this annotation:

GO:0042597 (periplasmic space) and its descendants should ONLY be used with gene products from the taxonomic group Fungi or Bacteria or Archaea

protein     O87990                   GO:0042597 periplasmic space                       ECO:0000314 (IDA) PMID:19015265  
518      Bordetella bronchiseptica

Note that Bordetella bronchiseptica is a bacteria, so what is the problem?

Thanks
Ruth

**Comment by pgaudet** [comment]
There was a problem with the P2GO taxon checks. Please wait for the next report and re-open if the issue comes back. 

Thanks, Pascale

**Comment by RLovering** [comment]
Yes no error anymore
