### ISSUE TITLE
Obsoletion request: GO:0141195 piRNA-mediated facultative heterochromatin formation

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#27842]
Please provide as much information as you can:

* **GO term ID and Label**
GO:0141195 piRNA-mediated facultative heterochromatin formation

* **Reason for deprecation** Put an x in the appropriate box: 
 - [ ] The reason for obsoletion is that the term is not clearly defined and usage has been inconsistent.
 - [ ]  The reason for obsoletion is that this term is pre-composed and should be represented as a GO-CAM model.
 - [ ]  The reason for obsoletion is that this term represent an assay and not a GO process.
 - [ ]  The reason for obsoletion is that this represents a phenotype.
 - [ ] The reason for obsoletion is that the data from the paper for which the term was requested can be accurately described using [appropriate GO term].
 - [ ] The reason for obsoletion is that this term represents a molecular function.
 - [ ]  The reason for obsoletion is that this term represents a gene product.
 - [ ] The reason for obsoletion is that this term refers to a class of proteins.
 - [x]  The reason for obsoletion is that this term was added in error.
 - [ ]  The reason for obsoletion is that more specific terms were created.
 - [ ]  The reason for obsoletion is that this term was an unnecessary grouping term.
 - [ ]  The reason for obsoletion is that the meaning of the term is ambiguous.
 - [ ]  The reason for obsoletion is that is not known to be catalyzed by any gene product.
 - [ ]  The reason for obsoletion is that it more specific than the specificity of any known gene product.
 - [ ]  The reason for obsoletion is that there is no evidence that this function/process/component exists.

* **Are there annotations to this term?**
- How many EXP: 0 

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**
* No

* **Any other information**

Cannot use this term in annotation - although siRNAs can do this, there are no examples of piRNA that I can find and remains 'hypothetical'

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by hattrill** [comment]
I can also see some strangeness in the GO where it looks like 'facultative heterochromatin formation' is now under piRNA-mediated heterochromatin formation
<img width="284" alt="Screenshot 2024-05-06 at 14 15 54" src="https://github.com/geneontology/go-ontology/assets/11865746/57e7a365-afe5-4bd6-994d-b7c879cc4872">

Should be like this for this branch:

<img width="682" alt="Screenshot 2024-05-06 at 14 19 08" src="https://github.com/geneontology/go-ontology/assets/11865746/9bd4bdab-d26e-4f64-97e4-b8841413b5f0">

**Comment by pgaudet** [comment]
For info - term was created here: https://github.com/geneontology/go-ontology/issues/27454

**Comment by pgaudet** [comment]
I fixed the hierarchy problems, we now have this 

<img width="555" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/7f6ff5f9-63c8-4c09-a5a4-72a8aadce399">

**Comment by hattrill** [comment]
No - although they say it can silence a reporter, it not clear if that constitutes facultative heterochromatin or just the assay for silencing. They show constitutive for sure, but I could find an example of piRNAs shutting down "normal" genes by heterochromatin formation - seeks to occur at degradation of transcript.
