### ISSUE TITLE
GO:1990133  molybdopterin cofactor (Moco) biosynthesis adenylyltransferase complex

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27852]
This complex is related to the "MPT synthase complex" - see #27655.

id: GO:1990133
name: molybdopterin cofactor (Moco) biosynthesis adenylyltransferase complex
namespace: cellular_component
def: "A heterodimeric protein complex which adenylates two molecules of the sulfur carrier subunit of the molybdopterin (MPT) cofactor synthase using ATP as part of molybdopterin cofactor (Moco) biosynthesis. In E. coli the subunits are MoeB and MoaD; Moco biosynthesis and its constituent molecules are evolutionarily conserved." [GOC:bhm, PMID:11713534, PMID:16669776]
is_a: GO:0032991 ! protein-containing complex
relationship: capable_of GO:0070566 ! adenylyltransferase activity
relationship: part_of GO:0005829 ! cytosol
created_by: bhm
creation_date: 2013-06-26T10:54:21Z

Following the changes in #27655:
- [x] rename to "MPT adenylyltransferase complex" (for brevity and consistency with "MPT synthase complex")
- [x] change "heterodimeric" to "heterotetrameric" (as per the given references)
- [x] add to the def to say that in human the subunits are MOCS3 and MOCS2A. [PMID:18491921]
- [x] change parent to "transferase complex"

**Comment by sjm41** [comment]
Based on https://github.com/geneontology/go-ontology/issues/27652#issuecomment-2107494400 comment, I should change the current name "MPT adenylyltransferase complex" to "molybdopterin adenylyltransferase complex" (because 'MPT' isn't a widely known abbreviation for 'molybdopterin').

Should do the same to GO:1990140 MPT synthase complex

**Comment by pgaudet** [comment]
thanks :)
