### ISSUE TITLE
Textual definition update: MAP kinase kinase activity

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#27856]
I think the def can be expanded to include TGY?

* **GO term ID and label for which you request a definition update**
GO:0004708 MAP kinase kinase activity

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
Catalysis of the concomitant phosphorylation of threonine (T) and tyrosine (Y) residues in a Thr-Glu-Tyr (TEY) or Thr-Gly-Tyr (TGY) thiolester sequence in a MAP kinase (MAPK) substrate. 

* **Reference(s)**
this alignment shows some MAP kinases -  HOG1/MAPK11 has TGY sequence, which is shown in  pmid  38270553 to be phosphorylated by MAPKK PBS2

![image](https://github.com/geneontology/go-ontology/assets/12727506/d0f96e52-0482-41f3-9821-80bbddb05ed0)

**Comment by raymond91125** [comment]
Aren't MAP2K target sites more diverse? e.g. PMID:12623839 mentions also TPY.
Perhaps "Catalysis of the concomitant phosphorylation of threonine (T) and tyrosine (Y) residues in a T-X-Y motif in the activation loop of a MAP kinase (MAPK) substrate."
I don't know the relevance of "thioester sequence" in the original def so I removed it.

**Comment by Antonialock** [comment]
Thank you, that sounds good to me (I just noticed that the one I was working on didn't conform to the definition)
