### ISSUE TITLE
resolve Rhea mapping for 'proton-transporting ATP synthase activity, rotational mechanism' and 'proton-transporting ATPase activity, rotational mechanism'

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#27850]
![7c36b01b90f99c4809efd36d0fef38e2760b9087979b9677199d88c11eacf307](https://github.com/geneontology/go-ontology/assets/210210/28609d0c-48c8-4796-bf8e-715f471f2601)

- [proton-transporting ATPase activity, rotational mechanism](http://purl.obolibrary.org/obo/GO_0046961) ProperSuperClassOf [ATP + 4 H(+)(in) + H2O => ADP + 5 H(+)(out) + phosphate](http://rdf.rhea-db.org/57721)		0.08
- [ATP + 4 H(+)(in) + H2O = ADP + 5 H(+)(out) + phosphate](http://rdf.rhea-db.org/57720) EquivalentTo [EC:7.1.2.2](http://purl.uniprot.org/enzyme/7.1.2.2)	(most probable)	0.75
- [proton-transporting ATPase activity, rotational mechanism](http://purl.obolibrary.org/obo/GO_0046961) ProperSuperClassOf [EC:7.1.2.2](http://purl.uniprot.org/enzyme/7.1.2.2)	(most probable)	0.8
- [proton-transporting ATP synthase activity, rotational mechanism](http://purl.obolibrary.org/obo/GO_0046933) EquivalentTo [ATP + 4 H(+)(in) + H2O = ADP + 5 H(+)(out) + phosphate](http://rdf.rhea-db.org/57720)	(most probable)	0.8
- [proton-transporting ATP synthase activity, rotational mechanism](http://purl.obolibrary.org/obo/GO_0046933) EquivalentTo [EC:7.1.2.2](http://purl.uniprot.org/enzyme/7.1.2.2)	(most probable)	0.8

**Comment by balhoff** [comment]
The mapping that is causing the "conflict" is [proton-transporting ATPase activity, rotational mechanism](http://purl.obolibrary.org/obo/GO_0046961) to RHEA:57721. Currently it's a basic xref, but I guess based on this image it should be made 'narrow'. Should these two GO terms have a relation to each other?

**Comment by pgaudet** [comment]
This is a rare case where we have two directional RHEAs - 

However there was a mistake on proton-transporting ATP synthase activity, rotational mechanism (GO:0046933), we were using the non directional - see https://github.com/geneontology/go-ontology/issues/25727

The def xref was fixed but not the general xref. 


GO:0046933 will now be mapped to RHEA:57722

<img width="742" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/408cda3f-fb63-4e8d-adc8-12b664c06673">


Should I add the non-directional reaction RHEA:57720 as a broad match to both terms? 

Thanks, Pascale

**Comment by pgaudet** [comment]
According to @balhoff this fixed the issues (in local tests)
