### ISSUE TITLE
resolve EC:1.14.13.- mappings

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#27862]
![0c57472f32018d03786e37cec49d76b9594bbc4f477a1cad4f810c2dfef49008](https://github.com/geneontology/go-ontology/assets/210210/65750867-29b6-47d3-bf3b-f00b62f71298)

- [x] - [tocotrienol omega-hydroxylase activity](http://purl.obolibrary.org/obo/GO_0052872) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [4-chlorobenzaldehyde oxidase activity](http://purl.obolibrary.org/obo/GO_0018471) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [carbon disulfide oxygenase activity](http://purl.obolibrary.org/obo/GO_0018643) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [x] - [phenanthrene 9,10-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018636) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [3,5-xylenol methylhydroxylase activity](http://purl.obolibrary.org/obo/GO_0018630) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [2-octaprenyl-3-methyl-6-methoxy-1,4-benzoquinol hydroxylase activity](http://purl.obolibrary.org/obo/GO_0043719) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [chlorophenol 4-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018642) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [x] - [2-hydroxy-phenylacetate hydroxylase activity](http://purl.obolibrary.org/obo/GO_0018654) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [thalianol hydroxylase activity](http://purl.obolibrary.org/obo/GO_0080014) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [x] - [dimethyl sulfide monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018633) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [1-hydroxy-2-oxolimonene 1,2-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018646) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [2-methylnaphthalene hydroxylase activity](http://purl.obolibrary.org/obo/GO_0034526) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [x] - [phenanthrene 3,4-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018656) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [x] - [phenanthrene 1,2-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018647) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [1-methylnaphthalene hydroxylase activity](http://purl.obolibrary.org/obo/GO_0034534) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [branched-chain dodecylbenzene sulfonate monooxygenase activity](http://purl.obolibrary.org/obo/GO_0034802) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [4-hydroxypyridine-3-hydroxylase activity](http://purl.obolibrary.org/obo/GO_0034894) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [3-methyl-2-oxo-1,2-dihydroquinoline 6-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018653) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [x] - [oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen](http://purl.obolibrary.org/obo/GO_0016709) ProperSuperClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [3-HSA hydroxylase activity](http://purl.obolibrary.org/obo/GO_0034819) EquivalentTo [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)	(most probable)	0.8
- [ ] - [bisphenol A hydroxylase A activity](http://purl.obolibrary.org/obo/GO_0034560) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [styrene monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018650) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [2-oxo-delta3-4,5,5-trimethylcyclopentenylacetyl-CoA 1,2-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018655) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [isobutylamine N-hydroxylase activity](http://purl.obolibrary.org/obo/GO_0034791) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [x] - [limonene monooxygenase activity](http://purl.obolibrary.org/obo/GO_0019113) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [xylene monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018639) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [tetrahydrofuran hydroxylase activity](http://purl.obolibrary.org/obo/GO_0018649) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [ ] - [toluene-4-sulfonate monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018651) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08
- [x] - [phenylacetate hydroxylase activity](http://purl.obolibrary.org/obo/GO_0018631) ProperSubClassOf [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-)		0.08

**Comment by pgaudet** [comment]
> [3-HSA hydroxylase activity](http://purl.obolibrary.org/obo/GO_0034819) EquivalentTo [EC:1.14.13.-](http://purl.uniprot.org/enzyme/1.14.13.-) ***(most probable) 0.8***

This is incorrect; this partial EC corresponds to [GO:0016709 oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen](https://amigo.geneontology.org/amigo/term/GO:0016709#display-lineage-tab)


I am removing all partial ECs, this leads to incorrect mappings, and see if others need to be obsoleted. 
Annotations are here: https://github.com/geneontology/go-annotation/issues/5221

**Comment by pgaudet** [comment]
-[limonene monooxygenase activity](http://purl.obolibrary.org/obo/GO_0019113) : 
- [ ] remove partial EC
- [ ] remove PMID:820855 reference, links to the wrong paper ("Long term changes in augmentation, potentiation, and depression of transmitter release as a function of repeated synaptic activity at the frog neuromuscular junction")

- [ ] [1-hydroxy-2-oxolimonene 1,2-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0018646)

**Comment by pgaudet** [comment]
[phenylacetate hydroxylase activity](http://purl.obolibrary.org/obo/GO_0018631) 

- [ ] add EC:1.14.14.54
- [ ] add RHEA:53392
- [ ] fix def and term label to match RHEA and EC
- [ ] change parent to 'oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen'

**Comment by pgaudet** [comment]
2-hydroxy-phenylacetate hydroxylase activity

- [ ] removed partial EC; cannot find an EC or a RHEA for this reaction. 
- [ ] added the reference cited by EAWAG-BBD , PMID: [8919815](https://pubmed.ncbi.nlm.nih.gov/8919815) - very weak evidence.

**Comment by pgaudet** [comment]
dimethyl sulfide monooxygenase activity

- [ ] Add EC:1.14.13.131
- [ ] Add RHEA:31355
- [ ] Add parent monooxygenase activity

**Comment by pgaudet** [comment]
dimethylsulfoxide oxygenase activity (not in the list because the partial EC is on the def xref, not on the xref):

**Comment by pgaudet** [comment]
- phenanthrene 3,4-monooxygenase activity
 - phenanthrene 1,2-monooxygenase activity
 - phenanthrene 9,10-monooxygenase activity

Citing PMID:1599252 (via EAWAG-BBD )
No evidence that this specific activity exists; also phenanthrene seems to be a grouping class for many compounds, see https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:25961


Removed the partial EC; added the PMID.

**Comment by pgaudet** [comment]
- [2-octaprenyl-3-methyl-6-methoxy-1,4-benzoquinol hydroxylase activity](http://purl.obolibrary.org/obo/GO_0043719)
- [x] Removed partial EC

**Comment by pgaudet** [comment]
GO:0052871 alpha-tocopherol omega-hydroxylase activity >> 
GO:0052870 tocopherol omega-hydroxylase activity
GO:0052872 tocotrienol omega-hydroxylase activity


Email MetaCyc 
> I am struggling with this entry 
(RXN-11003), that has a reaction: 
&#945;-tocopherol   reduced [NADPH-hemoprotein reductase]   dioxygen &#8594; 13'-hydroxy-&#945;-tocopherol   oxidized [NADPH-hemoprotein reductase]   H2O
Note that this reaction equation differs from the official Enzyme Commission reaction equation for this EC entry, which can be found here. 
The official EC reaction uses leukotriene B4. How are these two substrates related? 

Reply from Ron Capsi
> if you go to the actual MetaCyc page for this EC number,  
http://metacyc.ai.sri.com/META/NEW-IMAGE?type=EC-NUMBER&object=EC-1.14.14.94
 (you can get there by scrolling down in the page you referred, the table under the reaction diagram has a row for the EC number that is clickable), 
you will see that the reaction with leukotriene B4 is listed as the official reaction, but there are 4 additional reactions (including the one you pointed out) that are listed as "unofficial reactions". 
The justification can be found in the summary for the enzyme, CYP4F2 (http://metacyc.ai.sri.com/gene?orgid=META&id=HS02675-MONOMER), where it is explained that the enzyme catalyzes all of these reactions.
Even though  the structures of leukotriene B4 and α-tocopherol are quite different, the enzyme catalyzes a pretty similar reaction - hydroxylation of the last carbon at the linear tail of the molecule. It is typical for P450s to catalyze similar reactions on a large number of different substrates.

**Comment by pgaudet** [comment]
Others should be handled by https://github.com/geneontology/go-ontology/issues/28108
