### ISSUE TITLE
NTR: inositol pyrophosphate sensor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27868]
Please provide as much information as you can: 

* **Suggested term label:**

 inositol pyrophosphate sensor activity

* **Definition (free text)**

Binding to and responding, e.g. by conformational change, to changes in the cellular level of an  inositol pyrophosphate

* **Reference, in format PMID:#######**

PMID:37949217

Abstract
"SPX domains bind to inositol pyrophosphate and modulate activities of Pi-related proteins."

Results
" The SPX domain reportedly functions as a Pi sensor and to bind signaling molecules, PP- IPs, like IP7 and IP8 (21). "

* **Gene product name and ID to be annotated to this term**

initially fission yeast spx2 but potentially any SPX domain protein

https://www.pombase.org/gene_subset/interpro:IPR004331

* **Parent term(s)**

GO:0140299   small molecule sensor activity

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

inositol hexakisphosphate sensor (narrow)
because I think most use GO:0000822   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0000822/complete)
inositol hexakisphosphate binding

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
+[Term]
+id: GO:0180041
+name: polyphosphate import into vacuole
+namespace: biological_process
+comment: The process in which a polyphosphate is transported across the vacuolar membrane from the cytoplasm to the vacuole. {xref="GOC:vw"}
+is_a: GO:0034486 ! vacuolar transmembrane transport
+created_by: vw
+creation_date: 2024-05-21T13:43:18Z

**Comment by pgaudet** [comment]
@ValWood you closed this ticket but I dont see the new term - is this closed because you wont create the term? 

In case you want to add the term: 
-  I see you have put the definition as a 'comment' rather than as a def. 
- Is there a pubmed for this?

**Comment by ValWood** [comment]
Hmm, I thought that term was added, will double check tomorrow

I thought we did not use the PMID. If we used standard definitions, I can add one.

**Comment by ValWood** [comment]
+
+[Term]
+id: GO:0180043
+name: inositol pyrophosphate sensor activity
+namespace: molecular_function
949217]

**Comment by ValWood** [comment]
This did not apepar which is odd because the other changes I did at the same time were fine. Will look tomorrow...

**Comment by ValWood** [comment]
I see it, it seems Canto is not updating
