### ISSUE TITLE
Textual definition update:GO:0034041 ABC-type sterol transporter activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#27884]
* **GO term ID and label for which you request a definition update**
* GO:0034041 ABC-type sterol transporter activity

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
*change  a solute or solutes -> a sterol in def:
from "Enables the transfer of a solute or solutes from one side of a membrane to the other according to the reaction: ATP + H2O + sterol(in) = ADP + phosphate + sterol(out)."
to
Enables the transfer of a sterol from one side of a membrane to the other according to the reaction: ATP + H2O + sterol(in) = ADP + phosphate + sterol(out).

**Comment by ValWood** [comment]
Done this one. I needed a quick fix to see that the ontology had changed
