### ISSUE TITLE
NTR: sterol:proton antiporter activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#27883]
Please provide as much information as you can: 

* **Suggested term label:**
* sterol:proton antiporter activity

* **Definition (free text)**
Enables the transfer of a sterol from one side of a membrane to the other according to the reaction: H+(out) + sterol(in) = H+(in) + sterol(out).

* **Reference, in format PMID:#######**
PMID:10735876

* **Gene product name and ID to be annotated to this term**
Npc1a, FBgn0024320

* **Parent term(s)**
GO:0170055 lipid transmembrane transporter activity
GO:1901618 organic hydroxy compound transmembrane transporter activity
GO:0015297 antiporter activity

* **Cross-references**
* TCBD:2.A.6

* **Any other information**
Add as possible replacement term for GO:0015248 obsolete sterol transporter activity

**Comment by deustp01** [comment]
> * Enables the transfer of a sterol from one side of a membrane to the other according to the reaction: ATP + H2O + sterol(in) = ADP + phosphate + sterol(out)

Should this reaction also have a proton as an output, in line with, e.g., [RHEA:39103](https://www.rhea-db.org/rhea/39103) "ATP + H2O + sitosterol(in) = ADP + H(+) + phosphate + sitosterol(out)"?

**Comment by hattrill** [comment]
Sorry, pasted in wrong definition! (that was for another ticket)

Enables the transfer of a sterol from one side of a membrane to the other according to the reaction: H+(out) + sterol(in) = H+(in) + sterol(out).

I'll corrrect the above

**Comment by hattrill** [comment]
As sterol is a class of molecule, don't think there's a Rhea reaction for this.

**Comment by raymond91125** [comment]
Is PMID:10735876 the correct reference, @hattrill? And https://www.tcdb.org/search/result.php?tc=2.A.6.6.1 seems to be the more precise XREF.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160188
+name: sterol:proton antiporter activity
+namespace: molecular_function
+def: "Enables the transfer of a sterol from one side of a membrane to the other according to the reaction: H+(out) + sterol(in) = H+(in) + sterol(out)." [PMID:31543266]
+xref: TC:2.A.6.6.1
+is_a: GO:0015297 ! antiporter activity
+intersection_of: GO:0015297 ! antiporter activity
+intersection_of: has_primary_input CHEBI:15378 ! hydron
+intersection_of: has_primary_input CHEBI:15889 ! sterol
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27883" xsd:anyURI
+created_by: rynl
+creation_date: 2024-05-15T00:33:06Z

**Comment by raymond91125** [comment]
Let me know if anything needs fixing. Thanks.

**Comment by hattrill** [comment]
Hi @raymond91125 sorry to be a pain.
I reviewed this and I am wrong about the mechanism for sterol transport. The bacterial RNDs are H+ antiporters (but not for sterols), but the eukaryotic sterol "transporters" are pH-dependent but defitely not antiporters and I think are better described by the sterol transfer activity term - although I need to check this further.
The upshot is, could you obsolete this term as I requested it in error. Thanks!

**Comment by raymond91125** [comment]
@hattrill PMID:31543266 Structural Insight into Eukaryotic Sterol Transport through Niemann-Pick Type C Proteins states:
"NCR1 has its N-terminal domain (NTD) positioned to deliver a sterol to a tunnel connecting NTD to the luminal membrane leaflet 50 Å away. A sterol is caught inside this tunnel during transport, and a proton-relay network of charged residues in the transmembrane region is linked to this tunnel supporting a proton-driven transport mechanism. "
Thus it seems that this activity is valid.

**Comment by hattrill** [comment]
@raymond91125 yes, that is what I based the initial request on, but it seems that the proton-dependency varies for RND families. For eukaryotic NPC1-type transporters, they are tranporting sterols from inside the acidic lumen of a lysosome/late endolysome/vacuole, so the proton grandient is inside-to-out and that the proton accompanies the sterol. In [PMID:29577985 (RND transporters in the living world)](https://pubmed.ncbi.nlm.nih.gov/29577985/) they say that "since the endosome lumen is more acidic than the cytosol, NPC1 appears to function, unusually among RND transporters, as a proton/ligand symporter, rather than an antiporter".

Looking at this 2024 paper on the yeast protein, [PMID:38568972 (Conformational changes in the Niemann-Pick type C1 protein NCR1 drive sterol translocation)] (https://pubmed.ncbi.nlm.nih.gov/38568972/), it suggests that a proton is released to the cytosol and so would be symport (although the mechanism is very complex, but I think that is the correct interpretation). As they suggest that the transporter releases the sterol into the membrane, I am not 100% sure if this comes under TM transporter - I am erring on that side, rather than an 'insertase' or 'carrier' because of the channel and the crossing of a membrane and I think this is the general view of them.

For the bacterial RNDs, they are definitely proton antiporters [PMID:38689873](https://pubmed.ncbi.nlm.nih.gov/38689873/), but I cannot find an example of them transporting sterols - seem to be mainly involved in drug efflux.

So, perhaps "sterol:proton symporter activity" is what I want, but I am a bit reluctant to commit to that.

**Comment by raymond91125** [comment]
Thanks for the clarification.
