### ISSUE TITLE
 succinate dehydrogenase (quinone) activity - missing parent

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27915]
id: GO:0008177
name: succinate dehydrogenase (quinone) activity
namespace: molecular_function
alt_id: GO:0019737
def: "Catalysis of the reaction: a quinone + succinate = a quinol + fumarate." [RHEA:40523]
synonym: "fumarate reductase (menaquinone)" NARROW []
synonym: "succinate dehydrogenase (menaquinone)" NARROW []
synonym: "succinate dehydrogenase (ubiquinone) activity" NARROW []
synonym: "succinic dehydrogenase activity" BROAD [EC:1.3.5.1]
xref: EC:1.3.5.1
xref: KEGG_REACTION:R02164
xref: MetaCyc:RXN-14971
xref: RHEA:40523
is_a: GO:0000104 ! succinate dehydrogenase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/26087" xsd:anyURI

This term (which = EC:1.3.5.1) currently has this parentage:
```
oxidoreductase activity (EC:1.-.-.-)
       |__oxidoreductase activity, acting on the CH-CH group of donors (EC:1.3.-.-)
           |__succinate dehydrogenase activity (EC n/a)
               |__succinate dehydrogenase (quinone) activity (EC:1.3.5.1)
```

GO:0008177 should have an additional parent of:
oxidoreductase activity, acting on the CH-CH group of donors, quinone or related compound as acceptor (EC:1.3.5.- )

**Comment by pgaudet** [comment]
Sibling [fumarate reductase (NADH) activity](http://purl.obolibrary.org/obo/GO_0016156)
was also missing its EC parent, oxidoreductase activity, acting on the CH-CH group of donors, NAD or NADP as acceptor

I now added this.
