### ISSUE TITLE
Missing parent: GO:0042776   proton motive force-driven mitochondrial ATP synthesis

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27914]
* **GO term ID and label for which you request a new superclass**

GO:0042776   proton motive force-driven mitochondrial ATP synthesis
The transport of protons across a mitochondrial membrane to generate an electrochemical gradient (proton-motive force) that powers ATP synthesis.

exact synonym
mitochondrial ATP synthesis coupled proton transport

* **New superclass (parent) suggested**

missing parent
GO:1902600 | proton transmembrane transport

(it should probably be the child 
[GO:0015988](https://www.ebi.ac.uk/QuickGO/term/GO:0015988)    energy coupled proton transmembrane transport, against electrochemical gradient
if that term is required?

**Comment by ValWood** [comment]
Maybe here its the term def that needs tweaking to focus on the "ATP synthesis" that occurs via protein transport?

**Comment by pgaudet** [comment]
Makes sense. How would you reformulate?

**Comment by ValWood** [comment]
The genus should be from GO:0006754  ATP biosynthetic process


The chemical reactions and pathways resulting in the formation of ATP driven by transport of protons across a membrane to generate an electrochemical gradient (proton-motive force)

**Comment by pgaudet** [comment]
Sounds good to me.

**Comment by ValWood** [comment]
Also did sibling and parent.
Made all of the transport terms "related"
