### ISSUE TITLE
malate-aspartate shuttle parentage

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#27924]
Although it plays a crucial role in respiration malate-aspartate shuttle is not directly part of the electron transport chain (ETC)

parent should move up to 
GO:0045333   cellular respiration

**Comment by deustp01** [comment]
opinions, @sjm41 ?

**Comment by ValWood** [comment]
More info. There are 3 children:

<img width="850" alt="Screenshot 2024-05-19 at 17 50 01" src="https://github.com/geneontology/go-ontology/assets/7359272/9740c2cf-00d7-43bb-83aa-4b75a9fb3ec4">

so it should apply to one or more of these.

GO:0022904  respiratory electron transport chain
Definition 
A process in which a series of electron carriers operate together to transfer electrons from donors such as NADH and FADH2 to any of several different terminal electron acceptors to generate a transmembrane electrochemical gradient.

so I suppose it could fit, but most descriptions of the respiratory ETC  begin with mitochondrial NADH.

The problem I see is that in this case the citric acid cycle and other NADH providing systems could be included?

**Comment by rozaru** [comment]
On a related note:
Could 'malate-aspartate shuttle' term become also a child of NADH oxidation?
The other pathway that does a similar reaction 'glycerolphosphate shuttle' (GO:0006127) is part of NADH oxidation.

![image](https://github.com/geneontology/go-ontology/assets/22237719/bc6f3755-b61d-4d83-a68e-6188175fb841)

**Comment by ValWood** [comment]
That would definitely be correct, but I wonder if we plan to keep NADH oxidation (seems like a single-step process, so maybe should only be in molecular function @pgaudet ).

Anyway, I will add this parent for consistency.

Glycerophosphate shuttle should have some mitochondrial transport parent....

**Comment by deustp01** [comment]
> That would definitely be correct, but I wonder if we plan to keep NADH oxidation

Is NADH oxidation (or NAD reduction) ever annotated in isolation, or always as a part of a larger reaction (process) in which a second participant is reduced or oxidized?

**Comment by ValWood** [comment]
These are the only direct EXP annotations to NADH oxidation:

UniProtKB:Q9JXV5	Fructose-1,6-bisphosphate aldolase		GO:0006116
UniProtKB:P0DOB5	ATP-dependent 6-phosphofructokinase		GO:0006116
UniProtKB:Q9ALA2	NAD(P) transhydrogenase subunit alpha		GO:0006116
UniProtKB:Q07637	Pyruvate kinase		GO:0006116
UniProtKB:P05062	Fructose-bisphosphate aldolase B		GO:0006116
UniProtKB:P08201	Nitrite reductase (NADH) large subunit		GO:0006116
MGI:MGI:95679	glycerol-3-phosphate dehydrogenase 1 (soluble)		GO:0006116
MGI:MGI:95679	glycerol-3-phosphate dehydrogenase 1 (soluble)		GO:0006127
RGD:621381	glycerol-3-phosphate dehydrogenase 1		GO:0006116
FB:FBgn0022160	Glycerophosphate oxidase 1		GO:0006127
FB:FBgn0001098	Glutamate dehydrogenase		GO:0006116
UniProtKB:P0DMQ6	Sorbitol dehydrogenase		GO:0006116
SGD:S000001417	Mitochondrial glycerol-3-phosphate dehydrogenase		GO:0006116
AGI_LocusCode:AT3G10370	SUGAR-DEPENDENT 6		GO:0006127
SGD:S000002243	Mitochondrial external NADH dehydrogenase		GO:0006116
SGD:S000002180	NAD-dependent glycerol-3-phosphate dehydrogenase		GO:0006116
RGD:1311112	phosphoenolpyruvate carboxykinase 2 (mitochondrial)		GO:0006116
RGD:1311112	phosphoenolpyruvate carboxykinase 2 (mitochondrial)		GO:0006116
RGD:2503	NAD(P)H quinone dehydrogenase 1		GO:0006116
SGD:S000000349	Alcohol dehydrogenase isoenzyme V		GO:0006116
SGD:S000004589	NADH:ubiquinone oxidoreductase		GO:0006116
SGD:S000004918	Glucose-repressible alcohol dehydrogenase II		GO:0006116
SGD:S000005446	Alcohol dehydrogenase		GO:0006116
SGD:S000005446	Alcohol dehydrogenase		GO:0006116
SGD:S000005446	Alcohol dehydrogenase		GO:0006116
SGD:S000005420	NAD-dependent glycerol 3-phosphate dehydrogenase		GO:0006116
SGD:S000004753	Mitochondrial external NADH dehydrogenase		GO:0006116
SGD:S000004688	Mitochondrial alcohol dehydrogenase isozyme III		GO:0006116

**Comment by pgaudet** [comment]
Hi @deustp01 
In the wiki page you cite, 'NADH oxidation' is also described as 'NAD regeneration' (specifically, the authors write "Since the malate–aspartate shuttle regenerates NADH inside the mitochondrial matrix"). We also have a GO term for [NADH regeneration](http://purl.obolibrary.org/obo/GO_0006735); would that not be a more appropriate description of the biological purpose of the malate–aspartate shuttle? 

Pascale

**Comment by deustp01** [comment]
> ... would that not be a more appropriate description of the biological purpose of the malate–aspartate shuttle?

The way we used to explain the process to medical students is that, as a result of glycolysis NADH accumulates in the cytosol where it can't be used for much (mostly only NADPH can be be used for biosyntheses and there's no easy way to convert cytosolic NADH to NADPH) and meanwhile the pool of NAD+ needed for continued glycolysis is depleted. The shuttle transfers NADH to the mitochondrion where it can be fed into mitochondrial oxidative phosphorylation, yielding much useful energy, coupled to the restoration of cytosolic NAD+ via the molecular interconversions of the shuttle. So if it is regeneration of anything, it would be NAD+ regeneration, but if there is some sort of NAD(H) homoeostasis term, that would be a better fit to the idea that the whole process works to maintain appropriate levels of NAD and NADH in various cellular compartments. Sanity check, @sjm41

**Comment by ValWood** [comment]
@sjm41 @rozaru did https://github.com/geneontology/go-ontology/issues/28982
make this ticket obsolete? 
Do you agree that the matale aspartate shuttle supports the respiratory transport chain, but isn't part of it? of do you think the relationship should be part_of?

**Comment by sjm41** [comment]
> @sjm41 @rozaru did https://github.com/geneontology/go-ontology/issues/28982
make this ticket obsolete?

Yes, I believe so - I'll close this one.

> Do you agree that the matale aspartate shuttle supports the respiratory transport chain, but isn't part of it?
Yes.
