### ISSUE TITLE
Test change definitions for L-cysteine

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#27944]
Hey ontobot! apply: 

* change definition of GO:0000008 from 'OBSOLETE. A small disulfide-containing redox protein that serves as a general protein disulfide oxidoreductase. Interacts with a broad range of proteins by a redox mechanism, based on the reversible oxidation of 2 cysteine thiol groups to a disulfide, accompanied by the transfer of 2 electrons and 2 protons. The net result is the covalent interconversion of a disulfide and a dithiol.' to 'OBSOLETE. A small disulfide-containing redox protein that serves as a general protein disulfide oxidoreductase. Interacts with a broad range of proteins by a redox mechanism, based on the reversible oxidation of 2 L-cysteine thiol groups to a disulfide, accompanied by the transfer of 2 electrons and 2 protons. The net result is the covalent interconversion of a disulfide and a dithiol.'
* change definition of GO:0000096 from 'The chemical reactions and pathways involving amino acids containing sulfur, comprising cysteine, homocysteine, methionine and selenocysteine.' to 'The chemical reactions and pathways involving amino acids containing sulfur, comprising L-cysteine, homocysteine, methionine and selenocysteine.'
change definition of GO:0000097 from 'The chemical reactions and pathways resulting in the formation of amino acids containing sulfur, comprising cysteine, methionine and selenocysteine.' to 'The chemical reactions and pathways resulting in the formation of amino acids containing sulfur, comprising L-cysteine, methionine and selenocysteine.'

**Comment by ValWood** [comment]
Did this work?

**Comment by pgaudet** [comment]
No. We need a different strategy.
