### ISSUE TITLE
GO ribbon for viruses

### ISSUE THREAD

**Issue by jrr-cpt** [geneontology/go-ontology#27946]
Based on ribbon discussion at GOC meeting, I am suggesting the development of a virus ribbon to be applicable for NCBITaxon 10239, Viruses. That may require the development of a slim subset.

There was a virus slim back in 2015 https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4517558/, but I don't see it in the list anymore.

Although the multi-organism modifications to symbiont terms will likely bear on this, two 2017 papers on eukaryotic viruses (https://pubmed.ncbi.nlm.nih.gov/28207819/) and bacterial viruses (https://pubmed.ncbi.nlm.nih.gov/28545254/) would be a good place to start. 

@pgaudet

**Comment by pgaudet** [comment]
Hi @jrr-cpt 
There was this slim - http://release.geneontology.org/2016-04-01/ontology/subsets/goslim_virus.obo

I cannot tell when/why it was retired. Would that be a good place to start? Or if you have a list of useful terms you'd like to include? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Virus slim from 2015 
![image](https://github.com/geneontology/go-ontology/assets/4782928/b7020dfa-cc1b-4930-9a43-9a6c37abb864)


![image](https://github.com/geneontology/go-ontology/assets/4782928/8c48503a-5362-4299-993d-f27ea9203caf)

**Comment by pgaudet** [comment]
Hi @jrr-cpt 

I have added the virus subset: 

- GO:0001907 	symbiont-mediated killing of host cell 
- GO:0016032	viral process
- GO:0019049	virus-mediated perturbation of host defense response
- GO:0019058	viral life cycle
- GO:0019062	virion attachment to host cell
- GO:0019068	virion assembly
- GO:0019072	viral genome packaging
- GO:0019080	viral gene expression
- GO:0019083	viral transcription
- GO:0035891	exit from host cell
- GO:0039693	viral DNA genome replication
- GO:0044003	modulation by symbiont of host process
- GO:0044409	symbiont entry into host
- GO:0052008	symbiont-mediated disruption of host cellular anatomical entity
- GO:0075528	perturbation by virus of host immune response


According to GOA, it covers most manual annotations:  GO ID- term label - number of manual annotations to viral proteins  (search was restricted to [taxon:10239](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=10239)

GO:0039689    negative stranded viral RNA replication	106
GO:0039520    induction by virus of host autophagy	62
GO:0039695    DNA-templated viral transcription	59
GO:0039696    RNA-templated viral transcription	55
GO:0039686    bidirectional double-stranded viral DNA replication	45
GO:0039693    viral DNA genome replication	37
GO:0019079    viral genome replication	35
GO:0044659    viral release from host cell by cytolysis	33
GO:0046813    receptor-mediated virion attachment to host cell	30
GO:0019073    viral DNA genome packaging	27
GO:0039694    viral RNA genome replication	24
GO:0019058    viral life cycle	22
GO:0039501    suppression by virus of host type I interferon production	21
GO:0039697    negative stranded viral RNA transcription	21
GO:0019062    virion attachment to host cell	19
GO:0075512    clathrin-dependent endocytosis of virus by host cell	18
GO:0039684    rolling circle single-stranded viral DNA replication	17
GO:0046761    viral budding from plasma membrane	17
GO:0098996    symbiont entry into host cell via disruption of host cell glycocalyx	17
GO:0046718    symbiont entry into host cell	15
GO:0019069    viral capsid assembly	14
GO:0039708    nuclear capsid assembly	14
GO:0098003    viral tail assembly	14
GO:0019068    virion assembly	13
GO:0039690    positive stranded viral RNA replication	13
GO:0039704    viral translational shunt	11
GO:0046760    viral budding from Golgi membrane	10
GO:0019065    receptor-mediated endocytosis of virus by host cell	9
GO:0019083    viral transcription	9
GO:0039687    viral DNA strand displacement replication	9
GO:0099002    symbiont genome ejection through host cell envelope, short tail mechanism	9
GO:0019064    fusion of virus membrane with host plasma membrane	8
GO:0046765    viral budding from nuclear membrane	8
GO:0075528    perturbation by virus of host immune response	8
GO:0019080    viral gene expression	7
GO:0019074    viral RNA genome packaging	6
GO:0039521    suppression by virus of host autophagy	6
GO:0039666    virion attachment to host cell pilus	6
GO:0039702    viral budding via host ESCRT complex	6
GO:0046774    suppression by virus of host intracellular interferon activity	6
GO:0019046    release from viral latency	5
GO:0019048    modulation by virus of host process	5
GO:0019076    viral release from host cell	5
GO:0019082    viral protein processing	5
GO:0039640    viral release via suppression of host peptidoglycan biosynthetic process	5
GO:0098004    virus tail fiber assembly	5
GO:0098671    adhesion receptor-mediated virion attachment to host cell	5

**Comment by pgaudet** [comment]
let me know if there are terms think are missing. 

I think we can use the same subset for ribbons and for binning. 

Thanks, Pascale

**Comment by pgaudet** [comment]
@pmasson55 let me know if you have any suggestions to improve this subset.

**Comment by pgaudet** [comment]
updated metadata file

  - id: goslim_virus
    title: Virus slim
    short_label: Viruses
    status: active
    description: Virus-relevant terms
    role: Binning, Ribbon
    taxa:
      - id: NCBITaxon:10239
        label: Viruses
    tracker: https://github.com/geneontology/go-ontology/issues
    contact:
      - email: go-ontology@lists.stanford.edu
      label: GO Ontology Curators
    tracker: https://github.com/geneontology/go-ontology/issues
    contributors:
      - email: go-ontology@lists.stanford.edu
        label: GO Ontology Curators

**Comment by jrr-cpt** [comment]
It's good for the process terms to cover the most annotated processes. There are also some cellular component terms that would expand the ribbon in a useful way. I'm not sure if the preference is to use higher level terms that can encompass more annotations to child terms (is that how the ribbon tallies?), such as virion component and host cell part, or to use more specific terms, like viral capsid ([GO:0019028](https://www.ebi.ac.uk/QuickGO/term/GO:0019028)) and host cell nucleus ([GO:0042025](https://www.ebi.ac.uk/QuickGO/term/GO:0042025))?

**Comment by pgaudet** [comment]
Hi @jrr-cpt 

We can add up to 15 terms and still have the ribbon quite easily displayed on a webpage.

**Comment by pgaudet** [comment]
I've added 


- viral capsid GO:0019028
- host cell nucleus GO:0042025
- host cell plasma membrane
- symbiont-containing vacuole
- host cell Golgi apparatus
- host cell endoplasmic reticulum

Let me know if you think other terms should be added. 

Thanks, Pascale
