### ISSUE TITLE
Term merge: serine C-palmitoyltransferase complex  & SPOTS complex

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#27951]
We currently have this single parentage is_a hierarchy:
```
serine C-palmitoyltransferase complex (GO:0017059)
        |__SPOTS complex (GO:0035339)
```

id: GO:0017059 (16 EXP annotations direct to term)
name: serine C-palmitoyltransferase complex
def: "An enzyme complex that catalyzes the transfer of a palmitoyl on to serine, forming 3-dehydro-D-sphinganine." [PMID:19416851]
is_a: GO:0031211 ! endoplasmic reticulum palmitoyltransferase complex
is_a: GO:1902494 ! catalytic complex
relationship: capable_of GO:0004758 ! serine C-palmitoyltransferase activity

id: GO:0035339  (22 EXP annotations direct to term)
name: SPOTS complex
def: "A multiprotein complex at least composed of serine palmitoyltransferases and ORM proteins (known as ORMDL proteins in mammals and other higher vertebrates) that plays a key role in sphingolipid homeostasis." [PMID:20182505]
synonym: "serine palmitoyltransferase, Orm1/2, Tsc3 and Sac1 complex" NARROW []
is_a: GO:0017059 ! serine C-palmitoyltransferase complex

---

'serine C-palmitoyltransferase complex' is defined in [PMID:19416851] from 2009.
That paper says:
- In yeast, SPT is composed of a heterodimer of 2 highly-related subunits, Lcb1p and Lcb2p, and a third subunit, Tsc3p, which increases enzyme activity markedly
- The human complex comprises hLCB1 (SPTLC1) and hLCB2 (SPTLC2), together with ssSPTa (SPTSSA) or ssSPTb (SPTSSB) as the activator subunit 

'SPOTS complex' is defined in [PMID:20182505] from the following year, 2010.
That paper says:
- this yeast complex comprises Lcb1, Lcb2 and Tsc3 (as above) plus also Orm1/2 and Sac1
- They also show that human ORMDL3 binds to SPTLC1, suggesting the inclusion of Orm/ORMDL in the complex is conserved.

A later review (PMID:29863195 from 2018) says:
- At high SL levels, SPT1, SPT2, Tsc3p, Sac1, ORM1 and ORM2 exist in the “SPOTS complex” where association with the ORMs results in inhibition of SPT activity. ORMDL family proteins regulate SL biosynthesis in mammals and associate with SPT in a similar manner to ORMs in yeast

That is, the SPOTS complex is effectively the same as the 'serine C-palmitoyltransferase complex', but with ORM proteins present under certain conditions.

An even more recent paper (PMID: 33558761 from 2021) states:
- In humans, the first and rate-limiting step of sphingolipid synthesis is catalyzed by the serine palmitoyltransferase holocomplex, which consists of catalytic components (SPTLC1 and SPTLC2), and regulatory components (ssSPTa and ORMDL3)._ 
- eukaryotic SPTs...are elaborately regulated by two other membrane protein families: ssSPTs (small subunits of SPT) and ORMDLs (orosomucoid-like protein). SPTs, ssSPTs and ORMDLs are thought to coexist in a large, dynamic protein complex[5]. ssSPTs determine substrate selectivity and are positive regulators that enhance the SPT activity[25], whereas ORMDLs are negative regulators that reduce the SPT activity._

So...I propose the 'serine C-palmitoyltransferase complex' and 'SPOTS complex' are merged with a new definition and refs, like so:

name: serine palmitoyltransferase complex
def: "A protein complex that catalyses the condensation of L-serine with palmitoyl-CoA to form 3-ketosphinganine, the sphingoid base which is the starting point for all sphingolipids. In bacteria the enzyme is a cytoplasmic homodimer, whereas in eukaryotes the enzyme is a multiprotein complex localised to the endoplasmic reticulum. The eukaryotic complex consists of catalytic components (SPTLC1, SPTLC2 and SPTLC3 in humans; LCB1 and LCB2 in S. cerevisiae) and regulatory components, which include activators (SPTSSA/SPTSSB in humans, TSC3 in S. cerevisiae) and negative regulators (ORMDL1/ORMDL2/ORMDL3 in humans, ORM1/2 in S. cerevisiae )." [PMID:29863195, PMID:33558761]
is_a: GO:0031211 ! endoplasmic reticulum palmitoyltransferase complex
is_a: GO:1902494 ! catalytic complex
relationship: capable_of GO:0004758 ! serine C-palmitoyltransferase activity
synonyms: SPOTS complex, serine C-palmitoyltransferase complex, SPT, serine palmitoyltransferase, Orm1/2, Tsc3 and Sac1 complex

**Comment by sjm41** [comment]
Thanks @raymond91125 
I just noticed that we should remove the "is_a: GO:0031211 ! endoplasmic reticulum palmitoyltransferase complex" parent since that is only applicable to the eukaryotic complex and the term covers both bacterial and eukaryotic complexes.
I can do that step myself.

**Comment by raymond91125** [comment]
Thanks.
