### ISSUE TITLE
Term merge: GO:0097224 and GO:0120212

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#28003]
* **Term to be merged: Provide GO ID and term label**

GO:0097224 and GO:0120212

sperm connecting piece and sperm head-tail coupling apparatus 

they sound like the same thing?

The segment of the sperm flagellum that attaches to the implantation fossa of the nucleus in the sperm head; from the remnant of the centriole at this point, the axoneme extends throughout the length of the flagellum. 

A centrosome-based structure consisting of two cylindrical microtubule-based centrioles and associated components which anchors the flagellum to the sperm head

![image](https://github.com/geneontology/go-ontology/assets/12727506/bf7b52ce-4720-4cf1-8191-aac217a9b32f)

**Comment by raymond91125** [comment]
PMID:31995163 The coupling apparatus of the sperm head and tail

**Comment by Antonialock** [comment]
thanks. Out of interest why the obsoletion and not the merge? @raymond91125

**Comment by raymond91125** [comment]
@Antonialock We've changed our practice to obsolete with replaced_by instead of merging. This way makes the term history more tractable. Thank you!
