### ISSUE TITLE
NTR: beta-arrestin-dependent dopamine receptor signaling pathway

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28005]
Following up on https://github.com/geneontology/go-ontology/issues/26959

After discussion with @hattrill we agree that we should look into creating a new term under 'GO:0007166 cell surface signaling pathway',  based on the paper @raymond91125 cited, PMID: 25671228, and also PMID:35688404. 

One problem is that there are no general beta-arrestin or GSK3 signaling pathway terms in GO, so no 'module' we can reuse. Beta-arrestin a an adaptor that seem to activate may different proteins; can a a pathway in which the receptor binds beta-arrestin be defined unambiguously? 

The mechanism of signaling is not clear: PMID: 25671228, mentions PP2, Akt and GSK3A, while 

PMID:35688404 mentions Akt, PI3K, MAP kinases but not GSK3

![image](https://github.com/geneontology/go-ontology/assets/4782928/be7ba976-5f4c-4d18-bbab-8dcd4406355f)

![image](https://github.com/geneontology/go-ontology/assets/4782928/da03b48d-b15c-4a54-a6fc-7128967770df)

Are these the same pathway? 

The first step would be with it to review the direct annotations to GO:0007212 dopamine receptor signaling pathway (39 EXP) and see if they can be made more precise with existing terms, or if we already need a new term. 

@raymond91105 can you please set up an annotation review? 

Thanks, Pascale

**Comment by raymond91125** [comment]
@pgaudet For annotation review, is the proposal to make dopamine receptor signaling pathway do_not_annotate or obsolete or something else? Thanks.

**Comment by raymond91125** [comment]
The PMID:25671228 figure above is about D2R whereas PMID:35688404 D1R. As indicated in PMID:28328745, G-protein independent arrestin signaling is quite varied regarding both upstream (many different 7TM receptors) and downstream (kinase and non-kinase).

Perhaps we could do:
GO:0007166 cell surface signaling pathway
    GO:0007212 dopamine receptor signaling pathway (do_not_annotate)
        GO:0007191 adenylate cyclase-activating dopamine receptor signaling pathway (G protein-coupled receptor signaling pathway)
        GO:0007195 adenylate cyclase-inhibiting dopamine receptor signaling pathway (G protein-coupled receptor signaling pathway)
        GO:0060158 phospholipase C-activating dopamine receptor signaling pathway (G protein-coupled receptor signaling pathway)
        GO:nnnnnnn beta-arrestin-dependent dopamine receptor signaling pathway (LD = 'dopamine receptor signaling pathway'
 and ('has part' some 'arrestin-family protein binding'))

**Comment by pgaudet** [comment]
This looks good to me. @hattrill ?

**Comment by RLovering** [comment]
Hi
I think I have found a review which confirms the beta-arrestin-dependent dopamine receptor signaling pathway. Is this term going to be created?

https://pubmed.ncbi.nlm.nih.gov/21711983/ - if so I will use it and maybe try to curate that experimental paper.

Or is there a beta-arrestin/AKT/GSK signaling pathway that I have missed and therefore could state that the DRs pos reg the beta-arrestin/AKT/GSK signaling pathway

Thanks
Ruth

**Comment by pgaudet** [comment]
@raymond91125 Can you please create that new term?

**Comment by raymond91125** [comment]
What is the proper parent term? We don't have dopamine receptor signaling pathway anymore.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160213
+name: beta-arrestin-dependent dopamine receptor signaling pathway
+namespace: biological_process
+def: "A beta-arrestin-dependent signaling pathway initiated by a dopamine binding to its receptor on the surface of a target cell, and ending with the regulation of a downstream cellular process." [PMID:21711983, PMID:25671228]
+is_a: GO:0007166 ! cell surface receptor signaling pathway
+relationship: part_of GO:1903351 ! cellular response to dopamine
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28005" xsd:anyURI
+created_by: rynl
+creation_date: 2024-09-12T19:51:02Z
