### ISSUE TITLE
Ensure reactome mappings are checked prior to obsoletion

### ISSUE THREAD

**Issue by cmungall** [geneontology/go-ontology#28013]
When we check for term usage, we check for reactome mappings, such that @deustp01 can anticipate changes

See comments here for context:

 - https://github.com/geneontology/go-ontology/issues/27081#issuecomment-2147465217

We should do this in a way that it doesn't entail any additional work for GO editors - if we use the OAK usage check then this should be straightforward

**Comment by pgaudet** [comment]
There is a ticket here: 
https://github.com/geneontology/go-annotation/issues/4963

I'll ping Seth again.

**Comment by cmungall** [comment]
OK, we can close in favor of that. I'm 99% sure that checking the annotations derived from reactome should give the same results as checking reactome directly (doing the latter is now easy as reactome is registered in semantic-sql).
