### ISSUE TITLE
NTR: [peptide lactyltransferase (ATP dependent) activity] [protein lysine delactylase activity]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#28015]
Hi GO,

I would need a couple of terms for protein lactylation and delactylation. 

Please note that the lactyltransferase activity takes place in two consecutive steps, it is why it is associated with 2 Rhea reactions. I specified the ATP-dependence in the name since protein lactylation can also take place using CoA. 

I think it is useful to discriminate between the CoA- and ATP-dependent reactions, since they involve different metabolites, which is important in term of metabolism.

Thanks

Sylvain

1)
Name: peptide lactyltransferase (ATP dependent) activity
Definition: Catalysis of the reaction: lactate + ATP + L-lysyl-[protein] = N(6)-lactoyl-L-lysyl-[protein]+  AMP + diphosphate
child of GO:0016874 ligase activity
PMID:38653238
PMID:38512451
Xref RHEA:80271
Xref RHEA:80275

2)
Name: protein lysine delactylase activity
Definition; Catalysis of the reaction: H2O + N6-lactoyl-L-lysyl-[protein] + NAD = L-lysyl-[protein] + nicotinamide +2''-O-lactoyl-ADP-D-ribose 
Child of GO:0033558 protein lysine deacetylase activity
PMID:38512451
RHEA:80287

3) Please update the name of the following GO terms to specify that these reactions are CoA-dependent
GO:0120300 peptide lactyltransferase activity (CoA dependent)
GO:0120301 histone lactyltransferase activity (CoA dependent)

4) We should also change the hierarchy of GO:0106231, which is wrong.
GO:0106231 protein-propionyllysine depropionylase activity should be a child of Child of GO:0033558 protein lysine deacetylase activity

**Comment by pgaudet** [comment]
Hi @sylvainpoux 
for point 1: new term is here: 

+[Term]
+id: GO:0141207
+name: peptide lactyltransferase (ATP-dependent) activity
+namespace: molecular_function
+def: "Catalysis of the reaction: lactate + ATP + L-lysyl-[protein] = N(6)-lactoyl-L-lysyl-[protein]+ AMP + diphosphate\nchild of GO:0016874 ligase activity. Can also act on free lactate." [PMID:38512451, PMID:38653238, RHEA:80271]
+synonym: "peptide lactyltransferase (ATP dependent) activity" EXACT []
+synonym: "peptide lactyltransferase activity" BROAD []
+xref: RHEA:80271 {source="skos:exactMatch"}
+xref: RHEA:80271 {comment="skos:narrowMatch"}
+is_a: GO:0016886 ! ligase activity, forming phosphoric ester bonds
+is_a: GO:0140096 ! catalytic activity, acting on a protein
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28015" xsd:anyURI
+created_by: pg
+creation_date: 2024-06-07T08:13:32Z

**Comment by pgaudet** [comment]
Point 2: NTR:  protein lysine delactylase activity

+[Term]
+id: GO:0141208
+name: protein lysine delactylase activity
+namespace: molecular_function
+synonym: "Catalysis of the reaction: H2O + N6-lactoyl-L-lysyl-[protein] + NAD = L-lysyl-[protein] + nicotinamide +2''-O-lactoyl-ADP-D-ribose, removing a lactoyl group attached to a lysine residue in a protein." BROAD [PMID:38512451, RHEA:80287]
+xref: RHEA:80287
+is_a: GO:0033558 ! protein lysine deacetylase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28015" xsd:anyURI
+created_by: pg
+creation_date: 2024-06-07T08:37:00Z

**Comment by pgaudet** [comment]
Fixed point 3& 4 as requested, although it seems we're missing that these reactions are acyl/acetyl transferases; aren't we?

**Comment by sylvainpoux** [comment]
Hi @pgaudet 
Many thanks for the new terms!
Not sure to understand your question.
For point 3: peptide lactyltransferase activity (CoA dependent) is a child of N-acyltransferase activity, which is correct I think

Concerning point 4, GO:0106231 protein-propionyllysine depropionylase was a child of N-acyltransferase activity (a transferase), which was incorrect for a hydrase reaction

Sylvain

**Comment by pgaudet** [comment]
OK thanks for checking!

**Comment by sjm41** [comment]
For this NTR:

+[Term]
+id: GO:0141207
+name: peptide lactyltransferase (ATP-dependent) activity
+namespace: molecular_function
+def: "Catalysis of the reaction: lactate + ATP + L-lysyl-[protein] = N(6)-lactoyl-L-lysyl-[protein]+ AMP + diphosphate. Can also act on free lactate." [PMID:38512451, PMID:38653238, RHEA:80271]
+synonym: "peptide lactyltransferase (ATP dependent) activity" EXACT []
+synonym: "peptide lactyltransferase activity" BROAD []
+xref: RHEA:80271 {source="skos:exactMatch"}
+xref: RHEA:80271 {comment="skos:narrowMatch"}
+is_a: GO:0016886 ! ligase activity, forming phosphoric ester bonds
+is_a: GO:0140096 ! catalytic activity, acting on a protein
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28015" xsd:anyURI
+created_by: pg
+creation_date: 2024-06-07T08:13:32Z


Looks like "xref: RHEA:80271 {comment="skos:narrowMatch"}" should be:
 "+xref: RHEA:80275 {source="skos:narrowMatch"}"

I'll make that change now.
