### ISSUE TITLE
Term merge: 3-methylcrotonyl-CoA carboxylase complex, mitochondrial & methylcrotonoyl-CoA carboxylase complex

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28023]
* **Term to be merged: Provide GO ID and term label**
id: GO:0002169
name: 3-methylcrotonyl-CoA carboxylase complex, mitochondrial
def: "A mitochondrial protein complex which is capable of 3-methylcrotonyl-CoA carboxylase activity. In mammals, at least, consists as a dodecamer of 6 alpha and 6 beta subunits. MCCC-alpha has a covalently bound biotin essential for the ATP-dependent carboxylation. MCCC-beta possesses carboxyltransferase activity which presumably is essential for binding to 3-methylcrotonyl-CoA." [GOC:bf, GOC:hjd, PMID:15868465, PMID:17360195, PMID:22869039]
synonym: "mitochondrial 3-methylcrotonyl-CoA carboxylase holoenzyme" EXACT [PMID:22869039]
synonym: "mitochondrial MCCC complex" EXACT [GOC:bf]
synonym: "mitochondrial methylcrotonoyl-CoA carboxylase complex" EXACT [GOC:bf]
intersection_of: GO:0098798 ! mitochondrial protein-containing complex
intersection_of: capable_of GO:0004485 ! methylcrotonoyl-CoA carboxylase activity

* **Which term do you propose this term merge into? Provide GO ID and term label**
id: GO:1905202
name: methylcrotonoyl-CoA carboxylase complex
def: "A protein complex which is capable of methylcrotonoyl-CoA carboxylase activity." [GO_REF:0000088, GOC:bf, GOC:PARL, GOC:TermGenie, PMID:22158123]
intersection_of: GO:0032991 ! protein-containing complex
intersection_of: capable_of GO:0004485 ! methylcrotonoyl-CoA carboxylase activity

* **Reason for merge**
- '3-methylcrotonyl-CoA carboxylase complex, mitochondrial' is the single child term of 'methylcrotonoyl-CoA carboxylase complex' - there doesn't appear to be a need for this compartment-specific term
- there are only 2 EXP annotations to the mitochondrial-specific term (by Complex Portal to human MCCC1 and MCCC2 from PMID:17360195), and these are co-annotated with the parent term from the same paper.

* **Any other information**
Def of merged term could be:
"A protein complex capable of methylcrotonoyl-CoA carboxylase activity. In mammals, it is a mitochondrial complex comprising a dodecamer of 6 alpha and 6 beta subunits: MCCC-alpha has a covalently bound biotin essential for the ATP-dependent carboxylation; MCCC-beta possesses carboxyltransferase activity which presumably is essential for binding to 3-methylcrotonyl-CoA." [GOC:bf, GOC:PARL, GOC:hjd, PMID:15868465, PMID:17360195, PMID:22158123, PMID:22869039]

**Comment by raymond91125** [comment]
Oops. Thanks for catching it.
