### ISSUE TITLE
TTP reductase activity & CTP reductase activity - merge into ribonucleoside-triphosphate reductase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28055]
id: GO:0051064
name: TTP reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: dTTP + thioredoxin disulfide + H2O = TTP + thioredoxin. Thioredoxin disulfide is the oxidized form of thioredoxin." [MetaCyc:1.17.4.2-RXN]
synonym: "TTP reduction" RELATED []
xref: EC:1.17.4.-
is_a: GO:0008998 ! ribonucleoside-triphosphate reductase activity
=> 0 annotations

id: GO:0051065
name: CTP reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: dCTP + thioredoxin disulfide + H2O = CTP + thioredoxin. Thioredoxin disulfide is the oxidized form of thioredoxin." [MetaCyc:1.17.4.2-RXN]
synonym: "CTP reduction" RELATED []
xref: EC:1.17.4.-
is_a: GO:0008998 ! ribonucleoside-triphosphate reductase activity
=> 1 annotation to nrdD. 

Both defs above cite MetaCyc:1.17.4.2-RXN, which equates to EC:1.17.4.2 = GO:0008998:

id: GO:0008998
name: ribonucleoside-triphosphate reductase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2'-deoxyribonucleoside triphosphate + thioredoxin disulfide + H2O = ribonucleoside triphosphate + thioredoxin." [EC:1.17.4.2]
synonym: "2'-deoxyribonucleoside-triphosphate:oxidized-thioredoxin 2'-oxidoreductase activity" RELATED [EC:1.17.4.2]
synonym: "2'-deoxyribonucleoside-triphosphate:thioredoxin-disulfide 2'-oxidoreductase activity" RELATED [EC:1.17.4.2]
synonym: "ribonucleotide reductase activity" BROAD [EC:1.17.4.2]
xref: EC:1.17.4.2
xref: MetaCyc:1.17.4.2-RXN
xref: RHEA:12701
is_a: GO:0016728 ! oxidoreductase activity, acting on CH or CH2 groups, disulfide as acceptor

**So merge GO:0051064 and GO:0051065 into GO:0008998**

**Comment by pgaudet** [comment]
Hi @raymond91125 Can you please take this one?

**Comment by raymond91125** [comment]
I thought ribonucleoside-triphosphate reductase activity does not work on TTP. It should've been UTP.

**Comment by pgaudet** [comment]
Good point, even a better reason to obsolete this !
