### ISSUE TITLE
ADP/ATP dimethylallyltransferase activity GO:0052622/GO:0052623

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28059]
id: GO:0052622
name: ATP dimethylallyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: delta(2)-isopentenyl diphosphate + ATP = diphosphate + N6-(delta(2)-isopentenyl)adenosine 5'-triphosphate." [EC:2.5.1.27, MetaCyc:RXN-4303]
synonym: "2-isopentenyl-diphosphate:ATP 2-isopentenyltransferase activity" EXACT []
synonym: "2-isopentenyl-diphosphate:ATP delta2-isopentenyltransferase activity" EXACT [KEGG_REACTION:R08052]
synonym: "ATP isopentenyltransferase activity" EXACT []
synonym: "dimethylallyl-diphosphate:ATP dimethylallyltransferase activity" RELATED [EC:2.5.1.27]
xref: EC:2.5.1.-
xref: KEGG_REACTION:R08052
xref: MetaCyc:RXN-4303
is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups
created_by: ai
creation_date: 2010-08-26T10:45:38Z

- [ ] MetaCyc:RXN-4303 says this is EC:2.5.1.112 adenylate dimethylallyltransferase (ADP/ATP-dependent), so add that EC as a broadMatch
- [ ] Remove partial EC xref 
- [ ] Add RHEA xref RHEA:36331
- [ ] Check def matches RHEA:36331
- [ ] Change KEGG xref to  KEGG_REACTION:R08051

id: GO:0052623
name: ADP dimethylallyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: delta2-isopentenyl diphosphate + ADP = diphosphate + N6-(delta(2)-isopentenyl)adenosine 5'-diphosphate." [EC:2.5.1.27, MetaCyc:RXN-4305]
synonym: "2-isopentenyl-diphosphate:ADP 2-isopentenyltransferase activity" EXACT []
synonym: "2-isopentenyl-diphosphate:ADP delta2-isopentenyltransferase activity" EXACT [KEGG_REACTION:R08051]
synonym: "ADP isopentenyltransferase activity" EXACT []
synonym: "dimethylallyl-diphosphate:ADP dimethylallyltransferase activity" RELATED [EC:2.5.1.27]
xref: EC:2.5.1.-
xref: KEGG_REACTION:R08051
xref: MetaCyc:RXN-4305
is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups
created_by: ai
creation_date: 2010-08-26T10:45:44Z

- [ ] MetaCyc:RXN-4303 says this is EC:2.5.1.112 adenylate dimethylallyltransferase (ADP/ATP-dependent), so add that EC as a broadMatch
- [ ] Remove partial EC xref 
- [ ] Add RHEA xref RHEA: 36327
- [ ] Check def matches RHEA: 36327
- [ ] Change KEGG xref to  KEGG_REACTION: R08052

ALTERNATIVELY:
Both these terms have the same two EXP annotations to Arabidopsis IPT1 [PMID:15998742] and IPT4 [PMID:11479373].
Similarly, the two RHEAs here are associated with the same 8 proteins in UP.

So may be better just to have the one term here corresponding to EC:2.5.1.112 with the 2 RHEA/KEGG xrefs as narrowMatch xrefs.
@pgaudet ?

**Comment by pgaudet** [comment]
I agree, let's merge these two.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0052623 ADP dimethylallyltransferase activity and replace by GO:0052622 ATP dimethylallyltransferase activity.  The reason for obsoletion is that these terms represent the same activity; ATP or ADP can be used as the phosphate donor. Annotations to both terms are identical. Mappings will be bane narrow cross references on GO:0052622 ATP dimethylallyltransferase activity. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/28059

Thanks, Pascale

**Comment by sjm41** [comment]
EC name is "adenylate dimethylallyltransferase (ADP/ATP-dependent)", so I guess we either use "adenylate dimethylallyltransferase (ADP/ATP-dependent) activity" as the final name, or follow the current GO names and use the briefer "ADP/ATP dimethylallyltransferase activity"?
