### ISSUE TITLE
 bidentate ribonuclease III activity GO:0016443

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28074]
id: GO:0016443
name: bidentate ribonuclease III activity
namespace: molecular_function
def: "Catalysis of the digestion of double-stranded RNAs into 20 to 30-nucleotide products. These products typically associate to the RNA-induced silencing complex and serve as guide RNAs for posttranslational RNA interference." [PMID:15242644]
synonym: "bidentate RNase III activity" EXACT []
xref: EC:3.1.26.-
is_a: GO:0004525 ! ribonuclease III activity

- [x] EC:3.1.26.- should be removed from GO:0016443 since it is a grouping class, and is already correctly an xref on this term:

GO:0016891
name: RNA endonuclease activity, producing 5'-phosphomonoesters
def: "Catalysis of the hydrolysis of ester linkages within ribonucleic acids by creating internal breaks to yield 5'-phosphomonoesters." [GOC:ai]
xref: EC:3.1.26.-

- [ ] Alternatively, since GO:0016443 bidentate ribonuclease III activity is the only child of 'ribonuclease III activity' and has only been used in two annotations (to fly Dcr-1 and Dcr-2), I think it could be merged into its parent term:

id: GO:0004525
name: ribonuclease III activity
namespace: molecular_function
def: "Catalysis of the endonucleolytic cleavage of RNA with 5'-phosphomonoesters and 3'-OH termini; makes two staggered cuts in both strands of dsRNA, leaving a 3' overhang of 2 nt." [PMID:11157775, PMID:15242644]
synonym: "pre-mRNA 3'-end processing endonuclease" NARROW []
synonym: "ribonuclease 3 activity" RELATED [EC:3.1.26.3]
synonym: "RNase III activity" RELATED [EC:3.1.26.3]
xref: EC:3.1.26.3
xref: MetaCyc:3.1.26.3-RXN
is_a: GO:0016891 ! RNA endonuclease activity, producing 5'-phosphomonoesters
is_a: GO:0032296 ! double-stranded RNA-specific ribonuclease activity

**Comment by pgaudet** [comment]
Noting that the GO reaction talks about a 2nt overhang "Catalysis of the endonucleolytic cleavage of RNA with 5'-phosphomonoesters and 3'-OH termini; makes two staggered cuts in both strands of dsRNA, leaving a 3' overhang of 2 nt.", not mentioned by EC https://enzyme.expasy.org/EC/3.1.26.3
