### ISSUE TITLE
ribonuclease R activity GO:0008997

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28072]
id: GO:0008997
name: ribonuclease R activity
namespace: molecular_function
def: "Catalysis of the reaction: RNA + H2O = 5'-phosphomononucleotides. Cleaves RNA in the 3' to 5' direction, leaving an undigested core of 3-5 nucleotides." [PMID:11948193]
xref: EC:3.1.11.-
is_a: GO:0004540 ! RNA nuclease activity

But EC:3.1.11.- is a grouping class that correctly x-reffed to:
GO:0016895
name: DNA exonuclease activity, producing 5'-phosphomonoesters
xref: EC:3.1.11.-
So it shouldn't be an xref on GO:0008997

GO:0008997 has a single EXP annotation to E.coli rnr.
UP annotates this with EC:3.1.13.1 = GO:0008859 exoribonuclease II activity.
def: "Catalysis of the reaction: RNA + H2O = 5'-phosphomononucleotides. Cleaves RNA in the 3' to 5' direction." [EC:3.1.13.1, ISBN:0198547684]

So:
- [ ] Merge GO:0008997 into GO:0008859

**Comment by pgaudet** [comment]
@sjm41 

Is this a ribo or deoxyribonuclease? It should be a type of https://enzyme.expasy.org/EC/3.1.13.- ? 

We should review all nucleases as one small project.

**Comment by sjm41** [comment]
ribo.

That's why my first response was just to remove the current xref on GO:0008997 (which is both incorrect and partial!)
But I think merging GO:0008997 into GO:0008859 is better.
