### ISSUE TITLE
Merge 'keto acid formate lyase activity' & '2-ketobutyrate formate-lyase activity'

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28073]
The following two terms have the same MetaCyc xref and the same def so should be merged (with the partial EC xref removed):

id: GO:0043806 (25 annotations, no EXP)
name: keto acid formate lyase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2-oxobutanoate + CoA = propionyl-CoA + formate." [MetaCyc:KETOBUTFORMLY-RXN]
synonym: "keto-acid formate acetyltransferase" BROAD []
synonym: "keto-acid formate lyase activity" EXACT []
synonym: "keto-acid formate-lyase activity" EXACT []
xref: EC:2.3.1.-
xref: MetaCyc:KETOBUTFORMLY-RXN
is_a: GO:0016747 ! acyltransferase activity, transferring groups other than amino-acyl groups

id: GO:0043875 (2 annotations, 1 EXP)
name: 2-ketobutyrate formate-lyase activity
namespace: molecular_function
def: "Catalysis of the reaction: 2-oxobutanoate + coenzyme A = propionyl-CoA + formate." [PMID:9484901, RHEA:28054]
comment: This function is part of an anaerobic pathway for the catabolism of L-threonine.
synonym: "keto-acid formate acetyltransferase" BROAD []
synonym: "KFL" EXACT []
synonym: "TdcE" RELATED []
xref: MetaCyc:KETOBUTFORMLY-RXN
xref: RHEA:28054
is_a: GO:0016747 ! acyltransferase activity, transferring groups other than amino-acyl groups

**Comment by pgaudet** [comment]
Obsolete  GO:0043806 (25 annotations, no EXP)  keto acid formate lyase activity

Replace by GO:0043875  2-ketobutyrate formate-lyase activity

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0043806 keto acid formate lyase activity (no manual annotations) & replace by GO:0043875 2-ketobutyrate formate-lyase activity, since these two terms represent the same activity. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/28073

Thanks, Pascale
