### ISSUE TITLE
GO:0034938 pyrrole-2-carboxylate monooxygenase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28088]
id: GO:0034938
name: pyrrole-2-carboxylate monooxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: pryrole-2-carboxylate + NADH + O2 + H+ = 5-hydroxypyrrole-2-carboxylate + NAD+ + H2O." [UM-BBD_reactionID:r0968]
xref: EC:1.14.14.-
xref: UM-BBD_reactionID:r0968
is_a: GO:0016712 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen

This is RHEA:30351 = EC:1.14.13.130 (pyrrole-2-carboxylate monooxygenase):
H(+) + NADH + O2 + pyrrole-2-carboxylate = 5-hydroxypyrrole-2-carboxylate + H2O + NAD(+)

- [x] Update EC xref
- [x] Add RHEA xef
- [x] Use RHEA for def
- [x] Change parent to match EC, i.e. change to GO:0016709 oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

**Comment by pgaudet** [comment]
Hi @sjm41 
Next time if you fix a NAD-dependent term, would you please edit the label as we agreed? 

I updated to pyrrole-2-carboxylate monooxygenase (NADH) activity (from pyrrole-2-carboxylate monooxygenase activity)

Thanks, Pascale
