### ISSUE TITLE
Obsoletion of leaf catalytic activity terms with partial EC and no annotations

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28108]
The following are leaf catalytic activity terms matching the following criteria:
- they are leaf terms with a partial EC term xref
- used in zero GO annotations (excepting incorrect IEA annotations generated via the partial EC by ZFIN)
- with no RHEA term xref
- with no MetaCyc/KEGG xref (with 6 exceptions)

We propose they are obsoleted in bulk.  No need to send notifications for annotation review, since there are no annotations.

@balhoff - hope you can help with this? 

GO_ID | GO_term
-- | --
GO:0016900 | oxidoreductase activity, acting on the CH-OH group of donors, disulfide as acceptor
GO:0018466 | limonene-1,2-diol dehydrogenase activity
GO:0018542 | 2,3-dihydroxy DDT 1,2-dioxygenase activity
GO:0018555 | phenanthrene dioxygenase activity
GO:0018556 | 2,2',3-trihydroxybiphenyl dioxygenase activity
GO:0018557 | 1,2-dihydroxyfluorene 1,1-alpha-dioxygenase activity
GO:0018558 | 5,6-dihydroxy-3-methyl-2-oxo-1,2-dihydroquinoline dioxygenase activity
GO:0018559 | 1,1-dichloro-2-(dihydroxy-4-chlorophenyl)-(4-chlorophenyl)ethene 1,2-dioxygenase activity
GO:0018560 | protocatechuate 3,4-dioxygenase type II activity
GO:0018561 | 2'-aminobiphenyl-2,3-diol 1,2-dioxygenase activity
GO:0018562 | 3,4-dihydroxyfluorene 4,4-alpha-dioxygenase activity
GO:0018563 | 2,3-dihydroxy-ethylbenzene 1,2-dioxygenase activity
GO:0018565 | dihydroxydibenzothiophene dioxygenase activity
GO:0018566 | 1,2-dihydroxynaphthalene-6-sulfonate 1,8a-dioxygenase activity
GO:0018567 | styrene dioxygenase activity
GO:0018568 | 3,4-dihydroxyphenanthrene dioxygenase activity
GO:0018569 | hydroquinone 1,2-dioxygenase activity
GO:0018572 | 3,5-dichlorocatechol 1,2-dioxygenase activity
GO:0018573 | 2-aminophenol 1,6-dioxygenase activity
GO:0018574 | 2,6-dichloro-p-hydroquinone 1,2-dioxygenase activity
GO:0018575 | chlorocatechol 1,2-dioxygenase activity
GO:0034543 | 5-aminosalicylate dioxygenase activity
GO:0034803 | 3-hydroxy-2-naphthoate 2,3-dioxygenase activity
GO:0034806 | benzo(a)pyrene 11,12-dioxygenase activity
GO:0034808 | benzo(a)pyrene 4,5-dioxygenase activity
GO:0034810 | 4,5-dihydroxybenzo(a)pyrene dioxygenase activity
GO:0034812 | 9,10-dihydroxybenzo(a)pyrene dioxygenase activity
GO:0034814 | 7,8-dihydroxy benzo(a)pyrene dioxygenase activity
GO:0034827 | 1,2-dihydroxy-5,6,7,8-tetrahydronaphthalene extradiol dioxygenase activity
GO:0034834 | 2-mercaptobenzothiazole dioxygenase activity
GO:0034895 | pyridine-3,4-diol dioxygenase activity
GO:0034920 | pyrene dioxygenase activity
GO:0034922 | 4,5-dihydroxypyrene dioxygenase activity
GO:0034934 | phenanthrene-4-carboxylate dioxygenase activity
GO:0034935 | tetrachlorobenzene dioxygenase activity
GO:0034936 | 4,6-dichloro-3-methylcatechol 1,2-dioxygenase activity
GO:0034955 | 2,3-dihydroxydiphenyl ether dioxygenase activity
GO:0034956 | diphenyl ether 1,2-dioxygenase activity
GO:0034835 | 2-mercaptobenzothiazole monooxygenase activity
GO:0034836 | 6-hydroxy-2-mercaptobenzothiazole monooxygenase activity
GO:0034850 | isooctane monooxygenase activity
GO:0034898 | hexadecyltrimethylammonium chloride monooxygenase activity
GO:0018584 | 2,4,5-trichlorophenoxyacetic acid oxygenase activity
GO:0018603 | nitrobenzene 1,2-dioxygenase activity
GO:0018604 | 4-aminobenzoate 3,4-dioxygenase (deaminating) activity
GO:0018606 | benzenesulfonate dioxygenase activity
GO:0018607 | 1-indanone monooxygenase activity
GO:0018608 | 1-indanone dioxygenase activity
GO:0018609 | chlorobenzene dioxygenase activity
GO:0018611 | toluate dioxygenase activity
GO:0018612 | dibenzothiophene dioxygenase activity
GO:0018613 | 9-fluorenone dioxygenase activity
GO:0018614 | ethylbenzene dioxygenase activity
GO:0018615 | 2-indanone monooxygenase activity
GO:0018617 | 4-aminobenzenesulfonate 3,4-dioxygenase (deaminating) activity
GO:0034521 | 1-naphthoic acid dioxygenase activity
GO:0034825 | tetralin ring-hydroxylating dioxygenase activity
GO:0034906 | N-isopropylaniline 1,2-dixoxygenase activity
GO:0034907 | acetanilide 1,2-dioxygenase activity
GO:0034908 | 2-chloro-N-isopropylacetanilide 1,2-dioxygenase activity
GO:0034911 | phthalate 3,4-dioxygenase activity
GO:0034954 | diphenyl ether 2,3-dioxygenase activity
GO:0018471 | 4-chlorobenzaldehyde oxidase activity
GO:0018630 | 3,5-xylenol methylhydroxylase activity
GO:0018636 | phenanthrene 9,10-monooxygenase activity
GO:0018639 | xylene monooxygenase activity
GO:0018642 | chlorophenol 4-monooxygenase activity
GO:0018643 | carbon disulfide oxygenase activity
GO:0018646 | 1-hydroxy-2-oxolimonene 1,2-monooxygenase activity
GO:0018647 | phenanthrene 1,2-monooxygenase activity
GO:0018649 | tetrahydrofuran hydroxylase activity
GO:0018650 | styrene monooxygenase activity
GO:0018651 | toluene-4-sulfonate monooxygenase activity
GO:0018653 | 3-methyl-2-oxo-1,2-dihydroquinoline 6-monooxygenase activity
GO:0018654 | 2-hydroxy-phenylacetate hydroxylase activity
GO:0018655 | 2-oxo-delta3-4,5,5-trimethylcyclopentenylacetyl-CoA 1,2-monooxygenase activity
GO:0018656 | phenanthrene 3,4-monooxygenase activity
GO:0034526 | 2-methylnaphthalene hydroxylase activity
GO:0034534 | 1-methylnaphthalene hydroxylase activity
GO:0034560 | bisphenol A hydroxylase A activity
GO:0034791 | isobutylamine N-hydroxylase activity
GO:0034802 | branched-chain dodecylbenzene sulfonate monooxygenase activity
GO:0034819 | 3-HSA hydroxylase activity
GO:0034894 | 4-hydroxypyridine-3-hydroxylase activity
GO:0018680 | deethylatrazine monooxygenase activity
GO:0018681 | deisopropylatrazine monooxygenase activity
GO:0018682 | atrazine N-dealkylase activity
GO:0034577 | N-isopropylacetaniline monooxygenase activity
GO:0034795 | cyclohexane monooxygenase activity
GO:0034818 | ADD 9alpha-hydroxylase activity
GO:0034855 | 4-AD 9alpha-hydroxylase activity
GO:0043783 | oxidoreductase activity, acting on metal ions, flavin as acceptor
GO:0034569 | monodemethylisoproturon dehydrogenase activity
GO:0034574 | didemethylisoproturon dehydrogenase activity
GO:0034575 | 4-isopropylaniline dehydrogenase activity
GO:0034520 | 2-naphthaldehyde dehydrogenase activity
GO:0034530 | 4-hydroxymethylsalicyaldehyde dehydrogenase activity
GO:0050522 | oxidoreductase activity, acting on phosphorus or arsenic in donors, with other known acceptors
GO:0034580 | 4-methyloctanoyl-CoA dehydrogenase activity
GO:0034845 | naphthyl-2-methyl-succinyl-CoA dehydrogenase activity
GO:0034916 | 2-methylhexanoyl-CoA dehydrogenase activity
GO:0043830 | thiol-driven fumarate reductase activity
GO:0052758 | coenzyme F420-dependent 2,4,6-trinitrophenol reductase activity
GO:0052759 | coenzyme F420-dependent 2,4,6-trinitrophenol hydride reductase activity
GO:0052760 | coenzyme F420-dependent 2,4-dinitrophenol reductase activity
GO:0043912 | D-lysine oxidase activity
GO:0052585 | oxidoreductase activity, acting on the CH-NH2 group of donors, with a quinone or similar compound as acceptor
GO:0018532 | 5,10-methenyl-5,6,7,8-tetrahydromethanopterin dehydrogenase activity
GO:0018534 | nitrilotriacetate dehydrogenase activity
GO:0034568 | isoproturon dimethylaminedehydrogenase activity
GO:0034570 | hydroxymonomethylisoproturon dimethylaminedehydrogenase activity
GO:0034572 | monodemethylisoproturon dimethylaminedehydrogenase activity
GO:0052586 | oxidoreductase activity, acting on other nitrogenous compounds as donors, with a quinone or similar compound as acceptor
GO:0034800 | trinitrophenol dihydride denitratase activity
GO:0034914 | trinitrophenol hydride denitratase activity
GO:0018699 | 1,1,1-trichloroethane reductive dehalogenase activity
GO:0018700 | 2-chloro-N-isopropylacetanilide reductive dehalogenase activity
GO:0018701 | 2,5-dichlorohydroquinone reductive dehalogenase activity
GO:0018702 | 1,1-dichloro-2,2-bis(4-chlorophenyl)ethene dehalogenase activity
GO:0034539 | 3,3',5,5'-tetrabromobisphenol A reductive dehalogenase activity
GO:0034540 | 3-monobromobisphenol A reductive dehalogenase activity
GO:0034542 | trimethylarsine oxidase activity
GO:0034546 | 2,4-dichloroaniline reductive dehalogenase activity
GO:0034550 | dimethylarsinate reductase activity
GO:0034554 | 3,3',5-tribromobisphenol A reductive dehalogenase activity
GO:0034555 | 3,3'-dibromobisphenol A reductive dehalogenase activity
GO:0034937 | perchlorate reductase activity
GO:0034949 | 1,1-dichloroethane reductive dehalogenase activity
GO:0044685 | tetrahydromethanopterin-dependent serine hydroxymethyltransferase activity
GO:0034915 | 2-methylhexanoyl-CoA C-acetyltransferase activity
GO:0034945 | 2,6-dimethyl-5-methylene-3-oxo-heptanoyl-CoA C-acetyltransferase activity
GO:0036357 | 2-phosphoglycerate kinase activity
GO:0043749 | phenol, water dikinase activity
GO:0016897 | RNA exonuclease activity, producing 3'-phosphomonoesters
GO:0034861 | benzothiazole-2-sulfonate hydrolase activity
GO:0052790 | chitooligosaccharide deacetylase activity
GO:0034544 | trans-ACOHDA hydrolase activity
GO:0034565 | 1-nitro-1,2-dihydro-1,3,5-triazine hydrolase activity
GO:0034886 | gamma-aminovinylacetate deaminase activity
GO:0034896 | 3-formiminopyruvate hydrolase activity
GO:0034900 | 3-(N-formyl)-formiminopyruvate hydrolase activity
GO:0034958 | aminohydroquinone monooxygenase activity
GO:0034948 | 2,6-dihydroxypseudooxynicotine hydrolase activity
GO:0043728 | 2-keto-4-methylthiobutyrate aminotransferase activity
GO:0034815 | cis-4-(8-hydroxypyren-7-yl)-2-oxobut-3-enoate lyase activity
GO:0034830 | (2Z)-2,4-dihydroxydec-2-enedioate aldolase activity
GO:0034905 | 5-chloro-4-hydroxy-2-oxopentanate aldolase activity
GO:0034860 | 2-mercaptobenzothiazole desulfurase activity
GO:0018827 | 1-chloro-2,2-bis(4-chlorophenyl)ethane dehydrochlorinase activity
GO:0018829 | 1,1-dichloro-2,2-bis(4-chlorophenyl)ethane dehydrochlorinase activity
GO:0018830 | gamma-hexachlorocyclohexane dehydrochlorinase activity
GO:0018831 | 5-chloro-1,2,4-trihydroxybenzene dechlorinase activity
GO:0018839 | cis-4-[2-(3-hydroxy)-thionaphthenyl]-2-oxo-3-butenoate isomerase activity
GO:0034872 | trans-geranyl-CoA isomerase activity
GO:0018844 | 2-hydroxytetrahydrofuran isomerase activity
GO:0034528 | 2-carboxy-2-hydroxy-8-carboxychromene isomerase activity
GO:0034532 | 2-hydroxy-7-hydroxymethylchromene-2-carboxylate isomerase activity
GO:0034536 | 2-hydroxy-8-methylchromene-2-carboxylate isomerase activity
GO:0034951 | o-hydroxylaminobenzoate mutase activity
GO:0018848 | pinocarveol isomerase activity
GO:0034794 | cyclopropanecarboxyl-CoA decyclase activity
GO:0052685 | perillic acid-CoA ligase (ADP-forming) activity
GO:0018524 | acetophenone carboxylase activity

**Comment by balhoff** [comment]
@sjm41 yes I'll take care of it.

**Comment by pgaudet** [comment]
@balhoff 
Can you please add the obsoletion reason: "This term was obsoleted because there is no evidence that this specific activity exists."

**Comment by sjm41** [comment]
Thanks Jim!
