### ISSUE TITLE
Obsoletion: benzo(a)pyrene 9,10-dioxygenase activity & benzo(a)pyrene 7,8-dioxygenase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28102]
id: GO:0034811
name: benzo(a)pyrene 9,10-dioxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: benzo(a)pyrene + O2 = benzo(a)pyrene-cis-9,10-dihydrodiol." [UM-BBD_reactionID:r1132]
xref: EC:1.13.11.-
xref: UM-BBD_reactionID:r1132
is_a: GO:0016702 ! oxidoreductase activity, acting on single donors with incorporation of molecular oxygen, incorporation of two atoms of oxygen

id: GO:0034813
name: benzo(a)pyrene 7,8-dioxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: benzo(a)pyrene + O2 = benzo(a)pyrene-cis-7,8-dihydrodiol." [UM-BBD_reactionID:1137]
xref: EC:1.13.11.-
xref: UM-BBD_reactionID:r1137
is_a: GO:0016702 ! oxidoreductase activity, acting on single donors with incorporation of molecular oxygen, incorporation of two atoms of oxygen

These two terms have each been used twice to annotate zebrafish cytochrome P450 proteins:
- Zebrafish cyp1c1 and cyp1c2 from PMID:26231923
The terms represent substrate-specific activities of those broad-specificity enzymes, so are outside of GO scope and should be obsoleted.

(question for @pgaudet - did we decide the policy is to remove term xrefs from obsolete terms?)

**Comment by pgaudet** [comment]
> (question for @pgaudet - did we decide the policy is to remove term xrefs from obsolete terms?)

yes

**Comment by pgaudet** [comment]
Annotations can be replaced by GO:0070330 aromatase activity
