### ISSUE TITLE
biotin-protein ligase activity terms - merge

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28107]
Below is the current hierarchy for 'biotin-protein ligase activity' and children, together with current xrefs):
```
 biotin-protein ligase activity (EC:6.3.4.-, MetaCyc:BIOTINLIG-RXN)
    |__biotin-[acetyl-CoA-carboxylase] ligase activity (EC:6.3.4.15, MetaCyc:BIOTINLIG-RXN, RHEA:11756)
    |__biotin-[methylcrotonoyl-CoA-carboxylase] ligase activity (EC:6.3.4.11, MetaCyc:6.3.4.11-RXN, RHEA:24376)
    |__biotin-[methylmalonyl-CoA-carboxytransferase] ligase activity (EC:6.3.4.9, MetaCyc:6.3.4.9-RXN, RHEA:23668)
    |__biotin-[propionyl-CoA-carboxylase (ATP-hydrolyzing)] ligase activity (EC:6.3.4.10, MetaCyc:6.3.4.10-RXN, RHEA:11204)
    |__biotin-[pyruvate-carboxylase] ligase activity (EC:6.3.4.-)
```

Issues here:
- EC:6.3.4.- is a grouping class for 'Other carbon--nitrogen ligases' so shouldn't be an xref on either of two terms above
- MetaCyc:BIOTINLIG-RXN is given as an xref to both the parent and a child term.
- "biotin-[pyruvate-carboxylase] ligase activity" has no specific EC/RHEA/MetaCyc xref
- The name and def of "biotin-[acetyl-CoA-carboxylase] ligase activity" (GO:0004077) don't match those of its EC:6.3.4.15/RHEA:11756 xrefs: EC name is now "biotin--[biotin carboxyl-carrier protein] ligase" and def is "ATP + biotin + L-lysyl-[protein] <=> AMP + diphosphate + H(+) + N(6)-biotinyl-L-lysyl-[protein]"

PMID: 37997490 is a 2023 review about biotin ligases. It's intro says:
_The discovery of biotin protein ligase (BPL) by Lane and colleagues[4]-[7] followed the realization that protein-bound biotin was involved in mammalian carboxylation reactions...In early work, these enzymes were sometimes named after the enzyme-substrate used to assay BPL activity (e.g., holopyruvate carboxylase synthetase) in the belief that each biotin-dependent enzyme was modified by a specific ligase. However, genetic studies in microorganisms and humans indicate each organism generally encodes a single BPL that modifies each of the biotin-requiring enzymes._

Consistent with that view, direct EXP annotations to these GO terms are all very similar:
biotin-protein ligase activity: **yeast BPL1, fly Hcs, human HLCS, mouse Hlcs, bacterial birA**
biotin-[acetyl-CoA-carboxylase] ligase activity: **yeast BPL1, bacterial birA, Arabidopsis HCS1**
biotin-[methylcrotonoyl-CoA-carboxylase] ligase activity: **Arabidopsis HCS1**
biotin-[methylmalonyl-CoA-carboxytransferase] ligase activity: **[no annotations]**
biotin-[propionyl-CoA-carboxylase (ATP-hydrolyzing)] ligase activity: **human HLCS, rat Hlcs**
biotin-[pyruvate-carboxylase] ligase activity: **yeast BPL1**

And EC annotations to Swiss-Prot entries are also very similar:
EC:6.3.4.15: mammalian HLCS, yeast BPL1, Arabidopsis HCS1, bacterial birA
EC:6.3.4.11: mammalian HLCS, yeast BPL1, Arabidopsis HCS1
EC:6.3.4.9: mammalian HLCS, yeast BPL1
EC:6.3.4.10: mammalian HLCS, yeast BPL1

And the counts of UniProt annotations to the corresponding RHEA IDs are:
RHEA:11756: 18,325 proteins
RHEA:24376: 5 proteins
RHEA:23668: 4 proteins
RHEA:11204: 4 proteins

So, taking all this together, I think all the terms mentioned above need merging into a single term based on GO:0004077/EC:6.3.4.15/RHEA:11756, that would look like this:

name: biotin--[biotin carboxyl-carrier protein] ligase activity
def: "Catalysis of the reaction: ATP + biotin + L-lysyl-[protein] = AMP + diphosphate + H+ + N(6)-biotinyl-L-lysyl-[protein]." [RHEA:11756]
synonym: "biotin-apoprotein ligase activity" EXACT [] **etc**
xref: EC:6.3.4.15 [exactMatch]
xref: MetaCyc:BIOTINLIG-RXN [exactMatch]
xref: RHEA:11756 [exactMatch]
xref: EC:6.3.4.9 [narrowMatch]
xref: MetaCyc:6.3.4.9-RXN [narrowMatch]
xref: RHEA:23668 [narrowMatch]
xref: EC:6.3.4.10 [narrowMatch]
xref: MetaCyc:6.3.4.10-RXN [narrowMatch]
xref: RHEA:11204 [narrowMatch]
xref: EC:6.3.4.11 [narrowMatch]
xref: MetaCyc:6.3.4.11-RXN [narrowMatch]
xref: RHEA:24376 [narrowMatch]
is_a: GO:0016879 ! ligase activity, forming carbon-nitrogen bonds
is_a: GO:0140096 ! catalytic activity, acting on a protein

**Comment by raymond91125** [comment]
Should they be merges at EC and connected at RHEA? @kaxelsen Thanks.

**Comment by pgaudet** [comment]
Usually RHEA keeps the specific substrates, but GO doesn't. 
We can go ahead with the obsoletions.
