### ISSUE TITLE
3 Terms with xref: EC:3.2.1.20

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28110]
The three parent-child-grandhild terms below all have xref: EC:3.2.1.20.

That EC is for "Hydrolysis of terminal, non-reducing (1->4)-linked alpha-D-glucose residues with release of alpha-D-glucose", so should really only be an xref on GO:0004558 (as noted previously on #17840).

GO:0032450 is defined by MetaCyc:RXN-2141, but that ID is obsolete at MetaCyc. The xref on that term is a different ID (MetaCyc:RXN-15910) and that entry says "Note that this reaction equation differs from the official Enzyme Commission reaction equation for this EC entry" which is MALTODEXGLUCOSID-RXN = EC:3.2.1.20.

So the two action items here are:
- [ ] remove EC:3.2.1.20 from GO:0090599 alpha-glucosidase activity
- [ ] merge GO:0032450 maltose alpha-glucosidase activity into GO:0004558 alpha-1,4-glucosidase activity

id: GO:0090599
name: alpha-glucosidase activity
namespace: molecular_function
def: "Catalysis of the hydrolysis of terminal, non-reducing alpha-linked alpha-D-glucose residue with release of alpha-D-glucose." [GOC:tb]
xref: EC:3.2.1.20
is_a: GO:0015926 ! glucosidase activity
created_by: tb
creation_date: 2014-08-22T14:33:31Z

id: GO:0004558
name: alpha-1,4-glucosidase activity
namespace: molecular_function
alt_id: GO:0004562
alt_id: GO:0016982
def: "Catalysis of the hydrolysis of terminal, non-reducing alpha-(1->4)-linked alpha-D-glucose residues with release of alpha-D-glucose." [EC:3.2.1.20]
synonym: "acid maltase activity" RELATED [EC:3.2.1.20]
synonym: "alpha-D-glucosidase activity" RELATED [EC:3.2.1.20]
synonym: "alpha-D-glucoside glucohydrolase activity" RELATED [EC:3.2.1.20]
synonym: "alpha-glucopyranosidase activity" RELATED [EC:3.2.1.20]
synonym: "alpha-glucosidase II" RELATED []
synonym: "alpha-glucoside hydrolase activity" RELATED [EC:3.2.1.20]
synonym: "glucoinvertase activity" RELATED [EC:3.2.1.20]
synonym: "glucosidoinvertase activity" RELATED [EC:3.2.1.20]
synonym: "glucosidosucrase activity" RELATED [EC:3.2.1.20]
synonym: "lysosomal alpha-glucosidase activity" BROAD [EC:3.2.1.20]
synonym: "maltase-glucoamylase activity" RELATED [EC:3.2.1.20]
xref: EC:3.2.1.20
xref: MetaCyc:MALTODEXGLUCOSID-RXN
is_a: GO:0090599 ! alpha-glucosidase activity

id: GO:0032450
name: maltose alpha-glucosidase activity
namespace: molecular_function
def: "Catalysis of the reaction: alpha-maltose + H2O = 2 alpha-D-glucose." [MetaCyc:RXN-2141]
synonym: "maltase activity" EXACT []
xref: EC:3.2.1.20
xref: MetaCyc:RXN-15910
is_a: GO:0004558 ! alpha-1,4-glucosidase activity
relationship: part_of GO:0000023 ! maltose metabolic process

**Comment by pgaudet** [comment]
Also: obsolete & replace: 

- GO:0044653  dextrin alpha-glucosidase activity: single pombase EXP, non-specific for dextrin (see PMID:18556189) >> replace by GO:0004558 alpha-1,4-glucosidase activity
- GO:0044654 starch alpha-glucosidase activity: 2 pombase EXP, non-specific for dextrin (see PMID:18556189) >> replace by GO:0004558 alpha-1,4-glucosidase activity

**Comment by pgaudet** [comment]
Annotation review: https://github.com/geneontology/go-annotation/issues/5278

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete

GO:0032450 maltose alpha-glucosidase activity 
GO:0044654 starch alpha-glucosidase activity
GO:0044653 dextrin alpha-glucosidase activity

with replace by GO:0004558 alpha-1,4-glucosidase activity

There are 11 annotations to these terms, see https://github.com/geneontology/go-annotation/issues/5278
1 CACAO
1 CGD
6 PomBase
3 SGD

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/28110

Thanks, Pascale

**Comment by pgaudet** [comment]
Obsolete [alpha-1,3-glucosidase activity](http://purl.obolibrary.org/obo/GO_0090600) >> unnecessary grouping class, no EC, no RHEA. All annotations are to the single child, [glucan 1,3-alpha-glucosidase activity](http://purl.obolibrary.org/obo/GO_0033919).

**Comment by pgaudet** [comment]
Done in https://github.com/geneontology/go-ontology/pull/28299/commits/02d1722400a41050715fee977d10bdfa0030a9d5
