### ISSUE TITLE
Merge: inositol diphosphate pentakisphosphate diphosphatase activity & inositol-5-diphosphate-1,2,3,4,6-pentakisphosphate diphosphatase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28135]
These two terms are the same - same def, same KEGG xref, same papers in def.
GO:0052842 should be merged into GO:0052845

id: GO:0052842
name: inositol diphosphate pentakisphosphate diphosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: diphospho-1D-myo-inositol pentakisphosphate + H2O = 1D-myo-inositol hexakisphosphate + phosphate." [PMID:10827188, PMID:11502751]
xref: KEGG_REACTION:R05779
is_a: GO:0008486 ! diphosphoinositol-polyphosphate diphosphatase activity

id: GO:0052845
name: inositol-5-diphosphate-1,2,3,4,6-pentakisphosphate diphosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: 5-diphospho-1D-myo-inositol 1,2,3,4,6-pentakisphosphate + H2O = 1D-myo-inositol 1,2,3,4,5,6-hexakisphosphate + phosphate + H+." [PMID:10827188, PMID:11502751, RHEA:22384]
xref: KEGG_REACTION:R05779
xref: MetaCyc:RXN-10964
xref: RHEA:22384
is_a: GO:0052842 ! inositol diphosphate pentakisphosphate diphosphatase activity

**Comment by pgaudet** [comment]
Hi @sjm41  GO:0052842 inositol diphosphate pentakisphosphate diphosphatase activity is the grouping class for 3 other terms: 


<img width="640" alt="image" src="https://github.com/user-attachments/assets/fa446502-3ee7-4da8-ac8e-992d070846dd">

I think we should remove KEGG_REACTION:R05779 from the parent GO:0052842 but keep the grouping term.

**Comment by sjm41** [comment]
@pgaudet Ah yes, you're right. Thanks for fixing.
