### ISSUE TITLE
GO:0043878 glyceraldehyde-3-phosphate dehydrogenase (NAD+) (non-phosphorylating) activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28144]
id: GO:0043878
name: glyceraldehyde-3-phosphate dehydrogenase (NAD+) (non-phosphorylating) activity
namespace: molecular_function
def: "Catalysis of the reaction: D-glyceraldehyde 3-phosphate + NAD+ + H2O = 3-phospho-D-glycerate + NADH + H+." [PMID:9497334]
synonym: "glyceraldehyde-3-phosphate dehydrogenase (NAD) (non-phosphorylating) activity" EXACT []
synonym: "glyceraldehyde-3-phosphate dehydrogenase (NAD) activity" EXACT []
synonym: "NAD+-dependent glyceraldehyde-3-phosphate dehydrogenase activity" EXACT []
synonym: "non-phosphorylating glyceraldehyde-3-phosphate dehydrogenase (NAD)" EXACT []
xref: EC:1.2.1.3
xref: MetaCyc:RXN-3443
xref: RHEA:25294
is_a: GO:0016620 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor

This term has the wrong EC/RHEA xref, though the MetaCyc xref looks OK:
- EC:1.2.1.3 is: 'aldehyde dehydrogenase (NAD(+))' and is correctly an xref on GO:0004029 aldehyde dehydrogenase (NAD+) activity.
- RHEA:25294 is: 'acetaldehyde + H2O + NAD(+) = acetate + 2 H(+) + NADH'
- MetaCyc:RXN-3443 is: D-glyceraldehyde 3-phosphate + NAD+ + H2O → 3-phospho-D-glycerate + NADH + 2 H+
which seems OK.

The correct RHEA appears to be RHEA:42760 (not in the GO):
D-glyceraldehyde 3-phosphate + H2O + NAD(+) = (2R)-3-phosphoglycerate + 2 H(+) + NADH

RHEA:42760 maps that to **EC:1.2.1.90** (not in the GO), which is:
glyceraldehyde-3-phosphate dehydrogenase [NAD(P)(+)]
D-glyceraldehyde 3-phosphate + H2O + NADP(+) <=> (2R)-3-phosphoglycerate + 2 H(+) + NADPH
D-glyceraldehyde 3-phosphate + H2O + NAD(+) <=> (2R)-3-phosphoglycerate + 2 H(+) + NADH

And RHEA:42760 is also mapped to these MetaCyc IDs:
RXN-15754: D-glyceraldehyde 3-phosphate + NAD(P)+ + H2O → 3-phospho-D-glycerate + NAD(P)H + 2 H+
RXN-3443: D-glyceraldehyde 3-phosphate + NAD+ + H2O → 3-phospho-D-glycerate + NADH + 2 H+

So:
- [x] Remove RHEA:25294 from GO:0043878 and add RHEA:42760
- [x] Put RHEA:25294 as a narrowMatch xref on GO:0004029 aldehyde dehydrogenase (NAD+) activity
- [x] Remove EC:1.2.1.3 from GO:0043878
- [x] Either i) add EC:1.2.1.90 as broadMatch xref to GO:0043878 (and also GO:0008886), or ii) create new grouping term for GO:004387 and GO:0008886 that is an exactMatch for EC:1.2.1.90.  (Doing that would match how the sister 'phosphorylating' branch is currently handled - see below)

@pgaudet What do you think about the last point?

```
oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor
       |__glyceraldehyde-3-phosphate dehydrogenase (NAD(P)+) (phosphorylating) activity (GO:0043891) xref: EC:1.2.1.59
           |__glyceraldehyde-3-phosphate dehydrogenase (NAD+) (phosphorylating) activity (GO:0004365) xref: EC:1.2.1.12
           |__glyceraldehyde-3-phosphate dehydrogenase (NADP+) (phosphorylating) activity (GO:0047100) xref: EC:1.2.1.13
       |__glyceraldehyde-3-phosphate dehydrogenase (NAD+) (non-phosphorylating) activity (GO:0043878) no EC xref
       |__glyceraldehyde-3-phosphate dehydrogenase (NADP+) (non-phosphorylating) activity (GO:0008886) xref: EC:1.2.1.9
```

**Comment by pgaudet** [comment]
@sjm41 Let's look at this one together

**Comment by sjm41** [comment]
Hi @pgaudet

Looking at this again, I think I should create a new grouping term for GO:004387 and GO:0008886 that is an exactMatch for EC:1.2.1.90. (Doing that would match how the sister 'phosphorylating' branch is currently handled)

So the change would be from this:
```
oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor
       |__glyceraldehyde-3-phosphate dehydrogenase (NAD+) (non-phosphorylating) activity (GO:0043878) no EC xref
       |__glyceraldehyde-3-phosphate dehydrogenase (NADP+) (non-phosphorylating) activity (GO:0008886) xref: EC:1.2.1.9
```

to this:
```
oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor
       |__glyceraldehyde-3-phosphate dehydrogenase (NAD(P)+) (non-phosphorylating) activity (NTR) xref: EC:1.2.1.90
               |__glyceraldehyde-3-phosphate dehydrogenase (NAD+) (non-phosphorylating) activity (GO:0043878) no EC xref
               |__glyceraldehyde-3-phosphate dehydrogenase (NADP+) (non-phosphorylating) activity (GO:0008886) xref: EC:1.2.1.9
```

OK?

**Comment by sjm41** [comment]
+[Term]
+id: GO:0120533
+name: glyceraldehyde-3-phosphate dehydrogenase [NAD(P)+] (non-phosphorylating) activity
+def: "Catalysis of the reaction: D-glyceraldehyde 3-phosphate + NAD(P)+ + H2O = (2R)-3-phosphoglycerate + NAD(P)H + 2 H+." [EC:1.2.1.90]
+synonym: "GAPN activity" BROAD [EC:1.2.1.90]
+synonym: "non-phosphorylating glyceraldehyde-3-phosphate dehydrogenase activity" BROAD [EC:1.2.1.90]
+xref: EC:1.2.1.90 {source="skos:exactMatch"}
+is_a: GO:0016620 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors, NAD or NADP as acceptor
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28144" xsd:anyURI
+created_by: sjm
+creation_date: 2024-11-28T16:08:56Z

**Comment by sjm41** [comment]
I've gone ahead with my proposal above and closed this. We can re-open/revert the change if I got this wrong.
