### ISSUE TITLE
New check to detect terms with same MetaCyc/KEGG xrefs

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28146]
Hi Jim

Could you set up a check to initially flag, and subsequently prevent, GO terms having identical MetaCyc or KEGG term xrefs?
This check would be equivalent to the one you've made for duplicate EC xrefs alluded to here: https://github.com/geneontology/go-ontology/pull/26235

Currently, there are not many KEGG xref duplicates - see #28133 for list, which are either already fixed or in the process of being fixed.

Currently, there are ~117 MetaCyc xref duplicates (https://docs.google.com/spreadsheets/d/1NihWOJ3pfG05Jon0KUrIj4xK_uj3uHs42--WaMA1RxM/edit?gid=0#gid=0).
I'll be working through these in the coming week.

@pgaudet

**Comment by sjm41** [comment]
I also found a case where the same MetaCyc ID appeared twice on a single GO term, both as a narrowMatch xref and an un-typed ref. I would be good if the new check also flagged these types of case.

id: GO:0016805
name: dipeptidase activity
namespace: molecular_function
alt_id: GO:0102008
def: "Catalysis of the hydrolysis of a dipeptide." [https://www.ebi.ac.uk/merops/about/glossary.shtml#DIPEPTIDASE, PMID:19879002]
synonym: "cytosolic dipeptidase activity" NARROW []
xref: EC:3.4.13.-
xref: EC:3.4.13.18 {source="skos:narrowMatch"}
xref: EC:3.4.13.21 {source="skos:narrowMatch"}
**xref: MetaCyc:3.4.13.18-RXN {source="skos:narrowMatch"}
xref: MetaCyc:3.4.13.18-RXN**
xref: MetaCyc:3.4.13.21-RXN {source="skos:narrowMatch"}
is_a: GO:0008238 ! exopeptidase activity

**Comment by sjm41** [comment]
These are the remaining cases causing the pull request to fail:

MetaCyc:BUTYRATE--COA-LIGASE-RXN,MetaCyc:,http://purl.obolibrary.org/obo/GO_0120515;http://purl.obolibrary.org/obo/GO_0031956
MetaCyc:NPGLUCAT-PWY,MetaCyc:,http://purl.obolibrary.org/obo/GO_0019595;http://purl.obolibrary.org/obo/GO_0061680
MetaCyc:RXN-9385,MetaCyc:,http://purl.obolibrary.org/obo/GO_0052754;http://purl.obolibrary.org/obo/GO_0043910
MetaCyc:RXN-8307,MetaCyc:,http://purl.obolibrary.org/obo/GO_0102654;http://purl.obolibrary.org/obo/GO_0102843
MetaCyc:RXN-10884,MetaCyc:,http://purl.obolibrary.org/obo/GO_0052625;http://purl.obolibrary.org/obo/GO_0102085
MetaCyc:RXN-10885,MetaCyc:,http://purl.obolibrary.org/obo/GO_0052627;http://purl.obolibrary.org/obo/GO_0102086
MetaCyc:RXN-10886,MetaCyc:,http://purl.obolibrary.org/obo/GO_0052626;http://purl.obolibrary.org/obo/GO_0102087
MetaCyc:RXN-10887,MetaCyc:,http://purl.obolibrary.org/obo/GO_0052628;http://purl.obolibrary.org/obo/GO_0102088

**Comment by balhoff** [comment]
@sjm41 sorry! This is another example of the confusing automatic move of xrefs from obsolete terms to their replacements (planning to fix that soon). It's on GO:0047760.

**Comment by sjm41** [comment]
OK, I've fixed 4 of the remaining cases. The other 4 will be fixed by the proposed merges in https://github.com/geneontology/go-ontology/issues/28503

**Comment by sjm41** [comment]
@balhoff I believe your associated PR should now complete.

BUT BEFORE YOU DO THAT (!), I am wondering if this check for the same MetaCyc/KEGG database xref could be extended to also check for any terms that share the same MetaCyc/KEGG **definition** xref? Is that possible? If so, would it work best to bundle it with this current check?
I'm not sure whether this will throw up any additional cases, but if it does, then they should be examined and fixed.

**Comment by balhoff** [comment]
@sjm41 the current check does not compare definition xrefs. It would complicate the query to do both in one check, so I think we should make an issue to implement a one-to-one check for definition xrefs and tackle that after going ahead and merging this check. How does that sound?

**Comment by sjm41** [comment]
Sounds good, thanks!

**Comment by balhoff** [comment]
@sjm41 one direction of the check passes now ("one-to-one-xrefs-by-value") but the other direction ("one-to-one-xrefs-by-subject") still has many violations. I put both of these in the same PR. Should I split it up and get the first check merged?

**Comment by sjm41** [comment]
Yes please, splitting them into two sounds like an excellent idea!
I make myself a ticket or two to look at the other violations...

**Comment by sjm41** [comment]
@balhoff 
I have fixed all 96 cases where a MF term had multiple exactMatch MetaCyc xrefs (https://github.com/geneontology/go-ontology/issues/28526).
I also removed the 1 case where a CC term had multiple exactMatch MetaCyc xrefs (https://github.com/geneontology/go-ontology/issues/28527).
But I don't think I can easily "fix" the 47 BP terms with multiple exactMatch MetaCyc xrefs - these refer to pathway variants and it looks correct to me that we should allow multiple exactMatch xrefs in these cases  (https://github.com/geneontology/go-ontology/issues/28527).
So, I'm wondering if it is possible to disallow "one-to-one-xrefs-by-subject" for MetaCyc xrefs on MF and CC terms, but allow this for BP?
Regardless, we should wait for @pgaudet's take on this when she's back.

**Comment by balhoff** [comment]
@sjm41 my assumption is that the xref would be "narrow" in those cases, but waiting for Pascale sounds good to me.

**Comment by sjm41** [comment]
> But I don't think I can easily "fix" the 47 BP terms with multiple exactMatch MetaCyc xrefs - these refer to pathway variants and it looks correct to me that we should allow multiple exactMatch xrefs in these cases (https://github.com/geneontology/go-ontology/issues/28527).

@balhoff I believe I've now fixed all these cases (making them narrowMatch), so hopefully this check will now run successfully.
Of course, I might have missed something, so let me know if something still needs fixing!

**Comment by balhoff** [comment]
@sjm41 only 3 left!

- http://purl.obolibrary.org/obo/GO_0003962 (MetaCyc)
- http://purl.obolibrary.org/obo/GO_0000031 (MetaCyc)
- http://purl.obolibrary.org/obo/GO_0033840 (MetaCyc)

**Comment by sjm41** [comment]
Nearly there! I'll deal with those other 3 asap.

**Comment by sjm41** [comment]
OK, done, please try again @balhoff !
