### ISSUE TITLE
4 terms with xref: EC:1.2.3.9

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28141]
EC:1.2.3.9 is:
name: aryl-aldehyde oxidase
reaction: an aromatic aldehyde + H2O + O2 <=> an aromatic carboxylate + H(+) + H2O2
comments: Acts on benzaldehyde, vanillin and a number of other aromatic aldehydes, but not on aliphatic aldehydes or sugars.

It's an xref on this term:
id: GO:0018488
name: aryl-aldehyde oxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: an aromatic aldehyde + O2 + H2O = an aromatic acid + hydrogen peroxide." [EC:1.2.3.9]
synonym: "aryl-aldehyde:oxygen oxidoreductase activity" RELATED [EC:1.2.3.9]
xref: EC:1.2.3.9
xref: MetaCyc:ARYL-ALDEHYDE-OXIDASE-RXN
xref: RHEA:18569
xref: UM-BBD_reactionID:r0145
is_a: GO:0004031 ! aldehyde oxidase activity

As well as an xref on these 3 substrate-specific terms:

id: GO:0102794 (5 annotations, no EXP)
name: cinnamaldehyde:oxygen oxidoreductase activity
namespace: molecular_function
def: "Catalysis of the reaction: cinnamaldehyde + O2 + H2O = H+ + trans-cinnamate + hydrogen peroxide." [EC:1.2.3.9, GOC:pz]
xref: EC:1.2.3.9
xref: MetaCyc:RXN-8089
is_a: GO:0016623 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors, oxygen as acceptor

id: GO:0102795 (same 5 annotations, no EXP)
name: 1-naphthaldehyde:oxygen oxidoreductase activity
namespace: molecular_function
def: "Catalysis of the reaction: 1-naphthaldehyde + O2 + H2O = H+ + 1-naphthoate + hydrogen peroxide." [EC:1.2.3.9, GOC:pz]
xref: EC:1.2.3.9
xref: MetaCyc:RXN-8090
is_a: GO:0016623 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors, oxygen as acceptor

id: GO:0102796 (same 5 annotations, no EXP)
name: protocatechualdehyde:oxygen oxidoreductase activity
namespace: molecular_function
def: "Catalysis of the reaction: 3,4-dihydroxybenzaldehyde + O2 + H2O = H+ + 3,4-dihydroxybenzoate + hydrogen peroxide." [EC:1.2.3.9, GOC:pz]
xref: EC:1.2.3.9
xref: MetaCyc:RXN-8091
is_a: GO:0016623 ! oxidoreductase activity, acting on the aldehyde or oxo group of donors, oxygen as acceptor

And RHEA:18569 says there are additional potential substrate-specific children:
RHEA:59008 H2O + O2 + salicylaldehyde = H+ + H2O2 + salicylate
RHEA:58996 H2O + indole-3-carbaldehyde + O2 = H+ + H2O2 + indole-3-carboxylate
RHEA:58972 H2O + O2 + vanillin = H+ + H2O2 + vanillate
RHEA:58960 benzaldehyde + H2O + O2 = benzoate + H+ + H2O2
RHEA:23724 H2O + O2 + pyridoxal = 4-pyridoxate + H+ + H2O2

- [ ] merge GO:0102794 GO:0102795 GO:0102796 into GO:0018488

**Comment by pgaudet** [comment]
Fixed in https://github.com/geneontology/go-ontology/issues/28070
