### ISSUE TITLE
3 terms with xref to MetaCyc:BETA-LACTAMASE-RXN

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28157]
The 3 terms below all map to MetaCyc:BETA-LACTAMASE-RXN, which is EC:3.5.2.6/RHEA:20401.

MetaCyc:BETA-LACTAMASE-RXN is:
a β-lactam[periplasm] + H2O[periplasm] → a substituted β-amino acid[periplasm] + H+[periplasm]

GO:0033250 and GO:0033251 are for specific substrates, so should be merged into GO:0008800.

E.g. The comment on EC:3.5.2.6 says "A group of enzymes of varying specificity hydrolyzing beta-lactams; some act more rapidly on penicillins, some more rapidly on cephalosporins."

GO:0033250 and GO:0033251 have only have 3 annotations between them, all to the same gene.

id: GO:0008800
name: beta-lactamase activity
namespace: molecular_function
def: "Catalysis of the reaction: a beta-lactam + H2O = a substituted beta-amino acid." [EC:3.5.2.6]
synonym: "ampicillinase activity" RELATED [EC:3.5.2.6]
synonym: "beta-lactam hydrolase activity" RELATED [EC:3.5.2.6]
synonym: "beta-lactamase A, B, C" RELATED [EC:3.5.2.6]
synonym: "beta-lactamase AME I" RELATED [EC:3.5.2.6]
synonym: "beta-lactamase I-III" RELATED [EC:3.5.2.6]
synonym: "cephalosporin-beta-lactamase activity" RELATED [EC:3.5.2.6]
synonym: "exopenicillinase activity" RELATED [EC:3.5.2.6]
synonym: "neutrapen" RELATED [EC:3.5.2.6]
synonym: "penicillin amido-beta-lactamhydrolase activity" RELATED [EC:3.5.2.6]
synonym: "penicillin beta-lactamase activity" RELATED [EC:3.5.2.6]
synonym: "penicillinase I, II" RELATED [EC:3.5.2.6]
xref: EC:3.5.2.6
xref: MetaCyc:BETA-LACTAMASE-RXN
xref: RHEA:20401
is_a: GO:0016812 ! hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in cyclic amides

id: GO:0033250 (2 annotations to blaC by MTBBASE)
name: penicillinase activity
namespace: molecular_function
def: "Catalysis of the reaction: a penicillin + H2O = a substituted beta-amino acid derivative of the penicillin." [GOC:mlg]
xref: MetaCyc:BETA-LACTAMASE-RXN
is_a: GO:0008800 ! beta-lactamase activity

id: GO:0033251 (1 annotations to blaC by MTBBASE)
name: cephalosporinase activity
namespace: molecular_function
def: "Catalysis of the reaction: a cephalosporin + H2O = a substituted beta-amino acid derivative of the cephalosporin." [GOC:mlg]
xref: MetaCyc:BETA-LACTAMASE-RXN
is_a: GO:0008800 ! beta-lactamase activity

**Comment by pgaudet** [comment]
@raymond91125 Would you please obsolete GO:0033250 and GO:0033251  & replace by GO:0008800 beta-lactamase activity? 

Annotations (MTBBASE) will be automatically migrated.

Thanks, Pascale

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0033250 penicillinase activity and GO:0033251 cephalosporinase activity, and replace them by GO:0008800 beta-lactamase activity. The reason for obsoletion is that these represent specific substrates. There are 3 EXP annotations by MTBBASE that will be automatically migrated. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/28157

Thanks, Pascale
