### ISSUE TITLE
(3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity & children

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28163]
Looking at this set of terms (with the number of EXP annotations given in parentheses):

```
(3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity (GO:0019171, EC:4.2.1.59, RHEA:13097)
           |__(3R)-3-hydroxybutanoyl-[acyl-carrier-protein] hydratase activity  (1 EXP)
           |__(3R)-3-hydroxydecanoyl-[acyl-carrier-protein] dehydratase activity (2 EXP)
           |__(3R)-3-hydroxymyristoyl-[acyl-carrier-protein] dehydratase activity (0 EXP)
           |__(3R)-3-hydroxyoctanoyl-[acyl-carrier-protein] dehydratase activity (2 EXP)
           |__(3R)-3-hydroxypalmitoyl-[acyl-carrier-protein] dehydratase activity (0 EXP)
```

Only the parent term has an EC xref (EC:4.2.1.59), while the rest are substrate-specific terms that have a RHEA and sometimes a KEGG/MetaCyc xref.

There are additional substrate-specific reactions we could add here -  RHEA:13097 lists the following as specific forms:
RHEA:41924 (3R)-hydroxyoctadecanoyl-[ACP] = (2E)-octadecenoyl-[ACP] + H2O
RHEA:41908 (3R)-hydroxyhexadecanoyl-[ACP] = (2E)-hexadecenoyl-[ACP] + H2O
RHEA:41892 (3R)-hydroxytetradecanoyl-[ACP] = (2E)-tetradecenoyl-[ACP] + H2O
RHEA:41876 (3R)-hydroxydodecanoyl-[ACP] = (2E)-dodecenoyl-[ACP] + H2O
RHEA:41860 (3R)-hydroxydecanoyl-[ACP] = (2E)-decenoyl-[ACP] + H2O
RHEA:41844 (3R)-hydroxyoctanoyl-[ACP] = (2E)-octenoyl-[ACP] + H2O
RHEA:41828 (3R)-hydroxyhexanoyl-[ACP] = (2E)-hexenoyl-[ACP] + H2O
RHEA:41808 (3R)-hydroxybutanoyl-[ACP] = (2E)-butenoyl-[ACP] + H2O

MetaCyc lists many more - https://biocyc.org/META/NEW-IMAGE?type=EC-NUMBER&object=EC-4.2.1.59

But I think we should:

- [ ]  keep the parent term (GO:0019171) here, and obsolete all of the substrate-specific child terms.
- [x] Note that the MetaCyc xref on GO:0019171 should be replaced with 3-HYDROXYDECANOYL-ACP-DEHYDR-RXN

All terms are listed below FYI:

id: GO:0019171
name: (3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity
namespace: molecular_function
def: "Catalysis of the reaction: a (3R)-hydroxyacyl-[acyl-carrier-protein] = a (2E)-enoyl-[acyl-carrier-protein] + H2O." [RHEA:13097]
synonym: "(3R)-3-hydroxyacyl-[acyl-carrier-protein] dehydratase activity" RELATED []
synonym: "3-hydroxyacyl-[acyl-carrier protein] dehydratase activity" EXACT []
synonym: "3-hydroxyacyl-[acyl-carrier-protein] dehydratase activity" BROAD []
synonym: "3-hydroxyacyl-ACP dehydratase activity" EXACT []
xref: EC:4.2.1.59
xref: MetaCyc:4.2.1.59-RXN
xref: RHEA:13097
is_a: GO:0016836 ! hydro-lyase activity

===

id: GO:0047450 (1 EXP annotation to At2g22230)
name: (3R)-3-hydroxybutanoyl-[acyl-carrier-protein] hydratase activity
namespace: molecular_function
alt_id: GO:0080063
def: "Catalysis of the reaction: (3R)-hydroxybutanoyl-[acyl-carrier-protein] = (2E)-butenoyl-[acyl-carrier-protein] + H2O." [RHEA:41808]
synonym: "(3R)-hydroxybutanoyl-[acyl-carrier-protein] hydratase activity" EXACT []
synonym: "3-hydroxybutyryl acyl carrier protein dehydratase activity" EXACT []
synonym: "beta-hydroxybutyryl acyl carrier protein (ACP) dehydrase activity" EXACT []
synonym: "crotonoyl-[acyl-carrier protein] hydratase activity" EXACT []
synonym: "crotonoyl-[acyl-carrier-protein] hydratase activity" EXACT []
synonym: "crotonoyl-ACP hydratase activity" EXACT []
synonym: "crotonoyl-acyl-carrier-protein hydratase activity" EXACT []
synonym: "crotonyl acyl carrier protein hydratase activity" EXACT []
xref: KEGG_REACTION:R04428
xref: RHEA:41808
is_a: GO:0019171 ! (3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity

id: GO:0047451 (2 EXP annotations to fabA and fabZ)
name: (3R)-3-hydroxyoctanoyl-[acyl-carrier-protein] dehydratase activity
namespace: molecular_function
def: "Catalysis of the reaction: (3R)-3-hydroxyoctanoyl-[acyl-carrier protein] = H2O + (2E)-octenoyl-[acyl-carrier protein]." [PMID:8910376, RHEA:41844]
synonym: "(3R)-3-hydroxyoctanoyl-[acyl-carrier-protein] hydro-lyase activity" RELATED []
synonym: "3-hydroxyoctanoyl-[acyl-carrier protein] dehydratase activity" EXACT []
synonym: "3-hydroxyoctanoyl-[acyl-carrier-protein] dehydratase activity" BROAD []
synonym: "3-hydroxyoctanoyl-ACP dehydratase activity" EXACT []
xref: KEGG_REACTION:R04537
xref: MetaCyc:4.2.1.59-RXN
xref: RHEA:41844
is_a: GO:0019171 ! (3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity

id: GO:0004317 (0 EXP annotations)
name: (3R)-3-hydroxypalmitoyl-[acyl-carrier-protein] dehydratase activity
namespace: molecular_function
def: "Catalysis of the reaction: (3R)-hydroxypalmitoyl-[acyl-carrier protein] = 2-hexadecenoyl-[acyl-carrier protein] + H2O." [PMID:8088535, RHEA:41908]
synonym: "(3R)-3-hydroxypalmitoyl-acyl-carrier-protein hydro-lyase (hexadec-2-enoyl-acyl-carrier protein-forming)" EXACT []
synonym: "(3R)-3-hydroxypalmitoyl-acyl-carrier-protein hydro-lyase activity" EXACT []
synonym: "(3R)-hydroxypalmitoyl-[acyl-carrier-protein] dehydratase activity" EXACT []
synonym: "3-hydroxypalmitoyl-[acyl-carrier protein] dehydratase activity" EXACT []
synonym: "3-hydroxypalmitoyl-[acyl-carrier-protein] dehydratase activity" EXACT []
synonym: "3-hydroxypalmitoyl-ACP dehydratase activity" EXACT []
synonym: "3-hydroxypalmitoyl-acyl-carrier-protein dehydratase activity" EXACT []
xref: KEGG_REACTION:R04462
xref: RHEA:41908
is_a: GO:0019171 ! (3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity

id: GO:0008659 (0 EXP annotations)
name: (3R)-3-hydroxymyristoyl-[acyl-carrier-protein] dehydratase activity
namespace: molecular_function
def: "Catalysis of the reaction: (3R)-3-hydroxytetradecanoyl-[acyl-carrier protein] = tetradecenoyl-[acyl-carrier protein] + H2O." [GOC:ai, PMID:12368867, RHEA:41892]
synonym: "(3R)-hydroxymyristoyl-[acyl-carrier protein] dehydratase activity" EXACT []
synonym: "(3R)-hydroxymyristoyl-[acyl-carrier-protein] dehydratase activity" EXACT []
synonym: "(3R)-hydroxymyristoyl-ACP dehydratase activity" EXACT []
xref: RHEA:41892
is_a: GO:0019171 ! (3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity

id: GO:0008693 (2 EXP annotations)
name: (3R)-3-hydroxydecanoyl-[acyl-carrier-protein] dehydratase activity
namespace: molecular_function
def: "Catalysis of the reaction: (3R)-3-hydroxydecanoyl-[acyl-carrier protein] = 2,3-decenoyl-[acyl-carrier protein] or 3,4-decenoyl-[acyl-carrier protein] + H2O." [PMID:8910376, RHEA:41860]
synonym: "(3R)-3-hydroxydecanoyl-acyl-carrier-protein hydro-lyase activity" EXACT []
synonym: "3-hydroxydecanoyl-[acyl-carrier protein] dehydratase activity" EXACT []
synonym: "3-hydroxydecanoyl-[acyl-carrier-protein] dehydratase activity" EXACT []
synonym: "3-hydroxydecanoyl-ACP dehydratase activity" EXACT []
synonym: "3-hydroxydecanoyl-acyl carrier protein dehydrase activity" EXACT []
synonym: "3-hydroxydecanoyl-acyl carrier protein dehydratase activity" EXACT []
synonym: "3-hydroxydecanoyl-acyl-carrier-protein dehydratase activity" EXACT []
synonym: "beta-hydroxyacyl-ACP dehydrase activity" EXACT []
synonym: "beta-hydroxyacyl-acyl carrier protein dehydratase activity" EXACT []
synonym: "beta-hydroxydecanoate dehydrase activity" EXACT []
synonym: "beta-hydroxydecanoyl thioester dehydrase activity" EXACT []
xref: MetaCyc:3-HYDROXYDECANOYL-ACP-DEHYDR-RXN
xref: RHEA:41860
is_a: GO:0019171 ! (3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete 
GO:0047450 (3R)-3-hydroxybutanoyl-[acyl-carrier-protein] hydratase activity >> 1 EXP
GO:0008693 (3R)-3-hydroxydecanoyl-[acyl-carrier-protein] dehydratase activity >> 2 EXP
GO:0008659 (3R)-3-hydroxymyristoyl-[acyl-carrier-protein] dehydratase activity >> 0 EXP
GO:0047451 (3R)-3-hydroxyoctanoyl-[acyl-carrier-protein] dehydratase activity >> 2 EXP
GO:0004317 (3R)-3-hydroxypalmitoyl-[acyl-carrier-protein] dehydratase activity >> 0 EXP

& replace by parent GO:0019171 (3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity. The reason for obsoletion is that these represent specific substrates of GO:0019171 (3R)-hydroxyacyl-[acyl-carrier-protein] dehydratase activity; the enzyme is not selective for the length of the chain (see comments in https://enzyme.expasy.org/EC/4.2.1.59): 

> Different forms of the enzyme may have preferences for substrates with different chain length.
Despite the differences both forms can catalyze all steps leading to the synthesis of palmitate (C16:0).

Annotations are here: https://github.com/geneontology/go-annotation/issues/5307

Thanks, Pascale
