### ISSUE TITLE
true path violation fumarate reductase (NADH) activity (GO:0016156)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28162]
fumarate reductase (NADH) activity (GO:0016156)

is currently a child of 
succinate dehydrogenase activity(GO:0000104)

but it catalyses  the reduction of fumarate to succinate?

**Comment by pgaudet** [comment]
Does it? 

The reaction is 'NAD(+) + succinate = fumarate + H(+) + NADH' 

Also, in EC the direction of the oxidoreduction is standard in IUBMB, see https://iubmb.qmul.ac.uk/enzyme/rules.html
> One important extension of this principle is the question of the direction in which the reaction is written for the purposes of classification. To simplify the classification, the direction chosen should be the same for all enzymes in a given class, even if this direction has not been demonstrated for all. Thus the systematic names, on which the classification and code numbers are based, may be derived from a written reaction, even though only the reverse of this has been actually demonstrated experimentally.

In anycase, based on the definitions, the parentage seems right to me.

**Comment by ValWood** [comment]
ignore!
