### ISSUE TITLE
2-haloacid dehalogenase activity terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28188]
id: GO:0018784
name: (S)-2-haloacid dehalogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: (S)-2-haloacid + H2O = (R)-2-hydroxyacid + halide." [EC:3.8.1.2]
synonym: "(S)-2-haloacid halidohydrolase activity" RELATED [EC:3.8.1.2]
synonym: "2-haloacid dehalogenase activity" EXACT []
synonym: "2-haloacid halidohydrolase activity" RELATED [EC:3.8.1.2]
synonym: "2-haloalkanoic acid dehalogenase activity" RELATED [EC:3.8.1.2]
synonym: "2-haloalkanoid acid halidohydrolase activity" RELATED [EC:3.8.1.2]
synonym: "2-halocarboxylic acid dehalogenase II activity" RELATED [EC:3.8.1.2]
synonym: "DL-2-haloacid dehalogenase activity" RELATED [EC:3.8.1.2]
synonym: "halocarboxylic acid halidohydrolase activity" RELATED [EC:3.8.1.2]
synonym: "L-2-haloacid dehalogenase activity" RELATED [EC:3.8.1.2]
synonym: "L-DEX activity" RELATED [EC:3.8.1.2]
xref: EC:3.8.1.2
xref: MetaCyc:2-HALOACID-DEHALOGENASE-RXN
xref: RHEA:11192
xref: UM-BBD_reactionID:r0090
is_a: GO:0019120 ! hydrolase activity, acting on acid halide bonds, in C-halide compounds

- [x] MetaCyc:2-HALOACID-DEHALOGENASE-RXN should be broadMatch

id: GO:0033975
name: (R)-2-haloacid dehalogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: (R)-2-haloacid + H2O = (S)-2-hydroxyacid + halide." [EC:3.8.1.9]
synonym: "(R)-2-haloacid halidohydrolase activity" RELATED [EC:3.8.1.9]
synonym: "2-haloalkanoic acid dehalogenase activity" BROAD [EC:3.8.1.9]
synonym: "2-haloalkanoid acid halidohydrolase activity" BROAD [EC:3.8.1.9]
synonym: "D-2-haloacid dehalogenase activity" RELATED [EC:3.8.1.9]
synonym: "D-DEX" RELATED [EC:3.8.1.9]
xref: EC:3.8.1.9
xref: MetaCyc:RXN-6264
xref: RHEA:22188
is_a: GO:0019120 ! hydrolase activity, acting on acid halide bonds, in C-halide compounds

=> this looks good!

id: GO:0033976
name: 2-haloacid dehalogenase (configuration-inverting) activity
namespace: molecular_function
def: "Catalysis of the reactions: (S)-2-haloacid + H2O = (R)-2-hydroxyacid + halide, and (R)-2-haloacid + H2O = (S)-2-hydroxyacid + halide." [GOC:curators]
synonym: "2-haloalkanoic acid dehalogenase activity" BROAD [EC:3.8.1.10]
synonym: "2-haloalkanoid acid halidohydrolase activity" BROAD []
synonym: "DL-2-haloacid dehalogenase (inversion of configuration) activity" RELATED []
synonym: "DL-2-haloacid dehalogenase activity" BROAD []
synonym: "DL-2-haloacid halidohydrolase (inversion of configuration) activity" RELATED []
synonym: "DL-DEXi" RELATED []
xref: MetaCyc:2-HALOACID-DEHALOGENASE-RXN
xref: MetaCyc:RXN-6264
is_a: GO:0019120 ! hydrolase activity, acting on acid halide bonds, in C-halide compounds

- [x] MetaCyc:2-HALOACID-DEHALOGENASE-RXN should be exactMatch
- [x] remove MetaCyc:RXN-6264 (it's correctly on GO:0033975)
- [x] add EC:3.8.1.10

id: GO:0018778
name: DL-2 haloacid dehalogenase activity
namespace: molecular_function
def: "Catalysis of the reaction: trichloroacetate + 2 H2O = 3 H+ + 3 Cl- + oxalate." [UM-BBD_reactionID:r0382]
xref: EC:3.8.1.10
xref: MetaCyc:RXN-9150
xref: UM-BBD_reactionID:r0382
is_a: GO:0019120 ! hydrolase activity, acting on acid halide bonds, in C-halide compounds

- MetaCyc:RXN-9150 is a different reaction from UM-BBD_reactionID:r0382. RXN-9150 is: 2,2,2-trichloroacetate + 2 NADPH + dioxygen → oxalate + 3 chloride + 2 NADP+ + 2 H+, and entry says "No enzyme has been identified for this reaction in this database."
- EC:3.8.1.10 is similar but also different from UM-BBD_reactionID:r0382 - see GO:0033976 above

- [x] suggest GO:0018778 is obsoleted. It just has  10 IEA annotations, all from the incorrect EC association.

**Comment by sjm41** [comment]
@pgaudet I've done the other tasks, but GO:0018778 still needs obsoleting (if you agree).

**Comment by pgaudet** [comment]
Obsoleted other terms in that branch: 

- [ ] [deisopropyldeethylatrazine hydrolase activity](http://purl.obolibrary.org/obo/GO_0018783) : xref [UM-BBD_reactionID:0129](http://eawag-bbd.ethz.ch/servlets/pageservlet?ptype=r&reacID=0129) deprecated
- [ ] [1,3,4,6-tetrachloro-1,4-cyclohexadiene halidohydrolase activity](http://purl.obolibrary.org/obo/GO_0018777): represents a specific substrate of [haloalkane dehalogenase activity](http://purl.obolibrary.org/obo/GO_0018786)
