### ISSUE TITLE
Merge maltose glucosidase activity & maltose alpha-glucosidase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28195]
These two terms share the same MetaCyc:RXN-15910 xref, and from looking at PMID:16343940, describe the same activity - they should be merged:

id: GO:0032450
name: maltose alpha-glucosidase activity
def: "Catalysis of the reaction: alpha-maltose + H2O = 2 alpha-D-glucose." [MetaCyc:RXN-2141]
synonym: "maltase activity" EXACT []
xref: EC:3.2.1.20
xref: MetaCyc:RXN-15910
is_a: GO:0004558 ! alpha-1,4-glucosidase activity

id: GO:0102498
name: maltose glucosidase activity
def: "Catalysis of the reaction: H2O + maltose = 2 glucose." [GOC:pz, PMID:16343940]
xref: MetaCyc:RXN-15910
is_a: GO:0090599 ! alpha-glucosidase activity

---

That said, MetaCyc:RXN-15910 is an "unofficial reaction" of MetaCyc:MALTODEXGLUCOSID-RXN (EC:3.2.1.20):
(1,4-α-D-glucosyl)(n) + H2O → (1,4-α-D-glucosyl)(n-1) + D-glucopyranose

That  corresponds to GO:0004558, so we may want to merge both the above terms in to GO:0004558:

id: GO:0004558
name: alpha-1,4-glucosidase activity
def: "Catalysis of the hydrolysis of terminal, non-reducing alpha-(1->4)-linked alpha-D-glucose residues with release of alpha-D-glucose." [EC:3.2.1.20]
synonym: "acid maltase activity" RELATED [EC:3.2.1.20]
synonym: "alpha-D-glucosidase activity" RELATED [EC:3.2.1.20]
synonym: "alpha-D-glucoside glucohydrolase activity" RELATED [EC:3.2.1.20]
synonym: "alpha-glucopyranosidase activity" RELATED [EC:3.2.1.20]
synonym: "alpha-glucosidase II" RELATED []
synonym: "alpha-glucoside hydrolase activity" RELATED [EC:3.2.1.20]
synonym: "glucoinvertase activity" RELATED [EC:3.2.1.20]
synonym: "glucosidoinvertase activity" RELATED [EC:3.2.1.20]
synonym: "glucosidosucrase activity" RELATED [EC:3.2.1.20]
synonym: "lysosomal alpha-glucosidase activity" BROAD [EC:3.2.1.20]
synonym: "maltase-glucoamylase activity" RELATED [EC:3.2.1.20]
xref: EC:3.2.1.20
xref: MetaCyc:MALTODEXGLUCOSID-RXN
is_a: GO:0090599 ! alpha-glucosidase activity

(Sorry @pgaudet, this aspect will already be on your list of EC duplicates to check)

Note: there doesn't seem to be a RHEA for this.

**Comment by pgaudet** [comment]
Done in https://github.com/geneontology/go-ontology/issues/28110
