### ISSUE TITLE
Obsoletion request: GO:0018913 anaerobic ethylbenzene metabolic process   replace by GO:0010130 anaerobic ethylbenzene catabolic process

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28209]
These two terms represent the same process. Please make sure to transfer the db cross ref UM-BBD_pathwayID:ethb to GO:0010130.

Same for GO:0019261 and GO:0018912: obsolete GO:0018912  and replace by GO:0019261 

Thanks, Pascale

**Comment by LiNiMGI** [comment]
Hi Raymond, 
These are probably not natural products, there is no biosynthetic process, so the metabolic process grouping term is not necessary.
I will put all of them together here:
GO:0018913 anaerobic ethylbenzene metabolic process replace by GO:0010130 anaerobic ethylbenzene catabolic process
GO:0018912 1,4-dichlorobenzene metabolic process replace by GO:0019261 1,4-dichlorobenzene catabolic process
GO:0018865 acrylonitrile metabolic process replace by GO:0019256 acrylonitrile catabolic process
GO:0018967 tetrachloroethylene metabolic process replace by GO:0019337 tetrachloroethylene catabolic process

please make sure to transfer the db cross ref UM-BBD_pathwayID from 'metabolic process' to 'catabolic process' before obsolete the 'metabolic process'.

Thanks,
Li

**Comment by raymond91125** [comment]
Perhaps also obsolete GO:0018915 ethylbenzene metabolic process.
