### ISSUE TITLE
Missing parent: GDP-Man:Man1GlcNAc2-PP-Dol alpha-1,3-mannosyltransferase activity (GO:0004378)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28212]
* **GO term ID and label for which you request a new superclass**

GDP-Man:Man1GlcNAc2-PP-Dol alpha-1,3-mannosyltransferase activity (GO:0004378)

should this be is_a
alpha-1,3-mannosyltransferase activity (GO:0000033)?

note that
dol-P-Man:Man(5)GlcNAc(2)-PP-Dol alpha-1,3-mannosyltransferase activity  (GO:0052925)
is a descendant of alpha-1,3-mannosyltransferase activity, and I am getting PAINT propagation to

alpha-1,3-mannosyltransferase activity (GO:0000033)
which should be hidden by 
GDP-Man:Man1GlcNAc2-PP-Dol alpha-1,3-mannosyltransferase activity (GO:0004378)

* **New superclass (parent) suggested**

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by ValWood** [comment]
and if so
 GDP-Man:Man2GlcNAc2-PP-dolichol alpha-1,6-mannosyltransferase activity (GO:0102704)
should be is_a  alpha-1,6-mannosyltransferase activity (GO:0000009)

**Comment by pgaudet** [comment]
That looks right!
