### ISSUE TITLE
NTR: glycolipid 1,4-alpha-mannosyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28214]
Please provide as much information as you can: 

* **Suggested term label:**

 glycolipid 1,4-alpha-mannosyltransferase activity

* **Definition (free text)**

Catalysis of the transfer of an alpha-D-mannosyl residue from GDP-mannose into lipid-linked oligosaccharide, forming an alpha-(1->4)-D-mannosyl-D-mannose linkage.

* **Reference, in format PMID:#######**

SGD description is
Glycosylphosphatidylinositol-alpha 1,4 mannosyltransferase I;
we can use this reference
https://pubmed.ncbi.nlm.nih.gov/11226175/
but I cant see where the  1,4-alpha- originates.

* **Gene product name and ID to be annotated to this term**

https://www.pombase.org/gene/SPBC13E7.05 Gpi14

* **Parent term(s)**

GO:0051751 | alpha-1,4-mannosyltransferase activity
GO:0004376 | glycolipid mannosyltransferase activity | IEA with IPR007704

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

GPI-MT-I activity
glycosylphosphatidylinositol-mannosyltransferase I 

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

which transfers the first of the four mannoses in the GPI-anchor precursors.

**Comment by ValWood** [comment]
UniProt Human PIG-M concurs
Mannosyltransferase involved in glycosylphosphatidylinositol-anchor biosynthesis. Transfers the first alpha-1,4-mannose to GlcN-acyl-PI during GPI precursor assembly.
PMID: 11226175

PIG-M (gpi14) and PIG-X (Pbn1)

are the 2 members of
GO:1990529   glycosylphosphatidylinositol-mannosyltransferase I complex

PIG-X appears to be the regulatory protein

**Comment by deustp01** [comment]
Another useful reference? PMID: 15635094

**Comment by ValWood** [comment]
Yes thanks !

**Comment by pgaudet** [comment]
It would be great if we could find the EC and RHEA that correspond to this reaction  - https://enzyme.expasy.org/EC/2.4.1.-
but maybe there are none yet?

**Comment by ValWood** [comment]
I don't think RHea EC have every GPI pathway enzyme specificity. I could not find it anyway.
@kaxelsen

**Comment by kaxelsen** [comment]
Correct. There is so much variation (between species) in the architecture of GPI anchors, and so littel precise characterisation that it has not been possible create reactions for this pathway yet.

**Comment by pgaudet** [comment]
Hummm, that makes it a bit dubious fo GO as well then!

**Comment by ValWood** [comment]
I think it is valid in this instance. Otherwise we need to use 2 terms to model one activity:

GO:0051751 | alpha-1,4-mannosyltransferase activity
GO:0004376 | glycolipid mannosyltransferase activity

both are  valid annotations for this gene product.

Also GPI14 is universally conserved across eukaryotes  as are all other members of the GPI biosynthesis pathway, and others do now have a specific activity:
like [glycolipid 1,6-alpha-mannosyltransferase activity

**Comment by ValWood** [comment]
Besed on
UniProt Human PIG-M 
Mannosyltransferase involved in glycosylphosphatidylinositol-anchor biosynthesis. Transfers the first alpha-1,4-mannose to GlcN-acyl-PI during GPI precursor assembly.
PMID: 11226175

It should even be more specific?

**Comment by ValWood** [comment]
+[Term]
+id: GO:0180041
+name: glycolipid 1,4-alpha-mannosyltransferase activity
ing an alpha-(1->4)-D-mannosyl-D-mannose linkage." [PMID:11226175, PMID:15635094]
+synonym: "glycosylphosphatidylinositol-mannosyltransferase I" EXACT []
+synonym: "GPI-MT-I activity" EXACT []
+is_a: GO:0004376 ! glycolipid mannosyltransferase activity
+is_a: GO:0051751 ! alpha-1,4-mannosyltransferase activity
+created_by: vw
+creation_date: 2024-06-24T10:35:01Z
+
