### ISSUE TITLE
EC:1.14.14.178 steroid 22S-hydroxylase 

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28221]
id: GO:0102780
name: sitosterol hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: H+ + sitosterol + O2 + NADPH = (22alpha)-hydroxy-sitosterol + H2O + NADP." [EC:1.14.13.-, GOC:pz]
xref: MetaCyc:RXN-7876
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

id: GO:0102729
name: 6-oxocampestanol hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: H+ + 6-oxocampestanol + O2 + NADPH = cathasterone + H2O + NADP." [GOC:pz]
xref: MetaCyc:RXN-715
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

id: GO:0102677
name: campesterol,NADPH:oxygen oxidoreductase activity
namespace: molecular_function
def: "Catalysis of the reaction: H+ + campesterol + O2 + NADPH = (22S)-22-hydroxycampesterol + H2O + NADP." [EC:1.14.13.-, GOC:pz]
xref: MetaCyc:RXN-4225
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

id: GO:0102759
name: campestanol hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: H+ + campestanol + O2 + NADPH = 6-deoxycathasterone + H2O + NADP." [EC:1.14.13.-, GOC:pz]
xref: MetaCyc:RXN-773
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

(no annotations for any term)

MetaCyc says for all: "Note that this reaction equation differs from the official Enzyme Commission reaction equations for this EC entry" which = EC:1.14.14.178 = steroid 22S-hydroxylase (not in GO)

We should merge these terms into a single term to represent the more general reaction, matching EC:1.14.14.178:

steroid 22S-hydroxylase
a C27-steroid + O2 + reduced [NADPH--hemoprotein reductase] <=> a (22S)-22-hydroxy C27-steroid + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]
a C28-steroid + O2 + reduced [NADPH--hemoprotein reductase] <=> a (22S)-22-hydroxy C28-steroid + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]
a C29-steroid + O2 + reduced [NADPH--hemoprotein reductase] <=> a (22S)-22-hydroxy C29-steroid + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]

with RHEA:70059 (MetaCyc:RXN-22826), RHEA:70063 (MetaCyc:RXN-22825), RHEA:70067 (MetaCyc:RXN-22827) as narrowMatch xrefs.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160191
+name: steroid 22S-hydroxylase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: a C27-steroid + O2 + reduced NADPH--hemoprotein reductase = a (22S)-22-hydroxy C27-steroid + H+ + H2O + oxidized NADPH--hemoprotein reductase, a C28-steroid + O2 + reduced NADPH--hemoprotein reductase = a (22S)-22-hydroxy C28-steroid + H+ + H2O + oxidized NADPH--hemoprotein reductase, or a C29-steroid + O2 + reduced NADPH--hemoprotein reductase = a (22S)-22-hydroxy C29-steroid + H+ + H2O + oxidized NADPH--hemoprotein reductase." [EC:1.14.14.178]
+synonym: "steroid C-22 hydroxylase activity" EXACT [EC:1.14.14.178]
+xref: EC:1.14.14.178
+xref: MetaCyc:RXN-22825 {source="skos:narrowMatch"}
+xref: MetaCyc:RXN-22826 {source="skos:narrowMatch"}
+xref: MetaCyc:RXN-22827 {source="skos:narrowMatch"}
+xref: RHEA:70059 {source="skos:narrowMatch"}
+xref: RHEA:70063 {source="skos:narrowMatch"}
+xref: RHEA:70067 {source="skos:narrowMatch"}
+is_a: GO:0016712 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28221" xsd:anyURI
+created_by: rynl
+creation_date: 2024-06-27T00:40:39Z

**Comment by pgaudet** [comment]
Hi @raymond91125 

I simplified the reaction to "Catalysis of the reaction: a C28-steroid + O2 + reduced NADPH--hemoprotein reductase = a (22S)-22-hydroxy C28-steroid + H+ + H2O + oxidized NADPH--hemoprotein reductase. Also catalyzes the C-22 hydroxylation of a variety of C27 and C29 steroids." 


Also, I made the EC skos:exactMatch, since with @sjm41 we came to the conclusion that we cannot assume the relation between GO terms and EC, so it's better to state when we know it. 

Thanks, Pascale
