### ISSUE TITLE
GO:0033898 is a subreaction of GO:0033897

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28225]
id: GO:0033898
name: Bacillus subtilis ribonuclease activity
namespace: molecular_function
def: "Catalysis of the endonucleolytic cleavage to 2',3'-cyclic nucleotides." [EC:4.6.1.22]
synonym: "proteus mirabilis RNase activity" EXACT []
synonym: "ribonucleate nucleotido-2'-transferase (cyclizing) activity" BROAD []
xref: EC:4.6.1.22
xref: MetaCyc:RXN-19924
is_a: GO:0016892 ! RNA endonuclease activity, producing 3'-phosphomonoesters

(7 annotations, all IEA via the EC xref)

MetaCyc:RXN-19924 says that this is a Sub-reaction of 4.6.1.19, which is GO:0033897:

id: GO:0033897
name: ribonuclease T2 activity
namespace: molecular_function
def: "Catalysis of the two-stage endonucleolytic cleavage to nucleoside 3'-phosphates and 3'-phosphooligonucleotides with 2',3'-cyclic phosphate intermediates." [EC:4.6.1.19]
xref: EC:4.6.1.19
xref: MetaCyc:3.1.27.5-RXN
is_a: GO:0004521 ! RNA endonuclease activity
is_a: GO:0016849 ! phosphorus-oxygen lyase activity

- [x] So, I think GO:0033898 should be obsoleted?

- [x] Also, can add [RHEA:68052](https://www.rhea-db.org/rhea/68052) as xref to GO:0033897

**Comment by raymond91125** [comment]
It seems enzymes that carry out just the half rxn may be different from the full rxn ones.
EC:4.6.1.22 was used to annotate CRISPR-associated proteins, e.g. <https://www.uniprot.org/uniprotkb/U2UMQ6/entry> that appear to be different from those annotated with EC:4.6.1.19 at UniProt.

**Comment by sjm41** [comment]
Hi @raymond91125 

Thanks for looking into this.

I see there is only a single reviewed (SwissProt) entry at UniPort with EC:4.6.1.22 manually assigned to it:
https://www.uniprot.org/uniprotkb/A0Q7Q2/entry
This is "CRISPR-associated endonuclease Cas12a (cas12a)" from the bacterium Francisella tularensis subsp. novicida.  

The annotation comes from PMID: [28431230](https://pubmed.ncbi.nlm.nih.gov/28431230). That paper does say that Cas12a reaction is a "RNA cleavage reactions dependent on the presence of the 2’-hydroxyl group in the ribonucleotide upstream of the scissile phosphate typically proceed via acid-base (rather than metal-dependent) catalysis and yield products containing 5’-hydroxyl and 2’,3’-cyclic phosphate groups."
So, the EC:4.6.1.22 annotation does seem to be correct here?

(I note that EC:4.6.1.22 does not appear to be annotated to any Bacillus subtilis proteins, despite its EC name of "Bacillus subtilis ribonuclease activity ribonuclease activity".)


However, looking again at GO:0033897, I see that its associated [RHEA:68052](https://www.rhea-db.org/rhea/68052) has the comment saying "Multi-step reaction: RHEA:67796 and RHEA:68056"

and RHEA:67796 is: "a ribonucleotidyl-ribonucleotide-RNA = a 3'-end 2',3'-cyclophospho-ribonucleotide-RNA + a 5'-end dephospho-ribonucleoside-RNA", that RHEA says corresponds to MetaCyc:RXN-19924.

So, both MetaCyc and RHEA state that that GO:0033898 (= RHEA:67796 / MetaCyc:RXN-19924) is a sub-reaction of GO:0033897 (= EC:4.6.1.19 / RHEA:68052 / MetaCyc:3.1.27.5-RXN), in which case it should be obsoleted in GO.


@kaxelsen 
Could you confirm:
i) that the EC:4.6.1.22 annotation to A0Q7Q2 (cas12a) from PMID:28431230 is correct?
ii) whether RHEA:67796 = MetaCyc:RXN-19924 = EC:4.6.1.22 = GO:0033898? (there is currently no direct link between  RHEA:67796 and EC:4.6.1.22 in RHEA, though this is implied via the shared MetaCyc:RXN-19924 xref)
