### ISSUE TITLE
Obsoletion request GO:0018266  GPI anchor biosynthetic process via N-aspartyl-glycosylphosphatidylinositolethanolamine AND SIBLINGS

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28228]
Please provide as much information as you can:

* **GO term ID and Label**

- [x] GO:0018266 GPI anchor biosynthetic process via N-aspartyl-glycosylphosphatidylinositolethanolamine
- [x] GO:0018267 GPI anchor biosynthetic process via N-cysteinyl-glycosylphosphatidylinositolethanolamine
- [x] GO:0018265   GPI anchor biosynthetic process via N-asparaginyl-glycosylphosphatidylinositolethanolamine
- [x] GO:0018268   GPI anchor biosynthetic process via N-glycyl-glycosylphosphatidylinositolethanolamine
- [x] GO:0018269  GPI anchor biosynthetic process via N-seryl-glycosylphosphatidylinositolethanolamine
- [x] GO:0018270  GPI anchor biosynthetic process via N-alanyl-glycosylphosphatidylinositolethanolamine
- [x] GO:0050493   GPI anchor biosynthetic process via N-threonyl-glycosylphosphatidylinositolethanolamine

 - [x] The reason for obsoletion is that this term represents a molecular function.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

GO:0006506  GPI anchor biosynthetic process

* **Are there annotations to this term?**
- How many EXP:
There are no annotations or mappings to these terms

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ValWood** [comment]
These terms are not needed to curate GPI anchor biosynthesis
http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel%3A665912ed00000192

**Comment by ValWood** [comment]
@pgaudet  do you agree with this? They appear to MF term? This is a linear highly conserv ed pathway.

**Comment by ValWood** [comment]
These are definitely single steps. I'll go ahead with this on Monday

**Comment by pgaudet** [comment]
Hi @ValWood , yes I agree with these obsoletions. Moreover it seems these have not been used for annotations. 

Thanks, Pascale
