### ISSUE TITLE
Obsoletion request:  GO:0016254  preassembly of GPI anchor in ER membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28227]
Please provide as much information as you can:

GO:0016254  preassembly of GPI anchor in ER membrane
63 annotations
2EXP uniprot
2 TAS reactome

mainly used for PIG-L  but also for PIG-N and pig_A

I don't know how it is differentiated from the parent GPI anchor biosynthesis?

* **GO term ID and Label**

* **Reason for deprecation** Put an x in the appropriate box: 

- [x]  The reason for obsoletion is that this term was added in error.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

GO:0006506   GPI anchor biosynthetic process

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by deustp01** [comment]
> I don't know how it is differentiated from the parent GPI anchor biosynthesis?

In humans (and I think in yeasts), the overall process can be divided into distinct steps - see [R-HSA-163125](https://reactome.org/content/detail/R-HSA-163125) " Post-translational modification: synthesis of GPI-anchored proteins", and the reaction sequence covered by GO:0016254 "preassembly ..." is one of them. It wouldn't destroy our annotations to lose this term and annotations were all to the overall parent process, but a useful biological distinction would be lost.

**Comment by ValWood** [comment]
But do we have the other 2 steps?  It's a linear pathway  so it adds an extra level of unnecessary complication to add this grouping. If we keep it we should make connections between the MF terms  and t this BP because I'm not sure which BPs go under here from the existing annotation PIG-N, PIG-L and PIG-A

If we keep it the definitions should be better to say which part of the pathway it refers to (steps X to Y). DO you know which steps it is?

**Comment by deustp01** [comment]
Subpathway R-HSA-162710 "Synthesis of glycosylphosphatidylinositol (GPI)" lays out the steps that we grouped under GO:0016524 "preassembly of GPI anchor in ER membrane", and the next subpathway R-HSA-162791 "Attachment of GPI anchor to uPAR" lays out the steps that we grouped under GO:016255 "attachment of GPI anchor to protein"

**Comment by ValWood** [comment]
GO:016255 "attachment of GPI anchor to protein"
is defined
A transamidation reaction that results in the cleavage of the polypeptide chain and the concomitant transfer of the GPI anchor to the newly formed carboxy-terminal amino acid of the anchored protein. The cleaved C-terminal contains the C-terminal GPI signal sequence of the newly synthesized polypeptide chain.

so it seems to be single step (even though it is a 6 subunit complex, its only a single reaction)

**Comment by ValWood** [comment]
@pgaudet Maybe we can discuss this on a call?

**Comment by ValWood** [comment]
1.  GO:0016255  attachment of GPI anchor to protein part_of  GO:0051604  protein maturation

2. GO:0006506  GPI anchor biosynthetic process part_of  GO:0051604  protein maturation

3. Remove GO:0006506 GPI anchor biosynthetic process
as parent of   attachment of GPI anchor to protein (attachment isn't synthesis of the anchor)

4. GO:0016254   merge
preassembly of GPI anchor in ER membrane into  GO:0006506  GPI anchor biosynthetic process (there will be no other parts)

5. Make   GO:0016255  attachment of GPI anchor to protein part of 
AND
GO:0006506  GPI anchor biosynthetic process
part of 
make " NTR GPI anchored protein biosynthesis" 
(to include anchor synthesis and transfer of the anchor to the protein)

6. Check is_a parents

**Comment by ValWood** [comment]
Final step
obsolete 

GO:0016254 preassembly of GPI anchor in ER membrane

This is now single inheritance, no siblings:

(the split is  biosynthesis and attachment)

<img width="1093" alt="Screenshot 2024-08-19 at 15 12 00" src="https://github.com/user-attachments/assets/0b4d188f-3b8b-401a-8302-1775c76bfdb3">

**Comment by ValWood** [comment]
@deustp01  I think you still have the distinction you required (we already had the attachment step but it wasn't grouped with a common parent). 
@pgaudet  I will  also remove the is_a between GO:0006506 and GO:0051604 protein maturation
