### ISSUE TITLE
GO:0102760 and GO:0102097

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28222]
id: GO:0102760
name: 6-deoxocathasterone hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: 6-deoxycathasterone + O2 + a reduced electron acceptor = 6-deoxoteasterone + H2O + an oxidized electron acceptor." [EC:1.14.-.-, GOC:pz]
xref: MetaCyc:RXN-774
is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen

(no annotations)

MetaCyc:RXN-774 says that this reaction equation differs from the official Enzyme Commission reaction equations for this EC entry  = EC:1.14.14.147 (22alpha-hydroxysteroid 23-monooxygenase)

That EC equates to:
id: GO:0102097
name: (22S)-22-hydroxy-5alpha-campestan-3-one C-23 hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: (22S,24R)-22-hydroxy-5alpha-ergostan-3-one + O2 + reduced [NADPH--hemoprotein reductase] = 3-dehydro-6-deoxoteasterone + H+ + H2O + oxidized [NADPH--hemoprotein reductase]. Also converts 3-epi-6-deoxocathasterone to 6-deoxotyphasterol." [EC:1.14.14.147, GOC:pz]
xref: EC:1.14.14.147 {source="skos:exactMatch"}
xref: MetaCyc:RXN-11101
xref: RHEA:27321 {source="skos:narrowMatch"}
xref: RHEA:27325 {source="skos:narrowMatch"}
is_a: GO:0016712 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28070" xsd:anyURI

So the tasks are:

- [x] Merge GO:0102760 with GO:0102097 (or just delete GO:0102760?)
- [x] Rename GO:0102097 to '22alpha-hydroxysteroid 23-monooxygenase activity'
- [ ] Consider generalising the GO:0102097 def further? EC comment says "The enzyme has a relaxed substrate specificity, and C-23 hydroxylation can occur at different stages in the pathway."??

**Comment by pgaudet** [comment]
Did not add the EC comment 

> Consider generalising the GO:0102097 def further? EC comment says "The enzyme has a relaxed substrate specificity, and C-23 hydroxylation can occur at different stages in the pathway."??

since that really sounds like a protein, not a MF.

**Comment by deustp01** [comment]
Would it be useful keeping that EC sentence as a comment, to point out that while position 23 always gets hydroxylated, the rest of the substrate is not fully specified?
