### ISSUE TITLE
Merge 'taxoid 2alpha-hydroxylase activity' terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28220]
I think these two terms should be merged:
- rename as "taxoid 2alpha-hydroxylase activity"
- add EC:1.14.14.183 as exactMatch
- add RHEA:71407 and RHEA:71399 as narrowMatch.

Neither have any annotations.

id: GO:0102365
name: taxusin 2-alpha-hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: taxusin + NADPH + O2 + H+ = 2-alpha-hydroxytaxusin + NADP + H2O." [GOC:pz, PMID:15178487]
xref: MetaCyc:RXN-13486
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

id: GO:0102366
name: 7-beta-hydroxytaxusin 2-alpha-hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: 7-beta-hydroxytaxusin + NADPH + O2 + H+ = 2alpha, 7-beta-dihydroxytaxusin + NADP + H2O." [EC:1.14.13.-, GOC:pz]
xref: MetaCyc:RXN-13487
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

**Comment by sjm41** [comment]
This is the EC entry:

EC 1.14.14.183
taxoid 2alpha-hydroxylase

O2 + reduced [NADPH--hemoprotein reductase] + taxusin <=> 2alpha-hydroxytaxusin + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]

7beta-hydroxytaxusin + O2 + reduced [NADPH--hemoprotein reductase] <=> 2alpha,7beta-dihydroxytaxusin + H(+) + H2O+ oxidized [NADPH--hemoprotein reductase]

**Comment by pgaudet** [comment]
Also merged GO:0102367 '2-alpha-hydroxytaxusin 7-beta-hydroxylase activity' into GO:0036239 'taxoid 7beta-hydroxylase activity'


id: GO:0102367
name: 2-alpha-hydroxytaxusin 7-beta-hydroxylase activity
def: "Catalysis of the reaction: 2alpha-hydroxytaxusin + NADPH + O2 + H+ = 2alpha, 7beta-dihydroxytaxusin + NADP + H2O." [EC:1.14.13.-, GOC:pz]
xref: MetaCyc:RXN-13488


GO:0036239 'taxoid 7beta-hydroxylase activity'
def: "Catalysis of the reaction: taxusin + [reduced NADPH-hemoprotein reductase] + O2 = 7beta-hydroxytaxusin + [oxidized NADPH-hemoprotein reductase] + H2O and 2alpha-hydroxytaxusin + [reduced NADPH-hemoprotein reductase] + O2 = 2alpha,7beta-dihydroxytaxusin + [oxidized NADPH-hemoprotein reductase] + H2O." [PMID:15157877, PMID:15178487]
xref: EC:1.14.14.182

**Comment by pgaudet** [comment]
Fixed parent GO:0102365 from GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

to

GO:0016712 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen
