### ISSUE TITLE
GO:0070733 - extend enzyme activity to include  L-lysine residues in target proteins

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#28233]
* GO:0070733

* extend enzyme activity to include L-lysine residues in target proteins
i.e. change from 
"Catalysis of the reaction: ATP + protein = diphosphate + adenylyl-protein; mediates the addition of an adenylyl (adenosine 5'-monophosphate; AMP group) to L-serine, L-threonine, and L-tyrosine residues in target proteins"
 to
  "Catalysis of the reaction: ATP + protein = diphosphate + adenylyl-protein; mediates the addition of an adenylyl (adenosine 5'-monophosphate; AMP group) to L-serine, L-threonine, L-tyrosine and  L-lysine residues in target proteins"**

* Reference(s)
* PMID:36792600

**Comment by pgaudet** [comment]
@kaxelsen Do you think that can also be changed in EC? 
https://enzyme.expasy.org/EC/2.7.7.108

**Comment by pgaudet** [comment]
Ah ok - then we should no add this. Thanks ! 

@Pauldenny Can you use 'GO:0003972 RNA ligase (ATP) activity' to annotate this? The mechanism of the reaction may be different, but the overall reaction is the same. 

Thanks, Pascale

**Comment by Pauldenny** [comment]
Done - thanks!
