### ISSUE TITLE
Terms with multiple EC as def xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28243]
I came across a term with 2 different ECs as its def xref, which was unexpected, so I searched for other cases - found these 11 cases:

**GO:0008875**
gluconate dehydrogenase activity
def: "Catalysis of the reaction: D-gluconate + NADP+ = dehydro-D-gluconate + NADPH + H+." [EC:1.1.1.215, EC:1.1.1.69]
- [x] These ECs are 2 of the 3 xrefs on the 3 child terms of GO:0008875 - this isn't standard practice, so should change to GOC:curators?

**GO:0016759**
cellulose synthase activity
def: "Catalysis of the reaction: nucleoside-disphosphate-glucose + ((1,4)-beta-D-glucosyl)(n) = nucleoside-disphosphate + ((1,4)-beta-D-glucosyl)(n+1)." [EC:2.4.1.12, EC:2.4.1.29]
- [x] These ECs are the xrefs on the two child terms of GO:0016759 - this isn't standard practice, so should change to GOC:curators?

**GO:0034481**
chondroitin sulfotransferase activity
def: "Catalysis of the reaction: 3'-phosphoadenosine 5'-phosphosulfate + chondroitin = adenosine 3',5'-bisphosphate + chondroitin sulfate." [EC:2.8.2.17, EC:2.8.2.5, GOC:mah]
- [x] These ECs are 2 of the 3 xrefs on the 3 child terms of GO:0034481 - this isn't standard practice, so should change to GOC:curators?

**GO:0045181** 
glutamate synthase activity, NAD(P)H as acceptor
def: "Catalysis of the reaction: 2 L-glutamate + NAD(P)+ = L-glutamine + 2-oxoglutarate + NAD(P)H + H+." [EC:1.4.1.13, EC:1.4.1.14]
- [x] These ECs are the xrefs on the two child terms of GO:0045181 - this isn't standard practice, so should change to GOC:curators?

**GO:0043860**
cyanophycin synthetase activity
def: "Catalysis of the ATP-dependent polymerization of arginine and aspartate to multi-L-arginyl-poly-L-aspartic acid (cyanophycin; a water-insoluble reserve polymer)." [EC:6.3.2.29, EC:6.3.2.30, GOC:jl]
- [x] "These ECs are the xrefs on the two child terms of GO:0043860 - this isn't standard practice, so should change to GOC:curators?
- [x] GO:0043860 also has a term xref o EC:6.3.1.-, which should only be on ""GO:0016880 acid-ammonia (or amide) ligase activity", so remove this from GO:0043860 (and GO:0016211)

**GO:0008948**
oxaloacetate decarboxylase activity
"Catalysis of the reaction: oxaloacetate = pyruvate + CO2." [EC:1.1.1.38, EC:1.1.1.40, EC:4.1.1.112]
**GO:0004471** 
malate dehydrogenase (decarboxylating) (NAD+) activity
def: "Catalysis of the reaction: (S)-malate + NAD+ = pyruvate + CO2 + NADH + H+." [EC:1.1.1.38, EC:1.1.1.39]
- [x] these two are trickier - make separate ticket = #28245

**GO:0008943**
obsolete glyceraldehyde-3-phosphate dehydrogenase activity
def: "OBSOLETE. Catalysis of the reactions: glyceraldehyde 3-phosphate + phosphate + NAD(P)+ = 3-phospho-D-glyceroyl-phosphate + NAD(P)H + H+, and glyceraldehyde 3-phosphate + H2O + NAD(P)+ = 3-phospho-D-glycerate + NAD(P)H + H+." [EC:1.2.1.12, EC:1.2.1.13, EC:1.2.1.9]
- [x] obsolete term - remove xrefs from def.

**GO:0004374**
obsolete glycine cleavage system
def: "OBSOLETE. Catalysis of the reactions: glycine + lipoylprotein = S-aminomethyldihydrolipoylprotein + carbon dioxide (CO2), followed by S-aminomethyldihydrolipoylprotein + (6S)-tetrahydrofolate = dihydrolipoylprotein + (6R)-5,10-methylenetetrahydrofolate + ammonia. Made up of two components, aminomethyltransferase and glycine dehydrogenase (decarboxylating)." [EC:1.4.4.2, EC:2.1.2.10]
- [x] obsolete term - remove xrefs from def.

**GO:0004495**
obsolete mevaldate reductase activity
def: "OBSOLETE. Catalysis of the reaction: (R)-mevalonate + acceptor = mevaldate + reduced acceptor." [EC:1.1.1.32, EC:1.1.1.33]
- [x] obsolete term - remove xrefs from def.

**GO:0004086**
obsolete carbamoyl-phosphate synthase activity
def: "OBSOLETE. Catalysis of a reaction that results in the formation of carbamoyl phosphate." [EC:6.3.4.16, EC:6.3.5.5, GOC:mah]
- [x] obsolete term - remove xrefs from def.

**Comment by sjm41** [comment]
@pgaudet 

Do you agree that grouping terms like the one below should have GOC:curators as the term xref (rather than the 2 ECs that are xrefs on the children terms)?

GO:0008875
gluconate dehydrogenase activity
def: "Catalysis of the reaction: D-gluconate + NADP+ = dehydro-D-gluconate + NADPH + H+." [EC:1.1.1.215, EC:1.1.1.69]

**Comment by pgaudet** [comment]
Hi @sjm41 

I agree, grouping terms that have no EC or RHEA equivalent should use def xref `GOC:curators`


Thanks, Pascale

**Comment by pgaudet** [comment]
GO:0045181
glutamate synthase activity, NAD(P)H as acceptor >> obsolete, unnecessary grouping class, no EC and no annotations. 
Parent is now [glutamate synthase activity](http://purl.obolibrary.org/obo/GO_0015930), which covers other acceptors as well.
