### ISSUE TITLE
EC:1.1.1.38 / EC:1.1.1.40 / EC:4.1.1.112

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28245]
Looking at these ECs (following on from #28243):

**EC:1.1.1.38 malate dehydrogenase (oxaloacetate-decarboxylating)**
(S)-malate + NAD(+) <=> CO2 + NADH + pyruvate
H(+) + oxaloacetate <=> CO2 + pyruvate

**EC 1.1.1.39 malate dehydrogenase (decarboxylating)**
(S)-malate + NAD(+) <=> CO2 + NADH + pyruvate

**EC:1.1.1.40 malate dehydrogenase (oxaloacetate-decarboxylating) (NADP(+))**
(S)-malate + NADP(+) <=> CO2 + NADPH + pyruvate
H(+) + oxaloacetate <=> CO2 + pyruvate

**EC:4.1.1.112 oxaloacetate decarboxylase**
H(+) + oxaloacetate <=> CO2 + pyruvate

They are term/def xrefs on the following 3 GO terms - I've suggested what needs to be done to make the relationships clearer. Let me know if you agree @pgaudet (this issue is on the #26235 list/spreadsheet, marked as 'to discuss') 

id: GO:0008948
name: oxaloacetate decarboxylase activity
def: "Catalysis of the reaction: oxaloacetate = pyruvate + CO2." [EC:1.1.1.38, EC:1.1.1.40, EC:4.1.1.112]
xref: EC:1.1.1.38
xref: EC:1.1.1.40
xref: EC:4.1.1.112
xref: RHEA:15641
- [x] xref: EC:1.1.1.38 -> make broadMatch
- [x] xref: EC:1.1.1.40 -> make broadMatch
- [x] xref: EC:4.1.1.112 -> make exactMatch
- [x] Replace def xref with RHEA:15641

id: GO:0004471
name: malate dehydrogenase (decarboxylating) (NAD+) activity
def: "Catalysis of the reaction: (S)-malate + NAD+ = pyruvate + CO2 + NADH + H+." [EC:1.1.1.38, EC:1.1.1.39]
xref: EC:1.1.1.38
xref: EC:1.1.1.39
xref: RHEA:12653
- [ ] xref: EC:1.1.1.38 -> make broadMatch
- [x] xref: EC:1.1.1.39 & xref: RHEA:12653 -> make exactMatch
- [x] Replace def xref with RHEA:12653

id: GO:0004473
name: malate dehydrogenase (decarboxylating) (NADP+) activity 
def: "Catalysis of the reaction: (S)-malate + NADP+ = pyruvate + CO2 + NADPH + H+." [EC:1.1.1.40]
xref: EC:1.1.1.40
xref: RHEA:18253
- [ ] xref: EC:1.1.1.40 -> make broadMatch

**Comment by pgaudet** [comment]
We should also look at [phosphoenolpyruvate carboxylase activity](http://purl.obolibrary.org/obo/GO_0008964) when lookin at this group. [phosphoenolpyruvate carboxylase activity](http://purl.obolibrary.org/obo/GO_0008964) seems to be under the wrong parent.

**Comment by rozaru** [comment]
Not sure about this but as the malate reaction is the predominante one could

 xref: EC:1.1.1.40 -> make ExactMatch

in 
> id: GO:0004473
> name: malate dehydrogenase (decarboxylating) (NADP+) activity
> def: "Catalysis of the reaction: (S)-malate + NADP+ = pyruvate + CO2 + NADPH + H+." [EC:1.1.1.40]
> xref: EC:1.1.1.40
> xref: RHEA:18253
> 
>  xref: EC:1.1.1.40 -> make broadMatch

and

xref: EC:1.1.1.38 -> make ExactMatch

in 
> id: GO:0004471
> name: malate dehydrogenase (decarboxylating) (NAD+) activity
> def: "Catalysis of the reaction: (S)-malate + NAD+ = pyruvate + CO2 + NADH + H+." [EC:1.1.1.38, EC:1.1.1.39]
> xref: EC:1.1.1.38
> xref: EC:1.1.1.39
> xref: RHEA:12653
> 
>  xref: EC:1.1.1.38 -> make broadMatch
>  xref: EC:1.1.1.39 & xref: RHEA:12653 -> make exactMatch
>  Replace def xref with RHEA:12653
