### ISSUE TITLE
Term merge: [term labels and ID] symbiont-mediated suppression of RIG-I terms may need a merge

### ISSUE THREAD

**Issue by genegodbold** [geneontology/go-ontology#28251]
* **Which term do you propose this term merge into? Provide GO ID and term label**
Hey @pgaudet 
* **Terms to be merged: Provide GO ID and term label**
**RIG-I terms**
GO:0039540 symbiont-mediated suppression of host cytoplasmic pattern recognition receptor signaling pathway via inhibition of RIG-I activity
GO:0141078 symbiont-mediated suppression of host RIG-I signaling pathway
GO:0039545 symbiont-mediated suppression of host cytoplasmic pattern recognition receptor signaling pathway via inhibition of MAVS activity
GO:0039554 symbiont-mediated suppression of host cytoplasmic pattern recognition receptor signaling pathway via inhibition of MDA-5 activity

_RIG-I is a member of the RIG-I like receptors (RLRs) that also includes Melanoma Differentiation-Associated protein 5 (MDA5) and Laboratory of genetics physiology 2 (LGP2) RIG-I and MDA5 are both involved in activating MAVS and triggering an antiviral response._

* **Reason for merge**
I think the annotations for GO:0141078 should be merged into GO:0039540

* **Reference(s)**
PMID:nnnnnn

* **Any other information**

**Comment by pgaudet** [comment]
Done here https://github.com/geneontology/go-ontology/issues/28234

Or are you asking something different?

**Comment by pgaudet** [comment]
@genegodbold confirmed that this is a duplicate.
