### ISSUE TITLE
Term merge: [term labels and ID] Merge GO:0039724 (symbiont-mediated suppression of host cytoplasmic pattern recognition receptor signaling pathway via inhibition of IKBKE activity)  into GO:0085034 (symbiont-mediated suppression of host NF-kappaB cascade)

### ISSUE THREAD

**Issue by genegodbold** [geneontology/go-ontology#28253]
* **Term to be merged: Provide GO ID and term label**
GO:0039724 (symbiont-mediated suppression of host cytoplasmic pattern recognition receptor signaling pathway via inhibition of IKBKE activity)

* **Which term do you propose this term merge into? Provide GO ID and term label**
GO:0085034 (symbiont-mediated suppression of host NF-kappaB cascade) AND its name should be changed to "symbiont-mediated suppression of host cytoplasmic pattern recognition receptor signaling pathway via suppression of host NF-kappaB cascade"--this should be a child of...
GO:0039537 (symbiont-mediated suppression of cytoplasmic pattern recognition receptor signaling pathway) 

* **Reason for merge**
The GO:0039724 term is TOO specific "A process in which a symbiont interferes with, inhibits or disrupts a cytoplasmic pattern recognition receptor signaling pathway by reducing the activity of host I-kappa-B kinase epsilon (IKBKE/IKK-epsilon/IKK-E)" and I can't see that it has any annotations. There are a LOT of things that a symbiont can do to suppress NFkappaB signaling and this term hits just a tiny fraction. A better term is
GO:0039723 (symbiont-mediated suppression of host cytoplasmic pattern recognition receptor signaling pathway via inhibition of TBK1 activity) This term at least names an entire component of the NFkappaB signaling pathway. In fact, GO:0039723 should be a child of the renovated GO:0085034 while GO:0039724 should simply be obsoleted/disappear.

* **Reference(s)**
PMID:nnnnnn

* **Any other information**
@pgaudet

**Comment by pgaudet** [comment]
This needs to be looked into more closely. ViralZone uses GO:0039724 symbiont-mediated suppression of host cytoplasmic pattern recognition receptor signaling pathway via inhibition of IKBKE activity for [Inhibition of host IKBKE by virus](https://viralzone.expasy.org/4478), which according to the ViralZone hierarchy is part of the MDA5/RIG-I pathway

<img width="313" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/6ff568fd-0937-461b-b2ad-05380398b4d7">


I am not sure this is the only pathway in which IKK participates; we need to check with VZ whether 'GO:0085034 (symbiont-mediated suppression of host NF-kappaB cascade)' would work to map VZ:4478

@pmasson55 

Thanks, Pascale

**Comment by pmasson55** [comment]
Hi Gene and Pascale,

It depends on GO policy. In Swiss-Prot we have Keyword - Inhibition of host IKBKE by virus (KW-1224) which is fine, we can thus target all the viral proteins targeting this protein. This term is assigned to 32 viral proteins in Swiss-Prot and 1566 in TREMBL so we will keep it like that.
To note; I think that IKKE is not part of the NK-kappa-B signaling cascade. It is induced by TRAFs and lead to the activtation of IRF3 or IRF7 according to the cell type. So it's more an antiviral signaling program rather than a NF-kappa-B cascade.

**Comment by genegodbold** [comment]
@pmasson55 is right--this is a niche term and not congruent with NF-kappaB; we've got a new term for TRAF inhibition (that happens *at* TRAF
