### ISSUE TITLE
NTR: peroxisomal-mitochondrial tether activity

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#28255]
Please provide as much information as you can: 

* **Suggested term label:**

peroxisomal-mitochondrial tether activity

* **Definition (free text)**

The binding activity of a molecule that brings together a peroxisomal and mitochondrial membrane either via membrane lipid binding or by interacting with a mitochondrial protein, to establish and facilitate organelle exchange, such as the transit of peroxisomal citrate into mitochondria

* **Reference, in format PMID:#######**

PMID: 29720625
PMID: 38669296

![Screenshot 2024-06-21 at 12 53 03 PM](https://github.com/geneontology/go-ontology/assets/12737663/6fb4c3b7-2ba9-48e5-9a7e-569f902d3d7a)

![Screenshot 2024-06-21 at 12 52 15 PM](https://github.com/geneontology/go-ontology/assets/12737663/eb86148f-8a82-4f44-b4c2-09855218e34d)

* **Gene product name and ID to be annotated to this term**

FZO1 and PEX34 (S. cerevisiae)

* **Parent term(s)**

GO:0043495 protein-membrane adaptor activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

PerMit contact activity (EXACT)

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by robnash** [comment]
Thanks Raymond :)

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160190
+name: peroxisome-mitochondrion membrane tether activity
+def: "The binding activity of a molecule that brings together the peroxisome and the mitochondrial outer membrane, establishing the localization of the peroxisome close to the mitochondrion." [PMID:29720625, PMID:38669296]
+is_a: GO:0043495 ! protein-membrane adaptor activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28255" xsd:anyURI
+created_by: rynl
+creation_date: 2024-06-24T22:53:31Z
