### ISSUE TITLE
GO:0014823 response to activity -> "response to physical activity"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28257]
If this term is required the label should be changed because it is misleading.

Here the activity referred to is "physical activity" not a molecular activity

210/286 annotations are IEP

(also GO:0014865 detection of activity)

**Comment by ValWood** [comment]
Also add GO:0032501  
multicellular organismal process
to give taxon restriction

**Comment by ValWood** [comment]
@pgaudet  do you agree with this?

The definition is 
Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of an activity stimulus.

but the related synonym
"response to exercise" implies this refers to physical activity?

GO:0014865   detection of activity
Is weird, but has not been used in annotation. I can obsolete that one?

**Comment by ValWood** [comment]
@pgaudet  do you agree?

**Comment by pgaudet** [comment]
I cannot make a decision on an obsoletion without looking at the intended usage for the term. I have no time to look at 200 annotations.

**Comment by ValWood** [comment]
It just seems strange to use the  term label "activity"  in a label when it doesn't refer to the GO concept of "activity" (i.e molecular activity)

I thought this one would be a simple term relabelling , I didn't think we would  need to check the annotations,  but I guess it is possible that some of the direct  annotations  to the activity terms are not related to physical activity.

<img width="477" alt="Screenshot 2024-07-12 at 16 34 35" src="https://github.com/user-attachments/assets/90addd6e-5fbf-4d83-b08a-e860fb14416a">

I can close this one....I only opened because I was confused by the term
