### ISSUE TITLE
GPI-anchor transamidase activity (GO:0003923) issues

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28258]
GPI8/PIG-K

GPI-anchor transamidase activity (GO:0003923)
Definition
Catalysis of the formation of the linkage between a protein and a glycosylphosphatidylinositol anchor. The reaction probably occurs by subjecting a peptide bond to nucleophilic attack by the amino group of ethanolamine-GPI, transferring the protein from a signal peptide to the GPI anchor.

"Catalysis of the formation of the linkage between a protein and a glycosylphosphatidylinositol anchor"
is describing a transferase activity, but this term  is a subclass of
 cysteine-type endopeptidase activity

In reality this enzyme appears to have  2 activities, i)  cleaving the signal peptide, and  ii) transferring the GPI anchor onto the protein

**Comment by deustp01** [comment]
> In reality this enzyme appears to have 2 activities, i) cleaving the signal peptide, and ii) transferring the GPI anchor onto the protein

I din't know any actual data here, but there is the textbook possibility that this is a transpeptidation in which the cleavage and transfer are accomplished in a single reaction.

**Comment by ValWood** [comment]
That appears  the case 
see figure 3
https://www.researchgate.net/publication/6446252_Thematic_review_series_Lipid_Posttranslational_Modifications_GPI_anchoring_of_protein_in_yeast_and_mammalian_cells_or_how_we_learned_to_stop_worrying_and_love_glycophospholipids/figures?lo=1

In this situation I guess we add the missing parent
GO:0008483  transaminase activity to the MF GO:0003923   GPI-anchor transamidase activity

and keep the cycteine-type endopeptidase.

**Comment by ValWood** [comment]
whoops that is  GO:0003923 **transaminase** activity we don't have " transamidase activity"

**Comment by ValWood** [comment]
another bit of weirdness.

This has an additional redundant parent in Protege?
"catalytic activity acting on a protein"

<img width="767" alt="Screenshot 2024-06-24 at 12 12 03" src="https://github.com/geneontology/go-ontology/assets/7359272/9fea32a1-7a5e-43bf-805a-2da3089fff91">
:
<img width="397" alt="Screenshot 2024-06-24 at 12 01 22" src="https://github.com/geneontology/go-ontology/assets/7359272/7e056882-34cf-47a7-94ea-3e35d51fd7e3">

Why is that?

**Comment by pgaudet** [comment]
> another bit of weirdness.
This has an additional redundant parent in Protege?
"catalytic activity acting on a protein"


What's wrong with this?

**Comment by ValWood** [comment]
I wasn't sure why it has the instantiated subclass of a parent term?
"catalytic activity, acting on a protein"
But it doesn't show in QuickGO as a relationship
