### ISSUE TITLE
NTR: peroxisomal-mitochondrial contact site

### ISSUE THREAD

**Issue by robnash** [geneontology/go-ontology#28254]
Please provide as much information as you can: 

* **Suggested term label:**
* 
peroxisomal-mitochondrial contact site

* **Definition (free text)**

A contact site between peroxisomal and mitochondrial membranes.

* **Reference, in format PMID:#######**

PMID: 29720625
PMID: 38669296

![Screenshot 2024-06-21 at 12 53 03 PM](https://github.com/geneontology/go-ontology/assets/12737663/fdb37dbc-2283-4194-9d8e-d0613bc7df24)

![Screenshot 2024-06-21 at 12 52 15 PM](https://github.com/geneontology/go-ontology/assets/12737663/376d9c14-bc9c-468a-94c3-77bf796dc963)

* **Gene product name and ID to be annotated to this term**

FZO1 and PEX34 (S. cerevisiae)

* **Parent term(s)**

GO:0044232 organelle membrane contact site

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

none

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

PerMit contact sites (EXACT)
PerMit contacts (EXACT)

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
[Term]
id: GO:0160189
name: peroxisomal-mitochondrial contact site
namespace: cellular_component
def: "An organelle membrane contact site between peroxisomal membrane and mitochondrial outer membrane." [PMID:29684109, PMID:38669296]
synonym: "PerMit contact" EXACT []
synonym: "PerMit contact site" EXACT []
intersection_of: GO:0044232 ! organelle membrane contact site
intersection_of: overlaps GO:0005741 ! mitochondrial outer membrane
intersection_of: overlaps GO:0005778 ! peroxisomal membrane
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28254" xsd:anyURI
created_by: rynl
creation_date: 2024-06-24T22:11:59Z

**Comment by robnash** [comment]
Thanks Raymond :)

**Comment by raymond91125** [comment]
Thank you!
