### ISSUE TITLE
Fix glucosidase parents

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28262]
Move under
GO:0090599    alpha-glucosidase activity 

- [x] GO:0033933    branched-dextran exo-1,2-alpha-glucosidase activity | is_a
- [x] GO:0043896    glucan 1,6-alpha-glucosidase activity | is_a
- [x] GO:0051118    glucan endo-1,3-alpha-glucosidase activity | is_a
- [x] GO:0004339    glucan 1,4-alpha-glucosidase activity

Move under
GO:0008422    beta-glucosidase activity | is_a

- [x] GO:0046557    glucan endo-1,6-beta-glucosidase activity | is_a
- [x] GO:0033913    glucan endo-1,2-beta-glucosidase activity | is_a
- [x] GO:0042973    glucan endo-1,3-beta-D-glucosidase activity | is_a

These I'm not sure which type they are:
GO:0047402    protein-glucosylgalactosylhydroxylysine glucosidase activity | is_a
GO:0050081    maltose-6'-phosphate glucosidase activity | is_a
GO:0047539    2-deoxyglucosidase activity | is_a
GO:0047917    GDP-glucosidase activity | is_a
GO:0004573    Glc3Man9GlcNAc2 oligosaccharide glucosidase activity | is_a

**Comment by pgaudet** [comment]
@sjm41 maybe you have also come across these

**Comment by ValWood** [comment]
I did the ones which were obvious from the labels or definitions, I'll close this but reoepen if you can classify any others
