### ISSUE TITLE
Bulk obsoletion of catalytic terms with UM-BBD mapping only, and no annotations

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28261]
The following are catalytic terms with only UM-BBD mapping (no EC/RHEA/MetaCyc/KEGG mapping) and have no annotations - see list here: https://docs.google.com/spreadsheets/d/18UFJV5IpOZJIcWyWMpWH8SkFUMfkfpKqVR-gTuoOh8s/edit

Note that the UM-BBD xref should be removed as both the term and def xref as part of this process.

We propose they are obsoleted in bulk. No need to send notifications for annotation review, since there are no annotations.

Please: 

- [ ] remove cross references
- [ ] Add comment "This term was obsoleted because there is no evidence that this specific reaction exists."

@pgaudet 

GOID | Term label
-- | --
GO:0004028 | 3-chloroallyl aldehyde dehydrogenase activity
GO:0009389 | dimethyl sulfoxide reductase activity
GO:0018547 | nitroglycerin reductase activity
GO:0008785 | alkyl hydroperoxide reductase activity
GO:0018641 | 6-hydroxy-3-methyl-2-oxo-1,2-dihydroquinoline 6-monooxygenase activity
GO:0018742 | epoxide hydrolase B activity
GO:0034824 | citronellyl-CoA dehydrogenase activity
GO:0034820 | 4,9-DSHA hydrolase activity
GO:0034556 | nitrobenzoate nitroreductase activity
GO:0034832 | geranial dehydrogenase activity
GO:0034930 | 1-hydroxypyrene sulfotransferase activity
GO:0018446 | pinocarveol dehydrogenase activity
GO:0018447 | chloral hydrate dehydrogenase activity
GO:0018448 | hydroxymethylmethylsilanediol oxidase activity
GO:0018450 | myrtenol dehydrogenase activity
GO:0018451 | epoxide dehydrogenase activity
GO:0018453 | 2-hydroxytetrahydrofuran dehydrogenase activity
GO:0018469 | myrtenal dehydrogenase activity
GO:0018470 | 4-hydroxybutaraldehyde dehydrogenase activity
GO:0018472 | 1-hydroxy-2-naphthaldehyde dehydrogenase activity
GO:0018473 | cis-2-methyl-5-isopropylhexa-2,5-dienal dehydrogenase activity
GO:0018475 | trans-2-methyl-5-isopropylhexa-2,5-dienal dehydrogenase activity
GO:0018486 | 2-butanone oxidase activity
GO:0018487 | vanillate O-demethylase (anaerobic) activity
GO:0018495 | 2-hydroxycyclohexane-1-carboxyl-CoA dehydrogenase activity
GO:0018496 | 2,6-dihydroxycyclohexane-1-carboxyl-CoA dehydrogenase activity
GO:0018497 | 1-chloro-2,2-bis(4-chlorophenyl)ethane dehydrogenase activity
GO:0018499 | cis-2,3-dihydrodiol DDT dehydrogenase activity
GO:0018500 | trans-9R,10R-dihydrodiolphenanthrene dehydrogenase activity
GO:0018501 | cis-chlorobenzene dihydrodiol dehydrogenase activity
GO:0018503 | trans-1,2-dihydrodiolphenanthrene dehydrogenase activity
GO:0018508 | cis-1,2-dihydroxycyclohexa-3,5-diene-1-carboxylate dehydrogenase activity
GO:0018526 | 2-aminobenzoyl-CoA reductase activity
GO:0018528 | iminodiacetate dehydrogenase activity
GO:0018550 | tetrachloro-p-hydroquinone reductive dehalogenase activity
GO:0018553 | 3-(2,3-dihydroxyphenyl)propionate 1,2-dioxygenase activity
GO:0018585 | fluorene oxygenase activity
GO:0018586 | mono-butyltin dioxygenase activity
GO:0018588 | tri-n-butyltin dioxygenase activity
GO:0018589 | di-n-butyltin dioxygenase activity
GO:0018590 | methylsilanetriol hydroxylase activity
GO:0018593 | 4-chlorophenoxyacetate monooxygenase activity
GO:0018596 | dimethylsilanediol hydroxylase activity
GO:0018598 | hydroxymethylsilanetriol oxidase activity
GO:0018599 | 2-hydroxyisobutyrate 3-monooxygenase activity
GO:0018686 | 6-hydroxy pseudo-oxynicotine monooxygenase activity
GO:0018688 | DDT 2,3-dioxygenase activity
GO:0018689 | naphthalene disulfonate 1,2-dioxygenase activity
GO:0018703 | 2,4-dichlorophenoxyacetate dehalogenase activity
GO:0018705 | 1,2-dichloroethene reductive dehalogenase activity
GO:0018707 | 1-phenanthrol methyltransferase activity
GO:0018715 | 9-phenanthrol UDP-glucuronosyltransferase activity
GO:0018716 | 1-phenanthrol glycosyltransferase activity
GO:0018717 | 9-phenanthrol glycosyltransferase activity
GO:0018718 | 1,2-dihydroxy-phenanthrene glycosyltransferase activity
GO:0018721 | trans-9R,10R-dihydrodiolphenanthrene sulfotransferase activity
GO:0018722 | 1-phenanthrol sulfotransferase activity
GO:0018723 | 3-phenanthrol sulfotransferase activity
GO:0018724 | 4-phenanthrol sulfotransferase activity
GO:0018725 | trans-3,4-dihydrodiolphenanthrene sulfotransferase activity
GO:0018726 | 9-phenanthrol sulfotransferase activity
GO:0018727 | 2-phenanthrol sulfotransferase activity
GO:0018731 | 1-oxa-2-oxocycloheptane lactonase activity
GO:0018734 | butyrolactone hydrolase activity
GO:0018736 | 6-oxo-2-hydroxycyclohexane-1-carboxyl-CoA hydrolase activity
GO:0018737 | 2-ketocyclohexane-1-carboxyl-CoA hydrolase activity
GO:0018743 | phenanthrene-9,10-epoxide hydrolase (9R,10R-forming) activity
GO:0018745 | epoxide hydrolase A activity
GO:0018746 | phenanthrene-3,4-epoxide hydrolase activity
GO:0018747 | phenanthrene-1,2-epoxide hydrolase activity
GO:0018748 | iprodione amidohydrolase activity
GO:0018749 | (3,5-dichlorophenylurea)acetate amidohydrolase activity
GO:0018751 | 3,5-dichlorophenylcarboximide hydrolase activity
GO:0018758 | 2,4-dihydroxy-6-(N'-ethyl)amino-1,3,5-triazine aminohydrolase activity
GO:0018767 | 2-hydroxy-6-oxo-7-methylocta-2,4-dienoate hydrolase activity
GO:0018769 | 2-hydroxy-6-oxoocta-2,4-dienoate hydrolase activity
GO:0018770 | 6-oxo-2-hydroxy-7-(4'-chlorophenyl)-3,8,8-trichloroocta-2E,4E,7-trienoate hydrolase activity
GO:0018776 | trans-chloroacrylic acid dehalogenase activity
GO:0018780 | dichloroacetate halidohydrolase activity
GO:0018781 | S-triazine hydrolase activity
GO:0018782 | cis-chloroacrylic acid dehalogenase activity
GO:0018791 | 2-hydroxy-3-carboxy-6-oxo-7-methylocta-2,4-dienoate decarboxylase activity
GO:0018792 | bis(4-chlorophenyl)acetate decarboxylase activity
GO:0018793 | 3,5-dibromo-4-hydroxybenzoate decarboxylase activity
GO:0018794 | 2-hydroxyisobutyrate decarboxylase activity
GO:0018795 | 2-hydroxy-2-methyl-1,3-dicarbonate decarboxylase activity
GO:0018802 | 2,4-dihydroxyhept-2-ene-1,7-dioate aldolase activity
GO:0018808 | trans-4-(1'-hydroxynaphth-2'-yl)-2-oxobut-3-enoate hydratase-aldolase activity
GO:0018809 | E-phenylitaconyl-CoA hydratase activity
GO:0018810 | trans-4-[2-(3-hydroxy)-thionaphthenyl]-2-oxo-3-butenoate hydratase activity
GO:0018816 | 2-hydroxyisobutyrate dehydratase activity
GO:0018825 | triethanolamine lyase activity
GO:0018828 | halohydrin hydrogen-halide-lyase A activity
GO:0018832 | halohydrin hydrogen-halide-lyase B activity
GO:0018837 | 2-hydroxy-2H-benzo[h]chromene-2-carboxylate isomerase activity
GO:0018854 | 3-isopropenyl-6-oxoheptanoyl-CoA synthetase activity
GO:0018857 | 2,4-dichlorobenzoate-CoA ligase activity
GO:0018863 | phenanthrene-9,10-epoxide hydrolase (9S,10S-forming) activity
GO:0034522 | cis-1,2-dihydroxy-1,2-dihydro-8-carboxynaphthalene dehydrogenase activity
GO:0034523 | 3-formylsalicylate oxidase activity
GO:0034524 | 2-hydroxyisophthalate decarboxylase activity
GO:0034525 | 1-naphthaldehyde dehydrogenase activity
GO:0034527 | 1,2-dihydroxy-8-carboxynaphthalene dioxygenase activity
GO:0034529 | 2-hydroxy-3-carboxy-benzalpyruvate hydratase-aldolase activity
GO:0034531 | 2-hydroxy-4-hydroxymethylbenzalpyruvate hydratase-aldolase activity
GO:0034533 | 1,2-dihydroxy-7-hydroxymethylnaphthalene dioxygenase activity
GO:0034535 | 1,2-dihydroxy-8-methylnaphthalene dioxygenase activity
GO:0034537 | 2-hydroxy-3-methylbenzalpyruvate hydratase-aldolase activity
GO:0034538 | 3-methylsalicylaldehyde dehydrogenase activity
GO:0034541 | dimethylarsinite methyltransferase activity
GO:0034558 | technetium (VII) reductase activity
GO:0034559 | bisphenol A hydroxylase B activity
GO:0034561 | 1,2-bis(4-hydroxyphenyl)-2-proponol dehydratase activity
GO:0034562 | 2,2-bis(4-hydroxyphenyl)-1-propanol hydroxylase activity
GO:0034563 | 2,3-bis(4-hydroxyphenyl)-1,2-propanediol dioxygenase activity
GO:0034564 | 4,4'-dihydroxy-alpha-methylstilbene dioxygenase activity
GO:0034571 | 4'-(2-hydroxyisopropyl)phenylurea amidohydrolase activity
GO:0034573 | didemethylisoproturon amidohydrolase activity
GO:0034576 | N-isopropylacetanilide amidohydrolase activity
GO:0034578 | limonene 8-hydratase activity
GO:0034579 | (1-methylpentyl)succinate synthase activity
GO:0034581 | 4-methyloct-2-enoyl-CoA hydratase activity
GO:0034582 | 3-hydroxy-4-methyloctanoyl-CoA dehydrogenase activity
GO:0034778 | 2-hydroxy-4-isopropenylcyclohexane-1-carboxyl-CoA dehydrogenase activity
GO:0034779 | 4-isopropenyl-2-ketocyclohexane-1-carboxyl-CoA hydrolase activity
GO:0034780 | glyphosate dehydrogenase activity
GO:0034781 | N-cyclohexylformamide amidohydrolase activity
GO:0034782 | dimethylmalonate decarboxylase activity
GO:0034783 | pivalate-CoA ligase activity
GO:0034786 | 9-fluorenone-3,4-dioxygenase activity
GO:0034787 | 1-hydro-1,1a-dihydroxy-9-fluorenone dehydrogenase activity
GO:0034788 | 2,3-dihydroxy-2'-carboxybiphenyl 1,2-dioxygenase activity
GO:0034789 | 2-hydroxy-6-oxo-6-(2-carboxyphenyl)-hexa-2,4-dienoate hydrolase activity
GO:0034790 | 3,4-dihydroxy-3,4-dihydrofluorene dehydrogenase activity
GO:0034792 | hypophosphite dioxygenase activity
GO:0034793 | cyclopropanecarboxylate-CoA ligase activity
GO:0034796 | adipate-CoA ligase activity
GO:0034797 | fosfomycin 2-glutathione ligase activity
GO:0034798 | fosfomycin 2-L-cysteine ligase activity
GO:0034799 | dihydride TNP tautomerase activity
GO:0034801 | 2,4-dinitrocyclohexanone hydrolase activity
GO:0034804 | benzo(a)pyrene 11,12-epoxidase activity
GO:0034805 | benzo(a)pyrene-trans-11,12-dihydrodiol dehydrogenase activity
GO:0034807 | 4,5-dihydroxybenzo(a)pyrene methyltransferase activity
GO:0034809 | benzo(a)pyrene-cis-4,5-dihydrodiol dehydrogenase activity
GO:0034816 | anthracene 9,10-dioxygenase activity
GO:0034817 | cis-9,10-dihydroanthracene-9,10-diol dehydrogenase activity
GO:0034821 | citronellol dehydrogenase activity
GO:0034822 | citronellal dehydrogenase activity
GO:0034826 | 1,2-dihydroxy-1,2,5,6,7,8-hexyhadronaphthalene dehydrogenase activity
GO:0034828 | 4-(2-oxocyclohexyl)-2-hydroxy-buta-2,4-dienoate hydrolase activity
GO:0034829 | 2-hydroxydec-2,4-diene-1,10-dioate hydratase activity
GO:0034831 | (R)-(-)-1,2,3,4-tetrahydronaphthol dehydrogenase activity
GO:0034833 | geranylate CoA-transferase activity
GO:0034837 | 2-mercaptobenzothiazole-cis-6,7-dihydrodiol dehydrogenase activity
GO:0034838 | menthone dehydrogenase activity
GO:0034839 | menth-2-enone hydratase activity
GO:0034840 | 3-hydroxymenthone dehydrogenase activity
GO:0034841 | mentha-1,3-dione-CoA ligase activity
GO:0034842 | thiophene-2-carboxylate-CoA ligase activity
GO:0034843 | 2-oxoglutaryl-CoA thioesterase activity
GO:0034844 | naphthyl-2-methyl-succinate CoA-transferase activity
GO:0034846 | naphthyl-2-methylene-succinyl-CoA lyase activity
GO:0034847 | naphthyl-2-hydroxymethyl-succinyl-CoA dehydrogenase activity
GO:0034848 | naphthyl-2-oxomethyl-succinyl-CoA succinyl transferase activity
GO:0034849 | 2-naphthoate CoA-transferase activity
GO:0034851 | 2,4,4-trimethyl-3-oxopentanoyl-CoA 2-C-propanoyl transferase activity
GO:0034852 | 4,4-dimethyl-3-oxopentanal dehydrogenase activity
GO:0034853 | 2,4,4-trimethyl-3-oxopentanoate decarboxylase activity
GO:0034854 | 4,4-dimethyl-3-oxopentanoate decarboxylase activity
GO:0034857 | 2-(methylthio)benzothiazole monooxygenase activity
GO:0034858 | 2-hydroxybenzothiazole monooxygenase activity
GO:0034859 | benzothiazole monooxygenase activity
GO:0034862 | 2,6-dihydroxybenzothiazole monooxygenase activity
GO:0034863 | 2,4,4-trimethyl-1-pentanol dehydrogenase activity
GO:0034864 | 2,4,4-trimethylpentanal dehydrogenase activity
GO:0034865 | 2,4,4-trimethylpentanoate-CoA ligase activity
GO:0034866 | 2,4,4-trimethylpentanoyl-CoA dehydrogenase activity
GO:0034867 | 2,4,4-trimethylpent-2-enoyl-CoA hydratase activity
GO:0034868 | 2,4,4-trimethyl-3-hydroxypentanoyl-CoA dehydrogenase activity
GO:0034869 | 2,4,4-trimethyl-3-oxopentanoyl-CoA thioesterase activity
GO:0034870 | pinacolone 5-monooxygenase activity
GO:0034871 | 1-hydroxy-4,4-dimethylpentan-3-one dehydrogenase activity
GO:0034873 | thioacetamide S-oxygenase activity
GO:0034874 | thioacetamide S-oxide S-oxygenase activity
GO:0034876 | isonicotinic acid hydrazide hydrolase activity
GO:0034877 | isonicotinate dehydrogenase activity
GO:0034878 | 2-hydroxyisonicotinate dehydrogenase activity
GO:0034879 | 2,3,6-trihydroxyisonicotinate decarboxylase activity
GO:0034880 | citrazinate dehydrogenase activity
GO:0034881 | citrazinate hydrolase activity
GO:0034882 | cis-aconitamide amidase activity
GO:0034885 | gamma-N-formylaminovinylacetate hydrolase activity
GO:0034888 | endosulfan monooxygenase I activity
GO:0034889 | endosulfan hemisulfate sulfatase activity
GO:0034890 | endosulfan diol hydrolyase (cyclizing) activity
GO:0034891 | endosulfan diol dehydrogenase activity
GO:0034892 | endosulfan lactone lactonase activity
GO:0034893 | N-nitrodimethylamine hydroxylase activity
GO:0034897 | 4-(1-ethyl-1,4-dimethyl-pentyl)phenol monooxygenase activity
GO:0034901 | endosulfan hydroxyether dehydrogenase activity
GO:0034902 | endosulfan sulfate hydrolase activity
GO:0034903 | endosulfan ether monooxygenase activity
GO:0034904 | 5-chloro-2-oxopent-4-enoate hydratase activity
GO:0034910 | 6-hydroxy-3-succinoylpyridine hydrolase activity
GO:0034917 | 2-methylhex-2-enoyl-CoA hydratase activity
GO:0034918 | 3-hydroxy-2-methylhexanoyl-CoA dehydrogenase activity
GO:0034919 | butyryl-CoA 2-C-propionyltransferase activity
GO:0034921 | cis-4,5-dihydroxy-4,5-dihydropyrene dehydrogenase activity
GO:0034923 | phenanthrene-4,5-dicarboxylate decarboxylase activity
GO:0034924 | cis-3,4-phenanthrenedihydrodiol-4-carboxylate dehydrogenase activity
GO:0034925 | pyrene 4,5-monooxygenase activity
GO:0034926 | pyrene-4,5-epoxide hydrolase activity
GO:0034927 | pyrene 1,2-monooxygenase activity
GO:0034928 | 1-hydroxypyrene 6,7-monooxygenase activity
GO:0034929 | 1-hydroxypyrene 7,8-monooxygenase activity
GO:0034931 | 1-hydroxypyrene methyltransferase activity
GO:0034932 | 1-methoxypyrene 6,7-monooxygenase activity
GO:0034933 | 1-hydroxy-6-methoxypyrene methyltransferase activity
GO:0034939 | 5-hydroxypyrrole-2-carboxylate tautomerase activity
GO:0034940 | 5-oxo-4,5-dihydropyrrole-2-carboxylate amidase activity
GO:0034942 | cis-2-methyl-5-isopropylhexa-2,5-dienoate-CoA ligase activity
GO:0034943 | trans-2-methyl-5-isopropylhexa-2,5-dienoate-CoA ligase activity
GO:0034944 | 3-hydroxy-2,6-dimethyl-5-methylene-heptanoyl-CoA dehydrogenase activity
GO:0034946 | 3-isopropylbut-3-enoyl-CoA thioesterase activity
GO:0034947 | terephthalate decarboxylase activity
GO:0034950 | phenylboronic acid monooxygenase activity
GO:0034952 | malonate semialdehyde decarboxylase activity
GO:0034953 | perillyl-CoA hydratase activity
GO:0034957 | 3-nitrophenol nitroreductase activity

**Comment by pgaudet** [comment]
In fact some of these terms had annotations. 

Unobsoleted the following terms until we can sort out whether we want to keep them or not: 

- [ ] GO:0004028 3-chloroallyl aldehyde dehydrogenase activity
- [ ] GO:0008785 alkyl hydroperoxide reductase activity
- [ ] GO:0009389 dimethyl sulfoxide reductase activity
- [ ] GO:0034824 citronellyl-CoA dehydrogenase activity
- [ ] GO:0034832 geranial dehydrogenase activity


Thanks
