### ISSUE TITLE
Replace Xref ec with 4.2.3.75 for GO term GO:0052577

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#28268]
For GO:0052577 germacrene-D synthase activity, the current EC number needs to be replaced with ec 4.2.3.75. All the other X-ref are correct.

**Comment by sjm41** [comment]
I changed the term and def xref to 4.2.3.75 (exactMatch).
But I kept EC:4.2.3.22 as a broadMatch term xref because that EC entry says "Also catalyzes the reaction of EC 4.2.3.75"
