### ISSUE TITLE
Textual definition update:  GO:0160183

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#28285]
* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request a definition update**

GO:0160183 autophagosome-membrane adaptor activity

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**

The binding activity of a molecule that brings together a target membrane and an autophagosome during AUTOPHAGY. 
(currently mitophagy)

**Comment by raymond91125** [comment]
Oops. Thanks.
