### ISSUE TITLE
Consider obsoletion of GO:0071633 dihydroceramidase activity and GO:0070774 phytoceramidase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28294]
- GO:0071633 dihydroceramidase activity
- GO:0070774 phytoceramidase activity
17 EXP 

11  UniProt
3  SGD
2   BHF-UCL
1  TAIR

Seem to represent specific substrates of GO:0017040 N-acylsphingosine amidohydrolase activity. RHEA has many specific forms of https://www.rhea-db.org/rhea/20856

- [RHEA:58484](https://www.rhea-db.org/rhea/58484)
H2O + N-(acetyl)-sphing-4-enine = acetate + sphing-4-enine
- [RHEA:45356](https://www.rhea-db.org/rhea/45356)
H2O + N-(11Z-eicosenoyl)-sphing-4-enine = (11Z)-eicosenoate + sphing-4-enine
- [RHEA:45348](https://www.rhea-db.org/rhea/45348)
H2O + N-(5Z,8Z,11Z,14Z-eicosatetraenoyl)-sphing-4-enine = (5Z,8Z,11Z,14Z)-eicosatetraenoate + sphing-4-enine
- [RHEA:45092](https://www.rhea-db.org/rhea/45092)
H2O + N-octanoylsphing-4-enine = octanoate + sphing-4-enine
- [RHEA:41299](https://www.rhea-db.org/rhea/41299)
H2O + N-(9Z-octadecenoyl)-sphing-4-enine = (9Z)-octadecenoate + sphing-4-enine
- [RHEA:41295](https://www.rhea-db.org/rhea/41295)
H2O + N-(hexanoyl)sphing-4-enine = hexanoate + sphing-4-enine
- [RHEA:41291](https://www.rhea-db.org/rhea/41291)
H2O + N-dodecanoylsphing-4-enine = dodecanoate + sphing-4-enine
- [RHEA:41287](https://www.rhea-db.org/rhea/41287)
H2O + N-tetradecanoylsphing-4-enine = sphing-4-enine + tetradecanoate
- [RHEA:41283](https://www.rhea-db.org/rhea/41283)
H2O + N-tetracosanoyl-sphing-4-enine = sphing-4-enine + tetracosanoate
- [RHEA:41279](https://www.rhea-db.org/rhea/41279)
H2O + N-octadecanoylsphing-4-enine = octadecanoate + sphing-4-enine
- [RHEA:41275](https://www.rhea-db.org/rhea/41275)
H2O + N-eicosanoyl-sphing-4-enine = eicosanoate + sphing-4-enine
- [RHEA:41267](https://www.rhea-db.org/rhea/41267)
H2O + N-(15Z-tetracosenoyl)-sphing-4-enine = (15Z)-tetracosenoate + sphing-4-enine
- [RHEA:38891](https://www.rhea-db.org/rhea/38891)
H2O + N-hexadecanoylsphing-4-enine = hexadecanoate + sphing-4-enine

These dont seem to be within the scope of GO. 

@sjm41 what do you think?

**Comment by sjm41** [comment]
>These don't seem to be within the scope of GO.
@sjm41 what do you think?

Yes, I think that's right..

I see that PMID:10900202 (def xref on GO:0071633) says:
Phytoceramide, an equivalent of the mammalian ceramide, serves as a building block of yeast complex sphingolipids. It is synthesized de novo from a fatty acyl-CoA and phytosphingosine by (a CoA-dependent) ceramide synthase. Phytosphingosine is generated from dihydrosphingosine through hydroxylation by the action of dihydrosphingosine hy- droxylase (5, 6). Dihydrosphingosine is also acylated by a fatty acyl-CoA to generate dihydroceramide through the action of ceramide synthase. Phytoceramide (or dihydroceramide) accepts an inositol-phosphoryl group to yield inositol phosphoryl-ceramide (IPC).
