### ISSUE TITLE
4-hydroxy-2-oxoglutarate aldolase activity terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28306]
There are currently these 2 terms in GO:

id: GO:0008700 (4 EXP annotations)
name: 4-hydroxy-2-oxoglutarate aldolase activity
namespace: molecular_function
def: "Catalysis of the reaction: 4-hydroxy-2-oxoglutarate = pyruvate + glyoxylate." [EC:4.1.3.16]
xref: EC:4.1.3.16
xref: MetaCyc:4OH2OXOGLUTARALDOL-RXN
xref: RHEA:18169
is_a: GO:0016832 ! aldehyde-lyase activity
is_a: GO:0016833 ! oxo-acid-lyase activity

id: GO:0106009 (1 EXP annotation)
name: (4S)-4-hydroxy-2-oxoglutarate aldolase activity
namespace: molecular_function
def: "Catalysis of the reaction:(4S)-4-hydroxy-2-oxoglutarate = pyruvate + glyoxylate." [EC:4.1.3.42, GOC:hjd, PMID:1098660, PMID:1339418]
xref: EC:4.1.3.42
xref: RHEA:35639
is_a: GO:0016833 ! oxo-acid-lyase activity

The related ECs/RHEAs are:

**EC 4.1.3.16**
(4R)-4-hydroxy-2-oxoglutarate <=> glyoxylate + pyruvate
(4S)-4-hydroxy-2-oxoglutarate <=> glyoxylate + pyruvate

**EC 4.1.3.42**
(4S)-4-hydroxy-2-oxoglutarate <=> glyoxylate + pyruvate

**RHEA:18169**
4-hydroxy-2-oxoglutarate = glyoxylate + pyruvate
(no EC mapping)

**RHEA:35639 (2,209 proteins at UP)**
(4S)-4-hydroxy-2-oxoglutarate = glyoxylate + pyruvate
(mapped to EC:4.1.3.16 and EC:4.1.3.42)

**RHEA:30687 (2,209 proteins at UP)**
(4R)-4-hydroxy-2-oxoglutarate = glyoxylate + pyruvate
(mapped to EC:4.1.3.16)

I think we should do the following:
- [ ] merge GO:0106009 into GO:0008700
- [x] remove GO:0016832 ! aldehyde-lyase activity (= EC:4.1.2.-) parent on GO:0008700
- [x] Add to the GO:0008700 def: "Can act on the (4R) on the (4S) enantiomers of 4-hydroxy-2-oxoglutarate."
- [x] Make EC:4.1.3.16 and RHEA:18169 exactMatch xrefs on GO:0008700
- [x] Make EC:4.1.3.42, MetaCyc:4OH2OXOGLUTARALDOL-RXN, RHEA:35639 and RHEA:30687 narrowMatch xrefs on GO:0008700

Note:
GO:0106009 (4S)-4-hydroxy-2-oxoglutarate aldolase activity (matching EC:4.1.3.42) was previously requested by EcoCyc in https://github.com/geneontology/go-ontology/issues/13392, but we are currently aiming not to have enantiomer-specific terms unless they are essential.

**Comment by sjm41** [comment]
@pgaudet I've done most of the easy stuff here.  Still need to do the merge, and then add RHEA:35639 as a narrowMatch xref to GO:0008700 (I wasn't able to do that since it's still on GO:0106009)

**Comment by pgaudet** [comment]
In this case the stereospecificity seems important, at least in E. coli  - see https://pubmed.ncbi.nlm.nih.gov/4560498/

<img width="367" alt="image" src="https://github.com/geneontology/go-ontology/assets/4782928/980c6b9c-62e7-41b9-92cc-26cebd0eb12a">


and it's also mentioned in https://europepmc.org/article/MED/17981470 (although RHEA has annotated both reactions) 

@kaxelsen can you please have a look and let us know whether the S-specific form is the physiologically relevant form? 

Thanks, Pascale

**Comment by kaxelsen** [comment]
The E. coli enzyme is the defining entry for EC 4.1.3.42. I have requested an update of the Swiss-Prot entry for a long time.
In other species there is no preference for enantiomer, thus the entry EC 4.1.3.16.

I have also answered the question about this in the 'Queries about RHEA mappings' table.

**Comment by pgaudet** [comment]
Thanks @kaxelsen !

**Comment by pgaudet** [comment]
Given @kaxelsen 's answer: 

- [ ]  changed label GO:0008700 4-hydroxy-2-oxoglutarate aldolase activity to (R,S)-4-hydroxy-2-oxoglutarate aldolase activity
- [ ]  Change crossref type GO:0008700 for EC:4.1.3.42 and RHEA:30687 to exactMatch
- [ ] GO:0106009 (4S)-4-hydroxy-2-oxoglutarate aldolase activity: added to the definition: "Specific for the (4S) enantiomer of 4-hydroxy-2-oxoglutarate."

**Comment by sjm41** [comment]
@pgaudet - if you agree, I can do the 2 remaining tasks here myself.
