### ISSUE TITLE
Merge endo-1,3(4)-beta-glucanase activity (EC:3.2.1.6) terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28308]
The two terms below have the same EC and MetaCyc xrefs and should be merged.
Merged name = endo-1,3(4)-beta-glucanase activity
Merged def = Catalysis of the endohydrolysis of (1->3)- or (1->4)-linkages in beta-D-glucans when the glucose residue whose reducing group is involved in the linkage to be hydrolyzed is itself substituted at C-3.

There is no RHEA associated with EC:3.2.1.6

Note that this reverts a previous request to split EC:3.2.1.6 into two GO terms - see https://github.com/geneontology/go-ontology/issues/4994 - and thus effectively re-instate "GO:0033903 obsolete endo-1,3(4)-beta-glucanase activity"

id: GO:0052861 (2 EXP annotations to AFUA_2G14360 (AspGD) and At1g64760 (TAIR)
name: glucan endo-1,3-beta-glucanase activity, C-3 substituted reducing group
namespace: molecular_function
def: "Catalysis of the endohydrolysis of (1->3)-linkages in beta-D-glucans when the glucose residue whose reducing group is involved in the linkage to be hydrolysed is itself substituted at C-3." [EC:3.2.1.6]
synonym: "1,3-(1,3)-beta-D-glucan 3-glucanohydrolase activity" RELATED [EC:3.2.1.6]
synonym: "laminaranase activity" RELATED [EC:3.2.1.6]
synonym: "laminarinase activity" RELATED [EC:3.2.1.6]
xref: EC:3.2.1.6
xref: MetaCyc:3.2.1.6-RXN
is_a: GO:0052736 ! beta-glucanase activity
created_by: ai
creation_date: 2011-12-06T04:49:36Z

id: GO:0052862 (0 EXP annotations)
name: glucan endo-1,4-beta-glucanase activity, C-3 substituted reducing group
namespace: molecular_function
def: "Catalysis of the endohydrolysis of (1->4)-linkages in beta-D-glucans when the glucose residue whose reducing group is involved in the linkage to be hydrolysed is itself substituted at C-3." [EC:3.2.1.6]
synonym: "1,3-(1,4)-beta-D-glucan 4-glucanohydrolase activity" RELATED [EC:3.2.1.6]
synonym: "laminaranase activity" RELATED [EC:3.2.1.6]
synonym: "laminarinase activity" RELATED [EC:3.2.1.6]
xref: EC:3.2.1.6
xref: MetaCyc:3.2.1.6-RXN
is_a: GO:0052736 ! beta-glucanase activity
created_by: ai
creation_date: 2011-12-06T05:27:26Z

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0052862 glucan endo-1,4-beta-glucanase activity, C-3 substituted reducing group: replace by GO:0052861 endo-1,3(4)-beta-glucanase activity because the enzyme is not specific for either substrate.
There are no annotations to that term. Both terms were mapped to the same EC, EC:3.2.1.6

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/28308

Thanks, Pascale
