### ISSUE TITLE
Remove the  Parentage  "GO:0032993   protein-DNA complex from chromatin and kinetochore

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28301]
Could we remove the  Parentage  "GO:0032993   protein-DNA complex

From kinetochore and chromatin
otherwise we can't make "occurs_in" annotations to them In Noctua

https://github.com/geneontology/noctua/issues/899#issuecomment-2189138801

**Comment by pgaudet** [comment]
This changes all allowed relations in tbe files people provide. Are these
REALLY cellular components? This causes a lot of issues, we cannot swap
back and forth easily.  We also need to coordinate with Alex.

**Comment by ValWood** [comment]
I don't think of chromatin as A protein complex, it's multiple complexes? How would we define its scope as a complex? it's isn't stochiometric?

I think we do want to use these as "cellular components". 
The Spindle pole body/centrosome, and the kinetochore are major signalling hubs. Many processes occur there....

For example
Septation initiation signalling/ mitotic entry/ mitotic exit (spindle pole body/centrosome)
https://pubmed.ncbi.nlm.nih.gov/38670849/

mitotic spindle checkpoint/ meiotic cohesion protection (kinetochore)

I'm not following how it changes the allowed relationships? 

CC @vanaukenk

**Comment by ValWood** [comment]
Can we discuss this one on an editors call?

**Comment by pgaudet** [comment]
> I'm not following how it changes the allowed relationships?

Annotations to  [protein-containing complex](http://purl.obolibrary.org/obo/GO_0032991) & children use 'part of' 
Annotations to [cellular anatomical entity](http://purl.obolibrary.org/obo/GO_0110165) & children use 'occurs in'

So, when we make these changes we need to notify GOA and Noctua developers, so that they map annotations to the correct relation. This is not difficult, it just needs some coordination.

**Comment by ValWood** [comment]
I don't understand which annotations need to be fixed.

**Comment by pgaudet** [comment]
The relations need to be fixed as I described above https://github.com/geneontology/go-ontology/issues/28301#issuecomment-2217159599

**Comment by pgaudet** [comment]
@ValWood Kinetochore is not a complex; you shoudl have been able to use 'occurs_in' with kinetochore

<img width="403" alt="image" src="https://github.com/user-attachments/assets/7d4d92af-c762-4720-a099-e37c0cdb5379">

**Comment by ValWood** [comment]
> [d](https://github.com/ValWood) Kinetochore is not a complex; you shoudl have been able to use 'occurs_in' with kinetochore

I can. Not sure what the issue was with kinetochore...

**Comment by cmungall** [comment]
I agree with @ValWood: "I don't think of chromatin as a protein complex, it's multiple complexes"
