### ISSUE TITLE
dolichol-linked oligosaccharide biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28319]
dolichol-linked oligosaccharide biosynthetic process
The chemical reactions and pathways resulting in the formation of dolichol-linked oligosaccharide, usually by a stepwise addition of glycosyl chains to endoplasmic reticulum membrane-bound dolichol-P.

In this pathway dolichol is a lipid,  but the dolichol-linked oligosaccharide refers to the combination of an oligosaccharide attached to the lipid carrier dolichol. The oligosaccharide is temporarily associated with the dolichol lipid during its synthesis and transfer to proteins. So overall the dolichol isn't metabolized...

Shouldn't this really be "GO:0019348  (https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0019348/complete)
dolichol metabolic process"

It gets classified as lipid metabolic process, but it seems wrong?

(not sure about this one)
@pgaudet @deustp01

**Comment by deustp01** [comment]
> It gets classified as lipid metabolic process, but it seems wrong?

This looks like the usual trap that if a chemical entity is a part_of a larger chemical entity (as adenine is a part of coenzyme A) then the part inherits metabolism terms assigned to the larger entity. I think that in previous discussions people may have identified a workaround to escape this inheritance but I can't remember anything more.

**Comment by ValWood** [comment]
I removed 
"dolichol metabolic process" from the parentage.
I also removed "lipid metabolic process" from the parent term
oligosaccharide-lipid intermediate biosynthetic process
(although I don't see why we need this term - it's got a single child).
I will put this on  the list of terms I am noticing that could be obsoleted so I don't forget.

**Comment by pgaudet** [comment]
I agree we should obsolete oligosaccharide-lipid intermediate biosynthetic process
