### ISSUE TITLE
dextransucrase activity (GO:0047849) etc

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28313]
EC:2.4.1.5 (dextransucrase) catalyses:
[(1->6)-alpha-D-glucosyl](n) + sucrose <=> [(1->6)-alpha-D-glucosyl](n+1) + D-fructose

There are 10 annotations to this EC in SwissProt.
It maps to RHEA:18825 (which is annotated to 653 proteins in UP)
Also maps to MetaCyc:2.4.1.125-RXN

So, the corresponding GO entry for EC:2.4.1.5 looks good:
id: GO:0047849 (1 EXP annotation)
name: dextransucrase activity
def: "Catalysis of the reaction: sucrose + 1,6-alpha-D-glucosyl(n) = D-fructose + 1,6-alpha-D-glucosyl(n+1)." [EC:2.4.1.5, MetaCyc:DEXTRANSUCRASE-RXN]
xref: EC:2.4.1.5
xref: MetaCyc:2.4.1.125-RXN
is_a: GO:0016758 ! hexosyltransferase activity

Only task here is:
- [x] add RHEA:18825 xref

---

EC:2.4.1.125 (sucrose--1,6-alpha-glucan 3(6)-alpha-glucosyltransferase) catalyses 2 reactions:
[(1->6)-alpha-D-glucosyl](n) + sucrose <=> [(1->6)-alpha-D-glucosyl](n+1) + D-fructose
[(1->6)-alpha-D-glucosyl](n) + sucrose <=> (1->3)-alpha-D-glucosyl-[(1->6)-alpha-D-glucosyl](n) + D-fructose

There are 0 annotations to this EC in SwissProt/UniProt.
The first reaction is identical to EC:2.4.1.5/GO:0047849 above.
The second reaction is RHEA:57036, which is annotated to 0 proteins in UP.

In this case, the corresponding GO entry does **not** look good because the def line only mentions one of the two EC:2.4.1.125 reactions, and the one it mentions is identical to EC:2.4.1.5/GO:0047849!

id: GO:0047217 (0 GO annotations)
name: sucrose-1,6-alpha-glucan 3(6)-alpha-glucosyltransferase activity
def: "Catalysis of the reaction: sucrose + 1,6-alpha-D-glucosyl(n) = 1,6-alpha-D-glucosyl(n+1) + fructose." [EC:2.4.1.125, MetaCyc:2.4.1.125-RXN]
xref: EC:2.4.1.125
xref: MetaCyc:2.4.1.125-RXN
is_a: GO:0046527 ! glucosyltransferase activity

So tasks here are:
- [x] Obsolete this term
- [x] Add EC:2.4.1.125 as broadMatch xref to GO:0047849

---

EC:2.4.1.140 (alternansucrase) also appears to catalyses the same 2 reactions as EC:2.4.1.125, though in an alternating manner:
Transfers alternately an alpha-D-glucosyl residue from sucrose to the 6-position and the 3-position of the non-reducing terminal residue of an alpha-D-glucan, thus producing a glucan having alternating alpha-(1->6)-and alpha-(1->3)-linkages

There are 0 annotations to this EC in SwissProt.
There are no corresponding RHEAs.

id: GO:0033824 (3 GO annotations, no EXP)
name: alternansucrase activity
def: "Catalysis of the transfer of an alpha-D-glucosyl residue from sucrose to alternately the 6-position and the 3-position of the non-reducing terminal residue of an alpha-D-glucan, thus producing a glucan having alternating alpha-1,6- and alpha-1,3-linkages." [EC:2.4.1.140]
xref: EC:2.4.1.140
xref: MetaCyc:2.4.1.140-RXN
is_a: GO:0046527 ! glucosyltransferase activity

So tasks here are:
- [x] Obsolete this term
- [x] Add EC:2.4.1.140 and MetaCyc:2.4.1.140-RXN as relatedMatch xref to GO:0047849

**Comment by pgaudet** [comment]
@sjm41 

- Added [RHEA:57036](https://www.rhea-db.org/rhea/57036) as narrowMatch on GO:0047849 dextransucrase activity GO:0047849.
- I've also added EC:2.4.1.140 and MetaCyc:2.4.1.140-RXN as BROAD rather than RELATED matches as you suggested. Let me know if you disagree. 

Thanks, Pascale
