### ISSUE TITLE
Check cross references to UM-BBD enzymes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28322]
We dont want to link to UM-BBD enzymes, as these do not represent function. UM-BBD 'reactions' are the UM-BBD object type GO should link to. 

There are 86 terms that have cross references to UM-BBD enyzmes: 
https://docs.google.com/spreadsheets/d/1vSi-_wxpaHZJjaeSkZ2FutbaOyP00ZZs9yhQ7uzM02c/edit?gid=0#gid=0

Please see if the 'enzyme' can be replaced by a 'reaction'. 
Also, check that the GO term has an EC and/or RHEA. If not, please make a note.

**Comment by sjm41** [comment]
Thanks Li!
