### ISSUE TITLE
Textual definition update: GO_0035098 - ESC/E(Z) complex

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#28327]
* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request a definition update**
GO_0035098 - ESC/E(Z) complex

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
**Current def:** A multimeric protein complex that can methylate lysine-27 and lysine-9 residues of
histone H3. In Drosophila the core subunits of the complex include ESC, E(Z), CAF1 (NURF-55) and
SU(Z)12. In mammals the core subunits of the complex include EED, EZH2, SUZ12 and RBBP4.
**Revised def:** A multimeric protein complex comprised of a catalytic lobe and a targeting lobe that
can methylate lysine-27 and lysine-9 residues of histone H3. This bilobed structure is conserved in
Drosophila and mammals.  In mammals, the catalytic lobe is comprised of the methyltransferase EZH2,
along with EED and the VEFS domain of SUZ12, while the targeting lobe is comprised of the N-terminal
region of SUZ12, RBBP4/7, and various associated accessory proteins. The corresponding subunits in
the Drosophila catalytic lobe are the methyltransferase E(z), along with Esc and the VEFS domain of
Su(z)12, while the N-terminal region of Su(z)12 andp55 comprise the conserved core of the targeting
lobe.

* **Reference(s)**
PMID:33232890 - Glancy E, Ciferri C, Bracken AP. 2021. Structural basis for PRC2 engagement with chromatin.
PMID:17107999 - Kim SY, 2006. Juxtaposed Polycomb complexes co-regulate vertebral identity.
PMID:31123059 - Bracken AP, Brien GL, Verrijzer CP. 2019. Dangerous liaisons: interplay between SWI/SNF, NuRD, and Polycomb in chromatin regulation and cancer. 
GOC:krc

* **Additional information**

**Comment by raymond91125** [comment]
@krchristie Thanks for a nice summary of what is known about the complex. I wonder if it is beyond GO preference: a necessary and sufficient definition. Do you think extra details are required in this case to make it distinct from other complexes?
@pgaudet Are extensive textual defs preferred for protein complexes?
I guess a use case is for GO definition to be used as an up-to-date summary, similar to gene descriptions.

**Comment by pgaudet** [comment]
Discussion at the ontology editors' call: the guidelines are to keep the definitions minimal to describe the complex and make it clear for curators what the complex is so that they can annotate it confidently. 

However the extra stuff may get out of date, and we would not be able to maintain it. Also it makes the definitions uneven across the different terms of the ontology, which is not sustainable with the resources we have. 

So, we will stick to the guidelines here: https://wiki.geneontology.org/Protein_complexes#Textual_definition_for_protein-containing_complex_terms

If the current definition is not wrong, then we propose to just add the references you cite. 

Thanks, Pascale

**Comment by krchristie** [comment]
Maybe you could at least put that info into the comment with a date. I find that the current style of minimal definitions are so uninformative that I have to spend a lot of time figuring out what the term is meant to cover.

**Comment by raymond91125** [comment]
@krchristie We discussed the option of putting more extensive information in comments. That option still suffers from the difficulty of keeping the content up to date. We thought that by adding more references as you provided would serve, at least in part, the function of clarification and is a good compromise as we strive for brevity, necessity, and sufficiency.

**Comment by krchristie** [comment]
> @krchristie We discussed the option of putting more extensive information in comments. That option still suffers from the difficulty of keeping the content up to date. We thought that by adding more references as you provided would serve, at least in part, the function of clarification and is a good compromise as we strive for brevity, necessity, and sufficiency.

I am not finding that the current brevity of the definitions is sufficient for me to understand what the term is meant to be describing without having to go read papers. I do not in fact find them to be sufficient.

**Comment by pgaudet** [comment]
Hi @krchristie 

We discussed this with GO editors, we want to keep an even level of depth in the definitions. The definition should be sufficient to correctly annotate the term, but we cannot go beyond that. 

Thanks for your suggestion tough! Sorry we're unable to implement it.
