### ISSUE TITLE
rename glutamate decarboxylation to succinate (GO:0006540) TO gamma-aminobutyrate shunt

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28355]
rename  glutamate decarboxylation to succinate (GO:0006540) TO gamma-aminobutyrate shunt (exact synonym)
AND MOVE 
glutamate catabolic process parent
up to 

glutamate metabolic process 

@pgaudet  does this make sense to you?

**Comment by ValWood** [comment]
Also add "never in S. pombe" and never in octosporus

Pombe/octosporus  have lost this pathway , but japonicus still has it

**Comment by pgaudet** [comment]
I see 46 references when I search PubMed for "gamma-aminobutyrate shunt" 

@deustp01 @ukemi do you know what's the most common name for this pathway? 

Thanks, Pascale

**Comment by sjm41** [comment]
Tagging @rozaru

**Comment by ValWood** [comment]
Any thoughts about the rename. If you think it is OK as is I can close.
On the whole though, isn't it better for users  to refer to  names pathways by name rather than  rather than "x metabolism"

**Comment by ValWood** [comment]
GABA shunt is most common (337 PubMed)
but since we don't use abbreviations in GO terms this would be expanded to "gamma-aminobutyrate shunt" (46 results)
glutamate decarboxylation to succinate (0 Pubmed)

The children, if valid would become 

gamma-aminobutyrate shunt via 2-oxoglutarate-dependent GABA-transaminase activity
gamma-aminobutyrate shunt via  succinate semialdehyde
(although these are a bit odd because one is via an activity, and one is via an intermediate)

But they seem to  be the same pathway:
Glutamate is converted to GABA by the enzyme glutamate decarboxylase (GAD).
GABA is then converted to succinic semialdehyde by GABA transaminase (GABA-T).
Succinic semialdehyde is converted to succinate by succinic semialdehyde dehydrogenase (SSADH).
Succinate enters the Krebs cycle.

**Comment by ValWood** [comment]
Neither 
[GO:0036242 glutamate catabolic process to succinate via 2-oxoglutarate-dependent GABA-transaminase activity](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Famigo.geneontology.org%2Famigo%2Fterm%2FGO%3A0036242%23display-lineage-tab&data=05%7C02%7Cvw253%40universityofcambridgecloud.onmicrosoft.com%7C1c244d4fc7c84b6cfb8608dca2850d5b%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638563939532030766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=O8hcN%2BRRU8ORAYOkkmU%2BzIApflas8xvq%2Fp2fvPBU8XA%3D&reserved=0)
    [GO:0019549 glutamate catabolic process to succinate via succinate semialdehyde](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Famigo.geneontology.org%2Famigo%2Fterm%2FGO%3A0019549%23display-lineage-tab&data=05%7C02%7Cvw253%40universityofcambridgecloud.onmicrosoft.com%7C1c244d4fc7c84b6cfb8608dca2850d5b%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638563939532043323%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=BJbakajNMgVn003WgFJ5LuMHWbyEoVwJviL%2Fw66Djuo%3D&reserved=0)

have annotations.Propose obsoletion...

**Comment by pgaudet** [comment]
Sounds good!
