### ISSUE TITLE
Missing parent: GO:0006568 tryptophan metabolic process GO:0006549 isoleucine metabolic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28367]
* **GO term ID and label for which you request a new superclass**

* **New superclass (parent) suggested**

~GO:0006568    tryptophan metabolic process~ is OK?
GO:0006549    isoleucine metabolic process
add 
GO:0170039    proteinogenic amino acid metabolic process

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by deustp01** [comment]
Looking at the first few items on the list, the ChEBI default form of L-amino acid has no ionized groups, exactly like the [Wikipedia representation](https://en.wikipedia.org/wiki/Amino_acid), a fairly common textbook representation. In my small sample, ChEBI goes on to list all the physiologically relevant charged forms of each amino acid as is_a children of this non-ionized one, so it's not clear that correct information is lost. And what is the exact form of an L-amino acid (or strictly, an aminoacyl-tRNA?) at the point it is recruited to be incorporated into a protein?

My opinion is that all the changes that @cmungall has been arguing for in the organization of the ChEBI amino acid ontology and in the text definitions of specific terms (e.g., flagging the one that is predominant at pH 7.3) will make this specific small fix unnecessary, so we should go for the main goal, the larger reorganization.

**Comment by pgaudet** [comment]
But they do have CHEBI:57719 'D-tryptophan zwitterion' - this should be proteogenic, shouldn't it?

**Comment by pgaudet** [comment]
> My opinion is that all the changes that @cmungall has been arguing for in the organization of the ChEBI amino acid ontology and in the text definitions of specific terms (e.g., flagging the one that is predominant at pH 7.3) will make this specific small fix unnecessary, so we should go for the main goal, the larger reorganization.


and meanwhile why do we do ? assert anything missing from ChEBI ?

**Comment by deustp01** [comment]
> and meanwhile what do we do ?

I'm worried that continuing to make ad hoc patches on a broken structure wastes a lot of GO time and does not solve the problem - not unlike the rationale for the many clean-up and rationalization exercises now underway in the BP and MF ontologies.

**Comment by pgaudet** [comment]
Right me too!! And ChEBI has been slow to make large changes. I was hoping they would make a smaller change about this set of terms (proteinogenic aa) quicker...

**Comment by ValWood** [comment]
Closing this one, these terms are actually fine. I wasn't looking at the L-form. These are under proteogenic amino acid, I just need to make annotations more specific.
