### ISSUE TITLE
Multiple terms with EC:2.3.1.48 as definition xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28368]
EC:2.3.1.48 is:
Name: histone acetyltransferase
Reaction: acetyl-CoA + L-lysyl-[protein] <=> CoA + H(+) + N(6)-acetyl-L-lysyl-[protein]
Comment: A group of enzymes acetylating histones.

But it's currently the definition xref for many of the more specific child terms in GO (see tree below).  EC/RHEA/MetaCyc don't have specific entries for the different acetylated residue activities.

I've found a couple of general PMIDs that we can use instead of the EC for the definition xref:

PMID: [19056256](https://pubmed.ncbi.nlm.nih.gov/19056256) Catalysis and Substrate Selection by Histone/Protein Lysine Acetyltransferases

PMID: [18552846](https://pubmed.ncbi.nlm.nih.gov/18552846) Combinatorial patterns of histone acetylations and methylations in the human genome

So I will replace the current EC:2.3.1.48 def xref with one/both of those PMIDs as appropriate, as shown below.

Note there is one GO term (histone H3K72 acetyltransferase activity [GO:0044019](https://www.ebi.ac.uk/QuickGO/term/GO:0044019) for which I can find no evidence in either PMID, nor through a more general PubMed search. It has 0 annotations. I suggest this term is obsoleted.

```
histone acetyltransferase activity [EC:2.3.1.48] => add PMID:19056256
|__histone H2A acetyltransferase activity [EC:2.3.1.48] => PMID:19056256
|   |__histone H2AK5 acetyltransferase activity  [EC:2.3.1.48] => PMID:19056256 & PMID:18552846
|   |__histone H2AK9 acetyltransferase activity [EC:2.3.1.48] => PMID:18552846
|__histone H2B acetyltransferase activity [EC:2.3.1.48] => PMID:19056256
|   |__histone H2BK5 acetyltransferase activity [EC:2.3.1.48] => PMID:18552846
|   |__histone H2BK12 acetyltransferase activity [EC:2.3.1.48] => PMID:18552846
|__histone H3 acetyltransferase activity [EC:2.3.1.48] => PMID:19056256
|   |__histone H3K4 acetyltransferase activity [EC:2.3.1.48] => PMID:18552846
|   |__histone H3K9 acetyltransferase activity [EC:2.3.1.48] => PMID:19056256 & PMID:18552846
|   |__histone H3K14 acetyltransferase activity [GOC:vw, PMID:21289066] => add PMID:19056256 & PMID:18552846
|   |__histone H3K18 acetyltransferase activity [EC:2.3.1.48] => PMID:18552846
|   |__histone H3K23 acetyltransferase activity [EC:2.3.1.48] => PMID:19056256 & PMID:18552846
|   |__histone H3K27 acetyltransferase activity [EC:2.3.1.48] => PMID:18552846
|   |__histone H3K36 acetyltransferase activity [EC:2.3.1.48] => PMID:18552846
|   |__histone H3K56 acetyltransferase activity [EC:2.3.1.48] => PMID:19056256
|   |__histone H3K72 acetyltransferase activity [EC:2.3.1.48] => OBSOLETE (0 annotations, nothing in PubMed)
|   |__histone H3K122 acetyltransferase activity [PMID:23415232]
|__histone H4 acetyltransferase activity [EC:2.3.1.48] => PMID:19056256
    |__histone H4K5 acetyltransferase activity [EC:2.3.1.48] => PMID:19056256 & PMID:18552846
    |__histone H4K8 acetyltransferase activity [EC:2.3.1.48] => PMID:19056256 & PMID:18552846
    |__histone H4K12 acetyltransferase activity [EC:2.3.1.48] => PMID:19056256 & PMID:18552846
    |__histone H4K16 acetyltransferase activity [EC:2.3.1.48]=> PMID:19056256 & PMID:18552846

```

**Comment by sjm41** [comment]
@pgaudet Can you do this bit please:
>Note there is one GO term (histone H3K72 acetyltransferase activity [GO:0044019](https://www.ebi.ac.uk/QuickGO/term/GO:0044019) for which I can find no evidence in either PMID, nor through a more general PubMed search. It has 0 annotations. I suggest this term is obsoleted.

**Comment by pgaudet** [comment]
I also quite like 
https://pubmed.ncbi.nlm.nih.gov/25303536/

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0044019 histone H3K72 acetyltransferase activity

The reason for obsoletion is that there is no evidence that this function exists (we find no literature about H3K72ac). There are no annotations to this term; these term is not present in any subsets. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/28368

Thanks, Pascale

**Comment by pgaudet** [comment]
@sjm41 I'm doing the obsoletion, I assume you'll be doing the xref edits?

**Comment by sjm41** [comment]
Yes, already done!  Sorry, should have said that above....

**Comment by pgaudet** [comment]
I didnt see the linked PR, that's all. (now I do, I hadn't checked closely enough)
