### ISSUE TITLE
Merge EC:2.1.1.44-related terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28375]
EC:2.1.1.44 describes a methyltransferase activity that adds three consecutive methyl groups to histidine:
Accepted Name: L-histidine N(alpha)-methyltransferase
Alt name: dimethylhistidine N-methyltransferase
Reaction: L-histidine + 3 S-adenosyl-L-methionine <=> 3 H(+) + hercynine + 3 S-adenosyl-L-homocysteine
xrefs are: RHEA:38471, MetaCyc:RXN-14431, KEGG:R01169

RHEA:38471 says "**Multi-step reaction: RHEA:38475 and RHEA:38479 and RHEA:11104.**", where:
RHEA:38475: L-histidine + S-adenosyl-L-methionine = H(+) + N(alpha)-methyl-L-histidine + S-adenosyl-L-homocysteine
RHEA:38479: N(alpha)-methyl-L-histidine + S-adenosyl-L-methionine = H(+) + N(alpha),N(alpha)-dimethyl-L-histidine + S-adenosyl-L-homocysteine
RHEA:11104: N(alpha),N(alpha)-dimethyl-L-histidine + S-adenosyl-L-methionine = H(+) + hercynine + S-adenosyl-L-homocysteine

We currently have 3 MF terms relating to EC:2.1.1.44 (one for each mono/di/trimethylase activity, corresponding to the individual RHEAs), plus a BP term to cover all 3 methylations:

id: GO:0052706 (4 annotations, 1 EXP)
name: histidine N-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + L-histidine = S-adenosyl-L-homocysteine + N-alpha,N-alpha,N-alpha-trimethyl-L-histidine." [EC:2.1.1.44]
is_a: GO:0008757 ! S-adenosylmethionine-dependent methyltransferase activity

id: GO:0052705 (0 annotations)
name: methylhistidine N-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + N-alpha-methyl-L-histidine = S-adenosyl-L-homocysteine + N-alpha,N-alpha-dimethyl-L-histidine." [EC:2.1.1.44]
is_a: GO:0008757 ! S-adenosylmethionine-dependent methyltransferase activity

id: GO:0030745 (0 EXP annotations)
name: dimethylhistidine N-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: S-adenosyl-L-methionine + N-alpha,N-alpha-dimethyl-L-histidine = S-adenosyl-L-homocysteine + N-alpha,N-alpha,N-alpha-trimethyl-L-histidine." [EC:2.1.1.44]
xref: EC:2.1.1.44
xref: KEGG_REACTION:R04436
xref: MetaCyc:2.1.1.44-RXN
xref: RHEA:11104
is_a: GO:0008757 ! S-adenosylmethionine-dependent methyltransferase activity

id: GO:0052707 (7 annotations, 2 EXP by PomBase and UniProt)
name: N-alpha,N-alpha,N-alpha-trimethyl-L-histidine biosynthesis from histidine
namespace: biological_process
def: "The pathway resulting in the formation of N-alpha,N-alpha,N-alpha-trimethyl-L-histidine from histidine. Histidine undergoes three methylations by a histidine-alpha-N-methyltransferase (EC:2.1.1.44) to form N-alpha,N-alpha,N-alpha-trimethyl-L-histidine (also known as hercynine or histidine betaine)." [EC:2.1.1.44]
xref: KEGG_REACTION:R01169

I think the solution here is to merge the above 4 terms into a single MF term that looks something like this:

name: L-histidine N(alpha)-methyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-histidine + 3 S-adenosyl-L-methionine <=> 3 H(+) + hercynine + 3 S-adenosyl-L-homocysteine. This reaction is the addition of three methyl groups to L-histidine to form N-alpha,N-alpha,N-alpha-trimethyl-L-histidine (also known as hercynine)." [RHEA:38471]
synonym: [add all synonyms from MF terms]
xref: EC:2.1.1.44 [exactMatch]
xref: KEGG_REACTION: R01169 [exactMatch]
xref: MetaCyc:RXN-14431 [exactMatch]
xref: RHEA:38471 [exactMatch]
xref: RHEA:38475 [narrowMatch]
xref: RHEA:38479 [narrowMatch]
xref: RHEA:11104 [narrowMatch]
xref: MetaCyc:2.1.1.44-RXN [narrowMatch]
MetaCyc:RXN-14437 [narrowMatch]
MetaCyc:RXN-14438 [narrowMatch]
KEGG_REACTION:R04436 [narrowMatch]
KEGG_REACTION:R10524 [narrowMatch]
KEGG_REACTION:R10523 [narrowMatch]
is_a: GO:0008757 ! S-adenosylmethionine-dependent methyltransferase activity

**Comment by pgaudet** [comment]
MFs: OK: Obsolete GO:0052705 methylhistidine N-methyltransferase activity (0 annotations) and GO:0030745 
 dimethylhistidine N-methyltransferase activity (0 EXP annotations): merge into GO:0052706 L-histidine N(alpha)-methyltransferase activity. These represent substeps of the overall reaction GO:0052706. See https://github.com/geneontology/go-ontology/issues/28375


BP: GO:0052707   N-alpha,N-alpha,N-alpha-trimethyl-L-histidine biosynthesis from histidine (7 annotations, 2 EXP by PomBase and UniProt): obsolete & replace by GO:0052704 ergothioneine biosynthesis from histidine via gamma-glutamyl-hercynylcysteine sulfoxide, since  N-alpha,N-alpha,N-alpha-trimethyl-L-histidine biosynthesis from histidine  is a substep of the pathway that is equivalent to the MF GO:0052706 L-histidine N(alpha)-methyltransferase activity. 

@ValWood @marcfeuermann Is this OK with you? 

Thanks, Pascale

**Comment by ValWood** [comment]
sure!
