### ISSUE TITLE
Proposed obsoletions of some catalytic activity terms with no mappings

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28382]
Some proposed obsoletions from reviewing catalytic activity leaf terms with no mappings but with an EC in the def xref (see https://docs.google.com/spreadsheets/d/1ytuqiOii6IYvMgy2rqRiy6JDCXIyucLcqcy5vFTO3bk/edit?gid=0#gid=0):

---

- [x] Obsolete GO:0018071	NAD(P)-cysteine ADP-ribosyltransferase activity
- [x] Obsolete GO:0018121	NAD(P)-asparagine ADP-ribosyltransferase activity
- [x] Obsolete GO:0018127	NAD(P)-serine ADP-ribosyltransferase activity

id: GO:0018071
name: NAD(P)-cysteine ADP-ribosyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: NAD(P)+ + L-cysteine = nicotinamide + N2-(ADP-D-ribosyl)-L-cysteine." [EC:2.4.2.-]
is_a: GO:0016763 ! pentosyltransferase activity

id: GO:0018121
name: NAD(P)-asparagine ADP-ribosyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: NAD(P)+ + L-asparagine = nicotinamide + N2-(ADP-D-ribosyl)-L-asparagine." [EC:2.4.2.-]
is_a: GO:0016763 ! pentosyltransferase activity

id: GO:0018127
name: NAD(P)-serine ADP-ribosyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: NAD(P)+ + L-serine = nicotinamide + N2-(ADP-D-ribosyl)-L-serine." [EC:2.4.2.-]
is_a: GO:0016763 ! pentosyltransferase activity

None of these 3 terms have any annotations, and all of them are only defined by a partial EC (which corresponds to 'pentosyltransferases').

---

- [x] Obsolete GO:0036136	kynurenine-oxaloacetate transaminase activity

id: GO:0036136
name: kynurenine-oxaloacetate transaminase activity
namespace: molecular_function
def: "Catalysis of the reaction: L-kynurenine + 2-oxoglutarate = 4-(2-aminophenyl)-2,4-dioxobutanoate + L-aspartate." [EC:2.6.1.-, GOC:pde, PMID:15606768, PMID:4149765]
synonym: "L-kynurenine-oxaloacetate transaminase activity" EXACT [GOC:bf]
is_a: GO:0036137 ! kynurenine aminotransferase activity
created_by: bf
creation_date: 2012-03-06T02:14:11Z

This term has no annotations, and just has a partial EC in the def xref.

PMID:4149765 is a 1973 paper called 'Aromatic amino acid transaminase in rat intestine.' Can't tell which specific gene/protein that corresponds to.

PMID:15606768 is a 2004 paper. It says: 'In mammals, kynurenine aminotransferase I/glutamine transaminase K (EC2.6.1.64; KAT-I) is a multifunctional enzyme. In vitro, the enzyme catalyzes the transamination of several amino acids (e.g. glutamine, methionine, aromatic amino acids including kynurenine) and also possesses cysteine S-conjugate β-lyase activity (EC4.4.1.13) 

I think that protein corresponds to KYAT1 (Q16773), which UniProt annotates to EC:2.6.1.7 (2-oxoglutarate + L-kynurenine = H2O + kynurenate + L-glutamate), as well as EC:2.6.1.64 (3-phenylpyruvate + L-glutamine = 2-oxoglutaramate + L-phenylalanine) and EC:4.4.1.13.

Searching in RHEA for the reaction given in GO:0036136, I can find this:
RHEA:66088 L-kynurenine + oxaloacetate = 4-(2-aminophenyl)-2,4-dioxobutanoate + L-aspartate
Three things to note:
- From the GO:0036136 name, it looks like "2-oxoglutarate" in the GO def should be "oxaloacetate", meaning that GO:0036136 = RHEA:66088
- However, RHEA:66088 has no other cross-references and no annotations at UniProt
- Moreover, RHEA:66088 is part of RHEA:66084

So, overall, lots of reasons to obsolete GO:0036136.

---

- [x] Obsolete GO:0004727	prenylated protein tyrosine phosphatase activity

id: GO:0004727
name: prenylated protein tyrosine phosphatase activity
namespace: molecular_function
def: "Catalysis of the reaction: prenylated-protein tyrosine phosphate + H2O = prenylated-protein tyrosine + phosphate." [EC:3.1.3.48]
is_a: GO:0004725 ! protein tyrosine phosphatase activity

This term just has 3x TAS annotations, and the EC:3.1.3.48 def xref corresponds to the more general parent term 'protein tyrosine phosphatase activity'.

---

- [ ] Obsolete GO:0052789  mannan 1,3-beta-mannosidase activity

id: GO:0052789
name: mannan 1,3-beta-mannosidase activity
namespace: molecular_function
def: "Catalysis of the hydrolysis of (1->3)-beta-D-mannosidic linkages in mannans, releasing mannose." [EC:3.2.1.78, GOC:mengo_curators]
synonym: "1,3-beta-D-mannan mannanohydrolase activity" RELATED [EC:3.2.1.78]
synonym: "beta-1,3-mannan 3-mannanohydrolase activity" RELATED [EC:3.2.1.78]
synonym: "exo-1,3-beta-mannanase activity" RELATED [EC:3.2.1.78]
synonym: "exo-1,3-mannanase activity" RELATED [EC:3.2.1.78]
synonym: "exo-beta-1,3-mannase activity" RELATED [EC:3.2.1.78]
is_a: GO:0004567 ! beta-mannosidase activity
created_by: ai
creation_date: 2011-10-04T01:11:41Z

This term has no annotations, and the EC:3.2.1.78 number given in the def xref is actually for the hydrolysis of 1->4 linkages and is already correctly on a different GO term:

id: GO:0016985
name: mannan endo-1,4-beta-mannosidase activity
namespace: molecular_function
def: "Catalysis of the random hydrolysis of (1->4)-beta-D-mannosidic linkages in mannans, galactomannans, glucomannans, and galactoglucomannans." [EC:3.2.1.78]
synonym: "1,4-beta-D-mannan mannanohydrolase activity" RELATED [EC:3.2.1.78]
synonym: "beta-1,4-mannan 4-mannanohydrolase activity" RELATED [EC:3.2.1.78]
synonym: "beta-D-mannanase activity" RELATED [EC:3.2.1.78]
synonym: "beta-mannanase activity" BROAD [EC:3.2.1.78]
synonym: "beta-mannanase B" RELATED [EC:3.2.1.78]
synonym: "endo-1,4-beta-mannanase activity" RELATED [EC:3.2.1.78]
synonym: "endo-1,4-mannanase activity" BROAD [EC:3.2.1.78]
synonym: "endo-beta-1,4-mannase activity" RELATED [EC:3.2.1.78]
synonym: "endo-beta-mannanase activity" BROAD [EC:3.2.1.78]
xref: EC:3.2.1.78
xref: MetaCyc:3.2.1.78-RXN
is_a: GO:0004567 ! beta-mannosidase activity

**Comment by sjm41** [comment]
FYI, Sylvain at UP agrees with these obsoletions.

**Comment by pgaudet** [comment]
- [x] GO:0030945 protein tyrosine phosphatase activity, via thiol-phosphate intermediate: replace by GO:0004725 protein tyrosine phosphatase activity; represents a substep. 1 EXP, will be automatically re-annotated
