### ISSUE TITLE
rename cell wall integrity MAPK cascade-> cell integrity MAPK cascade

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28384]
Please provide as much information as you can: 

~"cell integrity signalling" OR "cell integrity pathway"
(102 PubMed results)
The series of molecular signals regulates  multiple biological processes including  cell wall maintenance  (in yeast), cytokinesis, vacuole fusion, and ionic homeostasis by fine tuning  the  cell integrity MAPK cascade**~

we decided the new term was not necessary

* **Reference, in format PMID:#######**
PMID:24498240
PMID:34198697

* **Gene product name and ID to be annotated to this term**

(note that I intend to change the name of 
https://www.pombase.org/term/GO:0000196
 cell wall integrity MAPK cascade  to cell integrity MAPK cascade (cell wall is too restrictive, because it also covers plasma membrane integrity, I will put this in another ticket)

* **Parent term(s)**

 intracellular signal transduction (GO:0035556)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

https://www.pombase.org/term/GO:0000196
 cell wall integrity MAPK cascade

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

WIthout this term I have no common signalling term to describe the pathway. Most of these have only 
intracellular signal transduction (GO:0035556)

**Comment by pgaudet** [comment]
Can we adjust the definition and/or label of [cell wall integrity MAPK cascade](http://purl.obolibrary.org/obo/GO_0000196)?

**Comment by pgaudet** [comment]
It sounds like it should be is_a [MAPK cascade](http://purl.obolibrary.org/obo/GO_0000165). Please have a look at the definitions in the branch, @hattrill and I tried to be a lot more specific about the component of the signaling cascade/pathway, otherwise it's my end up being annotated for proteins somehow upstream of the pathway.

**Comment by ValWood** [comment]
I would love that , but my understanding is that the MAP kinase cascades begin with the MAP kinase.

I am trying to capture these upstream components of the CIP pathway.

<img width="456" alt="Screenshot 2024-07-03 at 15 40 53" src="https://github.com/geneontology/go-ontology/assets/7359272/64009a6b-23e7-4af6-bc3b-e0c4ba9a4581">

If I could annotate these directly to "cell wall integrity MAPK cascade" that would be OK

(note that I don't want to annotate these as "positive regulation of MAPK cascade" I want to annotate them as part_of the pathway)

**Comment by ValWood** [comment]
i.e the definitiions states
" It starts with the activation of an upstream MAP4K, and continues with the consecutive activation of a MAP3K and a MAP2K."

**Comment by ValWood** [comment]
cell integrity signalling begins with Rho, proceeds through protein kinase C and the MAP kinase cascade.
I want to:
i) avoid annotating a single pathway steps  to different terms, and have a collective term for all steps (under signalling)
ii)  capture the direction of regulation by relations between activities

**Comment by ValWood** [comment]
I think you are saying that I annotate all to "positive regulation of cell wall integrity MAPK cascade"
I can do that.

I still want to revise the label and definition of cell wall integrity MAPK cascade to 
"cell integrity MAPK cascade" which is more correct  (and update the definition, and remove the regulation of cell wall parentage,  downstream regulation need to be added as concurrent annotations)

**Comment by ValWood** [comment]
The  other issue is thet MAPK are all defined as "stress-activated" and have a "stress activated parent". However 
"The evolutionarily conserved MAPK signaling pathways orchestrate multiple and fundamental cellular functions in eukaryotic organisms that assure cell proliferation and survival **during unperturbed conditions and** in response to environmental stimuli. "

**Comment by ValWood** [comment]
stress-activated can probably go under stress (not sure)
but CIP   is not always stress  (although some inputs are stress activated)

**Comment by hattrill** [comment]
Hi @ValWood Removing stress-activated MAPK sounds like a good idea - we look at this before and moved some of the MAPK cascades out from under it. I will make a note to look at this term with Pascale again, as there are some direct annotations to this term but I need to remind myself why we still have it. Think if CIP is moved from under it, then even more reason to question its existence.

As for the intended use of 'cell wall integrity MAPK cascade' then only the MAPKs and the scaffolds should be annotated with this term, to keep it inline with other cassettes. For all components, a separate 'encompassing pathway' term which begins with a Rho and ends with XXXX would fit the pattern of the other MAPK-containing pathways. Are there other pathways where the cassette is used?

**Comment by ValWood** [comment]
I see, I thought p38MAPK was the canonical stress cascade, but that isn't even under stress-activated. In that case I think it should go.

So in summary, actions
1. Obsolete  GO:0051403   stress-activated MAPK cascade grouping term

2. Should we also obsolete "GO:0031098  stress-activated protein kinase signaling cascade"
even if a pathway is *called* stress-activated, that doesn't mean it is *only* stress activated?

3. Relabel "cell wall integrity MAPK cascade" to "cell integrity MAPK cascade" 

5. Tweak the definition of "cell integrity MAPK cascade" 

Existing def is OK but could add

The cell integrity MAPK cascade regulates multiple biological processes including cell wall maintenance (in yeast), cytokinesis, vacuole fusion, plasma membrane integrity and ionic homeostasis.
How close is this def to ERK1/2  ? (see 5)

6. Note that the core effector of the CIP is MAPK Pmk1, an ERK1/2 ortholog which makes sense, so these are orthologous signalling pathways. ) We should probably really consider merge and call it  ERG/cell integrity MAPK cascade? but I can ignore that for now.

7. I have  annotated upstream of  CIP MAPK to positive  regulation...

**Comment by ValWood** [comment]
I just re read this
>  For all components, a separate 'encompassing pathway' term which begins with a Rho and ends with XXXX would fit the pattern of the other MAPK-containing pathways. Are there other pathways where the cassette is used?

So we should have the encompassing pathway.
I am not aware of other pathways which use this cassette.
At least , I think they all go through protein kinase C pck2.....

**Comment by hattrill** [comment]
@ValWood I think that if you are ok with "I have annotated upstream of CIP MAPK to positive regulation..." then we don't have to make an encompassing pathway. 
This means that the "cell integrity MAPK cascade" still fits in the definition of the "MAPK cascade" even if it is a bit of an 'special case' in that it is only used in that context it does mean that it is useful for those wanting to see all the types of MAPK cascade units. Which I think, on balance is the stronger argument here. 
So, unless you really needed an encompassing pathway, which from the above comment you don't, then let's not make one.

**Comment by hattrill** [comment]
As for " GO:0031098 stress-activated protein kinase signaling cascade" - there are some direct annotations to this term, but looks like it could/should go.
Same for GO:0051403 stress-activated MAPK cascade .

Also, cell integrity MAPK cascade has a part_of rel to 'cell wall organization or biogenesis' which based on "The cell integrity MAPK cascade regulates multiple biological processes including cell wall maintenance (in yeast), cytokinesis, vacuole fusion, plasma membrane integrity and ionic homeostasis." should be removed.

On point 6, Pascale and I talked about this before and decided against merging these as we thought making the functional distinction makes sense from the perspective of users. So, I would keep cell integrity MAPK cascade separate.

**Comment by ValWood** [comment]
OK, I had noted the incorrect parent, but forgot to include it in the list!

**Comment by ValWood** [comment]
Updated the action items

**Comment by pgaudet** [comment]
see also https://github.com/geneontology/go-ontology/issues/26810
