### ISSUE TITLE
Merge multiple terms with EC:1.1.1.1 as definition xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28393]
EC:1.1.1.1 is alcohol dehydrogenase, and is associated with these two reactions:
a primary alcohol + NAD(+) <=> an aldehyde + H(+) + NADH
a secondary alcohol + NAD(+) <=> a ketone + H(+) + NADH

It therefore makes sense that we have GO:0004022 with EC:1.1.1.1 as it's definition and term xref:

id: GO:0004022
name: alcohol dehydrogenase (NAD+) activity
def: "Catalysis of the reaction: an alcohol + NAD+ = an aldehyde or ketone + NADH + H+." [EC:1.1.1.1]
xref: EC:1.1.1.1
xref: MetaCyc:ALCOHOL-DEHYDROG-GENERIC-RXN
xref: RHEA:10740
xref: UM-BBD_reactionID:r0022
xref: UM-BBD_reactionID:r0603
is_a: GO:0018455 ! alcohol dehydrogenase [NAD(P)+] activity

However, EC:1.1.1.1 is also the definition xref for these three more specific child terms of GO:0004022:

id: GO:0004023 (0 annotations)
name: alcohol dehydrogenase (NAD+) activity, metal ion-independent
def: "Catalysis of the reaction: an alcohol + NAD+ = an aldehyde or ketone + NADH + H+; can proceed in the absence of a metal ion." [EC:1.1.1.1, GOC:mah]
is_a: GO:0004022 ! alcohol dehydrogenase (NAD+) activity

id: GO:0004025 (1 annotation)
name: alcohol dehydrogenase (NAD+) activity, iron-dependent
def: "Catalysis of the reaction: an alcohol + NAD+ = an aldehyde or ketone + NADH + H+, requiring the presence of iron." [EC:1.1.1.1, GOC:mah]
is_a: GO:0004022 ! alcohol dehydrogenase (NAD+) activity

id: GO:0004024 (6 EXP annotations)
name: alcohol dehydrogenase (NAD+) activity, zinc-dependent
def: "Catalysis of the reaction: an alcohol + NAD+ = an aldehyde or ketone + NADH + H+, requiring the presence of zinc." [EC:1.1.1.1, GOC:mah]
is_a: GO:0004022 ! alcohol dehydrogenase (NAD+) activity

Given this level of specificity is outside the scope of GO, and given the low number of annotations, we propose that GO:0004023, GO:0004025 and GO:0004024 are merged into the parent term GO:0004022.

**Comment by pgaudet** [comment]
Dear all, 

The reason has been made to obsolete 
GO:0004023 alcohol dehydrogenase (NAD+) activity, metal ion-independent
GO:0004025 alcohol dehydrogenase (NAD+) activity, iron-dependent
GO:0004024 alcohol dehydrogenase (NAD+) activity, zinc-dependent

The reason for obsoletion is that the co-factor is outside the scope of GO. Note that this is also outside the scope of EC and RHEA. There are 8 annotations to these terms: by Reactome, EcoCyc, EcoWiki (as well as MGI and UniProt, that will be automatically replaced). The terms will be replaced by the parent GO:0004022 alcohol dehydrogenase (NAD+) activity.

Annotations are here: https://github.com/geneontology/go-annotation/issues/5358

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/28393

Thanks, Pascale
