### ISSUE TITLE
Entner-Doudoroff pathway II (non-phosphorylative)

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28392]
We currently have two terms with xref to MetaCyc:NPGLUCAT-PWY = Entner-Doudoroff pathway II (non-phosphorylative): 

id: GO:0019595  (6 EXP annotations to bacterial gdh/gdh2/gcd genes)
name: non-phosphorylated glucose catabolic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the breakdown of non-phosphorylated forms of glucose." [GOC:ai]
synonym: "non-phosphorylated glucose breakdown" EXACT []
synonym: "non-phosphorylated glucose catabolism" EXACT []
synonym: "non-phosphorylated glucose degradation" EXACT []
xref: MetaCyc:NPGLUCAT-PWY
is_a: GO:0006007 ! glucose catabolic process
is_a: GO:0046430 ! non-phosphorylated glucose metabolic process

id: GO:0061680 (0 annotations)
name: Entner-Doudoroff pathway through gluconate to D-glyceraldehyde
namespace: biological_process
def: "The Entner-Doudoroff pathway that proceeds through a D-gluconate intermediate and yields pyruvate and D-glyceraldehyde." [GOC:dph, MetaCyc:ENTNER-DOUDOROFF-PWY-II, PMID:12921536]
xref: MetaCyc:NPGLUCAT-PWY
is_a: GO:0061679 ! Entner-Doudoroff pathway through gluconate
intersection_of: GO:0061679 ! Entner-Doudoroff pathway through gluconate
intersection_of: ends_with GO:0061677 ! 2-dehydro-3-deoxy-D-gluconate aldolase activity
intersection_of: has_primary_output CHEBI:17378 ! D-glyceraldehyde
created_by: dph
creation_date: 2015-01-22T08:51:31Z

@rozaru and I think those two terms should be merged.
Sound right to you @ukemi and @deustp01 ?

Note the two terms have different parentages - I think the single merged term should get both parentages.
That said, the intermediate "GO:0046430  non-phosphorylated glucose metabolic process" isnt' necessary and could just be deleted.

![Screenshot 2024-07-04 at 16 24 54](https://github.com/geneontology/go-ontology/assets/16306861/b76f429c-c9a0-43dc-aefb-c10531eec260)

**Comment by sjm41** [comment]
Should also replace "MetaCyc:ENTNER-DOUDOROFF-PWY-II" with "NPGLUCAT-PWY" in the GO:0061680 def xref, since the former is obsolete and has been replaced with the latter (as per the term xref).

def: "The Entner-Doudoroff pathway that proceeds through a D-gluconate intermediate and yields pyruvate and D-glyceraldehyde." [GOC:dph, MetaCyc:ENTNER-DOUDOROFF-PWY-II, PMID:12921536]
xref: MetaCyc:NPGLUCAT-PWY

**Comment by deustp01** [comment]
> @rozaru and I think those two terms should be merged. Sound right to you @ukemi and @deustp01 ?

This looks like a new instance of the recent discussion about our creation of BP terms to distinguish multiple types of glycolysis and it looks to me like the argument then in favor of merging them back together (including the thought that GO-CAM processes, not yet in regular use when the distinguishing work was done, can capture these biological distinctions reliably and flexibly so there's no need to hard-code them in the ontology) applies equally here. Or am I missing a more basic distinction @ukemi ?

**Comment by sjm41** [comment]
Thanks Peter.

I think the main issue in this particular case is that "GO:0019595 non-phosphorylated glucose catabolic process" and "GO:0061680 Entner-Doudoroff pathway through gluconate to D-glyceraldehyde" appear to describe exactly the same pathway - each term has the same, single xref to MetaCyc:NPGLUCAT-PWY Entner-Doudoroff pathway II (non-phosphorylative).

Further, "GO:0019595 non-phosphorylated glucose catabolic process" (which sounds like it might be a grouping term) currently has no children, and "GO:0061680 Entner-Doudoroff pathway through gluconate to D-glyceraldehyde" appears to be the only known instance.  Are there other glycolytic pathways that could be considered children of "GO:0019595 non-phosphorylated glucose catabolic process"?

On a similar note, the only current child of "GO:0046430 non-phosphorylated glucose **metabolic** process" is "GO:0019595 non-phosphorylated glucose catabolic process".

**Comment by deustp01** [comment]
> Are there other glycolytic pathways that could be considered children of "GO:0019595 non-phosphorylated glucose catabolic process"?
My recollection is that this was the only one we found, but we were mining Metacyc, not doing our own independent trawls through the literature.

**Comment by sjm41** [comment]
I'm going to solve the immediate problem (the duplicate MetaCyc xrefs) by removing the MetaCyc xref on GO:0019595 'non-phosphorylated glucose catabolic process'.
I will also add GO:0019595 as a parent to GO:0061680 'Entner-Doudoroff pathway through gluconate to D-glyceraldehyde'
And I'll also replace the obsolete 'MetaCyc:ENTNER-DOUDOROFF-PWY-II' def xref on GO:0061680, with its current ID of MetaCyc:NPGLUCAT-PWY = 'Entner-Doudoroff pathway II (non-phosphorylative)'
