### ISSUE TITLE
NTR: phospholipase C/protein kinase C signal transduction

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28410]
An intracellular signaling cassette that starts with activation of phospholipase C (PLC) activity and ends with the activation of protein kinase C (PKC). PLC produces inositol 1,4,5-trisphosphate (IP3) and diacylglycerol (DAG). IP3 regulates the opening of calcium channels in intracellular calcium store, leading to the release of calcium into the cytosol. Calcium and DAG activate protein kinase C (PKC), which in turn activates downstream effectors. 

@hattrill does that look OK to you? 

This would replace GO:0070528 protein kinase C signaling (and regulation terms: )
GO:0090036 regulation of protein kinase C signaling
GO:0090038 negative regulation of protein kinase C signaling
GO:0090037 positive regulation of protein kinase C signaling

as well as 
GO:0051281 positive regulation of release of sequestered calcium ion into cytosol
GO:0031587 positive regulation of inositol 1,4,5-trisphosphate-sensitive calcium-release channel activity
GO:0060316 positive regulation of ryanodine-sensitive calcium-release channel activity

I need to also create the regulation terms.

**Comment by hattrill** [comment]
@pgaudet that sounds correct to me.

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141212
+name: phospholipase C/protein kinase C signal transduction
+namespace: biological_process
+def: "An intracellular signaling cassette that starts with activation of phospholipase C (PLC) activity and ends with the activation of protein kinase C (PKC). PLC produces inositol 1,4,5-trisphosphate (IP3) and diacylglycerol (DAG). IP3 regulates the opening of calcium channels in intracellular calcium store, leading to the release of calcium into the cytosol. Calcium and DAG activate protein kinase C (PKC), which in turn activates downstream effectors. This cassette is often part of the phospholipase C-activating G protein-coupled receptor signaling pathway." [PMID:26605346]
+synonym: "PLC/PKC signaling" EXACT []
+synonym: "PLC/PKC/PKD signaling" EXACT []
+is_a: GO:0141124 ! intracellular signaling cassette
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28410" xsd:anyURI
+created_by: pg
+creation_date: 2024-07-08T14:39:30Z
