### ISSUE TITLE
NTR: [symbiont-mediated generation of symbiont-containing vacuole]

### ISSUE THREAD

**Issue by genegodbold** [geneontology/go-ontology#28420]
Please provide as much information as you can: 

* **Suggested term label:**
Symbiont-mediated generation of symbiont-containing vacuole

* **Definition (free text)** 
* This term is meant to annotate sequences that are involved in the creation of vacuoles in host cells in which symbionts can replicate in a protected environment.

* **Reference, in format PMID:#######**
(REQUIRED) See below--also https://pubmed.ncbi.nlm.nih.gov/?term=%22pathogen-containing+vacuole%22

* **Gene product name and ID to be annotated to this term**
* ROP4 to Toxoplasma gondii is thought to be involved in the maintenance of the parasitophorous vacuole (PVM) in host cells [PMID:23186105]. ROP4 migrates to the PVM after discharge of the rhoptries and then becomes phosphorylated [PMID:15470260].
* AnkX from Legionella pneumophila modifies host Rab small GTPases by phosphocholination [PMID:21822290]. Phosphocholination of Rab interferes with host endocytic recycling and is critical for inhibiting fusion of the Legionella-containing vacuole with lysosomes [PMID:28944216]. 
* AptA  localizes to Anaplasma phagocytophilum inclusions during infection and activates MAPK pathways. AptA expression in mammalian cells induces phosphorylation of Erk1/2 through MEK. AptA interacts specifically and directly with host intermediate filament protein vimentin which colocalize in infected host cells. The MAPK pathway is activated through vimentin in infected neutrophils [PMID:20716207].
* Francisella tularensis mutants in which the gene for DipA is disabled are targeted, in murine and human macrophages, to autophagic vacuoles unlike wild-type bacteria. DipA is required for cytosolic replication but not phagosomal escape [PMID:22863802]. DipA has four Sel1-like repeats and a coiled-coil motif but otherwise appears novel. DipA is membrane associated and is localized on the bacterial surface during macrophage infection. The coiled-coil domain is indispensable for membrane association [PMID:23840797].
* CaeA appears to be involved in biogenesis of the Coxiella burnetii containing vacuole; it localizes to the host cell nucleus. Loss of function of CaeA results in a bacterial mutant with a small-vacuole phenotype [PMID:29339460].
* ChlaDUB1 and the related ChlaDUB2 are chlamydial effectors that can perform both lysine deubiquitination and lysine acetyltransferase reactions using the same conserved Cys residue and a unique inserted helix (VR3). The His203Tyr mutation inactivates both enzymatic activities. The deubiquitinase activity of these effectors is responsible for the redistribution of the Golgi around the inclusion body in host cells infected with bacteria. The effector localizes to the Golgi during infection [PMID:30397340].
* CpoS is a chlamydial T3SS effector that recruits host Rab small GTPases and Rab effectors to the periphery of the inclusion body in infected cells. In doing so it redirects and intercepts host clathrin-coated vesicles from the recycling pathway to the periphery of the inclusion [PMID:30893609].
* Etf-2 is a T4SS effector that localizes to ehrlichial inclusions and sequesters the host Rab5 small GTPase in its GTP-bound form. Etf-2 delays Rab5 dissociation from (and Rab7 localization to) phagosomes from endosomes. Binding of Etf-2 to Rab5-GTP delays Rab5 inactivation and avoids routing of ehrlichial inclusions to host phagosomes. Etf-2 delays the maturation of phagosomes to phagolysosomes [PMID:30181274].
* LaiB/SdeB is a translocated Dot/Icm T4BSS effector of Legionella pneumophila that is upregulated during the post-exponential phase of intracellular growth [PMID:26545400]. SidJ acts on SidE family proteins (LaiA/SdeA, LaiB/SdeB, LaiC/SdeC, SidE/LaiD), which are found on the cytoplasmic face of the Legionella-containing vacuole (LCV), to restrain their toxicity to the host cell. Overexpression of an individual SidE family protein is lethal to host cells in the absence of SidJ. SidJ mediates the disappearance of SidE proteins from the LCV after their initial appearance. SidJ may directly target SidE proteins for degradation by the host proteasome.  SidJ and the SidE-family proteins are required for optimal intracellular growth in the LCV [PMID:25774515].
* LegC2 appears to contribute to the formation of the intracellular niche of Legionellae in host cells by interfering with pathways that modulate vesicle maturation [PMID:18670632]. In vivo, a mutant strain of Legionellae in which the genes for LegC2 and LegC7 are deleted is defective in establishing a vacuole that supports bacterial replication. This was correlated with a decrease in the association of endoplasmic reticulum-derived vesicles with vacuoles containg the mutant bacteria [PMID:27459495].

* **Parent term(s)**
Maybe GO:0044068 Symbiont-mediated perturbation of host cellular process

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
@pgaudet

**Comment by pgaudet** [comment]
Noting that we need to clearly distinguish that new term from 
- [entry into host cell by a symbiont-containing vacuole](http://purl.obolibrary.org/obo/GO_0085017) and 
- [symbiont-mediated perturbation of host vacuole organization](http://purl.obolibrary.org/obo/GO_0044075)


Pascale

**Comment by genegodbold** [comment]
Here is the problem: there are a *lot* of vacuoles. 
* The compartment in which a symbiont enters the cell (either because it forced entry or it has been captured by the host) is one thing. But for an intracellular parasite, that's just the beginning. Most viruses need to subvert that initial compartment, typically by destruction, which liberates them into the cytosol. That's not what most protozoa and bacteria do, though.
* I don't like the term "entry into host cell by a symbiont-containing vacuole". Why does this need to be distinguished from entry into host cell?
* For many protozoa and most intracellular bacteria, they start messing with host cell biology as soon as they are inside. They manipulate small GTPases, the cytoskeleton (usually actin) and do odd things to membrane components to **conver**t the vacuole into something that the _host_ controls to something that _they_ control. They also mess with autophagy proteins to stop xenophagy from occurring. I try to document this kind of thing.

**Comment by pgaudet** [comment]
[Term]
id: GO:0141213
name: symbiont-mediated generation of symbiont replication vacuole
namespace: biological_process
def: "A process in which a symbiont alters or subverts vacuole organization in its host organism to form a protected environment in which it can replicate. The host is defined as the larger of the organisms involved in a symbiotic interaction." [PMID:21822290, PMID:23186105, PMID:30893609]
is_a: GO:0044075 ! symbiont-mediated perturbation of host vacuole organization
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28420" xsd:anyURI
