### ISSUE TITLE
Obsoletion notice: Regulation of telomerase activity & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28437]
From #28394

@RLovering 

> Looking at the child terms and taking on the removal of BP regulates MF terms. I note that there is the term [GO:0010521]
telomerase inhibitor activity but not an activator term. I have just looked up one of the proteins associated with the positive reg term and UniProt describes NVL https://www.uniprot.org/uniprotkb/O15381/entry as: Participates in the assembly of the telomerase holoenzyme and effecting of telomerase activity via its interaction with TERT (PubMed:[22226966](https://www.uniprot.org/citations/22226966)). A SWIS annotation confirms NVL binds TERT.
https://europepmc.org/article/MED/22226966 abstract points to the role of NVL in telomerase assembly and that NVL2 is an essential component of the telomerase holoenzyme.

> Would this support telomerase activator activity? If so could this term be created before I start deleting all the pos reg terms?

> I can see that many of the other reg terms relate to signaling pathway proteins which presumably should be annotated to a pathway not reg of telomerase.

----

Pascale: 

> I see there are 42 EXP annotations to [GO:0051973](https://www.ebi.ac.uk/QuickGO/term/GO:0051973) positive regulation of telomerase activity, so we need to check all of them, but for NVL, I would annotate this to 'protein complex assembly', not regulation; what do you think ?

----
Ruth:
> I think that 'protein complex assembly' does not indicate NVL has a role in telomerase assembly. I guess if NVL is involved in assembly of many complexes perhaps this specific role is not required. So I guess you are making me find a better paper to demonstrate that it activates not just assembles the complex. Before I look at this further, have you decided to annotate adaptor proteins as activating the complexes or signaling pathways they are associated with rather than just annotating them as involved in protein complex assembly?

I would have thought that if the protein remains associated with the activated complex then it could be considered as part of the signaling pathway or activating the complex, (rather than just assembling the complex) although I am sure nothing is this simple.

I will see if I can find a better activator, I really do not want to check all these annotations without an alternative term to use if the gp is an activator.

**Comment by pgaudet** [comment]
Yes, that's helpful - is it a chaperone?

**Comment by RLovering** [comment]
Hi Pascale

just realised this NVL annotation is not actually a UCL annotation ;) I think you are right about complex assembly terms. I have added a couple of annotations to this record as I was here: 	
telomerase holoenzyme complex assembly
and upstream of 	positive regulation of telomere maintenance

Let me know if you don't like these and want me to delete them.

I will look at the other regulation of telomerase activity terms - but only the UCL ones ;)

Best

Ruth

**Comment by ValWood** [comment]
I think so
https://www.mdpi.com/2218-273X/9/11/715
(review describes a suit of ATPase assembly factors that
The yeast AAA-ATPases Rix7 (green), Rea1 (multi-colored) and Drg1 (red) associate at different stages of assembly with pre-60S subunits and catalyze the release of specific maturation factors, which are recycled and join freshly produced pre-ribosomes.

**Comment by RLovering** [comment]
Hi Pascale

I have reviewed all the regulation of telomerase activity annotations and I think I have deleted/changed all of them, I got some that were also in the AE field but I may have missed some.

Ruth

**Comment by pgaudet** [comment]
Thank you @RLovering 
All annotations should be here https://github.com/geneontology/go-annotation/issues/5331 (click on links)

The review ticket is here: https://github.com/geneontology/go-annotation/issues/5331

Sorry it took me a little while to make the spreadsheet. I suppose yours are all done! 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @raymond91125 

Would you please take this one? Note that the obsoletion notice has not yet been sent. 

Thanks, Pascale
