### ISSUE TITLE
Term defintion update : N-acetyllactosaminide alpha-2,3-sialyltransferase activity

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#28444]
GO:0008118    N-acetyllactosaminide alpha-2,3-sialyltransferase activity

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
Should we specify that it can also sialylate glycolipids?

* **Reference(s)**
PubMed:10206952

* **Additional information**
As stated in the EC number and shown in PubMed:10206952, it sialylates glycoproteins but also glycolipids. It is stated in the parent term GO:0008373 sialyltransferase activity :"Catalysis of the transfer of sialic acid to an acceptor molecule, typically the terminal portions of the sialylated glycolipids (gangliosides) or to the N- or O-linked sugar chains of glycoproteins."

**Comment by lbreuza** [comment]
I realised that lipid glycosylation GO:0030259 is not part of glycolipid biosynthetic process GO:0009247 as protein glycosylation is for glycoprotein biosynthetic process.

**Comment by pgaudet** [comment]
Hi @lbreuza 

Thanks for pointing that out. I will update the reaction to the same as RHEA, that doesn't specify proteins or lipids, and add the a comment based on the one in EC "The enzyme recognizes the sequence beta-D-galactosyl-(1->4)-N-acetyl- D-glucosaminyl (known as type 2 histo-blood group precursor disaccharide) in non-reducing termini of glycan moieties in glycoproteins and glycolipids." >> The substrate for this reaction is a beta-D-galactosyl-(1->4)-N-acetyl- D-glucosaminyl (known as type 2 histo-blood group precursor disaccharide) in non-reducing termini of glycan moieties in either glycoproteins and glycolipids.

Does that work?

**Comment by pgaudet** [comment]
Also, add [RHEA:52316](https://www.rhea-db.org/rhea/52316) (was only present as def xref)
