### ISSUE TITLE
Obsoletion request: GO:2001268 - negative regulation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway

### ISSUE THREAD

**Issue by slaulederkind** [geneontology/go-ontology#28468]
Please provide as much information as you can:

* **GO term ID and Label**
* 
* negative regulation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway (GO:2001268)

* **Reason for deprecation** Put an x in the appropriate box: 
 - [ ] The reason for obsoletion is that the term is not clearly defined and usage has been inconsistent.
 - [ ]  The reason for obsoletion is that this term is pre-composed and should be represented as a GO-CAM model.
 - [ ]  The reason for obsoletion is that this term represent an assay and not a GO process.
 - [ ]  The reason for obsoletion is that this represents a phenotype.
 - [ ] The reason for obsoletion is that the data from the paper for which the term was requested can be accurately described using [appropriate GO term].
 - [ ] The reason for obsoletion is that this term represents a molecular function.
 - [ ]  The reason for obsoletion is that this term represents a gene product.
 - [ ] The reason for obsoletion is that this term refers to a class of proteins.
 - [ ]  The reason for obsoletion is that this term was added in error.
 - [ ]  The reason for obsoletion is that more specific terms were created.
 - [ ]  The reason for obsoletion is that this term was an unnecessary grouping term.
 - [ ]  The reason for obsoletion is that the meaning of the term is ambiguous.
 - [ ]  The reason for obsoletion is that is not known to be catalyzed by any gene product.
 - [ ]  The reason for obsoletion is that it more specific than the specificity of any known gene product.
 - [ ]  The reason for obsoletion is that there is no evidence that this function/process/component exists.

This term is not a node term but an end of branch leaf node, yet it is labelled "Not4Curation"

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by sjm41** [comment]
All these related terms MF and BP should probably go too:

id: GO:0097153
name: cysteine-type endopeptidase activity involved in apoptotic process
namespace: molecular_function

id: GO:0097199
name: cysteine-type endopeptidase activity involved in apoptotic signaling pathway
namespace: molecular_function

id: GO:0097200
name: cysteine-type endopeptidase activity involved in execution phase of apoptosis
namespace: molecular_function

==

id: GO:0006919
name: activation of cysteine-type endopeptidase activity involved in apoptotic process
namespace: biological_process

id: GO:0043154
name: negative regulation of cysteine-type endopeptidase activity involved in apoptotic process
namespace: biological_process

id: GO:0043280
name: positive regulation of cysteine-type endopeptidase activity involved in apoptotic process
namespace: biological_process

id: GO:0043281
name: regulation of cysteine-type endopeptidase activity involved in apoptotic process
namespace: biological_process

id: GO:0097296
name: activation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway
namespace: biological_process

id: GO:1990001
name: inhibition of cysteine-type endopeptidase activity involved in apoptotic process
namespace: biological_process

id: GO:2001267
name: regulation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway
namespace: biological_process

id: GO:2001268
name: negative regulation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway
namespace: biological_process

id: GO:2001269
name: positive regulation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway
namespace: biological_process

id: GO:2001270
name: regulation of cysteine-type endopeptidase activity involved in execution phase of apoptosis
namespace: biological_process

id: GO:2001271
name: negative regulation of cysteine-type endopeptidase activity involved in execution phase of apoptosis
namespace: biological_process

id: GO:2001272
name: positive regulation of cysteine-type endopeptidase activity involved in execution phase of apoptosis
namespace: biological_process

**Comment by pgaudet** [comment]
Definitely the BPs should be obsoleted. 

WRT MFs: these terms were created to represent 'caspase activity', but the intention was not to explicitly name 'caspase' because that represents a gene product (or a class of gene products). These can be merged up but I wonder if the community expects to be able to find 'caspase' in GO; it's really widely used, we may want to keep it.

**Comment by sjm41** [comment]
> WRT MFs: these terms were created to represent 'caspase activity', but the intention was not to explicitly name 'caspase' because that represents a gene product (or a class of gene products). These can be merged up but I wonder if the community expects to be able to find 'caspase' in GO; it's really widely used, we may want to keep it.

Ah, OK, then it makes sense to keep those MFs.

But given we have those apoptotic-specific terms, then I'd remove the two caspase synonyms from the more general parent term:
id: GO:0004197
name: cysteine-type endopeptidase activity
def: "Catalysis of the hydrolysis of internal, alpha-peptide bonds in a polypeptide chain by a mechanism in which the sulfhydryl group of a cysteine residue at the active center acts as a nucleophile."
**synonym: "caspase activity" NARROW [GOC:mtg_apoptosis]**
synonym: "lysosomal cysteine-type endopeptidase" NARROW []
**synonym: "metacaspase activity" NARROW [GOC:mtg_apoptosis]**
synonym: "thiol endopeptidase activity" EXACT []
xref: EC:3.4.22.-
is_a: GO:0004175 ! endopeptidase activity
is_a: GO:0008234 ! cysteine-type peptidase activity

**Comment by pgaudet** [comment]
@raymond91125 Would you please run an annotation review so we can decide how to proceed?

**Comment by raymond91125** [comment]
> @raymond91125 Would you please run an annotation review so we can decide how to proceed?

Annotation review for MF's also?

**Comment by raymond91125** [comment]
@raymond91125 test bump

**Comment by raymond91125** [comment]
@pgaudet Do you think we are ready to proceed with obsoleting all these BP and MF terms Steven listed above?

**Comment by pgaudet** [comment]
It looks like people have not yet reviewed their annotations. Can you ping them? 

We cannot automatically assign the annotations to 'regulation of apoptotic process' or 'apoptotic process'. 

Thanks, Pascale

**Comment by raymond91125** [comment]
Also obsoleted
GO:0008635 activation of cysteine-type endopeptidase activity involved in apoptotic process by cytochrome c

**Comment by raymond91125** [comment]
@deustp01 Apologies. It is replaced by GO:2001056 positive regulation of cysteine-type endopeptidase activity

**Comment by deustp01** [comment]
Thanks. Now both MF and BP terms have been patched in Reactome.

**Comment by pgaudet** [comment]
Hi @raymond91125 

GO:2001056 positive regulation of cysteine-type endopeptidase activity should also be obsoleted, as a single step BP. This could perhaps be replaced by [cysteine-type endopeptidase activator activity](http://purl.obolibrary.org/obo/GO_0140608), if this is the activity of the gene (and not just upstream). 

Thanks, Pascale

**Comment by paola-scibite** [comment]
Hi @pgaudet et al, I hope you are all well.
I was part of the GOC:mtg_apoptosis working group back when of course GO-CAM models didn't exist. Two quick thoughts:

1. In case it helps, you can find details of the thought process behind wanting to keep "caspase" in synonyms [here](https://wiki.geneontology.org/Apoptosis_Curation_Manual#Annotations_to_caspase-related_terms_(“molecular_function”_branch_of_GO)) and [here](https://sourceforge.net/p/geneontology/ontology-requests/8481/). Hence, I think it'd be nice to keep the two narrow synonyms listed [here](https://github.com/geneontology/go-ontology/issues/28468#issuecomment-2225224359).
2. The [Apoptosis Curation Manual](https://wiki.geneontology.org/Apoptosis_Curation_Manual#Annotations_to_caspase-related_terms_(“molecular_function”_branch_of_GO)) was written back then, on curators' request. It's quite possible that nobody knows it even exists now, but in case anyone still refers to it, you might want to add a link from it to this obsoletion ticket.

Thank you, and take care!

Paola

**Comment by deustp01** [comment]
> GO:2001056 positive regulation of cysteine-type endopeptidase activity should also be obsoleted, as a single step BP.

So what does that do to the patch I just made? The pathway / process in question is [R-HSA-111459](https://reactome.org/PathwayBrowser/#/R-HSA-111459) "Activation of caspases through apoptosome-mediated cleavage" - a small (two-step) but distinctive step in the overall process of apoptosis. So, two questions: first, are you really sure that GO:2001056 is not a legitimate BP, and second, if so, what BP does fit our caspase activation process / pathway?

**Comment by raymond91125** [comment]
@deustp01 As suggested by Pascale, would GO:0140608 cysteine-type endopeptidase activator activity work in the "Activation of caspases through apoptosome-mediated cleavage" case?

**Comment by raymond91125** [comment]
@pgaudet Was I not supposed to obsolete the MFs? They are mixing MF and BP.

id: GO:0097153
name: cysteine-type endopeptidase activity involved in apoptotic process

id: GO:0097199
name: cysteine-type endopeptidase activity involved in apoptotic signaling pathway

id: GO:0097200
name: cysteine-type endopeptidase activity involved in execution phase of apoptosis

**Comment by deustp01** [comment]
No. To us, this looks like a process / pathway, not a single-step molecular function - see the Reactome web page [R-HSA-111459](https://reactome.org/PathwayBrowser/#/R-HSA-111459) "Activation of caspases through apoptosome-mediated cleavage" - so I need an alternative biological process term.

**Comment by raymond91125** [comment]
For BP, I think what may work is GO:0097190 apoptotic signaling pathway.

**Comment by raymond91125** [comment]
@pgaudet GO:2000116 regulation of cysteine-type endopeptidase activity and children have a total of 362 EXP annotations. I wanted to make sure that we are ready to start the obsoletion request.

**Comment by raymond91125** [comment]
These are all the child terms to be obsoleted.
regulation of cysteine-type endopeptidase activity (GO:2000116)
negative regulation of cysteine-type endopeptidase activity (GO:2000117)
inhibition of cysteine-type endopeptidase activity (GO:0097340)
inhibition of cysteine-type endopeptidase activity involved in apoptotic process (GO:1990001)
negative regulation of cysteine-type endopeptidase activity involved in apoptotic process (GO:0043154)
inhibition of cysteine-type endopeptidase activity involved in apoptotic process (GO:1990001)
negative regulation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway (GO:2001268)
negative regulation of cysteine-type endopeptidase activity involved in execution phase of apoptosis (GO:2001271)
positive regulation of cysteine-type endopeptidase activity (GO:2001056)
activation of cysteine-type endopeptidase activity (GO:0097202)
positive regulation of cysteine-type endopeptidase activity involved in apoptotic process (GO:0043280)
activation of cysteine-type endopeptidase activity involved in apoptotic process (GO:0006919)
activation of cysteine-type endopeptidase activity involved in apoptotic process by cytochrome c (GO:0008635)
positive regulation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway (GO:2001269)
activation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway (GO:0097296)
positive regulation of cysteine-type endopeptidase activity involved in execution phase of apoptosis (GO:2001272)
regulation of cysteine-type endopeptidase activity involved in apoptotic process (GO:0043281)
negative regulation of cysteine-type endopeptidase activity involved in apoptotic process (GO:0043154)
inhibition of cysteine-type endopeptidase activity involved in apoptotic process (GO:1990001)
negative regulation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway (GO:2001268)
negative regulation of cysteine-type endopeptidase activity involved in execution phase of apoptosis (GO:2001271)
positive regulation of cysteine-type endopeptidase activity involved in apoptotic process (GO:0043280)
activation of cysteine-type endopeptidase activity involved in apoptotic process (GO:0006919)
activation of cysteine-type endopeptidase activity involved in apoptotic process by cytochrome c (GO:0008635)
positive regulation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway (GO:2001269)
activation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway (GO:0097296)
positive regulation of cysteine-type endopeptidase activity involved in execution phase of apoptosis (GO:2001272)
regulation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway (GO:2001267)
negative regulation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway (GO:2001268)
positive regulation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway (GO:2001269)
activation of cysteine-type endopeptidase activity involved in apoptotic signaling pathway (GO:0097296)
regulation of cysteine-type endopeptidase activity involved in execution phase of apoptosis (GO:2001270)
negative regulation of cysteine-type endopeptidase activity involved in execution phase of apoptosis (GO:2001271)
positive regulation of cysteine-type endopeptidase activity involved in execution phase of apoptosis (GO:2001272)
