### ISSUE TITLE
regulation of protein dephosphorylation (obsoletion candidate)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28499]
regulation of protein dephosphorylation branch 

branch has only 86 EXP  fairly distributed across resources,

(needs 'obsoletion candidate" not "do not annotate flag")

**Comment by ValWood** [comment]
@pgaudet  do you want me to do this one?
Considering the low number of annotations  should w proceed straight to obsoletion?

**Comment by pgaudet** [comment]
@ValWood and I just looked at this - there are few enough annotations to obsolete.

@raymond91125 can you please take this one? 

This is the full list of terms: 

- [ ] negative regulation of myosin-light-chain-phosphatase activity
- [ ] regulation of peptidyl-serine dephosphorylation
- [ ] negative regulation of peptidyl-serine dephosphorylation
- [ ] positive regulation of peptidyl-serine dephosphorylation
- [ ] negative regulation of protein dephosphorylation
- [ ] positive regulation of protein dephosphorylation
- [ ] regulation of endoplasmic reticulum stress-induced eIF2 alpha dephosphorylation
- [ ] positive regulation of endoplasmic reticulum stress-induced eIF2 alpha dephosphorylation
- [ ]

**Comment by raymond91125** [comment]
These terms are regulation of a molecular function.
Related tickets
https://github.com/geneontology/go-ontology/issues/27626
https://github.com/geneontology/go-ontology/issues/28482

**Comment by pgaudet** [comment]
Right, this is what I was suggesting to use the list in my comment above (https://github.com/geneontology/go-ontology/issues/28499#issuecomment-2236592183) but we can go ahead and use the list you generated. These are very closely related, it makes sense to do them together.
