### ISSUE TITLE
updates for BP GO:0019640 glucuronate catabolic process to xylulose 5-phosphate (term name, definition, hierarchy, Xref)

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#28494]
For GO:0019640 glucuronate catabolic process to xylulose 5-phosphate:

- the pathway is specific for D-glucuronate and D-xylulose 5-phosphate
There is a caveat for D-xylulose 5-phosphate. The other BP that include this chemical all use xylulose 5-phosphate (children of term GO:0051167), normally is should have been D-xylulose 5-phosphate.
Is it better to leave xylulose 5-phosphate to avoid the mismatch?

- the current definition is less specific than the GO term name suggests. The current meaning is more or less identical to  GO:0042840 D-glucuronate catabolic process

**GO:0042840 D-glucuronate catabolic process**
The chemical reactions and pathways resulting in the breakdown of D-glucuronate, the D-enantiomer of glucuronate.

**GO:0019640 glucuronate catabolic process to xylulose 5-phosphate**
The chemical reactions and pathways resulting in the breakdown of glucuronate into other compounds, including xylulose 5-phosphate.

- Could MetaCyc:[PWY-5525](https://biocyc.org/pathway?orgid=META&id=PWY-5525) be added as an Xref as it covers the first steps of the pathway?

Proposed changes (highlighted in bold):

id: GO:0019640
name: **D-glucuronate catabolic process to D-xylulose 5-phosphate**
def: "**The chemical reactions and pathways resulting in the breakdown of D-glucuronate into D-xylulose 5-phosphate**." [GOC:go_curators]
synonym: "glucuronate breakdown to xylulose 5-phosphate" EXACT []
synonym: "glucuronate degradation to xylulose 5-phosphate" EXACT []
**xref: MetaCyc:PWY-5525 NARROW**
is_a: GO:1901159 ! xylulose 5-phosphate biosynthetic process
**is_a: GO:0042840! D-glucuronate catabolic process**
intersection_of: GO:0009056 ! catabolic process
intersection_of: **has_primary_input CHEBI:15748 ! D-glucuronate**
intersection_of: **has_primary_output CHEBI:57737 !D-xylulose 5-phosphate(2−)**

**Comment by raymond91125** [comment]
From PMID:27189775
![image](https://github.com/user-attachments/assets/72369141-8b3b-4ad9-974f-a0730f30d910)

**Comment by raymond91125** [comment]
GO:0042840 D-glucuronate catabolic process already has MetaCyc:PWY-5525 as an XREF.
