### ISSUE TITLE
Fix remaining cases of terms with duplicated MetaCyc xref

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28503]
Remaining cases to fix, identified in #28146:

---

MetaCyc:BUTYRATE--COA-LIGASE-RXN, MetaCyc:,http://purl.obolibrary.org/obo/GO_0120515;http://purl.obolibrary.org/obo/GO_0031956

id: GO:0120515
name: fatty acid-CoA ligase activity
namespace: molecular_function
def: "Catalysis of the reaction: a fatty acid + ATP + CoA = a fatty acyl-CoA + AMP + diphosphate." [RHEA:38883]
xref: MetaCyc:BUTYRATE--COA-LIGASE-RXN {source="skos:exactMatch"}
xref: RHEA:38883 {source="skos:exactMatch"}
is_a: GO:0015645 ! fatty acid ligase activity
is_a: GO:0016405 ! CoA-ligase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28199" xsd:anyURI
created_by: sjm
creation_date: 2024-06-25T12:17:07Z

id: GO:0047760
name: obsolete butyrate-CoA ligase activity
namespace: molecular_function
def: "OBSOLETE. Catalysis of the reaction: ATP + an acid + CoA = AMP + diphosphate + an acyl-CoA." [MetaCyc:BUTYRATE--COA-LIGASE-RXN]
comment: This term was obsoleted because it represents a specific substrate of medium-chain fatty acid-CoA ligase activity ; GO:0031956.
xref: MetaCyc:BUTYRATE--COA-LIGASE-RXN
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25800" xsd:anyURI
is_obsolete: true
replaced_by: GO:0031956

- [x] remove xref from obsolete term

---

MetaCyc:NPGLUCAT-PWY, MetaCyc:,http://purl.obolibrary.org/obo/GO_0019595;http://purl.obolibrary.org/obo/GO_0061680

- [x] Addressed in #28392

---

MetaCyc:RXN-9385, MetaCyc:,http://purl.obolibrary.org/obo/GO_0052754;http://purl.obolibrary.org/obo/GO_0043910

id: GO:0052754 [NO ANNOTATIONS]
name: GTP:coenzyme F420 guanyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: GTP + factor gamma-F420-2 + H+ = coenzyme F390-G + diphosphate." [GOC:mengo_curators, MetaCyc:RXN-9385]
synonym: "coenzyme F390-G synthetase activity" EXACT []
synonym: "GTP:coenzyme F420 guanylyltransferase activity" EXACT []
xref: MetaCyc:RXN-9385 {source="skos:exactMatch"}
is_a: GO:0070568 ! guanylyltransferase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28324" xsd:anyURI
created_by: ai
creation_date: 2011-09-22T03:25:30Z

id: GO:0043910 [NO ANNOTATIONS]
name: ATP:coenzyme F420 adenylyltransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: ATP + factor gamma-F420-2 + H+ = coenzyme F390-A + diphosphate." [GOC:jl, MetaCyc:RXN-9385, PMID:7957247, PMID:8550473]
synonym: "ATP:coenzyme F420 adenyltransferase activity" EXACT []
synonym: "coenzyme F390-A synthetase activity" EXACT []
xref: MetaCyc:RXN-9385
is_a: GO:0070566 ! adenylyltransferase activity

- [x] Replace MetaCyc xref on GO:0052754 with MetaCyc :RXN-18273 (or we could just delete both entries given they haven't been used in the 13 years since creation....)

---

MetaCyc:RXN-8307, 
MetaCyc:, http://purl.obolibrary.org/obo/GO_0102654;http://purl.obolibrary.org/obo/GO_0102843

id: GO:0102654  [2 ANNOTATIONS BY UP]
name: palmitoyl-[glycerolipid] 3-(E)-desaturase activity
namespace: molecular_function
def: "Catalysis of the reaction: a 1-acyl-2-hexadecanoyl-glycerolipid + 2 H+ + O2 + 2 reduced [2Fe-2S]-[ferredoxin] = a 1-acyl-2-[(3E)-hexadec-3-enoyl]-glycerolipid + 2 H2O + 2 oxidized [2Fe-2S]-[ferredoxin]. The this activity introduces an unusual trans double bond at carbon 3 of a palmitoyl group attached to the sn-2 position of glycerolipids." [RHEA:46764]
synonym: "1-18:1-2-16:0-phosphatidylglycerol trans-3 desaturase activity" RELATED []
xref: EC:1.14.19.43 {source="skos:exactMatch"}
xref: MetaCyc:RXN-16053 {source="skos:exactMatch"}
xref: MetaCyc:RXN-1725 {source="skos:narrowMatch"}
xref: MetaCyc:RXN-8307 {source="skos:narrowMatch"}
xref: MetaCyc:RXN-8318 {source="skos:narrowMatch"}
xref: MetaCyc:RXN-8319 {source="skos:narrowMatch"}
xref: RHEA:46764 {source="skos:exactMatch"}
is_a: GO:0016717 ! oxidoreductase activity, acting on paired donors, with oxidation of a pair of donors resulting in the reduction of molecular oxygen to two molecules of water
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28070" xsd:anyURI
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28362" xsd:anyURI

id: GO:0102843  [1 ANNOTATION BY UP]
name: palmitoyl-[glycerolipid] 7-desaturase activity
namespace: molecular_function
def: "Catalysis of the reaction: a 1-acyl-2-hexadecanoyl-glycerolipid + 2 H+ + O2 + 2 reduced [2Fe-2S]-[ferredoxin] = a 1-acyl-2-[(7Z)-hexadecenoyl]-glycerolipid + 2 H2O + 2 oxidized [2Fe-2S]-[ferredoxin]." [RHEA:46756]
synonym: "1-18:2-2-16:0-monogalactosyldiacylglycerol desaturase activity (SN2-16:1 forming)" EXACT []
xref: EC:1.14.19.42 {source="skos:exactMatch"}
xref: MetaCyc:RXN-16048 {source="skos:exactMatch"}
xref: MetaCyc:RXN-1728 {source="skos:narrowMatch"}
xref: MetaCyc:RXN-8304 {source="skos:narrowMatch"}
xref: MetaCyc:RXN-8307 {source="skos:narrowMatch"}
xref: RHEA:46756 {source="skos:exactMatch"}
is_a: GO:0016717 ! oxidoreductase activity, acting on paired donors, with oxidation of a pair of donors resulting in the reduction of molecular oxygen to two molecules of water
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28070" xsd:anyURI
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28363" xsd:anyURI

- [x] Remove MetaCyc:RXN-8307 {source="skos:narrowMatch"} from GO:0102654

---

MetaCyc:RXN-10884
MetaCyc:,http://purl.obolibrary.org/obo/GO_0052625;http://purl.obolibrary.org/obo/GO_0102085

id: GO:0052625  [1 ANNOTATION BY TAIR]
name: 4-aminobenzoate amino acid synthetase activity
namespace: molecular_function
def: "Catalysis of the reaction: 4-aminobenzoate + L-glutamate + ATP = N-(4-aminobenzoyl)-L-glutamate + AMP + diphosphate + H+." [MetaCyc:RXN-10884, PMID:19189963]
synonym: "4-aminobenzoyl amino acid synthetase activity" EXACT []
synonym: "p-aminobenzoate amino acid synthetase activity" EXACT []
synonym: "p-aminobenzoyl amino acid synthetase activity" EXACT []
synonym: "pABA amino acid synthetase activity" EXACT []
xref: MetaCyc:RXN-10884 {source="skos:exactMatch"}
is_a: GO:0016881 ! acid-amino acid ligase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28324" xsd:anyURI

id: GO:0102085  [NO ANNOTATIONS]
name: N-(4-aminobenzoyl)-L-glutamate synthetase activity
namespace: molecular_function
def: "Catalysis of the reaction: 4-aminobenzoate + L-glutamate + ATP = H+ + p-aminobenzoyl glutamate + AMP + diphosphoric acid." [EC:6.3.-.-, GOC:pz]
xref: MetaCyc:RXN-10884
is_a: GO:0016879 ! ligase activity, forming carbon-nitrogen bonds

- [x] Merge GO:0102085 into GO:0052625 (though I prefer the name on GO:0102085)

---

MetaCyc:RXN-10885
MetaCyc:,http://purl.obolibrary.org/obo/GO_0052627;http://purl.obolibrary.org/obo/GO_0102086

id: GO:0052627  [1 ANNOTATION BY TAIR]
name: vanillate amino acid synthetase activity
namespace: molecular_function
def: "Catalysis of the reaction: vanillate + L-glutamate + ATP = N-vanillate-L-glutamate + AMP + diphosphate + H+." [MetaCyc:RXN-10885, PMID:19189963]
xref: MetaCyc:RXN-10885 {source="skos:exactMatch"}
is_a: GO:0016881 ! acid-amino acid ligase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28324" xsd:anyURI

id: GO:0102086  [NO ANNOTATIONS]
name: N-vanillate-L-glutamate synthetase activity
namespace: molecular_function
def: "Catalysis of the reaction: vanillate + L-glutamate(1-) + ATP = H+ + N-vanillate-L-glutamate + AMP + diphosphoric acid." [EC:6.3.-.-, GOC:pz]
xref: MetaCyc:RXN-10885
is_a: GO:0016879 ! ligase activity, forming carbon-nitrogen bonds

- [x] Merge GO:0102086 into GO:0052627 (though I prefer the name on GO: 0102086)

---

MetaCyc:RXN-10886,
MetaCyc:,http://purl.obolibrary.org/obo/GO_0052626;http://purl.obolibrary.org/obo/GO_0102087

id: GO:0052626 [1 ANNOTATION BY TAIR]
name: benzoate amino acid synthetase activity
namespace: molecular_function
def: "Catalysis of the reaction: benzoate + L-glutamate + ATP = N-benzoyl-L-glutamate + AMP + diphosphate + H+." [MetaCyc:RXN-10886, PMID:19189963]
synonym: "benzoyl amino acid synthetase activity" EXACT []
xref: MetaCyc:RXN-10886 {source="skos:exactMatch"}
is_a: GO:0016881 ! acid-amino acid ligase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28324" xsd:anyURI

id: GO:0102087 [NO ANNOTATIONS]
name: N-benzoyl-L-glutamate synthetase activity
namespace: molecular_function
def: "Catalysis of the reaction: benzoate + L-glutamate + ATP = H+ + N-benzoyl-L-glutamate + AMP + diphosphoric acid." [EC:6.3.-.-, GOC:pz]
xref: MetaCyc:RXN-10886
is_a: GO:0016879 ! ligase activity, forming carbon-nitrogen bonds

- [x] Merge GO:0102087 into GO:0052626 (though I prefer the name on GO: 0102087)

---

MetaCyc:RXN-10887,
MetaCyc:,http://purl.obolibrary.org/obo/GO_0052628;http://purl.obolibrary.org/obo/GO_0102088

id: GO:0052628 [2 ANNOTATIONS BY TAIR]
name: 4-hydroxybenzoate amino acid synthetase activity
namespace: molecular_function
def: "Catalysis of the reaction: 4-hydroxybenzoate + L-glutamate + ATP = N-(4-hydroxybenzoyl)-L-glutamate + AMP + diphosphate + H+." [MetaCyc:RXN-10887, PMID:19189963]
synonym: "4-hydroxybenzoyl amino acid synthetase activity" EXACT []
synonym: "4HBA amino acid synthetase activity" EXACT []
synonym: "p-hydroxybenzoate amino acid synthetase activity" EXACT []
synonym: "p-hydroxybenzoyl amino acid synthetase activity" EXACT []
xref: MetaCyc:RXN-10887 {source="skos:exactMatch"}
is_a: GO:0016881 ! acid-amino acid ligase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28324" xsd:anyURI

id: GO:0102088 [NO ANNOTATIONS]
name: N-(4-hydroxybenzoyl)-L-glutamate synthetase activity
namespace: molecular_function
def: "Catalysis of the reaction: 4-hydroxybenzoic acid + L-glutamate + ATP = H+ + N-(4-hydroxybenzoyl)-L-glutamate + AMP + diphosphoric acid." [EC:6.3.-.-, GOC:pz]
xref: MetaCyc:RXN-10887
is_a: GO:0016879 ! ligase activity, forming carbon-nitrogen bonds

- [ ] Merge GO:0102088 into GO:0052628 (though I prefer the name on GO:0102088)

**Comment by sjm41** [comment]
Hi @pgaudet Could you deal with the merges I've suggested above (or else reassign), thanks.

**Comment by pgaudet** [comment]
GO:0052625, GO:0052626, GO:0052627 and GO:0052628 are substrates of A. thaliana GH3.12
https://www.uniprot.org/uniprotkb/Q9LYU4/entry

> Catalyzes the conjugation of specific amino acids (e.g. Glu and possibly His, Lys, and Met) to their preferred acyl substrates (e.g. 4-substituted benzoates), in a magnesium ion- and ATP-dependent manner. Can use 4-substituted benzoates such as 4-aminobenzoate (pABA), 4-fluorobenzoate and 4-hydroxybenzoate (4-HBA), and, to a lesser extent, benzoate, vanillate and trans-cinnamate, but not 2-substituted benzoates and salicylic acid (SA), as conjugating acyl substrates.

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete the following terms because they each had another equivalent term in the ontology: 
- GO:0102085  N-(4-aminobenzoyl)-L-glutamate synthetase activity: represents the same activity as GO:0052625
- GO:0102086 N-vanillate-L-glutamate synthetase activity: represents the same activity as GO:0052627
- GO:0102087 N-benzoyl-L-glutamate synthetase activity: represents the same activity as GO:0052626
- GO:0102088 N-(4-hydroxybenzoyl)-L-glutamate synthetase activity: represents the same activity as GO:0052628

There are no annotations; these terms are not in any subsets. Mapping have been moved to the remaining terms. 

You can comment on the ticket: https://github.com/geneontology/go-ontology/issues/28503

Thanks, Pascale
