### ISSUE TITLE
Rhea alignment of glucosidase II

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28502]
GO:0106407 Glc2Man9GlcNAc2 oligosaccharide glucosidase activity

catalyses 2 steps
[https://www.rhea-db.org/rhea/55996](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.rhea-db.org%2Frhea%2F55996&data=05%7C02%7Cvw253%40universityofcambridgecloud.onmicrosoft.com%7C468799cf070e45e696a708dca5610df1%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638567083462054616%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=cHoknNDUBAKJXISCc6hAQomBXY2qWTB%2BXPGa10syY9U%3D&reserved=0)
[https://www.rhea-db.org/rhea/56000](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.rhea-db.org%2Frhea%2F56000&data=05%7C02%7Cvw253%40universityofcambridgecloud.onmicrosoft.com%7C468799cf070e45e696a708dca5610df1%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638567083462065725%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=aInc0Z5AQ8Ov2wfvKNRvii74FSKYEU4ZI5%2FrAaLpzMc%3D&reserved=0)

**Comment by pgaudet** [comment]
Also added EC:3.2.1.207 
Added both RHEAs as narrow 

It would be nice for RHEA to create an overall reaction

**Comment by ValWood** [comment]
It's 2 separate steps though?

**Comment by pgaudet** [comment]
This is why an overall reaction would be nice - right?

**Comment by ValWood** [comment]
I guess so. It's an odd case. Normally we would not have separate activities for this because it's the same reaction twice, but for the rest of the pathway we have precise activities with respect to the dolichol structure:
https://www.pombase.org/term_genes/GO:0006488 (here the product largely mirror the MF terms)

I guess this 'trimming' is a  subsequent QC step and does not really need the individual steps to be described  (but I can see why it has been based on the rest of the pathway). In an ideal world I guess it would be a single activity, but it doesn't lead to inconsistent annotation (i.e 2 ways to describe the same thing) so for now we can sit on it. It might be nice to look at these edge cases in some sort of jamboree later.
