### ISSUE TITLE
Term definitions and scope of GO:0052695 cellular glucuronidation and GO:0019390 glucuronoside biosynthetic process

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#28506]
GO terms:

> **GO:0052695	cellular glucuronidation**
> The modification of an organic chemical by the conjugation of glucuronic acid. The substances resulting from glucuronidation are known as glucuronosides (or glucuronides) and are often much more water-soluble than the non-glucuronic acid-containing precursor. 
> 
> **GO:0036234	deglucuronidation**
> The removal of glucuronic acid from a conjugated substrate.

 and 

> **GO:0019390	name: glucuronoside biosynthetic process**
> The chemical reactions and pathways resulting in the formation of glucuronosides, compound composed of a hydroxy compound linked to a glucuronate residue.
> **GO:0019391	name: glucuronoside catabolic process**
> The chemical reactions and pathways resulting in the breakdown of glucuronosides, compound composed of a hydroxy compound linked to a glucuronate residue.

Based on their definition and how proteins involved in these processes are annotated I am not sure in which context they should be used (or what is the difference between them). At the moment, I have the impression that they mean more or less the same.

![image](https://github.com/user-attachments/assets/322ded4d-1dde-4e2e-b551-be811bbd368b)

Glucuronides (or glucuronosides) are produced by linking glucuronic acid (GlcA) (provided by UDP-GlcA) to a molecule via a glycosidic bond.
The molecule can be:
- endogenous substances (e.g., bilirubin)
- drugs
- xenobiotics (e.g., environmental toxins)
- also the same reaction is part of the synthesis of:
- tetrasaccharide linkage used for glycosaminoglycan biosynthesis (Ser/Thr- Xyl - Gal - Gal- GlcA)
- part of the repeat disaccharide unit of Heparin/Heparan sulfate (HS) and chondroitin sulfate (CS)/dermatan sulfate (DS)

Examples of annotation:

PMID: 22294686 was used to create the GO term deglucuronidation. In the paper they characterised ABHD10. For the annotation based on this paper GO glucuronoside catabolic process instead/ of GO cellular glucuronidation was used.

GO:0019391	glucuronoside catabolic process	 IDA 	PMID: 22294686
GO:0052695	cellular glucuronidation			TAS		Reactome

For mouse Gusb:
GO:0030200	heparan sulfate proteoglycan catabolic process	(IMP)
GO:0019391	glucuronoside catabolic process		ECO:0000314	(IDA)
the assay use artificial compound hence the glucuronoside catabolic process.

**Comment by pgaudet** [comment]
Yes, all cellular terms should be merged. 

@raymond91125 Would you please merge GO:0052695 cellular glucuronidation into GO:0036234 deglucuronidation  ?

**Comment by raymond91125** [comment]
Shouldn't it be that:
1. GO:0052695 cellular glucuronidation merged into GO:0019390 name: glucuronoside biosynthetic process
2. GO:0036234 deglucuronidation merged into GO:0019391 name: glucuronoside catabolic process

However, should they be obsoleted because they are one-step processes corresponding to GO:0008194 UDP-glycosyltransferase activity and glucuronidase esterase activity (not sure of the proper GO term, or if we need a new one), respectively?

**Comment by pgaudet** [comment]
Good points - I hadn't looked at the terms closely. 

Looks like this branch could also be obsoleted: 
- GO:0019389 glucuronoside metabolic process
- GO:0019390 glucuronoside biosynthetic process (as you mentioned)
-  GO:0019391 glucuronoside catabolic process

4 EXP total. 


@rozaru I am not sure how you came across these terms; would you miss them? 

Thanks, Pasacale

**Comment by rozaru** [comment]
I was working on the glucuronate and UDP-glucuronate (UDP-GlcA) pathways. It is when I looked at the annotation of the enzymes involving UDP-GlcA that I found these GO terms and thought that their definition looked similar.

"glucuronidation" is the term used in the literature to describe the process and usually refers to addition of GlcA to a molecule to make it more soluble so that it can be excreted.

@raymond91125 is right, those terms represent in fact a one step reaction.

-------
For **glucuronidation/glucuronoside biosynthetic process** the MF GO term GO:0015020 glucuronosyltransferase activity and its children would cover it.
In terms of BP, depending on the context these and their relevant children could be used:

protein glucuronation
GO:0006486 protein glycosylation
GO:0030166 proteoglycan biosynthetic process

xenobiotic glucuronation
GO:0042178 xenobiotic catabolic process
GO:1990748 cellular detoxification

etc..

-------
For **deglucuronidation/glucuronoside catabolic process** the MF GO term GO:0004566 beta-glucuronidase activity, GO:0046559 alpha-glucuronidase activity and, GO:0016788 esterase activity and their relevant children, would cover it.

For BP, glycoprotein catabolic process and its children could be used.

**Comment by pgaudet** [comment]
> Addressing @amandamackie 's comment in the Annotation review ticket - and to go back to what @rozaru wrote above: 

>  glucuronidation/glucuronoside biosynthetic process the MF GO term GO:0015020 glucuronosyltransferase activity and its children would cover it.

Since there are multiple activities, is this not a process?

**Comment by rozaru** [comment]
@pgaudet 
in this case, it's one reaction but depending on the substrate (glycan or xenobiotics) the enzyme is different, but they would normally belong to the glucosyltransferase activity. 
One of the EC is:[https://enzyme.expasy.org/EC/2.4.1.17]( https://enzyme.expasy.org/EC/2.4.1.17)

For this type of situation would a BP be OK?

**Comment by pgaudet** [comment]
I am not sure - this is the UniProt summary for https://www.uniprot.org/uniprotkb/O60656/entry


> UDP-glucuronosyltransferase (UGT) that catalyzes phase II biotransformation reactions in which lipophilic substrates are conjugated with glucuronic acid to increase the metabolite's water solubility, thereby facilitating excretion into either the urine or bile (PubMed:[12181437](https://www.uniprot.org/citations/12181437), PubMed:[15470161](https://www.uniprot.org/citations/15470161), PubMed:[15472229](https://www.uniprot.org/citations/15472229), PubMed:[18004212](https://www.uniprot.org/citations/18004212), PubMed:[18052087](https://www.uniprot.org/citations/18052087), PubMed:[18674515](https://www.uniprot.org/citations/18674515), PubMed:[19545173](https://www.uniprot.org/citations/19545173)).
Essential for the elimination and detoxification of drugs, xenobiotics and endogenous compounds (PubMed:[12181437](https://www.uniprot.org/citations/12181437), PubMed:[18004212](https://www.uniprot.org/citations/18004212)).
Catalyzes the glucuronidation of endogenous estrogen hormones such as estradiol and estrone (PubMed:[15472229](https://www.uniprot.org/citations/15472229)).
Also catalyzes the glucuronidation of the isoflavones genistein, daidzein, glycitein, formononetin, biochanin A and prunetin, which are phytoestrogens with anticancer and cardiovascular properties (PubMed:[18052087](https://www.uniprot.org/citations/18052087), PubMed:[19545173](https://www.uniprot.org/citations/19545173)).


GO:0019391 glucuronoside catabolic process is probably not the right process, but I am not sure what is - any suggestion?

**Comment by pgaudet** [comment]
Indeed the children should also be obsoleted - I suppose these are activities that lead to detoxification (for xenobiotics) or to modification (for flavenoids)? I just looked quickly, really annotations should be reviewed. 
I am sorry, I hadn't seen these terms had children.

**Comment by rozaru** [comment]
Looking back at the tread it seems that the GO term glucuronidation and deglucuronidation are going to be kept despite that they probably covers one reaction processes. Is that correct?

There are 60 experimental annotations to the term cellular glucuronidation and children. They all corresponds to genes that belong to the UDP-glucuronosyltransferase family that catalyses:
glucuronate acceptor + UDP-alpha-D-glucuronate = acceptor beta-D-glucuronoside + H+ + UDP
EC 2.4.1.17 (MF glucuronosyltransferase activity GO:0015020)

There is 1 experimental annotation to the term deglucuronidation and children (Palmitoyl-protein thioesterase ABHD10).

```
|__glucuronate metabolic process
           |__cellular glucuronidation
           |   |__acyl glucuronidation
           |   |__flavonoid glucuronidation
           |   |__xenobiotic glucuronidation
           |__deglucuronidation
           |   |__acyl deglucuronidation
```
Before I close this ticket, I was wondering if the "cellular" could be removed from cellular glucuronidation GO term name.

GO:0052695 cellular glucuronidation
The modification of an organic chemical by the conjugation of glucuronic acid. The substances resulting from glucuronidation are known as glucuronosides (or glucuronides) and are often much more water-soluble than the non-glucuronic acid-containing precursor.

**Comment by pgaudet** [comment]
Hi @rozaru 


I agree these terms should be obsoleted : 

deglucuronidation <http://purl.obolibrary.org/obo/GO_0036234>


'acyl glucuronidation' <http://purl.obolibrary.org/obo/GO_0036236>
'acyl deglucuronidation' <http://purl.obolibrary.org/obo/GO_0036235>
'protein glucuronidation' <http://purl.obolibrary.org/obo/GO_0018411>
'cellular glucuronidation' <http://purl.obolibrary.org/obo/GO_0052695>
'flavonoid glucuronidation' <http://purl.obolibrary.org/obo/GO_0052696>
'protein O-glucuronidation' <http://purl.obolibrary.org/obo/GO_0018412>
'xenobiotic glucuronidation' <http://purl.obolibrary.org/obo/GO_0052697>
'regulation of cellular glucuronidation' <http://purl.obolibrary.org/obo/GO_2001029>
'negative regulation of cellular glucuronidation' <http://purl.obolibrary.org/obo/GO_2001030>
'positive regulation of cellular glucuronidation' <http://purl.obolibrary.org/obo/GO_2001031>

(but maybe there are additional children?) 
But I dont think annotations should be transferred to 'x metabolic process'; these are also essentially MFs; the meaning is just 'x is converted into something else'. It's even more vague than a MF. 

We need an annotation review for these terms - @raymond91125 is there one? I could find it. 

Thanks, Pascale

**Comment by raymond91125** [comment]
- [ ] GO:0036234 deglucuronidation
- [ ] GO:0036235 acyl deglucuronidation
- [ ] GO:0036236 acyl glucuronidation
- [ ] GO:0018411 protein glucuronidation
- [ ] GO:0018412 protein O-glucuronidation
- [ ] GO:0052695 cellular glucuronidation
- [ ] GO:0036236 acyl glucuronidation
- [ ] GO:2001030 negative regulation of cellular glucuronidation
- [ ] GO:2001031 positive regulation of cellular glucuronidation
- [ ] GO:2001029 regulation of cellular glucuronidation
- [ ] GO:0052697 xenobiotic glucuronidation

**Comment by raymond91125** [comment]
Missed one
- [ ] GO:0052696 flavonoid glucuronidation

**Comment by raymond91125** [comment]
All done, I believe.
