### ISSUE TITLE
Pathway (BP) terms with multiple MetaCyc mappings

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28527]
The following 48 BP terms (and 1 CC term) each has multiple mappings to MetaCyc IDs.
Need to review to check if correct/makes sense, and (re)move any incorrect mappings.
I'm not sure if it will make sense to tag these with exact/broad/narrowMatch (like we do with catalytic activity terms)...I think there may be cases where several MetaCyc pathway variants are effectively all 'exactMatch'...but I'll report back here when I get chance. 

GO:0019285	glycine betaine biosynthetic process from choline
GO:0051596	methylglyoxal catabolic process
GO:0009088	threonine biosynthetic process
GO:0015940	pantothenate biosynthetic process
GO:0019643	reductive tricarboxylic acid cycle
GO:0006099	tricarboxylic acid cycle
GO:0030207	chondroitin sulfate catabolic process
GO:0030209	dermatan sulfate catabolic process
GO:0005992	trehalose biosynthetic process
GO:0005993	trehalose catabolic process
GO:0019653	anaerobic purine nucleobase catabolic process
GO:0009686	gibberellin biosynthetic process
GO:0019272	L-alanine biosynthetic process from pyruvate
GO:0019277	UDP-N-acetylgalactosamine biosynthetic process
GO:0015937	coenzyme A biosynthetic process
GO:0016132	brassinosteroid biosynthetic process
GO:0006055	CMP-N-acetylneuraminate biosynthetic process
GO:0006048	UDP-N-acetylglucosamine biosynthetic process
GO:0036172	thiamine salvage
GO:0006046	N-acetylglucosamine catabolic process
GO:0005980	glycogen catabolic process
GO:0006561	proline biosynthetic process
GO:0019358	nicotinate nucleotide salvage
GO:0005978	glycogen biosynthetic process
GO:0009051	pentose-phosphate shunt, oxidative branch
GO:0009052	pentose-phosphate shunt, non-oxidative branch
GO:0006065	UDP-glucuronate biosynthetic process
GO:0006633	fatty acid biosynthetic process
GO:0019592	mannitol catabolic process
GO:0019465	aspartate transamidation
GO:0010127	mycothiol-dependent detoxification
GO:0009257	10-formyltetrahydrofolate biosynthetic process
GO:0006526	arginine biosynthetic process
GO:0033386	geranylgeranyl diphosphate biosynthetic process
GO:0006032	chitin catabolic process
GO:0061611	mannose to fructose-6-phosphate catabolic process
GO:0033261	obsolete regulation of S phase
GO:0006636	unsaturated fatty acid biosynthetic process
GO:0019551	glutamate catabolic process to 2-oxoglutarate
GO:0042840	D-glucuronate catabolic process
GO:0019431	acetyl-CoA biosynthetic process from ethanol
GO:0035269	protein O-linked mannosylation
GO:0008654	phospholipid biosynthetic process
GO:0008295	spermidine biosynthetic process
GO:0033358	UDP-L-arabinose biosynthetic process
GO:0019676	ammonia assimilation cycle
GO:0019544	arginine catabolic process to glutamate
GO:0019545	arginine catabolic process to succinate
GO:0016612	molybdenum-iron nitrogenase complex

**Comment by rozaru** [comment]
I looked at the following GO terms.
The links are all valid for them. Mostly, they cover pathway variants that occur in different taxa.

- [x] GO:0030207 chondroitin sulfate catabolic process 
xref: MetaCyc:PWY-6572 Bacteria
xref: MetaCyc:PWY-6573 Metazoa

- [x] GO:0030209 dermatan sulfate catabolic process
xref: MetaCyc:PWY-6576 Metazoa
xref: MetaCyc:PWY-7646 Bacteria

- [x] GO:0005992 trehalose biosynthetic process
xref: MetaCyc:PWY-2622 Bacteria (1 step reaction)
xref: MetaCyc:PWY-2661 Bacteria
xref: MetaCyc:PWY-5983  Archaea, Thermotogae (1 step reaction)
xref: MetaCyc:PWY-5985 Deltaproteobacteria, Thermoprotei (1 step reaction)
xref: MetaCyc:PWY-881 Actinomycetota, Fungi
xref: MetaCyc:TREHALOSESYN-PWY Actinomycetota
xref: MetaCyc:TRESYN-PWY Arthropoda, Bacteria, Fungi

- [x] GO:0005993 trehalose catabolic process
xref: MetaCyc:PWY-2721 Bacillota
xref: MetaCyc:PWY-2722 Bacteria, Euglenozoa, Fungi
xref: MetaCyc:PWY-2723 Fungi
xref: MetaCyc:PWY0-1182 Arthropoda, Bacteria, Fungi
xref: MetaCyc:PWY0-1466 Bacteria, Fungi
xref: MetaCyc:TREDEGLOW-PWY Bacteria

- [x] GO:0019277 UDP-N-acetylgalactosamine biosynthetic process
xref: MetaCyc:PWY-5512 Bacteria, Euryarchaeota, Fungi, Metazoa (1 step reaction)
xref: MetaCyc:PWY-5514 Giardiinae
xref: MetaCyc:PWY-8013 Thermoproteota

- [x] GO:0006055 CMP-N-acetylneuraminate biosynthetic process
xref: MetaCyc:PWY-6138 Eukaryota
xref: MetaCyc:PWY-6139 Bacteria

- [x] GO:0006048 UDP-N-acetylglucosamine biosynthetic process
xref: MetaCyc:UDPNACETYLGALSYN-PWY Eukaryota
xref: MetaCyc:UDPNAGSYN-PWY Archaea, Baceria, Opisthokonta

- [x] GO:0006046 N-acetylglucosamine catabolic process
xref: MetaCyc:GLUAMCAT-PWY Bacteria, Fungi, Metazoa
xref: MetaCyc:PWY-6517 Bacteria, Fungi, Metazoa

- [x] GO:0005980 glycogen catabolic process
xref: MetaCyc:GLYCOCAT-PWY OK bacteria
xref: MetaCyc:PWY-5941 OK bacteria/Archea
xref: MetaCyc:PWY-7662 OK fungi

- [x] GO:0005978 glycogen biosynthetic process
See ticket [#28271](https://github.com/geneontology/go-ontology/issues/28271)
Pending ticket [#27467](https://github.com/geneontology/go-ontology/issues/27467) Currently the links are OK. If the new terms are created the xref will be split.
xref: MetaCyc:GLYCOGENSYNTH-PWY (ADP glc precursor) Bacteria
xref: MetaCyc:PWY-5067 (UDP glc precursor) Fungi, Metazoa
xref: MetaCyc:PWY-7900 ((from α-maltose 1-phosphate)) Bacteria

- [x] GO:0009051 pentose-phosphate shunt, oxidative branch
xref: MetaCyc:OXIDATIVEPENT-PWY Bacteria, Eukaryota
xref: MetaCyc:PWY-7796 Archaea

- [x] GO:0009052 pentose-phosphate shunt, non-oxidative branch
xref: MetaCyc:NONOXIPENT-PWY Bacteria, Eukaryota
xref: MetaCyc:PWY-8178 Bacteria, Entamoeba

- [x] GO:0006065 UDP-glucuronate biosynthetic process
xref: MetaCyc:PWY-4841 Embryophyta
xref: MetaCyc:PWY-7346 Archaea, Bacteria, Eukaryota

- [x] GO:0019592 mannitol catabolic process
xref: MetaCyc:MANNIDEG-PWY bacteria (1 step reaction)
xref: MetaCyc:PWY-3861 Tracheophyta

- [x] GO:0006032 chitin catabolic process
Note that the ontology has been simplified (see [#27960](https://github.com/geneontology/go-ontology/issues/27960))
xref: MetaCyc:PWY-6855 Archaea
xref: MetaCyc:PWY-6902 Actinomycetota, Bacillota, Bacteroidota, Opisthokonta, Pseudomonadota, Viridiplantae
xref: MetaCyc:PWY-7118 Opisthokonta (focus on acetate catabolism)
xref: MetaCyc:PWY-7822 Bacteria

- [x] GO:0061611 mannose to fructose-6-phosphate catabolic process
xref: MetaCyc:MANNCAT-PWY Archaea, Bacteria
xref: MetaCyc:PWY3O-1743  Archaea, Bacteria, Eukaryota

**Comment by rozaru** [comment]
- [ ] GO:0042840 D-glucuronate catabolic process 
xref: MetaCyc:PWY-5525 Vertebrata
xref: MetaCyc:PWY-6501 Bacteria
xref: MetaCyc:PWY-8390 Burkholderiaceae, Comamonadaceae, Pseudomonadaceae
Links above are correct but see ticket [#28494](https://github.com/geneontology/go-ontology/issues/28494)

To remove:
xref: MetaCyc:PWY-7247 Bacteria
start with a D-glucuronide so should go normally to BP GO term which has been made obsolete
id: GO:0019391
name: obsolete glucuronoside catabolic process
See ticket [#28506](https://github.com/geneontology/go-ontology/issues/28506)

**Comment by sjm41** [comment]
Looking at the remaining terms:

id: GO:0019285
name: glycine betaine biosynthetic process from choline
def: "The chemical reactions and pathways resulting in the formation of betaine (N-trimethylglycine) from the oxidation of choline." [GOC:jl]
xref: MetaCyc:BETSYN-PWY
xref: MetaCyc:CHOLINE-BETAINE-ANA-PWY
xref: MetaCyc:P542-PWY

---

id: GO:0051596
name: methylglyoxal catabolic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the breakdown of methylglyoxal, CH3-CO-CHO, the aldehyde of pyruvic acid." [GOC:ai]
synonym: "methylglyoxal breakdown" EXACT []
synonym: "methylglyoxal catabolism" EXACT []
synonym: "methylglyoxal degradation" EXACT []
xref: MetaCyc:METHGLYUT-PWY
xref: MetaCyc:Methylglyoxal-Detoxification

---

id: GO:0009088
name: threonine biosynthetic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the formation of threonine (2-amino-3-hydroxybutyric acid), a polar, uncharged, essential amino acid found in peptide linkage in proteins." [GOC:jl, ISBN:0198506732]
synonym: "threonine anabolism" EXACT []
synonym: "threonine biosynthesis" EXACT []
synonym: "threonine formation" EXACT []
synonym: "threonine synthesis" EXACT []
xref: MetaCyc:HOMOSER-THRESYN-PWY
xref: MetaCyc:THRESYN-PWY

---

id: GO:0015940
name: pantothenate biosynthetic process
def: "The chemical reactions and pathways resulting in the formation of pantothenate, the anion of pantothenic acid. It is a B complex vitamin that is a constituent of coenzyme A and is distributed ubiquitously in foods." [GOC:ai, ISBN:0721662544]
xref: MetaCyc:PANTO-PWY
xref: MetaCyc:PWY-3961

---

id: GO:0019643
name: reductive tricarboxylic acid cycle
namespace: biological_process
alt_id: GO:0019644
def: "A pathway leading to the fixation of two molecules of CO2 and the production of one molecule of acetyl-CoA; essentially the oxidative TCA cycle running in reverse. Acetyl-CoA is reductively carboxylated to pyruvate, from which all other central metabolites can be formed. Most of the enzymes of reductive and oxidative TCA cycle are shared, with the exception of three key enzymes that allow the cycle to run in reverse: ATP citrate lyase, 2-oxoglutarate:ferredoxin oxidoreductase, and fumarate reductase. 2-oxoglutarate:ferredoxin oxidoreductase catalyzes the carboxylation of succinyl-CoA to 2-oxoglutarate, ATP citrate lyase the ATP-dependent cleavage of citrate to acetyl-CoA and oxaloacetate, and fumarate reductase the reduction of fumarate forming succinate." [GOC:jl, PMID:15838028]
synonym: "reductive carboxylate cycle" EXACT []
synonym: "reductive carboxylic acid cycle" EXACT []
synonym: "reductive citric acid pathway" EXACT []
synonym: "reductive Kreb's cycle" EXACT []
synonym: "reductive TCA cycle" EXACT []
xref: MetaCyc:P23-PWY
xref: MetaCyc:REDCITCYC

**Comment by sjm41** [comment]
I will remove the "MetaCyc:CPLX*" xrefs on these terms:

id: GO:0016612
name: molybdenum-iron nitrogenase complex
def: "An enzyme complex containing a molybdenum-iron cluster found in many species. It is composed of two proteins, dinitrogenase and nitrogenase reductase; dinitrogenase, the molybdenum-iron protein, is tetrameric with an alpha2-beta2 structure, and nitrogenase reductase is a homodimer." [PMID:11566366]
xref: MetaCyc:CPLX-186
xref: MetaCyc:CPLX-525

id: GO:0043853
name: methanol-CoM methyltransferase complex
def: "A heterotrimeric protein complex composed of a methanol methyltransferase subunit, a corrinoid protein and a methanol-specific corrinoid:coenzyme M methyltransferase subunit. Catalyzes the transfer of a methyl group from methanol to coenzyme M as part of the pathway of methanogenesis from methanol." [PMID:9363780]
xref: MetaCyc:CPLX-421

id: GO:0140690
name: dihydropyrimidine dehydrogenase (NAD+) complex
def: "A heteromultimeric complex capable of dihydropyrimidine dehydrogenase (NAD+); in E. coli, composed of PreA and PreT." [PMID:21169495, PMID:34097066]
xref: MetaCyc:CPLX0-7788

id: GO:0009353
name: obsolete mitochondrial oxoglutarate dehydrogenase complex
def: "OBSOLETE. A mitochondrial complex of multiple copies of three enzymatic components: oxoglutarate dehydrogenase (lipoamide) (E1), dihydrolipoamide S-succinyltransferase (E2) and dihydrolipoamide dehydrogenase (E3); catalyzes the overall conversion of 2-oxoglutarate to succinyl-CoA and carbon dioxide (CO2) within the mitochondrial matrix." [GOC:mtg_sensu, MetaCyc:CPLX66-42, PMID:10848975]

**Comment by sjm41** [comment]
@pgaudet 
Just to recap what Rossana and I found in this ticket. Most/all of the BP terms with multiple MetaCyc xrefs are accurate - the multiple xrefs refer to pathway variants or taxa-specific versions that exactly match the GO def. In a few cases, it may be possible/appropriate to create new, more specific child terms that describe the pathway variant (using distinctions like "biosynthesis process from X" or "catabolic process via Y" etc), but for most cases it seems we have have multiple MetaCyc xrefs that c/should be accurately tagged as exactMatch matches.

If that's the case, then we would have to allow multiple EXACT MetaCyc xrefs on BP terms (but not MF or CC terms).

Unless you see an alternative?

**Comment by pgaudet** [comment]
If the various pathways are variants and taxon-specific pathways, I would rather use narrowMatch; or is there a problem with that?

**Comment by cmungall** [comment]
> I will remove the "MetaCyc:CPLX*" xrefs on these terms:
>
These seem fine? Is the think that we are so incomplete it's better to have
none rather than a useless handful?

**Comment by cmungall** [comment]
+1 to narrowMatch

If we go with the more specific terms we need to mark the existing ones as
do-not-annotate and manage the process of having all groups automatically
pushdown annotations to the taxon-specific subclasses.

Note we do have a semi-implemented undocumented DP for the via-X pathways,
many presumably created for alignment with metacyc/biocyc at some point in
the past, but I don't think this was implemented very consistently

**Comment by sjm41** [comment]
>>  I will remove the "MetaCyc:CPLX*" xrefs on these terms:
> These seem fine? Is the think that we are so incomplete it's better to have
> none rather than a useless handful?

Right, there were only 4 MetaCyc complex IDs x-reffed to GO-CC complex terms, which seems next to useless.  I don't believe we have a policy of trying to add external xrefs to GO terms to complexes (in MetaCyc, or in ComplexPortal or Reactome), but if wanted to introduce that we should do so systematically and via files provided by them.

**Comment by sjm41** [comment]
> If the various pathways are variants and taxon-specific pathways, I would rather use narrowMatch; or is there a problem with that?

I guess it's OK.
So, if we have a leaf GO-BP (metabolic pathway) term that describes a general pathway, and we have MetaCyc pathways that fit the BP description but are taxon-specific or otherwise alternative version of the pathway, then I will tag them as narrowMatch.
E.g. these types of case:

id: GO:0008654
name: phospholipid biosynthetic process
def: "The chemical reactions and pathways resulting in the formation of a phospholipid, a lipid containing phosphoric acid as a mono- or diester." [ISBN:0198506732]
xref: MetaCyc:PHOSLIPSYN-PWY = superpathway of phospholipid biosynthesis III (E. coli)
xref: MetaCyc:PHOSLIPSYN2-PWY = superpathway of phospholipid biosynthesis II (plants)

or

id: GO:0016132
name: brassinosteroid biosynthetic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the formation of brassinosteroids, any of a group of steroid derivatives that occur at very low concentrations in plant tissues and may have hormone-like effects." [ISBN:0192801023]
xref: MetaCyc:PWY-2582 = brassinolide biosynthesis II
xref: MetaCyc:PWY-699 = brassinolide biosynthesis I

**Comment by pgaudet** [comment]
Sounds good!

**Comment by cmungall** [comment]
MetaCyc also has pathway *classes* that more closely correspond to GO BP
classes

https://cabbi-biocyc.igb.illinois.edu/META/NEW-IMAGE?type=ECOCYC-CLASS&object=Phospholipid-Biosynthesis
https://cabbi-biocyc.igb.illinois.edu/META/NEW-IMAGE?type=ECOCYC-CLASS&object=Brassinosteroid-Biosynthesis

Loose analogy:

MetaCyc pathway classes - GO BP classes
MetaCyc pathways - GO-CAM templates
BioCyc pathways - GO-CAM species specific models

**Comment by sjm41** [comment]
Right, and MetaCyc also has "superpathways".  The following example has both as current xrefs:

id: GO:0051596
name: methylglyoxal catabolic process
def: "The chemical reactions and pathways resulting in the breakdown of methylglyoxal, CH3-CO-CHO, the aldehyde of pyruvic acid." [GOC:ai]
xref: MetaCyc:METHGLYUT-PWY = superpathway of methylglyoxal degradation
xref: MetaCyc:Methylglyoxal-Detoxification = grouping class for 10 degradation pathways

subpathways of METHGLYUT-PWY are:
[methylglyoxal degradation I](https://metacyc.org/pathway?orgid=META&id=PWY-5386)
[methylglyoxal degradation III](https://metacyc.org/pathway?orgid=META&id=PWY-5453)
[methylglyoxal degradation IV](https://metacyc.org/pathway?orgid=META&id=PWY-5459)
[L-lactaldehyde degradation (aerobic)](https://metacyc.org/pathway?orgid=META&id=PWY0-1317)

sub pathways of Methylglyoxal-Detoxification are:
[methylglyoxal degradation I](https://metacyc.org/pathway?orgid=META&id=PWY-5386)
[methylglyoxal degradation II](https://metacyc.org/pathway?orgid=META&id=PWY-5462)
[methylglyoxal degradation III](https://metacyc.org/pathway?orgid=META&id=PWY-5453)
[methylglyoxal degradation IV](https://metacyc.org/pathway?orgid=META&id=PWY-5459)
[methylglyoxal degradation V](https://metacyc.org/pathway?orgid=META&id=PWY-5458)
[methylglyoxal degradation VI](https://metacyc.org/pathway?orgid=META&id=MGLDLCTANA-PWY)
[methylglyoxal degradation VII](https://metacyc.org/pathway?orgid=META&id=PWY-5456)
[methylglyoxal degradation VIII](https://metacyc.org/pathway?orgid=META&id=PWY-5386-1)
[methylglyoxal degradation IX](https://metacyc.org/pathway?orgid=META&id=PWY-8458)
[methylglyoxal degradation X](https://metacyc.org/pathway?orgid=META&id=PWY8J2-23)

**Comment by cmungall** [comment]
Hmm, in this case the the metacyc class seems to be more semantically aligned with the GO class, since would would presumably group the same I-X, and our def matches their note: "_This class is a variant class, i.e. its purpose is to group together a set ofvariant pathways. Variant pathways are those that accomplish roughly the same biological function, such as degradation of a given starting material, or biosynthesis of an end product. The variant pathways may or may not share any common reactions._"

Do we know why the superpathway doesn't encompass all?

I would say try and make a single exact mapping to the most precise (the class), then everything else can be inferred

**Comment by cmungall** [comment]
Also of note in this case we have two subclasses:

* [] GO:0009438 ! methylglyoxal metabolic process
    * [i] **GO:0051596 ! methylglyoxal catabolic process**
        * [i] GO:0061727 ! methylglyoxal catabolic process to lactate
            * [i] GO:0019248 ! D-lactate biosynthetic process from methylglyoxal via (R)-lactaldehyde <-- never used for annotation
            * [i] GO:0019243 ! methylglyoxal catabolic process to D-lactate via S-lactoyl-glutathione 

The population of annotations is super lopsided christmas tree here. These subclasses don't seem to be doing us much good in terms of consistently discriminating among variants

**Comment by sjm41** [comment]
I made a second-pass through these ~50 GO-BP terms with multiple MetaCyc mappings, paying particular attention to the 'expected taxonomic range' associated for each pathway (as stated by MetaCyc) and the 'Class' to which each pathway is stated to belong within the MetaCyc pathway ontology. I edited the lists above to add this extra information.

Here are my observations/proposals:

1. Almost all of the MetaCyc pathway instances refer to taxon-specific variants, so I agree we should simply mark these as 'narrowMatch' xrefs to the given BP term. I'll go ahead and do this unless there are objections. (That will fix the original issue and allow #28146 to proceed!)

2. Currently, only one (GO:0051596) of these ~50 BP terms has a mapping to a MetaCyc 'Class'. So it seems mapping BPs to MetaCyc Classes is not something we've really done to date. As Chris said, these 'classes' are logically equivalent to GO-BP terms, so they could be added and tagged as 'exactMatch'. However, MetaCyc pathways don't always belong to a Class that equates to a BP term - e.g. an equivalent Class exists for 28 of the 46 non-obsolete BP terms in this list. So, I _could_ add these 28 Classes as new exactMatch xrefs, but coverage would be patchy (and of course I haven't looked at any mappings outside the current list). So, for now, I suggest I don't add Class mappings but I'll make a separate ticket to consider the pros/cons of doing so systematically.

3. Some MetaCyc pathways are associated with 'superpathways', defined in MetaCyc as "a class of metabolic pathways that are constructed by combining and connecting individual pathways (which can be shown separately) to depict relationships between them. In some cases those individual pathways start from a common precursor, or produce a common product, but they can have other relationships as well. Superpathways can have individual reactions as their components in addition to other pathways."
Despite this larger concept, there are several valid narrowMatch mappings to superpathways within the current list. So I suggest we just handle these the same as regular pathways, keeping them and marking them as narrowMatch or broadMatch as appropriate.

4. This exercise also revealed several other related issues (e.g. missing MetaCyc xrefs, incorrect MetaCyc xrefs, BP terms that are single steps and are really MFs etc) which I'll fix. These are noted above, but I'll make separate tickets for any significant issues.

5. From this exercise, it's possible that all current MetaCyc xrefs to BP terms (even 1:1 mappings) should be made narrowMatch. If so, that edit could be done computationally in bulk.

6. What about xrefs to other pathway databases? Following the above logic, it seems that all BP xrefs to Reactome pathways should be marked as 'narrowMatch' since they are specific to human pathways. In contrast, at least some mappings to KEGG_PATHWAY maps should be exactMatch since they are species/taxon agnostic, though others should be broad/narrow match where the KEGG pathway represents a broader/narrower concept than the BP term - a task for another day...

7. I'll also leave the question about whether or not GO wants to have some/all of the "process via X" pathway variants for another day.

**Comment by cmungall** [comment]
Thanks @sjm41, great work, and I agree with your analysis and proposed strategy!

**Comment by sjm41** [comment]
Hi @raymond91125.
I'm not sure I understand. MetaCyc:GLUCUROCAT-PWY is currently only an xref on GO:0019391 glucuronoside catabolic process - it is not an xref on GO:0042840 D-glucuronate catabolic process.
So the current situation seems to already represent what you are suggesting?  (Unless there have been edits since your post 3 days ago.)
