### ISSUE TITLE
Obsoletion request: Wnt signaling pathway involved in x

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28548]
Breaking down this large ticket: https://github.com/geneontology/go-ontology/issues/25766

Here are the terms for Wnt signaling pathway involved in x
GO:2000041 | negative regulation of planar cell polarity pathway involved in axis elongation
GO:2000151 | negative regulation of planar cell polarity pathway involved in cardiac muscle tissue morphogenesis
GO:2000168 | negative regulation of planar cell polarity pathway involved in neural tube closure
GO:2000164 | negative regulation of planar cell polarity pathway involved in outflow tract morphogenesis
GO:2000166 | negative regulation of planar cell polarity pathway involved in pericardium morphogenesis
GO:2000149 | negative regulation of planar cell polarity pathway involved in ventricular septum morphogenesis
GO:0003402 | planar cell polarity pathway involved in axis elongation
GO:0061350 | planar cell polarity pathway involved in cardiac muscle tissue morphogenesis
GO:0061349 | planar cell polarity pathway involved in cardiac right atrium morphogenesis
GO:0060775 | planar cell polarity pathway involved in gastrula mediolateral intercalation
GO:0061346 | planar cell polarity pathway involved in heart morphogenesis
GO:0090179 | planar cell polarity pathway involved in neural tube closure
GO:0061347 | planar cell polarity pathway involved in outflow tract morphogenesis
GO:0061354 | planar cell polarity pathway involved in pericardium morphogenesis
GO:0061348 | planar cell polarity pathway involved in ventricular septum morphogenesis
GO:2000040 | regulation of planar cell polarity pathway involved in axis elongation

A fresh review is here: https://github.com/geneontology/go-annotation/issues/5371

@raymond91105 can you please take this one? 

Thanks, Pascale

**Comment by raymond91125** [comment]
Also need to be obsoleted as obsoleted terms are in their LD.
GO:2000159 regulation of planar cell polarity pathway involved in heart morphogenesis
GO:2000160 negative regulation of planar cell polarity pathway involved in heart morphogenesis
GO:2000167 regulation of planar cell polarity pathway involved in neural tube closure
