### ISSUE TITLE
Obsoletion request: GO:0102028 cystathionine gamma-synthase activity (acts on O-phosphohomoserine) 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28545]
* **GO term ID and label for which you request a new superclass**

GO:0003962   cystathionine gamma-synthase activity 
GO:0102028	cystathionine gamma-synthase activity (acts on O-phosphohomoserine)

* **New superclass (parent) suggested**

There is no common parent, so we get an inference, even though we made a more specific annotation.

<img width="1255" alt="Screenshot 2024-07-19 at 14 52 01" src="https://github.com/user-attachments/assets/42baf3ea-7ba0-4d43-a7af-0bff852892ec">

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by pgaudet** [comment]
GO:0102028 cystathionine gamma-synthase activity (acts on O-phosphohomoserine) should be obsoleted and replaced by GO:0003962 cystathionine gamma-synthase activity (they share the same EC; GO:0102028 has no manual annotations). 

Thanks, Pascale
