### ISSUE TITLE
Missing parent: polyphosphate import into vacuole

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28540]
* **GO term ID and label for which you request a new superclass**

* **New superclass (parent) suggested**
vacuolar transport

Alerted by Inferred annotation:
<img width="846" alt="________GO MP" src="https://github.com/user-attachments/assets/07bf4672-ae6a-4591-b3ff-50e2c113fe96">

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by pgaudet** [comment]
This should be handled by logical definitions. There is an error in the LD: 

transport
 and ('has target end location' some 'vacuolar lumen')
 **_and ('has target end location' some cytosol)_**
 and ('results in transport across' some 'vacuolar membrane')
 and ('has primary input' some polyphosphate)


Cytosol should be the start location. 

Try it out and see if it works. 

Pascale
