### ISSUE TITLE
remove enzyme xrefs from obsolete terms

### ISSUE THREAD

**Issue by balhoff** [geneontology/go-ontology#28557]
First deal with this issue: #27821

**Comment by balhoff** [comment]
First output list of xrefs on obsolete terms, with term label, for review by @pgaudet.

**Comment by balhoff** [comment]
@pgaudet here are the obsolete terms that have xrefs: https://docs.google.com/spreadsheets/d/14gU8E-DHZOcIXKSqZj2ItFLHgFc_TsH8tWal2Tj4LzA/edit?gid=0#gid=0

**Comment by pgaudet** [comment]
Valid ECs in that list 

- [ ] [1.13.11.26](https://enzyme.expasy.org/EC/1.13.11.26)  peptide-tryptophan 2,3-dioxygenase
- [ ] [1.14.99.34](https://enzyme.expasy.org/EC/1.14.99.34) monoprenyl isoflavone epoxidase
- [ ] [2.5.1.117](https://enzyme.expasy.org/EC/2.5.1.117) homogentisate solanesyltransferase
- [ ] [2.5.1.41](https://enzyme.expasy.org/EC/2.5.41) phosphoglycerol geranylgeranyltransferase
- [ ] [2.5.1.42](https://enzyme.expasy.org/EC/2.5.42) geranylgeranylglycerol-phosphate geranylgeranyltransferase
- [ ] [2.7.11.29](https://enzyme.expasy.org/EC/2.7.11.29) [low-density-lipoprotein receptor] kinase >> _no associated entry in EC_
- [ ] [2.7.11.9](https://enzyme.expasy.org/EC/2.7.1..19)  [Goodpasture-antigen-binding protein] kinase >> _no associated entry in EC_
- [ ] [3.1.11.1](https://enzyme.expasy.org/EC/3.1.11.1) exodeoxyribonuclease I
- [ ] [3.1.11.2](https://enzyme.expasy.org/EC/3.1.11.2) exodeoxyribonuclease III
- [ ] [3.2.1.6](https://enzyme.expasy.org/EC/3.2.1.6) endo-1,3(4)-beta-glucanase
- [ ] [3.4.11.1](https://enzyme.expasy.org/EC/3.4.11.1) leucyl aminopeptidase
- [ ] [3.4.11.14](https://enzyme.expasy.org/EC/3.4.11.14) cytosol alanyl aminopeptidase
- [ ] [3.4.11.2](https://enzyme.expasy.org/EC/3.4.11.2) membrane alanyl aminopeptidase
- [ ] [3.4.11.22](https://enzyme.expasy.org/EC/3.4.11.22) aminopeptidase I
- [ ] [3.4.11.7](https://enzyme.expasy.org/EC/3.4.11.7) glutamyl aminopeptidase
- [ ] [3.4.13.19](https://enzyme.expasy.org/EC/3.4.13.19) membrane dipeptidase
- [ ] [3.4.15.1](https://enzyme.expasy.org/EC/3.4.15.1) peptidyl-dipeptidase A
- [ ] [3.4.15.5](https://enzyme.expasy.org/EC/3.4.15.5) peptidyl-dipeptidase Dcp
- [ ] [3.4.17.16](https://enzyme.expasy.org/EC/3.4.17.16) membrane Pro-Xaa carboxypeptidase
- [ ] [3.4.24.65](https://enzyme.expasy.org/EC/3.4.24.65) macrophage elastase
- [ ] [4.2.1.74](https://enzyme.expasy.org/EC/4.2.1.74) medium-chain-enoyl-CoA hydratase



- [ ] [RHEA:13221](https://www.rhea-db.org/rhea/13221) GO: obsolete mevaldate reductase (NADH) activity  >> _no associated entry in RHEA_
- [ ] [RHEA:17481](https://www.rhea-db.org/rhea/17481) GO:obsolete cob(II)alamin reductase activity >> _no associated entry in RHEA_; RHEA comments that this may occur spontaneously 
- [ ] [RHEA:20752](https://www.rhea-db.org/rhea/20752) GO: obsolete aquacobalamin reductase (NADPH) activity >> 4 entries; RHEA comments that this may occur spontaneously 
- [ ] [RHEA:24632](https://www.rhea-db.org/rhea/24632): GO:obsolete nitrite reductase NADPH activity; replaced by GO:0008942	nitrite reductase [NAD(P)H] activity
- [ ] [RHEA:28598](https://www.rhea-db.org/rhea/28598) >> _no associated entry in RHEA; deleted from KEGG
- [ ] [RHEA:33147](https://www.rhea-db.org/rhea/33147) obsolete ATPase-coupled daunorubicin transmembrane transporter activity

**Comment by pgaudet** [comment]
Also: 
GO:0102274 glutathione S-conjugate carboxypeptidase activity has no complete xrefs: added 
+xref: EC:3.4.17.25
+xref: RHEA:60448

**Comment by pgaudet** [comment]
Hi @balhoff 

I fixed all the xrefs I wanted to fix in the obsolete terms. You can go ahead and remove xrefs from obsolete terms.

Thanks, Pascale
