### ISSUE TITLE
Query RNA (cytidine(32)/uridine(32)-2'-O)-methyltransferase 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28550]
This is the first time I see this: RHEA has an OR in a reaction: 
https://www.rhea-db.org/rhea/42396 

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/82e24b62-10ca-4844-a063-c7ff8c20f748">

This is an exact match to EC:2.1.1.205 tRNA (cytidine(32)/guanosine(34)-2'-O)-methyltransferase, but GO has 2 reactions. 

----

However this one here is different, and RHEA created 2 reactions: 

<img width="1271" alt="image" src="https://github.com/user-attachments/assets/6e1e758b-590c-4137-81ed-c24f42023d97">

I think we should align with EC and have both substrates in the same reaction, for each of these 2 ECs. 

@sjm41 what do you think ? 

Thanks, Pascale

**Comment by sjm41** [comment]
> I think we should align with EC and have both substrates in the same reaction, for each of these 2 ECs.

Yes, I agree.

**Comment by raymond91125** [comment]
@sjm41 Is the following a correct summary? If so, I can implement.

| what we have |   |   |
|---|---|---|
|GO:0106339 tRNA (cytidine(32)-2'-O)-methyltransferase activity|EC:2.1.1.200/EC:2.1.1.205|RHEA:42396/RHEA:42932|
|GO:0106340 tRNA (guanine(34)-2'-O)-methyltransferase activity|EC:2.1.1.205|RHEA:42396|
|**WHAT WE WANT**|||
|GO:0106339/GO:016340 tRNA (cytidine(32)/guanosine(34)-2'-O)-methyltransferase activity|EC:2.1.1.205|RHEA:42396
|NTR tRNA (cytidine(32)/uridine(32)-2'-O)-methyltransferase activity|EC:2.1.1.200|RHEA:42932/RHEA:42936

**Comment by sjm41** [comment]
@raymond91125 I think that is correct, but I think we should wait for @pgaudet to confirm when she's back next week.

I realise that one potential issue with this change is what should be annotated if/when "(cytidine(32)-2'-O)-methyltransferase activity" is shown - would the curator then annotate with both the new GO terms?  We should look at current annotations (and their sources) to GO:0106339 and GO:0106340 to check on this.

**Comment by pgaudet** [comment]
This looks OK to me. I checked the annotation for both existing terms, GO:0106339  and GO:0106340, and they are greatly overlapping (most correspond to PTHR10920; others are either named 'tRNA (cytidine(32)/guanosine(34)-2'-O)-methyltransferase' and/or annotated to [Rhea 42396](https://www.rhea-db.org/rhea/42396). 


So @raymond91125 please go ahead with the plan you propose [above](https://github.com/geneontology/go-ontology/issues/28550#issuecomment-2272409064). 

Thanks, Pascale

**Comment by raymond91125** [comment]
EC:2.1.1.205 appears to be eukaryotic whereas EC:2.1.1.200 prokaryotic. Though should we create EC:2.1.1.200 tRNA (cytidine(32)/uridine(32)-2'-O)-methyltransferase activity right now before there is a request?

**Comment by pgaudet** [comment]
Yes I think this is what @raymond91125 had said in the proposal [above](https://github.com/geneontology/go-ontology/issues/28550#issuecomment-2272409064)

**Comment by raymond91125** [comment]
Also moved never_in Archaea from GO:0106339  to GO:0106340.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160206
+name: tRNA (cytidine(32)/uridine(32)-2'-O)-methyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: cytidine(32)/uridine(32) in tRNA + S-adenosyl-L-methionine = 2'-O-methylcytidine(32)/2'-O-methyluridine(32) in tRNA + H+ + S-adenosyl-L-homocysteine." [EC:2.1.1.200]
+synonym: "TrMet(Xm32) activity" EXACT []
+xref: EC:2.1.1.200
+xref: RHEA:42932 {source="skos:narrowMatch"}
+xref: RHEA:42936 {source="skos:narrowMatch"}
+is_a: GO:0008175 ! tRNA methyltransferase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28550" xsd:anyURI
+created_by: rynl
+creation_date: 2024-08-21T21:13:17Z
