### ISSUE TITLE
NTR: negative regulation of phospholipase C/protein kinase C signal transduction

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#28564]
Please provide as much information as you can: 

* **Suggested term label:**

 negative regulation of phospholipase C/protein kinase C signal transduction

* **Definition (free text)**

Any process that stops, prevents or reduces the frequency, rate or extent of phospholipase C/protein kinase C signal transduction. 

* **Reference, in format PMID:#######**
32033984

* **Gene product name and ID to be annotated to this term**

Q91WG7 Dgkg

* **Parent term(s)**
GO:1902532
GO:0141212

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
Proposed DGK gamma action
![image](https://github.com/user-attachments/assets/d2df7308-b24c-4e86-9856-47910b2c22a7)
