### ISSUE TITLE
NTR: Polaroplast

### ISSUE THREAD

**Issue by uermel** [geneontology/go-ontology#28569]
Please provide as much information as you can: 

* **Suggested term label:**

Polaroplast

* **Definition (free text)**

The polaroplast is a specialized structure within microsporidian spores that plays a crucial role in the germination and infection process. It is composed of multiple layers of membranes that swell during spore activation, contributing to the build-up of pressure inside the spore. This pressure is essential for the expulsion of the polar tube and the delivery of the sporoplasm into the host cell.

* **Reference, in format PMID:#######**
[DOI:10.1111/j.1462-5822.2009.01362.x](https://doi.org/10.1111/j.1462-5822.2009.01362.x)
[DOI:10.1016/j.ijpara.2005.04.003](https://doi.org/10.1016%2Fj.ijpara.2005.04.003)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**

GO: 0110165

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

https://en.wiktionary.org/wiki/polaroplast

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160201
+name: polaroplast
+namespace: cellular_component
+def: "A membrane-bounded organelle found in a microsporidian spore,  that swells with water, and exerts pressure to rupture the polar cap and evert the polar tube through which the sporoplasm escapes to infect the host." [PMID:16005007, PMID:19673893, Wikipedia:polaroplast]
+is_a: GO:0043231 ! intracellular membrane-bounded organelle
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28569" xsd:string
+created_by: rynl
+creation_date: 2024-07-25T22:10:47Z

**Comment by uermel** [comment]
Thanks @raymond91125! Do you know when this will be available?

**Comment by raymond91125** [comment]
@uermel It is available from GitHub GO project download. But I don't know how long it may take your curation tool to get the update. Sorry.

**Comment by uermel** [comment]
No worries, thanks again. We're using purl.obolibrary.org to link out, that's what I was referring to.

**Comment by pgaudet** [comment]
@cmungall Does purl.obolibrary.org  consume data from the GO release? How does that work ?

**Comment by cmungall** [comment]
I just got off a call with @uermel, we're all clear, but just for references, the OBO PURLs are just redirects, there is no separate ingests
