### ISSUE TITLE
NTR: positive regulation of 7-methylguanosine mRNA capping

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28568]
Please provide as much information as you can: 

* **Suggested term label:**

positive regulation of 7-methylguanosine mRNA capping

* **Definition (free text)**

standard definition

* **Reference, in format PMID:#######**

https://www.pombase.org/reference/PMID:19328067

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**

https://www.pombase.org/gene/SPBC19F8.07 (mcs6)
* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
Do you have a pathway for this? or it is a regulation of activity?

**Comment by raymond91125** [comment]
![gr7_lrg](https://github.com/user-attachments/assets/dcf209ae-b8d6-4864-bf9c-b4d0fd74f5cb)
The Mcs6 complex phosphorylates and primes the Pol II CTD (top), which facilitates recruitment of the Cdk9/Pcm1 complex to phosphorylate the CTD and Spt5, complete the 5′-cap structure, and relieve the Spt5-induced pause to elongation (bottom).

**Comment by ValWood** [comment]
This question comes up a lot @Antonialock  asked once.
(whether the TFIIH kinase/cyclin is regulation). I feel that it is because it is at the end of some signalling pathway (probably TOR usually). But, I'm also happy to annotate directly to the process for now. I just don't know what the rules are in these cases. It seems that nobody else does either, judging by the inferences.

My feeling is that all of the CTD kinases are integrating upstream signals to regulate the transcriptional events (sometimes generally and sometimes gene specifically)

**Comment by pgaudet** [comment]
Discussion with @ValWood 

For now that term is useful - even if we dont know which pathway mcs6 is part of, but that allow to capture the effect of mcs6 on capping.
