### ISSUE TITLE
NTR: Anchoring Disk

### ISSUE THREAD

**Issue by uermel** [geneontology/go-ontology#28570]
Please provide as much information as you can: 

* **Suggested term label:**

Anchoring Disk

* **Definition (free text)**

The anchoring disk is a structural component of the microsporidian spore's invasion apparatus. It is located at the anterior end of the spore and serves to attach the polar tube to the inside of the spore wall.

* **Reference, in format PMID:#######**
[DOI:10.1111/j.1462-5822.2009.01362.x](https://doi.org/10.1111/j.1462-5822.2009.01362.x)
[DOI:10.1016/j.ijpara.2005.04.003](https://doi.org/10.1016%2Fj.ijpara.2005.04.003)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**

GO: 0110165

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
Should this be called something like "polar tube anchoring disk" for precise  context?

**Comment by uermel** [comment]
Yes, that'd be fine by me. Do I edit this issue or is discussion here enough to reflect that?

These are my first NTRs, so I'm unsure about process.

**Comment by ValWood** [comment]
No it's fine, @raymond91125  will handle it.
Just "anchoring disk" could be used in other contexts in biology, its also easier to rule it out if you are browsing for a term

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160202
+name: polar tube anchoring disc
+namespace: cellular_component
+def: "A structural component of the microsporidian spore's invasion apparatus that is located at the anterior end of the spore and serves to attach the polar tube to the inside of the spore wall." [PMID:16005007, PMID:19673893]
+is_a: GO:0110165 ! cellular anatomical entity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28570" xsd:anyURI
+created_by: rynl
+creation_date: 2024-07-25T23:01:39Z
