### ISSUE TITLE
Textual definition update: GO:0044577 and GO:0044836 (xylose catabolic process to ethanol and child)

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#28614]
I am not sure what is the difference between these 2 terms:

xylose catabolic process to ethanol
    |__D-xylose fermentation

- The name of GO:0044577 and input/out chemicals are more specific than its definition 
- The definition of GO:0044836 would fit the name of GO:0044577

They show a picture of the pathway in PMID:[26927067](https://pubmed.ncbi.nlm.nih.gov/26927067/)

**id:GO:0044577**
name: xylose catabolic process to ethanol
def: "The anaerobic chemical reactions and pathways resulting in the breakdown of xylose, an aldopentose, **where one of the resulting products is ethanol**." [GOC:mengo_curators, GOC:tt]
synonym: "xylose catabolism to ethanol" EXACT []
is_a: GO:0042843 ! D-xylose catabolic process
intersection_of: GO:0009056 ! catabolic process
intersection_of: has_primary_input CHEBI:15936 ! aldehydo-D-xylose
intersection_of: has_primary_output CHEBI:16236 ! ethanol

**id: GO:0044836**
name: D-xylose fermentation
namespace: biological_process
def: "The anaerobic enzymatic conversion of D-xylose to ethanol, yielding energy in the form of ATP." [GOC:mengo_curators]
is_a: GO:0006113 ! fermentation
is_a: GO:0044577 ! xylose catabolic process to ethanol
intersection_of: GO:0006113 ! fermentation
intersection_of: has_primary_input CHEBI:53455 ! D-xylopyranose

**Comment by raymond91125** [comment]
I cannot say that they are different.  Xylose fermentation to ethanol. A review. <https://research-hub.nrel.gov/en/publications/xylose-fermentation-to-ethanol-a-review>

**Comment by rozaru** [comment]
@raymond91125 Thanks for making the change. I am sorry to reopen the issue but I was wondering if the name and def of GO:0044577 could be slightly modified to:

id: GO:0044577
name: **D-xylose** catabolic process to ethanol
def: "The anaerobic chemical reactions and pathways resulting in the breakdown of xylose, an aldopentose, **into ethanol**." [GOC:mengo_curators, GOC:tt]

**Comment by raymond91125** [comment]
Yes, that's more consistent. Thanks.
