### ISSUE TITLE
NTR: cannot locate the activity of ILV2 that  converts α-ketobutyrate -> α-aceto-α-hydroxybutyrate

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28613]
Please provide as much information as you can: 

* **Suggested term label:**

If I understand correctly from this image :
https://portlandpress.com/view-large/figure/3513999/EBC-2023-0003Ci001.tif

<img width="1261" alt="Screenshot 2024-07-25 at 15 54 26" src="https://github.com/user-attachments/assets/3964a5a1-99a2-4382-892f-9d55494e3c6c">

The ILV6/2 (Catalytic and regulatory subunit) complex  has 2 activities 

1. α-KB, α-ketobutyrate; -> α-HB, α-aceto-α-hydroxybutyrate  ( in isoleucine biosynthesis)
2. pyruvate ->  α-AL, acetolactate ( in valine biosynthesis)

I can locate only one term 
acetolactate synthase activity GO:0003984

acetolactate synthase activity 2 pyruvate = 2-acetolactate + CO2. (i.e  2 above)

Do we have 1. α-KB, α-ketobutyrate; -> α-HB, α-aceto-α-hydroxybutyrate  ( in isoleucine biosynthesis)

(both activities seem to be referred to as acetolactate synthase?)

see for e.g https://yeast.biocyc.org/pathway?orgid=YEAST&id=ILEUSYN-PWY

**Comment by ValWood** [comment]
There seems to be a similar situation with ILV3 Dihydroxyacid dehydratase

this does 
GO:0004160 dihydroxy-acid dehydratase activity In GO
Catalysis of the reaction: 2,3-dihydroxy-3-methylbutanoate = 3-methyl-2-oxobutanoate + H2O.

but this is only one of  multiple possible inputs and outputs, 

We need both:
1.DHIV, α,β-dihydroxyisovalerate;  -> KIV, α-ketoisovalerate; 
2. DHMV, α,β-dihydroxy-β-methylvalerate; -> KMV, α-keto-β-methylvalerate.

 2,3-dihydroxy-3-methylbutanoate = 2,3-dihydroxyisovalerate (DHIV?)
3-methyl-2-oxobutanoate = α-keto-isovalerate (KIV)

so we have the first reaction but not:

DHMV, α,β-dihydroxy-β-methylvalerate; -> KMV, α-keto-β-methylvalerate.
The one I need  for isoleucine biosynthesis.

Unfortunately, I don't know how to locate this reaction in Rhea if it exists because I can't locate these compounds in CHEBI. But they seem to have the same EC number in 
https://yeast.biocyc.org/pathway?orgid=YEAST&id=ILEUSYN-PWY

(I.e a branched chain aminotransferase)

**Comment by raymond91125** [comment]
> 1. α-KB, α-ketobutyrate; -> α-HB, α-aceto-α-hydroxybutyrate  ( in isoleucine biosynthesis)

I believe is this rxn https://www.rhea-db.org/rhea/27654, one of the two RHEA linked to EC:2.2.1.6 acetolactate synthase.

**Comment by ValWood** [comment]
Yes , excellent that's it.

**Comment by pgaudet** [comment]
So, do we need a new term? It looks like very different sets of proteins are annotated to these 2 RHEAs, that may indeed represent different substrate specificities: 

<img width="1125" alt="image" src="https://github.com/user-attachments/assets/c0f8cb56-006a-427b-a5ff-6372ec4b9126">

**Comment by ValWood** [comment]
I think we need the term, It's the same enzyme but it performs a different reaction depending on the inputs.
25249  one is in the valine biosynthesis  pathway, and 27654 is in the isoleucine biosynthesis pathway.
. It took me ages to figure it out...because upto now these appear to be conflated in curation (maybe the inputs and outputs were not checked?)

**Comment by raymond91125** [comment]
Should there be a new GO term though? It's a case of 1 EC -> 2 RHEAs. What do we call this activity? The literature appears to just say acetolactate synthase.

**Comment by raymond91125** [comment]
GO:0004160 dihydroxy-acid dehydratase activity, EC:4.2.1.9 -> 2 RHEA's,
For isoleucine biosynthesis I (from threonine)
RHEA:27694 	(2R,3R)-2,3-dihydroxy-3-methylpentanoate = (S)-3-methyl-2-oxopentanoate + H2O
For valine biosynthesis
RHEA:24809 	(2R)-2,3-dihydroxy-3-methylbutanoate = 3-methyl-2-oxobutanoate + H2O

**Comment by ValWood** [comment]
Is this how we would normally deal with such a case? It's OK if that is the way to do it, but the definition doesn't work for both Rhea IDs?

acetolactate synthase activity GO:0003984
Catalysis of the reaction: **H+ + 2 pyruvate** = (2S)-2-acetolactate + CO2, or 2-oxobutanoate + H+ + pyruvate = (S)-2-ethyl-2-hydroxy-3-oxobutanoate + CO2.

because for Rhe:27654
the input isn't 2 pyruvate molecules, it's 1 pyruvate and 1 2-oxobutanoate (aka alpha-ketobutyrate).

This is why I was confused building the pathway, the inputs and outputs did not work for isoleucine biosynthesis since the output of the previous reaction was alpha-ketobutyrate). This particular reaction only works for valine biosynthesis which uses the specificity with 2 pyruvates.

Therefore, to make this correct in GO we would need to *broaden* the specificity to "alpha keto acids", which would the required information about the pathway substrates? (pyruvate vs 2-oxobutanoate), and would be broader than either of them.

In this situation it seems the only way to be able to use the activity correctly in a model is to instantiate the 2 pathway specific terms?

A parallel situation exists for LV3 Dihydroxyacid dehydratase, the different specificities are specific for the 2 pathways.

**Comment by ValWood** [comment]
Note that the outputs are different too:
2-aceto-2-hydroxybutanoate
vs 2-acetolactate

**Comment by ValWood** [comment]
In bacteria these activities are typically performed by different genes

Acetohydroxyacid Synthase I (AHAS I): This version of ALS is primarily involved in the biosynthesis of valine and leucine. It uses pyruvate as a substrate to form acetolactate.

Acetohydroxyacid Synthase II (AHAS II): This version of ALS is involved in the biosynthesis of isoleucine. It uses 2-oxobutanoate (α-ketobutyrate) as a substrate along with pyruvate to form acetohydroxybutyrate.

**Comment by raymond91125** [comment]
1. Changes I proposed include both rxns in the definition, e.g. "def: "Catalysis of the reaction: H+ + 2 pyruvate = (2S)-2-acetolactate + CO2, or 2-oxobutanoate + H+ + pyruvate = (S)-2-ethyl-2-hydroxy-3-oxobutanoate + CO2." [RHEA:25249, RHEA:27654]".
2. I think this situation is similar to [NAD(P)](https://wiki.geneontology.org/Guidelines_for_catalytic_activity_terms#NAD/NADP_cofactors_-_different_meaning_of_NAD(P)H_in_GO_and_in_IUBMB:_implications_on_GO_hierarchy). Thus we could have the specific types as children.

**Comment by ValWood** [comment]
OK, I will use 
GO:0003984 acetolactate synthase activity  
and
GO:0004160 dihydroxy-acid dehydratase activity

for these 2 pathways. But I think the situation is quite different from NAD(P) because here it is the direct reaction participant. 
and the differences are the  primary reactant participants of interest for the interaction (not  the 'currency' chemicals, or secondary reactants).  In these cases, if there were Rhea reactions I thought we would aim to align.   It might be worth discussing this on a future editors call. 

FOllowing the current guidelines:


Note that RHEA has many substrate-specific reactions that are outside the scope of GO (e.g.). In these cases, either (i) if present, just add the appropriate generic RHEA and ignore the more specific RHEAs (e.g. XX); or (ii) if not present, add all of the specific RHEAs as narrowMatch xrefs (e.g. XX)


In the section
Pointers that indicate that a catalytic activity term should be merged/obsoleted (or not created)

The term describes a substrate-specific version of a more general activity, and no enzyme is known that distinguishes between these substrates among the common organisms that GO annotates. In these cases, the term usually has a RHEA or a MetaCyc as an exactMatch xref, and the proteins annotated to the RHEA terms for the different substrates are the same or greatly overlapping in UniProt.

 the individual terms would not be required for eukaryotes (although they would for prokaryotes  where they are encoded by different gene products).  For now I can differentiate by adding the inputs and outputs to the model. It's helpful to have both reavions in the definition (I didn't notice that yesterday!). So this can close.

**Comment by raymond91125** [comment]
> In these cases, if there were Rhea reactions I thought we would aim to align. It might be worth discussing this on a future editors call.

Yes, I'd love to have it deliberated. Thanks.
