### ISSUE TITLE
Textual definition update: GO:0004856

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#28622]
* **GO term ID and label for which you request a definition update**
* id: GO:0004856
name: D-xylulokinase activity

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
* def: "Catalysis of the reaction: D-xylulose + ATP = D-xylulose 5-phosphate + ADP + H+." [EC:2.7.1.17, RHEA:10964]

* **Additional information**
* It's H+ instead of 2 H+

**Comment by raymond91125** [comment]
Thanks!
