### ISSUE TITLE
Standardize arachidonic acid and arachidonate terms

### ISSUE THREAD

**Issue by ukemi** [geneontology/go-ontology#28648]
* **Additional information**
It would be good standardize the primary nomenclature to use the correct pH 7.3 species ie change primary term names to arachidonate. Since people will still search on arachidonic acid, it should remain a synonym.

**Comment by raymond91125** [comment]
Note: arachidonate omega-hydroxylase and arachidonic acid omega-hydroxylase both used in literature PMID: 8954571.
