### ISSUE TITLE
'detection of light stimulus involved in visual perception' should not be SubClassOf 'detection of visible light'

### ISSUE THREAD

**Issue by dosumis** [geneontology/go-ontology#28657]
I think this is wrong and too human centric. Birds and insects with UV photoreceptors perceive images using those receptors. This is visual perception.  This is causing problems for CL definition of photoreceptors. See https://github.com/obophenotype/cell-ontology/issues/2253

**Comment by dosumis** [comment]
Ooops - I accidentally did a hot fix to master !!  Sorry!!!

I didn't think that was possible on ODK repos.  Should probably set github to block. 

Anyway - I think minor edit so should be harmless.  Would have like to look for any secondary effect though!

**Comment by cmungall** [comment]
Better ti obsolete the grouping class than have an incomplete one?

**Comment by dosumis** [comment]
I don't think any grouping classes need changing. While this does leave a singleton, there is definitely plenty of detection of visible light outside visual perception - e.g. in plants or by clock cells with cryptochromes

![image](https://github.com/user-attachments/assets/98ab26af-4869-40ca-b846-c449ca1f4109)

**Comment by dosumis** [comment]
Passes QC at least
![image](https://github.com/user-attachments/assets/49d0f0da-ff13-4519-ae43-7c11f707d0a9)
