### ISSUE TITLE
Missing parent:  sulfite transport (GO:0000316)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28653]
* **GO term ID and label for which you request a new superclass**

 sulfite transport (GO:0000316)
relabel "sulphite transmembrane transport"

* **New superclass (parent) suggested**

GO:0055085 | transmembrane transport

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by raymond91125** [comment]
sulfite transport has an LD of transport and ('has primary input' some sulfite)
sulfite transmembrane transport would be 'transmembrane transport' and ('has primary input' some sulfite)
Compare to GO:0008272 sulfate transport.

**Comment by ValWood** [comment]
Two fixes are required here.
All sulfite and sulfate transport is transmembrane. Sulfite and sulphate are diffusable in luminal compartments.

1. rename  sulfite transport  -> sulphite transmembrane transport and add  a "transmembrane type" logical definition

3.  merge (i.e obsolete and direct replace ) GO:0008272 sulfate transport with sulphate transmembrane transport (is single inheritance, i.e term with only one child)

@raymond91125  do you want to take this one? I notice you haven't got many  assigned tickets. 
v

**Comment by raymond91125** [comment]
Sure. Please assign tickets to me. Thanks.

**Comment by ValWood** [comment]
Thank you!
