### ISSUE TITLE
NTR: mitochondrial disulfide relay system

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#28663]
* **Suggested term label:**
mitochondrial disulfide relay system

* **Definition (free text)**
Facilitates the import and folding of a subset of soluble proteins into mitochondrial intermembrane space via disulfide bond formation. Typically substrates of the mitochondrial disulfide relay system contain conserved cysteine motifs, known as twin-CX9C motifs. Minimally, the system requires the oxidoreductase CHCHD4 (aka Mia40) and the sulfhydryl oxidase GFER (aka Erv1). As unfolded protein substrates are imported from the cytsol via the mitochondrial outer membrane translocase complex, the oxidoreductase CHCHD4 promotes import and protein folding via the formation intramolecular disulfide bonds. GFER is required to regenerate CHCHD4 by oxidation.

* **Reference, in format PMID:#######**
PMID:37159021, PMID:32936885

* **Gene product name and ID to be annotated to this term**
AIF FBgn0031392
Alr FBgn0031068
CG7950 FBgn0260468

* **Parent term(s)**
is_a GO:0045041 protein import into mitochondrial intermembrane space
is_a GO:0006457 protein folding

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
EXACT: mitochondrial intermembrane space assembly pathway
EXACT: MIA pathway

**Comment by ValWood** [comment]
Hi @hattrill  I think we can go ahead with this but it seems more that it should be is_a protein folding and part_of import (because this pathway doesn't seem to do the import on it's own.
mia40 binds to the incoming proteins, but they are imported via the translocase, is that correct? this seems to link the IMS and matrix import systems?
v

**Comment by hattrill** [comment]
@ValWood part_of GO:0045041 would be better, as the import happens usually using a weak mitochiondrial targeting sequence via TOM complex and Mia40 via it's interaction with the protein makes that import stronger.

**Comment by ValWood** [comment]
OK!

@raymond91105, do you want to take this one?

@PCarme  when this term comes through, we can annotate
Aif1 currently "conserved unknown"
erv1 (only has protein folding)
mia40 (currently has protein folding and "protein import into mitochondrial intermembrane space (GO:0045041)"

@hattrill  I predict that hot13 and hot15 might be part of this pathway, 
https://www.pombase.org/term/GO:0045041
but so far I have been unable to identify higher eukaryotic orthologs for these (they are both quite small).

**Comment by raymond91125** [comment]
Please note that I've made the definition brief, assuming more detail is not required to make it 'necessary and sufficient'. Please reopen if needed. Thanks.

+[Term]
+id: GO:0160203
+name: mitochondrial disulfide relay system
+namespace: biological_process
+def: "A protein folding process that facilitates the import of a subset of soluble proteins into mitochondrial intermembrane space via disulfide bond formation." [PMID:32936885, PMID:37159021]
+synonym: "MIA pathway" EXACT []
+synonym: "mitochondrial intermembrane space assembly pathway" EXACT []
+is_a: GO:0006457 ! protein folding
+relationship: part_of GO:0045041 ! protein import into mitochondrial intermembrane space
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28663" xsd:anyURI
+created_by: rynl
+creation_date: 2024-08-05T23:59:12Z
