### ISSUE TITLE
NTR: L-valine biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28686]
Please provide as much information as you can: 

* **Suggested term label:**

NTR: L-valine biosynthetic process

* **Definition (free text)**

standard def

* **Gene product name and ID to be annotated to this term**

All biosynthesis in fission yeast.

* **Parent term(s)**

valine biosynthetic process
(so far I have been able to annotate  AA biosynthesis pathways to the L-form if applicable)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by ValWood** [comment]
Oddly there is no L-arginine biosynthetic process either. I thought these were all done a few months back, I wonder if there was a reason these were not added?

**Comment by raymond91125** [comment]
We have
GO:0009099 valine biosynthetic process
GO:0006526 arginine biosynthetic process
I believe we have an ongoing project about D/L amino acids but cannot seem to find it.

**Comment by pgaudet** [comment]
We could rename GO:0009099 valine biosynthetic process to L-valine? 

I think the D- amino acids are 'racemized' from the L forms. Is this a process? Maybe only the L- forms should be captured for synthesis (not sure about metabolism and degradation). 


From https://pubmed.ncbi.nlm.nih.gov/24752840/: 

> Bacteria synthesize D-AAs using one of two mechanisms:
inversion of stereochemistry about the α-carbon of the corresponding L-AA, or stereospecific amination of the corresponding α-ketoacid. The former, catalyzed by AA
racemase or epimerase enzymes, is a reversible reaction
resulting in direct interconversion of the L- and Dstereoisomers. The latter reaction, also reversible, relies on
an amino-containing co-substrate and is catalyzed by D-AA
aminotransferase enzymes.

**Comment by raymond91125** [comment]
How about GO:0006526 arginine biosynthetic process, also rename to L-?

**Comment by pgaudet** [comment]
Yes
