### ISSUE TITLE
NTR: mitochondrion membrane tether activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#28694]
Please provide as much information as you can: 

* **Suggested term label:**
mitochondrion membrane tether activity
or 
mitochondrion-mitochondrion membrane tether activity
or
mitochondrion outer membrane tether activity

(not sure what is the best name)

* **Definition (free text)**

The binding activity of a molecule that brings together mitochondrial outer membranes to bring them in close proximity. 

* **Reference, in format PMID:#######**
PMID:38843396

* **Gene product name and ID to be annotated to this term**
TRABD, UniProtKB:Q9H4I3

* **Parent term(s)**
protein-membrane adaptor activity GO:0043495

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160204
+name: mitochondrion-mitochondrion outer membrane tether activity
+namespace: molecular_function
+def: "The binding activity of a molecule that brings together two mitochondrion membranes via membrane lipid binding or by interacting with a mitochondrial outer membrane protein, to establish or maintain the localization of the mitochondrion." [PMID:38843396]
+synonym: "mitochondrion membrane tether activity" RELATED []
+synonym: "mitochondrion outer membrane tether activity" RELATED []
+is_a: GO:0043495 ! protein-membrane adaptor activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28694" xsd:anyURI
+created_by: rynl
+creation_date: 2024-08-15T17:06:16Z
