### ISSUE TITLE
NTR: Suicidal Thiazole Synthase (yeast thi4)

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28713]
* **Suggested term label:**

Suicidal Thiazole Synthase (I can't find this ?)
seems to be
NAD+ + Glycine + Sulfide (from Thi4) → Thiazole + Inactivated Thi4 + Nicotinamide + ??

* **Reference, in format PMID:#######**

Saccharomyces cerevisiae Thi4 is a suicide thiazole synthase.
Nature. 2011 Oct 26;478(7370):542-6. doi: 10.1038/nature10503.
PMID: 22031445 

* **Gene product name and ID to be annotated to this term**

S. cerevisae/ S. pombe Thi4

* **Parent term(s)**
??

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

synonym Thiazole Phosphate Synthase exact

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

Comment yeast Thi4 enzyme (Thiazole synthase 4) is a "suicide enzyme," (undergoes irreversible inactivation as part of its catalytic process). 
Thi4 is involved in the biosynthesis of the thiazole ring, a  component of thiamine pyrophosphate (TPP)
The sulfur is provided by a cysteine residue within the enzyme itself, leading to the enzyme's inactivation.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160205
+name: cysteine-dependent adenosine diphosphate thiazole synthase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: [ADP-thiazole synthase]-L-cysteine + glycine + NAD(+) = [ADP-thiazole synthase]-dehydroalanine + ADP-5-ethyl-4-methylthiazole-2-carboxylate + 2 H(+) + 3 H2O + nicotinamide." [RHEA:55708]
+synonym: "ADP-thiazole synthase activity" RELATED [EC:2.4.2.60]
+synonym: "suicide thiamine thiazole synthase activity" EXACT []
+xref: EC:2.4.2.60
+xref: RHEA:55708
+is_a: GO:0016763 ! pentosyltransferase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28713" xsd:anyURI
+created_by: rynl
+creation_date: 2024-08-20T00:05:09Z

**Comment by ValWood** [comment]
Thank you!
