### ISSUE TITLE
NTR: positive regulation of androgen receptor signaling pathway

### ISSUE THREAD

**Issue by krchristie** [geneontology/go-ontology#28728]
Please provide as much information as you can: 

* **Suggested term label:**
positive regulation of androgen receptor signaling pathway

* **Definition (free text)**
Any process that activates or increases the frequency, rate or extent of the activity of any androgen receptor signaling pathway.

* **Reference, in format PMID:#######**
PMID:29057879

* **Gene product name and ID to be annotated to this term**
Foxp1 = MGI:1914004
Shq1 = MGI:1919421

* **Parent term(s)**
regulation of androgen receptor signaling pathway - GO:0060765

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160207
+name: positive regulation of androgen receptor signaling pathway
+namespace: biological_process
+def: "Any process that activates or increases the frequency, rate or extent of androgen receptor signaling." [PMID:29057879]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: positively_regulates GO:0030521 ! androgen receptor signaling pathway
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28728" xsd:anyURI
+created_by: rynl
+creation_date: 2024-08-21T22:03:38Z
