### ISSUE TITLE
Chitinase activity & children

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28722]
Comment @raymond91125 in https://github.com/geneontology/go-ontology/issues/28340#issuecomment-2201522013

GO:0008843 endochitinase activity -> https://enzyme.expasy.org/EC/3.2.1.14 -> GO:0004568 chitinase activity (parent). There is a sibling GO:0035885 exochitinase activity, though.

PMID:34943233
![image](https://github.com/user-attachments/assets/56125e91-da1e-411b-8e49-1d9118c687e7)

EC:3.2.1.14 chitinase Random endo-hydrolysis of N-acetyl-beta-D-glucosaminide (1->4)-beta-linkages in chitin and chitodextrins
EC 3.2.1.201 exo-chitinase (reducing end) 
EC 3.2.1.200 exo-chitinase (non-reducing end) 
These three activities should be in parallel, children of GO:0016798 hydrolase activity, acting on glycosyl bonds, without any grouping terms.
We currently have:
GO:0004568 chitinase activity (EXP 69) XREF EC:3.2.1.14
... GO:0008843 endochitinase activity (19)
... GO:0035885 exochitinase activity (3) XREF RHEA:50672, XREF BioCyc RXN-12309 (->EC:3.2.1.200)
Scanned some current annotations. They will have to be re-annotated for this proposed re-organization. 

@pgaudet How should we deal with this; start an annotation review?

**Comment by raymond91125** [comment]
Given prior discussions, I think the solution is simple:
GO:0004568 chitinase activity
... GO:0008843 endochitinase activity EC:3.2.1.14
... GO:0035885 exochitinase activity EC:3.2.1.200 (narrowMatch) EC:3.2.1.201 (narrowMatch)
