### ISSUE TITLE
NTR: fibrous body-membranous organelle

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/go-ontology#28736]
Please provide as much information as you can: 

* **Suggested term label:**

fibrous body-membranous organelle

* **Definition (free text)**

A Golgi-derived organelle that forms in primary spermatocytes during C. elegans spermatogenesis.  This ‘double organelle’ consists of a fibrous body containing major sperm protein and a membranous organelle that envelops the developing fibrous body.  During spermatogenesis, fibrous body-membranous organelles are asymmetrically distributed into spermatids where the major sperm proteins contained in the fibrous body are released into the cytoplasm to assemble into the polarized cytoskeleton present in the amoeboid spermatozoa.  Upon sperm activation, the membranous organelle releases its content to the extracellular space by fusing with the spermatid and spermatazoan plasma membrane.

* **Reference, in format PMID:#######**

PMID:3517007
PMID:18050478
PMID:22872478
PMID:34930663

* **Gene product name and ID to be annotated to this term**

A number of C. elegans SPE proteins are currently annotated to other uninformative high-level organelle GO terms.  The plan is to re-annotate as many as possible to this new term.

* **Parent term(s)**

GO:0043231. intracellular membrane-bounded organelle

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

EXACT: FB-MO

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

@raymond91125  - let me know if you think the definition needs any revision.

**Comment by raymond91125** [comment]
FB-MOs are found in some nematodes but not others.
PMID:26093476 "Specific fibrous bodies (FB) as long parallel bundles of filaments occupy the peripheral cytoplasm. No structures resembling membranous organelles (MO), as found in the sperm of many other nematodes, were observed in immature spermatozoa of T. similis."

**Comment by raymond91125** [comment]
@vanaukenk Please review and see if this is sufficient. I can also add an only_in taxon constraint. Thanks.

+[Term]
+id: GO:0160208
+name: fibrous body-membranous organelle
+namespace: cellular_component
+def: "A Golgi-derived organelle that forms in primary spermatocytes during spermatogenesis of some nematodes including C. elegans. This ‘double organelle’ consists of a fibrous body containing major sperm protein and a membranous organelle that envelops the developing fibrous body." [PMID:18050478, PMID:8004009]
+synonym: "FB-MO" EXACT []
+is_a: GO:0043231 ! intracellular membrane-bounded organelle
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28736" xsd:anyURI
+created_by: rynl
+creation_date: 2024-08-22T00:14:41Z

**Comment by vanaukenk** [comment]
Thanks @raymond91125 

I like your changes to the definition, but at this point, I'm not sure about the only_in taxon constraint.  At what level would you apply it?

**Comment by raymond91125** [comment]
I think NCBITaxon:6231 Nematoda. I don't think it's necessary but I thought since it is so stated in the DEF, it can't hurt.

**Comment by vanaukenk** [comment]
Thanks @raymond91125 
That taxon constraint sounds good.
