### ISSUE TITLE
NTR: [N-acetyltaurine hydrolase activity]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#28746]
Hi GO,

I would need a GO term for  N-acetyltaurine hydrolase activity, an enzyme catalyzing the hydrolysis of N-acetyltaurine into taurine and acetate.

Name: N-acetyltaurine hydrolase activity
Definition: Catalysis of the reaction: N-acetyltaurine + H2O = acetate + taurine
Child of GO:0016788 hydrolase activity, acting on ester bonds
Xref: Rhea:81107 (Not yet public)
PMID:39112712

RX PubMed=39112712; DOI=10.1038/s41586-024-07801-6
RA Wei W., Lyu X., Markhard A.L., Fu S., Mardjuki R.E., Cavanagh P.E., Zeng X., Rajniak J., Lu N., Xiao S., Zhao M., Moya-Garzon M.D., Truong S.D., Chou J.C., Wat L.W., Chidambaranathan-Reghupaty S., Coassolo L., Xu D., Shen F., Huang W., Ramirez C.B., Jang C., Li L., Svensson K.J., Fischbach M.A., Long J.Z.
RT PTER is a N-acetyltaurine hydrolase that regulates feeding and obesity.
RL journal article: Nature 0:0-0 (2024)

Thanks

Sylvain

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141215
+name: N-acetyltaurine hydrolase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: N-acetyltaurine + H2O = acetate + taurine." [PMID:39112712, RHEA:81107]
+xref: RHEA:81107 {source="skos:exactMatch"}
+is_a: GO:0016788 ! hydrolase activity, acting on ester bonds
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28746" xsd:anyURI
+created_by: pg
+creation_date: 2024-08-23T09:58:14Z
