### ISSUE TITLE
Malformed xref Match qualifier lines

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28740]
Need to make these two changes to the terms below:

xref: EC:1.14.19.74 {xref="skos:exactMatch"} ->  xref: EC:1.14.19.74 {source="skos:exactMatch"}

xref: RHEA:16301 {xref="skos:broadMatch"} -> xref: RHEA:16301 {source="skos:broadMatch"}

id: GO:0102915
name: piperitol synthase activity
namespace: molecular_function
def: "Catalysis of the reaction: H+ + (+)-pinoresinol + NADPH + O2 = (+)-piperitol + NADP + 2 H2O." [EC:1.14.19.74, PMID:16785429]
xref: EC:1.14.19.74 {xref="skos:exactMatch"}

id: GO:0061809
name: NAD+ nucleotidase, cyclic ADP-ribose generating
namespace: molecular_function
def: "Catalysis of the reaction: NAD+ + H2O = nicotinamide + ADP-ribose, in a two steps reaction: first an ADP-ribosyl cyclase reaction, followed by a cyclic ADP-ribose hydrolase reaction." [GOC:dph, GOC:pad, GOC:PARL, GOC:pde, PMID:11866528]
xref: RHEA:16301 {xref="skos:broadMatch"}

**Comment by pgaudet** [comment]
Done?

**Comment by sjm41** [comment]
Now done!
