### ISSUE TITLE
GO:0009975    cyclase activity 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28803]
* **GO term ID and label for which you request a new superclass**

[GO:0009975](https://www.ebi.ac.uk/QuickGO/term/GO:0009975

* **New superclass (parent) suggested**

Is there any reason why this isn't is) lyase???

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by pgaudet** [comment]
I wonder if that's even a useful term, it doesn't match any high-level ECs. Do we need this?

**Comment by ValWood** [comment]
Perhaps we don't need it.

However, this class of lyases appear  to be mentioned in the definition 
Catalysis of the cleavage of C-C, C-O, C-N and other bonds by other means than by hydrolysis or oxidation, or conversely adding a group to a double bond. They differ from other enzymes in that two substrates are involved in one reaction direction, but only one in the other direction. When acting on the single substrate, a molecule is eliminated and this generates either a new double bond **or a new ring.**

So perhaps they is another EC that covers cyclases.

PomBase only has 3 cyclases annotated
<img width="656" alt="Screenshot 2024-08-30 at 16 21 41" src="https://github.com/user-attachments/assets/7f8bc96e-7dbe-4ffe-a110-4461967e87fa">


there are 2 children  (which have alternative parents)
and one direct to "cyclase activity" which I could happily move to lyase  if you think 'cyclase' is not useful as a grouping term.

There are 7 direct  EXP annotations to cyclase so there  may be some loss of information for these if they vcannot be made more specific

**Comment by pgaudet** [comment]
This is close to the lyase definition pretty: 

see https://en.wikipedia.org/wiki/Lyase

lyase is an [enzyme](https://en.wikipedia.org/wiki/Enzyme) that catalyzes the [breaking](https://en.wikipedia.org/wiki/Bond_cleavage) (an [elimination reaction](https://en.wikipedia.org/wiki/Elimination_reaction)) of various [chemical bonds](https://en.wikipedia.org/wiki/Chemical_bond) by means other than [hydrolysis](https://en.wikipedia.org/wiki/Hydrolysis) (a [substitution reaction](https://en.wikipedia.org/wiki/Substitution_reaction)) and [oxidation](https://en.wikipedia.org/wiki/Oxidation), often forming a new [double bond](https://en.wikipedia.org/wiki/Double_bond) or a new [ring structure](https://en.wikipedia.org/wiki/Ring_(chemistry)).

Consistent with this, the terms you have above are of EC class 4 (lyase). Seems we should merge these two terms.

**Comment by ValWood** [comment]
I'm not sure that we should obsolete the cyclase term, it is a valid catalytic grouping
EC 4.6 refers to enzymes that specifically form cyclic phosphates.
That feels weird.

==

Here are some common cyclases and their EC numbers:

Adenylate cyclase (EC 4.6.1.1):

This enzyme converts ATP (adenosine triphosphate) to cyclic AMP (cAMP) and pyrophosphate. cAMP is an important second messenger in many signaling pathways.
Guanylate cyclase (EC 4.6.1.2):

This enzyme catalyzes the conversion of GTP (guanosine triphosphate) to cyclic GMP (cGMP) and pyrophosphate. cGMP acts as a second messenger in various cellular processes, including smooth muscle relaxation and phototransduction.
General Characteristics
The common EC classification for cyclases is under EC 4.6, where:
EC 4 denotes lyases, enzymes that break chemical bonds by means other than hydrolysis or oxidation.
EC 4.6 refers to enzymes that specifically form cyclic phosphates.

**Comment by ValWood** [comment]
I would feel more comfortable  adding is_a lyase

**Comment by sjm41** [comment]
But not all cyclases (defined in GO as catalysing "a ring closure reaction") are classed as lyases....
e.g.
RNA-3'-phosphate cyclase activity (GO:0003963) = EC:6.5.1.4 (ligase)
tocopherol cyclase activity (GO:0009976) = EC:5.5.1.24 (isomerase)
glutaminyl-peptide cyclotransferase activity (GO:0016603) = EC:2.3.2.5 (transferase)

Which explains the top-level grouping of cyclases outside of the 7 main EC classes.

**Comment by ValWood** [comment]
OK! So if G-glutamate cyclase isn't a lyase,  all is correct. This ticket can close!

**Comment by ValWood** [comment]
Scrub that. In that case the current arrangement is correct.
