### ISSUE TITLE
Possible obsoletion - GO:0019551 glutamate catabolic process to 2-oxoglutarate

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28800]
id: GO:0019551
name: glutamate catabolic process to 2-oxoglutarate
namespace: biological_process
def: "The chemical reactions and pathways resulting in the breakdown of glutamate into other compounds, including 2-oxoglutarate." [GOC:go_curators]
synonym: "glutamate breakdown to 2-oxoglutarate" EXACT []
synonym: "glutamate catabolic process to 2-ketoglutarate" EXACT []
synonym: "glutamate catabolic process to alpha-ketoglutarate" EXACT []
synonym: "glutamate catabolic process to alpha-oxoglutarate" EXACT []
synonym: "glutamate catabolism to 2-ketoglutarate" EXACT []
synonym: "glutamate catabolism to alpha-ketoglutarate" EXACT []
synonym: "glutamate catabolism to alpha-oxoglutarate" EXACT []
synonym: "glutamate degradation to 2-oxoglutarate" EXACT []
xref: MetaCyc:GLUTAMATE-DEG1-PWY
xref: MetaCyc:PWY-5766
is_a: GO:0006106 ! fumarate metabolic process
intersection_of: GO:0009056 ! catabolic process
intersection_of: has_primary_input CHEBI:14321 ! glutamate(1-)
intersection_of: has_primary_output CHEBI:16810 ! 2-oxoglutarate(2-)

This term is essentially defined by its two MetaCyc xrefs.  They both describe single-step pathways catalysed either by EC:1.4.1.2 = GO:0004352 glutamate dehydrogenase (NAD+) activity or EC:1.4.1.3 = GO:0004353 glutamate dehydrogenase [NAD(P)+] activity.

That suggests this BP term should be obsoleted with the MetaCyc xrefs transferred to the respective MF terms.

Though I see that there are 6 EXP annotations to the GO:0019551 term, so maybe there are valid cases of this pathway comprising multiple steps?? - need to check.
Candida GDH2 by CGD
Rat Got1 & Got2 by RGD
Mouse Got1 & Got2 by MGI
Pombe gdh2 by PomBase

**Comment by raymond91125** [comment]
Per UniProt, gdh2 and got1/2 are all involved in single-step reactions between glutamate and 2-oxoglutarate.
GDH2: Rhea 15133
GOT1: Rhea 21824, 17441, 70223, 70295
GOT2: Rhea 21824, 65560

Thus this is a grouping term for MFs.

**Comment by sjm41** [comment]
Thanks @raymond91125. BTW, I've already moved the MetaCyc xrefs to the corresponding MF terms as part of fixing another ticket.

**Comment by raymond91125** [comment]
Yes, I noticed. Thanks.
