### ISSUE TITLE
Obsoletion request: GO:0003867    4-aminobutyrate transaminase activity 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28802]
Dear all, 

The proposal has been made to obsolete GO:0003867 '4-aminobutyrate transaminase activity' because it is an unnecessary grouping class that has not EC or RHEA cross reference. 

4 EXP.

**Comment by deustp01** [comment]
> The proposal has been made to obsolete GO:00038674

Is this accession number right? I can't find anything matching it in QuickGO. Thanks

**Comment by pgaudet** [comment]
Thanks @deustp01 

The space between the GOID and the term label was lost, which was indeed very confusing.

**Comment by deustp01** [comment]
Reactome has [one annotation](https://reactome.org/content/detail/R-HSA-916855), that, exactly as the obsoletion proposal suggests, could be re-annotated to the child term [GO:0034386](https://www.ebi.ac.uk/QuickGO/term/GO:0034386)
4-aminobutyrate:2-oxoglutarate transaminase activity, so no objections here. (In fact, I'll re-annotate it now figuring that more specificity is better.)

**Comment by raymond91125** [comment]
There are actually 13 EXP in AmiGO that need to be re-annotated to the children terms

1.    GO:0034386 4-aminobutyrate:2-oxoglutarate transaminase activity -> EC:2.6.1.19 -> RHEA:23352
2.    GO:0034387 4-aminobutyrate:pyruvate transaminase activity -> EC:2.6.1.96 -> RHEA:32263, RHEA:32267 (plant-specific)

GO:0032144 4-aminobutyrate transaminase complex should be changed to 'catalytic complex'
 and ('capable of' some '4-aminobutyrate:2-oxoglutarate transaminase activity')
