### ISSUE TITLE
Obsoletion request: GO:0052739 phosphatidylserine 1-acylhydrolase activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28816]
Hi @tberardini , 

GO:0052739 phosphatidylserine 1-acylhydrolase activity has a single annotation to A. thaliana PLIP1 (AT3G61680)

Is this really different from GO:0008970 'phospholipase A1 activity'? 

(Note that I made EC:3..1.1.32  a broadMatch for now in the larger ticket https://github.com/geneontology/go-ontology/issues/28070. )

Thanks, Pascale

**Comment by pgaudet** [comment]
Can you also check that GO:0080076  caffeoyl CoA:S-adenosyl-L-methionine O-methyltransferase activity (no xref) is different from GO:0042409 caffeoyl-CoA O-methyltransferase activity (RHEA:16925, EC:2.1.1.104) ? 

GO:0080076  caffeoyl CoA:S-adenosyl-L-methionine O-methyltransferase activity: Catalysis of the transfer of a methyl group from S-adenosyl-L-methionine to the oxygen atom of a caffeoyl CoA molecule.

GO:0042409 caffeoyl-CoA O-methyltransferase activity: Catalysis of the reaction: S-adenosyl-L-methionine + caffeoyl-CoA = S-adenosyl-L-homocysteine + feruloyl-CoA.

**Comment by tberardini** [comment]
Assigning to @lreiser while I'm on vacation.

**Comment by lreiser** [comment]
@pgaudet  just noticing this was assigned to me:
GO:0052739 phosphatidylserine 1-acylhydrolase activity has a single annotation to A. thaliana PLIP1 (AT3G61680)

Is this really different from GO:0008970 'phospholipase A1 activity'?
No... think its safe to obsolete GO:0052739

**Comment by pgaudet** [comment]
Great, thanks :)

**Comment by raymond91125** [comment]
@lreiser Could you also check this pair? Thanks. The UniProt annotations may be transferred automatically.
> Can you also check that GO:0080076 caffeoyl CoA:S-adenosyl-L-methionine O-methyltransferase activity (no xref) is different from GO:0042409 caffeoyl-CoA O-methyltransferase activity (RHEA:16925, EC:2.1.1.104) ?
> 
> GO:0080076 caffeoyl CoA:S-adenosyl-L-methionine O-methyltransferase activity: Catalysis of the transfer of a methyl group from S-adenosyl-L-methionine to the oxygen atom of a caffeoyl CoA molecule.
> 
> GO:0042409 caffeoyl-CoA O-methyltransferase activity: Catalysis of the reaction: S-adenosyl-L-methionine + caffeoyl-CoA = S-adenosyl-L-homocysteine + feruloyl-CoA.

**Comment by lreiser** [comment]
Im no biochemist but it seems to be the case.
