### ISSUE TITLE
Obsoletion request: GO:0047012 sterol-4-alpha-carboxylate 3-dehydrogenase (decarboxylating) activity

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28822]
Hi, 

The proposal has been made to obsolete GO:0047012 sterol-4-alpha-carboxylate 3-dehydrogenase (decarboxylating) activity. The reason for obsoletion is that this term corresponds to other terms. 

- SGD has 2 annotations to ERG26, which is already correctly annotated to [3beta-hydroxysteroid-4alpha-carboxylate 3-dehydrogenase (decarboxylating) [NAD(+)] activity](http://purl.obolibrary.org/obo/GO_0102191)

- TAIR has 4 annotations to 3BETAHSD/D1 and 3BETAHSD/D2, which, according to UniProt, should rather be annotated to [3beta-hydroxysteroid-4alpha-carboxylate 3-dehydrogenase (decarboxylating) [NAD(+)] activity](http://purl.obolibrary.org/obo/GO_0102191)

@tberardini can you please confirm? 

Thanks, Pascale

**Comment by pgaudet** [comment]
Hi @ValWood 
Sorry I forgot to paste - the correct annotation is [3beta-hydroxysteroid-4alpha-carboxylate 3-dehydrogenase (decarboxylating) [NAD(+)] activity](http://purl.obolibrary.org/obo/GO_0102191)

**Comment by ValWood** [comment]
So are 


GO:0103066 | 4alpha-carboxy-4beta-methyl-5alpha-cholesta-8-en-3beta-ol:NAD(P)+ 3-oxidoreductase (decarboxylating) activity | IEA with 1.1.1.170 | GO_REF:0000003 | 1
-- | -- | -- | -- | --
GO:0103067 | 4alpha-carboxy-5alpha-cholesta-8-en-3beta-ol:NAD(P)+ 3-dehydrogenase (decarboxylating) activity | IEA with 33447 | GO_REF:0000116 | 1

incorrect IEA mappings ?

**Comment by pgaudet** [comment]
EC:1.1.1.170  was mapped to 4 GO terms, including GO:0103066 and GO:0103067, see https://docs.google.com/spreadsheets/d/17QvDQoIXe-Rim9ReReVlZGntr-WkIGJ0cbPhaQDB_As/edit?gid=1251661278#gid=1251661278 

RHEA:33447 https://www.rhea-db.org/rhea/33447  is a specific form of RHEA:34771 

We have decided not to keep GO terms for specific substrates unless there is evidence that there is an enzyme with that specificity (see https://wiki.geneontology.org/Guidelines_for_new_Molecular_Functions#GO_Molecular_Functions) 


Thanks, Pascale

**Comment by ValWood** [comment]
Weird, we aren't picking up that GO:0103066 and GO:0103067 are obsolete at PomBase, not sure why...

**Comment by pgaudet** [comment]
They were obsoleted just yesterday.

**Comment by tberardini** [comment]
Back from vacation. I confirm. I've moved the annotations to the new term which didn't exist at the time of the original annotations.
