### ISSUE TITLE
Textual definition update: GO:0042351 de novo' GDP-L-fucose biosynthetic process

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#28825]
The  Xref for output and input are missing.

* **GO term ID and label for which you request a definition update**
GO:0042351 de novo' GDP-L-fucose biosynthetic process

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
intersection_of: has_primary_input CHEBI:57527 ! GDP-α-D-mannose(2−)
intersection_of: has_primary_output CHEBI:57984 ! GDP-L-fucose(2-)

**Comment by raymond91125** [comment]
Added has_primary_input CHEBI:57527 ! GDP-α-D-mannose(2−).
'biosynthetic process' and ('has primary output' some 'GDP-L-fucose(2-)') is already the logical definition of parent GDP-L-fucose biosynthetic process.
thanks.
