### ISSUE TITLE
cysteine synthase question, definition problem

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28833]
previously I used 
"cysteine synthase"
Catalysis of the reaction: O3-acetyl-L-serine + hydrogen sulfide = L-cysteine + acetate.

for fission yeast cys11 https://www.pombase.org/gene/SPBC36.04

However,
https://www.nature.com/articles/nchembio.2397

The same reasoning applied for the next enzyme in the L-cysteine biosynthetic pathway, L-cysteine synthase (Cys1a). Cys1apombe was almost three times less efficient with O-acetyl-L-serine ([12](https://www.nature.com/articles/nchembio.2397/compounds/12)) than with O-succinyl-L-serine (4.5 × 103 versus 1.2 × 104 s−1 M−1; [Supplementary Table 9](https://www.nature.com/articles/nchembio.2397#MOESM1)), which suggested that S. pombe forms L-cysteine via O-succinyl-L-serine (CHEBI [134286](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:134286))

Finally, we detected O-succinyl-L-serine in the metabolome of the wild-type strain of S. pombe, but not in a Cys2 mutant (FY17212)[36](https://www.nature.com/articles/nchembio.2397#ref-CR36) ([Supplementary Fig. 16](https://www.nature.com/articles/nchembio.2397#MOESM1)). It should be noted that we did not detect O-acetyl-L-serine in the S. pombe metabolome.

Which means this definition of cysteine synthase doesn't fit.

Do we need to broaden the definition?
Do we need to add specific descendant terms?

(note also that the upstream activity has different specificity
https://github.com/geneontology/go-ontology/issues/28832

**Comment by pgaudet** [comment]
We can create a reaction with  O-succinyl-L-serine, corresponding to https://www.rhea-db.org/rhea/53816

Would that work?

**Comment by ValWood** [comment]
Yep I think so.

**Comment by pgaudet** [comment]
Created new term 

[Term]
id: GO:0141223
name: cysteine synthase activity, acting on O-succinyl-L-serine
namespace: molecular_function
def: "Catalysis of the reaction: hydrogen sulfide + O-succinyl-L-serine = L-cysteine + succinate." [RHEA:53816]
synonym: "cysteine synthase activity" BROAD []
xref: RHEA:53816 {source="skos:exactMatch"}
is_a: GO:0016765 ! transferase activity, transferring alkyl or aryl (other than methyl) groups
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28833" xsd:anyURI
created_by: pg
creation_date: 2024-10-28T07:48:43Z

**Comment by ValWood** [comment]
but this new term isn't classed as a cysteine synthase?

**Comment by pgaudet** [comment]
Well,  cysteine synthase activity, acting on O-succinyl-L-serine is not using the same substrate - it's not a type of 'cysteine synthase activity': Catalysis of the reaction: O3-acetyl-L-serine + hydrogen sulfide = L-cysteine + acetate.

versus cysteine synthase activity, acting on O-succinyl-L-serine: Catalysis of the reaction: hydrogen sulfide + O-succinyl-L-serine = L-cysteine + succinate. 

a succinyl is not a acetyl - it would be wrong to make them child of each other.

**Comment by ValWood** [comment]
Doesn't that mean that the cysteine synthase definition is correct? It's still a cysteine synthase activity, isn't it? I'm having a logic issue here ;)

**Comment by pgaudet** [comment]
We can rename "cysteine synthase activity" to "cysteine synthase activity, acting on  acetyl-L-serine' to be more explicit. 

The reason why I hadn't done that is that this is the 'normal' substrate ; that pombe gene seems to be an exception. 

Should I rename "cysteine synthase activity" ?

**Comment by ValWood** [comment]
Don't worry, it seems like a hassle. I  can co-annotate to "cysteine synthase" so it doesn't look like a pathway hole when we look for pathway holes using BioCyc.
