### ISSUE TITLE
NTR: L-serine O-succinyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28832]
Please provide as much information as you can: 

* **Suggested term label:**

L-serine O-succinyltransferase activity

* **Definition (free text)**

Catalysis of the reaction: L-serine + succinyl-CoA = O-succinyl-L-serine + CoA.

* **Reference, in format PMID:#######**

PMID:28581482

* **Gene product name and ID to be annotated to this term**

S. pombe cys2  https://www.pombase.org/gene/SPBC106.17c

* **Parent term(s)**

GO:0016750  O-succinyltransferase activity

* **Cross-references**
RHEA:52820

* **Any other information**

@Antonialock  thanks for this.

**Comment by ValWood** [comment]
Note to self, update GO-CAM model

**Comment by ValWood** [comment]
I meant  to include

We carried out LC–MS analysis and found similar retention times and MS2 profiles for the metabolite produced by Cys2pombe and authentic O-succinyl-L-serine, which indicated that the latter was enzymatically formed by Cys2pombe ([Fig. 3c,d](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Farticles%2Fnchembio.2397%23Fig3&data=05%7C02%7Cvw253%40cam.ac.uk%7Cce09a4b4ec2d4f0aa20b08dccccc9a35%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638610426333066656%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=NjeTJaNlhdPChhF3yY%2B4vR6H4HXRjKw7T8XIBsV8tps%3D&reserved=0)). Next, we characterized Cys2pombe with succinyl-CoA in the presence of L-homoserine and L-serine. Its catalytic efficiency (kcat/Km) was more than 300 times higher with L-serine than with L-homoserine (6.2 × 103 versus 19 s−1 M−1; [Supplementary Table 8](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Farticles%2Fnchembio.2397%23MOESM1&data=05%7C02%7Cvw253%40cam.ac.uk%7Cce09a4b4ec2d4f0aa20b08dccccc9a35%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638610426333082662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=iz%2FHFCsaT9oU6iw7pfaV4%2BhYGEaWLRuhyMX2vRMUQhs%3D&reserved=0)), and implied the formation of O-succinyl-L-serine in the cell. The same reasoning applied for the next enzyme in the L-cysteine biosynthetic pathway, L-cysteine synthase (Cys1a). Cys1apombe was almost three times less efficient with O-acetyl-L-serine ([12](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Farticles%2Fnchembio.2397%2Fcompounds%2F12&data=05%7C02%7Cvw253%40cam.ac.uk%7Cce09a4b4ec2d4f0aa20b08dccccc9a35%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638610426333094720%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=OSUiZYULoATzkoMSXYAaWaI%2B8GVH0lF1J2%2Bw%2BaISt18%3D&reserved=0)) than with O-succinyl-L-serine (4.5 × 103 versus 1.2 × 104 s−1 M−1; [Supplementary Table 9](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Farticles%2Fnchembio.2397%23MOESM1&data=05%7C02%7Cvw253%40cam.ac.uk%7Cce09a4b4ec2d4f0aa20b08dccccc9a35%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638610426333105296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ysiXOrFE8pwLXzLjDj%2FnfEyDA%2FayEr6VabuPSvGP0xo%3D&reserved=0)), which suggested that S. pombe forms L-cysteine via O-succinyl-L-serine (CHEBI [134286](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ebi.ac.uk%2Fchebi%2FsearchId.do%3FchebiId%3DCHEBI%3A134286&data=05%7C02%7Cvw253%40cam.ac.uk%7Cce09a4b4ec2d4f0aa20b08dccccc9a35%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638610426333114630%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=spzepo63F3b3bCUYKI4bIp%2Ba%2F4j74ZHhY8s2Mgpj%2FRc%3D&reserved=0)). Finally, we detected O-succinyl-L-serine in the metabolome of the wild-type strain of S. pombe, but not in a Cys2 mutant (FY17212)[36](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Farticles%2Fnchembio.2397%23ref-CR36&data=05%7C02%7Cvw253%40cam.ac.uk%7Cce09a4b4ec2d4f0aa20b08dccccc9a35%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638610426333124633%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=e8yZNwxTQc%2FkVYFcaoXuUAv2er8ac8nxMqf7LZtaCdk%3D&reserved=0) ([Supplementary Fig. 16](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nature.com%2Farticles%2Fnchembio.2397%23MOESM1&data=05%7C02%7Cvw253%40cam.ac.uk%7Cce09a4b4ec2d4f0aa20b08dccccc9a35%7C49a50445bdfa4b79ade3547b4f3986e9%7C1%7C0%7C638610426333137693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=5fLJ9RTUPNdlSp1iHTTbwMW76BeLw%2FBzIBs0KC26bjQ%3D&reserved=0)). It should be noted that we did not detect O-acetyl-L-serine in the S. pombe metabolome.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160210
+name: L-serine O-succinyltransferase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: L-serine + succinyl-CoA = CoA + O-succinyl-L-serine." [PMID:28581482, RHEA:52820]
+xref: RHEA:52820
+is_a: GO:0016750 ! O-succinyltransferase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28832" xsd:anyURI
+created_by: rynl
+creation_date: 2024-09-04T23:29:11Z
