### ISSUE TITLE
Merge GO:0102472 and GO:0033771

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28849]
GO:0102472 - IEA 1 annotation

id: GO:0102472
name: eriodictyol 2-hydroxylase activity
def: "Catalysis of the reaction: eriodictyol + NADPH + O2 + 2 H+ = 2-hydroxyeriodictyol + NADP + H2O." [EC:1.14.13.-, GOC:pz]
xref: MetaCyc:RXN-14077
xref: RHEA:57596
is_a: GO:0016709 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, NAD(P)H as one donor, and incorporation of one atom of oxygen

RHEA says this a specific substrate of EC:1.14.14.162/RHEA:57584 => merge into flavanone 2-hydroxylase GO:0033771:

id: GO:0033771
name: flavanone 2-hydroxylase activity
namespace: molecular_function
def: "Catalysis of the reaction: a flavanone + O2 + reduced [NADPH--hemoprotein reductase] = a 2-hydroxyflavanone + H+ + H2O + oxidized [NADPH--hemoprotein reductase]." [EC:1.14.14.162, RHEA:57584]
synonym: "licodione synthase activity" NARROW []
xref: EC:1.14.14.162
xref: KEGG_REACTION:R07198
xref: MetaCyc:RXN-19645
xref: RHEA:57584
is_a: GO:0016712 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/25989" xsd:anyURI

**Comment by pgaudet** [comment]
Dear all, 
 
The proposal has been made to obsolete  GO:0102472 eriodictyol 2-hydroxylase activity. The reason for obsoletion is that this represents a specific substrate of GO:0033771 flavanone 2-hydroxylase activity, see https://www.rhea-db.org/rhea/57584. There are no annotations to this term, this term is not present in any subsets. 

Thanks, Pascale
