### ISSUE TITLE
Bulk obsoletion of catalytic terms with MetaCyc ID but no annotations

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28848]
Following on from #28776 which aims to resolve cases where the same xref is used as the def xref on multiple GO terms:

I think the following ~200 such terms can be obsoleted without further review - they have 0 annotations and have a single xref to a MetaCyc ID (a few also have a RHEA xref, but there are no RHEA annotations).

GO:0102907
GO:0102063
GO:0102385
GO:0102888
GO:0102065
GO:0102880
GO:0102066
GO:0102356
GO:0102886
GO:0102663
GO:0102569
GO:0102712
GO:0102495
GO:0102715
GO:0103008
GO:0102716
GO:0102496
GO:0102768
GO:0102972
GO:0102713
GO:0102714
GO:0103010
GO:0102653
GO:0102711
GO:0102494
GO:0103057
GO:0102755
GO:0102528
GO:0102941
GO:0102914
GO:0102603
GO:0102708
GO:0102147
GO:0102820
GO:0102122
GO:0102119
GO:0102438
GO:0102608
GO:0102399
GO:0102631
GO:0102630
GO:0102398
GO:0102709
GO:0102400
GO:0102942
GO:0102363
GO:0102939
GO:0102821
GO:0102436
GO:0102940
GO:0102629
GO:0102301
GO:0102583
GO:0102775
GO:0102247
GO:0102589
GO:0102817
GO:0102287
GO:0102737
GO:0102989
GO:0102093
GO:0102814
GO:0102594
GO:0102330
GO:0102595
GO:0102649
GO:0102586
GO:0102774
GO:0102248
GO:0102591
GO:0102806
GO:0102592
GO:0102660
GO:0102812
GO:0102581
GO:0102787
GO:0102333
GO:0102286
GO:0102788
GO:0102295
GO:0102275
GO:0102331
GO:0102332
GO:0102800
GO:0102898
GO:0102599
GO:0102897
GO:0102181
GO:0102370
GO:0102901
GO:0102368
GO:0102178
GO:0102902
GO:0102633
GO:0102606
GO:0102781
GO:0102427
GO:0103009
GO:0102639
GO:0102743
GO:0102899
GO:0102620
GO:0102372
GO:0102605
GO:0102152
GO:0102173
GO:0102680
GO:0102563
GO:0102376
GO:0102640
GO:0102602
GO:0102179
GO:0102292
GO:0102607
GO:0102600
GO:0102615
GO:0103098
GO:0102900
GO:0102133
GO:0102621
GO:0102476
GO:0102782
GO:0102466
GO:0102699
GO:0102992
GO:0102174
GO:0102052
GO:0102950
GO:0102951
GO:0102050
GO:0102665
GO:0102664
GO:0102051 
GO:0102123
GO:0102124
GO:0102730
GO:0102371
GO:0102125
GO:0102764
GO:0102142
GO:0019111
GO:0102141
GO:0102564
GO:0103005
GO:0102071
GO:0102508
GO:0102509
GO:0103105
GO:0102658
GO:0102570
GO:0102081
GO:0102582
GO:0102747
GO:0102753
GO:0102754
GO:0102298
GO:0102520
GO:0102792
GO:0102819
GO:0102727
GO:0102650
GO:0103044
GO:0102929
GO:0102540
GO:0102541
GO:0102281
GO:0102622
GO:0102681
GO:0102666
GO:0102667
GO:0036443
GO:0102297
GO:0102352
GO:0102827
GO:0102272
GO:0102273
GO:0102647
GO:0102648
GO:0102004
GO:0102725
GO:0103003
GO:0102912
GO:0102182
GO:0102896

**Comment by sjm41** [comment]
Hi @balhoff Just checking you are OK to action this ticket?

**Comment by balhoff** [comment]
@sjm41 yes, will do ASAP.

**Comment by balhoff** [comment]
@sjm41 which obsoletion reason should I attach to these?

**Comment by sjm41** [comment]
- [ ]  The reason for obsoletion is that is not known to be catalyzed by any gene product.

**Comment by balhoff** [comment]
Sorry for the delay @sjm41, this is done now.

**Comment by sjm41** [comment]
No problem! Thanks for taking care of this.

**Comment by Antonialock** [comment]
@sjm41 I annotated to GO:0102142 yesterday, Is there an alternative suggestion?

https://www.sciencedirect.com/science/article/pii/S0021925819737363?via%3Dihub
https://www.mdpi.com/1422-0067/23/13/7485
e,g https://www.ebi.ac.uk/internal-tools/protein2go/dynamic.html?database=production#ac=Q9Y2C2

**Comment by sjm41** [comment]
Hi @Antonialock 

I believe it's relatively straightforward to reinstate this term since you've now found a use case for it!
Until today, there were no annotations to the term, and I don't see anything a matching reaction in RHEA/EC (though the original GO term did have an xref to MetaCyc:RXN-11561).

So, I think we need to make a new ticket to reinstate the term, add the PMIDs you found (35806490 & 10187838) as def xrefs, and also ask RHEA to create an entry for it, which we can then add as an additional xref.  Right @pgaudet ?

Original entry:

id: GO:0102142
name: [dermatan sulfate]-L-iduronyl 2-Osulfotransferase activity
def: "Catalysis of the reaction: 3'-phosphonato-5'-adenylyl sulfate + [dermatan]-alpha-L-iduronate = adenosine 3',5'-bismonophosphate + [dermatan-sulfate]-2-O-sulfo-alpha-L-iduronate." [EC:2.8.2.-, GOC:pz]
xref: MetaCyc:RXN-11561
is_a: GO:0008146 ! sulfotransferase activity

**Comment by pgaudet** [comment]
Hi @Antonialock 

We can re-instate the term. Do you know if RHEA will create a reaction for this activity?

**Comment by Antonialock** [comment]
I don't know. I added the annotation as the original annotation to sulfotransferase activity was disputed

**Comment by pgaudet** [comment]
Hi @Antonialock 

I restored the term. I also emailed the Rhea helpdesk for help on this activity. 

I'll open another ticket when I hear back.

Thanks, Pascale
