### ISSUE TITLE
aliphatic desulfoglucosinolate sulfotransferase activity (GO:0120527) merges

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28853]
MetaCyc says that the 6 terms below are specific instances of EC:2.8.2.38 = GO:0120527
=> Merge these 6 GO terms into GO:0120527

id: GO:0120527
name: aliphatic desulfoglucosinolate sulfotransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 3'-phosphoadenylyl sulfate + an aliphatic (Z)-desulfo-glucosinolate = a (Z)-omega-(methylsulfanyl)-N-sulfo-alkylhydroximate S-glucoside + adenosine 3',5'-bisphosphate + H+." [RHEA:52724]
xref: EC:2.8.2.38 {source="skos:exactMatch"}
xref: MetaCyc:RXN-18179 {source="skos:exactMatch"}
xref: RHEA:52724 {source="skos:exactMatch"}
is_a: GO:0008146 ! sulfotransferase activity

---

id: GO:0103104 - 0 annotations
name: 6-methylthiohexyldesulfoglucosinolate sulfotransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 6-methylthiohexyldesulfoglucosinolate + 3'-phosphonato-5'-adenylyl sulfate = adenosine 3',5'-bismonophosphate + H+ + 6-methylthiohexylglucosinolate." [EC:2.8.2.-, GOC:pz]
xref: MetaCyc:RXNQT-4331
is_a: GO:0008146 ! sulfotransferase activity

id: GO:0080068 - 3 annotations - 1 TAIR IDA
name: 5-methylthiopentyl-desulfoglucosinolate sulfotransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 5-methylthiopentyl-desulfoglucosinolate + 3'-phosphoadenosine 5'-phosphosulfate = 5-methylthiopentyl-glucosinolate + adenosine 3',5'-bisphosphate." [PMID:19077143]
xref: MetaCyc:RXNQT-4330
is_a: GO:0047364 ! desulfoglucosinolate sulfotransferase activity
created_by: dhl
creation_date: 2009-04-13T04:06:59Z

id: GO:0080066 - 3 annotations - 1 TAIR IDA
name: 3-methylthiopropyl-desulfoglucosinolate sulfotransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 3-methylthiopropyl-desulfoglucosinolate + 3'-phosphoadenosine 5'-phosphosulfate = 3-methylthiopropyl-glucosinolate + adenosine 3',5'-bisphosphate." [PMID:19077143]
xref: MetaCyc:RXN-2209
is_a: GO:0047364 ! desulfoglucosinolate sulfotransferase activity
created_by: dhl
creation_date: 2009-04-13T04:04:08Z

id: GO:0080070 - 3 annotations - 1 TAIR IDA
name: 8-methylthiooctyl-desulfoglucosinolate sulfotransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 8-methylthiooctyl-desulfoglucosinolate + 3'-phosphoadenosine 5'-phosphosulfate = 8-methylthiooctyl-glucosinolate + adenosine 3',5'-bisphosphate." [PMID:19077143]
xref: MetaCyc:RXNQT-4333
is_a: GO:0047364 ! desulfoglucosinolate sulfotransferase activity
created_by: dhl
creation_date: 2009-04-13T04:07:58Z

id: GO:0080067 - 3 annotations -  1 TAIR IDA
name: 4-methylthiobutyl-desulfoglucosinolate sulfotransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 4-methylthiobutyl-desulfoglucosinolate + 3'-phosphoadenosine 5'-phosphosulfate = 4-methylthiobutyl-glucosinolate + adenosine 3',5'-bisphosphate." [PMID:19077143]
xref: MetaCyc:RXNQT-4329
is_a: GO:0047364 ! desulfoglucosinolate sulfotransferase activity
created_by: dhl
creation_date: 2009-04-13T04:05:53Z

id: GO:0080069 - 3 annotations -  1 TAIR IDA
name: 7-methylthioheptyl-desulfoglucosinolate sulfotransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: 7-methylthioheptyl-desulfoglucosinolate + 3'-phosphoadenosine 5'-phosphosulfate = 7-methylthioheptyl-glucosinolate + adenosine 3',5'-bisphosphate." [PMID:19077143]
xref: MetaCyc:RXNQT-4332
is_a: GO:0047364 ! desulfoglucosinolate sulfotransferase activity
created_by: dhl
creation_date: 2009-04-13T04:07:32Z

**Comment by pgaudet** [comment]
All IDAs are to TAIT SOT18 ([AT1G74090](http://arabidopsis.org/servlets/TairObject?type=locus&name=AT1G74090))

**Comment by pgaudet** [comment]
Also, related to this: 
Changed label of [desulfoglucosinolate sulfotransferase activity](http://purl.obolibrary.org/obo/GO_0047364) to add **aromatic** desulfoglucosinolate sulfotransferase activity, to match the EC (https://enzyme.expasy.org/EC/2.8.2.24) and distinguish it more clearly from GO:0120527 aliphatic desulfoglucosinolate sulfotransferase activity (EC:2.8.2.38 )

**Comment by pgaudet** [comment]
Other obsoletions in this branch: 

GO:0080071
name: indol-3-yl-methyl-desulfoglucosinolate sulfotransferase activity
namespace: molecular_function
def: "Catalysis of the reaction: indol-3-yl-methyl-desulfoglucosinolate + 3'-phosphoadenosine 5'-phosphosulfate = indol-3-yl-methyl-glucosinolate + adenosine 3',5'-bisphosphate." [PMID:19077143]
xref: MetaCyc:RXN-1443
>> replace by parent [aromatic desulfoglucosinolate sulfotransferase activity](http://purl.obolibrary.org/obo/GO_0047364)

1 EXP TAIR.
