### ISSUE TITLE
gibberellin 2-beta-dioxygenase activity merges

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28852]
Looks like the 6 terms below should be merged into GO:0045543:
id: GO:0045543
name: gibberellin 2-beta-dioxygenase activity
namespace: molecular_function
def: "Catalysis of the reaction: a gibberellin + 2-oxoglutarate + O2 = a 2-beta-hydroxygibberellin + succinate + CO2." [GOC:kad, RHEA:15005]
synonym: "gibberellin 2-beta-hydroxylase activity" RELATED [EC:1.14.11.13]
synonym: "gibberellin 2-oxidase activity" EXACT []
synonym: "gibberellin 2beta-dioxygenase activity" RELATED [EC:1.14.11.13]
synonym: "gibberellin 2beta-hydroxylase activity" RELATED [EC:1.14.11.13]
xref: EC:1.14.11.13
xref: RHEA:15005
is_a: GO:0016706 ! 2-oxoglutarate-dependent dioxygenase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/22382" xsd:anyURI

---

- [x] GO:0102111 - 23 annotations - 1 EXP UniProt
id: GO:0102111
name: gibberellin A20,2-oxoglutarate:oxygen oxidoreductase activity
def: "Catalysis of the reaction: gibberellin A20 + 2-oxoglutarate + O2 = gibberellin A29 + succinate + carbon dioxide." [EC:1.14.11.-, GOC:pz]
xref: MetaCyc:RXN-113
is_a: GO:0016706 ! 2-oxoglutarate-dependent dioxygenase activity
=> MetaCyc says this is version of EC:1.14.11.13 (GO:0045543 gibberellin 2-beta-dioxygenase activity) 

- [x] GO:0102924 - 23 annotations - 1 EXP UniProt
id: GO:0102924
name: gibberellin A44,2-oxoglutarate:oxygen oxidoreductase activity
def: "Catalysis of the reaction: 2 H+ + gibberellin A44 + 2-oxoglutarate + O2 = gibberellin A98 + succinate + carbon dioxide." [EC:1.14.11.-, GOC:pz]
xref: MetaCyc:RXN-886
is_a: GO:0016706 ! 2-oxoglutarate-dependent dioxygenase activity
=> MetaCyc says this is version of EC:1.14.11.13 (GO:0045543 gibberellin 2-beta-dioxygenase activity)

- [x] GO:0102652 - 23 annotations - 1 EXP UniProt
id: GO:0102652
name: gibberellin A9,2-oxoglutarate:oxygen oxidoreductase activity
def: "Catalysis of the reaction: gibberellin A9 + 2-oxoglutarate + O2 = gibberellin A51 + succinate + carbon dioxide." [EC:1.14.11.-, GOC:pz]
xref: MetaCyc:RXN-171
is_a: GO:0016706 ! 2-oxoglutarate-dependent dioxygenase activity
=> ~MetaCyc says this is version of EC:1.14.11.13 (GO:0045543 gibberellin 2-beta-dioxygenase activity)~  gibberellin 3-beta-dioxygenase activity ; GO:0016707

- [x] GO:0103055 - 2 annotations - only IEAs
id: GO:0103055
name: gibberelli A15, 2-oxoglutarate:oxygen oxidoreductase activity
def: "Catalysis of the reaction: gibberellin A15 + 2-oxoglutarate + O2 = gibberellin A24 + succinate + carbon dioxide + H2O." [EC:1.14.11.-, GOC:pz]
xref: MetaCyc:RXN1F-163
xref: RHEA:60780
is_a: GO:0016706 ! 2-oxoglutarate-dependent dioxygenase activity
=> MetaCyc just maps this to EC:1.14.11.- but it looks like another instance of EC:1.14.11.13 (GO:0045543 gibberellin 2-beta-dioxygenase activity)

- [x] GO:0103054 - 2 annotations - only IEAs
id: GO:0103054
name: gibberellin A12, 2-oxoglutarate:oxygen oxidoreductase activity (gibberellin A15-forming)
def: "Catalysis of the reaction: gibberellin A12 + O2 + 2-oxoglutarate = gibberellin A15 + carbon dioxide + succinate." [EC:1.14.11.-, GOC:pz]
xref: MetaCyc:RXN1F-162
xref: RHEA:60776
is_a: GO:0016706 ! 2-oxoglutarate-dependent dioxygenase activity
=> MetaCyc just maps this to EC:1.14.11.- ~but it looks like another instance of EC:1.14.11.13 (GO:0045543 gibberellin 2-beta-dioxygenase activity)~ replace by gibberellin 20-oxidase activity ; GO:0045544.

- [x] GO:0103056 - 2 annotations  - only IEAs
id: GO:0103056
name: gibberellin A53, 2-oxoglutarate:oxygen oxidoreductase activity
def: "Catalysis of the reaction: gibberellin A53 + O2 + 2-oxoglutarate = gibberellin A44 diacid + carbon dioxide + succinate." [EC:1.14.11.-, GOC:pz]
xref: MetaCyc:RXN1F-167
xref: RHEA:60800
is_a: GO:0016706 ! 2-oxoglutarate-dependent dioxygenase activity
=> MetaCyc just maps this to EC:1.14.11.- ~but it looks like another instance of EC:1.14.11.13 (GO:0045543 gibberellin 2-beta-dioxygenase activity)~ gibberellin 20-oxidase activity ; GO:0045544.

**Comment by pgaudet** [comment]
There are more terms: 

GO:0102714 gibberellin A12,oxoglutarate:oxygen oxidoreductase activity
GO:0102712 gibberellin A13,oxoglutarate:oxygen oxidoreductase activity
GO:0102715 gibberellin A17,oxoglutarate:oxygen oxidoreductase activity
GO:0102711 gibberellin A25,oxoglutarate:oxygen oxidoreductase activity
GO:0102716 gibberellin A28,oxoglutarate:oxygen oxidoreductase activity
GO:0102652 gibberellin A9,2-oxoglutarate:oxygen oxidoreductase activity
GO:0102972 gibberellin A12,2-oxoglutarate:oxygen oxidoreductase activity (gibberellin A110-forming)
GO:0102111 gibberellin A20,2-oxoglutarate:oxygen oxidoreductase activity
GO:0102663 gibberellin A34,2-oxoglutarate:oxygen oxidoreductase activity
GO:0102924 gibberellin A44,2-oxoglutarate:oxygen oxidoreductase activity
GO:0102653 gibberellin A51,2-oxoglutarate:oxygen oxidoreductase activity
GO:0103010 gibberellin A53,2-oxoglutarate:oxygen oxidoreductase activity (GA97-forming)
GO:0103054 gibberellin A12, 2-oxoglutarate:oxygen oxidoreductase activity (gibberellin A15-forming)
GO:0103057 gibberellin A19, 2-oxoglutarate:oxygen oxidoreductase activity
GO:0103056 gibberellin A53, 2-oxoglutarate:oxygen oxidoreductase activity
GO:0102755 gibberellin-15(closed lactone form),2-oxoglutarate:oxygen oxidoreductase (3beta-hydroxylating) activity
GO:0102738 (gibberellin-14), 2-oxoglutarate:oxygen oxidoreductase activity
GO:0102739 (gibberellin-36), 2-oxoglutarate:oxygen oxidoreductase activity


According to wikipedia, there are 136 GAs: https://en.wikipedia.org/wiki/Gibberellin

I suppose we may want to keep some major ones (if there are), but other terms that were not in the original list don't have annotations (see https://github.com/geneontology/go-annotation/issues/5445), so for now I will obsolete them.

**Comment by pgaudet** [comment]
Obsolete 
GO:0047927
-name: gibberellin-44 dioxygenase activity
-namespace: molecular_function
-def: "Catalysis of the reaction: gibberellin 44 + 2-oxoglutarate + O2 = gibberellin 19 + succinate + CO2." [EC:1.14.11.12, MetaCyc:GIBBERELLIN-44-DIOXYGENASE-RXN]
-synonym: "(gibberellin-44), 2-oxoglutarate:oxygen oxidoreductase activity" RELATED [EC:1.14.11.12]
-synonym: "(gibberellin-44),2-oxoglutarate:oxygen oxidoreductase activity" RELATED [EC:1.14.11.12]
-synonym: "gibberellin A44 oxidase activity" RELATED [EC:1.14.11.12]
-synonym: "oxygenase, gibberellin A44 oxidase activity" RELATED [EC:1.14.11.12]
-xref: EC:1.14.11.12
-xref: MetaCyc:RXN1F-168
-xref: RHEA:16033


 because it is an intermediate in gibberellin 20-oxidase activity GO:0045544, see PMID:32652020. No annotations, so associations in EC or in RHEA.

**Comment by pgaudet** [comment]
Another family: 

- [ ] GO:0102123  gibberellin A4 16alpha,17 epoxidase activity  - 0 annotations
def: "Catalysis of the reaction: gibberellin A4 + O2 + H+ + NAD(P)H = 16alpha,17-epoxy gibberellin A4 + H2O + NAD(P)." [EC:1.14.-.-, GOC:pz]
xref: MetaCyc:RXN-11385
- [ ]  GO:0102124 gibberellin A12 16alpha,17 epoxidase activity - 0 annotations
namespace: molecular_function
def: "Catalysis of the reaction: gibberellin A12 + O2 + H+ + NAD(P)H = 16alpha, 17-epoxy gibberellin A12 + H2O + NAD(P)." [EC:1.14.-.-, GOC:pz]
xref: MetaCyc:RXN-11387
- [ ] GO:0102125  - 0 annotations
name: gibberellin A9 16alpha,17 epoxidase activity
namespace: molecular_function
def: "Catalysis of the reaction: gibberellin A9 + O2 + H+ + NAD(P)H = 16alpha, 17-epoxy gibberellin A9 + H2O + NAD(P)." [EC:1.14.-.-, GOC:pz]
xref: MetaCyc:RXN-11388

MetaCyc states: 
>> Although the exact biochemical reactions carried out by this enzyme have not been identified to date, based on comparisons with other cytochrome P450 enzymes, it is likely that NAD(P)H and O2 are involved in this reaction.

Based on the lack of understanding of the reaction and the ack of annotations, I will obsolete these as well.
