### ISSUE TITLE
Obsoletion?: serine-pyruvate aminotransferase complex

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28856]
id: GO:0005969
name: serine-pyruvate aminotransferase complex
namespace: cellular_component
alt_id: GO:0005970
def: "An enzyme complex that catalyzes the formation of hydroxypyruvate and alanine from serine and pyruvate." [EC:2.6.1.51]
synonym: "serine-pyruvate aminotransferase, type 1 complex" NARROW []
synonym: "serine-pyruvate aminotransferase, type 2B complex" NARROW []
intersection_of: GO:0032991 ! protein-containing complex
intersection_of: capable_of GO:0004760 ! L-serine-pyruvate transaminase activity
relationship: part_of GO:0005737 ! cytoplasm

This complex is currently defined by EC:2.6.1.51, though the EC entry doesn't mention a complex.
There is one EXP annotation to mouse Eea1 from PMID:16399794 by MGI.
But I don't see mention of a "serine-pyruvate aminotransferase complex" in that paper.
So, obsolete this term?
(If keep, then remove EC from GO:0005969 def xref, though I can't find a real reference for this complex....)

**Comment by raymond91125** [comment]
I cannot find any reference to support this protein complex either.

**Comment by raymond91125** [comment]
Mouse Eea1 should probably be transferred to GO:0005769 early endosome.

**Comment by ukemi** [comment]
The mouse annotation looks like a typo. I fixed it. PMID: 851432 suggests the enzyme is a dimer.

**Comment by raymond91125** [comment]
Thanks. I did not see this reference. According to <https://wiki.geneontology.org/Protein_complexes>, "Homomultimeric proteins, e.g. the homodimeric alcohol dehydrogenase, may be included as cellular component terms,".

Perhaps we should keep this complex then?

Raymnod

**Comment by sjm41** [comment]
We touch on another can-of-worms...
A couple of months back, Pascale and I had also been thinking they were out-of-scope, but then also found the sentence in the doc saying they are actually in scope for GO!  I've certainly come across several instances of homomeric complexes in GO, though unfortunately, as in this case, the GO def doesn't always say that they are homomeric....

Since we now have evidence (thanks David and Chris!) I'd said we can keep GO:0005969 but swap the EC def xref for PMID:851432 & PMID: 22751661 and tweak the def to say that it's a "homodimeric complex".

Whether or not these things are generally in scope or not seems a wider discussion, which I'm happy to be involved in!

**Comment by sjm41** [comment]
Thanks @raymond91125 !

Though I noticed a typo in the new def:
def: "An protein homedieric complex that catalyzes the formation of hydroxypyruvate and alanine from serine and pyruvate." [PMID:22751661, PMID:851432]

homedieric -> homodimeric

**Comment by raymond91125** [comment]
Thanks!
