### ISSUE TITLE
Merge carboxynorspermidine dehydrogenase terms

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28857]
id: GO:0102143 (0 annotations)
name: carboxynorspermidine dehydrogenase I activity
def: "Catalysis of the reaction: carboxynorspermidine + NADP + H2O = L-aspartic acid 4-semialdehyde betaine + trimethylenediaminium + NADPH + H+." [EC:1.5.1.43, GOC:pz]
xref: MetaCyc:RXN-11565
xref: RHEA:34115
is_a: GO:0016646 ! oxidoreductase activity, acting on the CH-NH group of donors, NAD or NADP as acceptor

id: GO:0102144 (0 annotations)
name: carboxyspermidine dehydrogenase II activity
def: "Catalysis of the reaction: carboxyspermidine + H2O + NADP = L-aspartic acid 4-semialdehyde betaine + 1,4-butanediammonium + NADPH + H+." [EC:1.5.1.43, GOC:pz]
xref: MetaCyc:RXN-11566
xref: RHEA:34111
is_a: GO:0016646 ! oxidoreductase activity, acting on the CH-NH group of donors, NAD or NADP as acceptor

These two terms are both defined by EC:1.5.1.43, and EC indeed covers both reactions:
**carboxynorspermidine synthase:**
carboxynorspermidine + H2O + NADP(+) = H(+) + L-aspartate 4-semialdehyde + NADPH + propane-1,3-diamine
carboxyspermidine + H2O + NADP(+) = H(+) + L-aspartate 4-semialdehyde + NADPH + putrescine

Suggest these are merged into a single term that looks like this:

name: carboxyspermidine synthase activity
def: "Catalysis of the reactions: carboxynorspermidine + H2O + NADP(+) = H(+) + L-aspartate 4-semialdehyde + NADPH + propane-1,3-diamine and carboxyspermidine + H2O + NADP(+) = H(+) + L-aspartate 4-semialdehyde + NADPH + putrescine [EC:1.5.1.43]
xref: EC:1.5.1.43 [exactMatch]
xref: MetaCyc:RXN-11566 [narrowMatch]
xref: RHEA:34111 [narrowMatch]
xref: MetaCyc:RXN-11565 [narrowMatch]
xref: RHEA:34115 [narrowMatch]
is_a: GO:0016646 ! oxidoreductase activity, acting on the CH-NH group of donors, NAD or NADP as acceptor

**Comment by pgaudet** [comment]
I wonder which is the physiological substrate? 

[EC](ttps://enzyme.expasy.org/EC/1.5.1.43) states "The enzyme from Campylobacter jejuni only produces carboxyspermidine in vivo even though it also can produce carboxynorspermidine in vitro.", but in Vibrio norspermidine seems to be more relevant: https://pubmed.ncbi.nlm.nih.gov/19694812/

**Comment by sjm41** [comment]
I don't know about the physiological substrate...
I do see that the same two proteins are annotated with the two RHEA reactions at UP (Vibrio P0DPE4 and Q9KRL3).
So I think we just go ahead with the merge and mention both reactions in the def?
