### ISSUE TITLE
Obsolete "nitric-oxide synthase biosynthetic process"?

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28860]
id: GO:0051767
name: nitric-oxide synthase biosynthetic process
namespace: biological_process
alt_id: GO:0051768
def: "The chemical reactions and pathways resulting in the formation of a nitric-oxide synthase, an enzyme which catalyzes the reaction L-arginine + n NADPH + n H+ + m O2 = citrulline + nitric oxide + n NADP+." [EC:1.14.13.39, GOC:ai]
synonym: "brain nitric-oxide synthase biosynthetic process" NARROW [GOC:bf]
synonym: "endothelial nitric-oxide synthase biosynthetic process" NARROW [GOC:bf]
synonym: "inducible nitric-oxide synthase biosynthetic process" NARROW [GOC:bf]
synonym: "nitric-oxide synthase (type 2) biosynthesis" NARROW []
synonym: "nitric-oxide synthase (type 2) biosynthetic process" NARROW []
synonym: "nitric-oxide synthase (type II) biosynthesis" NARROW []
synonym: "nitric-oxide synthase (type II) biosynthetic process" NARROW []
synonym: "nitric-oxide synthase 2 biosynthetic process" NARROW []
synonym: "nitric-oxide synthase-1 biosynthetic process" NARROW [GOC:bf]
synonym: "nitric-oxide synthase-2 biosynthetic process" NARROW [GOC:bf]
synonym: "nitric-oxide synthase-3 biosynthetic process" NARROW [GOC:bf]
synonym: "NO synthase biosynthesis" EXACT []
synonym: "NO synthase biosynthetic process" EXACT []
synonym: "NOS biosynthesis" EXACT []
synonym: "NOS biosynthetic process" EXACT []
synonym: "NOS1 biosynthesis" NARROW [GOC:bf]
synonym: "NOS2 biosynthesis" NARROW [GOC:bf]
synonym: "NOS2 synthase biosynthesis" NARROW []
synonym: "NOS2 synthase biosynthetic process" NARROW []
synonym: "NOS3 biosynthesis" NARROW [GOC:bf]
is_a: GO:0009059 ! macromolecule biosynthetic process

This term appears to describe a BP synthesising the "nitric-oxide synthase" enzyme.
It is currently defined by the EC of that enzyme (which is correctly a term/def xref on the MF GO:0004517 nitric-oxide synthase activity).
GO:0051767 has 0 annotations.

I suggest it's obosoleted.
But if it's kept, then we should remove the EC def xref and find a better reference.

**Comment by deustp01** [comment]
Is this also a GO term that applies to a single gene product, and hence needs to be obsoleted in favor of a broader parent term for that reason?

**Comment by sjm41** [comment]
I decided not to add a public comment to try to explain why we have this term but no annotations, but I added a link to this ticket so that editors will be pointed to this little discussion.

**Comment by ukemi** [comment]
And I'm sure you're thinking the same as me....'I wonder if we could do this better in a specific GO-CAM model without the asserted term in the ontology'.

**Comment by pgaudet** [comment]
This refers to the synthesis of a specific gene product - ther expression of many genes is specifically regulated, I dont think we want to create terms for each target.

**Comment by sjm41** [comment]
Right, that was my initial thought too, especially when I saw "nitric-oxide synthase biosynthetic process" had 0 annotations.
But then @ukemi explained that "the regulation of the enzyme's synthesis is a major control point for downstream blood pressure regulation and the target process was needed for the logical definitions of the regulation terms".
And I see 56 EXP annotations to those regulation terms.

So, the question is whether this is a special case where the "(regulation of the) synthesis of a specific gene product" is a valid GO term?

**Comment by deustp01** [comment]
> So, the question is whether this is a special case where the "(regulation of the) synthesis of a specific gene product" is a valid GO term?

An annotation / ontology structure question is whether this grouping term is needd to link all the child annotations mentioned above to the grandparent term [GO:0009059](https://www.ebi.ac.uk/QuickGO/term/GO:0009059) macromolecule biosynthetic process, or whether in a GO0-CAM world the generic macromolecule process term plus the specific regulation term, all associated with NOS3 synthase enzyme (human [P29474](https://www.uniprot.org/uniprotkb/P29474/entry)) and its associated molecular function [GO:0004517](https://www.ebi.ac.uk/QuickGO/term/GO:0004517) nitric-oxide synthase activity would capture all of the information and avoid the need for a gene product-specific GO term? (This is a question, not an argument.)

**Comment by raymond91125** [comment]
GO:0051767 nitric-oxide synthase biosynthetic process may be better placed under GO:0010467 gene expression. There are similar terms like GO:0002781 antifungal peptide production in that the term itself has no annotations and its regulation terms do.

As @deustp01 alluded to, it's probably better to model the full information in GO-CAM than having these 'short-hand' terms, I think.

**Comment by raymond91125** [comment]
One example of annotation reference. PMID:11536325
![image](https://github.com/user-attachments/assets/ea9501c8-6436-4920-955d-50c8135761e7)

**Comment by pgaudet** [comment]
Discussion on the ontology editor's call: 
There are no annotations to NO synthase biosynthesis 
The annotations to the regulation of NO synthase biosynthesis are to signaling molecules, indicating that they should instead be annotated to the appropriate signaling pathway, + 'acts upstream of, positive effect' (positive) [GO:0141149 regulation of nitric oxide-cGMP mediated signal transduction](https://amigo.geneontology.org/amigo/term/GO:0141149#display-lineage-tab)

**Comment by raymond91125** [comment]
@pgaudet It turns out this term is used by the LD of CL:0000863 inflammatory macrophage. Thus it may be in the category of 'exceptions' you referred to regarding CL's needs.

**Comment by pgaudet** [comment]
@cmungall says we should open a CL ticket to request that they revise the logical definition. 
This is **_not_** a defining property of these cells 

@raymond91125 Can you please do that?
