### ISSUE TITLE
ecdysone-phosphate phosphatase activity / ecdysteroid-phosphate phosphatase activity

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28862]
There are currently these 2 distinct but related terms:

id: GO:0102531 - 3 annotations (all EXP by FlyBase/UniProt to Bombyx EPP and Drosophila App)
name: ecdysteroid-phosphate phosphatase activity
def: "Catalysis of the reaction: H2O + an ecdysteroid 22-phosphate = hydrogenphosphate + an ecdysteroid." [GOC:pz, PMID:12721294]
xref: MetaCyc:RXN-14734
xref: RHEA:63576
is_a: GO:0016791 ! phosphatase activity

id: GO:0102537 - no annotations
name: ecdysone-phosphate phosphatase activity
def: "Catalysis of the reaction: ecdysone 22-phosphate + H2O = ecdysone + hydrogenphosphate." [EC:3.1.3.-, GOC:pz]
xref: MetaCyc:RXN-14766
is_a: GO:0016791 ! phosphatase activity

RHEA:63576 is "ecdysone 22-phosphate + H2O = ecdysone + phosphate" it is mapped to MetaCyc:RXN-14766.

RHEA:63576 is annotated to Bombyx EPP and Drosophila Epp
MetaCyc:RXN-14766 and MetaCyc:RXN-14734 are both associated with just Bombyx EPP at MetaCyc
MetaCyc:RXN-14734 has no mapping in RHEA.

Looking at the papers used in the 3 GO annotations, the activity isn't specific to ecdysone 22-phosphate, but has wider specificity to other ecdysteroids.

Taken together, I think this means we just want one term in the GO that looks like this:

name: ecdysteroid-phosphate phosphatase activity
def: "Catalysis of the reaction: an ecdysteroid 22-phosphate + H2O = an ecdysteroid + phosphate." [MetaCyc:RXN-14734, PMID:12721294]
xref: MetaCyc:RXN-14734 [exactMatch]
xref: MetaCyc:RXN-14766 [narrowMatch]
xref: RHEA:63576 [narrowMatch]
is_a: GO:0016791 ! phosphatase activity

**Comment by pgaudet** [comment]
Dear all, 

The proposal has been made to obsolete GO:0102531  ecdysone-phosphate phosphatase activity. The reason for obsoletion is that this term represents the same activity as GO:0102537 ecdysone-phosphate phosphatase activity; the activity isn't specific to ecdysone 22-phosphate, but has wider specificity to other ecdysteroids 22 phosphate. There are no annotations to this term; this term is not in any subsets. 

You can comment on the ticket: 
https://github.com/geneontology/go-ontology/issues/28862

Thanks, Pascale

**Comment by pgaudet** [comment]
@sjm41 
Also added 

+xref: RHEA:63580 {source="skos:narrowMatch"}
+xref: RHEA:63584 {source="skos:narrowMatch"}

since I dont see that these have a 'more general' parent.
