### ISSUE TITLE
NTR: [apicoplast membrane]

### ISSUE THREAD

**Issue by nadya-urakova** [geneontology/go-ontology#28872]
Please provide as much information as you can: 

* **Suggested term label:**
apicoplast membrane

* **Definition (free text)**
Any of the lipid bilayers that surround an apicoplast and form the apicoplast envelope

* **Reference, in format PMID:#######**
38865262

* **Gene product name and ID to be annotated to this term**
A0A7J6KE60 A0A7J6K629 (APC1 and APC2)

* **Parent term(s)**
GO:0042170 plastid membrane
GO:0020011 apicoplast

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
Apicoplast has 3 or 4 membranes. PMID:20124342

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160211
+name: apicoplast membrane
+namespace: cellular_component
+def: "Any of the lipid bilayers that surround an apicoplast and form the apicoplast envelope." [PMID:20124342, PMID:38865262]
+is_a: GO:0031090 ! organelle membrane
+relationship: part_of GO:0020011 ! apicoplast
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28872" xsd:anyURI
+created_by: rynl
+creation_date: 2024-09-07T00:44:46Z
