### ISSUE TITLE
glycine-gated cation channel activity

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#28887]
Please provide as much information as you can: 

* **Suggested term label:**
glycine-gated cation channel activity

* **Definition (free text)**
Enables the transmembrane transfer of a cation  by a channel that opens when glycine is bound by the channel complex or one of its constituent parts on the extracellular side of the plasma membrane. 

* **Reference, in format PMID:11823786
(REQUIRED)

* **Gene product name and ID to be annotated to this term**

* **Parent term(s)**
transmitter-gated monoatomic ion channel activity [GO:0022824] 

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160212
+name: glycine-gated cation channel activity
+namespace: molecular_function
+def: "Enables the transmembrane transfer of a cation by a channel that opens when glycine is bound by the channel complex or one of its constituent parts on the extracellular side of the plasma membrane." [PMID:11823786]
+is_a: GO:0022824 ! transmitter-gated monoatomic ion channel activity
+intersection_of: GO:0022836 ! gated channel activity
+intersection_of: has_primary_input CHEBI:23906 ! monoatomic cation
+intersection_of: has_small_molecule_activator CHEBI:57305 ! glycine zwitterion
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28887" xsd:anyURI
+created_by: rynl
+creation_date: 2024-09-10T16:55:41Z
