### ISSUE TITLE
NTR: phosphatidylinositol 4-phosphate biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28898]
Please provide as much information as you can: 

* **Suggested term label:**

- [x] phosphatidylinositol 4-phosphate  biosynthetic process

(see below)

* **Definition (free text)**

- [x]  standard def

* **Reference, in format PMID:#######**

- [x]  PMID:39239853
Title | Fission yeast Duc1 links to ER-PM contact sites and influences PM lipid composition and cytokinetic ring anchoring.

* **Gene product name and ID to be annotated to this term**

f.y stt4 at first

* **Parent term(s)**

phosphatidylinositol phosphate biosynthetic

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

- [x] PI4P biosynthesis
- [x]  1-phosphatidyl-1D-myo-inositol biosynthetic process 
- [x]  phosphatidylinositol (PI)-4- phosphate biosynthetic process
- [x]  phosphatidylinositol-4-phosphate synthesis
- [x] 1-phosphatidyl-1D-myo-inositol 4-phosphate biosynthesis

* **Any other information**

 seven PIP species found in eukaryotic cells, PM phosphatidylinositol (PI)-4- phosphate (PI4P) and the most abundant PM PIP species, PI-4,5-bisphosphate [PI(4,5)P2], are important for the fidelity of cell division in diverse organisms (Eggert et al., 2004; Emoto et al., 2005; Field et al., 2005; Janetopoulos et al., 2005; Snider et al., 2017b, 2018b; Wong et al., 2005).

we have

[GO:1903102](https://www.ebi.ac.uk/QuickGO/term/GO:1903102)    1-phosphatidyl-1D-myo-inositol 3,5-bisphosphate biosynthetic process	is_a
[GO:1902635](https://www.ebi.ac.uk/QuickGO/term/GO:1902635)    1-phosphatidyl-1D-myo-inositol 4,5-bisphosphate biosynthetic process	is_a
[GO:0036092](https://www.ebi.ac.uk/QuickGO/term/GO:0036092)    phosphatidylinositol-3-phosphate biosynthetic process	is_a
[GO:1904563](https://www.ebi.ac.uk/QuickGO/term/GO:1904563)    phosphatidylinositol 5-phosphate biosynthetic process

This request adds one more, so we are still missing 2
We also need to standardise  and use either 1-phosphatidyl-1D-myo-inositol or phosphatidylinositol in these labels.
I think Rhea uses 1-phosphatidyl-1D-myo-inositol  but in practice everyone uses  "phosphatidylinositol"
all need synonyms and common names adding

(not to self stt4)

**Comment by ValWood** [comment]
also note for some of these the common names are in comments
these aren't  searchable:

<img width="951" alt="Screenshot 2024-09-11 at 08 10 22" src="https://github.com/user-attachments/assets/2c8cb147-fd75-4b01-a6cd-34a0f25c0444">

**Comment by ValWood** [comment]
@pgaudet @sjm41 
what should the standardization be with hyphens here?

phosphatidylinositol 4-phosphate synthesis
or
phosphatidylinositol-4-phosphate synthesis

We have both
phosphatidylinositol-3-phosphate synthesis
phosphatidylinositol 5-phosphate synthesis

**Comment by sjm41** [comment]
Funny you mention this - @rozaru and I were talking about exactly this issue (in another context) earlier this week.
We couldn't work out if there is a 'correct' standardisation, or what this should be, right Rossana? (though we didn't look too hard).
For the terms we were looking at, I think we looked at the relevant enzyme entries in EC and used their hyphenation.
In this case, I guess the authority would be ChEBI - that is, we use whatever hyphenation they use?

**Comment by ValWood** [comment]
Also some labels use
1-phosphatidyl-1D-myo-inositol 
and some use
phosphatidylinositol 

Rhea uses 1-phosphatidyl-1D-myo-inositol but in practice everyone uses "phosphatidylinositol"
Does GO need to follow Rhea for process the same way we do for enzymes?

**Comment by ValWood** [comment]
- [x] GO:1902635    1-phosphatidyl-1D-myo-inositol 4,5-bisphosphate biosynthetic process

Comments
Phosphatidylinositol-4,5-bisphosphate, PtdIns(4,5)P(2) common name.
migrated to synonyms

**Comment by ValWood** [comment]
Have used phosphatidylinositol 4-phosphate biosynthetic process here, 
will open a new ticket to resolve the inconsistencies

**Comment by ValWood** [comment]
I used
1-phosphatidyl-1D-myo-inositol 4-phosphate ChEBI ID | CHEBI:17526
 but that gives

if [ -s 'tmp_referenced_chebi_nums_not_7_3.txt' ]; then echo "ERROR: CHEBI IDs should be mapped to pH 7.3:" && cat tmp_referenced_chebi_nums_not_7_3.txt && exit 1; else exit 0; fi
ERROR: CHEBI IDs should be mapped to pH 7.3:
17526

I don't know how to fix that so for now I will remove the logical def.
@pgaudet

**Comment by ValWood** [comment]
1-phosphatidyl-1D-myo-inositol 4-phosphate(3−)
