### ISSUE TITLE
GO:0016104	 triterpenoid biosynthetic process 

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28895]
* **InterPro ID / label**

GO:0016104 | triterpenoid biosynthetic process | IEA with IPR018333

* **Example sequences with problematic annotation (ID + gene/protein name):**

* **Description of issue**

is a  triterpenoid derivative, rather than a triterpenoid.

you could  probably use  sterol biosynthetic process ?

**Comment by ValWood** [comment]
This highlights a potential ontology issue. The " isoprenoid family" classification is orthogonal to "end product" and it might complicate the curation of pathways.
For instance, in this case, lanosterol is_a triterpenoid, but is also past the commitment point of ergosterol biosynthesis (which isn't classed as isoprenoid biosynthesis because ergosterol is an isoprenoid-derivative rather than an iso[prenoid)

Flagging as an example.

**Comment by sarach06** [comment]
Hi Val,
Thank you very much. I have replaced GO:0016104 with GO:0006694, which will be available in the next InterPro release (102.).
Best wishes
Sara

**Comment by ValWood** [comment]
Hi Sara, 
see follow up comments, I changed my mind, I think this is an ontology issue, but I haven't figured out a fix yet.

**Comment by sarach06** [comment]
Ok, thanks, I will revert this then.
