### ISSUE TITLE
NTR: ER-plasma membrane adaptor  activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28899]
Please provide as much information as you can: 

* **Suggested term label:**

Endoplasmic Reticulum-plasma membrane adaptor

* **Definition (free text)**

* **Reference, in format PMID:#######**

PMID:23041194
PMID:39239853 

* **Gene product name and ID to be annotated to this term**

VAP family proteins like
https://www.pombase.org/gene/SPBC16G5.05c

* **Parent term(s)**
GO:0043495   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0043495/complete)
protein-membrane adaptor activity

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Any other information**

The ER transmembrane VAMP-associated proteins (VAPs) Scs2 and Scs22 are integral to ER-PM connections (D. Zhang et al., 2012). Cells lacking VAPs have many fewer physical links between the ER and the PM resulting in defects in cellular trafficking, lipid homeostasis and cell division site positioning (D. Zhang et al., 2012; D. Zhang & See, 2022). 
PMID:23041194

At the time I annotated these to
[GO:0061817](https://www.pombase.org/term/GO:0061817)	
[endoplasmic reticulum-plasma membrane tethering](https://www.pombase.org/term/GO:0061817)

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160214
+name: endoplasmic reticulum-plasma membrane adaptor activity
+namespace: molecular_function
+def: "The binding activity of a molecule that brings together a plasma membrane with an endoplasmic reticulum membrane, via membrane lipid binding, to establish membrane contact sites and mediate exchange and communication." [PMID:23041194, PMID:39239853]
+is_a: GO:0043495 ! protein-membrane adaptor activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28899" xsd:anyURI
+created_by: rynl
+creation_date: 2024-09-12T20:22:40Z
