### ISSUE TITLE
Cellular & (non-cellular) metabolic processes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28908]
Hello, 

I am creating a fresh ticket for the work started in https://github.com/geneontology/go-ontology/issues/17904

We have decided that all the chemical metabolic processes are cellular processes, so the following terms need to be fixed. 
- if there is a corresponding 'non-cellular' term, the term should be obsoleted and replaced by that 'non-cellular' process term.
- if there is no corresponding 'non-cellular' term, the term label, definition and logical definiton should be fixed to the non-cellular forms. 

Also, if there are asserted classes, these should generally be removed, unless they provide information that is not being inferred. Usually the ChEBI hierarchy should infer all parents that are needed. 

**Metabolic process**
- [x] GO:0044237  cellular metabolic process
- [x] GO:0044255  cellular lipid metabolic process
- [x] GO:0043446  cellular alkane metabolic process
- [x] GO:0043449  cellular alkene metabolic process
- [x] GO:0043452  cellular alkyne metabolic process
- [x] GO:0042180  cellular ketone metabolic process
- [x] GO:0006081  cellular aldehyde metabolic process
- [x] GO:0046950  cellular ketone body metabolic process
- [x] GO:0090345  cellular organohalogen metabolic process
- [x] GO:0090346  cellular organofluorine metabolic process
- [x] GO:0052701  cellular modified histidine metabolic process
- [x] GO:0006575  cellular modified amino acid metabolic process
- [x] GO:0046379  extracellular polysaccharide metabolic process
- [x] GO:0031323  regulation of cellular metabolic process
- [x] GO:0010565  regulation of cellular ketone metabolic process
- [x] GO:0006521  regulation of cellular amino acid metabolic process
- [x] GO:0090347  regulation of cellular organohalogen metabolic process
- [x] GO:0090348  regulation of cellular organofluorine metabolic process
- [x] GO:0031324  negative regulation of cellular metabolic process
- [x] GO:0031325  positive regulation of cellular metabolic process
- [x] GO:0045763  negative regulation of cellular amino acid metabolic process
- [x] GO:0010675  obsolete regulation of cellular carbohydrate metabolic process
- [x] GO:0090349  negative regulation of cellular organohalogen metabolic process
- [x] GO:0090350  negative regulation of cellular organofluorine metabolic process
- [x] GO:0043094 cellular metabolic compound salvage

----
**Biosynthetic process**
- [x] GO:0044249  cellular biosynthetic process
- [x] GO:0097384  cellular lipid biosynthetic process
- [x] GO:0052703  cellular modified histidine biosynthetic process
- [x] GO:0042398  cellular modified amino acid biosynthetic process
- [x] GO:0045226  extracellular polysaccharide biosynthetic process
- [x] GO:0031326  regulation of cellular biosynthetic process
- [x] GO:2000282  regulation of cellular amino acid biosynthetic process
- [x] GO:0031327  negative regulation of cellular biosynthetic process
- [x] GO:0031328  positive regulation of cellular biosynthetic process

----
 **Catabolic process**
- [x] GO:0044242  cellular lipid catabolic process
- [x] GO:0042402  cellular biogenic amine catabolic process
- [x] GO:0052702  cellular modified histidine catabolic process
- [x] GO:0042219  cellular modified amino acid catabolic process
- [x] GO:0071999  extracellular polysaccharide catabolic process
- [x] GO:0031329  regulation of cellular catabolic process
- [x] GO:1900419  regulation of cellular alcohol catabolic process
- [x] GO:0031330  negative regulation of cellular catabolic process
- [x] GO:0031331  positive regulation of cellular catabolic process
- [x] GO:1900420  negative regulation of cellular alcohol catabolic process
- [x] GO:1900421  positive regulation of cellular alcohol catabolic process
- [x] GO:0150094  amyloid-beta clearance by cellular catabolic process

Obsolete: precomposed: 

- [x] GO:0072000  extracellular polysaccharide catabolic process involved in ascospore release from ascus
- [x] GO:2000777  positive regulation of proteasomal ubiquitin-dependent protein catabolic process involved in cellular response to hypoxia

**Comment by cmungall** [comment]
Note that this would result in many terms that are clearly cellular moving out of the cellular hierarchy.

In 2019 I proposed a simple solution of placing metabolism under CP.
https://github.com/geneontology/go-ontology/issues/17904#issuecomment-549545694

The alternative is to get rid of CP altogether. Having a grouping class that is highly incomplete is confusing.

**Comment by pgaudet** [comment]
Sounds good. I dont think we want to get rid of cellular process - that's very central to @thomaspd 's BP reorganization.

I moved 'metabolic process' under 'cellular process', see https://github.com/geneontology/go-ontology/issues/28932

Thanks, Pascale

**Comment by edwong57** [comment]
GO:0044237 cellular metabolic process child terms have been moved
 GO:0044255 cellular lipid metabolic process child terms have been moved
GO:0044242 cellular lipid catabolic process child terms have been moved
GO:0097284 cellular lipid biosynthetic process child terms have been moved
