### ISSUE TITLE
Changes to retrotransposon silencing 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28924]
Change 'retrotransposon' to 'transposable element' 

Exchange by email with @hattrill  

> Hi Helen,
Colin and I were looking at this paper: https://europepmc.org/article/MED/26472911 in the context of this review : https://docs.google.com/spreadsheets/d/1b7l-q0PIggn2croU9GLQjYpj8MSmuc1IzX0TcA_Bedc/edit?gid=0#gid=0
and we were proposing to use ‘[piRNA-mediated retrotransposon silencing by heterochromatin formation](http://purl.obolibrary.org/obo/GO_0141006)’, but that talks about retrotransposons while the paper talks about transposons. Should we broaden  GO:0141006 to include both transposons and retrotransposons?
Thanks, Pascale

>Yes, I think that is a good idea. 
I have had in the back of my mind whether "transposable element" would be a better catch-all for a while - think that transposon is essentially the meaning. 
Perhaps we should change all the 'retrotransposon silencing' terms to 'transposon silencing' as the mechanisms, whether at the genome or in the cytosol, would be the same for a DNA transposon or retrotransposon regardless.
(Wrt the spreadsheet, I will have a look when I get back - flies do not have 'de nova' DNA methylation as lack Dnmt3 but do have a DNA methylase - FBgn0028707, Mt2. Not sure if I like those "regulation of" terms there, so will check those out.)
Helen

**Comment by pgaudet** [comment]
'transposable element silencing by heterochromatin formation' >> change parent from 'heterochromatin formation' to 'constitutive heterochromatin formation'

**Comment by hattrill** [comment]
> 'transposable element silencing by heterochromatin formation' >> change parent from 'heterochromatin formation' to 'constitutive heterochromatin formation'

I am not sure if this is always true. TEs are often found in areas of constitutive heterochromatin, but I am not so sure that the silencing of TA would always lead to constitutive heterochromatin formation. I think that would depend on where they integrate.

**Comment by pgaudet** [comment]
@colinlog

**Comment by colinlog** [comment]
Considering that whenever it has been studied, it always involves the H3K9me3 pathway, I would like to argue that is the unifying molecular pathway component. And, (for metazoa) H3K9me3 is *the* defining feature of constitutive hetrochromatin formation. So yes, even when integrated in euchromatin, they will recruit the H3K9me3 pathway if a DNA binding protein or a small interfereing RNA would recognize them and lead to heterochromatin formation. 

Furthermore, there is the (si and piRNA) mRNA destabilising pathway which does not necessarily involve heterochromatin formation. Hence, any 'exception' to the H3K9me3 constitutive pathway silencing is probably acted on via the mRNA destabilising pathway.

**Comment by hattrill** [comment]
That's good enough for me!
