### ISSUE TITLE
synonym request "breakdown"

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28921]
"breakdown" is currently an exact synonym of "catalytic process.

This makes the Europe PMC text miners flag every instance of "breakdown" as "catalytic process.

I'd like to edit this  synonym to be "breakdown of substance", make it related, or remove it altogether.

**Comment by deustp01** [comment]
This may be a tangent here, but breakdown should include spontaneous reactions that proceed without enzyme-mediated catalysis, like a number of physiologically important steps in eicosanoid metabolism, so will your edit fix the root problem?

**Comment by ValWood** [comment]
I guess that makes it even broader.
Is it a useful synonym? I can only see it being useful if it is in the context of a specific compound, so "x compound" would be useful, but  "catabolic process" is a high-level grouping term anyway.

(@pgaudet  not, don't worry I don't intend to do this for every problem synonym for text mining but this one has been bugging me for a couple of years when I have reviewed because it's a straightforward fox to remove a lot of obvious nonsense, and I don't think a curator would miss this label)

**Comment by pgaudet** [comment]
Would "breakdown of substance" (or breakdown of molecule) be enough to avoid it being picked up by text mining tools?

**Comment by ValWood** [comment]
I think so because they stopped doing partial string matches (or appeared to, but if not I will raise that issue again when I cheat with Europe PMC)

**Comment by pgaudet** [comment]
Sounds good, then go ahead and change it.

**Comment by pgaudet** [comment]
@ValWood I assume you meant 'catabolic process' , not catalytic process.
