### ISSUE TITLE
NTR: negative regulation of transcription initiation-coupled chromatin remodeling 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28928]
Please provide as much information as you can: 

* **Suggested term label:**
negative regulation of transcription initiation-coupled chromatin remodeling 

* **Definition (free text)**

* **Reference, in format PMID:#######**
PMID:33980486

* **Gene product name and ID to be annotated to this term**
KDM1A (UniProtKB:O60341)
L3MBTL3 (UniProtKB:Q96JM7)
SAMD1 (UniProtKB:Q6SPF0)

* **Parent term(s)**
'biological regulation' and 'negatively regulates' some 'transcription initiation-coupled chromatin remodeling'

**Comment by pgaudet** [comment]
Needed to annotate 3 genes in 
https://docs.google.com/spreadsheets/d/1b7l-q0PIggn2croU9GLQjYpj8MSmuc1IzX0TcA_Bedc/edit?gid=0#gid=0

**Comment by ValWood** [comment]
tagging myself. I'm not sure but this term might be relevant for 
https://github.com/geneontology/go-ontology/issues/22717

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160217
+name: negative regulation of transcription initiation-coupled chromatin remodeling
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of transcription initiation-coupled chromatin remodeling." [PMID:33980486]
+is_a: GO:0065007 ! biological regulation
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0045815 ! transcription initiation-coupled chromatin remodeling
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28928" xsd:anyURI
+created_by: rynl
+creation_date: 2024-09-18T00:47:50Z

**Comment by pgaudet** [comment]
Thanks @raymond91125 !
