### ISSUE TITLE
Obsoletion request: trehalose biosynthesis in response to heat stress (GO:0090441) 

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28943]
Please provide as much information as you can:

* **GO term ID and Label**
trehalose biosynthesis in response to heat stress (GO:0090441) 

* **Reason for deprecation** Put an x in the appropriate box: 
 - [x]  The reason for obsoletion is that this term is pre-composed and should be represented as a GO-CAM model.
 - [x]  The reason for obsoletion is that there is no evidence that this function/process/component exists.

* **"Replace by" term (ID and label)**
n/a

* **"Consider" term(s) (ID and label)**
GO:0005992 trehalose biosynthetic process (parent term)?

* **Are there annotations to this term?**
- How many EXP: 0

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**
No 

* **Is this term in a subset? (check the AmiGO page for that term)**
No

* **Any other information**
0 annotations (EXP or NON-EXP)

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by sjm41** [comment]
This is more complicated than I first realised.
There's a small hierarchy involved here:

```
trehalose metabolism in response to stress (200 direct annotations, 2 EXP)
           |__trehalose metabolism in response to cold stress (4 annotations)
           |__trehalose metabolism in response to heat stress (12 annotations, 2 EXP)
               |__trehalose biosynthesis in response to heat stress (0 annotations)
               |__trehalose catabolism in response to heat stress (0 annotations)
           |__trehalose metabolism in response to water deprivation (0 annotations)
```

**Comment by rozaru** [comment]
Probably, the GO terms above were made for yeast. According to SDG, in cerevisiae, "trehalose is a major reserve carbohydrate involved in response to thermal, osmotic, oxidative, and ethanol stresses, as well as the suppression of denatured protein aggregation." 
For insects, that make also trehalose, these terms are not applicable. Trehalose is their main circulating source of glucose and it's made all the time regardless of stress conditions.

**Comment by pgaudet** [comment]
We have terms under [response to nutrient levels](http://purl.obolibrary.org/obo/GO_0031667), for example: 
[carbohydrate utilization](http://purl.obolibrary.org/obo/GO_0009758)

<img width="740" alt="image" src="https://github.com/user-attachments/assets/1c0eeb01-97ec-4882-8c99-b851063c580b">

I dont think this exactly represents what is meant here, but it seems to match more closely than 'x in response to y'

**Comment by pgaudet** [comment]
There are annotations by 
PomBase @ValWood 
SGD @srengel 
CGD @jlewsmith 
EcoCyc @amandamackie 
Complex portal @sandraorchard 

See
https://github.com/geneontology/go-annotation/blob/master/reports/5568/GO_0070413-GO_0070414-GO_0070415-GO_0070416.tsv

It looks like this can merge into 'response to stress', see review 

https://www.sciencedirect.com/science/article/pii/S2214514123001381#:~:text=Trehalose%20upregulates%20Tre%2D%20and%20stress,stress%20responses%20and%20cell%20survival.

**Comment by amandamackie** [comment]
Fixed in EcoCyc. 
Replaced GO:0070415 trehalose metabolism in response to cold stress with GO:0070417 cellular response to cold

**Comment by pgaudet** [comment]
Hi @ValWood 

> but a merge would lose trehalose metabolism ?

This is a good point, but 'trehalose metabolism' doesn't seem to capture the effects of trehalose: see [Fig 2 here](https://www.sciencedirect.com/science/article/pii/S2214514123001381#:~:text=Trehalose%20upregulates%20Tre%2D%20and%20stress,stress%20responses%20and%20cell%20survival)

<img width="815" alt="image" src="https://github.com/user-attachments/assets/09fd8f88-0873-4311-b5af-ce4b6f7156e3">

Which mentions for example 
> 3.1.4. Trehalose upregulates Tre- and stress-associated genes under cold stress

So, this seems to be more 'trehalose-mediated signaling' rather than metabolism. 

Is this the same in pombe?

**Comment by ValWood** [comment]
OK,  no problem, I think it's the same

**Comment by raymond91125** [comment]
- [ ] GO:0070413 trehalose metabolism in response to stress
- [ ] GO:0070415 trehalose metabolism in response to cold stress
- [ ] GO:0070414 trehalose metabolism in response to heat stress
- [ ] GO:0070416 trehalose metabolism in response to water deprivation
- [ ] GO:0090441 trehalose biosynthesis in response to heat stress
- [ ] GO:0090442 trehalose catabolism in response to heat stress

replaced by GO:0005991 trehalose metabolic process
