### ISSUE TITLE
NTR: UDP-glucose biosynthetic process

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28951]
We already have:
GO:0006011 UDP-glucose metabolic process
and:
GO:0006258 UDP-glucose catabolic process
but not:
UDP-glucose biosynthetic process (= MetaCyc:PWY-7343)

Suggested new entry:

name: UDP-glucose biosynthetic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the formation of UDP-glucose, uridinediphosphoglucose, a substance composed of glucose in glycosidic linkage with uridine diphosphate." [GOC:sjm]
synonym: "UDP-glucose biosynthesis" EXACT []
synonym: "UDP-D-glucose biosynthesis" EXACT [MetaCyc:PWY-7343]
synonym: "UDP-D-glucose biosynthetic process" EXACT []
synonym: "uridine diphosphate glucose biosynthesis" EXACT []
synonym: "uridine diphosphate glucose biosynthetic process" EXACT []
xref: MetaCyc:PWY-7343
intersection_of: GO:0009058 ! biosynthetic process
intersection_of: has_primary_output CHEBI:58367 ! UDP-D-glucose(2-)

FYI, here's how the other two terms look:

id: GO:0006011
name: UDP-glucose metabolic process
namespace: biological_process
def: "The chemical reactions and pathways involving UDP-glucose, uridinediphosphoglucose, a substance composed of glucose in glycosidic linkage with uridine diphosphate." [GOC:ai]
synonym: "UDP-glucose metabolism" EXACT []
intersection_of: GO:0008152 ! metabolic process
intersection_of: has_primary_input_or_output CHEBI:58367 ! UDP-D-glucose(2-)

id: GO:0006258
name: UDP-glucose catabolic process
namespace: biological_process
alt_id: GO:0019691
def: "The chemical reactions and pathways resulting in the breakdown of UDP-glucose, uridinediphosphoglucose, a substance composed of glucose in glycosidic linkage with uridine diphosphate." [GOC:ai]
synonym: "UDP-glucose breakdown" EXACT []
synonym: "UDP-glucose catabolism" EXACT []
synonym: "UDP-glucose conversion" RELATED []
synonym: "UDP-glucose degradation" EXACT []
intersection_of: GO:0009056 ! catabolic process
intersection_of: has_primary_input CHEBI:58367 ! UDP-D-glucose(2-)

**Comment by pgaudet** [comment]
Hi Steven, 

Looking at the existing annotations of both metabolic process and catabolic process, this seems to represent a MF in a broader BP – or just a MF. For example: 

•	https://amigo.geneontology.org/amigo/reference/PMID:22132858 and https://amigo.geneontology.org/amigo/reference/PMID:8255669 >> seems to only have tested the activity and used ‘metabolism’ in the abstract

•	https://amigo.geneontology.org/amigo/reference/PMID:19286968 >> actually talks about sulfolipid biosynthesis

•	https://amigo.geneontology.org/amigo/reference/PMID:22654673 >> seems to talk about [galactose catabolic process via UDP-galactose](http://purl.obolibrary.org/obo/GO_0033499) (Leloir pathway) 


I would rather propose to obsolete the whole branch (and I wonder what other siblings look like), but if this is useful, go ahead and create it. Ideally there would be a clear start and end of the pathway.

**Comment by sjm41** [comment]
Hi Pascale

I didn't look at the annotations on the other two terms before....though I did notice that neither term has a good def xref.

GO:0006258 UDP-glucose catabolic process has only 1 annotation to rat Galt (by RGD) from PMID: 8255669 - I don't easily see the evidence for this from that paper, and there's no MetaCyc pathway for "UDP-glucose catabolism", so I agree this GO term can be obsoleted.

However, I see there are also these related terms:
GO:0010904    regulation of UDP-glucose catabolic process
GO:0010905    negative regulation of UDP-glucose catabolic process
- there is 1 IC annotation using GO:0010905 to human GSK3A from UniProt from PMID:11035810.
But again, I don't see the evidence for this in the paper....
So maybe these two GO terms can also be obsoleted.


But for the parent 'GO:0006011  UDP-glucose metabolic process', there are 60 EXP annotations, which for human are made to three different genes (GALT, UGP2 and UGGT1).
So it seems this term should be kept?

As for the NTR here, that at least has a direct MetaCyc xref (PWY-7343) where it's described as a 2-step pathway that, in  humans, involves PGM2 and UGP2. (The annotated fly pathway uses orthologs Pgm1 and UGP)

So, maybe we just need to end up with this:

```
UDP-glucose metabolic process (GO:0006011)
    |_UDP-glucose biosynthetic process (= MetaCyc:PWY-7343)
```

?

**Comment by pgaudet** [comment]
Generally this is OK for now and consistent with current practices, so you can create the term since you need it.  

However 'metabolic process' is a grouping term, we should be able to say whether the protein acts in the synthesis or the degradation of the compound. Also, I'd like to confirm with @cmungall , but if there is no evidence for 2 children, then we should not have the parent, in other words, if catabolic process does not exist, we shouldn't have metabolic process. Of course here that involves re-annotation, so it's a bigger project :(

**Comment by sjm41** [comment]
Right, curators would have to check if all the 60 EXP annotations direct to the parent 'metabolic process' here are really meant to be annotated to the new 'biosynthetic process term' requested here, or maybe they provide evidence for keeping the catabolic process' term after all...

So for now, I'll go ahead and make the new biosynthetic process term I need, as you suggest.

You said "Ideally there would be a clear start and end of the pathway."
So, should I additionally specify the input as 'CHEBI:4170 D-glucopyranose 6-phosphate' as per the MetaCyc:PWY-7343 pathway? Though I'd change that to the conjugate base (pH 7.3 form) "CHEBI:61548 D-glucopyranose 6-phosphate(2−)".  

Though that creates another problem, because RHEA says that the glucose 6-phosphate used in the first reaction in this pathway (= GO:0004614/RHEA:23536/EC:5.4.2.2) is CHEBI:58225 α-D-glucose 6-phosphate(2−)!!

Sugars are a pain....

Maybe I just specify the output for now?

**Comment by sjm41** [comment]
Actually, I have the same problem with the output....

MetaCyc:PWY-7343 says it's CHEBI:58885 UDP-α-D-glucose(2−)
But the two existing GO terms for metabolism/catabolism use CHEBI:58367 UDP-D-glucose(2-)

But in this case the relevant RHEA reaction (RHEA:19889) also uses CHEBI:58885 UDP-α-D-glucose(2−), so I think that's the correct output chemical to use here?

**Comment by pgaudet** [comment]
I think alpha is right (but if you could ask someone who knows more about sugars that would be good !)

**Comment by sjm41** [comment]
All occurrences of 'UDP-D-glucose' in RHEA are specifically 'UDP-α-D-glucose(2−)'.
Also, a search with CHEBI:58885 in RHEA finds 225 reactions, whereas a search with CHEBI:58367 in RHEA finds 0 reactions.
So I'll update the 2 existing terms to use CHEBI:58885 (as long as we keep them).

**Comment by sjm41** [comment]
+[Term]
+id: GO:0120530
+name: UDP-alpha-D-glucose biosynthetic process
+namespace: biological_process
+def: "The chemical reactions and pathways resulting in the formation of UDP-alpha-D-glucose, a substance composed of alpha-D-glucose in glycosidic linkage with uridine diphosphate." [MetaCyc:PWY-7343]
+synonym: "UDP-D-glucose biosynthesis" EXACT [MetaCyc:PWY-7343]
+synonym: "UDP-D-glucose biosynthetic process" EXACT []
+synonym: "UDP-glucose biosynthesis" EXACT []
+synonym: "uridine diphosphate glucose biosynthesis" EXACT []
+synonym: "uridine diphosphate glucose biosynthetic process" EXACT []
+xref: MetaCyc:PWY-7343
+intersection_of: GO:0009058 ! biosynthetic process
+intersection_of: has_primary_output CHEBI:58885 ! UDP-alpha-D-glucose(2-)
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28951" xsd:anyURI
+created_by: sjm
+creation_date: 2024-09-18T14:01:05Z
+
