### ISSUE TITLE
NTR: [RNA glycosylation]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#28963]
Hi GO,

Recent publications demonstrated the existence of RNA glycosylation. Last month, the first enzyme involved in RNA glycosylation was identified. RNA glycosylation is clearly a multi-step process, it is why I request a Biological process term.

For the moment, most studies have been on RNA-N-glycans, but a publication in bioRxiv suggest that O-glycosylation could be important as well. For this reason ,I think we should create a generic term for RNA glycosylation.

Thanks

Sylvain

Name: RNA glycosylation
Category: Biological Process
Definition: The posttranscriptional addition of a carbohydrate or carbohydrate derivative unit to residues in an RNA molecule.
child of GO:0009451 RNA modification
Synonym: glycoRNA biosynthesis

RX   PubMed=39173631; DOI=10.1016/j.cell.2024.07.044;
RA   Xie Y., Chai P., Till N.A., Hemberger H., Lebedenko C.G., Porat J.,
RA   Watkins C.P., Caldwell R.M., George B.M., Perr J., Bertozzi C.R.,
RA   Garcia B.A., Flynn R.A.;
RT   "The modified RNA base acp(3)U is an attachment site for N-glycans in
RT   glycoRNA.";
RL   Cell 0:0-0(2024).

RX   PubMed=34004145; DOI=10.1016/j.cell.2021.04.023;
RA   Flynn R.A., Pedram K., Malaker S.A., Batista P.J., Smith B.A.H.,
RA   Johnson A.G., George B.M., Majzoub K., Villalta P.W., Carette J.E.,
RA   Bertozzi C.R.;
RT   "Small RNAs are modified with N-glycans and displayed on the surface
RT   of living  cells.";
RL   Cell 184:3109-3124.e22(2021).

**Comment by pgaudet** [comment]
[Term]
id: GO:0141217
name: RNA glycosylation
namespace: biological_process
def: "The posttranscriptional addition of a carbohydrate or carbohydrate derivative unit to residues in an RNA molecule." [PMID:34004145, PMID:39173631]
synonym: "glycoRNA biosynthesis" EXACT []
is_a: GO:0006396 ! RNA processing
is_a: GO:0070085 ! glycosylation
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27105" xsd:anyURI
created_by: pg
creation_date: 2024-09-19T09:47:24Z
