### ISSUE TITLE
input/output chemicals on GO:0061624/R-HSA-70350

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28966]
id: GO:0061624
name: fructose catabolic process to hydroxyacetone phosphate and glyceraldehyde-3-phosphate
namespace: biological_process
def: "The chemical reactions and pathways resulting in the breakdown of fructose that results in the formation of dihydroxyacetone phosphate and glyceraldehyde-3-phosphate." [GOC:dph, ISBN:0201090910]
intersection_of: GO:0009056 ! catabolic process
intersection_of: has_part GO:0050354 ! triokinase activity
intersection_of: has_part GO:0061609 ! fructose-1-phosphate aldolase activity
intersection_of: has_primary_input CHEBI:28757 ! fructose
intersection_of: has_primary_output CHEBI:58027 ! glyceraldehyde 3-phosphate(2-)
intersection_of: starts_with GO:0004454 ! ketohexokinase activity
created_by: dph
creation_date: 2014-04-29T12:58:28Z

Reactome xrefs "Fructose catabolism (R-HSA-70350)" to this GO term, which is correct.

Few questions here:

1. GO:0061624 says "has_primary_input CHEBI:28757 ! fructose" whereas R-HSA-70350 has the more specific ChEBI:28645 β-D-fructofuranose.
The first reaction in this pathway is GO:0004454/RHEA:18145, and that RHEA also uses ChEBI:28645.
So, should the "has_primary_input" on GO:0061624 be changed to ChEBI:28645?

2. GO:0061624 says "as_primary_output CHEBI:58027 ! glyceraldehyde 3-phosphate(2-)" whereas R-HSA-70350 has CHEBI:59776 D-glyceraldehyde 3-phosphate(2−).
The last reaction in this pathway is GO:0050354/RHEA:13941, and that RHEA also uses CHEBI:59776.
So, should the  "has_primary_output" on GO:0061624 be changed to CHEBI:59776?

3. Should the "has_primary_output" be moved out of the LD and instead be asserted (I don't think it's needed for the LD to be "necessary and sufficient") or are we happy for it to stay in the LD?

I imagine there are lots more examples like this one, where the input/ouput in the GO LD doesn't match those in the Reactome pathway and/or the chemicals in the corresponding first/last RHEA reactions.
We might be able to automate a check/report on such cases once we integrate the Reactome xrefs into the GO as per #27081

@ukemi @deustp01 
@pgaudet @rozaru

**Comment by pgaudet** [comment]
Hi @sjm41 

I would say yes to all 3 questions above: if the chemical is the one used by RHEA, then it's the one you should use. 

Thanks, 
Pascale

**Comment by sjm41** [comment]
Thanks @pgaudet.
I will go ahead and make the changes for points 1 and 2, unless I hear objections from the others I tagged.

For point 3, do we need a final discussion/decision about what belongs in the LD versus being asserted? I know there's the argument that the LD should only contain the minimal info to uniquely distinguish the term.  But I can also see the advantage/logic of listing the 'has_primary_input' and 'has_primary_output' in the same way, rather than one being asserted and one being inferred.
Apologies if the final decision/consensus on this has been made and I missed it.

**Comment by pgaudet** [comment]
Hi Steven, 

This is on the agenda for the next Ontology call Oct 7th; can you make it? 

Thanks, Pascale

**Comment by sjm41** [comment]
I discussed this ticket with @ukemi and @deustp01 yesterday.

The emerging consensus from that discussion was that the inputs/outputs here (and on other metabolic BP terms) should use the most generic ph7.3 form that fits with the definition. This approach would fit with the general GO policy of using ph7.3 chemicals, while keeping the BPs broad enough to accommodate slight variations in chemicals metabolized in a particular species/context - this is particularly important for pathways involving chemicals that exist as more specific variants (e.g. D vs L stereoisomer, alpha vs beta enantiomer), any one of which may be stated as the metabolite in a paper or source database.

So, focussing on the input/output chemicals on GO:0061624 (fructose catabolic process to hydroxyacetone phosphate and glyceraldehyde-3-phosphate), and assuming that ChEBI entries with 'UniProt' synonyms are the pH7.3 forms:

---

Here's the is_a hierarchy in ChEBI for the fructose entries mentioned above, with notes:

```
|_CHEBI:28757 fructose  <- currently used as input on GO:0061624
    |_CHEBI:15824 D-fructose
        |_CHEBI:37721 D-fructofuranose  <- pH7.3 form
            |_CHEBI:28645 β-D-fructofuranose  <- used in R-HSA-70350 pathway / pH7.3 form
```

So, I believe the proposal here would be to change the GO:0061624 'has_primary_input' to CHEBI:37721 D-fructofuranose.

---

And here's the is_a hierarchy in ChEBI for the glyceraldehyde-3-phosphate entries mentioned above, also with notes:

```
|_CHEBI:58945 organophosphate oxoanion
    |_CHEBI:58027 glyceraldehyde 3-phosphate(2−)  <- currently used as output on GO:0061624 / pH7.3 form
    |_CHEBI:59776 D-glyceraldehyde 3-phosphate(2−)  <- used in R-HSA-70350 pathway / pH7.3 form
```

So, here the usage of CHEBI:58027 glyceraldehyde 3-phosphate(2−) for GO:0061624 'has_primary_output' looks correct since it's the the most generic ph7.3 form that fits with the definition.
However, note that  the ChEBI hierarchy doesn't assert that '**D**-glyceraldehyde 3-phosphate(2−)' is_a 'glyceraldehyde 3-phosphate(2−)'.  (This may relate to @cmungall's ongoing discussions with ChEBI?)


Please correct me if you disagree, @ukemi @deustp01

**Comment by sjm41** [comment]
I see the MetaCyc pathway that includes "GO:0061624 fructose catabolic process to hydroxyacetone phosphate and glyceraldehyde-3-phosphate" also specifies ChEBI:28645 β-D-fructofuranose and CHEBI:59776 D-glyceraldehyde 3-phosphate(2−), thus agreeing with Reactome and the participants on the relevant RHEA terms:

https://biocyc.org/pathway?orgid=META&id=PWY-8404

Based on this and more recent discussions, I'll go ahead and change those two input/output chemicals in the LD of GO:0061624 to match.
