### ISSUE TITLE
'glycogen biosynthetic process' parents

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#28968]
id: GO:0005978
name: glycogen biosynthetic process
namespace: biological_process
def: "The chemical reactions and pathways resulting in the formation of glycogen, a polydisperse, highly branched glucan composed of chains of D-glucose residues." [ISBN:0198506732]
synonym: "glycogen anabolism" EXACT []
synonym: "glycogen biosynthesis" EXACT []
synonym: "glycogen formation" EXACT []
synonym: "glycogen synthesis" EXACT []
xref: MetaCyc:GLYCOGENSYNTH-PWY {source="skos:narrowMatch"}
xref: MetaCyc:PWY-5067 {source="skos:narrowMatch"}
xref: MetaCyc:PWY-7900 {source="skos:narrowMatch"}
is_a: GO:0005977 ! glycogen metabolic process
is_a: GO:0009250 ! glucan biosynthetic process
intersection_of: GO:0009058 ! biosynthetic process
intersection_of: has_primary_output CHEBI:28087 ! glycogen
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/27107" xsd:anyURI
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28527" xsd:anyURI

@pgaudet
the two asserted is_a parents here could/should be removed, right? They are covered by the LD.

**Comment by pgaudet** [comment]
That seems correct. To test this, you can just remove the asserted classes, synchronize the reasoner, and check if they come back as inferred superclasses. 

In any case, we should not make these assertions for chemicals. If the proper groupings are missing, we need to check with ChEBI. 

OK? 

Thanks, Pascale

**Comment by sjm41** [comment]
Yep, I did the test you suggested and it looks good. So I'll go ahead and action this.

**Comment by sjm41** [comment]
Looks like the same goes for the asserted is_a on this term, so I'll remove that too:

id: GO:0061621
name: canonical glycolysis
namespace: biological_process
def: "The glycolytic process that begins with the conversion of glucose to glucose-6-phosphate by glucokinase activity. Glycolytic processes are the chemical reactions and pathways resulting in the breakdown of a carbohydrate into pyruvate, with the concomitant production of a small amount of ATP." [GOC:dph, ISBN:0201090910, ISBN:0879010479]
xref: MetaCyc:ANAGLYCOLYSIS-PWY
xref: Wikipedia:Glycolysis
is_a: GO:0061620 ! glycolytic process through glucose-6-phosphate
intersection_of: GO:0061620 ! glycolytic process through glucose-6-phosphate
intersection_of: has_part GO:0004365 ! glyceraldehyde-3-phosphate dehydrogenase (NAD+) (phosphorylating) activity
intersection_of: has_primary_input CHEBI:4167 ! D-glucopyranose
intersection_of: has_primary_input CHEBI:57540 ! NAD(1-)
intersection_of: has_primary_output CHEBI:57945 ! NADH(2-)
intersection_of: starts_with GO:0004340 ! glucokinase activity
created_by: dph
creation_date: 2014-04-14T09:21:54Z
