### ISSUE TITLE
calcium-activated cation channel activity (GO:0005227)

### ISSUE THREAD

**Issue by Argoudpuy** [geneontology/go-ontology#28979]
* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request a definition update**
calcium-activated cation channel activity (GO:0005227)

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
Enables the transmembrane transfer of an inorganic cation by a channel that opens when a specific calcium has been bound by the channel complex or one of its constituent parts. 

* **Reference(s)**
PMID:34381056

* **Additional information**

**Comment by pgaudet** [comment]
Also fixed GO:0015269 calcium-activated potassium channel activity and GO:0070089 chloride-activated potassium channel activity

Thanks, Pascale
