### ISSUE TITLE
go.obo and go-basic.obo have different data-version in snapshot

### ISSUE THREAD

**Issue by kltm** [geneontology/go-ontology#28988]
@balhoff This is more a question than anything else, but we noticed that in the last `snapshot` that we had

go-basic.obo:
```
data-version: releases/2024-09-18
```

go.obo
```
data-version: releases/2024-09-22
```

This `snapshot` run was a little odd, with a lot of restarts, so I'm not too surprised at the date difference. I would, however, expect them both to be at least from Sunday the 22nd, when the run started. I was curious if there were any lags built in the system that would easily explain this? (E.g. reaching out to the previous snapshot or release at some point.)

Tagging @suzialeksander , who noticed this.

**Comment by balhoff** [comment]
@kltm I can't explain this. I had two recent PRs changing owltools to robot, but it looks like I used all the same make variables related to dates:

https://github.com/geneontology/go-ontology/pull/28902/files
https://github.com/geneontology/go-ontology/pull/28893/files

**Comment by kltm** [comment]
@balhoff All good. We'll do a clean run soon and see if there's a difference. It might be down to some kind of workspace sanitation.
