### ISSUE TITLE
NTR: negative regulation of acetyl-CoA biosynthetic process from pyruvate

### ISSUE THREAD

**Issue by Antonialock** [geneontology/go-ontology#28993]
Please provide as much information as you can: 

* **Suggested term label:**

negative regulation of acetyl-CoA biosynthetic process from pyruvate

* **Definition (free text)**

standard

* **Reference, in format PMID:#######**
26942675
36849569
37754565

* **Gene product name and ID to be annotated to this term**

PGK1 in aspergillus and human
A0A7G5KET3
P00558

possibly also human MAPK1/ERK2

* **Parent term(s)**
GO:0010510 + a neg reg term

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**
In hypoxic conditions (human) PGK is phosphorylated at Ser-203, this leads to cis-trans isomerazation by PIN1 and exposure of a mitochondrial targeting sequence. It can also interact with a regulatory RNA that promotes binding to the TOM complex for mitochondrial import. In the mitochondrion it acts as a protein kinase that activates pyruvate dehydrogenase kinase PDK1 to inhibit pyruvate dehydrogenase complex activity and suppress the formation of acetyl-coenzyme A from pyruvate. 

In aspergillus, negative regulation of the biosynthesis of acetyl-CoA from pyruvate attenuates aflatoxin production (acetyl-CoA is an input for aflatoxin production).

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160218
+name: negative regulation of acetyl-CoA biosynthetic process from pyruvate
+namespace: biological_process
+def: "Any process that stops, prevents or reduces the frequency, rate or extent of the chemical reactions and pathways resulting in the formation of acetyl-CoA from pyruvate." [PMID:26942675, PMID:36849569, PMID:37754565]
+intersection_of: GO:0065007 ! biological regulation
+intersection_of: negatively_regulates GO:0006086 ! acetyl-CoA biosynthetic process from pyruvate
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28993" xsd:anyURI
+created_by: rynl
+creation_date: 2024-09-27T05:19:27Z
