### ISSUE TITLE
NTR: histone H3K4 deacetylase activity, NAD-dependent

### ISSUE THREAD

**Issue by PCarme** [geneontology/go-ontology#28994]
Please provide as much information as you can: 

* **Suggested term label:**
histone H3K4 deacetylase activity, NAD-dependent

* **Definition (free text)**
Catalysis of the reaction: histone H3 N6-acetyl-L-lysine (position 14) + NAD+ + H2O = histone H3 L-lysine (position 14) + 2''-O-acetyl-ADP-D-ribose + nicotinamide. This reaction transfers an acetyl group attached to a lysine residue in H3K4 to NAD, producing nicotinamide.

* **Reference, in format PMID:#######**
(REQUIRED)
PMID:23771057
PMID:20299449
* **Gene product name and ID to be annotated to this term**
SPBC16D10.07c sir2

* **Parent term(s)**
histone deacetylase activity, NAD-dependent (GO:0017136)
histone H3K deacetylase activity (GO:0141050)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
+[Term]
+id: GO:0141222
+name: histone H3K4 deacetylase activity, NAD-dependent
+namespace: molecular_function
+def: "Catalysis of the reaction: histone H3 N6-acetyl-L-lysine (position 14) + NAD+ + H2O = histone H3 L-lysine (position 14) + 2''-O-acetyl-ADP-D-ribose + nicotinamide. This reaction transfers an acetyl group attached to a lysine residue in H3K4 to NAD, producing nicotinamide." [PMID:20299449, PMID:23771057]
+xref: EC:2.3.1.286 {source="skos:broadMatch"}
+is_a: GO:0017136 ! histone deacetylase activity, NAD-dependent
+is_a: GO:0141050 ! histone H3K deacetylase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/28994" xsd:anyURI
+created_by: pg
+creation_date: 2024-09-26T12:37:07Z
