### ISSUE TITLE
Obsoletion request: GO:0052201 response to symbiont defenses

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#28998]
This term GO:0052201 response to symbiont defenses
has no annotations; I think it was created for 'symmetry' with [response to host defenses](http://purl.obolibrary.org/obo/GO_0052200); I propose we obsolete it. 

@mgiglio99 @genegodbold @ValWood what do you think ? 

Thanks, Pascale

**Comment by genegodbold** [comment]
I agree @pgaudet, the symbiont does have defenses, but the term would probably be invoked just with respect to a parasite/symbiont OF the symbiont (if that makes sense). All parasitic symbionts will have counters to the innate defenses of the host (like encoding superoxide dismutases to detoxify reactive oxygen species).
