### ISSUE TITLE
Missing parent: GO:0106340	tRNA (cytidine(32)/guanosine(34)-2'-O)-methyltransferase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28992]
* **GO term ID and label for which you request a new superclass**

GO:0106340 | tRNA (cytidine(32)/guanosine(34)-2'-O)-methyltransferase activity

* **New superclass (parent) suggested**

GO:0016427 | tRNA (cytidine) methyltransferase activity

**Comment by pgaudet** [comment]
Also added 
+is_a: GO:0016423 ! tRNA (guanine) methyltransferase activity


And for [tRNA (cytidine(32)/uridine(32)-2'-O)-methyltransferase activity](http://purl.obolibrary.org/obo/GO_0160206)
Added two parents: 
+is_a: GO:0016300 ! tRNA (uridine) methyltransferase activity
+is_a: GO:0016427 ! tRNA (cytidine) methyltransferase activity

Thanks, Pascale
