### ISSUE TITLE
 GO:0016814 | hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in cyclic amidine should tRNA-specific adenosine-34 deaminase activity be a descendant?

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#28991]
* **ARBA rule (ID and label):**

GO:0016814 | hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in cyclic amidines | IEA with ARBA00026853 | GO_REF:0000117 | 16

this is applied to

tRNA specific adenosine-34 deaminase subunit

but adenosine does not appear to be a cyclic amidines, I will filter this one fromPomBase but rule needs fixing

* **Sequences with problematic annotation (ID + gene/protein name):**

tad2 https://www.pombase.org/gene/SPBC16D10.10

* **Description of issue**

see above

**Comment by ValWood** [comment]
This looked like an ARBA issue, but it could be a GO parentage issue?

**Comment by ValWood** [comment]
Hi @sjm41 

ARBA predicts that  tRNA specific adenosine-34 deaminase subunit

is a GO:0016814 | hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in cyclic amidines 

Originally I was questioning the mapping, but it could be the GO hierarchy that is incorrect. What do you think?

Thanks for. any input,
v

**Comment by pgaudet** [comment]
@ValWood 

What is your question? tRNA-specific adenosine-34 deaminase activity is a grand child of GO:0016814 | hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in cyclic amidine

<img width="538" alt="image" src="https://github.com/user-attachments/assets/cfd51efb-67a4-42cf-9888-38918b09e496">

**Comment by ValWood** [comment]
Yep

GO:0008251  tRNA-specific adenosine deaminase activity
2024-09-02 | Added | RELATION | is a GO:0019239 (deaminase activity)
fixed it!

Sorry I didn't recheck from opening the ticket.
