### ISSUE TITLE
Taxon constraint for GO:0000196 cell integrity MAPK cascade

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29009]
From @kimrutherford  in https://github.com/pombase/pombase-chado/issues/1229

I noticed that parent term GO:0000196 has weird taxon constraints. Does it make sense to have two "Only in Taxon" constraints like this?

We create a pombe-only OBO file for loading into Canto using OWLTools. When I remove that taxon constraint from the input file (go-plus.owl), and re-run OWLTools the missing term (GO:1903139) reappears. So the constraint does look like at least part of the problem.

Parent term: https://www.ebi.ac.uk/QuickGO/term/GO:0000196

![image](https://github.com/user-attachments/assets/f06d7a4f-2e08-4c7b-8f56-7a5a4b4b4b94)

**Comment by ValWood** [comment]
Term should not have 

It looks like the "Viridiplantae or Bacteria or Euglenozoa" constraint was added in this PR:

https://github.com/geneontology/go-ontology/pull/26802

**Comment by pgaudet** [comment]
@balhoff This seems like a logical problem ? only in bacteria should be disjoint from only in eukaryotes, shouldn't it ?

**Comment by balhoff** [comment]
Yes, Bacteria is disjoint from Eukaryota, but it is not disjoint from the union of "Plants OR Bacteria OR Euglena". So in this case neither term is more specific than the other. However we do have a term [Viridiplantae or Euglenozoa](http://purl.obolibrary.org/obo/NCBITaxon_Union_0000008). This should be disjoint from Bacteria. I think it takes a bit more logical expressivity than we have available to infer that this is the actual taxon constraint (I will try to look into that). In the meantime it seems like this constraint could be added in place of the other union.

**Comment by balhoff** [comment]
@ValWood would you like me to do something here? Do you want to just remove that taxon constraint? I don't know anything was wrong in this case.

**Comment by ValWood** [comment]
Hi @balhoff I don't know what the precise action is to fix. I'll assign to @pgaudet instead.

**Comment by ValWood** [comment]
Maybe I just need to remove the incorrect taxon constrain  but it seems as though something is required to prevent this combination which is logically onconsistent.

**Comment by pgaudet** [comment]
Hi @balhoff 

The TC is not in the manually edited file (only_in_taxon). As @ValWood points out, it looks like the "Viridiplantae or Bacteria or Euglenozoa" constraint was added in this PR:

https://github.com/geneontology/go-ontology/pull/26802

I dont know how or why this got added. I dont see any parents that could justify these. I see in QuickGO that GO:0000196 used to have the relation: part of GO:0071554 (cell wall organization or biogenesis), but I dont see any TCs on that one. 

In Protégé it looks like it's asserted, not inferred, but I dont know how I can remove it. 

Pascale

**Comment by balhoff** [comment]
@pgaudet here is the PR that added the taxon constraint: https://github.com/geneontology/go-ontology/pull/26791

**Comment by balhoff** [comment]
@ValWood it is correct for these taxon constraints to remove the term from Canto, since S. pombe is not in "Viridiplantae or Bacteria or Euglenozoa". If that constraint is wrong then you can remove it or replace with something else. Want me to delete it?

**Comment by ValWood** [comment]
Hi @balhoff 

 Yes, this taxon contraint is incorrect

GO:0000196 | cell integrity MAPK cascade | Only in Taxon | 2, 33090, 33682 | Viridiplantae or Bacteria or Euglenozoa

but I think it's automated isn't it? (see above)

If it on;y needs removing I can do that, I thought it was something more complicated...

**Comment by balhoff** [comment]
Great, I will merge #29101.

**Comment by ValWood** [comment]
fixed at our end!
