### ISSUE TITLE
Obsoletion request: cellular metabolic process and regulation of cellular metabolic process terms

### ISSUE THREAD

**Issue by edwong57** [geneontology/go-ontology#29021]
Please provide as much information as you can:

* **GO term ID and Label**
- GO:0044237 cellular metabolic process
- GO:0046950 cellular ketone body metabolic process
- GO:0046379  extracellular polysaccharide metabolic process
- GO:0031323  regulation of cellular metabolic process
- GO:0006521  regulation of cellular amino acid metabolic process
- GO:0031324  neg regulation of cellular metabolic process
- GO:0031325  pos regulation of cellular metabolic process

The reason for obsoletion is that these terms are redundant terms to:

- GO:0008152  metabolic proces
- GO:1902224  ketone body metabolic process
- GO:0005976  polysaccharide metabolic process
- GO:0019222  regulation of metabolic process
- GO:0006521  regulation of amino acid metabolic process
- GO:0009892  neg reg of metabolic process
- GO:0009893  pos reg of metabolic process

Related to clean up of cellular process terms - https://github.com/geneontology/go-ontology/issues/28908

* **"Replace by" term (ID and label)**
Cellular term annotations should be moved to the corresponding non-cellular terms

* **Are there annotations to this term?**
- GO:0044237 cellular metabolic process: 41 EXP
- GO:0046950 cellular ketone body metabolic process: 4 EXP
- GO:0046379  extracellular polysaccharide metabolic process: 46 EXP
- GO:0031323  regulation of cellular metabolic process: 6 EXP
- GO:0006521  regulation of cellular amino acid metabolic process: 8 EXP
- GO:0031324  neg regulation of cellular metabolic process: 0 EXP
- GO:0031325  pos regulation of cellular metabolic process: 4 EXP

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

7 mappings/cross refs to review

* **Is this term in a subset? (check the AmiGO page for that term)**
- GO:0044237 cellular metabolic process - in do_not_annotate
- GO:0046950 cellular ketone body metabolic process - in goslim_pir
- GO:0046379  extracellular polysaccharide metabolic process - not in any subset
- GO:0031323  regulation of cellular metabolic process - in do_not_annotate
- GO:0006521  regulation of cellular amino acid metabolic process
- GO:0031324  neg regulation of cellular metabolic process: gocheck_do_not_annotate
- GO:0031325  pos regulation of cellular metabolic process: gocheck_do_not_annotate

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [x] check term usage in the ontology 
- [x] check internal mappings: RHEA, EC, MetaCyc
- [x] check subset usage
- [x] check taxon constraints 

***Check annotations***
- [x] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [x] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [x] find external mappings (via IEAS), include in obsoletion notice  
- [x] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [x] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [x] announce to GO friends (go-friends@mailman.stanford.edu)
- [x] paste the text in the ontology ticket

**Comment by deustp01** [comment]
Four Reactome pathways fixed as suggested (but is this this suggested term correct? GO:0006521 regulation of amino acid metabolic process)

**Comment by edwong57** [comment]
Which Reactome pathways are they? What were the annotations? 

I think the idea is that since metabolic process has been moved under 'cellular process' that 'regulation of amino acid metabolic process' has 'cellular process' as a parent and there's no need to have a separate 'regulation of cellular amino acid metabolic process' term. So, parentage-wise, I don't think that those should change going from 'regulation of cellular amino acid metabolic process' to 'regulation of amino acid metabolic process'

**Comment by deustp01** [comment]
> Which Reactome pathways are they? What were the annotations?

The GO BP terms associated with Reactome pathways R-HSA-1428517 "Aerobic respiration and respiratory electron transport", R-HSA-163675 "ChREBP activates metabolic gene expression", R-HSA-74182 "Ketone body metabolism", and R-HSA-350562 "Regulation of ornithine decarboxylase (ODC)", each needed updating to replace a cellular~ term with a plain metabolism one; no arguments from here about the metabolism versus cellular-metabolism distinction. The failure of the usage survey done as part of a GO obsoletion to pick up these Reactome instances is a known problem due to how we capture the BP terms and export that information in a GAF, that we are slowly working on.

**Comment by pgaudet** [comment]
Hi @deustp01 

The TAS and NAS are now included in the reports. I thought this would result in Reactome's annotations being included in reports. Can you give a specific example of an annotation you expect to be reported that was missing? Looks like we may need to fix something else. 

Thanks, Pascale

**Comment by deustp01** [comment]
> Can you give a specific example of an annotation

The three BP-to-pathway annotations in my last comment.

**Comment by srengel** [comment]
looks like these changes have already been made, but the email said we have until Oct14th.

**Comment by edwong57** [comment]
The terms listed in this ticket are still showing up in protege and the latest go-edit.obo, so it doesn't look like these have been obsoleted. I didn't tag SGD in the annotation review since the annotations should be replaced automatically with Noctua. I can assign someone, but thought it was unnecessary since it was going to be done computationally.

I did obsolete a few precomposed terms ([20919](https://github.com/geneontology/go-ontology/issues/29019) and [20920](https://github.com/geneontology/go-ontology/issues/29020)) that only had PomBase annotations after those got cleaned up.
