### ISSUE TITLE
GO:0101020 estrogen 16-alpha-hydroxylase activity with no cross reference

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-ontology#29025]
See https://github.com/geneontology/go-ontology/issues/28340.

GO:0101020 estrogen 16-alpha-hydroxylase activity lacks a published xref. 

"The four major naturally occurring estrogens in women are estrone (E1), estradiol (E2), estriol (E3), and estetrol (E4" (https://en.wikipedia.org/wiki/Estrogen). Thus, this activity may apply to 4 or more reactions, one for each estrogen substrate.

The super class activity is probably EC:1.14.14.1 unspecific monooxygenase , RHEA:17149, that is GO:0070330 aromatase activity, based on the the shared UniProt annotation of all genes annotated (EXP) with GO:0101020. RHEA:17149 has many specific reactions listed but those may not be exhaustive.

Some possible relevant RHEAs
RHEA:47204 estrone + O2 + reduced [NADPH--hemoprotein reductase] = 16alpha-hydroxyestrone + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]
RHEA:47260 O2 + progesterone + reduced [NADPH--hemoprotein reductase] = 16alpha-hydroxyprogesterone + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]
RHEA:47332 17beta-estradiol + O2 + reduced [NADPH--hemoprotein reductase] = 16alpha,17beta-estriol + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]
RHEA:53216 17alpha-hydroxyprogesterone + O2 + reduced [NADPH--hemoprotein reductase] = 16alpha,17alpha-dihydroxyprogesterone + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]

**Comment by raymond91125** [comment]
GO:0070330 aromatase activity is not XREF'ed to EC:1.14.14.1 anymore (https://github.com/geneontology/go-ontology/issues/28295).

**Comment by pgaudet** [comment]
hi @raymond91125 

Please update definition and parent to match the RHEA reaction. 

Thanks, Pascale

**Comment by pgaudet** [comment]
Based on the ChEBI hierarchy, progesterone is not an estrogen, so I removed the mappings to 
RHEA:47260 O2 + progesterone + reduced [NADPH--hemoprotein reductase] = 16alpha-hydroxyprogesterone + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]
and 
RHEA:53216 17alpha-hydroxyprogesterone + O2 + reduced [NADPH--hemoprotein reductase] = 16alpha,17alpha-dihydroxyprogesterone + H(+) + H2O + oxidized [NADPH--hemoprotein reductase]

**Comment by pgaudet** [comment]
Fixed definition to match RHEA
Catalysis of the reaction: estrogen + reduced [NADPH--hemoprotein reductase] + O2 = 16-alpha-hydroxyestrogen + oxidized [NADPH--hemoprotein reductase] + H2O.

ie reduced [NADPH--hemoprotein reductase] rather than the generic AH2 acceptor.

**Comment by pgaudet** [comment]
Added parent ''oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen' (since donor is reduced [NADPH--hemoprotein reductase] )
