### ISSUE TITLE
GO:0031073 cholesterol 26-hydroxylase activity with no cross reference

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-ontology#29029]
GO:0031073 cholesterol 26-hydroxylase activity lacks a EC/RHEA cross reference.

The definition xref is PMID:950499 On the heterogeneity of the mitochondrial C27-steroid 26-hydroxylase system. This activity probably corresponds to RHEA:43836 cholesterol + H(+) + NADPH + O2 = 26-hydroxycholesterol + H2O + NADP(+).

![image](https://github.com/user-attachments/assets/d3488b39-142c-41d3-8dd0-b4308767bcbb)

However, RHEA:43836 is a general XREF for GO:0008395 steroid hydroxylase activity, which seems too broad. Move RHEA:43836 from GO:0008395 to GO:0031073.

**Comment by pgaudet** [comment]
Please update the definition ans prent to be consistent with RHEA.

**Comment by raymond91125** [comment]
> Please update the definition ans prent to be consistent with RHEA.

Which parent should it be informed by RHEA:43836?

**Comment by pgaudet** [comment]
'oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, another compound as one donor, and incorporation of one atom of oxygen'
