### ISSUE TITLE
GO:0008396 oxysterol 7-alpha-hydroxylase activity with no cross reference

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-ontology#29041]
GO:0008396 oxysterol 7-alpha-hydroxylase activity lacks EC/RHEA cross references.
PMID:10882791 the reference cited for the definition does not seem to have anything to do with oxysterol. It must be a typo. A good reference
PMID:9295351 Identification and Characterization of a Mouse Oxysterol 7a-Hydroxylase cDNA*
PMID:10748047 Expression cloning of an oxysterol 7alpha-hydroxylase selective for 24-hydroxycholesterol 
PMID:27687912 Oxysterols: From cholesterol metabolites to key mediators. Mentions human/mouse CPY7B1 and CYP39A1.

**Comment by raymond91125** [comment]
https://en.wikipedia.org/wiki/Oxysterol mentions examples
Oxycholesterol (5,6-epoxycholesterol)
24S-Hydroxycholesterol
27-Hydroxycholesterol

GO:0008396 EXP annotations include 2 genes, CYP39A1 and CYP7B1

**Comment by raymond91125** [comment]
From the names, GO:0008396 oxysterol 7-alpha-hydroxylase activity should be a subclass of GO:0008387 steroid 7-alpha-hydroxylase activity, which has one EXP annotation of CYP39A1 and the definition has no publication reference.

**Comment by raymond91125** [comment]
Useful resource for P450s.
https://www.guidetopharmacology.org/GRAC/FamilyDisplayForward?familyId=242

**Comment by raymond91125** [comment]
CYP2A12 (the narrow synonym for GO:0008387 steroid 7-alpha-hydroxylase activity) is a bile acid 7-alpha hydroxylase. Per PMID:31645370 CYP2A12 converts deoxycholic acid (DCA) -> cholic acid and lithocholic acid (LCA) -> cheno-deoxycholic acid (CDCA).

**Comment by pgaudet** [comment]
> PMID:10882791 the reference cited for the definition does not seem to have anything to do with oxysterol. It must be a typo.

This reference was still present; removed.

**Comment by pgaudet** [comment]
Obsolete [steroid 22-alpha hydroxylase activity](http://purl.obolibrary.org/obo/GO_0010012) and replace by [steroid 22S-hydroxylase activity](http://purl.obolibrary.org/obo/GO_0160191); represent the same activity.

**Comment by pgaudet** [comment]
- [x] [steroid 17-alpha-monooxygenase activity](http://purl.obolibrary.org/obo/GO_0004508): change parent from is_a: GO:0016705 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen to 
+is_a: GO:0016712 ! oxidoreductase activity, acting on paired donors, with incorporation or reduction of molecular oxygen, reduced flavin or flavoprotein as one donor, and incorporation of one atom of oxygen

**Comment by pgaudet** [comment]
Done.
