### ISSUE TITLE
mRNA and ncRNA acetylation

### ISSUE THREAD

**Issue by AndreaAuchincloss** [geneontology/go-ontology#29051]
Hello,

I'd like to ask for 3 new GO terms please, for mRNA acetylation, non-coding (nc)RNA acetylation and ncRNA N-acetyltransferase activity. 

The first 2 would be children of RNA acetylation (GO:1990884), siblings to the tRNA and rRNA acetylation terms. In PMID 32555463 the authors show that Q5JHC6 (soon to be TMCA_THEKO) acetylates cytidine residues in a CCG motif. If you look at Figure 1 and 2 you will see that not only tRNA and rRNA but also mRNA and ncRNA (SRP in this case) are also subject to cytidine acetylation. 

Using the same paper you could also make the terms for non-coding RNA N-acetyltransferase activity, which would be a child of N-acetyltransferase activity (GO:0008080). The mRNA (GO:0051392), rRNA (GO:1990883), tRNA acetyltransferase (GO:0051392) activities exist already. Their names are a mixed bag, they all refer to N4 acetylation of cytidine but their names don't all reflect that.

mRNA acetylation has also been shown in PMID 38413733; the paper deals with human cells, so this is not confined to archaea. I have only read the abstract and Mats and Methods for that paper. I would not specify what kind of non-coding RNA is modified, that way the term will be applicable to all kingdoms.

There are some Rhea reactions, but the first is new as of yesterday, so you may not find it right away. They aren't going to make one for rRNA or ncRNA.

Generic reaction:
a cytidine in RNA + acetyl-CoA + ATP + H2O = an N(4)-acetylcytidine in RNA + ADP + phosphate + CoA + H(+)  [Rhea:82211]

tRNA acetylation:
a cytidine in tRNA + acetyl-CoA + ATP + H2O = an N(4)-acetylcytidine in tRNA + ADP + phosphate + CoA + H(+) [Rhea:53876]

mRNA acetylation:
a cytidine in mRNA + acetyl-CoA + ATP + H2O = an N(4)-acetylcytidine in mRNA + ADP + phosphate + CoA + H(+) [Rhea:58480]

Thanks, Andrea

**Comment by ValWood** [comment]
Hi @AndreaAuchincloss  these are now out of scope for GO. We have been slowly removing all of the x modification terms from the BP ontology (acetylation, adenylation, phosphorylation etc).

Instead you should use the appropriate molecular function  term  (i.e GO:0051392 
tRNA N-acetyltransferase activity) and then the 'actual process' that the modifier is involved in  (mRNA biosynthesis, catabolism, signalling, surveillance etc).

Please reopen if you need any function terms to describe these.
