### ISSUE TITLE
NTR: kinetochore-microtubule adaptor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29060]
Please provide as much information as you can: 

* **Suggested term label:**

kinetochore-microtubule adaptor activity

* **Definition (free text)**

The binding activity of a protein that connects the kinetochore and the spindle microtubules as part of attachment of mitotic spindle microtubules to kinetochore. PMID:22521786

* **Reference, in format PMID:#######**
PMID: 29724956 

* **Gene product name and ID to be annotated to this term**

All DASH complex and NDC80/MIND  complex subunits?

* **Parent term(s)**

GO:0140483  kinetochore adaptor activity

* **Any other information**

<img width="323" alt="Screenshot 2024-10-14 at 11 42 16" src="https://github.com/user-attachments/assets/c63cbb9a-99df-4c51-a9a9-323d110be98b">

**Comment by ValWood** [comment]
@pgaudet  OK to add this? I can't think of another way to describe the activity here.

**Comment by pgaudet** [comment]
yes sure
