### ISSUE TITLE
GO:0061483 sulfinylpropanyl adenylate synthase with no cross reference

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-ontology#29083]
GO:0061483 sulfinylpropanyl adenylate synthase lacks EC/RHEA cross references.
There is one Pombe annotation which shares the same reference with the definition. PMID:8346915 states that "We suggested that a sulfur analog of aspartate, cysteine sulfinate, might be utilized by these enzymes (adenylosuccinate synthetase and succinoaminoimidazole carboxamide ribonucleotide (SAICAR) synthetase)".
Therefore, it seems clear that adenylosuccinate synthetase (EC:6.3.4.4) has a different enzymatic activity that should be considered by RHEA.

**Comment by pgaudet** [comment]
There is a single IDA annotation to pombe ade2 
https://amigo.geneontology.org/amigo/gene_product/PomBase:SPAC144.03, also annotated to [adenylosuccinate synthase activity](https://amigo.geneontology.org/amigo/term/GO:0004019) (which corresponds to EC:6.3.4.4). 

The paper annotated to 'sulfinylpropanyl adenylate synthase (activity) is from 1993; "Two purine biosynthetic enzymes that are required for cadmium tolerance in Schizosaccharomyces pombe utilize cysteine sulfinate **_in vitro_**" 

@ValWood Would you be OK with obsoletion? it seems to be a non-physiological substrate. 

Thanks, Pascale

**Comment by ValWood** [comment]
Sure, I deleted it.
