### ISSUE TITLE
Taxon constraint:   JUN kinase activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29099]
Please provide as much information as you can: 

* **GO term ID label:**

GO:0004705 | JUN kinase activity | IEA with 2.7.11.24

* **Request to add a taxon constraint:**

* * **only in taxon: **
* * **never in taxon: **

never in yeast (need to check this) @edwong57  do you agree?

* **Request to remove a taxon constraint:**
Please specify

* **Supporting evidence if available (e.g PMID):**

**Comment by edwong57** [comment]
@ValWood, yes, this seems fine.

**Comment by cmungall** [comment]
no objection to the constraint but if this is done to prevent false
propagation from EC this should not be necessary as the EC term is broader
than the GO term, cc @balhoff

**Comment by ValWood** [comment]
> propagation from EC this should not be necessary as the EC term is broader

but the EC itself would not be blocked and isn't used  for the taxon contains. Isn't the  broad EC a separate unrelated issue?

**Comment by cmungall** [comment]
My point is that if you see

> GO:0004705 | JUN kinase activity | IEA with 2.7.11.24

There is a bug in someone's EC2GO propagation as this should never propagate as we should never propagate broad to narrow

**Comment by pgaudet** [comment]
I agree. I made the ticket high priority: #28763
