### ISSUE TITLE
GO:0008499 UDP-galactose:beta-N-acetylglucosamine beta-1,3-galactosyltransferase activity with no cross reference

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-ontology#29103]
GO:0008499 UDP-galactose:beta-N-acetylglucosamine beta-1,3-galactosyltransferase activity lacks EC/RHEA cross references.
One annotation reference PMID:9582303 is used by UniProt (e.g. https://www.uniprot.org/uniprotkb/Q9Y5Z6/entry) to support EC:2.4.1.86 and RHEA:53432.
N-acetyl-beta-D-glucosaminide beta-(1,3)-galactosyltransferase
an N-acetyl-beta-D-glucosaminyl derivative + UDP-alpha-D-galactose = a beta-D-galactosyl-(1->3)-N-acetyl-beta-D-glucosaminyl derivative + H(+) + UDP

**Comment by raymond91125** [comment]
EC:2.4.1.86 is already XREFed to GO:0047275 which is also XREFed to RHEA:16045. Rhea states that RHEA:16045 is a specific rxn to RHEA:53432.

**Comment by pgaudet** [comment]
Hi @raymond91125 

Do you need help with this one?

**Comment by raymond91125** [comment]
It looks to me that EC:2.4.1.86 and RHEA:53432 should be exact match to GO:0008499 and GO:0047275 should be a child of GO:0008499. However, [MetaCyc:2.4.1.86-RXN](https://biocyc.org/META/NEW-IMAGE?type=NIL&object=2.4.1.86-RXN), definition XREF for GO:0047275 says something different.

**Comment by pgaudet** [comment]
These two terms should be merged (obsolete/replace). 

-  [RHEA:53432](https://www.rhea-db.org/rhea/53432) and [RHEA:16045](https://www.rhea-db.org/rhea/16045) have essentially the same annotations, (see screenshot below)
![image](https://github.com/user-attachments/assets/d1584c42-9ac7-4785-a76b-541f533a9d65)
- The labels of the GO terms match the synonyms of EC: https://enzyme.expasy.org/EC/2.4.1.86
- 
<img width="611" alt="image" src="https://github.com/user-attachments/assets/a1ecad30-9a5d-4891-9184-40006f8db1ca">

The GO label is the 'systematic name' of 

Proposed actions: 
- [ ] obsolete GO:0047275 glucosaminylgalactosylglucosylceramide beta-galactosyltransferase activity (0 manual annotations)
- [ ] Move EC:2.4.1.86 and [RHEA:53432](https://www.rhea-db.org/rhea/53432) to GO:0008499 as exactMatches to GO:0047275 
- [ ] Change label GO:0008499 to  "N-acetyl-beta-D-glucosaminide beta-(1,3)-galactosyltransferase activity"
- [ ] Make sure the definition matches RHEA:53432


Thanks, Pascale
