### ISSUE TITLE
Add terms to the gocheck_obsoletion_candidate

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#29113]
Hey ontobot! apply: 

- GO:1904285	to subset gocheck_obsoletion_candidate
- GO:1904286	to subset gocheck_obsoletion_candidate
- GO:0010799	to subset gocheck_obsoletion_candidate
- GO:0010800	to subset gocheck_obsoletion_candidate
- GO:0010801	to subset gocheck_obsoletion_candidate
- GO:1903719	to subset gocheck_obsoletion_candidate
- GO:1903721	to subset gocheck_obsoletion_candidate
- GO:1903720	to subset gocheck_obsoletion_candidate
- GO:0033135	to subset gocheck_obsoletion_candidate
- GO:0033137	to subset gocheck_obsoletion_candidate
- GO:0033138	to subset gocheck_obsoletion_candidate
- GO:0033139	to subset gocheck_obsoletion_candidate
- GO:0033140	to subset gocheck_obsoletion_candidate
- GO:0033141	to subset gocheck_obsoletion_candidate
- GO:0001934	to subset gocheck_obsoletion_candidate
- GO:0001933	to subset gocheck_obsoletion_candidate
- GO:0001932	to subset gocheck_obsoletion_candidate
- GO:0043538	to subset gocheck_obsoletion_candidate
- GO:0060734	to subset gocheck_obsoletion_candidate
- GO:0060735	to subset gocheck_obsoletion_candidate
- GO:1904323	to subset gocheck_obsoletion_candidate
- GO:1904325	to subset gocheck_obsoletion_candidate
- GO:1904324	to subset gocheck_obsoletion_candidate
- GO:0010999	to subset gocheck_obsoletion_candidate
- GO:0031952	to subset gocheck_obsoletion_candidate
- GO:0050730	to subset gocheck_obsoletion_candidate
- GO:0031953	to subset gocheck_obsoletion_candidate
- GO:0031954	to subset gocheck_obsoletion_candidate
- GO:1900084	to subset gocheck_obsoletion_candidate
- GO:1900085	to subset gocheck_obsoletion_candidate
- GO:0061097	to subset gocheck_obsoletion_candidate
- GO:0050732	to subset gocheck_obsoletion_candidate
- GO:0050731	to subset gocheck_obsoletion_candidate
- GO:0010533	to subset gocheck_obsoletion_candidate
- GO:0042509	to subset gocheck_obsoletion_candidate
- GO:1904806	to subset gocheck_obsoletion_candidate
- GO:1904808	to subset gocheck_obsoletion_candidate
- GO:1904807	to subset gocheck_obsoletion_candidate
- GO:2000539	to subset gocheck_obsoletion_candidate
- GO:2000540	to subset gocheck_obsoletion_candidate
- GO:2000541	to subset gocheck_obsoletion_candidate
- GO:1901983	to subset gocheck_obsoletion_candidate
- GO:2000758	to subset gocheck_obsoletion_candidate
- GO:2000761	to subset gocheck_obsoletion_candidate
- GO:2000759	to subset gocheck_obsoletion_candidate
- GO:2000760	to subset gocheck_obsoletion_candidate
- GO:2000757	to subset gocheck_obsoletion_candidate
- GO:1902390	to subset gocheck_obsoletion_candidate
- GO:1902391	to subset gocheck_obsoletion_candidate
- GO:1901985	to subset gocheck_obsoletion_candidate
- GO:1901984	to subset gocheck_obsoletion_candidate
- GO:1904663	to subset gocheck_obsoletion_candidate
- GO:2000756	to subset gocheck_obsoletion_candidate
- GO:1904665	to subset gocheck_obsoletion_candidate
- GO:1904664	to subset gocheck_obsoletion_candidate
- GO:2000170	to subset gocheck_obsoletion_candidate
- GO:1902083	to subset gocheck_obsoletion_candidate
- GO:1904286	to subset gocheck_obsoletion_candidate
- GO:1904287	to subset gocheck_obsoletion_candidate
- GO:1904285	to subset gocheck_obsoletion_candidate
- GO:2000169	to subset gocheck_obsoletion_candidate
- GO:1901873	to subset gocheck_obsoletion_candidate
- GO:1901874	to subset gocheck_obsoletion_candidate
- GO:1901875	to subset gocheck_obsoletion_candidate
- GO:0060051	to subset gocheck_obsoletion_candidate
- GO:1904098	to subset gocheck_obsoletion_candidate
- GO:0060050	to subset gocheck_obsoletion_candidate
- GO:1904099	to subset gocheck_obsoletion_candidate
- GO:1904100	to subset gocheck_obsoletion_candidate
- GO:2000169	to subset gocheck_obsoletion_candidate
- GO:1901873	to subset gocheck_obsoletion_candidate
- GO:0060049	to subset gocheck_obsoletion_candidate
- GO:0031401	to subset gocheck_obsoletion_candidate
- GO:0031400	to subset gocheck_obsoletion_candidate
- GO:0035304	to subset gocheck_obsoletion_candidate
- GO:1903059	to subset gocheck_obsoletion_candidate
- GO:1903059	to subset gocheck_obsoletion_candidate
- GO:1902662	to subset gocheck_obsoletion_candidate
- GO:0060254	to subset gocheck_obsoletion_candidate
- GO:1903061	to subset gocheck_obsoletion_candidate
- GO:1903060	to subset gocheck_obsoletion_candidate
- GO:1902664	to subset gocheck_obsoletion_candidate
- GO:1902663	to subset gocheck_obsoletion_candidate
- GO:0060262	to subset gocheck_obsoletion_candidate
- GO:0120093	to subset gocheck_obsoletion_candidate
- GO:0120094	to subset gocheck_obsoletion_candidate
- GO:1903344	to subset gocheck_obsoletion_candidate
- GO:1903346	to subset gocheck_obsoletion_candidate
- GO:1903345	to subset gocheck_obsoletion_candidate
- GO:0010734	to subset gocheck_obsoletion_candidate
- GO:0010733	to subset gocheck_obsoletion_candidate
- GO:0010732	to subset gocheck_obsoletion_candidate
- GO:0090311	to subset gocheck_obsoletion_candidate
- GO:0090043	to subset gocheck_obsoletion_candidate
- GO:0090312	to subset gocheck_obsoletion_candidate
- GO:0090044	to subset gocheck_obsoletion_candidate
- GO:1900722	to subset gocheck_obsoletion_candidate
- GO:1900723	to subset gocheck_obsoletion_candidate
- GO:1900724	to subset gocheck_obsoletion_candidate

**Comment by pgaudet** [comment]
Replaces #27626

**Comment by pgaudet** [comment]
<img width="933" alt="image" src="https://github.com/user-attachments/assets/a63ca3e4-598b-428d-a118-8cba2ae85a15">

**Comment by balhoff** [comment]
@pgaudet I think you need an action word before each GO id
