### ISSUE TITLE
NTR: 	mitochondrial small subunit ribosome binding/small subunit ribosome translation factor adaptor activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29120]
Please provide as much information as you can: 

* **Suggested term label:**

mitochondrial small subunit ribosome binding

* **Definition (free text)**

standard 

* **Reference, in format PMID:#######**

PMID:38499152

* **Gene product name and ID to be annotated to this term**

mtf2, ppr4, mrh5 (Mrh5C complex, with contributes_to)

* **Parent term(s)**

GO:0097177 | mitochondrial ribosome binding

**Comment by ValWood** [comment]
I actually need a term to describe an adaptor between the ribosome and the translation factors, because isn't possible with extensions and it's tricky in GO cam without such a term

small subunit ribosome translation factor adaptor activity
parent protein-macromolecule adaptor activity
narrow synonym translation initiation factor recruiting 

this is for another paper from the same lab
PMID:34119521

**Comment by ValWood** [comment]
beautiful author curation @hattrill @sjm41 check this out:
https://curation.pombase.org/pombe/curs/811ad3c8dcd877f3/ro/ PMID:34119521
https://curation.pombase.org/pombe/curs/81cc9cd6e028de43/ro/  PMID:38499152
but the authors don't really like doing GO for some reason!

**Comment by hattrill** [comment]
That is lovely ...I guess curation with the GO can be a bit daunting. Can't go wrong with phenotypes - is what it is and as long as there is a term, life is sweet.

**Comment by pgaudet** [comment]
Hi @ValWood 
Why cant you use extensions? [protein-macromolecule adaptor activity](http://purl.obolibrary.org/obo/GO_0030674)+ relevant complexes or proteins as inputs?

**Comment by ValWood** [comment]
OK ! I forgot I could put a component in an extension
