### ISSUE TITLE
Add terms to the do_not_annotate subset - single step processes

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#29123]
Hey ontobot! apply: 

- add	GO:1904285	to subset gocheck_obsoletion_candidate
- add	GO:1904286	to subset gocheck_obsoletion_candidate
- add	GO:0010799	to subset gocheck_obsoletion_candidate
- add	GO:0010800	to subset gocheck_obsoletion_candidate
- add	GO:0010801	to subset gocheck_obsoletion_candidate
- add	GO:1903719	to subset gocheck_obsoletion_candidate
- add	GO:1903721	to subset gocheck_obsoletion_candidate
- add	GO:1903720	to subset gocheck_obsoletion_candidate
- add	GO:0033135	to subset gocheck_obsoletion_candidate
- add	GO:0033137	to subset gocheck_obsoletion_candidate
- add	GO:0033138	to subset gocheck_obsoletion_candidate
- add	GO:0033139	to subset gocheck_obsoletion_candidate
- add	GO:0033140	to subset gocheck_obsoletion_candidate
- add	GO:0033141	to subset gocheck_obsoletion_candidate
- add	GO:0001934	to subset gocheck_obsoletion_candidate
- add	GO:0001933	to subset gocheck_obsoletion_candidate
- add	GO:0001932	to subset gocheck_obsoletion_candidate
- add	GO:0043538	to subset gocheck_obsoletion_candidate
- add	GO:0060734	to subset gocheck_obsoletion_candidate
- add	GO:0060735	to subset gocheck_obsoletion_candidate
- add	GO:1904323	to subset gocheck_obsoletion_candidate
- add	GO:1904325	to subset gocheck_obsoletion_candidate
- add	GO:1904324	to subset gocheck_obsoletion_candidate
- add	GO:0010999	to subset gocheck_obsoletion_candidate
- add	GO:0031952	to subset gocheck_obsoletion_candidate
- add	GO:0050730	to subset gocheck_obsoletion_candidate
- add	GO:0031953	to subset gocheck_obsoletion_candidate
- add	GO:0031954	to subset gocheck_obsoletion_candidate
- add	GO:1900084	to subset gocheck_obsoletion_candidate
- add	GO:1900085	to subset gocheck_obsoletion_candidate
- add	GO:0061097	to subset gocheck_obsoletion_candidate
- add	GO:0050732	to subset gocheck_obsoletion_candidate
- add	GO:0050731	to subset gocheck_obsoletion_candidate
- add	GO:0010533	to subset gocheck_obsoletion_candidate
- add	GO:0042509	to subset gocheck_obsoletion_candidate
- add	GO:1904806	to subset gocheck_obsoletion_candidate
- add	GO:1904808	to subset gocheck_obsoletion_candidate
- add	GO:1904807	to subset gocheck_obsoletion_candidate
- add	GO:2000539	to subset gocheck_obsoletion_candidate
- add	GO:2000540	to subset gocheck_obsoletion_candidate
- add	GO:2000541	to subset gocheck_obsoletion_candidate
- add	GO:1901983	to subset gocheck_obsoletion_candidate
- add	GO:2000758	to subset gocheck_obsoletion_candidate
- add	GO:2000761	to subset gocheck_obsoletion_candidate
- add	GO:2000759	to subset gocheck_obsoletion_candidate
- add	GO:2000760	to subset gocheck_obsoletion_candidate
- add	GO:2000757	to subset gocheck_obsoletion_candidate
- add	GO:1902390	to subset gocheck_obsoletion_candidate
- add	GO:1902391	to subset gocheck_obsoletion_candidate
- add	GO:1901985	to subset gocheck_obsoletion_candidate
- add	GO:1901984	to subset gocheck_obsoletion_candidate
- add	GO:1904663	to subset gocheck_obsoletion_candidate
- add	GO:2000756	to subset gocheck_obsoletion_candidate
- add	GO:1904665	to subset gocheck_obsoletion_candidate
- add	GO:1904664	to subset gocheck_obsoletion_candidate
- add	GO:2000170	to subset gocheck_obsoletion_candidate
- add	GO:1902083	to subset gocheck_obsoletion_candidate
- add	GO:1904286	to subset gocheck_obsoletion_candidate
- add	GO:1904287	to subset gocheck_obsoletion_candidate
- add	GO:1904285	to subset gocheck_obsoletion_candidate
- add	GO:2000169	to subset gocheck_obsoletion_candidate
- add	GO:1901873	to subset gocheck_obsoletion_candidate
- add	GO:1901874	to subset gocheck_obsoletion_candidate
- add	GO:1901875	to subset gocheck_obsoletion_candidate
- add	GO:0060051	to subset gocheck_obsoletion_candidate
- add	GO:1904098	to subset gocheck_obsoletion_candidate
- add	GO:0060050	to subset gocheck_obsoletion_candidate
- add	GO:1904099	to subset gocheck_obsoletion_candidate
- add	GO:1904100	to subset gocheck_obsoletion_candidate
- add	GO:2000169	to subset gocheck_obsoletion_candidate
- add	GO:1901873	to subset gocheck_obsoletion_candidate
- add	GO:0060049	to subset gocheck_obsoletion_candidate
- add	GO:0031401	to subset gocheck_obsoletion_candidate
- add	GO:0031400	to subset gocheck_obsoletion_candidate
- add	GO:0035304	to subset gocheck_obsoletion_candidate
- add	GO:1903059	to subset gocheck_obsoletion_candidate
- add	GO:1903059	to subset gocheck_obsoletion_candidate
- add	GO:1902662	to subset gocheck_obsoletion_candidate
- add	GO:0060254	to subset gocheck_obsoletion_candidate
- add	GO:1903061	to subset gocheck_obsoletion_candidate
- add	GO:1903060	to subset gocheck_obsoletion_candidate
- add	GO:1902664	to subset gocheck_obsoletion_candidate
- add	GO:1902663	to subset gocheck_obsoletion_candidate
- add	GO:0060262	to subset gocheck_obsoletion_candidate
- add	GO:0120093	to subset gocheck_obsoletion_candidate
- add	GO:0120094	to subset gocheck_obsoletion_candidate
- add	GO:1903344	to subset gocheck_obsoletion_candidate
- add	GO:1903346	to subset gocheck_obsoletion_candidate
- add	GO:1903345	to subset gocheck_obsoletion_candidate
- add	GO:0010734	to subset gocheck_obsoletion_candidate
- add	GO:0010733	to subset gocheck_obsoletion_candidate
- add	GO:0010732	to subset gocheck_obsoletion_candidate
- add	GO:0090311	to subset gocheck_obsoletion_candidate
- add	GO:0090043	to subset gocheck_obsoletion_candidate
- add	GO:0090312	to subset gocheck_obsoletion_candidate
- add	GO:0090044	to subset gocheck_obsoletion_candidate
- add	GO:1900722	to subset gocheck_obsoletion_candidate
- add	GO:1900723	to subset gocheck_obsoletion_candidate
- add	GO:1900724	to subset gocheck_obsoletion_candidate

**Comment by ValWood** [comment]
All these have 
This term should not be used for direct annotation.
rather than the pending obsoletion term Is that OK?

**Comment by pgaudet** [comment]
What do you mean? We want to obsolete these single-step processes, don't we?

**Comment by pgaudet** [comment]
This is the list with the term labels

GO:2000756	regulation of peptidyl-lysine acetylation
GO:2000757	negative regulation of peptidyl-lysine acetylation
GO:2000758	positive regulation of peptidyl-lysine acetylation
GO:2000759	regulation of N-terminal peptidyl-lysine acetylation
GO:2000760	negative regulation of N-terminal peptidyl-lysine acetylation
GO:2000761	positive regulation of N-terminal peptidyl-lysine acetylation
GO:1902662	regulation of peptidyl-L-cysteine S-palmitoylation
GO:1902663	negative regulation of peptidyl-L-cysteine S-palmitoylation
GO:1902664	positive regulation of peptidyl-L-cysteine S-palmitoylation
GO:1900085	negative regulation of peptidyl-tyrosine autophosphorylation
GO:1900084	regulation of peptidyl-tyrosine autophosphorylation
GO:2000539	regulation of protein geranylgeranylation
GO:2000540	negative regulation of protein geranylgeranylation
GO:2000541	positive regulation of protein geranylgeranylation
GO:0120093	regulation of peptidyl-lysine crotonylation
GO:0120094	negative regulation of peptidyl-lysine crotonylation
GO:1904808	positive regulation of protein oxidation
GO:1904807	negative regulation of protein oxidation
GO:1904806	regulation of protein oxidation
GO:0090311	regulation of protein deacetylation
GO:0090312	positive regulation of protein deacetylation
GO:0031954	positive regulation of protein autophosphorylation
GO:0031952	regulation of protein autophosphorylation
GO:0031953	negative regulation of protein autophosphorylation
GO:0090043	regulation of tubulin deacetylation
GO:0090044	positive regulation of tubulin deacetylation
GO:1903059	regulation of protein lipidation
GO:1903061	positive regulation of protein lipidation
GO:1903060	negative regulation of protein lipidation
GO:2000170	positive regulation of peptidyl-cysteine S-nitrosylation
GO:2000169	regulation of peptidyl-cysteine S-nitrosylation
GO:0050730	regulation of peptidyl-tyrosine phosphorylation
GO:0050731	positive regulation of peptidyl-tyrosine phosphorylation
GO:0050732	negative regulation of peptidyl-tyrosine phosphorylation
GO:0061097	regulation of protein tyrosine kinase activity
GO:0060734	regulation of endoplasmic reticulum stress-induced eIF2 alpha phosphorylation
GO:0060735	regulation of eIF2 alpha phosphorylation by dsRNA
GO:1901983	regulation of protein acetylation
GO:1901985	positive regulation of protein acetylation
GO:1901984	negative regulation of protein acetylation
GO:0033140	negative regulation of peptidyl-serine phosphorylation of STAT protein
GO:0033141	positive regulation of peptidyl-serine phosphorylation of STAT protein
GO:0033137	negative regulation of peptidyl-serine phosphorylation
GO:0033135	regulation of peptidyl-serine phosphorylation
GO:0033139	regulation of peptidyl-serine phosphorylation of STAT protein
GO:0033138	positive regulation of peptidyl-serine phosphorylation
GO:0001932	regulation of protein phosphorylation
GO:0001933	negative regulation of protein phosphorylation
GO:0001934	positive regulation of protein phosphorylation
GO:0060262	negative regulation of N-terminal protein palmitoylation
GO:0060254	regulation of N-terminal protein palmitoylation
GO:1903720	negative regulation of I-kappaB phosphorylation
GO:1903721	positive regulation of I-kappaB phosphorylation
GO:1903719	regulation of I-kappaB phosphorylation
GO:1904325	positive regulation of inhibitory G protein-coupled receptor phosphorylation
GO:1904287	positive regulation of protein-pyridoxal-5-phosphate linkage
GO:1904286	negative regulation of protein-pyridoxal-5-phosphate linkage
GO:1904285	regulation of protein-pyridoxal-5-phosphate linkage
GO:1904324	negative regulation of inhibitory G protein-coupled receptor phosphorylation
GO:1904323	regulation of inhibitory G protein-coupled receptor phosphorylation
GO:0042509	regulation of tyrosine phosphorylation of STAT protein
GO:1904100	positive regulation of protein O-linked glycosylation
GO:1904099	negative regulation of protein O-linked glycosylation
GO:1904098	regulation of protein O-linked glycosylation
GO:1902083	negative regulation of peptidyl-cysteine S-nitrosylation
GO:1904665	positive regulation of N-terminal peptidyl-methionine acetylation
GO:1904664	negative regulation of N-terminal peptidyl-methionine acetylation
GO:1904663	regulation of N-terminal peptidyl-methionine acetylation
GO:0010732	regulation of protein glutathionylation
GO:0010734	negative regulation of protein glutathionylation
GO:0010733	positive regulation of protein glutathionylation
GO:1900722	regulation of protein adenylylation
GO:1900724	positive regulation of protein adenylylation
GO:1900723	negative regulation of protein adenylylation
GO:0010801	negative regulation of peptidyl-threonine phosphorylation
GO:0010800	positive regulation of peptidyl-threonine phosphorylation
GO:0010799	regulation of peptidyl-threonine phosphorylation
GO:0010999	regulation of eIF2 alpha phosphorylation by heme

**Comment by ValWood** [comment]
Yesterday I spotted that in QuickGO some of these had
"do not annotate" but did not have the "pending obsoletion"

But maybe the change had not filtered through.

**Comment by ValWood** [comment]
For example https://www.ebi.ac.uk/QuickGO/term/GO:1904286
