### ISSUE TITLE
 GO:0001537 N-acetylgalactosamine 4-O-sulfotransferase activity with no cross reference

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-ontology#29139]
GO:0001537 N-acetylgalactosamine 4-O-sulfotransferase activity lacks EC/RHEA cross references.
There is no publication reference either. QuickGO term history says that this term was XREF to [Reactome:R-HSA-3636919](https://reactome.org/content/detail/R-HSA-3636919), which is about Carbohydrate sulfotransferase 14 (CHST14), "the transfer of sulfate to position 4 of N-acetylgalactosamine (GalNAc) residue of dermatan". Also, UniProt annotated [CHST14](https://www.uniprot.org/uniprotkb/Q8NCH0/entry) with EC:2.8.2.35 dermatan 4-sulfotransferase, RHEA:48052
n 3'-phosphoadenylyl sulfate + dermatan = n adenosine 3',5'-bisphosphate + dermatan 4'-sulfate + n H(+)

**Comment by raymond91125** [comment]
Propose to rename GO:0001537 dermatan 4-sulfotransferase.

**Comment by pgaudet** [comment]
I think this can be closed?

**Comment by raymond91125** [comment]
Closed 5 days ago. Something hanging some where?
