### ISSUE TITLE
Missing parent: GO:0001576 globoside biosynthetic process

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29130]
* **GO term ID and label for which you request a new superclass**

GO:0001576  globoside biosynthetic process

The chemical reactions and pathways resulting in the formation of a ceramide with a core structure of GalNAc-beta-(1->3)-Gal-alpha-(1->4)-Glc(I).

* **New superclass (parent) suggested**

If this is a valid classification it should have is_a ceramide biosynthetic process, since it is defined as a ceramide

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by ValWood** [comment]
may be a definition proble. 
Glycosphingolipids are **derived from** ceramides

**Comment by pgaudet** [comment]
This is a ChEBI issue. Please open a ticket there.

**Comment by ValWood** [comment]
Is globoside definitely a ceramine, though?

**Comment by deustp01** [comment]
A quick Google search shows that:

- Globosides are a type of glycosphingolipid (GSL) made up of a ceramide backbone, and a terminal oligosaccharide.
- A ceramide is composed of sphingosine and a fatty acid joined by an amide bond.
- Sphingosine (2-amino-4-trans-octadecene-1,3-diol) is an 18-carbon amino alcohol with an unsaturated hydrocarbon chain.

So a ceramide is a part of a globoside in the same way that adenine is a part of NAD.

**Comment by ValWood** [comment]
OK, I will alter the definiton.

**Comment by ValWood** [comment]
The chemical reactions and pathways resulting in the formation of a ceramide with a core structure of GalNAc-beta-(1->3)-Gal-alpha-(1->4)-Glc(I).

->
The chemical reactions and pathways resulting in the formation of a glycosphingolipid with a core structure of GalNAc-beta-(1->3)-Gal-alpha-(1->4)-Glc(I).
