### ISSUE TITLE
Obsoletion request: GO:0097159 organic cyclic compound binding

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29143]
Please provide as much information as you can:

* **GO term ID and Label**

GO:0097159 organic cyclic compound binding
Definition
Binding to an organic cyclic compound, any molecular entity that contains carbon arranged in a cyclic molecular structure. 

* **Reason for deprecation** Put an x in the appropriate box: 

 - [ ]  The reason for obsoletion is that this term was an unnecessary grouping term.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

There are only 24 direct annotations

This is worse than just being an "unnecessary grouping term, because its descendants are quite random.

For example
RNA binding  (polymer)
threonine binding  (amino acid)
penicillin  (drug)

are under here
but not protein binding (which  makes no sense if RNA is under here)

its just the oddest grouping term ever

C) it makes other binding terms  difficult to locate in 'drilling down'

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

24 

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by pgaudet** [comment]
I propose we obsolete the following terms: 
GO:0097159 organic cyclic compound binding
GO:1901378 organic heteropentacyclic compound biosynthetic process
GO:1901377 organic heteropentacyclic compound catabolic process
GO:1901376 organic heteropentacyclic compound metabolic process
GO:0014070 response to organic cyclic compound
GO:0071407 cellular response to organic cyclic compound

As 'non-useful grouping classes' 


Thanks, Pascale
