### ISSUE TITLE
GO:0099053   activating signal cointegrator 1 complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29152]
The description of this complex (and the annotation of the complex members)
are very out of date.
It has been known for a while that  the physiological complex is involved in ribosome disassembly during translation  initiation scanning.

GO:0099053   activating signal cointegrator 1 complex
Definition ([GO:0099053 GONUTS page](http://gowiki.tamu.edu/wiki/index.php/Category:GO:0099053))
A protein complex that contains TRIP4 (ASC1) and acts a transcriptional coactivator by interacting with transcription factors such as NF-kappa B. In humans this complex has 4 subunits: TRIP4 + ASCC1-3. PMID:12077347

see
[Ribosomal collision is not a prerequisite for ZNF598-mediated ribosome ubiquitination and disassembly of ribosomal complexes by ASCC.](https://pubmed.ncbi.nlm.nih.gov/38366554/)
Miścicka A, Bulakhov AG, Kuroha K, Zinoviev A, Hellen CUT, Pestova TV.
Nucleic Acids Res. 2024 May 8;52(8):4627-4643. doi: 10.1093/nar/gkae087.
PMID: 38366554

[The ASC-1 complex promotes translation initiation by scanning ribosomes.](https://pubmed.ncbi.nlm.nih.gov/37092320/)
Kito Y, Matsumoto A, Ichihara K, Shiraishi C, Tang R, Hatano A, Matsumoto M, Han P, Iwasaki S, Nakayama KI.
EMBO J. 2023 Jun 15;42(12):e112869. doi: 10.15252/embj.2022112869. Epub 2023 Apr 24.
PMID: 37092320
 
[Unresolved stalled ribosome complexes restrict cell-cycle progression after genotoxic stress.](https://pubmed.ncbi.nlm.nih.gov/35180429/)
Stoneley M, Harvey RF, Mulroney TE, Mordue R, Jukes-Jones R, Cain K, Lilley KS, Sawarkar R, Willis AE.
Mol Cell. 2022 Apr 21;82(8):1557-1572.e7. doi: 10.1016/j.molcel.2022.01.019. Epub 2022 Feb 17.
PMID: 35180429 Free PMC article.
During the translation surveillance mechanism known as ribosome-associated quality control, the ASC-1 complex (ASCC) disassembles ribosomes stalled on the mRNA. Here, we show that there are two distinct classes of stalled ribosome. ...
 
[The ASC-1 Complex Disassembles Collided Ribosomes.](https://pubmed.ncbi.nlm.nih.gov/32579943/)
Juszkiewicz S, Speldewinde SH, Wan L, Svejstrup JQ, Hegde RS.
Mol Cell. 2020 Aug 20;79(4):603-614.e8. doi: 10.1016/j.molcel.2020.06.006. Epub 2020 Jun 23.
PMID: 32579943 Free PMC article.
Here, we reconstitute the disassembly of a collided polysome in a mammalian cell-free system. The widely conserved ASC-1 complex (ASCC) containing the ASCC3 helicase disassembles the leading ribosome in an ATP-dependent reaction.

We should probably follow best practice and  obsolete and reinstate a new term with the different definition. This will encourage beope to review all of the historical annotation.

**Comment by raymond91125** [comment]
It seems the ASCC complex in human cells contains 4 proteins, whereas ribosome quality control triggering complex (RQT) in yeast has 3 proteins. ASCC1 is not found in yeasts (PMID:32579943, PMID:36801861). What I haven't been able to figure out is if the transcriptional coactivator activity in human cells have been disputed, or that function is not conserved in yeasts.
There are only 3 EXP annotations to GO:0099053 at the moment (TRIP4, ASCC2, ASCC3). Thus I don't think that affects how we modify the definition. I think we could add the RQT function and say that ASCC1 is not a required component for that. @ValWood Is that suffcient?

**Comment by ValWood** [comment]
Can I get back to you o this one @raymond91125 
My feeling is that this is a paradigm shift on the function of this complex. The older data about DNA acetylation looks a bit and transcription coactivator looks shakey. Also yeast (at least pombe) does have ASCC1 .

the transcription co-activator stuff is from 2002,
https://pubmed.ncbi.nlm.nih.gov/12077347/
and does not seem to be repeated as far as I could see. I went through all of the abstracts I could see before I opened the ticket.

**Comment by raymond91125** [comment]
PMID:26924529 (2016) states "Trip4 and Ascc1 have identical expression patterns in 17.5-day-old mouse embryos with high expression levels in the spinal cord, brain, paraspinal ganglia, thyroid, and submandibular glands. Antisense morpholino-mediated knockdown of either trip4 or ascc1 in zebrafish disrupted the highly patterned and coordinated process of α-motoneuron outgrowth and formation of myotomes and neuromuscular junctions and led to a swimming defect in the larvae.".

**Comment by ValWood** [comment]
GO:0099053    activating signal cointegrator 1 complex

has only 3 EXP annotation
(human, from PMID:12077347)

although RQC-trigger complex is defined as
https://www.ebi.ac.uk/QuickGO/term/GO:0180022

A ribosome disassembly complex which dissociates stalled ribosome subunits as part of the ribosome quality control pathway. RQT complex is composed of a RNA helicase-family protein yeast Rqt2 (human ASCC3), a ubiquitin-binding protein yeast Rqt3, (human ASCC2), and Rqt4 (Human TRIP4). PMID:28757607 PMID:32099016


this is because it was first described in S. cerevisiae  which has no ASCC1
The human RQC-trigger complex does have ASCC1

This paper is clearly describing 
The ASC-1 Complex which == activating signal cointegrator 1 complex == RQC-trigger complex
The ASC-1 Complex Disassembles Collided Ribosomes https://pmc.ncbi.nlm.nih.gov/articles/PMC7447978/
(uses a mammalian cell-free system and includes ASCC1, although it says a yeast orthoog is not detected)

So, we definitely have multiple ways to describe the same complex. 
I have been following this group of genes for many years and had them annotated as "unknowns" until relatively recently because the processes were so inconsistent across species (because they were largely phenotypes).

However, it is possible that the complex has multiple roles because it is described as a ubiquitin ligase (I don't see the UB ligase domain, but it could be cryptic). Most of the early work is phenotypes, and it is unsurprising that a complex required to dissociate ribosomes would have pleiotropic effects.

The ribosome dissociation is a consistent story across species, and so far seems to be the major role.

So, I would recommend to  obsolete 
GO:0099053    activating signal cointegrator 1 complex

make
activating signal cointegrator 1 complex and ASC-1 complex exact synonyms of 

GO:0180022	RQC-trigger complex
We could even name this "RQC-trigger/ASC-1 complex" 
 
Revise the definition of GO:0180022	RQC-trigger complex
to include ASCC1 (can mention in comments this is not present in S. cerevisiae)

but also mention that it may have additional roles in DNA damage response and transcription in humans
