### ISSUE TITLE
NTR: cortical endoplasmic reticulum membrane

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29159]
Please provide as much information as you can: 

* **Suggested term label:**

 cortical endoplasmic reticulum membrane

* **Definition (free text)**

standard def

* **Reference, in format PMID:#######**

https://www.pombase.org/reference/PMID:32735772

* **Gene product name and ID to be annotated to this term**

https://www.pombase.org/gene/SPAC17C9.12 scs22
https://www.pombase.org/gene/SPBC16G5.05c scs2

* **Parent term(s)**

GO:0032541   cortical endoplasmic reticulum
GO:0005789 | endoplasmic reticulum membrane

[GO:0005789](https://www.pombase.org/term/GO:0005789)	
[endoplasmic reticulum membrane](https://www.pombase.org/term/GO:0005789)

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160219
+name: cortical endoplasmic reticulum membrane
+namespace: cellular_component
+def: "The lipid bilayer surrounding the cortical endoplasmic reticulum." [PMID:32735772]
+is_a: GO:0005789 ! endoplasmic reticulum membrane
+intersection_of: GO:0016020 ! membrane
+intersection_of: bounding_layer_of GO:0032541 ! cortical endoplasmic reticulum
+relationship: part_of GO:0032541 ! cortical endoplasmic reticulum
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/29159" xsd:anyURI
+created_by: rynl
+creation_date: 2024-11-11T23:58:54Z
