### ISSUE TITLE
NTR: [Morula formation]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#29162]
Hi GO,

I would need a couple of terms related to morula development (an early development stage in mammals that takes place before blastocyst formation).
Thanks
Sylvain

GO:XXXXXXX Morula development
The process whose specific outcome is the progression of the morula over time.
The morula is a spherical embryonic mass of blastomeres formed before the blastula and resulting from cleavage of the fertilized ovum.
child of GO:0001701 in utero embryonic development
child of GO:0048646 anatomical structure formation involved in morphogenesis
Xref UBERON_0000085
PMID:37935903
PMID:38386558
PMID:39361745

GO:XXXXXXX Morula formation
The initial formation of a spherical embryonic mass of blastomeres formed before the blastula and resulting from cleavage of the fertilized ovum.
child of GO:XXXXXXX Morula development
child of GO:0048646 anatomical structure formation involved in morphogenesis
Xref UBERON_0000085
PMID:37935903
PMID:38386558
PMID:39361745

**Comment by pgaudet** [comment]
Added 'blastula' synonyms to blastocyst terms - in Uberon it's a related synonym. 


Im mammals, the structure is called a (https://en.wikipedia.org/wiki/Blastocyst), and in other animals, a [blastula](https://en.wikipedia.org/wiki/Blastulation).
