### ISSUE TITLE
Missing parent: ascus development

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29179]
* **GO term ID and label for which you request a new superclass**

ascus development.
I never cane across this term before, but I am picking up an annotation.
Should it be moved under  sexual sporulation resulting in formation of a cellular spore?

<img width="1014" alt="TODO GO Ticket" src="https://github.com/user-attachments/assets/191f499e-096a-4182-9c80-e57ec5c18755">

* **New superclass (parent) suggested**

* **Reference(s), if appropriate**
PMID:nnnnnnn

**Comment by ValWood** [comment]
In fact, for the paper curated 
https://europepmc.org/article/MED/27604537  the annotation is based on 
"The percentage of ascus to the total cell number is averaged from 3 independent experiments, and more than 100 cells were counted in each experiment."

https://europepmc.org/article/MED/27604537
I would not annotate this to "regulation of ascus development"
This is just a sporulation assay, I'd annotate to "ascospore formation"

This is the only single annotation in the branch
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0075319&evidenceCode=ECO:0000269&evidenceCodeUsage=descendants

**Comment by pgaudet** [comment]
Hi Val, 

This is distinct from sporulation, it's the formation of the spore sack: see comment in the term 
> Note that ascospores and asci are separate biological structures. The ascus is the structure that contain the ascospores, but the development of the ascus is a different process than the formation of the ascospores themselves; for instance, some mutations affect sporulation without affecting ascus development. For this reason, GO:0030437 ascospore formation and GO:0075317 ascus development are different terms and are not linked.

**Comment by ValWood** [comment]
But its still part_of the broader "sporulation" process? i.e. ascomycetes you don't form an ascus outside of the "sporulation process"

ascospore formation is defined
The process in which cells that are products of meiosis acquire the specialized features of ascospores. Ascospores are generally found in clusters of four or eight spores within a single mother cell, the ascus, and are characteristic of the ascomycete fungi (phylum Ascomycota). PMID:16339736

but  we use this term to describe the entire "sporulation" process.
The reason that "sporulation" is broad, rather than exact is because we had to consider plant and bacterial spores.

@edwong57  what do you think?

Thay should definitely  have a common parent that refers to the entire sporulation process.

**Comment by pgaudet** [comment]
ascospore formation is a cellular process; 
isn't the ascus more of an organism-level process'? ie it contains all the spores; I dont quite see how one is part of the other.

**Comment by ValWood** [comment]
Probably we just need a common parent to describe the sporulation pathway which would include ascus formation ('ascospore formation' has always been used as a proxy for this). 

Maybe its ok, we don't use it anyway so I'll close.
