### ISSUE TITLE
Obsoletion request: DNA ligation and descendants

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29219]
Please provide as much information as you can:

* **GO term ID and Label**

DNA ligation and descendants:

<img width="830" alt="Screenshot 2024-11-14 at 11 36 35" src="https://github.com/user-attachments/assets/1a57ddff-2ab0-4bad-bb40-7fa7a696a663">

<img width="444" alt="Screenshot 2024-11-14 at 11 36 40" src="https://github.com/user-attachments/assets/e9e933d3-8823-4c1c-a449-50dd5c2ae034">

GO:1902972	biological_process	premeiotic DNA replication DNA ligation
GO:1902973	biological_process	mitotic DNA replication DNA ligation
GO:1902327	biological_process	bacterial-type DNA replication DNA ligation
GO:1902333	biological_process	nuclear DNA replication DNA ligation
GO:1904877	biological_process	positive regulation of DNA ligase activity
GO:1904875	biological_process	regulation of DNA ligase activity
GO:1902291	biological_process	cell cycle DNA replication DNA ligation
GO:0051103	biological_process	DNA ligation involved in DNA repair
GO:0051104	biological_process	DNA-dependent DNA replication DNA ligation
GO:0051102	biological_process	DNA ligation involved in DNA recombination
GO:0051107	biological_process	negative regulation of DNA ligation
GO:0051105	biological_process	regulation of DNA ligation
GO:0051106	biological_process	positive regulation of DNA ligation
GO:0006288	biological_process	base-excision repair, DNA ligation

* **Reason for deprecation** Put an x in the appropriate box: 

 - [x] The reason for obsoletion is that this term represents a molecular function.

* **"Replace by" term (ID and label)**
If all annotations can safely be moved to that term

* **"Consider" term(s) (ID and label)**
Suggestions for reannotation

* **Are there annotations to this term?**
- How many EXP:

* **Are there mappings and cross references to this term? (InterPro, Keywords; check QuickGO cross-references section)**

* **Is this term in a subset? (check the AmiGO page for that term)**

* **Any other information**

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by raymond91125** [comment]
- [ ] GO:0006266 DNA ligation
- [ ] GO:1902972 premeiotic DNA replication DNA ligation
- [ ] GO:1902973 mitotic DNA replication DNA ligation
- [ ] GO:1902327 bacterial-type DNA replication DNA ligation
- [ ] GO:1902333 nuclear DNA replication DNA ligation
- [ ] GO:1904877 positive regulation of DNA ligase activity
- [ ] GO:1904875 regulation of DNA ligase activity
- [ ] GO:1902291 cell cycle DNA replication DNA ligation
- [ ] GO:0051103 DNA ligation involved in DNA repair
- [ ] GO:0051104 DNA-dependent DNA replication DNA ligation
- [ ] GO:0051102 DNA ligation involved in DNA recombination
- [ ] GO:0051107 negative regulation of DNA ligation
- [ ] GO:0051105 regulation of DNA ligation
- [ ] GO:0051106 positive regulation of DNA ligation
- [ ] GO:0006288 base-excision repair, DNA ligation
