### ISSUE TITLE
NTR: [Rhoa-activating G protein-coupled receptor signaling pathway]

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#29217]
Hi GO,
I realize that there is no GO term for the Rhoa-activating GPCR signaling 

Could you create it?

Thanks

Sylvain

Term: ~Rhoa-activating G protein-coupled receptor signaling pathway~ 
**GO editors propose Rho-activating G protein-coupled receptor signaling pathway**
Definition: A G protein-coupled receptor signaling pathway in which the signal is transmitted via the activation of RhoA activity.
child of GO:0007186 G protein-coupled receptor signaling pathway
PMID:12515866, PMID:15240885

**Comment by raymond91125** [comment]
PMID:10836144
![image](https://github.com/user-attachments/assets/724ba0c4-fa7f-44eb-9ba2-d177281a5b4b)

**Comment by pgaudet** [comment]
Hi @raymond91125 

This is the 4th GPCR pathway, we dont have the term that represents the Galpha q pathway: see figure 1 from 
https://www.frontiersin.org/journals/endocrinology/articles/10.3389/fendo.2021.706957/full


<img width="1004" alt="image" src="https://github.com/user-attachments/assets/b79a7280-cf23-492b-a21e-a8722dbb01ab">


About the combinatorial, we should check again with @cmungall and @thomaspd , but my recollection is that we capture all the ligands. This is a lot of terms, but fewer than if we have 'x pathway involved in y process'. 

Thanks, Pascale
