### ISSUE TITLE
Obsoletion request: GO:0044349  DNA excision

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29220]
Please provide as much information as you can:

* **GO term ID and Label**

GO:0044349  DNA excision (1 IMP) (this is 2 MF's but it should be represented as activities as part of the larger process)
GO:0000718  nucleotide-excision repair, DNA damage removal (0)

* **Reason for deprecation** Put an x in the appropriate box: 
 
 - [ ] The reason for obsoletion is that this term represents molecular functions.

**Comment by raymond91125** [comment]
@dsiegele Are you OK with obsoleting GO:0044349 DNA excision?
