### ISSUE TITLE
Add synonyms  prenyltransferases

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-ontology#29264]
- [x] GO:0004161 dimethylallyltranstransferase is identical with geranyl diphosphate synthase (EC2.5.1.1) [RHEA:22408](https://www.rhea-db.org/rhea/22408)
add synonym

- [x] GO:0004337 geranyltranstransferase is identical with farnesyl  diphosphate synthase (EC2.5.1.10)
https://www.rhea-db.org/rhea?query=ec%3A2.5.1.10
add synonym

- [x] GO:0004311 farnesyltranstransferase is identical with geranylgeranyl diphosphate synthase (EC2.5.1.29)
https://www.rhea-db.org/rhea?query=ec%3A2.5.1.29
(add hyphenless string)

**Comment by sjm41** [comment]
These alternative names are also documented in this old ticket - https://github.com/geneontology/go-ontology/issues/20661

I should/will look at that ticket again to try to close it, and can also address these synonyms as I do so.  So I can take this ticket too?

**Comment by ValWood** [comment]
Sure, I didn't check as thoroughly as I should.
This info came in from our community checking my GO-CAM model - I really struggled with these activities, it took me a couple of attempts to get it right!

**Comment by sjm41** [comment]
Additional prenyltransferase synonyms to add from EC (adding 'activity' suffix, and marking as BROAD/NARROW/RELATED/EXACT as appropriate):

- [ ] all-trans-decaprenyl-diphosphate synthase activity (GO:0097269)
decaprenyl-diphosphate synthase
decaprenyl pyrophosphate synthetase
polyprenylpyrophosphate synthetase
terpenoidallyltransferase
terpenyl pyrophosphate synthetase
trans-prenyltransferase

- [ ] all-trans-nonaprenyl-diphosphate synthase (geranylgeranyl-diphosphate specific) activity (GO:0052924)
solanesyl diphosphate synthase

- [ ] dehydrodolichyl diphosphate synthase activity (GO:0045547)
ditrans,polycis-polyprenyl diphosphate synthase [(2E,6E)-farnesyl diphosphate specific]
=> this is the EC name, so use this as the GO name

- [ ] di-trans,poly-cis-undecaprenyl-diphosphate synthase activity (GO:0008834)
ditrans,polycis-undecaprenyl-diphosphate synthase [(2E,6E)-farnesyl-diphosphate specific]
=> this is the EC name, so use this as the GO name

- [ ] farnesyltranstransferase activity (GO:0004311)
geranylgeranyl diphosphate synthase
=> this is the EC name, so use this as the GO name

- [ ] geranylfarnesyl diphosphate synthase activity (GO:0044687)
FGPP synthase

- [ ] geranylgeranyl-diphosphate geranylgeranyltransferase activity (GO:0016767)
15-cis-phytoene synthase

- [ ] geranyltranstransferase activity (GO:0004337)
(2E,6E)-farnesyl diphosphate synthase
=> this is the EC name, so use this as the GO name

- [ ] hexaprenyl-diphosphate synthase ((2E,6E)-farnesyl-diphosphate specific) activity (GO:0036423)
HexPS

- [ ] octaprenyl pyrophosphate synthase activity (GO:0106350)
all-trans-octaprenyl-diphosphate synthase => this is the EC name, so use this as the GO name
terpenyl pyrophosphate synthetase
trans-heptaprenyltranstransferase
trans-prenyltransferase

- [ ] phosphoglycerol geranylgeranyltransferase activity (GO:0047294)
GGGPS
GGGP synthase

- [ ] squalene synthase [NAD(P)H] activity (GO:0051996)
squalene synthase
farnesyl-diphosphate farnesyltransferase
farnesyltransferase
presqualene-diphosphate synthase
presqualene synthase

- [ ] homogentisate geranylgeranyltransferase activity (GO:0010356)
HGGT

- [ ] homogentisate phytyltransferase activity (GO:0010176)
HPT

- [ ] homogentisate solanesyltransferase activity (GO:0010357)
HST

- [ ] 4-hydroxybenzoate polyprenyltransferase activity (GO:0008412)
4-hydroxybenzoate nonaprenyltransferase

- [ ] geranylgeranylglycerol-phosphate geranylgeranyltransferase activity (GO:0047295)
DGGGP synthase
