### ISSUE TITLE
Obsoletion request: GO:0046350:galactosaminoglycan metabolic process

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#29263]
Please provide as much information as you can:

* **GO term ID and Label**
galactosaminoglycan metabolic process GO:0046350
galactosaminoglycan catabolic process GO:0006028
galactosaminoglycan biosynthetic process GO:0006025

* **Reason for deprecation** Put an x in the appropriate box: 
- [x] The reason for obsoletion is that the term is not clearly defined and ~usage has been inconsistent.~ (not used)
- [x]  The reason for obsoletion is that this term was an unnecessary grouping term.

* **Are there annotations to this term?**
There is no annotation to these terms

* **Any other information**
According to the literature so far there are 3 types, chondroitin sulfate, dermatan sulfate and fucosylated chondroitin sulfate (PMID: 17239763), that would be part of galactosaminoglycans. Their corresponding GO terms are not children of GO:0046350 at the moment. This term seems to be an unnecessary grouping term. There is already a grouping term (mucopolysaccharide metabolic process) for all the GAG that are not bacterial proteoglycan.

Related to ticket #28977 ([Review of glycosaminoglycan metabolic process (GO:0030203) and proteoglycan metabolic process (GO:0006029) branches](https://github.com/geneontology/go-ontology/issues/new?assignees=&labels=obsoletion&projects=&template=term-obsoletion.md&title=Obsoletion+request%3A+%5BGO+ID%3ATerm+label%5D#top))

----
Checklist for ontology editor

***Check term usage and metadata in Protégé***
- [ ] check term usage in the ontology 
- [ ] check internal mappings: RHEA, EC, MetaCyc
- [ ] check subset usage
- [ ] check taxon constraints 

***Check annotations***
- [ ] create Annotation Review spreadsheet 
- * Annotation Review template: https://docs.google.com/spreadsheets/d/1izV3q1jnq_Ybg5MJ53O_b5BCTkGtjl_Fi-cOg3-7eBE/edit#gid=0
- * Instructions: https://wiki.geneontology.org/Annotation_Review_Request
- [ ] create annotation review ticket: https://github.com/geneontology/go-annotation/issues/new?assignees=&labels=annotation+review&template=annotation-review-for-obsoletion.md&title=Review+annotations+to+%5BINSERT+GO+TERM%5D
- [ ] find external mappings (via IEAS), include in obsoletion notice  
- [ ] tag curators in Annotation Review ticket. Responsible annotator for each group: https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

***Notification***
- [ ] create [obsoletion announcement](https://github.com/geneontology/go-announcements/issues/new?assignees=&labels=obsoletion&template=obsoletion-notice.md&title=Obsoletion+notice%3A+%5BGO+ID%3A+term+label%5D)
- [ ] announce to GO friends (go-friends@mailman.stanford.edu)
- [ ] paste the text in the ontology ticket

**Comment by ukemi** [comment]
I haven't used these terms in any models and if I did, I would use the specific types, so I guess yes.

**Comment by pgaudet** [comment]
No annotations, see 
https://github.com/geneontology/go-annotation/issues/5543
