### ISSUE TITLE
NTR: D-alanyl-D-serine ligase activity

### ISSUE THREAD

**Issue by Pauldenny** [geneontology/go-ontology#29277]
* **Suggested term label:**
D-alanyl-D-serine ligase activity

* **Definition (free text)**
Catalysis of the reaction: D-serine + D-alanine + ATP = D-alanyl-D-serine + ADP + phosphate + H(+)

* **Reference, in format PMID:#######**
PMID:8037690

* **Gene product name and ID to be annotated to this term**
Vancomycin C-type resistance protein VanC1
P29753

* **Parent term(s)**
GO:0016875

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?
N/A

* **Cross-references**
* Rhea:27706
EC=6.3.2.35

* Can also provide MetaCyc, KEGG, Wikipedia, and other links.
~BioCyc=MetaCyc:MONOMER-15483~
~KEGG=ag:AAA24786~

These represent genes and not reactions. We  dont really need this, we plan to use RHEA as a source of KEGG and MetaCyc xrefs. 

Thanks, Pascale

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160222
+name: D-alanine-D-serine ligase activity
+namespace: molecular_function
+def: "Catalysis of the reaction: ATP + D-alanine + D-serine = ADP + D-alanyl-D-serine + H+ + phosphate." [EC:6.3.2.35, RHEA:27706]
+xref: EC:6.3.2.35 {source="skos:exactMatch"}
+xref: KEGG_REACTION:R09595
+xref: MetaCyc:RXN-11299
+xref: RHEA:27706 {source="skos:exactMatch"}
+is_a: GO:0016881 ! acid-amino acid ligase activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/29277" xsd:anyURI
+created_by: rynl
+creation_date: 2024-11-22T00:43:34Z
