### ISSUE TITLE
NTR: G-quadruplex unwinding activity

### ISSUE THREAD

**Issue by raymond91125** [geneontology/go-ontology#29309]
Please provide as much information as you can: 

* **Suggested term label:**
* G-quadroplex unwinding activity

* **Definition:**
* Unwinding G-quadruplex structures in nucleic acids, DNA or RNA.

* **Reference, in format PMID:#######**
PMID:26883636
PMID:1324186
PMID:34113828

* **Gene product name and ID to be annotated to this term**
Pif1
DHX36
RPA1

* **Parent term(s)**
GO:0140640 catalytic activity, acting on a nucleic acid

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**
G4 unwinding activity (EXACT)
G-quadruplex resolving activity (EXACT)

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by raymond91125** [comment]
https://github.com/geneontology/go-annotation/issues/5540
@ValWood Is this good? RPA1 seems to break the typical helicase classification.

**Comment by ValWood** [comment]
add definition gloss " A DNA quadruplex (or G-quadruplex), is a specialized structure formed in DNA/RNA when sequences rich in guanine (G) assemble into a unique four-stranded arrangement."

**Comment by ValWood** [comment]
Sounds good. Good point that  it isn't a helix!

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160225
+name: G-quadruplex unwinding activity
+namespace: molecular_function
+def: "Unwinding G-quadruplex structures in nucleic acids. A G-quadruplex is a specialized structure formed in DNA/RNA when sequences rich in guanine (G) assemble into a unique four-stranded arrangement." [PMID:1324186, PMID:26883636, PMID:34113828]
+synonym: "G-quadruplex resolving activity" EXACT []
+synonym: "G4 unwinding activity" EXACT []
+is_a: GO:0140640 ! catalytic activity, acting on a nucleic acid
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/29309" xsd:anyURI
+created_by: rynl
+creation_date: 2024-12-04T00:07:15Z

**Comment by raymond91125** [comment]
https://github.com/geneontology/go-ontology/issues/29153
