### ISSUE TITLE
New QC check- ensure that EC xrefs exist

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#29320]
Hi @balhoff 

See comment here: 
https://github.com/geneontology/go-ontology/issues/27532#issuecomment-2505777752

We had a xref to a non-existing EC term. We should have look up lists to make sure that we only use valid ECs (I think we already have that for RHEA? 

Thanks, Pascale

**Comment by balhoff** [comment]
@pgaudet I implemented the check in #29372. However it found an error that appears to be "on purpose"; EC:1.14.13.253 is not published yet on Expasy (https://github.com/geneontology/go-ontology/issues/29305#issuecomment-2502368329).

Should we make a policy for this?

**Comment by pgaudet** [comment]
Would that be difficult? 

We also have the DNA helicase (if I recall correctly) issue somewhere, that is not yet updated on expasy but is in EC:

**Comment by balhoff** [comment]
Previous discussion: https://github.com/geneontology/go-ontology/issues/27997

**Comment by pgaudet** [comment]
Right, the GO policy is that we use Expasy as the source of truth.

**Comment by pgaudet** [comment]
Hi @balhoff 
I removed the problematic EC. You can go ahead and complete this.
