### ISSUE TITLE
Obsoletion request: '7-alpha-hydroxycholest-4-en-3-one 12-alpha-hydroxylase activity' '5-beta-cholestane-3-alpha,7-alpha-diol 12-alpha-hydroxylase activity'

### ISSUE THREAD

**Issue by pgaudet** [geneontology/go-ontology#29331]
GO:0008397 sterol 12-alpha-hydroxylase activity (EC:1.14.14.139) has 2 children: 
GO:0033779 7-alpha-hydroxycholest-4-en-3-one 12-alpha-hydroxylase activity
GO:0033778 5-beta-cholestane-3-alpha,7-alpha-diol 12-alpha-hydroxylase activity

These correspond to specific reactions in EC:1.14.14.139
Also, this EC corresponds to 3 RHEA reactions (ie, the 3 reactions defined in  EC:1.14.14.139):

- RHEA:46752 | 7α-hydroxycholest-4-en-3-one + reduced [NADPH—hemoprotein reductase] + O2 = 7α,12α-dihydroxycholest-4-en-3-one + oxidized [NADPH—hemoprotein reductase] + H2O + H+  
-  RHEA:65700 | chenodeoxycholate + reduced [NADPH—hemoprotein reductase] + O2 = cholate + oxidized [NADPH—hemoprotein reductase] + H2O + H+ 
-  RHEA:15261 | 5β-cholestane-3α,7α-diol + reduced [NADPH—hemoprotein reductase] + O2 = 5β-cholestane-3α,7α,12α-triol + oxidized [NADPH—hemoprotein reductase] + H2O + H+

The same 4 proteins are annotated to these 3 terms, as these 3 reactions are catalyzed by the same enzyme, CYP8B1 ([Q9UNU6](https://www.uniprot.org/uniprotkb/Q9UNU6/entry) in human)

So with @nnouspikel and Lucila from RHEA we have agreed to merge these into the parent GO:0008397 sterol 12-alpha-hydroxylase activity. 

There are 3 annotations, 2 UniProt, 1 RGD, that will automatically be re-mapped.

**Comment by pgaudet** [comment]
3 TAS annotations  from Reactome @deustp01 

https://amigo.geneontology.org/amigo/term/GO:0033778#display-lineage-tab

**Comment by deustp01** [comment]
> 3 TAS annotations from Reactome

Fixed.
