### ISSUE TITLE
NTR: [bile acid-gated sodium channel activity]

### ISSUE THREAD

**Issue by lbreuza** [geneontology/go-ontology#29336]
Please provide as much information as you can: 

* **Suggested term label:**
bile acid-gated sodium channel activity

* **Definition (free text)**
Enables the transmembrane transfer of sodium by a channel that opens when bile acid has been bound by the channel complex or one of its constituent parts.**

* **Reference, in format PMID:#######**
PMID:22735174

* **Gene product name and ID to be annotated to this term**
ASIC5

* **Parent term(s)**
ligand-gated sodium channel activity

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.
[Rhea:34963]

* **Any other information**

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160228
+name: bile acid-gated sodium channel activity
+namespace: molecular_function
+def: "Enables the transmembrane transfer of a sodium ion by a channel that opens when bile acid has been bound by the channel complex or one of its constituent parts." [PMID:22735174]
+is_a: GO:0005272 ! sodium channel activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/29336" xsd:string
+created_by: rynl
+creation_date: 2024-12-10T18:44:55Z
