### ISSUE TITLE
D A and Oligosaccharyltransferase complex B

### ISSUE THREAD

**Issue by sylvainpoux** [geneontology/go-ontology#29333]
Hi GO,
I would need 2 children terms for the terms for the Oligosaccharyltransferase complex. In vertebrates, there are 2 different complexes, OST-A that mediates glycosylation cotranslationally, and OST-B that mediates mediate modification of skipped glycosylation sites in unfolded proteins both co- and post-translationally.

Thanks

Sylvain

Name: Oligosaccharyltransferase complex A
Definition: A translocon-associated protein complex containing STT3A as catalytic subunit that directs glycosylation of specific substrates cotranslationally.
Child of GO:0008250 oligosaccharyltransferase complex
Synonym: OST-A
Xref
ComplexPortal=CPX-5621; Oligosaccharyltransferase complex A
PMID:31831667
PMID:39509507

Name: Oligosaccharyltransferase complex B
Definition:A protein complex containing STT3B as catalytic subunit that directs glycosylation of specific substrates cotranslationally and post-translationally. It mediate modification of skipped glycosylation sites in unfolded proteins
Child of GO:0008250 oligosaccharyltransferase complex
Synonym: OST-B
Xref
PMID:31831667

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160226
+name: oligosaccharyltransferase complex A
+namespace: cellular_component
+def: "An oligosaccharyltransferase complex that contains STT3A as the catalytic subunit." [PMID:31831667, PMID:39509507]
+synonym: "OST-A" EXACT []
+is_a: GO:0008250 ! oligosaccharyltransferase complex
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/29333" xsd:anyURI
+created_by: rynl
+creation_date: 2024-12-10T00:57:44Z
+
+[Term]
+id: GO:0160227
+name: oligosaccharyltransferase complex B
+namespace: cellular_component
+def: "An oligosaccharyltransferase complex that contains STT3B as the catalytic subunit." [PMID:31831667, PMID:39509507]
+synonym: "OST-B" EXACT []
+is_a: GO:0008250 ! oligosaccharyltransferase complex
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/29333" xsd:anyURI
+created_by: rynl
+creation_date: 2024-12-10T01:06:31Z
+
