### ISSUE TITLE
MetaCyc Xref for GO:0050428 3'-phosphoadenosine 5'-phosphosulfate biosynthetic process

### ISSUE THREAD

**Issue by rozaru** [geneontology/go-ontology#29387]
Would it be possible to add MetaCyc:PWY-5340 as an Xref for GO:0050428 3'-phosphoadenosine 5'-phosphosulfate biosynthetic process?

[MetaCyc:PWY-5340](https://biocyc.org/pathway?orgid=META&id=PWY-5340)

**Comment by raymond91125** [comment]
Moved MetaCyc:PWY-5340 from GO:0050427 3'-phosphoadenosine 5'-phosphosulfate metabolic process to GO:0050428 3'-phosphoadenosine 5'-phosphosulfate biosynthetic process.
