### ISSUE TITLE
Textual definition update: 

### ISSUE THREAD

**Issue by addiehl** [geneontology/go-ontology#29396]
* **Guidelines**
See http://wiki.geneontology.org/index.php/Guidelines_for_GO_textual_definitions#Use_genus-differentia_patterns_for_definitions
More details at https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/

* **GO term ID and label for which you request a definition update**
GO:0050877 nervous system process

* **Current definition (genus-differentia pattern, plus additional information if needed)**
A organ system process carried out by any of the organs or tissues of neurological system.

* **New proposed definition (genus-differentia pattern, plus additional information if needed)**
An organ system process carried out by any of the organs or tissues of the neurological system.

* **Reference(s)**
N/A

* **Additional information**
This fixes two typos in the definition.

**Comment by raymond91125** [comment]
Also fixed several similar typos in the terms directly under GO:0003008 system process. Thanks for the alert.
