### ISSUE TITLE
NTR: phytocytokine activity

### ISSUE THREAD

**Issue by lreiser** [geneontology/go-ontology#29424]
Please provide as much information as you can: 

* **Suggested term label:**

* **Definition (free text)**
 The activity of a  plant specific soluble extracellular gene product  that interacts with a receptor to effect a change in the activity of the receptor to control the response to pathogens, or growth,  or differentiation and effector function of tissues and cells.

* **Reference, in format PMID:#######**
PMID:34806087
PMID:35508659

* **Gene product name and ID to be annotated to this term**
AT1G06135
AT2G31345 
AT2G31335 
AT1G06137

* **Parent term(s)**

is a GO:0048018 receptor ligand activity 
or maybe it is same thing as 
GO:0005125 cytokine activity
and we could add as a synonym

* **Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

* **Synonyms (please specify, EXACT, BROAD, NARROW or RELATED)**

* **Cross-references**
* For enzymes, please provide RHEA and/or EC numbers. 
* Can also provide MetaCyc, KEGG, Wikipedia, and other links.

* **Any other information**

**Comment by pgaudet** [comment]
HI @lreiser 

The definition of cytokine activity is so vague 'The activity of a soluble extracellular gene product that interacts with a receptor to effect a change in the activity of the receptor to control the survival, growth, differentiation and effector function of tissues and cells. ' that I think a synonym would work, if that's OK. 

Unless you have specific children you'd like to add and that would be inconsistent with that ?

**Comment by raymond91125** [comment]
PMID:23072994 states: "I recommend that they should be named as plant cytokines or phytocytokines. This nomenclature will be convenient for study of plant secretory peptides and plant innate immunity.".

**Comment by raymond91125** [comment]
The definition of cytokine activity is phylum agnostic. If and when we decide to separate plant cytokines from animal ones, we then should place them as siblings, children of receptor ligand activity, and add the proper taxon restrictions. For now, perhaps we can get by with the synonym solution.
@lreiser If that's good enough, please close the ticket. Thanks.

**Comment by lreiser** [comment]
I'm fine with adding a synonym so plant people can find this.

**Comment by lreiser** [comment]
closing... pls add synonym. I have already made the annotations to GO:0005125 cytokine activity

**Comment by raymond91125** [comment]
Yes, I have added
GO:0005125 cytokine activity
synonym: "phytocytokine activity" NARROW [PMID:23072994]
