### ISSUE TITLE
NTR: peroxisome-endosome membrane tether activity

### ISSUE THREAD

**Issue by hattrill** [geneontology/go-ontology#29432]
* **Suggested term label:**

peroxisome-endosome membrane tether activity 

* **Definition (free text)**

The binding activity of a molecule that brings together a peroxisome and an ER membrane, either via membrane lipid binding or by interacting with a membrane protein.

* **Reference, in format PMID:#######**

PMID:39271061

* **Gene product name and ID to be annotated to this term**

FBgn0031478 Acbp7

* **Parent term(s)**

GO:0170009 endoplasmic reticulum-organelle membrane tether activity

**Comment by raymond91125** [comment]
Shouldn't it be peroxisome-endoplasmic reticulum membrane tether activity.

**Comment by raymond91125** [comment]
+[Term]
+id: GO:0160229
+name: peroxisome-endoplasmic reticulum membrane tether activity
+namespace: molecular_function
+def: "The binding activity of a molecule that brings together a peroxisome and an ER membrane, either via membrane lipid binding or by interacting with a membrane protein." [PMID:39271061]
+is_a: GO:0170009 ! endoplasmic reticulum-organelle membrane tether activity
+property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/29432" xsd:anyURI
+created_by: rynl
+creation_date: 2024-12-17T01:17:43Z

**Comment by hattrill** [comment]
Thanks @raymond91125. Corrected title and name in request!
