### ISSUE TITLE
Additional children of "histone deacetylase activity, hydrolytic mechanism"

### ISSUE THREAD

**Issue by sjm41** [geneontology/go-ontology#29468]
Add additional parent of "histone deacetylase activity, hydrolytic mechanism" to the following:

histone H4K5 deacetylase activity, hydrolytic mechanism
histone H4K8 deacetylase activity, hydrolytic mechanism
histone H4K12 deacetylase activity, hydrolytic mechanism
histone H4K16 deacetylase activity, hydrolytic mechanism

**Comment by ValWood** [comment]
does the Rhea mapping for parent histone deacetylase activity (GO:0004407)
need to change. that is hydrolytic.

**Comment by sjm41** [comment]
> does the Rhea mapping for parent histone deacetylase activity (GO:0004407)
need to change.

Yes, I think the RHEA:58196 xref on the definition of this term should be removed:

id: GO:0004407
name: histone deacetylase activity
namespace: molecular_function
def: "Removal of an acetyl group from a lysine residue in a histone." [PMID:24691964, PMID:9893272, RHEA:58196]
comment: Histone deacytylase (HDAC) enzymes are divided into four classes: the Class I Rpd3-like proteins (in human: HDAC1, HDAC2, HDAC3, and HDAC8); the Class II Hda1-like proteins (in human: HDAC4, HDAC5, HDAC6, HDAC7, HDAC9, and HDAC10); the Class III Sir2-like proteins (in human: SIRT1, SIRT2, SIRT3, SIRT4, SIRT5, SIRT6, and SIRT7); and the Class IV protein (HDAC11 in human). Except for Class III enzymes, the mechanism is a metal-dependent hydrolysis of the acetylated substrate. The Class III HDACs use NAD+ as a reactant to deacetylate acetyl lysine residues of protein substrates forming nicotinamide, the deacetylated product, and the metabolite 2'-O-acetyl-ADP-ribose. Therefore, Class III are classified as transferases (EC:2) and others are hydrolases (EC:3).
synonym: "histone deacetylase activity (NAD-independent)" EXACT []
xref: EC:2.3.1.- {source="skos:broadMatch"}
xref: EC:3.5.1.- {source="skos:broadMatch"}
is_a: GO:0033558 ! protein lysine deacetylase activity
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/22295" xsd:anyURI


RHEA:58196 = EC:3.5.1.98
N(6)-acetyl-L-lysyl-[histone] + H2O = L-lysyl-[histone] + acetate

So I should add RHEA:58196 as an xref to this term instead:

id: GO:0141221
name: histone deacetylase activity, hydrolytic mechanism
namespace: molecular_function
def: "Catalysis of the reaction: H2O + N6-acetyl-L-lysyl-[histone] = acetate + L-lysyl-[histone]." [PMID:24691964, PMID:28450737]
comment: Histone deacytylase (HDAC) enzymes are divided into four classes: the Class I Rpd3-like proteins (in human: HDAC1, HDAC2, HDAC3, and HDAC8); the Class II Hda1-like proteins (in human: HDAC4, HDAC5, HDAC6, HDAC7, HDAC9, and HDAC10); the Class III Sir2-like proteins (in human: SIRT1, SIRT2, SIRT3, SIRT4, SIRT5, SIRT6, and SIRT7); and the Class IV protein (HDAC11 in human). Except for Class III enzymes, the mechanism is a metal-dependent hydrolysis of the acetylated substrate. The Class III HDACs use NAD+ as a reactant to deacetylate acetyl lysine residues of protein substrates forming nicotinamide, the deacetylated product, and the metabolite 2'-O-acetyl-ADP-ribose. Therefore, Class III are classified as transferases (EC:2) and others are hydrolases (EC:3).
synonym: "histone deacetylase activity" BROAD []
synonym: "histone deacetylase activity, NAD-independent" EXACT []
xref: EC:3.5.1.98 {source="skos:exactMatch"}
xref: MetaCyc:3.5.1.98-RXN
is_a: GO:0004407 ! histone deacetylase activity
is_a: GO:0016811 ! hydrolase activity, acting on carbon-nitrogen (but not peptide) bonds, in linear amides
property_value: term_tracker_item "https://github.com/geneontology/go-ontology/issues/22836" xsd:anyURI
created_by: pg
creation_date: 2024-09-20T12:31:22Z

**Comment by pgaudet** [comment]
Good catch  @sjm41 !
