### ISSUE TITLE
inc parent cytochrome C oxidase activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#3838]
this (GO:0004129) has the parent hydrogen ion transporter activity?

is this correct?

v

also
ubiquinol-cytochrome c-reductase activity

Reported by: ValWood

Original Ticket: "geneontology/ontology-requests/3853":https://sourceforge.net/p/geneontology/ontology-requests/3853

**Comment by ValWood** [comment]
I opened a fresh ticket
