### ISSUE TITLE
lipid metabolic process vs. cellular lipid metabolic process

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#4722]
While adding a new regulation term, we noticed that 'lipid metabolic process' has a child 'cellular lipid metabolic process.'  Also, 'cellular lipid metabolic process' has a child term 'lipid biosynthetic process'.  Even though lipid biosynthesis occurs at a cellular level and there is no corresponding higher level biosynthesis term needed, we should rename this to be 'cellular lipid biosynthetic process' for consistency.

Cellular lipid metabolic process has children such as 'fatty acid metabolic process', 'isoprenoid metabolic process', 'steroid metabolic process', etc.  This is confusing because it is not clear whether all of these are legitimate children of cellular lipid metabolism or whether they should be moved up and be children of lipid metabolism.

We would like to either

(a) move these terms out from under cellular lipid metabolism to be direct children of lipid metabolism

or

(b) add the 'cellular' specificity to each of these existing term names.

Moving the terms would change their meaning implied by the graph and renaming the terms would be consistent with their current representation.  

We would like people to examine their annotations to these terms to determine if they only use them for cellular lipid metabolism or if they have used them for lipid metabolism at a tissue or organismal level.  This information will help us decide which of the above options to pursue.

David and Tanya

Reported by: tberardini

Original Ticket: "geneontology/ontology-requests/4737":https://sourceforge.net/p/geneontology/ontology-requests/4737

**Comment by ValWood** [comment]
close? 9 years ;)

**Comment by ValWood** [comment]
9 years old. Closing. There are probably many terms where we do not need separate cellular and non-cellular terms but thats a whole bigger issue

**Comment by ValWood** [comment]
Reopen if there is a specific action here
