### ISSUE TITLE
Protein Complex terms for the GO.

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#5297]
This is a set of potential protein complex terms to be added to the GO developed by our summer intern, William "Reb: Kornahrens. The following is from the Readme file with the zip file (attached). The zip contains an Excel spreadsheet and the readme.

Data Collection
-final copy of all complexes that might need to be added has two sheets, "All Complexes" and "New Complexes."
- All Complexes contains duplicate entries indicated by red text
-duplicate entries were combined from All Complexes and initial definitions from Wikipedia were added to produce "New Complexes"
-green highlight means it is a complete entry that came from a textbook
- blue text means that GO is missing that part of the term or synonym
- Columns: comments (GO IDs and terms that might be related to the missing term), results (if there is a 1, that means the term is in GO but is missing the blue text of the name)

Reported by: hdrabkin

Original Ticket: "geneontology/ontology-requests/5314":https://sourceforge.net/p/geneontology/ontology-requests/5314

**Comment by pgaudet** [comment]
@vanaukenk @bmeldal 
Does this fit in the GO protein complex working group tasks?

**Comment by bmeldal** [comment]
The attached file got lost in the move from SF. I've reattached it here. But it appears this was just a list of requests, not specific cases that may not fit into GO.
[complexes_SF2049652_MAH_comments.xls.gz](https://github.com/geneontology/go-ontology/files/1402049/complexes_SF2049652_MAH_comments.xls.gz)

**Comment by ValWood** [comment]
Should we close this? Better to add during annotation?

**Comment by bmeldal** [comment]
Has the originally requesting DB still need for the rest of the list? If not I’d close it and let people request terms if and when required. I’m certainly not going to tackle it in the CP my backlog is long enough :)

**Comment by pgaudet** [comment]
@hdrabkin looks like you submitted this - please comment.

**Comment by hdrabkin** [comment]
Not orginally
My original comment stands:
"This is a VERY large and ONGOING project; we make as we need"
I don't find it useful to add complexes if no-one uses. I'm fine fielding specific requests. The requester will deal with whether the complex exists with a PMID, etc.

**Comment by ValWood** [comment]
Close and add as needed?

**Comment by hdrabkin** [comment]
Yes;
