### ISSUE TITLE
GO:0009293 ! transduction

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#5749]
I'm wondering if this should be in GO.  Transduction is certainly a biological process, but it's not clear that it fits GO's notion of the kind of process that should be in the ontology.  There are two kinds of transduction, generalized and specialized.  Generalized transduction is a side product of imperfect specificity of DNA packaging by phage like P1 in E. coli and P22 in Salmonella, which use a headful mechanism.  T4 mutants can do generalized transduction, but only if genes that affect degradation of the host DNA are knocked out \(among other things, if I recall correctly\).  Specialized transduction is the result of a genome rearrangement that replaces a phage segment with a piece of DNA from the host.

In both cases, I'm not sure what genes in either the phage or host one would ever annotate to this GO term. Both happen at some rate naturally, but specialized transduction is the result of a specific kind of mutation.  Although generalized transduction happens normally, genes affecting transduction rates do so by being defective in some other process, such as DNA replication \(a lower phage DNA to host DNA ratio means that transducing particles are a higher fraction of the total\) or packaging.

Reported by: jimhu

Original Ticket: "geneontology/ontology-requests/5767":https://sourceforge.net/p/geneontology/ontology-requests/5767

**Comment by dosumis** [comment]
[go-discuss] Alert: Proposal to obsolete GO:0009293 ! transduction - Impacts no annotations
From:  	davidos@ebi.ac.uk

**Comment by dosumis** [comment]
### objections:

From: Guy Plunkett III 
Re: [go-discuss] Alert: Proposal to obsolete GO:0009293 ! transduction - Impacts no annotations
 
Just throwing this out there as a question: what about GTA (gene transfer agents) such as RcGTA in Rhodobacter capsulatus or VSH-1 in Brachyspira spp.?
I’m not actively doing GO annotation these days, so maybe they are covered by other parts of the ontology.

Dr. Guy Plunkett III
Senior Scientist, Genome Center of Wisconsin
Senior Scientist, DNASTAR, Inc.
http://www.genome.wisc.edu/information/gplunkett.html

---------------------

FROM: Ariane Toussaint

Hi all,
Would it be possible to know more about why Jim asked for obsoletion and about what would replace this to define generalized and specialized transduction? Ariane

Ariane Toussaint
Génétique et Physiologie Bactérienne
Université Libre de Bruxelles 
IBMM-DBM 
12 Rue des Professeurs Jeneer et Brachet 
B 6041 Gosselies, Belgium 
Tel: +3223546290
Cell: +32472700183

**Comment by dosumis** [comment]
_Guy Plunkett wrote:_

> what about GTA (gene transfer agents) such as RcGTA in Rhodobacter capsulatus or VSH-1 in Brachyspira spp.?

@jimhu-tamu: is this reason enough to keep term?
