### ISSUE TITLE
excessive granularity tRNA aminoacylation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#5961]
I have been meaning to submit this SF item for a while \(since we discussed the granularity beneath mitochondrial translation on the reference genome call\).

There are a number of terms which appeared to confuse the issue under here:

GO:0006418 tRNA aminoacylation for protein translation
GO:0006419 alanyl-tRNA aminoacylation
GO:0006420 arginyl-tRNA aminoacylation
GO:0006421 asparaginyl-tRNA aminoacylation
GO:0006422 aspartyl-tRNA aminoacylation
GO:0006423 cysteinyl-tRNA aminoacylation
GO:0006424 glutamyl-tRNA aminoacylation
GO:0006425 glutaminyl-tRNA aminoacylation
etc
and
tRNA aminoacylation for mitochondrial protein translation
with the children
GO:0070143 mitochondrial alanyl-tRNA aminoacylation
GO:0070144 mitochondrial arginyl-tRNA aminoacylation
GO:0070145 mitochondrial asparaginyl-tRNA aminoacylation
GO:0070146 mitochondrial aspartyl-tRNA aminoacylation
GO:0070147 mitochondrial cysteinyl-tRNA aminoacyl
etc.

These terms are an example of excessive granularity. This is not because of the representatation of component specific terms in process. This is because these terms are 'single-step' and are equivalent to the tRNA synthetase function terms
In fact, they are  defined as being catalysed by these enzymes\!

The process of coupling alanine to alanyl-tRNA in a mitochondrion, catalyzed by alanyl-tRNA synthetase. In tRNA aminoacylation, the amino acid is first activated by linkage to AMP and then transferred to either the 2'- or the 3'-hydroxyl group of the 3'-adenosine residue of the tRNA.

I propose that these terms are obsoleted,
with a recommendation that the annotations are made to
the appropriate function term and the appropriate translation process term.

We may need to retain a term for aminoacylation because this appears to occur independently of translation?

Summary
The granularity we are discussing should allow us to represent "component specific processes",
But it is not necessary to represent
"process specific functions" as we have done here.

Reported by: ValWood

Original Ticket: "geneontology/ontology-requests/5979":https://sourceforge.net/p/geneontology/ontology-requests/5979

**Comment by ValWood** [comment]
Let's close this one. I made a not of it in the list of terms we might not need but in the grand scheme of things their existence isn't harmful.
