### ISSUE TITLE
TPV for ncRNA polyadenylation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#6189]
Hi,

I'm looking at the tree for "ncRNA polyadenylation" \(GO:0043629\) and notice that it is under "RNA 3'-end processing". However, polyadenylation \(pA\) of ncRNAs is not necessarily part of producing a mature RNA, but is often the initial step in degradation. I think the tricky bit is that the exosome and TRAMP complex which perform the catabolism of various RNAs in the nucleus are also involved in 3'-end processing of a variety of RNAs, and it may be that the pA step occurs in 3'-end processing too. 

Perhaps moving "RNA polyadenylation" to be a direct child of "RNA metabolic process" would help. Then "ncRNA polyadenlyation" could have it's parentage under "ncRNA 3'-end processing" removed. It already has a child term "ncRNA polyadenylation during polyadenylation-dependent ncRNA catabolic process". If it becomes clear that the pA step is also occurring in ncRNA 3'-end processing, a parallel term for something like "ncRNA polyadenylation during polyadenylation-dependent ncRNA 3'-end processing" could be added.

However, I suspect that it may not be completely true for "mRNA  polyadenylation" to be under "RNA 3'-end processing" either. While it is true that mRNA pA occurs as part of mRNA 3'-end processing, I think that pA of mRNAs, or at least of pre-mRNAs also occurs as part of RNA surveillance and degradation to prevent incorrectly formed mRNAs from leaving the nucleus.

-Karen

Reported by: krchristie

Original Ticket: [geneontology/ontology-requests/6208](https://sourceforge.net/p/geneontology/ontology-requests/6208)

**Comment by dosumis** [comment]
Fixed
