### ISSUE TITLE
possible NTR: catalytic spliceosome grouping term

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#6590]
Hi,

I was wondering about adding a grouping term for a subset of the
spliceosomal complex terms. The Ohi et al. 2002 paper I'm reading
\(citation and PMID below\) describes isolation of complexes complexed
with either TAP-tagged versions of Sp Cdc5 or Sc CEF1, PRP19, SNT309,
PRP46/CWC1, and CWC2. They get large complexes containing U2, U5, and
U6 snRNAs. But they don't do anything that allows me to distinguish
between catalytic step 1 or catalytic step 2 spliceosomes, but it's
clearly more specific than just "spliceosomal complex", which is the
term I would have to use currently. So, I was thinking that it might
be nice to have a grouping term for "catalytic spliceosome". The def
could be something like this:

catalytic spliceosome:
A spliceosomal complex that contains three snRNPs, including U5, as
well as numerous proteins in addition to those found in the associated
snRNPs, bound to a substrate RNA

and then if that's OK, we should also add the specific terms for the
U2-type and the U12-type

Does this sound like a reasonable idea?

-Karen

Ohi MD, Link AJ, Ren L, Jennings JL, McDonald WH, Gould KL \(2002\)
Proteomics analysis reveals stable multiprotein complexes in both
fission and budding yeasts containing Myb-related Cdc5p/Cef1p, novel
pre-mRNA splicing factors, and snRNAs. Mol Cell Biol 22\(7\):2011-24
PMID:11884590

Reported by: krchristie

Original Ticket: [geneontology/ontology-requests/6610](https://sourceforge.net/p/geneontology/ontology-requests/6610)

**Comment by ukemi** [comment]
It looks as though these terms have already been added, but this item was never closed. Closing now. Please reopen if I am mistaken.
