### ISSUE TITLE
mRNA stability/turnover/degradation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#6677]
1\.
regulation of mRNA stability \(add  related synonym mRNA turnover\)?
Any process that modulates the propensity of mRNA molecules to degradation. Includes processes that both stabilize and destabilize mRNAs.

has no relationship to
mRNA catabolic process
The chemical reactions and pathways resulting in the breakdown of mRNA, messenger RNA, which is responsible for carrying the coded genetic 'message', transcribed from DNA, to sites of protein assembly at the ribosomes.

2\. deadenylated and or decapped mRNAs are subject to degradation \(5' 3' degradation by the exosome\), so should  mRNA deadenylation/mRNA decapping  be a child of 
regulation of mRNA stability or  regulation of catabolism?, or should thsi be captured by concurrent annotations?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/6697](https://sourceforge.net/p/geneontology/ontology-requests/6697)

**Comment by ukemi** [comment]
Since it appears that RNA decay is almost always enzyme-mediated, I propose to add a regulates relationship between regulation of ()RNA stability and ()RNA catabolic process.

**Comment by ukemi** [comment]
It seems that every time you regulate the stability, you are in some way regulating whether or not the molecule is catabolized.

**Comment by ValWood** [comment]
I think we can close this?
Val
