### ISSUE TITLE
obsolete 'polyketide synthase activity ; GO:0016218'

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#7340]
Undefined. This is a multimeric complex with many different functional domains. We have the corresponding cellular component terms, and a process term, so I suggest we obsolete this term. It has 37 annotations - mostly ISS.

Reported by: jl242

Original Ticket: [geneontology/ontology-requests/7119](https://sourceforge.net/p/geneontology/ontology-requests/7119)

**Comment by pgaudet** [comment]
Discussing with @marcfeuermann 
Polyketide synthases catalyze multistep reactions, iteratively going from basic building blocks (acyl-CoA) and producing a polyketide (chain of alternating ketone (or reduced forms of a ketone) and methylene groups: (-CO-CH2-); cyclic or not). 

According to the [GO guidelines](https://wiki.geneontology.org/Guidelines_for_new_Molecular_Functions#GO_Molecular_Functions), we dont create individual reactions for multistep reactions, so I will restore this term. 


Thanks, Pascale
