### ISSUE TITLE
SIG_MTG: hormone signaling and hormone receptor signaling

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#7447]
We've got some separate terms in signaling for both hormones and their receptors:

steroid hormone mediated signaling pathway ; GO:0043401
steroid hormone receptor signaling pathway ; GO:0030518

glucocorticoid mediated signaling pathway ; GO:0043402
glucocorticoid receptor signaling pathway ; GO:0042921

Do we really want both? I assume they're to fit in with the grouping terms:

hormone-mediated signaling pathway ; GO:0009755
intracellular receptor-mediated signaling pathway ; GO:0030522

Should they at least be linked? \(at the moment, they're just linked because they share their receptor activity children\)

Becky

Reported by: rebeccafoulger

Original Ticket: [geneontology/ontology-requests/7228](https://sourceforge.net/p/geneontology/ontology-requests/7228)

**Comment by dosumis** [comment]
steroid hormone receptor signaling pathway ; GO:0030518 has been changed to 'intracellular steroid hormone receptor signaling pathway'.  Apparently some steroid hormone receptors are in the PM.  I've manually made the  'mediated by' class a parent of this (would be good to formalise more, but no time).

Ditto corticosteroid term.

Note: children of 'intracellular steroid hormone receptor signaling pathway' need to be reviewed.  Should an intracellular variant be added.  Should def be made clearer?
