### ISSUE TITLE
issues with: DNA-directed RNA polymerase II, holoenzyme

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#7774]
There are issues with this term:

DNA-directed RNA polymerase II, holoenzyme - GO:0016591

1. It is defined with a specific composition. In actual fact, multiple RNAP II holoenzymes have been described in the literature, with varying compositions.

2. The relationships between this term and the component parts, e.g. TFIIA, are all part_of. This is incorrect for many, if not all, of these child complex terms as they are not thought to always be part of an RNAP II holoenzyme. Considering the variability of RNAP II holoenzyme compositions, I'm not sure if has_part relationships would solve the problem either, at least for some of these.

-Karen

Reported by: krchristie

Original Ticket: [geneontology/ontology-requests/7557](https://sourceforge.net/p/geneontology/ontology-requests/7557)

**Comment by ukemi** [comment]
An alternative option would be to simply remove the holoenzyme bit and make the term 'DNA-directed RNA polymerase II complex'.

**Comment by ukemi** [comment]
New definition added:

-def: "Large protein complex composed of the RNA polymerase core complex and a variety of other proteins including transcription factor complexes TFIIA, D, E, F, and H which are required for promoter recognition, and the Mediator subcomplex. Catalyzes the synthesis of eukaryotic pre-mRNA." [GOC:jl, PMID:15196470, Wikipedia:Rna_polymerase_ii]
+def: "A nuclear DNA-directed RNA polymerase complex containing an RNA polymerase II core enzyme as well as additional proteins and transcription factor complexes, that are capable of promoter recognition and transcription initiation from an RNA polymerase II promoter in vivo. These additional components may include general transcription factor complexes TFIIA, TFIID, TFIIE, TFIIF, or TFIIH, as well as Mediator, SWI/SNF, GCN5, or SRBs and confer the ability to recognize promoters." [GOC:jl, GOC:krc, PMID:16858867, Wikipedia:Rna_polymerase_ii]
