### ISSUE TITLE
SIG_MTG: RG: canonical wnt signaling via Hippo pathway

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#7783]
Hi,

NT: negative regulation of canonical Wnt receptor signaling pathway via hippo signaling pathway
Defn: Any process that decreases the rate, frequency, or extent of the Wnt receptor signaling pathway through beta-catenin, by taking part in the Hippo signaling pathway.
is_a: GO:0090090 negative regulation of Wnt receptor signaling pathway through beta-catenin
part_of: GO:0035329 hippo signaling pathway
dbxref: BHF

My attempt at the defn, please feel free to edit!  I have created the new term name based on the 19th July signaling discussion (http://gocwiki.geneontology.org/index.php/July\_19th\_2010\).

Would like to annotate the human Hippo pathway members, LATS1, LATS2, MTS1, MTS2, TAZ from PMID:20412773.

Thanks,
V

Reported by: vkhodiyar

Original Ticket: [geneontology/ontology-requests/7566](https://sourceforge.net/p/geneontology/ontology-requests/7566)

**Comment by pgaudet** [comment]
This is two pathways connected: Hippo pathway regulates Wnt/beta-catenin signaling.
This should be captured by a GO-CAM model. I am closing this.
