### ISSUE TITLE
SIG_MTG: norrin signaling pathway?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#7836]
Hi

PMID: 17955262 describes the activation of the receptor complex FZD4 Q00604/LRP5 O75197 by norrin (NDP) Q00604. From this paper: Despite lack of discernable sequence homology with the Wnt family, Norrin has been identifed as a specific ligand for FZD4 (Xu et al. 2004). ... Through a high affinity interaction specifc to the Cysteine Rich Domain (CRD) of FZD4, Norrin, a small secreted protein with a cysteine-knot motif, is able to activate the
Wnt/beta-catenin pathway when coupled with the co-receptor pair LRP5 and FZD4, resulting in so-called Norrin signaling (Xu et al. 2004).

Should we change the definition of wnt-receptor signaling to include signaling induced by NDP binding, or create a new GO term based on norrin eg norrin signaling pathway?

GO:0016055 Wnt receptor signaling pathway
Current definition The series of molecular signals initiated by binding of a Wnt protein to a frizzled family receptor on the surface of the target cell and ending with a change in cell state

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/7619](https://sourceforge.net/p/geneontology/ontology-requests/7619)

**Comment by pgaudet** [comment]
@vanaukenk 
Did this come up during the work you did for the 2017 signaling meeting ? This relates to beginning and end of the pathway, have you come up with a more precise definition? 

Thanks, Pascale

**Comment by pgaudet** [comment]
@thomaspd @pgaudet 
propose to update the definition to 

GO:0016055 Wnt receptor signaling pathway
Proposed definition: The series of molecular signaling events initiated by activation of a frizzled family receptor on the surface of the target cell and ending with a change in cell state. Ligand binding to the receptor is the activating step. 

Note that the definition of canonical Wnt signaling pathway (which is the pathway activated by NDP) also needs to be updated. 

(this may imply changing definition of other pathways to be consistent?)

Thanks, Pascale

**Comment by vanaukenk** [comment]
@pgaudet @thomaspd 

Ror receptor tyrosine kinases can also act as Wnt receptors to transmit a signal (see PMID: 18848778).  

Here is a proposed, revised definition reflecting that:

GO:0016055 Wnt signaling pathway
Proposed new definition:  The series of molecular signaling events initiated by activation of a Wnt receptor on the surface of a target cell and ending with a change in cell state.  Ligand binding to the receptor is the activating step; Wnt receptors include members of the frizzled and Ror receptor tyrosine kinase transmembrane proteins.

I agree that the definitions of the child terms of GO:0016055 would also need to be reviewed and potentially revised.

Let me know if you think the new def for GO:0016005 is okay.

**Comment by pgaudet** [comment]
Looks good to me. Thanks !

**Comment by RLovering** [comment]
Hi 

I have 2 problems with the proposal:

1. I don't understand why you feel that wnt signaling pathway is a good name for a term that will be associated with NDP. NDP and WNT are not in the same family.

My concern is that if you are expecting people to use the term wnt signaling pathway for ligands that are not wnt related then if people look at the definition they may decide that any pathway that includes the ROR receptor will be a wnt signaling pathway.

So I would prefer either a noggin specific pathway, or a Frizzled pathway, my preference would be to have the Frizzled pathway term and this could also be the parent to the canonical wnt pathway.
GO:0007166 cell surface receptor signaling pathway
> is a child Frizzled signaling pathway ; GO:NEW1
The series of molecular signals initiated by binding of a signal to a frizzled family receptor on the surface of the target cell and ending with a regulation of a downstream cellular process.
>>is a child GO:0060070 canonical Wnt signaling pathway

GO:0016055 Wnt signaling pathway
>is a child GO:0060070 canonical Wnt signaling pathway

Norrin/NDP can then be annotated to GO:NEW1.

2. In addition, a fourth Wnt pathway involves another family of Wnt receptors, the related to tyrosine kinase (Ryks) (reviewed in https://www.ncbi.nlm.nih.gov/pubmed/20004982?dopt=Abstract). Ryks are distinct from the Rors, they also belong to the RTK superfamily https://www.ncbi.nlm.nih.gov/pubmed/20602996?dopt=Abstract. so perhaps this family needs to be included in the new wnt pathway definition
 
Thanks

Ruth

**Comment by vanaukenk** [comment]
@RLovering 
Is the Norrin signaling pathway generally thought to act via the canonical Wnt signaling pathway, i.e. B-catenin stabilization?
If so, would it make sense to create a 'Norrin signaling pathway' term as an is_a child of 'canonical Wnt signaling' and then just revise the definitions of the Wnt and canonical Wnt signaling pathway terms to be inclusive of the various ligands and receptors that are used.
If we can emphasize in the canonical term definition that the key to being 'canonical' is B-catenin stabilization, then regardless of what combination of ligand and receptor is used, the accepted concept of what constitutes a canonical Wnt signaling pathway will be represented correctly in GO.
Here are a few of the papers I was looking at:
https://www.ncbi.nlm.nih.gov/pubmed/27823583
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4223636/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4151216/

**Comment by RLovering** [comment]
Hi Kimberly

certainly the paper I was trying to annotate https://www.ncbi.nlm.nih.gov/pubmed/15035989 suggests the canonical pathway so I think you suggestion would be good.

If Norrin can act via non canonical pathways then I guess a similar new term and ontology can be created to address this

Thanks

Ruth

**Comment by RLovering** [comment]
Hi Kimberly
do you think you could at least add 'Norrin signaling pathway' term as an is_a child of 'canonical Wnt signaling' and then just revise the definitions of the Wnt and canonical Wnt signaling pathway terms to be inclusive of the various ligands and receptors that are used.

**Comment by vanaukenk** [comment]
@RLovering - just reviewing this ticket again today.

**Comment by ValWood** [comment]
It is not clear if there is any outstanding action in this ticket. Please open a new ticket if there is.
