### ISSUE TITLE
SIG_MTG: Calcium-mediated signaling

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#7999]
Hi,

At the GO workshop that Ruth and I held last week, one of the scientists asked for the calcium signaling tree to be looked at:

===================================
Calcium-mediated signaling can be either release of calcium from
intracellular stores or it can be calcium influx from extracellular
sources.

GO:0019932 second-messenger-mediated signaling has GO:0019722
calcium-mediated signaling as a child

GO:0019722 should theoretically also be a child of GO:0070509 calcium ion
import

On its own, GO:0019722 does not discriminate between intracellular and
extracellular sources of the calcium, so it needs to be coupled with
another term higher up the tree to achieve this.
=====================================

Please could someone look into this.

Thanks,
V

Reported by: vkhodiyar

Original Ticket: [geneontology/ontology-requests/7784](https://sourceforge.net/p/geneontology/ontology-requests/7784)

**Comment by dosumis** [comment]
Added some links to calcium import types:

![image](https://cloud.githubusercontent.com/assets/112839/13142225/9def3cfe-d633-11e5-9f38-63304e85ea31.png)

![image](https://cloud.githubusercontent.com/assets/112839/13142262/e35d5794-d633-11e5-992d-7d61146fbb09.png)

As discussed above, we could potentially add some subclasses based on the molecular mechanism of import (e.g. via voltage-gated calcium channel).  We would then have some BP-MF inference issues.

Although have my doubts about these terms as I doubt the transduction really different depending on where the calcium comes from.

**Comment by dosumis** [comment]
related to: #9269
