### ISSUE TITLE
SIG_MTG: receptor signaling proteins

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8123]
I would like to do a clean up (obsolete/rename/redefine several terms) in the 'receptor signaling protein' bit of GO function.

Most of the terms in this node are confusing, undefined and combine subcellular location and molecular function info. In most cases, it's not clear whether it's the receptor or the signaling molecule that has the kinase activity. It contains molecules upstream of the receptor, receptors themselves (in one case), proteins that bind to the receptor to convey the signal, and proteins that lie further downstream of the receptor (eg MAPKs).

Whether the signaling molecule is downstream of a tyrosine kinase or ser/thr kinase receptor should be conveyed by existing GO PROCESS terms.

I think it's still important to capture that the protein is conveying the signal by phosphorylating/dephosphorylating downstream targets, so I'd like to keep some of the terms, but rename them to (hopefully) make it clearer.
------

1/ Redefine 'signal transducer activity ; GO:0004871'
From:
Mediates the transfer of a signal from the outside to the inside of a cell by means other than the introduction of the signal molecule itself into the cell.
(this is an old def taken straight from The Dictionary of Biochemistry and Molecular Biology)
to:
Converts a signal into a form where it can ultimately trigger a change in the state or activity of a cell. A signal is a physical entity or change in state that is used to transfer information in order to trigger a response.
(people were previously uncomfortable with 'converting a signal from one form to another' for cases where the signal was conveyed by transferring a phosphate group on one molecule to a phosphate group on another, since the form of the signal is the same, so I've tried to avoid that text string.)

------

2/ Define: receptor signaling protein activity ; GO:0005057
Conveys a signal from an upstream receptor or intracellular signal transducer, converting the signal into a form where it can ultimately trigger a change in the state or activity of a cell.
Comment: This term is intended for annotation of signal transducers that act directly or indirectly downstream of a receptor. For receptors themselves, consider annotating to the term 'receptor activity ; GO:0004872'. Also consider annotating to the term 'intracellular signal transduction ; GO:0035556'.

NB: I was originally thinking of obsoleting this term, and suggesting annotating to the term: 'intracellular signal transduction ; GO:0035556' , to distinguish the downstream molecules from the receptors themselves but looking at the annotations, I think people want a term to distinguish the receptors from the downstream signaling molecules.

------

3/ Up for obsoletion we have:

receptor signaling protein serine/threonine kinase signaling protein activity ; GO:0005076 (undefined) (0 annotations)
receptor signaling protein tyrosine kinase signaling protein activity ; GO:0008268 (undefined) (3 direct annotations)
receptor signaling protein serine/threonine phosphatase signaling protein activity ; GO:0005081 (undefined) (0 annotations)
receptor signaling protein tyrosine phosphatase signaling protein activity ; GO:0005082 (undefined) (2 annotations)
transmembrane receptor protein serine/threonine kinase signaling protein activity ; GO:0005071 (undefined) (2 direct annotations)
transmembrane receptor protein tyrosine kinase signaling protein activity ; GO:0005066 (undefined) (13 direct annotations)

I'm not even sure what these mean… there's too many instances of 'signaling protein' in one term name.
Annotations can be transferred to'signal transducer activity ; GO:0004871' or 'receptor signaling protein activity ; GO:0005057'

------
4/ Up for renaming, we have:
receptor signaling protein tyrosine kinase activity ; GO:0004716
&gt;
signal transducing protein tyrosine kinase activity
Acts directly or indirectly downstream of a receptor to convert a signal into a form where it can ultimately trigger a change in the state or activity of a cell, by catalysis of the reaction: ATP + protein tyrosine = ADP + protein tyrosine phosphate.

receptor signaling protein tyrosine phosphatase activity ; GO:0004728
&gt;
signal transducing protein tyrosine phosphatase activity

receptor signaling protein serine/threonine kinase activity ; GO:0004702 (undefined)
&gt;
signal transducing protein serine/threonine kinase activity

receptor signaling protein serine/threonine phosphatase activity ; GO:0009400
&gt;
signal transducing protein serine/threonine phosphatase activity

(NB: I know Amelia has plans to split the ser/thr terms into separate functions, but this can be done en-masse once the parent terms are in place).
------

5/
I will move:
transmembrane receptor protein serine/threonine kinase activity ; GO:0004675 from under GO:0004702 as it's a receptor itself.

I will move:
receptor regulator activity ; GO:0030545' out from under 'signal transducer activity', as it creates TPVs for ligands, which are not signal transducers according to GO:0004871 comment.

Thanks,
Becky

Reported by: rebeccafoulger

Original Ticket: [geneontology/ontology-requests/7908](https://sourceforge.net/p/geneontology/ontology-requests/7908)

**Comment by dosumis** [comment]
Receptor signaling protein terms renamed. See.  https://github.com/geneontology/go-ontology/issues/12677  Also fixed issues with incorrect inference of receptors under these terms. Decided not to touch TM receptor terms.  I think it is useful to make clear which activities involve transduction across membranes and which do not.
