### ISSUE TITLE
Relationship between "nodulation" and related terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8201]
"GO:0051819 induction of tumor, nodule, or growth in other organism involved in symbiotic interaction" and "GO:0009877 nodulation" are not related close to one another in the BP ontology, which might be correct, but I believe they require clarification in the form of usage comments.

The nodulation term (GO:0009877) is a child of "GO:0044403 symbiosis, encompassing mutualism through parasitism," whereas GO:0051819 is a child of "GO:0051817 modification of morphology or physiology of other organism involved in symbiotic interaction," which has a part_of relationship to GO:0044403. GO:0009877 is defined as "the formation of nitrogen-fixing root nodules on plant roots" and GO:0051819 is defined as "The process by which an organism causes the formation of an abnormal mass of cells in a second organism, where the two organisms are in a symbiotic interaction." I assume that the two terms are intended to mean different things, but I think that since they are superficially quite similar, comments on how to use them would be very helpful to users.

Would GO:0009877 be used to annotate both plant and symbiont gene products? I assume this is the case, since it mentions "nitrogen-fixing," which is performed by the microbial symbiont, as well as "root nodules on plant roots," which clearly indicates the plant. On the other hand, should "GO:0051819 induction of tumor, nodule, or growth in other organism involved in symbiotic interaction" be used to annotate a gene product from a symbiont only? If this is so, then can we update the comments of these two terms to reflect this?

I also wonder about the definition of "GO:0051819 induction of tumor, nodule, or growth in other organism involved in symbiotic interaction," in particular the phrase "abnormal mass of cells." (I am aware that issues concerning the use of "abnormal" are "normal" are not new to the GO.) I think that nodule formation, like many other structures, is quite a "normal" part of many symbioses, including from the perspective of the plant. Perhaps we could simply cut the word "abnormal" from the definition without needing to take more drastic measures.

Finally, I think adding the synonyms "nodule formation" and "nodule development" (as previously suggested by Jane) might facilitate searching for the proper terms to use. Currently a query with the term "nodule" does not result in the term "nodulation"! Adding some appropriate synonyms that contain the word "nodule" might help guide users to "nodulation" and prevent inappropriate usage of "induction of tumor, nodule, or growth in other organism involved in symbiotic interaction" when this is not the intended term.

Reported by: mchibuco

Original Ticket: [geneontology/ontology-requests/7987](https://sourceforge.net/p/geneontology/ontology-requests/7987)

**Comment by pgaudet** [comment]
Discussed with @thomaspd 

Decisions: 
1. Keep processes for symbiont genes and host genes distinct: 
nodulation = host genes
induction by symbiont of nodulation, tumor,or growth in host = to annotate symbiont genes 

2. Merge: 
'induction of tumor, nodule, or growth in other organism involved in symbiotic interaction'
'induction by symbiont in host of tumor, nodule, or growth'
'induction by symbiont in host of tumor, nodule, or growth containing transformed cells'
as these terms all refer to very similar concepts. 

See also changes in #14807 

Pascale
