### ISSUE TITLE
fixes to development graph

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8327]
In order to proceed with the cross-product work, we need as many of
the core primitive terms in GO to be disjoint. Doing this now would
result in about 200 violations in the development graph. Many of these
are actually mistakes in the ontology, although some are debatable.

In the report below/attached, the first two columns are proposed
disjoint pairs, and the 3rd colum is the violating term.

GO:0009653-anatomical structure morphogenesis   GO:0008283-cell proliferation   GO:0060664-epithelial cell proliferation involved in salivary gland morphogenesis
# OBVIOUS: change to part_of SGM

GO:0009653-anatomical structure morphogenesis   GO:0016477-cell migration   GO:0022007-convergent extension involved in neural plate elongation
GO:0009653-anatomical structure morphogenesis   GO:0016477-cell migration   GO:0060975-cardioblast migration to the midline involved in heart field formation
# OBVIOUS: change to part_of

GO:0009653-anatomical structure morphogenesis   GO:0030154-cell differentiation GO:0060672-epithelial cell morphogenesis involved in placental branching
# OBVIOUS: change to part_of

GO:0048856-anatomical structure development GO:0048646-anatomical structure formation involved in morphogenesis GO:0001410-chlamydospore formation
GO:0048856-anatomical structure development GO:0048646-anatomical structure formation involved in morphogenesis GO:0030437-ascospore formation
# remove isa paths, these are plain formation terms

GO:0048646-anatomical structure formation involved in morphogenesis GO:0071695-anatomical structure maturation  GO:0021691-cerebellar Purkinje cell layer maturation
# I think the 2nd isa should be removed

GO:0048856-anatomical structure development GO:0009653-anatomical structure morphogenesis   GO:0003202-endocardial cushion to mesenchymal transition involved in cardiac skeleton development
GO:0048856-anatomical structure development GO:0009653-anatomical structure morphogenesis   GO:0007470-prothoracic disc morphogenesis
GO:0048856-anatomical structure development GO:0009653-anatomical structure morphogenesis   GO:0035114-imaginal disc-derived appendage morphogenesis
GO:0048856-anatomical structure development GO:0009653-anatomical structure morphogenesis   GO:0042246-tissue regeneration
GO:0048856-anatomical structure development GO:0009653-anatomical structure morphogenesis   GO:0048611-embryonic ectodermal digestive tract development
GO:0048856-anatomical structure development GO:0009653-anatomical structure morphogenesis   GO:0060977-coronary vasculature morphogenesis
GO:0048856-anatomical structure development GO:0009653-anatomical structure morphogenesis   GO:0061113-pancreas morphogenesis
GO:0048856-anatomical structure development GO:0009653-anatomical structure morphogenesis   GO:0061197-fungiform papilla morphogenesis
GO:0048856-anatomical structure development GO:0009653-anatomical structure morphogenesis   GO:0061273-mesonephric distal tubule morphogenesis
GO:0048856-anatomical structure development GO:0009653-anatomical structure morphogenesis   GO:0061301-cerebellum vasculature morphogenesis
# all "morphogenesis" terms should isa morphogenesis only; all development terms should be usa development

GO:0048856-anatomical structure development GO:0030154-cell differentiation GO:0001410-chlamydospore formation
GO:0048856-anatomical structure development GO:0030154-cell differentiation GO:0003334-keratinocyte development
GO:0048856-anatomical structure development GO:0030154-cell differentiation GO:0003398-glial cell differentiation involved in amphid sensory organ development
GO:0048856-anatomical structure development GO:0030154-cell differentiation GO:0030437-ascospore formation
GO:0048856-anatomical structure development GO:0030154-cell differentiation GO:0042692-muscle cell differentiation
# fixes for all these are obvious I think

GO:0009653-anatomical structure morphogenesis   GO:0048589-developmental growth GO:0009826-unidimensional cell growth
GO:0009653-anatomical structure morphogenesis   GO:0048589-developmental growth GO:0042246-tissue regeneration
GO:0009653-anatomical structure morphogenesis   GO:0048589-developmental growth GO:0048673-collateral sprouting of intact axon in response to injury
GO:0009653-anatomical structure morphogenesis   GO:0048589-developmental growth GO:0060516-primary prostatic bud elongation
GO:0009653-anatomical structure morphogenesis   GO:0048589-developmental growth GO:0060523-prostate epithelial cord elongation
# TRICKY

GO:0048646-anatomical structure formation involved in morphogenesis GO:0008283-cell proliferation   GO:0003263-cardioblast proliferation
# I think this should be part_of heart formation

GO:0048646-anatomical structure formation involved in morphogenesis GO:0009653-anatomical structure morphogenesis   GO:0001838-embryonic epithelial tube formation
GO:0048646-anatomical structure formation involved in morphogenesis GO:0009653-anatomical structure morphogenesis   GO:0001843-neural tube closure
GO:0048646-anatomical structure formation involved in morphogenesis GO:0009653-anatomical structure morphogenesis   GO:0060431-primary lung bud formation
GO:0048646-anatomical structure formation involved in morphogenesis GO:0009653-anatomical structure morphogenesis   GO:0060513-prostatic bud formation
GO:0048646-anatomical structure formation involved in morphogenesis GO:0009653-anatomical structure morphogenesis   GO:0060615-mammary gland bud formation
GO:0048646-anatomical structure formation involved in morphogenesis GO:0009653-anatomical structure morphogenesis   GO:0061130-pancreatic bud formation
# I think all gross anatomy "formation" terms should be isa GO:0048646 and part_of ASM

GO:0048646-anatomical structure formation involved in morphogenesis GO:0030154-cell differentiation GO:0030220-platelet formation
GO:0048646-anatomical structure formation involved in morphogenesis GO:0030154-cell differentiation GO:0030435-sporulation resulting in formation of a cellular spore
# not sure about these

GO:0048856-anatomical structure development GO:0048589-developmental growth GO:0042246-tissue regeneration
# this one is also under morphogenesis. the text def says "re-growth". but is the text-def correct, the sense GO uses growth?

GO:0001775-cell activation  GO:0008283-cell proliferation   GO:0046651-lymphocyte proliferation
# tricky; proliferation follows activation

GO:0001775-cell activation  GO:0030154-cell differentiation GO:0002268-follicular dendritic cell differentiation
GO:0001775-cell activation  GO:0030154-cell differentiation GO:0002273-plasmacytoid dendritic cell differentiation
GO:0001775-cell activation  GO:0030154-cell differentiation GO:0030098-lymphocyte differentiation
GO:0001775-cell activation  GO:0030154-cell differentiation GO:0043011-myeloid dendritic cell differentiation
# these are probably fine

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/8114](https://sourceforge.net/p/geneontology/ontology-requests/8114)

**Comment by ukemi** [comment]
@cmungall 

I think that we should swap the 'patterning of blood vessels' name with the 'branching involved in blood vessel morphogenesis' synonym and remove it from pattern specification. From the def it looks like this is described as patterning only because it results in the 'pattern' of branches formed. We should keep the patterning term as a synonym because I think it is used to describe the pattern of branches. Is there anything else on this ticket or have the x-products corrected most of this?

-D

**Comment by RLovering** [comment]
I agree, often the pattern reflects need, although the 'pattern' of the main arteries is probably genetically determined.

Ruth

**Comment by ukemi** [comment]
OK. I cleaned up the blood vessel terms and their regulation by making the terms an is_a branching morphogenesis and making them part of the morphogenesis of the whole structure. I also did the same for the lymph vessel terms.
