### ISSUE TITLE
issues with "DNA replication" terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8402]
A couple issues with "DNA replication" terms were noticed during the
transcription overhaul in the process of proposing to obsolete
"transcription, RNA dependent" because the name and the definition
mean two completely different things, and to replace it with two
terms, one of which already exists in the "DNA replication" branch.

The Proposal for obsoleting "transcription, RNA dependent" is here:
http://wiki.geneontology.org/index.php/Proposal\_for\_obsoleting\_%22transcription,\_RNA\_dependent%22

and parts C and D which commented on DNA replication issues are copied
into this item:

Here are the original parts

C. issues with the term RNA-dependent DNA replication \(GO:0006278\)

This term is defined as "A DNA replication process that uses RNA as a
template for RNA-dependent DNA polymerases \(e.g. reverse
transcriptase\) that synthesize the new strands." and looks like it has
been used extensively for annotating reverse transcriptases.

We think that the definition should be revised to be more general, as
befitting a grouping term with 2 types of RNA-dependent DNA
replication processes under it.

Proposed new def: A DNA replication process that includes the use of
RNA as a template for an RNA-dependent DNA polymerase, e.g. reverse
transcriptase, telomerase.

As existing annotations are not wrong, just not as specific as they
could be, we feel that there is no need to obsolete this
term. Instead, once the new terms are in place, we would suggest
reevaluation of existing annotations to see if they could be moved
down to either the existing telomere maintenance via telomerase term
or the new reverse transcription term.

D. This is a potential SF item, but not something that will be dealt
with as part of the transcription overhaul. The definition of the term
DNA replication \(GO:0006260\) seems specific to DNA-dependent DNA
replication and possibly inappropriate as the parent term of
RNA-dependent DNA replication. In addition, browsing via AmiGO
suggests that DNA replication may suffer from the same annotation
issue as transcription in that it is being used frequently when
DNA-dependent replication is actually meant.

Mike Livstone had these comments:

1\) On Tue, 22 Feb 2011, Michael S. Livstone wrote:

Hi, Karen and David.  Thanks for putting so much hard work into this.
I like how you propose to handle "transcription, RNA-dependent," but
I'd like to address the proposed definition and placement of the new
term "reverse transcription."  You proposed the following:

reverse transcription \(GO:new\)
\- proposed def: "A DNA replication process that uses RNA as the
initial template for synthesis of DNA..."
\- parentage: RNA-dependent DNA replication \(GO:0006278\)

"Replication" refers to making a copy of the original entity.  Reverse
transcription copies the information in an RNA molecule and portrays
it as DNA, but does not actually replicate either one.  I think a
better definition would begin "A DNA biosynthetic process that uses
RNA..."  Similarly, the parental term "RNA-dependent DNA replication"
\(GO:0006278\) is a misnomer and should be "RNA-dependent DNA
synthesis"; its definition should be modified from "A DNA replication
process..." to "A DNA biosynthetic process...", and it should be moved
to become a child of "DNA biosynthetic process" \(GO:0071897\) instead
of "DNA replication" \(GO:0006260\).

I think this should help address issues C and D that you list in the
proposal.

Thanks,
Mike

2\) On Wed, 23 Feb 2011, Michael S. Livstone wrote:

&gt; Spoke a little too quickly.  I'm OK with parts A1 and B, but A2 is
&gt; covered by the comments below.
&gt; -M

Part A2 relates to the creation and definition of the proposed new
term "reverse transcription", so Karen had these further comments:

Getting in a term to represent "reverse transcription" separately from
actual "transcription, RNA-dependent" is key to obsoleting the current
term which munges the two together, so I would prefer to get a term in
sooner, even if the definition isn't perfect, i.e. I would prefer not
to wait for the issues with the definition of "DNA replication" to be
resolved in order to put in a term specifically for "reverse
transcription". I can include revisiting the definition of this term
in the SF item on "DNA replication" issues.

The definition we have proposed for "reverse transcription" is based
on a very recent review \(PMID: 20358252\), so please take a look.

-Karen

Reported by: krchristie

Original Ticket: [geneontology/ontology-requests/8189](https://sourceforge.net/p/geneontology/ontology-requests/8189)

**Comment by ukemi** [comment]
Working with Rebecca, I have renamed the ‘RNA-dependent DNA replication' to be ‘RNA-dependent DNA biosynthetic process' and removed 'viral double stranded DNA replication via reverse transcription’
as a child of ‘RNA metabolic process’ and ‘RNA-dependent DNA biosynthetic process’
keeping its current name? It still has viral DNA genome
replication as a parent. The reverse transcription part of it is still a
child of‘RNA-dependent DNA replication(biosyntehesis)’ and it still has
part DNA-templated viral transcription.

**Comment by ValWood** [comment]
;) great...this was a problem...
