### ISSUE TITLE
new terms for mRNA 3' cleavage factors? need advice

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8430]
Hi,

The Cellular Component ontology may need fleshing out in the area of mRNA cleavage and polyadenylation factors, but I'm not sure how granular we want to get. The existing terms are:

# GO:0005849 mRNA cleavage factor complex [133 gene products]
#                                  [is_a relation] GO:0005847 mRNA cleavage and polyadenylation specificity factor complex [104 gene products]
#                                  [is_a relation] GO:0005848 mRNA cleavage stimulating factor complex [5 gene products] 

PMID: 18158581 is a recent review that describes these complexes in both yeast and mammals. There are many more! See Table 1 of the review. Do we want to add terms for all of these individual complexes? I'm happy to work on the yeast ones but just wanted to check whether this is our strategy, or whether we want to annotate most things to the more general term GO:0005849.

Thanks,
Maria

Reported by: mariacostanzo

Original Ticket: [geneontology/ontology-requests/8217](https://sourceforge.net/p/geneontology/ontology-requests/8217)

**Comment by ValWood** [comment]
I don't think we need to do this   until required for annotation as it would be the only child of  GO:0005847?

**Comment by ValWood** [comment]
If required, new ticket...
