### ISSUE TITLE
transcription related, possible missing parent

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8525]
1\.
GO:0000083 : regulation of transcription involved in G1/S phase of mitotic cell cycle 
is a child of
regulation of gene-specific transcription from RNA polymerase II promoter

but
regulation of transcription involved in G2/M-phase of mitotic cell cycle
is not?

Should it be?
I suppose it is likely that not all G1/S or G2/M  regulation is restricted to pol II transcripts so we may need child terms with different parents

regulation of transcription involved in G2/M-phase of mitotic cell cycle from polymerase II promoter etc?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/8313](https://sourceforge.net/p/geneontology/ontology-requests/8313)

**Comment by ukemi** [comment]
I have moved the terms to the more generic parent as described above. I also modified the logical definitions. Inferred links should work correctly.
