### ISSUE TITLE
synonym: Wolffian duct and Wolffian body add to mesonephros

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8612]
Hi,
Please could you add the following \[exact\] synonyms:
Wolffian duct development to GO:0072177 mesonephric duct development 	
Wolffian duct formation to GO:0072181 mesonephric duct formation 	
Wolffian duct morphogensis to GO:0072180 mesonephric duct morphogenesis 
Wolffian body development to GO:0001823 	mesonephros development 	
Wolffian body morphogensis to GO:0061206 	mesonephros morphogenesis 

Reported by: yafaruque

Original Ticket: [geneontology/ontology-requests/8400](https://sourceforge.net/p/geneontology/ontology-requests/8400)

**Comment by ukemi** [comment]
Looks like the 'Wolffian' synonyms are exact in UBERON, so I have added them to GO as such.
