### ISSUE TITLE
chromosome organization is_a children

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8689]
chromosome organzation is linked through is\_a

histone H4-R3 methylation
histone H3-S10 phosphorylation
histone H4-K8 acetylation

which seems incorrrect. The problem may be at
chromatin modification
The alteration of DNA or protein in chromatin, which may result in changing the chromatin structure.
which implies that it may not alter the chromatin structure...if it does not change the chromatin structure, is it organizing chromosomes?

Val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/8477](https://sourceforge.net/p/geneontology/ontology-requests/8477)

**Comment by paolaroncaglia** [comment]
@ValWood 
This was an old request of yours. Mentioning you as you were no longer receiving notifications after the move to GitHub.

Note for self:
Some time has gone by after my last edits, so I need to check if there was any change in the meantime wrt the following points:

- look at direct annotations to 'chromatin modification' to see if we can move those annotations elsewhere... merge with parent? see below;

- merge chromatin modification into chromatin organization, and carry on the changes suggested by Becky;

- add 'chromatin modification' as a (related) synonym of 'chromatin organization' (actually, it should be done automatically at merge);

- look into merging 'non-covalent chromatin modification' (hasn't been used) into 'chromatin organization'.

**Comment by ValWood** [comment]
It all makes sense to me, except maybe 
merging 'non-covalent chromatin modification' (hasn't been used)

mainly becasue I don't know what this is...is it necessary to merge? Maybe just obsolete?

**Comment by ValWood** [comment]
Hi Paola, do you have any outstanding questions for this ticket before implementation?

Cheers

Val

**Comment by paolaroncaglia** [comment]
Following chat with Val, resolved to obsolete 'non-covalent chromatin modification', and carry on with the other plans as laid out above.

**Comment by paolaroncaglia** [comment]
Obsoletion email sent today.

**Comment by paolaroncaglia** [comment]
Obsoleted GO:0016582 'non-covalent chromatin modification' today.

**Comment by paolaroncaglia** [comment]
Work in progress. Done today:

- progressive alteration of chromatin involved in cell aging ; GO:0001301
changed def and xp to point to chromatin organization rather than modification;
placed directly under chromatin organization;

- moved directly under 'chromatin organization ; GO:0006325':
chromatin remodeling ; GO:0006338
and
covalent chromatin modification ; GO:0016569

- added link: 
macromolecule modification ; GO:0043412
--[isa]covalent chromatin modification ; GO:0016569

**Comment by paolaroncaglia** [comment]
Next: look at 'regulation of chromatin modification' branch.

**Comment by paolaroncaglia** [comment]
Done: descendants of ‘regulation of chromatin modification’: removed links to chromatin modification.

These terms have no direct annotations:
GO:1903308 regulation of chromatin modification
GO:1903309 negative regulation of chromatin modification
GO:1903310 positive regulation of chromatin modification
So I can now merge them with 'reg of chromatin organiz.' and pos + neg children.

**Comment by paolaroncaglia** [comment]
Created as they were missing:

ID: GO:1905268 Label: negative regulation of chromatin organization
ID: GO:1905269 Label: positive regulation of chromatin organization

**Comment by paolaroncaglia** [comment]
Merged reg. terms as above.

**Comment by paolaroncaglia** [comment]
As of today, QuickGO shows 102 manual (all manual, not just experimental) direct annotations to 'chromatin modification', for 97 proteins. We'd need to see if they can find a better (more specific) home than 'chromatin organization'. Otherwise that's where they'll end up when we carry out the next (and last!) step i.e. merge 'chromatin modification' with 'chromatin organization'.

I'll contact the individual databases (by mentioning the relevant curators in this ticket).

**Comment by paolaroncaglia** [comment]
@RLovering 
@ukemi 
@hdrabkin 
@ValWood 
@tberardini 
@mcourtot 

Dear curators,

Based on earlier discussion in this ticket, I’m going to merge 'chromatin modification' into 'chromatin organization’.
There are 102 manual annotations (for 97 proteins) directly to 'chromatin modification’. This is considering all manual annotations (i.e. not just experimental).
Before I merge, could you please review ‘your’ annotations and see if you’d like to rehouse them under a more specific term than 'chromatin organization’.
Otherwise, please be aware that that’s where they’ll end up.   
For your convenience, I am attaching here a spreadsheet containing those direct annotations, as downloaded from QuickGO today. There are separate tabs for the relevant databases.
I plan to do the merge in 2 weeks from today, i.e. on June 30th.

Thanks!
[chromatin_modification_all_manual_16062016.xlsx](https://github.com/geneontology/go-ontology/files/318616/chromatin_modification_all_manual_16062016.xlsx)

**Comment by ValWood** [comment]
done for pombase

**Comment by doughowe** [comment]
In ZFIN, we also have an IEA to chromatin modification from UniProtKW2GO 
KW-0156.  I presume that will be updated in the translation file as well?


Doug Howe, Ph.D.
ZFIN Data Curation Manager
Zebrafish Model Organism Database
5291 University of Oregon
Eugene, OR 97403-5291
(541)346-2355

**Comment by doughowe** [comment]
Done for zebrafish

Doug Howe, Ph.D.
ZFIN Data Curation Manager
Zebrafish Model Organism Database
5291 University of Oregon
Eugene, OR 97403-5291
(541)346-2355

**Comment by srengel** [comment]
done for SGD.  i edited what needed editing, and left the remainder to be rehoused under 'chromatin organization' automatically during the merge.

**Comment by RLovering** [comment]
BHF-UCL completed updates

**Comment by hattrill** [comment]
done for flybase

**Comment by paolaroncaglia** [comment]
Thank you all so far.
Note for self: I'll have to double-check my latest edits (as above) once a current GO release/conflict issue is resolved.

**Comment by paolaroncaglia** [comment]
Hi @doughowe ,
I contacted UniProt about the mapping issue. Thanks for bringing it to attention.

**Comment by pfey03** [comment]
Done for dictyBase; just a few TAF orthologs etc ISS to yeast proteins. If Stacia left them they'ill match, if not, P2G will alert later.

**Comment by sylvainpoux** [comment]
Sorry to interfere in the discussion but I think it is not appropriate to merge these 2 terms

I come from the chromatin field and I can say that reorganization of chromatin is not necessarily associated with modifications. You can perfectly have rearrangements of nucleosomes etc. Displacement of nucleosomes can be the consequence of ATPases, which trigger chromatin reorganization without necessarily modifying it.

In my opinion, it is correct to state that chromatin modification is a child of chromatin organization

By merging these 2 terms you would create more confusion and solve problems and I would look twice before merging these 2 terms

Thanks

Sylvain

**Comment by paolaroncaglia** [comment]
From @pgaudet 

"I concur with Sylvain, in these case we have two very distinct concepts - the chromatin organization can be via bindings, regardless of modifications (or in addition to modifications). 

Maybe the terms need to be reorganized, and the inter ontology links could need fixing, but I am in favor of keeping both concepts."

**Comment by mah11** [comment]
Hi Sylvain & Pascale,

I think the "modification" you describe is covered by GO:0016569 ! covalent chromatin modification, which is and will remain a subclass of chromatin organization. The motivation for the changes proposed here is that non-covalent alterations to chromatin are better described by "organization" than "modification".

**Comment by ukemi** [comment]
At any rate, I have updated the mouse annotations that are not coming in through pipelines to be more specific.

**Comment by ValWood** [comment]
On 17/06/2016 13:27, sylvainpoux wrote:
>
> Sorry to interfere in the discussion but I think it is not appropriate 
> to merge these 2 terms
>
> I come from the chromatin field and I can say that reorganization of 
> chromatin is not necessarily associated with modifications. You can 
> perfectly have rearrangements of nucleosomes etc. Displacement of 
> nucleosomes can be the consequence of ATPases, which trigger chromatin 
> reorganization without necessarily modifying it.
>
> In my opinion, it is correct to state that chromatin modification is a 
> child of chromatin organization
>
> By merging these 2 terms you would create more confusion and solve 
> problems and I would look twice before merging these 2 terms
>
> Thanks
>
> Sylvain
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/geneontology/go-ontology/issues/8689#issuecomment-226756130>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AHBLKAOm1EE5s3xltmvUTuxLhDmGl0xJks5qMpK9gaJpZM4Hhuqn>.
>

Hi Sylvian,

The comment to read for an explanation is Midori's on 31st May. The term 
was defined incorrectly (there was no difference between this term and 
the organization term, as defined), and the covalent chromatin 
modificition  is better defined.

Based on your comment I think it will be confusing for "chromatin 
organization" to have "chromatin modification" as a synonym,. Paola, 
could this synonym be deleted after the merge?

Val


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by paolaroncaglia** [comment]
Yes, no problem.

**Comment by paolaroncaglia** [comment]
Hi @sylvainpoux  and @pgaudet ,

Based on the detailed responses from Midori and Val, could you please confirm that you have no objections to merging the existing ill-defined ‘chromatin modification’ into its parent ‘chromatin organization’? The UniProtKW2GO KW-0156 should probably map to GO:0016569 ! covalent chromatin modification.

Sorry to ask, but your confirmation on this would be helpful so we know if we can go ahead with looking at rehousing the remaining existing annotations.

Many thanks,

Paola

**Comment by ValWood** [comment]
Also,  for consistency it might make sense to call the correctly defined
"covalent chromatin modification" straightforward "chromatin modification" after the merge
(with "covalent chromatin modification" synonym)

**Comment by tberardini** [comment]
I've reviewed and updated the TAIR experimental annotations to 'chromatin organization'.

**Comment by sylvainpoux** [comment]
Hi Paola,

ok, I understand now. Sure you can proceed.

Sorry for the inconvenience

Sylvain

On 20.06.2016 18:47, paolaroncaglia wrote:
>
> Hi @sylvainpoux <https://github.com/sylvainpoux> and @pgaudet 
> <https://github.com/pgaudet> ,
>
> Based on the detailed responses from Midori and Val, could you please 
> confirm that you have no objections to merging the existing 
> ill-defined ‘chromatin modification’ into its parent ‘chromatin 
> organization’? The UniProtKW2GO KW-0156 should probably map to 
> GO:0016569 ! covalent chromatin modification.
>
> Sorry to ask, but your confirmation on this would be helpful so we 
> know if we can go ahead with looking at rehousing the remaining 
> existing annotations.
>
> Many thanks,
>
> Paola
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/geneontology/go-ontology/issues/8689#issuecomment-227199660>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ATEYwT1zQxciSsIn50TAtGgsx5zHgdMxks5qNsQhgaJpZM4Hhuqn>.Web 
> Bug from 
> https://github.com/notifications/beacon/ATEYwZbQUzj14goLbKrBAb70WMq2yNPZks5qNsQhgaJpZM4Hhuqn.gif
>


-- 
Sylvain Poux, PhD
Head of annotation department
Swiss-Prot group
SIB Swiss Institute of Bioinformatics
1, rue Michel Servet
CH-1211 Geneva 4
Switzerland

sylvain.poux@sib.swiss - www.sib.swiss

**Comment by paolaroncaglia** [comment]
Thanks @sylvainpoux ! No inconvenience at all. Thank you, for your feedback.

Paola

**Comment by ValWood** [comment]
Yes we could have made it clearer the rationale for the merge, I had forgotten myself the thread  was so long! Always good to check...

**Comment by paolaroncaglia** [comment]
Tony S. updated the mapping.

**Comment by paolaroncaglia** [comment]
@mcourtot 
@vanaukenk

Just a friendly reminder :-) in case you haven’t had a chance to do this yet, if you’d like to look into UniProt/WormBase manual direct annotations to 'chromatin modification’ and see if they need rehousing please. Otherwise, no worries, the term will be merged into its parent 'chromatin organization’ next week, and the annotations will move too. Thanks!

**Comment by paolaroncaglia** [comment]
Note or self:
Summing up what is left to do for this ticket, as it’s become quite long:
- Double-check my latest edits (because of recent GO release issues).
- On June 30th, merge 'chromatin modification' into 'chromatin organization’.
- Delete the synonym ‘chromatin modification’ from 'chromatin organization’.
- Rename ‘covalent chromatin modification’ as ‘chromatin modification’ (keep ‘covalent chromatin modification’ as an exact synonym).
- Close ticket!

**Comment by paolaroncaglia** [comment]
Note for self: now verified - these went through ok: "Double-check my latest edits (because of recent GO release issues)."

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,

FYI, I may not be able to complete the merge of 'chromatin modification' into 'chromatin organization’ before my summer leave, so in the meantime I added a definition comment to 'chromatin modification':

comment: This term will soon be merged into GO:0006325 'chromatin organization’. Please do not annotate to it. Instead, consider using GO:0006325 'chromatin organization’ or one of its children, especially GO:0016569 ‘covalent chromatin modification’.

**Comment by paolaroncaglia** [comment]
All done.

**Comment by paolaroncaglia** [comment]
Hi @ValWood ,

FYI, wrt your previous request in this same ticket https://github.com/geneontology/go-ontology/issues/8689#issuecomment-227201961, I had to revert name and exact synonym, following an email from @hattrill at FlyBase:

"We’ve also had a problem with the “re-use” of the ‘chromatin modification' name (which I should of spotted as I followed the ticket : https://github.com/geneontology/go-ontology/issues/8689
[-merge 'chromatin modification' into 'chromatin organization’.
-Delete the synonym ‘chromatin modification’ from 'chromatin organization’.
-Rename ‘covalent chromatin modification’ as ‘chromatin modification’ (keep ‘covalent chromatin modification’ as an exact synonym).]
We’re currently trying work around this, but is there any chnace to revert to the old name “covalent chromatin modification”, as it’s not wrong or harmful!"

**Comment by ValWood** [comment]
That shouldn't be a problem as it was to be an exact synonym.  

What is the problem though? It isn't documented in this ticket and it should n't have vcaused any logical issues?

**Comment by hattrill** [comment]
Hi Val,

The problem is more of a timing thing. I don't do the update, our devs in Harvard do it. Our update pipeline is having to cope with the merging of the term and then the re-use of the term name at the same time. I think it could of coped if this had these changes were separate loads, but not in one.

**Comment by ValWood** [comment]
I see, that makes sense. I thought I had overlooked something.
