### ISSUE TITLE
NTR: 3,4-dihydroxybenzoate biosynthetic process

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8788]
Hi, 
please may I request the following new term for UniPathway2GO mapping of UPA00088:

GO:0018874 benzoate metabolic process
\--&lt; GO:NEW 3,4-dihydroxybenzoate biosynthetic process  \[defn: The chemical reactions and pathways resulting in the formation of 3,4-dihydroxybenzoate \(CHEBI:36241\) .

Thanks,
Yasmin

Reported by: yafaruque

Original Ticket: [geneontology/ontology-requests/8576](https://sourceforge.net/p/geneontology/ontology-requests/8576)

**Comment by ukemi** [comment]
Changed all names to be consistent with ChEBI nomenlature.
