### ISSUE TITLE
plasma lipoprotein particle oxidation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8830]
Hi 

GO:0034441 plasma lipoprotein particle oxidation should not have the parent GO:0042161 lipoprotein oxidation. In general the proteins in plasma lipoprotein particles are bound together rather than covalently associated therefore this parent is in appropriate. There are currently no annotations using this term (although I would like to add one).

Instead it should have the parent GO:0034369 plasma lipoprotein particle remodeling
The definition should be changed from:
The modification of a lipoprotein by oxidation of one or more amino acids or the lipid group, occurring in the blood plasma.
to 
The modification of a lipid or protein within a plasma lipoprotein particle by oxidation of the lipid or one or more amino acids.

Thanks

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/8618](https://sourceforge.net/p/geneontology/ontology-requests/8618)

**Comment by pgaudet** [comment]
Hi @RLovering 

This issue looks like it's still valid. However GO:0034441 does not have the label "plasma lipoprotein particle oxidation", but just "plasma lipoprotein oxidation " ('lipoprotein particle is a related synonym.) All annotations to this term if from you group (see below). 

Would it solve your pb if I swapped the term label and synonym and changed the hierarchy as you request ? 

UniProtKB:P06727	Apolipoprotein A-IV	GO:0034445	BHF-UCL	IDA	PMID:16945374	20080719
UniProtKB:Q13093	Platelet-activating factor acetylhydrolase	GO:0034441	BHF-UCL	IDA	PMID:8624782	20110711
UniProtKB:P27169	Serum paraoxonase/arylesterase 1	GO:0034445	BHF-UCL	IDA	PMID:15342686	20090205
UniProtKB:O95445	Apolipoprotein M	GO:0034445	BHF-UCL	IDA	PMID:16682745	20110309
UniProtKB:O95445	Apolipoprotein M	GO:0034445	BHF-UCL	IDA	PMID:22204862	20120531
MGI:MGI:1930124	apolipoprotein M	GO:0034445	BHF-UCL	IDA	MGI:MGI:5427066|PMID:22204862	20120531


Thanks, Pascale

**Comment by RLovering** [comment]
Hi Pascale

please revise as you/I suggest

Ruth

**Comment by pgaudet** [comment]
Changes made: 

OLD name: plasma lipoprotein oxidation
NEW name: plasma lipoprotein particle oxidation
 namespace: biological_process
OLD def: "The modification of a lipoprotein by oxidation of one or more amino acids or the lipid group, occurring in the blood plasma." [GOC:BHF, GOC:mah]
OLD synonym: "plasma lipoprotein particle oxidation" RELATED [GOC:dph]
OLD is_a: GO:0042161 ! lipoprotein oxidation
NEW def: "The modification of a lipid or protein within a plasma lipoprotein particle by oxidation of the lipid or one or more amino acids." [GOC:BHF, GOC:mah]
NEW synonym: "plasma lipoprotein oxidation" RELATED [GOC:dph]
NEW is_a: GO:0034369 ! plasma lipoprotein particle remodeling

Thanks, Pascale
