### ISSUE TITLE
regulation of translation in response to stress

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8850]
I wonder if 
regulation of translation in response to stress and all its children except for
the mitochindrial terms
regulation of mitochondrial translation in response to stress ; GO:0010892 
could be renamed as cytoplasmic  translation regulation terms?

\(and new general terms created\)

I checked all  of the existing annotations \(73\), and they all refer to cytoplasmic translation except for the ones annotated specifically to mitochondrial terms.

Many thanks

Val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/8638](https://sourceforge.net/p/geneontology/ontology-requests/8638)

**Comment by ValWood** [comment]
Can close this one. I wanted terms so that we could ensure  all of our gene products were appropriately annotated to mitochondrial or cytoplasmic translation. This is done so all of the terms I needed are there. Anything else required can be done later.
Val
