### ISSUE TITLE
cranial / craniofacial suture

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8950]
GO:

+is\_a GO:0097094 \! craniofacial suture morphogenesis \*\*\* 
++is\_a GO:0060363 \! cranial suture morphogenesis \*\*\* 
+++is\_a GO:0060364 \! frontal suture morphogenesis \*\*\* 
+++is\_a GO:0060365 \! coronal suture morphogenesis \*\*\* 
+++is\_a GO:0060366 \! lambdoid suture morphogenesis \*\*\* 
+++is\_a GO:0060367 \! sagittal suture morphogenesis \*\*\* 
++is\_a GO:0097095 \! frontonasal suture morphogenesis \*\*\* 
++is\_a GO:0097096 \! facial suture morphogenesis \*\*\* 
+++is\_a GO:0097097 \! nasal suture morphogenesis \*\*\* 

mouse:

+is\_a MA:0001475 \! cranial suture \*\*\* 
++is\_a MA:0002795 \! coronal suture
++is\_a MA:0002796 \! frontal suture
++is\_a MA:0002797 \! lambdoid suture
++is\_a MA:0002798 \! sagittal suture
++is\_a MA:0002973 \! frontonasal suture

I think MA is correct. The cranium includes the whole skull except the mandible. The nasal bones are part of the cranium.

I think the structure of GO is fine but are the names right? Maybe something like "cranial" --&gt; "roof ok skull"..? I don't really know any good references here.

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/8738](https://sourceforge.net/p/geneontology/ontology-requests/8738)

**Comment by ukemi** [comment]
This ticket is out of date. These terms all have equivalence axioms with Uberon.
