### ISSUE TITLE
transcription repressor activity

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#8993]
Please see attached file, 

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/8782](https://sourceforge.net/p/geneontology/ontology-requests/8782)

**Comment by ukemi** [comment]
Hi Ruth,

I am pretty sure that with the renaming of the transcription regulatory MF terms, the distinct transcription repressor terms are now in GO and they are logically defined.

-D
