### ISSUE TITLE
NTR: pos reg of transc inv'd in G1 of cell cycle

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9088]
Hi,
I see that we have these terms for regulation of transcription involved in G1 phase of mitotic cell cycle:

GO:0000114 regulation of transcription involved in G1 phase of mitotic cell cycle
-is\_a GO:0060277 negative regulation of transcription involved in G1 phase of mitotic cell cycle

could we please have the positive regulation term also?

GO:NEW positive regulation of transcription involved in G1 phase of mitotic cell cycle

also with parentage under GO:0045944 positive regulation of transcription from RNA polymerase II promoter.

PMID: 20502685

thanks,
stacia

Reported by: srengel

Original Ticket: [geneontology/ontology-requests/8878](https://sourceforge.net/p/geneontology/ontology-requests/8878)

**Comment by ukemi** [comment]
The original parent terms in this request have been obsoleted. It also looks like the other terms were sorted out previously.  Therefore I am closing this request.
