### ISSUE TITLE
Incorrect parentage: 7532 & other direct children of 6355

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9135]
\(1\) GO:0007532 regulation of transcription, mating-type specific
This term seems to be ALMOST what I need, except that it is a direct child of GO:0006355 \(regulation of transcription, DNA-dependent\). Can we make this term a child of GO:0006366 \(transcription from RNA polymerase II promoter\)? Or create a new term that is a child of regulation of transcription, mating-type specific? 

Also, should GO:0007532 \(regulation of transcription, mating-type specific\) be explicitly related to GO:0009373 \(regulation of transcription by pheromones \)?

\(2\) Fix children of GO:0006355 \(regulation of transcription, DNA-dependent\)
The term that I'm highlighting above isn't the only one that needs to be fixed. Probably the majority of the terms that are direct children of GO:0006355 \(regulation of transcription, DNA-dependent\) should either be polymerase specific, or should have polymerase specific children created.

Thanks,

-Dianna

Reported by: diannafisk

Original Ticket: [geneontology/ontology-requests/8925](https://sourceforge.net/p/geneontology/ontology-requests/8925)

**Comment by ukemi** [comment]
I went through the children and most already had a polymerase II-specific child or I was uncertain of them. I moved one additional term based on its children. Annotations in this branch of the ontology should become automatically categorized as we move towards using Noctua and we specify the polymerase II transcription as the regulation target.
