### ISSUE TITLE
GO:0007020 ! microtubule nucleation logical def

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9187]
looking for a logical def of:

[Term]
id: GO:0007020
name: microtubule nucleation
namespace: biological_process
def: "The 'de novo' formation of a microtubule, in which tubulin heterodimers form metastable oligomeric aggregates, some of which go on to support formation of a complete microtubule. Microtubule nucleation usually occurs from a specific site within a cell." [ISBN:0815316194]
xref: Wikipedia:Microtubule_nucleation
is_a: GO:0000226 ! microtubule cytoskeleton organization

of course, we don't *have* to fit everything into standard templates, we don't want to lose biological subtleties, etc. But it's nice if we can

Does this not fit the assembly template?

"The aggregation, arrangement and bonding together of a cellular component."

Although it's not clear. The defs says it's the 'de-novo' formation of a microtubule, but then goes on to suggest that the aggregation of tubulin is only part of the formation of a complete microtubule.

I'm not madly keen on using weasel-quotes in the genus of a definition
- I like simple plain speak. What's wrong with just saying "the
formation of a microtubule", and have "formation" mean the same thing
across GO?

How should we provide a logical definition for this?

One option:

id: GO:0007020
name: microtubule nucleation
intersection_of: GO:0022607 ! cellular component assembly
intersection_of: has_output GO:0005874 ! microtubule

Another option is something involving 'tubulin' (not yet in PRO)

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/8978](https://sourceforge.net/p/geneontology/ontology-requests/8978)

**Comment by paolaroncaglia** [comment]
No edit has been requested specifically for those terms (anything that was required with related terms has already been dealt with). No specific issue has been highlighted with those terms either, so I’ll close.
