### ISSUE TITLE
merge: GO:0040023 and GO:0007097

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9189]
Based on their text definitions, these should be merged, as the top
def is subsumed by the bottom one:

~~ is_a GO:0040023 ! establishment of nucleus localization [DEF: "The directed movement of the nucleus to a specific location within a cell."]
```   is_a GO:0007097 ! nuclear migration ***  [DEF: "The directed movement of the nucleus."]

Furthermore, the transport rules don't appear to be consistently
applied. For example, "nuclear migration along a microtubule" is
considered a subclass of transport:

~is_a GO:0006810 ! transport
~~is_a GO:0046907 ! intracellular transport
~~~is_a GO:0030705 ! cytoskeleton-dependent intracellular transport
`is\_a GO:0010970 \! microtubule-based transport
`~is_a GO:0072384 ! organelle transport along microtubule
```~~is_a GO:0030473 ! nuclear migration along microtubule *** 

However, "nuclear migration" itself is not a subtype of
transport. This is fairly odd. 

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/8980](https://sourceforge.net/p/geneontology/ontology-requests/8980)

**Comment by pgaudet** [comment]
I don't see why these two terms shouldn't be merged. In fact I would propose a three-way merge with 'GO:0051647 nucleus localization' 

For 'nuclear migration' & 'establishment of nucleus localization': 
'nuclear migration' is the only sub-type of 'establishment of nucleus localization'. The other term we have is cell-type and process specific: establishment of oocyte nucleus localization involved in oocyte dorsal/ventral axis specification

So, unless there are objections I will merge and keep 'nuclear migration' as the main label. 
References: 
PMID:10725321 
PMID:24563363 

I'll look at the annotations for 'nucleus localization' and suggest something.

**Comment by tberardini** [comment]
@pgaudet, sure, please roll into your next set of edits.  Thank you.

**Comment by ValWood** [comment]
The merge is OK, but we have used child terms  like
"microtubule polymerization based movement"
As these terms are directed movement, I think they should probably  be a type of transport?

**Comment by pgaudet** [comment]
Hi @hattrill 

To do this I need to first deal with the children terms. I am trying to understand the difference between ‘establishment of localization to x’ and ‘transport to x’. (looking at issue https://github.com/geneontology/go-ontology/issues/9189) 

GO:0040023 ! establishment of nucleus localization has two children 

- GO:0030722  establishment of oocyte nucleus localization involved in oocyte dorsal/ventral axis specification (3 EXP flybase annotation)
— GO:0007312   oocyte nucleus migration involved in oocyte dorsal/ventral axis specification (about 30 annotations) 

Are these two terms really different ? I tried to look at the annotations for GO:0030722  establishment of… but I couldn’t see that the proteins localize the nucleus, I might have missed something. 

Do you think these can be merged ? 

Thanks, Pascale

**Comment by hattrill** [comment]
Not sure .....they sound equivalent, but I'll have a look either today or tomorrow. 

"I tried to look at the annotations for GO:0030722 establishment of… but I couldn’t see that the proteins localize the nucleus, I might have missed something."

......I assume that it doesn't matter where the proteins localize but the organelle itself.

**Comment by hattrill** [comment]
Can't see any difference in the ways that the terms have been used. Go ahead a merge away!

**Comment by pgaudet** [comment]
Hello again @hattrill 

I just noticed that the parent of these two occyte nuclear migration terms, 'oocyte nucleus localization involved in oocyte dorsal/ventral axis specification' has the same definition as the two other terms. 

 GO:0051663 'oocyte nucleus localization involved in oocyte dorsal/ventral axis specification'

The directed movement of the nucleus to a specific location within a cell during the establishment and maintenance of the dorsal/ventral axis of the oocyte.

-- GO:0030722 'establishment of oocyte nucleus localization involved in oocyte dorsal/ventral axis specification'
The directed movement of the nucleus to a specific location within the cell during the establishment and maintenance of the dorsal/ventral axis of the oocyte. In the insect oocyte, for example, the nucleus is repositioned to a dorso-anterior position. 

---- GO:0007312 	'oocyte nucleus migration involved in oocyte dorsal/ventral axis specification'
The directed movement of the oocyte nucleus within the cell as part of the establishment and maintenance of the dorsal/ventral axis of the oocyte. An example of this is found in Drosophila melanogaster. 

Localization should have meant 'migration' OR 'maintenance of location'. Do you want to check whether these should be moved to the 'nuclear migration...' term? 


There is a small number of FlyBase IMP annotations: 


Q9VEX5 | Asun | PMID:24333177
P42271 | gammaTub37C | PMID:21852952
A0A0B4K682 | jvl | PMID:21989913
A0A0B4K6H8 | jvl | PMID:21989913
A0A0B4K6X6 | jvl | PMID:21989913
Q6NNB4 | jvl | PMID:21989913
Q7KSJ6 | jvl | PMID:21989913
Q960P5 | jvl | PMID:21989913
Q9VFG3 | jvl | PMID:21989913
A1ZBL5 | par-1 | PMID:16753562
A1ZBL7 | par-1 | PMID:16753562
A1ZBL9 | par-1 | PMID:16753562
E1JGM9 | par-1 | PMID:16753562
E1JGN0 | par-1 | PMID:16753562
Q6NPA6 | par-1 | PMID:16753562
Q7K9Q9 | par-1 | PMID:16753562
Q7YU80 | par-1 | PMID:16753562
Q8IGD5 | par-1 | PMID:16753562
Q8MQR8 | par-1 | PMID:16753562
Q95T80 | par-1 | PMID:16753562
Q95U75 | par-1 | PMID:16753562
Q963E5 | par-1 | PMID:16753562
Q963E6 | par-1 | PMID:16753562
Q9V8V7 | par-1 | PMID:16753562
Q9V8V8 | par-1 | PMID:16753562


Thanks, Pascale

**Comment by hattrill** [comment]
Moved most: oocyte nucleus localization involved in oocyte dorsal/ventral axis specification to oocyte nucleus migration involved in oocyte dorsal/ventral axis specification. 
(and dumped par-1 as evidence quite weak)
