### ISSUE TITLE
GO:0007035 ! vacuolar acidification

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9195]
compare:

[Term]
id: GO:0007035
name: vacuolar acidification
namespace: biological_process
def: "Any process that reduces the pH of the vacuole, measured by the concentration of the hydrogen ion." [GOC:jid]
is_a: GO:0051452 ! intracellular pH reduction
intersection_of: GO:0045851 ! pH reduction
intersection_of: occurs_in GO:0005773 ! vacuole

and:

[Term]
id: GO:0007042
name: lysosomal lumen acidification
namespace: biological_process
def: "Any process that reduces the pH of the lysosomal lumen, measured by the concentration of the hydrogen ion." [GOC:jid]
synonym: "lysosome pH reduction" EXACT [GOC:bf, GOC:rph]
is_a: GO:0035751 ! regulation of lysosomal lumen pH
is_a: GO:0051452 ! intracellular pH reduction

one has a logical def, the other doesn't. One is in the regulation hierarchy, the other isn't. One explicitly mentions the lumen, the other doesn't (the acidification is presumably always in the lumen)

on a side note, should the child terms here not have negative and positive synonyms?

GO:0035751 ! regulation of lysosomal lumen pH 
~~~         is_a GO:0007042 ! lysosomal lumen acidification
~~~         is_a GO:0035752 ! lysosomal lumen pH elevation

What should the general template for acidification terms be?

One option is to treat them all as regulation terms.

We have to be careful with occurs_in. It is strong, because

participates_in o occurs_in --&gt; part_of (at some time)

This means that if G actively participates in vacuolar acidification, and this occurs in the vacuole (or even more specifically, the lumen) then G is at some time part of the vacuole (or lumen)

The safest thing might be to remove the acidification logical defs from the main GO, bounce them back to bp_xp_cc, and then put them back in later this year when we consider others of the same broad category. It may be safest to use the pattern of very specification relations here (and reference the lumen specifically)

one more thing

[Term]
id: GO:0035751
name: regulation of lysosomal lumen pH
namespace: biological_process
def: "Any process that modulates the pH of the lysosomal lumen, measured by the concentration of the hydrogen ion." [GOC:rph]
is_a: GO:0051453  ! regulation of intracellular pH
relationship: part_of GO:0007040 ! lysosome organization

How do we infer that this process is part of lysosome organization? The organization def template doesn't really mention anything about acidification. Crudely speaking, it seems more about shuffling around of parts (I guess the protons are parts...)

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/8986](https://sourceforge.net/p/geneontology/ontology-requests/8986)

**Comment by ValWood** [comment]
vacuolar acidification is a slightly weird term,  (phenotype), what do we really mean?

**Comment by vanaukenk** [comment]
Possibly useful reference for this ticket:
http://mmbr.asm.org/content/70/1/177.full.pdf+html

**Comment by ValWood** [comment]
There are probably too many terms around here, but the problems described in this ticket no longer exist:
<img width="469" alt="Screenshot 2022-11-19 at 10 19 57" src="https://user-images.githubusercontent.com/7359272/202846021-b36c391b-2991-4201-a7b4-f04017766ce1.png">
