### ISSUE TITLE
positive regulation of transcription by competitive promoter

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9228]
Please could you create the positive reg and regulation terms similar to:GO:0010944 negative regulation of transcription by competitive promoter binding

ie:
GO:0006355 regulation of transcription, DNA-dependent
&gt;is\_a regulation of transcription by competitive promoter binding
&gt;&gt;is\_a positive regulation of transcription by competitive promoter binding

GO:0045893 positive regulation of transcription, DNA-dependent
&gt;is\_a positive regulation of transcription by competitive promoter binding

Although I think RNA pol II specific \(pos and neg regulation\) terms would be useful too

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/9019](https://sourceforge.net/p/geneontology/ontology-requests/9019)

**Comment by ukemi** [comment]
This ticket is quite out of date and it seems with Noctua we can now capture these mechanisms much more accurately.
