### ISSUE TITLE
NTR: new odorant receptor terms

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9269]
Could we have some terms for PMID:19135896?

They identify a set of proteins that are related to ionotropic glutamate receptors but lack conserved residues in their glutamate binding regions suggesting that they bind a different ligand. Based on the pattern of expression they suspected that some of these could be chemoreceptors so they test with various odorants and find one that responds specifically to ammonia and one to phenylacetaldehyde. I’m not sure how best to represent this...

We already have the term olfactory receptor activity and these are clearly distinct from the G-protein coupled olfactory receptor activity so could we have the new child term odorant-gated ion channel activity that would also have the parent ligand-gated ion channel activity?

Then have new specific odorants listed as children of odorant-gated ion channel activity:

ammonia-gated ion channel activity
phenylacetaldehyde-gated ion channel activity

A coupled of other things I noticed... It seems a bit odd that ionotropic neurotransmitter receptor is a narrow synonym of the quite general term ligand-gated ion channel activity but it not a synonym of  transmitter-gated ion channel activity - something to add maybe? Should ionotropic receptor be added as a synonym to ligand-gated ion channel activity? 

Based on the intro of PMID:10049997 ionotropic glutamate receptor activity also be a child of ligand-gated ion channel activity.

Could we add the synonym chemoreception to detection of chemical stimulus \(we have chemoperception already but no chemoreception\). I notice that 'chemoreceptor' crops up in lots of terms but we don't have a chemoreceptor activity - not sure if that would be a useful grouping terms for odorant receptors and the like? Feel free to ignore that suggestion\!

Thanks Susan

Reported by: stweedie

Original Ticket: [geneontology/ontology-requests/9060](https://sourceforge.net/p/geneontology/ontology-requests/9060)

**Comment by dosumis** [comment]
@paolaroncaglia @rebeccafoulger

Ancient ticket lost on SourceForge.  Now ressurrected on GitHub.  Looks like original classes were added, but the general issue of whether ionotropic receptors belong under signalling.  My instinct is not.  The general issue is relevant to the go_synapse project.  @Pimelorous - any opnion?

**Comment by dosumis** [comment]
> the general issue of whether ionotropic receptors belong under signalling remains.

I think they only do where the transported ion is a second messenger, the obvious case being calcium.
I have fixed this along with a bunch of related issues. Details to follow.

**Comment by dosumis** [comment]
![image](https://cloud.githubusercontent.com/assets/112839/13145174/dcc276c2-d646-11e5-89de-a8b2d9f3db86.png)


Merge:

![image](https://cloud.githubusercontent.com/assets/112839/13145191/0605ccc8-d647-11e5-8d8e-98306bd2f84f.png)

![image](https://cloud.githubusercontent.com/assets/112839/13145227/313551f2-d647-11e5-93a3-f65cb0563e95.png)

![image](https://cloud.githubusercontent.com/assets/112839/13145238/3e13b15c-d647-11e5-9c4e-a72da9f678e3.png)

New terms: 

![image](https://cloud.githubusercontent.com/assets/112839/13145270/677ff424-d647-11e5-817b-bf9421833361.png)

![image](https://cloud.githubusercontent.com/assets/112839/13145276/76f2d020-d647-11e5-98ab-2a3f1c2b4d12.png)
