### ISSUE TITLE
weirdness with GO:0035127 !post-embryonic limb morphogenesis

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9276]
`po GO:0035108 \! limb morphogenesis
`~~is_a GO:0035127 ! post-embryonic limb morphogenesis *** 
`is\_a GO:0007480 \! imaginal disc-derived leg morphogenesis
`~~po GO:0036011 ! imaginal disc-derived leg segmentation
`is\_a GO:0035128 \! post-embryonic forelimb morphogenesis
`~~is_a GO:0035130 ! post-embryonic pectoral fin morphogenesis
`is\_a GO:0035129 \! post-embryonic hindlimb morphogenesis
`~~is_a GO:0035131 ! post-embryonic pelvic fin morphogenesis

[1] imaginal disc-derived legs aren't limbs - I thought we already established limbs were tetrapod limbs?
[2] fins aren't limbs
[3] it's rather an odd grouping class. Post-embryonic appendage morphogenesis would seem unremarkable in a fly, which has post-embryonic stages with a lot of morphogenesis going on. Post-embryonic appendage morphogenesis in a mammal would seem much more unusual. I question the value of "post-embryonic" as a pan-metazoan (eukaryotic?) grouping qualifier.
Also, I am not a developmental biologist, but does post-embryonic limb morphogenesis actually happen much? Even in marsupials which do a lot of post-embryonic development in the womb the limbs are fully formed are they not? Surely this would be restricted to regeerating limbs (e.g lizards), not mice?
[4] There are no annotations to the fin terms. Why request such an odd term if not to annotate to it?
[5] The only other non-fly annotations are two mouse annotations. I skimmed both of these.

One (PMID:17151017) is primarily about hair follicles. The only thing related to limbs is a phenotype for "stiff legs" in the first month. Seems a bit of a leap to go from this to post-embryonic limb morphogenesis.

The other (PMID:17085896) in an IMP from mice with short legs. I suppose morphogenesis could be considered to include determining width/length ratio, I don't know, this still seems like a big jump to me.

And then there are the usual slew of mammalian hangers-on.

This should be reviewed by a developmental biologist. My recommendation would be mass obsoletion 

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/9067](https://sourceforge.net/p/geneontology/ontology-requests/9067)

**Comment by ukemi** [comment]
I just played around in Protege with making logical defs for all of these post_embryonic terms the genus plus the differentia of part_of post-embryonic development. This seems to have worked ok with respect to classification of the post-embryonic bits. The rest of the classification is done by the new logical defs between cell and anatomy and the core development terms. Does it work for everyone if I just make these logical defs and then let the terms sort themselves out based on UBERON?

**Comment by cmungall** [comment]
We should probably have a dedicated ticket for post-embryonic

I feel bad about you manually adding these I thought we had a separate xp file to be merged in but no time to look right now

**Comment by ukemi** [comment]
I think this ticket is now obsolete because we do create logical defs with the Uberon terms.
