### ISSUE TITLE
issues with "copper ion sensor activity"

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9512]
Hi,

Basically, I’d like to make new terms that better represent the MF of the transcriptional regulator, csoR, that the term “copper ion sensor activity” was created to annotate. These new terms will be more consistent with the other copper binding txn factor activity terms I have created. Becky and I have discussed this a little bit offline, but I'll put all the background here.  

Here is a question to consider in reading the information below.

Question: What should be the fate of the existing “copper ion sensor activity” term (GO:0097077)? 

I am not keen on converting 97077 into the term, or even a parent of the term, that I think should actually be used for annotating csoR since the existing def doesn’t talk about the effect on DNA binding or txn at all, so it seems like a violation of our rules to make the term a lot more specific. So, it seems like 97077 should probably be obsoleted. Thoughts?

-Karen

Background:

There is a MF term "copper ion sensor activity" GO0097077: with this definition: Interacting selectively and non-covalently with and responding, e.g. by conformational change, to changes in the cellular level of copper(I) (Cu+).

The 97077 term predates this MF term I created as part of the transcription overhaul: 
Term: copper ion regulated core promoter proximal region sequence-specific DNA binding RNA polymerase II
Def: Interacting selectively and non-covalently with copper(I) (Cu+) ion(s) and responding, e.g. by conformational change, to changes in the cellular level of copper(I) (Cu+), such a way that copper ion binding regulates the activity of the transcription factor, perhaps by regulating the ability to interact selectively and non-covalently with a sequence of DNA that is in cis with and relatively close to a core promoter for RNA polymerase II (RNAP II), or by regulating some other function of the transcription factor, in order to modulate transcription by RNAP II.
GOID: GO: 0001202

When I created the "copper ion regulated ... txn factor activity" I gave it "copper ion sensor activity"  (97077) as an is_a parent because based on the def of "copper ion sensor activity", the term I created (1202) was acting in that manner. However, this threw an error for QuickGO:

From Becky’s email on 29 Nov 2011: 
Tony noticed a slight problem with the following new GO term:

copper ion regulated core promoter proximal region sequence-specific DNA binding RNA polymerase II
transcription factor activity ; GO:0001202

It's blocking a QuickGO update because of a loop (it's reaching 'copper ion binding ; GO:0005507'
via both a HAS_PART, and an is_a relationship):

copper ion binding ; GO:0005507
--[isa]copper ion sensor activity ; GO:0097077
----[isa]copper ion regulated core promoter proximal region sequence-specific DNA binding RNA
polymerase II transcription factor activity ; GO:0001202

copper ion binding ; GO:0005507
--[HASPART]copper ion regulated core promoter proximal region sequence-specific DNA binding RNA
polymerase II transcription factor activity ; GO:0001202

As a short term fix, Becky removed the is_a link between GO:0097077 and GO:0001202 as a quick fix (so QuickGO can update) since the HAS_PARTs are consistent with other TF terms.

Proposal:

Regarding the 97077 “copper ion sensor activity”, it was created from PMID: 19928961 and, in AmiGO, has only been used to annotate one gene product, csoR, from Mycobacterium tuberculosis and also a structure from the same species, likely corresponding  to the same gene product since both annotations use the PMID: 19928961 that was used for the term definition. However, the term “copper ion sensor activity” with its current definition only captures half of the functional information in PMID: 19928961.  The gene csoR is a transcriptional repressor that binds DNA in the apo-copper form, but which loses affinity for DNA when it binds copper.

In contrast, the CUP2 gene from S. cerevisiae requires binding to copper in order to bind DNA. 

Both csoR and CUP2 have very similar functions, so I would like to represent the terms for the MF’s of these genes in a consistent way.

Since the way copper binding is affecting DNA binding is opposite for the two example cases, csoR and CUP2, I would like to indicate in the MF terms whether the copper binding is activating or repressing on DNA binding. Using the high level parent term that already exists (1199) as the base for my examples below, I would like to create terms like new1 and new2 below and corresponding specific children for copper in the bacterial-type and RNAP II branches:

GO:0001199 – metal ion regulated sequence-specific DNA binding RNA polymerase transcription factor activity

GO:new1 – metal ion activated sequence-specific DNA binding RNA polymerase transcription factor activity

GO:new1 – metal ion repressed sequence-specific DNA binding RNA polymerase transcription factor activity

Reported by: krchristie

Original Ticket: [geneontology/ontology-requests/9305](https://sourceforge.net/p/geneontology/ontology-requests/9305)

**Comment by pgaudet** [comment]
I am adding label 'MF refactoring' because I think these types of terms are being discussed. 

Pascale

**Comment by thomaspd** [comment]
In the TF refactoring, we should have a term to cover copper ion-regulated transcription factor activity.  We don't necessarily need detail about which polymerase, etc.  In this way the term can cover all domains of life, as the main point is that it is a compound function where one domain/function activates another domain/function, like nuclear receptors.

**Comment by ValWood** [comment]
@pgaudet I think you can close this as out of date?
