### ISSUE TITLE
def peptide transport

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9543]
based on the def of peptide transport:
peptide transport

this does not exclude "protein transport"
but protein transport is not a parent? should it be?

Definition 	The directed movement of peptides, compounds of two or more amino acids where the alpha carboxyl group of one is bound to the alpha amino group of another, into, out of or within a cell, or between cells, by means of some agent such as a transporter or pore.

\(note to self, check isp4 and others, mappings\)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/9336](https://sourceforge.net/p/geneontology/ontology-requests/9336)

**Comment by ValWood** [comment]
This is the same issue as reported in this more recent ticket
https://github.com/geneontology/go-ontology/issues/12369
(or at least the same fix, its about whether a peptide is_a protein)
