### ISSUE TITLE
ntrs: cellular response to [substance]

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9568]
Hi,

For each of these, we would like a "response to" parent and "cellular response to" child, all with standard defs and relationships \(incl. classifying substances according to ChEBI\). Any that are accepted, we'll use in cross-products for pombe phenotype terms.

name: response to \[x\]
def: "Any process that results in a change in state or activity of a cell or an organism \(in terms of movement, secretion, enzyme production, gene expression, etc.\) as a result of an \[x\] stimulus." \[GOC:curators\]

name: cellular response to \[x\]
def: "Any process that results in a change in state or activity of a cell \(in terms of movement, secretion, enzyme production, gene expression, etc.\) as a result of an \[x\] stimulus." \[GOC:curators\]

for these values of \[x\]:
bismuth \(I've used ChEBI:33301 'bismuth atom' for another phenotype term\)
hydroxyurea
mercaptoethanol
methyl methanesulfonate \(synonym: MMS\)
sodium dodecyl sulfate \(synonym: SDS\)
sorbitol
thiabendazole \(synonym: TBZ\)

If these are OK and you want me to add them, assign to me.

thanks,
m

Reported by: mah11

Original Ticket: [geneontology/ontology-requests/9361](https://sourceforge.net/p/geneontology/ontology-requests/9361)

**Comment by paolaroncaglia** [comment]
Note for self: re-added bismuth ion to imports_requests as there was an error

**Comment by paolaroncaglia** [comment]
Done.
@mah11 thanks for waiting!
Paola
