### ISSUE TITLE
Too much specificity "tRNA transcription"

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9617]
Original query:

Re:
GO:1900446 ; negative regulation of tRNA transcription from RNA polymerase III promoter
biological_process
Any process that stops, prevents or reduces the frequency, rate or extent of tRNA transcription from RNA polymerase III promoter.

From our recent discussion, should  GO:1900446 (above) warrant  a term ? Unless I am mistaken , there is no specific regulator for negatively regulating tRNA transcription which is separable from general negative regulation of transcription from RNA polymerase III.  Is this a case where you would advise users to capture the information in an extension, as it is not a biologically separable process ?

similarly tRNA transcription, is this an process  which can be distinguished from
transcription from RNA polymerase III
or
transcription from mitochondrial prompter?

(there is a possibility my biological knowledge is out of date here and RNA pol III  does have "gene specific" regulators but I have not seen anything.....)

Val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/9410](https://sourceforge.net/p/geneontology/ontology-requests/9410)

**Comment by ukemi** [comment]
@jimhu-tamu can you please have a look at this old ticket and comment? I'm trying to clean up some old GH tickets.

**Comment by jimhu-tamu** [comment]
I don't think we need this level of granularity for bacterial transcription either. There are differences in the regulation of tRNAs and rRNAs from most other mRNAs, but it's the same RNA polymerase in the eubacteria.

**Comment by pgaudet** [comment]
TO DO 
- [] obsolete GO:1900446

**Comment by pgaudet** [comment]
Obsoletion notice sent Nov 23
Dear all, 

The proposal has been made to obsolete 'GO:1900446 negative regulation of tRNA transcription from RNA polymerase III promoter’. The reason for obsoletion is that there is no specific regulator for negatively regulating tRNA transcription which is separable from general negative regulation of transcription from RNA polymerase III. 
There is a single protein annotated to this term by SGD. Comments can be added to the ticket: 

https://github.com/geneontology/go-ontology/issues/9617

We’d like to proceed and obsolete this term on Nov 30, 2017. Unless objections are received by Nov 30, 2017, we will assume that you agree to this change.

Thanks, Pascale

**Comment by pgaudet** [comment]
Hello, 

As a last action for this ticket I propose to merge the following terms into their parent (ie removing terms with 'type x' promoter. This can be captured in the MF. These are  

GO ID | Label | EXP
-- | -- | -- 
GO:0001009 | transcription from RNA polymerase III type   2 promoter | 16
GO:0001020 | RNA polymerase III type 3 promoter transcriptional preinitiation complex   assembly | 1
GO:0001035 | transcription from RNA polymerase III type 3 promoter | 1
GO:0001041 | transcription from a RNA polymerase III hybrid type promoter | 8
GO:0042791 | 5S class rRNA transcription from RNA polymerase III type 1 promoter | 8

I attach a file with the exact annotations to keep as reference. 

Thanks, Pascale

[ticket-9617-RNApolIII_types-BP-annotations.xlsx](https://github.com/geneontology/go-ontology/files/1682223/ticket-9617-RNApolIII_types-BP-annotations.xlsx)

**Comment by pgaudet** [comment]
@krchristie @ValWood @RLovering Is this OK with you ? 

Thanks, Pascale

**Comment by RLovering** [comment]
I agree with the majority of the proposals. However:

GO:0042791 | 5S class rRNA transcription from RNA polymerase III type 1 promoter | 8 | rename '5S class rRNA transcription from RNA polymerase III'
to be consistent with the other renaming should be rename '5S class rRNA transcription **by** RNA polymerase III'
I am not sure about 

GO:0001022 | transcription initiation from RNA polymerase III type 1 promoter | 0 | GO:0006384 transcription initiation from RNA polymerase III promoter 
should this be GO:0006384 transcription initiation **at** RNA polymerase III promoter (need to agree text and apply to all initiation terms if appropriate

Ruth

**Comment by krchristie** [comment]
Like Ruth, I agree with most of the merges and other changes.

Regarding Ruth's two suggestions:

> GO:0042791 | 5S class rRNA transcription from RNA polymerase III type 1 promoter | 8 | rename '5S class rRNA transcription from RNA polymerase III'
to be consistent with the other renaming should be rename '5S class rRNA transcription by RNA polymerase III'

I agree that having dropped the word promoter out of the term name, that it should also now say "**by**" RNA polymerase III, rather than "**from**".

>I am not sure about
> GO:0001022 | transcription initiation from RNA polymerase III type 1 promoter | 0 | GO:0006384 transcription initiation from RNA polymerase III promoter
should this be GO:0006384 transcription initiation at RNA polymerase III promoter (need to agree text and apply to all initiation terms if appropriate

It sounds fine to me to say transcription initiation "**from**" RNA polymerase x promoter, so I don't think this needs to be changed to use the word "**at**" instead. I would use "**at**" if I were talking about the initiation site, but the promoter isn't a specific site, but a region. Personally, I don't think this one is worth the work, especially if "**from**" is already used in other terms.

**Comment by pgaudet** [comment]
OK - all good then. I left the naming of the 'initiation' as is (" transcription initiation from RNA polymerase III promoter" etc). 

I'll merge this one. 

Thanks, Pascale
