### ISSUE TITLE
postsynaptic density protein 95 clustering parent?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9621]
Hi

it seems to makes sense to create a relationship for postsynaptic density protein 95 clustering (GO:0097119) to be part_of postsynaptic density assembly (GO:0097107) since postsynaptic density protein 95 is a component of the postsynaptic density.

The original references articles Sejal used were:

PMID: 10433269
Paper shows that Shank1 (Q9WV48) and GKAP (P97838) result is clustering of PSD-95 in order to form protein complex in the postsynaptic density (figure 4).

PMID: 21424692
Figure 3A and 3B shows that NRXN1(Q9CS84), and NRXN2 (B2RX09) allows for PSD-95 clustering involved in postsynaptic density of glutamatergic postsynaptic assembly.

PMID: 21423165
Shank 3 knockout mouse (Q4ACU6) was used to investigate the regulation of postsynaptic density (PSD) in terms of PSD protein network looking at scaffold proteins (figure 3B) and glutamate receptors subunits (figure 3C). There was a decrease in scaffold protein levels of  SAPAP3, PSD-93 and Homer, figure 3B and a decrease in glutamate receptor subunits of GluR2, NR2A, and NR2B figure 3C, in postsynaptic density of  glutamate synapse.

What do you think?

Thanks

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/9414](https://sourceforge.net/p/geneontology/ontology-requests/9414)

**Comment by ukemi** [comment]
made 'postsynaptic density protein 95 clustering' part of postsynaptic density organization.
