### ISSUE TITLE
query - ribosome biogenesis & subunit export

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9667]
Hi,

At present, 'ribosomal subunit export from nucleus' (GO:0000054) is part_of ribosome biogenesis (GO:0042254). The generic ancestor 'cellular component biogenesis' doesn't have anything about transporting an assembled component, though, so we want to make sure the current arrangement is actually optimal.

Val tell me that a number of genes whose products are involved in RNA processing have mutants with ribosomal subunit export defects, which looks very much like a downstream effect.

So we're wondering whether there's any reason other than those phenotypes for including the export parent (and the bit of the ribosomal subunit biogenesis defs that says "includes transport to the sites of protein synthesis"). If not, it may be best not to have the GO:0000054 part_of GO:0042254 link in the ontology. Can anyone shed any light?

thanks,
Midori & Val

(Val also suggests assigning this to David because he's worked on this part of go before.)

Reported by: mah11

Original Ticket: [geneontology/ontology-requests/9460](https://sourceforge.net/p/geneontology/ontology-requests/9460)

**Comment by ValWood** [comment]
@ukemi  any thoughts?
Val

**Comment by ukemi** [comment]
@hdrabkin you would know more about this than I would.

**Comment by pgaudet** [comment]
Hi @valwood @mah11

According to the wikipedia article cited in the GO term definition (https://en.wikipedia.org/wiki/Ribosome_biogenesis) PMID:26404467 and PMID:17509569 it seems like export can be considered part of the ribosome biogenesis. 

Can this be closed ? 

Thanks, Pascale

**Comment by ValWood** [comment]
OK....I remember older discussions that people call  processing export and assembly biogenesis
