### ISSUE TITLE
start and end of conjugation

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9717]
To define the start and end of conjugation I have consulted 3 fission yeast experts
(professor Olaf Nielsen who has worked on conjugation for &gt;20 years http://www1.bio.ku.dk/english/staff/profile/?id=39875&f=3, Juan Mata  who works on conjugation related fields/ meiosis and Antonia Lock our curator whose PhD was related to pheromone pathway)

Start and end: conjugation 
conjugation starts when cells of opposite mating type begin to physically  move towards each other (shooing)  and ends with the formation of a diploid zygote.

This means that the graph is a bit wrong at the moment.

Processes which are defiantly considered to "part_of" conjugation are 
i) Shmoo formation (movement of cells toward each other and the associated shape changes) 
i) agglutination 
ii) Cell wall degradation involved in conjugation 
ii) karyogamy 
iii) cytogamy 

This means that the graph is a bit wrong at the moment as it includes processes which are clearly upstream (mainly upstream direct regulation) 

All of the following terms are "regulation of conjugation", rather than "involved in" 
1. response to pheromone involved in conjugation with cellular fusion 
This one is a little more complicated as it has a child term 
       GO:0000753 cell morphogenesis involved in conjugation with cellular fusion 
(this includes the narrow synonym Shmooing, we should  have a separate  term for  "shmooingshmoo formation"), which is part of the process. 
2. peptide pheromone export involved in conjugation with cellular fusion 
3. peptide mating pheromone maturation involved in conjugation with cellular fusion 
4. mating pheromone secretion involved in conjugation with cellular fusion 
5. signal transduction involved in conjugation with cellular fusion 

First step is to see if SGD agree with this start and end, or if the S. cerevisiae community see thing differently….

Val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/9510](https://sourceforge.net/p/geneontology/ontology-requests/9510)

**Comment by ukemi** [comment]
I think I agree with Val on this point because the objective of the signaling is to start the conjugation process. I would suggest changing the terms above to:

1. response to pheromone involved in regulation of conjugation with cellular fusion
2. peptide pheromone export involved in regulation of conjugation with cellular fusion
3. peptide mating pheromone maturation involved in regulation of conjugation with cellular fusion
4. mating pheromone secretion involved in regulation of conjugation with cellular fusion
5. signal transduction involved in regulation of conjugation with cellular fusion 

I would move GO:0000753 cell morphogenesis involved in conjugation with cellular fusion to be a part of the conjugation process.

-D

**Comment by ValWood** [comment]
@AntoniaLock How does this sound to you?

**Comment by Antonialock** [comment]
So it sounds like you have agreed to make pheromone signalling and shmooing (cells growing towards each other) part of "regulation" of conjugation.

This means that conjugation itself starts with agglutination? (followed by cell wall breakdown, cytogamy & karyogamy)?

I think this sounds good (though I could probably be swayed in a different direction!)

**Comment by ukemi** [comment]
The process would start with schmooing.
From above:

Processes which are defiantly considered to "part_of" conjugation are
i) Shmoo formation (movement of cells toward each other and the associated shape changes)
i) agglutination
ii) Cell wall degradation involved in conjugation
ii) karyogamy
iii) cytogamy

**Comment by Antonialock** [comment]
yeah, that ;)
