### ISSUE TITLE
update def TFIIIB complex?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9729]
TFIIIB complex is defined as 

A transcription factor complex that is involved in regulating transcription from RNA polymerase III (Pol III) promoters. TFIIIB contains the TATA-binding protein (TBP) and two Pol III-specific proteins, B'' and BRF.

but, I think this involved directly in transcription? not in regulation? (i.e in PolIII assembly at the promoter)

(if so, some  SPKW mappings will need moving)

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/9522](https://sourceforge.net/p/geneontology/ontology-requests/9522)

**Comment by ValWood** [comment]
duplicate of later
https://github.com/geneontology/go-ontology/issues/12985
