### ISSUE TITLE
part_of child terms for regulation of action potential

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9737]
Hi David

sorry, but do you think GO:0086070 SA node cardiomyocyte to atrial cardiomyocyte communication should be a part\_of child to GO:0086014 regulation of atrial cardiac muscle cell action potential
although GO:0086026 atrial cardiomyocyte to AV node cell signaling is a parent of GO:0086014 regulation of atrial cardiac muscle cell action potential so potentially this would lead to \(this is just a rough idea of how this would snowball, there would be a lot more terms involved\):

GO:0086068	Purkinje myocyte to ventricular cardiac muscle cell communication
&gt;part\_of regulation of Purkinje myocyte action potential
&gt;&gt;part of GO:0086069	bundle of His cardiac muscle cell to Purkinje myocyte communication
&gt;&gt;&gt;part\_of regulation of bundle of His cell action potential
&gt;&gt;&gt;&gt;part of GO:0086067	AV node cell to bundle of His cell communication
&gt;&gt;&gt;&gt;&gt;part\_of regulation of AV node cell action potential
&gt;&gt;&gt;&gt;&gt;&gt;part of GO:0086026 atrial cardiomyocyte to AV node cell signaling 
&gt;&gt;&gt;&gt;&gt;&gt;&gt;part\_of GO:0086014 regulation of atrial cardiac muscle cell action potential
&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;part of GO:0086070 SA node cardiomyocyte to atrial cardiomyocyte communication
&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;part of GO:0086018 SA node cardiomyocyte to atrial cardiomyocyte signalling
&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;part of GO:0086015 	regulation of SA node cardiac muscle cell action potential 

The last 3 terms above exist already in this relationship

Anyway I guess the key being that if you regulate the SA node to atrial cardiomyocyte communication then you will regulate Purkinje myocyte to ventricular cardiac muscle cell communication

Ruth

Ruth

Reported by: RLovering

Original Ticket: [geneontology/ontology-requests/9530](https://sourceforge.net/p/geneontology/ontology-requests/9530)

**Comment by ukemi** [comment]
Closing this because this type of stringing of annotations will be better suited once we are able to use Noctua. For the reasons of recursion stated above, I think it would be a bad idea to use this quick fix in the ontology.
