### ISSUE TITLE
TPV queuosine biosynthetic process

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9776]
This seems to be a true path violations as something cannot be both 
macromolecule metabolic process and small molecule biosynthetic process.

This is a tRNA modifications which is synthesised in tRNA by swapping a nucleotide 
but the problem occurs because there isn't an easy way to distinguish free residues from those in macromolecules in GO

The solution may depend if the queuosine  molecules exist as free molecules in some organisms?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/9569](https://sourceforge.net/p/geneontology/ontology-requests/9569)

**Comment by ValWood** [comment]
There is still a "true path violation" here.
GO:0008616 queuosine biosynthetic process
is still both a small molecule and a mcormolecule biosynthetic process.

Oddly I though this one got fixed at some point via another ticket...I'll try to track that one down.

**Comment by ValWood** [comment]
Probably best to  address with
https://github.com/geneontology/go-ontology/issues/11905

**Comment by ValWood** [comment]
is no longer 
macromolecule biosynthetic process
so this one fixed
