### ISSUE TITLE
mRNA transcription from RNA polymerase II promoter

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9827]
Hi David,

mRNA transcription from RNA polymerase II promoter

it isn't a different process from
transcription from RNA polymerase II promoter

similar to the  issue for RNA pol III:
https://sourceforge.net/tracker/index.php?func=detail&aid=3523223&group\_id=36855&atid=440764

Val

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/9620](https://sourceforge.net/p/geneontology/ontology-requests/9620)

**Comment by ukemi** [comment]
Since we now have several terms differentiating the types of RNA that are being transcribed (pri-miRNA, snoRNA, etc), I think we need to consider the mRNA term more specific than the parent.
