### ISSUE TITLE
hypoblast - zebrafish vs mammals

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9883]
GO has a fairly standard mammalian definition of hypoblast:

GO:0090008 ! hypoblast development [DEF: "The process whose specific outcome is the progression of the hypoblast over time, from its formation to the mature structure. The hypoblast is a tissue formed from the inner cell mass that lies beneath the epiblast and gives rise to extraembryonic endoderm."]

I have open Gilbert Fig 11.32, the GO text def is consistent with the lineage diagram here

There is currently one annotation - oep, a zebrafish gene

However, in zebrafish, the term "hypoblast" has a different definition

id: ZFA:0000117
name: hypoblast
def: "The inner of the two layers of the blastoderm that forms during gastrulation and give rise to the definitive mesoderm and endoderm." [ZFIN:ZDB-PUB-961014-576]
synonym: "mesendoderm" EXACT [ZFIN:ZDB-PUB-961014-576]

The lineage is different, even though it may be analagous in terms of spatial configuration.

The lineage actually fits the embedded GO term here:

GO:0048382 ! mesendoderm development [DEF: "The process whose specific outcome is the progression of the mesendoderm over time, from its formation to the mature structure. In animal embryos, mesendoderm development gives rise to both mesoderm and endoderm tissues."]
http://www.ncbi.nlm.nih.gov/pubmed/14499649

VHOG has a status "uncertain" homology association between XAO:mesendoderm and mammalian hypoblast

Representing early development in a multi-species way is a challenge!

Reported by: cmungall

Original Ticket: [geneontology/ontology-requests/9676](https://sourceforge.net/p/geneontology/ontology-requests/9676)

**Comment by cmungall** [comment]
Revisiting. Thinking of this for uberon:

mesendoderm: region of tissue that gives rise to both endoderm and mesoderm

I don't think this is a germ layer - pre germ layer?

Then we can let figure out all the different species-specific hypoblast definitions, see where they fall out as @cerivs suggests

**Comment by pgaudet** [comment]
@cerivs @cmungall Is there an action here ? Otherwise I will close this.

**Comment by cerivs** [comment]
Can we change the def to 

The process whose specific outcome  is the progression of the hypoblast over time, from its formation to the  mature structure. The hypoblast is a tissue formed from the inner cell  mass that lies beneath the epiblast.
The portion of the definition defining the fate of the hypoblast is wrong for zebrafish.  If the definition isn't changed we need a new hyboblast term for zebrafish with the correct developmental outcome.
https://zfin.org/zf_info/zfbook/stages/figs/fig13.html
