### ISSUE TITLE
new terms for Staph IDO

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9895]
Here are some new GO term suggestions related to Staphylococcus aureus virulence factors:

GO Term: bone sialoprotein-binding
Ontology: Biological Process
def: Interacting selectively and non-covalently with a bone sialoprotein, an extracellular matrix glycoprotein found on the surface of bones and dentin.
synonym: "BSP-binding" EXACT \[\]
Parent: GO:0050840 \! extracellular matrix binding
Reference: PMCID:PMC1220796

GO Term: catalase secretion
Ontology: Biological Process
def: The regulated release of catalase from a cell or group of cells. The enzyme catalase converts hydrogen peroxide to water and oxygen.
Parent: GO:0009306 \! protein secretion
Reference: PMID:14745498

GO Term: chemotaxis inhibitory protein secretion
Ontology: Biological Process
def: The regulated release of chemotaxis inhibitory protein \(CHIP\) from a cell or group of cells. CHIP is capable of binding to monocytes and neutrophils, inhibiting chemotaxis and activation through the fMLP and C5a receptors found on these cells.
Synonym: “CHIP secretion” EXACT \[\]
Parent: GO:0009306 \! protein secretion
Reference: PMID:14993252, PMID:16882032

GO Term: coagulase secretion
Ontology: Biological Process
def: The regulated release of coagulase from a microorganism, such as Staphylococcus aureus and Yersinia pestis. The enzyme coagulase is produced by bacteria, such as Staphylococcus aureus and Yersinia pestis, and is capable of binding to and activating prothrombin, which converts fibrinogen to fibrin, thereby promoting blood clotting.  Coagulase may be bound to the cell surface or released from the cell.
Parent: GO:0009306 \! protein secretion
Reference: PMCID:PMC3388267

GO Term: Panton-Valentine leukocidin secretion
Ontology: Biological Process
def: The regulated release of Panton-Valentine Leukocidin \(PVL\) from certain strains of bacteria, such as Staphylococcus aureus. PVL is a non-hemolytic toxin, which kills segmented neutrophils and macrophages.
Synonym: “PVL secretion” EXACT \[\]
Parent: GO:0009306 \! protein secretion
Reference: PMCID: PMC88931

GO Term: staphylococcal complement inhibitor secretion
Ontology: Biological Process
def: The regulated release of Staphylococcal complement inhibitor \(SCIN\) from certain strains of Staphylococcus aureus. SCIN protects C3 convertase from decay, thus, inhibiting all complement pathways.  This results in a decrease in opsonization and phagocytosis of bacterial cells, and a reduced chemotaxis response towards the site of bacterial infection.
Synonym: “SCIN secretion” EXACT \[\]
Parent: GO:0009306 \! protein secretion
Reference: PMID:16086019; PMID:16882032

GO Term: staphylokinase secretion
Ontology: Biological Process
def: The regulated release of staphylokinase from certain strains of Staphylococcus aureus. Staphylokinase is a bacterial enzyme, which is capable of binding to and inactivating alpha-defensins. Addtionally, staphylokinase can bind to and activate plasminogen.
Parent: GO:0009306 \! protein secretion
Reference: PMID:16111912

GO Term: toxic shock syndrome toxin-1 secretion
Ontology: Biological Process
def: The regulated release of the enterotoxin, toxic shock syndrome toxin-1 \(TSST-1\), from certain strains of Staphylococcus aureus. TSST-1 is a bacterial superantigen, which induces the release of large amounts of interleukin-1, interleukin-2, and tumor necrosis factor by T-lymphocytes, causing toxic shock syndrome.
Synonym: “TSST-1 secretion” EXACT \[\]
Synonym: “enterotoxin F secretion” EXACT \[\]
Parent: GO:0009306 \! protein secretion
Reference: PMCID: PMC88931

GO Term: von willebrand factor binding protein secretion
Ontology: Biological Process
def: The regulated release of von Willebrand Factor Binding Protein from certain strains of bacteria, such as Staphylococcus aureus. von Willebrand Factor Binding Protein is capable of binding to prothrombin and fibrinogen to promote blood clotting.
Synonym: "vWbp secretion" EXACT \[\]	
Synonym: "von Willebrand factor-binding protein secretion" EXACT \[\]
Parent: GO:0009306 \! protein secretion
Reference: PMCID:PMC3388267

Reported by: ddougall

Original Ticket: [geneontology/ontology-requests/9689](https://sourceforge.net/p/geneontology/ontology-requests/9689)

**Comment by paolaroncaglia** [comment]
Closing as out of date.
