### ISSUE TITLE
DNA replication initiation - improve def

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9913]
Hello lucky GO people,

In SF 3549889, we realized that the start and end of initiation could do to be much more precisely specified in the 'DNA replication initiation' (GO:0006270) def.

It's fairly straightforward in bacteria, but unfortunately for eukaryotes it may not be easy to pin down the start. (This is all based on skimming through papers from a 'dna replication initiation review' PubMed search and a small amount of googling.)

In bacteria, initiation starts when the initiator protein (DnaA; most or all species use this gene name) binds to the origin and melts the DNA. DnaA then loads a helicase, the helicase melts origin DNA, DNA polymerase and some other proteins come along, and Bob's your uncle. Initiation includes primer synthesis* and ends when DNA polymerases start to extend the primers (i.e. when elongation starts).

*but not the synthesis of Okazaki fragment primers; that's lagging strand elongation

For euks, it's well established that these these steps have to happen:

\- ORC binds to replication origins;

\- MCM proteins and a few others, e.g. Cdt1 & Cdc6 (budding yeast names) join ORC at origins to form the prereplicative complex (pre-RC);

\- Yet more proteins (the GINS complex and Cdc45 in fission yeast) join the pre-RC to form the DNA replication preinitiation complex (pre-IC) -- a name that may or may not be accurate; also, Cdt1 & Cdc6 leave;

\- Protein phosphorylation happens;

\- The helicase (MCM hexamer) melts DNA;

\- DNA polymerases and other proteins join the fun and the first primers are synthesized.

The exact order of some of the protein phosphorylation events with respect to some of the complex assembly events isn't well established.

Some sources seem to say that initiation starts with pre-IC assembly (despite its name); others count pre-RC formation as an early initiation event; still others (tho apparently not many) say DNA melting is the beginning of initiation proper.

Most, however, are woollier and don't explicitly peg any of the steps as Step 1 of Initiation. As a result, the only things I'm really confident of are that (a) ORC binding is not the first step -- ORC is bound to origins throughout the cell cycle -- and (b) initiation doesn't start any later than DNA melting.

I think the end of initiation is basically the same as in bacteria, i.e. primer extension/beginning of elongation.

Sorry for all the parentheticals and weasel words, but I'm having trouble extracting anything firmer. There's a lot of consistency regarding what events happen, and to the effect that all of the above events are somehow very relevant to initiation, but not about precisely where the line between 'precedes, and required for, initiation' and 'part of initiation' belongs.

Oh, and just to make it even more complicated, the connections with S phase of the cell cycle may have to be evaluated too, because the pre-RC forms during G1. So if pre-RC assembly counts as part of initiation, then not all of the entire replication process takes place during S phase. Ow my head.

A specific note: depending on where GO puts the beginning of initiation, the text def of GO:0071163 may have to be adjusted.

have fun,
m

Reported by: mah11

Original Ticket: [geneontology/ontology-requests/9708](https://sourceforge.net/p/geneontology/ontology-requests/9708)

**Comment by ValWood** [comment]
Hi Midori,

I'm sitting with Paola now. What do we need to do for this one ?

VAl

**Comment by mah11** [comment]
Determine when initiation begins and when it ends (from the comments it looks like people were close to nailing down the beginning), and put that information into the definition(s).

Check whether the changes have any knock-on effects on other definitions - the original summary mentioned GO:0071163 (I would have to look more closely to remember why).

**Comment by paolaroncaglia** [comment]
Hi @ukemi,
This ticket is about an ontology mini-project to define start and end of DNA replication initiation. It requires some reading and/or specialistic knowledge of the field. Perhaps this can be taken on board by someone else in the future. I’ll assign it to you though, rather than leave it unassigned, so it doesn’t get lost. Thanks!

**Comment by ukemi** [comment]
There is a nice new review on this. PMID:28209641. I will work on this ticket as part of the GHathon.
