### ISSUE TITLE
what does "signal transducer activity" mean?

### ISSUE THREAD

**Issue by gocentral** [geneontology/go-ontology#9993]
I noticed that 
phopholipase C is mapped to "signal transducer activity" IEA using SPKW

I reilised I'm not eexactly sure what the is term means:

it is defined
Molecular Function
Definition 	Conveys a signal across a cell to trigger a change in cell function or state. A signal is a physical entity or change in state that is used to transfer information in order to trigger a response.

Does this mean "across a cell" or "across  a membrane" ?

The children all look like receptors so it seems to be across a cell membrane.
However, GO:0004709	MAP kinase kinase kinase activity has a parentage to "signal transducer activity"

but not MAP kinase, or MAP kinase kinase?

Reported by: ValWood

Original Ticket: [geneontology/ontology-requests/9789](https://sourceforge.net/p/geneontology/ontology-requests/9789)

**Comment by dosumis** [comment]
Made equivalentTo: molecular_function that 'part of' some 'signal transduction'

Now has MAPK activity etc.

Parent class 'molecular transducer activity' looks vague and hard to maintain, should probably obsolete.  Will add ticket on this to MF refactoring tracker.

**Comment by dosumis** [comment]
Note - after further consideration I have removed the 'molecular transducer' parent class.

Ticket on this class is here:
geneontology/molecular_function_refactoring#/7
